string DLG_TEXT[34] = {
"Any orders, cap'n?",
"Nothing for now.",
"Are we glad to see you, cap'n! We thought we were all going to die here. But at least someone made it out, I see.",
"Are we glad to see you, cap'n! We were all stuck here waiting to die. Poor old Nobby snuffed it only this morning.",
"Yes, a couple of the lads escaped, got caught and ended up in the same prison as me. We escaped together. Anyway. ",
"If I'm getting off this island then I'm going to need to steal a ship, which means I need a crew.",
"You didn't think I was going to abandon you in this hell-hole, did you?",
"Now what, cap'n?",
"You lot go to the port and find something to steal so we can get out of here.",
"And what will you be doing?",
"I'm going to the tavern. No, not to get drunk! There's supposed to be a ship with a payroll leaving some time and I want to know more about it.",
"We found a ship. It's not much but it should hold us all.",
"Well done, lads! A small ship is good, we don't want to attract attention on the way out. We can find something better in #sSantiago#. What did you do with the crew?",
"We tied them up in the hold. We can release them when we're away and clear.",
"We slit their throats. We'll dump them overboard when we're out at sea - don't want the bodies getting washed up and found too soon, do we?",
"Excellent, just what I'd have done.",
"What now, cap'n?",
"You lot follow him. Make sure he doesn't reach the tavern, or at least that he doesn't get back.",
"Why?",
"Because if he reports back that the tavern is only handing out one free drink to each man, it won't have the effect we want, which is the entire crew of this ship charging off to get drunk for free.",
"There's a mob coming through the gate from the town, heading this way.",
"Probably the ship's crew. They'll be in a bad mood due to finding there was only one free drink each, and they won't be happy to see us either. We'd best get to sea now!",
"What now, cap'n?",
"Get someone up there as a lookout. The moment the 'Siroco' comes into sight, we need to get to sea - she won't take long to get into port!",
"'Siroco' in sight, cap'n!",
"Right, lads - back to the ship, quickly!",
"Do you want help, cap'n?",
"No, this is between him and me. If he wins fair and square, the ship's his. But if anyone else tries to interfere, kill them!",
"You did it! You kidnapped the governor's ",
"Yes. Now take ",
" to the ship. Intact! The governor won't pay if ",
" is harmed in any way, which means if it happens, you'll be taking swimming lessons from sharks.",
"Well, who'd have thought it? You getting married? Congratulations from me and the lads, cap'n! The rum'll be flowing free tonight in your honour, that's for sure!",
"Thanks. Yes, by all means go and have a good time. I certainly will!",
}