string DLG_TEXT[37] = {
"What are you doing aboard my ship?",
"Sorry, sir. I'll return to my own ship.",
"I don't know who you are, but you have made a serious mistake boarding my ship.",
"I am ",
", reporting as ordered, sir.",
"Hardly. If you were really ",
", you would be in a proper uniform.",
"Surely you do not expect me to believe that ",
" is a woman!",
" Guards! Take this spy away and hang #spronoun#!",
"Can't I get changed?",
"I am ",
". Who are you?",
"Ah, of course. But why is the '",
"' not here?",
"We engaged several pirate ships when we arrived. We sank one, captured one, and one got away. My ship was severely damaged so I sent her to port for repair and took over the ship we captured. That is the ship you saw, sir.",
"Are you not aware that standing naval orders are that a captain must remain with his own ship? You should have stayed on the 'Joli', and only transferred to the other ship if yours was about to sink. This will have to be dealt with when you reach port.",
"Sorry, sir.",
"Now, on to business. These are ",
" and ",
". And this is ",
"Report on your activities on #sisland_Isla Mona#, if you please.",
"Yes, sir. We engaged a pirate ship but she ran away. Rather than pursue her, ",
"Yes, sir. After the encounter with the pirate ships, ",
"we proceeded to land on the island. The squad which I sent to the Taino village reported that they are peaceful and pose no threat. We continued to the fort, which as you may imagine was in some disrepair after decades of neglect.",
"Indeed, this was to be expected. Continue.",
"I had my men make a start on clearing the place up. We have made good progress. Then you arrived and we handed the fort over to your men. My crew are now embarked and we are ready to leave at your command, sir.",
"Very good. You may be wondering why we have taken over #sisland_Isla Mona#, a tiny island with no resources to speak of.\n",
"Word will soon reach our enemies that we are here. With no commercial interest on this island, they will conclude that we mean to use it as a base for an attack on #sSanto Domingo# or #sIsla Muelle#.\n",
"They will therefore move their forces to defend those towns. And so, for the expenditure of a small garrison, we cause the enemy to move much larger forces to the wrong place. Meanwhile our true attack will be elsewhere.",
"May we know where you plan to attack, sir? I am sure that the other captains are as eager as I am to join in that attack.",
"Your enthusiasm is to be commended. Unfortunately even I do not have details at the moment. The next phase is being planned at the highest level. I am sure that we will play our part in due time. Dismissed, gentlemen - you may return to your ships.",
"Yes, sir.",
"Your enthusiasm is to be commended. And that is where ",
" is involved.\nWhile the fleet proceeds to #sPort au Prince# to take on supplies and new troops, ",
" will return to #sRedmond#. In due time, our fleet will move to a beach near that town.\n",
" will send men to ambush the troops guarding the landward gate, then open the gate to allow our troops to invade without our ships having to attack the fort first.\nInstead, our force will attack the fort from land, where its defences are much weaker.\nInstead of being a thorn in France's side, #sRedmond# will become a spear aimed at #sisland_Cuba#.\nDismissed, gentlemen - you may return to your ships.",
}