string DLG_TEXT[146] = {
", what brings you to our tribe?",
"How may this humble Taíno help you?",
"Is your first time in our village? I not see you here before.",
"I'm ",
", captain and owner of the ship ",
". I've got a couple of questions for you.",
"My name is ",
", and I need some answers.",
"You can call me Captain ",
". I'd like some information.",
"Hello, Captain ",
". What brings you to our settlement?",
"Ah, Captain ",
". ",
"! You return! Has the sea been calm or angry?",
"Hello, ",
", how I help you?",
"What's the latest buzz?",
"What's going on around here lately?",
"What do the local drinkers chatter about these days?",
"I'm looking to catch up on the latest news, rumors, tall tales...whatever you've got.",
"I've been at sea - I'm interested in anything I don't know yet.",
"Dish me up some rumors; maybe there's some bit of news I can turn into gold.",
"I need some directions.",
"I'm not really familiar with the town. I could use some directions.",
"I need to be somewhere, and I'd appreciate some directions.",
"You look like a local to me. Can you tell me how to get to...",
"I could use some directions.",
"No time to chat. Just tell me how to find...",
"I'd like to ask you about someone you may know.",
"I need some information on one of the locals.",
"Can you tell me about one of the locals?",
"I'd like you to tell me what you know about a certain fellow...",
"I'm curious about one of the citizens. Can you fill me in?",
"I'll bet you know everyone who lives here, don't you? I've got some questions.",
"Tell me about the island.",
"Sorry. I thought you were someone else.",
"I'm just passing by. It'll be easier if you step aside.",
"What do you want to know, ",
"?",
"Can I help, captain?",
"What you want from me?",
"I'm sure this land is ripe with rumours. Tell me a couple of the juiciest.",
"Has anything interesting happened lately?",
"I just want to know what's going on in the neighborhood - murders, swindles...anything interesting.",
"How can I get to...",
"Can you help me to find my bearings here in town?",
"I still can't find...",
"Can you tell me about someone in particular?",
"I'd like to ask you about someone you may know.",
"I need some information on one of the locals.",
"Nothing! Just passing through.",
"Thanks. One more thing...",
"Nice chatting with you. See you later!",
"Anything else, Captain ",
"?",
"Tell me what you need, ",
".",
"I'm listening, ",
".",
"What's the latest buzz?",
"What's going on around here lately?",
"I'm looking to catch up on the latest news, rumors, tall tales...whatever you've got.",
"I need some directions.",
"I'm not really familiar with the town. I could use some directions.",
"I need to be somewhere, and I'd appreciate some directions.",
"I'd like to ask you about someone you may know.",
"I need some information on one of the locals.",
"Can you tell me about one of the locals?",
"Maybe next time. Farewell.",
"Who you need, ",
"?",
"You want know about someone?",
"Who you mean?",
"I mean your chief.",
"I'm interested in the owner of the tavern...",
"I'm wondering about the owner of the shipyard.",
"I am interested in the local merchant.",
"Let's get back to this later.",
"Chief is old and wise. He is friend to paleface visitors like you.",
"I see. I have another question for you.",
"Thanks. So long.",
"He is good friend to Taíno. Not charge too much for fire-water.",
"I no see place to build ships here. Perhaps you drink too much fire-water and think you are on mainland!",
"He's known for his honesty and for quality of his goods.",
"Where you heading, ",
"?",
"Not problem, captain. Where you want go today?",
"I'm happy to help, ",
". Where exactly do you want to go?",
"Where's the tavern?",
"Where can I find the shipyard?",
"I need to find someone who'll give me a fair price for my goods.",
"Tavern in light tower in port. Be careful not go through wrong door, chief of port also live in light tower.",
"Got it. Thanks.",
"Where's the shipyard?",
"Where can I sell the fine goods I've brought with me?",
"Nearest shipyard in #sSanto Domingo#.",
"I see. And how can I get to the tavern?",
"I need to find someone who'll give me a fair price for my goods.",
"Thanks for your help. That's all I need for now.",
"Going from the town sea gate, take the first street to the right. Walk down that street until it ends, then go downstairs. There you'll find the shop.",
"Where can I find the local shipyard?",
"How can I get to the tavern?",
"Thanks for your help. That's all I need for now.",
"Very well, ",
" - but not much of interest here.",
"Sure thing, I tell you what you want to know, captain.",
"I happy to talk! You listen,",
".",
"I'm interested in the history of this island...",
"Is there anything besides the town on this island?",
"Let's change the subject.",
"Taíno here long before palefaces. First palefaces come from Spain. Then Spain lose interest in little island so Spanish go away. These days, ships sometimes visit and a few palefaces live in port area.",
"Go on.",
"Yeah, that's what they all say. Let me ask you about something else.",
"I not know much about history. You talk to chief, he knows everything.",
"Got it. Let me ask you about something else.",
"This small island. What you see is what we got.",
"Doesn't sound that interesting. What else can you tell me?",
"Plenty of jungle where Taíno hunt. Guano mine probably still around somewhere, nobody go there now.",
"I see. Anything else?",
"Fort left by English still there.",
"Go on.",
"I see. Let's tackle a new subject, shall we?",
"Got it. Thanks.",
"Where's the shipyard?",
"Where can I sell the fine goods I've brought with me?",
" We are a small tribe. And there are visitors like you.",
"It is said that our people once lived in the land of the setting sun, and that we fled here to escape the darkness.",
"The fastest man can not outrun the wolf. But then, he only needs to outrun the slower man.",
"Nothing interesting happens lately. Life goes on smoothly. I wonder how long that'll last!",

};
