string DLG_TEXT[94] = {
"Good day, ",
"Hello, ",
"Well, well. ",
". Doing business with the governor of #sPort au Prince#, are you?",
"It's not what it seems. Anyway, who are you?",
"I am ",
", sent by ",
" to arrest you for the abduction of ",
". And now for treachery as well. Surrender at once!",
"I didn't take ",
", and can't go with you until I find out who did. Anyway, do you think you can take me by yourself?",
"No, but I'm not alone. Men - get #spronoun2#!",
"Bad move, ",
"Stop! I surrender!",
"Who are you? What's going on?",
"I do not really work for ",
". I work for the governor of #sSantiago#.",
"Nonsense! I know Governor ",
" very well. He would never send someone like you after me.",
" is no longer governor of Santiago. You're suspected of taking ",
", and as your relationship with ",
" is known, he is suspect as well. So he's been arrested and ",
" is now governor of #sSantiago#.",
"But I did not take ",
"No, I did. Then I made sure there were plenty of witnesses when I loudly said to my men that I was working for you.",
"But why? What does ",
" have against me?",
"You don't get it, do you? This isn't about you. You're just a useful tool.\nWhen ",
" learned of the arrival of ",
" in this region, he saw a chance to become governor of #sSantiago# as a step towards a position at the Spanish royal court.\nSo after I'd captured you, he was going to 'heroically rescue' the Electress as well as claim credit for your capture. Or death.",
"I don't like being used. More to the point, if you took the Electress, where is she?",
"My men are holding her in a cave near Peninsula de Zapata.",
" Her ship is there also.",
"Thank you. That is what I wanted to know.",
"What are you going to do now? Are you going to kill me?",
"No, I need you alive to testify to all this. You'll be taken aboard my ship. Make any attempt to escape and parts of you will be thrown overboard to feed the sharks.",
"Ah, captain ",
". I wondered who would introduce themselves by throwing a bottle in here. Fortunately I saw the bottle coming in and was quick enough to hold my breath. Your presence means the fumes have presumably dispersed.",
"Whoever you are, surrender! There is nowhere for you to run. We have your ship.",
"I am ",
". And I have ",
". It is you who will surrender, or I shall kill her.",
"I can't do that. Everyone thinks I took her, so I'm in big trouble until I take her to #sHavana#. If you won't surrender then I'll have to try it the hard way. Or perhaps we can make a deal so that both of us get what we want. What ransom do you demand for her release?",
"This is not about ransom. It is barely even about you. My employer knows your association with former governor ",
". By implicating you in the kidnap, we discredited him, so he lost his position, leaving the post of governor of #sSantiago# open for my employer.",
"Very clever.",
"It gets better. My employer will in due time take the Electress back to #sHavana#, claiming to have rescued her. As the hero, his position as governor of #sSantiago# will be merely a step towards a position at the Spanish royal court.",
"Oh? Then you're in more trouble than I first thought. Once I'm dead or totally discredited, you and your gang become the only ones who can tell anyone the truth. Your boss won't want to leave you alive. He'll either kill you during the 'heroic rescue' or he'll send assassins after you. So here's the deal. You hand ",
" over to me. I walk out of here and leave you unharmed.",
"Assuming for a moment that I considered such a deal, what guarantee have I that once you have the hostage, you won't attack me anyway?",
"You seem to know about me, so you know my reputation. I keep my word. So you have my word that if the Electress is released to me unharmed, you won't be harmed either.",
"What would you intend to do to me and my men if I were to surrender the Electress to you?",
"Nothing. Or, if you prefer, I can take you aboard my ship. Then I can release you wherever you want.",
"Alright. I don't seem to have much choice. If you give me your word that you'll take me to #sTortuga#, I'll release the Electress to you.",
"You seem to know about me, so you know my reputation. If you kill the Electress, I'll kill you, slowly and painfully.",
"And if I were to release the Electress to you?",
"I could use a man like you. So join me as an officer. Once you've signed articles, I can't kill you without a good reason, otherwise my crew would know their own signatures on the articles were worthless and I'd have a mutiny within the day.",
"Sounds good. Whether I kill the Electress or release her to you, I'm out of a job. Taking a new job with you seems to be my best move.",
"A wise choice. One more thing - who is your employer? Bear in mind that he won't be pleased with you, so it's probably in your interests if I know who he is so I can deal with him.",
"Good point. His name is ",
"Thank you. Now, help me get the Electress out of here so I can revive her.",
"You kept your word, then.",
"Yes. I always do.",
"Nevertheless, it's a relief to be here. No hard feelings, I hope? You know how it is in our business. Perhaps we'll meet again - we might even be on the same side.",
"That is unlikely, though stranger things have happened. But for now, it's goodbye.",
"Hello, captain ",
"! It's good of you to join us.",
"Such talk! It sounds as though you mean to betray us. You're making the men nervous. We should continue this conversation outside.\n<To his gang> Men, stay here. If I'm not back in 10 minutes, kill the hostage.\n<To you> Well? Shall we go?",
"Very well, follow me.",
"I am ",
". As you probably guessed, that little show was for the benefit of ",
". If you value her life, you should leave now.",
"You do realise that your employer will probably pay you with a bullet to the head? Once I'm dead or totally discredited, you're the only person who can tell anyone what really happened, and your employer won't want to risk that. So here's the deal. You hand ",
" over to me. I'll take her and leave, and you won't be harmed.",
"Even if I were to accept such an offer, my men would not. They'll want something to show for all their efforts.",
"Alright. How much is your employer claiming to pay you for all this? I'll match that amount, provided you tell me his name.",
"We're to be paid 100000 in gold. Can you match that?",
"Yes, I have that much.",
"One more thing. What guarantee have I that, if I release the hostage to you, you won't then attack us?",
"You know about me so you know my reputation. I keep my word. When I have the Electress, you have my word that I'll leave. Or, if you prefer, I can take you to the port of your choice.",
"You know about me so you know my reputation. If you kill the Electress, I'll kill you, slowly and painfully. But if you release her, I can offer you a job - I could use a man like you.",
"Very well, we have a deal. First give me the money and I'll tell you the name of my employer. Then I'll return to the cave and bring the hostage out. After that, you'll take me to #stortuga#.",
"Very well, we have a deal. First give me the money and I'll tell you the name of my employer. Then I'll return to the cave and bring the hostage out. After that, I'll join you as an officer.",
"Here is the money. Now, about your employer?",
"His name is ",
". Now, wait here while I bring the hostage out.",
"I'll wait. Don't make me come in to get her.",
"That is far too much! First I'll kill you here, then I'll go in and get the Electress myself.",
"You should not have tried to fight. Prepare to die!",
"One of us is about to die, and it's not me!",
"Well, captain ",
", here is the Electress. Will you keep your side of the bargain?",
"Yes. Follow me to my ship and I shall take you to #sTortuga#.",
"Yes. As of now you are a member of my crew, with the same rights and obligations as any other.",
}