string DLG_TEXT[79] = {
"I'm told you've gone to great lengths to request an audience. My name is ",
"I am ",
"Who are you and what is your business here?",
"Is it much further to the ship?",
"Not much further, no.",
". I have been sent by #sadmiral# to evacuate you.",
"Thank heavens! The French are already attacking. Presumably your ship is anchored somewhere other than in port?",
"Yes, I am moored at ",
"Excellent! Allow me to inform my wife, then we shall join you.",
"Incidentally, I was told that there would be a reward for this.",
"Yes, of course. If you can convey my wife and myself to safety, you shall receive 20000 gold coins.",
"A reasonable fare. Very well, get your wife, but don't be too long - I don't intend to wait for the French army to arrive.",
"Allow me to introduce my wife, #swife#. Now, if you please, let us be on our way.",
"My sentiments exactly - let's get out of here while we can! Follow me, please, all of you. Keep together, there may be bandits between here and my ship.",
"I am impressed, ",
"! You have done what the Royal Navy could not - you have defeated the '#swarship#'. This calls for a change of plan.",
"What sort of change? You still owe me 20000 gold, regardless of where you want me to take you.",
"The English flag still flies over the fort, which means my troops are still fighting. And you seem to be a #sperson# of action.\nSo here is my proposal. Join the battle and help end this invasion once and for all. You will receive 200000 gold, and possibly other rewards besides, for you will have been instrumental in saving #sRedmond#.",
"Well, I don't like to leave a job half done, and your offer is attractive. Very well, you're on.",
"Excellent! When the battle is over, my wife and I shall return home. When you join me there, you will receive your reward.",
"Then I look forward to seeing you back in the residence. And now I must prepare for another battle.",
"Ah, ",
", you have returned. But why are these soldiers with you?",
"I suspect the fort commander was not sure why I was there, or whether I was acting on your orders.",
"I see. Soldiers, you are dismissed - return to the fort.",
"And now there's the matter of my payment, Excellency.",
"Of course - here are the 200000 gold coins I promised. You have certainly earned them!",
"There was also a reward for dealing with #svillain#, if you recall?",
" I killed #spronoun2# in a duel on board the '#swarship#'.",
"Indeed? Well then, an additional 10000 coins would be a suitable bounty for that traitor.",
"Thank you, Excellency. This has certainly been a most profitable day.",
"Now we must discuss the '#swarship#'. Obviously she can not remain under the command of a private captain. If you turn her over to the Royal Navy, you will be paid another 100000 gold coins.",
"I could get more than that for the '#swarship#' by selling her in your shipyard. Or someone else's shipyard. Better yet, after the effort I took to capture the '#swarship#', I think I'll keep her.",
"You realise I could simply order my men to commandeer the '#swarship#', and if necessary, arrest you?",
"What? Oh - ha ha! You almost had me worried there. Of course, you are only joking.",
"Not at all...",
"Not at all serious, I'm sure you were about to say. And in the same spirit of joking, not at all serious threats, remember that your navy failed to take the '#swarship#', whereas my crew succeeded. And then consider where the guns of the '#swarship#' are pointed at the moment.",
"You wouldn't dare!",
"Of course not, any more than you would really try to take my ship by force. All these threats are just jokes, and in poor taste, so enough of this silliness, I'm sure you'll agree.",
"Then perhaps I can interest you in a Letter of Marque? Consider - you'll be free to sail as you wish, and when you attack French targets, you'll be serving yourself and England at the same time. You'll get all the plunder you would anyway, and additional rewards from England besides.",
"I already have a Letter of Marque from Spain.",
"That sounds like my kind of deal. I accept.",
"No, I don't wish to be tied to England that way.",
"What of it? England and Spain are allied against France. Accepting a Letter of Marque from England merely means you will be rewarded by both England and Spain for attacking the same target. You have nothing to lose and plenty to gain for doing what you'll be doing anyway.",
"Excellent! A wise decision, captain. If you continue to fight well for England, who knows what glory you may earn? We may even name a warship after you.",
"As you wish. You can always buy a Letter of Marque from me, or any other English governor, if you change your mind.",
"A good point well made, Excellency. Besides, having Letters of Marque from both England and Spain means I am not so closely tied to either nation. I accept your offer.",
"Even so, I can not accept a Letter of Marque from England.",
"And now I must take my leave. Goodbye, Excellency.",
"Oh well, perhaps it is not so bad after all. You are a privateer in the service of England, so you will of course only use the '#swarship#' against England's enemies.\nThat being so, I wish you good hunting, captain. Perhaps if you continue to distinguish yourself, we may even name a warship after you.",
"I shall do anything you ask! Just do not harm my ",
"After all #spronoun# has done? After #spronoun# has threatened my wife? You ask too much!",
"It is the only way we can end this. Your word, or I can not help you.",
"Very well, then. #svillain#, if you kill ",
" then I give my word that you can leave safely.",
"Thank goodness! I promised there would be a reward for dealing with #svillain#. Here are 10000 gold coins - a fitting bounty for such a traitor!",
"You also owe me rather more for saving your town. I believe you mentioned the sum of ",
"There's also the little matter of defeating the French invasion. Presumably that is worth something as well?",
"Indeed so. The sum of 200000 gold coins should be suitable reward for such heroism.",
"You were going to let #svillain# kill me, then steal my possessions! And what were you going to do to my wife?",
"Nothing. It provoked #svillain# into fighting me, didn't it? And you're still alive, which you wouldn't be if I'd dropped my sword and let #spronoun2# do as #spronoun# pleased.",
"So you say. Why should I trust you?",
"Because I'm not trying to kill you and put the blame on #svillain#. Your wife is safe, your possessions are safe and you're safe.",
"I suppose that is true.",
"And, as I recall, you mentioned a reward for #svillain#, dead or alive. Well, #spronoun# is dead.",
"That is also true. Very well, the reward is 10000 gold coins. Here they are.",
"And perhaps, as a further honour, you would accept a Letter of Marque? Consider - you'll be free to sail as you wish, and when you attack French targets, you'll be serving yourself and England at the same time. You'll get all the plunder you would anyway, and additional rewards from England besides.",
"Who are you? What happened? Are the French invading the town?",
". You'll be pleased to know that the French invasion has been defeated.",
"Thank heavens! I shall write to #sadmiral# at once to congratulate him for the work of his fleet.",
"Don't bother. It wasn't his fleet who defeated the French. If you want to thank the person who defeated the French, here I am.",
"What are you on about, #sperson#? You expect me to believe that a ",
"pirate",
"privateer",
" defeated the '#swarship#', the most powerful ship of the French fleet?",
"Believe it. The Royal Navy had nothing to do with it. And I expect to be well paid for today's action.",
"Thank you, soldier. Dismissed. Well, ",
", that would seem to confirm what you say. That puts me, and this whole town, firmly in your debt. Perhaps the sum of 200000 gold crowns would be sufficient payment?",
"A warship? If so, I hope it is a big one. ",
}