string DLG_TEXT[61] = {
"Yes? Who are you and why are you here?",
"I am ",
", and I have some information which may be of interest to you. ",
"?? You are known as enemy of the Crown! GUARDS!! ARREST THIS SPY!!",
"? I had a report about you... yes, here it is. By rights I should hang you as a #sbackground#. But ",
"after an incident at #sRedmond#, you received a full pardon",
"you have paid for amnesty from the crown",
", and apparently have not disgraced yourself since. So, what sort of information do you have?",
"How much would you be willing to pay to learn the whereabouts of the '#swarship#'?",
"Interesting that you mention the '#swarship#'. Everyone has heard of the 'Soleil Royal', one of the most powerful ships of the French navy, and if you'd mentioned her then I'd have had you thrown out on your ear because I happen to know she's in the Mediterranean.\nBut not so many people have heard of her less famous sister, the '#swarship#'. How does 5000 gold coins sound?",
"Interesting enough. Hand it over and I'll tell you where I saw the '#swarship#'.",
"Do you take me for a fool? For all I know, you could pick the name of a random port, take the money and never be seen here again. No, you'll tell me where you saw the '#swarship#', and I'll send ships to confirm it. If you're telling the truth, be back here in, say, two weeks, and you'll get your money - you have my word on that.",
"Now it is you who take me for a fool. Once I tell you where I saw the '#swarship#', what's to prevent you from having me thrown out and not paying a single coin?",
"My word is my bond - if I say you'll be paid then paid you shall be. Your problem is that by the time you've found someone who'll tell you that, your information will be out of date and worthless.\nI understand the usual method in these situations is to pay half the money in advance and half upon satisfaction. So I'll offer you a choice.\nYou can have 3500 gold right now, and if you're lying then you'd better never show your face in an English port ever again. You can have 5000, half now and half in two weeks when I have verified your report. Or you can have 6000 in two weeks. Which do you prefer?",
"Honour aside, I don't know what I'll be doing in two weeks' time, so if you don't mind, I'll take the 3500 right now.",
"Half now, half later satisfies both our honours and both our suspicions. It's a fair deal.",
"I can afford to wait, and you do seem trustworthy. Very well, I'll return later for the full 6000.",
"As you wish. Here's your money. Now, where is the '#swarship#'?",
"A fair deal indeed. Here is the first payment. In return, where is the '#swarship#'?",
"Aren't you forgetting something? Where is the '#swarship#'?",
"Last time I saw the '#swarship#', she was moored in #sMarigot#.",
"#sMarigot#? If she's there, it's serious for all of us. Thank you, ",
", you have certainly earned your pay - if the '#swarship#' truly is in #sMarigot#, that is. And now I have to organise a reconnaissance to confirm this. Goodbye.",
"Goodbye, Admiral.",
" I'll be back to collect what you owe me.",
"Are you still here? Leave, please - I am about to be very busy acting on your information.",
"Sorry, Admiral - I was just on my way out.",
"Ah, ",
", you're back. As promised, here is the #samount# gold which I owe you for your information.",
"Thank you, Admiral. Did you find the '#swarship#', then?",
"Yes, though it did not go well for us. I was able to send what I hoped would be a suitable force to take her on. Our squadron succeeded in destroying two of her escorts and crippling a third, but were unable to do serious harm to the '#swarship#' herself.\nIn return, our force was all but destroyed; only one badly damaged frigate made it back to base.",
"I'm sorry to hear that. ",
"If I find anything else of use, I'll bring the information to you - for a suitable fee, of course. Well, goodbye, Admiral.",
"Meanwhile, I've found out what the '#swarship#' will be doing next.",
"Oh, it's you again, ",
". What business do you have this time?",
"I've found out what the '#swarship#' will be doing next.",
"And presumably you will want payment for that information.",
"Yes, and as I believe I can now trust you, I'll tell you what I know, then you can decide what it's worth. Better yet, I'll show you. Look what I found in the naval building in #sPointe a Pitre#.",
"Let's see...\nGood heavens! She's going to attack #sRedmond#, and we have nothing that can stop her! The force I sent to investigate your report was all but destroyed and only succeeded in sinking the escorts of the '#swarship#'.\nAlright - you're evidently a type who takes risks for money.",
"True enough, depending on whether the money is good enough to balance the risk. What are you proposing?",
"Sail to #sRedmond# with all possible speed. Show the governor the document you just showed me. He'll undoubtedly want to evacuate the town. Assist in any way you can. If he doesn't reward you suitably, return here and I will.",
" Meantime, here's 10000 gold for bringing this to my attention.",
"Working for you is certainly profitable. I shall indeed sail to #sRedmond#. Goodbye, Admiral.",
"I've 'acquired' a document which I believe will interest you, from the naval building in #sPointe a Pitre#.",
"What sort of document?",
"Orders for an attack on #sRedmond#. What is it worth to you?",
"I'd need to see the document first, of course. But I am a man of my word, and I give you my word that you will be paid appropriately.",
"Alright, I'll take a chance. Look at this.",
"No deal. For the trouble it took me to get this, I'll want money up front. 5000 gold coins or I leave right now.",
"Let's see...\nGood heavens! The '#swarship#' will be leading the attack, and we have nothing available that can stop her!\nAlright - you're evidently a type who takes risks for money.",
"Very well, here's your 5000. Let me see what you have.",
"Thanks. Alright, here's the document.",
"Let's see...\nGood heavens! She's going to attack #sRedmond#, and we have nothing that can stop her! The force I sent to investigate your report was all but destroyed and only succeeded in sinking the escorts of the '#swarship#'.\nI shall need to consider what to do about this.",
"Let's see...\nGood heavens! The '#swarship#' will be leading the attack, and we have nothing available that can stop her!\nI shall need to consider what to do about this.",
"Thank you, Admiral. I wish you luck with the defence of #sRedmond#. Goodbye.",
"I'm afraid your information is out of date, captain.",
"You are too late, captain. The French have already put those plans into effect.",  
" The '#swarship#' has attacked #sRedmond#. The town has fallen to the French. Goodbye, captain ",
" The '#swarship#' then continued on with her mission to attack #sRedmond#. The town has fallen to the French.",
"That is unfortunate, Admiral. I'll leave you to consider what you will do next. Goodbye.",
};