string DLG_TEXT[62] = {
"I'm told you've gone to great lengths to request an audience. My name is ",
". Now, if you please, tell me the purpose of your visit, ",
"My name is ",
"So, why do you distract me from the very important affairs of state?",
"No! I recognise you. You are the notorious pirate ",
"! Guards - arrest this ",
"I should have worn a better disguise. But you'll soon need to hire some more guards!",
"I'd like to offer my services to France.",
"What is your business here, soldier?",
"Your Excellency, I am here on behalf of ",
", the governor of #sFalaise de Fleur#. He wishes me to take custody of ",
". I am then instructed to take her back to France.",
" is mistaken! ",
"It is true that I sent a task force to intercept the galleon carrying ",
". But unfortunately the task force was defeated by the galleon's escort.",
" arrived safely in #sSanto Domingo# but was abducted there. I do not know who was responsible.",
"Perhaps another French governor ordered the abduction?",
"Certainly not. Nothing happens on #sisland_Hispaniola# without my knowing, and nothing involving France on #sisland_Hispaniola# happens without my authority.",
"I apologise, Excellency. I merely want to be certain of all the facts before I return to ",
". And I also apologise for taking up your time. Goodbye, Excellency.",
"Get out before I call more guards!",
"Don't worry, I'm leaving!",
"Is there anything else you want here?",
"No, I'll be leaving now. Goodbye.",
"You wish to serve France? Very well. I have a simple task for you. If you carry it out, you will be paid, and perhaps receive more interesting work in the future.",
"This sounds like the beginning of a promising career. Please tell me more.",
"Allow me to introduce ",
". Your job is to take him to #sIsla Muelle# on #sisland_Isla Muelle#. He will give you more details.",
"I beg your pardon, but what use is this... man... to France?",
"Don't let his appearance deceive you, ",
". It is intended to deceive the Spanish in general and the officials of #sIsla Muelle# in particular. ",
" is one of our most capable spies and the appearance which caused you such amusement is merely a disguise.",
"I see. Nobody would suspect such a person of being a spy - which, of course, is a big advantage for a spy.",
"Precisely. When you have delivered ",
" to #sIsla Muelle#, return here for your payment.",
"And possibly for further work. Until my return, then, goodbye, Excellency.",
"I recognise you. You are the notorious pirate ",
"Welcome back, ",
". Is ",
" safely in #sIsla Muelle#?",
"Yes, Excellency. The albatross is in his nest. And the real ",
" is safely in my hold. Nobody other than you, I and ",
" know of the switch.",
"The albatross, you say? Good. Here is your reward.",
"Thank you, Excellency. Have you any other work for me?",
"Yes. You were accused of the kidnap of #senvoy#, the envoy from the Holy Roman Empire. We'd like to take custody of her.",
"But I did not kidnap her!",
"I know that. Our agent in #sSanto Domingo# observed the kidnappers loudly claiming to work for you, but they did not board your ship.",
"Then where did they go?",
"According to the agent's report, ",
"some of them boarded the ship on which #senvoy# had been travelling, presumably taking her at the same time. The rest boarded their own ship. Both ships were then seen to set course for #sisland_Cuba#.",
"they were seen to board a different ship which appeared to set course for #sisland_Cuba#.",
"Yes. The Spanish believe that the notorious pirate ",
" abducted #senvoy#, the envoy from the Holy Roman Empire, from #sSanto Domingo#. But although #spronoun# is guilty of many crimes, we do not believe that #spronoun# committed this one.",
"Why not?",
"Our agent in #sSanto Domingo# observed the kidnappers loudly claiming to work for ",
", but they did not board #spronoun3# ship. Instead, ",
"Very interesting, Excellency, but how am I to be of service in this matter?",
"The kidnappers presumably do not work for the Spanish government, or at least, not openly. So they will not be in #sHavana# or #sSantiago#.\nBut #sisland_Cuba# has many beaches and inlets. You will search them and find out where the kidnappers are hiding. Then you will report back here. We can then send a force to eliminate the kidnappers and retrieve #senvoy#.",
"May I ask why you intend to rescue the Electress? Surely her kidnap will benefit France?",
"Having her as a hostage will benefit France even more. She will be a useful bargaining counter in any future negotiation with the Holy Roman Empire.",
"I understand. Then I shall leave for #sisland_Cuba# as soon as possible.",
}