string DLG_TEXT[23] = {
"Hello, ",
". Look around, what do you want to see?",
"I've heard that you're the best tailor in town, so you should be able to help me. I need a disguise.",
"What sort of disguise?",
"Something that doesn't look so much like a pirate. Perhaps throw in a shave and a haircut as well.",
"Something to make me look a proper lady. Yes, I know. <spit> Sometimes it has to be done.",
"You're in luck. Someone brought in a nice ",
"outfit",
"dress",
" to sell - didn't need it because ",
" did want to continue looking like a pirate. Yours for just 2000 gold coins.",
"OK, but it had better be good for that sort of money.",
"Too much! I'll offer 1000.",
"Sorry, I don't have that much on me.",
"1500 or you can look somewhere else.",
"1500 is more reasonable. We have a deal.",
"OK, I'll look somewhere else.",
"A wise choice, ",
". Do you want to try it on now, or just bag it and take it for later?",
"I'd better try it now.",
"Bag it, please. As long as I'm in #sTortuga# I don't need a disguise.",
"Very well. Hand over the money and the outfit is yours.",
"Here's your money. A pleasure doing business with you, ",
}