string DLG_TEXT[14] = {
"This is the best meal you'll get for the rest of your life.",
"Makes me almost look forward to the hanging.",
"Get this down your throat while you can still get anything down it.",
"Any chance of a bit of bread?",
"Someone must really like you, to keep you here so you can eat my lovely stew.",
"Cruel and unusual punishment, I call it.",
"Here's your meal, pirate!",
"Call that food? I wouldn't feed it to the ship's rats!",
"What are you doing out of your cell? Guards!",
"Shut it, unless you want another headache!",
"Oh no, not you again!",
"Yes, me again.",
"Well, don't bother walloping me again. I no longer carry a key. Enjoy your stew!",
"Oh no, not again...",
}