string DLG_TEXT[41] = {
".",
".",
"You're a friend of that nice young #sperson# who moved here a few weeks ago, aren't you?",
"Yes. Why do you ask?",
"I have terrible news for you - #spronoun# has been kidnapped! One day #spronoun# was walking around and a gang of men grabbed #spronoun2# and made off. As you'd expect, the soldiers did nothing - makes you wonder why anyone pays taxes!",
"Any idea where they took #spronoun2#?",
"No, there's only one way out of this area and I couldn't see where they went next.",
"I see. Well, thanks for letting me know anyway. Goodbye.",
"Ah, another visitor to the #smerchant# house. Do you know its history?",
"No, is it interesting?",
"They say when Spain owned #sisland_Redmond#, that house belonged to the Inquisition. Not surprising, with its view over the wall.",
"Good way to spy on the governor, then. What else did they get up to?",
"Well, the story is that the Inquisition had their prison somewhere down that dungeon next door. Tortured people, they did. And to this day the dungeon is haunted by the ghosts of their victims.",
"Ghosts? There are no such things as ghosts!",
"That's probably what the gang who took that young #sperson# down there thought. But nobody who goes down there comes out again. Don't say I didn't warn you!",
"True enough. If I do go down there and run into your ghosts, I won't be able to say anything much. Thanks for the warning, though!",
"Welcome, capitan! What do you want?",
"I'm looking for one of my officers. Has a #sperson#, young and probably looking like a noble, been here recently?",
"Yes. A group of sailors were also in here for #spronoun#. At first #spronoun2# seemed willing to go with them, then there was an argument but #spronoun2# went with them anyway. One of them may have had a hidden gun.",
"They can't have been my crew. If they'd brought my officer back to my ship, I'd have known about it. Thanks anyway.",
"Perhaps not. But the story also goes that the Inquisition hid all the gold they took from their victims down there. So occasionally someone goes looking for it. And they never come back out.",
"Gold? Whatever is down there isn't ghosts, but if there's gold, it's going to be mine. Thanks for the warning about the 'ghosts', though!",
". Hallo, ",
"May I help you, ",
"Hallo. Perhaps you can help me. I'm looking for #svillain#, who I am told was sailing here in the East Indiaman '#sship#'. Have you seen #spronoun2#?",
"No, I don't remember anyone by that name.",
"Have you seen the '#sship#', then? She's supposed to have sailed here from #sRedmond#.",
"No, almost all the English ships which have arrived here recently came from #sCharlestown#. Ships from the west are mostly Spanish.\nStrange, Holland being friends with both England and Spain - usually we're at war with one or the other.",
"Politics don't interest me. But I really must find #svillain# - #spronoun# has been trying to help the French and there's a reward for bringing #spronoun2# in.",
"If #spronoun# is a friend of France then perhaps you are looking in the wrong port. #sMarigot# is on the other side of this island and belongs to France.\nBut don't try walking there because we're besieging #sMarigot# and the French are besieging #sPhilipsburg#. If the soldiers don't kill you then a cannonball will.\nAnd the French fort may have seen you as you approached the island, so sailing to #sMarigot# may be dangerous. But some say there's a tunnel between #sPhilipsburg# and #sMarigot#. Perhaps you can find it.",
"Thanks, that's useful to know. Goodbye.",
". Bonjour, ",
"Hallo.",
"'Hallo'? You sound English!",
"By birth, yes. By choice, a friend of France. Like #svillain# - have you seen #spronoun2#?",
"Oh, that's different then. Any friend of France is a friend to me. Yes, #svillain# was here a few days ago, then left for #sPointe a Pitre# on the island of #sisland_Guadeloupe#.",
"Thanks! Perhaps I can catch up with #spronoun2# there.",
"I'll tell you something else, as you are a friend of France. Do you see that ship out there?",
"The big one with a lot of guns?",
"That's the one. That's the '#sship#'. She's just arrived. The English and their allies have nothing like her. Now the '#sship#' is here, we'll clean them out of the Caribbean!",
"That is welcome news indeed. Thank you again, and goodbye. <Thinks: I wonder how much the English would pay to know that. Maybe try my luck at #sisland_Antigua#.>",
}