string DLG_TEXT[146] = {
", ¿qué te trae a nuestra tribu?",
"¿Cómo puede ayudarte este humilde taíno?",
"¿Es tu primera visita a nuestra aldea? No te he visto antes por aquí.",
"Soy ",
", capitán en propiedad del barco ",
". Tengo un par depreguntas para ti.",
"Me llamo ",
" y necesito algunas respuestas.",
"Puedes llamarme capitán ",
". Quiero un poco de información.",
"Hola, capitán ",
". ¿Qué te trae a nuestro asentamiento?",
"Ah, capitán ",
". ",
", has vuelto. ¿El mar ha estado tranquilo o furioso?",
"Hola, ",
", ¿cómo te ayudo?",
"¿Cuáles son los últimos rumores?",
"¿Qué ha estado pasando últimamente?",
"¿De qué hablan los borrachos locales?",
"Quiero ponerme al día de las últimas noticias, rumores, cuentos de viejas... Cualquier cosa que tengas.",
"He estado un tiempo en alta mar. Me interesa cualquier cosa que me haya perdido.",
"Dame los últimos rumores; quizás haya alguna noticia que pueda convertir en oro.",
"Necesito indicaciones.",
"No conozco este sitio. Me vendrían bien unas indicaciones.",
"Tengo que llegar a un sitio y me gustaría que me indicaras el camino.",
"Pareces de por aquí. ¿Puedes decirme cómo llegar a...",
"Me vendrían bien unas indicaciones.",
"No tengo tiempo para charlar. Solo dime cómo encontrar...",
"Me gustaría preguntarte sobre alguien a quien quizás conozcas.",
"Necesito información sobre uno de tus vecinos.",
"¿Puedes hablarme de uno de los lugareños?",
"Quiero que me cuentes lo que sepas sobre cierta persona...",
"Tengo curiosidad sobre uno de los vecinos. ¿Puedes informarme?",
"Apuesto a que conoces a todo el mundo por aquí, ¿eh? Tengo algunas preguntas.",
"Háblame sobre la isla.",
"Lo siento. Te confundí con otra persona.",
"Solo estoy de paso. Será mejor que te partes.",
"¿Qué quieres saber, ",
"?",
"¿Puedo ayudarte, capitán?",
"¿Qué quieres de mí?",
"Seguro que estás tierras están llenas de rumores. Cuéntame los más jugosos.",
"¿Ha ocurrido algo interesante últimamente?",
"Solo quiero saber lo que está pasando en el vecindario: asesinatos, estafas..., Cualquier cosa interesante.",
"¿Cómo puedo llegar a...",
"¿Puedes ayudarme a orientarme?",
"Todavía no puedo encontrar...",
"¿Puedes hablarme de alguien en concreto?",
"Me gustaría preguntarte sobre alguien a quien quizás conozcas.",
"Necesito información sobre uno de tus vecinos.",
"¡Nada! Solo estoy de paso.",
"Gracias. Una cosa más...",
"Un placer hablar contigo. ¡Hasta luego!",
"¿Algo más, capitán ",
"?",
"Dime qué necesitas, ",
".",
"Te escucho, ",
".",
"¿Cuáles son los últimos rumores?",
"¿Qué ha estado pasando últimamente?",
"Quiero ponerme al día de las últimas noticias, rumores, cuentos de viejas... Cualquier cosa que tengas.",
"Necesito indicaciones.",
"No conozco este lugar. Me vendrían bien unas indicaciones.",
"Tengo que ir a un sitio y me vendrían bien unas indicaciones.",
"¿Puedes hablarme de uno de los lugareños?",
"Quiero que me cuentes lo que sepas sobre cierta persona...",
"¿Puedes hablarme de uno de los lugareños?",
"Quizás la próxima vez. Adiós.",
"¿De quién se trata, ",
"?",
"¿Quieres saber de alguien?",
"¿A quién te refieres?",
"Me refiero a vuestro cacique.",
"Me interesa el dueño de la taberna...",
"Tengo curiosidad por el dueño del astillero.",
"Me interesa el mercader local.",
"Volvemos a este tema más tarde.",
"El cacique es viejo y sabio. Es amigo de los visitantes rostros pálidos como tú.",
"Ya veo. Tengo otra pregunta para ti.",
"Gracias. Hasta otra.",
"Buen amigo de los táinos. Vende agua de fuego barata.",
"No veo ningún lugar para construir barcas aquí. ¡Quizás has bebido demasiada agua de fuego y crees que estás en el continente!",
"Es conocido por su honestidad y la buena calidad de su productos.",
"¿Adónde te diriges, ",
"?",
"Sin problema, capitán. ¿Adónde quieres ir?",
"Será un placer ayudarte, ",
". ¿Adónde quieres ir exactamente?",
"¿Dónde está la taberna?",
"¿Dónde puedo encontrar el astillero?",
"Busco a alguien que me dé un precio justo por mis mercancías.",
"La taberna está en la torre de luz del puerto. Cuidado con no equivocarte de puerta, el jefe del puerto también vive en la torre de luz.",
"Lo tengo. Gracias.",
"¡Dónde está el astillero?",
"¿Dónde puedo vender los productos que he traído?",
"El estillero más cercano está en #sSanto Domingo#.",
"Ya veo. ¿Y cómo llego a la taberna?",
"Busco a alguien que me dé un precio justo por mis mercancías.",
"Gracias por tu ayuda. Eso es todo por ahora.",
"Desde la puerta de mar, toma la primera calle a la derecha. Síguela hasta el final y baja las escaleras. Allí está la tienda.",
"¿Dónde puedo encontrar el astillero?",
"¿Cómo llego a la taberna?",
"Gracias. Por tu ayuda. Eso es todo lo que necesito.",
"Muy bien, ",
"..., pero no hay nada interesante por aquí.",
"Claro, te cuento lo que quieras, capitán.",
"Yo estoy encnatado de hablar si tú escuchas,",
".",
"Me interesa la historia de la isla...",
"¿Hya algo más en esta isla aparte de la aldea?",
"Cambiemos de tema.",
"Los taínos vivían aquí mucho antes que los rostros pálidos. Los primeros rostros pálidos vinieron de España. Luego España perdió interés y lo sespañoles se fueron. Ahora, a veces vienen barcos y algunos rostros pálidos viven en la zona del puerto.",
"Sigue.",
"Sí, eso dicen todos. Déjame preguntarte otra cosa.",
"No sé mucho de historia. Habla con el cacique, él sabe todo.",
"Entendido. Déjame preguntarte otra co.",
"Es una isla pequeña. Lo que ves es lo que hay.",
"No suena muy interesante. ¿Qué más puedes decirme?",
"Hay mucha selva donde los taínos cazamos. Había una mina, pero ya nadie va allí.",
"Ya veo. ¿Algo más?",
"El fuerte que dejaron los inglese ssigue ahí.",
"Continúa.",
"Ya veo. Cambiemos de tema, ¿de acuerdo?",
"Entendido. Gracias.",
"¿Dónde está el astillero?",
"¿Dónde puedo vender mis mercancías?",
" Somos una tribu pequeña. Y hay algunos visintates, como tú.",
"Se dice que nuestro pueblo vivía en la tierra del sol poniente, pero que huimos aquí para escapar de la oscuridad.",
"El hombre más veloz no puede correr más rápido que el lobo. Pero al lobo le basta con correr más rápido que el hombre más lento.",
"No ha pasado nada interesante últimamente. La vida sigue su curso. ¡Me pregunto cuánto durará!",

};
