string DLG_TEXT[62] = {
"Me han dicho que has insistido mucho para pedir una audiencia. Mi nombre es ",
". Ahora, por favor, dime el propósito de tu visita., ",
"Me llamo ",
"Entonces, ¿por qué me distraes de mis importantes asuntos de estado?",
"¡No! Te reconozco. ¡Tus piraterías son bien conocidas, ",
"! ¡Guardias! ¡Arrestad a este demonio de ",
"Debería haber llevado un disfraz mejor. ¡Pero tú pronto tendrás que contratar a nuevos guardias!",
"Me gustaría ofrecer mis servicios a Francia.",
"¿Qué asuntos te traen aquí, soldado?",
"Excelencia, vengo de parte de ",
", el gobernador de #sFalaise de Fleur#. Quiere que me haga cargo de la custodia de la ",
". Mis órdenes son llevarla de vuelta a Francia.",
" se equivoca. ",
"Es cierto que envié una escuadra a interceptar el galeón en el que viajaba la ",
". Pero, desgraciadamente, esa escuadra fue derrotada por la escolta del galeón",
" llegó sana y salva a #sSanto Domingo#, pero fue secuestrada una vez allí. No sé quién fue responsable.",
"¿Algún otro gobernador francés podría haber ordenado su secuestro?",
"Seguro que no. Nada pasa en #sisland_Hispaniola# sin mi concimiento, y nada que tenga que ver con Francia pasa en #sisland_Hispaniola# sin mi autorización.",
"Mis disculpas, Excelencia. Solo quiero asegurarme de todos los hechos antes de volver a informar a ",
". Y me disculpo también por desperdiciar el tiempo de Su Excelencia. Adiós.",
"¡Vete antes de que llame a más guardias!",
"No hay problema. ¡Ya me voy!",
"¿Necesitas algo más?",
"No, me retiraré. Adiós.",
"¿Quieres servir a Francia? Muy bien. Tengo una tarea sencilla para ti. Si la llevas a cabo, te pagaré bien, y quizás recibas trabajos más interesantes en el futuro.",
"Parece el inicio de una prometedora carrera. Ruego a Su Excelencia que me diga más.",
"Permíteme presentarte a ",
". Tu trabajo es llevarlo a #sIsla Muelle#, en #sisland_Isla Muelle#. Él te dará más detalles.",
"Con el debido respeto, pero, ¿qué utilidad tiene este... hombre para Francia?",
"No te dejes engañar por su apariencia, ",
". Su aspecto tiene la intención de burlar a los españoles en general y a las autroridades de #sIsla Muelle# en particular. ",
" es uno de nuestros mejores espías y esa apariencia que tanto te divierte es un mero disfraz.",
"Ya veo. Nadie sospecharía que una persona así fuera un espía. Lo que, por supuesto, es una gran ventaja para un espía.",
"Precisamente. Cuando hayas llevado a ",
" a #sIsla Muelle#, vuelve aquí para recibir tu recompensa.",
"Y posiblemente, para nuevos trbaajos. En ese caso, adiós, Excelencia, hasta mi regreso.",
"Te reconozco. Tus piraterías son bien conocidas, ",
"Estás de vuelta, ",
". ¿",
" está sano y salvo en #sIsla Muelle#?",
"Sí, Excelencia. El albatros está en su nido. Y el verdadero ",
" está sano y salvo en mi bodega. Nadie más que Su Excelencia, yo y ",
" se ha enterado del cambio.",
"¿Albatros, dices? Bien. Aquí está tu recompensa.",
"Gracias, Excelencia. ¿Hay más trabajo para mí?",
"Sí. Se te ha acusado del secuestro de #senvoy#, la enviada del Sacro Imperio Romano. Nos gustaría hacernos cargo de su custodia.",
"¡Pero yo no la secuestré!",
"Eso ya lo sé. Nuestro agente en #sSanto Domingo# escuchó a los secuestradores proclamar a los cuatro vientos que trabajaban para ti, pero no subieron a bordo de tu barco.",
"¿Y adónde fueron?",
"Según el informe del agente, ",
"algunos embarcaron en el barco en el que había viajado #senvoy#, y suponemos que se la llevaron con ellos. El resto subieron a bordo de su propio barco. Ambos barcos fueron vistos dirigiéndose a #sisland_Cuba#.",
"fueron vistos embarcando en un barco diferente que zarpó, aparentemente, rumbo a #sisland_Cuba#.",
"Sí. Los españoles creen que ",
", célebre pirata, secuestró a la #senvoy#, la enviada del Sacro Imperio Romano, en #sSanto Domingo#. Pero, aunque Ardent es culpable de muchos crímenes, no creemos que #spronoun# haya cometido este.",
"¿Por qué no?",
"Nuestro agente en #sSanto Domingo# escuchó a los secuestradores proclamar a los cuatro vientos que trabajaban para ",
", pero no subieron a bordo de su barco, sino que ",
"Muy interesante, Excelencia, pero, ¿cómo puedo yo ser de utilidad en este asunto?",
"No creemos que los secuestradores trabajen para el gobierno epsañol, no abiertamente, al menos. Así que no estarán en #sHavana# ni en #sSantiago#\n Pero #sisland_Cuba# tiene muchas playas y calas apartadas. Registrarás la costa y averiguarás dónde se esconden los secuestradores. Cuando lo hayas hecho, volverás a informarme. Entonces, enviaremos una fuerza para eliminar a los secuestradores y recuperar a la #senvoy#.",
"¿Puedo preguntar por qué Su Excelencia quiere rescatar a la Electora? Sin duda, su secuestro beneficia a Francia, ¿no?",
"Tenerla como rehén beneficiará a Francia aún más. Será una baza importante en cualqier futura negociación con el Sacro imperio.",
"Entiendo. Ebtonces, zarparé rumbo a #sisland_Cuba# lo antes posible.",
}