string DLG_TEXT[41] = {
".",
".",
"Tú tienes amistad con ese encanto de #sperson# tan joven y amable que se mudó aquí hace ubas semanas, ¿verdad?",
"Sí. ¿Por qué lo preguntas?",
"Tengo muy malas noticias para ti: ¡ #spronoun2# han secuestrado! Un días, estaba #spronoun# paseando tranquilamente cuando una banda de hombres #spronoun2# agarraron y se #spronoun2# llevaron con ellos. Como te puedes imaginar, los soldados no hicieron nada. ¡No sé para qué pagamos impuestos!",
"¿Alguna idae de adónde se #spronoun2# llevaron?",
"No, solo hay una salida de esta zona, pero no pude ver adónde fueron después.",
"Ya veo. Gracias por hacérmelo saber, de todas formas. Adiós.",
"Ah, otro visitante que acude a la casa #smerchant#. ¿Conoces su historia?",
"No, ¿es interesante?",
"Dicen que cuando #sisland_Redmond# era española, esta casa pertenecía a la Inquisición. No me sorprende, ya que tiene una buena vista por encima de las murallas.",
"Una buena forma de espiar al gobernador. ¿Qué más hacían aquí?",
"Bueno, la leyenda dice que la Inquisición tenía su prisión secreta en algún punto de esa mazmorra a la que se entra por la puerta de al lado. Allí torturaban a la gente. Y desde entonces, los fantasmas de sus vícitmas vagan por esa mazmorra.",
"¿Fantasmas? ¡Los fantasmas no existen!",
"Seguramente, eso es lo que pensaron los matones que llevaron allí abajo a su joven víctima ¡Pobre #sperson#! Nadie que se adentra allí vuelve a salir. ¡No digas que no te he advertido!",
"Si me meto allí abajo y me encuentro con tus fantasmas, no estaré en condicones de decir nada. Pero gracias por el aviso.",
"¡Te doy la bienvenida, capitán! ¿Qué quieres?",
"Estoy buscando a uno de mis oficiales. Te lo describiré: #sperson#, joven y con aspecto de noble. ¿Ha estado por aquí?",
"Sí. Un grupo de marineros también vino buscándo#spronoun#. Al principio, parecía que #spronoun2# los acompañaba de buen grado; luego hubo una discusión, pero #spronoun2# acabó yendo con ellos igualmente. Creo que uno de ellos escondía una pistola.",
"No pueden haber sido de mi tripulación. Si hubieran traído a mi oficial de vuelta al barco, me habría enterado. Gracias, de todos modos.",
"Tal vez no. Pero también se dice que la Inquisición escondió allí abajo todo el oro que robó a sus vícitmas. De vez en cuando, algún incauto entra en su busca. Y nunca vuelve a salir.",
"¿Oro? Haya lo que haya allí abajo, no pueden ser fantasmas, pero si hay oro, será mío. Pero gracias por avertirme de tus 'fantasmas'.",
". Hallo. ¿Puedo ayudarte, ",
"¿Puedo ayudarte, ",
"Hallo. Tal vez puedas ayudarme. Estoy buscando a #svillain#, que, según me han informado, navega a bordo del east indiaman '#sship#'. ¿Por casualidad #spronoun2# has visto?",
"No, no recuerdo a nadie con ese nombre.",
"¿Pero has visto el '#sship#'? Se supone que venía hacia aquí desde #sRedmond#.",
"No, casi todos los barcos ingleses que han llegado recientemente venían de #sCharlestown#. Los barcos que vienen del oeste son en su mayoría españoles\n Es raro que Holanda esté en una alianza con los ingleses y con los españoles; normalmente estamos en guerra con uno o con otro.",
"La política no me interesa. Pero tengo que encontrar a #svillain#: ha estado ayudando a los franceses y hay una recompensa por capturar#spronoun2#.",
"Si #spronoun# está en liga con los franceses, entonces estás buscando en el puerto equivocado. #sMarigot# está al otro lado de la isla y pertenece a Francia\n Pero no intentes llegar allí a pie, porque estamos asediando #sMarigot# y los franceses están asediando #sPhilipsburg#. Si los soldados no te matan, te matará una bala de cañón perdida\n Y puede que hayan visto tu barco desde el fuerte francés cuando te acercaste a la isla, así que entrar navegando en el puerto de #sMarigot# podría ser peligroso. Pero hay quien dice que existe un túnel entre #sPhilipsburg# y #sMarigot#. Tal vez puedas encontrarlo.",
"Gracias, esa información es muy útil. Adiós.",
". Bonjour. ¿Puedo ayudarte, ",
"Hallo.",
"¿'Hallo'? ¡Eso suena a inglés!",
"Por nacimiento, es lo que soy. Pero por elección, sirvo a Francia. Como #svillain#. ¿Por casualidad #spronoun2# has visto?",
"Oh, eso es otra cosa. Todos los amigos de Francia son amigos míos. Sí, #svillain# estuvo aquí hace unos días, antes de zarpar hacia #sPointe a Pitre#, en la isla de #sisland_Guadeloupe#.",
"¡Gracias! Espero poder alcanzar#spronoun2# allí.",
"Te diré otra cosa, ya que sirves a Francia. ¿Ves ese barco de allí?",
"¿El grande con muchos cañones?",
"Ese mismo. Es el '#sship#'. Acaba de llegar. Los ingleses y sus aliados no tienen nada que se le pueda comparar. ¡Ahora que el '#sship#' está aquí, los barreremos del Caribe!",
"¡Qué buenas noticias! Gracias otra vez, y adiós. <Piensa: me pregunto cuánto pagarían los ingleses por esta información. Quizás debería probar suerte en #sisland_Antigua#.>",
}