string DLG_TEXT[25] = {
"Ah, Mr. Legrand, ahн estб. їHa conseguido resolver el rompecabezas?",
"їїQuй?? їCуmo demonios puede saber usted nada sobre eso? (їQuiйn es este petimetre?)",
"No me reocnoce usted. Pero nos hemos visto antes...",
"(Puede que su cara me resulte familiar, pero...) Lo siento, no recuerdo...",
"Olvнdelo. їHa comprobado ya esa parte donde pone 'SE.ENTH'? їYa sabe quй letra representa la 'R'?",
"Bueno, yo... no estoy del todo seguro...",
"Tal vez deberнa volver a intentarlo. No olvide consultar el libro de misiones.",
"Verй quй puedo hacer...",		
"Sн, es la 'B'",	
"Sн, es la 'C'",
"Sн, es la 'F'",
"Sн, es la 'J'",
"Sн, es la 'K'",		
"Sн, es la 'P'",
"Sн, es la 'Q'",
"Sн, es la 'V'",
"Sн, es la 'W'",	
"Sн, es la 'X'",
"Sн, es la 'Y'",	
"Sн, es la 'Z'",
"Sн, por supuesto que sн. їQuй opina de '2'?",
"En efecto, aparece en varias ocasiones. Ahora solo quedan dos letras. Las dos se usan en una ъnica ocasiуn. Probemos primero con '.'.",
"Es usted muy listo, Mr. Legrand. Solo falta una letra y es bastante fбcil. '_' tiene que ser...",
"ЎEnhorabuena, ha encontrado todas las letras! їPor quй no va a ver si Mr. Poe ha regresado a casa?",
"Gracias, y adiуs (me sigue recordando a alguien...).",



};