string DLG_TEXT[251] = {
"Ese ha sío mi último tiro, 'massa' Will.",
"Sí, yo también he agotado la munición. Recojamos las gallinetas de agua y volvamos a casa.",
"Traiga p'acá, déjeme llevar ese saco.",
"Como tú digas, Júpiter. Atravesemos por el naufragio y vayamos dando un paseo por la orilla, en busca de conchas y especímenes entomológicos.",
"¿Qué pasa, 'massa'?",
"Oh, nada, Jup.",
"El bicho que vi é un bicho dorao, de oro macizo, tó toíto, por adentro y por ajuera, menos las alas. Nunca en mi vía tantié un bicho má pesao.",
"¿Un bicho de oro, dices? Hum, ¡volvamos y busquemos con más detenimiento!",
"'Massa' Will, ¿no dice usté na del bicho?",
"Puede que tengas razón, Júpiter. ¡Volveremos e intentaremos atraparlo!",
"¡Cuidao, 'massa' Will, hay alguien en la casa!",	//10
"¿Estás seguro, Júpiter?",
"¿Ve la jumareda, 'massa'? Yo no encindí ningún fuego, le digo.",
"Oh, oh, ¿quién puede ser?",
"Yo llevo las armas, 'massa'.",
"Sí, gracias, Júpiter.",
"¿Qué pasa, 'massa'?",
"¿No reconoces a nuestro amigo Mr. Poe, Jup?",
"No tié ná d'estaño, 'massa' Will, se lo he dicho a usté. El bicho é toíto de oro macizo por adentro y ajuera, menos las alas. Nunca en mi vía tantié un bicho má pesao.",
"Pongamos que así sea, Jup. ¿Es ésa razón para que dejes quemarse las aves?",
"¡A cená!",	//20
"My bien, comamos.",
"¿Qué é eso, 'massa'?",
"Un trozo de papel sucio, creo. ¡Pero puedo usarlo para atrapar el 'scarabæus'!",
"Oh, s'ha hecho tarde. Me voy a la cama, 'massa' Will. He cerrao la puerta pa e'ta noche.",
"Gracias. Una cosa, Júpiter, ¿sabes dónde está el caldero grande?",
"Abajo.",
"Buenas noches.",
"Jup, quiero que vayas al cobertizo de los botes; creo que queda algo de leña allí.",
"El cobertizo, sí. Y el plato pa horniar 'tá en la de'pense del sótano, 'massa' Will.",
"Gracias, Júpiter. (No me atrevo a preguntar dónde puso la llave)",		//30
"Quiero que vayas al pueblo de Moultrie y compres unas hojas de papel.",
"Deme el dinero, 'massa' Will.",
"No tengo dinero... Lleva ese pez grande, seguro que alguien del peublo puede venderlo a los turistas.",
"'tá bien, Júpiter irá.",
"Oh, sí, una cosa má. ¿Puedes visitar al teniente G en el fuerte y traer de vuelta el escarabjo de oro?",
"Me voy al fuerte, Júpiter, necesito la ayuda del teniente G con este texto cifrado.",
"'ta luego, 'massa' Will.",
"Júpiter, ¿el teniente G dejó alguna contraseña para mí?",
"¿Qué seña, 'massa' Will?",
"¿Un papel, quizás?",			//40
"Na má que el papel onde traía el bicho de oro.",
"Enséñame ese papel, Júpiter.",
"Está bien, ¿una carta o una nota quizás?",
"¿Qué carta, 'massa' Will?",
"Pero é noche cerrá, 'massa' Will.",
"Sí, es muy pronto. Descansemos un rato antes de ir a Charleston.",
"Pero si ya é casi de noche, 'massa' Will.",
"Sí, es muy tarde. Esperaremos hasta mañana para ir a Charleston.",
"Júpiter, Mr. Poe se ha mudado, según he oído. ¿Sabes adónde?",
"Júpiter no lo sabe seguro, 'massa' Will.",	//50
"Pero, ¿no acompañaste a Mr. Poe a casa la otra noche?",
"'taba tan o'curo que a Mr. Poe le co'tó encontrar la verja.",
"Una verja. Bueno, algo es algo. ¡Busquémosla!",
"¿'DEGREES'? (grados)",
"!!!",
"Júpiter, ¿has oído hablar de algún edificio que se conozca con el nombre de Bishop's Hostel o Hotel? (Hostal u Hotel del Obispo)",
"Bessop, sí, conozco la plantasión mu bien...",
"Bessop, dices... Hum, ¿por qué no? Júpiter, ¿dónde se sitúa esa plantación?",
"Saliendo de la siudá pol lao de la selva, 'massa'.",
"Ah, ¿sí?",				//60
"A lo mejó nos poemos colar en la plantasión po la noche, 'massa' Will.",
"Sí, es nuestra única oportunidad. Pero necesitamos algo para distraer a los guardias...",
"¿Quié decir como fuegos artifisiales o bombas?",
"Fuegos artificiales, qué buena idea. Me pregunto quién vende esa clase de cosas.",
"Los chinos venden fuegos artifisiales, 'massa'.",
"¿Los chinos? ¿En el restaurante chino, quieres decir?",
"Sí, e'pero qu'haiga pasao la malaria.",
"Ya lo veremos, Júpiter.",
"Oh no, ¿quié qu'hagamos ",
"el trabajo peligroso, eh?",		//70
"'tá bien, yo hago el re'taurante. Usté hace lo de leer y tó eso, 'massa' Will.",
"Muy bien, entonces todo está dispuesto. Ahora, ¿por dónde empiezo?",
"'Massa' Will, el chino ha mandao má cosas pa usté...",
"Déjame ver..., ¿qué es?",
"Carbón vegetal.",				//75
"Salitre.",
"Azufre.",
"Carbón vegetal y salitre.",
"Carbón vegetal y azufre.",
"Salitre y azufre.",			//80
"Carbón vegetal, salitre y azufre.",
"Muy bien, dámelo, Jup.",
"'Massa' Will, e'ta é la última vez que el chino le pué ayudá con los ingredientes. Se le han acabao tós.",
"No me digas. Bueno, veamos qué es lo que tienes ahí.",
"Deme esos barriles, 'massa'; Jup se los dará vacíos.",	//85
"Ah, muy bien, Júpiter.",
"Ahora voy al restaurante, 'massa'.",
"Nos subimos a esa montaña, 'massa' Will, y vemos la plantasión desde arriba primero.",
"Buena idea, Júpiter, ¡encontremos la forma de subir!",
"¿Ve la casa que echa jumo? los barracones están ju'to detrá. Dos barracones, 'massa', uno pa las mujeres y otro pa los esclavos varones.",	//90
"Hum, la plantación parece estar muy bien vigilada...",
"Sí, mire, una torre de vigilansia a ese lao, 'massa'.",
"Sí, ese camino es imposible. Me verían inmediatamente, ¿por el otro lado, quizás?",
"¿Va a ir usté solo, 'massa' Will?",
"Claro que sí, entrar en este sitio es demasiado peligroso para un negro. Yo quizás pueda razonar con ellos si me descubren.",
"Ya veo. Jup tirará los fuegos artifisiales desde ajuera, ¿sí? Y mire: hay otra torre de vigilansia en e'te lao tamién.",
"Tienes razón, Júpiter. Tendremos que acercarnos más; mantente agachado y sígueme.",
"¿Qué pasa, 'massa' Will?",
"Creo que es mejor esperar hasta esta noche.",
"Sí, va a tener que e'conderse entre esos fardos cuando consiga entrar, 'massa' Will.",	//100
"(¿Guardar..? ¿Qué quiere decir con eso?) Está bien, bajemos.",
"Quédese cerca de la ladera, 'massa', y espere a los fuegos artifisiales antes de saltar la valla.",
"Eso haré, Júpiter.",
"Deme ese yesquero y el cofre de fuegos artifisiales, 'massa' Will.",
"Claro, aquí tienes, Júpiter. Recuerda comprobar los números antes de encender los cohetes.",
"¿Quié que Jup quite esa caja, 'massa' Will?",
"Claro, ¿seguro que puedes con ella?",
"¿Y sí yo sujeto la palanca demientras usté sigue solo, 'massa' Will?",
"Pero, te quedarías atrás, Júpiter.",		//109
"Y usté iría solo a esa roca mi'teriosa.",
"Hum, está bien. Toma la palanca y dame un segundo para llegar a la reja.",
"Buena suerte, 'massa' Will.",
"Hasta luego, Júpiter, y ten cuidado con esos bandidos.",
"¿'tá usté bien, 'massa' Will?",
"Claro. Por favor, vuelve a abrir la verja. Y, Júpiter, no olvides recoger la palanca cuando caiga al suelo. La necesitaremos más tarde.",
"No é buena idea volver atrá. E'peremos que vaya tó bien.",
"Pero, ¿no son bandidos?",
"Cimarrones, 'massa' Will, cimarrones. Usté déjeme hablar a mí, a lo mejó entoavía poemos salir de e'ta.",
"¿Estás seguro, Júpiter?",
"Hola, Hero. Sí, soy un hombre libre dende hace mucho tiempo, y 'massa' Will encontró un bicho de oro... ",
" ...míalo tú mi'mo.",
"¿Aónde vamos ahora, 'massa' Will? ",
"Necesitamos un sextante, una brújula y un catalejo.",
"A la tienda, entonces.",
"¿Sabes dónde está, Júpiter?",
"Claro, usté m'ha mandao allá muchas veces. Está al lao de la casa de Mr. Poe.",
"Vayamos, pues.",
"Se comieron unos a otros.",
"¿De qué estás hablando? No querrás decir...",
"Claro, Jup irá. Aquí tié el yesquero, 'massa' Will. Y tenga cuidao con ese Pym... ",
"Son solo rumores, Júpiter, no hay nada de lo que preocuparse. Nos reuniremos en casa de Mr. Poe. ",
"¿'tá usté bien, 'massa'?",
"Sí, estoy bien, Júpiter, gracias. Y veo que has conseguido un catalejo.",
"Aquí lo tié, 'massa' Will...",
"¡Muy bien!",
"Ah, 'massa' Will. Jup tié una idea...",
"Pues oigámosla, Júpiter.",
"Poemos usar la e'calera de la montaña.",
"Hum, sí, muy buena idea (¿por qué no se me habrá ocurrido a mí?).",
"Pero, 'massa' Will, ¿no sabía usté ya qu'iba a pasar eso?",
"Sí, por supuesto, solo estaba comprobando una cosa...",
"Tenemos que probar otra cosa.",
"Hum, sí, me pregunto cómo podemos hacer para pasar los dos...",
"¡Nesesitamos una tabla pa bloquiar la reja cuando baje, 'massa' Will!!",
"¡SÍ! Tienes razon. Quizás podamos usar una de las tablas del puente.",
"Voy a por una, 'massa' Will.",
"Muy bien, Júpiter, yo volveré a buscar la palanca.",
"¿Ha vi'to la balsa debajo'l puente, 'massa'? A lo mejó podemos evitar a los malos navegando.",
"¿Balsa? Enséñamela, Jup, pero no hagas el menor ruido.",
"Ahí 'tá, pero, ¿cómo bajamos hasta allá, 'massa' Will?",
"Hum, tendré que echar un vistazo más de cerca desde el puente.",
"Traiga p'acá, déjeme llevar esa botavara.",
"Muy bien, vamos.",
"Sí, 'massa', Jup se pué trepar a cualquier árbol que haiga en el mundo.",
"Pues arriba entonces, Júpiter.",
"¿Hasta ónde de alto tengo que subir, 'massa'?",
"Empieza por el tronco, y ya te diré qué camino tienes que tomar... Solo dame un segundo para encontrar un sitio desde donde vea mejor, Júpiter.",
"¿Pa ónde tengo que ir ahora, 'massa' Will?",
"Sigue la rama más gruesa... la de este lado.",
"¿Cuánto más p'arriba tengo que subir?",					//160
"¿A qué altura estás ahora?",
"Tan alto, tan alto, que pueo ver el sielo entre las hojas del árbol.",
"Olvídate del cielo, escucha bien lo que te digo. Mira hacia abajo y cuenta las ramas que hay debajo de ti, de este lado. ¿Cuántas ramas has pasado?",
"Una, dos, tré, cuatro, sinco... he pasao sinco ramas de e'te lao, 'massa'.",
"Entonces sube una rama más.",
"Me da mucho miedo andar por e'ta rama p'alante; está mue'ta casi toa.",
"¿Dijiste que es una rama muerta, Júpiter?",
"Sí, 'massa', mue'ta como mi agüelo, seguro. Subía al sielo con los angelitos.",
"En nombre del cielo, ¿qué voy a hacer?",
"Ya voy, 'massa' Will; 'toy casi a la punta.",		//170
"¡A la punta! ¿Quieres decir que estás en la punta de la rama?",
"Enseguía llego a la punta, 'massa',  ¡O-o-o-oh! ¡Santísimo Padre! ¿Qué é e'to qu'hay en el árbol?",
"¿Y bien? ¿Qué es?",
"Pues na más que una calavera;  Alguno que l'han dejao la cabeza en el árbol, y los cuervos l'han comío toa la carne y el pellejo.",
"¿Una calavera, dices? ¡Muy bien! ¿Cómo está sujeta a la rama? ¿Qué la mantiene ahí?",
"Claro, 'massa', ahora miro. ¡Vaya, qué cosa má curiosa, vaya que sí! Hay un gran clavo clavao en la calavera que la sujeta al árbol.",
"Muy bien, Júpiter, ya puedes bajar.",				//177
"¡Rápido, 'massa'! ¡Atrás, al otro lao de la verja...!",
"¿Uh? ¿Tienes un plan?",
"¡Aprisa, 'massa' Will! Tenemos que llegar a la balsa antes de qu'abran la verja otra vez.",
"!!!",
"Tenemos que ir mu callaos, 'massa', pa que no nos oigan los cimarrones.",
"Sí, pasemos sigilosamente, Júpiter.",
"¿Qué e'tamos haciendo aquí? Los cimarrones nos van a encontrar...",
"Estoy buscando la entrada a esa cueva que visitamos antes, Jup.",
"¡Oh, no! ¿Ahora qué vamos a hacer, 'massa' Will?",
"Registremos de arriba abajo esta cueva dejada de la mano de Dios. Quizás podamos encontrar algo útil.",
"¡Mire, 'massa'! Los cimarrones ya 'tán aquí.",
"Sigamos, Júpiter.",
"¿S'han ido, 'massa'?",							//190
"Hum, parece demasiado bueno para ser verdad. Andémonos con mucho cuidado, Jup.",
"Sacos en el sótano. Sí, ya sé. Y el mosquetón tamién, pero, ¿ónde tá la llave del armero, 'massa'?",
"También hay sacos en el desván, Júpiter. Creo que decidimos esconder la llave en uno de los tarros.",
"Y necesitaremos el bote p'al tesoro grande, 'massa' Will.",
"¿Crees que podrás llegar navegando al Hostal de Obispo sin perderte?",
"Ah, ahí e'tán, por fin.",
"Veo que has traído un arma y el bote. Buen trabajo, Jup.",
"Tengo pólvora, 'massa' Will, pero na de metralla.",
"Hum...",
"Sí, 'massa', Jup pué treparse a cualquier árbol...",					//200
"Sí, ya lo sé, Júpiter; esta vez quiero que te lleves contigo esta cuerda.",
"No hay problema, démela p'acá.",
"Ten, toma también el escarabajo de oro. Úsalo como un peso para lastrar el extremo de la cuerda.",
"¡Oh, no! Mire qué garras y qué boca. Nunca vi un bicho má condenao: muerde y patea tó lo que se le arrima.",
"Pero ya está muerto, Jup.",
"A lo mejó me podría ir más p'alante de la rama si fuera solo, eso é verdá.",
"¿Solo? ¿A qué te refieres?",
"Pues al bicho. É un bicho mu pesao. Si lo tiro p'abajo, la rama no se romperá solo con el peso del viejo Júpiter.",
"¡Canalla infernal! ¿Qué clase de disparates estás diciendo? Te aseguro que si se te ocurre soltar ese escarabajo, te retuerzo el pescuezo, Júpiter, ¿me oyes?",
"Sí, 'massa', no hay por qué gritar al pobre Jup así.",
"¡Bien! Ahora escucha: ¡estamos buscando una fortuna y tú tienes miedo de un insecto! Por favor, Júpiter, aventúrate lo más que puedas por la rama y no dejes caer el escarabajo.",
"Ya voy, 'massa' Will; 'toy casi a la punta.",
"¡Muy bien!",								//213
"¿El ojo isquierdo de la calavera 'tá al mi'mo lao que la mano isquierda de la calavera? Porque la calavera no tié mano nenguna... 
¡No importa! Ya he encontrao el ojo isquierdo, ¡aquí 'tá el ojo isquierdo! ¿Qu'hago con él?",
"Pasa el escarabajo a través del ojo y déjalo caer hasta donde alcance la cuerda; pero ten cuidado de no soltar el extremo.",
"Ya 'tá hecho, 'massa' Will, é mu fácil pasar el bicho por el abujero, ¡cuidao que va'l bicho p'abajo!",
"¡¡Sí!!",
"Deme p'acá esa pala, 'massa' Will.",
"Gracias, Júpiter.",
"Ya sé, ya sé...",
"'tá hecho de metal, 'massa'. ",
"Creo que tienes razón, Júpiter. Démonos prisa, ¡puede que este sea el lugar!",
"Aquí tié más sacos vacíos...",
"Gracias, Júpiter. Volvamos junto al cofre del tesoro antes de que vuelvan los cimarrones.",
"Sacos, sí, 'massa'. Pero solo quedan dos.",
"Hum, puede que tú puedas cargar con el cofre esta vez, ¿no, Júpiter?",
"Hero sabe mu bien lo que se hace. No nos va a perder.",
"Hum, parece que lo conoces muy bien...",
"Deme acá la punta de la cuerda, 'massa' Will. Iré con la balsa pa tener bien vigilao el tesoro.",
"Muy bien, Jup.",
"Era... era mi primo.",
"Oh, cuánto lo siento, Jup.",
"E'pero que no haigan má...",
"Yo también. Vamos a despojarlos de lo que tengan antes de volver a casa con el tesoro.",
"'Massa' Will, deme p'acá su saco. Es el último.",
"Gracias, Júpiter.",
"Yo me quedo de'pierto tamién, 'massa'; tengo mucho qu'hacer...",
"Muy bien, buenas noches entonces.",
" ¡Y tó e'to po'l bicho de oro! ¡El lindo bicho de oro! ¡El probe bichito de oro que yo maltraté como un bestia! ¿No tiés vergüensa de ti, Júpiter? ¡Contesta!",
"¿Lo has movido todo aquí arriba y lo has puesto en orden?",
"Claro que sí, 'massa' Will, mírelo.",
"¡Has hecho un gran trabajo, Júpiter! Ahora veamos qué tenemos aquí.",
"Ahora solo me quea una pregunta, 'massa' Will: 
¿Qué hay de los e'quiletos que encontramos en el abujero?",
"He aquí una cuestión que soy tan incapaz de responder como tú.",
"Mr. Poe está mu cansao. Ha estao e'cribiendo esos papeles toa la noche...",
"Sí, eso me dijo.",
"Y en los campos de caña de azúcar. Quizás pueda encontrar alguna zona segura en esos edificios. Todos los guardias parecen estar patrullando fuera.",
"He estao ahí abajo, 'massa', asín que óigame bien; solo pué guardar en las zonas seguras.",
"'Encender en orden', ¿eh?",
"¡Ja!",

};