string DLG_TEXT[39] = {
"¡Pide algo o piérdete!",
"No vuelvas a hablarme de ese modo.",
"¿Qué quieres tomar, capitán?",
"¡Ron, y solo el de la mejor calidad!",
"Dame una botella de vino.",
"Cerveza, y que sea rápido.",
"Beberé agua, gracias.",
"Ahh, hay un pequeño problema... Se nos ha acabado el ron por ahora.",
"Ya veo. Entonces dame alguna otra cosa.",
"Buena elección, capitán. Son solo 250 piezas de oro por botella.",
"Suena muy barato, ¿el vino tiene algo de malo?",
"En absoluto, capitán. Tenemos nuestras propias... ejem... 'importaciones', eso es todo.",
"Muy bien, entonces ponme una botella ahora mismo.",
"No, no quiero gastar dinero en vino ahora mismo. Ponme alguna otra cosa.",
"Una jarra de cerveza fuerte. Solo 5 piezas de oro, capitán.",
"Muy bien, pues ponme un poco de cerveza.",
"Aqui´tienes, capitán.",
"¡Salud!",
"No, no quiero gastar dinero en cerveza ahora mismo. Ponme alguna otra cosa.",
"¿¿Agua?? ¡Nadie nos ha pedido eso nunca!",
"Bueno, yo... (quería decir un vaso, estúpido)",	//20
"¡Oh, no! Entonces ponme cualquier cosa.",
"Hum, ya veo...",
"¿Compra pescao, camarero?",
"Muy bien, te doy una botella de coñac por él.",
"¡¿Coñá?! Nesesito dinero, camarero.",
"Bueno, pues esta es mi oferta: coge alguna botella vacía que haya por aquí y llénala en ese barril grande de la esquina.",
"Hum, 'ta bien, é un trato.",
"Bienvenido al restaurante de Fort Moultrie, forastero. Me llamo ",
". ¿Qué le trae a mi humilde establecimiento?",
"Gracias. Me llamo ",		//30
".",
"Me llamo ",
", y se puede ahorrar tanta hospitalidad. Estoy aquí por negocios.",
"Señó, ¿tié hojas de papel pa Júpiter?",
"¡Bienvenido, señor! ¿Quiere algo de comer o beber?",
"No, esto es un restaurante, aquí vendemos comida y bebida. Ahora, por favor, pide algo.",
"¿Está aquí el teniente G?",
"Oh, sí, está tomando una copa abajo, como de costumbre.",

};