string DLG_TEXT[174] = {
"William, mi querido amigo. Disculpe esta intrusión. El tiempo ha refrescado, así que he encendido un fuego, espero que no le importe.",
"Por supuesto que no. Bienvenido, viejo amigo. Cenaremos pronto.",
"¿Imagino que han estado de caza todo el día?",
"Así es. Aquí viene Júpiter...",
"¿Sí? ¿Qué puedo hacer por usted?",
"Oh, nada por el momento.",
"¿Qué tiene ahí? ¿Algunas conchas nuevas?",
"¡Sí, y creo que una de ellas es un bivalvo desconocido, que constituye un nuevo género! Tenga, eche un vistazo.",
"Son muy hermosas..., pero ha encontrado usted algo más. Lo veo en su rostro, William.",
"Así es. He perseguido y cazado, con ayuda de Júpiter, un 'scarabæus' que, en mi opinión, es completamente nuevo, y sobre el cual me gustaría tener su opinión mañana por la mañana.",
"¿Y por qué no esta misma noche?",	//10
"¡Ah, si hubiera sabido que usted estaba aquí! Pero hemos pasado tanto tiempo sin vernos... ¿Cómo podía adivinar que vendría a visitarme justamente esta noche? Mientras volvía a casa me encontré con el teniente G, del fuerte, y cometí la tontería de prestarle el escarabajo; de manera que hasta mañana por la mañana no podrá usted verlo. Quédese a pasar la noche; Jup irá a buscarlo al amanecer. ¡Es la cosa más encantadora de la creación!",
"¿Qué? ¿El amanecer? ",
"¡Qué ocurrencia! ¡No! ¡El escarabajo! Es más o menos del tamaño de una nuez grande de nogal, color de oro brillante, y con dos manchas negras como azabache, cerca de un extremo del dorso, y otra, algo más extensa, al otro extremo. Las antenas son algo de verdad extraño...",
"Supongo que nos hemos quedado sin cena. Pero dígame, ¿de veras es ese escarabajo tan fantástico?",
"Oh, mi amigo es un poco impulsivo... Y sí, el color casi sería suficiente para justificar la opinión de Júpiter. Le aseguro que nunca ha visto usted un brillo metálico semejante al que emiten los élitros..., pero eso no podrá juzgarlo usted hasta mañana. Por el momento, trataré de darle una idea de su forma.",
"¿Qué busca, amigo mío?",
"Sé que tengo pluma y tinta por alguna parte. Quizás también algo de papel.",
"¿Puedo ver...?",
"¡Claro!",
"Está empezando a hacer mucho calor. ¿Podría reducir un poco el fuego, por favor?",	//20
"Veré qué puedo hacer...",
"El tiempo ha refrescado, ¿qué tal si aviva un poco el fuego?",
"El tiempo ha refrescado, ¿qué tal si enciende otro fuego?",
"¡Bueno! Debo reconocer que el escarabajo es realmente extraño. Completamente nuevo para mí. Jamás vi nada parecido..., como no sea un cráneo o una calavera, que es a lo que se asemeja más que a cualquier otra cosa que yo haya visto.",
"¡Una calavera! ¡Oh, sí...! Bueno, no hay duda de que, sobre el papel, puede tener algún parecido. Las dos manchas negras superiores dan la impresión de ojos, ¿no es verdad?, y la más grande de la parte inferior forma como una boca... y la forma general es ovalada.",
"Tal vez sea así, pero me temo, Legrand, que no es usted un gran artista. Tendré que esperar a ver personalmente el escarabajo, para poder hacerme una idea de su aspecto.",
"En fin, no sé qué decirle. Dibujo pasablemente... o por lo menos debería ser así, ya que tuve buenos maestros, y me jacto de no ser un completo zopenco.",
"Pues en ese caso, querido amigo, está usted bromeando. Este es un cráneo más que pasable, hasta me atrevería a decir que es un excelente cráneo, conforme a las nociones vulgares sobre esa región anatómica; y si su escarabajo se le parece, ha de ser el escarabajo más raro del mundo. Incluso podríamos elaborar una pequeña superstición aprovechando el parecido. Me imagino que usted denominará a su insecto 'Scarabæus caput hominis' o algo por el estilo. No faltan nombres semejantes en la historia natural. ¿Pero dónde están las antenas de que hablaba usted?",
"¡Las antenas! ¡No puede ser que no vea las antenas! Las dibujé con tanta claridad como puede verlas en el insecto mismo, y supongo que eso debería bastar.",
"Bueno, bueno.  Tal vez así lo haya hecho, pero, de todos modos, no las veo.",			//30
"---",
"Buenas noches, amigo mío. Veo que se está perdiendo más y más en su ensoñación, sin que nada de lo que yo diga baste para arrancarle de ella.",
"Bueno, yo... el pergamino... Hum. Júpiter le escoltará de vuelta a casa. Adiós.",
"¡Ah, William, bienvenido! Por favor, siéntese. Y pasa tú también, Júpiter, pasa.",
"Me alegro de verle, Edgar.",
"Ahora, dígame, mi viejo amigo, qué es lo que le trae aquí.",
"Bueno, es una historia larga y extraña. Recordará usted aquel pergamino que le mostré...",
"Esto es fascinante. ¿Ha encontrado usted ya las tres letras T H E?",
"Sí, pero a partir de ahí, las cosas se ponen más difíciles...",
"Si nos situamos en el segundo 'THE' empezando desde el final, encontramos la siguiente secuencia: 'THET.EETH'.",	//40
"¿Sí..?",
"Supongamos que ese último 'TH' es el inicio de una palabra diferente y descartemos el 'THE' inicial, ya que es imposible formar una palabra en inglés de la cual dicho 'TH' forme parte. Nos quedamos, pues, reducidos a la palabra 'T.EE'.",
"Entonces esa palabra tiene que ser 'TREE' (árbol). ¡Por lo tanto '(' es la letra R!",
"En efecto. Si miramos algo después de estas palabras, nos encontramos con la siguiente combinación: 'THE TREE THR...H THE'.",
"Sí, ya lo veo...",
"Aquí una nueva palabra se pone inmediatamente de manifiesto. Tal vez debería tomarse un descanso (guardar la partida) y consultar ese papel cuadriculado que tiene ahí.",
"De acuerdo, pero yo... ¿Cómo...?",
"Permítame una sugerecia, viejo amigo. ¿Por qué no va a visitar a Mr. Dupin? Es un viejo amigo mío y un investigador muy inteligente.",
"¿Se refiere al famoso detective? ¿Dónde vive?",
"Es muy fácil encontrarlo, William. Su oficina está cerca de las puertas que conducen de la ciudad al puerto.",		//50
"Lo encontraré. Gracias, Edgar, y adiós. Y, eh, mi copia del texto cifrado, si no le importa...",
"Permítame preguntarle una cosa: ¿ha conseguido averiguar a qué letra corresponde el símbolo 'X' ?",
"No, no tengo ni la menor idea.",
"Quizás debería volver a intentarlo. No olvide consultar el libro de misiones.",
"Sí, es la 'A'",	//55
"Sí, es la 'B'",	
"Sí, es la 'C'",
"Sí, es la 'D'",
"Sí, es la 'F'",
"Sí, es la 'G'",	//60
"Sí, es la 'I'",
"Sí, es la 'J'",
"Sí, es la 'K'",	
"Sí, es la 'L'",	
"Sí, es la 'M'",	//65
"Sí, es la 'N'",
"Sí, es la 'O'",
"Sí, es la 'P'",
"Sí, es la 'Q'",
"Sí, es la 'S'",	//70
"Sí, es la 'U'",
"Sí, es la 'V'",
"Sí, es la 'W'",
"Sí, es la 'X'",
"Sí, es la 'Y'",	//75
"Sí, es la 'Z'",
"Muy bien. Quizás también tenga alguna idea sobre la equivalencia de '?'.",
"Lo está haciendo muy bien. Y '3', ¿a qué letra corresponde?",
"Sí, eso creo yo también. La palabra tiene que ser 'THROUGH' (a través, siguiendo), este descubrimiento nos proporciona tres nuevas letras. Examinando con atención el código para buscar combinaciones de caracteres ya conocidos, encontramos no lejos del comienzo la siguiente serie: 'EGREE'.",
"¿'EGREE'?",	//80
"¡Por supuesto! Y dos letras más gracias a Júpiter. Sin embargo, lamentándolo mucho, mi querido William, tengo que marcharme ahora mismo por un asunto de negocios.",
"¡Bienvenido de nuevo, querido amigo! ¿Qué puedo hacer por usted?",
"Gracias, Edgar. Verá, he resuelto el criptograma, pero no tiene ningún sentido...",
"¿Puedo escuchar lo que ha conseguido descifrar hasta ahora?",
"Aquí está: 'A good glass in the bishop's hostel in the devil's seat forty-one degrees and thirteen minutes northeast and by north main branch seventh limb east side shoot from the left eye of the death's-head a bee line from the tree through the shot fifty feet out'.",
"Hum... es decir: 'Un buen vaso en el Hostal del Obispo en la Silla del Diablo cuarenta y un grados trece minutos norte-nordeste tronco principal séptima rama lado este tirar desde el ojo izquierdo de la calavera una línea recta desde el árbol siguiendo el tiro cincuenta pies hacia afuera'.",	//86
"No, el enigma sigue siendo tan inescrutable como antes. ¿Qué sentido puede extraerse de toda esa jerigonza sobre sillas del diablo, calaveras, y hostales del obispo?",
"Admito que el asunto se presenta sumamente difícil a primera vista. El primer paso ha de consistir en dividir la frase conforme a la división natural que debió tener en mente el criptógrafo.",
"¿Puntuarla, quiere usted decir?",
"Por favor, pasen y siéntense, los dos.",	//90
"Gracias.",
"Algo por el estilo. ¿Le queda algo de papel limpio?",
"Claro, un segundo...",
"Pienso que el autor de la cifra decidió escribir deliberadamente las palabras sin separación, a fin de que resultara más difícil descifrarlas. Ahora bien, al hacer esto, un hombre de inteligencia rústica tenderá con casi total seguridad a exagerar; es decir, que cuando en el curso de su redacción llegue a un lugar que requiera una separación o un punto, se apresurará a amontonar los signos, poniéndolos más juntos que en otras partes. Si examina usted el manuscrito, podrá advertir cinco lugares donde ese amontonamiento es fácilmente visible.",
"Partiendo de esta noción, podemos dividir el texto en la siguiente forma:",
"Ahora, por favor, si me disculpa...",
"Por supuesto, y gracias, amigo mío. Tengo que darle más vueltas a esto.",
"Ajá, bienvenidos, amigos míos.",
"Edgar, perdone la intrusión.",
"En absoluto, amigo mío. ¿Qué puedo hacer por usted?",		//100
"Bueno, estamos buscando algunos instrumentos de navegación.",
"La único que tengo es una vieja y pesada brújula...",
"¿Podemos tormarla prestada por un tiempo?",
"Por supuesto. Un segundo...",
"Es usted muy amable, Edgar.",
"Aquí está la brújula, con una bolsa incluida para transportarla.",
"Gracias, Edgar.",
"Supongo que están siguiendo las pistas de ese texto cifrado...",
"Así es, ¿por qué no se une a nosotros?",
"Suena fascinante, pero hoy tengo una cita muy importante.",	//110
"Algún otro día entonces, Edgar.",
"¿Y..?",
"Oh, le pido perdón por la intrusión, Edgar. Pero necesitamos su ayuda...",
"Hum, deme solo un minuto para vestirme. Quizás pueda esperar arriba en mi habitación...",
"Por supuesto. Vamos, Júpiter.",
"Déjeme adivinar: ha resuelto las pistas en ese texto cifrado y necesita ayuda para acarrear el tesoro pirata.",
"¡¿Cómo puede usted haber deducido todo eso?! Es más de lo que yo sé. ¿Piratas, dice? Por favor, cuéntenos más.",
"El pergamino que me mostró tenía un dibujo de algo que al principio me pareció una cabra. Sin embargo, al examinarlo con más detenimiento, terminé por reconocer que se trataba de un cabrito.",
"No irá a buscar una relación especial entre sus piratas y una cabra. Bien sabe que los piratas no tienen nada que ver con las cabras. Solamente los granjeros se interesan por ellas.",
"Pero le acabo de decir que el dibujo no representaba una cabra.",		//120
"Bueno, pues un cabrito..., pero es casi la misma cosa.",
"Casi, pero no del todo. Supongo que habrá usted oído hablar de un tal capitán Kidd.",
"Por supuesto. Continúe.",
"Consideré inmediatamente que el dibujo equivalía a una especie de calambur visual o firma jeroglífica -cabrito en inglés es 'kid'-. Si digo firma es porque su posición en el pergamino sugería esta idea. Del mismo modo, la calavera colocada en el ángulo diagonalmente opuesto producía el efecto de un sello.",
"Sí, he oído muchas historias sobre el tesoro del capitán Kidd. Pero de ahí a creer que sean reales...",
"Observará usted que las historias que se cuentan aluden siempre a buscadores de tesoros y no a los que los encuentran. Si el pirata hubiera recuperado su dinero, el asunto habría acabado ahí. Consideré, pues, como cosa segura que la tierra guardaba aún su tesoro, y no le sorprenderá si le digo que tuve la esperanza, por no hablar de certeza, de que aquel pergamino hallado de manera tan  rara contenía las informaciones concernientes al lugar donde se encontraba el botín.",
"Tiene usted razón. Hemos encontrado algunas cosas realmente extrañas en un lugar llamado Bessop's Castle. Cosas que bien podrían ser obra de piratas.",
"¿Pero aún no han encontrado el tesoro?",				//128
"No, necesitamos más herramientas que una simple pala. También hay un problema con un grupo de cimarrones muy hostiles. Así que también necesitamos armas. Y además de eso, nos gustaría que usted se uniera a nosotros en esta búsqueda del tesoro.",
"Los acompañaré, todo esto es apasionante. En cuanto a las armas, tengo una buena pistola en el taller del herrero para unas reparaciones. Pero no puedo permitirme pagarlas...",
"Tenga su brújula, quizás pueda usarla para llegar a un acuerdo con el herrero.",
"Gracias, William. Tengo alguna idea sobre dónde podemos encontrar herramientas sin tener que pagar por ellas...",
"Muy bien. Haré una visita al fuerte, a ver si puedo conseguir algún tipo de arma. Tenemos algunos sacos vacíos en casa, Jup. ¿Podrías ir a por ellos, por favor?",
"William, nos reuniremos en las afueras de la ciudad, junto a las puertas, cuando hayamos conseguido todo lo necesario.",
"Así será, en las afueras.",
"He encontrado estos clavos en la iglesia, ¿quizás puedan servir?",
"Sí, ¿por qué no? Déselos a Júpiter.",
"¿Así que este es el árbol con la calavera?",	//138
"En efecto. Ahora, Júpiter, si eres tan amable, ¿nos harías el favor de trepar al árbol otra vez?",
"¿Qué está haciendo ahí arriba? No se oye nada.",
"¿¿??",
"Según recuerdo, había algo acerca de una línea recta desde el árbol siguiendo el 'tiro'. Pero, ¿cómo debería ser de larga esa línea?",
"Tengo que consultar mis papeles.",
"¿Y bien? ¿Cómo de larga tiene que ser la línea?",		//144
"Ejem, tengo que comprobarlo otra vez...",
"Cincuenta pies.",
"Bien. Ahora, Júpiter, ¿serías tan amable de sujetar el extremo de esta cinta métrica y situarte cerca del árbol?",
"Ajá.",
"Entonces, mediré con la cinta métrica cincuenta pies a partir de la estaca.",
"Muy bien, Edgar. ¡Ya estamos cerca!",
"¡Venga! Debemos volver, la partida aún no ha acabado.",
"Suficiente; tendremos que volver a empezar.",
"Jup tendrá que volver a trepar al tulípero.",
"No, no, bastará con colocar otra estaca al lado de la primera.",
"Cierto. Por favor, Edgar, adelante.",
"¿Qué es esto? ¿La X marca el lugar?",
"Hum, ¿por qué no? Apartemos a estos pobres bastardos... ¡Hay algo debajo de los esqueletos!",
"William, déjeme probar con el pico.",
"¡Sí, buena idea!",
"Sí, es extraño, ¡dónde están los cimarrones? ¿Habrán perdido nuestra pista?",
"Quién sabe. Tenemos que andarnos con mucho cuidado.",
"¡Ja, menuda victoria!",
"¿Qué pasa, Júpiter?",
"Creo que me sentaré un rato y tomaré algunas notas...",
"... ¡Nuestra aventura me ha dado una idea!",
"William, querido amigo, no se preocupe, sea feliz. El tesoro está a salvo, Júpiter solo lo ha trasladado al desván.",	//166
"¡Muy bien! ¿Todavía está despierto, Edgar?",									//167
"Sí, estaba escribiendo y me he dejado llevar. Cuando haya terminado de examinar el tesoro más de cerca, me alegraría mucho si quisiera escuchar mi último relato corto.",	//168
"Por supuesto, Edgar, Me encantaría.",									//169
"Oh, ¿y qué hay de todo lo demás que recogimos de los cimarrones?",
"Júpiter se ha encargado de todo. La comida está en la despensa, las armas por supuesto en el armero y las herramientas en los cofres justo detrás de usted.",
"¿Y los objetos más valiosos?",
"Los llevó al desván junto con el tesoro.",							//173


};