string DLG_TEXT[54] = {
"---",
"---",
"I'm pleased to meet you, Captain.",
"So you must be the 'Damsel in Distress'. Am I correct?",
"Yes, and I hope that you are the brave captain that can help me.",
"That remains to be seen Mistress, and we won't know till you tell me what your problem is, now will we? Let's start by you telling me your name.",
"Ah! My name is Annabella Brin... kley-Achoo! Sorry I have a bit of a cold. My name is Miss Annabella Brin.",
"That's a start. Good day to you Miss Annabella Brin. [THINKS: Brin, Now that's a name that Matthew mentioned.] I am Captain ",
", at your service. So, we are introduced. Now, what is your problem? ",
"Oh! Captain, it is trifling in the great scheme of things, but to me it is of great consequence, and causing me much distress.",
"Indeed, indeed. And the matter of this 'Great Consequence'?",
"I have had a stupid argument with my Father. He gave me charge of my sisters and my Mother's jewels on a short voyage here. I have become separated from my sister and dare not return to my Father without her.",
"I see. And your mother's jewels? [THINKS: We need to get our prioritites in order here!]",
"Oh! They are safe enough, I have them on me, but I fear being robbed, being a young lady alone. Perhaps you would take charge of them for me. But it is my sister I am more concerned about.",
"Very well, give me the jewels if that will make you feel better. As to your sister, where exactly did you 'loose' her?",
"Here are the jewels. I am much relieved now you have charge of them. My sister and I were separated in the town on the other side of the island, and I dare not travel through the jungle alone to try to find her. Captain, could we not sail there on your ship to seek her out?",
"We could indeed Miss Annabella, we could indeed. We could also take the land route through the jungle. With me to protect you, we would have little problem. Let me think for a moment as to which course to take. [THINKS: Well, the jewels will give me some leverage against my costs in this mission should the dear lady and I get separated.]",
"Have you decided?",
"Yes, Miss Annabella I have. Let's go.",
"Well, we made it. We should go to the Tavern to see if my sister is there.",
"Seems logical. Let's try that then.",
"Captain, I'm so glad to see you again. This is a matter of great importance, and we had to be sure we had the right person.",
"You only left a moment ago. Will you just tell me what this is all about.",
"Of course Captain, I owe you that. I am indeed separated from my sister, Bella, but I did not lose her. She was kidnapped by pirates along with her maid.",
"I see, so you are indeed Annabella Brin. And your mothers jewels? [THINKS: Nobody seems to have their priorities in order around here.]",
"Ah! The jewels. I'm afraid they were a test. A test to see if you would steal them and run off.",
"Steal them! As if.. You malign my character Miss Brin.",
"Oh! No! Captain, we were certain you were the right person, but we just had to be doubly sure of your character.",
"And I take it that now you are?",
"Yes Captain. The mission will need you to masquerade as a pirate and infiltrate their island to rescue my sister. We cannot go as we would be too easily recognised.",
"Oh! Is that all? Then I'll do it right after supper! .. Miss Brin, what you propose is a very dangerous task.. not to mention expensive, very expensive.",
"I understand the danger Captain, that's why we chose you. As to the expense, use the jewels I gave you, plus these, to fit out your expedition. I can assure you that my father will reward you hansomely when you have rescued my sister.",
"Very well, I will undertake your mission. Where should I start looking for your sister and the maid?",
"And if I decline your request?",
"Try #sisland_Quebradas Costillas# Island first. That is the last report we have of them.",
"Your reputation on this island is already in doubt. All Mr Brock here needs to do is confirm my 'kidnapping' and your future will be bleak. That is, if you get out of this room alive.",
"I shall leave as soon as I am suitably equipped Miss Brin. Wish me a fair wind and a calm sea.",
"I will take my chances in that respect Miss Brin. En garde!",
"Then I shall indeed wish you a fair wind Captain and I hope to see you again soon in #sisland_Redmond#",
"Let's hope that day won't be too far off.",
"Ah! Captain Skull, let me introduce the brave Captain who was going to help me rescue my sister. Ha! Ha!",
"What? I thought you couldn't come here? What's going on?",
"A slight change of plan my dear Captain. Miss Brinn and her sister were indeed kidnapped, but by Captain Skull and I. I just happen to look like Annabella that is all, but it suited our purpose. What we needed was someone to transport them back and collect the ransom for us.",
"And I was the dupe you selected? [THINKS] All is not lost, I can see some leverage coming my way here.",
"Quite so, dear Captain. You will take one sister back to #sisland_Redmond#, collect the ransom, bring it back here, and then we shall release the other sister. I will come along to keep an eye on things.",
"And how do you know I won't trick you?",
"Because we shall also keep your companion here till you return. If you trick us, she dies! As does the sister. Do you understand?",
"It seems I have no option... Very well, I accept your terms.",
"So.. we are to travel in two ships, I hear?",
"For comfort Miss Brinkley. One ship is too small to accommodate us all. To sea then, to sea. We have things to do, and places to go.",
"When will we get back to our father?",
"Soon, Miss Brin, soon.",
"Thank you for rescuing us Captain. What happens now?",
"We get you back to your father. Let's get going.",

};