string DLG_TEXT[29] = {
"I am ready for sea.",
"That's good Captain.",
"Who are you?",
"A friend of Captain Petros and Sir Christopher Mings.",
"Oh! You are, are you? Then we both seem to be...?",
"Members of the Brotherhood.",
"Good! Sorry about that, but we need to be careful. What is your name? And what are you doing here?",
"I am Captain ",
", and I am looking for Captain Nathan Kell. Do you know where he is?",
"Ah! Captain Kell, there are a few here who would like to see him, and not to his advantage. And why would you want to see him?",
"I believe he has something I need.",
"You will need to be more specific I'm afraid. I need to be sure you are indeed one of us.",
"He has part of a map that the Brotherhood needs, mate. Satisfied?",
"Very well, go where you would if you were ill, he has a secret room in there. I'm afraid I cannot come with you, both of us going in at once will attract attention.",
"And a cautious man like yourself wouldn't have any of that now, would he? Alright then, thank you for your help. I shall go now.",
"Captain Kell, Captain ",
". Cutler Beckett is in town, and he is asking about you Captain ",
".",
"A touch inconvenient, to say the least. But I've outwitted him before.",
"Good to see you again, Captain. You'll find your ship in the harbour all fitted out.",
"Thank you, Captain Damski. What now?",
"You should sail back to Lighthouse Bay. Anamaria will meet you there. We're expecting Barbossa to be in the area so he should come and contact you.",
"Very well, Lighthouse Bay it is. I did promise a certain miss Anamaria I would go back for her. Oh! And thank you all for your help.",
"We have a meeting with Captain Boelen. So we will bid you a fair and following wind till we meet again.",
"And to you all, captains. Till we meet again.",
".",
".",
".",
"Good to see you Captain. I see that both you and Cap'n Drow are here. We took the liberty of sailing your ship here after you were captured. You'll find it in the harbour.",
};