string DLG_TEXT[28] = {
"Are you ready?",
"I am just a bottle of rum short of being it, mate.",
"Captain, when we arrived in the tavern room we found the last piece of the map and we managed to figure it out using it as well. The map shows the Isla de Muerte.",
"Ah! The Isla de Muerta. Yes I know a little about it, but better than that, I have a compass that can get us there, and with the whole map we can find the treasure. But where are the others?",
"Oh yes! The others. I don't know if you noticed but that dammed Lieutenant Bligh followed us here, so the others have set sail to make him follow them, in order to lead him on a wild goose chase.",
"While we, in the meantime sail off to the Isla de Muerta, I imagine?",
"Exactly! We need to set sail as soon as possible.",
"Alright. Scurry then.",
"I think he means we... er... can sort of see through you!",
"See through me? AHH! Bugger! My hands! They're all bones!",
"That's what we meant! You've caught something Jack... Something nasty!",
"I feel alright though... I think.",
"Jack! What are you doing here..? You look, er... normal. We were just coming for you, the doctor is already aboard my ship.",
"I'm fine. It seems I wasn't before but I am now. The treasure is cursed. If you take but a single coin of it you are cursed. It will take too long to explain, but I've written it down, here take it and get it to Sir Christopher.",
"Thanks Jack. I'll offload the doctor and then we can sail back to #sOxbay# and Sir Christopher.",
"You do that. I want my ship back so I am going to go to #sisland_Turks#. I assume she is still there?",
"Yes, she is. Here are your map parts by the way. I suppose this is goodbye then?",
"It is, until we meet again. It has been fun, hasn't it? Goodbye and fair winds. I need to refit before I leave.",
"Captain, we have received a message from Captain Charles at the Plantation. You remember that he had part of the map, but it was taken from him.", // TALISMAN added  -->
"That I do. What is the message, then?",
"Well, Captain Charles has managed to do a rough sketch of the piece he had from memory, and has sent it to us. With that sketch and the pieces you provided, we have managed to identify the island. It is the Isla de Muerta.",
".",
".",
".",
".",
".",
".",
".",
};