string DLG_TEXT[25] = {
"G'day captain.",
"Hello captain.",
"Hello, I see you're travelling with Lucas.",
"And what if I am?",
"Something has happened to the governor's daughter. I think you should go and see Governor Le Moigne.",
"Ok, thanks for the advice.",
"So what is up with the governor's daughter?",
"She has disappeared. She went to #sHavana# and has not returned in two months. A frigate called 'La Foudre' was sent to find her and hasn't been heard of either.",
"Ok. Well, I'm sailing towards #sisland_Cuba# anyway, so if you want to sail with me I would welcome it.",
"Thanks for the offer. I think I'll accept it, just in case. Which ship is yours?",
"The 'Van Diemen'.",
"We will set sail soon.",
"Well, we made it to #sHavana#. I would go and see the portadmiral, if I was you.",
"Thanks for the advice.",
"It was a pleasure sailing with you, captain, but I must sail on now. I may see you around sometime.",
"Thanks for all your help, Captain Maggee. Farewell.",
"Hello again captain, this is Tia Dalma. I suggest you have her sail with you on your next voyage.",
"Why is that Captain Maggee?",
"Just trust me... It may save your life!",
"Ok I will allow her to sail with me, what are you going to do now?",
"I have business elsewhere, so I must leave.",
"Goodbye again then Captain Maggee.",
"I noticed the governor has been quite quiet recently, perhaps you know why?",
"Yes I do... His daughter has disappeared on route to #sHavana# and he has also lost a frigate in the search. I have now been asked to search for her and the frigate as well now... savvy.",
"Ok. Well, I'm sailing towards #sisland_Cuba# anyway, so if you want to sail with me I would welcome it. Oh, by the way, call me Captain Maggee.",

};