string DLG_TEXT[234] = {
"Give me a penny and you'll stop me from crying, ", // SJG All dialogue changed here for Jack Sparrow Story
" Give me some gold and you'll stop me from dying!",
"I know about Davy, the Spot and the Kraken. I know about Pirates and who they're attacking! I could tell you some stories, how ghosts can touch man, about treasure, the witch and the cursed Flying Dutchman. So give me a coin, just one or say two, ask me a question and see how I do",
"Oh ",
", help a poor beggar, you never can tell, I might tell you something that serves you quite well.",
"I'm sorry; I don't give handouts, especially to bad beggar poets!",
"I don't have anything smaller than a piece of gold. Will one be enough to stop you from starving for a while?",
"I won't give you a handout -- but I'll let you earn some money if you're willing.",
"Thank you, ",
"! You'll be a man who is lucky, you see if you don't. Look out for old Davy, the spot and the boat!",
"Right. You've got your coin. Now, stop the riddles and poetry and answer a few questions for me.",
"Thanks. You can go now.",
"No money for Henry, ",
"You're poor or you're mean. Beware, in these waters, the Kraken's been seen. ",
"(Return.)",
" Henry knows much, he's poor but he's smart. At answering questions, he's the best in the art, ",
", Ask away with your question and I'll see you alright. Henry can talk far into the night.",
"Do you know the town very well?",
"Have you heard any word of the governor of #sRedmond#?",
"Can you only speak in riddles? I shouldn't waste my time asking questions of a beggar.",
"I'm sorry, ",
" Henry is poor and owns not a lot, What could he tell you that you haven't got. \n You're questions are puzzling, I find it quite hard. To look for an answer, try asking the guard.",
"You may be right. I shouldn't waste my time asking questions of a beggar.",
"I'm not asking someone else right now. I'm asking you, and stop it with the rhyming, you're playing with my mind",
"No money for Henry, ",
" you're poor or you're mean, beware, in these waters, a witch will be seen. ",
"(Return.)",
" Knowledge is mine it's all I have got. Ask me your question, I'll tell you a lot. ",
"?",
"Where can I find the tavern?",
"Where is the shipyard?",
"Where can I sell the fine goods I've brought with me?",
"Charity is a virtue, ",
", I know with this answer you'll think I'm quite brash, but to give you an answer I'll be needing more cash.",
"You must be joking. I'm not going to pay for information from a beggar! AND STOP IT with the rhyming!",
"How much?",
"I'm listening,",
"Do you know the town very well?",
"Have you heard any word on the governor of #sRedmond#?",
"You may be right. I shouldn't waste my time asking questions of a beggar.",
"A drink for the Captain? Some food and a song? Straight on to the Governor's you'll not be far wrong. The Tavern you'll find on the left of the square, and many fine folks awaiting you there.",
"Fine. Thank you.",
"Where's the shipyard?",
"Where can I get some coin for the fine goods I've brought with me?",
"The shipyard itself, behind the town gates at the shore -- but the manager's office is a short walk, and no more, ",
" to the left from the gates. You'll see the sign hanging, go through his front door and you'll soon hear him banging. ",
".",
"Thanks. And how can I find the tavern?",
"Where can I sell some of the goods I've brought with me?",
"Thanks for the information. That's all I need for now.",
"Go straight down the middle, and this isn't a riddle, ",
", on to the square, a really fine sight, the building you need is just there on your right.",
"Where is the town's shipyard?",
"Can you direct me to the tavern?",
"Thanks. That's all for now.",
" gold, if you please, ",
" My life will be short if this should get out. Henry has enemies roaming about.",
"All right, here's your money. Spill it, and I'm NOT paying for just more poetry!",
"I'm not paying that much. I'm just looking for some answers -- you don't have to engrave them in gold.",
"Fine, fine., ",
" Come closer my friend, this is what I have heard, the Governor they say, is not a good bird!",
"That's it? That's all you have for me? I'm going to need a refund.",
"Tell me something I don't know. Better yet, stop wasting my time. Get lost!",
"I'm sorry, ",
". It appears you're a little bit short on funds right now.",
"(Return.)",
"Not at all, ",
"! The Governor is greedy. He hides it quite well, away from the people, but Henry can tell. He's rich and so powerful and not yet too old, stopping at nothing to get some more gold! But he's not your worry, not on this fine day. There's another more crafty, that's all I will say",
"So far, I'm not impressed with the return on my investment, and the poetry's not improved either!",
"Great. I'll keep that in mind. Goodbye.",
"Buccaneers eat crab, kings eat them too. Give heed to these words, while the fish you watch flying, when you break their fine code, they'll tell you whose lying!",
"Nothing but riddles and poetry! Poetry and riddles! I'm beginning to suspect you have nothing useful to tell me.",
"Give me a coin just one, or say two, ask me a question, and I'll answer for you. ",
" we've spoken before, an answer I gave, I know for the rhyming you weren't apt to rave!",
"Charity, Charity is all that I beg, if I don't eat quite soon, I'll be eating my leg!",
", one bag of gold is that asking too much? I don't ask for more, you're not a soft touch",
"Have you forgotten? I don't believe in handouts, and the rhyming hasn't got any better either!",
"You again? Fine, take it.",
"I'll give you some money, but you'll answer some questions in exchange.",
"Thank you, ",
"! Your kindness itself, a joy to behold, Henry is grateful to have gotten your gold!",
"By the way, I'd like to know something.",
"Thanks. You can go.",
"Alas, ",
", it appears you don't even have money to spare for charity.",
"(Return.)",
"Sure, ",
". It's the least I can do for someone so kind. Ask what you will, I really don't mind.",
"Do you know the town?",
"What do you hear about the Governor of #sRedmond#?",
"You know, I can't think of any questions for you now, and I'm REALLY sick of this rubbish poetry!",
"I'm truly sorry, ",
", but your questions are hard, to find what you want, try asking the guard.",
"Maybe. But I'm asking you.",
"I guess you're right. You couldn't possibly have the information I need.",
"Alas, ",
", it appears you don't even have money to spare for charity.",
"(Return.)",
"Knowledge is mine it's all I have got, give me some gold and I'll tell you a lot, ",
"?",
"Where can I find a drink and some conversation?",
"Where's the shipyard?",
"Where can I get the best price for the goods I've brought with me?",
"I'm sorry, ",
". Gold I'll be asking before we move on, once I have told you, I know you'll be gone.",
"Are you kidding? I'm not going to buy answers from a common beggar! Especially one who is the worst poet I've ever heard",
"How much?",
"I'm listening.",
"Do you know the town?",
"What do you hear about the Governor of #sRedmond#?",
"I guess you're right. You couldn't possibly have the information I need.",
"A drink for the Capatain, just the best rum, drinking all night till his nose goes quite numb. Got to the main square near the Governor's resort, the Tavern you'll find is just off to your port.",
"Got it. Thank you.",
"Where's the shipyard?",
"Where can I get the best price for the goods I've brought with me?",
"The shipyard itself is behind the town's gates, at the shore. But the manager's office isn't there any more, ",
", to the left from the gates. Can you see the sign swinging, go on through the door, you'll soon hear him singing, ",
"?",
"I see. And where is the tavern?",
"Where can I sell the fine goods I've brought with me?",
"Thanks for the info. That's all I'll be needing. Now I'm a darn poet, I'd better be leaving!",
"Go straight down the middle, this isn't a riddle ",
". When you get to the square, a really fine sight, the store you will find, is just to the right.",
"How can I get to the tavern?",
"Where's the shipyard?",
"Thanks. That's all I wanted to know. That's enough poetry for one day!",
"Please, ",
", My life will be short if this should get out, Henry has enemies wandering about.",
"All right, fine. Take your money and talk!",
"At that price, I think I can do without a beggar's secrets, and the rubbish poetry!",
"Come closer, ",
". I'll tell what I've heard, the Governor they say, is not a good bird! .",
"That's it? That's all you have for me? I'm going to need a refund.",
"Tell me something I don't know. Better yet, stop wasting my time. Get lost!",
"I'm sorry, ",
". It appears you're a little bit short on funds right now.",
"(Return.)",
"Not at all, ",
"! The Governor is greedy, he hides it quite well, but Henry, he knows, yes, Henry can tell. Rich and so powerful and not yet too old, but all that he wants is getting more gold! But he's not your worry, not on this fine day. There's another more crafty, that's all I will say!",
"So far, I'm not impressed with the return on my investment, and I'm NOT impressed with the poetry either",
"Great. I'll keep that in mind. Goodbye.",
"How about this: Buccaneers eat crabs, kings eat them too. Give heed to these words while you watch the fish flying, read them again and they'll tell you whose lying! ",
"Riddles and poetry, Poetry and riddles, is that all you've got? I'm beginning to suspect you have nothing useful to tell me.",
"Give a coin to a poor man, ",
", I know about witches, the Kraken and gold, stories of Davy that haven't been told!",
"Please! Give me some money, you never can tell, I might tell you something that serves you quite well!",
"Oh ",
", show me some mercy don't be so cold, some rum or some whiskey, maybe some gold?",
"I'm sorry; I don't give handouts, and your poetry hasn't improved, has it?",
"Oh, it's you again. Here, take it.",
"Thank you, ",
". Your generosity is bottomless, a bottomless well, Arrr, sir you're so kind, Henry can tell.",
"I'm hoping you can refresh my memory of a few things we've spoken about before.",
"Thanks. You can go now.",
"Can it be, ",
", that you don't even have money for charity? Perhaps you should join me in my, um, work. ",
"(Return.)",
"With pleasure, ",
". The Governor I'm thinking is what you're about, come in a bit closer, you know I can't shout.",
"No, it has nothing to do with the Governor. I'm just a little bit lost at the moment.",
"Exactly. What did you tell me about him?",
"I don't have any questions for you right now.",
"I'm sure it's my fault that you have forgotten. Your memory's like mine getting old and quite rotten, ",
", come closer, kind sir, come a bit nearer, I don't want this heard by any old hearer.",
"I am all ears.",
"You're very nearly trembling with fear! Let's speak of something else.",
"Ah! No problem, ",
". I'll point you right, like a fine Navy compass, straight where you're going, no fuss and no rumpass.",
"Where can I find the tavern?",
"I'm looking for #sRedmond#'s shipyard.",
"I've brought goods I'd like to sell. Where can I do that?",
"Thank you, ",
". What more can I do? What else do you need, or are we all through?",
"I need some directions. ",
"I don't need anything, thanks, especially more poetry! . Goodbye.",
"Ah, a drink for the Captain, some food and some song. Go straight down the street you can't get it wrong. When you get to the square,the Governor's resort, the tavern you'll see, just off to your port.",
"Got it. Thank you.",
"Where's the shipyard?",
"Where can I sell the fine goods I've brought with me?",
"The shipyard itself is behind the town's gates at the shore. But the manager's office it stands there no more, ",
", to the left from the gates. Can you see the sign swinging? Go through the door, You'll soon hear him singing. ",
"?",
"I see. And the tavern?",
"Where I can sell my goods?",
"I see. Thanks for your help.",
"Go by the central street ",
", and when you get to the square, a really fine sight, the store you will find, just off to your right.",
"Where's the local shipyard?",
"How do I get to the tavern?",
"I see. That's all I wanted to know.",
"Remember, The Governor is a greedy man, and yet is not too old, he sits there in his palace, just dreaming of more gold. But he is not the one to watch, he's not among the scabs, remember what I said to you about buccaneers and crabs!",
"That's right, and I told you I was fed up with all this poetry. What was the crab bit again?",
"Yes, I remember now. Thanks.",
"Buccanneers eat crabs, kings eat them too! Studying these words, tells whose after you! Write as a list, that's what you should do, Then read down the left, Hey Presto! your clue!",
"Yes. It's all coming back to me. I need to study the buccaneers and kings phrase for the answer as to who I should watch out for!",
"Ah! Captain you're back, but a frown on your brow. Henry it seems must be helping you now.",
"Henry, listen I have a major problem. I have just met the real Cutler Beckett and he has told me to capture the imposter, but I don’t know where to start looking, or if he is an imposter, or whether I should bother with it at all.",
"Think hard my dear Captain, think hard and think slow. What you do now sends you where you will go. There’s no coming back when your answer you’ve given. Your life will be set as to how you’ll be livin’. You can follow your quest the rainbow to find, or cast off this old life and leave it behind. You can sail the wide seas on adventure most rare, but who knows what troubles are waiting you there.",
"My choices are then , stay with this quest or forget about it and choose a new life?",
"Correct my dear captain, at the crossroads you’re standing and how you decide will show where you’re landing.",
"O.K. I will stay with the quest and find the other Cutler Beckett.",
"O.K. I’ll start a new life, a new country and find Beckett that way. I’m in need of a change.",
"Then tell old friend Henry what it is that you know, and he will advise as to where you should go.",
"Well, I have this document that was for the other Beckett. It looks like it is part of a map.",
"Ah! yes my dear Captain a map it will be. If you find the parts missing, then whole it will be. It leads to vast treasure like you’ve not seen before. And the parts to complete are in total just four. Go find the man Rheims as you have been told, he has a map part, that leads to the gold. But be cautious dear captain all is not as it seems. Follow your head, not your heart, nor your dreams.",
"What! another riddle? Now it’s not just the poetry that playing with my mind. And what about the other Beckett.",
"One leads to the other dear Captain you’ll see. They both come together like the sky and the sea. The map it was torn into parts as you know, and those the parts carry, know where they must go. They would meet on an island theirs parts to put back but then they will find the thing that they lack.",
"What do they lack? I don’t understand. ",
"Don’t worry dear Captain, you’ve enough on your plate. Make haste to set sail before it’s too late.",
"Alright, alright. I’ll set sail for the pirate island.",
"Well, I have this document that was for the other Beckett but it seems to be in code.",
"Ah! yes my dear Captain a code to be sure, of a plan for invasion, for trading and more. Your Beckett you see has a plan to make good, the trade on these islands to be as it should. The nation he serves for trading does much, and to find more about it go talk to the Dutch. The Dutch have a company that trades far and near, and that trade my dear Captain they would bring to be here. ",
"So I will help the Dutch take over these islands?",
"Can’t I stop them?",
"The choice will be yours when your Beckett is met, on an island that’s Dutch and you’ve not got there yet.",
"Alright, alright I will look for Beckett on one of the Dutch islands.",
"Back again my dear Captain, and looking quite well. If you pay me 1,000 a secret I’ll tell.",
"A 1,000 in gold. You're getting greedy aren’t you Henry?",
"Oh Captain that’s cruel, Henry is on your side. This secret pays well but you can decide.",
"O.K. here’s you 1,000. This better be good or you’ll taste my sword.",
"Thank you kind Captain I’ll not make a quip. Go straight to the shipyard and sell them your ship.",
"Sell my ship! Are you mad as well as greedy?",
"No Captain, not so, when the Governor you meet. You’ll find Henry’s advice was really most sweet. But please don't forget when that business is done, to the shipyard and store and the tavern to run.",
"O.K. So I will go and sell my ship then see the Governor. This better work out well for me, or I'll be back!",
"Ah! Captain, again you need Henry's advice. If you have some spare cash, now that would be nice.",
"Henry, you really are a money grabbing old beggar! I'm broke and I've got no ship, just a leaky old Tartane.",
"My Captain your choices are few, as you will see, and as you're so poor I'll give give them for free.",
"Well, that's a surprise I must say. So what should I do?",
"There's a ship in the harbour that would fit you quite well. If you went there and stole it... well you never can tell. Or, Weatherby Swann is the Governor these days, you could go to him and see what he pays. Or, if your dream is to start life over anew, just walk round the town and enjoy the fine view.",
"O.K. I'll give the ship a try... There are two soldiers down there guarding it. I'll go and have a look.",
"Yes, you're right, I'm tired of all this running around. I'll go and see the governor, see what he has to offer. At least he pays well.",
"A good choice my Captain, this will lead to your dreams. Talk to those soldiers they will give you the means.",
"Thanks Henry, and I appreciate the 'no charge' this time!",
"Yes. I think I'll start all over and try to forget my past.",

};