string DLG_TEXT[96] = { 
"I'm told you've gone to great lengths to request an audience. My name is ",
". Now, if you please, tell me the purpose of your visit, ",
".",
"My name is ",
".",
"Ah, it's you again. What brings you here this time? ",
"I'd like to talk to you about some business.",
"I'm sorry, but there are things that I have to do.",
"So, why do you distract me from the very important affairs of state?",
"I'd like to talk to you about a small piece of business.",
"I'm just here to pay my respects, #saddr#. Nothing more.",
"In that case, please leave my study and let me get back to more important matters.",
"Yes, of course. Sorry I disturbed you.",
"I'm sorry, but I don't have anything to talk about right now",
"Oh yes? I have a proposition for you, captain.",
"Indeed?",
"I have learned that you completed the task successfully; my congratulations, captain! Here is your reward.",
"My thanks; It was a pleasure to aid you.",
"You must destroy the ",
" vessel ",
"quest pirate",
" menacing the shipping off ",
". If you sink her, I will reward you the hefty sum of ",
" gold. What say you, captain?",
"You shall not hear of her again, that I promise.",
"I'm afraid I can't help you.",
"I crave forgiveness, your Excellency.",
"I'm interested to learn about #sgov_nation# relations with other nations.",
"I'm looking for a Letter of Marque.",
"I've heard I'm up for promotion.",
"I can no longer serve ",
", your Excellency.",
"I'm through serving ",
"As insurance that you are an able captain, and to recompense my time in presenting your case to ",
", I must ask you for ",
" gold.",
"Not a chance.",
"Very well.",
"#sgov_nation# is always pleased to accept new captains into her service. ",
"We are currently at war with ",
"",
"no great power, but ",
". Of course, ",
"Pirates are always to be sunk on sight.",
" In light of your previous service, ",
" grants you the rank of ",
"I'll make you proud, your Excellency.",
"You have harmed ",
", and ",
" does not forget his enemies. Leave at once, or the guards will toss you out on your ear!",
"...",
"You have caused ",
" great harm, captain, but ",
" is willing to overlook your past transgressions... for a price: ",
"Very well, Sir. I accept.",
"A pleasure dealing with you, ",
"And you, your Excellency.",
"You are indeed! Excellent work. Your new rank is ",
". In addition, you are awarded ",
" acres of land by order of ",
"Thank you, Sir.",
"Are you sure, ",
" will be sorry to lose your service.",
"Yes, I am.",
" does not take kindly to turncoats, ",
"Uh, never mind.",
"Very well. But I hope you will reconsider, in time...",
"Goodbye, ",
"Huh?",
"Tough.",
"Well, I have a mission if you are interested.",
"Maybe. What is it exactly?",
"Two months ago a convoy of French merchant ships left #sisland_Falaise De Fleur# to sail for #sHavana#. My daughter, Justine, was on board one of the ships. The convoy never arrived. After one month I sent my best captain to search for her. But I have heard no news from 'La Foudre' since.",
"So you want me to search for both the frigate and the convoy? Why don't you send another ship of your own?",
"Unfortunately I don't have the military resources to spare another one of my ships. With #sFalaise De Fleur# being the only colony on #sisland_Falaise De Fleur#, I would be looked down upon by my people if I were to compromise the safety of the colony for a personal cause.",
"Very well, Sir. So now onto the things that matter. How much will you pay me if I bring back your daughter?",
"I can afford no more than 40000 gold coins.",
"That sounds pretty good to me. I accept your offer. Expect to hear from me soon.",
"I'm sorry, Governor, but I have to decline. I cannot spare the time required for such an endeavour.",
"Thank you ever so much! Please make finding my daughter your highest priority, captain.",
"I'll do my best, sir.",
"I understand, captain. Hopefuly I will find another privateer willing to do the job.",
"The best of luck, governor.",
"Thank God! You brought my daughter back!",
"Indeed Governor, but the pirate who kidnapped your daughter also came here!",
"An officer reported me the arrival of the pirate ship a few minutes ago. Please Captain help my soldiers to repel the enemy. While of the fight, I'm going to hide Justine in a secret room of the residence.",
"Wise decision Sir. I'm going to the fight right now! (THINKS: Hopefully I don't have to do much fighting though)",
"Congratulations Captain! you did a fantastic job.",
"Thank you sir, that was a dangerous mission.",
"Indeed! Justine spoke to me of Davy Jones. That Pirate seems to be the Devil. Fortunately, thanks to you, he won't soon come back.",
"I think so Governor. Now the mission is accomplished, I have other priorities but before we should talk about the reward, aye... savvy?",
"Of course. As agreed, here are the 40 000 gold coins! Thanks again and Goodbye Captain.",
"Goodbye Governor.",
"...",
"...",
"Some time ago a convoy of French merchant ships left #sisland_Falaise De Fleur# to sail for #sHavana#. My daughter, Justine, was on board one of the ships. The convoy never arrived. After one month I sent my best captain to search for her. But I have heard no news from 'La Foudre' since.",

};
