string DLG_TEXT[40] = {
"This may be the way to go.",
"hmm!",
"You've obviously just arrived Captain, and that is very fortunate, as I have been looking for someone like you.",
"Have you indeed? Tell me more.",
"I am not the usual rag-a-muffin you find in these waters. I have my own ship and enough gold to equip it.",
"Your point being?",
"I have information regarding the Treasure of Cortez and need a partner to help me get it.",
"The Treasure of Cortez - it seems just about everyone is after that.",
"Ah! Indeed Captain they are, but, they are all following scratches on bits of parchment.",
"You mean maps, I think.",
"Yes, yes, maps, but they are all wasting their time. The treasure cannot be found that way.",
"Indeed? And you know how it can be found?",
"Yes I do, but I need you to commit to join me first before I tell you.",
"I don't think so. I think I need to gain more experience before I set off on such an adventure.",
"Very well, I will commit to join you on your venture.",
"Goodbye then Captain.",
"Goodbye.",
"Excellent Captain. Do what you need to equip yourself and your ship then meet me back at the dock, and I will explain everything.",
"Very well, I will meet you at the dock shortly.",
"Glad to see you again, I can't wait to leave. Everyone else around here stinks of seaweed or sea bicuits!",
"Well, I'm ready to go. So what is the plan?",
"The Indians are the key. They already know where the treasure is.",
"So why don't they go and get it?",
"They don't want it. They are only interested in the crystal skulls which they use for their rituals.",
"Ah! you mean, we get the skulls, give them to the natives, and they tell us where the treasure is?",
"That's about it. Only I don't know how many and what colour.",
"How about two of each colour, Red, Blue and clear, to start with?",
"Yes. We can try that. We should work our way around the islands to find them. I have 5,000 in gold which I will put towards their purchase. We will have to live on out wits, and the money from prize ships, to get any more money.",
"Sounds fair. Let's set sail then and talk from time to time to see how many we have. Some of the merchants here may have some for sale.",
"Look if you wish. When we have enough we will sail for #sisland_Battle Rocks# to meet with the indians.",
"Let's get on with it then.",
"We need to keep our resources separatate in case we are attacked at sea. Give me the money, I will look after that, you will keep the treasure as we get it.",
"Very well.",
"Good. Now prepare to die captain. I have all I need, the game is over for you. I trapped you nicely, didn't I?",
"WHAT?",
"",
"",
"",
"",
"",
};