string DLG_TEXT[18] = {
"It's time we set sail.",
"Agreed.",
"Unless I'm mistaken, you're the captain we've been hoping to meet. Thank you for your help! If not for you, I'd be resting on the seabed with the rest of my crew.",
"Aye. I lost many good members of my own crew. After one of their broadsides, one of my men got hit with flying bits of wood in both arms and his eye.",
"Is he ok?",
"Larry lost both arms and his right eye, poor bloke. His sailing days are over. But why did you decide to drop anchor here? I have orders to escort you to #sIsla Muelle#.",
"I had to put a passenger ashore. I've got orders, too, you see.",
"I wasn't told anything about that - but fair enough. It's your business, not mine.",
"That's right, ",
". We each have our duties, and we don't need to discuss them.",
"Indeed. Can we depart now? I'd like to get you and your ship to safety as soon as possible.",
"Nothing's holding me here now.",
"Great! Let's waste no more time, then!",
"Aye captain!",
"We got all of them captain, you are free to escape.",
"What are you doing here?!",
"Returning the favour. I dropped off our Maltese friend and then saw that man and soldiers waiting for you outside the church. So I decided to follow and strike at a good time.",
"Thank you, my friend. It is greatly appreciated.",

};
