string DLG_TEXT[101] = {
"Let's keep going, Captain",
"Alright.",
"Oh! Captain ",
" I'm so pleased to meet you. I hope I've caught you in time!",
"Er.. I'm pleased to meet you too, but, in time for what?",
"Oh! Captain we can't talk here. Meet me on the beach in Gray Rock Bay. Be sure to come by ship.",
"Gray Rock Bay? Where's that?",
"As resourceful as you are, you'll find it Captain. Remember, come by ship.",
"By ship, Gray Rock Bay. What's this all about?",
"You'll see. I must go now.",
"Now just a minute, young lady... if you think I'm going to...",
"You made it then Captain ",
". I had a feeling you might not come.",
"Well, I'm here, so will you be kind enough to explain to me what is going on, and why everyone keeps disappearing?",
"Fair enough Captain, but I warn you, it gets complicated. My name is Susan Shaypen and I'm an Excise Agent working for the Crown.",
"An Excise Agent! Now that's a first for me. So what's your story then?",
"Miss Brin is really Miss Brinkley. She has kidnapped the real Miss Brin and hopes to get a large ransom for her, to help with her business.",
"Her business? I would have thought that kidnapping was enough of a business on its own. So what is this business?",
"Diamond smuggling. She begs, steals and borrows diamonds, which she then has shipped to the pirates and they buy them, making a handsome profit for our Miss Brinkley. I'm here to stop her, but I need your help.",
"Diamond smuggling Eh? A very profitable line of work. And, why would you be needing my help?",
"Because I don't have a ship at the moment, and you do.",
"Ah! I can see the logic in that.",
"Will you help me bring Miss Brinkley to justice and rescue Miss Brin? There will of course, be a large reward, if we are successful.",
"Yes, I will help you. I never did like kidnappers. [THINKS: And I DO like rewards, especially large ones.]",
"No, I don't think I can help you right now. [THINKS: If I rescue her on my own, I don't have to split the reward, and she did say it would be a large one.]",
"Thank you Captain, you will not regret it. We need to sail to #sTortuga#. It is a pirate island so we must change flags when we are out of sight of land.",
"Then to sea it is Miss Shaypen... er.. No! I don't mean you are misshapen.. er.. I mean.. er.. Miss Susan Shaypen.",
"Relax Captain. Just call me Susan, it's easier.",
"Yes perhaps it would be.",
"That's disapointing Captain, but I'm sure you have your reasons.",
"Er.. Yes, nothing personal, you understand.",
"Oh! Indeed I do Captain, but I'm afraid I must commandeer your ship. You will find a Tartane you can use in the port.",
"What? Huh? Wait a minute, you can't do that! You're an Excise Agent!",
"Let's just say it the tax due on those diamonds you have in your pocket. Nothing personal you understand.",
"Why you.. **!**!!!***!",
"Well, we're here. The Tavern is usually the best place for gossip, don't you think?",
"Yes, but I need to resupply the ship. So let's not forget that.",
"That narrows the search a little I think. It seems like she is headed for a pirate island.",
"Yes, it does. But which pirate island?",
"So Captain ",
", you decided not to come and meet me at Gray Rock.",
"I had a previous commitment, which I'm sure you are aware of.",
"Oh! Yes Captain, I am very much aware. Aware too, that you have turned pirate. And you, as a pirate, can only have one motive: easy money. A very unfortunate choice.",
"That Miss.. whatever your name is, was my choice. It is my motive that should be of more concern to you.",
"My name is Susan Shaypen and I'm an Excise Agent working for the Crown. MY motive is to stamp out piracy. And that... makes you my enemy!",
"An Excise Agent! That would never be my choice of work! But I suppose someone's got to do it.",
"Enough of this flippancy Captain. Surrender your sword, you are under arrest!",
"You DO know you are on a pirate island Miss Shaypen? You have no authority here, and I am sure no resources to call upon.",
"I have the authority of my sword, and am capable of taking you in on my own. Surrender now Captain, or die!",
"As you wish, but you could end up very misshapen.. Miss Shaypen. Draw your sword.",
", we meet again. You are obviously very resourceful to have found me here.",
"That’s as may be. But, we have the matter of you stealing my ship to resolve first.",
"Commandeer, Captain, I commandeered your ship. I am an Excise Agent working for the Crown, and as such, the business of the Crown overrides that of the individual.",
"Not this individual, it doesn’t. I shall be… re-commandeering my vessels forthwith.",
"Captain! I reiterate, I am working for the Crown and am in need of your ship. I will take all the necessary measures, and resources at my disposal, to retain it. I will even arrest you if you continue to interfere with my work here.",
"An Excise Agent! ... Well, I can't believe I'm going to say this, but it seems we are on the same side. I am working for the East India Company. Here are my papers.",
"Well, well, Captain. You surprise me yet again. So are you prepared to work with me now to rescue Miss Brin?",
"I think we could get some leverage out of that. [THINKS: And there is a reward.]",
"So what do you suggest we do next?",
"We should go to the Tavern. If there is any information floating about we will find it there.",
"Who is 'the Big Man'?",
"That's the pirate leader on this island. We need to go and see him. At least we know there's someone upstairs in that room.",
"WHAT! ...",
"Needs must, I'm afraid. --- [You give Susan a knowing wink unseen by Skull. --- She gives an imperceptible nod that she understands.]",
"What are you playing at? Two ships? How will that help?",
"Simple my dear Susan. When we get out to sea, we will sail for Bridgetown, not Jamaica. You sail ahead, once there, you will land first and hand over Miss Brinkley to the Prison Commander. Then you sell your ship, which was mine, if you remember, give me the money, and we part company. I return the Brin sisters to their father at #sRedmond#.",
"Oh! And you also just happen to collect the ransom money as well, I suppose?",
"Trust me my dear, trust me! This way your occupation as an Excise Agent remains a secret, so you can continue your 'good works' on the islands. The girls get safely home, and I can continue with my own affairs. Everybody wins!",
"I see. Well, that might just work, but you still haven't mentioned the ransom money, won't Skull be looking for that?",
"I won't ask for ransom. Shall we say.. I will rely on the Governor's.. generosity. Skull will be happy to be left alone to get on with his own business. Shh! He is coming back.",
"Miss Brinkley is in custody in the prison. She was not happy. Here is the money for your ship, less certain duty due to the crown, of course. I suppose that concludes our business for now?",
"AH! A nice day's work don't you think? We may meet again, you never know. But, for now I must deliver my charges to their father.",
"Don't think because you got us out of there that I think I owe you anything! I remember what you did to me!",
"Calm down woman! You don't know it, but I just saved your life!",
"What are you talking about! From what I hear some gold changed hands, that's all!",
"My dear Miss Shaypen... I was told there was only one sister here, and I was told that by the 'other' sister! Someone is trying to get me killed, and by association, you as well, savvy?",
"Oh! You mean Miss Brinkley and Mr. Brock? I knew about them a while back. That is why I wanted you to meet me at Gray Rock Bay.",
"You did! Hmmm! I need to get the Governor's daughter's home. Then I will pay them a visit. Now, we need to make sail as soon as we can. I suggest we part company once we are out to sea.",
"Very well, I will go back to Barbados and see what I can find out.",
"Good. I will go to Jamaica first, then I will catch up with you. Now let's get going.",
"I hope Bootstrap knows what he's doing. I'm pretty sure I saw that man come out of the cabin.",
"I'm sure he does, and anyway we need to find Billy Brock, so let's get going",
"I think we should split up again Captain. Brock doesn't know who I am, but he knows you, so I will have a better chance of finding him on my own.",
"Good idea. I'll look around anyway. I'll meet you in the shipyard later.",
"I met Governor Brin in the town and I saw you come in here, so I suggested to the Governor that we follow you.",
"That worked out just right. I killed Brock and the daughters seem to be fine.",
"That worked out well for the two of us. I am to join the Governor when he returns to #sisland_Redmond#.",
"Oh! So we part company then? In a funny sort of way I rather enjoyed working for the crown.",
"Yea! right! I somehow think you have a bit of the pirate in you. Anyway, here are I couple of things I found on Brock's body. You might as well have them, as being an agent of the crown, I can't keep them.",
"Thanks. Good luck with your promotion. You never know we might meet again.",
"Any luck Captain?",
"Not yet. I'm wondering if we should go across the island to #sGreenford#.",
"Well, if it helps, a sailor told me that a ship set sail for #sisland_Turks# Island last night, with some women passengers.",
"Hmmm... #sisland_Turks# Island. That is a pirate island, so it sort of makes sense. Perhaps we should go there.",
"What are you up to Captain? This isn't #sTortuga#! We need to get out of here fast and back to #sTortuga#!",
"Oh dear! Not one of my best days I'll admit. You're right, we should leave.",
"[THINKS: I see some leverage here...] Very noble, very noble indeed. Perhaps we should join forces after all.",
"Hello again Captain. I trust you delivered your charges without problem?",
"Yes thank you Susan... and how did you fare with Brock and Brinkley?",
"Brinkley is in prison. Brock, I'm afraid, died when we tried to arrest him. Which reminds me, here are some items I took off Brock's body, which you might find of use. I am recalled back to #sisland_Redmond#, so I will leave you now.",
"So it's goodbye, for the moment at least. Perhaps we will meet again. You never know.",
};