string DLG_TEXT[50] = { 
"I've got me ear to the ground Captain.",
"Good for you.",
"You might want to visit the tavern captain.",
"Alright. Thanks.",
"Have you heard the latest captain?",
"No. But I'm sure I'm about to.",
"They say the map to the treasure of Cortez has been found.",
"Really?",
"Yes, they say Barbossa found it. It's on some sort of secret island.", 
"Well, it can't be that secret if you know about it, now can it?",
"Captain! I'm trying to help you.",
"Alright then my dear fellow, go on.",
"I don't need your help right now. I'm very busy, savvy?",
"Well, they say he got drunk celebrating his good fortune and someone stole it from him. Tore it into four parts, he did, and hid them around the islands.",
"'They' know a lot, don't 'they'? So why don't 'they' go and get the treasure themselves, one might wonder?",
"Ah! Captain, they say Barbossa found out who it was that stole it, and had them killed.",
"After he had got them to tell him where they had hidden the parts, I trust?", 
"There's the rub captain. They say Barbossa was so angry, he had them killed before they told him.",
"Hmm.. Not very clever. Who is this Barbossa anyway?",
"He's a Pirate Lord. Well connected in pirate circles, he is.",
"Really? Well I think that's enough information for the moment. I've got business to attend to. See you again. Oh! And give my regards to 'They'.",
"Hello again captain, back so soon? I haven't heard anything new yet.",
"No, no, it's not that. I have a proposition for you. I need to find someone on #sisland_Isla Muelle#, and I think you might be just the man to find out where he is.",
"That doesn't sound too difficult. Why can't you do it yourself?",
"Because the man's a prisoner of the Spanish, and I think I could be recognised as working with the Company, what with my ship in port there and any loose chatter by the crew. If you do it, they won't take as much notice. I'll make it worth your while.",
"How much, worth my while? If he's a prisoner, then it's got to be the authorities that has him. Talking to the authorities can be tricky, if you know what I mean.",
"Shall we say 500 in gold? Half now, the rest of the lot when we get back.",
"We have a deal captain. Thomas'll find the man for you. You see if he don't. By the by, wear these clothes. You'll look less like a Company man. When do we leave?",
"Just tag along with me. I need to check the supplies for the ship. Changing clothes is a good idea. Here's the 250 in gold as first payment.",
"Hang on Captain, you'll miss the best part. I managed to get part of the map for you, here you are.",
"Why thank you, Thomas. Here's 100 pieces of gold for your trouble. Stay safe till we meet again.",
"Fancy meeting you here, Captain. Are you looking for someone?",
"Yes, I heard a ship arrived here recently from #sOxbay# and I need to know if a Billy Brock was on board.",
"That smuggler! The pirates here wouldn't put up with him. He's too crooked even to be a corkscrew. I'm afraid you've been misinformed Captain, he won't leave #sOxbay#.",
"You mean he's still there?",
"Well, we got here captain.", 
"Yes we did.",
"This place looks like a proper rabbit warren.",
"It does look busy, but I'm sure you'll ferret something out. We had better split up now. You go and see what you can find out. I'll do the same.",
"Aye, aye, captain. What's the plan then? For later I mean?",
"We will meet in the tavern later to compare notes.",
"I'm afraid so Captain. You'd be better off searching for him yourself this time and not listening to rumours.",
"O.K. Back to #sOxbay# it is.",
"",
"", 
"",
"Good to see you again captain. I heard that the Spanish Admiral in #sSanto Domingo# on #sisland_Hispaniola# has lost his son.",
"Thanks for the advice, Thomas.",
"Hang on Captain, I have yet to tell you the most important part. They say that the only way to find the island is with some strange Aztec compass, and to discover the treasure you need all the pieces of the map. Why this is, I don't know, your guess is as good as mine, Captain.",
"Thank you Thomas, that is very interesting. Here is 100 pieces of gold for your trouble. Stay safe and if you should happen to find out anything else let me know.",

};
