string DLG_TEXT[43] = {
"Let us not be too hasty Commodore, the man did save my daughter after all.",
"Yes Sir, an important point. Saving lives is a noble act.",
"Yes, Yes, we shouldn't be too rash. Put him in prison while I get my daughter to the residence so she may recover and change her clothes. We can always hang him tomorrow.",
"Not quite what I had in mind! ... I think it's time I was somewhere else! Just remember this as the day you almost caught Captain ",
"Ah! So this is the famous Captain ",
". Believe it or not we were just talking about you.",
"Indeed your excellency? Given the present company, I doubt it was a good conversation though.",
"Not so Captain. For all your faults you have the very skills we are in desperate need of at this time.",
"How so Sir?",
"The situation in Europe has taken a severe turn for the worse. The French have mustered a large fleet, and the intelligence is that they are planning to take over these islands.",
"Indeed sir, that is unsettling, but why would that involve me?",
"They intend to ally with the pirates to increase the pressure apon us, and with your past.. er history, if you are willing, you could help us thwart these endeavours.",
"Regarding my history, I feel that I have been greatly misunderstood, and I would like some assurance that my record will be expunged.",
"For my part your record is clear, and I will allow Sir Cutler Beckett to speak for himself.",
"I am all ears M'Lord.",
"Be quiet Captain Norrington. Let the man finish what he has to say. Go on, ",
"Thank you M'Lord. As Captain Norrington said, you cannot trust pirates, BUT, they can be trusted to trust each other, and as a pirate, I can command that trust.",
"Indeed, Captain ",
". And how, pray tell, would that be of benefit to us?",
"The French aren't stupid. They also believe the pirates cannot be trusted. They have bought a temporary alliance to allow them to re-supply their ships, that is all. And for a vast sum of money, I'll be bound. But knowing the French, that money will not be paid until the supplies have been loaded.",
"That is logical. But what of it? It still doesn't help our cause, and the defence of these islands.",
"Well M'Lord, all we have to do is to show the pirates that they will not get paid, and they will turn on the French, and we know that the French will turn on the pirates once they have what they need.",
"Go on Captain, this is starting to show some merit.",
"If I tell the pirates what the French are up to, then the pirates will attack the French fleet for us, leaving Norrington's squadron free to subdue the other French islands.",
"[To Will] On our return to Port Royal, I granted you clemency. And this is how you thank me? By throwing in your lot with him? He's a pirate!",
"[Will] And a good man. If all I have achieved here is that the hangman will earn two pairs of boots instead of one, so be it. At least my conscience will be clear.",
"Elizabeth... Elizabeth... wait!",
"You've lost her mate. Cupid's done his work.",
"And how would you execute this ruse to be sure of its success?",
"My plan would be this M'lord. I will sail to #sisland_Turks# Island and put the word around that I met the French fleet and they have given me the money to pay to the English, so they can re-supply their ships at English ports.",
"WHAT! But, what would that achieve?",
"By handing over the money, as proof you understand, I could get them to believe that the French are in fact coming to take over their islands, not the English ones, AND if Captain Norrington could accompany me as my first officer, that would indeed add even more credibility to the mission.",
"Hush Norrington! This plan indeed has merit. How much money would we need for this venture Captain?",
"I would suggest 300,000 in gold my Lord. You will save more than that in not having to put Norrington's ships to sea, plus keeping your fleet intact for more pressing matters.",
"A bold plan ",
". Very well, I will have the 300,000 delivered to your ship. When can you sail?",
"Ah! there is one other small matter.",
"And that is?",
"I do not have a ship at the moment that would be suitable for the journey, nor would it convey my stature as being able to represent the English.",
"Hmmm! Very well. Captain Norrington, provide the good Captain with a frigate and I think you should indeed sail with him as his first officer. Just to protect our investment you understand. And Sir Cutler, perhaps you would be kind enough to provide escort in the Interceptor until they are clear of our waters and have to raise the pirate flag.",
"Err... Thank you M'Lord, we will leave as soon as practicable.",
"41",
"42",

};