string DLG_TEXT[46] = { 
"Good Day to you Captain.",
"Good Day to you sir.",
"Who are you? I'll not give up without a fight.",
"Steady Lieutenant. I am Captain ",
". Sir Cutler sent me, we are here to rescue you.",
"Well, that's good news I must say. Let's go there's no reason to delay.",
"You're right we need to get away from here.",
"I am I glad to see you. Those bandits have been getting closer. Can we leave now?",
"Yes as soon as we're aboard it's #sRedmond# here we come.", 
"",
"",
"",
"",
"",
"",
"",
"", 
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"", 
"",
"",
"",
"",
"",
"",
"",
"",
"", 
"",
};
