string DLG_TEXT[71] = {
"Hola, ",
". Soy ",
"Ewan Glover",
"Ewan Glover",
", capitán del bergantín de guerra ligero 'Albion'",
"Es un placer conocerte, ",
"Ewan Glover",
".",
"El placer es mío, capitán. El propio Silehard me dijo que dejaste a los franceses sin pólvora ni balas de cañón. ¡Y con qué habilidad! No me importa decírtelo: me quedé impresionado.",
"Gracias, ",
"Ewan Glover",
", me halagas.",
"De nada. Estoy seguro de que pronto podremos hablar de nuestras aventuras con una jarra de cerveza en la mano. Pero ahora tenemos cosas que hacer.",
"¿Estás listo para zarpar?",
"Sí, pero, ",
", tu flota es demasiado grande y se supone que debemos pasar desapercibidos. Deja uno de tus navíos aquí en #sRedmond#, y me reuniré contigo cuando todo esté listo.",
"De acuerdo, ",
"Estoy listo para partir. Tan pronto como zarpes, te seguiré.",
"Fantástico. ¡Nos veremos en el mar!",
"Te esperaré en la taberna. Pregunta a ",
"Charles Windem",
" por mí.",
"Trato hecho. Te haré llamar.",
"Lo siento, ",
", pero tengo prisa. Tengo previsto zarpar pronto.",
"Claro, tienes razón. No te entretendré más.",
"Hola, ",
". Entonces, ¿hay sitio para mí?",
"Me temo que todavía no. Tendrás que esperar un poco más.",
"Nos estamos preparando para zarpar. ¿Estás listo?",
"Ya lo creo, aunque siento tener que abandonar este agradable puerto y su buen ron.",
"Pronto volveré.",
"Todo está preparado. Te veo en el puerto.",
"Luego te veo.",
"Debemos irnos. Quiero terminar con esto lo antes posible.",
"Yo también, así que zarpemos.",
"Vayamos a la taberna, ",
". La mejor forma de esperar a que caiga la noche es con una jarra de buena cerveza delante.",
"En eso tienes toda la razón. ¡Vamos allá!",
"Te alcanzaré después. Primero debo ocuparme de otros asuntos.",
"De acuerdo. Cuando termines, ven a la taberna. ¡Le diré al tabernero que caliente un poco de vino especiado para ti!",
"Qué amable. Volveré pronto.",
"¿Dónde está el tipo que se supone que debía reunirse con nosotros?",
"Quedémonos un rato por aquí. Seguramente llegará pronto.",
"...y aquella preciosidad me gritó: '¡A menos que te conviertas en un capitán respetable, no tienes nada que hacer conmigo!'",
"¿Y te hiciste capitán?",
"Sí. Sí, pero entretanto me di cuenta de que aquella mujer no significaba nada para mí, por muy encantadora que fuera. No me quería a mí: ¡quería gastarse el dinero de un capitán! Así que, ¿por qué iba a volver?",
"Tiene sentido.",
"Deberíamos ponernos en marcha pronto. ¡Ya ha oscurecido!",
"Por cierto, ¿has oído hablar de ese oficial estirado que utiliza la fragata del rey para usos personales?",
"¿De qué estás hablando?",
"Me encantaría oírlo, pero en otra ocasión. ¡Ahora vamos!",
"Hace poco, llegó a #sRedmond# una fragata desde Glasgow. Se supone que iba a ser el nuevo buque insignia de la escuadra de #sisland_Redmond#. En Londres pensaban que podrían surgir problemas en las colonias...",
"¿Y?",
"Entonces, cuando los franceses capturaron #sOxbay#, el capitán de la fragata recibió una orden secreta del gobernador Silehard\n ¡Al día siguiente, la fragata zarpó y el gobernador acabó teniendo que reclutar barcos civiles para enfrentarse a la flota francesa!",
"Interesante. Pero no hay ninguna razón para sospechar que actuó mal.",
"¿Que no? ¿La guerra estaba a punto de empezar y el gobernador envía al barco más potente de la flota a Dios sabe dónde? ¡A lo mejor tiene un trato con los franceses!",
"Supongo que te das cuenta de que esa es una acusación muy grave. Pero preguntaré a Silehard por la fragata.",
"Desde luego. Hazlo. Y dime qué te contesta. Me interesaría saberlo.",
"Lo haré. Y ahora atendamos nuestros negocios.",
"Por fin has llegado. Siéntate, por favor, ",
". Tu vino especiado viene de camino.",
"Gracias.",
"Mi trabajo aquí ha terminado. Vuelvo a #sRedmond#. ¿Quieres que naveguemos juntos? Es más seguro ir acompañado.",
"Me temo que no. Todavía no puedo irme.",
"Tienes otra misión que cumplir, ¿verdad? En ese caso, buena suerte, ",
".",
"Lo mismo digo. Ya nos veremos, ",
".",
"¡Eh! ¡Nos hemos perdido! Tenemos que llegar al puerto de #sGreenford#, no a esta playa dejada de la mano de Dios.",
"No nos hemos perdido. Tengo algunos asuntos que resolver aquí, y cuando haya terminado, te llevaré a #sGreenford#.",

};
