string DLG_TEXT[29] = {
"¿No tienes nadie más con quien sentarte a beber?",
"¿Eres  ",
"?",
"...Sí. ¿Cómo puedo ayudarte?",
"Counterspy",
" no podrá venir a la taberna.",
"¿Qué? ¿Por qué? ¿Quién eres?",
"Soy ",
". Tengo un mensaje de ",
"Counterspy",
".",
" Esto no estaba previsto. ¿Ha cambiado el trato? ¡Ordenaré su detención de inmediato!",
"No, espera, tuvimos problemas. Tuvimos que cambiar el lugar de encuentro.",
"Esto es terrible. ¡Podría ser una trampa! ¿Por qué me habré mezclado con él?",
"Parece que estás perdiendo los nervios.",
"¡No! ¡Oh, no! Dime, ¿qué mensaje te dio ",
"Counterspy",
" para mí?",
"Que está preparado y te espera detrás de la taberna. Cerca de la muralla de la ciudad.",
"¿Por qué no ha venido?",
"Hay soldados franceses por todas partes.",
"Ya veo... Así que supongo que quiere que le ayude a salir de la ciudad.",
"Sí. Cuanto antes mejor.",
"A qué esperamos. Vayámonos.",
"Venga, vamos.",
"¡Corre al barco! ¡Date prisa!",
"¡Tenemos problemas!",
"Vayamos al barco y zarpemos lo más aprisa posible. Si el viento es favorable, ¡nadie podrá alcanzarnos!",
"Envidio tu optimismo.",

};