string DLG_TEXT[140] = {
"Oh, lo siento, me temo que estoy muy ocupado para hablar en este momento. He tenido una nueva idea y estoy un poco distraido.",
"Suena bien. Pero ten cuidado y no nos vueles a todos por los aires.",
"¡Socorro! ¡Ayuda!",
"Aguanta. ¡Lo estoy intentando!",
"¡Ayuda! ¡Ayuda!",
"No, gracias, no arriesgaría mi vida por ti.",
"¡Oh, gracias! Muchas gracias, ",
", si no fuera por ti, esos mentecatos me habrían hecho pedazos.",
"No hay de qué.",
"Discúlpame, pero estoy trabajando en un experimento que requiere mi atención, así que debo despedirme. No pongas esa cara. Tengo un par de invitados muy agradables en mi casa. Creo que te gustará hablar con ellos.",
"Sí, será interesante conocer a tus invitados.",
"Me alegro de verte, ¿dónde está ",
"Danielle",
"?",
"Hum... Creía que #spronoun# ya estaba aquí.",
"¡Oh, no! ¿Qué te ha pasado, ",
"? No pareces tú..., mira tu ropa y esos golpes, ¡y estás como una sopa!",
"¡Déjame recuperar el aliento! Tráeme vino, me muero de sed.",
"Aquí está.",
"¿Eso es todo? ¡Si eso es un yate, yo soy el rey! ¡Eso no es más que una barca de pesca!",
"Eso es todo lo que puedo hacer por ti, ",
", y no te enfades.",
"Lo siento. Supongo que no tengo elección. Tendré que buscar a ",
"Danielle",
" con esta bañera.",
"Aquí está tu vino. Ahora, dime qué ha pasado.",
"Es una larga historia. ¿",
"Danielle",
" está aquí? No veo #spronoun3# barco.",
"No, todavía no ha llegado.",
"¡Maldición! Ese demonio de #sgirl# no puede quedarse en el mismo sitio ni un instante. ¡Y resulta que yo he perdido mi barco!",
"Hum... Tengo un pequeño yate. ¿Quizás te sirva?",
"¿Un yate? ¡Viejo zorro!, ¿por qué no me lo has dicho antes?",
"Bueno, es un yate muy pequeño...",
"Enséñamelo.",
"No, todavía no ha llegado.",
"¡Maldición! Ese demonio de #sgirl# no puede quedarse en el mismo sitio ni un instante. Tendré que encontrar#spronoun2#.",
"¡Claro que sí! ¡Te debo la vida! ¿Puedo saber cómo te llamas?",
"Me llamo ",
", soy capitán.",
"¡Qué interesante! Tengo un par de inventos que podrían instalarse en un barco\n Pero, ¿qué hacemos aquí de pie? Te estoy tan agradecido por haberme rescatado... Insisto en invitarte a mi casa, quiero recompensar tu amabilidad. Ven, ven.",
"De acuerdo, vayamos a echar un vistazo a tu casa. Pero no le hagas nada a mi barco.",
"Tenemos que volver al barco. Temo que la destrucción del templo pueda causar un terremoto, ¡o incluso algo peor! Los incas eran expertos en construir trampas elaboradas.",
"¿Trampas capaces de causar un terremoto? Suena bastante descabellado.",
"¡Sí, sí! Está bien, supongamos que no habrá ningún terremoto, pero las inscripciones en las paredes del templo advierten de un severo castigo que borrará de la faz de la Tierra a quellos que cometan sacrilegio.",
"El templo derrumbándose sobre nuestras cabezas me parece bastante severo. Probablemente, ese era el castigo. Deberíamos seguir intentando buscar el tesoro.",
"¡Capitán, no! ¡No hay tesoro en el mundo por el que merezca la pena perder la vida!",
"Bueno, el terreno parece un poco inestable ahora mismo, así que quizás deberíamos irnos y volver en otro momento. Si va a haber una erupción volcánica, no quiero estar aquí cuando ocurra.",
"Sí, supongo que no es mala idea...",
"#sPronoun_upper# podría haber esperado a la respuesta, por lo menos.",
"Sigamos su ejemplo, ",
". Yo iré por la derecha y tú, capitán, seguirás de frente. Si no te importa.",
"¿Qué diferencia hay? Solo intenta no perderte.",
"Lo dudo. Según las inscripciones, la trampa está junto a la entrada de la hornacina del dios solar. Parece que aquí es donde empieza el laberinto.",
"¿Laberinto?",
"Sí, laberinto. ¿No lo había mencionado? Para poder llegar hasta los tesoros, hay que atravesar el laberinto. Supongo que solo uno de estos pasadizos nos llevará hasta el final.",
"Creo que a los que crearon este templo les gustaban las bromas.",
"Tened cuidado en el tempo, amigos míos. En la tablilla está escrito que hay una trampa en la entrada a la hornacina del dios solar\n Por desgracia, no explica cómo evitar o desarmar la trampa, pero dice que las instrucciones pueden encontrarse dentro del templo.",
"Gracias por la advertencia. ¿Ya has terminado la traducción?",
"Sí, pero los papeles están mojados y arrugados. No he podido descifrarlo todo. Había una parte sobre la hornacina y un dios dormido. No creo que haya que prestarle mucha atención. Seguro que no es más que un cuento de los nativos.",
"¡Maldición! ¿Dónde están los tesoros?",
"Supongo que la entrada a la cámara del tesoro, o para ser más precisos, la cámara funeraria, está en la hornacina.",
"Adelante, pues.",
"Espera, el caso es que solo se puede entrar en el templo cuando lo ilumina la luz del sol. Es algún tipo de mecanismo complejo, no sé exactamente...",
"¿Ah, sí? En ese caso, tendremos que esperar a que salga el sol. Espero que la estación de lluvias no empiece hoy.",
"Si no recuerdo mal, íbamos a ir al templo.",
"Ah, sí, es cierto.",
"¡Oh, capitán ",
"! ¿Qué estás haciendo aquí? ¿También te han encarcelado?",
"No, amigo, he venido a rescatarte.",
"¿A rescatarme? ¿Cómo? ¡No creo que puedas convencer al guarda de que me suelte sin una orden del gobernador!",
"Ya lo he hablado con él, ",
".",
"¿Es eso cierto? Eres increíble, capitán, pero ¿por qué has venido de repente a ayudarme?",
"Si te digo la verdad, quiero que me hagas un favor a cambio.",
"Hum... Estoy dispuesto a hacerlo, aunque, ¿te importa que sigamos con esta conversación en otro sitio?",
"Desde luego. Vayamos al faro, te lo contaré todo de camino.",
"...¡Qué cosa más insensata e imprudente! No puedo creer que la gente sea capaz de eso...",
"Cada uno entiende la diversión a su manera.",
"Entonces, ¿quieres que traduzca el texto de este papel? Te interesa sobre todo la parte que describe cómo acceder al templo, ¿no es así?",
"Sí. Dijiste que conocías el idioma de los nativos.",
"Sí, sí... Pasé mucho tiempo estudiando a la población aborigen... y, ",
", si vas a lanzar una expedición para buscar ese templo, ¡navegaré contigo!",
"... ¿Por qué?",
"Sé por qué vas allí... y te aseguro que no me interesa el oro. ¡Quiero estar allí para verlo todo y tal vez hacer un descubrimiento importante!",
"Hum... No quiero que sufras las tribulaciones de un viaje por mar...",
"¡Qué tontería! Te juro, ",
", que si no aceptas llevarme contigo no traduciré ni una palabra de este texto.",
"Entonces, trato hecho. Te llevaremos con nosotros.",
"¡Fantástico! ¡Te lo agradezco muchísimo! En cuanto a la traducción, necesito tiempo. Creo que me llevará un par de días. El dialecto es bastante inusual.",
"Repararemos el barco y nos prepararemos para partir.",
"¡Vaya, si eres tú, capitán! Ya casi he terminado la traducción. Necesito una semana más y habré terminado.",
"No podemos esperar. ¿Por qué no sigues traduciendo durante el viaje?",
"Sí, es una buena idea, ¿por qué no? ¿Me dolerá la cabeza al navegar? Supongo que no... ¿Me marearé? No, no lo creo... Está bien. Pero, tengo curiosidad..., ¿a qué viene tanta prisa?",
"Supongo que la batalla en el puerto te pasó desapercibida y tal vez te lo debería explicar...",
"¿Batalla? ¿Qué batalla? ¡En qué puerto?",
"... El gobernador Silehard no va a regalarnos la colonia... y sospecho que tiene planes de colgarnos a la primera oportunidad.",
"¿Colgarnos? Ah, ya veo. Seguiré con mi trabajo durante el viaje. La verdad es que hemos tenido suerte de partir en esta época del año. Dicen que sólo se puede acceder a la bahía de #sisland_Khael Roa# dos veces al año.",
"¿Por qué no se pueden acercar los barcos a la isla en otras épocas del año?",
"Según el texto, hay un fenómeno natural que afecta a las mareas.",
"Igual por eso ",
"Raoul Rheims",
" no pudo entrar al templo.",
"Puede ser. Aunque también menciona otros peligros. Peligros que aguardan a quienes buscan el corazón del templo del dios del sol.",
"Sigue leyendo. Tienes los próximos días para investigarlo todo. Vayamos al barco.",
"Por cierto, capitán, necesitaré un camarote y sería de agradecer que estuviese hacia la popa para que las voces de la tripulación no me distraigan de mi trabajo.",
"De acuerdo. Tendrás tu camarote.",
"No tengáis prisa, amigos. Estamos en el umbral. Por aquí cerca debería estar la entrada secreta a la cámara funeraria.",
"¿Crees que deberíamos dar golpecitos en los muros?",
"En absoluto. Esas pinturas de los muros deberían indicarnos cómo encontrar la entrada a la cámara funeraria, así como avisarnos de las posibles trampas.",
"¿No hemos dejado atrás todos los peligros?",
"No, no lo creo. Los ingenieros nativos hicieron todo lo posible por proteger su templo. Estoy seguro de que todavía nos esperan muchos peligros\n En fin, pronto lo averiguaremos. Y ahora, dejadme pensar un momento.",
"Sí, por favor.",
"¡Ay, no! ¡No toques eso!",
"¿Qué sucede?",
"Es una trampa... ¡No, no! ¡Ya has tocado la piedra!",
"¡Oh, no! ¿Qué ha pasado?",
"¡Esta es la última trampa que dejaron los constructores del templo! ¡¿Por qué no has esperado?! ¡Podría haber leído las inscripciones para averiguar cómo evitarla, pero no, tenías que tocar algo!",
"Si es una trampa, ¿por qué seguimos vivos?",
"¡Si esperamos más, moriremos seguro! La trampa abre un canal que lleva el agua desde el lago de la montaña a las cuevas que hay bajo el templo\n La cámara del volcán que hay bajo el templo sigue activa, ¡así que te puedes imaginar lo que sucederá cuando el agua llegue a la lava hirviendo!",
"Hum. ¿Tú crees...? ¿Crees que las cosas podría poners eun poco complicadas?",
"¿Complicadas? ¡El vapor hará saltar el templo por los aires! ¡Debemos irnos!",
"¿Y qué hay del tesoro?",
"¡Olvídate del tesoro! ¡Tenemos que salir de aquí!",
"¿No hay forma de...?",
"Llévame a casa, captán. Por favor. Me temo que ya he tenido más avenutras de las que necesito a mi edad.",
"Tienes rtazón. Zarpemos.",
"¡Por favor, capitán! ¡Tenemos que irnos!",
"¡Está bien!",
"Bueno, capitán, ¡eso es lo que yo llamo una aventura!",
"Tienes razón, Clement. Me alegro de que todos hayamos salidos sanos y salvos.",
"Una pena que no podamos volver a entrar en el templo para estudiarlo y aprender más sobre ese pueblo perdido.",
"Yo siento que no pudiéramos quedarnos a buscar el oro, si es que existía.",
"Oh, creo que existe, capitán. Solo es cuestión de encontrar la forma de conseguirlo... Hum...",
"Clement, si alguien puede hacerlo, eres tú. Gracias otra vez por tu ayuda.",
"...",
"¿Clement?",
"¿Puedes levarme de vuelta a mi faro, por favor, ",
"? Tengo que estudiar todas las notas que he ido tomando.",
"Claro, Clement.",
};
