string DLG_TEXT[436] = {
"Preséntate, si eres tan amable. Creo que no nos conocemos.",
"Me llamo ",
", y soy capitán del ",
".",
"Capitán ",
". Confío en que tengas buena salud. ¿Y a qué se debe el honor de tu visita?",
"Hola, ",
", hola.  ¿Cuál es el motivo de tu visita?",
"Te escucho, ", // NK
". ¿De qué se trata?",
"Tengo unos asuntos que quería discutir.",
"Pensaba que quizás Su Excelencia tendría un trabajo para un capitán competente.",
"Sólo pasaba por aquí señor. Adiós",
"Bien, capitán ",
", veo en tu cara que tienes algo urgente que decirme.",
"Siento informar a Su Excelencia de que uno de las colonias de #sisland_Oxbay# ha sido atacada. La ciudad de #sOxbay# ha caído en manos enemigas, señor.",
"¿Has traído al prisionero? ¿Dónde está? Quiero verlo.",
"Lo siento, señor, no traigo buenas noticias. El prisionero escapó antes de que yo llegara a #sGreenford#.",
"¡Bueno, pues habla! Tienes mi atención, acabemos con esto cuanto antes.",
"Hablaremos de eso más tarde, señor.",
"Acabo de regresar de #sOxbay#, señor.",
"La misión está cumplida.",
"Pues en este momento no tengo nada para ti. Pero, si quieres, puedes preguntarme más tarde.",
"Tengo unos asuntos que quería discutir.",
"Solo era una visita de cortesía. Adiós, Excelencia.",
"De acuerdo, capitán ",
", pero antes de pedirme audiencia, deberías pensarte dos veces los temas que quieres tratar conmigo.",
"¿Tiene Su Excelencia trabajo para un capitán competente?",
"Sólo pasaba por aquí, señor. Adiós",
"Jajajaja, no seas tan humilde, capitán. ¡A lo mejor lo que quieres decir es que ellos empezaron primero!",
"Pues sí señor, así fue.",
"Bueno, en cualquier caso, será un placer darte tu recompensa por enfrentarte a los piratas.",
"Gracias señor. Hay algo que deberíamos discutir.",
"Gracias. Quería preguntar, si no es molestia, ¿tiene Su Excelencia trabajo para un capitán competente?",
"Muchas gracias, señor, por esta recompensa. Lamentablemente, tengo que irme. Adiós.",
" ",
"¡Cielos! Esta noticia es de lo más inquietante... ¿cómo es posible que haya piratas tan osados y bien organizados en estas aguas?\n ¡El capitán Tomlison me aseguró que su escuadra había apresado o hundido a los canallas más peligrosos de los alrededores!",
"Esa es la cuestión, señor. No eran piratas. Eran barcos franceses y tropas francesas.",
"¿¡Qué!? ¡Sabía que estaban desesperados, pero esto es un acto de guerra! Su Señoría, Carl, debería haber dado un disparo de advertencia hace tiempo ya\n Por favor, cuéntamelo todo. ¿Cómo conseguiste escapar? ¿Cuántos barcos, cuántos cañones, cuántos soldados? ¿De dónde venían?\n ¿Puedes afirmar con seguridad que los barcos pertenecían a la flota francesa?",
"Sin lugar a dudas, señor. Lo primero que advertí fueron las banderas francesas.",
"¡Esto es horrible, horrible! Soldados franceses ocupando suelo inglés, y apenas tenemos oro en las arcas de la colonia para enfrentarnos a una guerra abierta. ¿Cómo vamos a proteger nuestros hogares?\n Me temo, ",
", que esto te afectará a ti y a tu barco.",
"¿A mí? ¿Cómo?",
"... Estábamos hablando de la escuadra francesa, señor.",
"Hum. No me huele nada bien. Será mejor que me vaya, señor.",
"Verás, capitán, tras la campaña contra los piratas, sólo quedan dos barcos de guerra en activo, y son demasiado valiosos como para arriesgarlos en una misión de este tipo. En vista de lo que está ocurriendo, ordeno requisar y armar todos los barcos privados allá donde se necesite para defender nuestro territorio\n Lo lamento, capitán, pero tu barco no está exento de esta orden.",
"¿Qué? ¡No permitiré que requisen mi barco!",
"Ah, sí... sí... ¿Y qué tipo de barcos han utilizado para batir el fuerte? ¿Qué tipo de armas tenían? ¿Cuántos soldados?",
"Conté al menos tres o cuatro barcos: ",
"Te estimo mucho, ",
", pero, muy a mi pesar, no puedo dejarte marchar. Tengo que requisar tu barco para enfrentarnos a estos invasores.",
"Mis disculpas, señor, pero no he oído bien lo que Su Excelencia ha dicho...",
"Si te resistes, capitán, tendré que confiscar tu barco por la fuerza. Intenta comprender que no tengo alternativa.",
"Bien, entonces Su Excelencia me permitirá que le ofrezca una alternativa: mi barco y yo estamos al servicio de Su Excelencia.",
"¿Por la fuerza? ¡Adelante, inténtalo!",
"Tu información es de gran ayuda, capitán. Es una contrariedad, pues tu situación no es precisamente envidiable. Pero, de todos modos, tengo que decirte algo, ",
".",
"¿Decirme algo? ¿Por qué esto suena tan ominoso, señor?",
"Una excelente decisión, capitán ",
". Me alegro de haber encontrado una solución que nos complace a ambos. Y ahora, tu misión: me parece que, en lugar de entrar al servicio del ejército, sería mejor que\n trabajaras por tu cuenta.",
"¿Qué quiere decir Su Excelencia?",
"Por el momento, ignoraré tu insolencia, capitán. Pero ten en  cuenta con quién estás hablando, y no olvides que hay guardias al otro lado de la puerta. Permíteme que continúe...",
"En ese caso, me gustaría capitanear mi propio barco. ¡Ruego que se me permita ponerlo al servicio de Su Excelencia!",
"Al ser una cara nueva en estas aguas, mi esperanza es que tú seas la clave para conseguir más información sobre las fuerzas francesas\n Desde la colonia vecina en la isla, puedes atravesar la selva y penetrar en las murallas de la ciudad y, una vez allí, sacarles más información a los habitantes del lugar\n Quizás incluso puedas espiar las conversaciones de los soldados franceses.",
"¿Su Excelencia quiere que me cuele en la ciudad conquistada y descubra lo que los franceses planean hacer con la colonia?",
"¿Y qué pasa con mis honorarios, señor?",
"Sí... un plan muy audaz, lo admito. Si tiene éxito, quizás sabremos por dónde podría venir un nuevo ataque, y lo que es más importante, cómo liberar la colonia.",
"Lo comprendo. ¿Algo más, señor?",
"Por cierto, ¿podría recibir parte de mis honorarios por adelantado antes de emprender la misión?",
"Si necesitas dinero, capitán, aquí tienes 1.000 piezas de oro. Pero deberías gastártelas en preparar tu barco para el viaje. Recuerda que este dinero lo descontaré de tu recompensa final.",
"Gracias, señor.",
"Desgraciadamente, capitán ",
", no puedo pagarte por adelantado; debemos invertir nuestros fondos en la construcción de una escuadra y en preparar el fuerte para una posible campaña militar.",
"Qué inspirador.",
"Te aseguro, capitán, que se te compensará. Por ahora, te otorgaré una patente de corso para indicar, si fuera necesario, que estás trabajando en mi nombre. Pero no intentes engañarme. Si intentas evadir tus obligaciones\n, correré la voz de que practicas la piratería, y la escuadra del capitán Tomlison te pisará los talones hasta el fin de tus días, no encontrarás paz en todo el Caribe.",
"¡Si queda algo de la escuadra después de la batalla contra los franceses!",
"Ejem... Nuestra conversación se está desviando del tema. Recuerda: tu misión consiste en conseguir información sobre los planes que los franceses tienen para #sOxbay#\n Habla con los ciudadanos, visita la taberna; no dudo de que estará abierta e intacta, pues seguro que los franceses disfrutan de un pequeño descanso después de la batalla\n Haz todo lo que puedas para descubrir los planes del mando francés\n Créeme cuando te digo que esta vez seré muy generoso con mi recompensa. Buena suerte, ",
"Adiós, señor.",
"Escucha, ",
", considéralo un mal necesario. Al final, deberías dar las gracias por la suerte que tienes\n Trabajarás al servicio de la Corona, una posición a la que muchos aspiran. Además, ¡tengo fama de ser generoso con mis capitanes!",
"Espero poder ser testigo muy pronto de esa generosidad.",
"Enhorabuena por tu regreso, capitán. Por favor, preséntame tu informe.",
"Los ciudadanos de #sOxbay# no sienten mucho aprecio por sus conquistadores.",
"¿Y has conseguido descubrir dónde encaja esta invasión en los planes futuros de los franceses?",
"Están usando #sOxbay# como base para asaltar #sRedmond#. La escuadra fondeada en #sOxbay# está en espera de recibir municiones, que deben llegar desde #sisland_Falaise de Fleur# a bordo de un carguero. Una vez las tengan, zarparán para atacar #sRedmond#.",
"Esta información no tiene precio. Has demostrado tu valía. Gracias por tus servicios, ",
". Aquí tienes 3.000 piezas de oro.",
"Gracias, señor.",
"En vista de lo que me acabas de decir, tu próxima misión será asegurarte de que las municiones no llegan a #sOxbay#. Cuando tengamos que enfrentarnos a los franceses en batalla, cuanta menos pólvora tengan mejor.",
"¿Su Excelencia quiere que hunda el barco?",
"El método es cosa tuya, capitán. Abórdalo, húndelo... tú decides. Lo principal es que los franceses no consigan esas municiones. Tómate el tiempo que necesites para prepararte, ¡pero asegúrate de tener éxito!",
"¿Y qué pasa con su escolta? Podría ser demasiado para mi barco.",
"Sí, señor. Es vital que esas municiones no lleguen a #sOxbay#. Primero, me aseguraré de que estoy en condiciones de acometer la misión y luego zarparé rumbo a #sisland_Falaise de Fleur# para averiguar más, ",
".",
"¡En ese caso, quizás deberías pensar en hacerte con un barco más grande! Pero, ",
", quizás haya una forma de aprovecharnos de esto\n Como has demostrado que se te da bien meterte en terreno hostil y que sabes mantenerte alerta, deberías zarpar rumbo a #sFalaise de Fleur#. Con un poco de astucia y las preguntas adecuadas, quizás puedas encargarte de la nave escolta antes de que zarpe...",
"Lo dudo... pero lo puedo intentar.",
"Bien, ",
", pero no te olvides de dirigirte a mí como corresponde.",
"Los aventureros no estamos acostumbrados a todas estas formalidades...",
"Entonces recuerda que, cuando me sirves a mí, sirves a la Corona. No lo olvides, capitán.",
"Sí, señor.",
"Según tengo entendido, conseguiste dejar sin suminisros a la escuadra francesa.",
"Completamente, señor.",
"Después de que tú zarparas, envié otro capitán a #sisland_Oxbay#. Ella descubrió una gran cueva en la isla, cerca de una playa apartada\n Tengo la intención de desembarcar una guarnición de soldados y ocultarlos en esa cueva. Cuando estén en sus puestos, los utilizaré para liberar la ciudad, con un ataque coordinado desde tierra y mar.",
"Me parece un plan razonable, pero dudo que en mi barco haya espacio para un destacamento completo.",
"No será necesario, capitán. Ya me he encargado de eso. Tu misión será proteger al buque de transporte de tropas durante el viaje. El bergantón 'Albion', al mando del capitán ",
"Ewan Glover",
"Ewan Glover",
", está anclado en el puerto. ",
"Ewan Glover",
" te esperará a las puertas de la ciudad.",
"Ya veo. Entonces, supongo que debería ponerme en camino...",
"Espera, no he terminado. Tienes que escoltar al bergantín 'Albion' hasta el puerto de #sGreenford#, en #sisland_Oxbay#\n Uno de los vecinos, leal a la Corona, te indicará el camino hasta la cueva. Después volverás a infiltrarte en #sOxbay# y buscarás a uno de nuestros agentes que se encuentra oculto en la ciudad.",
"Son muchas cosas que recordar. ¿Qué tengo que hacer cuando encuentre al agente?",
"Él tiene información muy valiosa. Por eso tienes que hacer todo lo que puedas para asegurarte de que sobrevive y de que puede hacernos llegar la información.",
"¿Y el nombre del agente?",
"Counterspy",
". Tiene contactos entre los habitantes de la ciudad. Si no puedes encontrarle directamente, pregunta por él. Pero hazlo de forma discreta.",
"Como desee Su Excelencia. ¿Cuándo podré recibir los honorarios por mi última misión?",
"No te preocupes, ",
", aquí tienes tu oro.",
"Me alegro de oírlo, señor.",
"Y ahora vete, capitán. Quedo a la espera de tu próximo informe.",
"Adiós señor.",
"Bien, capitán ",
"..., creía que tenías más agallas. Pero lo hecho, hecho está. Por lo menos has cumplido con parte de la misión.",
"Pero...",
"Enhorabuena, capitán. No te puedes imaginar el alivio que es tenerte a mi servicio.",
"Gracias, señor",
"No me interesan tus explicaciones, capitán. He oído tu informe de boca de ",
"Counterspy",
" y me ha detallado lo que ha pasado. Estoy decepcionado porque, por culpa de tu fracaso, se derramará más sangre en la guerra.",
"Lo lamento, ",
", he hecho todo lo que he podido.",
"... Bien. Estas cosas pasan. Después de todo, hemos tenido la oportunidad de reconstruir nuestra escuadra.",
"Entonces, ¿cuál es mi siguiente misión?",
"Vas a unirse a nuestra escuadra en el asalto a #sOxbay#. No hace falta decir que tendrás que prepararte\n Espero que esto sea suficiente para ti. He descontado parte de tu paga por la pérdida del 'Albion'.",
"¿Cuándo zarparemos?",
"Pronto. De momento, haz lo que tengas que hacer en la ciudad, y cuando llegue el momento te avisarán. Relájate un poco y descansa. Todo capitán debería pasar una noche agradable en la taberna después de una larga singladura.",
"Pocas veces es así, aunque algo de verdad hay en ello.",
"Eso no importa. Mi mensajero te encontrará, Buena suerte, capitán.",
"Adiós.",
"counterspy",
" acaba de informarme de tus hazañas. Y ",
"Ewan Glover",
"Ewan Glover",
" parecía satisfecho tras haber navegado en tu compañía.",
"Emm... No sé a qué hazañas se refiere Su Excelencia.",
"Ja. Eres demasiado humilde. Toma tu recompensa. Sugiero que prepares tu barco para navegar. Tendrás que volver a zarpar muy pronto.",
"¿Y qué tipo de misión me espera esta vez?",
"El asedio de #sOxbay#. Te unirás a nuestra escuadra en la liberación de la isla.",
"¿Y cuándo va a zarpar la escuadra?",
"Pronto. De momento, haz lo que tengas que hacer en la ciudad, y cuando llegue el momento te avisarán. Relájate un poco y descansa. Todo capitán debería pasar una noche agradable en la taberna después de una larga singladura. Mandaré un mensajero en tu busca.",
"De acuerdo. Pues entonces me voy.",
"¡Ah! ¿¡Qué!? ¿¡Qué haces aquí!? ¿",
"? ¡¡¿",
"Danielle",
"?!!",
"Siento interrumpir tu sueño, querido gobernador, pero tenemos preguntas que necesitan respuesta.",
"¿Qué quieres decir? ¡Vete ahora mismo, y quizás te perdone la vida!",
"Creo que no entiendes bien tu posición, gobernador, ",
". Tú ya no eres el que da las órdenes. Y si se te ocurre siquiera pensar sin antes pedir permiso, entonces, ",
"Danielle",
", aquí presente, no tendrá más opción que poner en práctica sus elegantes técnicas de esgrima.",
"¡De acuerdo, de acuerdo, por favor! No hace falta ser tan extremista. Por supuesto que voy a responder a todas vuestras preguntas..., pero envaina tu espada, ",
"Danielle",
", por favor. ¡Controla a tu perro guardián! Su mirada me pone nervioso.",
"Cállate y escucha. Sabemos lo que te traes entre manos con el tesoro, y tienes muchas explicaciones que dar.",
"¡Por favor, malditos diablos, no me hagáis daño!",
"Bonito cumplido, pero, de momento, deberías empezar por decirnos lo que sabes sobre el ídolo que abre la puerta del palacio.",
"¡Canallas, no voy a contaros nada! ¡Guardias!",
"¡Oh no! ¡",
"Danielle",
"! ¡Volvamos a nuestros barcos!",
"¿Escapó? ¿Cómo ha podido pasar?",
"No me lo han explicado. Sólo me han dicho que todavía continúa la búsqueda del fugitivo.",
"¡Maldita sea! ¡Esta situación se está descontrolando!",
"Mis disculpas, señor, pero tengo buenas noticias.",
"Veamos lo que tienes que decir, ",
". No tengo todo el día.",
"He encontrado el rastro del capitán que traicionó la confianza de Su Excelencia, y a Inglaterra.",
"Raoul Rheims",
", ¿eh? Es cierto. No son las peores noticias que he recibido hoy.",
"Podría capturarlo, si Su Excelencia lo desea.",
"Por supuesto, que los vientos te sean favorables, ",
". Y, capitán... Esta vez, asegúrate de traerlo de vuelta. Y recuerda que, hasta que esté aquí, no deberá hablar con nadie, ni siquiera contigo. ¿Está claro?",
"Sí señor. Así se hará.",
", por fin. ¡Has estado fuera tanto tiempo, que empezaba a preocuparme por ti!",
"Estoy bien, y he cumplido la misión.",
"Para serte sincero, me sorprende. No esperaba que esta expedición me trajera resultados positivos\n Has podido recuperar la colección completa, ¿verdad?",
"Sí señor, excepto un ídolo. Un forastero lo compró.",
"¿Un ídolo? Vamos a ver qué es lo que falta.",
"Su Excelencia puede comproabarlo por sí mimso.",
"Es cierto, falta un ídolo, qué pena.",
"¿Debería ir a buscarlo, señor?",
"No, no te preocupes, ",
". Aunque agradezco tu disposición tan servicial. En vez de eso, tengo otra tarea para ti. Encontraré a otro que vaya en busca del ídolo\n Ah, sí, casi se me olvida. Aquí está el dinero que te prometí.",
"Gracias señor, tengo curiosidad por conocer mi próxima misión.",
"Sí, verás... poco antes de tu llegada, ",
", me informaron de que un pirata había sido capturado en #sGreenford#. Este pirata en particular siempre consigue escaparse de mis garras, y me ha causado muchos problemas\n Quiero que me traigas a ese pirata.",
"Parece bastante sencillo, señor. ¿Puedo irme?",
"Un momento, ",
". Valoro tu entusiasmo, pero eso no es todo.",
"Lo siento, señor.",
"Al llegar a #sGreenford#, habla con el comandante de la prisión, ",
"Greenford Prison Commendant",
"Greenford Prison Commendant",
"\n Enséñale esta carta y dejará al prisionero en libertad bajo tu custodia\n Cuando regreses, recibirás 5.000 piezas de oro.",
"Comprendido, señor.",
"Espero que hayas regresado porque has cumplido la misión y le has entregado la carta a su destinatario.",
"Sí, señor. Pero ha sido todo un reto. Los modales de los piratas dejan mucho que desear, pero Su Excelencia puede confiar en que tiene la carta.",
"Buen trabajo. Espero que la próxima misión se te dé igual de bien, ",
".",
"¿De qué se trata?",
"Relájate, no hay prisa, ",
". Primero, deja que te dé tu recompensa.",
"Gracias, señor. Es un placer trabajar para Su Excelencia.",
"Y tus halagos siempre son bienvenidos, ",
". Y ahora, hablemos de lo que nos ocupa.",
"Soy todo oídos, señor.",
"Tu próxima misión, ",
", es una cuestión un tanto personal para mí. Para un hombre de mi posición, sería poco ético utilizar las fuerzas imperiales para mis propios asuntos. Por eso me interesa mucho que seas tú quien se encargue de esto.",
"Me intriga la propuesta, señor. Mientras Su Excelencia no pretenda que me enfrente en solitario a la flota francesa...",
"Ya veo que te tomas las cosas con sentido del humor, ",
", pero no nos alejemos del tema que nos ocupa.",
"Lo siento, señor.",
"Hace varios días, un barco fue apresado por piratas, el '",
"pirate captain 06",
"', que se dirigía a Europa desde las Bahamas. Cuando estaba pasando cerca de nuestra colonia, los piratas atacaron\n Además de las mercancías habituales, llevaba a bordo varios ídolos de oro. Son unos tesoros incas excepcionales que había pedido para mi colección\n Conseguí descubrir el nombre del líder pirata que ordenó el asalto. Se llama ",
"Alistair Garcilaso",
"Alistair Garcilaso",
"\nDicen que él y su banda de carniceros y ladrones se esconden en la selva de #sisland_Douwesen#, pero no sé exactamente dónde\nNecesito que tú, ",
", los encuentres y te las apañes para recuperar mi colección\nSoy consciente de que no es la misión más fácil del mundo, y por eso te doy ahora 10.000 piezas de oro y te daré otra cantidad igual si cumples la misión con éxito\n Como te he dicho, no me gustaría utilizar a personal militar para mis asuntos personales. Y la mera idea de desembarcar tropas en #sisland_Douwesen#... No queremos arriesgarnos a tener conflictos con los holandeses\n Eres mi única esperanza.",
"Encontrar a hombres que no quieren ser encontrados no es exactamente una tarea fácil, pero creo que estaré a la altura, y esta es una suma ciertamente muy generosa.",
"Bueno, si lo logras habrá valido más que la pena, ",
". Pues, sin más dilación, aquí están tus honorarios. Buena suerte.",
"Regresaré en cuanto pueda, señor.",
"Has regresado, ",
", pero, ¿dónde está ",
"Raoul Rheims",
"? No veo que te acompañe.",
"He fracasado, señor, le perdí la pista en la guarida de los contrabandistas.",
"Me has decepcionado, ",
". Una misión tan sencilla, ¡¿y no has podido cumplirla?! Creía que tenías más agallas.",
"Mis disculpas, señor. Pero con el permiso de Su Excelencia, le diré que conseguí descubrir lo que planea ",
"Raoul Rheims",
". Va a emprender una expedición. Aquí está su diario, donde lo explica todo.",
"Bueno, no está en mi naturaleza castigar el fracaso, especialmente cuando el esfuerzo ha sido sincero. Pero espero que no fracases en tu próxima misión.",
"Gracias por la confianza, señor. Haré todo lo que esté en mis manos para no volver a defraudar a Su Excelencia.",
"De nada, ",
". Por cierto, aquí tienes las 5.000 piezas de oro que te prometí, aunque no te las mereces del todo.",
"Gracias, señor. La generosidad de Su Excelencia me abruma.",
"Bueno, ya basta, ",
". No hace falta que me adules. Ahora, vamos a hablar de negocios\n Tengo entendido que has ido a la base pirata\n Pues ahora que ya sabes dónde ir, necesito que tomes esta carta y se la lleves al jefe pirata. Responde al nombre de ",
"Isenbrandt Jurcksen",
"Isenbrandt Jurcksen",
"\n Antes de que te sorprendas, estoy seguro de que te intriga saber qué razón podría yo tener para comunicarme con ese diablo de mala calaña. Quizás recuerdes que ",
"Raoul Rheims",
" sabe demasiado y no puedo dejarlo escapar\n Si no consigues atraparlo, puede que los piratas lo hagan. ¿Cuándo vas a empezar tu viaje?",
"Mi barco está listo para zarpar, señor.",
"Perfecto. Entonces, zarpa inmediatamente. Cuando hayas cumplido con tu misión, vuelve a por tu recompensa. ¿Está todo claro, ",
"?",
"Sí, señor, zarparé inmediatamente.",
"Bien, nadie puede molestarnos.",
"Adelante, señor.",
"Primero, me gustaría compartir contigo una buena noticia: #sOxbay# es libre\n Nos has ayudado mucho para conseguir nuestra victoria. Gracias.",
"De nada. ¿Quizás Su Excelencia tiene algo nuevo para mí?",
"Por supuesto. ¡Quiero que me traigas a la persona que nos ha traicionado y ha puesto en peligro a la colonia! Se llama ",
"Raoul Rheims",
"Raoul Rheims",
".",
"Si no es indiscreción, ¿qué es lo que ha hecho?",
"¡Una naturaleza inquisitiva! Me gusta\n No te equivoque, Rheims es un vil traidor a la Corona. Y también ha traicionado a sus propios hombres. Estaba llevando a cabo una misión muy importante cuando cambió de bando\n Cuando uno de los miembros de su tripulación me advirtió de la traición de Rheims, casi logramos evitar esta calamidad\n Por desgracia, el pobre hombre ya estaba a las puertas de la muerte y no pudo decirme adónde se dirigía Rheims\n Sabemos que se detuvieron en el campamento pirata para abastecerse de provisiones\n Tienes que ir al campamento pirata y si ",
"Raoul Rheims",
" sigue allí, arrestarlo\n Si no está, descubre todo lo que puedas.",
"Comprendido. Pero enfrentarse a los piratas es algo peligroso. Espero que se me recompense bien.",
"Eso no lo dudes. Te pagaré 5.000 piezas de oro ahora y otras 5.000 cuando regreses con el traidor.",
"Un precio justo. Será mejor que me ponga en camino, señor.",
"¿Cómo es que estás libre? ¿Qué ha pasado? ¿Y los guardias?",
"Lo siento, pero me encarcelaron injustamente. No me iba a quedar ahí para siempre. Cuando recuperé mi arma, lo único que hice fue buscar mi libertad.",
"¡Lo siento muchíismo, ",
"! Ha habido un terrible error\n Mis soldados tenían órdenes de arrestar a un espía francés\n Te deben haber confundido con el espía.",
"Acepto las disculpas, señor. No sabía si alguna vez volvería a ser libre.",
"Aplaudo tu habilidad y tu astucia. Son dignas de ti, ¡pero el carcelero debe ser ahorcado por dejarte escapar!",
"Me temo que no queda nadie a quien colgar, señor. Ese asunto ya está arreglado.",
"El carcelero ya no es asunto mío. Y ahora, ¿sería Su Excelencia tan amable de explicarme por qué he acabado en prisión?",
"Señor, me gustaría hablar en su favor. Me ha dicho que en su día era muy hábil con los cañones. Yo necesito un buen condestable que dirija mi artillería, y, con el permiso de Su Excelencia, me gustaría enrolarlo.",
"Hum. Supongo que podría considerar ser indulgente, ",
", pero ese carcelero está al servicio de la colonia; no puedo dejar que se vaya sin más.",
"¿Cuánto dinero costaría sustituirlo, señor?",
"1.000 piezas de oro será suficiente.",
"Una buena oferta, señor. Acepto",
"Vaya. Es más de lo que esperaba. Será mejor que el carcelero siga al servicio de la colonia.",
"Llévatelo, pero podrías arrepentirte; he oído que es un borracho.",
"Tendré en cuenta la advertencia, señor. Y ahora, ¿sería Su Excelencia tan amable de explicarme por qué me han arrestado?",
"Tu sed de sangre es un poco excesiva, pero quizá es lo que hace falta en este mundo; nunca te dejarás doblegar por la compasión.",
"Eso espero, señor. Y ahora, si no es inconveniente, querría saber por qué me han arrestado.",
"Ha sido un terrible error. Un tremendo error. Mis soldados tenían órdenes de arrestar a un espía francés\n Mis agentes me aseguraron que justo en ese momento se encontraba en la taberna\n Resulta que ya se había marchado, y, por error, mis soldados te arrestaron a ti.",
"Bueno, un misterio menos. Su Excelencia podrá imagínar mi angustia cuando me vi en ese oscuro lugar.",
"Ha sido un terrible error. Un terrible error. Mis soldados tenían órdenes de arrestar a un espía francés\n Mis agentes me aseguraron que justo en ese momento se encontraba en la taberna\n Resulta que ya se había marchado, y, por error, mis soldados te arrestaron a ti.",
"Bueno, un misterio menos.",
"Y ahora que hemos terminado con estas bobadas, quiero que vengas conmigo a mi estudio\n Tengo importantes asuntos que discutir contigo.",
"Por supuesto, señor.",
"Por favor, acepta mis disculpas por las acciones de mis soldados\n Creo que este dinero te demostrará cuánto lamento el incidente.",
"Gracias, señor. Por mi parte, agradezco la amabilidad de Su Excelencia.",
"Deseo servir a Inglaterra, Excelencia.",
"#sgov_nation# siempre se complace en aceptar nuevos capitanes a su servicio. ",
"Estamos",
"..., mejor dicho, no estamos",
" en guerra con ",
"the ",
"ninguna nación",
". Por supuesto,",
", pero",
"los piratas siempre deben ser hundidos en cuanto sean avistados.",
"Haré que Su Excelencia se sienta orgulloso.",
"¿Cómo va mi carrera, señor?",
"Has hundido ",
" barcos enemigos, ",
" barcos piratas, en total ",
" barcos.",
"Gracias.",
"Espero que Su Excelencia no tenga queja de mis servicios.",
"¡Ya lo creo que no, captain! De hecho, e para mí un placer recompensarte con el rango de oficial de la Armada de su Majestad Británica. Como oficial, recibirás una recompensa por cada barco que hundas al servicio de Inglaterra.",
"Es un honor, Excelencia. Trataré de estar a la altura de la confianza que Su Majestad ha depositado en mí.",
"Me gustaría recoger mi paga, señor.",
"Mu bien, has hundido ",
" barcos enemigos, ",
" barcos piratas, ",
" barcos en total. Tu paga asciende a ",
", dando un total de ",
"Gracias, señor.",
"¡Escoria traidora! ¿Así que te dedicas a hundir los barcos de tus comptriotas? Por la presente, te expulso de la Armada con deshonor, tu nombre será borrado de los registros. ¡Y no quiero volver a ver tu cara en esta ciudad nunca más!",
"...",
" desde la última vez, aquí tienes ",
" piezas de oro",
"He oído que se me ha concedido un ascenso.",
"¡En efecto! Excelente trabajo. Tu nuevo rango es ",
"Gracias, señor.",
" barcos españoles, ",
" barcos holandeses, y ",
"¿Ah, sí? Tengo una proposición que hacerte, capitán.",
"¿De qué se trata?",
"Me he enterado de que has compeltado tu tarea con éxito. ¡Mis felicitaciones, capitán! Aquí está tu recompensa.",
"Gracias; ha sido un placer ayudar a Su Excelencia.",
"Debes destruir este barco: ",
" vessel ",
"",
", que amenaza el tráfico marítimo en aguas de ",
". Si lo hundes, te recompensaré con la considerable suma de ",
" piezas de oro. ¿Qué dices, capitán?",
"Prometo a Su Excelencia que no volverá a saber de ese barco.",
"Me temo que no puedo ayudar a Su Excelencia.",
"¡Ah, ",
", cuánto me alegro de verte! Soy ",
", enviado or Su Majestad para arrestar a Silehard y llevarlo de vuelta a Gran Bretaña; o, si fuera necesario, para encargarme de él de manera más... directa. Tú, ",
", has hecho mi tarea mucho más fácil.",
"Ha sido un placer, milord.",
"Ha sido un placer, milord. ¡De hecho, tengo una sorpresa para Su Excelencia!",
"Suplico el perdón, Excelencia.",
"Me interesa conocer las relaciones de #sgov_nation# con otras naciones.",
"Me interesaría adquirir una patente de corso.",
", qué alegría que vengas a visitarme. Me gustaría presentarte  a mi ",
". Se unirá a nosotros cuando hayamos concluido nuestros asuntos.",
"No puedo seguir sirviendo a ",
", Excelencia.",
"Me he hartado de servir a ",
"Como aval de tu aptitud como capitán, y para compensar el tiempo que voy a perder en presentar tu caso a ",
", debo pedirte ",
" piezas de oro.",
"Ni hablar.",
"Muy bien.",
" A la luz de tus servicios anteriores, ",
" te otorga el rango de ",
"Has dañado los intereses de ",
", y ",
" no olvida a sus enemigos. ¡Vete inmediatamente, o los guardias te echarán a patadas!",
"Has causado a ",
" un gran daño, capitán, pero ",
" está dispuesta a pasar por alto tus transgresiones pasadas... por un precio: ",
"Muy bien, Excelencia. Acepto.",
"Un placer tratar contigo, ",
"Y con Su Excelencia.",
". Además, se te concede un premio de ",
" acres de tierra por orden de ",
"¿Seguro, ",
" lamentará perder tus servicios.",
"Sí, seguro.",
" no ve con buenos ojos a los chaqueteros, ",
"Hum..., no he diho nada.",
"Muy bien. Pero espero que lo reconsideres, con tiempo...",
"Adiós, ",
"¿Eh?",
"¡Señor, avisté una flota francesa cerca de #sOxbay#!",
"¿Ah, sí? ¿Cuántos barcos? ¿Y qué estaban haciendo allí?",
"Hum... Lo siento, no sabría decirlo. Una terrible tormenta me arrastró a mar abierto antes de que pudiera investigar.",
"Una tormenta, ¿eh? Apuesto a quehuiste de los gabachos. En cualquier caso, sin detalles sobre las actividades de los franceses, tu supuesta información no es más que un rumor inútil.",
"Está bien, volveré con detalles. Quizás entonces, Su Excelencia me tome más en serio. Adiós, señor.",
"Bueno, a Su Majestad le apenará no poder encerrar a Silehard en la Torre de Londres. Pero este resultado es igual de definitivo. De hecho, es para mí un placer recompensarte por este servicio a Gran Bretaña con la considerable suma de 200.000 piezas de oro.",
"Cuánta generosidad, milord.",
"¿Ah, sí?",
"En efecto. He capturado a Silehard; mis hombres lo están trayendo aquí ahora mismo.",
"¡Oh, excelente! Su Majestad estará muy satisfecho. ¡Tan satisfecho que, sin duda, autorizará personalmente este desembolso de 400.000 piezas de oro como recompensa por semejante servicio!",
"Un servicio generoso merece una recompensa generosa, ",
"\n Su Majestad también ha considerado oportuno confiarme el gobierno de esta isla, sacándome de mi retiro; pero siempre estoy dispuesto a servir a Su Majestad y a Gran Bretaña. Pero estoy divagando. Desde ahora en adelante, yo seré tu intermediario con la Corona, quien te encomiende misiones y te recompense por tus servicios.",
"Será un honor servir a un hombre de la fama de Su Excelencia.",
"No me cabe duda de que Su Excelencia prosperará en este nuevo puesto; pero yo debo seguir mi camino.",
"Me halagas, ",
"\n Ahora, hablemos de tu posición. Las lamentables acciones de Silehard te forzaron a enemistarte con nuestro país; pero ",
" sabe que no fue tu culpa. ",
", por lo tanto, te permitirá reintegrarte en el servicio, manteniendo tu rango. Te doy la binevneida de nuevo, ",
"Tus hazañas han impresionado tanto a ",
" que me ha encomendado concederte con efecto inmediato una patente de corso.",
"Gracias, milord.",
"Primero, me gustaría compartir algunas buenas noticias: ¡#sOxbay# es libre. Nos has ayudado mucho par alcanzar la victoria. Gracias.",
"Se siente.",
"El resto de los barcos estaban ocultos por la bruma.",
" me ha informado de que rindió su ",
", que quedó bajo tu mando. Pero no veo ese barco en el puerto. ¿Dónde está?",
"Esto...",
"¿Estás intentando quedártelo para ti? ¿O lo has vendido? En cualquier caso, ese barco es propiedad de ",
". Me lo devolverás, o apresarás otro barco del mismo tipo. No regreses hasta que no tengas mi ",
" en estado de revista para entregármelo.",
"Muy bien, señor. Le conseguiré a Su Excelencia su ",
"¿Qué haces aquí todavía, ",
"? Ve y tráeme mi ",
"Lo siento, señor. Ya me iba.",
"Por cierto, ",
" me ha informado de que te hiciste con algunos barcos más de cmaino aquí. Tendrás que deshacerte de algunos de ellos antes de que tus barcos originales te puedan ser devueltos.",
"Muy bien, iré al astillero ahora mismo.",
"¿Y bien, ",
"? ¿Te has deshecho de tus barcos sobrantes?",
"Sí, señor.",
"Muy bien. Tus barcos originales quedan de nuevo bajo tu mando.",
"Y aún así, todavía tienes demasiados.",
};
