string DLG_TEXT[56] = {
"¿SÍ?",
"No, nada.",
"Hola. Creo que ",
"Danielle",
" te ha estado hablando de mí, ¿no?",
"Sí, claro, ",
". Me llamo ",
". Se podría decir que ",
"Danielle",
" y yo somos viejos amigos.",
"Por fin llegas.",
"¿Has localizado a ",
"Raoul Rheims",
"?",
"He oído que vosotros dos estáis buscado a la misma persona\n Resulta que sé dónde encontrarlo.",
"¿Sabes dónde está ",
"Raoul Rheims",
"? ¿Cómo?",
"Se podría decir que fuimos vecinos hace tiempo.",
"¿Puedes llevarme hasta él?",
"Por supuesto. En un abrir y cerrar de ojos.",
"Excelente...",
"¿Ves esa mesa al lado de la puerta? Ese es  ",
"Raoul Rheims",
". Sugiero que hables con él, antes de que desaparezca... Ahora, si me perdonas, tengo otros asuntos que atender.",
"Algo me dice que no me gustaría saber lo que estás tramando. De todas formas, gracias por tu ayuda. Vamos, hablaremos luego.",
"He oído hablar de vuestra relación.",
"Algunos temas es mejor mantenerlos en privado. Dime, ¿cómo encontraste a ",
"Raoul Rheims",
" y porqué has decidido ayudarnos?",
"Bueno, para ser exactos, no tengo interés en ayudarte a ti. Sólo estoy ayudando a ",
"Danielle",
" en este asunto.",
"Ya veo. Pero tengo curiosidad por Rheims, ¿cómo lo encontraste?",
"Lo que tú digas, ",
".",
"Por favor. Basta ya de confianzas. Ni siquiera sé si me puedo fiar de ti.",
"Danielle",
" tenía razón sobre ti. Eres demasiado suspicaz.",
"Lo que ",
"Danielle",
" piense o diga es asunto suyo. Pero yo necesito saber de qué conoces al hombre que estamos buscando y por qué decidiste ayudar a ",
"Danielle",
", ¡o te haré daño!",
"Está bien, está bien, cálmate. Conozco a ",
"Raoul Rheims",
" muy bien. Fuimos, por así decirlo, vecinos una temporada. En cuanto a ",
"Danielle",
", decidí ayudar#spronoun2# porque #spronoun# me ayudó una vez en una situación muy desagradable.",
"Convincente. Comprobaré esa información. Entonces, ¿dónde dijiste que se esconde ",
"Raoul Rheims",
"?",
"No lo dije. Debes hablar con ",
"Danielle",
" primero. A lo mejor, #spronoun# no quiere que vengas con nosotros.",
"Está bien. Se lo diré.",

};