string DLG_TEXT[28] = {
"¡Vaya, mira quién está aquí! ¡¡",
"!!",
"Disculpa, ¿te conozco?",
"¿Así que has terminado tu trabajo?",
"Sí, ya no te molestará más.",
"¡Perfecto!",
"Si necesitas algo más, estaré encantado de ayudarte.",
"Ah, sí, ya me acuerdo de ti. ¡Tú eres el único capitán que logró escapar cuando los franceses tomaron #sOxbay#!",
"Sí. ¿Cómo lo sabes?",
"Me lo dijo un pajarito.",
"Ya veo. Bueno, si me disculpas...",
"Espera, por favor. A juzgar por tu tono, no estás pasando buenos momentos. Quizá pueda ayudarte.",
"Depende. ¿Por qué me ayudarías?",
"Me gustaría pensar que en estos tiempos modernos aún se valora la amistad, la camaradería, los buenos modales, y no se recurre a la violencia para resolver los problemas. Desgraciadamente, no es el caso. Necesito acción, y quiero que me ayudes.",
"¿Y qué tendría que hacer?",
"Hay un tipo que entorpece mis negocios.",
"¿Y tú quieres librarte de él? ¿Por qué no lo haces?",
"Lo haría, pero vive en #sIsla Muelle#. Soy muy popular allí, me reconocerían.",
"Supongamos que acepto. ¿Qué obtendría a cambio?",
"Si te soy franco, no tengo mucho dinero que ofrecer. Mis ahorros están en otro lugar, guardados por alguien de confianza, pero...",
"¿Pero qué?",
"Tengo un barco excelente que podría darte.",
"Umm... Tentador. Creo que acepto el trato.",
"¡Fantástico! Entonces te daré el barco y tú te encargarás de  ",
"Sidonio Ogarrio",
"Sidonio Ogarrio",
" en #sIsla Muelle#. Vive en una pequeña plaza detrás de la taberna.",
"De acuerdo. Trato hecho.",

};
