string DLG_TEXT[28] = {
"¡Pero mira a quién veo! ",
"!!",
"Lo siento, ¿te conozco?",
"Entonces, ¿has completado tu tarea?",
"Sí, no te molestará más.",
"¡Perfecto!",
"Si necesitas algo más, estaré encantado de ayudarte.",
"Está bien, me acuerdo de ti. ¡Eres el capitán que logró escapar cuando los franceses capturaron #sOxbay#!",
"Sí. ¿Pero cómo lo supiste?",
"Un pajarito me lo dijo.",
"Ya veo. Bueno, si me disculpa...",
"Espere, por favor. A juzgar por su tono, ha visto días mejores. ¿Quizás pueda ayudarte?",
"Eso depende. ¿Por qué ibas a ayudarme?",
"Me encantaría creer que en estos tiempos modernos toda la gente sea amable, se lleve bien, cuide sus modales y no recurra a la violencia para resolver sus problemas. Por desgracia, no es así. Necesito acción, y quiero que me ayudes",
" ¿Qué tendría que hacer?",
"Hay un tipo que obstaculiza mi negocio.",
"¿Y quieres deshacerte de él? ¿Por qué no lo haces tú?",
"Lo haría, pero vive en #sIsla Muelle#. Allí soy muy conocido y me reconocerían.",
"Supongamos que estoy dispuesto. ¿Cuál será la recompensa?",
"Para ser sincero, no tengo mucho dinero que ofrecer. Todos mis ahorros están en otra parte, en manos de una persona de confianza, pero...",
"¿Pero qué?",
"Tengo un excelente barco que puedo ofrecerte.",
"Hmm... suena tentador. Supongo que tenemos un trato.",
"¡Genial! Entonces te daré el barco y te encargarás de ",
"Sidonio Ogarrio",
"Sidonio Ogarrio",
". Vive cerca de una pequeña plaza detrás de la taberna de #sIsla Muelle#.",
"De acuerdo. Acepto",
};