string DLG_TEXT[32] = {
", ilustre visitante. Soy ",
", propietario del astillero local.",
"Y yo soy ",
", capitбn del '",
".'",
", ",
". їNecesitas los servicios de mi astillero, ",
"?",
"Pues sн, necesito que tapes un par de agujeros en el casco y remiendes las velas.",
"Ahora mismo, solo quiero hablar contigo.",
"No, simplemente pasaba por aquн.",
"Bueno, estoy encantado de conocerte. Si eres capitбn, mi astillero estarб siempre a tu servicio.",
"Perfecto, ",
". Empecemos con esas reparaciones.",
"Te lo agradezco. Pero primero, quisiera hablar contigo.",
"Quizбs la prуxima vez. Ahora me tengo que ir.",
"їQuй te interesa saber exactamente, ",
"?",
"No, no lo creo.",
"Ya veo. їNecesitas algo mбs, ",
"?",
"Me gustarнa ponerle un par de parches a la vieja baсera que me ha traнdo aquн.",
"Gracias, eso es todo. ЎAdiуs!",
"їQuй necesitas exactamente?",
"Necesito reparar mi barco. Aunque podrнa considerar mandarlo al desguace y comprarme otro nuevo.",
"Necesito instalar nuevos caсones en mi barco.",
"Nada, muchas gracias.",
"Me niego a tratar con una persona con tu reputaciуn y relaciones. Mбrchate ahora mismo, ",
", antes de que llame a los guardias.",
"Muy bien.",
"Bien, mi muelle junto al fuerte estб disponible para ti. Si te parece bien, le dirй al capataz del muelle que remolque tu barco hasta allн. Solo entonces podrй analizar los daсos y decirte cuбnto tiempo y dinero costarб repararlo. ",
"їїMUELLE AL LADO DEL FUERTE?? Uhh... Acabo de recordar que tengo... eh... otros asuntos urgentes que debo atender primero. Adiуs.",

};
