string DLG_TEXT[58] = {
"Capitán, ¿tienes mercancías para comerciar, o tal vez sólo necesitas algunos objetos personales?",
"Enséñame lo que tienes para comerciar en mercancías, me gustaría ver tus precios.",
"Me gustaría comerciar con artículos personales, si los precios son buenos.",
"No vamos a hacer negocios hoy. Que tengas un buen día.",
"Saludos, ",
". Mi humilde tienda está a tu servicio.",
"Gracias. Me llamo ",
".",
"¡Albricias! Si es mi mejor cliente, ",
". Me alegro de verte. ¿Hacemos negocios?",
"¿Qué necesitas esta vez, capitán?",
"¡Ah, capitán! Dime, ¿qué puedo hacer por ti?",
"Veamos qué tienes.",
"Primero, me gustaría hablar contigo.",
"Que te vaya bien.",
"Es un placer conocerte, ",
". Soy ",
". Espero que esto sea el comienzo de una estrecha relación comercial.",
"Bien, ",
", veamos qué tienes para comerciar.",
"Me gustaría hablar contigo, ",
".",
"Que tengas un buen día.",
"Siempre es un placer hablar contigo, capitán.",
"Te escucho.",
"Me han pedido que te entregue un cargamento.",
"Por casualidad no necesitarás un capitán, ¿verdad? Tengo un barco excelente y puedo llevar cualquier cargamento a donde sea.",
"No tengo tiempo para hablar ahora.",
"No, no necesito tus servicios. Al menos mientras sigas hundiendo barcos de pabellón #snation_desc#.",
"En ese caso, adiós.",
"Lo siento, pero por ahora no tengo nada para ti.",
"Entonces procuraré volver más tarde.",
"Lo siento, pero tu barco no tiene la capacidad de carga suficiente para el encargo que tenía en mente.",
"Entonces procuraré volver más tarde.",
"¡Ah! Precisamente iba a pedirte que me hicieras un favor. Verás, necesito llevar un cargamento a ",
", y lo antes posible. Si consigues hacerlo antes de un mes, recibirás ",
" piezas de oro cuando llegues. ¿Qué te parece la oferta?",
"¡Me parece muy bien!",
"Me temo que no puedo aceptarla.",
"Ya te dije que hoy no tengo nada para ti.",
"Ah, es verdad. Lo siento.",
"Parece que te has acordado de tu misión un poco tarde, ¿no crees? Me llevaré las mercancías de todos modos, pero no esperes que te pague. ¡Presta más atención la próxima vez! Que tengas un buen día.",
"Por desgracia, me he demorado demasiado. Que te vaya bien.",
"¡Oh! He estado esperando este envío durante mucho tiempo. ¡Aquí está tu recompensa, joven ",
"!",
"Se agradece.",
"Como desees, ",
".",
"Veamos qué tienes por ahí.",
"Gracias por tu ayuda. Te veré pronto.",
"Por desgracia, ",
", los franceses han confiscado la munición y la mayor parte de mis mercancías, y me han prohibido vender el resto hasta que la guerra haya terminado.",
"¡Maldita sea mi suerte!",
"No me gusta tu reputación ni las compañías que frecuentas. Me niego a comerciar contigo. Márchate ahora mismo, ",
", antes de que llame a los guardias.",
"Muy bien.",
"Ah, sí. Estoy esperando una entrega de #squantity# quintales de #scargo#. ¿Lo tienes?",
"Umm... Parece que una parte del cargamento se ha extraviado. ¡No te preocupes, reemplazaré lo que se haya perdido y te lo traeré!",				 
};