string DLG_TEXT[56] = {
"?Tiene mercancia para comerciar, o solo necesita algunos articulos personales, capitan?",
"Muestrame lo que tienes para comerciar con mercancias, me gustaria ver tus precios.",
"Me gustaria comerciar con articulos personales, si los precios son buenos.",
"No vamos a comerciar en este momento. Te deseo un buen dia",
"Bien conocido",
". Mi humilde tienda esta a su servicio",
"Gracias, mi nombre es",
".",
"!Vaya, en verdad! Querida mia ",
". Encantado de verte. ?Hacemos un trueque?",
"?Que busca esta vez, capitan?",
"!Ah, capitan! Reza, ?que puedo hacer por ti?",
"Veamos lo que tienes",
"Primero, me gustaria hablar con usted.",
"Que te vaya bien",
"Encantado de conocerte",
". Yo soy",
". Espero que esto sea el comienzo de una relacion comercial fuerte",
"Bueno,",
", dejanos ver lo que tienes a cambio.",
"Me gustaria hablar con usted",
".",
"Buenos dias",
"Siempre es un placer charlar con usted, capitan",
"Estoy escuchando",
"Me pidieron que le entregara una carga.",
"?Necesita usted, por casualidad, un capitan, senor? Tengo un barco excelente, y puedo entregar cualquier carga, donde quieras.",
"No tengo tiempo para hablar ahora mismo.",
"No, no necesito tus servicios. Al menos mientras hundas barcos ingleses",
"En ese caso, que tenga un buen dia",
"Lo siento, pero no tengo nada para ti en este momento.",
"Me esforzare por volver mas tarde, entonces.",
"Lo siento, pero su nave no tiene la capacidad para la mision que tengo en mente.",
"Me esforzare por volver mas tarde, entonces.",
"!Oh! Iba a pedirte que me hicieras un favor. Vera, necesito que me entreguen un cargamento en ",
", y tan pronto como sea posible! Si consigues hacerlo en el plazo de un mes, recibiras ",
"oro cuando llegues! ?Que te parece esta oferta?",
"!Ciertamente me gusta!",
"Me temo que no puedo aceptarlo.",
"Ya te dije hoy que no tengo nada para ti.",
"Ah, que cierto. Le ruego me disculpe",
"Parece que has recordado un poco tu mision demasiado tarde, ?crees que no? Me llevare la mercancia de todos modos, pero no esperes que te pague. Presta mas atencion la proxima vez! Buenos dias.",
"Desgraciadamente, llegue tarde. Que te vaya bien",
"!Oh! !He estado esperandolo durante tanto tiempo! Aqui esta tu recompensa, joven",
"!",
"Siempre bienvenido",
"Como desees,",
".",
"Veamos lo que tienes a mano",
"Gracias por su ayuda. Te vere pronto",
"Ay,",
"Los franceses han confiscado la mayor parte de mis bienes y municiones, y me han prohibido vender el resto hasta que termine la guerra.",
"!Maldita sea mi suerte!",
"Me niego a comerciar con una persona de su reputacion y sus relaciones. Ahora vete,",
", antes de que llame a los guardias.",
"Muy bien.",

};