string DLG_TEXT[46] = {
"He visto tu pelea con nuestro capitбn. Segъn nuestra ley, ahora tъ eres nuestro capitбn y el barco te pertenece.",
"їDуnde puedo encontrarlo?",
"Estб cerca, en la bahнa de Playa de las Palmeras. Gira a la izquierda cuando salgas del pueblo y enseguida lo verбs.",
"ЎPerfecto! ЎConmigo aprenderйis lo que significa ser verdaderos lobos de mar, muchachos!",
"Ugh. Tъ debes ser ese capitбn del que hablaba Artois. Llegas tarde... Unghh... Si hubieras llegado cinco minutos antes, no tendrнa esta daga clavada en el pecho. Ungh...",
"ЎMaldita sea! ЎAlguien ha apuсalado a este chico!",
"ЎPiйrdete, escoria!",
"Serб un placer. Pero no hasta descubrir por quй uno de mis hombres estб tumbado inconsciente sobre la hierba, y en tu compaснa.",
"ЎЙste ha sido tu ъltimo error! ЎA por йl, muchachos!",
"ЎIntentadlo si os atrevйis, perros sarnosos!",
"Me temo que tu hombre no estб bien. Una bala le ha alcanzado el pulmуn y necesita un cirujano.",
"їY cuбnto me va a costar?",
"Bastante. Requiero 2000 monedas de oro por mis servicios.",
"Trato hecho. La vida de mi oficial es mбs importante que un poco de oro.",
"ЎCon esos precios, prefiero dejarlo morir!",
"Y una cosa mбs. Tu oficial estб delirando, dijo que los ataques podrнan continuar. Tardarб dos o tres semanas en recuperarse. їNo crees que deberнas poner a alguien para que le proteja durante este tiempo?",
"Hum... Pues sн, este no es el primer intento de ataque a Artois. Lo protegerй yo en persona.",
"ЎїDos semanas?! ЎNi hablar, yo me largo!",
"Lo siento capitбn, pero a partir de ahora ya no voy a navegar contigo. Tu sed de sangre es demasiado para mн. Adiуs.",
"ЎPiйrdete, escoria!",
"Estoy harto de navegar con un patйtico gusano como tъ. ЎYa encontrarй a alguien que sea lo bastante sanguinario!",
"ЎAllб tъ!",
"їQuй quieres?",
"Quiero que vengas conmigo en mis viajes.",
"De acuerdo, pero cuida de que no se repita el comportamiento que me hizo marcharme la ъltima vez.",
"Bien.",
"He oнdo que buscas trabajo.",
"Algo de eso hay. Y yo he oнdo que estбs buscando a alguien que guнe a tu barco.",
"Es cierto. Creo que eres justo la persona que estoy buscando. їTe gustarнa navegar conmigo?",
"їCuбnto me vas a pagar?",
"Necesito que me sigas hasta ",
" y te pagarй ",
" piezas de oro.",
"Acepto.",
"No puedo aceptar tu propuesta.",
"Gracias, tengo la sensaciуn de que mi destino estб en buenas manos. Toma tu dinero.",
"Gracias.",
", debo estar en un lugar llamado ",
", al ",
"Gracias por tu ayuda, capitбn. Me siento mucho mбs seguro con mi barco en tu compaснa.",
"De nada. Te llevarй a tu destino tan pronto como pueda.",
"Justo cuando pensaba que podrнamos llegar sin sobresaltos, Ўfuimos atacados! Gracias por defenderme. Creo que mereces una bonificaciуn en tu paga.",
"Muchas gracias. ЎAhora casi me alegro de que nos hayamos encontrado algo de oposiciуn en el camino! ЎJa, ja!",
"Vamos a entrar en aguas peligrosas. Para evitar que nos ataquen, izarй una bandera falsa.",
"ЎAh, gracias por decнrmelo! Me habrнa llevado un buen susto de haberlo visto sin saberlo de antemano.",
"ЎPodrнas asustarte y salir huyendo de mн! ЎO atacar mi barco! Mejor evitar esos malentendidos.",

};
