string DLG_TEXT[101] = {
"No desperdicies mi y tu tiempo, #ssir#, no tratamos con civiles aqui. La unica excepcion son los corsarios leales con una Carta de Marca",
"No podria probar mi lealtad y compromiso con el esfuerzo de guerra con una ... err ... contribucion financiera para usted ... err ... me refiero a la cresta de guerra de la Corona? Digamos que ...",
"Oro? No te molestes con un recibo, confio en que no guardes ni una moneda para ti mismo ... (WINK)",
"Pero TENGO UNA CARTA DE MARCA ...",
"Oye, ?ya no me conoces? Ya te pague antes",
"Mi, mi, pareces ser un hombre muy ocupado e importante. ?Cual es exactamente tu trabajo ... error ... deber?",
"Lastima ... Bueno, parece que tendre que visitar a esos asesinos en las afueras. Adios, amigos",
"Soy el Agente-Vicepresidente de la Estacion Naval de las Islas de Sotavento. La Junta de Victimas de la Armada me encargo que mantuviera al escuadron de las Islas de Sotavento en todo momento, por lo que no puedo escatimar una sola bala de canon para los civiles como usted. la excepcion son los corsarios leales con una Carta de marca, porque a su vez nos suministran tiendas capturadas. Aquellos pueden obtener viveres si me pagan ... err ... la Corona para ellos ",
"!Tu, #ssir#, no eres mas que un impostor! Tu relacion con la Corona NO es lo suficientemente buena como para una Carta de Marca. !Maestro de Armas, arresta a este tramposo!",
"Usted esta muy bien informado acerca de mis RELACIONES ... Bueno, las personas que saben demasiado deben ser asesinadas. Tal vez su sucesor sea menos entrometido ...",
"?De verdad? Bueno, a quien le importa, de todos modos es solo un trozo de papel. Sientase libre de comprar lo que nuestro almacen tiene en stock. Y si puede ahorrar cualquier suministro, la flota lo aceptara con gusto. La Junta de Vencedores le remitira el mercado habitual precio.",
"En efectivo, espero, y no en bonos del Estado ..",
"!Ah, ya veo! Bueno, entonces puede obtener tiendas de nuestro stock a precios bajos del gobierno. Y si puede ahorrar cualquier suministro, la flota con gusto lo tomara. La Junta de Vencimiento le remitira el precio habitual del mercado",
"Lo niego rotundamente, ?me escuchas, #ssir#? Porque eso hubiera sido un procedimiento irregular. !Nunca nos hemos visto antes! ?ENTIENDAS? (WINK)",
"!Oh no, no conmigo! Solo finges que no nos hemos visto antes para poder extorsionar a otro soborno ...",
"Ah, oh, si, entiendo. (WINK) Debo haberte confundido con otro oficial, pequena maravilla ... los uniformes me parecen igual. Un buen dia, querido senor",
"Los idiotas indiscretos deben ser silenciados .. !ALARMA! !ESTO ES UN SABOTEUR! #sGENDERSubj# TIENE UNA BOMBA, MATAR #sGENDERObj# EN EL PUNTO !!!",
"Esos jefes de bloque navales dificilmente creeran que un corsario acusa a su superior ...",
"!!SHHH !! Querido #ssir#, se mas discreto, !te lo ruego! La Junta de Vicevaluacion ya ha sospechado de mi ... Ah, no importa, pero si no te molesta, te concedere acceso a nuestra tiendas a bajos precios gubernamentales. Y si puede ahorrar cualquier suministro, la flota lo aceptara con gusto. La Junta de Vencimiento le remitira el precio de mercado habitual ",
"!Swell! Mira, con los argumentos correctos uno puede convencer incluso a los jefes de bloque navales ...",
"#ssir#, ?esta tratando de corromper a un oficial de la orgullosa Marina de Su Real Majestad? !Mi honor, no conmigo! !Maestro de armas, arreste a este vil villano!",
"Cientos de funcionarios corruptos aqui, y debo encontrarme con el unico justo. Bueno, tal vez tu reemplazo sea mas susceptible. !Porque te enviaran a casa pronto ... en un ataud lleno de ron!",
"!Ah, gracias ... erren ... en nombre de la Corona! !Ahora si eso no es una prueba de su lealtad ... Tales sujetos honestos merecen, por supuesto, el apoyo de todos los oficiales navales! Puede obtener tiendas de nuestras existencias a bajas tasas gubernamentales. Y si puede ahorrar cualquier suministro, la flota lo aceptara con gusto. La Junta de Vencimiento le remitira el precio de mercado habitual ",
"Mis disculpas capitan",
", No te reconoci en esta luz.",
"No hay problema. ?Podemos ponernos a trabajar?",
"Por supuesto, #ssir#, por supuesto. Nos dijeron que lo esperaramos",
"De veras? Y como se logro eso puedo preguntar?",
"Una fragata rapida llamo aqui hace aproximadamente un dia con una carta sobre usted de Sir Cutler Beckett. Por cierto, aqui hay un paquete de documentos que debe devolverle",
"Ciertamente tiene cosas bien organizadas, debo admitir. !Siempre parece estar un paso por delante de mi!",
"!Oh, si! No es un hombre con el que se pueda jugar. Pero para los negocios, su nave se cargara de inmediato, tenemos la lista de lo que se requiere. El pago de estos bienes ya se realizo. ?Necesita algo mas? ? ",
"Soy el capitan",
", de la East India Trading Company. Aqui estan mis papeles",
"Si, podria hacer con algunas tiendas",
"No, creo que he terminado",
"!Ah! Por supuesto, capitan, me alegro de verte otra vez. ?Quieres que te carguemos con carga o solo necesitas tiendas?",
"Si, llevame con carga. Tan rapido como puedas, estoy ansioso por meterme en el mar",
"No antes de que haya terminado, Capitan. Los botes alegres se estan yendo ahora. ?Sera todo este viaje o necesita algo mas?",
"Te gustaria ver lo que tengo en stock?",
"Claro. Vamos a echar un vistazo",
"Mas tarde. En este momento, necesito hablar.",
"En otro momento.",
"Vamos a hacer un trato o simplemente quiere comprar algunos suministros?",
"Quiero vender algunos bienes",
"Me gustaria comprar un poco de equipo",
"Nada, gracias. Adios!",
"De que quieres hablar?",
"Estoy escuchando.",
"Me pidieron que te entregara algo de carga",
"Podria necesitar un capitan, senor? Tengo un barco excelente, y puedo entregar cualquier carga, donde quiera",
"No tengo tiempo para hablar ahora",
"No, no necesito tus servicios. No mientras estes hundiendo barcos ingleses",
"En ese caso, adios",
"Lo siento, pero no tengo nada para ti en este momento",
"Volvere mas tarde, entonces.",
"Lo siento, pero su nave no es lo suficientemente grande como para que pueda hacer el trabajo que tengo en mente",
"Volvere mas tarde, entonces.",
"!Oh! Solo iba a pedirte que me hagas un favor. La cosa es que necesito que me entreguen algo de carga",
", y tan pronto como sea posible. Si logras hacerlo en un mes, recibiras",
"oro cuando llegas. ?Eso suena justo?",
"Definitivamente me gusta",
"No puedo aceptarlo",
"Ya te dije hoy que no tengo nada para ti",
"Oh, lo siento.",
"Recuerdas tu tarea un poco tarde, ?no crees? Tomare los bienes de todos modos, pero no esperes que te paguen. Presta mas atencion la proxima vez! Adios",
"Despedida.",
"!Oh! Lo he estado esperando durante mucho tiempo. Aqui esta tu recompensa, mi bien",
"Siempre bienvenido.",
"Bienvenido, ",
". ?Que puedo hacer por ti?",
"Estoy aqui para hacer una compra para mi barco",
"Soy el Agente-Vicepresidente de la Estacion Naval de las Islas de Sotavento. La Junta de Victimas de la Armada me encargo que mantuviera al escuadron de las Islas de Sotavento en todo momento. Como parte de ese escuadron, esta autorizado a aprovisionar su barco aqui . ",
"DLG_TEXT[72]",
"DLG_TEXT[73]",
"DLG_TEXT[74]",
"DLG_TEXT[75]",
"DLG_TEXT[76]",
"DLG_TEXT[77]",
"DLG_TEXT[78]",
"DLG_TEXT[79]",
"DLG_TEXT[80]",
"DLG_TEXT[81]",
"DLG_TEXT[82]",
"DLG_TEXT[83]",
"DLG_TEXT[84]",
"DLG_TEXT[85]",
"DLG_TEXT[86]",
"DLG_TEXT[87]",
"DLG_TEXT[88]",
"DLG_TEXT[89]",
"DLG_TEXT[90]",
"DLG_TEXT[91]",
"DLG_TEXT[92]",
"DLG_TEXT[93]",
"DLG_TEXT[94]",
"DLG_TEXT[95]",
"DLG_TEXT[96]",
"DLG_TEXT[97]",
"DLG_TEXT[98]",
"DLG_TEXT[99]",
"DLG_TEXT[100]",

};