string DLG_TEXT[29] = {
"ЎMuйvanse! ЎDespejen las calles!",
"...",
"ЎEh, tъ! Me parece que tienes una pinta muy sospechosa. їQuiйn demonios eres? ЎEnsйсame tus papeles!",
"їQuiйn demonios eres TЪ? ЎIdentifнcate, y hazlo rбpiso!",
"ЎAlto! Nunca te he visto antes, Ўpero tienes pinta de pirata! їPuedes demostrar que no lo eres?",
"Soy ",
", y aquн estбn mi comisiуn y los papeles del barco para demostrarlo. їEs eso lo bastante rбpido para tu considerable mal genio?",
"ЎOh, sн, por supuesto, seсor! Mi identificaciуn estб aquн, en esta bolsa, justo debajo de las 200 piezas de oro. *GUIСO*",
"Si no despareces de mi vista ahora mismo te enseсarй lo que es la rapidez... Ўcon mi espada!",
"ЎNo te atrevas a dirigirte a un superior en ese tono de nuevo, insolente esbirro! їNo sabes quiйn soy? ЎSoy el Inspector Real de los Regimientos Caribeсos de Su Majestad, y acabo de llegar en el ъltimo barco para supervisar nuestras tropas aquн! Ahora no me molestes mбs, Ўo tendrй que explicarle a tu comandante por quй he llegado tarde a mi cita con йl!",
"Ah, sн, la el cuсo de las monedas te identifica como una persona que se preocupa por el bienestar de los guardias mal pagados, je, je... De acuerdo, te dejarй pasar, pero sуlo por eta vez. ЎY mбs vale que te comportes!",
"ЎClaro que sн! їQuiйn crees que soy? їAlguna especie de truhбn? *GUIСO*",
"ЎNo me fнo de ti! ЎALARMA! ЎA MН LA GUARDIA!",
"Buen intento, canalla, Ўpero conmigo no funciona! ЎALARMA! ЎEspнa! ЎCorred la voz!",
"їQuй es esto? ЎALARMA! ЎPirata!",
" Parece que mis DESTREZAS son insuficientes para intentar ESE acercamiento. їO ha sido tan sуlo mala suerte? Bueno",
" Espero que mi esgrima tenga mбs йxito que mi charlatanerнa...",
"Dйjame ver... Bien, todo estб en orden. Siento haberte molestado, #ssir#, pero debemos estar muy atentos aquн. Este apostadero naval es un objetivo muy tentador para ladrones comunes, espнas enemigos y sabteadores. \nCon demasiada frecuencia, se las arreglan para colarse, a pesar de nuestros guardias en las puertas y la lнnea de costa. Debe haber algъn pasadizo secreto en algъn lugar...",
"No hay problema...",
"Bueno, ahora que nos hemos conocido, tal vez podrнas contarme algo sobre este puerto.",
"Pareces un tipo con experiencia naval, seguramente me puedes decir dуnde puedo obtener provisiones para mi barco.",
"Con mucho gusto, #ssir#. #sSt John's# no es un puerto cualquiera, sino una base naval, de hecho es una de las mбs importantes en el Caribe, debido a su estratйgica posiciуn cerca del paso principal entre las islas de Barlovento y de Sotavento, Ўy sus fortificaciones son inexpugnables! Incluso tenнamos un hospital aquн, justo al lado de la plaza de armas, pero ha sido trasladado a un lugar... mбs aislado.",
"Suena a que disfrutarй mi estancia aquн. Gracias por los consejos, adiуs.",
"Pareces un tipo con experiencia naval, seguramente me puedes decir dуnde puedo obtener provisiones para mi barco.",
"Bueno, la oficina del astillero naval estб al final del pantalбn. El gran edificio cerca del pantalбn es el almacйn del agente de avituallamiento. Encontrarбs al almirante del puerto y al capitбn del servicio de reclutamiento en la Casa del Almirantazgo, la mansiуn cerca de la plaza de armas.\nPero como #sSt John's# no es un puerto ordinario, sino una base naval, sus instalaciones estбn normalmente reservadas a barcos de nuestra Armada. Nuestros corsarios reciben servicios y suministros si pagan por ellos, pero otros barcos civiles no encontrarбn suministros o lugar donde hacer reparaciones aquн en el puerto. \nAunque he oнdo que algunos funcionarios navales pueden ser generosos contigo si tъ eres generoso con ellos, si sabes a lo que me refiero. Y como ъltimo recurso puedes recurrir a los mercaderes civiles en las afueras del puerto, y tal vez allн puedas enrolar a algunos hombres tambiйn. Pero ten cuidado, hay mucha escoria y gente de mal vivir por allн.",
"Me hace sentir de nuevo en casa... Gracias por los consejos, adiуs.",
"Interesante, їy puedes contarme algo mбs sobre este puerto en general?",
"Era demasiado peligroso tener todos esos enfermos aquн. Despuйs de todo, regimientos enteros murieron de fiebre en el viejo hospital. Sus ruinas todavнa permanecen allн, puesto que nadie quiere usar un sitio tan poco saludable. Algunos incluso dicen que el lugar estб encantado. \nEl puerto entero es un бrea militar, asн que encontrarбs pocos civiles aquн, Ўaparte de ladrones o saboteadores! Asн que mantйnte alerta por si ves algъn individuo sospechoso... Hablando de ladrones, hay un pequeсo asentamiento civil frente a las puertas de la estaciуn naval: un barrio de mala muerte con tabernas baratas donde van los marineros a que les roben y los embarquen a la fuerza, y mercaderes timadores que te revenden lo que los ladrones te acaban de robar...",
"Pero..., їy eso por quй?",

};
