string DLG_TEXT[52] = { //textfile for ccc buildingset
"No malgastes mi tiempo ni el tuyo, #ssir#, aquí no tratamos con civiles. La única excepción son los corsarios leales con patente de corso.",
"¿No podría probar mi lealtad y compromiso con el esfuerzo de guerra con una... contribución financiera para ti..., o sea, para las arcas militares de la Corona? Déjame ver... cuánto puedo permitirme... considerando el estado de mi cascarón... Digamos... ¿",
" piezas de oro? No te molestes con un recibo, confío en que no te guardarás ni una sola moneda para ti... (GUIÑO)",
"Pero yo TENGO una patente de corso...",
"¿Hey, no te acuerdas de mí? Ya te había pagado antes...",
"Oh vaya, pareces ser un hombre muy ocupado e importante. ¿Cuál es exactamente tu trabajo... esto... deber?",
" Qué lástima... Bueno, parece que mi carpintero tendrá que apañárselas para reparar mi barco por su cuenta. Adiós, oficial.",
"Soy el Comisario del Astillero Naval. La Junta Naval me ha enviado para supervisar a los oficiales principales del astillero. Tener un Astillero Naval aquí en el Caribe es de vital importancia porque, sin constantes reparaciones, nuestra escuadra de las Islas de Sotavento quedaría inutilizada por la podredumbre, los teredos y los huracanes.\n Los barcos se deterioran tan rápido en aguas tropicales que siempre estamos escasos de suministros y mano de obra. Así que debo pedirte que me dejes trabajar, no podemos prescindir de ninguno de nuestros recursos para buques civiles. La única excepción son los corsarios leales con una patente de corso, dado que a su vez nos proveen con suministros y buques apresados.",
"¡Tú, #ssir2#, no eres más que un fraude! Tu relación con la Corona NO es lo bastante buena como para tener una patente de corso. ¡Sargento, arreste a esta escoria!",
" Estás demasiado bien informado sobre mis relaciones... Bueno, la gente que sabe demasiado debe morir. Quizás tu sucesor sea menos entrometido...",
"¿De veras? Bueno, a quién le importa, de todos modos sólo es un trozo de papel. Bueno, acabo de recordar que el dique seco justo en frente de esta oficina ha quedado disponible esta misma mañana y no será ocupado hasta dentro de una semana. Deja tu barco allí, y daré órdenes al comandante del arseanl para que se encargue de carenarlo y reacondicionarlo. Después del horario oficial de trabajo, por supuesto.",
"Por supuesto. Conociendo el servicio público, apuesto a que tus trabajadores todavía tendrán energía suficiente después de su jornada normal...",
"¡Oh, ya veo! Bueno, acabo de recordar que el dique seco justo en frente de esta oficina ha quedado disponible esta misma mañana y no será ocupado hasta dentro de una semana. Deja tu barco allí, y pediré al comandante del arseanl que se encargue de carenarlo y reacondicionarlo. Solo tendrás que pagar ",
" piezas de oro por los materiales.",
"¡Eso es una ganga! Tendría que ser idiota para rechazar tal oferta.",
"Lo niego rotundamente, ¿me has oído, #ssir#? Porque eso habría sido un procedimiento irregular. ¡Nunca nos hemos visto antes! ¿LO ENTIENDES? (GUIÑO)",
"¡Oh no, conmigo eso no funciona! Sólo estás fingiendo que no nos hemos conocido antes para así poder sacarme otro soborno...",
"Ah, sí, ya entiendo. (GUIÑO) Debo haberte confundido con otro oficial, no es de extrañar..., esos uniformes me parecen todos iguales. Que tenga un buen día, señor.",
" Los idiotas indiscretos deben ser silenciados... ¡¡ALARMA!! ¡SABOTAJE! ¡¡¡TIENE UNA BOMBA, MÁTEN#sGENDERObj# INMEDIATAMENTE!!!",
" No creo que esos zoquetes de la Armada vayan a creer las acusaciones de un corsario contra su superior...",
"¡¡Chitón!! ¡Un poco de discreción, por favor! La Junta Naval ya sospecha de mis... ah, no importa. Pero, si no montas un escándalo, te daré acceso a un dique que ha quedado disponible esta misma mañana y no será ocupado hasta dentro de una semana. Deja tu barco allí, y daré órdenes al comandante del arseanl para que se encargue de carenarlo y reacondicionarlo. Después del horario oficial de trabajo, por supuesto.",
"¡Estupendo! ¿Ves? Con los argumentos adecuados uno puede convencer incluso a los zoquetes de la Armada...",
"Pero #ssir#, ¿estás intentando corromper a un oficial de la orgullosa Armada de Su Majestad? ¡Por mi honor, no seré yo ése! ¡Sargento, arreste a esta vil escoria!",
"Cientos de funcionarios corruptos, y tengo que encontrarme al único honrado... Bueno, puede que tu sustituto sea más razonable. Porque tú vas a volver a casa pronto... ¡en un ataúd de plomo lleno de ron!",
"Ah, gracias..., ¡en nombre de la Corona! Si eso no es una prueba de tu lealtad... ¡Personas tan honradas merecen, por supuesto, el apoyo de cualquier funcionario naval! Bueno, acabo de recordar que el dique seco justo en frente de esta oficina ha quedado disponible esta misma mañana y no será ocupado hasta dentro de una semana. Deja tu barco allí, y pediré al comandante del arseanl que se encargue de carenarlo y reacondicionarlo. Después del horario oficial de trabajo, por supuesto.",
"Ah, capitán, estás al mando del East Indiaman que he visto en el puerto. ¿Estoy en lo cierto?",
"Sí, señor, así es, aquí están mis papeles. Necesito algunas reparaciones.",
"Sí, sí... ¡Firmado por el propio Lord Beckett! Todo está en orden. Lleva tu barco al dique seco en el puerto. Empezaremos a trabajar inmediatamente. Voy a cargar los costes a la cuenta del Almirantazgo.",
"Muchas gracias, señor, muchas gracias. A su señoría le alegrará oírlo.",
"Buenos días, ",
". ¿Qué asuntos te traen por aquí?",
"Mi barco ha sufrido algunos daños. Quiero que sea reparado.",
"Por supuesto, #ssir#. Si llevas tu barco a nuestro muelle, daré órdenes al comandante del arseanl para que se encargue de carenarlo y reacondicionarlo. Solo tendrás que pagar ",
"Gracias. Dejaré mi barco en las hábiles manos de tu comandante del arsenal inmediatamente.",
"Solo estoy echando un vistazo por el puerto. Buenos días.",
"Soy el Comisario del Astillero Naval. La Junta Naval me ha enviado para supervisar a los oficiales principales del astillero.  Tener un Astillero Naval aquí en el Caribe es de vital importancia porque sin constantes reparaciones nuestra escuadra de las Islas de Sotavento quedaría inutilizada por la podredumbre, los teredos y los huracanes.\nEsto, por supuesto, incluye tu barco. Si ha sufrido daños por las acciones del enemigo, o por una tormenta, podemos repararlo y dejarlo completamente preparado para la batalla.",
"DLG_TEXT[36]",
"DLG_TEXT[37]",
"DLG_TEXT[38]",
"DLG_TEXT[39]",
"DLG_TEXT[40]",
"DLG_TEXT[41]",
"DLG_TEXT[42]",
"DLG_TEXT[43]",
"DLG_TEXT[44]",
"DLG_TEXT[45]",
"DLG_TEXT[46]",
"DLG_TEXT[47]",
"DLG_TEXT[48]",
"DLG_TEXT[49]",
"DLG_TEXT[50]",
"DLG_TEXT[51]",

};