string DLG_TEXT[52] = { //textfile for ccc buildingset
"No malgastes mi tiempo y el tuyo, #ssir#, aqui no tratamos con civiles. La unica excepcion son los corsarios leales con una Carta de marca.",
"No podria probar mi lealtad y compromiso con el esfuerzo de guerra con a.. err.. contribucion financiera a usted.. err.. Quiero decir, ?la mejor de la Corona? Dejame ver.. ?Cuanto puedo ahorrar.. considerando el estado de mi Banera.. Digamos.. ",
"?Oro? No te molestes con un recibo, confio en que no guardaras una sola moneda para TI..(WINK)",
"Pero TENGO una carta de la Marca..",
"Oye, ?ya no me conoces? Ya te pague antes..",
"Vaya, vaya, parece ser un hombre muy ocupado e importante. Cual es exactamente tu trabajo.. err.. deber?",
" Lastima.. Bueno, parece que mi carpintero tendra que reparar mi barco por su cuenta. Adios, brasshead.",
"Soy el Comisionado del Astillero Naval. La Junta de la Marina me envio para supervisar a los oficiales principales del patio. Tener un astillero Naval aqui en el Caribe es de vital importancia porque sin una constante reparacion nuestro escuadron de islas de Sotavento pronto estaria inmovilizado por la putrefaccion, el gusano Taredo y los danos de los Huracanes.\n naves de Vela decaen tan estrategia en aguas tropicales que siempre estamos cortos de tiendas y mano de obra. Asi que debo pedirle que me deje en paz ahora, no podemos escatimar ninguno de nuestros recursos para naves civiles. La unica excepcion son los corsarios leales con una Carta de Marca, ya que a su vez nos suministran con las tiendas capturadas y prizeships.",
"!Tu, #ssir2#, no eres mas que un impostor! Su relacion con la Corona no es lo suficientemente buena para Una carta de marca. !Maestro de Armas, arresta a este tramposo!",
"Estas demasiado bien informado sobre mis relaciones.. Bueno, la gente que sabe demasiado debe ser asesinada. Tal vez tu trineo sea menos ruidoso..",
"?En serio? Bueno, a quien le importa, es solo un trozo de papel de todos modos. Bueno, acabo de decir que el drydock justo en frente de esta oficina ha quedado vacante esta misma manana y no estara ocupado durante una semana. Ponga su nave ahi, y le pedire al Maestro Asistente que la cargue y la preparadas. Despues de las horas normales de trabajo, por supuesto.",
" Por supuesto. Conociendo el Servicio publico apuesto a que sus trabajadores tendran suficiente energia despues de su trabajo oficial..",
"!Ah, ya veo! Bueno, acabo de recordar que el muelle ha quedado vacante esta misma manana y no estara ocupado durante una semana. Ponga su nave ahi, y le pedire al Maestro Asistente que la cargue y la preparadas. Solo tendras que pagar. ",
"para el material.",
"!Ahora si eso no es una ganga! Seria tonto si rechazara una oferta asi.",
"Lo niego rotundamente, ?me oyes, #ssir#? Porque eso habria sido un procedimiento irregular. Nunca hemos visto antes! ?ENTENDEIS? (GUINO)",
"Oh, no, no conmigo! Finge que no nos hemos visto antes para que puedas extorsionar otro soborno...",
"Ah, si, lo acto. Debe haberte confundido con otro oficial, pequena maravilla.. esos uniformes me parecen iguales. Un buen dia para usted, querido Senor.",
"Los idiotas indiscretos deben ser silenciados.. !ALARMA!! !ES UN SABOTEADOR! #sGENDERSubj# tiene una BOMBA, MATA a sGENDERObj en el entiendo!!!",
"Esos Blockheads navales dificilmente creeran a un corsario acusando a su superior..",
"!SHHH!! Querido #ssir2#, se mas discreto, te lo ruego! La Junta de la Marina ya sospecha de mi.. Ah, no importa, pero si no haces un escandalo te concedere el acceso a un muelle que ha quedado vacante esta misma manana y no estara ocupado durante una semana. Ponga su nave ahi, y le pedire al Maestro Asistente que la cargue y la preparadas. Despues de las horas normales de trabajo, por supuesto.",
"!Estupendo! Mira, con los argumentos correctos uno puede convencer incluso a los Blockheads navales..",
"#ssir#, ?estas tratando de corromper a un oficial de la orgullosa Armada de su Majestad? Mi honor, no conmigo! !Maestro de Armas, arreste a este vil villano!",
"Cientos de funcionarios corruptos aqui, y debo conocer al unico justo.. Bueno, tal vez tu reemplazo sea mas susceptible. Porque seras enviado a casa pronto.. !en un leadcoffin lleno de Ron!",
"Ah, gracias.. err.. en nombre de la Corona! Ahora si eso no es una prueba de su lealtad.. !Tales temas honestos merecen por supuesto el apoyo de cada oficial Naval! Bueno, acabo de decir que el muelle ha quedado vacante esta misma manana y no estara ocupado durante una semana. Ponga su nave ahi, y le pedire al Maestro Asistente que la cargue y la preparadas. Despues de las horas normales de trabajo, por supuesto.",
"Ah capitan, usted es del hombre de las Indias orientales que vi en el puerto. ?Confio en que estoy en lo cierto?",
" Si, Senor, como de costumbre, aqui estan mis papeles. Necesito algunas reparaciones.",
"Si, si. !Firmado por Lord Beckett! Todo esta en orden. Lleva tu nave al drydock en el puerto. Empezaremos a trabajar de inmediato. Cargare los costos a la cuenta del Almirantazgo.",
"Muy agradecido senor, muy agradecido. Transmitire una buena noticia sobre usted a su Senoria.",
"Buen dia, ",
". ?Cual es su negocio aqui?",
"Mi nave ha sufrido algunos danos. Deseo que sea reparado.",
"Ciertamente, #ssir#. Si mueve su nave a nuestro muelle, le pedire al maestro Asistente que la cargue y la preparadas. Solo tendras que pagar. ",
"Agradecer. Pondre mi nave en las capaces manos de Su maestro Asistente de inmediato.",
"Solo estoy mirando alrededor de este puerto. Buenas tardes.",
"Soy el Comisionado del Astillero Naval. La Junta de la Marina me envio para supervisar a los oficiales principales del patio. Tener un astillero Naval aqui en el Caribe es de vital importancia porque sin una constante reparacion nuestro escuadron de islas de Sotavento pronto estaria inmovilizado por la putrefaccion, el gusano Taredo y los danos de los Huracanes.esto, por supuesto, incluye su nave. Si ha sido danada por una accion enemiga o por una tormenta, podemos repararla a plena capacidad de combate.",
"DLG_TEXT[36]",
"DLG_TEXT[37]",
"DLG_TEXT[38]",
"DLG_TEXT[39]",
"DLG_TEXT[40]",
"DLG_TEXT[41]",
"DLG_TEXT[42]",
"DLG_TEXT[43]",
"DLG_TEXT[44]",
"DLG_TEXT[45]",
"DLG_TEXT[46]",
"DLG_TEXT[47]",
"DLG_TEXT[48]",
"DLG_TEXT[49]",
"DLG_TEXT[50]",
"DLG_TEXT[51]",

};