string DLG_TEXT[32] = {		// LDH was 31 25Feb09
", ilustre visitante. Soy ",
", propietario del astillero local.",
"Y yo soy ",
", capitán del '",
"'.",
", ",
". ¿Necesitas los servicios de mi astillero, ",
"?",
"Pues sí, necesito que tapes un par de agujeros en el casco y remiendes las velas.",
"Ahora mismo, solo quiero hablar contigo.",
"No, simplemente pasaba por aquí.",
"Bueno, estoy encantado de conocerte. Si eres capitán, mi astillero estará siempre a tu servicio.",
"Perfecto, ",
". Empecemos con esas reparaciones.",
"Te lo agradezco. Pero primero, quisiera hablar contigo.",
"Quizás la próxima vez. Ahora me tengo que ir.",
"¿Qué te interesa saber exactamente, ",
"?",
"No, no lo creo.",
"Ya veo. ¿Necesitas algo más, ",
"?",
"Me gustaría ponerle un par de parches a la vieja bañera que me ha traído aquí.",
"Gracias, eso es todo. ¡Adiós!",
"¿Qué necesitas exactamente?",
"Necesito reparar mi barco. Aunque podría considerar mandarlo al desguace y comprarme otro nuevo.",
"Necesito instalar nuevos cañones en mi barco.",
"Nada, muchas gracias.",
"No me gusta tu reputación ni las compañías que frecuentas. Me niego a tratar contigo. Márchate ahora mismo, ",
", antes de que llame a los guardias.",
"Muy bien.",
"Bien, mi muelle junto al fuerte está disponible para ti. Si te parece bien, le diré al capataz del muelle que remolque tu barco hasta allí. Solo entonces podré analizar los daños y decirte cuánto tiempo y dinero costará repararlo. ",
"¿¿MUELLE AL LADO DEL FUERTE?? Uhh... Acabo de recordar que tengo... eh... otros asuntos urgentes que debo atender primero. Adiós.",

};
