string DLG_TEXT[32] = {		// LDH was 31 25Feb09
", querido visitante! Yo soy",
", propietario del astillero local.",
"Y yo soy",
"capitan del barco",
".'",
", ",
". ?Necesita los servicios de mi astillero?",
"?",
"De hecho, necesito que repares un par de agujeros de concha y repares algunas velas.",
"Ahora mismo, solo necesito hablar contigo.",
"No, solo pense en pasar por aqui.",
"Bueno, estoy encantado de conocerte. Si eres capitan, mi astillero esta siempre a tu servicio",
"Perfecto,",
". Empecemos con las reparaciones",
"Gracias. Pero primero, hablemos",
"La proxima vez, tal vez. Tengo que irme",
"?Que es exactamente lo que te interesa?",
"?",
"No, no creo que lo haga",
"Ya veo. ?Necesitas algo mas,",
"?",
"!Me gustaria poner un par de parches en la vieja tina que me trajo aqui!",
"Eso es todo, gracias. !Adios!",
"?Que necesitas exactamente?",
"Necesito reparar mi nave, aunque podria considerar desguazarla y comprar una nueva.",
"Necesito instalar nuevas armas en mi nave",
"Nada, gracias",
"Me niego a comerciar con una persona de su reputacion y sus relaciones. Ahora vete,",
", antes de que llame a los guardias.",
"Muy bien.",
"Muy bien, mi muelle al lado del fuerte esta disponible para ti. Si quiere, le dire a mi capitan que remolque su nave alli. Solo entonces puedo inspeccionar los danos y decirle cuanto tiempo y dinero le llevara. ",
"ATRACAR AL LADO DEL FUERTE? Uhh.... Solo recuerdo que tengo... eeh.... otro asunto urgente que debo atender primero. Adios.",

};
