string DLG_TEXT[9] = {
"Una simple caja, semienterrada en la arena. Sirve como obstбculo y puede convertirse en una trampa con una granada.",
"Esta cosa es solo una molestia inъtil. ЎContramaestre! Despeja todo esto. Y devuelve las tablas a la bodega.",
"Un lugar prefecto para una trampa. Una grnaada con un pedernal conectado a la tapa le darб una buena sorpresa a cualquier entrometido. Y a ver quiйn resiste la tentaciуn...",
"Serб mejor que no toque nada...",
"ЎEh, tъ, enfrente del teclado! Este es una construcciуn creada POR TI, asн que, їpor quй no creas tu propio diбlogo para acompaсarlo? Solo tienes que usar Bloc de Notas para abrir el archivo PROGRAM\DIALOGS\SPANISH\ ",
" y sobreescribir este texto con el tuyo. Luego sigue las instrucciones en los comentarios.",
"Escribe aquн el texto de diбlogo del NPC.",
"Texto de diбlogo del jugador: opciуn link.l1, que cierra el diбlogo.",
"Texto de diбlogo del jugador: opciуn link.l2, que conduce a otro intercambio.",
};