string DLG_TEXT[43] = {
", fuerzas hostiles avistadas. Preparad la defensa.",
", Ўmovimientos enemigos en nustro sector! ЎZafarrancho de combate!",
", Ўmovimientos sospechosos en el perнmetro, todos a sus puestos!",
"Un informe detallado, soldado. Ahora.",
"ЎDйjame en paz con esas tonterнas, ese es tu trabajo! Para eso os he contratado como carne de caс... caсoneros expertos. De todas formas no tengo tiempo: tengo que irme.",
"Informo de que la",
" estб guarnecida y lista para el combate, ",
" todo estб tranquilo en este sector.",
"Nos retiramos de esta posiciуn. Desmantelad la",
", cargad las tablas en la bodega y presentaos al contramaestre para que os asigne vuestros deberes a bordo.",
"Esta fortificaciуn tendrнa un aspecto mucho mбs formidable con un caсуn. Por no mencionar el aumento en potencia de fuego. Soldado, toma estas 5000 piezas de oro y procura un caсуn para esta posiciуn.",
"Soldado, tengo una misiуn especial para ti. Toma esta granada, y si el enemigo nos supera y asalta esta posiciуn...",
"Solo pasaba pora quн...",
"Muy bien, soldado. Continъa.",
"Soldado, їno es esta fortificaciуn demasiado baja y dйbil para detener un asalto?",
"Eh, їquй haces ahн sin moverte? ",
"їTe has tragado un palo de escoba?...",
"Vamos, relбjate un poco... ЎDESCANSE, SOLDADO!",
"Espero un poco mбs de actividad por parte de mis infantes de marina, їme oyes?",
"ЎEh, tъ, enfrente del teclado! Este es un edificio creado POR TI, asн que, їpor quй no creas tu propio diбlogo para acompaсarlo? Solo tienes que usar Bloc de Notas para abrir el archivo PROGRAM\DIALOGS\SPANISH\ ",
" y sobreescribir este texto con el tuyo. Luego sigue las instrucciones en los comentarios.",
"Escribe aquн el texto de diбlogo del NPC.",
"Texto de diбlogo del jugador: opciуn link.l1, que cierra el diбlogo.",
"Texto de diбlogo del jugador: opciуn link.l2, que conduce a otro intercambio.",
"... los volarй en pedazos. ЎConozco mi deber, mi comandante!",
"ЎAsн se habla, soldado! Con tu sentido del deber, pronto llegarбs a cabo (... si vives lo sifciente).",
"Sн, ",
", conozco bastante bien al sargento mayor del arsenal local. Por 5000 piezas de oro, venderнa toda su artillerнa. Solo necesitarй unas pocas horas.",
"ЎAsн se habla, soldado! Con tu buen entendimiento de la logнstica, pronto llegarбs a cabo (... si vive lo suficiente).",
"ЎSe acercan los salvajes canнbales akellani, ",
"! Oh, si tan solo tuviйramos mбs bastiones, empalizadas, minas y caсones...",
"ЎAtenciуn, soldado! Mantйn esta posiciуn pase lo que pase. No dejes de dispararg y no dejes que el enemigo te arrastre a un combate cuerpo a cuerpo. Yo me ocuparй de eso...",
"ЎFrancisco Pizarro el Joven y su horda de conquistadores merodeadores se acercan, ",
"! Бvidos de sangre, botнn y bajos instintos... Oh, si tan solo tuviйramos mбs bastiones, empalizadas, minas y caсones...",
"їDemasiado baja? Parece que tienes las mismas ideas anticuadas en cuanto a arquitectura militar que esos canteros rusos que construyeron todos esos ayuntamientos y fuertes medievales por el archipiйlago. Pero la invenciуn de la pуlvora ha dejado obsoletos los muros altos y almenados. El perfil bajo de este bastiуn ofrece a la artillerнa de sitio un objetivo mбs difнcil. No importa que la infanterнa enemiga pueda escalar los parapetos bajos; mientras nuestra artillerнa siga disparando, no vivirбn para llegar hasta la base del muro.",
"Bueno, toda la madera buena se destina a los astilleros, asн que hemos tenido que construir esta empalizada con troncos quebradizos y madera de deriva. Es verdad, hay huecos lo bastante grandes para que un enemigo pueda colarse. Pero mientras nuestra artillerнa siga disparando, no vivirбn mucho tiempo.",
"їAsн que la artillerнa es la clave de todo? їCуmo puedo depslegar los caсones de la forma mбs efectiva?",
"Concentra varias fortificaciones con caсones para que puedan apoyarse unas a otras, pero no tan cerca como para que todas puedan ser atacadas a la vez. En primera lнnea, un robusto bastiуn que pueda soportar el grueso del ataque, y detrбs empalizadas mбs baratas desde las que disparar a los atacantes mientras estбn ocupados con el bastiуn. Pero asegъrate de que ninguno de tus hombres se mete en la lнnea de fuego. A largas distancias, nuestras granadas volarбn por los aires a cualquiera que estй cerca del objetivo. No te involucres directamente en el combate o quйdate cerca de los caсones, donde su punterнa es mejor.",
"Hum, no sй si puedo permitirme todo eso... Pero gracias por la lecciуn en fortificaciones del siglo XVII.",
"Siempre nos ponemos firmes en presencia de un superior. Esa es nuestra instrucciуn y la instrucciуn lo es todo.",
"Le tengo el ojo echado a un objetivo sospechoso y no quiero perderlo. 'Apunta bien, no te muevas, no parpadees', solнa decir nuestro sargento instructor.",
"La primera regla del camuflaje: el movimiento atrae la atenciуn. Asн que nunca te muevas si no tienes que hacerlo.",
"Estб bien, entiendo... Continъa.",
};