string DLG_TEXT[34] = {
", ilustre visitante. Soy ",
", propietario del astillero local.",
"Y yo soy ",
", capitán del '",
"'.",
", ",
". ¿Necesitas los servicios de mi astillero, ",
"?",
"Sí, mi barco necesita unas reparaciones.",
"En realidad, prefiero hablar.",
"No, gracias.",
"Bueno, me complace conocerte. Si eres capitán, entonces has venido al lugar indicado.",
"Perfecto, ",
". Empecemos con esas reparaciones.",
"Gracias. Pero primero déjame preguntarte algo.",
"Quizás la próxima vez. Tengo que irme.",
"¿Qué es exactamente lo que te interesa, ",
"?",
"No en este momento.",
"Ya veo. ¿Necesitas algo más, ",
"?",
"Sí. Me gustaría usar los servicios de tu astillero.",
"Eso es todo por ahora, gracias. ¡Adiós!",
"¿Qué es exactamente lo que necesitas?",
"Necesito reparar mi barco o quizas considerare comprar uno nuevo.",
"Quiero instalar nuevos cañones en mi barco.",
"Nada, gracias.",
"el maestro carpintero de este astillero.",
"Me niego a tratar con una persona con tu reputación y relaciones. Márchate ahora mismo, ",
", antes de que llame a los guardias.",
"Muy bien.",
"Bien, mi muelle junto al fuerte está disponible para ti. Si te parece bien, le diré al capataz del muelle que remolque tu barco hasta allí.",
"¿¿MUELLE JUNTO AL FUERTE?? Uhh... Acabo de recordar que tengo... eh... otros asuntos urgentes que debo atender primero. Adiós.",
"Esta bien, veamos lo que ofrecen tus instalaciones.",

};