string DLG_TEXT[388] = {
"Oh, eres tú, ",
". ¿Qué estás haciendo aquí?",
"No es asunto tuyo, ",
". Y podría hacerte la misma pregunta... pero tengo demasiadas cosas que hacer\n Así que encuentra un lugar para sentarte y dejame en paz.",
"¡No esperaba verte aquí!",
"Me alegro de verte también, ",
". Me han dicho que ahora pasas tu tiempo libre salvando ancianitos.",
"Ahora es mi turno de interrumpirte. ¿Dónde encontraste a un muchacho tan util?, ",
"?",
"Ese es mi secreto, ",
". Pero ya has oído lo que ha dicho. Así que ahora podemos trabajar juntos, como te ofrecí antes.",
"Me alegra ver que me esperaste. Ahora podemos ir juntos.",
"Por supuesto. Tan pronto como ",
"Vincent Bethune",
" nos diga a dónde vamos.",
"¡Es una emboscada! Id a la casa y encerraos dentro\n Yo los retrasaré todo el tiempo que pueda.",
"¡Cuídate!",
"¡¿Qué demonios está pasando aquí?!",
"Ah. ",
"Vincent Bethune",
" me habló de ti. ¡Trabajas como correveidile de ",
"Robert Christopher Silehard",
"!",
"Por fin despiertas, ¿eh?",
"¿Qué pasó?",
"Ha llegado el momento de hacer una visita al gobernador y hacerle algunas preguntas incómodas.",
"Estoy contigo. Vamos.",
"Bien, pero no podemos irrumpir en la residencia a plena luz del día. Esperemos en la taberna hasta que caiga la noche.",
"Bien pensado. Y me vendría bien un trago.",
"Mira, cuanto antes obtengamos respuestas del gobernador, antes podremos volver a confiar el uno en el otro.",
"Sí. Supongo que tienes razon.",
"Primero, salgamos de esta ciudad.",
"De acuerdo.",
"Deberíamos separarnos aquí. Así podremos meternos en más problemas\n Encuentra a ese chico que copió la leyenda, y yo iré tras el ídolo.",
"Me vale. Podemos encontrarnos en el faro, donde vive el viejo.",
"¡¿Qué estás haciendo aquí?!",
"¡Te estaba buscando! ¡¿Cómo pude ser tan idiota?!",
"Vaya, mira lo que ha traído la marea. Pensé que habíamos quedado en encontrarnos en el faro.",
"Me cansé de esperar.",
"Bueno, creo que estarás de acuerdo conmigo en que la espera valió la pena. He encontrado un cuaderno de bitácora. Veamos..., espera..., ¡Maldita sea! ¡Aquí no hay nada sobre donde encontrarlo! Espera... ¡Silencio! Juraría que he oído el crujido de la puerta. ¡Alguien viene!",
"¿Y? Ahora puedo encontrar a ese corsario español que supuestamente secuestró a la chica.",
"Ve al barco pirata.",
"Todavía no. No es el momento.",
"Ahora tengo que buscar a esa chica. Si ella no está por aquí, estoy en un serio aprieto.",
"...",
"¡Apenas escapé de esos fanáticos! Este asunto se está poniendo más caliente de lo que pensaba.",
"Debo informar de esto al padre Domingues. ¿Pero quién es este?",
"Los secuestradores de Lucas exigieron que el rescate fuera llevado a esta taberna, pero ellos no parecen estar aquí\n Ajá, esos dos junto al mostrador parecen estar esperando a alguien...",
"No hay necesidad de perder el tiempo. Probablemente son los que busco. (Hacer la seña convenida)",
"¿Tal vez debería escuchar su conversación primero? (Escuchar la conversación.)",
"La suerte me sonríe hoy. El barco de ",
"Pepin Bertillon",
" está atracado, por lo que su capitán debeRÍA estar por aquí cerca. Lo Único que queda por hacer es encontrarlo y hacerle unos agujeros en el pecho\n Primero tengo que asegurarme de que es a él a quien voy a matar. Los lugarenos son gente violenta, y un error podría causarme muchos problemas.",
"...",
"No te molestes con eso. No creo que seas alguien que pierda el tiempo, así que\n Me imagino que estás aquí por un chico llamado ",
"Raoul Reims",
". Te guste o no, iré contigo.",
"Está bien, ",
", puedes acompañarme.",
"¿Cuánto debemos esperar?",
"Researcher",
"dijo que podría llevar días.",
"Ya ha pasado una semana. ¡Necesito acción!",
"Estamos hablando de cientos de libras de oro. ¿No crees que eso bien vale una semana de espera?",
"Para ti, tal vez. No puedo aguantar mucho más. Necesito estar en movimiento. ¿Por qué no puede terminar la traduccion en el barco?",
"¿Sabes?, no se me había ocurrido eso.",
"Sí, supongo que los piratas no tienen mucho sentido comun, ¿verdad? Bueno, ¿y qué tienes pensado hacer con el oro, ",
"?",
"¿Qué?",
"¿Tengo que hablar más despacio? Qué. Vas. A. Hacer. Con. Tu parte del tesoro.",
"Comprare una isla inglesa, supongo, y hacer mis propias reglas. O tal vez me convierta en Par de Inglaterra. Eso podría tener sus ventajas. ¿Y tu?",
"Es un secreto.",
"Está bien. Haz lo que quieras.",
"¿Vas a enfrentarte a la flota regular?",
"No. ¡Voy a destrozarla!",
"¡Yo comandaré el fuerte! ¡Ten cuidado con los cañonazos!",
"¡Procura acertar a lo que estés apuntando!",
"¡Ganamos! Escribirán canciones sobre esta batalla, ¡que me aspen si no tengo razón! ¡Podríamos tomar todo el archipiélago juntos! ¡O todo el Caribe!",
"Claro que podríamos. Pero tendría más sentido tener una charla con ",
"Researcher", // NK - "Moses Blinman",
" primero.",
"¡Escúchate hablar, ",
"! ¡Debería darte vergüenza aplastar así los sueños de una dulce muchacha con tu aburrida lógica!",
"El tesoro siempre es lo primero, querida. Después, si aún quieres conquistar el Caribe, estaré contigo. Considéralo una promesa.",
"Espero que el erudito haya tenido tiempo suficiente para examinar esos garabatos. Dudo que pudiéramos resistir un segundo ataque.",
"No sé si el gobernador tendrá más buques de guerra.",
", el templo parece estar situado en algun lugar tierra adentro. ¡Vamos a dar un paseo!",
"Cierto, pero no queremos llamar la atención. Deberíamos dejar a la tripulación aquí hasta que hayamos revisado este templo con nuestros propios ojos.",
"¡No puedo creer que lo hayamos logrado! ¡Es solo cuestión de tiempo antes de que estemos rodando en oro!",
"Si es que hay oro.",
"¡No digas eso! ¡No podemos haber llegado tan lejos por nada!",
"Ya veremos.",
"Hay tres pasadizos aquí, y cualquiera podría ser el correcto. ¿En qué dirección deberíamos ir?",
"No lo sé. Esta podría ser la trampa de la que ",
"Researcher",
"estaba hablando.",
"Entonces, deberíamos separarnos. Cubriremos más terreno de esa manera. Yo tomaré el pasadizo de la izquierda, ¡y veremos quién encuentra el tesoro primero!",
"¡Oye, espera...!",
"¡Parece que ahora podemos ir a #sisland_Khael Roa#!",
"No tengo claro que vaya a ser tan fácil.",
"Tal vez deberíamos seguir adelante y registrar el templo mientras él lee esos garabatos.",
"¡No sin alguna idea de adónde vamos! ¡El mismo diablo podría perderse en ese laberinto!",
"Hazlo a tu manera, pero yo voy a dar un paseo. ¡Oh! ¡Ya veo algo! ¡Ten en cuenta que yo lo encontré primero!",
"¿Qué?",
"Tiene que ser la alcoba de la que ",
"Researcher",
"estaba hablando. ¿Pero dónde está el tesoro?",
"No lo sé. Incluso si arrancáramos todo el oro de las paredes, no sería mucho...",
"No podemos perder más tiempo buscando, ",
". ¡Tomarán la ciudad!",
"Solo quiero asegurarme de que no me hundes a mí también también, después de que nos hayamos ocupado de la flota inglesa.",
"Eso duele, ",
".",
"¡Era broma! Solo bromeaba. ¡Buena suerte!",
"¡Dios mío! ¿Qué ha sido eso?",
"¡No lo sé!",
"¡Tres mil demonios, ",
"! ¡Nadie podría sobrevivir a eso! ¡Mi tesoro! ¿Podríamos intentar recuperar una parte? ¿Solo un poquito?",
"No lo sé. Supongo que no es el único tesoro del mundo.",
"¿Qué más da? ¡Oh, qué perdida tan amarga!",
"Por alguna razón, tengo la sensación de que esto no te decepciona tanto como quieres aparentar.",
"No debería volver allí. ¡Tengo que salir de #sRedmond#, y rapido!",
"Ha sido duro, ¿no? ¿Sigues de una pieza?",
"Bueno, no creo que vaya a morir hoy, en cualquier caso.",
"Me alegro de oírlo, aunque no sé si a la Muerte le importará mucho lo que crea la gente como nosotros.",
"Vayamos a liberar a ",
"Researcher",
" de la prisión.",
", cada cosa a su tiempo. Salvemos al pobre viejo primero.",
"Lo que tú digas.",
"¿Qué hacemos ahora? No podemos encontrar el tesoro si no podemos traducir esa leyenda. Y me temo que el viejo...",
"Ya nos hemos puesto en contra al #sGovernor# y a la corona inglesa. ¿Qué tenemos que perder si tomamos esa miserable ciudad y liberamos a Aurentius?",
"No sabía que tenías tendencias suicidas. Pero si vas en serio con esto, ¡vamos a divertirnos un poco!",
"¡Así se habla! Ya me siento como un verdadero pirata. Atacaré el fuerte desde el mar, y tú y tus hombres podéis sitiar la ciudad desde tierra. ¿Qué me dices?",
"Digo que he creado un monstruo, ",
". ¡Pero estaré lista cuando tú lo estés!",
"¡Cálmate! ¿Qué ha ocurrido?",
"¿Qué ha ocurrido? ¡Me dijeron que habías muerto! Navegué hasta #sGreenford# para averiguar lo que realmente pasó. El dueño de la taberna me dijo que no te había visto. Entonces un muchacho se me acercó de la nada y me dijo que sabía dónde estabas. ¡Y caí en la trampa como una tonta!",
"Relájate. Ahora todo está bien. ¿Qué pasó entonces?",
"Puse rumbo aquí, a #sIsla Muelle#, con esa perro mentiroso. Dijo que nos reuniríamos con los piratas que te habían capturado. Me llevó a la selva..., y luego huyó mientras dos amigos suyos se abalanzaban sobre mí. Para cuando me encargué de ellos y regresé a la orilla, ya no estaba. ¡Y mi barco tampoco!",
"¿Pasaste por todo eso por mí? ¡La fria y altanera Danielle se lanzó a mi rescate sin pensarlo dos veces!",
"¡Sigue hablando, y te tragarás mi sable!",
"¡Ya he terminado! ¡Ni una palabra más, lo prometo! Entonces..., ¿hemos perdido las tabletas?",
"Realmente crees que no soy más que una chica tonta, ¿no? No, las guardé conmigo.",
", querida, ¿te he dicho alguna vez que eres la pirata más inteligente que conozco?",
"No. Por lo que recuerdo, lo que te cautivó de mí fue mi 'lengua afilada sin rival'. Ahora dime: ¿cómo llegaste aquí?",
"Después de capturar el barco enviado para llevar el ídolo al #sGovernor#, puse rumbo a nuestro lugar de encuentro. Pero encontré mal tiempo y me caí por la borda como un marinero de agua dulce. Creía que iba a morir, pero de repente me encontré en tierra cerca de #sisland_Douwesen#.",
"Sí. La fortuna favorece a los tontos.",
"¡Ahora calma! Ya lo he pasado bastante mal. Cuando recuperé el sentido, a trancas y barrancas llegué a #sDouwesen# y me las apañé para conseguir un pequeño barco. No mucho después, acabé aquí. Puedes imaginar lo sorprendido que me quedé cuando vi mi viejo barco en el puerto de Muelle. Aún estaban reparándolo después de aquella maldita tormenta.",
"¡Increíble! La fortuna favorece a los tontos, ¡pero ni tú eres tan tonto como para tener TANTA suerte!",
"Bueno, en ese caso... me lo he inventado todo. ¡Sí! Sólo era un cuento chino para entretenerte. Aquí estoy, en cualquier caso.",
"Y aquí estoy yo. Y ahora tenemos el ídolo. Deberíamos navegar juntos hasta #sisland_Oxbay# y hablar con Aurentius para traducir la leyenda.",
"Oh, ¡nunca hubiera soñado que dirías eso! Navegar juntos... suena tan... ¡dulce!",
", querido, ¡cállate!",
"Sí, trabajo para él.",
"¡Maldito! ¡¿Y me has preparado una emboscada a la entrada de la ciudad?!",
"Yo no...",
"¡Muere!",
"Aún haciéndote la dura, ¿verdad? Está bien...",
"Cierra el pcio, ",
", ¿vale?",
"¿Te parece divertido? ¡Me gustaría verte reir con un montón de leña bajo tus pies!",
"¿Hablabas en serio? Pensé que le ayudaste a llevar comida o algo así.",
"Aunque hablando en serio, ¿qué estás haciendo aquí?",
"Estoy intentando encontrar a alguien, pero cuanto más cerca estoy, peor me van las cosas.",
"He tenido más problemas de lo que debía.\nY todo por un muchacho. Da la casualidad de que también es capitán. Atiende por el nombre de ",
"Raoul Rheims",
"Raoul Rheims",
".",
"¿Hablas en serio? ¡Estamos buscando al mismo hombre! ¿Pero por qué le buscas?",
"¡Oro, por supuesto! Un hombre muy poderoso quiere tener unas palabras con ese diablo, y me ha prometido una pequeña cantidad si se lo llevo.",
"Entiendo. Quizás podríamos buscarle juntos.",
"Estoy completamente de acuerdo, pero debo decirte que no tengo ni idea de dónde está.",
"Entonces estamos igual, yo tampoco tengo ni idea.",
"Bueno, no se nos puede dar peor juntos de lo que se nos ha dado por separado. Y tiene que ser cosa del destino, encontrarnos así ¿Cuándo empezamos a buscar a nuestro mutuo 'amigo'?",
"Bueno, tengo algunos asuntos que resolver aquí...",
"Sin problema. De hecho, yo también tengo que atar algunos cabos sueltos.",
"Bien. Podemos encontrarnos aquí dentro de una semana. ¿Qué dices a eso?",
"Perfecto. Te veré entonces.",
"¡Buena suerte!",
"¿No recuerdas nada?",
"Me va a estallar la cabeza, ",
". No me atosigues. ¿Por qué no me explicas qué estás haciendo aquí?",
"Eh, si alguien debería enfadarse, tendría que ser yo. ¡Recibir esa daga donde yo lo hice no es precisamente la cosa más agradable que me haya pasado!",
"¡Te lo merecías! Sé que me estás persiguiendo por orden el gobernador inglés. Vamos a arreglar esto ahora. ¡Desenvaina tu espada!",
"Tranquilízate, ",
". Lo has entendido todo mal. Yo no te estoy persiguiendo en absoluto. Ni siquiera sabía que ",
"Robert Christopher Silehard",
" te quería muerta.",
"¡No me salgas con esas, ",
"! ¡Siempre has dicho que harías cualquier cosa por dinero!",
"¡Oh, vamos, ",
"! ¡Era un juego! Tú esperabas que fuera un sinvergüenza ¡Te gustan los sinvergüenzas! No podía decepcionarte.",
"¡¿De qué estás hablando?! ¡Siempre te consideré un hombre honesto!",
"¡Oh, no! Todo el tiempo que hace que nos conocemos, y nunca estuvimos de acuerdo.",
"¡Eso es verdad! ¡Siempre estabas intentando arrebatarme los mejores trabajos delante de mis narices!",
"¿Pero cuándo te he hecho yo algo a ti? Tal y como yo lo veo, ¡parece como si siempre hubiese estado salvándote el pellejo!",
"Quizás. ¡Pero ahora estás trabajando para un hombre que quiere verme muerta!",
"Lo estaba, ",
". Hace poco que me... retiré. Pero ",
"Robert Christopher Silehard",
" no lo sabe aún.",
"¿Qué, no te pagaba lo suficiente?",
"El dinero no es la cuestión. Esta vez no. Es sólo que decidí que no quería trabajar nunca más para un hombre como él.",
"¿Qué estás diciendo? ¿Eres un hombre libre? ¡Entonces déjame en paz!",
"¡Bien! Veo que eres tan cabezota como siempre. Buena suerte con los tres cadáveres que tienes en tus manos.",
"¡¿?!",
"¿Qué más quieres?",
"...",
"¿Tenías algo más que decir, o me puedo marchar ya?",
"... Gracias... por tu ayuda, ",
". Estaría muerta de no ser por ti.",
"Olvídalo. ¿Me puedo ir?",
"¡Espera, ",
"! ¿Qué vas a hacer ahora?",
"Voy a hacerle unas preguntas a cierto gobernador corrupto.",
"Sólo espera un momento, ¿vale? No puedes ir allí solo. ¡Es un suicidio! Si ",
"Robert Christopher Silehard",
" sospecha algo, ¡te matará sólo por si las moscas!",
"¡Gracias, pero correré el riesgo!",
"No sin mí, ¡no lo harás!",
"¿Por qué? Estaré bien.",
"Lo primero, tengo mis propias preguntas que hacer. Y segundo... ",
"¿Qué?",
"Conozco un buen sitio para echar el ancla en #sisland_Redmond#, donde nadie estará esperándonos.",
"Está bien, de acuerdo. Uniremos nuestras fuerzas por el momento.",
"¡Bien! Pero si me engañas sólo una vez más, ",
", te mataré, ¡lo juro!",
"¿Qué está pasando? ¡Esos soldados intentaban matarnos!",
"No lo sé, ",
", pero deberías salir de la ciudad; es peligroso.",
"Y... ¿dónde podría haber guardado ese papel? Veamos.",
"(Comenzar a buscar)",
"¡Toda la ciudad es presa del pánico! Están gritando que el puerto está en llamas. No podemos ir en esa dirección.",
"Tengo una idea. Diremos que hay tropas francesas en la ciudad. ¡Grítalo con todas tus fuerzas! ¡Eso confundirá a los guardias!",
"Creo que veo la figura de Nigel Blythe por allí delante. Interesante. ¿Adónde se dirigirá?",
"...",
"Hum...A lo mejor me equivoco, pero parece que un hombre de mi tripulación, Artois Voysey, acaba de entrar en la ciudad.",
"...",
"El oficial Edgar Attwood acaba de abandonar el barco sin mi permiso.",
"...",
"¡Diablos! ¡Alguien disparó a Artois! ¡Tengo que llevarlo a una taberna y buscarle un médico!",
"...",
"Snorri:...ando en este agujero durante dos semanas, ¡y todavía no hay oro! ¡Y tú nos dijiste que el viejo pagaría seguro!",
"...",
"Billy: Pagará, ya verás como lo hará. Pero reunir tanto oro no es algo que se pueda hacer tan rápido.",
"...",
"Snorri: ¡¿Y qué pasa si no le importa un rábano su condenado hijo?! ¡¿Y si en vez de oro, viene un galeón cargado de españoles ansiosos de sangre?!",
"...",
"Billy: ¡Ya es suficiente! ¿Has visto alguna vez a un padre que abandone a su hijo en una situación como esta? No te preocupes, el almirante pagará el rescate. Realmente no tiene elección.",
"Ya he oído suficiente. Estos son los que busco. (Hacer la seña convenida)",
"¡Ahora, a liberar al padre Domingues!",
"Las celdas están a la derecha. Vamos.", 
"(Veo un pequeño montículo de piedras)",
"Apuesto a que hay algo enterrado aquí. Voy a cavar.",
"(Diez minutos después)",
"¡Qué preciosidad de espada! Pero hay un nombre grabado en la hoja...",
"¡PETER! ¿ADÓNDE VAS?",
"Hum... Parece que ya no me oye. Será mejor que lo siga. Parece que corre en dirección a la tienda.",
"(Arrecia una tormenta repentina)",
"Qué raro. ¿De dónde ha salido esta tormenta tan de repente? Será mejor que me vaya de aquí cuanto antes.",
"(Arrecia otra toermnta repentina)",
"¿Otra tormenta repentina? Esto no me gusta.",
"(Los españoles detectan tu presnecia)",
"¡¡¡MOOVEOS!!! ¡¡¡HERMANOS DE LA COSTA!!!",
"(Ves al soldado del puerto)",
"¡Es él otra vez! ¡Atrpémoslo!",
"(Barbossa hablando con su tripulación)", 
"¡Caballeros, ha llegado la hora! ¡Nuestra salvación está cerca! ¡Nuestro tormento está a punto de llegar a su fin! Diez años nos han puesto a prueba, y todos y cada uno de vosotros habéis demostrado una fortaleza cien veces superior. ¡Y cien veces más si fuera necesario! El castigo infligido ha sido desproporcionado al crimen cometido. ¡Aquí está! El tesoro maldito del mismísimo Cortés. Todas y cada una de las piezas que sustrajimos han sido devueltas. ¡Excepto esa!",
"¡Puede que seas inmortal, pero aún puedo dejarte sin sentido, idiota! Ahora, tengo que reunirme con mi tripulación para reveritr la situación en mi barco.",
"Capitán ",
"Se os acusa de crímenes contra la Corona, siendo dichos crímenes en cantidad numerosa y de siniestra naturaleza. Los más atroces de ellos se citan a continuación: piratería, contrabando, navegación bajo pabellones falsos, incendio premeditado, secuestro, saqueo, pesca furtiva, bandolerismo, hurto, depravación, depredación y desorden generalizado. Y por estos crímenes habéis sido sentenciado a que, en el día de hoy, se os cuelgue de la horca hasta morir. Que Dios se apiade de vuestra alma.",
"... ¡Me parece que no!...",
"¡Oh, en fin!... Tendré que ser yo mismo quien lleve a cabo al acto heroico.",
"[La moneda maldita en el medallón que cuelga del cuello de Elizabeth ha convocado a la #scursed_ship#]",
"Hum... ¡no es mi mejor día!",
"Ahí hay un barco que podría darme la ventaja que necesito. Debería ir a verlo más de cerca.",
"(Veo que la arena ha sido removida)",
"Alguien ha enterrado algo aquí.",
"(Dos minutos después)",
"¡UN MAPA! Apuesto a que el oro está allí.",
"(Hay ocho cajas de oro en la cueva)",
"He encontrado el oro... pero solo una pequeña parte del oro robado en Aguadilla. ¿Dónde está el resto?",
"(Unos días después)",
"Ha llegado el momento de volver a ver a mi informante. Esperemos que haya encontrado algo.",
"(Dos días después en la taberna)",
"Esta noche, debo ver el tesoro.",
"(Escuchas la conversación de los soldados)",
"Pertenecen a la Flota de la Plata... Debo advertir a Elting de que han establecido un campamento fortificado en frente del fuerte.",
"(Por la noche, oyes a alguien caminando)",
"¿Quién anda ahí?",
"(Tu barco está levando anclas)",
"¡Bastardo! ¡Me las pagará!",
"(Unas horas después)",
"¡Hace demasiado calor! Necesito beber agua rápidamente o de lo contrario moriré en los próximos dos días.",
"(Has terminado de cavar un hoyo en la arena)",
"¡Maldita sea! ¡No hay agua en el islote.",
"(Al día siguiente)",
"¡¡Sí!! Está lloviendo. ¡Gracias, Dios! ¡Por fin, AGUA!",
"(Muchos dÍas han pasado)",
"DeberÍa explorar el islote para saber si alguien estaba aquí antes que yo y dejó algo.",
"(Encuentras una daga)",
"¡Excelente! Podría usarla con un palo para hacer una lanza y pescar en las aguas que rodean el islote.", 
"(Ves un barco acercándose)",
"¡AQUIIIÍ! ¡¡¡AYUDAAA!!!",
"(Ves a una joven hermosa)",
"[Piensa] Voy a hablar con ella. Parece estar sola.",
"(Ves un galeón de guerra en el puerto)",
"¡Qué hermoso navío! Tiene muchos cañones. Podría usarlo para la operación de distracción. Hablaré de esto con mis compañeros esta noche. Ahora, debo unirme al gobernador en su residencia.",
"(Oye una disputa en el jardín de la residencia)",
"¡¿Qué?! Pero si es la hija del gobernador la que esta discutiendo... Voy a hablar con ella para entender lo que está pasando.",
"(Dirigiéndote a todos)",
"Caballeros, ha llegado el momento de explicar cúal es mi plan. Al caer la niche pondremos en marcha cuatro operaciones. Mi tripulación y yo apresaremos un barco español en el puerto. Es el 'San Martín': un buque de guerra de 56 cañones. Hay dos razones para ello. Primero, quiero evitar que el barco dispare contra el fuerte durante nuestro ataque. La segunda razón es más personal; perdí el 'Santiago' a causa del motin y, viendo que necesitaré un nuevo barco cuando se cumpla la mision, bien puede ser este.",
"Creo que todo el mundo sabe lo que tiene que hacer. ¡Buena suerte!",
"(Hablando con tu tripulación)",
"¡Luchad contra los soldados, pero dejadme al capitán a mí!",
"Qué extraño, tengo la sensación de que...",
"........",
"(Ves a las fuerzas holandesas preparando el asalto)",
"!Bien! El capitán Dierman y Elting están listos para atacar. Informemos al capitán Queiroz.",
"Déjame ver. ¿Dónde debería empezar a buscar? Todos los capitanes tienen un cuaderno de bitácora. Podría estar en aquella caja...",
"¡UF! Me siento como si hubiera dormido durante una semana, y la barba que me ha crecido en el mentón lo confirmo. Ahora que me he lavado y adecentado, debo buscar a Hunter.",
"Una buena noche de descanso, por fin. Ahora, a buscar al Sr. Bush.",
"¡Tengo la llave del alcaide! Ahora, a salir de aquí...",
"Nada que valga la pena en este momento. Debería pasar algún tiempo en la taberna e intentarlo de nuevo más tarde. Además, necesitaré ver si la tienda puede venderme un mapa de las aguas de #sisland_Cuba#.",
"Parece que la tripulación se lo ha creído. Ahora, a tomar el control del barco antes de que se den cuenta de que han sido engañados.",
"Los papeles del barco deben estar por aquí... ¡Ajá, los tengo! Barco 'Tonina'... ¿Qué clase de nombre es ese?, ¡vamos a tener que cambiarlo! El capitán es, o más bien era..., el alférez de Navío Esteban Rovapera.",
"Al garete con mis planes d eocmprar un mapa de #sisland_Cuba#. Pero hay uno justo en la ventana. Tendré que volver cuando oscurezca.",
"Al garete con mis planes d eocmprar un mapa de #sisland_Cuba#. Pero hay uno justo en la ventana. Y está oscuro ahora...",
"Espera un momento... ¡será mejor que esa cuerda esté bien amarrada!",
"Tratando de espiarnos en nuestra intimidad, ¿verdad? ¡Piérdete o tendrás una relación íntima con mi espada!",
"¡Buena seguridad! La prisión está justo al lado de la puerta de la ciudad. Debería llevar el barco a la playa, entonces escapar de la prisión será mucho más fácil.",
"¿Qué tenemos aquí? Parece que hay planes para una invasión... #sRedmond#, si no me equivoco. El almirante de #sisland_Antigua# probablemente pagaría bien. Pero me pregunto cuál es el papel de #svillain# en todo esto.",
"Eso parece una puerta trasera a la residencia del gobernador. Me pregunto si podré abrir la puerta.",
"Pero lo mejor será intentarlo de noche.",
"Esto debería ser más que suficiente... Un buen documento de algún tipo, bien largo, ¡y con la firma del gobernador al final!",
"Ahora tengo que rescatar a mi tripulación del fuerte. Simplemente podría intentar abrirme paso luchando y salir del mismo modo\n Alternativamente, he oído que un falsificador vive en el campamento de los Bucaneros. Probablemente querrá una muestra de la letra del gobernador si va a falsificar un documento de liberación para mi tripulación. Así que necesito conseguir uno.",
"¿Qué tenemos aquí? Parece que hay planes para una invasión de #sSantiago#, a menos que me equivoque. ¡Justo lo que el gobernador quería!",
"Adiós a #sproposer#. Pero tal vez pueda robar al gobernador de #sDouwesen# sin su ayuda. Por supuesto, eso arruinaría mis relaciones con Holanda y puede significar que no pueda volver a poner un pie en #sDouwesen#.",
"Quiero intentarlo de todos modos.",
"Olvídalo, no quiero meterme en problemas con Holanda.",
"Empinar el codo: el sutil arte de hacer que el ron acabe por todas partes menos dentro de ti. Por eso él esta en el Suelo y yo sigo en pie.",
"Ahora, a buscar su uniforme. Pero él es solo un soldado común, necesito el uniforme de un oficial; un capitán, tal vez. Un sastre debería ser capaz de hacer los retoques necesarios.",
"Hum... Es cierto que la carta es del Almirantazgo. España es ahora aliada de Gran Bretana, lo que hace a don Julián nuestro enemigo.",
"Y yo le he dado uno de los barcos de guerra más poderosos de estas aguas...",
"No podré mover esa roca sin ayuda. Parece que no podré salir de aquí...",
"¡El '",
"' no está en el puerto! El capitán ",
" debe haberse impacientado y ya se ha ido a #sHavana#.",
"Tendré que navegar allí yo también y esperar alcanzarlo.",
"Los secuestradores estan probablemente en esa cueva con #senvoy#. Si irrumpo allí, pueden matarla, o puede que muera accidentalmente en la pelea.",
"Si lanzo una botella de éter allí, su efecto debería ser mayor en un espacio tan confinado.",
"Tendré que entrar con cuidado e intentar negociar su liberación.",
"Será mejor que espere a que el aire se despeje. No quiero acabar yo también inconsciente, igual que los secuestradores, ¿no?",
"¡Perfecto! Todos los secuestradores están fuera de combate. También lo está #senvoy#, así que tal vez tenga que disculparme más tarde.",
"Pero por ahora, tendré que sacarla de aquí antes de que los secuestradores se despierten.",
"(Ves dos soldados ingleses muertos)",
"Hum... ¿Bandidos? ¿Los contrabandistas cometieron este crimen? Este lugar es más peligroso de lo que pensaba...",
"(Ves un campamento militar frances)",
"¡Maldita sea! Un campamento de soldados franceses. ¿Qué hacen aquí? Supongo que están preparando un ataque a #sConceicao#. Ahora, entiendo por qué vi a esos soldados ingleses muertos en la playa. Deben haber sido emboscados cuando patrullaban la costa. No tengo elección. Si quiero encontrar algo en la mansión de Bartolomeu, debo acercarme al campamento y evitar a los guardias.",
"¡Maldita sea! Un campamento de soldados franceses. ¿Qué hacen aquí? Supongo que están preparando un ataque a #sConceicao#. Ahora, entiendo por qué vi a esos soldados ingleses muertos en la playa. Deben haber sido emboscados cuando patrullaban la costa. Debo volver a la playa y esperar un mejor momento.",
"(Miras al cofre)",
"Este debe ser el cofre en el que Fernando encontró el diario de Bartolomeu. Qué raro, hay una pequeña llave dentro. ¿Por qué no se la llevaría Fernando? Debió pensar que no servía para nada... Quizás pueda abrir algo con ella. Pero solo veo paredes y ninguna puerta... ¿Qui´zas la llave alguna caja enterrada bajo la mansión?",
"Esa parece la vanguardia del tren de transporte de plata.",
"Espera a que estén todos a la vista antes de atacar.",
"¡La palta es nuestra!",
"Ahora, volvamos al barco.",
"¿Qué? Es mi barco el que se aleja..., ¡bajo una bandera pirata! ¡MALDITO SEAS, SPARROW!",
"Al menos me ha dejado algo que navega.",
"La puerta no está cerrada con llave, pero no puedo pasar...",
"... ¿Estoy condenado a vagar por aquí para siempre?",		//370
"Ahora que he llegado hasta la bodega, será mejor que encuentre un lugar donde esconderme.",
"Tal vez destrás de esas cajas de ahí.",
"Vaya, qué contrariedad. Ahora tengo que librarme del cuerpo. No puedo arrastrarlo hasta cubierta, es casi seguro que me verían.",
"Con un poco de suerte, puedo meterlo en una de esas cajas.",
"Hala, con eso bastará hasta que el barco llegue a donde quiera que que esté yendo. Ahora, de vuelta a mi escondite...",
"He llegado demasiado pronto, debería volver mañana por la noche.",
"¡Pero no más tarde! Si me retraso demasiado, el contrabandista se marchará sin mí, y puede que nunca consiga salir de esta isla.",
"¡Vaya! ¡Esta fiesta es un aburrimiento! Tengo que escaparme de aquí o, por lo menos, encontrar algo interesante que hacer!",
"...",
"¡Huy! ¡Lo siento! ¡Qué vergüenza! A veces soy tan tope... ¡Cuantísimo lo siento! Lo pondré donde estaba, ¿ves? Perdón...",
"[PIENSA:] ¿Por qué había una llave en el jarrón? ¡En fin, nadie se dará cuenta!",
"¡Qué pérdida de tiempo! ¡Justo cuando la fiesta se estaba poniendo interesante, apareció esa loca con el sacudidor de alfombras!",
"Bueno, he termiando con mis asuntos aquí. Será mejor que vuevla al barco para reunirme con los otros.",
"Bueno, menuda aventura. Espero que haya podido ayudar a ese joven. Pero lo más importantes es que tengo el dinero para el ron. Ahora debería volver al barco para reunirme con los otros. ¡Beatrice ya debe de estar preocupada!",
"...",
"Bueno, puede que yo sea un saco de boxeo, pero tú, Chico, ¡tú eres la vaina de mi espada!",
"Debería tomar el dinero y salir de aquí. La pequeña Bea debe de estar furiosa.",
};
