string DLG_TEXT[60] = {
"Bienvenido a mi taberna, extrano. Mi nombre es ",
". ?Que te trae a mi humilde establecimiento? ?Necesitas un lugar para descansar?",
"Agradecer. Mi nombre es ",
". Estoy aqui por negocios.",
"Mi nombre es ",
", y usted puede prescindir de su hospitalidad. Estoy aqui por negocios.",
"!Bienvenidos, #ssir#! ?Que quereis?",
"Necesito algo de informacion, y me parece que el posadero local es generalmente el hombre a preguntar.",
"Estoy buscando para contratar algunos marineros para mi barco.",
"Senalame a los clientes aqui que podrian estar buscando un trabajo. Tengo que anadir a mi equipo, y no me importa si son salvajes.",
"?Tienes una habitacion? Me gustaria quedarme aqui un tiempo.",
"?Tiene una cama libre en esta casucha?",
"No tengo ningun negocio contigo ahora. Despedir.",
"Eso es cierto. Oigo casi todo. ?Que quieres saber?",
"Necesito un trabajo. ?No conoces a ningun chico rico en esta isla que tenga miedo de viajar solo?",
"No tengo ninguna pregunta en este momento. Hablemos de otra cosa.",
"Tal vez si. Hay muchos rumores.",
"Prisa. Soy un hombre ocupado.",
"Es un poco tarde para encontrar buenos marineros. Ya estaran dormidos o desmayados. Vuelve por la manana o puedes pasar la noche aqui en la taberna.",
"Muy bien. ?Tiene una habitacion?",
"No necesito una habitacion en este momento. Hablemos de otra cosa.",
"Tengo una vacante. ?Cuanto tiempo te vas a quedar?",
"Noche.",
"Solo hasta que oscurezca.",
"Fino. Seran 5 piezas de oro.",
"Muy bien. Aqui tienes.",
"Lamentablemente, no creo que pueda permitirme nada mejor que una noche en el salon de la taberna.",
"?Eso viene con personal? Paso.",
"Lo pensare.",
"Fino. Seran 5 piezas de oro.",
"Muy bien. Aqui tienes.",
"Lamentablemente, no creo que pueda permitirme nada mejor que una noche en el salon de la taberna.",
"Eso es demasiado. Me carteles en el salon de la taberna.",
"Lo pensare.",
"Queridos visitantes! !Por favor, detengan esta atrocidad! No me obligues a llamar a los guardias!",
"!Muy bien, muy bien! !Ya me he ido!",
"Si es que prefieren navegar con menos satelites, ya sabes esto", 
"Si, lo olvide. Muy bien, volvere mas tarde, cuando tenga menos naves, ja-ja.",
"No quiero ayudarte. Has causado demasiados problemas a mi pais.",
"Basta con mirar a este patriota. Bueno, adios.", 
"Tus manos estan cubiertas de sangre. No pensaras en serio que alguien viajaria contigo, ?verdad?",
"!Tienes razon, todos me tienen miedo! !Ja, ja!",
"Llegaste justo a tiempo. Un comerciante estaba buscando la compania adecuada para viajar. Deberias hablar con el. Ahi esta, llegando a la taberna.",
"Lo hare.",
"No, no hay nadie asi en este momento, Tal vez la proxima vez.",
"Hmm, entonces esperare.",
"Disculpe, pero ?tiene un primo llamado Sven?",
"?Que es esto? Una especie de codigo secreto?",
"No, pero una vez tuve un barbero llamado Dominique.",
"!Bugrit! !Bugrit! Millennium Hand y camarones.",
"!Yo soy de goma, tu eres pegamento!",
"Oh, bueno ... no importa, ",
"?Podrias dejar de decir tonterias y volver a los negocios serios, por favor?",
"Bueno, lo suficientemente cerca. Como pareces ser un miembro de la Cirujano Secreta de los tres Monos de Cabeza, te mostrare el mapa De las grandes Riquezas Mas alla de la Imaginacion. Si te interesa, claro.",
"Por supuesto que si, hermano.",
"?Lo has visto? Visto? Dicen que esta debajo de la cabeza de mono. Lamentablemente nadie sabe donde se encuentra la isla, pero esta ahi fuera en alguna parte. Puedo sentirlo. El origen de la Cirujano Secreta de los tres Monos con Cabeza se encuentra alli.",
"Junto con las Grandes Riquezas Mas alla de la Imbecilidad, supongo?",
"!Imaginacion! Grandes Riquezas Mas Alla De La Imaginacion. De todos modos, si averigua mas, hagamelo saber y podriamos empezar una expedicion.",
"Sonidos, er ... Interesante.... ?Por casualidad conoce a alguien-otro hermano - que pueda dar mas organismo?",
"Podrias tratar de buscar al gran Maestro de la cirujano, si estas listo para Las tres pruebas. No me preguntes quien es el gran Maestro. Aunque lo supiera no te lo diria.",
};