string DLG_TEXT[28] = {
"Le pido amablemente que salga de mi casa en este instante. Estoy ocupado.",
"...",
"Asi Que, Conc ",
"Robert Christopher Silehard",
"me envia su mano derecha #sgender#. ?Que quiere de mi?",
"?Quien dice que trabajo para el?",
"? Que te hace pensar que estoy aqui por orden del conc?",
"Le pido perdon, pero ?parezco el idiota del pueblo? En el momento en que supe que alguien me estaba buscando, hice averiguaciones.? me miras a los ojos y niegas que has estado trabajando para el durante los ultimos meses?",
"Bueno, digamos que tienes razon, y el gobernador me envio. ?Que diferencia hace eso? Tendria que negarse a hablar con un representante del gobernador?",
"Mira, ya he tenido suficiente de este gato y raton. ?Vas a hablar conmigo, o prefieres elegir Cual de tus piernas quieres mantener?",
"Capitan, me pregunto si sabe con quien esta hablando. Debes confiar en mi cuando digo que si no quisiera hablar contigo, no estarias aqui.",
"Oh, no hay necesidad de violencia fisica, #sboy#. Hablare contigo porque tengo curiosidad: ?que quiere ese viejo zorro, el conc, de mi?",
"Fino. Necesito saber donde puedo encontrar a un caballero con el nombre de ",
"Raoul Reims",
". Se que se esconde en algun lugar de esta isla.",
"Tu informacion esta desactualizada, joven #sgender#. ",
"Raoul Reims",
"ciertamente paso un par de dias aqui. Practicamente nunca salio de su casa, pero ya ha zarpado de nuevo, y mantuvo su destino en secreto incluso de mi. Claramente, estaba preocupado por algo, pero no podia decir que.",
"?Tiene una casa aqui? ?Donde puedo encontrarlo?",
"Tiene una cabana aqui en la isla, ?verdad? ?Donde esta?",
"Un momento, #sboy#. Puede que seas un enviado del conc Ingles, pero eso no te da permiso para invadir la casa de otro hombre y pasar por sus pertenencias. ?He sido muy claro?",
"Le ruego que haga una excepcion por mi, Senor. Debo averiguar donde ",
"Raoul Reims",
"era la vela, y pronto!",
"Oh, vamos. Eres un contrabandista, conocido en todo el archipielago por tu falta de principios. ?Vas a hablarme de la ley?",
"Puedo ver que no escuchas razones. Si no puedo convencer a permanecer lejos de la casa, voy simplemente el fin de mis hombres a vigilar y disparar a la vista. Estoy seguro de que incluso usted puede tomar una pista de una bola de mosquete. !Ahora, vete!",
"Despedir.",
"Esto no ha terminado!",

};