string DLG_TEXT[71] = {
"¡Oh no, clientes!",
"¿...?",
"Este no es un buen momento para visitar el hotel, créeme.",
"Bueno, no he venido a alojarme, solo busco a alguien que sepa de plantas misteriosas.",
"Sí, sí, esa soy yo, pero tenemos algunos problemas graves en el hotel a día de hoy.",
"",
"",
"¿Cuál es el problema?, ¿cómo puedo ayudar?",
"El hotel está invadido por antiguos aventureros, o debería decir piratas. Esto pasa de vez en cuando.",
"¿Quieres que los espante y, si es necesario, que los mate?",
"¡Sería muy difícil matarlos, teniendo en cuenta que ya estan muertos!",	//10
"¿Cómo puedo deshacerme de ellos?",
"Siempre dicen que les faltan algunas cosas. Dos objetos cada uno. Si puedes encontrarles sus cosas, con un poco de suerte se irán.",
"Muy bien, veré qué puedo hacer.",
"¿Se han ido los fantasmas, capitán?",
"Todavía no, me temo.",
"",
"Tómatelo con calma, yo te ayudaré.",
"¿Dónde está mis efectos persoanles?",
"Estoy trabajando en ello.",
"La próxima vez, como no los tengas...",					//20
"(*traga saliva*)",
"Tienes algo que es mío. ¡Dámelo!",
"Aqui estás...",
"¡Sí que lo son!",
"¿Cómo puedo agradecértelo?",
"Bueno..., ¿que tal si dejas que me quede con los objetos que he encontrado?",
"Puedes quedarte con los objetos que hayas encontrado en el hotel, capitán.",
"Gracias, señorita.",
"Cálmate; los fantasmas ya se han ido, de verdad.",
"¿Seguro? ¿Qué quieres de mí, capitán?",			//30
"Estoy buscando plantas raras. ¿Puedes ayudarme?",
"Tal vez pueda. Tengo estas plantas de ayahuasca. ¿Te interesan?",
"Por supuesto que sí. Por favor, dámelos.",
"Tienes que hacerme un favor primero.",
"Ajá ¿qué quieres?",
"¡Sácame de aqui!",
"Hum, ¿adónde quieres ir?",
"No importa, capitán, mientras me aleje de este hotel maldito.",
"Muy bien, entonces. Vamos al puerto, un barco está esperando.",
"Tú otra vez, capitán. ¿Qué quieres ahora?",				//40
"Oh... esto... Nada.",
"Te seguiré, capitán.",
"Entonces, vamos, señor Broome.",
"¡Me siento libre!",
"Buena suerte.",
"!No, no lo es! Ella tiene deberes que atender aquí en el Hotel.",
"Hazte a un lado o te...",
"¡¡Guardias!! Detenedlos.",
"¡¿?!",
"¡Basta! Llévate a la chica y piérdete, pero primero, ¡las llaves del hotel!",	//50
"Vamos, Abequa.",
"Tienes mi garfio de abordaje. ¡Dámelo!",
"Tienes mi silbato de contramaestre. ¡Dámelo!",
"Tienes mi garfio de abordaje y mi silbato de contramaestre. ¡Dámelos!",
"Tienes mi crucifijo.¡Dámelo!",
"Tienes mi Biblia. ¡Dámelo!",
"Tienes mi crucifijo y mi Biblia. ¡Dámelos!",
"Tienes mi sextante.¡Dámelo!",
"Tienes mi equipo de dibujo. ¡Dámelo!",
"Tienes mi sextante y mi equipo de dibujo.¡Dámelos!",		//60
"Tienes mi catalejo. ¡Dámelo!",
"Tienes mi bocina. ¡Dámela!",
"Tienes mi catalejo y mi bocina. ¡Dámelos!",
"Tienes mi instrumental quirúrgico. ¡Dámelo!",
"Tienes mis vendas. ¡Dámelas!",
"Tienes mi instrumental quirúrgico y mis vendas. ¡Dámelos!",
"Esta bien, limpiaré las habitaciones del hotel de inmediato.",
"Pero, capitán, se han encerrado. No puedo limpiar las habitaciones. Solo podemos encontrar la llave de la habitación 3.",
"Capitán, gracias por el viaje. Antes de que te deje, aquí están las plantas que te prometí.",
"Sí. ¡Por fin!",							//70
};
