string DLG_TEXT[137] = {
"Te doy la bienvenida, ",
". Considérate en tu casa, ¡y a mí como tu familia!",
"Hum..., sí. Gracias. Soy ",
".",
"¡Eh, ",
"! ",
".",
"Vaya, vaya... ¡Mira a quién ha arrastrado la marea! Me alegro de verte, ",
".",
"Es maravilloso tenerte aquí, ",
". ¿Qué puedo ofrecerte hoy?",
"Necesito algunos hombres fuertes para ayudar en las tareas de mi barco. Los preferiría listos, pero me conformo con que sepan estarse callados.",
"Espero que tengas un momento para hablar.",
"Necesito una habitación. Una limpia.",
"¿Tienes un montón de paja libre en este granero?",
"Lo siento. Ya me estaba yendo, ",
". Ya nos veremos.",
"Oh, podrás asegurarte de ello en persona, ",
". Mi nombre es ",
". Soy el dueño de esta humilde taberna.",
"Necesito contratar tripulación, ",
".",
", hablemos...",
"¿Tienes una habitación que pueda usar? ",
"Me gustaría quedarme aquí por un tiempo.",
"Puede que te haga una visita más tarde.",
"Ciertamente. ¿De qué te gustaría hablar, capitán ",
"?",
"Seguro que un tipo amistoso como tú escucha un montón de rumores interesantes Me gustaríaa saber que está pasando estos días.",
"Tengo algo en mente...",
"¿Sí?",
", un hombre llamado ",
"Ewan Glover",
"Ewan Glover",
" dijo que me esperaría aquí.",
"Necesito un trabajo. ¿No conoces a algún niño rico en esta isla que tema viajar solo?",
"Buenos dias. ¿En qué puedo ayudarte?",
"Estoy buscando a un joven español. Su nombre es Lucas Da Saldanha. Tal vez lo hayas visto.",
"¿Sabes, ",
"? Ya me pondré al día contigo en otro momento.",
"Si es así, prefieren zarpar con menos escolta, ya lo sabes.",
"Sí, lo olvidé. De acuerdo, volveré más tarde, cuando tenga menos barcos, ¡ja, ja!",
"No quiero ayudarte. Has causado muchos problemas a mi país",
"Vaya, tenemos un patriota. Bien, adiós", 
"Tus manos están manchadas de sangre. No pensarás en serio que alguien viajaría contigo, ¿verdad?",
"Tienes razón, ¡todo el mundo me teme! ¡Ja, ja!",
"Llegas justo a tiempo. Un mercader estaba buscando una buena escolta con la que viajar. Deberías hablar con él. Aquí está, justo ahora está entrando en la taberna.",
"Eso haré.",
"No, no hay nadie así en este momento. Quizás la próxima vez.",
"Hmm, entonces esperaré.",
"Interesante. Por cierto, estoy buscando espaldas fuertes para añadir a mi triuplación.",
"Me gustaría hablar contigo, si tienes un momento.",
"Lo siento, ya me iba, ",
". Seguro que nos veremos de nuevo.",
"Por favor, cuando quieras.",
"Estoy buscando espaldas fuertes para añadir a mi triuplación.",
"¿Tienes un momento para hablar?",
"Lo siento. Ya me estaba yendo, ",
". Ya nos veremos.",
"Sí, a decir verdad, estuvo aquí. ",
"Ewan Glover",
" se marchó hace poco en compañía de alguna dama. Si puedes quedarte, ",
", estoy seguro de que volverá pronto.",
"Gracias. Esperare aquí.",
"Oh, normalmente este lugar está lleno de hombres dispuestos a zarpar si el barco es el adecuado. Pero ya es tarde. Empezarán a llegar por la mañana\n ¿Quizás te gustaría alquilar una habitación y esperar?",
"Muy bien. ¿Tiene una habitación libre?",
"Podría hacer eso, pero primero tengo algunas otras preguntas.",
"Tengo una habitación o dos. ¿Cuánto tiempo esperas quedarte?",
"Hasta mañana.",
"Solo hasta esta noche.",
"Bien, bien. Serán 5 piastras.",
"Es justo. Aquí tienes.",
"Eso es más de lo que puedo permitirme. Supongo que pasaré la noche en el salón comun con los otros pobres y tacaños.",
"¿Qué incluye eso, mi propia bailarina privada? Olvídalo. No será la primera vez que pase una noche en el salón de una taberna.",
"Lo pensaré.",
"Te costará 5 monedas de oro.",
"Muy bien, aquí está tu dinero",
"Eso es más de lo que quiero pagar por una noche de alojamiento. Si es necesario, descansaré con la cabeza apoyada en una de las mesas de la taberna.",
"¿Qué incluye eso, mi propia bailarina privada? Olvídalo. No será la primera vez que pase una noche en el salón de una taberna.",
"Lo pensaré. Hablemos de otra cosa.",
"¡Caballeros, por favor! ¡Parad de una vez o llamaré a la guardia!",
"Está bien, relájate. Me marcho.",
"Sí, lo recuerdo. Un buen tipo, y un buen cliente. Pagaba generosamente cada vez que venía.",
"¿Sabes dónde está ahora?",
"No estoy seguro de adónde fue, pero es posible que pueda decirte por qué se fue...",
"Por favor, hazlo. ¡Es vital que lo sepa!",
"Bueno, se rumorea que el joven español trató de hacerle la corte a la hija del gobernador. No sé lo que pasó, pero cuando volvió aquí estaba de un humor de perros. A la mañana siguiente, él y su yate se habían ido, y nadie lo ha visto desde entonces.",
"¿La hija del gobernador? El hombre tiene buen gusto, ¿no? ¿Hay alguna posibilidad de que pueda hablar con ella, o su padre la vigila demasiado de cerca?",
"Oh, ten por seguro que cuando no la está vigilando, paga  aalguien para que lo haga por él. Bueno, tiene sus razones, ¿no? Es una chica muy guapa. De vez en cuando sale a pasear fuera de la ciudad, pero siempre está escoltada por varios guardias.",
"Esos guardias no deberían ser un problema; no tengo la intención de secuestrarla ni nada de eso, solo quiero hacerle unas cuantas preguntas. Gracias, Charles, has sido de gran ayuda.",
"Eh, ¿adónde fueron?",
"Lo siento, ¿puedes especificar un poco más a qué te refieres?",
"¿Has visto al gobernador retirado y a su hija Caroline?",
"Por aquí, capitán; estoy seguro de que te están esperando.",
"Gracias, Charles. Estoy en camino.",
"Eh..., hum, no puedo encontrarlos. Tienes que darme una pista, Charles.",
"Bueno, ¡je, je! Hay un atajo que lleva a la residencia de Woodes Rogers. Por favor, ponte detrás del mostrador, capitán.",
"Cuidado con esa risita tuya, Windem...",
"Tú otra vez, ¿qué estás haciendo en mi habitación privada? ¿No los has encontado, a pesar de mis instrucciones?",
"¡Por última vez, viejo, cuida tu lengua y abre la puerta de las habitaciones del gobernador!",
"Esa puerta está cerrada por una razón, y además, un poco de cortesía sería de agaradecer.",
"¿Qué razón? ¿Y podrías, por favor (o te mataré en 2 segundos) abrir la puerta?",
"Van a comenzar algunas reparaciones de toda la casa hoy. Y no señor, a esta hora del día tengo que descansar un poco del trabajo de la taberna.",
"Tal vez un poco de oro podría compensarte de este terrible problema",
"Entonces, serán 5 piezas de oro.",
"Aquí están. ¡Date prisa y abre la puerta de una vez!",
"Hum, parece que no tengo monedas por el momento, pero te pagaré más tarde, te lo aseguro.",
"Llevo un negocio, capitán. Dame el dinero o la puerta permanece cerrada.",
"------",
"¿Tienes botellas vacias en la taberna?", 
"¿Botellas vacias? ¡No hay problema, capitán, toma estas!",
"Gracias, Windem.",
"¿Botellas vacias? No hay problema, capitán, pero primero necesitas un botiquín.",
"Volveré pronto.",
"¿Qué es eso que he oído decir sobre cierta persona, #skid# de una rica familia local, que va a emparentar por matrimonio con la nobleza española?",
"¡Es verdad! ",
", hijo",
", hija",
" del mercader ",
", se ha comprometido con ",
"la hija",
"el hijo",
" del gobernador de #sSantiago#.",
"¿Dónde vive ",
"? Me gustaría ofrecer mis felicitaciones en persona, tal vez también ofrecer mis servicios.",
"Solo tienes que atravesar la puerta a la siguiente parte de la ciudad y estarás mirnado directamente a la casa. Una grande, que descuella por encima d ela pared de nuestro Ayuntamiento; es imposible no verla.",
"¡Gracias!",
"¿Has oído algo sobre cierta persona, #sperson#, en concreto #sromance#, que llegó a la ciudad en manos de una banda armada?",
"¡No! De hecho, #sromance# se casó recientemente con #svillain#.",
"¡Casados!",
"Sí. A mí me encargaron proveer la comida y la bebida para la recepción. Eso sí, en mi trabajo he aprendido a distinguir una sonrisa genuina de una forzada, y si #sromance# estaba feliz con el enlace, me comeré el sombrero de alguien.",
"Si, eso probablemente explicaría por qué llegó aquí a la fuerza.",
"¿Ha estado ocurriendo algo interesante en #sRedmond# últimamente?",
"Bueno, está el matrimonio de #sromance# con #svillain#. La boda en sí tuvo lugar en #sSantiago#, pero también hubo una fiesta aquí.",
"¡Debe haber sido una gran fiesta!",
"Sí, #svillain# trajo un cargamento de vino francés. No me preguntes cómo lo consiguio, con la guerra\n Pero, debido a la guerra, muchos se negaron a probarlo por patriotismo, lo que fue bueno para mí porque vinieron aquí a beber en su lugar\n Tal vez podrías comprar el vino barato y venderlo en otro sitio.",
"Una idea interesante. Veré qué puedo hacer al respecto. ¡Gracias!",
};