string DLG_TEXT[78] = {
"...",
"Vaya, parece que tienes una gran flota. Es una pena que no haya lugar para mí, ¿no?",
"¡Hola, #sfriend#! ¿Eres capitán, por casualidad?",
"Sí, lo soy. ¿Por qué preguntas?",
"Fuera de mi vista, pimpollo. No me sirves de nada.",
"Muy bien. Volveré más tarde.",
"Este podría ser un día de suerte para los dos. Me estoy preparando para emprender una empresa bastante arriesgada, y tengo la sensación de que tú y yo podríamos asociarnos.",
"¿Cómo de arriesgada?",
"Digamos que el beneficio hace que merezca la pena el peligro. ¿Te gustaría hacerte con un verdadero montón de oro?",
"¿Es una pregunta trampa? Sigue hablando.",
"Ya corro bastantes riesgos en mi día a día como para ir buscando más. Lo siento.",
"¡Ja! Sabía que eras la clase de #sgender# indicada para el trabajo. Escucha: todo lo que tenemos que hacer es desembarcar en un lugar seguro y tomar el oro. ¡Un plan brillante!",
"Me parece que has pasado por alto dos puntos muy importantes. Primero: ¿deembarcar dónde? Segundo: ¿quitarle el oro a quién?",
"Todos esos detalles están resueltos, te lo aseguro. Pero no puedo revelar el resto del plan hasta que esté segura de que somos socios. ¡Una vez que estemos en camino, te lo contaré todo!",
"Supongo que no tengo nada que perder. ¿Cuándo estarás lista para zarpar?",
"Lo siento. No tengo tiempo que perder en una búsqueda inútil.",
"¡Cuanto antes mejor! Mi barco ya me espera en el puerto. Únete a mi y nos dirigiremos a #sisland_Oxbay#.",
"Bien. Voy a resolver mis asuntos aquí y me uniré a ti. Por cierto, ¿cuáles son tus condiciones?",
"Lo típico: repartiremos el botín equitativamente entre nuestras tripulaciones.",
"Es justo. Muy bien, nos vemos en el puerto.",
"¡La mitad del trabajo ya esta hecho, camarada! Todo lo que tenemos que hacer ahora es capturar las minas, y el oro será nuestro.",
"¿Oro #sEnglish#? No dijiste que era oro #sEnglish#.",
"¿Y?",
"No importa.",
"No, no. Lo entiendo, yo tampoco quiero problemas con el gobierno #sEnglish#. Pero si seguimos mi plan al pie de la letra, nadie sabrá que estuvimos aquí.",
"Espera. ¿Estás diciendo que deberíamos matarlos a todos? ¿Ese es tu 'brillante plan'?",
"¡Exactamente!",
"Debería haberlo sabido. Mira, tómatelo con calma, y tal vez no tengamos que derramar sangre.",
"¡Ha sido un verdadero pandemonium, camarada!",
"Es cierto. Pero no veo ningún oro.",
"Tienes razón. ¡Rayos! Ya lo han enviado. Date prisa, las huellas de los carros siguen frescas. Aún podemos alcanzarlos. Estoy segura de que llevan el oro a #sOxbay#, como siempre.",
"Supongo que hemos ido demasiado lejos como para dar marcha atrás. ¡Vamos tras ellos!",
"¡No! Ya he tenido suficiente de esta locura! Lamento haberme involucrado en tu descabellado plan.",
"¡Si capturamos ese convoy, donaré personalmente una cruz de oro gigante a la Iglesia!",
"¡Deja de parlotear! No van a esperarnos.",
"¡No! Somos socios. ¡Me ayudarás a llegar hasta el final o te atravesare!",
"Inténtalo. ¡Veremos si te quedan ganas de luchar!",
"Está bien, está bien. No tengo estómago para más peleas.",
"¡Ahí están! ¡No debemos dejar que se escapen!",
"¡Adelante!",
"¡Maldición! ¡Los perdimos! Maldita sea tu incompetencia, ahora tendremos que irnos sin nada.",
"¡Y rápido, antes de que decidan darse la vuelta y perseguirnos! Supongo que esto disuelve nuestra sociedad.",
"¡Lo conseguimos!",
"Sí, pero ahora tenemos que salir de aquí, y nunca lograremos abrirnos camino luchando de vuelta a los barcos.",
"Cierto. Necesitamos un plan. No podemos dejar que este oro se nos escurra de las manos.",
"¿Qué tal esto? Enviamos un par de hombres a los barcos para que los guíen a una bahía cercana.",
"Bien, bien. Eso es lo que haremos. ¡Ahora, salgamos de aqui, deprisa!",
"...",
"Estamos en el lugar indicado y nuestros barcos están aquí. Todo lo que tenemos que hacer es cargar el oro. Llevará un tiempo, así que tendremos que esperar.",
"Silencio. Oigo voces. ¡Parece que vamos a tener compañía!",
"¡Uf! ¡Menudo día! Finalmente podemos cargar el oro y emprender la huida.",
"Bien. La mitad para ti y la otra para mí, tal y como acordamos.",
"Creo que no. Esta empresa ha resultado mucho más arriesgada de lo que me hiciste creer. Así que voy a necesitar una parte mayor de las ganancias.",
"No exactamente. Casi haces que me maten con tu 'brillante plan'. Me llevaré todo el oro.",
"¡Excelente! Eres #sgender# de palabra. El oro que hemos conseguido vale ",
" piezas de oro. Así que tu parte asciende a ",
" piezas de oro.",
"No está mal para un día de trabajo.",
"No está nada mal. ¿Qué te parecería seguir con esta asociación y navegar juntos?",
"Me parece bien.",
"No creo que sea una buena idea.",
"Me alegra oírlo.",
"Bienvenida a la tripulacion entonces, ",
". Ahora volvamos a nuestros barcos.",
"Pondré rumbo de vuelta a #sIsla Muelle#, entonces. Puedes encontrarme allí si me necesitas.",
"Muy bien.",
"¿Aún sigues considerando mi oferta?",
"Sí, no la he olvidado.",
"No, ya lo he decidido. Bienvenida a mi tripulación.",
"¡Excelente! ¡No hay límite a lo que tú y yo podemos lograr juntos!",
"Sí, sí. Pero, por ahora, tenemos muchos asuntos de los que ocuparnos.",
"¡¿Qué?! ¡Recibirás tu mitad y punto, o te rajaré aquí mismo!",
"Relájate. Estaba... bromeando. La mitad es suficiente para mí.",
"No te lo estoy pidiendo, te lo estoy diciendo. ¡Necesito una parte mayor!",
"¡Por encima de mi cadáver!",
"¡Yo no podría haberlo dicho mejor! ¡En guardia!",
"¡Me resultas familiar, casi ocmo un espejo! ¿Eres capitán como yo, por casualidad?",
"¡No tienes derecho a usar esa cara! ¡Desaparece antes de que te la arranque!",

};
