string DLG_TEXT[49] = {
"¿Qué opinas de nuestro último combate? ¡No recuerdo nada parecido!",
"!Sí! ¡Fue una gloriosa carnicería! ¡Y lo que nos espera ne el futuro! Así es nuestra vida, amigo mío.",
"¡Si quieres pelear de nuevo, necesito algunos hombres que desembarquen conmigo la próxima vez que toquemos tierra!",
"Necesitas un uniforme mejor.",
"Debo suministrar armas a nuestra brigada de abordaje.",
"Si, capitán. ¿Cuántos hombres quieres que te acompañen?",
"Un hombre será suficiente.",
"2 hombres. Tengo algunos asuntos en la ciudad y no quiero problemas.",
"3 hombres. Necesito una escolta decente.",
"4 hombres. Debemos estar alerta.",
"5 hombres. Esta isla puede ser peligrosa.",
"6 hombres. Quizás tengamos que atravesar selvas peligrosas en esta isla.",
"7 hombres. Tendremos que atravesar selvas peligrosas.",
"8 hombres. ¡No me gusta esta maldita isla!",
"9 hombres. Esta isla parece muy peligrosa y probablemente tendremos que luchar.",
"10 hombres, ¡y prepárarlos para un asalto!",
"Si, capitán. Solo un hombre te acompañará a tierra.",
"Si, capitán. Dos hombres te acompañarán a tierra.",
"Si, capitán. Tres hombres te acompañarán a tierra.",
"Si, capitán. Cuatro hombres te acompañarán a tierra.",
"Si, capitán. Cinco hombres te acompañarán a tierra.",
"Si, capitán. Seís hombres te acompañarán a tierra.",
"Si, capitán. Siete hombres te acompañarán a tierra.",
"Si, capitán. Ocho hombres te acompañarán a tierra.",
"Si, capitán. Nueve hombres te acompañarán a tierra.",
"Si, capitán. Diez hombres te acompañarán a tierra.",
"!Bien!",
"He cambiado de opinión.",
"Necesito practicar esgrima. Crucemos espadas amistosamente, #slad#.",
"¿Quieres que sea suave contigo, capitán?",
"Sí, estoy un poco oxidado. Muéstrame lo básico.",
"No, estoy listo para ti. ¡Muéstrame de qué eres capaz, marinero!",
"Cuando tú me digas, capitán.",
"No os meéis en los pantalones, muchachos.",
"Sí, camarada. Vamos a ello.",
"Lo siento, capitán. ¿Necesitas tiempo para recuperar el aliento?",
"Uf, esta vez me has pillado, capitán. ¿Puedo tomarme un descanso?",
"Claro. Podemos bailar en otro momento. Ahora ve a descansar.",
"No. Un poco mas, por favor. Necesito estar en buena forma para el próximo abordaje.",
"¿Podrías darme alguna información?",
"Por supuesto que puedo, capitán. ¿Qué necesitas saber?",
"Me gustaría saber qué hora es.",
"No importa, acabo de acordarme. Continúa.",
"#ssir#, ahora son las ",
". ¿Quieres que esperemos un rato?",
"No, ahora es tan buen momento como cualquier otro. ¡Vamos!",
"Sí, esperaremos una hora más.",
"Sí, esperaremos 3 horas más.",
"Sí, esperaremos 8 horas más.",
};
