string DLG_TEXT[49] = {
"їQuй opinas de nuestro ъltimo combate? ЎNo recuerdo nada parecido!",
"!Sн! ЎFue una gloriosa carnicerнa! ЎY lo que nos espera ne el futuro! Asн es nuestra vida, amigo mнo.",
"ЎSi quieres pelear de nuevo, necesito algunos hombres que desembarquen conmigo la prуxima vez que toquemos tierra!",
"Necesitas un uniforme mejor.",
"Debo suministrar armas a nuestra brigada de abordaje.",
"Si, capitбn. їCuбntos hombres quieres que te acompaсen?",
"Un hombre serб suficiente.",
"2 hombres. Tengo algunos asuntos en la ciudad y no quiero problemas.",
"3 hombres. Necesito una escolta decente.",
"4 hombres. Debemos estar alerta.",
"5 hombres. Esta isla puede ser peligrosa.",
"6 hombres. Quizбs tengamos que atravesar selvas peligrosas en esta isla.",
"7 hombres. Tendremos que atravesar selvas peligrosas.",
"8 hombres. ЎNo me gusta esta maldita isla!",
"9 hombres. Esta isla parece muy peligrosa y probablemente tendremos que luchar.",
"10 hombres, Ўy prepбrarlos para un asalto!",
"Si, capitбn. Solo un hombre te acompaсarб a tierra.",
"Si, capitбn. Dos hombres te acompaсarбn a tierra.",
"Si, capitбn. Tres hombres te acompaсarбn a tierra.",
"Si, capitбn. Cuatro hombres te acompaсarбn a tierra.",
"Si, capitбn. Cinco hombres te acompaсarбn a tierra.",
"Si, capitбn. Seнs hombres te acompaсarбn a tierra.",
"Si, capitбn. Siete hombres te acompaсarбn a tierra.",
"Si, capitбn. Ocho hombres te acompaсarбn a tierra.",
"Si, capitбn. Nueve hombres te acompaсarбn a tierra.",
"Si, capitбn. Diez hombres te acompaсarбn a tierra.",
"!Bien!",
"He cambiado de opiniуn.",
"Necesito practicar esgrima. Crucemos espadas amistosamente, #slad#.",
"їQuieres que sea suave contigo, capitбn?",
"Sн, estoy un poco oxidado. Muйstrame lo bбsico.",
"No, estoy listo para ti. ЎMuйstrame de quй eres capaz, marinero!",
"Cuando tъ me digas, capitбn.",
"No os meйis en los pantalones, muchachos.",
"Sн, camarada. Vamos a ello.",
"Lo siento, capitбn. їNecesitas tiempo para recuperar el aliento?",
"Uf, esta vez me has pillado, capitбn. їPuedo tomarme un descanso?",
"Claro. Podemos bailar en otro momento. Ahora ve a descansar.",
"No. Un poco mas, por favor. Necesito estar en buena forma para el prуximo abordaje.",
"їPodrнas darme alguna informaciуn?",
"Por supuesto que puedo, capitбn. їQuй necesitas saber?",
"Me gustarнa saber quй hora es.",
"No importa, acabo de acordarme. Continъa.",
"#ssir#, ahora son las ",
". їQuieres que esperemos un rato?",
"No, ahora es tan buen momento como cualquier otro. ЎVamos!",
"Sн, esperaremos una hora mбs.",
"Sн, esperaremos 3 horas mбs.",
"Sн, esperaremos 8 horas mбs.",
};
