string DLG_TEXT[40] = {
"Si quieres pedir algo de beber, habla con el dueño. Está detrás del mostrador.",
"Gracias por el consejo.",
"Disculpa, pero no he podido evitar oírte hablar del tren de la plata.",
"Esa clase de charla puede traer problemas. Así que, suponiendo por un momento que hayas oído bien, ¿qué quieres?",
"Nada en particular. Pero si pides una botella de vino, Salvadore querrá que te la lleves arriba. Y si haces eso, me reuniré contigo allí.",
"Está bien, no me vendría mal una botella de vino. Sobre todo, con la compañía adecuada.",
"Aquí podemos hablar en privado. Si quieres hablar sobre el tren de la plata, es seguro hacerlo.",
"Está bien. ¿Qué sabes sobre el tren de la plata?",
"No mucho, solo que, una vez que alcance la ciudad, estará fuera de tu alcance. Será embarcado en botes bien vigilados y trasladado al fuerte\n El fuerte de #sCartagena# sería un hueso duro de roer incluso en el mejor momento y, créeme, ¡cuando la flota de la plata está anclada a su lado, no es el mejor momento!",
"Entonces, me estás diciendo que el tren de la plata no puede ser atacado ni en la ciudad ni en el fuerte.",
"Así es. Tu única oportunidad será mientras atraviesa la selva. Los que mejor conocen la selva son los indios de la zona. Y es a ellos a los que quiero ayudar.",
"¿Por qué necesitan ayuda y cómo me ayuda todo esto a llegar hasta el tren de la plata?",
"Su aldea está asolada por la enfermedad. No pueden permitirse comprar medicinas y no hay nadie dispuesto a dárselas gratis\n Si tú aceptas llevar un cargamento de medicinas a la playa cercana, concertaré una reunión para que puedas entregárselo  alos indios, y estoy segura de que podré persuadirlos para que a cambio te guíen hasta el tren de la plata.",
"¿De qué tamaño de cargamento estamos hablando?",
"Cuanto más grande mejor, pero al menos 100 cajas.",
"¡Es es mucho!",
"Aquí las medicinas son muy caras, pero quizás sea más barato si las compras en otra colonia y las traes hasta aquí. ¡Y vas a nacesitar el espacio de todos modos, si planeas hacerte con toda es plata!",
"Cierto. Muy bien, conseguire las medicinas.",
"Cuando las tengas, vuelve a hablar conmigo. No menciones el tren de la plata. ",
"Dime que me quedaría mejor un vestido azul. Esa será la señal de que lo tienes otdo listo para entregar las medicinas a los indios.",
"Un vestido azul, ¿eh? Ahora que lo dices, creo que te sentaría muy bien. Pero no lo volveré a mencionar hasta que tenga tus medicinas.",
"¡Parece que es su día de suerte! Porque resulta que ya tengo a bordo un cargamento de medicinas.",
"¡Oh, qué bien! Espera un par de días y navega hasta la playa. Hablaré con mis amigos y me encargaré de que algunos indios se reúnan contigo allí.",
"Muy bien, seguro que encuentro alguna forma de pasar los próximos dos días.",
"No tengo suficiente espacio a bordo para tanta medicina.",
"Entonces, tampoco tendrás suficiente para cargar toda la plata del tren de la plata, ¿no crees? ¡No esperarás llevártela en el bolsillo!",
"Tienes razón. Lo intentaré cuando tenga un barco más grande.",
"Si consigues hacerte con un barco más grande o hacer hueco para las medicinas, vuelve a hablar conmigo. No menciones el tren de la plata. ",
"Me gustaría charlar contigo, si no estuviera tan ocupada. ¡Un buen día para la taberna no siempre es un buen día para hablar!",
"Te dejaré volver al trabajo. Pero tengo que decirte una cosa: estarías mucho más guapa con un vestido azul.",
"...",
"Muy amable por tu parte. ¿Por qué no alquilas una habitación para esta noche? Me reuniré contigo cuando tenga tiempo.",
"¡Te estaré esperadno!",
"¡Hola de nuevo! ¿Tienes las medicinas para la aldea india?",
"Sí. 100 cajas, como me pediste.",
"Hum... No.",
"¿Qué? ¡Confié en ti! ¡No volveré a repetir ese error!",
"Lo siento, pero otros asuntos tienen prioridad. Adiós.",
"¡Otra vez tú! ¡No quiero seguir hablando contigo!",
"No me importa. Hay otras tabernas con personal más agradable.",
}