string DLG_TEXT[40] = {
"Te doy la bienvenida a bordo, ¿capitán...?",
"Capitán ",
"Sé perfectamente lo que estás buscando: a la señorita Elizabeth Shaw.",
"Cierto. ¿Quién te lo ha dicho?",
"El gobernador de #sPhilipsburg#. Se podría decir que trabaja para mí.", // TALISMAN-to remove Wrong Governor name-Dickman not used by game
"Entiendo. Tenía la sensación de que me ocultaba la verdad. ¿Pero por qué secuestraste a la hija del gobernador Shaw? ¿Para pedir un rescate?", 
"No soy un pirata como los demás, capitán; estaba buscando amor y lo he encontrado desde que la conocí.",
"¿Y ella te ama?",
"Humm... humm... No por ahora, pero me amará en el futuro. Parece que todavía no se ha hecho a la vida a bordo...",
"¿Sí? Tal vez pueda resolver tu problema.",
"¿Cómo?",
"Ponla temporalmente bajo la autoridad del gobernador de #sPhilipsburg# y a cambio convenceré al gobernador Shaw para que deje de intentar traerla de vuelta a #sisland_Cayman#. Como prueba de buena voluntad, déjeme llevarla a #sPhilipsburg#.",
"¡NO!... Es demasiado arriesgado... No me fío de ti.",
"¿Por qué? Mientras te esperaba, un miembro de la tripulación me dijo que te gustaba jugar a los dados.",
"Sí, pero ¿por qué hablas de esto ahora?",
"¿Por qué no jugamos y quienquiera que gane lleva a Elizabeth Shaw a #sPhilipsburg#.",
"¡NO!... Aceptaré tu sugerencia de ponerla bajo la autoridad del gobernador de #sPhilipsburg#. Pero yo la llevaré allí.",
"¿Tienes miedo de jugar conmigo?",
"¿Estás bromeando? Me considero el mejor jugador. Toma el cubilete y los dados, te voy a dar una lección.",
"¿Cuántas rondas?",
"Sólo una. ¡Vamos a jugar! Apuesto cuatro cuatros.",
"Humm... Apuesto cuatro cincos.",
"¡Ajá! ¡Siete cincos!",
"¡Ocho cincos!",
"¡Mientes! !Muéstrame tus dados!",
"Tengo cuatro cincos y tú también. Perdiste.",
"¡Maldición! Está bien, puedes llevártela, pero no trates de engañarme o te mataré.",
"Entendido, nos vemos en #sPhilipsburg#.",
"¡Rata traidora! ¿Crees que puedes engañarme y salirte con la tuya?",
"¡Lo Siento, capitán!",
"¿Y crees que voy a perdonarte por lo que hiciste?",
"No me arrepiento de lo que hice, sino de lo que voy a hacer.",
"¿¡Qué has hecho!?",
"Sabes muy bien lo que hice. Elizabeth me dijo durante el viaje que solo puedes pisar tierra firme una vez cada diez años, asi que cuando te vi cerca de la orilla, inmediatamente pensé en empujarte hacia el agua. Ahora, no puedes volver a capturarla.",
"Maldita sea tu estampa, ",
"¿Realmente pensaste que podrías escapar de mí y seguir navegando por los mares como is nada? Muy osado, ",
"Hum...",
"Ja, ja... ¡Trato hecho! No volverás a saber de mí, capitán ",
", ¡a menos que se rompa nuestro acuerdo!",
"Es bueno saberlo.",

};
