string DLG_TEXT[46] = { 
"Encantado de conocerte, ",
". Estoy ",
", y estoy a su Servicio.",
"Soy el Capitan ",
".",
"Bueno verte de nuevo, ",
".",
"!Eres tu! Esperaba no volver a ver tu cara por aqui.",
"Buenos dias a TI tambien, ",
".",
"Supongo que no es tu dia de suerte, ",
"?Te gustaria ver lo que tengo en stock?",
"Asegurese. Echemos un vistazo.",
"Tarde. Ahora mismo, necesito hablar.",
"En otra ocasion.",
"?Vamos a hacer un trato, o solo quieres comprar algunos suministros?",
"Quiero vender algunas mercancias.",
"Me gustaria comprar algo de equipo.",
"Nada, gracias. Bye!",
"?De que quieres hablar?",
"Estoy escuchando.",
"Me pidieron que le entregara un cargamento.",
"?Necesita un capitan, Senor? Tengo una nave excelente, y puedo entregar cualquier carga, donde quieras.",
"No tengo tiempo para hablar ahora.",
"No, no necesito tus servicios. No mientras hundes barcos franceses.",
"En ese caso, adios.",
"Lo siento, pero no tengo nada para TI en este momento.",
"Volvere mas tarde, entonces.",
"Lo siento, pero su nave no es lo suficientemente grande para que usted pueda hacer el trabajo que tengo en mente.",
"Volvere mas tarde, entonces.",
"!Oh! Iba a pedirte que me hicieras un favor. La cosa es, necesito un poco de carga entregado a ",
"y tan pronto como sea posible. Si conduces para hacerlo en un mes, recibiras ",
"oro cuando llegues. ?Te parece justo?",
"Definitivamente me gusta.",
"No puedo aceptarlo.",
"Ya te he dicho hoy que no tengo nada para TI.",
"Oh, lo siento.",
"Has recordado tu tarea un poco tarde, ?no crees? Cogere la mercancia de todos modos, pero no esperes que me paguen. Prestar mas atencion la proxima vez! Despedir.",
"Despedida.",
"!Oh! Lo he estado esperando por mucho tiempo. Aqui esta tu recompensa, mi buen ",
"Siempre Bienvenido.",
"Lamentablemente, no necesito sus servicios en este momento.",
"Siento oir eso. Entonces hablemos de otra cosa.",
"Me niego a comerciar con una persona de su reputacion y relaciones. Ahora salir, ",
", antes de que llame a los guardias.",
"Muy bien.",

};