string DLG_TEXT[18] = {
".....",
".....",
"?Cuando zarpamos hacia #sPhilipsburg#?",
"Nunca.",
"?Que?! Pero este asesino me dijo que me llevabas a #sPhilipsburg#.",
"No parece que te guste Davy Roy.",
"?Estas bromeando? Nunca lo amare.",
"Facil de adivinar.. De hecho, estoy trabajando para tu padre y estoy aqui para TI.", 
"!DIOS TE RECOMPENSE!",
"En este caso, sera tu padre. Pero no debemos perder tiempo, tenemos que navegar a #sisland_Cayman# lo mas estrategia posible. No creo que tu Carter se vaya a quitar de TI tan facilmente.",
"Por fin, te has despertado.",
"Si, pero ?que paso?",
"?No recuerdas?",
"Si, Davy Roy me pedazos.",
" Si, pero la bala, afortunadamente, solo te rasguno la cabeza y te desmayaste.",
"Acto...y Davy Jones?",
"Se fue rapidamente de la isla. Y poco despues, la guarnicion del fuerte llego al puerto y lo vio estirado. Ahora parece que estas restaurado, deberias ir al Ayuntamiento y hablar con mi padre. Tiene tu recompensa esperandote.",
"!Son buenas noticias!",

};
