string DLG_TEXT[76] = { 
"Aparentemente te preocupas mucho por los asuntos en Europa. Me complace ver eso. Mi nombre es",
" Y soy emisario especial para",
".",
"Me llamo ",
".",
"Ah, eres tu otra vez. ?Que te trae por aqui esta vez?",
"Me gustaria hablar con usted sobre algunos asuntos",
"Lo siento, pero hay cosas que tengo que hacer",
"Ser el unico funcionario en el Caribe para mi nacion exige mucho tiempo. Que te trae a mi que es tan importante?",
"Me gustaria hablar con usted acerca de un pequeno negocio",
"Solo estoy aqui para presentar mis respetos, #saddr#. Nada mas",
"En ese caso, deje mi estudio y dejeme volver a asuntos mas importantes",
"Si, por supuesto. Lo siento, te moleste",
"Lo siento, pero no tengo nada de que hablar en este momento",
"Ah, si? Tengo una propuesta para usted, capitan",
"En efecto?",
"Aprendi que completo la tarea con exito; felicidades, capitan! Aqui tiene su recompensa",
"Mi agradecimiento; fue un placer ayudarte",
"Debes destruir el",
" buque",
"pirata de busqueda",
"amenazando el envio",
". Si la hundes, te recompensare con la fuerte suma de",
"Oro. Que dices, capitan?",
"No volveras a oir de ella, que te lo prometo",
"Me temo que no puedo ayudarte",
"Anhelo el perdon, su Excelencia",
"Estoy interesado en aprender sobre #sgov_nation# relaciones con otras naciones",
"Estoy buscando una letra de la marca",
"He oido que estoy en ascenso",
"Ya no puedo servir",
", su excelencia.",
"Estoy por servir",
"Como seguro de que usted es un capitan capaz, y de recompensar mi tiempo en presentar su caso a",
", Debo pedirte para",
" oro.",
"De ninguna manera.",
"Muy bien.",
"#sgov_nation# siempre esta complacido de aceptar nuevos capitanes en su servicio.",
"Actualmente estamos en guerra con",
"",
"No hay gran poder, pero",
". Por supuesto, ",
"Los piratas siempre deben ser hundidos a la vista",
"A la luz de su servicio anterior",
"Te otorga el rango de",
"Te hare sentir orgulloso, Excelencia",
"Has hecho dano",
", y",
"no se olvida de sus enemigos. Vete de una vez, o los guardias te echaran en la oreja!",
"...",
"Has causado",
" gran dano, capitan, pero",
" esta dispuesto a pasar por alto sus transgresiones pasadas ... por un precio:",
"Muy bien, senor. Acepto",
"Un placer hacer tratos con usted, ",
"Y usted, su Excelencia",
"Lo eres! Excelente trabajo. Tu nuevo rango es",
". Ademas, eres galardonado",
" acres de tierra por orden de",
"Gracias Senor.",
"Estas seguro, ",
" lamentare perder su servicio",
"Si lo soy.",
" no le da la bienvenida a las chaquetas",
"Uh, no importa",
"Muy bien. Pero espero que reconsidere, a tiempo ...",
"Adios, ",
"Eh?",
"Dificil.",
"Cuales son tus ordenes, #saddr#?",
"Debo manejar esta colonia",
"?Conoces algunas hostilidades en aguas cercanas, #saddr#?",
"Hay cosas que tengo que hacer",

};
