string DLG_TEXT[76] = { 
"Aparentemente te preocupas mucho por los asuntos de Europa. Eso me complace. Mi nombre es ",
" y soy el emisario especial de ",
".",
"Me llamo ",
".",
"Ah, eres tú otra vez. ¿Qué te trae por aquí esta vez?",
"Me gustaría hablar con Su Excelencia sobre algunos asuntos",
"Lo siento, pero tengo cosas que hacer",
"Ser el único funcionario de mi nación en el Caribe exige mucho tiempo. ¿Que es tan importante como para trarte a mi presencia?",
"Me gustaría hablar con Su Excelencia acerca de un pequeño negocio",
"Solo estoy aquí para presentar mis respetos, #saddr#. Nada más",
"En ese caso, por favor, sal de mi estudio y déjame volver a asuntos más importantes.",
"Sí, por supuesto. Siento haber molestado a Su Excelencia.",
"Lo siento, pero no tengo nada de qué hablar ahora mismo",
"Oh, ¿sí? Tengo una propuesta para ti, capitán.",
"¿De veras?",
"Me he enterado de que has completado la tarea con éxito; ¡mi enhorabuena, capitán! Aquí está tu recompensa.",
"Muchas gracias; ha sido un placer ayudar a Su Excelencia.",
"Debes destruir un barco de ",
" vessel ",
"quest pirate",
", que amenaza el tráfico marítimo en aguas de ",
". Si lo hundes, te recompensaré con la considerable suma de ",
" piezas de oro. ¿Qué dices, capitán?",
"Prometo a Su Excelencia que no volverá a saber de ese barco.",
"Me temo que no puedo ayudar a Su Excelencia.",
"Suplico el perdón, Excelencia.",
"Me gustaría saber más acerca de las relaciones de #sgov_nation# con otras naciones.",
"Quiero conseguir una patente de corso.",
"He oído que se me ha concedido un ascenso.",
"No puedo seguir sirviendo a ",
", Excelencia.",
"Me he hartado de servir a ",
"Como garantía de tus capacidades como capitán, y para compensar el tiempo que voy a perder en presentar tu caso a ",
", debo pedirte ",
" piezas de oro.",
"De ninguna manera.",
"Muy bien.",
"#sgov_nation# siempre se complace en aceptar nuevos capitanes a su servicio. ",
"Actualmente estamos en guerra con ",
"",
"... ninguna gran potencia, pero ",
". Por supuesto, ",
"los piratas siempre deben ser hundidos en cuanto sean avistados.",
" A la luz de tus anteriores servicios, ",
"te otorgo el rango de ",
"Haré que Su Excelencia se sienta orgulloso.",
"Has dañado los intereses de ",
", y ",
" no olvida a sus enemigos. ¡Vete inmediatamente, o los guardias te echarán a patadas!",
"...",
"Has causado a ",
" grandes daños, capitán, pero ",
"está dispuesta a pasar por alto tus transgresiones pasadas... por un precio: ",
"Muy bien, Excelencia. Acepto.",
"Un placer tratar contigo, ",
"Y con Su Excelencia.",
"¡En efecto! Excelente trabajo. Tu nuevo rango es ",
". Además, se te concede un premio de ",
" acres de tierra por orden de ",
"Gracias, Excelencia.",
"¿Seguro, ",
" lamentará perder tus servicios.",
"Sí, seguro.",
" no ve con buenos ojos a los chaqueteros, ",
"Hum..., no he diho nada.",
"Muy bien. Pero espero que lo reconsideres, con tiempo...",
"Adiós, ",
"¿Eh?",
"Se siente.",
"¿Cuáles son lus órdenes, #saddr#?",
"Debo administrar esta colonia",
"¿Hay alguna noticia de hostitlidades en aguas cercanas, #saddr#?",
"Tengo cosas que hacer",

};
