string DLG_TEXT[230] = {
"Por casualidad no necesitarбs un ofical, їverdad, capitбn?",
"їUn oficial? їY quй sabes hacer?",
"No, tengo suficientes oficiales por ahora",
"Bueno, la gente dice que hago un buen trabajo como ",
". Contrбtame para tu barco, capitбn, y podrбs comprobarlo en persona.",
"їCuбnto pides?",
"Lo siento, pero ya tengo ",
".",
"їHas cambiado de opiniуn, capitбn? їHas decidido que, despuйs de todo, podrнa serte ъtil como ",
"?",
"Sн, tal vez. їCuбnto quieres?",
"Te equivocas. ЎAdiуs!",
"Creo que podemos ponernos de acuerdo en ",
" piezas de oro.",
"їNo crees que eso es demasiado por tus servicios?",
"Estoy de acuerdo. Consнderate parte de mi tripulaciуn.",
"Tъ no vales tanto. Adiуs",
"Estб bien. Creo que entonces podrнa aceptar ",
" piezas de oro. їQuй te parece?",
"Eso estб mejor. Te doy la bienvenida a mi tripulaciуn",
"Sigo pensando que es demasiado. Adiуs",
"Lo lamento, capitбn, pero sй que valgo lo que pido. Si es demasiado caro para ti, busca a alguien que te pida menos.",
"Bueno... Te contratarй.",
"Eso es lo que harй. Adiуs",
"Gracias, capitбn. No lamentarбs gastar ese oro cuando me veas en acciуn",
"Eso espero.",
"ЎOye, parece que no tienes dinero! Lo siento, capitбn, pero no trabajo a crйdito.",
"ЎMaldita sea!",
"Permнtame terminar mi bebida primero, capitбn. Pero no te preocupes, te aseguro que estarй a bordo antes de zarpar.",
"Estб bien. Si tengo que esperarte, te mandarй a baldear las cubiertas.",
"ЎA la orden, ",
"No, descansa.",
"Te despido. ЎNo necesito tus servicios!",
"ЎComo tъ digas, capitбn! Pero ten esto en cuenta: si me despides, nunca regresarй a tu barco. Asн que tъ decides.",
"Bueno. He cambiado de opiniуn. Todavнa te necesito",
"ЎGenial! ЎDesaparece de mi vista!",
"Te lo dije, capitбn, no volverй. Tengo mi propio orgullo",
"ЎY yo tampoco te necesito!",
"En el prуximo abordaje, vendrбs conmigo.",
"їPor quй no te quedas a cubierto en el prуximo abordaje?",
"ЎPor supuesto!",
"Entonces, ha quedado claro.",
"Bien, me entretendrй persiguiendo ratas en la bodega.",
"ЎQuйdate aqui!",
"Sнgueme, Ўy hazlo rapido!",
"De acuerdo.",
"Buen trabajo, їeh? їCуmo de bueno?",
"Impresionante, їverdad?",
"Muy bien, ordenarй a la tripulaciуn que ice el pabellуn ",
".",
"Gracias.",
"Lo tendrй todo listo para seguirte en un momento, solo tengo que recoger mi equipaje. Te verй al otro lado de la siguiente puerta.",
"Genial, me vendrнan bien algunos refuerzos. ЎTe doy la bienvenida a la tripulaciуn!",
"En estos momentos, estamos sirviendo raciones de comida ",
" y raciones de ron ",
" . Tenemos suficiente comida para ",
" dнas y suficiente ron para ",
" dнas, si seguimos con las raciones actuales. їQuieres cambiar las raciones?",
"Sн, ordena servir raciones completas de comida y raciones normales de ron.",
"Sн, ordena servir medias raciones de comida y raciones normales de ron.",
"Sн, ordena servir raciones completas de comida y dobles raciones de ron.",
"Sн, ordena servir medias raciones de comida y dobles raciones de ron.",
"Muy bien, a partir de ahora serviremos raciones completas de comida y raciones normales de ron.",
"Muy bien, a partir de ahora serviremos medias raciones de comida y raciones normales de ron.",
"Muy bien, a partir de ahora serviremos raciones completas de comida y dobles raciones de ron",
"Muy bien, a partir de ahora serviremos medias raciones de comida y dobles raciones de ron.",
"Primero, tendrбs que dividir el botнn, capitбn ",
"Oh, entonces olvнdalo.",
"їUn salario? їSeguro, #ssir#? La tripulaciуn no se enrolу con esas condiciones.",
"Sн, seguro. ЎY no me importa cuбntos deserten!",
"їЎFirmar articulos!? їSeguro, #ssir#? La tripulaciуn no se enrolу con esas condiciones.",
"Sн, seguro. ЎY no me importa cuбntos deserten!",
"Muy bien, informarй a la tripulaciуn. Pero debo advertirte: es posible que algunos de ellos decidan desertar.",
"Muy bien, informarй a la tripulaciуn. Pero debo advertirte: es posible que algunos de ellos decidan desertar.",
"їQuй bandera quieres que hagamos ondear, capitбn?",
"Nuestro actual pabellуn ",
"La bandera pirata.",
"En cuanto al barco y la tripulaciуn...",
"En cuanto a mн...",
"En cuanto a ti...",
"їSн?",
"No importa.",
"їCuбl es el estado de nuestras provisiones?",
"Vamos a dejar de perseguir botines. Ahora, todos recibirйis un salario.",
"Vamos a firmar artнculos",
"Arrнa nuestro pabellуn; vamos a izar otra bandera.",
"їCuбl es el estado de nuestros barcos atracados?",
"Me parece que no encajo muy bien en este mundo...",
"Necesito cambiarme de ropa",
"Necesitas un mejor uniforme",
"Camarada, me temo que ya no necesito tus servicios. Harй que lleven tu cofre de marino a tierra en la prуxima escala que hagamos.",
"...",
"їSeguro, capitбn? Me gustarнa quedarme, si me aceptaras.",
"Sн, mi decisiуn estб tomada. Pero nunca se sabe, me gustarнa poder encontrarte si te necesito de nuevo.",
"Que nos volvamos a ver pronto, entonces. ЎViento en las velas y mares en calma, capitбn!",
"Te deseo lo mismo.",
"їQue clase de pirata eres, capitбn? En este momento, se te conoce como ",
" y actualmente no te informamos de los avistamientos, a menos que tengamos posibilidad de derrotarlos.",
" y actualmente te informamos de todos los barcos que divisamos.",
"Quiero dictar nuevas уrdenes con respecto al avistamiento de barcos enemigos.",
"Muy bien.",
" Ahora no te molestaremos informбndote si avistamos enemigos demasiado poderosos.",
" Ahora te informaremos de todos los avistamientos.",
"",
"Un ",
"",
"un ",
"",
"De acuerdo, como desees. їY debemos agregar algunos muebles, accesorios o equipamiento? Eso podrнa ser necesario para que el edificio realice una funciуn adecuada",
"No, solo el edificio tal cual.",
"Cancela esa orden, tengo que inspeccionar el terreno de construcciуn una vez mбs",
"ЎSн, buena idea!",
"Asн que erigiremos una",
" con un",
"Exacto, Ўponte manos a la obra!",
"Eh, lo siento, no sй con seguridad si este es un buen diseсo para este lugar. їY quй dijiste de nuestros recursos?",
"Iza el pabellуn ",
"Mis colores personales.",
"Justo aquн, frente a ti, їverdad? Muy bien. Tenemos ",
" unidades de tablas y de ladrillos respectivamente, y",
" piezas de oro para comprar otros materiales. Y permнteme recordarte que debes destacar a algunos de nuestros ",
" marineros para proteger y mantener cada edificio. Entonces, їquй te gustarнa construir?",
"Una caja semienterrada (como barricada improvisada o escondite para una trampa; requiere 2 tablas, 100 piezas de oro, 0 hombres).",
"Una empalizada de madera (fortificaciуn simple; requiere 10 tablas, 1000 piezas de oro, 5 hombres).",
"Un bastiуn revestido de piedra (equipado con un caсуn, una formidable fortificaciуn; requiere 30 tablas, 10000 piezas de oro, 15 hombres).",
"Una fortaleza (fortaleza para salvaguardar tus tesoros; requiere 30 tablas, 20000 piezas de oro, 15 hombres)",
"Una casa (como refugio y lugar de recreo, paga alquiler; requiere 20 tablas, 4000 piezas de oro y 3 hombres).",
"Un taller (base para una joyerнa, fundiciуn, astillero, destilerнa, etc.; requiere 20 tablas, 4000 piezas de oro y 3 hombres).",
"Una granja (sirve como refugio, produce trigo y cafй; requiere 30 tablas, 5000 piezas de oro, 10 hombres).",
"Un bosque (produce tablas y йbano; requiere 0 tablas, 1000 piezas de oro, 5 hombres).",
"Una mansiуn renacentista (se puede convertir en tu cuartel general o en una casa de mala nota; requiere 30 tablas, 20000 piezas de oro, 5 hombres).",
"Una mansiуn renacentista (se puede convertir en tu cuartel general; requiere 30 tablas, 20000 piezas de oro, 5 hombres).",
"Un observatorio (se puede convertir en tu cuartel general; requiere 30 tablas, 20000 G, 5 hombres).",
"*** Ranura en blanco para tus creaciones, Ўno la uses ahora! ('Producciуn' ; 20 tablas, 4000 piezas de oro, 5 hombres).",
"їHum? їLo he entendido bien? їHarбs consturir cualquier edificio que yo quiera? їAquн mismo? їTiene algъn sentido hacer eso?",
"Aplaza esa orden, tengo que inspeccionar el terreno de construcciуn una vez mбs.",
"Si tiene sentido o no depende totalmente de ti. TЪ eres el arquitecto de este edificio, tъ puedes crear este asentamiento. Si te apetece poner un astillero en una montaсa, un bosque en un ayuntamiento o un burdel en una iglesia, seguirй tus уrdenes y lo construirй. Pero no me culpes si desperdicias tu dinero en una ruina mal situada. Solo hay una limitaciуn: no podemos edificar mбs de 15 construcciones en un mismo lugar. Y si intentamos amontonar demasiadas casas en una ciudad que ya estй llena de gente, puede volverse superpoblada y ciertos personajes pueden dejar de aparecer.", 
"Hum... hum... їUn burdel en una iglesia? Quiйn sabe, podria ser una idea rentable. Pero, por ahora, sigamos adelante con la construcciуn aquн",
"Estб bien, їquieres que armemos esta fortificaciуn?",
"Esta bien, їquieres que armemos esta posiciуn?",
"Entonces, їquй te gustarнa agregar a tu edificio?",
"Un castillete sobre un pozo minero (convierte un taller en una joyerнa; requiere 10 tablas, 4000 piezas de oro, 5 hombres).",
"Una fundiciуn de balas de caсуn (convierte un taller en una fundiciуn; requiere 10 tablas, 4000 piezas de oro, 5 hombres).",
"Una destilerнa de ron (convierte un taller en una destilerнa; requiere 10 tablas, 4000 piezas de oro, 5 hombres).",
"Un muelle de carena (convierte un taller en astillero; requiere 10 tablas, 4000 piezas de oro, 5 hombres).",
"Un caсуn (para armar una fortificaciуn; requiere 0 tablones, 5000 piezas de oro, 3 hombres).",
"Un puesto de mercado (convierte una casa en un puesto comercial, se alquila al doble de precio; requiere 5 tablas, 5000 piezas de oro, 3 hombres).",
"Muebles lujosos (mejora la posibilidad de йxito en el tratamiento de heridas en casas y granjas; requiere 5 tablas, 1000 piezas de oro, 1 hombre).",
"Etablecimiento para Entretenimiento de Caballeros de Madame Monique (produce 'dividendos', atrae a marineros que pueden ser reclutados; requiere 5 tablas, 1000 piezas de oro, 1 hombre).",
"Un despacho (como tu cuartel general, para recibir agentes y contratar oficiales; 5 tablas, 1000 piezas de oro, 1 hombre).",
"Hum, ignora todo lo que he dicho despuйs de 'buenos dнas', tengo que volver a repasar los planos.",
"*** Ranura en blanco para tus creaciones, Ўno la uses ahora! (; Tablas, oro, hombres).",
"Hum, #ssir#, tu proyecto de",
" requiere ",
" tablas y ladrillos respectivamente, ",
" piezas de oro y ",
" hombres. Pero, como te dije antes, solo tenemos ",
" tablas, ",
" piezas de oro y ",
" hombres...",
"Huy... Ha habido un pequeсo... Esto... ЎMaldito sea ese arquitecto, el muy cretino me dio los planes equivocados! No me lo puedo creer No importa, descansa mientras vuelvo a repasar los croquis...",
"Trae a algunos hombres con palas y hachas, quiero erigir un edificio. ЎAquн y ahora!",
"Ў#ssir#, tenemos que aсadir algo a este edificio para que tenga algъn uso!",
"Dйjame revisar los planos y decidir lo que quiero.",
"Deja izada mi bandera personal.",
" con",
"Voy a cambiarte de puesto en el barco.",
"Sн, capitбn, їdуnde me necesitas?",
"Te voy a poner a cargo de la tripulaciуn, contramaestre.",
"ЎEncбrgate de los caсones, condestable!",
"Ahora eres responsable de trazar nuestro rumbo, piloto.",
"ЎTe voy a ascender a primer oficial!",
"Encбrgate de la gestiуn diaria del barco como intendente.",
"Necesito que seas el nuevo carpintero.",
"Necesito tus habilidades como cirujano.",
"Necesito tu fuerte brazo para ayudarme en combate.",
"Pensбndolo mejor, quйdate como estбs",
"ЎA la orden, capitбn!",
"Prosigue con tus labores.",
"Camarada, me temo que ya no necesito tus servicios. Harй que lleven tu cofre de marino a tierra en la prуxima escala que hagamos, y aquн estбn las ",
" piezas de oro que te debo.",
"Hablame de las finanzas del barco.",
"ЎSн, #ssir#! Actualmente le debemos a la tripulaciуn ",
" piezas de oro, y a los oficiales, ",
". Sobre la base de la tripulaciуn que tenemos a dнa de hoy, estamos pagando",
" piezas de oro al mes para la tripulaciуn, y",
" piezas de oro al mes para tus oficiales.",
"! їOcurre algo?",
"Tengo una cosa muy especial, dicen que sirve de ayuda. їPodrнas tomarla, por favor?",
"En cuanto a...",
"Vamos a realizar una entrega de contrabando y necesito saber el horario de patrulla de los guardacostas.",
"Siempre se puede preguntar a algunos de los guardias en la taberna, podrнan divulgar la informaciуn. Pero yo tambiйn podrнa echar un vistazo en tu lugar e informarte de cuбl es el mejor momento",
"Voy a probar suerte con los guardias.",
"ЎMe gusta tu forma de pensar! Pregunta por ahн, discretamente, explora las costas; hagas lo que hagas, vuelve a informarme aquн en un dнa. ЎY ten cuidado!",
"Lo siento, no pude descubrir cuбl es el mejor momento para la operaciуn de contrabando. Habнa demasiados guardias",
"їAsн que he esperado un dнa entero por nada? Bueno, supongo que lo hiciste lo mejor que pudiste.",
"Pude recopilar informaciуn y creo que el mejor momento para una operaciуn de contrabando serнa ",
"Estб bien, volverй maсana.",
"Solo necesito recoger mi equipaje. Ve delante, te alcanzarй lo antes posible.",
"Es hora de repartir un poco de alegrнa entre los hombres y dividir el botнn, ",
".",
"Es un honor que me permitas servirte, capitбn. Si aъn no has vendido los barcos de tus oficiales, y toda su mercancнa y sus caсones, quizбs deberнas hacerlo primero, antes de volver a hablar conmigo. En la situaciуn actual, la parte del botнn de cada tripulante serб de ",
" piezas de oro. No me cabe duda de que la tripulaciуn estarб ",
"; y tu parte asciende a ",
" piezas de oro. El capital inicial para tu prуxima expediciуn serб de ",
". Tendrбs que empezar a reclutar tripulaciуn de nuevo. їSeguro que quieres dividir el botнn, capitбn?",
"Sн.",
"No.",
"Muy bien, seguro que la tripulaciуn estarб ",
" con su parte. ЎBuena suerte en tu prуxima expediciуn!",
"Gracias.",
"Sн, capitбn. Supongo que ahora mismo solo quieres repartir el oro, їverdad?",
"Sн, solo dividir el oro, pro favor. La tripulaciуn debe recibir su paga sin importar cuбl sea nuestra situaciуn actual.",
"Creo que es hora de dar este viaje por concluido y empezar a planear una nueva expediciуn.",
"Muy bien.  ",
"Con nuestros nъmeros actuales, la parte de cada tripulante serб de ",
" piezas de oro. Seguro que la tripulaciуn estarб ",
"; y tu parte asciende a ",
" piezas de oro. ",
"Tambiйn te quedarбn ",
" piezas de oro para gastos inmediatos. їQuieres proceder con la diviisуn, capitбn?",
"Como desees, capitбn. Si aъn no has vendido los barcos de tus oficiales, y toda su mercancнa y sus caсones, quizбs deberнas hacerlo primero, antes de volver a hablar conmigo. En la situaciуn actual, la parte del botнn de cada tripulante serб de ",
"Muy bien, seguro que la tripulaciуn estarб ",
" con su parte.",
"Gracias por tu ayuda.",
"Creo que es hora de revisar tu salario.",
"Gracias, capitбn. He estado intentando progresar en mis habilidades.",
"Lo estбs haciendo bien, pero todavнa no estбs ahн.",
"Te mereces un aumento de salario como recompensa por tu buen trabajo. Sigue asн.",
"A partir de ahora, recibirбs un salario como el resto de mis oficiales.",
};
