string DLG_TEXT[53] = { 
"!Ayuda! !Estan tras de mi, por favor, ayuda!",
"#ssir#, tienes que ayudarme!",
"!Por favor, amigo, debes ayudarme contra estos churls!",
"?Que esta pasando aqui?",
"?De que se trata?",
"?Cual es el problema?",
"!Estos estilistas ale-soused quieren violarme! !No soy una muneca de porcelana, pero no puedo encargarme de todos por mi mismo!",
"!Estos cerdos de engorde piensan solo con su mal olor! Tienes que ayudar a ensenarles una leccion!",
"Yo estaba caminando por la playa, como lo hago a menudo, cuando estos LIS-Liverpool troncos de humores me atacaron a mi y a mis amigos y se les metio en la cabeza de ojos de cebolla que les sacarian sus panuelos a latigazos. Les ayudaria a librarse de esos horribles tumores, !pero necesito su ayuda!",
"Ah, entiendo.",
"!Ja, realmente mostramos a esos cerdos! Es bueno saber que todavia hay almas buenas y valientes en este mundo, #ssir#. !Muchas gracias por su ayuda!",
"!Tres pecadores mas para la Serpiente de la Antiguedad! Estoy muy agradecido por la ayuda, #ssir#! Uno casi espera que podamos volver a unir 1.200 en el futuro.",
"!Piensa en conocer a un caballero de brillante armadura aqui! Muchas gracias, #ssir#, no me las habria arreglado sola.",
"Solo hay una manera de tratar a las ratas de sentina como estas.",
"Solo tengo un poco de dinero. Por favor tomelo como muestra de mi gratitud.",
"Agradecer. X para ser mas vigilantes en el futuro.",
"!Les dire a todos que me ayudaste! !Sabran lo valiente #sgentleman# y feroz luchador que eres!",
"Agradecer. Ten cuidado en el futuro.",
"Tengo solo algunas monedas. Por favor, tomalos, es lo menos que puedo hacer.",
"Gracias. Encuentrame si hay mas papeleo que necesite el extremo puntiagudo de una espada.",
"!No estes tan nervioso, amigo! Solo bromeaba. Nos vamos.",
"!Muy bien, muy bien! Hemos cambiado de opinion. No eres mas que una vieja arpia.",
"Eres todo un heroe, ?verdad? Bueno, esta vez puede que hayas ganado, pero vamos a estar tendiendo por TI, maldito bastardo.",
"Ahora lo has pedido...",
"Asi que arruinarias nuestra diversion, ?eh? Bueno, vamos a estropear sus menudillos.",
"Es bueno ver que has hecho la eleccion correcta. Ahora con vosotros!",
"No hay vuelta atras ahora. !Nos vemos en el lago de fuego, muchacho!",
"Miedo de nosotros, matey? Me temo que no puedo dejar de salir con vida!",
"Lo siento, pero no puedo ayudarla, senorita.",
"Podrias haber dejado las cosas como estaban, pero ahora pagaras con el precio... en la sangre!",
"!Esto es cosa tuya! !Muere!",
"Asi que eso es todo, ?eh? !Te haremos 100.000! !Te cortaremos el higado y lo asaremos en nuestra fogata!",
"!Pruebalo!",
"!Ja, realmente mostraste a esos cerdos! Es bueno saber que todavia hay almas buenas y valientes en este mundo, #ssir#. !Muchas gracias por su ayuda!",
"!Tres pecadores mas para la Serpiente de la Antiguedad! Estoy muy agradecido por la ayuda, #ssir#! Aunque no soy un asesino, tal vez aprendere de su valiente ejemplo contra tal vileza.",
"!Piensa en conocer a un caballero de brillante armadura aqui! Muchas gracias, #ssir#, no me las habria arreglado sola.",
"!Malditos sean tus ojos!",
"?Quieres que nos rindamos a tu lameculos culo? Te haremos cosquillas en las costillas. El dinero es facil de quitarle a un cadaver.",
"!Los dientes de Dios!",
"?Tu otra vez? Te dejamos ir una vez. Ahora vete, muchacha, antes de que cambiemos de opinion.",
"Asi que has encontrado mas oro en tus bolsillos para compartir con nosotros, ?eh? !Magnifico! !Har-har!",
"!Ahora si que me has hecho un rastrillo a la popa, #slad#! !Sal de mi vista antes de que te hurgue los rinones con mi poniard!",
"!Muy bien, me voy! .",
"!He pensado en ello, y he vuelto para darte lo que te mereces!",
"?Que quieres? Fuera de aqui!",
"Vete de aqui! !Dejennos a nuestro negocio! No volver!",
"!Vete, maldito infeliz! O por Dios pagaras un precio muy caro por tu peepin.",
"Ya me voy, amigos.",
"Tus malas acciones no queden impunes!",
"!Alejate de mi! Quiero vivir! Fuera de aqui!",
"!Ayuda! #spronoun#'s un loco! !No quiero morir!",
"!Perdoname! !No soy mas que un humilde filcher! !Soy demasiado joven para morir!",
"!Vivirias mas si te sentaras en tu casa en tu mecedora, amigo!",

};