string DLG_TEXT[306] = { 
"Saludos. No nos conocemos, pero te ofrezco mi humilde consejo.",
"Sí, con mucho gusto.",
"No necesito tu consejo.",
"Saludos, caminante. ¿Adónde vas?",
"Oh, solo voy a ocuparme de mis asuntos.",
"No es asunto tuyo.",
"Buenos días, visitante. ¿Qué tal te va?",
"Bien, gracias.",
"No tengo tiempo para hablar contigo.",
"Hola. No te he visto aquí antes. ¿Has venido en barco?",
"Sí, acabo de atracar aqui.",
"No tengo tiempo para hablar contigo.",
"Saludos, visitante. Me alegra verte por aquí.",
"Hola.",
"Disculpa, pero no puedo hablar contigo en este momento.",
"Saludos, navegante. ¿Quieres oír un buen consejo?",
"Buenos días. Habla.",
"No tengo tiempo que perder.",
"Buenos días, visitante. Tengo algunas cosas que pueden interesarte.",
"Negociemos, entonces.",
"No tengo tiempo para hablar contigo.",
"Buenos dias, visitante. ¿Tu tripulación sigue resultando herida en desagradables, pero lucrativos 'accidentes'? ¡Puedo ofrecerte un simple vendaje para detener sus hemorragias al precio de oferta de 120 piezas de oro por unidad!",
"La verdad es que no puedo permitirme perder a mi tripulación. ¡Me lo llevo! Y me aseguraré de hablar contigo de nuevo si necesito más.",
"120 piezas de oro, ¿eh? Creo que los he visto más baratos en la tienda de la ciudad. ¡Y allí los conseguiré si los necesito!",
"Buenos dias, navegante. Me hallo en circunstacnias penosas. ¿No me ayudarás?",
"Hum, ¿por qué debería...?",
"Ese es tu problema.",
"#stitle#, ¿no vas a ayudar a esta pobre alma con un par de monedas?",
"Por supuesto, la Iglesia nos enseña a ayudar a nuestro prójimo.",
"Aparta, pobre #sperson#, y no me molestes más.",
"Mi #stitle#, ¡no me dejes en tanta pobreza! Dame una moneda, por favor, para que pueda comprar comida.",
"No te preocupes, pobre criatura. Aquí tienes 10 monedas.",
"Aparta, pobre #sperson#, y no me pidas más.",
"Buenos días. Veo que eres una persona audaz, ¿supongo que te metes en muchas peleas?",
"Sí, por supuesto.",
"Eso es asunto mío. Adiós.",
"Hola. No me encuentro a menudo con personas tan respetables aquí. ¿Eres capitán?",
"Sí, ¿qué puedo hacer por ti?",
"¿Sabes? Tengo prisa. Adiós.",
"Buenos días. ¿Estás paseando por aquí sin nada urgente que hacer?",
"En general, sí. Será un placer hablar contigo.",
"No, tengo mucho que hacer.",
"Te advierto que ni siquiera las ciudades están a salvo del crimen en estos tiempos. El 'Padrino del Archipiélago', el notorio Nathan Kell, ha organizado bandas de matones y ladrones que gobiernan las calles. Así que ten cuidado si caminas por la ciudad, cualquiera que lleve un arma puede asaltarte, incluso si parece un ciudadano honrado a primera vista.",
"Gracias por tu consejo.",
"Hoy en día hay muchos matones peligrosos que rondan por las calles. Vigila atentamente a los transeúntes: cualquiera que lleve un arma puede ser un criminal. Si quieres evitarlos mantente lejos de las calles principales.",
"Prefiero enfrentarme a ellos.",
"No me interesan este tipo de consejos. Adiós.",
"Si tienes que luchar contra ellos, trata de aislar a algunos de ellos y alejarlos de sus compañeros para que no te abrumen con superioridad numérica. O toma posición en un pasaje estrecho donde tus flancos estén protegidos. Y trata de enfrentar a los enemigos que llevan armas de fuego en una lucha a espada antes de que tengan la oportunidad de disparar contra ti.",
"Muy bien, lo recordaré.",
"Viajar a pie se ha vuelto muy peligroso recientemente. Hay muchos corsarios tan cortos de dinero que se dedican a robar a los viajeros. Incluso en las ciudades, ya no estás a salvo. Muchas personas hoy en día son asesinadas en sus casas o en callejones donde los guardias no patrullan, y si no es un ciudadano local sino viajeros como tú y yo, nadie mueve un dedo para atrapar al asesino. Pero después de cada asesinato los guardias se vuelven muy vigilantes durante algún tiempo y despejan las calles de todos esos criminales.",
"Sí, ¿algo más?",
"No tengo tiempo para hablar contigo.",
"Muchos viajeros con pinta de vagabundos o mendigos son en realidad comerciantes ricos que llevan mucho dinero encima. Se disfrazan de pobres porque los viajeros ricos sufren robos a menudp.",
"Gracias.",
"Los guardias del pueblo no son más que un puñado de holgazanes y cobardes corruptos. Solo la peor escoria de los ejércitos europeos se ofrece para servir en estas colonias dejadas de la mano de Dios. Por lo general, hacen la vista gorda si hay una pelea, solo interfieren si algún ciudadano influyente está siendo atacado. Pero si se sienten amenazados, contraatacan con miedo ciego, y atacan a cualquiera que empuñe una espada, a menudo confundiendo amigo y enemigo en su pánico.",
"Muy interesante, gracias.",
"El contrabando es un negocio floreciente aquí, y muchas cuevas y bodegas son utilizadas por los contrabandistas como escondite y para almacenar mercancíua ilegal. Ten cuidado, no les gustan los visitantes sin invitación. Pero de vez en cuando tambien puede toparte con civiles desarmados en esos escondites, generalmente vecinos que comercian con los contrabandistas. Aunque matar a gente desarmada nunca es bueno, nadie te culpará si uno de esos compradores acaba muerto en una pelea. Sin embargo, mantente en guardia; a veces pueden volverse contra ti y tomar un arma..., especialmente si has... esto... regresado de muy lejos para seguir donde lo dejaste.", // ccc apr15 NK 4-24
"Muy bien, tendré cuidado de atacar solo a los que desencainen con intención hostil. No quiero que ningún daño colateral empañe mi reputación, ¿eh?", // ccc apr15
"Ten cuidado cuando entres en una taberna y mantén tu mano en la empuñadura de tu espada. Muchos marineros se vuelven pendencieros cuando están borrachos, y es muy posible que te encuentres con una pelea. Y si te metes en una pelea de taberna, aprovecha las mesas y bancos para proteger tus flancos.",
"Buen consejo, gracias.",
"Estas islas fueron una vez el dominio de las temibles tribus Alkellani. Pero los colonos de Europa les han tomado la tierra fértil a los Alkellani, y los pocos nativos que quedan viven al borde de la inanición en refugios dispersos por la selva. Tienen costumbres extrañas, estos salvajes: sus más feroces guerreros llevan máscaras espantosas y vestimentas hechas de piel humana seca.",
"Como los caníbales, ¿eh? Haré lo posible por evitarlos.",
"Si me das veinte monedas, le diré a todo el mundo lo amable que eres. No te dejes engañar por las apariencias; aunque sea pobre, tengo muchos amigos, que siempre se alegrarán de verte aquí.",
"¿Desperdiciar dinero solo para que los mendigos hablen de mí? Pues no, gracias.",
"¿Sí? Muy bien, veinte monedas de oro no son tanto para dar a #sperson# con tal necesidad.",
"Te agradezco lo que has hecho. Te ofrezco las gracias que tengo. Bebe este remedio mágico; te devolverá la salud.",
"Gracias a ti también.",
"Gracias. Tengo poco para mostrar mi gratitud, pero al menos toma este objeto. Tal vez encuentres un buen uso para él.",
"Con mucho gusto.",
"Gracias, #sperson#.",
"No hay de qué.",
"Capitán, ¿me aceptarías a bordo de tu barco? Hace mucho que sueño con participar en emocionantes batallas navales y largos viajes oceánicos.",
" Por supuesto. Serás mi oficial.",
"No, no necesito nuevos marineros.",
"Págame, y te enseñaré un par de trucos para vencer a cualquiera en un combate mano a mano. ¿O te gustaría aprender algunos movimientos defensivos?",
"No necesito tu consejo. Ya sé todo eso, y hasta podría ser yo quien te lo enseñara a ti.",
"Muéstrame tus movimientos ofensivos.", // ccc oct06
"No necesito tu consejo. Ya sé todo eso, y hasta podría ser yo quien te lo enseñara a ti.",
"Muéstrame tus movimientos defensivos.", // ccc oct06
"Gracias, pero no necesito ayuda ahora.",
"Hace algún tiempo yo también era navegante..., viví famosas aventuras. Puedo enseñarte mucho sobre cómo dirigir la tripulación de tu barco.",
"No necesito tu consejo. Ya sé todo eso, y hasta podría ser yo quien te lo enseñara a ti.",
"Sí, me gustaría saber más al respecto.",
"Gracias, pero no necesito ayuda ahora.",
"Yo tambien soy navegante..., piloto. Por unas monedas, compartiré mis secretos que te ayudarán a guiar mejor tu barco.",
"No necesito tu consejo. Ya sé todo eso, y hasta podría ser yo quien te lo enseñara a ti.",
"Sí, me gustaría saber más sobre las maniobras.",
"Gracias, pero no necesito ayuda ahora.",
"Soy artillero en un barco de guerra británico. Con gran placer, puedo enseñarte a calcular la trayectoria de una bala de cañón, y acertar a tu objetivo con cada tiro.",
"No necesito tu consejo. Ya sé todo eso, y hasta podría ser yo quien te lo enseñara a ti.",
"Dímelo, y pagaré todo lo que me pidas.",
"Gracias, pero no necesito ayuda ahora.",
"Soy artillero en un barco de guerra británico. Te puedo indicar cómo reducir el tiempo de recarga de tus cañones.",
"No necesito tu consejo. Ya sé todo eso, y hasta podría ser yo quien te lo enseñara a ti.",
"Dímelo, y pagaré todo lo que me pidas.",
"Gracias, pero no necesito ayuda ahora.",
"Soy artillero en un barco de guerra británico. Puedo contarte muchas historias sobre el arte del abordaje.",
"No necesito tu consejo. Ya sé todo eso, y hasta podría ser yo quien te lo enseñara a ti.",
"Dímelo, y pagaré todo lo que me pidas.",
"Gracias, pero no necesito ayuda ahora.",
"Trabajo en el astillero y lo sé todo sobre la reparación y construcción de barcos. Si me pagas, enseñaré a tu tripulación a reparar tu barco más rápido.",
"No necesito tu consejo. Ya sé todo eso, y hasta podría ser yo quien te lo enseñara a ti.",
"Dímelo, y pagaré todo lo que me pidas.",
"Gracias, pero no necesito ayuda ahora.",
"Soy comerciante. Puedo enseñarte algunos trucos comerciales que te ayudarán a aumentar los beneficios de todas tus transacciones.",
"No necesito tu consejo. Ya sé todo eso, y hasta podría ser yo quien te lo enseñara a ti.",
"Dímelo, y pagaré todo lo que me pidas.",
"Gracias, pero no necesito ayuda ahora.",
"¿Y bien? ¿Vas a pagarme ",
"?",
"Parece que no tengo suficiente dinero.",
"Te pagaré. Cuéntame tus secretos.",
"No, es demasiado.",
"¿Y bien? ¿Vas a pagarme ",
" por mis secretos de esgrima?",
"Parece que no tengo suficiente dinero.",
"Te pagaré. Cuéntame tus secretos.",
"No, es demasiado.",
"¿Y bien? ¿Vas a pagarme ",
"?",
"Parece que no tengo suficiente dinero.",
"Te pagaré. Cuéntame tus secretos.",
"No, es demasiado.",
"¿Y bien? ¿Vas a pagarme ",
" por mis secretos de la defensa?",
"Parece que no tengo suficiente dinero.",
"Te pagaré. Cuéntame tus secretos.",
"No, es demasiado.",
"¿Y bien? ¿Vas a pagarme ",
"?",
"Parece que no tengo suficiente dinero.",
"Te pagaré. Cuéntame tus secretos.",
"No, es demasiado.",
"¿Y bien? ¿Vas a pagarme ",
" por mis lecciones en la dirección de la tripulación?",
"Parece que no tengo suficiente dinero.",
"Te pagaré. Cuéntame tus secretos.",
"No, es demasiado.",
"¿Y bien? ¿Vas a pagarme ",
"?",
"Parece que no tengo suficiente dinero.",
"Te pagaré. Cuéntame tus secretos.",
"No, es demasiado.",
"¿Y bien? ¿Vas a pagarme ",
" por mis secretos de la maniobra?",
"Parece que no tengo suficiente dinero.",
"Te pagaré. Cuéntame tus secretos.",
"No, es demasiado.",
"¿Y bien? ¿Vas a pagarme ",
"?",
"Parece que no tengo suficiente dinero.",
"Te pagaré. Cuéntame tus secretos.",
"No, es demasiado.",
"¿Y bien? ¿Vas a pagarme ",
" por mis lecciones de precisión con cañones?",
"Parece que no tengo suficiente dinero.",
"Te pagaré. Cuéntame tus secretos.",
"No, es demasiado.",
"¿Y bien? ¿Vas a pagarme ",
"?", 
"Parece que no tengo suficiente dinero.",
"Te pagaré. Cuéntame tus secretos.",
"No, es demasiado.",
"¿Y bien? ¿Vas a pagarme ",
" por los secretos de la recarga de cañones?",
"Parece que no tengo suficiente dinero.",
"Te pagaré. Cuéntame tus secretos.",
"No, es demasiado.",
"¿Y bien? ¿Vas a pagarme ",
"?",
"Parece que no tengo suficiente dinero.",
"Te pagaré. Cuéntame tus secretos.",
"No, es demasiado.",
"¿Y bien? ¿Vas a pagarme ",
" por mis consejos sobre el abordaje?",
"Parece que no tengo suficiente dinero.",
"Te pagaré. Cuéntame tus secretos.",
"No, es demasiado.",
"¿Y bien? ¿Vas a pagarme ",
"?",
"Parece que no tengo suficiente dinero.",
"Te pagaré. Cuéntame tus secretos.",
"No, es demasiado.",
"¿Y bien? ¿Vas a pagarme ",
" por mis secretos de reparación?",
"Parece que no tengo suficiente dinero.",
"Te pagaré. Cuéntame tus secretos.",
"No, es demasiado.",
"¿Y bien? ¿Vas a pagarme ",
"?",
"Parece que no tengo suficiente dinero.",
"Te pagaré. Cuéntame tus secretos.",
"No, es demasiado.",
"¿Y bien? ¿Vas a pagarme ",
" por mi asesoramiento comercial?",
"Parece que no tengo suficiente dinero.",
"Te pagaré. Cuéntame tus secretos.",
"No, es demasiado.",
"Gracias, eres muy amable.",
"No hay de qué.",
"¿Heridas? ¿Terribles hemorragias? ¡Tengo más vendas si las necesitas! Solo tienes que decir una palabra.",
"Parece que mis lobos de mar no pueden cuidar de sí mismos. ¡Me llevaré otor!",
"Y la palabra es NO. Ya me voy.",
"¿Así que quieres negociar?",
"Sí, me gustaría comprar algo.",
"No, perdón por interrumpir.",
"¿Qué quieres? Pensé que lo habíamos dejado todo claro.",
"No, nada.",
"Tus órdenes, capitán.",
"Nada.",
"¿Quieres escuchar algun consejo?",
"Sí, me interesa escuchar lo que tengas que decir.",
"No, perdón por interrumpir.",
"Te advierto que ni siquiera las ciudades están a salvo del crimen en estos tiempos. El 'Padrino del Archipiélago', el notorio Nathan Kell, ha organizado bandas de matones y ladrones que gobiernan las calles. Así que ten cuidado si caminas por la ciudad, cualquiera que lleve un arma puede asaltarte, incluso si parece un ciudadano honrado a primera vista.",
"Gracias por tu consejo.",
"Hoy en día hay muchos matones peligrosos que rondan por las calles. Vigila atentamente a los transeúntes: cualquiera que lleve un arma puede ser un criminal. Si quieres evitarlos mantente lejos de las calles principales.",
"Prefiero enfrentarme a ellos.",
"No estoy interesado en este tipo de consejo. Adiós.",
"Si tienes que luchar contra ellos, trata de aislar a algunos de ellos y alejarlos de sus compañeros para que no te abrumen con superioridad numérica. O toma posición en un pasaje estrecho donde tus flancos estén protegidos. Y trata de enfrentar a los enemigos que llevan armas de fuego en una lucha a espada antes de que tengan la oportunidad de disparar contra ti.",
"Y además...",
"No tengo tiempo para hablar contigo.",
"Los guardias del pueblo no son más que un puñado de holgazanes y cobardes corruptos. Solo la peor escoria de los ejércitos europeos se ofrece para servir en estas colonias dejadas de la mano de Dios. Por lo general, hacen la vista gorda si hay una pelea, solo interfieren si algún ciudadano influyente está siendo atacado. Pero si se sienten amenazados, contraatacan con miedo ciego, y atacan a cualquiera que empuñe una espada, a menudo confundiendo amigo y enemigo en su pánico.",
"Parece que no puedo esperar ninguna protección de ellos.",
"El contrabando es un negocio floreciente aquí, y muchas cuevas y bodegas son utilizadas por los contrabandistas como escondite y para almacenar mercancíua ilegal. Ten cuidado, no les gustan los visitantes sin invitación. Pero de vez en cuando tambien puede toparte con civiles desarmados en esos escondites, generalmente vecinos que comercian con los contrabandistas. Ten cuidado de no lastimarlos, porque matar a gente desarmada siempre daña su reputación, sin importa dónde lo hagas.", // ccc apr15
"Muy bien, tendré cuidado de atacar solo a los que desencainen con intención hostil. No quiero que ningún daño colateral empañe mi reputación, ¿eh?", // ccc apr15
"Si tienes problemas con la ley por alguna razón, solo tienes que esconderte en algún lugar tranquilo por un tiempo. Las autoridades usualmente se calman rápidamente aquí en los trópicos, y hay tantos criminales sueltos que los guardias pronto olvidarán tu cara.",
"Buen consejo. Gracias.",
"Estas islas fueron una vez el dominio de las temibles tribus Alkellani. Pero los colonos de Europa les han tomado la tierra fértil a los Alkellani, y los pocos nativos que quedan viven al borde de la inanición en refugios dispersos por la selva. Tienen costumbres extrañas, estos salvajes: sus más feroces guerreros llevan máscaras espantosas y vestimentas hechas de piel humana seca.",
"Como los caníbales, ¿eh? Haré lo posible por evitarlos.",
"229",
"Lo siento, no sé nada de tráfico marítimo, y nunca hablo con marineros. Son gente muy pendenciera.",
"¡Sea lo que sea, soy inocente! Y todos mis parientes jurarán que estuve con ellos cuando sucedió.",
"¡Oh, no, eres tú! Ejem... Me alegro de volver a verte...",
"!Oh, tú otra vez! Eh..., ejem... Tengo mucho que hacer, debo irme...",
"¡Alto! ¡No irás a ninguna parte! ¡Me has robado mi dinero y los guardias se encargarán de ti!",
"¡Infame maleante, haré que te arresten aquí mismo!",
"¡Al único sitio al que vas a ir es a prisión, carterista!",
"Escucha, si corres te meterás en problemas, pero si me devuelves mis #smoney# piezas de oro, lo olvidaré todo.",
"Ten un poco de sensatez, lleguemos a un acuerdo: puedes quedarte con mi dinero, no me importa mucho el oro. Pero devuélveme el anillo de diamantes, es un regalo de mi esposa.",
"¡Cuidado! ¡Estás en peligro mortal! ¡Mi bolsa de dinero es una trampa CazaLadrones(TM) con una lanceta envenenada dentro!",
"¡Maleante, te cortaré la garganta aquí mismo!",
"¡Cortaré tus dedos ladrones con esta misma espada!",
"¿Te he dicho que esta antigua espada fue usada una vez para amputar las manos de los carteristas? ¿Probamos a ver si todavía está lo bastanta afilada para hacer su trabajo?",
"No lograrás nada aquí con métodos tan obvios. No tienes pruebas reales contra mí, y tengo buenas conexiones con las autoridades. ¡Vete al cuerno, imbécil!",
"Muy bien, así que tendré que recuperar mi dinero por otros medios. Tal vez debería matarte en el acto... Pero tal vez sea mejor esperar hasta que te atrape a solas...",
"¿Qué? Oh, no, en tu bolsa solo había... ¡Aarrgggh, me has pillado con la guardia baja! Estoy envejeciendo demasiado para este trabajo, mejor cambiaré de profesión y me dedicaré a la mendicidad honesta. ¿Me ayudarás a empezar una nueva vida y no me denunciarás? Aquí está tu dinero.",
"Muy bien. Te deseo más éxito en su nueva carrera profesional. Adiós.",
"Bueno, guárdate algo de oro para empezar tu nueva vida. Está bien, no hace falta que me lo agradezcas. Hasta la vista.",
"¡Oye, espera! ¡Cálmate, no hagas nada precipitado! Aquí te devuelvo tu dinero y, si me dejas libre, te daré esta hermosa pieza de joyería. ¿No es una obra maestra? ¿Qué me dices?",
"Seguramente es una obra maestra ROBADA, ¿eh? No, no tocaré un artículo que seguro que alguien está buscando. Escucha, te dejaré en paz si le devuelves esto a su legítimo dueño. ¡Y no intentes engañarme! Ya puedes irte.",
"Hum... ¿a que viene de repente tanta sumisión y generosidad? ¿O intentas corromperme con joyas robadas? Olvídalo, quédate con eso, solo quiero recuperar mi dinero.",
"Qué hermosura..., y botín robado, ¿verdad? Estás tratando de convertirme en cómplice, ¿eh? No, no caeré tan bajo, solo recuperaré mis posesiones legítimas.",
"¡Oh, realmente hermoso! ¡DAME ESO! Y ahora, piérdete.",
"Será mejor que no te pregunte cómo conseguiste esto, ¿a quién le importa? Muchas gracias, adiós.",
"¡Chist, no muestres estas cosas aquí en la calle! Pásame las monedas, y la piedra. ¡Pero discretamente, por favor!",
"(El borde de una bolsa bien llena asoma del bolsillo de tu nuevo conocido)",
"Oye, tu bolsa está a punto de caerse de tu bolsillo. Ten más cuidado con ella. ",
"(Lentamente, muy, muy lentamente metes tu mano en el bolsillo y agarras la bolsa)",
"(Más rápido que un relámpago, agarras la bolsa y huyes)",
"(Miras en otra dirección, con enfasis, pones cara inocente, silbas una melodía y agarras la bolsa sin mirarla)",
"(Finges tropezar, agarras la ropa de la víctima y sacudes la bolsa para sacarla del bolsillo)",
"(Dejas caer 'accidentalmente' al suelo tu inventario, y mientras tu víctima le ayuda a recoger tu equipo, le quitas la bolsa)",
"(Le preguntas a tu víctima si el hombre que tiene detrás es el notorio Barbanegra. Mientras tu víctima se da la vuelta horrorizada, le quitas la bolsa)",
"(¡Tienes la bolsa! Lleva una etiqueta: CazaLadrones(TM) )",
"¡¡AARGH!! ¡Los monederos CazaLadrones(TM) tienen trampas explosivas o lancetas envenenadas! ¡Será mejor que me dehaga de esta máquina de matar!",
"¡Bah! Algún imitador puso esa etiqueta en esta simple bolsa para asustar a los ladrones. ¡La abriré! ¡Sin riesgo no hay recompensa!",
"¿Qué? Y ya se lo he pasado a... ¡Maldicion, me pillaste! Pero no vas a recuperar tu bolsa por más que me des la tabarra, créeme, porque ya no la tengo. Trabajo en un equipo de carteristas. Yo robo, cierto, pero paso inmediatamente el botín a un corredor para que no me pillen con pruebas si me descubren. Y si lo que dices sobre el contenido de tu bolsa es verdad, nunca volveremos a ver a mi corredor. Así que no te servirá de nada si das la voz de alarma aquí. Sé razonable, si me dejas irme de rositas, te daré estas joyas como compensación.",
"No, insisto en que se haga justicia. Tal vez estás mintiendo y todavía tienes mi dinero. ¡Haré que te arresten aquí mismo!",
"Bueno, enviarte a la cárcel seguramente no cubrirá mis pérdidas, pero esa joya posiblemente lo hará. Pasámela y lárgate. ¡Y date prisa, antes de que cambie de opinión e intente recuperar mi dinero con mi espada!",
"269",
"Prefiero hablar de asuntos marítimos. Seguro que en tus viajes has aprendido mucho sobre eso, ¿no? ¿Hay algún mercante que siga las rutas de comercio costero? ¿O piratas que las acechen?",
"Me interesan las últimas noticias sobre el tráfico marítimo local. ¿Has oído hablar de algún barco pirata o mercante en los alrededores últimamente?",
"Solo me preocupa el tráfico marítimo local. Seguro que hablas con muchos marineros, ¿eh? ¿Han hablado de alguan vela extraña en el horizonte últimamente?",
"Ahora que preguntas, sí, hay algunos. Ten cuidado de notoparte con ellos, ¡je, je! Hay muchos peligros en el mar, ya sabes, yo prefiero quedarme en tierra. Siempre digo que si el Señor hubiera querido que paseáramos por los mares nos habría dado aletas y branquias, ¿eh? ¡Je, je!",
"Oh, hasta yo he avistado algunas velas mientras caminaba por los acantilados. Pero había demasiada neblina para identificarlas con exactitud. ¿Sabes?, para mí, todos los barcos se parecen.",
"Pues claro. Sienpre están las típicas historias de taberna que cuentan los marineros, diciendo que han escapado por los pelos de un terrible pirata que acechaba justo en la boca del puerto. Pero no me importa esa charla de borrachos, me preocupan más todos los ladrones y matones que acechan en tierra. ¡No creerías cuántos corsarios tratan de colarse en esta ciudad!",
"Oh, bueno, gracias por esta información tan esclarecedora. Tal vez debería hacer una labor de reconocimietno más detallada.",
"Bien, bien. Exploraré en persona las aguas costeras. Lamento haberte molestado.",
"¡En esta ciudad solo hay marineros de agua dulce sin remedio! Bueno, ¡sigue chupando polvo! Deja que los marinos nos ocupemos de las aguas.",
"¡Buenos días, capitaá! ¡Es tu día de suerte!",
"¿Qué quieres decir?",
"No me molestes si no quieres que te corte la garganta, camarada.",
"¡Tengo un secreto que vender! ¿Quieres ganar una fortuna, #sperson#?",
"¿A qué te refires? ¡Habla!",
"¡Escucha! ¡Un viejo pirata moribundo me dijo donde él y sus compañeros escondieron un tesoro robado a los españoles! Lo único que necesitas para ganar una fortuna es un buen barco y comida para el viaje. ¡Anímate, #sperson#!",
"¿Y por qué no vas tú a buscar el tesoro?",
"¡Porque no puedo dejar esta maldita isla y no tengo barco! Todos los piratas ya han desaparecido, ¡pero este tesoro tiene un gran valor!",
" está compuesto de oro, joyas, esmeraldas e ídolos de oro indios. ¿Te interesa o no, capitán?",
"¿Y cuánto quieres por este secreto?",
" piezas de oro",
"Aquí está el dinero. Dime dónde encontrar el tesoro. Espero que tu historia sea cierta. ¡De lo contrario, volveré para matarte!",
"No, es demasiado.",
"Espera un segundo y pregúntame de nuevo. Tengo que enderezarme el cuello de la camisa...",
"De acuerdo.",
"Hum... Te he visto antes..., durante una escaramuza naval hace algún tiempo, en el alcázar de un barco, creo... ¡Oye, tú eres ese demonio del Averno que pasó navegando cerca de nuestro barco! ¡Pensamos que tu barco era amistoso hasta el momento en que abriste tus portras, abriste fuego contra nuestro baroc y despué snos abordaste y masacraste a nuestra tripulación! !ALARMA! ¡Piratas disfrazados!",
"Debería haber matado a TODOS los testigos de mis piraterías pasadas...",
"296",
"¡Psst!... Oye, tengo algo aquí que te puede interesar.",
"Hum, claro, mueétrame lo que tienes.",
"No, no lo creo.",
"Lo siento, ",
"muchacho",
"moza",
", pero mi oferta era de las que se hacen una vez en la vida. ¡Ahora piérdete antes de que te atraviese!",
"...",
" piezas de oro, lo olvidaré todo.",

};
