string DLG_TEXT[52] = {
"Bienvenido a mi taberna!",
"seguro te hara sentir comodo",
"Gracias pero ",
"no necesita consolar",
"Ah, capitan",
"! Que coincidencia! Hace solo media hora, un tipo pregunto por tu paradero, un marinero de aspecto bastante duro. Dijo que era un viejo companero tuyo y queria unirse a ti como contramaestre. Todavia esta aqui, tomando una copa arriba. ",
"Ah, me encantaria beber y navegar con un viejo companero! Y tal vez sea un buen oficial ... Me reunire con el de inmediato",
"Umm ... considerando mi pasado sangriento, preferiria no encontrarme con ningun 'viejo companero'. Un corsario no tiene muchos viejos amigos, sino muchos viejos enemigos ...",
"Como puedo ayudarte?",
"Apuntame a la chusma en busca de trabajo. Necesito unos asesinos que no hacen demasiadas preguntas",
"Estoy buscando contratar algunos marineros para mi tripulacion",
"Tengo pocas manos. Conoces algun alquitran que busque un barco?",
"Tienes una habitacion libre? Me gustaria quedarme aqui por un tiempo",
"Necesito una habitacion limpia con una cama limpia. Nada lujoso",
"Me gustaria descansar aqui por un tiempo",
"No necesito nada en este momento. Adios",
"Bueno, solo nos hemos mudado recientemente a este edificio y nuestras futuras habitaciones aun no estan amuebladas, lo siento. Cuanto tiempo planearon quedarse?",
"Hasta la manana.",
"Solo hasta el anochecer",
"Por que no te pones comodo en ese banco en la esquina de alli? Aun no tenemos muchos clientes, asi que no te molestara tanto. Te traere una manta ...",
"Esta bien, eso servira para mi. Si uno puede dormir en la atmosfera humeda y desagradable de un barco abarrotado, ciertamente tambien se puede dormir aqui",
"Gracias. Eso es al menos mas comodo que una hamaca en una cubierta de armas llena de gente. Pero, por favor, sacuda las pulgas de esa manta, quieres?",
"Bueno, mejor que durmiendo en la playa ...",
"Hmm, tal vez prefiero quedarme en la casa de un amigo. Es decir, si puedo encontrar un amigo en esta ciudad ...",
"En ese caso, deberias hablar con ese tipo que acaba de entrar. Es un viejo perro de mar y conoce a todos y cada uno de los alquitranes de este hemisferio",
"Solo el hombre que necesito ..",
"Me temo que no hay marineros en alquiler aqui en este momento. Sera mejor que lo intentes de nuevo otro dia",
"Demasiado...",
"DLG_TEXT[28]",
"DLG_TEXT[29]",
"DLG_TEXT[30]",
"DLG_TEXT[31]",
"DLG_TEXT[32]",
"DLG_TEXT[33]",
"DLG_TEXT[34]",
"DLG_TEXT[35]",
"DLG_TEXT[36]",
"DLG_TEXT[37]",
"DLG_TEXT[38]",
"DLG_TEXT[39]",
"DLG_TEXT[40]",
"DLG_TEXT[41]",
"DLG_TEXT[42]",
"DLG_TEXT[43]",
"DLG_TEXT[44]",
"DLG_TEXT[45]",
"Cual es el ultimo chisme en la ciudad? Alguna noticia de las otras colonias?",
"Cual es el ultimo rumor?",
"Hay noticias?",
"DLG_TEXT [49]",
"DLG_TEXT [50]",
"DLG_TEXT [51]",
"Cual es el ultimo chisme en la ciudad? Alguna noticia de las otras colonias? [Regala una pieza de oro]",
"Cual es el ultimo rumor? [Dar una pieza de oro]",
"Basta de gibbering sin sentido! ?Sabes algo, que podria ser interesante para mi? [Dar una pieza de oro]",
"Tienes un primo llamado Sven?",
};