string DLG_TEXT[71] = { 
"¡Eh! ¿Qué estás haciendo en esta fortificación restringida del ejército? ¿Ha venido a espiarnos?",
"¡Por favor, perdóname la vida, te lo ruego! ¡Soy civil!",
"¡Déjame en paz! ¡No soy uno de esos brutos de uniforme!",
"¡Cierra el pico y piérdete!",
"¡Calla! ¡Debo largarme antes de que lleguen los refuerzos!",
"¡Fuera de mi camino! ¡Voy a enfrentarme a hombres de verdad!",
"¡Chist! Pareces un tipo inteligente, amigo. Tú y yo vamos a saquear todos los almacenes y cofres de este lugar, ¿eh? *GUIÑO*",
"¡Te cortaré en pedacitos si das la voz de alarma! Haz lo que digo y seguirás de una pieza.",
"¡Haz lo que te digo o morirás!",
"¡Te perdonaré tu miserable vida solo si cooperas!",
"¡Cálmate, amigo! ¿Te parezco alguien que haría daño a civiles? Confía en mi, nos llevaremos bien.",
"¡Está bien, está bien! ¿Qué quieres?",
"Créeme, no haré nada precipitado si tú tampoco lo haces. ¿Pero qué estás tramando?",
"¡Entendido! ¿Y ahora qué?",
"Está claro que no eres un soldado. ¿Quién eres?",
"Dime, ¿qué hace un civil en este fuerte tan celosamente guardado?",
"Solo quiero saber qué negocios te traen aquí.",
"Soy un enviado del Secretario de Guerra de Su Majestad, y estoy aquí para inspeccionar estas fortificaciones.",
"En ese caso, sé MI enviado y dile al gobernador que exijo la rendición inmediata e incondicional de la ciudad, o la bombardearé con estos mismos cañones. Tengo excelentes artilleros en mi tripulación, y convertirán al ayuntamiento en un montón de escombros.",
"Te dejaré vivir si me muestras dónde está escondida tu bolsa... Eso es, sé un buen chico... eh, enviado.",
"Ah, Señoría, me alegra encontrarme con una persona de tan alta categoría e importancia, aunque bajo circunstancias un tanto.. ejem... inusuales y, me temo, desagradables. Por favor, acepte Su Señoría mis más humildes disculpas por este desafortunado incidente que es, se lo aseguro, solo el resultado de un malentendido. En realidad vine aquí para buscar la paz y la amistad. Para probar mis buenas intenciones, no molestaré más a Su Señoría con mi presencia, mientras Su Señoría, sin duda, me concederá a cambio una patente de corso... Sí, los diplomáticos como nosotros nos entendemos, ¿eh? Le agradezco mucho a Su Señoría su amabilidad.",
"Te advierto, joven, para que tengas en cuenta las graves implicaciones de acto tan imprudente e impúdico: una demanda de tal insolencia puede provocar violentas represalias. Y la conquista de esta ciudad podría perturbar el equilibrio de poder en el archipiélago. (es decir, estropear la misión principal ;-) )",
"Bah, no temo ninguna represalia. Y siempre puedo restaurar el equilibrio de poder devolviendo la ciudad a su actual gobernante. No me importan las impli... imprecaciones, ¡ve y dile al gobernador que exijo nada menos que la llave de esta ciudad!",
"Hum... Sería menos imprudente si solo me llevo tu bolsa. Aunque sin duda seguirás encontrándolo impúdico, ¿eh? Yo también te advierto, viejo, para que tengas en cuenta las graves implicaciones de mi espada en tu barriga. ¡Dame tu oro!",
"Veo que Su Señoría Ilustrísima es un hombre de diplomacia y sabiduría. Sí, también valoro mucho el equilibrio de poder. Por lo tanto, busco buenas relaciones con la orgullosa nación que Su Señoría representa. Hagamos un trato equitativo: yo perdono a la ciudad, y Su Señoría me ofrece a cambio una amnistía y una patente de corso... Sí, los diplomáticos como nosotros nos entendemos, ¿eh? Le agradezco mucho a Su Señoría su amabilidad.",
"¡No confío en ti! ¡ALARMA! ¡CONVOCAD A LA MILICIA!",
"¡No pondré mi destino en tus manos! ¡ALARMA! ¡Llamen a las patrullas!",
"¡No puede haber ningún trato con alguien como tú! ¡ALARMA! ¡Traed a los guardias!",
"... Bah, pelearé contra todos hasta que la ciudad se rinda. Y la próxima vez te trataré con menos cortesía, ¡créeme!",
"Tu audacia ha tenido su recompensa... esta vez. El gobernador prefiere rendirse antes que arriesgarse a atacar este inexpugnable fuerte. ¿Cuáles son tus condiciones?",
"Perdonaré a la ciudad y a sus habitantes si juráis lealtad a Portugal.",
"Jurad lealtad a las Provincias Unidas de los Paises Bajos. 'Oranje boven...'",
"Jurad lealtad a Gran Bretaña. 'Rule, Britannia, rule the waves...' Britania domina las olas..., y esta ciudad...",
"Jurad lealtad a Francia. ¡Tres hurras por ",
", el nuevo sobernao de esta ciudad!",
"Jurad lealtad a España. ¡Larga vida a ",
", que devolverá esta ciudad a la verdadera fe!",
"Jurad lealtad a los Estados Unidos de América. ¡Libertad, justicia y el modo de vida americano!",
"Jurad lealtad a Suecia. ¡Salve, ",
", que ahora ostentará la soberanía sobre esta ciudad!",
"¡Izad la Jolly Roger, abajo los tiranos! Ahora esta es una ciudad pirata. ¡Arr...!",
"Solo me interesan el oro y las mercancías. Cargad todas vuestras posesiones de valor en mi barco y os dejaré en paz.",
"... Parece que no tengo otra opción que darte mis ",
"... Qué se le va a hacer. *SUSPIRO* Adiós, mis amadas ",
"... Está bien, está bien, aquí tienes ",
" piezas de oro.",
"¡No jures, da gracias a Dios de seguir con vida y piérdete!",
"Muchas gracias, ha sido un placer hacer negocios contigo. Hasta la vista.",
"¡Buen chico! ¡Y ahora, apártate de mi camino! ¡Voy a enfrentarme a hombres de verdad!",
"Soy solo un secretario del comandante.",
"No voy a estropear el filo de mi espada en los huesos de un secretario. Sospecho que voy a necesitar una hoja bien afilada cuando atraviese la próxima puerta...",
"Un secretario, ¿eh? Tu ropa parece muy cara para un secretario. Probablemente tienes acceso a la caja de caudales de la guarnicion, ¿eh? Bueno, pues entrégamela o te estropeare la casaca... ¡CON SANGRE DE SECRETARIO!",
"Soy un inspector de la Real Junta de Arsenales, y estoy aquí para inspeccionar los almacenes de esta Armería.",
"No dejes que te distraiga de tu trabajo. Y tan pronto como haya conquistado este fuerte, esperaré recibir un informe detallado sobre mis almacenes. Puedes retirarte, continúa con tu deber.",
"Me vendría bien rellenar mi propio arsenal. Manda a mi barco un cargamento de bombas, y no te entretengas, o inspeccionarás tus intestinos... ¡derramados en el suelo cuando te raje las tripas!",
"En ese caso seguramente podrás darme alguna de esas nuevas armas especiales. Vamos, hazlo, o te haré inspeccionar barriles de pólvora abiertos.. ¡con una antorcha atada entre las manos!",
"Soy un agente de reclutamiento, y acabo de llegar con un barco cargado de... eh... voluntarios recién llegados de las prisi... eh... de las principales familias, quiero decir.",
"Quieres decir que eres un canalla que vende idiotas reclutados a la fuerza y desgraciados de las cárceles a las guarniciones del Caribe, ¿no? Donde la mayoría de ellos morirán de fiebre amarilla en los primeros meses, por lo que siempre hay demanda para tu repugannate oficio, ¿eh? Desprecio a las sanguijuelas como tú. ¡Piérdete antes de que te reclute para el servicio en el burdel de Verruckt!",
"Esos pobres diablos estarán mucho mejor en mi hermoso barco que en algún barracón infestado de bichos. Así que lleva a tus 'voluntarios' a mi barco de inmediato. Y si no cooperas te 'reclutaré' también: ¡como 'paje' para tus antiguas víctimas!",
"¡Nadie debería beneficiarse de la venta de hombres para que sirvan como esclavos! Así que dame tu sucio dinero... ¡AHORA!",
"Soy un proveedor, y  he comprado un contrato para abastecer a esta guarnición de forraje para los caballos, de licores para el tratamiento de heridos, de madera para las empalizadas y de lona para las tiendas de campaña. Solo venía a pedir ayuda para descargar mi carreta.",
"Bah, cosas aburridas. Ve a alimentar a tus caballos, proveedor.",
"Hum, tal vez podría usar esas cosas para fines ligeramente diferentes. Señor proveedor, monta en tu carreta y condúcela hasta mi barco. Allí conseguirás ayuda para descargar, je, je. ¡Y si no llegas allí, yo me encargaré de que no llegues a ningún sitio nunca más, créeme! ¡Ve a hacer la entrega! ¡AHORA!",
"¿COMPRASTE el contrato? Y probablemente los estafas y entregas suministros de peor calidad, ¿eh? Bueno, así es como funciona la adjudicación de contratos públicos en este siglo. Pero eso incluye también sobornos y dinero de protección a todos los que podrían cortarte el negocio, ¿eh? Como YO, que también podría cortarte la cabeza...",
"Quiero convertirme en alférez de este regimiento, y vine aquí a comprar el puesto. Pero no me aceptaron, aunque les ofrecí una suma considerable. Demasiado viejo, dijeron. Los muy cretinos...",
"Deberías estar agradecido, si te hubieran aceptado ya te habría matado. Piérdete, o te daré tu primera lección de esgrima... y la última también.",
"Una suma considerable, ¿eh? Dámela y te aseguraré un buen puesto de oficial. Tengo mucha influencia en este regimiento... Muchas gracias.",
"No desperdicies tu talento en el Ejército, no ofrecen nada más que pies doloridos y barracones infestados de chinches. Pero el mar ofrece aventuras y tesoros. ¡Únete a la marina, sé mi oficial!",
"¿Aventuras? ¿TESOROS? ¡Suena genial! Estoy listo para seguirte en un momento, solo tengo que ir a buscar mis efectos personales primero. Te veré detrás de la próxima puerta.",
"Genial, necesitaré refuerzos. ¡Bienvenido a la tripulacion! Y ahora, date prisa en recoger tus cosas. ¡Nos vemos!",
"Quieres decir que eres un canalla que vende idiotas reclutados a la fuerza y desgraciados de las cárceles a las guarniciones de Caribe, ¿no? Donde la mayoría de ellos morirán de fiebre amarilla en los primeros meses, por lo que siempre hay demanda para tu repugannate oficio, ¿eh? Desprecio a las sanguijuelas como tú. ¡Piérdete antes de que te reclute para el servicio en las minas de #sisland_Oxbay#!",

};
