string DLG_TEXT[23] = { 
"!Ayuda! !Socorro! !Auxilio! !Me van a colgar, por favor ayuda!",
"!Aah! !Por favor, ayudame, #ssir#! !Alejen a estos bastardos de mi!",
"Por favor, #ssir#, ten piedad y ayudame a torre de estos bandidos! !Te lo suplico!",
"?Que esta pasando aqui?",
"?De que se trata este asunto?",
"?Cual es el problema?",
"Yo solia correr en una banda con ellos... Pero he visto el error de mis caminos y quiero vivir una vida honesta de la que pueda estar orgulloso. !Pero esos bastardos prefieren verme muerto que libre!",
"Estos bandidos... Una vez fui un ladron, pero he encontrado la fe y solo quiero sentar la cabeza y vivir una vida honesta. Me trato de escabullirse, pero me vieron y ahora me llevan de vuelta y me tortura! !Por favor, Ayudenme!",
"En el nombre de Dios, #ssir#, tienes que ayudarme! !Quiero dejar esta vida de crimen, pero ahora mis antiguos 'amigos' no se detendran ante nada para hacerme sufrir, para hacer un ejemplo de mi!",
"Ahh, ahora entiendo.",
"Sinceramente, #ssir2#, no puedo agradecerte lo suficiente por tu ayuda!",
"!Reloj de la honestidad! Muchas gracias por ayudarme a salir de esta malvada vida, nunca olvidare lo que has hecho por mi hoy.",
"!Gracias a Dios que estabas aqui! Nunca hubiera esperado que alguien diera un paso adelante por un extrano como ese. Es bueno saber que todavia hay almas bondadosas y valientes en este mundo.",
"Una superposicion de alma vale diez de estos cretinos.",
"Consegui este #sgem# durante mi primer trabajo y lo conserve como un recuerdo. Pero quiero dejar esa vida atras, asi que me gustaria que usted tiene.",
"Gracias. Asegurese de mantenerse alejado de ese tipo de vida a partir de ahora.",
"!Le dire a todo el mundo lo que has hecho por mi hoy! Sabran lo valiente y amable que eres.",
"Agradecer. Que tengas buena suerte en el futuro.",
"Estas solian ser las herramientas de mi 'oficio', pero ya no las necesitare. Tal vez usted puede ponerlos a un mejor uso, o simplemente deshacerse de ellos.",
"Gracias. Con suerte usted encontrara un verdadero comercio y adquirir algunas herramientas honestas.",
"Oye, eres ",
"?no es asi? No he oido nada bueno sobre TI, y lo que hiciste aqui lo prueba. Tal vez haya una forma de pagarle.",
"?Que tienes en mente?",
};