string DLG_TEXT[36] = {
"¡Cof, cof!... ¡Maldito tiempo! Mi nombre es ",
", y soy el mejor constructor de barcos de estas islas.",
"Me permito disentir, en mi opinión, hace un tiempo maravilloso. Mi nombre es ",
".",
"¡Basta de lamentaciones! Mi nombre es ",
". Supongo que has oído hablar de mí.",
"Oh, eres tú otra vez, con tus problemas... ¡Cof, cof!",
"Puede que tu salud no sea muy buena, pero tu memoria está en plena forma. Ahora, vayamos al grano.",
"Así es, soy yo otra vez, y tú eres tan pesado como siempre. Hablemos de negocios.",
"Siento molestarte. Debo irme.",
"¿Sabes?, ya me he hartado de tus quejas incesantes sobre la vida. Adiós.",
"¡Los jóvenes de hoy en día sois tan irrespetuosos! Tienes pasion y fuerza, ¿qué más necesitas?",
"Tú mismo debes haber sido joven alguna vez. Ten un poco de paciencia.",
"Si, y supongo que tu juventud murió hace tanto tiempo, que ni siquiera puedes recordarla.",
"¡Muestra algo de respeto por tus mayores, pollastre!",
"Por favor, no vuelvas a levantarme la voz. ¿Podemos ir al grano?",
"¡Cuida tu lengua arrugada, viejo, o acabaré con tu sufrimiento! Si eres inteligente, cerrarás la boca y pensarás en los negocios.",
"Lo siento. Veo que no tiene sentido hablar contigo.",
"¡Ya he hablado demasiado! Adiós.",
"¡Sí, sí, está bien! ¿Qué quieres de mí, ",
"?",
"Me gustaría usar los servicios de tu astillero.",
"Necesito los servicios de tu astillero. ",
"Lo siento, tengo que irme.",
"Tengo asuntos urgentes en otra parte. Ya me voy.",
"¿Qué necesitas exactamente?",
"Necesito reparar mi barco. Aunque podría considerar mandarlo al desguace y comprarme otro nuevo.",
"Necesito instalar nuevos cañones en mi barco.",
"Nada, gracias.",
"Me niego a tratar con una persona con tu reputación y relaciones. Márchate ahora mismo, ",
", antes de que llame a los guardias.",
"Muy bien.",
"Bien, mi muelle junto al fuerte está disponible para ti. Si te parece bien, le diré al capataz del muelle que remolque tu barco hasta allí. Solo entonces podré analizar los daños y decirte cuánto tiempo y dinero costará repararlo. ",
"¿¿MUELLE AL LADO DEL FUERTE?? Uhh... Acabo de recordar que tengo... eh... otros asuntos urgentes que debo atender primero. Adiós.",
"Después de cerrar este diálogo, pulsa ENTER para abrir la interfaz de cambio de velas.",
"Salir",

};