string DLG_TEXT[95] = {
"!Oh! No te habia visto., ",
"!",
"Por favor, perdoname, se Wade rita.",
"Lamento haberla asustado, Milady.",
"Oooh, Capitania ",
"! !Has vuelto! Madre del Dios, ?esta bien?",
"Lo encontre sano y saludable, doecherne Estrella.",
"Aun no lo he encontrado, seechar ra. Pero me ire pronto.",
"Esperar. Eres un capitan de barco. ?Llevas una carta para entregar aqui?",
"Si, tengo una carta.",
"No, lo siento, se Blake, no lo soy.",
"Gracias Dios! !Por fin! Damelo, por favor.",
"Esperar. Dice en el exterior que va a haber una recompensa.",
"Si, por supuesto. Mi Dios, cinco mil de oro, ?hara eso para mantener tus labios sellados?",
"Eso es muy generoso, seechera rita, gracias. Pero pareces preocupado. ?Hay algo que pueda hacer?",
"Entonces vete, Capitolio, y dejame con mis lagrimas.",
"Pareces preocupado. ?Hay algo que pueda hacer?",
"Muy bien, despidan a rita. De nuevo, siento haberte molestado.",
"No te conozco. ?Como podria confiar en ti?",
"Bueno, mi nombre es ",
" ",
"y mi barco es",
".- ? Ha oido hablar de mi?",
"Ah. Tienes razon en eso. Tal vez4 decir adios.",
"No te conozco. ?Como podria confiar en ti?",
"Bueno, mi nombre es ",
" ",
", y mi barco es",
".- ? Ha oido hablar de mi?",
"Ah. Tienes razon en eso. Tal vez4 decir adios.",
"!Oh! El famoso Carter ",
"! Si, si, he oido hablar de TI. Las historias de tus hazanas han llegado incluso a esta insignificante Colonia de Espa. Soy Christopher Estrela de Allen, esposa del conc de esta miserable isla.",
"Por favor, se Wade ra, puedes llamarme ",
".",
"!Oh! Usted es el notorio Capitan ",
"! Por favor, dejame en paz, o llamare a los guardias!",
"Como desees.",
"Muy bien, Capitania ",
". Aqui esta tu recompensa. Pero lo siento, no veo como podrias ayudarme.",
"No pareces muy feliz de estar aqui, doechernestrella.",
"Muy bien, Capitania ",
". Pero lo siento, no veo como podrias ayudarme. Por favor, dejame en paz.",
"Como desees.",
"Odio este lugar. No amo a mi marido, pero no puedo dejarlo. Si, soy muy infeliz. Estas cartas son mi unica salida de una vida por lo demas completamente insatisfactoria y miserable.",
"Eres demasiado joven para ser tan amargado.",
"Eres muy amable, capitan. ",
". ?Amable y quizas generoso tambien?",
"Uno simplemente tiene que preguntar, Milady.",
"Y uno puede aceptar tan facilmente como rechazar, ?correcto, Carter?",
"Muy cierto. ?Que es lo que quieres?",
"?Como conseguiste esta carta? ?Quien te lo dio?",
"Un nuevo oficial que contrate recientemente. Dijo que se lo quito a un pirata. Un pirata muerto.",
"!Dios mio, rezo para que no este muerto!",
"?Estas intercambiando cartas con un pirata, doecher Estrella?",
"Capitania ",
", Te lo ruego, por favor dime que mi amor no ha muerto!",
"M'Lady!",
"Oh ",
"Capitania ",
", por favor ayudame, o me volvere loco por no saber!",
"!Se Blake ra, no llores! Averiguare lo que pueda.",
"Te dare una recompensa generosa, capitan Wade, si averiguas si mi amada sigue viva... O Dios mio, muerto. !Rezo para que no este muerto! Favor. Encuentrelo, Capitan. Encuentrenlo.",
"Ummm... Si navego en algun lugar, necesito provisiones y pago por mis hombres.",
"Aqui. Es todo lo que me queda por ahora. Puedo conseguir mas, pero solo si haces una solemne promesa de guardar silencio sobre todo este asunto. Nadie-NADIE-puede saber de esto.",
"Oh si, se Wade ra. Mis labios estan sellados. Tiene mi palabra. Absolutamente. ?Como se llama y donde vive?",
"Esta en #sisland_Quebradas Costillas#. Armand Delacroix. Su nave es la 'reina del Vudu'.",
"Reina Vudu? He oido hablar de ella. Es grande y da miedo. Y tambien he oido hablar de el. Tiene una mala reputacion. Sin cuartel. ?Estas seguro de que este es el hombre? No pareces el tipo de mujer que iria por un hombre tan rudo.",
"El era una vez un Chevalier frances, Caballero, un Caballero, y es un hombre muy cortesano, educado, y encantador.",
"Si usted lo dice, haga la llamada.",
"Lo amo.",
"?Como lo conociste, si puedo preguntar?",
"Abordo y tomo el barco en el que yo viajaba.",
"Y obviamente te perdono la vida.",
"Estaba siendo transportado a #sisland_Isla Muelle# desde Espana para casarme con un hombre que nunca habia conocido. La Marina de mi pronto marido se las arreglo para matarme de lo que ellos llamaban un destino peor que la muerte. Armand hizo que sus hombres saquearan el barco, y ... .. Bien... Antes de que todos escaparan, mi valiente pirata y yo nos habiamos convertido en amantes.",
"Y su marido nunca sospecho?",
"?Alguna vez has conocido a Cristofor de Alen, ",
"?Capitarne? Fue un matrimonio arreglado, un matrimonio de conveniencia, y no hemos tenido...contacto. ?Como podria saberlo?",
"Ah. Ya veo. Te prometo que encontrare a Delacroix para TI.",
"Gracias, capitan. ",
". Por favor, tome esta Cruz para mostrarle a Armand. Es solo una muestra hecha de una moneda vieja, pero el la hizo para mi, y la reconocera. Lo reconoceras porque lleva uno igual alrededor de su cuello. Y justo vela para usted. No descansare hasta que vuelvas.",
"Volvere tan pronto como encuentre noticias.",
"Santa Maria! Gracias, gracias, gracias.",
"M'Lady... M'Lady... Aqui... Aqui esta su ficha de vuelta, y un panuelo. Ahora seca tus lagrimas. El esta bien.",
"T-th-gracias, ",
"Capitania. Eres una especie de #sperson#.",
"Hay mas, se Wade ra.",
"Tengo que recompensarte,  ",
".",
"Bueno, si. Pero lo mas importante Para usted mi Senora, Armand ha encontrado una manera de sacarla de #sisland_Isla Muelle#.",
"!Mi Dios! !Por fin! Como?",
"Con mi ayuda, se Wade ra. ?Crees que puedes confiar en mi?",
"Ya he confiado en TI mucho mas alla de la confianza que le doy a mis amigos mas antiguos, capitan Carter. Si, si. Se que se puede confiar en TI.",
"Sera peligroso.",
"Estoy dispuesto a arriesgar cualquier cosa por estar con mi hermosa Armand.",
"Muy bien entonces. Esto es lo que haremos... ",

};
