string DLG_TEXT[22] = {
"Capitan ",
".",
"...El disfraz es perfecto, m'lady!",
"Estoy temblando, ",
"Capitania.",
"No tengas miedo, haz la llamada.",
"No tengo miedo. Estoy emocionado.",
"Bueno, tampoco te excites. Esto es peligroso, y tenemos un largo camino por recorrer.",
"No te preocupes, me ensenaron a usar la espada y la pistola que llevo.",
"Eso podria ser util, "" haz la llamada a la estrella, pero por mi alma, por favor no te pongas en peligro, o Armand tendra mi pellejo."",
"Esta arriesgando su vida por nosotros, Capitan ",
". Te apoyare, si es necesario.",
"Muy bien, entonces. - Vamos, vamos. Sigame, Mantengase cerca, y cualquier otra cosa que pueda hacer, por favor, por favor, guarde silencio.",
"Eso fue clo -- ",
"!Shhh! !Te dije que te callaras! Esto no ha terminado todavia. Ahora ten cuidado, hay mas peligros aqui que los monos y los Akellani. Venga, vamos.",
"!Esta cerca, lo se! Armand! !ARMAND!",
"M'Lady! !Silencio!",
"!Armand! !Madre del Dios, soldados!",
"!Soldados! Deberiamos esperarlos aqui y tomarlos uno por uno. Difundir y conseguir listo!",
"Adios, Capitan ",
". Para mi, eres un heroe de gran honor.",
"Milady, fue un honor conocerla. Ve y ten cuidado, se feliz.",

};