string DLG_TEXT[23] = {
"!Alto, #ssir#! ?Que estas haciendo aqui?",
"Arresto a un hombre hace unos minutos en el burdel.",
"Si. ?Y que?",
"Quiero hablar con el. Es eso posible?",
" !Claro que no! !Podrias intentar liberarlo! No confio en el y tampoco confio en TI.",
"?Cuanto quieres?",
"?Que quieres decir?",
"Excelente. Ahora estamos llegando a alguna parte. Aqui estan tus 500 monedas de oro. Ahora dejame entrar.",
"Eso es bastante oro lo que quieres. Volvere mas tarde.",
"Muy bien. Te dejare entrar. Pero no te quedes ahi mucho tiempo.",
"No hay problema. No tengo la intencion de permanecer en una prision tan sombria como esta por mas tiempo del necesario.",
"Adios y gracias por su visita. Hare buen uso de tu oro cuando el burdel se abra de nuevo.",
"En realidad, me preguntaba si podrias hacerme un favor mas. Ganaras otras 500 monedas si me ayudas.",
"Por favor, dime que no quieres que libere al prisionero. No hare eso. Ni siquiera por 50000 monedas de oro. El conc quiere que me arresten inmediatamente. Y ejecutados tambien, lo mas probable.",
"Es una pena. Eso era exactamente lo que iba a preguntarte. ?Sabes como puedo hacer que liberen al prisionero?",
"...",
"...",
"? Estas listo para darme el dinero ahora?",
"Si. Aqui esta. Ahora dejame entrar.",
"Sabes muy bien lo que quiero decir.",
"Hmm. Si me das 500 monedas de oro, eso podria convencerme de tu honradez.",
"La unica persona con ese poder es el conc. Hablale de ello. Pero no esperes que sea barato.",
"Gracias. Voy a hacerle una visita entonces.",

};
