string DLG_TEXT[30] = { 
"!No ves que estoy de Servicio! No me molestes.",
"Esta bien, esta bien.",
"?No quieres informarme sobre algun crimen?",
"No, por supuesto. Despues de todo, soy capitan. Veo que no estas escuchando.",
"X - !no permitimos la lucha en las calles! Solo puedes luchar si alguien te ataca.",
"Bien, considerare esa informacion.",
"Tal tiempo, y tengo que quedarme aqui. Lo creas o no, el unico entretenimiento que tengo es luchar con las moscas que estan tratando de aterrizar en mi cara.",
"Una pena, pero no puedo ayudarte. Es tu trabajo.",
"Si quieres hablar de encontrar a alguien mas, tengo que centrarme en mi trabajo y no puedo hablar contigo.",
"Me preguntaba si estas vivo o no. Estas parado aqui como una estatua.",
"?Crees que es facil declarar nuestra ciudad? !Para nada! Es un trabajo muy importante y peligroso. Una vez...",
"Turista en otro momento, tengo que irme.",
"Sigue tu camino, no me molestes.",
"Como usted diga, soldado.",
"!Oye! ?No me traeras una taza de Ron de la taberna?",
"Si, pero mas tarde me colgaran por hacer un soldado borracho. No, espera a que te releven y podras beber tanto como desees.",
"?Por que solo los marineros groseros como usted estan tratando de hablar conmigo?! Hay mujeres hermosas en esta ciudad?",
"? Y lo llamas para servir? Mira, no te pierdas a un peligroso criminal como yo. !ja, ja!",
"Te ves muy saludable! ?No quieres unirte a nuestro ejercito? Tenemos mucho espacio en nuestras barracas, buena comida, Ron gratis.",
"Suena bien, pero debo negarme. No podia lidiar con la disciplina del ejercito.",
"Este calor... Daria todo lo que tengo para volver a mi encantadora Francia con sus florecientes flores y su olor a hierba.",
"Si, parece que este clima no te conviene.",
"?Que quieres?",
"Usted...hic...!canalla! !Lastimaste a mi amigo!",
"?Que amigo? Estas solo aqui, ",
".",
"?Que? Lo era...aqui hace un minuto. Ire a buscarlo. Usted...hic...!esperaras aqui si quieres tu paliza!",
"Como te atreves a contradecirme! !Te voy a estrangular!",
"No permitimos que salvajes como tu amigo entren en la ciudad. Tampoco permitimos que sus amigos entren. !Vete de aqui!",
"Muy bien. No quiero causar problemas.",
};
