string DLG_TEXT[84] = {
", #saddr#! Como puede ayudarte este siervo de Dios?",
"Soy ",
", capitan de la",
".",
"Bienvenido, ",
", #saddr#! Me alegro de que tu tiempo en el mar no te hiciera olvidar tu fe.",
"Saludos, ",
". Entonces háblame de tus pecados",
"Es bueno verte y estoy listo para tomar tu confesión, #saddr#.",
"Me gustaria dar un regalo a la iglesia",
"Solo necesito hablar con usted, #sFather#",
"Aprecio eso. Tal vez la próxima vez",
"Estoy muy feliz de dar la bienvenida a un nuevo miembro a la congregacion. Sir",
".",
"Maravilloso, entonces espero que acepte mi regalo a la iglesia",
"Puedo hablar con usted, #sFather#?",
"Gracias, #sFather#, pero debo irme.",
"¿Esto es por tu fe?",
"En realidad, se trata de su fe",
"De hecho, me preocupa",
"Lo siento, pero he reunido pruebas que demuestran que ha roto sus votos como sacerdote",
"No. Y hablemos de otra cosa.",
"¿Qué quiere decir?",
"Me enviaron aquí para ver si los rumores que mancharon su nombre eran ciertos",
"¿Rumores? ¿Rumores?",
"Supongo que se declara inocente. Desafortunadamente, tengo cartas que dicen que es culpable.",
"¿En serio? ¿Qué cartas? ¡Juro que no hice nada!",
"Aquí están. Será mejor que deje de actuar, #sFather#",
"Pero nunca he visto esto antes",
"Estan escritas por usted, #sFather#. Y muestran la imagen completa de su degradación",
"Aún no sé de lo que estás hablando!",
"Estoy hablando de cartas de amor que le escribió a cierta joven",
"¡Juro que nunca escribí esas cartas! !!!Dios mío, quien me creerá cuando los vea!!!",
"Hmm. O eres un muy buen actor, #sFather#, o realmente no escribiste estas cartas. Me alegro de que esa no sea mi decision.",
"No se desespere, #sFather#. Ahora puedo ver que está diciendo la verdad. Todavia hay esperanza",
"¿Esperanza? Mi reputación está ¡destruida!",
"Sepa que, podría simplemente 'perder' estas cartas.",
"¿Qué puedo hacer para convencerte de que me las des?",
"Creo que 2.000 piezas de oro podrian distraerme lo suficiente como para dejarlas aquí.",
"¡No! No te sobornaré con oro de la iglesia. Por favor, vete.",
"Como desee.",
"Está bien. Aquí está tu dinero",
"Y aquí están sus cartas",
"Gracias. Ahora me voy. Y me llevo las cartas conmigo",
"¿Qué? ¡Pensé que estábamos de acuerdo!",
"Usted pensó mal. Estaba probando su historia. Un hombre inocente no buscaría comprar la solución a sus problemas. Ahora sé que usted es culpable",
"¿Que quieres decir, #saddr#?",
"Fui enviado por",
"Padre Bernard",
"Padre Bernard",
", para comprobar algunos rumores desagradables sobre usted",
"¿Qué clase de rumores? No tengo ni idea de lo que estás hablando.",
"¿Me está diciendo que es inocente de traicionar sus votos como sacerdote? ¿Y no sabe quién pudo empezar esos rumores?",
"¡Oh, Dios mío, no! No tengo ni idea de quien querría mancharme asi.  Pregúntale a alguien de la ciudad. Pregúntale a mi asistente.\nPregunte, todos le dirán que no he hecho nada malo.",
"Tal vez sea buena idea",
"Bueno, está bien. Pero debo decir que ese desprecio no servirá de nada.",
"Me doy cuenta. Acepte mi regalo a la iglesia",
"Lo siento, #sFather#, pero tengo que irme",
"Por supuesto, #saddr#. Cuánto quieres donar?",
"Lo siento, #sFather#, pero no puedo hacer una donación en este momento",
"Me temo que 100 piezas de oro es todo lo que puedo pagar ahora",
"Creo que el Señor se sentiría bien con 1000 piezas de oro",
"Me va bien en estos días, así que daré 5000 piezas de oro",
"Es tu decisión, #saddr#. Nunca es demasiado tarde para cambiar, y debes saber que todo se tendrá en cuenta en el momento de tu muerte. ",
"Mi muerte está todavia muy lejos, si Dios quiere. Hablemos de otra cosa.",
"Lo siento, papa. Debo irme",
"Gracias por su regalo en nombre de la Santa iglesia, #saddr#.",
"Necesito hablar con usted, #sFather#",
"Lo siento, #sFather#, pero tengo que irme",
"Gracias por su regalo en nombre de la Santa iglesia, #saddr#.",
"Necesito hablar con usted, #sFather#",
"Lo siento, #sFather#, pero tengo que irme",
"Gracias por su regalo en nombre de la Santa iglesia, #saddr#.",
"Necesito hablar con usted, #sFather#.",
"Lo siento, #sFather#, pero tengo que irme.",
"Me temo que ",
" oro es todo lo que puedo permitirme ahora mismo.",
"Creo que el Señor lo tomaría amablemente ",
"Me va bien en estos dias, así que daré ",
" piezas de oro.",
"Nos hemos reunido hoy aquí para celebrar, en medio de la guerra, la Union de estas dos personas enamoradas. Si hay alguien aquí que tenga una causa justa por la que esta pareja no deba casarse, que hable ahora o calle para siempre.",
"Tú, #sgroom#, ¿tomas a esta mujer como tu esposa, para amarla, honrarla y amarla mientras vivan?",
"Sí, quiero.",
"Y tú, #sbride#, ¿tomas a este hombre como tu esposo, para amarlo, honrarlo y cuidarlo mientras vivan?",
};
