string DLG_TEXT[41] = {
"¡Capitán! ¿Eres realmente tú?",
"¡Soy yo, camarada! En carne y hueso.",
"¡Es un milagro! ¿Cómo conseguiste salvarte?",
"¡Cálmate! Te he hecho una pregunta.",
"Mis disculpas, capitán. Nos alegramos de verte a salvo.",
"Y yo me alegro de que me veáis. Pero la pregunta sigue siendo: ¿qué os ha traído aquí?",
"Bueno, después de que tú cayeras por la borda, la tormenta nos estuvo zarandeando unas horas más. Cuando la tempestad finalmente amainó, descubrinmos que la tierra más cercana era #sisland_Isla Muelle#. El barco estaba muy dañado, así que contratamos los servicios del astillero español\n Tardó bastante tiempo, pero ahora, el '",
"ship storage",
"' está en muy buen estado.",
"Son buenas noticias. ¿Pero cómo pagasteis las reparaciones?",
"Juntamos nuestro oro. A algunos les hizo menos gracia que a otros contribuir..., pero sus cortes y moretones sanarán. Después de todo, también es nuestro barco... ¡aunque la tripulación estará encantada de saber que vuelve a tener a su capitán!",
"Bueno, os doy las gracias a todos.",
"¡Esto merece una celebración! ¿Por qué no vamos a la taberna?",
"Mejor aún, vamos a traer la taberna aquí. Mandaré que lleven diez barriles de ron al barco. ¡Que beban como muestra de mi gratitud!",
"¡Hurra, capitán! ¡Dios te bendiga, ",
"!",
"Gracias a todos.",
"¡Realmente es un milagro que hayas sobrevivido! ¡Dios debe de estar contigo, capitán!",
"Me gustaría pensar que sí, aunque a veces me lo pregunto...",
"... ¡O el diablo de los mares! ¡He oído que otorga su favor a a los marinos audaces y los mantiene a salvo del daño!",
"No creo haber escuchado ese cuento antes.",
"¿Qué cuentos? ¡Jovannie Speckled del bergantín 'Ardent' me dijo que vio al diablo de los mares con sus propios ojos!",
"¿Vio al diablo? Apuesto a que lo vio a tavés del fondo de una botella de ron.",
"No, capitán. Juró que no había bebido ni una gota.",
"¡Esperadme aquí, hombres!",
"¡No, capitán! ¡Llévame contigo! ¡No deberias meterte en la boca del lobo en solitario!",
"No soy una niña pequeña que necesite vigilancia, amigo mío.",
"Por supuesto que no, capitán. Pero... ¡acabamos de recuperarte de las garras de la muerte! Hazlo por mi tranquilidad.",
"No, no. Una compañía grande solo causaría problemas.",
"¿Pero que haremos mientras no estés?",
"Disfrutaréis del ron. Y que algunos marineros me esperen cerca de la salida de #sOxbay#.",
"¿Crees que podrías tener que salir corriendo de la ciudad?",
"Espero que no. Pero nunca se sabe.",
"¿No hay manera de que puedas cambiar de opinión, capitán? Dos tipos fuertes podrían ayudarte a resolver cualquier problema.",
"Entonces, que ayuden a proteger el barco. Volveré antes de que sepas que me he ido.",
"Muy bien. ¡Te esperaremos aquí, capitán! Si algo sale mal, vuelve aquí lo más rápido posible. ¡Te cubriremos!",
"Te creo. ¡Pero no os descubráis ni un segundo antes!",
"Lo llevaremos al barco, capitán. Me alegro de que todo haya acabado tan bien.",
"¿Estás seguro de eso? Ahora, vete. ¡Te seguiré pronto!",

};
