string DLG_TEXT[80] = {
"Saludos, ",
". ¿Y cuál es tu nombre?",
"¿Puedo saber tu nombre, ",
"?",
"¿Con quién tengo el honor de hablar?",
"Yo soy ",
", capitán del '",
"'.",
"Hola de nuevo, ",
"¡Ah, ",
"! ¡Me alegro de verte!.",
"Hola, ",
". ¡Estoy tan feliz de que hayas venido!",
"¡Hola, mi bien! Estoy tan feliz de que hayas venido. ¡Parece que hace siglos que no te veo!",
"Un placer verte, como siempre. Pero debo seguir mi camino.",
"...",
"Pero debo irme.",
"(( Charla inconsecuente )))",
"((( Proponer matrimonio )))",
"Dime, ¿que ha estado pasando por aqui?",
"Lo mismo digo, mi amor. Pero vamos a... reencontrarnos... en privado.",
"Ah, entonces debes estar a punto de estallar... de cosas que decirme. Así que vamos.",
"Yo soy ",
". Es un placer conocerte, ",
"Oh, mi nombre es ",
", y estoy muy feliz de conocerte.",
". ¡Oh, estoy tan feliz de conocerte! ¡Todo el mundo ha oído hablar de tus audaces hazañas!",
"El placer es todo mío, señorita.",
"((( Mantienes una agradable conversación con tan interesante #slady#. )))",
"...",
"((( A tu nueva amistad, ",
" del gobernador, le impresionan tu ingenio y encanto. #spronoun# accede a recopilar informacion para ti en la corte del gobernador. )))",
"¡Y conozco el lugar perfecto!",
"¡Adelante!",
"Has conquistado mi corazón, ",
", pero mi pretendiente es #sman# de carácter muy celoso. Sin duda, te desafiará a un duelo...",
"Muy bien. Nuestro amor mutuo me protegerá...",
"Ah. Entonces, me temo que debo retirarme...",
"¡Oh! Eso es muy bonito, ",
", pero hablemos de otras cosas...",
"Perdón, pero debo irme...",
"((( Tu ",
"te dice que ",
"no ha pasado nada muy importante. )))",
"...",
"¡Oh, bien hecho, amor mío!",
"Tu amor ha sido para mí un escudo más fuerte que cualquier acero...",
"Ahora, ¡vamos a la iglesia!",
"Vamos, amor mío.",
"Un dia maravilloso -!y qué noche!- pasa...",
" y su amor son solo para mí, pisaverde! ¡En guardia!",
"Solo me quedan dos palabras: ¡en guardia!",
"Me has superado en un combate justo, ",
". Os deseo mucha felicidad a los dos; me retiraré.",
"Fuiste un honorable oponente; te deseo lo mejor.",
"Mi señora, me temo que el mar me llama y no puedo estar en tierra lo suficiente para ser el epsoso que te merces.",
"Ha sido un placer conocerte, pero me voy en busca de cosas mejores.",
"Si tienes que irte, deberías hacerlo; pero siempre recordaré nuestro tiempo juntos.",
"¡Vaya, qué descaro! ¿¡óomo te atreves a tratarme así!?",
"Yo también.",
"...",
"Sí, quiero.",
"[Sacerdote] Por el poder que me ha sido conferido por esta parroquia y por el buen Señor, yo os declaro marido y mujer. Ahora puedes besar a la novia.",
"X",
"Sí.",
"Lo haré.",
"Er... sí, lo haré.",
", toma este anillo como signo de mi amor y fidelidad. En el nombre del Padre, del Hijo y del Espíritu Santo.",
"¡Arrr!",
"Bueno, no sé si esto te interesará, pero he oído una conversación entre mi padre y un emisario español. El cargamento de plata que lleva toda la plata de las colonias españolas en Sudamérica va de camino a #sCartagena#.",
"Sabes que los españoles reúnen toda la plata que extraen de sus colonias en Sudamérica para enviarla a España en una gran flota, ¿verdad? Esa flota ha sido avistada de camino a #sCartagena#. Así que la plata probablemente también esté de camino allí.",
"Surgió una conversación interesante anoche durante la cena. El cargamento de plata está de camino a #sCartagena# ahora mismo, llevando toda la plata de las colonias españolas de Sudamérica.",
"¡Gracias, mi bien! Eso es muy interesante. ¡Tendré que hacer mis propios preparativos para ese cargamento de plata!",
"El cargamento de plata estará sin duda bien vigilado y dudo que vaya a ser capaz de hacerme con él. Pero gracias por contármelo, de todos modos.",
"Preferiría no enemistarme con España intentnado atacar su cargamento de plata.",
"Tal vez haya olvidado mencionártelo, pero ostento el rango de ",
" al servicio de España. ¡Deberías tener más cuidado con sus secretos, mi bien!",
"El palcer es todo mío, buen señor.",
" y su amor son solo para mí, señora! ¡En guardia!",
"Buen señor, me temo que el mar me llama y no puedo estar en tierra lo suficiente para ser la epsosa que te merces.",
};