string DLG_TEXT[189] = {
"Me han dicho que has insistido mucho para pedir una audiencia. Mi nombre es ",
". Ahora, por favor, dime el propуsito de tu visita., ",
".",
"Mi nombre es ",
".",
"Ah, eres tъ otra vez. їQuй te trae por aquн esta vez? ",
"Me gustarнa hablar con Su Excelencia acerca de algunos asuntos.",
"Lo siento, pero hay cosas que tengo que hacer.",
"Entonces, їpor quй me distraes de mis importantes asuntos de estado?",
"Me gustarнa hablar con Su Excelencia acerca de un pequeсo asunto de negocios.",
"Solo estoy aquн para presentar mis respetos, #saddr#. Nada mas.",
"En ese caso, por favor, sal de mi estudio y dйjame volver a asuntos mбs importantes.",
"Sн, por supuesto. Siento haber molestado a Su Excelencia.",
"Lo siento, pero no tengo nada de quй hablar ahora mismo",
"їAh, si? Hay algunos elementos hostiles en nuestras aguas.",
"Esos elementos hostiles suenan interesantes.",
" Me he enterado de que has completado la tarea con йxito; Ўmi enhorabuena, capitan! Aqui estб tu recompensa.",
"Muchas gracias; ha sido un placer ayudar a Su Excelencia.",
"Debes destruir un barco de ",
" vessel ",
"quest pirate",
", que amenaza el trбfico marнtimo en aguas de ",
". Si lo hundes, te recompensarй con la considerable suma de ",
" piezas de oro. їQuй dices, capitбn?",
"Su Excelencia no volverб a saber de ese barco, eso se lo prometo.",
"Me temo que no puedo ayudar a Su Excelencia.",
"Suplico el perdуn, Excelencia.",
"їPuede Su Excelencia hablarme de las relaciones internacionales en el Caribe?",
"Quiero conseguir una patente de corso para que mis acciones sean legales, al actuar en nombre del gobierno #sgov_nation#.",
"He oнdo que se me ha concedido un ascenso.",
"No puedo seguir sirviendo a ",
", Excelencia.",
"Me he hartado de servir a ",
"Debido a tu reputaciуn en nuestra naciуn, y para compensar el tiempo que voy a perder en presentar tu caso a ",
", debo pedirte ",
" piezas de oro.",
"De ninguna manera.",
"Muy bien. Es un pequeсo precio para garantizar que no se me tacharб de pirata por mis acciones.",
"#sgov_nation# siempre se complace en aceptar nuevos capitanes a su servicio. ",
"Actualmente, estamos en guerra con ",
"",
"... ninguna gran potencia, pero ",
". Por supuesto, ",
"los piratas siempre deben ser hundidos en cuanto sean avistados.",
" A la luz de tus anteriores servicios, ",
"te otorgo el rango de ",
"Harй que Su Excelencia se sienta orgulloso.",
"Has daсado los intereses de ",
", y ",
"no olvida a sus enemigos. ЎVete inmediatamente, o los guardias te echarбn a patadas!",
"...",
"Has causado a ",
" grandes daсos, capitбn, pero ",
"estб dispuesta a pasar por alto tus transgresiones pasadas... por un precio: ",
"Muy bien, Excelencia. Acepto.",
"Un placer tratar contigo, ",
"Y con Su Excelencia.",
"ЎEn efecto! Excelente trabajo. Tu nuevo rango es ",
". Ademбs, se te concede un premio de ",
"acres de tierra por orden de ",
"Gracias, Excelencia.",
"їSeguro, ",
" lamentarб perder tus servicios.",
"Sн, seguro.",
" no ve con buenos ojos a los chaqueteros, ",
"Hum..., no he diho nada.",
"Muy bien. Pero espero que lo reconsideres, con tiempo...",
"Adiуs, ",
"їEh?",
"Duro.",
"їCuбles son las уrdenes, #saddr1#?",
"Debo administrar esta colonia.",
"їPuedo ofrecer mi asistencia, #saddr2#?",
"Hay cosas que tengo que hacer.",
"Recibirбs el 50 por ciento del valor de cualquier barco apresado que vendas, como tu parte correspondiente del botнn de presa. Ademбs, hay un precio fijo para cualquier presa legнtima vendida por los corsarios empleados a mi servicio.",
"ЎSuena rentable! Se agradece no tener que regatear por los precios, ",
"Gracias, ",
". їTiene Su Excelencia alguna orden para mн?",
"Asegъrate de leer este libro sobre el 'Arte de Guerra'. ЎNo me gustarнa que fueras la causa de un incidente internacional!",
"Prometo que lo estudiarй detenidamente.",
"їPodrнa Su Excelencia aconsejarme para evitar que me tachen de pirata?",
" Y hay otra cosa. ",
"Tengo un problema con los contrabandistas.",
"Me gustaria que Su Excelencia me hablara de esos contrabandistas.",
"Ъltimamente, estбn apareciendo aquн cada vez mбs y mбs contrabandistas. Quiero pedirte que investigues esto. Por favor, infнltrate en sus filas e infуrmame de lo que averigьes. Como recompensa por la informaciуn que obtengas, recibirбs una parte del dinero que los contrabandistas paguen por las mercancнas.",
"ЎEsto suena como un trabajo para mн!",
"No creo que sea un buen trabajo para mн.",
"Muy bien. Se te entregarбn #samount# quintales de #scargo#. Te lo advierto: Ўno intentes fugarte con la mercancнa o con el dinero de los contrabandistas! Ademбs, te darй un documento indicando que estбs a mi servicio. Puede que te ayude en algъn caso extremo. Pero ten cuidado de que no lo vean los contrabandistas. Si lo ven, lo negarй todo.",
"ЎGracias, #saddr#!",
"Tengo algo que Su Excelencia querrб ver.",
"Esto es muy interesante, has hecho un muy buen trabajo.",
"Como recompensa te pagarй ",
"Pero creo que apenas has araсado la superficie, asн que, por favor, Ўve y trata de averiguar mбs!",
"ЎBuen trabajo! ЎEsperбbamos que hubiera una lista como esta, pero nunca pudimos encontrarla!",
"ЎAh! ЎAsн es como lo hacen! Gracias por la informaciуn.",
"їSu Excelencia ha tenido tiempo de leer mis informes?",
"De hecho, sн. Y creo que nos has proporcionado toda la informaciуn que necesitбbamos. Tal vez necesitemos mбs informaciуn mбs adelante. Pero por ahora esto servirб. Como muestra de gratitud, por favor acepta este pequeсo regalo.",
"Muy bien, #saddr#. Cuando mis servicios vuelvan a ser necesarios, ruego a Su Excelencia que me lo haga saber.",
"Parece que algunos de los comandantes del fuerte de Su Excelencia me disparan en cuanto me ven, aunque no somos enemigos.",
"Un malentendido, їeh? Solo pбgame la modesta suma de ",
" piezas de oro y yo me asegurarй de que esto se resuelva inmediatamente.",
"ЎїA un amigo de nuestra nacion?! ЎMe asegurarй de que esto se resuelva inmediatamente!",
"Podrнas demostrar tu lealtad a #sgov_nation# a travйs de tu ayuda.",
"Parece que he extraviado mi barco, #saddr#. Pero no puedo hacer mucho daсo a nuestros enemigos sin uno.",
"ЎEsto no es cosa de risa! Tienes suerte de que necesitemos a todos los capitanes disponibles. Te darй un nuevo mando en lugar de ponerte frente a un consejo de guerra, Ўpero no esperes un ascenso en una buena temporada!",
"No volverб a pasar, #saddr#. ЎLo prometo!",
"ЎEres una desgracia para mi gran nacion! Por la presente, se te expulsa del servicio con deshonor. ЎFuera de mi vista!",
"Deberнa haberlo visto venir, supongo. Puede que nos encontremos de nuevo en el futuro, aunque es probable que sea bajo circunstancias diferentes. ЎY puede que a Su Excelencia no le guste!",
"Por cierto, necesito que me devuelvas el documento que te di. Ya no serб valido.",
"Por supuesto, #saddr#.",
"Ahora, ve a #sGreenford#, al Cuartel General Naval, por favor. #sbriefing_officer# te espera allн con tus nuevas уrdenes, creo.",
"Muy bien, #saddr#. Zarparй rumbo a #sGreenford# de inmediato.",
"їQuй van diciendo de mн otros piratas estos dнas?",
"ЎHan oнdo hablar de tus recientes hazaсas! Te llaman ",
"Tus incursiones no han pasado desapercibida entre los Hermanos de la Costa. Se han referido a ti como ",
"ЎEse ъltimo saqueo fue la comidilla de la taberna durante dнas! Te estбn llamando. ",
"Normalmente, eso serнa cierto. Tus hazaсas deberнan haberte hecho ganar un ascenso\n No obstante, me ha llegado la noticia de que has estado ejecutando prisioneros de guerra. Esto es en violaciуn de las regulaciones de guerra que debe sobedecer\n Si nuestros enemigos se enteran de ello, podrнan tomar represalias y ejecutar a aquellos de nuestros hombres que han caнdo prisioneros\n Como puede que no estuvieras al tanto de esta situaciуn, serй indulgente por esta vez. Tu ascenso estб bloqueado, pero no se tomarбn mбs medidas.",
"Agradezco la misericordia de Su Excelencia.",
"Pero ten cuidado. Ya no tienes la excusa de la ignorancia. Si me entero de mбs ejecuciones por tu parte, se te expulsarб del servicio.",
"\n Ademбs, tengo entendido que posees patentes de corso de otras naciones. Escribirй a sus embajadores para informarles de todo esto. Sus gobernadores tampoco verбn con buenos ojos la ejecuciуn de prisioneros de guerra.",
"Entiendo, Excelencia. Adiуs.",
"Tendrнas que ponerte en contacto con los contrabandistas locales; con este propуsito, te proporcionarй las mercancнas adecuadas. Lamentablemente, tu barco no tiene la suficiente capacidad para aocmodoar esa carga.",
"Muy bien, volverй cuando tenga mбs espacio en mis bodegas.",
"Deseo informar de que he arrestado personalmente a los contrabandistas. Su Excelencia puede leer todos los detalles en mi informe.",
"ЎMuy bien, #saddr#!",
" Ahora, en cuanto a los #samount# quintales de #scargo# que te fueron entregados. Son propiedad del estado y deben ser devueltos. ",
"Los estбn descargando de tu barco en este momento.",
"Me parece justo.",
"Parece que ya no tienes el cargamento. Te doy un mes para recuperarlo. Si no lo haces, asumirй que lo has robado y se te declararб fuera de la ley.",
"Su Excelencia no debe preocuparse, Ўtraerй de vuelta ese cargamento, de un modo u otro!",
" Bueno, recibiste de los contrabandistas una suma de #smoney# piezas de oro a cambio de la mercancнa que te fue proporcionada por el estado, por lo tanto ese dinero tambiйn pertenece al estado. Por favor, devuйlvelo.",
"Tambiйn recibiste de los contrabandistas una suma de #smoney# piezas de oro a cambio de la mercancнa que te fue proporcionada por el estado, por lo tanto ese dinero tambiйn pertenece al estado. Por favor, devuйlvelo.",
"Por supuesto, Excelencia.",
"Hum... No tengo esa cantidad ahora mismo.",
"Ya veo. En ese caso, te doy un mes para conseguir #smoney# piezas de oro y traйrmelas. Si no lo haces, asumirй que has robado el dinero y se te declararб fuera de la ley",
"ЎEn ese caso, serб mejor que salga cuanto antes para recuperar el dinero de Su Excelencia!",
"Y ahora, hablemos de tu recompensa. ",
"Por contactar con los contrabandistas e informar sobre sus actividades, recibirбs ",
"Por arrestar a los contrabandistas personalmente, recibirбs ",
" por ciento del valor de la mercancнa. Eso suma ",
" piezas de oro.",
"una recompensa de ",
" piezas de oro, ya que la mercancнa no valнa mucho.",
"їEstбs en condiciones de reemplazar los #samount# quintales de #scargo# que se te confiaron para tu misiуn con los contrabandistas?",
"Sн, tengo la mercnacнa de Su Excelencia.",
"No, aъn no he podido reemplazar la mercancнa.",
"Eso estб bien. La mercancнa serб descargada de tu barco de inmediato. ",
" ЎY ahora, sal de mi vista!",
"їTienes las #smoney# piezas de oro que debes al estado tras tu misiуn con los contrabandistas?",
"Sн, tengo suficiente para pagar a Su Excelencia.",
"No, aъn no tengo suficiente para pagar a Su Excelencia.",
"Muy bien. En ese caso, no habrб mбs castigo, pero esto quedarб reflejado en tu expediente.",
" ЎAhora, vete!",
"Entonces, vete, y no vuelvas hasta que no tengas lo que me debes. ЎRecuerda que mi paciencia es limitada!",
"Adiуs, #saddr#.",
" Ademбs, ",
"tengo unammisiуn especial par alguiend con tus particulares... talentos.",
"їUna misiуn especial? Suena interesante.",
"Debes investigar el '",
"', ",
" en el puerto de ",
", en ",
".",
"їQuiere Su Excelencia que sabotee el '",
"'?",
"No. El barco en sн mismo es de poca importancia, pero creemos que se unirб auna fuerza mayor en algъn otro lugar. Tu misiуn es encontrar es fuerza y volver a quн a informarme\n Tampoco serнa de gran utilidad que averiguaras cuбles son los planes del enemigo para esa fuerza.",
"Entiendo. Zarparй rumbo a ",
" en cuanto me sea posible. Adiуs, Excelencia.",
"Todo eso suena un poco complicado para mн, Excelencia. Tal vez, cuando tenga mбs expreiencia, me sienta capaz de llevar a cabo es amisiуn. Hasta entonces, adiуs.",
"Ah, has regresado. їHas completado tu misiуn?",
"Sн, Excelencia. Conseguн subir a bordo del '",
"', que zarpу desde ",
" rumbo a ",
". Allн, logrй colarme en el ayuntamiento, donde encontrй los planes del enemigo. Aquн traigo una copia. Dejй el original donde estaba para que el enemigo no sospeche que lo encontrй.",
"ЎMuy astuto! Has hecho un excelnte trabajo. ",
"Ahora que sabemos lo que el ",
" pretende hacer con su flota, podemos enviar nuestros propios barcos a prepararles una sorpresita. Aquн estб tu recompensa.",
"Como puede que ya sepas, mientras estabas fuera, ",
" y ",
" han firmado un tratado de paz. Pero los planes que nos has traнdo demuestran que ",
" probablemente tiene la intenciуn de romper el tratado. Cuando lo hagan, estaremos preparados apr aellos. Aquн estб tu recompensa.",
"Hay una cosa mбs, Excellency. Tuve que contratar un barco para que me trajera de vuelta aquн. No tenнa suficiente dinero para pagar al capitбn, asн que prometн pagarle el doble de lo que costaba el pasaje al llegar aquн. їPuedo solicitar que esa cantidad sea asumida como gastos de la misiуn?",
"їDe quй cantidad estamos hablando?",
"Debo ",
" piezas de oro, Excelencia.",
"ЎYa te he pagado ",
", y ahora quieres mбs! Pero soy una persona razonable. No deberнa dejarte en la estacada despuйs del servicio que nos has prestado\n Muy bien, puedes contar con otras ",
" piezas de oro como paga extraordinaria. Con eso y con lo que ya te he pagado, cubrirбs tu deuda y aъn te quedarб algo de recompensa.",
"Gracias, Excelencia.",
};
