string DLG_TEXT[31] = {
"Lo siento. Tengo que irme.",
"...",
"¡Te lo ruego, ",
"! ¡Por favor, ayúdame!",
"¿Qué está pasando aqui?",
"¡Quieren matar al viejo!",
"¿Dónde están los soldados? Es su trabajo mantener el orden en esta ciudad, no el mío.",
"¡Los soldados tienen que vivir aquí, tú no! Y pareces una persona decente. ¿No salvarás a ese pobre viejo? ¡Esos bárbaros van a quemarlo vivo!",
"¿Por qué? ¿Qué ha hecho?",
"¿Vas a quedarte aquí interrogándome mientras lo matan?",
"La multitud está preparando la pira. Tienes mucho tiempo para responder a mis preguntas.",
"¡¿Cómo puedes actuar con tanta calma?!",
"Llámalo un requisito de mi trabajo. Ahora están atando al viejo a la hoguera. Quizás quieras hablar antes de que sea demasiado tarde.",
"¡De acuerdo! Se le acusa de brujería, pero créeme, es un hombre normal. ¡Vive solo en el faro y nunca molesta a nadie!",
"Entonces, ¿por qué la multitud tiene tantas ganas de asarlo? ¿Y por qué eres tú la única persona que quiere salvarlo?",
"Es un chiflado inofensivo. Siempre está inventando algún cacharro nuevo, y la mayoría de ellos no funcionan como se supone que deberían; así que ha molestado a mucha gente.",
"Sí, la verdad es que parecen bastante molestos.",
"Bueno, esta mañana explotó algo en su faro, y el viento arrastró una nube apestosa que cubrió toda la ciudad.",
"Menuda nube debe haber sido para justificar quemarlo en la hoguera. Pero de nuevo, ¿por qué solo tú quieres salvarlo?",
"Una vez, mi hija enfermó gravemente y nadie podía ayudarla. ¡Pero ",
"researcher",
" encontró una cura para ella en un viejo manuscrito indio!",
"Bueno, eso suena digno de salvación. Haré lo que pueda. ¿Como dijiste que se llamaba? ",
"researcher",
", ¿no?",
"Es una historia muy conmovedora. Pero no creo que sea lo bastante conmovedora como para hacer que me enfrente a una turba asesina.",
"¡Oh, Dios te bendiga! ¡Estás haciendo una buena obra!",
"Haré lo que pueda.",
"¿No tienes corazón, #ssir#? ¡No eres mejor que esos asesinos que construyen la pira!",
"¿Como que no tengo corazón? ¡Tengo el corazón de una ballena! Si tengo que demostrártelo, lo haré.",
"Puedo que no lo tenga, pero no puedo quedarme mirando mientras esto sigue adelante. Ayudaré al viejo si puedo.",

};