string DLG_TEXT[88] = { 
"¿No ves que estoy de servicio? No me molestes.",
"Está bien, está bien.",
"¿Quieres denunciar algún crimen?",
"No, por supuesto. Soy capitan, después de todo..., pero veo que no me estás escuchando.",
"Recuerda: no permitimos que haya peleas en las calles. Por supuesto, puedes defenderte si alguien te ataca.",
"De acuerdo, tendré en cuenta esa información.",
"No hay quien aguante este clima..., y tengo que quedarme aquí quieto. Tal vez no me creas, pero mi único pasatiempo consiste en espantar las moscas que intentan posarse en mi cara.",
"Es una pena, pero no puedo ayudarte. Es tu deber.",
"Si quieres charlar, búscate a otro. Estoy cumpliendo con mi deber y mi deber no incluye hablar contigo.",
"Solo me preguntaba si estabas vivo o no. Estás ahí plantado como una estatua.",
"¿Crees que es fácil proteger nuestra ciudad? ¡Pues no! Es un trabajo muy importante y peligroso. Me acuerdo que una vez...",
"Otro día me lo cuentas. Tengo que irme.",
"Vete, no me molestes.",
"Lo que tu digas, soldado.",
"¡Eh! ¿Por qué no me traes un vaso de ron de la taberna?",
"Tal vez. Pero, ¿no me colgarán por ayudar a emborracharse a un soldado de servicio? No, espera a que cambien la guardia y entonces podrás beber tanto como te plazca.",
"¡¿Por qué siempre tienen que ser rudos marineros los que intentan hablar conmigo?! ¿Es que no hay chicas guapas en esta ciudad?",
"¿A esto lo llamas cumplir con tu deber? Oye, no querrás dejar escapar a un criminal peligroso como yo, ¿no? ¡Ja, ja!",
"Se te ve muy saludable. ¿No quieres alistarte en nuestro ejército? Tenemos mucho espacio en los barracones, buena comida y ron gratis.",
"Suena bien, pero no puedo aceptar la oferta. La disciplina militar no va conmigo.",
"Qué calor... Daría lo que fuera por volver a mi querida Inglaterra.",
"Sí, no parece que te siente bien este clima.",
"Necesito tu ayuda para salvar a un hombre.",
"Quiero saber más sobre lo que está pasando en la ciudad últimamente.",
"¿Qué es exactamente lo que quieres saber? Siempre está pasando algo en la ciudad, no conozco todos los rumores. Mejor pregunta en la taberna.",
"Creo que puedes ayudarme. Estoy buscando información sobre alguien a quien acusaron de asesinato, y que luego huyó.",
"¡Ah, eso! Claro que lo sé.",
"Cuéntame todos los detalles. Su Señoría el gobernador me ha ordenado investigar este caso.",
"¿Cómo sé que tú representas al gobernador?",
"Mira, esta carta está firmada por el propio gobernador.",
"De todos modos, será mejor que hables con el comandante de la prisión, ",
". Él sabe mejor lo que pasó.",
"Hablaré con él mas tarde, pero ahora quiero saber lo que sabes.",
"Muy bien, haz tus preguntas.",
"Dime en detalle cómo fue el arresto, qué llevaba encima, cómo escapó.",
"Era tarde por la noche, mi compañero y yo patrullábamos las calles...",
"¿Quieres decir que hiciste el arresto tú mismo?",
"Así es.",
"Continúa.",
"Y de repente, vemos a una chica vestida con ropa de hombre saliendo de una casa, con sangre en sus botas.",
"¿Así que dices que viste sangre en #spronoun3# botas esa noche?",
"Sí, #spronoun2# vi a la luz de un farol de la calle.",
"Ah. ¿Y entonces qué?",
"Entonces, #spronoun2# arrestamos y después, cuando vimos un cadáver tirado en un charco de sangre, pusinmos a tu #sgirl# bajo custodia.",
"Ya veo. ¿Encontrasteis algo interesante entre sus cosas?",
"Estaba registrándo#spronoun2#, pero me interrumpieron.",
"¿Qué quieres decir?",
"¿Te lo imaginas? Este otro tipo intentó robar un pequeño bote, y cuando lo atrapamos, le quitamos un extraño ídolo de oro.",
"Eso es interesante. ¿Y qué pasó con este ídolo?",
"Esa es mi desgracia. El capitán estaba en la patrulla nocturna. Así que se llevó el ídolo.",
"Gracias por tu ayuda, soldado.",
"No hay de qué, ",
", es mi deber proteger a los ciudadanos.",
"¡Perfecto! Entonces ayúdame a evitar la muerte de un anciano.",
"Bueno... Mira, ",
", no puedo ayudarte.",
"¿Por qué, soldado? ¿Acaso no es un ciudadano de esta ciudad?",
"Claro que sí.",
"Entonces, ¿qué? No creerás que es un hechicero...",
"¡No! Si lo fuera, podría echar a volar y escaparse.",
"Entonces, ¿por qué no me ayudas?",
"Debes comprenderlo; todos creen que es un siervo de Satanás, y no podemos tener algo así en esta ciudad.",
"¿Así que tienes miedo de un escándalo público?",
"Algo así, ",
".",
"¿Y si os pago a ti y a tu compañero 200 piezas de oro?",
"¡Estoy de Servicio!",
"Veo que no puedo persuadirte.",
"Está bien, ",
". Dame tu dinero. Hay seis de nosotros aquí, por lo que serán 1200 piezas de oro. Ten la seguridad de que la vida de ese hombre estará a salvo.",
"Bien, aquí está tu dinero.",
"Espera, eso es más de lo que puedo pagar.",
"Desaparece, ",
".",
"Traeme al viejo, esperaré cerca de la puerta.",
"¡No me hables así, ",
"! ¡Sirvo a Inglaterra!",
"¡Mira! ¿Un hombre inocente muere, y tú no haces nada? No sirves a nada... ¡Eres demasiado cobarde para enfrentarte a un poco de peligro!",
"¡Tal vez sea así, ",
"! Pero para demostrarte que no soy un cobarde, te traeré a tu hombre. Espérame cerca de la puerta.",
"Eso suena bien, amigo mío.",
"¿Qué quieres?",
"¡Serás... hip... serás bellaco! ¡Has hecho daño a... hip... mi amigo!",
"¿Qué amigo? Si no hay nadie contigo, ",
".",
"¿Qué? Estaba... aquí hace un momento. Iré a buscarlo. ¡Tú... hip... espera aquí si quieres que te zurre!",
"¡¿Cómo te atreves a llevarme la contraria?! ¡Te voy a estrangular!",
"Y de repente vemos a un hombre saliendo de una casa, con sangre en sus botas.",

};