string DLG_TEXT[201] = { 
"Me han dicho que has hecho un gran esfuerzo para pedir una audiencia. Mi nombre es ",
". Ahora, por favor, digame el proposito de su visita., ",
".",
"Mi nombre es ",
".",
"Ah, eres tu otra vez. ?Que te trae por aqui esta vez? ",
"Me gustaria hablar con usted acerca de algunos negocios.",
"Lo siento, pero hay cosas que tengo que hacer.",
"Entonces, ?por que me distraes de los asuntos de estado tan importantes?",
"Me gustaria hablar con usted acerca de un pequeno negocio.",
"Solo estoy aqui para presentar mis respetos, #saddr#. Nada mas.",
"En ese caso, por favor deja mi estudio y dejame volver a asuntos mas importantes.",
"Si, por supuesto. Siento haberte molestado.",
"Lo siento, pero no tengo nada de que hablar ahora",
"Oh, si? Tengo una propuesta para usted, capitan.",
" ?De verdad?",
" Me he enterado de que ha completado usted la tarea con exito; !mi enhorabuena, capitan! Aqui esta tu recompensa.",
" Muchas gracias; ha sido un placer ayudaros.",
"Debes destruir el ",
" vaso ",
"pirata de la busqueda",
"amenazando el envio ",
". Si la hundes, te recompensare la considerable suma de ",
" oro. ?Que dice, capitan?",
"No volveras a saber de ella, eso te lo prometo.",
"Me temo que no puedo ayudarte.",
"Deseo perdon, su excelencia.",
"Estoy interesado en aprender acerca de las relaciones de #sgov_nation# con otras Naciones.",
"Estoy buscando Una carta de Marca.",
"He oido que estoy a favor de un ascenso.",
"No puedo servir ",
"excelencia.",
"Estoy harto de servir ",
"Como seguro de que usted es un capitan capaz, y para recompensar mi tiempo en la presentacion de su caso a ",
", Debo pedirte ",
" oro.",
"De ninguna manera.",
"Muy bien.",
"#sgov_nation# siempre se complace en aceptar nuevos capitanes a su Servicio. ",
"Actualmente estamos en guerra con ",
"",
"no hay gran poder, pero ",
". Por supuesto, ",
"Los piratas siempre deben ser hundidos a la vista.",
"A la luz de su Servicio anterior, ",
"te otorga el rango de ",
"Os hare sentir orgullosos, excelencia.",
"Hemos hecho dano ",
", y ",
"no olvida a sus enemigos. !Vete de una vez, o los guardias te tiraran a la oreja!",
"...",
"Hemos causado ",
"gran dano, capitan, pero ",
"esta dispuesto a pasar por alto sus transgresiones pasadas... por un precio: ",
" Muy bien, Senor. Acepto.",
"Un placer tratar con usted, ",
"Y usted, su excelencia.",
"Estas hecho! Excelente trabajo. Tu nuevo rango es ",
". Ademas, se le premia ",
"acres de tierra por orden de ",
"Gracias, Senor.",
"? Estas seguro, ",
"lamentara perder su Servicio.",
"Si, lo soy.",
"no toman amablemente a los chaqueteros, ",
"No importa.",
"Muy bien. Pero espero que lo reconsidere, con tiempo...",
"Despedir, ",
"?Eh?",
"Duro.",
"Bienvenidos a Cartagena, #ssir#. Soy Gregorio Montavez, el conc de Este pueblo. Es un placer ver a un alto representante de la nobleza aqui. ?Tuviste un buen viaje?",
"Si, gracias. Como sabe, soy Don Guillermo de la Rosa, Enviado de nuestro Rey.",
"Lo sabia. Se esperaba su llegada...",
"Me han dicho que Cartagena era la ciudad mas hermosa del Caribe y es verdad. Solo el puerto es impresionante con este gran fuerte que guarda la entrada.",
"Es San Felipe, excelencia. Se puede vinculadas a cualquier ataque de buques de guerra. ",
"Creo. Espero visitarlo.",
"Por supuesto, manana, te mostrare el fuerte de San Felipe si aceptas.",
"Excelente, de todos modos, comprobar las defensas de Cartagena es uno de los objetivos de mi visita. Por favor, lea esta carta escrita por nuestro Rey para entender mejor el proposito de mi venida.",
"Ya veo... Debo darte todos los detalles de la situacion de Cartagena: fuerzas y debilidades y ?cual es mi estrategia para desarrollar la ciudad. Es un informe largo que debe preparar.",
"No te preocupes, tendre el tiempo necesario para este trabajo. Debo quedarme aqui dos semanas antes de Turquia las otras colonias espanolas del Caribe.",
"Muy bien, pero primero dejame preparar una fiesta. Esta noche, seras el invitado de honor de Cartagena. Para la cena, toda la aristocracia de mi ciudad estara contigo. Y no olvide que tendras un dormitorio en mi residencia, mas comodo que una cabina para tu estancia.",
"Gracias por la invitacion, conc.",
"?Me seguiras para que pueda mostrarte un poco la ciudad?", 
"Me gustaria, pero ahora no puedo. Debo hablar con el Capitan de mi nave para darle algunas instrucciones para la estancia.",
"Acto. No llegues tarde a mi casa esta noche.",
"Por supuesto, no quiero perderme mi propia fiesta ja ja!",
"!Dom Guillermo, adelante! Permitanme presentarles a algunas buenas personas de Cartagena.",
"Por supuesto, conc.", 
"Como dije, permitanme presentarles a algunas personas de mi pueblo. El primero es el Almirante de mi pueblo, Lorenzo Delgado.",
"Espero que te guste esta fiesta.",
"Obviamente, Excelencia. Sin embargo, no me gustaria ir a descansar demasiado tarde esta noche.",
"Es comprensible. Tan pronto como estes cansado, habla con mi valet, te mostrara tu habitacion.",
"Muchas gracias.",
"Dom Guillermo de la Rosa! ?Descansaste lo suficiente anoche?",
"Si, Conc. El dormitorio de la residencia es mucho mejor que la cabina de un barco para dormir.",
"!Ja! ja! Lo predije. ?Estas listo para Turquia Cartagena?",
"Absolutamente. Estoy sobre todo impaciente por Turquia el fuerte de San Felipe.",
"El fuerte mas fuerte del Caribe como ustedes saben. Comencemos por el fuerte si lo desea, Dom Guillermo...",
"Como se puede ver, la fortaleza se encuentra en un lugar estrategico, dominando los accesos a la ciudad por tierra o por mar.",
"De hecho, la ubicacion no podia ser mejor.",
"Incluso si la fortaleza es antigua viendo que la construccion comenzo en el ano 1536, hace unos anos, se amplio.",
"?Podria explicarme su arquitectura?",
"Por supuesto, la fortificacion consiste en una serie de paredes, anchas en la base y estrechas hacia el parapeto, formando un formidable patron de bunkeres. Las baterias y los parapetos se declaran unos a otros, por lo que es practicamente imposible tomar una bateria sin tomar todo el sistema de defensa. Las armas del castillo comandan toda la bahia, asi que cualquier nave sospechosa que intente atracar podria ser atacada.",
"Impresionante...",
"La fortaleza es sorprendente por su gran entrada y su complejo laberinto de tuneles. En Resumen, es el mas formidable complejo defensivo de las fuerzas armadas espanolas en el Caribe.",
"?Que quieres decir con el < laberinto complejo de tuneles? Hay alguna diferencia con las otras fortificaciones espanolas?",
"El numero de tuneles es mayor que cualquier otro fuerte espanol en el Caribe. Esto permite a los soldados moverse rapidamente de un punto a otro y esto es una ventaja si el fuerte esta bajo ataque.",
"Ciertamente...",
"Pero los tuneles no se limitan a la fortaleza.",
"No acto, conc.", 
"Hay incluso un tunel que conecta el fuerte con la ciudad. Asi, la fortaleza puede recibir las guarniciones de la ciudad si es atacada.",
"Esto aumenta drasticamente el numero de soldados que pueden defender la fortaleza...",
"Si. Por eso considero a San Felipe inalcanzable.",
"Humm... Solo por curiosidad ?donde esta la salida del tunel en la ciudad?",
"No te preocupes, esta En la oficina del Almirante. La mejor ubicacion protegida de la ciudad HAHA!",
"Todo parece estar bien pensado. Nuestro Rey estara encantado de saber como la ciudad esta bien protegida.",
"Gracias, Dom Guillermo. Pero siganme, hay algo que quiero mostrarles.",
"Aqui estamos, en la cima del fuerte.",
"La vista es fantastica en la bahia.",
"Efectivamente. Pero Sigueme a esta cabana justo enfrente de TI. Creo que te gustaria otra vista.",
"Mira esta reserva de polvora.",
"!Que cantidad impresionante de Campeones tienes!",
"Barriles de polvora y balas de canon. Podriamos luchar contra una armada de naves si fuera necesario.",
" Por Supuesto, Conc. Ya pensaba que San Felipe era un fuerte impresionante, pero ahora tomo nota de sus defensas y su organizacion es la mejor que he visto. Mi visita a Cartagena no ha terminado pero debo decir que mis primeras impresiones son muy buenas.",
"Gracias por estas palabras alentadoras, Dom Guillermo. Pero veo que ya es mediodia, tal vez quieras almorzar conmigo en mi residencia antes de continuar tu visita.",
"Gracias, conc por su invitacion pero desde ayer por la tarde no vi a mi tripulacion y debo hablar con ellos para saber si todo esta bien en mi nave. Entonces, almorzare con ellos en el barco.",
"Como quieras, te espero esta tarde en mi residencia para que podamos continuar la visita.",
"Estare alli a las 2 en punto.",
"!Ah! Dom Guillermo,",
"Conc, acabo de hablar con su hija frente a su residencia y me dijo que tiene un problema con los holandeses.",
"Desafortunadamente, si. Uno de sus buques de guerra ataco a muchos barcos mercantes espanoles en los ultimos meses en la ruta entre Cartagena y Puerto Rico. De uno de nuestros espias, yo sabia de una hora antes de que el buque de guerra de los moros en Willemstad y ella se queda alli una semana mas para ser reparados y suministrados. Decidi atacarla con mi propia flota en los proximos dias.",
"Entonces, ?no puedo continuar la visita de la ciudad con ustedes esta tarde?",
"Es cierto, Dom Guillermo. Necesito muchos dias para terminar esta operacion y hoy pesare el ancla. ?Quieres acompanarme durante la mision.",
"Humm... Prefiero continuar mi deber aqui, conc. Tambien tengo una mision que cumplir y estoy seguro de que podria preparar mi informe hablando con sus subordinados.",
"Por supuesto, Dom Guillermo. La gente de Cartagena te dara toda la ayuda necesaria durante mi ausencia.",
"Gracias Gobernador. Ha llegado el momento de dejarte en paz. Debes preparar tu permiso y no quiero retrasarlo mas.",
"No te preocupes, en unos dias, volvere trayendo buenas noticias.",
"Nuestro rey apreciara su lealtad a Espana. Que tengas un buen viaje.",
"!Dom Guillermo ! Estaba a punto de enviar a un hombre a su nave. Tenia prisa por hablar contigo.",
"?Es sobre la mision? ?Tuviste exito?",
"Bien... En realidad no, desafortunadamente. Los holandeses han rechazado nuestra incursion. He tenido la sensacion de que nos estaban esperando.",
"?Como es posible?",
"No lo se. Willemstad estaba preparado para el ataque y no se benefician del efecto sorpresa. De todos modos, encontrare otra forma de hundir su flota. Pero no se trataba de la mision que queria verte.",
"?No?",
"Aprendi que peleaste con Dom Ortega.",
"Fue solo un desacuerdo.",
"?Llamas duelo a la discusion?! Dom Ortega es una de las personas mas importantes de mi pueblo. ?Es tu manera de agradecer mi hospitalidad?",
"Lo siento, conc. Esto no volvera a pasar.",
"Espero que si, porque de lo rec4 informar de su comportamiento a nuestro Rey. No estoy seguro, lo aprecia. De todos modos, hay otro problema. Sabia la razon de este duelo. Parece que quieres cortejar a mi hija.",
"Tenemos muchas afinidades...",
"Y no puedo aceptar esta situacion. Le prometi la mano de la hija a los padres de Ortega. Quiero reunir a nuestras familias con la boda.",
"Conc, su hija no ama a Dom Ortega.",
"No es tu problema, Dom Guillermo. Esto es algo que debo resolver entre mi hija y yo. Con el tiempo, cambiara de opinion sobre Dom Ortega.",
"Pero...",
"Basta, Dom Guillermo. Nuestra discusion sobre mi hija ha terminado. Hasta que te vayas, mi hija se quedara en el claustro de Cartagena y tu tienes Prohibido volver a verla. ?Estamos de acuerdo?",
"[PIENSA: !al diablo! Como desee, conc.",
"Excelente, sabia que eras razonable #sgender#. De lo contrario, ?todavia necesita mi ayuda para terminar su informe?",
"Solo necesito ver a su Almirante.",
"!Ah! Ya debe estar en su oficina a esta hora. La tarea fue dificil para el durante la mision, pero es un hombre valiente y no defrauda incluso despues de un fracaso.",
"Es bueno oirlo. Voy a su oficina ahora mismo. Que tenga un buen dia, conc.",
"!Dom Guillermo! ?Como estan ustedes?",
"Estoy bien, conc Montavez. Solo dos dias antes de mi permiso.",
"Hay un final para todo.",
"Efectivamente. Que raro...",
"?Que es raro?",
"Hace una hora, estaba hablando con un guardia y sabia que un pirata habia sido arrestado en el Claustro. Pirata, Claustro... ?Cual es el vinculo?",
"Confirmo y sabemos su nombre. Es Johan Elting, un traidor. Fue reconocido por uno de mis capitanes liderando una patrulla en la noche. Este capitan trabajo muchos anos en la Habana antes de ser transferido aqui.",
"Un traidor??",
"Si, trabajo para Espana. De hecho, para el ex vicealmirante de #sHavana# antes de traicionarlo y matarlo.",
"Eso es horrible! No podemos confiar en ningun Holandes.",
"Tienes razon. Desafortunadamente, el vicealmirante cometio este error. Pero conmigo, no tendra ninguna oportunidad. Sera ahorcado pronto.",
"Bueno. Debe estar enfrentamos en la carcel.",
"No.",
"?No??",
"Esta enfrentamos, por supuesto, pero en un lugar secreto. Queria asegurarme de que ningun miembro de la tripulacion o amigo suyo intentara liberarlo antes de su muerte.",
"Buena iniciativa. No sabia que tenias otra carcel en la ciudad...",
"Es una cueva secreta debajo de la iglesia. Nadie podria pensar en un lugar asi alli JAJA!!",
"!JAJA! Que ingenio! !Reconozco el espiritu espanol! Entonces, ?sera ahorcado hoy?",
"No, manana. Quiero saber por que estaba en el claustro. Creo que estaba tratando de secuestrar a mi hija para un rescate futuro pero no estoy completamente seguro. Es por eso, que va a ser torturado para obtener una declaracion.",
"[PIENSA: Tortura!? Podria ser inutil, un pirata como el debe tener una gran voluntad. Podia soportar cualquier tipo de tortura.",
"Ya veremos. Pero, no pierda mucho tiempo y hable de la vida de un pirata. Si no, ?todavia necesitas mi ayuda antes de irte?",
"No particularmente. Ordene a mi tripulacion preparar el permiso comprando los suministros necesarios y manana por la tarde esta tarea se llevara a cabo.",
"?Y Cual sera su proxima mision?",
"Debo Turquia la Habana y Santiago de Cuba como lo hice aqui antes de regresar a Espana.",
"Bueno. ?Podria presentarme antes de irse las conclusiones de su informe sobre Cartagena, Dom Guillermo?",
"Lo hare. Te vere manana por la tarde para el informe. Que tenga un buen dia, conc.",
"Buenas tardes, Dom Guillermo.",
"Buenas tardes, excelencia. Cuando estaba cruzando la ciudad, note que habia mas soldados patrullando.",
"De hecho, una orden mia. Anoche, el holandes Elting fue liberado. Estamos tratando de encontrarlo.",
"Increible, ?como fue eso posible?",
"Alguien lo ayudo... Lo mas curioso es que no acto como sabia que Elting estaba escondido en la iglesia.",
"Tal vez, algunos de sus hombres estaban espiando en la ciudad y han visto a sus soldados llevandolo a la iglesia.",
"Debes tener razon. Les dije que tomaran a Elting discretamente pero parece que todavia hay algunas personas incompetentes en mi guardia. Me encargare de ellos mas tarde.",
"Bueno, de lo rec, creo que pidio presentar mi informe hoy.",
"Tienes razon. Puedes empezar tu discurso.",
"Gracias, Dom Guillermo. Por lo que has dicho, parece que te gusto como se gestiona y protege la ciudad.",
"Exactamente. Nuestro rey estara complacido por mi informe sobre Cartagena. Espero ver el mismo nivel de exigencia en Cuba.",
"Creo que si. Se que los Gobernadores de Santiago y la Habana y que no ahorran esfuerzos para proteger a sus pueblos",
"Eso es perfecto, excelencia. Es hora de volver a mi nave y confirmar que todos los preparativos para mi viaje a Cuba estan listos.",
"Por supuesto, por supuesto. Hazlo, manana por la manana estare en el puerto para despedirme.",
"Gracias, hasta manana.",
};
