string DLG_TEXT[201] = { 
"Me han dicho que has insistido mucho para pedir una audiencia. Mi nombre es ",
". Ahora, por favor, dime el propósito de tu visita, ",
".",
"Mi nombre es ",
".",
"Ah, eres tú otra vez. ¿Qué te trae por aquí esta vez? ",
"Me gustaría hablar con Su Excelencia acerca de algunos asuntos.",
"Lo siento, pero hay cosas que tengo que hacer.",
"Entonces, ¿por qué me distraes de mis importantes asuntos de estado?",
"Me gustaría hablar con Su Excelencia acerca de un pequeño asunto de negocios.",
"Solo estoy aquí para presentar mis respetos, #saddr#. Nada más.",
"En ese caso, por favor, sal de mi estudio y déjame volver a asuntos más importantes.",
"Sí, por supuesto. Siento haber molestado a Su Excelencia.",
"Lo siento, pero no tengo nada de qué hablar ahora mismo",
"Oh, ¿sí? Tengo una propuesta para ti, capitán.",
"¿De veras?",
"Me he enterado de que has completado la tarea con éxito; ¡mi enhorabuena, capitán! Aquí está tu recompensa.",
"Muchas gracias; ha sido un placer ayudar a Su Excelencia.",
"Debes destruir un barco de ",
" vessel ",
"quest pirate",
", que amenaza el tráfico marítimo en aguas de ",
". Si lo hundes, te recompensaré con la considerable suma de ",
" piezas de oro. ¿Qué dices, capitán?",
"Prometo a Su Excelencia que no volverá a saber de ese barco.",
"Me temo que no puedo ayudar a Su Excelencia.",
"Suplico el perdón, Excelencia.",
"Me gustaría saber más acerca de las relaciones de España con otras naciones.",
"Quiero conseguir una patente de corso.",
"He oído que se me ha concedido un ascenso.",
"No puedo seguir sirviendo a ",
", Excelencia.",
"Me he hartado de servir a ",
"Debido a tu reputación en nuestra nación, y para compensar el tiempo que voy a perder en presentar tu caso a ",
", debo pedirte ",
" piezas de oro.",
"De ninguna manera.",
"Muy bien.",
"#sgov_nation# siempre se complace en aceptar nuevos capitanes a su servicio. ",
"Actualmente estamos en guerra con ",
"",
"... ninguna gran potencia, pero ",
". Por supuesto, ",
"los piratas siempre deben ser hundidos en cuanto sean avistados.",
" A la luz de tus anteriores servicios, ",
"te otorgo el rango de ",
"Haré que Su Excelencia se sienta orgulloso.",
"Has dañado los intereses de ",
", y ",
" no olvida a sus enemigos. ¡Vete inmediatamente, o los guardias te echarán a patadas!",
"...",
"Has causado a ",
" grandes daños, capitán, pero ",
"está dispuesta a pasar por alto tus transgresiones pasadas... por un precio: ",
"Muy bien, Excelencia. Acepto.",
"Un placer tratar contigo, ",
"Y con Su Excelencia.",
"¡En efecto! Excelente trabajo. Tu nuevo rango es ",
". Además, se te concedido un premio de ",
"acres de tierra por orden de ",
"Gracias, Excelencia.",
"¿Seguro, ",
" lamentará perder tus servicios.",
"Sí, seguro.",
" no ve con buenos ojos a los chaqueteros, ",
"Hum..., no he diho nada.",
"Muy bien. Pero espero que lo reconsideres, con tiempo...",
"Adiós, ",
"¿Eh?",
"Se siente.",
"Bienvenido a #sCartagena#, #ssir#. Soy Gregorio Montavez, el gobernador de esta ciudad. Es un placer ver a un alto representante de la nobleza aquí. ¿Habéis tenido un buen viaje?",
"Sí, gracias. Como Su Excelencia sabe, soy don Guillermo de la Rosa, enviado de nuestro Rey.",
"Lo sabía. Esperábamos vuestra llegada...",
"Me habían dicho que #sCartagena# era la ciudad mas hermosa del Caribe y es verdad. Solo el puerto es impresionante con este gran fuerte que guarda la entrada.",
"Es San Felipe, excelencia. Puede resistir a cualquier ataque de buques de guerra. ",
"Lo creo. Espero visitarlo.",
"Por supuesto, mañana os mostraré el fuerte de San Felipe si aceptaís.",
"Excelente. De todos modos, comprobar las defensas de #sCartagena# es uno de los objetivos de mi visita. Esta carta escrita por nuestro Rey explicará mejor el propósito de mi venida.",
"Ya veo... Debo daros todos los detalles de la situación de #sCartagena#: fuerzas y debilidades y cuál es mi estrategia para desarrollar la ciudad. El informe que debéis preparar es largo.",
"Su Excelencia no debe preocuparse, tendré el tiempo necesario para este trabajo. Debo quedarme aquí dos semanas antes de visitar las otras colonias españolas del Caribe.",
"Muy bien, pero primero dejadme preparar una fiesta. Esta noche, seréis el invitado de honor de #sCartagena#. Para la cena, toda la aristocracia de mi ciudad estará presente. Y no olvideis que tendréis un dormitorio en mi residencia, más comodo que el camarote de un barco para vuestra estancia.",
"Gracias por la invitación, gobernador.",
"¿Me seguiréis para que pueda mostraros un poco la ciudad?", 
"Me gustaría, pero ahora no puedo. Debo hablar con el capitán de mi barco para darle algunas instrucciones para nuestra estancia.",
"Lo entiendo. No lleguéis tarde a mi casa esta noche.",
"Por supuesto, no quiero perderme mi propia fiesta, ¡ja, ja!",
"¡Don Guillermo, adelante! Permitidme presentaros a algunas buenas gentes de #sCartagena#.",
"Por supuesto, gobernador.", 
"Como dije, permitidme presentaros a algunas personas de mi ciudad. El primero es el almirante Lorenzo Delgado.",
"Espero que os guste esta fiesta.",
"Obviamente, Excelencia. Sin embargo, no me gustaría retirarme demasiado tarde esta noche.",
"Es comprensible. Tan pronto como estéis cansado, hablad con mi mayordomo, os mostrará vuestra habitación.",
"Muchas gracias.",
"¡Don Guillermo de la Rosa! ¿Descansasteis lo suficiente anoche?",
"Sí, gobernador. El dormitorio de la residencia es mucho mejor que el camarote de un barco para dormir.",
"¡Ja, ja! Lo predije. ¿Estáis listo para visitar #sCartagena#?",
"Absolutamente. Estoy sobre todo impaciente por visitar el fuerte de San Felipe.",
"El fuerte más poderoso del Caribe, como bien sabréis. Comencemos por el fuerte, si lo deseáis, don Guillermo...",
"Como podéis ver, la fortaleza se encuentra en un lugar estratégico, dominando los accesos a la ciudad por tierra y por mar.",
"De hecho, la ubicación no podía ser mejor.",
"Incluso si la fortaleza es antigua, viendo que la construcción comenzo en el año 1536, hace unos años se amplió.",
"¿Podria Su Excelencia explicarme su arquitectura?",
"Por supuesto, la fortificación consiste en una serie de muros, anchos en la base y que se estrechan hacia el parapeto, formando una formidable red de reductos. Las baterías y los parapetos se defienden unos a otros, por lo que es prácticamente imposible tomar una batería sin tomar todo el sistema de defensa. Las armas del castillo dominan toda la bahia, así que cualquier embarcación sospechosa que intente entrar está a su alcance.",
"Impresionante...",
"La fortaleza llama la atención por su gran entrada y su complejo laberinto de túneles. En resumen, es el más formidable complejo defensivo de las fuerzas armadas españolas en el Caribe.",
"¿Que quiere decir Su Excelencia con el 'laberinto de túneles'. ¿Hay alguna diferencia con las otras fortificaciones españolas?",
"El número de túneles es mayor que el de cualquier otro fuerte español en el Caribe. Esto permite a los soldados moverse rápidamente de un punto a otro y es una ventaja si el fuerte está bajo ataque.",
"Ciertamente...",
"Pero los túneles no se limitan a la fortaleza.",
"No entiendo, gobernador.", 
"Hay incluso un túnel que conecta el fuerte con la ciudad. Así, la fortaleza puede recibir las guarniciones de la ciudad si es atacada.",
"Eso aumenta drásticamente el número de soldados que pueden defender la fortaleza...",
"Sí. Por eso considero a San Felipe inexpugnable.",
"Hum... Solo por curiosidad, ¿dónde está la salida del túnel en la ciudad?",
"No ospreocupéis, está en la oficina del almirante. La ubicación mejor protegida de la ciudad. ¡Ja, ja!",
"Todo parece estar bien pensado. Nuestro Rey estará encantado de saber que la ciudad esta bien protegida.",
"Gracias, don Guillermo. Pero seguidme, hay algo que quiero mostraros.",
"Aquí estamos, en la cima del fuerte.",
"La vista de la bahía es fantástica.",
"Efectivamente. Pero seguidme a esta cabaña justo enfrente de vos. Creo que os gustaría otra vista.",
"Mirad esta reserva de pólvora.",
"¡Qué cantidad tan impresionante de barriles!",
"Barriles de pólvora y balas de cañón. Podríamos luchar contra una armada de navíos si fuera necesario.",
"Por Supuesto, gobernador. Ya pensaba que San Felipe era un fuerte impresionante, pero ahora tomo nota de sus defensas, y su organización es la mejor que he visto. Mi visita a #sCartagena# no ha terminado, pero debo decir que mis primeras impresiones son muy buenas.",
"Gracias por estas palabras tan alentadoras, don Guillermo. Pero veo que ya es mediodía, tal vez queráis almorzar conmigo en mi residencia antes de continuar la visita.",
"Gracias, gobernador, por la invitación pero desde ayer por la tarde no he visto a mi tripulación y debo hablar con ellos para saber si todo está bien en mi barco. Almorzaré con ellos en el barco.",
"Como deseéis, os esperaré esta tarde en mi residencia para que podamos continuar la visita.",
"Estaré allí a las 2 en punto.",
"¡Ah! Don Guillermo, ",
"Gobernador, acabo de hablar con la hija de Su Excelencia frente a la residencia y me ha dicho que tenéis un problema con los holandeses.",
"Desgraciadamente, sí. Uno de sus buques de guerra ha atacado a muchos barcos mercantes españoles en los últimos meses en la ruta entre #sCartagena# and #sisland_Isla Muelle#. Por uno de nuestros espías, he sabido hace una hora que el buque de guerra está anclado en #sWillemstad# y se quedará allí una semana más para ser reparado y abastecido.He decidido atacarlo con mi propia flota en los próximos días.",
"Entonces, ¿no puedo continuar la visita de la ciudad con Su Excelencia esta tarde?",
"Me temo que no, don Guillermo. Necesitaré muchos días para completar esta expedición y levaré anclas hoy. ¿Queréis acompañarme en la misión?",
"Hum... Prefiero continuar con mi deber aquí, gobernador. También tengo una misión que cumplir y estoy seguro de que podré preparar mi informe hablando con los subordinados de Su Excelencia.",
"Por supuesto, don Guillermo. La gente de #sCartagena# os dará toda la ayuda necesaria durante mi ausencia.",
"Gracias, gobernador. Ha llegado el momento de dejar en paz a Su Excelencia para que prepare su partida, no quiero retrasarla más.",
"No os preocupéis. En unos días, volveré trayendo buenas noticias.",
"Nuestro rey apreciará la lealtad de Su Excelencia a España. Buen viaje.",
"¡Don Guillermo! Estaba a punto de enviar a un hombre a vuestro barco. Tenía prisa por hablar con vos.",
"¿Es sobre la misión? ¿Ha sido un éxito?",
"Bueno... En realidad no, por desgracia. Los holandeses han rechazado nuestra incursión. He tenido la sensación de que nos estaban esperando.",
"¿Cómo es posible?",
"No lo sé. #sWillemstad# estaba preparada para el ataque y no pudimos beneficiarnos del efecto sorpresa. De todos modos, encontraré otra forma de hundir su flota. Pero no era a prpósito de la misión que quería veros.",
"¿No?",
"Me he enterado de que reñisteis con don Sebastián Ortega.",
"Fue solo un desacuerdo.",
"¡¿Llamáis desacuerdo a un duelo?! Don Sebastián es una de las personas más importantes de mi ciudad. ¿Es esa vuestra manera de agradecer mi hospitalidad?",
"Lo siento, gobernador. No volverá a pasar.",
"Espero que no, porque de lo contrario, tendré que informar de vuestro ocmportamiento a nuestro Rey. No estoy seguro de que lo aprecie. De todos modos, hay otro problema. Conozco la razón de ese duelo. Parece que queréis cortejar a mi hija.",
"Tenemos muchas afinidades...",
"Y no puedo aceptar esta situación. Le prometí la mano de mi hija a los padres de Ortega. Quiero que esta boda sirva para unir a nuestras familias.",
"Gobernador, vuestra hija no ama a don Sebastián Ortega.",
"No es vuestro problema, don Guillermo. Esto es algo que debe resolverse entre mi hija y yo. Con el tiempo, cambiará de opinión sobre don Sebastián.",
"Pero...",
"Basta, don Guillermo. Nuestra discusión sobre mi hija ha terminado. Hasta que os vayáis, mi hija permanecerá en el claustro de #sCartagena# y vos tenéis prohibido volver a verla. ¿Estamos de acuerdo?",
"[PIENSA: ¡Al diablo!] Como desee Su Excelencia, gobernador.",
"Excelente, sabía que eraís un #sgender# razonable. Pasando a otro asunto, ¿todavía necesitáis mi ayuda para terminar vuestro informe?",
"Solo necesito ver al almirante.",
"¡Ah! Ya debe de estar en su oficina a esta hora. La misión fue difícil para él, pero es un hombre valiente y no defrauda incluso después de un fracaso.",
"Es bueno saberlo. Voy a su oficina ahora mismo. Que Su Excelencia tenga un buen dia.",
"¡Don Guillermo! ¿Cómo estáis?",
"Estoy bien, gobernador Montavez. Solo me quedan dos días antes de partir.",
"Hay un final para todo.",
"Efectivamente. Qué raro...",
"¿Qué es raro?",
"Hace una hora, estaba hablando con un guardia y sabía que un pirata había sido arrestado en el Claustro. Pirata, claustro... ¿Cuál es el vínculo?",
"Lo confirmo, y sabemos su nombre. Es Johan Elting, un traidor. Fue reconocido por uno de mis capitanes liderando una patrulla durante la noche. Ese capitán trabajó durante muchos años en la Habana antes de ser transferido aquí.",
"¿¿Un traidor??",
"Sí, trabajó para España. De hecho, para el antiguo vicealmirante de #sHavana#, antes de traicionarlo y matarlo.",
"¡Eso es horrible! No podemos confiar en ningún holandés.",
"Tenéis razón. Desgraciadamente, el vicealmirante cometió este error. Pero conmigo, no tendrá ninguna oportunidad. Será ahorcado pronto.",
"Bien. Sin duda estará encerrado en la cárcel.",
"No.",
"¿¿No??",
"Esta encerrado, por supuesto, pero en un lugar secreto. Queria asegurarme de que ningún miembro de su tripulación o amigo suyo intentara liberarlo antes de su muerte.",
"Buena iniciativa. No sabía que teníais otra cárcel en la ciudad...",
"Es una cueva secreta debajo de la iglesia. Nadie podría pensar que allí exista un lugar asi. ¡Ja, ja!",
"¡Ja, ja! ¡Qué ingenio! ¡Reconozco el espíritu español! Entonces, ¿será ahorcado hoy?",
"No, mañana. Quiero saber por qué estaba en el claustro. Creo que estaba tratando de secuestrar a mi hija para obtener un rescate, pero no estoy completamente seguro. Es por eso que va a ser torturado para obtener una declaración.",
"[PIENSA: ¡¿Tortura?!] Podría ser inútil, un pirata como él debe tener una gran voluntad. Podrá soportar cualquier tipo de tortura.",
"Ya veremos. Pero no perdáis mucho tiempo hablando de la vida de un pirata. Entonces, ¿todavía necesitáis mi ayuda antes de iros?",
"No especialmente. He rdenado a mi tripulación preparar la partida comprando los suministros necesarios y mañana por la tarde esta tarea estará completada.",
"¿Y cuál será vuestra próxima misión?",
"Debo visitar #sHavana# y #sSantiago# de Cuba, como lo he hecho aquí, antes de regresar a España.",
"Bien. Antes de iros, ¿podríais presentarme conclusiones de vuestro informe sobre #sCartagena#, don Guillermo?",
"Lo haré. Veré a Su Excelencia mañana por la tarde para darle el informe. Deseo a Su Excelencia un buen día.",
"Buenas tardes, don Guillermo.",
"Buenas tardes, Excelencia. Mientras cruzaba la ciudad, noté que había más soldados patrullando.",
"En efecto, es orden mía. Anoche, el holandes Elting fue liberado. Estamos tratando de encontrarlo.",
"Increíble, ¿Cómo fue eso posible?",
"Alguien lo ayudo... Lo más curioso es que no entiendo cómo alguien pudo saber que Elting estaba escondido en la iglesia.",
"Tal vez, algunos de sus hombres estaban espiando en la ciudad y han visto a los soldados llevandolo a la iglesia.",
"Debéis tener razón. Les dije que llevaran a Elting discretamente, pero parece que todavía hay algunos incompetentes en mi guardia. Me encargaré de ellos más tarde.",
"Bueno, cambiando de tema, creo que Su xcelencia me pidió que le presentara mi informe hoy.",
"Tenéis razón. Podéis empezar vuestro discurso.",
"Gracias, don Guillermo. Por lo que habéis dicho, parece que os ha gustado cómo se gestiona y protege la ciudad.",
"Exactamente. Nuestro rey estará complacido por mi informe sobre #sCartagena#. Espero ver el mismo nivel de exigencia en Cuba.",
"Creo que sí. Conozco a los gobernadores de #sSantiago# y #sHavana#, y sé que no ahorran esfuerzos para proteger a sus ciudades",
"Eso es perfecto, Excelencia. Es hora de volver a mi barco y confirmar que todos los preparativos para mi viaje a Cuba están listos.",
"Por supuesto, por supuesto. Hacedlo, mañana por la mañana estaré en el puerto para despediros.",
"Gracias, hasta mañana.",
};
