string DLG_TEXT[101] = { 
"Me han dicho que has insistido mucho para pedir una audiencia. Mi nombre es ",
". Ahora, por favor, dime el propósito de tu visita, ",
".",
"Mi nombre es ",
".",
"Ah, eres tú otra vez. ¿Qué te trae por aquí esta vez? ",
"Me gustaría hablar con Su Excelencia acerca de algunos asuntos.",
"Lo siento, pero hay cosas que tengo que hacer.",
"Entonces, ¿por qué me distraes de mis importantes asuntos de estado?",
"Me gustaría hablar con Su Excelencia acerca de un pequeño asunto de negocios.",
"Solo estoy aquí para presentar mis respetos, #saddr#. Nada más.",
"En ese caso, por favor, sal de mi estudio y déjame volver a asuntos más importantes.",
"Sí, por supuesto. Siento haber molestado a Su Excelencia.",
"Lo siento, pero no tengo nada de qué hablar ahora mismo",
"Oh, ¿sí? Tengo una propuesta para ti, capitán.",
"¿De veras?",
"Me he enterado de que has completado la tarea con éxito; ¡mi enhorabuena, capitán! Aquí está tu recompensa.",
"Muchas gracias; ha sido un placer ayudar a Su Excelencia.",
"Debes destruir un barco de ",
" vessel ",
"quest pirate",
", que amenaza el tráfico marítimo en aguas de ",
". Si lo hundes, te recompensaré con la considerable suma de ",
" piezas de oro. ¿Qué dices, capitán?",
"Prometo a Su Excelencia que no volverá a saber de ese barco.",
"Me temo que no puedo ayudar a Su Excelencia.",
"Suplico el perdón, Excelencia.",
"Me gustaría saber más acerca de las relaciones de #sgov_nation# con otras naciones.",
"Quiero conseguir una patente de corso.",
"He oído que se me ha concedido un ascenso.",
"No puedo seguir sirviendo a ",
", Excelencia.",
"Me he hartado de servir a ",
"Como garantía de tus capacidades como capitán, y para compensar el tiempo que voy a perder en presentar tu caso a ",
", debo pedirte ",
" piezas de oro.",
"De ninguna manera.",
"Muy bien.",
"#sgov_nation# siempre se complace en aceptar nuevos capitanes a su servicio. ",
"Actualmente estamos en guerra con ",
"",
"... ninguna gran potencia, pero ",
". Por supuesto, ",
"los piratas siempre deben ser hundidos en cuanto sean avistados.",
" A la luz de tus anteriores servicios, ",
"te otorgo el rango de ",
"Haré que Su Excelencia se sienta orgulloso.",
"Has dañado los intereses de ",
", y ",
" no olvida a sus enemigos. ¡Vete inmediatamente, o los guardias te echarán a patadas!",
"...",
"Has causado a ",
" grandes daños, capitán, pero ",
"está dispuesta a pasar por alto tus transgresiones pasadas... por un precio: ",
"Muy bien, Excelencia. Acepto.",
"Un placer tratar contigo, ",
"Y con Su Excelencia.",
"¡En efecto! Excelente trabajo. Tu nuevo rango es ",
". Además, se te concede un premio de ",
" acres de tierra por orden de ",
"Gracias, Excelencia.",
"¿Seguro, ",
" lamentará perder tus servicios.",
"Sí, seguro.",
" no ve con buenos ojos a los chaqueteros, ",
"Hum..., no he diho nada.",
"Muy bien. Pero espero que lo reconsideres, con tiempo...",
"Adiós, ",
"¿Eh?",
"Se siente.",
"¿De verdad? ¿Y quien es tu compañero?",
"Este es Bonifacio del Agave, un agente especial. Creemos que el '",
"', un barco actualmente amarrado en este puerto, puede eestar implicado en el secuestro de ",
". Normalmente nuestras propias tropas registrarían el barco y arrestarían a su tripulación, pero como está en el puerto de Su Excelencia, nos pareció más apropiado pedir la ayuda de Su Excelencia.",
"Por supuesto, cualquier cosa para ayudar a nuestros aliados. Necesitaré ver alguna prueba de vuestra autoridad, por supuesto.",
"Hum. Hay algunos en la corte española, el gobernador de la Vega entre ellos, que querrían que Holanda fuera una vez más dependiente de España. Si informo de que Su Excelencia no ha cooperado, los navío de guerra que enviará tal vez sean prueba suficiente de nuestra autoridad.",
"Ya veo. Puedes decirle al gobernador de la Vega que las cosas han cambiado con los años, y que si envía sus navíos de guerra, nuestro fuerte les dará una cálida bienvenida. ¡Ahora, vete!",
"Esto...",
"Bueno, ciertamente eres más elocuente que tu acompañante. Pero te digo lo mismo: ¿puedes dar puebas de tu autoridad?",
"Eso cambia las cosas por completo. Por supuesto, estaré encantado de ayudar a tu gobernador en este asunto. ¡Sargento! Reúne a tus hombres. Reúnete con estos caballeros en el puerto y ayúdalos con su búsqueda.",
"Gracias, Excelencia. Informaré cuando la operación haya sido completada.",
"¿Y bien? Supongo que la búsqueda fue un éxito.",
"Sí, Excelencia. Y quiero pedir disculpas por mi arrebato de antes.",
"Bueno, los soldados normalmente no son contratados para su diplomacia. Y estoy gratamente sorprendido por tu disculpa. Pero, ¿dónde está tu compañero?",
"Tiene un prisionero que interrogar. Dejaré los detalles a la imaginación de Su Excelencia. Gracias de nuevo por la ayuda, Excelencia.",
"El sargento me ha dicho cómo encontraste a #scaptive#. ¿Qué harás con el barco y su capitán?",
"La embarcacioón será incautada y llevada a #sSantiago#. Dejaremos que la bandera inglesa ondee por ahora para no molestar a otros barcos ingleses en #sWillemstad#. Una vez que estemos abuen recaudo, izaremos nuestra propia bandera y regresaremos a casa.",
"Por favor, presenta mis respetos al gobernador de la Vega. Ha sido un honor para mí ayudar en el rescate de su #srelative#.",
"Eso haré, Excelencia. Será un honor para mí informar de la importante que ha sido la ayuda de Su Excelencia en el resate.",
"¿De veras? Pero me resultas familiar. ¿Me has visitado antes?",
"No, Excelencia. Esta es mi primera visita a #sWillemstad#.",
"Hum... Estoy seguro de que he visto tu cara en alguna parte antes.",
"Es un regalo muy generoso. Por favor, dale a tu padre mis más sinceras gracias.",
"Déjame ver... hum... Parece justo. Tendrá que haber más negociaciones sobre los detalles, tales como precios y tarifas y sin duda intercambiaré varias cartas con ",
" en el futuro cercano. Pero por ahora, por favor regresa a #sSantiago# y dile que, al menos en principio, estoy de acuerdo con su propuesta.",
"Agradezco a Su Excelencia que nos haya concedido su tiempo. Ven, ",
", debemos regresar junto a tu padre con esta buena noticia.",
"No sé quien eres realmente, pero intentar hacerse pasar por un oficial, incluso aunque sea español, es una ofensa grave. ¡Vete ahora u ordenaré al sargento que te arreste!",
"¡Ups! <Piensa: Será mejor que me vuelva a poner mi uniforme si quiero que crea que soy un soldado.>",
"¿Por qué sigues aquí? ¡Vete y vuelve con tu propio gobernador!",
"Creo que el ",
};
