string DLG_TEXT[101] = { 
"Me han dicho que has hecho un gran esfuerzo para pedir una audiencia. Mi nombre es ",
". Ahora, por favor, digame el proposito de su visita., ",
".",
"Mi nombre es ",
".",
"Ah, eres tu otra vez. ?Que te trae por aqui esta vez? ",
"Me gustaria hablar con usted acerca de algunos negocios.",
"Lo siento, pero hay cosas que tengo que hacer.",
"Entonces, ?por que me distraes de los asuntos de estado tan importantes?",
"Me gustaria hablar con usted acerca de un pequeno negocio.",
"Solo estoy aqui para presentar mis respetos, #saddr#. Nada mas.",
"En ese caso, por favor deja mi estudio y dejame volver a asuntos mas importantes.",
"Si, por supuesto. Siento haberte molestado.",
"Lo siento, pero no tengo nada de que hablar ahora",
"Oh, si? Tengo una propuesta para usted, capitan.",
" De verdad?",
" Me he enterado de que ha completado usted la tarea con exito; !mi enhorabuena, capitan! Aqui esta tu recompensa.",
" Muchas gracias; ha sido un placer ayudaros.",
"Debes destruir el ",
" vaso ",
"pirata de la busqueda",
"amenazando el envio ",
". Si la hundes, te recompensare la considerable suma de ",
" oro. Que dice, capitan?",
"No volveras a saber de ella, eso te lo prometo.",
"Me temo que no puedo ayudarte.",
"Deseo perdon, su excelencia.",
"Estoy interesado en aprender acerca de las relaciones de #sgov_nation# con otras Naciones.",
"Estoy buscando Una carta de Marca.",
"He oido que estoy a favor de un ascenso.",
"No puedo servir ",
"excelencia.",
"Estoy harto de servir ",
"Como seguro de que usted es un capitan capaz, y para recompensar mi tiempo en la presentacion de su caso a ",
", Debo pedirte ",
" oro.",
"De ninguna manera.",
"Muy bien.",
"#sgov_nation# siempre se complace en aceptar nuevos capitanes a su Servicio. ",
"Actualmente estamos en guerra con ",
"",
"no hay gran poder, pero ",
". Por supuesto, ",
"Los piratas siempre deben ser hundidos a la vista.",
"A la luz de su Servicio anterior, ",
"te otorga el rango de ",
"Os hare sentir orgullosos, excelencia.",
"Hemos hecho dano ",
", y ",
"no olvida a sus enemigos. !Vete de una vez, o los guardias te tiraran a la oreja!",
"...",
"Hemos causado ",
"gran dano, capitan, pero ",
"esta dispuesto a pasar por alto sus transgresiones pasadas... por un precio: ",
" Muy bien, Senor. Acepto.",
"Un placer tratar con usted, ",
"Y usted, su excelencia.",
"Estas hecho! Excelente trabajo. Tu nuevo rango es ",
". Ademas, se le premia ",
"acres de tierra por orden de ",
"Gracias, Senor.",
"Estas seguro, ",
"lamentara perder su Servicio.",
"Si, lo soy.",
"no toman amablemente a los chaqueteros, ",
"No importa.",
"Muy bien. Pero espero que lo reconsidere, con tiempo...",
"Despedir, ",
"Eh?",
"Duro.",
" De verdad? Y quien es tu companero?",
"Este es Bonifacio del Agave, un agente especial. Creemos que ",
", un barco actualmente amarrado en su puerto, a ser implicado en el secuestro de ",
". Normalmente nuestras propias tropas registrarian el barco y arrestarian a su tripulacion, pero como esta en su puerto, nos parecio mas apropiado pedir su ayuda.",
"Por supuesto, cualquier cosa para ayudar a nuestros aliados. Necesitare ver alguna prueba de su autoridad, por supuesto.",
"Hmm. Hay algunos entre la corte espanola, el conc de la Vega entre ellos, que quiz ver a Holanda una vez mas como una dependencia de Espana. Si informo que no ha cooperado, los acorazados que enviara probablemente mostraran nuestra autoridad.",
"Ya veo. Puede decirle al conc de la Vega que las cosas han cambiado con los anos, y si envia acorazados, se les dara una calida bienvenida en nuestro fuerte. Ahora vete!",
"Er...",
"Bueno, ciertamente eres mas elocuente que tu companero. Pero lo mismo se aplica. ?Puede probar su autoridad?",
"Eso cambia las cosas por completo. Por supuesto, estare encantado de ayudar a su conc en este asunto. !Sargento! Reuna a sus hombres. Reunanse con estos Caballeros en el puerto y ayudenlos con su busqueda.",
"Gracias, excelencia. Informare cuando la operacion este completa.",
"Y bien? Supongo que la busqueda fue un exito.",
"Si, Excelencia. Y quiero pedir disculpas por mi anterior arrebato.",
"Bueno, los soldados normalmente no son contratados para su diplomacia. Y estoy gratamente sorprendido por tu disculpa. Pero donde esta tu companera?",
"Tiene un prisionero que interrogar. Dejare los organismo a tu imaginacion. Gracias de nuevo por su ayuda, excelencia.",
"El sargento me ha dicho como encontro #scaptive#. Que haras con el barco y el capitan?",
"La nave sera incautada y llevada a #sSantiago#. Dejaremos que la bandera inglesa ondee por ahora para no molestar a otros barcos ingleses en #sWillemstad#. Una vez que este claro, levantaremos nuestra propia bandera y regresaremos a casa.",
"Por favor, Dale mis saludos al gobernador de la Vega. Fue un honor para ayudar en el rescate de su #srelative#.",
"Eso hare, excelencia. Sera un honor para mi informar de la importancia de su ayuda en theones.",
" De verdad? Pero me pareces familiar. Me has visitado antes?",
"No, Excelencia. Esta es mi primera vez en #sWillemstad#.",
"Hmm... Estoy seguro de que he visto tu cara en alguna parte antes.",
"Es un regalo muy generoso. Por favor, Dale a tu padre mis mas sinceras gracias por ello.",
"Dejame ver... hmm... esto parece justo. Tendra que haber mas negociaciones sobre organismo tales como precios y tarifas y sin duda voy a intercambiar varias cartas con ",
"en un futuro cercano. Pero por ahora, por favor regresa a #sSantiago# y dile que al menos en principio, estoy de acuerdo con su propuesta.",
"Gracias por su tiempo, Excelencia. Venir, ",
", debemos regresar a tu padre con esta buena noticia.",
"No se quien es usted realmente, pero intentar hacerse pasar por un oficial, incluso espanol, es una ofensa grave. Vete ahora o ordenare al sargento que te arreste!",
"UPS! <Thinks: I'd better put my uniform back on if I want him to believe I'm a soldier.>",
"Por que sigues aqui? Vete y vuelve con tu propio gobernador!",
"Creo que ",
};
