string DLG_TEXT[32] = {
"Saludar.",
"Despedir.",
"¡Mi Supremo! ¡Mi Supremo! ¡Un navio a corte distancia al arresto, que viene en nuestra direccion! ¡Creo que es el Natividad!",
"¡Salve el Supremo!",
"Oh, bien, y ahora, por favor, disculpenme.",
"Senal desde el punto, Senor. 'Natividad' se ha ido. Una vuelta mas y estara en la boca del puerto.",
"Muy bien, Teniente.",
"Informes de vigilancia 'Natividad' ha anclado, Senor.",
"¿Encajada por la noche, eh?",
"Senor, era yo el que estaba alli en observacion. Vi un pequeno pueblo no muy lejos de aqui. Querras evitar eso, estoy pensando.",
" En efecto, Senor. ",
". ¿Viste la ruta que debemos tomar?",
"Si, Senor. La primera vuelta a la izquierda va a ese pueblo, asi que nos saltamos eso. La siguiente vuelta es a la izquierda de una pequena colina con un arbol grande y ese es el que queremos.",
"Gracias, Sr. ",
"¡Rendíos! ¡Rendíos, Españoles! ¡Rendíos!",
"Puede conservar su espada, capitan.",
"¡Pero nos hemos rendido! Hay reglas de guerra.",
"Creame, capitan, si Don Julian le ve durante el dia siguiente, los matara a todos. Esas son sus 'reglas de guerra'.",
"¡Hay mujeres a bordo! ¿Que hacen estos espanoles?",
"Sera mejor que prepares el arnes.",
"Y eso no es todo, senora. El es tan suave y calida como cualquier hombre que nunca navego por el rey.",
"¡SR. OLDROYD!",
"¿Como se esta asentando su Senoria, Sr. Oldroyd?",
"¡Esta abajo atendiendo a los heridos, Senor!",
"¿Que?",
"Insistio en ayudar, Senor. Hay tantos, Senor.",
"¿Esta ahi abajo en todo ese lio?",
"No la detengo, Senor. Se puso la chaqueta de Contramaestre y se fue a trabajar.",
"Bueno, ve abajo, hombre, ¡y ayudala!",
"¡Si, Senor!",
"Me alegro de verle, Senor. Los almirantes estan arriba.",
"Gracias, Teniente.",
}