string DLG_TEXT[42] = {
"No sé quién eres, pero si te vas ahora mismo, ¡no tendré que echarte a los tiburones!",
"...",
"¿Por qué estás buscando a ",
"Raoul Rheims",
"?",
"Eso no es asunto tuyo.",
"Silehard me dijo que vendrías. Me pidió que le mandara tu cabeza.",
"Bueno, aquí la tienes, justo encima de mis hombros. ¡Ven a por ella si te atreves!",
"¡Ah, si es mi valiente ",
", amante y adalid de las masas oprimidas! ¿Qué trae a #sgender# tan noble como tú a buscar la compañía de un pirata vil como yo?",
"¡Ah, eres tú, ",
"! ¡Tu reputación despiadada y sangrienta amenaza con sobrepasar incluso la mía! ¿Qué te trae a mi humilde morada?",
"He venido a entregarte esta carta.",
"Eres aún más payaso de lo que esperaba. Toma esta carta que he traído para ti, y así podré seguir mi camino.",
"Tengo la sensación de que debería estar familiarizado contigo, #slad#..., pero, por más que lo intento, no puedo imaginar por qué. ¿Quién eres?",
"Me llamo ",
", y estoy aquí por negocios. Te he traído una carta.",
"¿Una carta, dices? Me gustaría saber de quién.",
"¿Por qué no la lees tú mismo? ¿O necesitas que te la lea yo?",
"¡Cuida tu lengua, #schild#, o tomaré tu cabeza como trofeo!",
"Bueno, eso responde a mi pregunta... Muy bien, si quieres saberlo, la carta es del gobernador inglés, ",
"Robert Christopher Silehard",
".",
"Robert Christopher Silehard",
", ¿eh? Entonces, ¿el viejo zorro quiere mi ayuda otra vez? Muy interesante. ¿Por qué sigues ahí? Has entregado la carta, ¡así que lárgate!",
"...",
"Déjame explicarte dónde te equivocas, #slad#. Este asentamiento es mío. Esta isla es mía. Y todo lo que sucede aquí sucede porque esa es mi voluntad.",
"Entonces, ¿wué eres?... ¿Un jefe pirata?",
"Prefiero pensar en mí mismo como gobernador de una colonia independiente. Pero sigo esperando tu respuesta.",
"¡Menuda civilización es esta que tienes aquí, en la que una pobre chica está tratando de encontrar a su amante y todo el mundo inmediatamente pone el grito en el cielo!",
"¿Amante? ¡Ja,ja! ¡No me digas! ¡Aún ocurren milagros en este mundo! ¿Por qué te dejó?",
"Dime, ¿estuvo aquí? ¿Cuándo? ¿Adónde fue?",
"Él estuvo aquí... haciendo reparaciones después de una tormenta. Pero no se adónde puso rumbo al zarpar. No lo dijo. De acuerdo, ahora retírate.",
"...",
"¡Ahoy, camarada! Vaya, que Davy Jones me lleve si no tienes todas las trazas de ser pirata.",
"Esa es una idea interesante, sin duda. ¡Y debo admitir que me estoy cansando de tener a tu cuadrilla de bandidos persiguiéndome por todo el Caribe!",
"Trato de evitar toda familiaridad con los piratas. Adiós.",
"Siéntete libre de unirte a nuestra noble Hermandad. ¡Pero te advierto que te ganarás el odio de toda la gente común, como el resto de nosotros!",
"Naturalmente. Robamos a los ricos. Y a los pobres. Y nos lo guardamos para nosotros. No puedes esperar hacer muchos amigos si haces eso. ¡Pero es parte de la diversión!",
"¿Qué? ¡Pero yo no soy ese tipo de pirata! Soy el tipo de pirata AMABLE que da dulces a los niños pequeños. ¡Adiós, sinvergüenza sin corazón!",
"En ese caso, por favor, permíteme ser el primero en darte la bienvenida a la Hermandad, mi #slad#!",
"¡¡¡¡¡¡¡¡¡¡ARRRRRRRRRRRR!!!!!!!!!!",
"Estoy ocupado.",
};
