string DLG_TEXT[230] = { 
"Me han dicho que has hecho un gran esfuerzo para pedir una audiencia. Mi nombre es ",
". Ahora, por favor, digame el proposito de su visita., ",
".",
"Mi nombre es ",
".",
"Ah, eres tu otra vez. Que te trae por aqui esta vez? ",
"Me gustaria hablar con usted acerca de algunos negocios.",
"Lo siento, pero hay cosas que tengo que hacer.",
"Entonces, por que me distraes de los asuntos de estado tan importantes?",
"Me gustaria hablar con usted acerca de un pequeno negocio.",
"Solo estoy aqui para presentar mis respetos, #saddr#. Nada mas.",
"En ese caso, por favor deja mi estudio y dejame volver a asuntos mas importantes.",
"Si, por supuesto. Siento haberte molestado.",
"Estoy escuchando, ",
".",
"Estoy aqui para obtener mi recompensa por la muerte de Dirty Garry.",
"Lo siento, pero no tengo nada de que hablar ahora",
"Oh, he oido lo que has hecho. Por la cara de toda la Colonia te mostrare nuestro aprecio.",
"Asi es, me gustaria ver una recompensa.",
"Eres un bromista. Ja, ja. Aqui esta tu dinero.", 
"Gracias, soy su humilde servidor.",
"Sobre la apuesta que hiciste... despues de obtener la aprobacion de nuestro Departamento de impuestos veo que tenemos... dejame ver... seis mil.",
"Que?! El trato era de 10 mil!",
"No puedo ayudarte. En el futuro, trate de ser mas tranquilo.",
"Lo que tu digas, #saddr#. Cerdo asqueroso...",
", es usted consciente de que esta acusado de asesinato? Te vieron cerca del cuerpo de la victima. Que dice en respuesta a este cargo?",
"No tiene nada que ver conmigo. El hombre ya estaba muerto cuando entre en la habitacion! Me dijeron que solo estaba herido, y que podria tener informacion importante para mi.",
", Me acaban de decir que un hombre fue capturado cuando intentaba dejar la ciudad con un cuchillo manchado de sangre en su poder. Confeso el asesinato del que se le acusaba. Puede irse inmediatamente.",
"Agradecer. Sabia que podia confiar en la justicia aqui en #sConceicao#.",
"Deseo desertar a Portugal.",
" De verdad? Muy bien, ahora eres ciudadano Portugues.",
"Le agradezco su infinita bondad, Senor.",
"Oh, si? Tengo una propuesta para usted, capitan.",
" De verdad?",
" Me he enterado de que ha completado usted la tarea con exito; mi enhorabuena, capitan! Aqui esta tu recompensa.",
" Muchas gracias; ha sido un placer ayudaros.",
"Debes destruir el ",
" vaso ",
"pirata de la busqueda",
"amenazando el envio ",
". Si la hundes, te recompensare la considerable suma de ",
" oro. Que dice, capitan?",
"No volveras a saber de ella, eso te lo prometo.",
"Me temo que no puedo ayudarte.",
"Deseo perdon, su excelencia.",
"Estoy interesado en aprender acerca de las relaciones de #sgov_nation# con otras Naciones.",
"Estoy buscando Una carta de Marca.",
"Ah, ",
"que bueno que viniste. Me gustaria presentarles a mi ",
". Vendra una vez que terminemos el negocio.",
"He oido que estoy a favor de un ascenso.",
"No puedo servir ",
"excelencia.",
"Estoy harto de servir ",
"Como seguro de que usted es un capitan capaz, y para recompensar mi tiempo en la presentacion de su caso a ",
", Debo pedirte ",
" oro.",
"De ninguna manera.",
"Muy bien.",
"#sgov_nation# siempre se complace en aceptar nuevos capitanes a su Servicio. ",
"Actualmente estamos en guerra con ",
"",
"no hay gran poder, pero ",
". Por supuesto, ",
"Los piratas siempre deben ser hundidos a la vista.",
"A la luz de su Servicio anterior, ",
"te otorga el rango de ",
"Os hare sentir orgullosos, excelencia.",
"Hemos hecho dano ",
", y ",
"no olvida a sus enemigos. Vete de una vez, o los guardias te tiraran a la oreja!",
"...",
"Hemos causado ",
"gran dano, capitan, pero ",
"esta dispuesto a pasar por alto sus transgresiones pasadas... por un precio: ",
" Muy bien, Senor. Acepto.",
"Un placer tratar con usted, ",
"Y usted, su excelencia.",
"Estas hecho! Excelente trabajo. Tu nuevo rango es ",
". Ademas, se le premia ",
"acres de tierra por orden de ",
"Gracias, Senor.",
"Estas seguro? ",
"lamentara perder su Servicio.",
"Si, lo soy.",
"no toman amablemente a los chaqueteros, ",
"No importa.",
"Muy bien. Pero espero que lo reconsidere, con tiempo...",
"Despedir, ",
"Eh?",
"Duro.",
"Oh, si? Dime lo que quieres.",
"He oido que te gustaria arrestar a un pirata.",
"En verdad, como lo sabes?",
"Un capitan de #sRedmond# me lo dijo.",
"? Eres Capitan?",
"Si, gobernador. Mi nombre es Bartolomeu, vengo de Portugal hace un tiempo.",
"Compatriota. Has tenido alguna experiencia en el archipielago?",
"Si, ya he peleado con los espanoles en #sSantiago#.",
"Excelente! Nuestra pequena Colonia necesita capitanes como tu. Debido a la guerra con Espana, todo lo que debilita al enemigo nos ayudara a conseguir la independencia.",
"El pirata trabaja para los espanoles?",
"No. Es Ingles, pero no se si trabaja para los britanicos o los espanoles.",
"Que hizo, contra la Colonia o contra Portugal?",
"Ha atacado muchos barcos portugueses e incluso ha tenido la audacia de atacar a los agricultores fuera de la ciudad.",
"Sabes donde puedo encontrar a este desgraciado arrogante?",
"No tengo ni idea. Hemos tratado de arrestarlo muchas veces, siempre logra torre de nuestra flota. De hecho, tiene una nave rapida, una nueva caravana de modelos.",
"Esta parece ser una tarea dificil... para capturarlo, quiero decir.",
"Por eso sere muy generoso si tienes exito.",
"Que tan generoso, exactamente?",
"Usted recibira 40 000 monedas de oro y los agricultores suministraran muchos bienes de nuestras plantaciones.",
"!Que recompensa tan generosa para un Capitan!! Estoy dispuesto a ayudarte. El unico problema es que no tengo ni idea de empezar mi busqueda.",
"Bueno, la Ultima vez que fue perseguido por uno de mis barcos, se escapo a #sisland_Oxbay#.",
"Cuando sucedio esto?",
"Solo hace un mes.",
"El rastro esta todavia caliente, por que su capitan no trato de capturarlo alli?",
"El no podia, ordenes que usted ve. Tenemos un acuerdo con las autoridades Britanicas. Ninguno de nuestros buques de guerra puede amarrar en esta isla a menos que esten en peligro.",
"Asi que no sabes si este pirata atraco en #sisland_Oxbay#, o no?",
"No. Sin embargo, envie a un diplomatico alli solo unos dias despues, pero los britanicos no estaban interesados en ayudarnos.",
"Extrano, los britanicos protegiendo a un pirata!! Crees que esto nos dice algo?",
"Como te dije, no puedo confirmar si trabaja para ellos o no, pero es inevitable que lo haga. Mi diplomatico solo podia aconsejar que no vio el barco en ninguno de los puertos de la isla.",
"Solo una pregunta mas. Su capitan dano el barco pirata o simplemente lo persiguio?",
"Logro danar ligeramente la Carabela. Pero el pirata se las arreglo para escapar. Por que preguntas?",
"Ire a #sisland_Oxbay#. Tal vez pueda obtener mas informacion que su diplomatico.",
" Muy bien, capitan. Haz lo mejor que puedas. Ya estoy impaciente por que encuentres una pista.",
"Gracias Gobernador. Hasta pronto!",
"Capitan! aqui estan. Felicitaciones por el arresto de Charles Baxter. Es su nombre, no?",
"Si, gobernador. Pero, esa fue una mision peligrosa capturarlo.",
"Lo creo. Donde lo encontraste?",
"En #sCharlestown#. Estaba protegido por el propio gobernador.",
"Como puede ser! Las relaciones entre Portugal e Inglaterra son amistosas. Es inconcebible que un gobernador britanico declare un pirata atacando mi Colonia.",
"Era corrupto y Charles era muy generoso.",
"Enviare un envio a nuestro Rey, el aconsejara a la Corona britanica. Tal vez su Rey deponga al gobernador de #sCharlestown#.",
"De hecho, eso podria ser una solucion.",
"Como sea, como prometi, hablemos de tu recompensa. Primero, el dinero, 40 000 monedas de oro, como prometi, y ya he dado la orden de cargar algunas mercancias en su barco.",
"Gracias Gobernador. Ha sido un placer servirle.",
"Eso no es todo, quiero darte un objeto especial.",
"Que es? Tengo curiosidad.",
"Como agradecimiento por su valor y valor, permitame darle esta espada. Lo contarme cuando era un joven oficial en Brasil. Esta un poco desgastado, pero creame, sigue siendo una excelente espada. Pareceras un espadachin profesional.",
"Que hermosa espada! Me honras con este regalo.",
"Siempre eres Bienvenido en nuestra buena Colonia. Obviamente tienes otros planes ahora, con un bolso lleno y carga para vender. Estare feliz de saludarte de nuevo en el futuro.",
"Asi es. Adios, gobernador!",
"Si?",
"Tu enviado me dijo que tienes una mision para mi.",
" En Efecto, Capitan. Pero, es una triste historia que tengo que contar.",
"Por que triste?",
"Mi hermano vino de Portugal hace un ano. Me ayudo en la guerra contra los espanoles al mando de la Armada de #sisland_Conceicao#. Gano muchas batallas contra nuestros enemigos pero desafortunadamente fue asesinado durante un abordaje por un Capitan espanol hace unas semanas.",
"Por favor, acepte mis condolencias, gobernador. Pero la muerte de tu hermano, tiene alguna relacion con la mision?",
"Si, Capitan. Quiero mi venganza. Se que tienes mucha experiencia en la lucha contra los espanoles. Te pagare 50.000 monedas de oro, si encuentras y matas a su asesino.",
"Una gran recompensa. ?Sabes quien mato a tu hermano?",
"Si, gracias a un espia, ahora se su nombre. Es El Capitan Arturo Campos. Patrullaba por #sTortuga# y San Salvador.",
"Asi que esa es la clave, voy a navegar a las islas en busca de el.",
"Efectivamente. Pero esta vez, tendras la ayuda de mi Armada.",
"Es necesario, gobernador?",
"Los soldados y marineros que comprometieron bajo mi hermano voluntariamente pidieron participar en esta mision. Mi hermano era muy respetado.", 
"Cuantos hombres me acompanaran?",
"De hecho, te voy a prestar una Fragata Latina Para la mision. Si ganaste en la loteria, tienes que usar tu nave. Tus hombres pueden quedarse aqui hasta que cumplas la mision.",
"Ese barco no es ya Capitan?",
" Si, Capitan Queiroz. El sera su oficial durante la mision. Puedes encontrarlo afuera... Esperandote.",
"Esta bien. Necesito hablar con mi oficial, Emilio Soares, antes de salir de la isla.",
"Eso es entendible. Haz lo que quieras, solo quiero que tengas exito en matar a Arturo Campos.",
"Consideralo un hombre muerto que camina. Hasta pronto, gobernador.",
"Aqui estas! Que ha ocurrido? Encontraste a Campos?",
"Si, gobernador. Lo conocimos en #sisland_Turks#. Fue asesinado durante una productividad entre sus soldados y los espanoles.",
"Felicidades, Capitan! Finalmente, la muerte de mi hermano ha sido vengada. No sabes lo importante que era. Toma estas 50.000 monedas de oro como te prometi.",
"Gracias Gobernador.",
"Sin embargo, tengo una mala noticia para ti. Conociste a tu gente antes de venir aqui?",
"No. Hay algo malo con ellos?",
"Cuando estabas llevando a cabo la mision, tu nave fue abordada por el enemigo.",
"El enemigo? Quien se atrevio a atacar mi nave?!",
"Un mercenario trabajando para los espanoles segun su tripulacion. En secreto abordo tu nave por la noche con sus hombres. Tan silenciosamente atacaron, que los soldados de la fortaleza protegiendo el puerto hicieron incluso notar.",
"Pero el robo mi barco, la vi amarrada en el puerto hoy.",
"El no estaba interesado en robar su barco, el solo estaba buscando para usted.",
"Humm.. Otro mercenario espanol con ganas de ganar una recompensa sustancial por mi captura, ja ja, gran oportunidad que tienen.",
"Creo que fue el espanol.",
"Olvidelo, gobernador. Buscara durante mucho tiempo antes de que pueda sinceridad.",
"Pero, usted no entiende, cuando dejaron su barco se llevaron a su oficial, Emilio Soares.",
"Hijo del culo de un mono! Lo pagara caro, como lo hizo Pedro Rivera, pero no tan estrategia. Esto lo cambia todo. No dejare a Emilio en manos de su captor. Lo encontrare.",
"Si quieres ayuda, solo tienes que pedirla. Necesita un barco o algunos soldados para ayudar en su busqueda?",
"No, gobernador. Solo necesito saber el nombre del mercenario. Lo sabe mi tripulacion?",
"Preparatorio pero ellos lo saben.",
"Sin su nombre, la busqueda sera mas dificil.",
"Tal vez pueda ayudarte. Hay un Espanol que trabaja para mi como informante. Gracias a el, descubri que fue Campos quien mato a mi hermano.",
"Interesante. Donde puedo encontrarlo?",
"El informante vive en #sIsla Muelle#. Toma esta carta que explica que trabajas para mi. Si no, te tratara como a un enemigo.",
"Gracias Gobernador. Debo dejar #sConceicao# y encontrar a mi oficial-cuanto antes, mejor.",
"Por supuesto, capitan, tenga cuidado, estara en Suelo enemigo. Buena suerte y vientos justos.",
"Adios, Excelencia.",
"Capitan Bartolomeu! Hace mucho que no te conocia. Siempre es un placer volver a verte.",
"Gracias Gobernador. Desafortunadamente, he tenido algunos problemas recientemente. Me gustaria saber si podrias ayudarme.",
" Por supuesto. Pero, que paso?",
"Mi tripulacion se amotino debido al comportamiento de un oficial. Capturaron mi barco, me abandonaron, atacaron un buque de guerra Ingles y se hundieron frente a Jamaica.",
"Triste noticia, de hecho.",
"Necesito ganar dinero lo suficientemente estrategia. Tal vez, podrias darme una mision como hiciste en el pasado.",
"De hecho, Capitan, vino en el momento adecuado. Tengo una mision muy importante.",
"Que es exactamente?",
"Dejame explicarte. Hace dos semanas una pequena flota portuguesa capturo #sisland_Isla Muelle# un buque de guerra espanol procedente de Espana.",
"Y?",
"A bordo, habia un enviado del Rey que tenia que ir a Cartagena para una mision. Llevaba consigo una carta del propio Rey. Su mision era comprobar las defensas de la ciudad recientemente mejoradas y saber la situacion real de Cartagena en muchos aspectos.",
"Donde esta?",
"En la carcel con la tripulacion del buque de guerra.",
"Que ayuda quieres?",
"Me gustaria que fueras a Cartagena siendo tomado por el enviado. La idea es hacer un Servicio de inteligencia primero. Quiero saber si un pequeno grupo de soldados puede hacer una operacion espectacular para golpear la moral espanola en la region, pero tambien para impulsar la portuguesa en Europa en la guerra contra los espanoles.",
"Bueno, eso me gusta. Debo ir ahora mismo a Cartagena?",
"Todavia no. Como saben, nuestras relaciones con Holanda son amistosas. Ambos paises tienen el mismo enemigo: Espana. Creo que seria interesante si pudiera animar a los neerlandeses a participar en una futura operacion.",
"Podria ser util para eso. Conozco a un capitan Holandes que vive en Bonaire. Podria obtener la ayuda de su gobernador.",
"Excelente! Voy a escribir una carta explicando mis intenciones. Se lo daras al gobernador despues de hablar con tu amigo.",
"Lo hare.",
"Vuelve aqui tan pronto como tengas una respuesta.",
" Por Supuesto, gobernador. Estare en el puerto esperando la carta.",
"Aqui tiene, capitan Bartolomeu! Tienes alguna buena noticia?",
"Si, Excelencia. El Gobernador holandes accedio a ayudarnos en una operacion militar.",
"Genial! Ahora, puedes empezar tu mision. Como dije en nuestra Ultima charla, quiero que vayas a Cartagena para que te tomen por el enviado. Entonces, usaran su nave que capturamos durante el arresto.",
"Donde esta?",
"En el puerto en este momento. Tuvimos que repararla estos ultimos dias pero ahora esta en perfectas condiciones. Tambien le he proporcionado un nuevo equipo para sustituir al espanol. Parte de la tripulacion esta compuesta por soldados que participaran en una posible operacion militar.",
"Quien es su Capitan?",
"Lo conoces. Es Augusto Queiroz.",
"Por supuesto, yo recuerdo. Me ayudo cuando tuve que matar al Capitan espanol Arturo Campos en la isla de los turcos.",
"Exacto. El y sus soldados permaneceran escondidos en la nave hasta que comiences la operacion militar. Capitan! solo empezaras la operacion despues de que la acepte. No quiero ninguna iniciativa personal sin mi consentimiento. Entendeis?",
"Si, Excelencia. Enviare a alguien aqui para que acepte los organismo del ataque que quiero liderar.",
"Bueno. Antes de salir de #sisland_Conceicao#, tome esta carta escrita por el Rey espanol que tenia el enviado. Se lo daras al gobernador de Cartagena. tu nombre ahora es Guillermo de la Rosa.",
"No lo olvidare. Adios Excelencia!",
"Ja! Capitan. Estoy tan feliz de verte de nuevo y el Capitan Queiroz ya explico que la mision ha sido un exito. Sin duda, estoy orgulloso de ti!",
"Gracias, excelencia. El fuerte de Cartagena fue parcialmente danado. Los espanoles necesitaran muchas semanas para que el fuerte vuelva a funcionar.",
"Maravilloso, debo decir. Es un duro golpe en su confianza. Entonces, ?como podria recompensarte por eso? Yo se... Te doy algunas tierras en #sisland_Conceicao#. Por lo tanto, regularmente ganarA !n algo de oro del cultivo de ellos.",
"Gracias de nuevo gobernador por su generosidad. Siempre me ayudaste cuando lo necesitaba.",
"Y te lo mereces de todos modos. En Portugal, la gente ya sabe de tus hazanas en el Caribe. Incluso nuestro Rey sabe como luchar contra los espanoles. No seria de extranar que un dia el Rey te invite a visitarlo en Lisboa.",
"Seria un placer regresar a mi pais algun dia.",
"Efectivamente. Bueno, se que tiene mas que hacer ahora en mi ciudad asi que tenga un buen dia, capitan Bartolomeu.",
"Usted tambien, gobernador.",
"Eso es entendible. Haz lo que quieras, solo quiero que tengas exito en matar a Arturo Campos. Y viendo que estas trabajando para mi ahora, deberias tomar esta carta de Marque para legalizar tus acciones en mi nombre.",
};
