string DLG_TEXT[18] = {
"!Venceremos!",
"...",
"Saludos! He oido hablar mucho de ti ... y, de hecho, tu ayuda fue muy apreciada.",
"Me alegro de conocerte, tambien. Pero a que ayuda te refieres? Oh, espera... Estas hablando de ese pequeno revuelo cerca de las costas de #sisland_Oxbay#?",
"Un favor, comandante? Y si alguien te robo a tu hijo o hija, y algun burocrata te pidio un favor antes de dejar que salves a tu hijo?! Indignante! ?Un hombre asi tiene corazon?",
"",
"Exactamente, ",
". Eras una gran ayuda para nosotros entonces. Si no fuera por ti, supongo que ahora estaria en el vientre de un tiburon.",
"Y a menos que me equivoque, eres el misterioso pasajero que aterrizo en el puerto de sgreen leccion. Correcto?",
"Misterioso? Ah, creo que entiendo lo que quieres decir. Si, soy yo.",
"Entonces tal vez me diga su nombre y como esta conectado con los acontecimientos recientes.",
" Por supuesto. Mi nombre es ",
". Soy un caballero Maltes. Hace unos anos, participe en la destruccion de un culto utilizaronolico de satanistas en Italia...",
"Y ahora has venido aqui a terminar el trabajo?",
"Exactamente. Y, si no te importa, me gustaria unir fuerzas contigo. Creeme, no sere inutil.",
"Bueno, conoces la cara del enemigo y estoy seguro de que puedes luchar. No veo razon para rechazarte, asi que bienvenida a bordo.",
"No se arrepentira de esto, capitan. ?Donde quieres que te siga primero?",
"A #sisland_Isla Muelle#! Necesitamos mas informacion.",

};
