string DLG_TEXT[55] = {
"Bienvenido a mi tienda, ",
". Mi nombre es ",
".",
"Encantado de conocerte. Soy ",
", un capitan libre de mi propio destino.",
"Mi nombre es ",
". Soy el capitan y el dueno de un buen barco.",
"Bienvenido a mi tienda. No encontraras nada mejor. Y si lo haces, asegurate de decirme que mi marido y yo nos encargaremos de ellos., ",
".",
"Les agradezco su cortesia, pero debo hablar de negocios con ustedes ahora.",
"Cada uno de ustedes comerciantes dice lo mismo: !Bienvenido, Capitan! !Bienvenidos! Bienvenue! Willkommen! ?Hay alguna escuela a la que asistan? Mientras estas retorciendo tu cerebro por una respuesta original, me gustaria hablar de negocios.",
"Si, si, asi es...",
"Solo Muestrame lo que tienes en stock.",
"Muestreme que bienes tiene en oferta.",
"Me gustaria algo de informacion.",
"Estoy mas interesado en la informacion que en el trueque.",
"Lo siento, pero debo despedirme de ti.",
"He disfrutado de nuestra pequena charla, pero ahora debo atender otros asuntos.",
"Toma un poco... mercancias... (guino) para vender, o solo necesita un par de articulos de corte personal?",
"Me gustaria vender la carga que he traido.",
"Quiero comprar un par de cosas para mi.",
"No cambiaremos nada. Despedir.",
"Ciertamente, escorbuto #slad#. Pero, ?que es exactamente lo que quieres?",
"Estoy escuchando.",
"Me pidieron que le entregara un cargamento.",
"Seguramente debes tener algun trabajo que te gustaria hacer. Estaria feliz de prestarle mis servicios por una tarifa.",
"No puedo hablar ahora.",
"No, no necesitare tus servicios... Crees que porque soy una mujer que no puede hacer frente en la mia?",
"Siento haberle pagado. Las mujeres son dramaticas.",
"Lo siento, pero no tengo nada para ti en este momento. Eres demasiado bueno para meterte en asuntos de piratas.",
"Volvere mas tarde, entonces.",
"Lo siento, pero su nave carece de la capacidad de manejar la tarea que tengo en mente.",
"Volvere mas tarde, entonces.",
"Oh! Iba a pedirte que me hicieras un favor. La cosa es, necesito una carga entregada a ",
"y tan pronto como sea posible. Si conduces para hacerlo en un mes, recibiras ",
"oro cuando llegues. Y si no lo haces... Bueno, digamos que ningun dueno de tienda te dara otro trabajo. !O nunca sera capaz de hacerlo! ?Que te parece esa oferta?",
"Yo no soy asustadiza, ma estoy. Me gusta el sonido de un poco de peligro en un comerciante de ejecucion.",
"Solo estaba pidiendo una pequena carga para transportar para usted, no un acuerdo de vida o muerte. Creo que sera mejor que me vaya...",
"Ya te he dicho hoy que no tengo nada para ti.",
"Oh, lo siento.",
"Has recordado tu entrega un poco demasiado tarde, ?no crees? Podria haber tenido escorbuto para cuando decidiste aparecer. Eres indigno de llamarse capitan! Despedir.",
"Despedida.",
"Oh! Lo he estado esperando por mucho tiempo. Aqui esta tu dinero. ?Ya has pensado en gastarlo? Si no, tengo una sugerencia o dos...",
"Siempre Bienvenido.",
"Lo siento. No tengo ganas de ayudarte ahora mismo.",
"Es una pena. Tal vez respondas algunas preguntas, entonces.",
"Historia de mi vida. ?Que tal un poco de informacion, entonces?",
"Salir, ",
", antes de que me llame marido y sus companeros de beber.",
"Muy bien, no quiero molestar a su grog party.",

};
