string DLG_TEXT[40] = {
"¡Te doy la bienvenida! Toma asiento en una mesa libre. ¿Que deseas pedir, ",
"?",
"Nada. Estoy aquí por negocios.",
"¡Oh! Lo siento mucho. No quería molestarte. Volveré a mi trabajo.",
"No, espera, no me estás molestando. De hecho, necesito hablar contigo.",
"No tan rapido. Quiero hablar contigo.",
"Soy todo oídos. ¿Cómo puedo ayudarte?",
"Necesito enrolar a algunos marineros.",
"Quiero añadir alguans manos a mi tripulacion.",
"Hablemos de negocios.",
"Me gustaría alquilar una habitación.",
"¿Tienes una habitación libre en este lugar?",
"No importa. Me tengo que ir.",
"Ciertamente, ",
". ¿Qué tienes en mente?",
"Dime: ¿quién es el dueño de la casa cerca de tu taberna?",
"En realidad, no es nada importante.",
"Tengo una habitación libre. ¿Cuánto tiempo piensas estar con nosotros?",
"Pasaré aqui la noche.",
"Solo quiero descansar hasta el anochecer.",
"Bien. Te costará cinco piezas de oro.",
"Muy bien. Aquí tienes.",
"¿Tanto? Me parece que voy a pasar la noche en el salón de la taberna.",
"¿Qué pago con eso? ¿La residencia del gobernador? No, gracias.",
"Lo pensaré. Por ahora, déjame hacerte otra pregunta.",
"Te costará cinco piezas de oro.",
"Muy bien. Aquí tienes.",
"¿Tanto? Me parece que voy a pasar la noche en el salón de la taberna.",
"¿Qué pago con eso? ¿La residencia del gobernador? No, gracias.",
"Muy bien, lo pensaré.",
"Bueno, es bastante tarde. Todos los marineros que puedan estar buscando trabajo ya habrán encontrado algún sitio donde pasar la noche\n Será mejor que esperes hasta mañana. ¿Tal vez podría alquilarte una habitación? ",
"¿Tienes una habitación libre?",
"No. Tengo otra pregunta.",
"¡Amigos, por favor! Basta de esta locura. ¡No me hagáis llamar a la guardia!",
"¡Relájate! Ya me marcho.",
"Estoy buscando trabajo. ¿Sabes si alguien necesita un capitán?",
"¡Tienes suerte! El joven pirata Will Turner está haciendo preparativos para una expedición y le gustaría tener un socio.",
"¿Adónde quiere ir?",
"No tengo ni idea, capitán... Deberías hablar con él. En este momento, debe estar en su casa, al final del muelle.",
"Gracias, voy a hablar con él.",
};