string DLG_TEXT[34] = {
"estimado cliente, soy ",
", el propietario del astillero local.",
"Yo soy ",
", capitan de la '",
".",
", ",
". Como puedo ayudarte hoy?, ",
"?",
"Mi nave necesita ser reparada.",
"Solo quiero hablar.",
"Debo irme.",
"Bueno, es un placer conocerte. Mi astillero esta a su servicio.",
"Gran, ",
". Veamos lo que tu Jardin tiene para ofrecer.",
"Solo quiero hablar.",
"Debo irme. Gracias.",
"De que quieres hablar exactamente?, ",
"?",
"Nada por el momento.",
"Hmm...?necesitas algo mas, ",
"?",
"Si, me gustaria usar los servicios de su astillero.",
"Agradecer. Adios!",
"Que necesitas exactamente?",
"Vamos a ver lo que su Jardin tiene para ofrecer.",
"Me gustaria instalar armas nuevas en mi nave.",
"Debo irme. Gracias.",
"Me niego a comerciar con una persona de su reputacion y relaciones. Ahora salir, ",
", antes de que llame a los guardias.",
"Muy bien.",
"Muy bien, mi muelle junto al fuerte esta disponible para ti. Si quieres, le dire a mi capitan que remolque tu barco alli. Solo entonces puedo inspeccionar el dano y decirte cuanto tiempo y dinero me llevara.",
"MUELLE JUNTO AL FUERTE?? Uhh... Yo solo x que tengo... eeh... otro asunto urgente que debo atender primero. Despedir.",
"Despues de cerrar este dialogo, pulse ENTER para conversacion la interfaz de cambio de vela.",
"Salida",

};