string DLG_TEXT[35] = {
"Bienvenidos! Tome asiento en la mesa libre. Que desea pedir?, ",
"?",
"Nada. Estoy aqui por negocios.",
"Oh! Lo siento mucho. No queria molestarte. Volvere a mi trabajo.",
"No, espera , no me estas molestando. De hecho, necesito hablar contigo.",
"No tan rapido. Quiero hablar con usted.",
"Soy todo oidos. ?Como puedo ayudarte?",
"Necesito contratar a algunos marineros.",
"Estoy buscando anadir a mi tripulacion.",
"Hablemos de negocios.",
"Me gustaria una habitacion.",
"Tienes una habitacion libre en este lugar?",
"No importa. Me tengo que ir.",
"Ciertamente, ",
". Que tienes en mente?",
"Dime: quien es el dueno de la casa cerca de tu taberna?",
"En realidad, no es nada importante.",
"Tengo una vacante. ?Cuanto tiempo planeabas estar con nosotros?",
"Me carteles esta noche.",
"Solo hasta el atardecer.",
"Fino. Te costara cinco piezas de oro.",
"Muy bien. Aqui tienes.",
"Tanto? Parece que voy a pasar la noche en el salon de la taberna.",
"Para que? ?la residencia del gobernador? No, gracias.",
"Lo pensare. Por ahora, dejame hacerte otra pregunta.",
"Te costara cinco piezas de oro.",
"Muy bien. Aqui tienes.",
"Tanto? Parece que voy a pasar la noche en el salon de la taberna.",
"Para que? ?la residencia del gobernador? No, gracias.",
"Muy bien, lo pensare.",
"Bueno, es bastante tarde. Todos los que contrates habran encontrado un lugar para pasar la noche.estas mejor esperando hasta manana. Tal vez podria alquilarte una habitacion? ",
"Tienes una habitacion gratis?",
"No. Tengo otra pregunta.",
"Amigos, por favor! Basta de esta locura. !No me hagas llamar al guardia!",
"Relajate! Me marcho.",
};