string DLG_TEXT[183] = {
"¿Quién eres, ",
"?",
"Soy ",
", capitán del '",
"'.",
"Mi nombre es ",
", y soy, por supuesto, el gobernador de esta colonia.",
"Es un placer conocer a Su Excelencia.",
"Oh, he oído hablar mucho de ti, ",
". Dicen que eres buen capitán, y que has ganado mucha fama.",
"Me alegra oír eso, Excelencia.",
"¿Qué puedo hacer por ti, ",
"?",
"Me gustaría hablar de negocios contigo.",
"Me temo que tengo que rechazar la misión que me dio Su Excelencia. Ese barco de guerra inglés es demasiado para mí.",
"He venido a hablar un momento.",
"¿Hablar? ¿Por quién me tomas, ",
"? Soy un oficial del estado. ¡No tengo tiempo para parlotear!",
"Pido perdón a Su Excelencia. Me iré.",
"Lo siento, pero no tengo nada de qué hablar ahora, ",
".",
"Lo siento, señor. He cambiado de opinión.",
"Sí, creo que puedo encontrarte una misión.",
"¿Qué tal si me deshago de ese formidable barco pirata que bloquea las rutas comerciales?",
"Me enteré de que derrotaste al barco corsario. Mis felicitaciones, ",
". ¡Fue una victoria brillante!",
"Es un placer servir a Francia ya Su Excelencia, pero me gustaría recibir mi recompensa por eliminar esa fragata ligera pirata antes de recibir una nueva misión.", // PB: Changed to save confusion
"No puedo decir que me alegre de verte, pero supongo que no tengo otra opción. Tienes algunos amigos muy influyentes.",
"Gracias, señor.",
"¿Así que una de las personas más buscadas del archipiélago aparece justo frente a mi? ¡¡¡Guardias!!!",
"Ruego a Su Excelencia que retire a sus hombres de inmediato, o una cierta dama con el nombre de ",
"Virginie d'Espivant",
"morirá. No creo que su padre esté contento al saber que su muerte podría haberse evitado.",
"Te escucho. ¿Qué quieres?",
"En mi barco tengo una dama llamada ",
"Virginie d'Espivant",
"...",
"¡¿La has encontrado?! ¡Gracias A Dios! Pero, dime, capitán, ¿es una prisionera en tu barco?",
"Exactamente, señor. Aunque fue pura coincidencia que la encontrara.",
"¡Claro que no! Al contrario, es mi invitada de honor.",
"Me alegra escuchar eso. ¿Cómo la encontraste?",
"Es una larga historia, señor. No me cabe duda de que. ",
"Virginie d'Espivant",
" la contará ella misma, si lo considera necesario.",
"Sí, por supuesto. No te retrasaré más. Acepta este dinero con mi más profundo agradecimiento, y haré los arreglos para que la joven sea escoltada desde el puerto cuando la bajes  atierra.",
" Por supuesto, señor.",
"¿Así que la estás reteniendo ahí para cobrar un rescate?",
"Sí. Y me gustaría señalar que llegó allí por pura coincidencia.",
"Tomo nota. Ahora, ¿qué quieres a cambio de su libertad?",
"Dinero. Y al garantía de que se me permitirá volver a mi barco sin obstáculos, por supuesto.",
"¿Cuánto?",
"Creo que 7000 piezas de oro serán suficientes.",
"¿Quée? ¡¿Estás mal de la cabeza?!",
"¿Realmente Su Excelencia cree que este es un momento apropiado para regatear?",
"Muy bien. Aquí esta el dinero. Y tienes mi garantía de salvoconducto para volver a tu barco. Deja ir a la chica.",
"¿Garantia? Me han dicho que Su Excelencia es hombre de palabra, pero no voy a arriesgar mi cuello para averiguarlo. Entregaré a la chica cuando zarpe.",
"Muy bien. Pero cuidado: ¡intenta engañarme y ordenaré a todos los barcos disponibles que me traigan tu cabeza!",
"De acuerdo.",
"Ya veo. Bueno, me veo obligado a decir esto... Tengo que perdonarte todos tus crímenes contra mi país...",
"¡Cuánto honor, señor!",
"¡Cuidado con tu sarcasmo! Si dependiera de mí, colgarías de una soga en la plaza de la ciudad. Agradece mi generosidad a la joven a la que salvaste.",
"¡Mi gratitud es infinita, señor!",
"Estoy seguro de ello. Además, se me ha ordenado pagarte una recompensa. Aquí está. Y ahora, por favor, hazme un favor: vete.",
"Con mucho gusto, señor.",
"Entonces, crees que estás a la altura del desafío, ¿verdad? Ya que nuestra flota está ocupada en otra parte con una operación importante, será tu misión hundirlo.",
"¿Puedo apresarla si lo prefiero, señor?",
"Me temo que debo negarme.",
"Si quieres, ",
". Te pagaré 30000 piezas de oro para hundir o apresar el buque de guerra. Y puede que también tenga una bonificación extraordinaria para ti.",
"De acuerdo. Acepto la miisón.",
"No. Eso no es suficiente dinero para persuadirme de luchar contra un enemigo tan formidable. Me veo en la obligación de rechazar la oferta a menos que la recompensa sea más alta.",
"Excelente. Te deseo suerte, ",
".",
"Su Excelencia puede estar tranquilo. Yo me encargaré de esta misión.",
"¡No voy a negociar contigo como un comerciante del mercado! Soy un noble. ¡Acepta la misión o sal de mi vista!",
"Muy bien. Hundiré el barco de guerra, señor.",
"¡A Su Excelencia le será difícil encontrar capitanes dispuestos a hacer su trabajo sucio por tan exiguas recompensas!",
"Ten, toma tu recompensa como acordamos y esta espada también. Considéralo una muestra de mi gratitud. No te alejes demasiado. Puede que tenga otras tareas para ti más tarde.",
"Por supuesto, señor. Dejaré a Su Excelencia volver al trabajo. Adiós.",
"Debo decir que me ha decepcionado descubrir tu cobardía.",
"Su Excelencia puede decir lo que quiera, Pero valoro mi vida más que el oro.",
"¡Retirad eso, señor! ¡Lo haré, pero no toleraré otro insulto!",
"Me das asco. ¡Sal de mi despacho de inmediato!",
"Como desee Su Excelencia.",
"Deseo servir a Francia, Excelencia.",
"#sgov_nation# siempre se complace en aceptar nuevos capitanes a su servicio. ",
"Actualmente, ",
"no",
" estamos en guerra contra ",
"el gobierno ",
"ninguna nación",
". Por supuesto,",
", pero",
" los piratas siempre deben ser hundidos en cuanto sean avistados.",
"Haré que Su Excelencia se sienta orgulloso.",
"¿Como está mi hoja de servicios, señor?",
"Has hundido ",
" barcos ingleses, ",
" barcos piratas, un total de ",
" barcos.",
"Gracias.",
"Espero que no haya quejas de mi servicio, señor.",
"¡Claro que no, capitán! De hecho, es un placer para mí otorgarle una comisión en la Armada de Su Cristiana Majestad. Como oficial se te recompensará por cada barco que hundas al servicio de Francia.",
"Su Excelencia me honra, y trataré de estar a la altura de la confianza que Su Cristiana Majestad ha puesto en mí.",
"Me gustaría cobrar mi salario, señor.",
"Bueno, has hundido ",
" barcos holandeses, ",
" barcos piratas. Así que ",
" barcos en total. Tu salario actual asciende a ",
", asi que un total de ",
"Gracias, señor.",
"¡Escoria traidora! Conque hundiendo los barcos de tus compatriotas, ¿eh? Por la presente, se te expulsa del servicio, tu nombre queda borrado de las listas, ¡y no quiero volver a ver tu cara en esta ciudad!",
"...",
" desde la última vez, aquí están tus ",
" piezas de oro",
"He oído que se me ha concedido un ascenso.",
"¡En efecto! Excelente trabajo. Tu nuevo rango es ",
"Gracias, señor.",
" barcos holandeses, y ",
"Entonces, tengo una propuesta para ti, capitán.",
"¿De verdad?",
"Me he enterado de que has completado la tarea con éxito; ¡mi enhorabuena, capitán! Aquí está tu recompensa.",
"Muchas gracias; ha sido un placer ayudar.",
"Debes destruir un barco de ",
" vessel ",
"quest pirate",
", que amenaza el tráfico marítimo en aguas de ",
". Si lo hundes, te recompensaré con la considerable suma de ",
" piezas de oro. ¿Qué dices, capitán?",
"Prometo a Su Excelencia que no volverá a saber de ese barco.",
"Me temo que no puedo ayudar.",
"Suplico el perdón, Excelencia.",
"Me gustaría saber más acerca de las relaciones de #sgov_nation# con otras naciones.",
"Quiero conseguir una patente de corso.",
"Ah, ",
", que alegría que nos honres con tu visita. Me gustaría presentarte a mi ",
". Vendrá una vez que hayamos termiando con nuestros asuntos.",
"No puedo seguir sirviendo a ",
", Excelencia.",
"Me he hartado de servir a ",
".",
"Como garantía de tus capacidades como capitán, y para compensar el tiempo que voy a perder en presentar tu caso a ",
", debo pedirte ",
" piezas de oro.",
"De ninguna manera.",
"Muy bien.",
"A la luz de tus anteriores servicios, ",
" te otorga el rango de ",
"Has dañado los intereses de ",			 
", y ",
" no olvida a sus enemigos. ¡Vete inmediatamente, o los guardias te echarán a patadas!",
"...",
"Has causado a ",
" grandes daños, capitán, pero ",
"está dispuesta a pasar por alto tus transgresiones pasadas... por un precio: ",
" piezas de oro.",
"Muy bien, Excelencia. Acepto.",
"Un placer tratar contigo, ",
"Y con Su Excelencia.",
". Ademas, se te concede un premio de ",
" acres de tierra por orden de ",
".",
"¿Seguro, ",
" lamentará perder tus servicios.",
"Sí, seguro.",
" no ve con buenos ojos a los chaqueteros, ",
"Hum..., no he diho nada.",
"Muy bien. Pero espero que lo reconsideres, con tiempo...",
"...",
"Adiós, ",
"¿Eh?",
"Se siente.",
"Soy amigo de Roxanne Lalliere y me gustaría saber dónde está.",
"¿Puedes repetir tu nombre, #ssir#?",
"Soy Bartolomeu o Portugues. Fui su compañero en el ataque al almacén de Santiago.",
"Sí, me habló de esa operación. ¿Y por qué quieres verla?",
"Creo que está en peligro por mi culpa. Algunos mercenarios españoles quieren atraparme y es muy posible que intenten capturarla e interrogarla, o algo peor, ya que es mi mejor amiga.",
"Eso es una molestia, por decirlo suavemente. Está en una misión secreta para mí. No me gustaría que estos personajes pendencieros lo sabotearan. Está en Alice Town.",
"¿Cuándo fue allí?",
"Hace una semana. Estoy seguro de que seguirá allí cuando llegues.",
"Excelente, gobernador. Levaré anclas hoy mismo.",
"Date prisa, esos mercenarios no pueden interferir con su misión.",
"A la orden, gobernador. ¡Adiós!",
};
