string DLG_TEXT[77] = {
"querida mandataria! Estoy ",
", propietario del astillero local.",
"Y estoy ",
", capitan del barco ",
".",
", ",
". Necesitas los servicios de mi astillero?, ",
"?",
"De hecho, necesito que arregles un par de agujeros de bala y arregles algunas velas.",
"Ahora mismo, solo necesito hablar contigo.",
"No, solo pense en pasarme.",
"Bueno, estoy muy contento de conocerte. Si eres capitan, entonces mi astillero esta siempre a tu Servicio.",
"Perfecto, ",
". Vamos a empezar con esas reparaciones.",
"Gracias. Pero primero, hablemos.",
"La proxima vez, tal vez. Tengo que irme.",
"Que es exactamente lo que te interesa, ",
"?",
"No, no creo que lo haga.",
"Ya veo. ?Necesitas algo mas, ",
"?",
"Me gustaria poner un par de parches en la vieja Banera que me trajo aqui!",
"Eso es todo, gracias. Adios!",
"Que necesitas exactamente?",
"Necesito reparar mi nave, aunque podria considerar simplemente desguazarla y comprar una nueva.",
"Necesito instalar nuevas armas en mi nave.",
"Nada, gracias.",
"En que puedo ayudarle, Capitan?",
".",
"Necesito hablar con Florens Clauss.",
"Como puedo ayudarte, #ssir#?",
"Necesito hablar con Florens Clauss.",
"Clauss? Me debe 5000 dolares. Si estas dispuesto a pagar su deuda, puedes hablar con el tanto como quieras.",
"Fino. Yo cubrire su deuda.",
"Me temo que no tengo esa cantidad de dinero.",
"Llegas demasiado tarde. Clauss la deuda fue pagada por uno de los piratas locales que vive cerca de la ciudad. Te aconsejo que no los busques . no les importan los extranos.",
"Asi que los piratas tienen a Claus ahora. Ya veo....",
"Necesitas los servicios de mi astillero?",
"Encantado de conocerte.",
"Necesitas los servicios de mi astillero?",
"Perfecto, ",
". Empecemos con la reparacion.",
"Gracias. Pero primero, hablemos.",
"He cambiado de opinion. Te dare 5000 dolares para pagar la deuda de Clauss.",
"Tal vez la proxima vez. Me tengo que ir.",
"Me niego a comerciar con una persona de su reputacion y relaciones. Ahora salir, ",
", antes de que llame a los guardias.",
"Muy bien.",
"Muy bien, mi muelle junto al fuerte esta disponible para ti. Si quieres, le dire a mi capitan que remolque tu barco alli. Solo entonces puedo inspeccionar el dano y decirte cuanto tiempo y dinero me llevara. ",
"MUELLE JUNTO AL FUERTE? Uhh... Yo solo x que tengo... eeh... otro asunto urgente que debo atender primero. Despedir.",
"Despues de cerrar este dialogo, pulse ENTER para conversacion la interfaz de cambio de vela.",
"Salida",
"Me gustaria mejorar mi nave, por casualidad.",
"Senor, parece nervioso... ?por casualidad no tienes suficiente dinero ahora mismo?",
"- La Ultima mejora cientifica para su barco, directamente de los constructores de Brest: placas de cobre a la declaracion de su casco de algas marinas y otras molestias",
"- Para un capitan tan famoso, los mejores canones de bronce... Si, ellos pueden ser un poco caros, pero son los mas precisos en el Caribe",
"- Que pasa con esos dos grandes cazadores de bronce? Pueden derribar un mastil de Mesana a distancias increibles.",
"- Por supuesto, Senor, podemos proveerle con nueva fachada, velas, cables, y todo el aparejo que necesite",
"- Tenemos largos mastiles superiores, de la mejor madera 'palosanto'. Puedes conseguir un par de nudos mas. Pero ten cuidado de arreglarlos bien.",
"- No me atreveria a Mostrar esto si usted no tiene tal fama de' abierto ' y de actualizadaante cientifico: el ultimo articulo publicado de la Royal Society de Londres muestra que con estas velas triangulares entre sus mastiles se puede ganar velocidad, vuelta, e incluso virar mas cerca del viento.",
" Quieres un casco mas fuerte? Podemos reforzar los cuadros, vigas y rodillas, pero, cuidado, no podemos SACARLOS despues.",
"- Si, lo se, todo el mundo quiere 'flush' una nave capturada... por supuesto, no estoy diciendo que usted, senor, fueron un pirata! .",
"Me gustaria sacar una mejora",
"He cambiado de opinion, vamos a cambiar de tema",
"Bien, Senor, Cual de sus naves sera el objetivo?",
" (",
"piastras - ",
" jornadas)",
"Bueno, Senor, nuestro astillero ofrece orgullosamente estas mejoras tecnicas...",
" Ehum... tal vez deberia reconsiderar mis decisiones. Que tenga un buen dia, Senor.",
" Que quieres descartar?",
"- Quiero sacar mis platos de cobre",
"- Quiero vender mis canones de bronce",
"- Estos cazadores de bronce eran un regalo de un gremio de comerciantes, pero tengo que venderlos",
"- Mis nuevas velas y la fachada de Manila",
"- He intentado usar largos mastiles superiores, pero mis naves se comportan extrano con ellos en la parte superior. Quiero cambiar a los mas comunes",
" Ehum...estancia velas! Buf! esos extranos inventos nunca son para bien",
};
