string DLG_TEXT[21] = {
"¡Estaré siempre en deuda contigo, #ssir#!",
"Para nada. Me han pagado mucho dinero para salvarte.",
"Pero, ¿quién eres tú? ¿Por qué me has salvado?",
"Continuemos con esta conversación afuera.",
"Por favor, dime quién eres. ¿Por qué me salvaste?",
"Hablaremos más tarde. Por ahora, salgamos de aquí. No tengo ningún deseo de hablar con un guardia francés.",
"¿Quién eres?",
"Soy ",
". Tu padre estaba muy preocupado por tu desaparición, y me envió a buscarte.",
"Ya veo. Iba a verlo cuando me metí en el lio del que acabas de sacarme. Te debo mi vida.",
"No me lo agradezcas. Me pagaron bien por mis esfuerzos.",
"Sin embargo, me salvaste la vida, y te estoy agradecido. Ahora, ¿qué tal si vamos a ver a mi padre?",
"Sí. No perdamos mas tiempo.",
"Capitán, no tengo palabras para expresar mi gratitud. Tal vez me dejes servir como parte de tu tripulación. No soy un mal espadachín, y sé manejarme a bordo de un barco.",
"Siempre hay lugar para un hombre capaz, especialmente un hombre leal. Bienvenido a mi tripulación.",
"Aprecio tu oferta, pero no puedo aceptarla en este momento.",
"Lo entiendo. Pero, de nuevo, te doy las gracias, capitán. Podrás encontrarme a menudo en la residencia del gobernador. Búscame allí si cambias de opinión.",
"Lo tendré en cuenta. ¡Buena suerte!",
"¡Capitán, me alegro de verte! Todavia estoy dispuesto a servir en tu tripulacion, si has cambiado de opinión.",
"De hecho, sí. Me vendría bien un tripulante capaz.",
"Lo tendré en cuenta. ¡Buena suerte!",

};