string DLG_TEXT[340] = {
"Con tu permiso, #ssir#. Estoy pensando en retirarme. Sé que es un mundo nuevo y espléndido el que tenemos aquí, con muchas oportunidades para gente emprendedora que busque emoción, y almas sedientas de aventuras. Pero lo que antes parecía una vida sencilla, hoy en día me hace sentir inseguro, sin rumbo fijo. Tal vez sean los achaques de la vejez, que no perdona.",
"¿Qué quieres decir con inseguro, #sname#? ¿Cuál es el problema?",
"¡Escúpelo de una vez, hombre! ¡Solo dime qué estás haciendo en mi camarote!",
"Lo siento, #sname#, puede que las cosas hayan cambiado, pero no hay tiempo para andar rememorando los viejos tiempos. Puede que ahora la vida marinera sea más compleja, pero el vigía ha dado aviso de que una flota de guerra con pabellón #senemy# se dirige hacia aquí y no me gustaría quedarme en medio de lo que se avecina. Sé que estamos en plena tempestad y que podemos terminar a la deriva o incluso naufragar. Sin embargo, correré ese riesgo, y zarparé enseguida. Así que si te vas, te digo adiós y te deseo buena suerte ¡Puede que vuelva a verte de nuevo en mis viajes!",
"Esto..., bueno... Quiero decir... ¡LAS COSAS NO SON COMO ANTES! Se habla mucho a bordo sobre quién está en guerra con quién, o dónde están aplastando el contrabando, y cómo todo eso afecta al tratamiento que recibimos los pobres marineros vayamos donde vayamos. Incluso los comerciantes y los corsarios honrados, y hasta la Armada, tienen que vigilar sus pasos. El contrabando tampoco es tan fácil hoy en día, ya que muchas islas cuentan con mejores patrullas de aduanas. Me preocupa no vivir para ver mi retiro, capitán...",
"¡Tonterías, #sname#! Aunque pueda parecer confuso para el marinero ignorante, es solo cuestión de conocer la situación internacional, asumir un código común de conducta y entender hasta qué punto puedes desviarte de él para obtener alguna ventaja. Recuerdo que hace poco he visto algunos libros sobre relaciones internacionales y conntrabando que te ayudarían a entender cómo prosperar en el Nuevo Mundo.",
"Puede que tengas razón, #ssir#, pero nosotros solo seguimos tus órdenes y asumimos que tú sabes lo que haces. Así que mientras te mantengas al tanto de la situacion y conozcas esos libros, supongo que estaremos bien.",
"Hum... Seguir órdenes siempre es una excusa endeble para la ignorancia. Por supuesto que espero que las sigas, por eso soy capitán. Pero deberías tratar de entender por qué doy las órdenes que doy. Estarás de acuerdo conmigo en que la vida es más fácil si sabes a lo que te atienes. No puedes navegar por estas aguas sin hacer algunos enemigos tarde o temprano, ¿eh, #sname#? ",
"¡Claro que no, capitán! Y además del riesgo de enemistarte con cualquier nación y sus aliados o de mezclarte con contrabandistas, hay muchas otras formas de meterse en problemas. Muchos villanos desesperados vagan por las calles de estos colonias del Caribe y se puede contratar a un asesino por una pinta de ron. Y no esperes ninguna ayuda de las autoridades coloniales corruptas. Los guardias de la ciudad no levantarán un dedo para proteger a gente como nosotros. Tienes que ir con ojos en el cogote todo el tiempo, y es mejor que te lleves un guardaespaldas contigo cuando estés en tierra.",
"Parece que mi aventura en el Caribe va a ser más arriesgada de lo que esperaba. Tendré que tener cuidado hasta que tenga más experiencia y sepa todo lo que hay que saber sobre cómo funcionan las cosas por aquí. ¿Hay algo más que debas decirme, #sname#?",
"¡Bueno, capitán! Ayer me pediste que te recordara algunas cosas que tenías que hacer hoy.",
"Ah, sí, muy bien. Está bien, adelante.",
"Me acuerdo de todo perfectamente. Gracias.",
"¡Olvida todo eso, el vigía ha avistado buques con pabellón #senemy# navegando en esta dirección! ¡Debemos salir de puerto ahora, antes de quedar atrapados en medio de una batalla, con tormenta o sin tormenta!",
"En primer lugar, toma tu equipo personal. Recuerda, siempre debes tener contigo tu espada, tu pistola y tu catalejo. Quién sabe lo que puede pasar en estas colonias.",
"Después de subir a bordo, ¿dónde guardamos todo eso?",
"Todas tus cosas están dentro de ese cofre grande que hay detrás de ti.",
" Acércate a él y veras un icono en la esquina superior izquierda de la pantalla\n Esto significa que puedes interactuar con el objeto. Cuando veas el icono, pulsa la tecla 'Acción'.",
"Ya veo.",
"Si usas una caja o un cofre de esta manera, verás una interfaz que te permitirá tomar objetos del contenedor o ponerlos en él. Ahora, ve a buscar tus posesiones, capitán, y vuelve a hablar conmigo cuando hayas terminado.",
"Muy bien, espérame aquí.",
"¿No has olvidado algo, capitán? Parece que aún no has recogido todas tus posesiones.",
"¡Ah, sí! ¿Cómo se me ha podido olvidar? Discúlpame un momento.",
"Muy bien. Antes de continuar, debemos ocuparnos de una cosa importante que podría determinar tu supervivencia durante un abordaje. Cada barco tiene un armero donde se almacenan las armas utilizadas por los grupos de abordaje. Lo encontrarás en la cámara del capitán. Este armero tiene un icono con un símbolo especial, una psitola y un cuchillo cruzados, pero se accede a él igual que a un cofre normal. Cuanto mejores sean las armas que pongas en el armero, más éxito tendrá tu tripulacion durante los combates cuerpo a cuerpo.",
" Tu tripulación devolverá todas las armas después de cada acción de abordaje, junto con las que tomen de los enemigos derrotados. ",
" Tu tripulación llevará armas consigo, por lo que debes acordarte de reponer los suministros en el armero con cierta frecuencia. ",
"Cuando estés en la cámara del capitán de un barco apresado, puedes inspeccionar su armero para encontrar armas adicionales.",
"Por cierto, capitán, podría enseñarte algunas cosas sobre esgrima, si quieres. Solo tienes que preguntarme.",
"Creo que me vendría bien un poco de entrenamiento. Enséñame.",
"No me interesa, #sname#. Continuemos con el programa de hoy.",
"Me estoy cansando de esto. Ya es suficiente.",
"¡Genial! Ahora deberías equipar tus armas y tu catalejo. Para ello, pulsa la tecla de la pantalla de personaje (F2) y selecciona la pestaña 'Inventario' en la parte superior derecha de la pantalla. Una vez que estés en tu inventario, verás varias categorías en la parte inferior de la pantalla, 'Arma', 'Medicación', 'Objetos', 'Mapas' y 'Objetos de misión'. Para equipar tu espada haz clic en la categoría de 'Arma' y luego selecciona tu espada y haz clic en el botón 'Equipar' para equiparla o en el botón 'Desequipar' para devolverla al inventario. Haz lo mismo con tu pistola.",
" Cuando hayas terminado, haz clic en la categoría 'Objetos', selecciona tu catalejo y equípalo. Tambien puedes utilizar la tecla 'Equipar rápido' de tu teclado (F). Ten en cuenta que tu arma blanca debe estar equipada antes que tu pistola. Ten en cuenta también que no todos los objetos pueden ser equipados. Ahora equipa tu espada, pistola y catalejo, y después habla conmigo de nuevo.",
"Un segundo...",
"No podrás defenderte muy bien solo con los puños, capitán.",
"Muy bien...",
"¡Ey, capitánn, te olvidas tu pistola! También debe estar equipada.",
"¡Por favor, discúlpenme, me abruma tanta información!",
"Lo haré ahora.",
"Ahora, para ayudar a tus hombres en los abordajes, pon este montón de ",
"s en tu armero.",
"De acuerdo.",
"Capto la idea; ponlos tú y sigamos con cosas más importantes.",
"Parece que aún no has llenado el armero, capitán.",
"Espera un minuto...",
"No hay problema, capitán. Presta atención, por favor. En la esquina inferior izquierda podrás ver el icono de tu personaje. La barra roja que hay encima del icono es tu salud. La barra azul representa el estado de carga de tu pistola. Y los círculos encima de las barras muestran cuántos disparos tienes cargados en tu pistola.",
"Entendido.",
"Bien. Necesitaremos más espacio para nuestros ejercicios. Sígueme; cuando te acerques a la puerta verás el icono correspondiente en la esquina superior izquierda de la pantalla. Pulsa la tecla 'Acción' para ir a la siguiente ubicación.",
"Adelante.",
"Ahora, capitán, desenvaina tu espada con la tecla 'Desenvainar/Envainar espada'. Primero deberías familiarizarte con los controles, así que no te atacaré. Utiliza la tecla 'Acción' para atacar y la tecla 'Disparar pistola' para disparar tu pistola.",
"Déjame intentarlo.",
"Un segundo. Para ganar distancia rapidamente entre tu adversario y tú, puedes saltar hacia atrás pulsando la tecla 'Esquivar'. Ten en cuenta que no puedes hablar con nadie mientras tengas el arma desenvainada. Así que, antes de hablar, envaina tu arma pulsando la tecla 'Desenvainar/Envainar espada' de nuevo.",
"Lo he entendido. Ahora déjame intentarlo.",
"Bueno, ¿seguro que lo has entendido todo hasta ahora?",
"Sí, y gracias por la instrucción, #sname#",
"No, creo que lo intentaré de nuevo.",
"Me he cansado de toda esta instrucción, vamos a seguir con otras cosas.",
"Muy bien, es suficiente, capitán. ¿Crees que podrás con un poco de acción real?",
"¡Claro, adelante!",
"Todavía no. Déjame practicar un poco más.",
"No hay problema, capitán.",
"Gracias.",
"Esta vez, te devolveré los golpes. Ten cuidado, capitán, y no olvides que puedes parar los golpes que recibas con la tecla 'Bloquear'. Si te lanzas al combate sin pensar, pronto estarás alimentando a los buitres.",
"Lo he entendido. Vamos a empezar.",
"¡No está mal, capitán, no está mal! Ten en cuenta que si has recibido heridas en un combate, puedes recuperar un poco de salud usando pociones, vendas y otros objetos de curación. Para hacer esto, debes pulsar la tecla 'Menú de comando rápido' y seleccionar el icono de 'Usar objeto'. A continuación, pulsa la tecla 'Acción', selecciona el objeto de curacion de la lista, y pulsa la tecla 'Acción' de nuevo.",
"Ya veo. ¿Qué viene ahora?",
"Quiero entrenar un poco más. Vamos a luchar de nuevo.",
"Basta de estas lecciones. Puedes retirarte.",
"Hum... Parece que necesitas más práctica... Ten en cuenta que si has recibido heridas en un combate, puedes recuperar un poco de salud usando pociones, vendas y otros objetos de curación. Para hacer esto, debes pulsar la tecla 'Menú de comando rápido' y seleccionar el icono de Usar. A continuación, pulsa la tecla 'Acción', selecciona el objeto de curacion de la lista, y pulsa la tecla 'Acción' deó nuevo. Ahora, vamos a intentarlo de nuevo.",
"Si tú lo dices. Empecemos de nuevo.",
"Mejoraré mis habilidades más tarde. ¿Qué viene ahora?",
"Basta de estas malditas lecciones. Retírate.",
"¡Siempre listo, capitán!",
"Prepárate.",
"Eso está mucho mejor, capitán. Ahora puedo dejarte bajar a tierra sin preocuparme.",
"¿Y ahora qué?",
"Creo que todavía necesito algo más de práctica.",
"Basta de estas lecciones. Retírate.",
"Pues no... Supongo que llevará un poco más de tiempo enseñarte esgrima como es debido. Tal vez deberías pasar un par de días a bordo recibiendo entrenamiento.",
"¿Podemos intentarlo una vez más?",
"Ya mejoraré más tarde. ¿Y ahora qué?",
"Bien. Antes de desembarcar, déjame hablarte de tus destrezas y habilidades. Ya que un capitán habil siempre tiene más oportunidades de sobrevivir en este mundo cruel, tendrás que desarrollar tu personaje sabiamente\n Tu personaje gana puntos de experiencia al luchar contra enemigos y completar misiones. Cuando obtienes suficiente experiencia, tu personaje gana un nuevo nivel y más puntos de destreza y habilidades. Usando estos puntos, puedes mejorar varios aspectos de tu personaje\n Para obtener toda la información acerca de tu personaje, pulsa la tecla de 'Pantalla de estado del personaje' (F2). Allí verás tu nivel, tu reputación, tu dinero, tus destrezas y tus puntos de vida. Tienes algunos puntos de destreza y habilidad\n Puedes distribuirlos ahora o más tarde.",
"¿Cómo puedo distribuír puntos de destreza y habilidad?",
"Bien. Antes de desembarcar, déjame hablarte de tus destrezas y habilidades. Ya que un capitán habil siempre tiene más oportunidades de sobrevivir en este mundo cruel, tendrás que desarrollar tu personaje sabiamente\n Ganas puntos de experiencia al luchar contra enemigos y completar misiones. Cuando obitnes suficiente experiencia, ganas un nuevo nivel y más puntos de destreza y habilidad. Aunque puedes decidir qué habilidades te gustaría aprender, tus destrezas mejorarán automáticamente según tus acciones\n Por ejemplo, si entras en combate cuerpo a cuerpo, tu destreza de 'Esgrima' mejorará. Cuando la mejora alcanza el 100 por 100, la destreza subirá de nivel\n Para obtener toda la información acerca de tu personaje, pulsa la tecla de 'Pantalla de estado del personaje' (F2). Allí verás tu nivel, tu reputación, tu dinero, tus destrezas y tus puntos de vida, así como el nivel y porcentaje de avance de tus destrezas. Tienes un punto de habilidad\n Puedes repartirlo ahora o más tarde.",
"Me gustaría saber cómo ganar más puntos de destreza.",
"¿Puedes darme una descripción de las diferentes destrezas?",
"Olvídate de esos puntos de habilidad, sigamos con otra cosa.",
"Si quieres hacerlo ahora, abre la 'Pantalla de estado de persoanje' (F2)\n Para obtener una habilidad debes seleccionar la casilla de 'Habilidades' en la parte inferior de la pantalla y pulsar la tecla 'Acción'. Entonces verás una lista de todas las habilidades. Selecciona la que deseas aprender y pulsa de nuevo 'Acción' para leer la descripción de la habilidad. Para aprender una habilidad, pulse la tecla 'Acción' por tercera vez.\Algunas habilidades no pueden ser aprendidas hasta que hayas cumplido ciertos requisitos.",
"Lo haré ahora.",
"Olvídate de esos puntos, sigamos con otra cosa.",
"Háblame cuando hayas terminado y continuaremos.",
"Claro. ¿Cuál te interesa?",
"Liderazgo.",
"Esgrima.",
"Navegación.",
"Puntería.",
"Cañones.",
"Abordaje.",
"Reparación.",
"Defensa.",
"Comercio.",
"Suerte.",
"Puedes mejorar el 'Liderazgo' hablando con la gente de las ciudades, completando misiones y pagando a tu tripulación regularmente.",
"Gracias. ¿Y las otras?",
"Es suficiente. Háblame de otra cosa.",
"Para mejorar tu destreza de 'Esgrima' obviamente deberás practicar mucho con la espada, ¡solo ten cuidado de no herir a transeúntes inocentes!",
"Mejorarás tu destreza de 'Navegación' cuanto más tiempo pases controlando activamente tu barco. Las tormentas y los tornados también pueden ayudar a mejorar tu experiencia, aunque pueden dañar seriamente tu barco.",
"Disparando tu pistola o tus cañones puedes ganar puntos de 'Puntería'. Usar una pistola es más efectivo.",
"Hacer progresos en la destreza de 'Cañones' requiere que combatas contra otros barcos o fuertes y les aciertes con tus andanadas.",
"Mejorarás tu destreza de'Abordaje' cada vez que lanzas los garfios para abordar un barco enemigo.",
"Observa como el carpintero de ribera repara tus barcos en el astillero y obtendrás experiencia en 'Reparación'. Lograrás el mismo efecto cuando efectúes reparaciones en tu barco durante las batallas navales.",
"Convertirse en un maestro de la 'Defensa' requiere experiencia usando el bloqueo durante los combates a espada y la reparación de barcos en el astillero o durante una batalla naval.",
"Si tratas a menudo con mercaderes, puedes mejorar rápidamente tu destreza de 'Comercio'. Cuando tu destreza comercial es baja, los mercaderes te desplumarán; ¡cuando es alta, tú podrás desplumarlos a ellos!",
"Tu 'Suerte' mejorará cuando juegues a las cartas en las tabernas. Además, mejorará al completar misiones y hablando con las personas que encontres; pero ten cuidado, capitán, Cuando tu Suerte es baja, algunos de ellos pueden tratar de robarte tus pertenencias.",
"¿Necesitas algún Consejo sobre cómo distribuir tus puntos de destreza? Puedes poner algunos en 'Esgrima' y algunos en 'Liderazgo' para empezar, o tal vez en 'Comercio' para cuando vendemos nuestra carga\n Pero no hay prisa con eso, siempre se puede hacer más tarde, según surja la necesidad.",
"Esta destreza te permite controlar mejor a tu gente. Si tienes una voluntad fuerte, tu tripulacion tendrá menos probabilidades de rendirse en combate. También, al admirar tu confianza y fuerza, tus enemigos se desmoralizarán y se rendirán antes. Esta habilidad es muy útil para cualquier capitán en estas aguas.",
"Creo que voy a distribuir mis puntos ahora.",
"El daño que infliges con tu espada depende de esta destreza. Tambien afecta a la posibilidad de atravesar los bloqueos del enemigo y bloquear exitosamente los ataques enemigos.",
"Esta destreza demuestra tu pericia a la hora de navegar y gobernar tu barco. Si esta destreza es alta, tu barco será más rápido y más ágil.",
"Una buen puntería puede ayudarte a ganar una batalla naval incluso contra un enemigo superior. Esta destreza representa la precisión con la que tus artilleros pueden disparar los cañones. Recuerda, disparar manualmente desde la cubierta siempre logra mejor puntería.",
"Esta destreza está relacionada con la de 'Puntería' y también es importante para las batallas navales. Mientras más alta sea esta destreza, más rápido recargará los cañones tu tripulación, y más rápido dispararán cada andanada.",
"Esta destreza es muy útil para cualquier pirata o corsario. Te permite lanzar correctamente los garfios de abordaje para atrapar a un barco enemigo y tratar de apresarlo con tu grupo de abordaje.",
"Esta destreza te permite reparar tu barco en mar abierto. Cuanto mayor sea la destreza, mayor será el porcentaje de daño que podrás reparar. Tendrás que tener tablas y lona a bordo de tu barco para llevar a cabo cualquier trabajo de reparación.",
"La tripulación es la parte más frágil del barco y la más importante. Sin suficiente tripulación, cualquier barco se vuelve ingobernable y torpe. La destreza de 'Defensa' te ayuda a proteger a su tripulación del fuego enemigo. También disminuye las pérdidas de tripulación en las batallas navales.",
"La destreza de 'Comercio' es esencial para los mercaderes y comerciantes. Con un comercio alto puedes conseguir mejores precios en las tiendas y a veces puedes incluso conseguir un descuento al contratar a un oficial.",
"Bueno, estas islas están a medio civilizar. Las autoridades aún son débiles, y muchos aventureros y criminales vienen aquí a aprovecharse de eso. Así que las calles y las tabernas estan llenas de ladrones, contrabandistas, jugadores y asesinos, y debes aprender a moverte en esos ambientes si quieres hacer frente a esos tipos y evitar trampas y engaños. Si juegas, luchas, traficas con contrabando o robas, tendrás más éxito cuanto más alta sea tu suerte. Recibirás menos daños y más recompensas",
"Ahora debo recordarte ese asunto que planeamos para hoy.",
"Adelante.",
"En primer lugar, tenemos mercancía que vender, debemos venderla al comerciante local, que no debería ser demasiado difícil de encontrar\n Además, nuestro barco sufrió algunos daños en esa última tormenta y necesita reparaciones. El astillero local podrá encargarse de ello\n Después tenemos que contratar a algunos tripulantes nuevos para reemplazar a los que fueron arrastrados por la tormenta. Pregunta al tabernero local por marineros que busquen trabajo, y recuerda que siempre puedes pedir a la gente indicaciones para llegar a donde necesites ir.",
"¿Eso es todo?",
"Casi. Tu catalejo está muy viejo y rayado, no te dará las ventajas que necesitas en estas aguas peligrosas, capitán. Tal vez podrías comprar uno nuevo. Habrá alguno a la venta en alguna parte de la ciudad.",
"Y una cosa más: nuestro vigía ha informado de que una flota de guerra con pabellón #senemy# está peligrosamente cerca. Te aconsejo que ices un pabellón #senemy# cuando hayas zarpado del puerto. Puedes cambiar tu bandera entrando en la 'Pantalla de estado de personaje' (F2) y luego en la pestaña 'Relaciones'. Al ondear el pabellón #senemy#, podremos engañar al almirante #senemy# y escabullirnos, ¡si la suerte está de nuestro lado!",
"Vamos.",
"Si quieres comprar un nuevo catalejo deberías poder hacerlo ahora mismo. La mayoria de las ciudades tienen mercaderes callejeros vendiendo sus mercancias.",
"Bien, hagámoslo.",
"Puedo hacerlo más tarde. Sigamos con otra cosa.",
"Puedes irte. Encontraré mi camino.",
"Tenemos que ir al centro de la ciudad si queremos seguir con nuestro plan para el día. Debemos ir a las puertas de entrada y luego tomar la siguientea puerta hacia la otra parte de la ciudad. Sígueme a las puertas y cuando veas el icono De 'Cerradura abierta' en la esquina superior izquierda de la pantalla, pulsa la tecla 'Acción' para ir a la siguiente ubicación.",
"El asentamiento pirata se encuentra lejos de la costa, en medio de la selva. Para llegar allí, debemos ir más allá de esas rocas, y luego girar a la izquierda cerca de una choza. Más tarde veremos la empalizada. Acércate a la puerta de madera después de mí y cuando veas el icono De 'Cerradura abierta' en la esquina superior izquierda de la pantalla, pulsa la tecla 'Acción' para ir a la siguiente ubicación.",
"¡No hay ni un solo vendedor en la isla! Afortunadamente, he descubierto que podemos comprar un catalejo en la tienda local. Iremos allí a vender nuestra carga, y veremos si tienen un nuevo catalejo.",
"Como desees, capitán. Sígueme.",
"...",
"Los mercaderes callejeros venden varios bienes y normalmente puedes encontrarlos en sus puestos durante el día. Deberías poder comprar un nuevo catalejo. Habla con ellos y pregúntales qué tienen. Verás 4 categorías en la parte superior de la pantalla: 'Arma', 'Medicación', 'Objetos' y 'Mapas'. En cada categoría se ve una lista de artículos: simplemente haz clic en el que necesites y selecciona 'Comprar', A continuación, selecciona la cantidad que deseas comprar y haz clic en 'OK' para realizar la compra. Y ya está.",
"Lo tienes. Genial. Ahora vamos a vender la mercancía que hemos traído a la isla.",
"Muy bien. ¿Dónde podemos hacer eso?",
"Lo haré yo. Regresa al barco.",
"Oye, ¿dónde está ese nuevo catalejo, capitán? ¡No lo veo!",
"Lo compraré ahora.",
"He decidido no comprarlo ahora mismo. Continuemos.",
"Puedo seguir sin ti, #sname#.",
"Como tú digas. Ahora vamos a vender la mercancía que hemos traído a la isla.",
"La tienda local está en el distrito más lejano. Te guiaré hasta allí.",
"La tienda local está dentro de las murallas de la ciudad. Sígueme a las puertas y cuando veas el icono de 'Cerradura abierta' en la esquina superior izquierda de la pantalla, pulsa la tecla 'Acción' para ir a la siguiente ubicación.",
"Yo sé dónde está la tienda, y tú tienes algunas mercancías a bordo que debes vender para sacar dinero con el que pagar las reparaciones del barco y contratar tripulación. Para ver que mercancía tienes a bordo, debes abrir la 'Pantala de estado de personaje' (F2) y seleccionar la pestaña 'Bodega'. A continuación, selecciona un barco de los disponibles para ver su carga. Verás una lista de las mercancías que tiene a bordo. Puedes desplazarla hacia la derecha o hacia la izquierda. También puedes ver la cantidad de munición que tienes en tu barco.",
"Gracias por la información. ¿Nos vamos ya?",
"No necesito tu ayuda.",
"Sígueme. Te mostraré la puerta correcta y dejaré que sigas por tu cuenta. Pero si tienes alguna pregunta, házmela.",
"Ahora ve a hablar con el comerciante, capitán. Vende tu ",
" y ",
". Para conseguir un catalejo, dile al comerciante que quieres comprar algo de equipo personal y él debería tener alguno a la venta. Después de eso, debes vender nuestra carga, que consiste en ",
", pero no compres nada, necesitamos dinero para arreglar nuestro barco y contratar más tripulación. ¿Necesitas más detalles sobre el comercio?",
". Podemos usar el dinero que ganemos comerciando para contratar tripulacion y reparar el barco. ¿Necesita más aclaraciones?",
"Si, eso sería útil.",
"No, puedo arreglármelas.",
"Es muy sencillo, capitán. Habla con el comerciante y dile que quieres comerciar con mercancías. A continuación, selecciona el barco con el que quieras hacer la transacción. Verás una lista de mercancías. Selecciona un artículo que desees vender o comprar y pulsa la tecla 'Acción'. A continuación, selecciona el boton 'Comprar' o 'Vender' y elige la cantidad deseada. Pulsa de nuevo la tecla 'Acción' para confirmar la transacción.",
"Gracias por la explicación.",
"Te esperaré fuera de la tienda. Por cierto, si no has asignado tus puntos de desteza todavía puede ponerlos en su destreeza de 'Comercio' para obtener más beneficios de tus transacciones.",
"Te esperaré fuera de la tienda. Recuerda: tratar mucho con los comerciantes te ayudará a aumentar tu destreza de 'Comercio', que te da la oportunidad de obtener mejores tratos al negociar con ellos.",
"Muy bien, gracias.",
"Deberías vender toda la mercancía que tienes. Pero con eso basta por ahora, a continuación te mostraré cómo puedes contratar tripulación para tu barco. Esto se puede hacer en una taberna.",
"Bien.",
"La encontraré sin tu ayuda. Puedes irte.",
"Ahora que tenemos dinero, podemos ir y contratar algunos marineros más. Para eso, vamos a la taberna.",
"Sígueme. Te llevaré a la taberna.",
"Te sigo.",
"Sí, capitán. Aquí se puede enrolar tripulación. Además, a veces puedes encontrar un buen oficial para tu barco en una taberna, habla con la gente y tal vez tengas suerte. Para enrolar tripulantes, habla con el encargado de la taberna, que esta de pie detrás del mostrador, y pregúntale por marineros que busquen trabajo. A continuación, selecciona el barco al que quieras asignar la tripulación, y pulsaa el boton 'Enrolar'. Después de eso, selecciona cuántos marineros deseas. Presta atencion a la moral de la tripulación. Por último, pulse la tecla 'Acción' para pagar y contratar a esos marineros.",
"A veces sucede que no hay tripulación disponible en una isla... Si pasa eso, mala suerte, tendrás que navegar a otra isla para enrolar tripulantes allí. Te esperaré afuera.",
"Estaré alli enseguida..",
"Vamos bien, capitán. Todo lo que tenemos que hacer ahora es reparar el barco. Mientras enrolabas gente, me di un paseo y encontré el astillero local.",
"Bien. Vamos allá.",
"Sé dónde esté. Puedes volver a bordo.",
"Disculpa, capitán, pero será mejor que contrates a toda la tripulación que puedas. Siempre es mejor que el barco tenga suficiente tripulación para poder gobernarlo con más eficacia. Pero, ya que siempre puedes hacer eso después, podemos ir ahora a arreglar nuestro barco. He encontrado el astillero local.",
"¡A la orden, capitán! Sígueme.",
"En marcha.",
"Ahora estamos en el astillero. Aquí puedes reparar tu barco, mejorarlo, venderlo o comprar uno nuevo. Además, en un astillero puedes instalar diferentes cañones en tu barco. ¿Quieres que te dé instrucciones de cómo reparar tu barco?",
"Sí, dime.",
"No, puedo arreglármelas.",
"Muy bien. Habla con el carpintero de ribera y pídele que le eche un vistazo a tu barco. Entonces, elige el barco que necesite ser reparado, ahora mismo solo tienes uno. A continuación, selecciona 'Reparación'. Si tienes suficiente dinero, solo tiene que pulsar la tecla 'Acción' después de seleccionar el botón 'Reparar todo', y tu barco será totalmente reparado\n Si no, tendrás que seleccionar un porcentaje de casco y aparejo para ser reparado. Selecciona 'Casco' y establece el valor deseado. Haz lo mismo con las velas. Luego selecciona 'Ok' y pulsa la tecla 'Acción' para confirmar las reparaciones.",
"Genial, gracias.",
"Bueno, si está todo claro, te esperaré afuera.",
"Supongo que eso es todo, capitán. Puedo hacerte algunas sugerencias sobre qué hacer, si quieres, pero ahora debo decirte algo. Me he hecho viejo, como demuestra mi barba blanca, y estoy cansado de navegar. Me gustaría que me dieras permiso para abandonar el barco y retirarme aquí, ¡retirarme a la taberna, quiero decir! Ha sido genial conocerte, capitán, pero el resto de mis días quiero ocuparlos bebiendo y jugando. Lo siento si eso te causa problemas.",
"Supongo que eso es todo, capitán. Puedo hacerte algunas sugerencias sobre qué hacer, si quieres\n Mi único sueño es retirarme  a una vida tranquila, surcar los mares solo por placer, y tal vez para sacar un poco de beneficio personal, aquí y allá. Verás, he estado en la mar desde que era un niño, capitán, y ahora mi barba es toda gris. Te estaré muy agradecido si me das permiso para quedarme aquí, colgar el látigo de nueve colas y disfrutar de la taberna local.",
"Hum... Puedo entender tus razones, pero voy a necesitar un buen primer oficial para reemplazarte, #sname#.",
"Encontrarás nuevos oficiales para contratar en la taberna, y yo estaré encantado de darte consejo en cualquier momento si pasas por allí.",
"¿Puedes hacerme algunas sugerencias sobre qué hacer a continuación?",
"Háblame de cómo gobernar mi barco.",
"Háblame de cómo disparar cañones.",
"Háblame de cómo abordar barcos enemigos.",
"Hábleme de cómo pagar a mis oficiales y tripulación.",
"Hábleme de la 'Navegación directa'.",
"Háblame de la 'Moral' de la tripulación.",
"Háblame de izar 'Banderas'.",
"Gracias por tu ayuda, #sname#. ¡Adiós!",
" en la colonia de ",
"Bueno, la última vez que estuve en la tienda, me di cuenta de que tienen ",
" a un precio bastante bajo. Si yo fuera tú, lo compraría aqui y pondría rumbo a ",
". Allí puedes obtener un buen precio por un cargamento de ",
". También puedes sacar beneficios vendiendo ",
"Por desgracia, no puedo ayudarte, capitán.",
"Muy bien. Pero antes de que te vayas, debería recordarte los asuntos que tienes pendientes hoy cuando bajes a tierra.",
"Casi. Tu catalejo está viejo y la lente rayada. Deberías comprarte uno nuevo. Debe haber alguno a la venta en algún lugar de la ciudad.",
"Y una cosa más: nuestro vigía nos informó de que una flota de guerra con pabellón #senemy# está peligrosamente cerca. Te aconsejaría que izaras pabellón #senemy# cuando zarpes del puerto.", // KK
"... Si necesitas mi ayuda otra vez, estaré en la taberna local.",
"Gracias. Hasta la vista.",
"Como desees, capitán. Puedo hacerte algunas sugerencias sobre qué hacer si quieres, pero ahora debo decirte algo\n Me he hecho viejo, como demuestra mi barba blanca, y estoy cansado de navegar. Me gustaría que me dieras permiso para abandonar el barco y retirarme aquí, ¡retirarme a la taberna, quiero decir! Ha sido genial conocerte, capitán, pero el resto de mis días quiero ocuparlos bebiendo y jugando. Lo siento si eso te causa problemas.",
"¿Puedes hacerme algunas sugerencias sobre qué hacer a continuación?",
"Bueno, gobernar un barco no es tan difícil como parece. Los barcos se mueven con el viento. Cuanto más fuerte sople el viento, mas rápido va el barco. Puede disponer tus velas en dos posiciones; a toda vela y velas de batalla, o arriarlas por completo\n En posición de batalla, el barco es más maniobrable, pero la velocidad máxima se reduce. A toda vela, tu barco se mueve más rápido, pero vira más despacio. Mantén un ojo atento a la dirección del viento, tu barco no irá muy rápido si navegas con el viento en contra.",
"Disparar en el modo de tercera persona es muy simple, solo tienes que mantener a los enemigos dentro del arco de tiro de tus cañones y pulsar la tecla de 'Disparo' cuando tus cañones estén cargados. Tus artilleros apuntarán automáticamente los cañones al enemigo\n No olvides que, en el modo de primera persona, puede utilizar el disparo 'manual', así como el automático, pero ten cuidado si utilizas el disparo 'manual'; dispararás independientemente de que estés apuntando a un barco aliado o enemigo\n Disparar maualmente desde la cubierta puee ser un poco complicado. Deberías apuntar tus cañones al barco enemigo, pero no como lo harías con una pistola o un mosquete. No olvides que los cañones disparan con trayectoria balística y debes elevar más el punto de mira cuanto más lejos esté el enemigo\n O bajarlo si está más cerca. Incluso puedes hacer fuego directo, pero solo si tu enemigo está muy cerca de ti.",
"Para abordar un barco enenmigo, debes acercarte mucho a él. Su velocidad relativa y la tuya también deben ser similares, a menos que tengas una habilidad especial o una puntuación alta en la destreza de 'Abordaje'\n Cuando estés en posición, tendrás que abrir el menú de acción rápida y seleccionar la orden de abordaje. A continuación, tendrás que abrirte camino por las cubiertas del barco enemigo con tu tripulación, acuchillando y matando a los marineros enemigos, ¡y saqueando todo lo que puedas por el camino!\n Después de ganar el abordaje, puedes saquear todas las mercancías de ese barco o apresarlo si tienes un oficial para ponerlo al mando del barco capturado.",
"Hay dos maneras de pagar a tu tripulación. Puedes pagarles un 'Salario' o puedes 'Firmar artículos' con ellos. Ten en cuenta que algunos tripulantes podrían desertar si tienes un bajo nivel de liderazgo al cambiar entre pagar un salario fijo y dividir el botín.",
"Háblame de pagar 'Salario'.",
"Hábleme de 'Firmar artículos'.",
"Si estás pagando un salario, el día 8 de cada mes aparecerá una ventana preguntándote si quieres pagar a la tripulación. Si eliges no pagar, la moral de la tripulación bajará. Bajará menos si tienes la ahabilidad 'Voluntad de hierro'. Si la moral de la tripulación baja demasiado, se amotinarán, y eso es algo que no quieres que pase. Con un salario, la moral será mas estable, pero no tan alta como puede llegar a ser si has firmado artículos para repartir el botín.",
"Para 'Firmar artículos' con tu tripulación y oficiales, tendrás que dividir el botín. Puedes firmar artículos usando la 'Pantalla de estado de personaje' (F2), yendo a la pestaña 'Barco' y haciendo clic en el icono de la tripulación. También puedes hablar con cualquier miembro de tu tripulación a bordo de tu barco, o con cualquier prestamista cuando estés en tierra. Cuando quieras dividir el botín regresa al prestamista y dile que quieres dividir el botín; él te explicará qué hacer\n Si firmas artículos, tendrás que dividir el botín para pagar a tu tripulación y mantenerla contenta. Al dividir el botín, podrás subir la moral más que con la opcion de 'Salario', pero será más difícil mantenerla alta. Digamos que si te pierde la codicia y ganas mucho dinero, pero no lo compartes con tu tripulación, se te hará mas difícil mantener su moral alta; un capitan demasiado codicioso siempre acaba con una tripulación rebelde.",
"La navegación directa es simple si tienes el equipo adecuado y un buen sentido de la orientación. El significado de 'Navegación Directa' es que ahora se puede navegar de una isla a otra sin abandonar la vista de navegación 3D. Ya no hay necesidad de salir al mapa del mundo para navegar de isla en isla\n Sin embargo, utilizar el mapa del mundo será más rápido que usar la navegación en 3D'. No obstante, la navegación directa te da la oportunidad de disfrutar de las vistas mientras navegas directamente de una isla a otra. Puedes encontrar algún cargamento o tesoro flotante a lo largo del camino, o incluso encontrar otros barcos\n Sin una brújula, será difícil encontrar tu rumbo, a menos que seas un viejo lobo de mar con experiencia como yo. Ten en cuenta que cada hora que pasa en el modo de navegación 3D añadirá un día a tu viaje. Si encuentras tu viaje demasiado largo, puedes usar la tecla 'Acelerar el tiempo' para hacer que el tiempo corra más rápido.",
"La 'Moral' de tu tripulación es muy importante. Si la moral está alta, tu tripulación tendrá mejor rendimiento; si la moral está baja, su rendimiento será bajo, y tendrás que afrontar la posibilidad de un motín si la moral se hunde demasiado\n Hay maneras de mantener la moral alta, asegurándote de que hay suficiente comida y uficiente ron. Pagar a tu tripulación un salario te permitirá tener una moral media estable; firmar artículos permitirá que la moral sea más alta que con un salario, pero será más difícil mantenerla así\n También puedes aumentar la moral doblando las raciones de ron, ¡pero puede que se destae una pelea de borrachos!\n La moral bajará si te niegas a pagar a tu tripulación, si pierdes demasiados combates, si reduces la ración de comida o ron, si te quedas sin comida o ron durante el viaje, si contratas más tripulación en la taberna, si tienes mucho dinero de la tripulación en tu poder (mejor sería poner algo en el armero del barco) y si reclutas tripulación de un barco enemigo apresado.",
"La bandera puede ser útil si se usa correctamente. La bandera representa a diferentes naciones, como 'Inglaterra', 'Francia', 'Holanda', 'España', 'Portugal', 'Pirata' y tu propia 'bandera personal'. Cambiar la bandera de una nación a otra puede ser muy útil. Si Francia es tu enemiga y tienes que ir a un puerto francés, izar una bandera francesa te ayudará a entrar sin levantar sospechas\n Te recomiendo que, si tienes que izar otra bandera para entrar en un puerto hostil, lo hagas antes de estar a la vista de la isla. No querrás que los guardias de la ciudad o del fuerte te pillen en el momento de cambiar de bandera, ¿verdad? Sé consciente de tu 'Fama'; cuanto más fama tengas, más difícil será engañar al enemigo. Ser popular tiene cosas buenas y cosas malas, supongo\n También puedes fingir que eres un barco francés navegando con bandera francesa y acercarte a un barco francés sin que sospeche de ti, para entonces izar tu verdadera bandera y enfrentarte a tu enemigo.",
"Hasta otra, capitán. Espero que te vaya bien surcando el Caribe sin mí.",
"Claro, #sname#, Espero que seas feliz en tierra firme.",
"¿Necesitas mi consejo, capitán?",
"Te he llamado porque, como seguramente ya sabrás, planeo dejar atrás esta vida de lobo de mar y retirarme en esta isla. Por lo tanto, como entiendo y apoyo de todo corazón tus aspiraciones, he decidido concederte un barco propio. Toma el mando de ese ",
"que apresamos recientemente. No lo necesito y hasta le puse el nombre de '",
"' para darte una alegría.",
"Oh, cielos... ¡Ese barco no! Esperaba obtener el mando de tu ",
"Excelente, justo lo que necesitábamos para colarnos bajo las narices de ese escuadrón #senemy# que vimos. Estoy seguro de que la tormenta que se avecina no será para tanto, ¡asi que me voy! Buena suerte.",
"¿Qué dijiste? No lo he oído.",
"Gracias, muchas gracias... ¡Cuidaré de este barco como si estuviera hecho por mis propias manos!",
"#sname#, me gustaria darte las gracias por todo y desearte suerte en tierra firme. Ahora me gustaria visitar la ciudad.",
"Para tener un inicio más fácil, puedes tomar cosas de ese cofre, encontrarás armas y un catalejo. También puedes llvarte todo lo demás, incluso el dinero que encuentres alli.",
"Puedes ir a la ciudad si lo deseas; tengo algunas cosas que hacer aquí. Nos encontraremos en la taberna local.",
"Hola, capitán. Una carta para ti.",			//240
"Muy bien, #sname#. (¡SÍ! La primera carta que he recibido nunca.)",	//241
};