string DLG_TEXT[82] = {
"Hola, ",
".",
"Es un placer conocerte. Mi nombre es ",
".",
"Me alegro de verte, ",
". Me llamo ",
"Marc Blacque",
"Marc Blacque",
".",
"Marc Blacque",
", ¿eh? Conozco una familia con ese nombre. Viven en #sFalaise de Fleur#.",
"Tu nombre me resulta muy familiar, pero no puedo recordar por qué. Lamento no tener tiempo para averiguar más. En otra ocasión, tal vez.",
"¡¿Los conoces?! ¿Están bien?",
"Entonces, estás relacionado con ellos. Me lo imaginaba. ¿Eres el hijo que desapareció hace varios años?",
"Sí, soy yo. Pero, por favor, ",
", dime cómo están.",
"Me temo que tengo malas noticias para ti. Tu hermana ha muerto, y tu padre se volvió loco de pena cuando te perdió.",
"Me temo que tengo malas noticias para ti. Tu padre se volvió loco de pena cuando te perdió.",
"Rachel Blacque",
"... ¡No! ¿Cómo sucedió? ¡Dime la verdad, por favor!",
"Tu hermana fue asesinada por un trabajador portuario. En cuanto a tu padre, está vivo pero a las puertas de la muerte.",
"¿Cómo puede ser esto? Mi familia me necesita y no puedo ayudarlos.",
"¿Por qué no puedes ayudarlos? ¿Por qué les has hecho creer que estabas desaparecido todos estos años?",
"Es una historia muy larga, ",
".",
"Lo siento, no tengo tiempo para historias largas. Tal vez te vea más tarde.",
"No voy a ir a ninguna parte. Cuéntame tu historia.",
"Hace cinco años, tenía mi propio barco mercante. No era muy grande, una típica balandra, pero gané un buen dinero transportando mercancías por todo el archipiélago\n Entonces, emnpezaron los problemas: mi barco cayó en manos de piratas y a mí me vendieron como esclavo. ETrabajé en las plantaciones casi cinco años hasta que logré escapar..., pero me atraparon. Iban a azotarme hasta la muerte como ejemplo para los demás, pero #sThomas O'Reily# pagó mi rescate \n Naturalmente, no pude enviar noticias a mis parientes mientras era esclavo. Y desde que #sO'Reily# me liberó, ha estallado la guerra entre #snationR# y #snationF#\n Así que te puedes imaginar por qué no he podido mandar ninguna carta a mi familia...",
"Yo puedo entregar tu carta.",
"Puedes hacer algo mejor que una carta. Puedo llevarte con ellos.",
"Deberías aprender a contar historias más cortas. Tengo que irme.",
"¡Oh, muchas gracias! Tómala, por favor; la escribí en cuanto #sThomas# me compró, y he estado esperando una oportunidad para enviarla.",
"Muy bien, le daré esta carta a tu familia tan pronto como pase por #sFalaise de Fleur#.",
"Espera un segundo: ¿qué gano yo con este acto de bondad?",
"Dile a mi padre que estoy bien, que podré pagar mi rescate muy pronto y volveré con él.",
"Adiós.",
"Acabo de ser liberado de años de esclavitud. ¡No tengo nada de dinero!",
"Una pena. Adiós.",
"No, por supuesto que no. Dame tu carta de todos modos, la entregaré gratis.",
"Eres muy amable, ",
", pero no puedo ir a casa hasta que pague mi rescate de 3000 piezas de oro a #sThomas#\n De momento, solo he ahorrado 500.",
"Te ayudaría si pudiera permitírmelo. Tal vez la próxima vez.",
"Eso no es problema. Pagaré el resto del dinero y te llevaré a casa.",
"¡Oh, gracias!",
"No me lo agradezcas hasta que llegues a casa de una pieza. Ahora, dime dónde puedo encontrar a #sThomas#.",
"No es difícil localizarlo. Es el dueño de la tienda, aquí en la ciudad.",
"Bien. Dame tus 500 piezas de oro y espérame aqui.",
", ",
". ¿Hablaste con #sThomas#?",
"Todavía no. Volveré cuando lo haya hecho.",
", ",
". ¿Hablaste con #sThomas#?",
"Sí. Pero, ya sabes... Se negó a dejarte ir. Hasta la vista...",
", ",
". ¿Hablaste con #sThomas#?",
"Sí. Ya eres libre de irte. Mi barco está en el puerto., ",
". Te esperaré allí.",
".",
"Le di la carta a tu padre. Le ha levantado el ánimo de forma casi milagrosa.",
".",
"Ahora no, tengo mucho que hacer.",
"Puedo entregar tu carta.",
"Puedo ayudarte a volver con tu familia.",
"¡Oh, gracias por tu ayuda, ",
"!",
"¡Muchas gracias por tu ayuda, ",
"! Dios te dio un corazón amable y generoso.",
"Déjame darte las gracias, ",
", por todo lo que has hecho por mí.",
"Ni lo menciones. Me alegra poder ayudar.",
"¡Espera! ¿Y el dinero que te di?",
"Oh, sí, aquí está. Toma.",
"¿Qué dinero?",
"Te estoy agradecido por levantar este gran peso de mi corazón.",
"De nada, por supuesto. Hasta la vista.",
"Puedo ayudarte a volver con tu familia.",
"Oye, ¿te has olvidado? ¡Te di 500 piezas de oro!",
"Debes haberme confundido con otra persona. ¡Hasta la vista!",
"Capitán, tengo una petición... Necesito trabajo. Si tú quisieras aceptarme...",
"¿Entonces, tu experiencia no ha disminuido tu amor por la mar? Sí, puedo ofrecerte un puesto como oficial.",
"Lo siento #sMarc#, creo que deberías quedarte aquí, en tierra, y cuidar a tu hermana y a tu padre... Necesitan un hombre para protegerlos."
"Hace cinco años, tenía mi propio barco mercante. No era muy grande, una típica balandra, pero gané un buen dinero transportando mercancías por todo el archipiélago\n Entonces, emnpezaron los problemas: mi barco cayó en manos de piratas y a mí me vendieron como esclavo. ETrabajé en las plantaciones casi cinco años hasta que logré escapar..., pero me atraparon. Iban a azotarme hasta la muerte como ejemplo para los demás, pero #sThomas O'Reily# pagó mi rescate \n Naturalmente, no pude enviar noticias a mis parientes mientras era esclavo. Y desde que #sO'Reily# me liberó, ha habido muchos ataques piratas contra cualquier barco #snation#\n Así que te puedes imaginar por qué no he podido mandar ninguna carta a mi familia...",
};
