string DLG_TEXT[81] = {
"Saludar, ",
".",
"Encantado de conocerte. Mi nombre es ",
".",
"Me alegro de verte, ",
". Mi nombre es ",
"Marc Blacque",
"Marc Blacque",
".",
"Marc Blacque",
" Conozco una familia con ese nombre-viven en #sFalaise de Fleur#.",
"Tu nombre me parece muy familiar, pero no puedo pensar por que! Lamento no tener tiempo para averiguar mas. En otra ocasion, tal vez.",
"Los conoces?! Estan bien?",
"Entonces, estas relacionado con ellos. Me lo imaginaba. Eres el hijo que desaparecio hace varios anos?",
"Si, soy yo. Pero, por favor, ",
", dime como estan.",
"Me temo que tengo malas noticias para ti. Tu hermana ha muerto, y tu padre se volvio loco de pena cuando te perdio.",
"Me temo que tengo malas noticias para ti. Tu padre se volvio loco de pena cuando te perdio.",
"Rachel Blacque",
"! No! Como sucedio? Dime la verdad, por favor!",
"Tu hermana fue asesinada por un trabajador portuario. En cuanto a tu padre, esta vivo pero a la puerta de la muerte.",
"Como puede ser esto? Mi familia me necesita mucho, y no puedo ayudarlos en lo absoluto.",
"Por que no puedes ayudarlos ahora? Por que les has hecho creer que estabas perdido todos estos anos?",
"Esa es una historia muy larga, ",
".",
"Lo siento, no tengo tiempo para historias largas. Tal vez te vea mas tarde.",
"No voy a ninguna parte. Cuentame tu historia.",
"Hace cinco anos, tenia mi propio barco mercante. No era muy grande, solo su promedio de caida, pero hice bastante buen dinero la entrega de bienes en todo el archipielago. \nThen entonces me encontre con problemas - mi barco cayo en manos de piratas, y me vendieron como un esclavo. Habia estado trabajando en las plantaciones durante casi cinco anos cuando finalmente logre torre...pero me atraparon. Los diablos iban a atacar a mi a la muerte como un ejemplo para los demas, pero afortunadamente me fue rescatado por Thomas O'Reily. naturalmente, no podia enviar noticias a mis parientes mientras estaba esclavizada. Y desde Que O'Reily me libero, ha habido una guerra entre Inglaterra y Francia. \nSo, usted puede ver por que no he sido capaz de obtener una nota a traves de mi familia...",
"Puedo entregar tu carta.",
"Puedes hacerlo mejor que una nota. Puedo llevarte hasta ellos.",
"Deberias aprender a contar historias mas cortas. Tengo que irme.",
"Oh, muchas gracias! Tomelo, por favor-lo escribi tan pronto Thomas me compro, y he estado esperando que podria enviar con alguien.",
"Muy bien, le dare esta carta a tu familia tan pronto como este de vuelta en #sFalaise de Fleur#.",
"Espera un segundo - ?que consigo por mi bondad?",
"Dile a mi padre que estoy bien, y me voy a rescatar muy pronto y volvere con el.",
"Despedida.",
"Acabo de ser liberado de anos de esclavitud. !No tengo nada de dinero!",
"Siento oir eso. Despedir.",
"No, por supuesto que no. Dame tu carta de todos modos, la entregare gratis.",
"Eres muy amable, ",
", pero no puedo ir a casa hasta que pague mi rescate de 3000 dolares a Thomas. \nSo mucho, he guardado solo 500.",
"Te ayudaria si pudiera permitirmelo. Tal vez la proxima vez.",
"Eso no es un problema. Pagare el resto del dinero y te llevare a casa.",
"Oh, gracias!",
"No me lo agradezcas hasta que llegues a casa de una pieza. Ahora, dime donde puedo encontrar a Thomas.",
"No es dificil de localizar. Es el dueno de la tienda aqui en la ciudad.",
"Bueno. Dame tus 500 monedas y Esperame aqui.",
", ",
". Hablaste con Thomas?",
"Todavia no. Volvere cuando lo haya hecho.",
", ",
". Hablaste con Thomas?",
"Lo hice. Pero, ya sabes...se nego a dejarte ir. Hasta la vista...",
", ",
". Hablaste con Thomas?",
"Si. Ahora eres libre de irte. Mi barco esta en puerto., ",
". Te esperare alli.",
".",
"Le di la carta a tu padre. Sus espiritus han mejorado milagrosamente.",
".",
"Ahora no , estoy muy ocupado.",
"Puedo entregar la carta por TI.",
"Puedo ayudarte a volver con tu familia.",
"Oh, gracias por su ayuda, ",
"!",
"Muchas gracias por tu ayuda, ",
"! Dios te dio un corazon amable y generoso.",
"Dejame agradecerte, ",
", por lo que hiciste por mi.",
"Ni lo menciones. Estoy feliz de poder ayudar.",
"Espera! ?Y el dinero que te di?",
"Oh, si, aqui esta. Tomala.",
"Que dinero?",
"Te estoy agradecido por levantar este gran peso de mi corazon.",
"De nada, por supuesto. Hasta la vista.",
"Puedo ayudarte a volver con tu familia.",
"Oye, te Olvidaste?! !Te di 500 oro!",
"Debes haberme confundido con otra persona. !Hasta la vista!",
"Capitan, tengo una peticion... Necesito una posicion si estas dispuesto a aceptarme...",
"Tu experiencia no ha disminuido tu deseo por el mar, entonces? Si, puedo ofrecerte un puesto como oficial.",
"Lo siento Marc, creo que deberias quedarte aqui en tierra y cuidar a tu hermana y a tu padre... Necesitan un hombre para declararlos."

};
