string DLG_TEXT[52] = {
"Oye, este no es lugar para un civil, me oyes? Mira a tu alrededor, incluso las aves y las recupera han huido de esta zona de guerra. Solo las ratas florecen aqui.. en los cadaveres! !Sal de este campo de exterminio mientras tengas todas las piernas!",
"Que esta pasando aqui?",
"Y por que no te vas de aqui, detras de los muros de la ciudad? No seria mas seguro estar DETRAS de tu artilleria en vez de merodear por aqui en la zona de fuego?",
"No hay manera de salir de aqui?",
"Soy un mensajero de su comandante, y debo recibir un mensaje importante a traves de las lineas enemigas. Tienes que despejarme el camino!",
"Ratas? Ratas! Seguire el ejemplo de las recupera antes de que haya otro ataque. Como ese que se esta formando, por ejemplo..",
"No has oido que los holandeses nos sitian? Todos nuestros intentos de torre han flaqueado en el fuego de sus siegeworks, y sus soldados y geuzen matan a todos los que tratan de colarse a traves de sus lineas. eso es.. CASI todo el mundo: de vez en cuando algun valiente y diab mensajero consigue a traves... uhh.. UF! ?Ves esa partida de caza holandesa reuniendose en su campamento? Parece que los Holandeses piensan que eres otro mensajero..",
"Yo? No, eso es un malentendido! No tienes que cazarme, me oyes...",
"Me lo estas diciendo! Dile eso a nuestro comandante! En sus siguientes el nos ordeno a escaramuzas aqui: mantener a sus exploradores y mentores lejos de nuestras fortificaciones \nsupport mensajeros que tratan de colarse a traves de las lineas, acosar el campo de sitio Holandes con los ataques de atropello y fuga.. A.. Un ataque?? ALARMA! !Los Holandeses atacan!",
"Umm.. Golpear o correr, esa es ahora la pregunta...",
"Solo una muy estrecha y peligrosa: usted debe evadir las patrullas Holandesas y geuzen. Pero el peor peligro es la artilleria holandesa en las fortificaciones de campana al lado de su campamento. \nHave una mirada a sus posiciones... Damme, ?que esta pasando ahi?. Mucha actividad.. Un ataque?? ALARMA! !Los Holandeses atacan!",
"Podria ser esa la manera de salir de aqui?",
"Oh, genial, otro intento de fuga suicida? Suspira bien, NO se puede evitar, ordenes son ordenes. Muy bien, vamos a fingir un ataque, los holandeses seguro como el infierno contraataque, un monton de buenos hombres moriran, y usted PODRIA conseguir a traves si explota la confusion general.",
"Vamos, no te quejes, asi es la vida en el ejercito: 99 por ciento de espera aburrida y uno por ciento de confusion sangrienta. Vamos entonces.",
"DLG_TEXT[14]",
"DLG_TEXT[15]",
"DLG_TEXT[16]",
"DLG_TEXT[17]",
"DLG_TEXT[18]",
"DLG_TEXT[19]",
"DLG_TEXT[20]",
"DLG_TEXT[21]",
"DLG_TEXT[22]",
"DLG_TEXT[23]",
"DLG_TEXT[24]",
"DLG_TEXT[25]",
"DLG_TEXT[26]",
"DLG_TEXT[27]",
"DLG_TEXT[28]",
"DLG_TEXT[29]",
"DLG_TEXT[30]",
"DLG_TEXT[31]",
"DLG_TEXT[32]",
"DLG_TEXT[33]",
"DLG_TEXT[34]",
"DLG_TEXT[35]",
"DLG_TEXT[36]",
"DLG_TEXT[37]",
"DLG_TEXT[38]",
"DLG_TEXT[39]",
"DLG_TEXT[40]",
"DLG_TEXT[41]",
"DLG_TEXT[42]",
"DLG_TEXT[43]",
"DLG_TEXT[44]",
"DLG_TEXT[45]",
"DLG_TEXT[46]",
"DLG_TEXT[47]",
"DLG_TEXT[48]",
"DLG_TEXT[49]",
"DLG_TEXT[50]",
"DLG_TEXT[51]",

};