string DLG_TEXT[89] = {
"Pie Iesu Domine... Dona eis requiem. *GOLPE*. (El monje se golpea la frente con un pesado libro en un acto de penitencia) ¿Eh? ¡No interrumpas mi procesión individual!...",
"Por favor, perdona que te lo diga, pero no pareces el típico monje...",
"Lo siento, padre, por favor acepta mis disculpas y estas 100 piezas de oro para los pobres del archipiélago.",
"Hum, ¿y qué aspecto debería tener el típico monje?",
"Algo menos seguro de sí mismo, un poco más suplicante, y sin duda mucho menos peligroso.",
"No lo sé, pero... Bueno, pensé que eras un saco de patatas andante, ya sabes, con esa capa que parece un saco y todo eso. Tu cabeza parecía una gran patata podrida y comida de gusanos.",
"¡Tú no eres un monje! ¡Eres un espía! ¡Tal vez incluso un lunático haciéndose pasar por un saco de patatas! ¿No deberías estar en una casa de locos?",
"Ha sido agradable hablar contigo, pero ahora tengo que irme. Tal vez nos reencontremos cuando tus argumentos sean un poco más específicos...",
"Adiós, padre, o lo que quiera que seas...",
"Ah, otra vez tú. ¿Tienes otra respuesta para mí? ¿Qué aspecto debería tener un monje?",
"No sé lo que eres, pero no eres como los otros monjes que conozco, no puedo quitarme esta sensación de que eres demasiado tonto.",
"¿Espía? ¡Espía! Soy un monje, vivo una vida piadosa, obedezco a mis mayores, rezo mis oraciones y soy casi completamente casto. ¡¡Por favor, cierra la &$@&$ boca, pirata de &$@&$!!",
"Está bien, cálmate. No quiero tener ningún problema. Me marcho.",
"Oye, estás desarmado. ¿No deberías tener más cuidado al hablar asi con gente armada?",
"Ah, otra vez tú. ¿No has aprendido la lección?",
"Por favor, acepta mis disculpas. Fuiste muy amable al dejarme vivir. Ningún espia lo habría hecho.",
"Está bien. Aquí están sus armas. Preguntaré de nuevo: ¿qué aspecto debería tener un monje?",
"¿Quien ha dicho que estoy desarmado?",
"¡No veo ningún arma!",
"Y ahora yo tampoco veo las tuyas. Supongo que esta es una lección que tienes que aprender: nunca juzgues a un hombre basándote solo en su apariencias.",
"Ooh... ¿Cómo has hecho eso? ¿Dónde están mis armas?",
"Interesante. ¿Puede ser? Posiblemente. Ahora te haré otra pregunta: ¿qué es mas fuerte: una buena espada o una pluma?",
"La espada. ¿Alguna vez has intentado luchar contra una espada agitando una pluma?",
"La pluma. Quizás no en una pelea, pero a largo plazo, una pluma puede matar a más hombres que todas las espadas juntas.",
"Ninguna de las dos; depende de la mente que domina la espada o la pluma.",
"¡Felicidades! Estoy seguro de que ganarás muchas batallas con tu espada, pero al final perderás, porque el que a hierro mata, a hierro muere.",
"No entiendo lo que estás diciendo. Me marcho...",
"¿Qué? ¿Has pasado algún tiempo pensando en mi pregunta? ¡Muy bien! Vamos a escuchar tu respuesta: ¿qué es más fuerte: una buena espada o una pluma?",
"No está mal, pero entonces, ¿por qué llevas una espada contigo y no una pluma? No estoy seguro de si esa es realmente tu respuesta.",
"Tambien quiero sobrevivir a corto plazo. Adiós..., maldito saco de patatas meapilas.",
"Te crees muy inteligente, ¿no? ¿Puedes probar que lo eres realmente?",
"Eso espero. ¿Qué tienes en mente?",
"Te ofrezco estas tres reliquias, cada una con poderes especiales, pero todas con una gran carga... ",
"Por favor, sé un poco mas especifico.",
"Si tomas una no podrás salir del archipiélago y volver a dónde lo dejaste hasta que no hayas encontrado asilo en terreno consagrado o hasta que se la devuelvas a un miembro de mi orden.",
"¿Y los poderes?",
"¡Vamos a ver si eres tan inteligente! ¡Tú eliges! Y se me han acabado las Santas Granadas de Antioquía, así que no te molestes en preguntar.",
"Me llevaré la cruz que aumenta mis habilidades de combate.",
"Soy demasiado débil para una vida de aventuras, voy a llevarme la cruz que duplica mis puntos de salud.",
"¿La tercera cruz me ayudará en el comercio, ya sea lícito o ilícito? ¡La necesito!",
"La carga es demasiado pesada, y yo estaba buscando una Santa Granada de Antioquía. Aparentemente, no te quedan.",
"Si alguna vez sientes la necesidad de salir del archipiélago y ser capaz de continuar donde lo dejaste, devuelve la reliquia a un miembro de mi orden ",
"Seguro que lo encontraré cuando quiera salir del archipiélago. ¡Gracias y adiós!",
"Vuelve si cambias de opinión. O si la carga se vuelve demasiado pesada, siempre puedes tratar de destruirla en los fuegos de cierto Monte del Destino; eso también funcionaría. ",
"Eres muy amable conmigo. ¡Adiós!",
"Otra vez tú. ¿Quieres aceptar el desafío? ¡Veremos si tu ment ees capaz de dominar los poderes sabiamente! ¡Tú eliges!",
"Mi orden me habló de ti. ¿Quieres aceptar el desafío? ¡Veremos si tu ment ees capaz de dominar los poderes sabiamente! ¡Tú eliges!",
"Siento el aura de la pesada carga que llevas. Es difícil cargar con una de nuestras reliquias, ¿verdad? ¿Deseas renunciar a la cruz para ser capaz de salir del archipiélago y continuar después donde lo dejaste? ",
"Sí, es hora de que me vaya, pero... ¡VOLVERÉ!",
"No, continuaré llevando la carga... ¡y disfrutando de sus poderes!",
"Siento el aura de la pesada carga que llevas. ¿Quieres librarte de ella? Tienes que encontrar al miembro de mi orden... ",
"¡Espero sobrevivir hasta entonces!",
"Si alguna vez quieres aceptar el desafío de nuevo, vuelve a mí u otro miembro de mi orden.",
"¡No nos corresponde a nosotros decidir cuál será el futuro! Tal vez nos volvamos a ver, tal vez no.",
"¡Aceptaré el desafio de nuevo, cuando regrese!",
"La carga es demasiado para mí, no creo que nos volvamos a encontrar. ¡Adiós!",
"¡Qué sorpresa! ¡Qué sorpresa! Capitán ",
"¡Conozco esa voz! Lord Beckett... eres tú, ¿verdad?",
"Baja la voz. Hay demasiados oídos atentos alrededor de este lugar. Siéntate. Siéntate y hablaremos.",
"Bien, pero creo que me debes una explicación. ¿Quién eres? He conocido al verdadero Lord Beckett en la residencia del gobernador, así que...",
"Sí. Pero me está costando muhco saber quién eres.",
"En primer lugar, soy Lord Beckett, o uno de ellos... Lord Cuthbert Ulysses Beckett.",
"¡Cuthbert! ¡Dijiste que te llamabas Cutler!",
"Ese es mi hermano, Lord Cutler Oswald Beckett.",
"Esto va muy despacio, milord... Supongo que debería llamarte así... ¿Qué está pasando aquí?",
"Está bien, está bien, capitán ",
"Te lo debo. Mi hermano y yo somos los hijos gemelos más jóvenes del duque de Middlesex. Nuestro hermano mayor heredará el título ducal, así que mi hermano y yo buscamos nuestra fortuna en el comercio.",
"¿Hay mas de vosotros? No estoy seguro de que debamos continuar esta conversación.",
"Paciencia, paciencia, mi querido amigo. Solo somos Culter y yo en estas aguas. Ambos trabajábamos para la Honorable Compañía de las Indias Orientales y las cosas fueron bien hasta que escuchamos una historia sobre el Cofre de Cortés. Llamó la atención de mi hermano y esta empeñado en encontrarlo.",
"¿Qué tiene eso de malo? Una caza del tesoro de vez en cuando nos viene bien a todos, ¿no?",
"Se ha convertido en una obsesión para él, hasta el punto de que está dispuesto a eliminar a cualquier persona a la que crea con posibilidades de estar más cerca del tesoro que él..., incluyéndome a mí. Y me estoy acercando, a juzgar por cierta información que he encontrado.",
"Te refieres a los documentos que he estado recibiendo para ti, ¿no? Tienen algo que ver, ¿verdad?",
"Eres un capitán muy inteligente, Que, por cierto, es por lo que te elegí en primer lugar. Te involucré para intentar frustrar los planes de mi hermano, y sí, los documentos son parte de un mapa del tesoro. Cuando esté completo, revelará la ubicacion del cofre.",
"Y hay cuatro partes..., ¿verdad, milord?",
"Tan agudo como siempre, capitán. Sí, cuatro partes. Creo que tú tienes una y yo tengo otra, así que estamos a mitad de camino. Te daré mi parte, aquí está. Creo que los hombres de mi hermano están en mi camino, de ahí el disfraz, por lo que el mapa no estará seguro conmigo. Puedes devolvérmelo cuando nos volvamos a ver. Mantenlo a salvo.",
"¿Volvernos a ver, milord? ¿Dónde y cuándo será eso?",
"No te preocupes, te encontraré. Estoy seguro de que tienes otras cosas que hacer. Así que me despido por el momento. Capitán, espero reunirme con alguien aquí. Mantén los documentos a salvo. Mientras tanto, volveré a mi disfraz.",
"Esto... Sí, milord... Adiós, por el momento.",
"Esto está mejor, ahora podremos ver a cualquiera que se acerque.",
"Puede ser, pero todavía necesito esa explicación.",
"Volvemos a encontrarnos, milord. Tu voz se está volviendo bastante familiar. ¿Qué haces en esta isla?",
"Vine a recoger algunos ídolos, pero creo que tú te me has adelantado. Así que pense en sentarme aquí y ver quién iba y venía.",
"¡Ah! La información de Su Señoría está tan al día como siempre.",
"Así, es, así es. Pero vayamos al grano. Es hora de demostrar nuestra confianza mutua. Sé que mi hermano te envió para conseguir los ídolos, y necesito estropear sus planes. Así que, capitán, déjame ver el cargamento de ídolos, solo necesito saber qué hay ahí antes de que él; eso le quitará el viento a sus velas.",
"No sé, milord. Eso suena muy arriesgado... para mí.",
"¿Cómo? Él nunca sabrá que alguien ha echado un vistazo. Tengo la sensación de que una de las cajas está vacía, y quiero estar seguro.",
"Muy bien, milord, confiaré en ti. Echa un vistazo.",
"Gracias, capitán. Gracias. Esto alterará sus planes. Toma este dinero para cubrir tus molestias. Deberías irte, pero no tengas miedo de que nos volvamos a ver.",
"Estoy seguro de que lo haremos, señor. Estoy seguro de que lo haremos.",

};
