string DLG_TEXT[46] = {
"Qué calor hace hoy en esta ciudad, ¿eh?",
"Uh, sí.",
"¿Qué quieres? Si no te vas a unir a la diversión, no la interrumpas.",
"¿Crees que esto es divertido, bestia desalmada?",
"¿Diversión? Parece que estáis a punto de quemar vivo a alguien.",
"¿Así que has decidido no entrometerte? Sabia elección. ¡Ahora, vete de aquí!",
"¿Buscas problemas?",
"¡Te he dicho que te vayas, a menos que quieras unirte al viejo!",
"Mira, todos lo han visto, tú me ha golpeado primero.",
"¿Y qué? ¿Crees que alguien va a salir en tu defensa? Veo a muchos de mis amigos aquí; no veo a ninguno de los tuyos, visitante.",
"No necesitaré amigos cuando lleguen los soldados.",
"¿Ah, sí? ¿Y dónde están? ¿Qué te hace pensar que te ayudarán?",
"Lo más importante es que no nos molesten.",
"¡Claro, únete a nosotros! ¿Dónde si no podrías disfrutar de un espectáculo así?",
"¿Espectáculo? ¿Llamas espectáculo a ver a un hombre consumido por las llamas?",
"¡Ey, es mejor que trabajar en el puerto!",
"Sí, se nota que os aburrís mucho.",
"Sabes, gracias a gente como tú, esta colonia es considerada la más bárbara e incivilizada de todo el archipiélago. El gobernador ",
"Robert Christopher Silehard",
" en persona me lo ha dicho muchas veces.",
"Claro. Vosotros, bestias descerebradas, no sois capaces de inventaros ninguna otra forma de entreteneros.",
"Quizás pueda ofreceros algo más emocionante.",
"¿No preferiríais tomar un trago?... ¿o seis? Yo invito.",
"Ninguna persona con valor se quedaría mirando mientras queman vivo a un pobre anciano.",
"¿El propio gobernador? ¡Estás bromeando!",
"¿Te parece que estoy bromeando? Me envió aquí para ver lo mal que se habían puesto las cosas. No le va a gustar mi informe.",
"Estás mintiendo. ¿Adivinas lo que hacemos con los mentirosos por aquí? ¡Piérdete!",
"¿Y tú adivinas lo que hago yo con los hombres que me hablan de esa manera, escoria?",
"¡Está bien, está bien! No quiero problemas.",
"¿Informe? ¡No me hagas reír! ¡Todo el archipiélago está infestado de piratas!",
"Puede ser, pero no en todas las colonias se asan viejos a la parrilla. ¿Habéis informado a la Iglesia de vuestros planes de quemar a este hombre?",
"No es necesario. Creo que la Iglesia aprobará nuestras acciones.",
"Bueno, bueno. ¿Cómo dijiste que te llamabas?",
"Lo estás estropeando todo, ¿lo sabías? ¡Llévate al viejo y vete!",
"Ahora nos entendemos.",
"¿Sabes cuánto podemos beber mis amigos y yo? ¿Qué te hace pensar que puedes pagar por todos nosotros?",
"Estas 2000 piezas de oro dicen que puedo. Con esta cantidad, podréis beber hasta perder el sentido.",
"No, supongo que no tengo esa cantidad de dinero, ahora que lo mencionas. ¿Pero realmente os parece divertida esta ejecución?",
"¡Me parece bien! Pero tal vez deberíamos quemar al viejo primero...",
"Déjamelo a mi. Yo me ocuparé de él.",
"¿A quién llamas bestia?!",
"¿Así que eres sordo además de estúpido? Te llamo bestia a ti. Solo un animal podría encontrar este espectáculo entretenido.",
"¿Qué estás haciendo aquí? Quieres problemas? ¡Bueno, pues eso se puede arreglar fácilmente!",
"¿Qué? Te escondes detrás de tus amigos, ¿verdad? No debería sorprenderme, viniendo de la clase de cobarde que quemaría vivo a un viejo por diversión.",
"¿Crees que te tengo miedo? ¡Será un placer demostrarte lo contrario!",
"¡Adelante, animal!",

};