string DLG_TEXT[52] = {
"Cual es tu problema?, ",
" Quien esta detras de tu cabeza?",
"Que?",
"Saludar. Quienes sois?",
"Estoy ",
". Y necesito tu ayuda.",
"Lo siento, me equivoque.",
"Entonces, estas necesitando mi ayuda otra vez?",
"Esa es la vida de los piratas...",
"Gracias a Dios, no. Esa ayuda es demasiado cara.",
"Asi que usted esta en problemas con los piratas?",
"Efectivamente. Me gustaria normalizar las relaciones con mis hermanos de la costa.",
"Espa.",
"Portugal.",
"Holanda.",
"Francia.",
"Acabo de cambiar de opinion.",
"Necesita hacer las paces con nuestra comunidad?",
"Me temo que no entiendo.",
"Tal vez usted estaria interesado en mis servicios?",
"No se, ?que tienes para ofrecer?",
"Ayudo a la gente a resolver sus problemas.",
"Como Cuales?",
"Bien... Digamos que, durante sus viajes, usted participa de algunos barcos de piratas gordos. Antes de que te des cuenta, toda la comunidad pirata esta detras de tu cabeza, y la vida se vuelve dificil. Si vienes a mi, puedo ayudar a restaurar las relaciones entre tu y los piratas.\nOf supuesto, este Servicio no viene facilmente, y para mi para organizar tales cosas puede costar una cantidad considerable. Pero podras Turquia puertos y pueblos piratas y comerciar alli de nuevo..",
"Que garantias me da de que mis 'relations' seran restablecidas?",
"Soy el conc de #sGrand Turk#. Mis decisiones son respetadas.",
"Muy bien, me gustaria usar sus servicios.",
"Eso costara ",
" oro.",
"Acordar.",
"Demasiado.",
"Eso costara ",
" oro.",
"Acordar.",
"Esto es demasiado para mi. !Hasta luego!",
"Tratar. Eso costara ",
" oro.",
"Acordar.",
"Demasiado.",
"Eso costara ",
" oro.",
"Acordar.",
"Demasiado.",
"Eso costara ",
" oro.",
"Acordar.",
"Demasiado.",
"Disculpe, no tiene suficiente oro. No hay trato.",
"Argh! Tal vez regrese cuando tenga algo mas que ofrecer.",
"Ya pueden zarpar. Todo se arreglara lo antes posible.",
"Agradecer. Cuidar.",
"Eso no es todo.",

};