string DLG_TEXT[28] = {
"¿Qué puedo decirte? Solo trabajo aquí. Con quien deberías hablar es con mi jefe. Está allí, cerca del camino que lleva a la isla.",
"Gracias. Lo haré.",
"Hola, capitán. Supongo que eres tú, ¿verdad? Capitán ",
"Si, soy yo. ¿Qué puedo hacer por ti?",
"El capitán Boelen me dice que vas tras la flota francesa. Tengo un barcoe muy rápida que acabo de apresar y que podría interesarte.",
"¿En serio? Qué oportuno, podría interesarme (Pero no por lo que crees).",
"Ya me lo imaginaba. Tiene fama de ser el barco mas veloz del Caribe. Lo atrapé porque lo gobernaba un marinero de agua dulce. Una presa fácil, ni siquiera tuve que disparar una andanada, solo lo abordé. Así que no sufrió daños.",
"Ya veo. ¿Podemos ir a verlo?",
"Por supuesto. Está en el muelle.",
"No hay tiempo como el presente. Vamos a verlo.",
"Bueno, ahí está, capitán. Brillante como un botón. Estaba pensando que unas 200000 piezas de oro podrían hacerlo tuyo. Libre y despejado.",
"Tiene muy buen aspecto, no te lo discuto. ¿Pero quién es ese joven que tus hombres tienen vigilado en el muelle?",
"¡Oh! ¿Él? Es el marinero de agua dulce que intentaba gobernar el barco. Nos divertiremos con él más tarde. Bueno, capitán ¿qué pasa con el barco?",
"Bueno, parece un precio justo, pero creo que podríamos hacer algo mejor.",
"¿Eh? ¿Mejor? ¿Nosotros? ¿Qué quiere decir?",
"Mira, Oswald. Creo que ese muchacho es el hijo de un noble, lo que significa un gran rescate que, por supuesto, compartiríamos.",
"¡Oh! ¿Y cómo propones que hagamos eso? No podemos acercarnos a ningún puerto inglés sin que nos vuelen por los aires. El muchacho me dijo que robó el barco, así que lo estarán buscando.",
"Es tan fácil como hundir una bala de cañón, Oswald, así de fácil. Me lo llevo a #sTortuga# y se lo entrego a un amigo mío que se especializa en estos asuntos. Nos da una considerable suma y se encarga del acuerdo de rescate, añadiendo su comisión, por supuesto. Vuelvo aquí y lo divido contigo, menos el coste del barco que te debo, y ambos sacamos un buen provecho.",
"Sí, maravilloso. Debes pensar que tengo una bala de cañón por cerebro. Te doy el barco y zarpas hacia la puesta de sol. Ni en tus sueños, camarada. Piénsalo bien.",
"¡No, no! Oswald, no te estás enterando. Sería imposible para mí y para ese joven navegar en este barco a cualquier lugar más lejos que #sTortuga#. Totalmente imposible, especialmente con la flota francesa tan cerca. Y como tú mismo has dicho, no podemos acercarnos a ningún puerto inglés.",
"¡Hum! Estoy pensando... ¡Espera un minuto! ¿Por qué no voy contigo? Así puedo proteger mi inversión.",
"No sé si eso sería prudente, Oswald. Si te estuviera engañando, ¿no aprovecharía para matarte cuando te quedaras dormido? Esa no es forma de proteger tu inversión.",
"¡Ah! Es verdad, eso es lo que yo haría si te estuviera engañando. No, esa opción está descartada. ¿Pero cómo puedo asegurarme de que puedo confiar en ti?",
"Eso es fácil. Cuando el joven sea devuelto a su padre, se correrá la voz. Ya sabes cómo les gusta gritar a los cuatro vientos que han arrancado a alguien de las garras de los piratas. Así que si tellegan las noticias y yo no he vuelto, entonces sabrás que tienes que venir a por mí. Si no te enteras de nada, entonces sabrás que sigo trabajando en ello.",
"¡Si! Eso funcionaría, porque si son los ingleses los que hablan de ello, eso me diria que has zarpado del puerto. No tengo que oirlo de tu boca, y no tendrás forma de engañarme. ¡Sí, sí! Soy más listo de lo que pensaba. ¿Cuánto tiempo crees que tardarás?",
"¡Oh! Podría tardar un mes o dos, ya que tendré que esperar a que mi contacto regrese a #sTortuga#. A eso añádele otros dos o tres días para volver aquí.",
"Bien, aunque es un poco más de lo que esperaba, así que zarpa tan pronto como puedas. Esperaré aquí tu regreso con nuestro dinero. Ha sido un buen negocio.",
"Sí, no hay problema. Nos vamos inmediatamente. Me encanta cuando todo el mundo gana. Adiós.",

};