string DLG_TEXT[93] = {
"!querido cliente! Estoy ",
", propietario del astillero local.",
"Estoy ",
", capitan de la '",
".",
", ",
". ?Necesitas los servicios de mi astillero, ",
"?",
"Si, por favor amarre a mi nave.",
"No, solo quiero hablar.",
"No, solo estoy de visita.",
"Bueno, es un placer conocerte. Si eres capitan, mi astillero esta disponible para tu encargo.",
"Gran, ",
". Necesito tus conocimientos expertos.",
"Gracias. Pero primero, hablemos.",
"La proxima vez, tal vez. Tengo que irme.",
"?Que es exactamente lo que te interesa, ",
"?",
"Nada por ahora.",
"Sobre ese cofre que me pediste que llevara a #sRedmond#....",
"? Puedo ayudarte en algo mas, ",
"?",
"Si, necesito los servicios de su astillero.",
"Agradecer. Eso es todo. Adios!",
"?Que necesitas?",
"Necesito que tus artesanos revisen mi barco, aunque podria considerar solo cambiarlo y comprar uno nuevo.",
"Necesito instalar nuevas armas en mi nave.",
"Nada, gracias.",
"?Que estas pensando, ",
"? ?De verdad crees que los franceses me dejaran reparar tu barco bajo sus narices? !Han puesto guardias en cada resbalon de mi astillero!",
"Es una pena.",
"?Que ha pasado? ?Pasa algo?",
"Tenemos que escondernos. !Los soldados franceses nos persiguen!",
"?Por que?",
"No lo se. Mira, podemos discutirlo mas tarde. !Los soldados llegaran en cualquier momento!",
"Muy bien, te escondere. Y no te preocupes, los distraere de tu rastro si Nigeria aqui.",
"Agradecer.",
"Les mostre la puerta a los soldados. Asi que, ?tal vez ahora puedas letal que paso?",
"Parece el sospechoso frances ",
"Counterspy",
".",
"?Y han decidido cogerlo primero y hacer preguntas despues?",
"Ese parece ser el Tamano de la misma, si. Gracias por su ayuda.",
"Ni lo menciones. Tal vez podrias hacerme un favor a cambio. Necesito conseguir algo para #sRedmond#, pero solo levantare Pass si lo llevo yo mismo.",
"? Y esto es algo que no puedes enviar de la forma habitual?",
"No. El contenido de este cofre es extremadamente importante. No puedo confiar en un extrano con ella-pero confio en TI, ",
"\n es por eso que te pido que lo entregues a #sRedmond#, si estas dispuesto.",
"Despues de lo que has hecho por mi, ?como puedo negarme?",
"Agradecer. Por favor, lleva este cofre a ",
"Charles Windem",
" ",
"Charles Windem",
". Es el dueno de la taberna #sRedmond#. Dile que es de mi parte, y el lo entendera. Vientos justos para TI, ",
".",
"Y a TI. Hasta la vista.",
"?Si? Has entregado?",
"Me temo que no. Alguien se interpuso. O algo...cosa.",
"?Algo?!",
"Dos hombres que no pudieron ser asesinados con una espada.",
"!Dios Mio! Entonces es verdad...",
"?Que es verdad? ?Hay algo que quieras decirme?",
"Oh, no...no, no es nada. Es una pena que te hayan atacado....",
"Derramarlo, o derramar sangre. Haz tu eleccion.",
"!Espera! Te dire lo que se. Hay una historia sobre un pirata horrible. Saqueo y hundio barcos, no tuvo piedad.... Y un dia hizo algo tan terrible que Dios lo abandono para siempre. este pirata se convirtio en algo indescriptible...!los muertos vivientes! Dicen que el y su tripulacion todavia cazan y saquean barcos, pero ahora nadie puede esperar a vinculadas - porque no pueden ser asesinados! Se dice que esta buscando algo...monedas antiguas o tesoro perdido aqui en el archipielago.",
"Eso es una locura! Una historia para asustar a los ninos.",
"?Lo es? !Viste a esos piratas oscuros con tus propios ojos! Envie ese cofre a mi viejo enemigo., ",
"Charles Windem",
", en la creencia de que contenia el tesoro que buscaban. Esperaba que lo encontraran y lo mataran eventualmente. Tienes que creerme - !nunca pense que te alcanzarian primero!",
"?De donde sacaste ese cofre?",
"Un hombre me lo vendio. Me pidio muy poco a cambio y me prometio que podria librarme de mi antiguo rival simplemente enviandoselo.",
"? Donde puedo encontrar a este hombre?",
"El vive en #sisland_Falaise de Fleur#, cerca del puerto! Es con el con quien quieres hablar. !sabe mucho mas de ese cofre que yo!",
"Si no fuera un #sgender# de honor, te haria pagar por ponerme en tal peligro!",
"Me niego a comerciar con una persona de su reputacion y relaciones. Ahora salir, ",
", antes de que llame a los guardias.",
"Muy bien.",
"Muy bien, mi muelle junto al fuerte esta disponible para TI. Si quieres, le dire a mi capitan que remolque tu barco alli. Solo entonces puedo inspeccionar el dano y decirte cuanto tiempo y dinero me llevara.",
"MUELLE JUNTO AL FUERTE?? Uhh... Yo solo x que tengo... eeh... otro asunto urgente que debo atender primero. Despedir.",
"Despues de cerrar este dialogo, pulse ENTER para conversacion la interfaz de cambio de vela.",
"Salida",
"La gente dice que tienes un gran pedido. Supongo que necesita algunos suministros, entonces?",
"Si, de hecho estoy en necesidad de algunos suministros. La tienda esta toda agotada. ?Podrias ir a buscarme? ",
"Te pagare ",
"monedas de oro.",
"Soy tu hombre. Tendras esos suministros en poco tiempo.",
"Lo siento, no estoy interesado",
"Para mal, encontrare a alguien mas entonces",
"Parece que 'esa gente' esta tratando de enganarte o tal vez deberias preguntar mas. No tengo ninguna oferta......ojala lo hubiera hecho.",
"Te traje los materiales que necesitabas",
"Muchas gracias. Aqui esta tu dinero.",
"De nada",
"Alguien mas llego antes que tu asi que ya tengo todo lo que necesito. Tal vez la tienda quiere tu mercancia."
};