string DLG_TEXT[56] = {
"Hola, #saddr#. Que te trae al seno de la Iglesia? Has venido a confesarte o a hacer una donacion?",
"Tengo que hablar con usted, Padre.",
"Me gustaria hacer una donacion, Padre.",
"Solo echando un vistazo. Debo ir.", // 3
"Estoy escuchando, #saddr#.",
"No tengo ningun negocio contigo ahora.",
"Por supuesto, #saddr#. Cuanto quieres dar?",
"Lo siento, Padre, pero no puedo hacer una donacion ahora.",
"Me temo que 100 de oro es todo lo que puedo pagar ahora.",
"Pensaria que el Senor miraria amablemente en 1000 oro.",
"Lo estoy haciendo bien en estos dias, asi que voy a dar 5000 piastras de oro.",
"Es tu decision, #saddr#. Nunca es demasiado tarde para cambiar - y tenga en cuenta que todo se tendra en cuenta en el momento de su muerte.",
"Mi muerte esta todavia muy lejos, si Dios quiere! Hablemos de otra cosa.",
"Lo Siento, Padre. Me tengo que ir.",
"Te agradezco por tu regalo en el nombre de la Santa iglesia, #saddr#.",
"Necesito hablar con usted, Padre.",
"Lo siento, Padre, pero tengo que irme.",
"Te agradezco por tu regalo en el nombre de la Santa iglesia, #saddr#.",
"Necesito hablar con usted, Padre.",
"Lo siento, Padre, pero tengo que irme.",
"Te agradezco por tu regalo en el nombre de la Santa iglesia, #saddr#.",
"Necesito hablar con usted, Padre.",
"Lo siento, Padre, pero tengo que irme.", // 22
"Tengo miedo ",
"el oro es todo lo que puedo pagar ahora.",
"Creo que el Senor miraria amablemente ",
"piezas de oro.",
"Estoy bien estos dias, asi que voy a dar ",
"En este titulada dia, celebramos la Union de estas dos personas en Santo matrimonio. ",
", habeis venido aqui libremente y sin reservas para daros el uno al otro en matrimonio?",
"Si.",
"Ejem, (te Mira fijamente) Se honraran el uno al otro como marido y mujer por el resto de sus vidas?",
"Lo hare.",
"Va a aceptar amorosamente a los ninos de Dios, y a educarlos segun la ley de Cristo y de su Iglesia?",
"Er... si, lo hare.",
"Que el Senor bendiga estos anillos que este hombre y esta mujer estan a punto de dar los unos a los otros.",
"#sgroom#, ?tomas #sbride# para ser tu esposa? Prometes serle fiel en los buenos tiempos y en los malos, en la salud y en la enfermedad, amarla y honrarla todos los dias de tu vida?",
"Lo hago.",
"#sbride#, ?tomas a #sgroom# para ser tu esposo? ?Prometes serle fiel en los buenos tiempos y en los malos, en la enfermedad y en la salud, amarle y honrarle todos los dias de tu vida?",
"...",
"Cada uno ha declarado su consentimiento para entregarse al otro, y para recibir ese regalo con el amor en el cual es dado. Que el Senor bendiga y cuide a esta pareja que se ha Unido hoy aqui a su vista. Lo que Dios ha Unido, los hombres no deben dividirlo.",
"Arrr!",
"Quien eres y por que interrumpes estos procedimientos?",
"Ah, #svillain#. Si, Leo sobre ti. De hecho estabas casado con #sromance#, pero el matrimonio fue sin ",
"su",
"ella",
" consentimiento. El Santo Padre en Roma ha decretado que el matrimonio ha sido anulado y #sromance# es de nuevo libre para casarse.",
"No! No debe haber derramamiento de sangre en esta iglesia!",
"Entonces perdoname, padre, porque estoy a punto de pecar.",
"Que has hecho? Se ha derramado sangre. Este lugar sagrado esta profanado!",
"Queria que la lucha fuera, pero #svillain# no me dejo otra opcion.",
"Soy leal a Espana, pero soy leal a la iglesia primero. Y mi primera preocupacion es la Iglesia, Excelencia. No se puede realizar ningun otro estudio aqui hasta que este edificio haya sido reconstruido.",
"Lo eres... muy persuasivo, excelencia. Muy bien, entonces. Continuaremos. Er... donde estabamos?",
"Estabamos en parte a traves del intercambio de promesas, Padre.",
"Ah, si. Ejica. ",
" y ",
};
