string DLG_TEXT[56] = {
"Hola, #saddr#. ¿Qué te trae al seno de la Iglesia? ¿Has venido a confesarte o a hacer una donación?",
"Tengo que hablar contigo, padre.",
"Me gustaría hacer una donación, padre.",
"Solo estaba echando un vistazo. Debo irme.", // 3
"Te escucho, #saddr#.",
"No tengo ningún asunto que tratar contigo ahora mismo.",
"Por supuesto, #saddr#. ¿Cuánto quieres donar?",
"Lo siento, padre, pero no puedo hacer una donación ahora mismo.",
"Me temo que 100 piezas de oro es todo lo que puedo permitirme en este momento.",
"Creo que el Señor vería con agrado una donación de 1000 piezas de oro.",
"Me va bastante bien estos días, así que voy a dar 5000 de oro.",
"Es tu decisión, #saddr#. Nunca es demasiado tarde para cambiar. Y no olvides que tus buenas obras serán tenidas en cuenta en el momento de tu muerte.",
"¡Mi muerte aún está muy lejana, si Dios quiere! Hablemos de otra cosa.",
"Lo siento, padre. Me tengo que ir.",
"Te agradezco tu regalo en el nombre de la Santa Iglesia, #saddr#.",
"Necesito hablar contigo, padre.",
"Lo siento, padre, pero tengo que irme.",
"Te agradezco tu regalo en el nombre de la Santa Iglesia, #saddr#.",
"Necesito hablar contigo, padre.",
"Lo siento, padre, pero tengo que irme.",
"Te agradezco tu regalo en el nombre de la Santa Iglesia, #saddr#.",
"Necesito hablar contigo, padre.",
"Lo siento, padre, pero tengo que irme.", // 22
"Me temo que ",
" piezas de oro es todo lo que puedo pagar ahora.",
"Creo que el Señor vería con agrado una donación de ",
" piezas de oro.",
"Me va bastante bien estos días, así que voy a dar ",
"En este jubiloso día, celebramos la unión de estas dos personas en santo matrimonio. ",
", ¿habéis venido aquí libremente y sin reservas para daros el uno al otro en matrimonio?",
"Sí.",
"Ejem, (*te mira fijamente*) ¿Os honraréis el uno al otro como marido y mujer por el resto de vuestras vidas?",
"Lo hare.",
"¿Aceptaréis amorosamentea vuestros hijos como hijos de Dios, y los educaréis según la ley de Cristo y de su Iglesia?",
"Er... Sí, lo haré.",
"Que el Señor bendiga estos anillos que este hombre y esta mujer están a punto de intercambiarse.",
"#sgroom#, ¿quieres tomar a #sbride# para ser tu esposa? ¿Prometes serle fiel en los buenos tiempos y en los malos, en la salud y en la enfermedad, amarla y honrarla todos los dias de tu vida?",
"Sí, quiero.",
"#sbride#, ¿quieres tomar a #sgroom# para ser tu esposo? ¿Prometes serle fiel en los buenos tiempos y en los malos, en la enfermedad y en la salud, amarle y honrarle todos los dias de tu vida?",
"...",
"Ambos habéis declarado vuestro consentimiento para entregaros al otro, y para recibir ese regalo con el mismo amor con el que es entregado. Que el Señor bendiga y cuide a esta pareja que se ha unido hoy aquí ante su vista. Lo que Dios ha unido, que no lo separe el hombre.",
"¡Arrr!",
"¿Quién eres y por qué interrumpes esta ceremonia?",
"Ah, #svillain#. Sí, recuerdo haber leído sobre ti. De hecho, te habías casado con #sromance#, pero el matrimonio fue sin ",
"su",
"su",
" consentimiento. El Santo Padre de Roma ha decretado que el matrimonio ha sido anulado y #sromance# es de nuevo libre para casarse.",
"¡No! ¡No debe haber derramamiento de sangre en esta iglesia!",
"Entonces, perdóname, padre, porque estoy a punto de pecar.",
"¿Qué has hecho? Se ha derramado sangre. ¡Este lugar sagrado ha sido profanado!",
"Habría querido que la pelea ocurriera fuera, pero #svillain# no me dejó otra opción.",
"Soy leal a España, pero primero soy leal a la Iglesia. Y mi primera preocupación es la Iglesia, Excelencia. No se puede realizar ninguna otra ceremonia aquí hasta que este templo haya sido reconstruido.",
"Su Excelencia es... una persona muy persuasiva. Muy bien, entonces. Continuaremos. Ejem... ¿dónde estábamos?",
"Estábamos a mitad del intercambio de votos, padre.",
"Ah, sí. Ejem... ",
" y ",
};
