string DLG_TEXT[23] = {
"¡Movéos! ¡Despejad las calles!",
"...",
"¡Eh, tú! Tienes una pinta sospechosa. ¿Quién diablos eres? ¡Enséñame tus papeles!",
"¿Quién demonios eres? ¡Identifícate y que sea rápido!",
"¡Alto! ¡Nunca te he visto antes, pero tienes cara de pirata! ¿Puedes probar que no lo eres?",
"Soy ",
", y aquí están mi nombramiento y los papeles del barco para probarlo. ¿Te ha parecido lo bastante rápido, soldado?",
"¡Oh, sí, por supuesto, señor! Aquí, mi identificación está en esta bolsa, justo debajo de las 200 piezas de oro. *GUIÑO*",
"¡Si no desapareces de mi vista inmediatamente, te mostraré lo rápido que puede ser el filo de mi espada!",
"¡No te atrevas a volver a dirigirte a un superior de esa manera, esbirro insolente! ¿No me conoces? ¡Soy Inspector Real de los Regimientos Caribeños de Su Majestad, y acabo de llegar en el último barco para inspeccionar a las tropas destinadas aquí! ¡No me molestes más, o tendrás que explicarle a tu comandante por qué he faltado a mi cita con él!",
"Ah, si, la efigie en las monedas te identifica como alguien que se preocupa por los guardias mal pagados, ¡je, je!. Muy bien, te dejaré pasar, pero solo esta vez. ¡Y será mejor que te comportes!",
"¡Por supuesto! ¿Quien crees que soy? ¿Un pícaro sinvergüenza? *GUIÑO*",
"No me fío de ti! ¡ALARMA! ¡CONVOCAD A LA MILICIA!",
"¡Buen intento, pero no funcionará conmigo! ¡ALARMA! ¡Espia! ¡Dad la alarma!",
"¿Qué es esto? ¡ALARMA! ¡Pirata!",
"Parece que mis DESTREZAS no han sido suficiente para tener éxito. ¿O ha sido solo mala suerte?",
"Espero que mi esgrima tenga más éxito que mi charlatanería...",
"Hum..., esto... Ya veo. Perdón por haberte molestado, #ssir#. Adiós.",
"Muy bien, continúa, y que tengas una guardia tranquila.",
"¿No has leído 'Prohibido el paso' en la puerta? Esta es una fortificación militar de alto secreto, y solo los soldados de la Brigada Costera de élite pueden entrar. ¡Cualquier otro será considerado un espía! ¡Especialmente ciertos capitanes corsarios con pocos escrúpulos!",
"¿Firmar? Lo siento, no se leer. Y tengo una cita urgente con el inspector real..., quiero decir que soy el inspector y tengo...",
"¿Alguna orden, #ssir#?",
"Nada por ahora."

};
