string DLG_TEXT[125] = {
"Es agradable ver a una persona en este agujero olvidado Dios que viste bien. Mi nombre es ",
", y soy el dueño de este establecimiento.",
"¿Hablas de cómo visto, pero ni siquiera puedes mantener limpia esta pocilga? Bueno, ya veo lo buen tabernero que eres.",
"Por supuesto, como tú digas, ",
". ¿Cómo puedo ayudarte?",
"Necesito enrolar algunos marineros para mi tripulación.",
"Mi tripulación está desgastada por el combate y quiero enrolar a algunos marineros jóvenes e inexpertos que estén buscando trabajo.",
"Tengo una propuesta de negocios para ti.",
"¿Tienes una habitación libre? Me gustaría quedarme aquí un tiempo.",
"¿Tienes una habitación libre en esta pocilga?",
"No tengo más preguntas para ti. Adiós.",
"Ya sé todo lo que quería saber. Hasta la vista.",
"Entonces, hablemos de negocios. ¿Qué quieres?",
"Gracias, no. Necesito al piloto de Rheims.",
"Estoy buscando a una persona. Es una chica llamada ",
"Danielle",
"Danielle",
", ¿tal vez puedas decirme algo de ella?",
"Me gustaría confesar mis pecados, pero dicen que el sacerdote local está él mismo cargado de pecados. ¿Es eso cierto?",
"¿Sabes?, parece que te equivocaste con el sacerdote.",
"Ese holandés estaba loco, así que tuve que matarlo. ¿Averiguaste algo de la camarera?",
"Ese holandés se nego a hablar conmigo. ¿Te las has arreglado para sacar algo en claro de tus sirvientes?",
"Descubrí que esas cartas son realmente falsas. ¿Qué has descubierto tú?",
"Me gustaría conocer los detalles sobre la muerte de la persona llamada ",
"Giraldo Figuiera",
"Giraldo Figuiera",
".",
"Me gustaría saber si una fragata negra ha llegado al puerto.",
"Dime, ¿ha pasado por aquí últimamente un hombre llamado ",
"Blaze",
"Blaze",
"? Es un capitán. Es difícil no verlo.",
"Necesito dejar la ciudad, discretamente. ¿Tal vez puedas ayudarme a hacerlo? Por, digamos, ¿una moneda de oro?",
"Necesito información sobre un hombre. Siempre lleva un hábito rojo y se hace llamar 'Profesor'.",
"Necesito trabajo. ¿No conoces a algún niño rico en esta isla que tema viajar solo?",
"Nada por el momento.",
"Si es así, prefieren zarpar con menos escolta, ya lo sabes.",
"Sí, lo olvidé. De acuerdo, volveré más tarde, cuando tenga menos barcos, ¡ja, ja!",
"No quiero ayudarte. Has causado muchos problemas a mi país",
"Vaya, tenemos un patriota. Bien, adiós", 
"Tus manos están manchadas de sangre. No pensarás en serio que alguien viajaría contigo, ¿verdad?",
"Tienes razón, ¡todo el mundo me teme! ¡Ja, ja!",
"Llegas justo a tiempo. Un mercader estaba buscando una buena escolta con la que viajar. Deberías hablar con él. Aquí está, justo ahora está entrando en la taberna.",
"Eso haré.",
"No, no hay nadie así en este momento. Quizás la próxima vez.",
"Hum, entonces esperaré.",
"¡Ah! !Tendrás que ir a ver al alcaide de la prisión! Ese tipo fue arrestado hace unos días... Estaba incitando a la gente a la rebelión.",
"Bien, me has ayudado mucho.",
"Por cierto, un piloto vive no lejos de aquí. ¿Tal vez sea el que estás buscando?",
"¡Gracias! Creo que le haré una visita...",
"No lo creo. Pero si me pagas 50 monedas de oro...",
"Trato hecho. Aquá están tus monedas.",
"¡Eso es un robo!",
"Vamos a la trastienda, te daré un nuevo conjunto de ropa para que no te reconozcan.",
"¡Genial!",
"No recientemente. Suele aparecer por aquí de vez en cuando, pero ha pasado mucho tiempo desde la última vez que lo vi\n Dicen que se hundió con su barco durante esa tormenta que hubo hace una semana.",
"He oído eso...",
"¿Una fragata negra? Déjame pensar... No, estoy seguro de que no ha habido ninguna fragata negra en nuestro puerto\n Aunque conozco a un tipo que la ha visto antes.",
"¿Y bien? ¿Cómo puedo encontrar a esa persona?",
"Allí está, en la mesa más cercana. Si no me equivoco, su nombre es ",
"Balltesar Figueiredo",
"Balltesar Figueiredo",
".",
"Bien, iré a hablar con él.",
"Si, esa mujer confesó que nadie le había escrito nunca tales cartas y que dijo todas esas mentiras por orden del asistente del sacerdote.",
"Excelente, gracias. Tu ayuda ha sido inestimable.", // --Cat
"¡Te equivocas! Esa persona es inocente y todos esos rumores son infundados.",
"Bueno, ¿cómo aparecieron esas cartas, entonces?",
"Creo que son falsos. Vi al asistente del sacerdote hablando recientemente con un holandés llamado ",
"Yedam Kinne",
"Yedam Kinne",
"\n Todo el mundo sabe que, además de otras muchas cosas turbias que ese tipo puede hacer, también puede falsificar documentos y e imitar la letra de otros.",
"Hum...Bien, tratare de averiguar los detalles. Mientras tanto, deberías hablar con la camarera. Quizás también te diga algo importante.",
"¡Oh! Has venido a hablar con la persona correcta. Ese accidente ha sido discutido por muchas personas varias noches seguidas en mi casa.",
"Entonces, ¿qué sabes de la persona que lo mató?",
"Dicen que fue una chica loca la que lo hizo. Él era su amante o su rufián\n Dicen que es una chica hermosa y muy inteligente. ¡Incluso logró escapar de la prisión! ¿Te lo puedes imaginar? ¿Sabes por qué lo mató? Una estatuilla de oro fue encontrada en la casa del hombre asesinado, ¡y su peso era de unas 10 libras!\n Sería interesante saber de dónde sacó esa estatuilla, ¿eh!",
"Sí; por un lado, tuvo suerte de hacerse con esa estatuilla, pero, por otro lado, si no fuera por ella, aún estaría vivo. ¿Dónde está ahora? ¿Es posible echar un vistazo a ese tesoro?",
"!Ja! ¿Estás tratando de planear cómo hacerte con ella? ¡No serás capaz! El ídolo lo tiene el jefe de la guarnición, y no se lo dará a nadie\n Hubo tres tipos que trataron de meterse con él...; sus cabezas todavía cuelgan en las puertas de la ciudad.",
"Entonces, ¿dices que el ídolo está con el jefe de la guarnición? Eso es bueno.",
"¿Estás hablando del ",
"padre Jerald",
"padre Jerald",
"? ¡No escuches esas maledicencias, ",
"!\n Sí, a veces puede beber una copa o dos de vino, pero es y siempre ha sido un hombre muy devoto.\n Creo que puedes confesarte con él sin ningún miedo.",
"¡Oh! Gracias por despejar todas mis dudas sobre él.",
"Sí, he oído hablar de ella.",
"¡¿En serio?! ¿Qué es exactamente lo que has oído de ella? ¿Cuándo estuvo aquí por última vez?",
"Dame una moneda de oro, ",
", y te diré todo lo que sé.",
"Toma esta moneda.",
"¡Ja! Por ese dinero, yo te contaría cualquier cosa.",
"Ella estuvo aquí no mucho antes de la liberación de #sOxbay#, pero no sé quedó. La vi porque un trabajador intentó hacerle una proposicion deshonesta, pero ella lo puso en su lugar.",
"No sabes mucho. Dime, por favor, ¿ha oído algo sobre las tablillas de arcilla que se encontraron en las minas?",
"Págame una pieza de oro más, ",
", y te lo diré. ",
"¡Tacaño! Aquí está, tómala.",
"Eh, no, trataré de averiguarlo por mi cuenta.",
"¿Tablillas de arcilla, dices? Sí, sé algo de ellos. Había un tipo que vivió en mi casa hace varios años y se tomó muchas molestias por esas tablillas. No le dejaban llevárselas de las minas, así que trabajaba allí mismo y solía decir que las tablillas lo harían rico y famoso.",
"Ya veo. ¿Dónde está ahora?",
"Solo Dios lo sabe. Te estoy diciendo que no le dejaron llevarse esas tablillas de las minas, aunque no entiendo por qué. Así que, ese tipo se quedó sin dinero y se mudó de aquí y desde entonces no lo he vuelto a ver.",
"Muy bien, supongo que tendré que ir a las minas. ¿Dónde está ese lugar?",
"Debes salir de la ciudad y entonces verás las minas. Hay un faro detrás de ellas. Estoy seguro de que las encontrarás fácilmente.",
"Bien.",
"Normalmente, tengo muchos hombres aquí deseando embarcarse, pero ya es tarde. Empezarán a aparecer solo por la mañana\n ¿Por que no alquilas una habitación y los esperas?",
"Muy bien. ¿Tienes habitaciones libres?",
"No necesito una habitación ahora mismo. Cambiemos de tema.",
"Tengo habitaciones disponibles. ¿Cuánto tiempo vas a quedarte aquí?",
"Hasta mañana.",
"Hasta la noche.",
"Te costará 5 piezas de oro.",
"Aquí está tu dinero.",
"Por desgracia, parece que el lujo de dormir en una cama no es para mí y mi menguada bolsa. Dormiré en el salón de la taberna.",
"¿Alquilas una habitaciñon digna de un rey? No, gracias..., si ese es el precio, dormiré en el salón de la taberna.",
"Lo pensaré.",
"Te costará 5 piezas de oro.",
"Aquí está tu dinero.",
"Por desgracia, parece que el lujo de dormir en una cama no es para mí y mi menguada bolsa. Dormiré en el salón de la taberna.",
"¿Alquilas una habitaciñon digna de un rey? No, gracias..., si ese es el precio, dormiré en el salón de la taberna.",
"Lo pensaré.",
"¡Queridos parroquianos! ¡Por favor, detened este escándalo en mi taberna o llamaré a los guardias!",
"Muy bien. Ya me voy.",
"¿Recuerdas cuando me dijiste que hablara con el alcaide sobre un prisionero? Bueno, he ido y he matado a ese muegriento bastardo, así que, ¿qué debo hacer ahora?",
"Bueno, ya que el alcaide está muerto, digo que vayas y hables con el prisionero. No es que nadie vaya a detenerte.",
"Lo haré. Gracias.",
"¡Ah! Ese tipo fue arrestado hace unos días... Estaba incitando a la gente a rebelarse. Ya que el alcaide ha sido asesinado, te sugiero que vayas a la prisión y tengas una charla con el canalla.", 
};
