string DLG_TEXT[134] = {
"He oido que quieres verme. Entonces, que asuntos tienes conmigo?",
"Me gustaria ofrecer mis servicios.",
"Asi que eres el capitan de un barco. Como te llamas?",
"Mi nombre es ",
", capitan de la '",
".",
"Bien, voy a x su nombre. Que te trae por aqui?",
"Me gustaria hablar de negocios contigo.",
"Nada. Me voy, si me lo permite.",
"Puedes irte. Pero no desaparezcas por completo, es posible que tenga planes para ti.",
"Como tu dices, #saddr#.",
"Estoy escuchando. ?Que te trae por aqui?",
"Negocios #saddr#.",
"Me voy.",
"Entonces hablemos de negocios.",
"Estoy aqui en nombre de esas mujeres que estan junto a tu entrada.",
"Tu mision es un exito. Los ninos desaparecidos han sido devueltos a sus padres.",
"Quiero hablar de un hombre que encuentra el favor de su gracia.",
"Tu mision se ha cumplido, #saddr#.",
"No tengo nada que discutir contigo en este momento, #saddr#",
"Si, ya lo se, aqui esta tu recompensa. Espero que en el futuro pueda utilizarte.",
"En cualquier momento, #saddr#",
"Entonces, de quien quieres hablar?",
"Un bucanero, #sBernardo Gamboa#, #saddr#.",
"",
"",
"Ah. Ese hombre?! Y que quieres que diga? Por lo que se, su reputacion es impecable...",
"Estarias equivocado. Por lo que se, secuestro a una chica de tu pueblo.",
"Ah, ah, ah. ?Estas seguro de eso? No quiero insultarlo injustamente.",
"Si no te importa, investigare esto en privado. Nadie sabra de tu participacion. Si el no secuestro a esta chica, su relacion con el permanecera intacta, si lo hizo, entonces usted mostraria a todo el mundo lo justo y poderoso que eres.",
"Hmmm... Eso no es irracional. De hecho, no arriesgo nada en este caso. Puedes averiguar que esta pasando. Si tu mision termina con exito, te recompensare. Pero, ya que esta es su iniciativa, sera una modesta suma.",
"Gracias #saddr#.",
"Recuerdame, ?que estabamos discutiendo?",
"Estabamos hablando de una chica secuestrada.",
"Ah, si, lo recuerdo. Segun tengo entendido, realmente fue secuestrada.",
"Si. El sinverguenza no quiso devolver a la chica y fue asesinado por sus propios hombres.",
"Bueno, no hay piratas, no hay problema. Aqui esta tu recompensa. Puedes salir de mi habitacion ahora...",
"Como quieras.",
"Ah, eso es lo que querias discutir...",
"No acto por que no tomas esto mas en serio. ?No es su responsabilidad proveer por la seguridad de los ciudadanos de la Colonia?",
"Capitan, le perdonare que me critique por esta vez. No lo hagas de nuevo si quieres encontrar un favor en esta oficina. \nAs para esas mujeres... Puedo decir que eres un hombre inteligente, asi que, te dire algo.",
"Soy todo oidos.",
"Dos soldados fueron encontrados muertos hoy. Uno de ellos tenia un pedazo de tela carmesi en la mano. \nseveral horas antes de que fueran descubiertos una fragata fue visto actualizadaando lejos de la isla en plena vela.",
" Y esto detiene su investigacion?",
"Bien... Es obvio que se llevaron a los ninos secuestrados de la isla. Bajo las circunstancias, la busqueda no vale el dinero que se gastara en tal expedicion. \nmorreover, podrian estar en cualquier lugar. 4 entender a ese Capitan. El mar ofrece muchos lugares para esconderse. nAnyway, si te conmueve tanto el dolor de esas mujeres, te desafio a encontrar a sus hijos. ni prometo que si la busqueda va a tener exito, voy a Mostrar mi gratitud a usted.",
"Muy bien, estoy de acuerdo, pero primero me gustaria saber donde puedo encontrar un testigo que vio la fragata.",
"No, no quiero gastar mi tiempo en tales tonterias.",
"Aceptas? Perfecto! Puedes encontrar al testigo en la taberna. Fue un capitan mercante quien avisto ese barco.",
"Gracias, puedo despedirme de ti ahora?",
"Deseo unirme a los Hermanos, Senor.",
"Los Hermanos siempre estan contentos de aceptar nuevos capitanes en el redil. ",
"Somos",
"no",
"actualmente en guerra con ",
"el ",
"cualquier nacion",
". Por supuesto,",
" pero",
"todos los enemigos piratas seran hundidos a primera vista.",
"Le hare sentir orgulloso, Senor.",
"Como estoy, Senor?",
"Te has hundido ",
"Barcos franceses, ",
"barcos piratas, un total de ",
" buque.",
"Agradecer.",
"Espero que no tenga qurrel con mi Servicio, Senor.",
"Claro que no, capitan ! De hecho, es un placer darles la bienvenida a los Hermanos. Seras recompensado por cada barco que hundes al Servicio de la cirujano.",
"Me siento honrado, Senor, y tratare de estar a la altura de la confianza del jefe en mi.",
"Me gustaria cobrar mi salario, Senor.",
"Bueno, te has hundido ",
"Barcos franceses, ",
"Buques piratas, ",
"naves totales. Sus salarios actuales son ",
", asi que un total de ",
"Gracias Senor.",
"Traidora escoria! Hundan los barcos de sus compatriotas, ?si? Por la presente quedas despedido del ejercito, tu nombre borrado del rollo, !y no quiero volver a ver tu cara en esta ciudad!",
"...",
"desde la Ultima vez, aqui esta ",
" oro",
"He oido que estoy a favor de un ascenso.",
"Estas hecho! Excelente trabajo. Tu nuevo rango es ",
"Gracias Senor.",
"Barcos espanoles, ",
"Barcos ingleses, y ",
"Oh, si? Tengo una propuesta para usted, capitan.",
"De verdad?",
" Me he enterado de que ha completado usted la tarea con exito; mi enhorabuena, capitan! Aqui esta tu recompensa.",
" Muchas gracias; ha sido un placer ayudaros.",
"Debes destruir el ",
" vaso ",
"pirata de la busqueda",
"amenazando el envio ",
". Si la hundes, te recompensare la considerable suma de ",
" oro. ?Que dice, capitan?",
"Yo me encargare de ella.  Puedes contar con eso.",
"Me temo que no puedo ayudarte.",
"Quiero hacer las paces con los Hermanos.",
"Me gustaria saber sobre las relaciones de #sgov_nation# con las grandes potencias.",
"Quiero unirme a los Hermanos de la Costa.",
"Ah, ",
"gracias por venir. Me gustaria que conocieras a mi ",
". Vendra una vez que terminemos el negocio.",
"No puedo servir ",
", Sir.",
"Estoy harto de servir ",
"Como seguro de que usted es un capitan capaz, y para recompensar mi tiempo en la presentacion de su caso a ",
", Debo pedirte ",
" oro.",
"De ninguna manera.",
"Muy bien.",
"A la luz de su Servicio anterior, ",
"te otorga el rango de ",
"Hemos hecho dano ",
", y ",
"no olvida a sus enemigos. !Vete de una vez, o los guardias te tiraran a la oreja!",
"...",
"Hemos causado ",
"gran dano, capitan, pero ",
"esta dispuesto a pasar por alto sus transgresiones pasadas... por un precio: ",
"Muy bien, Senor. Acepto.",
"Placer, ",
"Y usted, Senor.",
". Ademas, se le premia ",
"acres de tierra por orden de ",
"Estas seguro? ",
"lamentara perder su Servicio.",
"Si, lo soy.",
"no toman amablemente a los chaqueteros, ",
"No importa.",
"Muy bien. Pero espero que lo reconsidere, con tiempo...",
"Despedir, ",
"Eh?",
"Duro.",

};
