string DLG_TEXT[26] = {
"...",
"...",
"Buenos días. ¿Puedo preguntar quién eres?",
"Soy ",
", capitán del ",
"Soy Pieter Boelen, corsario holandés y capitán de un hermoso barco, el 'Amsterdam'. Encantado de conocerte.",
"¿Qué te trae a esta ciudad infestada de piratas?",
"Intento ayudar a todos los piratas honrados de este archipiélago. Esta vez, hay rumores de que el gobernador de #sSantiago# está planeando algún tipo de acción contra esta colonia. Estoy tratando de averiguar si hay algo de verdad en esos rumores. Podrías ayudarme si quieres y ganar algo de dinero por el camino.",
"¿Dinero? Soy todo oídos, capitán. ¿Qué quieres que haga?",
"No puedo dejar esta isla por si el ataque llega mientras estoy fuera. Debo permanecer aquí para defender a mis amigos. Sin embargo, sería posible que tú visitaras #sSantiago# para averiguar si hay algo de verdad en el rumor.",
"Necesitaría engañar a algún alto cargo de #sSantiago# para que me diera esa información. Parece una mision bastante peligrosa. Podrían colgarme por espía si me descubren.",
"Depende de ti. Te daré 20000 monedas de oro si tienes éxito. Lo tomas o lo dejas.",
"Muy bien. Tenemos un trato. No me importa un poco de peligro.",
"Lo siento. Me parece muy peligroso. Te deseo la mejor de las suertes defendiendo esta colonia.",
"¡Excelente! Espero oír noticias tuyas pronto. Y ten cuidado.",
"No te preocupes, lo tendré. Nos vemos en un par de días.",
"¡Ah! ¡Estás aquí! ¿Has averiguado lo que planea el gobernador español?",
"Sí, y son malas noticias, me temo. El gobernador de #sSantiago# pretende tomar el control de esta isla. Su ataque llegará en los próximos días.",
"Me lo imaginaba. Por favor, toma a tus hombres y ve al faro para evitar que el enemigo desembarque allí. Me ocuparé de la defensa del puerto con mi barco y mi tripulación de confianza.",
"Está bien. Saldré ahora mismo y prepararé una cálida bienvenida para nuestros invitados. ¡Buena suerte!",
"¡Ah! ¡Ahí estás! ¿Has tenido éxito?",
"¡Claro que sí! Que esto sea una lección para esos españoles. ¡Los piratas seguirán siendo libres!",
"¡Excelente, capitán! También hemos podido impedir que desembarquen en el puerto. Desafortunadamente, mi hermoso barco, el 'Amsterdam', ha sido dañado durante la batalla y no puedo arriesgarme a zarpar hasta que hayamos hecho algunas reparaciones. No podemos estar seguros de que los españoles no vayan a intentarlo de nuevo, pero seguro que si lo hacen, traerán una flota mucho más grande. Necesitaré la ayuda de los piratas de #sTortuga#. ¿Puedes llevarme allí mientras mi barco está siendo reparado?",
"Por supuesto, no hay problema. Será un honor tenerte como invitado a bordo de mi barco.",
"Gracias por tu ayuda, capitán. Tu intervención ha sido decisiva. No podríamos haberlo hecho sin ti. Hiciste mucho más de lo que habíamos acordado, así que es justo que aumente tu recompensa. ¿Qué te parecen 40000 monedas de oro?",
"¡Oh! Es muy amable por su parte. Tengo otras cosas que hacer ahora, pero no me cabe duda de que, con la ayuda de los piratas de #sTortuga#, serás capaz de defenderte de cualquier ataque español. Espero que volvamos a vernos algún día. ¡Adiós y buena suerte, Pieter!",

};
