string DLG_TEXT[105] = {
"Fuera de aqui! No estoy de humor para hablar con extranos.",
"No quieres comprarme un poco de Ron?",
"En camino. Estoy ocupado.",
"...",
"Que?",
"Estoy buscando a un hombre llamado ",
"Raoul Reims",
"Raoul Reims",
". Es un capitan. ?Lo has visto?",
"Si! Si! Lo he visto con mis propios ojos! Pero seria mejor preguntar que posadero mujer - ella lo sabe mucho mejor que yo. Si me entiendes, #ssir#.",
"Ya veo. Gracias.",
"De todo el ",
"la gente en esta isla, tuve que correr a usted...",
"Espera ahi, amigo. Solo necesito informacion sobre su Colonia. Puede que haya algo de Ron para ti, si eres util.",
"*sigh* Bien, pide lejos - pero sea estrategia con el.",
"avia prisa, tengo un buen grog, un buen botin y chicas adecuadas esperando en mi camarote.",
"Sera mejor que te pongas estrategia, antes de que se me pase el efecto de la buena porrista.",
"Por pequeno que sea tu pueblo, todavia necesito algunas direcciones.",
"Solo necesito orientarme.",
"Seria tan amable de decirme donde encontrar?..",
"Que puedes decirme de esta ilustre y totalmente legitima Colonia tuya?",
"Uno de sus encantadores ciudadanos me interesa...",
"Vine aqui para averiguar sobre alguien en la ciudad.",
"Ser querido y hablarme de alguien? Podria ser un amigo tuyo.",
"Casi puedo ver una corona de lineas apestosas para ir con ese olor a pocky. No importa.",
"A quien tienes en mente, eh, amor? *cero*",
"Eh? *pedo*",
"Vaya, todos mis amigos, son ... cada uno de estos malditos sinverguenzas, ja! *burp*",
"Quien os gobierna a todos?",
"Tu Dispensadora de cerveza, barwench, como quieras llamarla.",
"Ese caballero que hace presagios para reparar buques de navegacion ... Oh, lo siento, ?son mis palabras demasiado grandes para ti?",
"El que vende las velas y esas cosas.",
"Ese comadrejo de ojos rasgados a las afueras de la ciudad.",
"La senorita que gobierna el burdel...",
"No importa, nadie vale la pena saber sobre esta roca. Pero me gustaria saber algo mas.",
"Arne? Incluso para un pirata, ese chico es corrupto. Ademas, siempre estaba haciendo una raqueta, cuando tenia su tienda aqui detras de las estacas ... asi que amablemente le proporcionamos una nueva tienda, AFUERA.",
"Muy bien. Otra cosa...",
"Gracias, eso es todo.",
"Isenbrandt? Un tipo severo, ese. Pero tiene lo que se necesita para mantener las cosas en orden aqui. Elegido unanimemente ... como para liderarnos a los perros.",
"Tendre que hacerle una visita. Pero sobre otro asunto...",
"Gracias. - Hasta luego.",
"El bueno de Ines. Ella cuida bien de nosotros, los chicos ruidosos. Sabe como prescindir de lo que nos gusta la ortodoncia.",
"Siento retenerte, pero hay otra cosa...",
"Si, Jakob Nickerson. Se mudo a la ciudad no hace mucho. Hace un buen trabajo arreglando barcos, ademas tiene una partitura para vender.",
"Bueno. Algo mas?",
"Ja, ese seria el viejo soplador. Te enganara si puede... y eso es lo mejor que puedes hacer aunque le gustes.",
"Ya veo. Tengo otra pregunta para ti.",
"Es bueno oirlo. Hasta luego.",
"Ya veo a donde vas con esto ... siguiendo a tu bowspirit en un puerto amistoso, ?eh, amigo? Un poco de ol' nudge-nudge, wink-wink, eh friend? heh... Anyway, Celestine -- for that's the 'spectable mistruss's name -- keeps a fine stable o' pretty mares, she does. I think you'll enjoy a visit.",
"En el punto. Va a tener una pregunta mas?",
"Bien, ?ahora que?",
"Conozco esta isla mejor que nadie, asi que sera mejor que me lo preguntes.",
"Conoce bien este lugar, yo lo conozco. Pero estas a punto de conocerme. flappin' on overlongs-like... mate.",
"Venderia mi barco, mi querida mama y mi alma si pudiera tomar una Copa...",
"Un buen juego de goteras me trajo aqui - quien puede ponerme una nave para llenar los vacios?",
" Hay un comerciante aqui que no sea un tramposo?",
"Puede alguien en esta miserable roca reparar mi espada sangrienta?",
"Un tipo tiene necesidades... si me entiendes. Donde podrian encontrarse?",
"Arne -- que en esa choza por ahi facin' las puertas -- es un saltarin, skitterish cabron, y los cargos en exceso, Y el toma mucho tiempo... ahora que lo pienso, sera mejor que no te molestes.",
"Me arriesgare, gracias.",
"Y tu pobre excusa para un astillero?",
"Quien va a comprar la mierda vieja fuera de mi bodega?",
"Ines' tiene una cisterna esperando por ti en el lado cercano de la gran roca que se encuentra en el centro de la ciudad.",
"Muchas gracias, mi maleducado amigo.",
" Y donde puedo tener mi nave reparada?",
"Y si quiero hacer algun trato legal?",
"Mi espada esta a punto de oxidarse para nada... puede alguien de esta ciudad arreglarlo?",
"Caminando a traves de las puertas, la casa de reparaciones de la nave esta en la plataforma -- no, la izquierda. Puerto, verdad? Siempre me confundo con esos dos. Un dia, me dice a mi mismo, voy a aprender yo mismo estos terminos nauticos...",
"Pero lo mas importante ... donde esta tu casa de cerveza?",
"Necesito encontrar a alguien que me de un precio justo por mis bienes.",
"Has sido de gran ayuda; eso es todo.",
"Quien os sirve de Herrero?",
"Una de las casas del medio a la izquierda, frente a las rocas que ensucian el medio de nuestras calles. Esa es la izquierda, al entrar en la ciudad.",
"Donde esta tu astillero?",
"Que hay de la taberna?",
"Eso es todo lo que puedo soportar de tu compania, gracias.",
"Y si te dijera que mi espada no es suficiente como para abrir un melon maduro?",
"No estoy seguro de entender, amigo...",
"Ya sabes -- ciertas necesidades, que un #sgender# posesses de vez en cuando... Un #sgender# long en el mar, con solo la compania de #spronoun# mates, que, por muy bonita que pueda ser, no van un largo camino para apagar ciertos fuegos que se queman en #spronoun# loins?",
"Que es eso? Burnin' lomos? Creo que podria tener algun unguento aqui, si eso es lo que esta despues... No veo que mas quieres decir...",
"Dejame que te lo deletree, AMIGO: ?Donde guardas tus malditas putas?!",
"Me caballo? Esta de vuelta en su establo, comiendo bien, cargado de avena, gordo y bonito. Sin embargo, no veo que tiene eso que ver con entranas ardientes.",
"Olvidalo... parece que ha vuelto el sonanismo para este marinero solitario.",
"Por cierto, capitan, solo entre nosotros dos: no hay ningun OIN violenta o ecuestre persuade alli, pero es posible que le gustaria caer por el burdel al otro lado de la roca, justo al lado de la casa de nuestro gobernador. Alli tienen un juego de dados muy bonito. Y saluda a la pequena Lucie de mi parte, si quieres... *blush... belch*",
"*sigh*",
"Nosotros los tipos de baja fibra moral somos un grupo de pacientes ... hasta cierto punto. (A Observer and steely point, y's See. Avia prisa.",
"Bien, cualquier cosa que quieras saber ... ceptin' donde tengo mi alijo.",
"Realmente eso es lo que deseas, ?eh? La mayoria de los visitantes de aqui se dieron a la fuga, si lo saben...",
"Me gustaria conocer la historia de la famosa isla de los piratas.",
"Que hay en esta roca desolada ademas de tu pueblo?",
"No, mas bien, otro tema servira, ?de acuerdo?",
"Aye, storied she is: a fine 'istory o' blood an' guts. But we freebootin', seafarin' folk -- calls ourselves 'Buccaneer Caribbeans', if it please ye -- take good care of our own sort, and as long as ye be flyin' the skull'n'bones, yer a mate of ours. Why, there's",
"Fascinante... hazme el favor y dime mas.",
"Intruiging perfectamente. Pero tengo otras cosas en la cabeza.",
"Esta tierra ha estado en muchas manos desde que los espanoles la colonizaron por primera vez, de vuelta en el derecho-seis si mal no recuerdo. Luchamos con esta roca de los franceses hace 20 anos, y nadie ha sido lo suficientemente hombre para intentar quitarnosla. Y que lo intenten, digo yo!",
"Vaya historia. Me gustaria saber mas sobre el estado actual de las cosas, ahora.",
"No, no hay nada mas que encontrar aqui... solo nuestro pequeno acuerdo, para estar seguros. Y yo tendria cuidado, preguntando por nuestros asuntos privados aqui, marquenme.",
"Hmhm... debidamente anotado. Algo mas que sepas sobre tu isla?",
"Bien... en el otro lado de la isla, a traves de algunos bocados, puede que se Topen con una agradable sorpresa. Pero por ahora no dire nada.",
"Que bonito. Me gustaria saber mas, si me aguanten.",
"No lo has oido de mi, pero ... .. Una bonita mansion, justo a traves de un rincon de la selva. Hemos estado abandonados todos estos anos, incluso llenos de swag como ella es, pero estamos todos apenados para tocarlo, a menos que el propietario debe decidir volver-uno temeroso derecho que es, todos debemos pensar.",
"Ah, si?",
"Has sido inesperado, pero deliciosamente, util. Podrias contestarme otra, amigo?",
".",
"nosotros ahora!",

};
