string DLG_TEXT[170] = {
". ¿De qué se trata, ",
"?",
"¿Puedo ayudarte, ",
"?",
"¿Es esta tu primera visita a nuestra ciudad, ",
"? No te he visto antes.",
"Soy ",
", capitán en propiedad del barco '",
"'. Tengo algunas preguntas, si tienes un momento.",
"Mi nombre es ",
". Me gustaría hacerte algunas preguntas.",
"Puedes llamarme capitán ",
". Solo quiero información.",
"Hola, capitán ",
". ¿Qué te trae a nuestra colonia?",
"Ah, capitán ",
". ",
", eres tú otra vez. Espero que tu viaje haya sido agradable. ¿Qué hay de nuevo?",
"Hola, ",
". ¿Cómo puedo ayudarte?",
"¿Me he perdido algo mientras estaba fuera?",
"¿Ha pasado algo interesante mientras estaba fuera?",
"¿Qué historias intercambian los viejos lobos de mar estos días, entre trago y trago de ron?",
"¿Cúal es el último rumor de las tabernas?",
"Busco chismes, rumores, cuentos..., cualquier cosa que no conozca puede ser útil.",
"Dame algunos de tus chismes más frescos, camarada. Hasta el menor cotilleo puede encerrar aventura o posibilidades de ganar dinero.",
"Sigo sin poder encontrar...",
"¡Es imposible encontrar nada en este laberinto! ¿Dónde esta...",
"Me he perdido igual que un piloto borracho. ¡Otra vez!",
"Pareces de por aquí. Dime dónde puedo encontrar...",
"Por favor, dime cómo llegar a...",
"He tenido un día de perros, así que nos ahorrarás a ti a y a mí un mal rato si me dices cómo encontrar...",
"Me gustaría tu opinión sobre un ciudadano local.",
"Necesito saber todo lo que puedas decirme sobre alguien que vive aquí en la ciudad.",
"¿Qué puedes decirme de...",
"Dime todo lo que puedas sobre cierta persona...",
"Espero que puedas decirme algo sobre una persona que tal vez conozcas.",
"Este lugar no es muy grande; apuesto a que conoces a todos los que viven aquí. Hablemos.",
"Háblame de #sPort Au Prince#.",
"¿Qué puedes decirme de este lugar dejado de la mano de Dios?",
"Me gustaría saber más sobre esta hermosa colonia.",
"¿Cúal es la historia de esta ciudad y de la isla?",
"¿Sabes algo de interés sobre #sPort Au Prince#?",
"...",
"Lo siento. Pensé que eras otra persona.",
"Solo estoy de paso. Así que aparta o te aparto.",
"¿Qué te gustaría saber, ",
"?",
"¿Qué te interesa, capitán?",
"¿Qué quieres de mí?",
"Ciudades como esta siempre están llenas de chismorreos. Dime lo más destacado.",
"¿Ha pasado algo interesante por aquí últimamente?",
"Solo quiero saber que está pasando en el vecindario. ¿Alguien ha estafado a un amigo? ¿Alguien ha sido asesinado? ¿El posadero es realmente una mujer? Ya me entiendes.",
"¿Cómo puedo llegar a...",
"¿Puedes ayudarme a orientarme en la ciudad?",
"¿Dónde puedo encontrar...",
"¿Puedes hablarme de alguien que me interese?",
"Me gustaría obtener información sobre un vecino. ¿Podrías ayudarme?",
"Me pregunto qué tiene que decir la gente de la ciudad sobre cierta persona...",
"¿Qué puedes decirme de #sPort Au Prince#?",
"Me gustaría conocer la historia de tu ciudad.",
"Me gustaría obtener información sobre esta colonia.",
"Solo estoy de paseo. Hasta luego.",
"Gracias. Hay una cosa más...",
"Ha sido agradable charlar contigo. ¡Hasta la vista!",
"¡Alguna otra cosa, capitán ",
"?",
"Oigámoslo, ",
".",
"Te escucho, ",
".",
"¿Cuál es la comidilla de la ciudad estos días?",
"¿Qué historias intercambian los viejos lobos de mar estos días, entre trago y trago de ron?",
"Ha pasado mucho tiempo desde que puse un pie en estas costas. ¿Qué me he perdido?",
"¿Podrías darme algunas indicaciones?",
"Me he perdido por completo en estas calles.",
"Es mi primera vez en esta ciudad, y me gustaría que me dieras algunas indicaciones.",
"Me gustaría saner tu opinión sobre un ciudadano local.",
"Necesito saber todo lo que puedas decirme sobre alguien que vive aquí en la ciudad.",
"¿Podrías darme alguna información sobre los lugareños?",
"Háblame de #sPort Au Prince#.",
"¿Qué puedes decirme de esta colonia?",
"Me gustaría saber algo sobre #sPort Au Prince#.",
"Acabo de darme cuenta de que tengo que estar en otra parte. Adiós.",
"¿A quién te refieres,",
"?",
"¿Preguntas por alguien en especial?",
"¿De quién quieres saber exactamente?",
"Me refiero al gobernador.",
"Me interesa el dueño de la taberna.",
"El propietario del astillero.",
"Estoy hablando del comerciante local.",
"Nadie. Olvídalo.",
"Hum.. ¿Qué quieres que te diga? Nos trata bien, y nuestra ciudad ha prosperado desde que ella está al mando.",
"Ya veo. Tengo otra pregunta para ti.",
"Gracias, y adiós.",
"Siempre tiene algún chiste en la punta de la lengua. ¡Y sabe mucho de lo que pasa en el mundo! Se le da muy bien escuchar.",
"Ya veo. Tengo otra pregunta para ti.",
"Gracias, y adiós.",
"Es un hombre solitario. Solo se dedica a su barcos. Pero, por eso mismo, lo sabe todo acerca de ellos. Si alguien tiene que arreglar tu barco, él es el hombre adecuado.",
"Ya veo. Tengo otra pregunta para ti.",
"Gracias, y adiós.",
"Es muy codicioso. Algunos dicen que era el asistente de Baldewin Coffier, pero cuando la tienda se arruinó, él la compró a bajo precio. No sé mucho sobre la calidad o el precio de sus mercancías, pero no parece ser muy... buena persona.",
"Ya veo. Tengo otra pregunta para ti.",
"Gracias, y adiós.",
"¿Adónde vas, ",
"?",
"No hay problema, capitán. ¿Adónde tienes que ir?",
"Será un placer guiarte, ",
". ¿Pero adónde quieres ir?",
"¿Cómo puedo llegar a la taberna?",
"¿Dónde está el astillero?",
"¿Dónde puedo vender la mercancía que he traído conmigo?",
"Eso es fácil. Cuando vienes del puerto es la casa de la izquierda. Solo tienes que pasar por el pequeño pasillo entre las dos casas y girar a la izquierda, y verás la puerta.",
"Bien. Gracias por tu tiempo.",
"¿Dónde está el astillero?",
"¿Dónde puedo conseguir un precio decente por las mercancías de calidad que he traído a la ciudad?",
"El astillero es la gran casa en el centro de la ciudad. No tiene pérdida. ",
"Ya veo. ¿Y la taberna?",
"¿Dónde puedo conseguir un precio decente por las mercancías de calidad que he traído a la ciudad?",
"Creo que eso es todo. Gracias por tu ayuda.",
"¿Sabes dónde esta la taberna? La tienda esta enfrente. ",
"¿Dónde puedo encontrar el astillero local?",
"¿Cómo llego a la taberna?",
"Ya veo. Gracias por la información.",
"No sé porque te interesaría algo así, pero, ¿por qué no?",
"¿Qué es exactamente lo que te interesa, ",
"?",
"Por supuesto, ",
". Afortunadamente, es una historia bastante corta.",
"Me interesa la historia de la colonia...",
"Háblame de la colonia.",
"¿Hay algo en la isla, además de la ciudad?",
"Tengo algunas preguntas más para ti, si no te importa.",
"Los españoles fueron los primeros en ocupar estas tierras. Entonces los franceses vinieron y la conquistaron. En 1749 se fundó la ciudad de #sPort Au Prince#.",
"Gracias. Déjame hacerte unas preguntas más.",
"Sabes, realmente pensé que iba a ser más interesante. Déjame preguntarte algo más.",
"Eso es todo lo que necesito. Gracias.",
"Gracias por tu tiempo. Hasta la vista.",
"Bueno, al otro lado de la isla está #sSanto Domingo#. También tenemos algunas plantaciones. Pero el resto es selva.",
"Que mas puedes decirme sobre la Colonia?",
"Que mas puedes decirme?",
"Nuestra iglesia es la más antigua. La primera piedra se puso en 1521 y la terminaron en 1540.",
"Ya veo. ¿Qué más?",
"No. Encontrarás un par de plantaciones y casas en esta parte de la isla, pero en general está poco desarrollada.",
"En ese caso, tal vez me puedes decir algo más acerca de la colonia.",
"Entiendo. Déjame preguntarte algo más.",
"Conoces a un contramaestre llamado Fred Bob?",
"¿Qué puedes decirme del capitán del puerto?",
"Oh, ¿Fred Bob? ¡No es un amotinado, eso te lo aseguro! Es un buen marino, y un hombre fuerte al que merece la pena tener de tu lado cuando te superan en numero. Es una lástima lo de su encarcelamiento. Todos esperamos que el gobernador lo libere, porque nadie más aparte de ese pomposo primer oficial cree que sea culpable.",
"Interesante. Tengo otra pregunta para ti.",
"Muchas gracias, y adiós.",
"No sé como lo hace, pero nuestro capitán de puerto se las arregla para conocer a todos los marinos del archipiélago.",
"Ya veo. ¿Una pregunta más, por favor, si no te importa?",
"Gracias por tu tiempo. Adiós.",
"¿Fred Bob? ¿El contramaestre? Es muy difícil entender lo que dice, pero mi hermano lo conoce bien. No es un amotinado. Ese oficial está equivocado. Todos esperamos que el gobernador lo libere. Su lugar está a bordo de un barco, no en el cepo.",
"Buen hombre, excelente marinero. Yo no creo ni por un minuto que amenazara con amotinarse.",
"Esto..., se me he olvidado por completo sobre quién iba a preguntar. Solo dame un segundo y me acordaré...",
"¿Cómo esta el viejo herrero Tomás hoy en día?",
"¿Te refieres a Tomasina, ¿no? El viejo Tomás murió de repente hace poco, y ahora es su esposa la que maneja el yunque. No se puede decir que ella haga un mal trabajo, la verdad.",
"Oh, cielos... ¿no le dan vahídos dedicándose a esa profesion? No importa; cambiemos de tema.",
"Vaya. ¿Una viuda casadera que puede reparar una espada? Tendré que presentarle mis respetos inmediatamente...",
"Mi espada favorita de todos los tiempos en el mundo ha perdido un poco el filo. ¿A quién puedo confiársela?",
"¿Tenemos un herrero? Es la primera noticia que tengo de eso. Avísame si lo encuentras.",
"Bueno, esté bien, ya buscaré por ahí. Gracias de todos modos.",
"¿Dónde está el astillero?",
"¿Dónde puedo conseguir un precio decente por las mercancías de calidad que he traído a la ciudad?",
"¿A quién le puedo confiar mi espada? Su antaño agudo filo se ha embotado un poco.",
" Tenemos una población de ",
" ciudadanos.",

};
