string DLG_TEXT[135] = {
"¡Fuera de aquí! No estoy de humor para hablar con extraños.",
"¿No quieres invitarme a un trago de ron?",
"Lárgate. Tengo cosas que hacer.",
"...",
"¿Qué?",
"Estoy buscando a un hombre llamado ",
"Raoul Reims",
"Raoul Reims",
". Es un capitán. ¿Lo has visto?",
"¡Sí! ¡Sí! ¡Lo he visto con mis propios ojos! Pero sería mejor que le preguntaras a esa posadera; ella lo conoce mucho mejor que yo. Si entiendes lo que quiero decir, #ssir#.",
"Ya veo. Gracias.",
"De todas las ",
" personas que hay en esta isla, tuve que tropezarme contigo...",
"Espera ahí, camarada. Solo necesito información sobre la colonia. Puede que haya algo de ron para ti, si me resultas útil.",
"*suspiro* De acuerdo, pregunta, pero que se rápido.",
"Date prisa. Tengo un buen grog, un montón de botin y unas mozas bien dispuestas esperando en mi camarote.",
"Será mejor que te des prisita, antes de que se me pase la alegría del ron.",
"Por pequeño que sea tu pueblo, necesito algunas indicaciones.",
"Solo necesito orientarme.",
"¿Serías tan amable de decirme dónde encontrar...",
"¿Qué puedes decirme de esta ilustre y totalmente legítima colonia tuya?",
"Me interesa uno de tus encantadores conciudadanos...",
"He venido aquí para averiguar algunas cosas sobre alguien de esta ciudad.",
"¿Tendrías la amabilidad de hablarme de cierta persona? Puede que sea amigo tuyo.",
"¡Puaj!, casi puedo ver una corona de líneas apestosas a juego con ese olor nauseabundo. No importa.",
"¿A quién tienes en mente, eh, amor? *se rasca*",
"¿Eh? *pedo*",
"¡Claro, todos son amigos míos!... ¡Todos y cada uno de estos malditos sinvergüenzas, ja! *eructo*",
"¿Quién os gobierna a todos?",
"Vuestra dispensadora de cerveza, moza de taberna, como quieras llamarla.",
"Ese caballero que se ocupa en reparar navíos de altura... Oh, lo siento, ¿son mis palabras demasiado refinadas para ti?",
"El que vende las velas y esas cosas.",
"Ese hojalatero bizco con pinta de comadreja a las afueras de la ciudad.",
"La señorita que regenta el burdel...",
"No importa, no hay nadie a quien valga la pena conocer en esta roca. Pero me gustaría saber algo más.",
"¿Arne? Incluso para un pirata, ese chico es un corrupto. Además, montaba un escándalo del demonio cuando tenia su taller aquí, dentro de la empalizada..., así que fuimos tan amables de proporcionarle un nuevo taller, FUERA.",
"Muy bien. Otra cosa...",
"Gracias, eso es todo.",
"¿Isenbrandt? Un tipo severo, ese. Pero tiene lo que hay que tener para mantener las cosas en orden aquí. Fue escogido unánimemente para liderar a esta jauría de perros.",
"Tendré que hacerle una visita. Pero, pasando a otro asunto...",
"Gracias. Hasta luego.",
"La buena de Inés. Ella cuida muy bien bien de nosotros, sus chicos traviesos. Sabe cómo dispensar lo que nos gusta.",
"Siento retenerte, pero hay otra cosa...",
"Si, Jakob Nickerson. Se mudó a la ciudad no hace mucho. Hace un buen trabajo arreglando barcos, y además tiene unos cuantos para vender.",
"Bien. ¿Algo más?",
"No 'el', 'la'. El viejo Peter Blowhorn se retiró hace años. Su hija Kate es la que dirige la tienda ahora. Ella no te tima como lo hacía el viejo Pete... Será que no quiere que te lleves tus negocios a #sCharlestown#, ¿verdad?",
"Ya veo. Tengo otra pregunta para ti.",
"Es bueno saberlo. Hasta luego.",
"Ya veo por donde vas, camarada... Siguiendo el rumbo de tu palo bauprés hacia un puerto amigo, ¿eh? Quieres darle un poco de alegría al cuerpo, ¿no? Je, je... Bueno, Celestine, que así se llama nuestra respetable dama, tiene un buen establo de bonitas potrillas, ya lo creo. Creo que disfrutarás de la visita.",
"Perfecto. ¿Me permites una pregunta más?",
"Bien, ¿ahora que?",
"Conozco esta isla mejor que nadie, así que será mejor que me preguntes a mí.",
"Conozco este sitio, lo conozco. Pero tú vas a conocer mi bota aún mejor si sigues dándole a la lengua mucho más tiempo..., camarada.",
"Vendería mi barco, a mi querida mamá y hasta mi alma a cambio de un trago...",
"He llegado aquí en un cascarón que hace aguas por todas partes... ¿Quién puede tapar los agujeros para que vuelva a ser un barco?",
"¿Tenéis algún comerciante aquí que no sea un timador?",
"Hay alguien en esta miserable roca que pueda reparar mi maldita espada?",
"Todo el mundo tiene sus necesidades... si entiendes a qué me refiero. ¿Dónde podría satrisfacerlas?",
"Arne. Vive ahí fuera, en esa choza enfrente de las puertas. Es un bastardo nervioso y asustadizo, y cobra más de la cuenta, y tarda mucho tiempo... Ahora que lo pienso, será mejor que no te molestes.",
"Me arriesgaré, gracias.",
"¿Y esa pocilga que llamáis astillero?",
"¿Quién va a comprar toda la mierda que tengo en la bodega?",
"Inés tiene una jarra esperándote en el lado de acá de esa gran roca que está en el centro de la ciudad.",
"Muchas gracias, mi maloliente y descortés camarada.",
"¿Y dónde puedo reparar mi barco?",
"¿Y si quiero hacer algún trato COM-PLE-TA-MEN-TE legal?",
"Mi espada está comida por el óxido... ¿Hay alguien en este agujero que pueda arreglarla?",
"Según cruzas las puertas, la casa del carpintero de barcos está a la der..., no, la izquierda. Babor, ¿no? Siempre me confundo con esos dos. Un dia, me digo siempre, voy a aprenderme estos términos náuticos...",
"Pero lo más importante ..., ¿dónde esta vuestro abrevadero local?",
"Necesito encontrar a alguien que me dé un precio justo por mis mercancías.",
"Has sido de gran ayuda; eso es todo.",
"¿Quien os sirve de herrero?",
"Una de las casas cemtrales a la izquierda, frente a las rocas que hay plantadas en medio de nuestras calles. O sea, a la izquierda, según entras en la ciudad.",
"¿Dónde esta el astillero?",
"¿Qué hay de la taberna?",
"Eso es todo lo que puedo soportar de tu compañía, gracias.",
"¿Y si te dijera que mi espada no está lo bastante afilada ni para abrir un melón maduro?",
"No sé si te entiendo, camarada...",
"Ya sabes, tengo ciertas necesidades, que cualquier #sgender# tiene de vez en cuando... Cualquier #sgender# que ha pasado mucho tiempo en la mar, con la única compañía de sus camaradas de tripulación, que, por muy guapo que pueda ser alguno, no dan para extinguir ciertos fuegos que arden en las partes bajas.",
"¿Qué? ¿Ardor en las partes bajas? Creo que tengo algún ungüento para eso, si es lo que buscas... No sé que otra cosa me quieres decir...",
"Déjame que te lo diga alto y claro, CAMARADA: ¡¿Dónde demonios tenéis a vuestras putas?!",
"¿Frutas? A mí qué me dices, pregunta en la tienda... Pero la fruta es buena para el escorbuto, no veo qué tiene eso que ver con el ardor en tus partes bajas.",
"Olvídalo... Parece que tendré que resignarme y volver a #sonanism# en las noches solitarias.",
"Por cierto, capitán, así entre tú y yo: es posible que te gustara dejarte caer por el burdel, en el lado de allá de la roca, justo al lado de la casa de nuestro gobernador. Allí no hay ungüentos ni frutas, pero se juega a los dados que da gusto. Y saluda a la pequeña Lucie de mi parte, si quieres... *se sonroja... eructa*",
"*suspiro*",
"La gente de baja fibra moral como nosotros tiene mucha paciencia..., hasta cierto punto... o más bien, hasta cierta punta. Una punta de acero muy afilada. Así que date prisa.",
"Claro, cualquier cosa que quieras saber... excepto dónde guardo mi alijo.",
"¿Realmente te interesa tanto? La mayoría de los visitantes que vienen aquí salen corriendo, ya sabes...",
"Me gustaría conocer la historia de la famosa isla de los piratas. Seguro que es una historia trepidante.",
"¿Qué hay en esta roca desolada, además de este pueblo?",
"No, la verdad, pasemos a otro tema, ¿de acuerdo?",
"Sí, y tan trepidante: una bonita historia de sangre y tripas. Pero la gante de mar filibustera como nosotros —puedes llamarnos 'bucaneros caribeños', si quieres— cuida bien de los suyos, y mientras la calavera y las tibias ondeen en tu mástil, te llamaremos camarada. ¡Ahora hay aquí unos ",
"Fascinante... Por favor, cuéntame más.",
"Realmente intrigante. Pero ahora tengo otras cosas en mente.",
"Esta tierra ha pasado por muchas manos desde que los españoles la colonizaron por primera vez, allá por el año seis, si mal no recuerdo. Le arrebatamos esta roca a los franceses hace 20 anos, y nadie ha sido lo suficientemente hombre para intentar quitárnosla. ¡Que lo intenten, digo yo!",
"Vaya historia. Me gustaría saber más sobre el estado actual de las cosas.",
"No, no hay nada más que ver aquí... solo nuestro pequeño asentamiento, te lo aseguro. Y si yo fuera tú, me andaría con más cuidado, al preguntar por nuestros asuntos privados, recuerda lo que te digo.",
"Ajá... Lo tendré en cuenta. ¿Algo más que sepas sobre tu isla?",
"Bueno..., al otro lado de la isla, cruzando la selva, puede que te tropieces con una bonita sorpresa. Pero, por ahora, no diré nada.",
"Qué bonito. Me gustaría saber más, si no te importa.",
"Yo no te he dicho nada, pero ... Hay una bonita mansión, justo al otro lado de un tramo de selva. Ha estado abandonada todos estos años, incluso aunque está llena de riquezas, pero ninguno de nostros se atreve a tocarlas, no vaya a ser que el dueño decida volver. Ese sí que da miedo.",
"Ah, ¿sí?",
"Has sido inesperada, pero deliciosamente, útil. ¿Podrías contestarme a otra pregunta, camarada?",
".",
" de los nuestros!",
"Estoy buscando a una chica joven...",
"¿Y quién no?",
"Esta es una chica que fue secuestrada por los piratas.",
"¿Qué piratas?",
"Oh, vamos, pareces un joven muy observador e inteligente. ¿Quizás hayas visto a una chica alta que fue traída a este pueblo como rehén?",
"Está bien, los vi traer a una nueva chica al asentamiento, una morena.",
"¿Qué pasó con ella? ¿Dónde puedo encontrarla?",
"Supongo que la vendieron.",
"¿Como esclava? ¿A quién?",
"Usa tu imaginación...",
"De acuerdo, camarada, no puedo pasarme todo el dia hablando contigo (Malas noticias; ¡supongo que se refiere al burdel!).",
"No sé nada.",
"Tal vez haya algo de oro para ti si tienes información útil.",
"¿De cuánto oro estamos hablando?",
"Bueno, digamos 40 piezas de oro, y eso es solo si sabes algo que sea de valor para mí.",
"Pareces muy impaciente capitán, ¿por qué no 60?",
"¡Pirata miserable! Te daré 50, y ya me parece demasiado.",
"Son 30 o nada, ¡miserable robaperas!",
"Toma tu oro y empieza a hablar o te...",
"¡Si sabes algo, escúpelo o te haré mucho daño!",
"¿Tengo que repetirlo, capitán? ¡No sé de qué estás hablando!",
"¡No te tengo miedo, joven!",
"Sal de mi vista ahora mismo.",
"Afloja la mosca, capitán.",
"buscar a Nemo",
"frotar la cubierta de proa",
"darle al yunque de Venus",
"sacarle brillo al mástil",
"tocar la zambomba",
"zurrarme la sardina",

};
