string DLG_TEXT[36] = {
"¿Tú andabas preguntando por ",
"Desmond Ray Beltrop",
"?",
"Sí. Me gustaría hablar con él.",
"¿Ah, sí? Deberías saber que no es fácil hablar con ",
"Desmond Ray Beltrop",
".",
"Gracias por el consejo, pero, a menos que tú seas el que se encarga de sus citas, seguiré mi camino.",
"Digamos que soy un socio de ",
"Desmond Ray Beltrop",
"y si quieres una audiencia con él, tendrás que hablar conmigo.",
"Está bien, pero lo que tengo que decirle es solo para sus oídos. Llévame hasta tu jefe o hazte a un lado. Puedo encontrarlo sin tu ayuda.",
"En ese caso, tengo una idea: llévame hasta tu jefe o te atravieso.",
"Puedo llevarte hasta él, pero tendrás que entregarme tu espada y tu pistola.",
"¿Te crees muy valiente? ¡Con solo un chasquido de mis dedos, no quedará nada de ti!",
"Voy con mis armas, o no voy. Ya encontraré a ",
"Desmond Ray Beltrop",
" sin tu ayuda.",
"Cuando te dispare en el hígado, vivirás tal vez unas pocas horas y morirás en medio de insoportable sdolores.",
"¿Quieres hablar con ",
"Desmond Ray Beltrop",
" o no? ¡Dame tus armas o esto acabrá mal!",
"Si me disparas, tú también morirá... Así que creo que es un farol.",
"He dicho todo lo que voy a decir. Llévame hasta ",
"Desmond Ray Beltrop",
", o déjarme encontrarlo por mi cuenta.",
"Entonces llevame hasta ",
"Desmond Ray Beltrop",
", o tendrás que vértelas con mi acero.",
"Vamos, pero te advierto que a ",
"Desmond Ray Beltrop",
" no le va a gustar esto.",
"Cálmate, te llevaré hasta ",
"Desmond Ray Beltrop",
" y, a partir de ahí, será problema tuyo.",
"Ahora nos entendemos. Ve tú delante.",

};