string DLG_TEXT[71] = {
"¡Fuera!",
"¡Ya me voy, no hace falta gritar!",
"¡¿Qué estás haciendo en mi casa?! ¡Fuera!",
"Primero, responde: ¿dónde está ",
"Teodoro Fernandez",
"?",
"¡Te tenemos! Te hemos esperado mucho tiempo. ¡Sabemos que estás espiando para el capitán del puerto! No saldrás con vida de aquí!",
"Como desees.",
"¿Qué estás haciendo aquí?",
"Me envió un hombre desde la taberna.",
"¡No conozco a ningún ",
"Teodoro Fernandez",
"! ¡Fuera! ¡Ahora!",
"¿Por qué tiemblas? No me estarás ocultando nada, ¿verdad?!",
"Vete, o...",
"¿O qué? Déjame adivinar, ¿llamarás a los guardias? Bueno, siento decepcionarte, pero también están buscando a ",
"Teodoro Fernandez",
".",
"¿Qué quieres de mí?",
"Solo quiero saber que le pasó al hombre que vino aquí hace diez minutos.",
"Salió por la puerta de atrás. No creo que lo atrapes.",
"Entonces, tal vez tú me puedas decir lo que quería.",
"¡Déjame en paz! ¡Ya te he dicho lo que sé!",
"Ya veo. Entonces, ¿qué hay en esos papeles que escondes a tus espaldas?",
"¡No es asunto tuyo! ¡Es solo una carta de... eh, mi sobrina!",
"Déjame ver, ¡te lo leeré en voz alta!",
"¡¿Cómo te atreves?! ¡¿Quién demonios te crees que eres?!",
"Soy ",
", capitán libre, y no acostumbro a recibir órdenes; si no me das esa carta ahora mismo, hurgaré en tus tripas con mi espada.",
"¡Pirata!",
"¡Has dado en el clavo! Así que contaré hasta tres. Uno...",
"¡Tómala, maldita sea, pero no me hagas daño!",
"Ah, veamos... ¿Una sobrina, dices?",
"¡Déjame ya!",
"No tan rápido. Aquí veo que estás comprando productos de contrabando. Es una senda traicionera que lleva a la perdición.",
"¡Lo que yo haga no es asunto tuyo!",
"No te emociones demasiado. No estarás en libertad por mucho tiempo. Creo que las autoridades estarán muy interesadas en estos documentos.",
"¡Ah, ",
"Andre Juliao",
"!",
"Cierto, era él.",
"En realidad, no se presentó.",
"¡Fuera, ahora!",
"¿Qué pasa?",
"¡Ahora, he dicho! ¡Antes de que llame a los guardias!",
"Como desees.",
"¡Inténtalo y te arrepentirás!",
"Nunca lo hace, ¡je, je!... Bien, vayamos al grano.",
"Deberíamos haberlo hecho hace mucho tiempo.",
"Entonces, ¿necesita un producto específico, capitán?",
"Sí.",
"¿Puedo preguntar para qué?",
"Bueno... Aún no lo sé, pero no hay nada de malo en comprarlo de todos modos, ¿verdad?",
"Me pidieron que lo comprara.",
"¿Quién?",
"¿De verdad crees que te diría su nombre?",
"Muy bien, te creo. Pero, te costará... ¡Argh!... Siempre olvido estos números.",
"¡Hum!",
"Oh, no te preocupes, lo tengo aquí. Solo necesito echar un vistazo a mis papeles.",
"Déjame echar un vistazo a mí también.",
"¡Oye! ¿Qué es lo que haces?!",
"Pon los papeles sobre la mesa y hazte a un lado...",
"¿Qué? ¿Quién eres?",
"Yo soy ",
", capitán de un barco pirata, nada menos. Te lo voy a dejar muy claro: si no me das esos papeles ahora mismo, tendré que recurrir a medidas menos caballerosas.",
"¡¿Pirata?! ¡Oh, no!",
"Así es; has oído las historias, ¿eh? Bien. Así que sé amable y haz lo que te digo.",
"Toma los papeles, ¡no me hagas daño!",
"Así está mejor. Hum, veo que no solo tienes problemas para recordar los números; lo tienes todo anotado, incluyendo nombres...",
"¡Te arrepentirás de esto!",
"Creo que tú serás el único con algo de lo que arrepentirse cuando le muestre estos papeles a las autoridades.",

};
