string DLG_TEXT[47] = { 
"¿No ves que estoy de servicio? No me molestes.",
"Está bien, está bien.",
"¿Querías informar de algún delito?",
"No, desde luego que no. Al fin y al cabo soy capitán..., pero ya veo que no estás escuchando.",
"Recuerda: no permitimos que haya peleas en las calles. Por supuesto, puedes defenderte si alguien te ataca.",
"De acuerdo, tendré en cuenta esa información.",
"No hay quien aguante este clima..., y tengo que quedarme aquí quieto. Tal vez no me creas, pero mi único pasatiempo consiste en espantar las moscas que intentan posarse en mi cara.",
"Es una pena, pero no puedo ayudarte. Es tu deber.",
"Si quieres charlar, búscate a otro. Estoy cumpliendo con mi deber y mi deber no incluye hablar contigo.",
"Solo me preguntaba si estabas vivo o no. Estás ahí plantado como una estatua.",
"¿Crees que es fácil proteger nuestra ciudad? ¡Pues no! Es un trabajo muy importante y peligroso. Me acuerdo que una vez...",
"Otro día me lo cuentas. Tengo que irme.",
"Vete, no me molestes.",
"Lo que tu digas, soldado.",
"¡Eh! ¿Por qué no me traes un vaso de ron de la taberna?",
"Tal vez. Pero, ¿no me colgarán por ayudar a emborracharse a un soldado de servicio? No, espera a que cambien la guardia y entonces podrás beber tanto como te plazca.",
"¡¿Por qué siempre tienen que ser rudos marineros los que intentan hablar conmigo?! ¿Es que no hay chicas guapas en esta ciudad?",
"¿A esto lo llamas cumplir con tu deber? Oye, no querrás dejar escapar a un criminal peligroso como yo, ¿no? ¡Ja, ja!",
"Se te ve muy saludable. ¿No quieres alistarte en nuestro ejército? Tenemos mucho espacio en los barracones, buena comida y ron gratis.",
"Suena bien, pero no puedo aceptar la oferta. La disciplina militar no va conmigo.",
"Qué calor... Daría lo que fuera por volver mi Inglaterra natal.",
"Sí, no parece que te siente bien este clima.",
"¿Adónde vas? ¡Vuelve aquí!",
"Tranquilo, soldado. Tengo que hablar con el gobernador.",
"¿De qué?",
"De un asunto muy importante. ¡Debo decirle al gobernador que los soldados franceses han tomado #sOxbay#! ¿Puedo irme ya?",
"¡Menuda noticia! ¡Pero de todas formas tendrás que esperar a Su Excelencia hasta mañana! Puedes alquilar una habitación en la taberna.",
"Qué mala suerte...",
"¡Menuda noticia! ¿Por qué no me lo dijiste antes? Entra inmediatamente.",
"¡Eso está mejor!",
"¿Qué quieres?",
"¡Serás... hip... serás bellaco! ¡Has hecho daño a... hip... mi amigo!",
"¿Qué amigo? Si no hay nadie contigo, ",
".",
"¿Qué? Estaba... aquí hace un momento. Iré a buscarlo. ¡Tú... hip... espera aquí si quieres que te zurre!",
"¡¿Cómo te atreves a llevarme la contraria?! ¡Te voy a estrangular!",
"Lo siento, pero tengo ordenes de no dejar que nadie visite al gobernador.",
"¿Por qué?",
"Su Excelencia nos ha dado esas órdenes, ",
".",
"Pero tendrás que hacer una excepción en este caso. Voy a informar al gobernador de algo muy importante. En esta carta se explica todo.",
"Desde luego. Puedes entrar. Pero que no te acompañe nadie.",
"¡Diablos! Por supuesto. Muchachos, esperadme en el barco. Volveré enseguida.",
"Está bien, veamos... Bien, parece que hay órdenes del gobernador para que te dejemos entrar.",
"Entonces, ¿puedo entrar?",
"Sí. Supongo que no te acompaña nadie. De lo contrario, tendré que dejar fuera a tus amigos.",
"Tranquilo, no hay nadie conmigo.",

};
