string DLG_TEXT[179] = {
"He oído que quieres verme. Entonces, ¿qué asuntos tienes conmigo?",
"Me gustaría ofrecer mis servicios.",
"Así que eres capitán de un barco. ¿Cómo te llamas?",
"Mi nombre es ",
", capitan del '",
"'.",
"Bien, recordaré tu nombre. ¿Qué te trae por aquí?",
"Me gustaría hablar de negocios.",
"Nada. Me voy, con permiso.",
"Puedes irte. Pero no desaparezcas por completo, es posible que tenga planes para ti.",
"A la orden, #saddr#.",
"Estoy escuchando. ¿Qué te trae por aquí?",
"Negocios, #saddr#.",
"Me voy.",
"Entonces, hablemos de negocios.",
"Estoy aquí en nombre de esas mujeres que están junto a la entrada.",
"Tu misión ha sido un éxito. Los niños desaparecidos han sido devueltos a sus familias.",
"Quiero hablar de un hombre que cuenta con el favor de Su Señoría.",
"La misión está cumplida, #saddr#.",
"No tengo nada que discutir en este momento, #saddr#",
"Si, ya lo sé, aquí esta tu recompensa. Espero que en el futuro pueda volver a utilizar tuse servicios.",
"En cualquier momento, #saddr#",
"Entonces, ¿de quién quieres hablar?",
"Un bucanero, #sBernardo Gamboa#, #saddr#.",
"",
"",
"Ah. ¿Ese hombre? ¿Y qué quieres que diga? Por lo que sé, su reputacion es impecable...",
"Nada más lejos de la verdad. Por lo que sé, secuestro a una chica de esta ciudad.",
"Ah, ah, ah. ¿Lo sabes con certeza? No quiero insultarlo injustamente.",
"Con el permiso de Su Excelencia, investigaré este asunto en privado. Nadie sabrá de la participación de Su Excelencia. Si él no secuestró a esta chica, la relación de Su Excelencia con él permanecerá intacta; si lo hizo, entonces Su Excelencia mostrará a todo el mundo cuán justo y poderoso es.",
"Hum... Eso me parece razonable. De hecho, no arriesgo nada en este caso. Puedes averiguar qué está pasando. Si tu misión termina con éxito, te recompensaré. Pero, ya que esta es tu propia iniciativa, será una suma modesta.",
"Gracias, #saddr#.",
"Recuérdame, ¿de qué estábamos hablando?",
"Estábamos hablando de una chica secuestrada.",
"Ah, sí, lo recuerdo. Según tengo entendido, realmente fue secuestrada.",
"Sí. El canalla no quiso devolver a la chica y fue degollado por sus propios hombres.",
"Bueno, no hay pirata, no hay problema. Aquí está tu recompensa. Ahora ya puedes salir de mi habitación...",
"Como guste.",
"Ah, eso es lo que querías discutir...",
"No entiendo por qué Su Excelencia no se toma esto más en serio. ¿No es responsabilidad de Su Excelencia proporcionar seguridad a los ciudadanos de la colonia?",
"Capitán, te perdonaré que me critiques por esta vez. No lo hagas de nuevo si quieres encontrar favor en este despacho\n En cuanto a esas mujeres... Puedo ver que eres inteligente, así que, te diré algo.",
"Soy todo oídos.",
"Dos soldados fueron encontrados muertos hoy. Uno de ellos tenía un pedazo de tela carmesí en la mano\n Varias horas antes de que fueran descubiertos, una fragata fue vista alejándose de la isla a toda vela.",
"¿Y hasta ahí llega la investigación?",
"Bueno... Es obvio que se llevaron a los niños secuestrados de la isla. Bajo las circunstancias, la búsqueda no vale el dinero que se gastará en tal expedición\n Por si fuera poco, podrían estar en cualquier parte. Debes entender eso, capitán. El mar ofrece muchos lugares para esconderse\n En cualquier caso, si te conmueve tanto el dolor de esas mujeres, te planteo el desafío de encontrar a sus hijos\n Te prometo que si la busqueda llega a buen puerto, te mostraré mi gratitud.",
"Muy bien, estoy de acuerdo, pero primero me gustaría saber dónde puedo encontrar un testigo que viera la fragata.",
"No, no quiero gastar mi tiempo en tales tonterías.",
"¿Aceptas? ¡Perfecto! Puedes encontrar al testigo en la taberna. Fue un capitán mercante quien avistó ese barco.",
"Gracias, ¿puedo retirarme?",
"Deseo servir a Holanda, Excelencia.",
"Holanda siempre se complace en aceptar nuevos capitanes a su servicio. ",
"Actualmente, ",
"no",
" estamos en guerra contra ",
"el gobierno ",
"ninguna nación",
". Por supuesto,",
", pero",
" los piratas siempre deben ser hundidos en cuanto sean avistados.",
"Haré que Su Excelencia se sienta orgulloso.",
"¿Como está mi hoja de servicios, señor?",
"Has hundido ",
" barcos franceses, ",
" barcos piratas, un total de ",
" barcos.",
"Gracias.",
"Espero que haya quejas de mi servicio, Excelencia.",
"¡Claro que no, capitán! De hecho, es un placer para mi otorgarte una comisión en la Armada de Su Alteza Real. Como oficial se te recompensará por cada barco que hundas al servicio de Holanda.",
"Su Excelencia me honra, y trataré de estar a la altura de la confianza que Su Alteza Real ha puesto en mi.",
"Me gustaría cobrar mi salario, señor.",
"Bueno, has hundido ",
" barcos franceses, ",
" barcos piratas, ",
" barcos en total. Tu salario actual asciende a ",
", así que un total de ",
"Gracias, señor.",
"¡Escoria traidora! Conque hundiendo los barcos de tus compatriotas, ¿eh? Por la presente, se te expulsa del servicio, tu nombre queda borrado de las listas, ¡y no quiero volver a ver tu cara en esta ciudad!",
"...",
" desde la última vez, aquí están tus ",
" piezas de oro",
"He oído que se me ha concedido un ascenso.",
"¡En efecto! Excelente trabajo. Tu nuevo rango es ",
"Gracias, señor.",
" barcos españoles, ",
" barcos ingleses, y ",
"Oh, ¿sí? Tengo una propuesta para ti, capitán.",
"¿De verdad?",
" Me he enterado de que has completado la tarea con éxito; ¡mi enhorabuena, capitán! Aquí está tu recompensa.",
" Muchas gracias; ha sido un placer ayudar.",
"Debes destruir un barco de ",
" vessel ",
"quest pirate",
", que amenaza el tráfico marítimo en aguas de ",
". Si lo hundes, te recompensaré con la considerable suma de ",
" piezas de oro. ¿Qué dices, capitán?",
"Prometo a Su Excelencia que no volverá a saber de ese barco.",
"Me temo que no puedo ayudar.",
"Suplico el perdón, Excelencia.",
"Me gustaría saber más acerca de las relaciones de #sgov_nation# con otras naciones.",
"Quiero conseguir una patente de corso.",
"Ah, ",
", que alegría que nos honres con tu visita. Me gustaría presentarte a mi ",
". Vendrá una vez que hayamos termiando con nuestros asuntos.",
"No puedo seguir sirviendo a ",
", Excelencia.",
"Me he hartado de servir a ",
"Como garantía de tus capacidades como capitán, y para compensar el tiempo que voy a perder en presentar tu caso a ",
", debo pedirte ",
" piezas de oro.",
"De ninguna manera.",
"Muy bien.",
"A la luz de tus anteriores servicios, ",
" te otorga el rango de ",
"Has dañado los intereses de ",			 
", y ",
" no olvida a sus enemigos. ¡Vete inmediatamente, o los guardias te echarán a patadas!",
"...",
"Has causado a ",
" grandes daños, capitán, pero ",
"está dispuesta a pasar por alto tus transgresiones pasadas... por un precio: ",
"Muy bien, Excelencia. Acepto.",
"Un placer tratar contigo, ",
"Y con Su Excelencia.",
". Ademas, se te concede un premio de ",
" acres de tierra por orden de ",
"¿Seguro, ",
" lamentará perder tus servicios.",
"Sí, seguro.",
" no ve con buenos ojos a los chaqueteros, ",
"Hum..., no he diho nada.",
"Muy bien. Pero espero que lo reconsideres, con tiempo...",
"Adiós, ",
"¿Eh?",
"Se siente.",		 
"Capitan, ¿cuál es el objeto de tu venida?",
"Excelencia, estoy trabajando para el gobernador de #sisland_Conceicao#. Debo entregar a Su Excelencia esta carta y llevar de vuelta la respuesta a la petición de mi gobernador.",
"Muy bien, Dame la carta.",
".......",
"(Unos minutos después) ¿Cartagena? Una acción militar contra esa ciudad tan bien defendida... Sería demasiado peligroso, incluso si nuestras naciones aunaran sus esfuerzos.",
"En realidad, esta operación no tiene por objetivo la captura de la ciudad. Sabemos que no tenemos suficientes fuerzas para eso. La idea sería ejecutar una acción rápida y espectacular para desmoralizar a los españoles en el Caribe, y tal vez en todo el mundo.",
"Ya lo entiendo mejor... Continúa.",
"En cualquier caso, solo necesitaríamos un pequeno número de soldados experimentados. Por supuesto, antes de comenzar la operación, iré allí para confirmar que se dan las condiciones para llevar a cabo esta operación.",
"Ese ya parece un proyecto más realista.",
"¿Puedo informar a mi gobernador de que Su Excelencia acepta participar en una posible operación?",
"Sí, si me puedes asegurar que no será una misión suicida. No aceptaré perder a mis soldados en una operación desastrosa.",
"Lo entiendo. Se tomarán todas las precauciones. Informaré a Su Excelencia en las próximas semanas.",
"No te preocupes, elegiré a los mejores hombres de mi guarnición para la operación.",
"Gracias, Excelencia. El gobernador de #sisland_Conceicao estará encantado de conocer esta respuesta.",
"¿Necesitas mi ayuda para alaguna otra cosa?",
"Para la primera fase de mi misión en Cartagena, me gustaría que el capitán Elting viniera conmigo. Hemos trabajado con éxito en el pasado y él podría facilitar mi tarea.",
"Por supuesto, llevátelo. No tengo ninguna misión para el capitán Elting en este momento.",
"Gracias y hasta pronto, señor.",
"¿Sí, kapitein? ¿Qué haces aquí?",
", Su Excelencia está bajo arresto. El cargo es corrupción, especificamente la retirada de fondos de las arcas públicas para uso propio.",
"¡Absurdo! ¿Bajo qué autoridad pretendes arrestarme?",
"Bajo la autoridad de este uniforme, y a falta de ella, bajo la autoridad de esta espada. A menos que Su Excelencia desee desafiar esa autoridad, por favor, ruego que me muestre su libro de cuentas y caja de caudales.",
"Muy bien, pero primero quiero saber tu nombre. ¡Cuando esto termine, puedes tener por seguro que responderás por esta atrocidad!",
"Soy el Kapitein Mart-jan van de Weg, Tercera Compañía de Infantería. Y ahora, el libro de cuentas y la caja de caudales, por favor.",
"Muy bien. Están en ese cofre de allí.",
"Gracias.",
"¿Oh? ¡No pareces el tipo de persona que vaya a arrestar a nadie, mucho menos a un gobernador! ¡Soldado! Arresta a esta persona. Podemos empezar con una acusación de calumnias, luego ir subiendo hasta la traicion.",
"Ups...",
", se te acusa de suplantar la identidad de un oficial del ejército holandés, encarcelamiento injusto, calumnias, y la retirada de fondos públicos por medios fraudulentos.",
"No sé nada de eso, Excelencia. Entré en la ciudad con la intención de llevar a cabo negocios legales, e inmediatamente los soldados me atacaron y me trajeron aquí.",
"¿Así que lo niegas? Entonces, llamaré a mi primer testigo. ",
", ¿es esta la persona que te robó el uniforme?",
"Sin embargo, hemos establecido que robaste el uniforme de este soldado. Entonces, evidentemente, lo decoraste con la insignia de un Kapitein. Y ahora llamo a mi siguiente testigo. ",
", ¿es esta la persona a quien ayudaste en su escandalosa acción, llevada a cabo en este mismo salón?",
"Está bien, lo admito. Sí, fui yo quien robó el dinero. Pero ",
" no tiene culpa. Él creyó que yo era un auténtico Kapitein y que estaba siguiendo órdenes. No recibió nada del dinero. Asumo toda la responsabilidad de mis acciones.",
"Muy bien. Eso te honra, al menos. Sin embargo, en vista de la gravedad de tus crímenes, to sentencio a 15 años de prisión. ¡Guardias! Lleváos al prisionero.",
"¡Quince años!",
"Ah, ",
", he recibido un documento bastante peculiar que te concierne.",
"¿Qué tipo de documento? ¿Qué tiene de peucliar?",
"Al parecer, nada menos que el mismíismo Stadtholder ha leídoacerca de sus hazañas. Por razones que no alcanzo a comprender, aparentemente encontró el relato divertido\n Déjame ver... 'afable sinvergüenza'..., 'muestra lo bien que se respeta el uniforme de uno de mis oficiales'... Bueno, ¡tú no mostraste mucho respeto por el uniforme!\n En cualquier caso, la conclusión es que él ha ordenado que se te conceda un indulto.",
"¿Indulto? ¿Eso quiere decir que soy libre?",
"Sí, eso es lo que quiere decir. Te aseguro que tu sorpresa no es menos que la mía. También te aseguro que, si cometes algún otro delito en mi ciudad, Su Señoría el Stadtholder no tendrá tiempo de leerlo antes de que te mande ahorcar. Ahora, ¡fuera de mi vista!",
"Gracias, Excelencia. Y por favor, transmita mi agradecimiento al Stadtholder.",
};
