string DLG_TEXT[60] = {
"Ah, ¡Una cara nueva en mi taberna! ¡Te doy la bienvenida, ",
"! ¡La mejor hospitalidad del archipiélago está a tu disposición!",
"Hola. Mi nombre es ",
".",
"Gracias. Mi nombre es ",
".",
"De nada. ¡Por favor, toma asiento, bebe un buen ron, prueba una de mis especialidades! Te alegrarás de haberlo hecho.",
"Me alegro de volver a verte, ",
". Siéntate a cualquiera de las mesas libres y descansa tus huesos.",
"¡Oh, eres tú! Hace siglos que no te veía. ¿Puedo empezar por servirte una copa de vino para remojar tu gaznate?",
"Si no te importa, me gustaría ir directamente al grano.",
"Tengo poco tiempo, amigo, y muchos asuntos serios que discutir.",
"Lo siento. Tengo demasiadas cosas en mente para pensar en la hospitalidad en este momento.",
"Relájate. Solo vine a ver quién estaba por aquí, ya me voy.",
"Es un placer conocerte, ",
". Mi nombre es ",
".",
"Por supuesto, ",
", tú mandas. ¿Cómo puedo ayudarte?",
"Quiero añadir algunas manos más a mi tripulacion. ¿Podrías indicarme a alguien que pueda estar buscando trabajo?",
"Las batallas más recientes me han dejado con cierta escasez de personal. Necesito encontrar algunos muchachos que busquen trabajo.",
"Me gustaría hablar de negocios.",
"¿Tienes una habitación disponible? Me gustaría quedarme aquí un tiempo.",
"Estoy buscando una habitación limpia, con una cama limpia. Nada más, nada menos.",
"Ahora no tengo tiempo para hablar. Volveré más tarde.",
"Lo siento, ahora tengo mucho que hacer. Pero volveré para charlar cuando esté libre.",
"¡Claro que sí! ¿Y de qué negocios quieres hablar?",
"Necesito trabajo. ¿No conoces a algún niño rico en esta isla que tema viajar solo?",
"¿Sabes?, ahora que lo pienso, no tengo ningún negocio que tratar contigo.",
"Es tarde para eso. Tendrás mejor suerte si vuelves por la mañana. ¿O tal vez te gustaría pasar una noche en la taberna?",
"Tal vez sí. ¿Tienes una habitación libre?",
"Tal vez lo haga. Pero déjame preguntarte algo primero.",
"Tengo una habitación disponible. ¿Cuánto tiempo planeas quedarte?",
"Hasta mañana.",
"Solo hasta el anochecer.",
"Bien. Te costará 5 monedas de oro.",
"Muy bien. Aquí tienes.",
"En ese caso, me temo que mi bolsa y yo pasaremos la noche en la sala común.",
"No, gracias. Si ese es el precio, me ahorraré unas monedas y pasaré la noche en la sala común.",
"Tal vez más tarde. Déjame preguntarte algo más.",
"Bien. Te costará 5 monedas de oro.",
"Muy bien. Aquí tienes.",
"En ese caso, me temo que mi bolsa y yo pasaremos la noche en la sala común.",
"No, gracias. Si ese es el precio, me ahorraré unas monedas y pasaré la noche en la sala común.",
"Lo pensaré. Gracias.",
"¡Por favor! ¡Detener esta locura de una vez! ¡No me hagáis llamar a los guardias!",
"¡Está bien! Ya me voy.",
"Si hay alguna persona así, seguramente prefiera no llamar la atención innecesariamente navegando con demasiada compañía.", 
"Sí, lo olvidé. De acuerdo, volveré más tarde, cuando tenga menos barcos, ¡ja, ja!",
"No quiero ayudarte. Has causado muchos problemas a mi país",
"Vaya, tenemos un patriota. Bien, adiós", 
"Tus manos están manchadas de sangre. No pensarás en serio que alguien viajaría contigo, ¿verdad?",
"Tienes razón, ¡todo el mundo me teme! ¡Ja, ja!",
"Llegas justo a tiempo. Un mercader estaba buscando una buena escolta con la que viajar. Deberías hablar con él. Aquí está, justo ahora está entrando en la taberna.",
"Eso haré.",
"No, no hay nadie así en este momento. Quizás la próxima vez.",
"Hum, entonces esperaré.",
"Estoy buscando a alguien que conozca los caminos de la selva, y que tal vez haya encontrado un viejo templo.",
"¡Ah, sí! Mauricio Juradu dijo algo acerca de cómo escapó por los pelos de un templo rodeado de indios.",
"¡Gracias! Parece que quizás pueda ayudarme.",
};
