string DLG_TEXT[173] = { 
"Saludar, ",
". Desafortunadamente, no he tenido el honor de conocerte antes, pero puedo decir que eres el capitan de ese barco en el puerto.",
"Y que? No tengo tiempo para charlar con marineros.",
"Estoy ",
". De que nave hablas exactamente?",
". Es tuya, ?verdad?, ",
"buque, ",
"?",
"Como adivinaste?",
"Esa puede ser mi nave. Pero no es asunto tuyo. Vete.",
"No fue dificil, ",
". Te vi llegar a tierra. Estoy ",
".",
"Ya veo. Bueno, fue agradable hablar contigo.",
"No tienes algo mas interesante que hacer que ver barcos entrando y saliendo del puerto?",
"Desafortunadamente, he sido relevado de deberes por violar las reglas de la nave.",
"Eso es muy malo. No puedes hacer algo al respecto?",
"Eso es desafortunado. Bueno, !buena suerte y buen dia!",
"Bien... tal vez si un respetado capitan fuera puesto en una palabra para mi al capitan del puerto... pero a quien le importo yo ",
"?",
"Hmm... Intentare hacer algo al respecto.",
"Podria hablar con el capitan del puerto, pero necesitaria algo de TI para hacerlo.",
"Lo siento ,no puedo ayudarte.",
"Realmente, ",
" Bueno, capitan, si puede ayudarme le prometo que no lo olvidare.",
"Vamos, eso no es lo que busco.",
"Bueno, en realidad, no tengo tiempo para ayudarte.",
"Oh. Por lo tanto, su generosidad tiene un precio cuando se trata de su projimo, ",
". Pero tengo algo que ofrecer.",
"Bueno, vamos a escucharlo entonces ",
"Probable. No lo creo.",
"Hey, no, capitan. Me vas a ayudar y te voy a devolver el favor, !asi es como soy!",
"Dejame hablar primero con el capitan del puerto.",
"Por cierto, ?donde puedo encontrar al capitan del puerto?",
"Pues bien, no hay mucho que yo pueda hacer excepto simplemente ver barcos entrar y salir del puerto. Adios, capitan!",
"Despedir.",
"Conozco a alguien que pagara muy buen dinero a cualquiera que puedaincarle ciertas tareas. si me ayudas, te lo presentare. Confia en mi y estoy seguro de que le sentara bien.",
"Hmm...eso es interesante. Muy bien, tratare de ayudarte.",
"Por cierto, ?donde puedo encontrar al capitan del puerto?",
"Tal vez esta en ese edificio frente a las puertas de la ciudad ",
"AHA, gracias.",
"Oh, ",
"! Saludar, ",
".",
"Saludar, ",
". Pense que nunca nos volveriamos a ver...",
"Oh, eres tu otra vez, ",
". Me alegro de verte sana y salva.",
"Asi que nadie decidio ayudarte, ",
"?",
"Saludar. Y adios! Estoy ocupado.",
"Exactamente, ",
". Tendre que despedirme del mar.",
"Esta bien, te ayudare.",
"Que hay para mi?",
"No es culpa de nadie, sino tuya. Hasta la vista.",
"Realmente, ",
"! Bueno, capitan, si puede ayudarme le prometo que no lo olvidare.",
"Vamos, eso no es lo que busco.",
"Bueno, en realidad, no tengo tiempo para ayudarte.",
"Oh. Por lo tanto, su generosidad tiene un precio cuando se trata de su projimo, ",
". Pero tengo algo que ofrecer.",
"Bueno, vamos a escucharlo entonces",
"Probable. No lo creo.",
"Hey, no, capitan. Me vas a ayudar y te voy a devolver el favor, !asi es como soy!",
"Dejame hablar primero con el capitan del puerto.",
"Por cierto, ?donde puedo encontrar al capitan del puerto?",
"Pues bien, no hay mucho que yo pueda hacer excepto solo para ver los barcos que entran y salen del puerto. Adios, capitan!",
"Adios.",
"Conozco a alguien que pagara muy buen dinero a cualquiera que puedaincarle ciertas tareas. si me ayudas, te lo presentare. Confia en mi y estoy seguro de que le sentara bien.",
"Hmm...eso es interesante. Muy bien, tratare de ayudarte.",
"Por cierto, ?donde puedo encontrar al capitan del puerto?",
"Hey, es ",
"! Saludar, ",
".",
"Saludar, ",
". Nunca pense que nos volveriamos a ver algun dia...",
"Oh, eres tu, ",
". Me alegro de verte sana y salva.",
"Tuviste exito?",
"Voy a ver al capitan del puerto ahora.",
"Todavia no. Lo siento, hablemos mas tarde.",
"Por cierto, donde puedo encontrar al capitan del puerto?",
"Oh, lo siento, no quiero apresurarte, ",
". Estoy tan cansada de estar aqui en la tierra!",
"No vas a estar aqui mucho tiempo. Yo me encargo.",
"Escucha, tengo un par de preguntas para TI. Eres un marinero experimentado, ?no?",
"Me gustaria preguntarle sobre la navegacion.",
"Eso espero, ",
". Me encantaria invitarte a una Copa, pero soy capitan y tu solo eres un marinero.",
"Ja! Ofreceme eso antes de zarpar.",
"Pero un marinero puede beber con un capitan!",
"Sera dificil encontrar un mejor marinero que yo entre aqui y #sisland_Redmond#, ",
"!",
"Entonces comparte tu experiencia conmigo.",
"Hmm, bueno, esta bien, te vere mas tarde.",
"Apenas puedo darte un Consejo sobre navegacion o maniobras ya que no soy un oficial. \n Pero en cuanto a algunas otras cosas ЃEestare encantado de ayudarle.",
"Perfecto. ?Que puede decirme sobre lo que el capitan debe saber?",
"Como debo tratar a mi tripulacion?",
"Que tal un par de consejos de marineros?",
"Hmm, no puedo decirte sobre navegacion o comercio pero algunas cosas son vitales para nosotros los marineros. Es por eso que tenemos que aprender nosotros mismos para no quedar atrapados con nuestros pantalones abajo!",
"?Que quieres decir?",
"Lo primero y lo mas importante es una defensa. Si un capitan no puede organizar adecuadamente a su tripulacion en un barco, entonces el fuego pesado cubrira la cubierta con sangre la mejor defensa, menos bajas.",
"Continua, te escucho..",
"Ya veo, gracias por aclararmelo.",
"Nunca descuides a tu tripulacion, a menos que tengas ganas de encallar o estar a la deriva. Una tripulacion es el corazon de un barco, y el capitan no sera capaz de dirigir su barco solo. \n Si usted no tiene suficientes personas en su equipo entonces la nave sera tan torpe como un cachalot.",
"Los marineros tambien son personas. Nadie lo duda.",
"Creo que te dare algunos sabios consejos para los jovenes capitanes, que a menudo corren de cabeza a la batalla y pueden quedar atrapados por un numero abrumador.\n cuando usted esta tratando de torre, x, es mejor perder su carga que su cabeza.",
"Ya veo. ?Algo mas?",
"Adios, gracias por tu Consejo.",
"Lo siguiente que necesitas saber es un poco de esgrima. Algunos dicen que solo un capitan4 saber hacer eso, pero los marineros tambien saben un poco al respecto.",
"!Genial! Me gusta como suena eso.",
"Supongo que es suficiente informacion para mi por hoy. Hasta la vista.",
"La moral es muy importante para su tripulacion tambien. Si la tripulacion no esta contenta con su capitan, mutiny no esta muy lejos.",
"Cambiemos de tema.",
"Gracias, hablaremos de eso en otro momento. Despedir.",
"Yo digo, ",
". Nunca pelees con los guardias de la ciudad. Nunca pelean limpio. te atacaran a la vez y te ataran de pies y manos. Es mejor pelear con 3 piratas que con un monton de guardias.",
"Cambiemos de tema.",
"Gracias, hablaremos de eso en otro momento. Despedir.",
"Una cosa mas importante es como abordar a tu enemigo. Su tripulacion tiene que aprender a lanzar grapples y la cuerda\no a una nave que desea abordar. Tendran que ser capaces de hacerlo a diferentes velocidades y distancias.",
"Es gracioso, cuando das consejos no lo haces.",
"Gracias, hablaremos de eso en otro momento. Despedir.",
"Lo siento, ",
". Me deje llevar por el momento.",
"Muy bien. Cambiemos de tema.",
"Bueno, gracias por la informacion. Despedir.",
"Ah, ",
"Saludar, ",
".",
"Saludar, ",
". No pense que nos volveriamos a ver...",
"Ah, eres tu otra vez, ",
". Me alegro de verte sana y salva.",
" Hay algun resultado?",
"Ay!, ",
". No conduje para hacer nada.",
"Todavia no, lo siento, hablemos mas tarde.",
"Eso es muy malo, pero de todos modos, gracias por tu ayuda,",
".",
"No te enfades, ",
". Te llevare a mi nave.",
"Escucha, tengo un par de preguntas para TI. Eres un marinero experimentado, no?",
"Me gustaria preguntarle sobre la navegacion.",
"Bueno, ?como estoy, capitan?",
"Puedes invitarme un trago, Rys.",
"Aun no he resuelto este problema.",
"Es realmente tan malo, ",
"?",
"Supongo que no, por el rec, se puede llegar a ser empleado en un barco...",
"Gracias, capitan! !A decir verdad, en el fondo de mi corazon no creia que fueras capaz de hacer eso!",
"Has subestimado mis talentos.",
"Buena suerte, ",
"! Nos vemos.",
"Admito que lo hice asi. que puedo hacer por TI?, ",
" Dejame mostrarte mi gratitud.",
"Agradecer, ",
", pero no necesito nada. Hasta la vista.",
"Por cierto, pense - ?quizas te uniras a mi tripulacion como mi oficial?",
"Bueno, supongo que una conferencia mas no haria dano.",
"Es perfecto para mi.",
"! Necesito un poco de dinero para terminar mi negocio aqui.",
"Cuanto necesitas?",
"500 de oro. Acto que es mucho dinero.",
"Trato hecho, aqui esta el dinero.",
"En serio, es una gran suma. No puedo permitirme eso ahora.", / / PB: Cambiado para salvar la confusion
"capitan. Es bueno verte y bueno que sigas vivo. Es peligroso ser capitan estos dias.",
"Escuchar, ",
", podria por favor decirme que hace a un buen capitan una vez mas?",
"Por cierto, pense - ?quizas te uniras a mi tripulacion como mi oficial?",
"Bueno, creo que ya lo se. Despedir.",
"Cuales seran las ordenes, capitan?",
"Ninguno.",

};
