string DLG_TEXT[74] = {
"Hola, mi nombre es ",
"pero mis amigos me llaman ",
".",
"Es un placer conocerte, ",
"mi nombre es ",
". Lo siento, pero tengo asuntos que atender, hablemos en otro momento.",
"Hola, belleza, mi nombre es ",
", pero para TI soy justo ",
". Hasta luego.",
"Hola! A trabajamos por tu nombre eres la hija del dueno de esta tienda, ?no?",
"Hola preciosa, ?no es tu padre el que esta de pie junto al serviran?",
"Estoy tan contenta de verte, ",
"!",
"Todos en la ciudad pag. de TI y de tus hazanas!",
"Si, si, pero ahora tengo prisa.",
"Ahora no! Siento haber sido un poco grosera a veces pero conozco mi trabajo muy bien. Tengo cosas que hacer ahora pero hablare contigo mas tarde.",
"...",
"...",
"...",
"...",
"...",
"He oido hablar mucho de TI, ",
". Todos dicen que eres la unica mujer pirata...",
"La gente se equivoca, no soy un pirata, soy un capitan ejercitos.",
"Por favor no se dirija a mi tan sin contemplaciones. Soy el capitan, ",
", y no me llames de otra manera en publico. ?Me entiende?!",
"No has cambiado de opinion, ?verdad? !Por favor, sacame de aqui!",
"Por favor no se dirija a mi tan sin contemplaciones. X soy un capitan. ",
"Ya te pedi que no te dirigieras a mi tan sin contemplaciones en publico. Soy el capitan, ",
", y no me llames de otra manera?!",
"Oh, lo siento, ",
".",
"Quieres hablar conmigo de algo en particular o solo me estas haciendo perder el tiempo?",
"Estas probando mi paciencia con esta charla ociosa. ?Tienes algun negocio para mi o no?",
"Tengo negocios para TI. !Eres mi Ultima esperanza!",
"A juzgar por el tono de su voz usted esta planeando algunos sombra de empresa y quieres participar.",
"Vaya, en serio! ?Soy tu 'Ultima esperanza'? Que interesante! Muy bien, dinos que tipo de negocio tienes para mi.",
"Lo siento, pero no tengo tiempo para resolver tus problemas.",
"Eso es una tonteria, pide ayuda a tu papa y no me lo impidan.",
"Gracias por aceptar escucharme. La cosa es que no puedo quedarme mas tiempo con mi padre. Es una buena persona pero quiere casarme con alguien.",
"Que hay de malo en eso para una chica como tu?",
"Que tiene de malo casarse? Una vez que le pongas las manos encima a tu marido, podras girarlo alrededor de tu dedo menique.",
"Quiere casarte con alguien contra tu voluntad? Eso no es justo, y acto por que estas enfadada con el, pero ?como puedo ayudarte?",
" Sin preguntarte si estas de acuerdo o no? !Que padre! Esos padres deberian ser colgados de un yardarm! Pero aun asi, no puedo entender lo que querrias de mi.",
" Por que? Pense que me entenderias con seguridad. !No quiero casarme con nadie! Quiero ser independiente y libre!",
"Yo diria que tienes deseos bastante extranos para una mujer joven, pero ?que quieres de mi?",
"Que puedo decir? Entonces asuman de casa. No veo que tiene que ver esto conmigo.",
"Sacame de aqui, te lo ruego! Quiero navegar en su barco y admirar el mar y...",
"Espera, espera, espera! ?Realizando quieres que te secuestre de tu padre?",
"Oye! Espera un segundo! ?Quieres que arriesgue mi vida para resolver tus insignificantes problemas?",
"No, no lo hare. Eres una chica joven e inexperta. Todos ustedes se arrepentiran demasiado pronto de esa decision.",
"AHA, como si no tuviera nada mas que hacer que ayudarte, tengo mis propios problemas que resolver.",
"Bueno, cuando te vi pense que podrias ayudarme pero si crees que esto es 'mezquino'...",
"Calmar. ?De verdad prefieres navegar a la comodidad de un buen hogar?",
"Deja de lloriquear! ?De verdad quieres dejar tu casa y esa vida pacifica por una vida en alta mar?",
"Bueno, te acto muy bien pero no creo que tenga el derecho de entrometerme en tu vida. Vivir como todo el mundo vive y ser feliz.",
"Tienes razon, tus deseos son solo los caprichos mezquinos de una nina mimada y mimada.",
"Si, he estado sonando con viajar durante anos. Quiero ver muchos lugares interesantes, conocer gente nueva y no esconderme a espaldas de mi padre y dejar que el decida lo que debo hacer con mi vida.",
"Esta bien, puedo llevarte conmigo, pero por favor no pienses que navegar siempre esta libre de preocupaciones.",
"Esta bien, esta bien. Mi barco esta en el puerto e informare a mi tripulacion para que le permitan conversacion a bordo, pero si se queja de algo durante el viaje le dare de comer a los tiburones.",
"Estas equivocado. Cuando viajas no solo ves lugares nuevos e interesantes, sino que a menudo te encuentras en situaciones peligrosas. Seria mejor que te quedaras en casa.",
"Bueno, no te escondas detras de la espalda de tu padre. !Vive tu vida, disfrutala y haz lo que quieras, las opiniones de tu padre estan malditas! ",
"Oh, muchas gracias, capitan ",
"Voy a empacar mis cosas de vez en cuando y luego ire a tu nave.",
"Bien, pero no llegues tarde, vamos a zarpar pronto.",
"Ni se te ocurra quitarte toda la ropa, solo lo necesario.",
"Probablemente tengas razon, gracias.",
"No importa. Ahora dejame ocuparme de mis cosas.",
"Como tu digas, ",
". No me atrevo a retrasarte mas.",
"Por supuesto que no te atreves. No te Aires, chica.",
"Si, me gustaria que mi padre fuera capitan para que yo pudiera navegar con el y pararme bajo las velas blancas como la nieve ondeando en la brisa del mar...",
"Un bonito sueno, pero no podemos elegir a nuestros padres. Muy bien, tengo cosas que hacer.",
"Tonta! Una mujer en el barco trae mala suerte, asi que quedense secos en tierra.",

};