string DLG_TEXT[181] = {
". ¿De qué se trata, ",
"?",
"¿Puedo ayudarte, ",
"?",
"¿Es esta tu primera visita a nuestra ciudad, ",
"? No te he visto antes.",
"Soy ",
", capitán en propiedad del barco '",
"'. Tengo algunas preguntas, si tienes un momento.",
"Mi nombre es ",
". Me gustaría hacerte algunas preguntas.",
"Puedes llamarme capitán ",
". Solo quiero información.",
"Hola, capitán ",
". ¿Qué te trae a nuestra colonia?",
"Ah, capitán ",
". ",
", eres tú otra vez. Espero que tu viaje haya sido agradable. ¿Qué hay de nuevo?",
"Hola, ",
". ¿Cómo puedo ayudarte?",
"¿Me he perdido algo mientras estaba fuera?",
"¿Ha pasado algo interesante mientras estaba fuera?",
"¿Qué historias intercambian los viejos lobos de mar estos días, entre trago y trago de ron?",
"¿Cúal es el último rumor de las tabernas?",
"Busco chismes, rumores, cuentos..., cualquier cosa que no conozca puede ser útil.",
"Dame algunos de tus chismes más frescos, camarada. Hasta el menor cotilleo puede encerrar aventura o posibilidades de ganar dinero.",
"Sigo sin poder encontrar...",
"¡Es imposible encontrar nada en este laberinto! ¿Dónde esta...",
"Me he perdido igual que un piloto borracho. ¡Otra vez!",
"Pareces de por aquí. Dime dónde puedo encontrar...",
"Por favor, dime cómo llegar a...",
"He tenido un día de perros, así que nos ahorrarás a ti a y a mí un mal rato si me dices cómo encontrar...",
"Me gustaría tu opinión sobre un ciudadano local.",
"Necesito saber todo lo que puedas decirme sobre alguien que vive aquí en la ciudad.",
"¿Qué puedes decirme de...",
"Dime todo lo que puedas sobre cierta persona...",
"Espero que puedas decirme algo sobre una persona que tal vez conozcas.",
"Este lugar no es muy grande; apuesto a que conoces a todos los que viven aquí. Hablemos.",
"Háblame de #sSantiago#.",
"¿Qué puedes decirme de este lugar dejado de la mano de Dios?",
"Me gustaría saber más sobre esta hermosa colonia.",
"¿Cúal es la historia de esta ciudad y de la isla?",
"¿Sabes algo de interés sobre #sSantiago#?",
"...",
"Lo siento. Pensé que eras otra persona.",
"Solo estoy de paso. Así que aparta o te aparto.",
"¿Qué te gustaría saber, ",
"?",
"¿Qué te interesa, capitán?",
"¿Qué quieres de mí?",
"Ciudades como esta siempre están llenas de chismorreos. Dime lo más destacado.",
"¿Ha pasado algo interesante por aquí últimamente?",
"Solo quiero saber que está pasando en el vecindario. ¿Alguien ha estafado a un amigo? ¿Alguien ha sido asesinado? ¿El posadero es realmente una mujer? Ya me entiendes.",
"¿Cómo puedo llegar a...",
"¿Puedes ayudarme a orientarme en la ciudad?",
"¿Dónde puedo encontrar...",
"¿Puedes hablarme de alguien que me interese?",
"Me gustaría obtener información sobre un vecino. ¿Podrías ayudarme?",
"Me pregunto qué tiene que decir la gente de la ciudad sobre cierta persona...",
"¿Qué puedes decirme de #sSantiago#?",
"Me gustaría conocer la historia de tu ciudad.",
"Me gustaría obtener información sobre esta colonia.",
"Solo estoy de paseo. Hasta luego.",
"Gracias. Hay una cosa más...",
"Ha sido agradable charlar contigo. ¡Hasta la vista!",
"¡Alguna otra cosa, capitán ",
"?",
"Oigámoslo, ",
".",
"Te escucho, ",
".",
"¿Cuál es la comidilla de la ciudad estos días?",
"¿Qué historias intercambian los viejos lobos de mar estos días, entre trago y trago de ron?",
"Ha pasado mucho tiempo desde que puse un pie en estas costas. ¿Qué me he perdido?",
"¿Podrías darme algunas indicaciones?",
"Me he perdido por completo en estas calles.",
"Es mi primera vez en esta ciudad, y me gustaría que me dieras algunas indicaciones.",
"Me gustaría saner tu opinión sobre un ciudadano local.",
"Necesito saber todo lo que puedas decirme sobre alguien que vive aquí en la ciudad.",
"¿Podrías darme alguna información sobre los lugareños?",
"Háblame de #sSantiago#.",
"¿Qué puedes decirme de esta colonia?",
"Me gustaría saber algo sobre #sSantiago#.",
"Acabo de darme cuenta de que tengo que estar en otra parte. Adiós.",
"¿A quién te refieres,",
"?",
"¿Preguntas por alguien en especial?",
"¿De quién quieres saber exactamente?",
"Me refiero al gobernador.",
"Me interesa el dueño de la taberna.",
"El propietario del astillero.",
"Estoy hablando del comerciante local.",
"Nadie. Olvídalo.",
"He oído que trabaja muy estrechamente con el gobernador de #sHavana#. Pero eso tiene sentido, supongo. Algunos dicen que teme la posibilidad de una invasión desde #sRedmond#.",
"Ya veo. Tengo otra pregunta para ti.",
"Gracias, y adiós.",
"A veces está más borracho que algunos de sus clientes. ¡Eso es muy molesto! Pero la mayor parte del tiempo es un buen tipo.",
"Ya veo. Tengo otra pregunta para ti.",
"Gracias, y adiós.",
"Ha ganado mucho dinero, gracias al importante nudo comercial que hay no lejos de aquí. Los barcos mercantes son frecuentemente atacados por piratas y bucaneros. Supongo que no habría sacado tantos benefiicos si la gente no confiara en la calidad de su trabajo.",
"Ya veo. Tengo otra pregunta para ti.",
"Gracias, y adiós.",
"No voy a la tienda muy a menudo, me gustan más los puestos del mercado, así que no sé nada de él.",
"Ya veo. Tengo otra pregunta para ti.",
"Gracias, y adiós.",
"¿Adónde vas, ",
"?",
"No hay problema, capitán. ¿Adónde tienes que ir?",
"Será un placer guiarte, ",
". ¿Pero adónde quieres ir?",
"¿Cómo puedo llegar a la taberna?",
"¿Dónde está el astillero?",
"¿Dónde puedo vender la mercancía que he traído conmigo?",
"De acuerdo. Empezaremos frente a la mansión del gobernador. Da la espalda a la mansión y tendrás enfrent eun plaza. La taberna está al fondo a la izquierda, se accede por un pequeño tramo de escaleras.",
"Bien. Gracias por tu tiempo.",
"¿Dónde está el astillero?",
"¿Dónde puedo conseguir un precio decente por las mercancías de calidad que he traído a la ciudad?",
"El astillero está en la zona portuaria. Es un edificio de tres pisos cerca de la puerta que sale de la ciudad. ",
"Ya veo. ¿Y la taberna?",
"¿Dónde puedo conseguir un precio decente por las mercancías de calidad que he traído a la ciudad?",
"Creo que eso es todo. Gracias por tu ayuda.",
"¡Tendrás que andar un buen trecho! Ve más allá de la casa del gobernador hasta el gran edificio arqueado. Desde allí, gira a la derecha y busca un edificio grande y marrón con toldos sobre las ventanas.",
"¿Dónde puedo encontrar el astillero local?",
"¿Cómo llego a la taberna?",
"Ya veo. Gracias por la información.",
"No sé porque te interesaría algo así, pero, ¿por qué no?",
"¿Qué es exactamente lo que te interesa, ",
"?",
"Por supuesto, ",
". Afortunadamente, es una historia bastante corta.",
"Me interesa la historia de la colonia...",
"Háblame de la colonia.",
"¿Hay algo en la isla, además de la ciudad?",
"Tengo algunas preguntas más para ti, si no te importa.",
"Fundada el 25 de julio de 1515, #sSantiago# ha sido y sigue siendo un importante puerto para la flota española de Indias.",
"Gracias. Déjame hacerte unas preguntas más.",
"Sabes, realmente pensé que iba a ser más interesante. Déjame preguntarte algo más.",
"Eso es todo lo que necesito. Gracias.",
"Gracias por tu tiempo. Hasta la vista.",
"Bueno, tenemos #sHavana# al otro lado de la isla. También es la isla más grande del archipiélago. Yo aún no la he recorrido entera, así que no puedo darte mucha información.",
"¿Qué más puedes decirme sobre la colonia?",
"¿Qué más puedes decirme?",
"#sSantiago# también es un puerto importante en el comercio de esclavos.",
"Ya veo. ¿Qué más?",
"No. Encontrarás un par de plantaciones y casas en esta parte de la isla, pero en general está poco desarrollada.",
"En ese caso, tal vez me puedes decir algo más acerca de la colonia.",
"Entiendo. Déjame preguntarte algo más.",
"Conoces a un contramaestre llamado Fred Bob?",
"¿Qué puedes decirme del capitán del puerto?",
"Oh, ¿Fred Bob? ¡No es un amotinado, eso te lo aseguro! Es un buen marino, y un hombre fuerte al que merece la pena tener de tu lado cuando te superan en numero. Es una lástima lo de su encarcelamiento. Todos esperamos que el gobernador lo libere, porque nadie más aparte de ese pomposo primer oficial cree que sea culpable.",
"Interesante. Tengo otra pregunta para ti.",
"Muchas gracias, y adiós.",
"No sé como lo hace, pero nuestro capitán de puerto se las arregla para conocer a todos los marinos del archipiélago.",
"Ya veo. ¿Una pregunta más, por favor, si no te importa?",
"Gracias por tu tiempo. Adiós.",
"¿Fred Bob? ¿El contramaestre? Es muy difícil entender lo que dice, pero mi hermano lo conoce bien. No es un amotinado. Ese oficial está equivocado. Todos esperamos que el gobernador lo libere. Su lugar está a bordo de un barco, no en el cepo.",
"Buen hombre, excelente marinero. Yo no creo ni por un minuto que amenazara con amotinarse.",
"Esto..., se me he olvidado por completo sobre quién iba a preguntar. Solo dame un segundo y me acordaré...",
"¿Cómo esta el viejo herrero Tomás hoy en día?",
"¿Te refieres a Tomasina, ¿no? El viejo Tomás murió de repente hace poco, y ahora es su esposa la que maneja el yunque. No se puede decir que ella haga un mal trabajo, la verdad.",
"Oh, cielos... ¿no le dan vahídos dedicándose a esa profesion? No importa; cambiemos de tema.",
"Vaya. ¿Una viuda casadera que puede reparar una espada? Tendré que presentarle mis respetos inmediatamente...",
"Mi espada favorita de todos los tiempos en el mundo ha perdido un poco el filo. ¿A quién puedo confiársela?",
"#sSantiago# no tiene herrero. Pero sé que el de la Habana es muy bueno. Prueba allí.",
"¡Maldita sea! Parece que hay muchas ciudades sin un buen herrero. Tal vez pueda contribuir con algo para convencer a un herrero de que se establezca aquí. Tal vez debería averiguar si hay algunos muchachos piratas trabajando en esto, alguna especie de 'red'.",
"¿Dónde está el astillero?",
"¿Dónde puedo conseguir un precio decente por las mercancías de calidad que he traído a la ciudad?",
"¿A quién le puedo confiar mi espada? Su antaño agudo filo se ha embotado un poco.",
" Tenemos una población de ",
" ciudadanos.",
"Mi vecina trabaja en la residencia del gobernador. Ella dice que su ",
" no espera la boda con mucho entusiasmo, piensa que su ",
" es cruel y arrogante. ¡Pobre criatura! Casi te hace alegrarte de ser pobre, al menos puedes casarte con la persona a la que amas.",
"hija",
"hijo",
"fiance",
"Te perdiste la emoción. ¡Hubo algunos disparos!",
"¿Qué pasó?",
"No mucho, en realidad. Oí el disparo, miré de dónde venía, pero no vi ningún cuerpo. El arma del soldado debe haberse disparado accidentalmente.",
"¿Así que fue un soldado quien disparó?",
"Sí. Aunque es extraño. No llevaba un mosquete como todos los demás soldados.",

};
