string DLG_TEXT[92] = {
"Buenos días, ",
". ¿Algo que informar?",
"Buenos días, señor. Nada que informar, señor.",
"¿Quién es usted?",
"Soy ",
", señor.",
"Ah, ",
", me alegra volver a verle.",
"Felicitaciones por su ascenso a ",
"Gracias, señor.",
"¿Por qué sigue aquí? Ya conoce su deber; ¡cúmplalo!",
"Ejem..., sí, señor.",
"Tengo órdenes para usted. Debe tomar un cargamento de mosquetes y municiones, y entregarlo a un rebelde llamado ",
". Ha tomado el fuerte de Playa de Sabana.",
"Estoy familiarizado con ese fuerte, señor. Lo volamos para evitar que una banda de rebeldes se apoderara de él. Si puedo preguntar, señor, ¿por qué los estamos ayudando ahora?",
" está luchando contra los españoles, que son nuestros enemigos. Se aplica el viejo adagio 'El enemigo de mi enemigo es mi amigo'. Aparentemente, ",
" ha reparado el fuerte. Y le aconsejo que no mencione usted su participación en su destrucción. Ese hombre es conocido por su temperamento violento.",
"Si me permite la pregunta, señor, ¿por qué estamos ayudando a un grupo de rebeldes?",
" está luchando contra los españoles, que son nuestros enemigos. Se aplica el viejo adagio 'El enemigo de mi enemigo es mi amigo'. Pero tenga cuidado al tratar con ",
", ya que es conocido por ser un hombre de temperamento violento.",
"Ya veo, señor. Esperemos que ese temperamento se desate contra los españoles.",
"Esa es la idea, sí. Las armas ya están siendo cargadas en su barco. Termine de aprovisionarlo y ponga rumbo a Playa de Sabana lo antes posible.",
"Sí, señor.",
"Esa es la idea, sí. Pero me han informado de que su barco ya está muy cargado. Libere un poco de espacio en su bodega, luego regrese aquí. Entonces ordenaré que las municiones se carguen a bordo del ",
"Sí, señor. Iré a la tienda ahora mismo.",
"Todavía no tiene usted suficiente espacio para la pólvora que va a trasnportar. Despeje más espacio, ",
"Muy bien, ",
". Ya he dado órdenes para que la munición sea transferida al ",
". Usted debe zarpar hacia Playa de Sabana tan pronto como sea posible.",
"Muy bien, señor. Zarparé hacia Playa de Sabana tan pronto como esté a bordo del ",
"Ahora, los franceses han enviado una escuadra de cuatro navíos de línea a #sisland_Hispaniola#. Probablemente anclarán en #sPort Au Prince#. Usted se unirá a mi escuadra. Bloquearemos #sPort au Prince# y encerraremos a la fuerza francesa en el puerto.",
"Disculpe, señor, pero, ¿y si en vez de eso la escuadra francesa se presenta en #sSanto Domingo#?",
"Hum. ¿Qué sugiere, ",
"Tal vez podría ir con el '",
"' a #sSanto Domingo# para ver si los franceses están allí.",
"Efectivamente. He leído informes sobre su carrera, ",
". Es usted propoenso a las acciones individuales. En busca de presas y botín para usted, ¿eh?",
"¡Para nada, señor!",
"Hum. Muy bien. Cuando nos acerquemos a #sisland_Hispaniola#, deberá separarse de la escuadra. Pondrá rumbo a #sSanto Domingo# y averiguará si los barcos franceses están allí\n Si están, deberá volver a reunirse conmigo en #sPort Au Prince#. Entonces bloquearemos #sSanto Domingo#\n Bajo ninguna circunstancia debe enfrentarse solo a la flota francesa. ¿Entendido, ",
"Entendido, señor.",
" a sus órdenes, señor.",
"¿Lady Barbara Wellesley viaja en este barco?",
"Ya ha sido informada de su llegada, señor.",
"Sus proezas en la mar le han hecho famoso, ",
". Cuando se presente ante el Cuartel General Naval, seguramente se le ofrecerá algo mejor que una humilde fragata de ",
" cañones.",
"Me limité a cumplir con mi deber, señor.",
"Es evidente que tuvo usted muchísima suerte al poder derrotar al 'Natividad', especialmente habiéndolo cedido antes siguiendo su propia iniciativa.",
"En su momento me pareció lo más conveniente.",
"El capitán de una fragata no decide normalmente la política del Almirantazgo.",
"Si hubiera podido comunicar con el Almirantazgo, lo habría hecho.",
"Pero, la verdad, Hornblower... ¡Entregar un barco de 60 cañones a un hombre fuera de sus cabales!",
"Estoy dispuesto a asumir mi responsabilidad.",
"¡De haber estado bajo mi mando, tendría sin duda que asumirla! Un consejo de guerra tacharía su decisión de irresponsable\n Y, por si fuera poco, puso en peligro la vida de la hermana del duque de Wellington.",
"Extremo que lamento mucho, señor.",
"De haberle ocurrido algo, las cosas se le habrían puesto difíciles, ",
". También yo aprecio profundamente a Lady Wellesley. Vamos a casarnos.",
"Lo sé, Lady Barbara me lo comunicó.",
"Supongo que un barco tan reducido es lugar apropiado para confidencias que, en circunstancias normales, no se producirían.",
"¡Ah, finalmente estás aquí, querida! No sabes lo preocupados que hemos estado todos por tu causa.",
"¿Nos vamos? Tu familia te espera impaciente en Londres, y después tenemos que ir a visitar a la mía a Irlanda.",
"Capitán ",
", llevamos navegando más de un mes",
", y no parece que estemos aún cerca de de #sisland_Saint Martin#. Dado que se me dijo que es usted un buen navegante y está familiarizado con estas aguas, debemos asumir que no se trata de un accidente. ¿Tiene algo que decir en su defensa?",
"No tengo excusa, señor.",
"El almirante Pellew me dio órdenes secretas, señor.",
"Mentir no le ayudará, Hornblower. Me lo podría haber creído si hubiera solicitado permiso para separarse de la escuadra para seguir esas supuestas órdenes por su cuenta. Lo más probable, dado que yo soy quien está al mando de esta escuadra, es que sir Edward Pellew hubiera tenido al menos la cortesía de informarme que estaba usted bajo órdenes especiales, incluso aunque fueran tan secretas como para que no pudiera comunicarme los detalles.",
"No tengo nada más que decir, señor.",
"Entonces, lo que creo es que ha estado usted usando un navío de Su Majestad para perseguir sus propios objetivos personales, lo que constituye un motín; o que ha retrasado deliberadamente nuestro viaje para permitir que los frnaceses entren en el Caribe sin oposición, lo que constituye alta traición. Un consejo de guerra determinará el cargo exacto, pero para usted no habrá diferencia\n La pena en ambos casos es la horca. La sentencia se ejecutará de inmediato.",
"Bien, caballeros, ahora que al fin nos hemos reunido, les comunicaré las desagradables noticias que acabo de recibir. Los franceses han roto el cerco de McCartney en #sMarigot#. Al parecer, tenía a los barcos franceses vigilados en una bahía, pero, aprovechando una noche de niebla espesa, desaparecieron cuatro navíos de línea como por ensalmo.",
"¿Qué rumbo cree que tomaron, señor?",
"Solo han podido dirigirse hacia #sisland_Hispaniola#. Así que si continuamos desde nuestra posición, espero que podamos interceptarlos de camino a #sPort au Prince#. Cuatro contra cuatro, el resultado es obvio.",
"Ejem... jem...",
"Parece no estar de acuerdo, capitán ",
". ¿Puede saberse adónde irían esos barcos según usted, si no es a #sPort au Prince#?",
"Yo aventuraría que a #sSanto Domingo#, señor.",
"¿Al extremo sur de #sisland_Hispaniola#? ¡Tonterías! ¿Por qué iban a hacerlo? Desde #sPort au Prince# pueden atacar a los españoles de #sisland_Cuba#.",
"Si yo fuera el comandante francés, señor, tentaría la idea de lanzar un ataque contra #sisland_Redmond#.",
"Los franceses no arriesgarían cuatro navíos en una misión descabellada contra el fuerte de #sRedmond#.",
"Tal vez lo harían, si con ello pudieran eliminar nuestra base más cercana a #sisland_Cuba# antes de atacar esa isla. Propongo que, en vez de concentrarnos en #sPort au Prince#, bordeemos la costa sur de #sisland_Hispaniola#.",
"El ALmirantazgo no nos lo perdonaría si los franceses toman la ruta del norte y llegan a #sPort au Prince# sin oposición.",
"Y nos lo perdonarían menos aún si los franceses atacan #sRedmond#.",
"Quizás podríamos hacernos cargo de ambas posibilidades. Tres barcos en la ruta del norte a #sPort au Prince# y uno siguiendo la costa sur.",
"¡Me parece buena idea, ",
"! Admito de buen grado sus sugerencias. Las agradezco en lo que valen, en realidad. Hemos de ganar la guerra\n Vamos a ver, ¿quién seguirá la costa? ¿Cuál es nuestro barco de menor calado?",
"El 'Sutherland', señor. Construcción francesa.",
"Oh, ahora comprendo lo que llevaba usted en mente, ",
". Quizá intente ganar otra recompensa, ¿eh?",
"En absoluto, señor.",
"Quisiera poder creerle. Sé que le gusta actuar por su propia cuenta. Le ordeno que no arriesgue el barco bajo ningún motivo, capitán. No admitiré locuras. Si avista a los barcos enemigos, deberá comunicármelo, para que podamos destruirlos juntos. ¿Está claro?",
"Perfectamente claro, señor.",
"De cualquier forma, denle la orden por escrito.",
}