string DLG_TEXT[95] = {
"¡Hola! Soy ",
"Y yo soy ",
"Me alegro de conocerte. Soy algo así como un investigador de artefactos antiguos. Estatuillas, tallas, ese tipo de cosas\n Y calaveras de cristal. Tengo una gran colección; de hecho, incluso podría desprenderme de algunas de ellas, si tengo una buena oferta\n But hay una calavera en particular que es muy rara, creo que solo debe de haber una. Como pareces #sperson# de carácter aventurero, ¿querrías ayudarme a conseguirla?",
"¡Te doy la bienvenida de nuevo, ",
"! ¿Te interesa ayudarme a encontrar la esquiva calavera que me falta para compeltar mi oclección, o te gustaría comprar una de las variedades más comunes?",
"Cuéntame más sobre esa calavera perdida.",
"¿Qué calaveras tienes a la venta?",
"¿Calaveras? Eh..., hoy no, gracias.",
"Las calaveras están hechas de cristal. Por lo que he podido averiguar, parece que fueron creadas por los mayas para algún tipo de ritual\n Las que tengo a al venta son de cristal rojo, blanco o azul.",
"Me gustaría comprar una calavera de cristal blanca.",
"¿Podrías darme una calavera de cristal roja?",
"La calavera de cristal azul es la que me interesa.",
"Pensándolo bien, no me interesa comprar una calavera. Pero esa que te falta suena interesante.",
"En realidad, no creo que tenga interés en comprar una calavera después de todo. Adiós.",
"Puedo venderte una calavera roja por ",
"La calavera blanca solo te va a costar ",
"La calavera azul es la más rara y la más cara. Te la puedo dejar por ",
" piezas de oro.",
"Trato hecho. Aquí está tu dinero.",
"No tengo tanto. Tal vez en otra ocasión.",
"¡No voy a pagar tanto por una baratija!",
"Ha sido un placer hacer negocios contigo, ",
"Como desees. Tal vez podamos hacer negocios otro día. Hasta entonces, adiós, ",
"Adiós.",
"Como todas las calaveras de cristal, la calavera ámbar que busco fue creada por los mayas. Pero por lo que he podido averiguar, parece que fue robada por los indios caribes\n Los caribes originalmente vivían en el continente antes de trasladarse al mar que lleva su nombre. Una de las tribus que se asentaron en estas islas es la que tomó la calavera ámbar.",
"¿Sabes dónde se puede encontrar esta tribu?",
"Toda mi investigación sobre este tema apunta a #sisland_Guadeloupe#. ¡Pero ten cuidado! Los caribes no son como Los arawaks pacíficos que puedes haber encontrado en otra parte. Son más belicosos y potencialmente hostiles.",
"¿Así que son salvajes?",
"Hasta cierto punto. Hacen la guerra a otras tribus, pero nosotros también hacemos la guerra a otras naciones\n Hay algunos indicios de que los caribes practican el canibalismo ritual\n En realidad, sin embargo, la principal razón por la que pensamos en los caribes como 'salvajes' es simplemente que han sabido resistirse con más eficacia a nuestra intrusion en sus tierras.",
"¿Y qué gano yo si te traigo esa calavera ámbar?",
"Oro, y mucho, por un artículo tan único. ¿Qué si no?",
"Muy bien. Seguro que puedo persuadir a los caribes para que la entreguen, ya sea por intercambio o por la fuerza. Zarparé rumbo a #sisland_Guadeloupe# tan pronto como sea posible.",
"¡El oro no sirve de nada si no estás con vida para gastarlo! No me arriesgaré a enfrentarme a toda una tribu de indios hostiles.",
"¡Excelente! Estoy deseando ver esa calavera ocupando su lugar en mi colección. Hasta la vista, ",
"Está bien. Házmelo saber si cambias de opinión, pero no tardes demasiado. Puede haber otros aventureros con más ganas de aceptar el trabajo. Gracias.",
"¿Y bien, ",
"? ¿Has reconsiderado mi propuesta? ¿O deseas comprar una de mis otras calaveras?",
"He reconsiderado tu propuesta. Y he decidido aceptarla.",
"¿Cómo va tu búsqueda de la calavera ámbar, ",
"Todavía no he encntrado a la tribu en #sisland_Guadeloupe#.",
"Te doy la bienvenida de nuevo, capitán ",
". ¿Has traído la calavera ámbar?",
"No, no he podido traértela.",
"No, se la di a los caribes.",
"Sí. Ahora, ¿qué hay del oro que me prometiste a cambio?",
"Qué desafortunado. Entonces, no creo que tengamos nada más que discutir.",
"Mal. Háblame de ",
"¿En serio? Cuéntamelo todo, por favor. Si no puedo tener la calavera, quizas al menos pueda tener una buena historia.",
"(*Le relatas a ",
" tu aventura*)",
"¿Y le entregaste la calavera de cristal al jefe caribe? Tal vez sea lo mejor- Después de todo, era de ellos.",
"El jefe se sintió obligado a darme algo a cambio: este tomahawk.",
"Cierto. Y yo ",
"recuperé a mi oficial sano y salvo.",
"recibí el antídoto para su veneno.",
"Y ahora, es hora de que me vaya. Adiós, ",
"Déjame ver... ¡Qué magnífica arma! Es un tomahawk ceremonial, muy efectivo en batalla, estoy seguro, pero es mucho más que eso. El jefe no haría un regalo así a la ligera.\n ¿Me lo venderías? Estoy dispuesto a ofrecerte 15000 piezas de oro por él. Cualquiera que no conozca su valor cultural te daría la décima parte.",
"No, creo que me lo quedaré. Nunca volveré a recibir un regalo así.",
"¿15000, dices? Muy tentador. Muy bien, tenemos un trato.",
"Si es tan importante como dices que es, seguro que podrías ofrecerme algo mejor. Que sean 20000 y tenemos un trato.",
"¡Regateas duro! Pero debo tener ese tomahawk. Muy bien, que sean 20000.",
"Ha sido un placer hacer negocios contigo.",
"Primero, dime: ¿cómo conseguiste la calavera de cristal?",
"Los caribes me emboscaron. ",
"Tomaron como rehén a uno de mis oficiales.",
"Dijeron que las flechas con las que me hirieron estaban cubiertas con un veneno que tomaría dos meses en matarme.",
"Pero las tabernas están llenas de oficiales de reemplazo.",
"Pero no les creí. Un veneno te mata o no te mata. No espera dos meses.",
"Así que fingí seguirles la corriente. Luego, cuando regresé con los caribes, luché contra ellos y me quedé con la calavera.",
"¡Me alegro de no ser uno de tus oficiales, si los sacrificas tan fácilmente! Pero estoy dispuesto a ofrecer 20000 piezas de oro por la calavera.",
"Yo no estaría tan seguro. Los caribes no son buenos mentirosos, pero son buenos con los venenos. Si te dijeron que el veneno te mataría en dos meses, deberías creerlos. Y eso significa que nuestro trato cambia.",
"¡Muy astuto! En cuanto al pago, estoy dispuesto a ofrecer 20000 piezas de oro por la calavera.",
"Me parece un precio justo por lo que costó conseguirla. Muy bien.",
"¿Vas a cambiar el trato? ¿Cómo, exactamente?",
"Tienes algo que quiero, esa calavera. Tengo algo que quieres, el antídoto para tu veneno. Así que propongo un simple intercambio.",
"Parece que no tengo elección. Aquí está la calavera. ¡Ahora, dame el antidoto!",
"Sigo sin créermelo del todo. ¡Quiero el oro que prometiste!",
"Espera aquí. Lo traeré de mi almacén.",
"No voy a ir a ninguna parte. Y tú tampoco, si intentas traicionarme.",
"No te hará mucho bien si mueres antes de gastarlo. Y me imagino que la mayor parte de tus dos meses ya ha pasado.",
"Y ahora, ¿hay algo más que pueda hacer por ti?",
"Sí. Puedes hablarme de ",
". ¿Cómo supo dónde encontrarme?",
" He usado sus servicios en el pasado. Se le da bien... conseguir cosas.",
"Se le daba bien, querrás decir. En pasado. Ahora es comida para tiburones. Pero eso no responde a mi pregunta. ¿Cómo sabía lo de la calavera? ¿Decidiste enviarlo en su busca también?",
"¡No, no! Ya te había dado el trabajo, no tendría sentido enviar a alguien más\n Confieso que hablé de la calavera con uno de mis colegas. Probablemente, fue él quien decidió enviar a ",
" para que le consiguiera la calavera de cristal. Tal vez pretendía vendérmela, o tal vez quería atribuirs eel mérito de mi investigación. ¡En cualquier caso, voy a tener unas palabras con él, puedes contar con ello!",
"A mí también me gustaría tener una charla con ese 'colega'. ¿Quién es?",
"En esa charla probablemente hablen tus armas más que tú. No puedo aprobar tal acto. Pero puedes tener por seguro que, cuando termine con él, quedará arruinado por completo. Si en tu próxima visita a esta ciudad ves a un mendigo por las calles, podría ser él.",
"Muy bien, supongo que es una venganza adecuada. Adiós por ahora.",
"Esto es lo que he preparado, basándome en mi investigación sobre los venenos de los caribes. Bébetelo todo, preferiblemente todo de una vez. Sabe horrible, pero va a curarte.",
"¿No puedes dar una garantía mejor que esa?",
"Nadie me ha informado nunca de que no funcionara.",
"Bueno, no. Si no funciona, nadie podrá informarte, ¿verdad? Pero si esto no funciona, algunos muchachos de mi tripulación se asegurarán de que tú no me sobrevivas por mucho tiempo.",
"! ¿Te gustaría comprar una de las variedades más comunes de calavera de cristal?",
}