string DLG_TEXT[68] = {
"Que estas haciendo aqui?",
"Relajate, he traido la mercancia!",
"Que piensas? !He traido la mercancia!",
"Mira, sal de aqui! Si arruinas el trato, te mataremos!",
"Te atreves a amenazarme?",
"!Te ahogaras con esas palabras, sinverguenza!",
"Calmar. Seguire mi camino. Despedir.",
"Supongo que los tienes en los bolsillos? Vamos, donde esta tu barco y la mercancia?",
"Queria asegurarme de que todo estaba bien primero.",
"No queria arriesgar mi nave. Queria comprobar si todo estaba bien primero.",
"Se acabo el trato!",
"No te enganaremos. Vamos, trae tu barco, y vigila las patrullas costeras.",
"Esta bien. Esperame aqui.",
"Que? Bromeas?",
"Hablo completamente en serio.",
"No puedes enganarnos asi! !Pagaras por esto con la cabeza!",
"Lo dudo!",
"Te arrepentiras de esto!",
"Ve aullar a otro lugar, perros escorbuto!",
"Te arrepentiras de esto!",
"Ve aullar a otro lugar, perros escorbuto!",
"Aha, bien. Tan...",
". El precio es ",
". Asi sera ",
" total. ?Trato hecho?",
"Tratar.",
"No hay trato. Buscare otro comprador.",
"Que estas haciendo aqui? No tienes nada que vender! Esto no es lo que queremos. Todo lo que tienes que comprar en la ciudad!",
"No hubo suerte.",
"Me alegra oir eso. Continuamos? ",
". El precio es ",
". Asi sera ",
" total. Trato hecho?",
"Tratar.",
"No hay trato. Buscare otro comprador.",
"Bien...",
". El precio es ",
". Asi sera ",
" total. Lo suficientemente bueno?",
"Asegurese.",
"No. Creo que ire a buscar otro comprador.",
"Y finalmente...",
". El precio es ",
". ",
" total. ?Esta bien?",
"Si.",
"No hay trato. Buscare otro comprador.",
"No hubo suerte? Organizas una reunion y luego dices 'no hubo suerte'? Sal de aqui. !Harias bien en honrar tus tratos en el futuro!",
"Esperabas honor entre ladrones? Eso es gracioso.",
"La suma total es ",
" oro. !Tu dinero, nuestra mercancia!",
"Trato hecho!",
"Demasiado! No hay trato!",
"Aqui esta tu dinero. Ahora vamos a descargar las cosas...",
"Mi equipo ya lo ha tirado en la playa. No queria esperar a que apareciera el Guardacostas.",
"No iras a ninguna parte desde aqui. Ahora que tengo tu dinero me carteles con la mercancia tambien. Y para escapar de la ira de su contrabando hermanos voy a reclamar que la guardia costera matado y confiscaron el contrabando. Por supuesto que no debe haber testigos, lo que significa...",
"Hinchar. Adios entonces.",
"Hasta la proxima.",
"Espera un minuto! Estoy un poco corto de provisiones para mi nave. ?Por casualidad tienes cosas asi en ese monton de cosas por ahi?",
"Ese monton contiene provisiones, plun... eh.. rescatado de una nave que.. umm.. tuve un desafortunado accidente cerca de esta playa. Pero estabamos a punto de quemarlo todo, no podemos molestarnos con cosas de bajo rendimiento, y no debemos dejar a evide.. eh.. basura en esta hermosa playa. Puedes comprarlo, todo o nada, por 1000 a diferencia",
"!Me encanta comprar paquetes sorpresa! Aqui esta el dinero, deja las cosas en mi bodega. Fue un placer hacer negocios con usted, adios.",
"1000 de Oro por un monton de trigo empapado y velas rasgadas? No, gracias y adios.",
"Me gustaria saltarme esto bueno si no te importa.",
"Muy bien.",
"Continuemos, ?de acuerdo?",
"Te has saltado todo! ?Parezco un idiota al que puedes enganar?",
" Como alejaste a esos guardias? Eso fue demasiado facil! Nos traicionaras, verdad? !En Guardia!",
"No... No... ESPERA!"
};