string DLG_TEXT[23] = {
"Tiren sus armas, ",
". Esta bajo arresto.",
"Bajo arresto?! Para que?",
"Tengo una orden de arresto, ",
"y todos los que estan con el.",
"Que?! Quien te dio esa orden?",
"Suelta el arma! Estas bajo arresto!",
"Que esta pasando?! Te has vuelto loco?",
"Esta bajo arresto, ",
". Por favor, venga con nosotros.",
"Si las probabilidades no talla a tu favor, me encontrarias menos agradable. Pero bien, llevame lejos. Sin embargo, insisto en informar al gobernador sobre mi arresto. Despues de todo, estoy trabajando para el.",
"Deponed las armas, ahora!",
"No te saldras con la tuya!",
"Gobernador ",
"Robert Christopher Silehard",
". Tienen un minuto para soltar sus armas y rendirse.",
"Me temo que todo esto es un terrible error. Vamos a ver al gobernador y aclararemos todo este lio.",
"Tonto! Fue el gobernador quien me ordeno que te llevara a la carcel. La unica forma de que te vayas es a traves de la horca.",
"!Sucio perro! Le gusto mi acero!",
"!Eso no es asunto tuyo, cerdo! !No discutas con el oficial!",
"!No me hables en ese tono de voz, campesino!",
"No estas en posicion de exigir nada. Ven con nosotros.",
"Diablo.",

};