string DLG_TEXT[93] = {
"¿Qué estás haciendo en mi casa, ",
"?",
"No te preocupes, ya me voy.",
"No es asunto tuyo, vieja bruja. Si dices una palabra más, te arrepentirás de haber venido al mundo. Aunque en realidad... No quiero ensuciar mis manos o mi espada contigo, así que me iré.",
"Hola extrano, ?a que debo el placer de darle la bienvenida a mi humilde morada?",
". ",
"Sabine Matton",
" bajo mi protección. Le gusta parlotear más que a cualquier otra persona que conozca. ¿Eres su madrina?",
"Tengo entendido que tú eres ",
" y ",
"Sabine Matton",
", a quien he traído aquí, es tu ahijada, ¿verdad?",
"Tengo la desgracia de tener a ", 
"¿Sabes? Creo que algo va mal. ",
"Sabine Matton",
", tu ahijada, cree que la he traído para entregarla a su padre, pero tengo otras ideas.",
"Cállate, vieja bruja. ",
"Sabine Matton",
", tu ahijada, está bajo mi 'protección' y seré yo quien decida qué hacer con ella.",
"¡¿Qué le ha pasado a mi ahijada?! ¿Qué has hecho con ella?",
"No te preocupes tanto. Tu hija está en mi barco y está bien.",
"Cállate. No me molestes con tus lloriqueos. La chica está viva, pero es asunto mío lo que haga con ella.",
"Ah, empiezo a entender. ¿Qué quieres a cambio de su liberación? ¿Dinero, supongo?",
"Ees muy perspicaz. Quiero que me pagues para liberarla.",
"Tienes toda la razón, por supuesto. El tintineo de las monedas de oro siempre ha sido música para mis oídos.",
"¡Oh, lo siento! ¡Me alegro de que me lo hayas recordado! Quería librarme de ella lo antes posible.",
"Esa ",
"Sabine Matton",
" casi me mata de aburrimiento con su incesante parloteo sobre las olas y el cielo . Quédate con la chica y que te vaya bien.",
"La chica se queda conmigo, así que no tengo nada de qué hablar contigo.",
"Debes calmarte. Voy a quedarme con la chica por ahora; después ya veremos.",
"¡¿Cuánto quieres para liberar a mi niña, canalla?!",
"¿Cuánto puedes ofrecer, madame?",
"¿Cuánto vale ella para ti? Dime tu precio, y veremos si me convence.",
"Te daré todo lo que tengo: 2000 piezas de oro.",
"Trato hecho. Dame el dinero y liberaré a mi 'pasajera'.",
"Ah, veo que eres astuta y se te dan bien los negocios. Bueno, dame el oro y dejaré ir a la chica.",
"Bien, creo que tomaré el dinero, pero ",
"Sabine Matton",
" también se queda conmigo.",
"¡Ja! ¡Solo tengo que tomar tu dinero y mantener a la chica conmigo!",
"Aquí está tu oro. ¡Así se te atragante!",
"¡Cielos, qué falta de educación! Aun asi, yo mantengo mi palabra: aquí está tu ahijada. Adiós.",
"No eres la primera persona en desearme ese destino. Dame el dinero, aquí está la chica.",
"¡No, no puedes hacernos esto! ¡Por favor, ",
", ten piedad!",
"No te preocupes tanto, podrías tener un corte de digestión... Dame el dinero y dime adiós.",
"¿Por qué no? No es como si pudieras detenerme. Y si se te pasa por la cabeza llamar a la guardia, entonces las cosas se complicarán mucho para tu ahijada.",
"Toma el dinero y vete. ¡No mereces llmarte capitán, eres un monstruo sin honor!",
"Adiós, madame.",
"Oh, por favor, deja de quejarte.",
"¡Oh, eres tan amable, ",
"! Veo que tienes un corazón bondadoso, aunque te las des de pirata cruel.",
"Estás muy equivocada, querida. Es solo que me he hartado de tu ahijada y de sus sueños ingenuos. ¿Cuánto tiempo puede alguien aguantar navegando en el mismo barco con una chica así?",
"No entiendes nada, vieja. Tu ahijada me ha agotado con todas sus ensoñaciones. El escaso placer que podría derivar de su compañía no puede compararse con la interminable molestia que me causa.",
"Me temo que te equivocas, madame. Soy oportunista...",
"No pienses mejor de la gente de lo que merece. Uso cualquier situación a mi favor.",
"Ahora veo que en realidad he sido demasiado amable contigo. ¡No eres más que escoria sin corazón!",
"Me alegra que finalmente me estimes por mi verdadero valor, pero tengo otros compromisos, así que tendré que poner fin a  esta conversación.",
"No es la primera vez que alguien me dedica esas palabras..., pero si no quieres que te pase nada a ti o a la chica, ¡te sugiero que te las guardes para ti!",
"No me importa lo que pienses. No soy una jovencita impresionable y puedo ver la verdad.",
"Como quieras, madame, pero ahora, con tu permiso, me marcharé.",
"Bueno, me parece muy bien que pienses que puedes ver la verdad, vieja, pero de cualquier manera, debo irme.",
"¿Por qué? ¿Qué vas a hacer con ella?",
"No te preocupes. Mantendré a tu ahijada a salvo.",
"Tranquila. Yo decidiré qué hacer con la chica, y créeme, encontraré un uso para ella.",
"Bien, ",
", probablemente ",
"Sabine Matton",
" no sabía de las verdaderas intenciones de su padre. Puede que esté mejor contigo. ",
"Gracias por admitirlo, aunque sea a regañadientes..., y ahora debo despedirme.",
"En realidad, se suponía que debia traerte a tu ahijada..., así que si tienes sitio para acogerla, aqui te la dejo, y me despido.",
"¡Te deseo vientos favorables, ",
"!",
"Adiós.",
"¡¿Qué?! ¿Cómo te atreves a decir esas cosas? ¡Eres un monstruo sin coprazón, ",
"!",
"No voy a escuchar tus insultos. Volveré a mi barco y la chica se quedará a bordo. Si tratas de detenerme o entorpecer mi camino, ¡juro por Dios que te cortaré el cuello!",
"¡No, mi niña no, por favor! ¡Déjala ir!",
"Ni lo sueñes, vieja.",
"Sí. Y te estoy muy agradecida por lo que has hecho por nosotras.",
"No importa. Por cierto, ",
"Arnaud Matton",
"me pidió que te diera esta carta.",
"Gracias, dejo la justa recompensa a tu juicio. Si tienes un poco de oro de sobra, no diría que no y, por cierto, tengo una carta para ti.",
"Gracias de nuevo. ¡Espera un segundo! Voy a escribir un par de lineas para ",
"Arnaud Matton",
" y, si no es mucha molestia, por favor entrégale esta carta la próxima vez que lo veas.",
"Adiós. Espero que todo te vaya bien.",
"Adiós.",
"¡Claro, claro! Aquí está todo lo que puedo permitirme. Son 800 piezas de oro, solo espero que sea suficiente para cubrir tus gastos.",
"Oh. Sí. Sí, por supuesto. ",
"¿Qué haces en mi casa? No tengo nada mas que decirte."

};