string DLG_TEXT[40] = {
"Tos-tos...!maldito tiempo! Mi nombre es ",
", y yo soy el mejor constructor de barcos en estas islas.",
"Me permito disentir - pienso que el clima es maravilloso. Mi nombre es ",
".",
"!Basta de tus 55 anos! Mi nombre es ",
". Supongo que has oido hablar de mi.",
"Oh, eres tu otra vez, con tus problemas...!tose-tose!",
"Puede que no tengas salud, pero tu memoria esta bien. Ahora vayamos al grano.",
"Asi es, soy yo otra vez, y tu eres tan pesado como siempre. Hablemos de negocios.",
"Siento molestarte. 4 irme.",
"Sabes, he oido suficiente de tus quejas sobre la vida. Despedir.",
"!Ustedes los jovenes son tan irrespetuosos en estos dias! Tienes pasion y fuerza, que mas necesitas?",
"Debes haber sido joven alguna vez, tu mismo. Ten un poco de paciencia.",
"Si, y supongo que tu juventud murio hace tanto tiempo, que ni siquiera puedes x ello.",
"!Muestra algo de respeto por tus mayores, cachorro!",
"Por favor, no vuelvas a levantarme la voz. Podemos ir al grano?",
"!Cuida tu lengua arrugada, viejo, o te TT de tu miseria! Si eres inteligente, cerraras la boca y pensaras en los negocios.",
"Lo siento. Veo que no tiene sentido hablar contigo.",
"!Ya he hablado demasiado! Despedir.",
"Si, si - !muy bien! Que quieres de mi?, ",
"?",
"Me gustaria usar los servicios de su astillero.",
"Necesito los servicios de su astillero. ",
"Lo siento, tengo que irme.",
"Tengo asuntos urgentes en otra parte. Ya me voy.",
"Que necesitas exactamente?",
"Necesito reparar mi nave, aunque podria considerar simplemente desguazarla y comprar una nueva.",
"Necesito instalar nuevas armas en mi nave.",
"Nada, gracias.",
"Me niego a comerciar con una persona de su reputacion y relaciones. Ahora salir, ",
", antes de que llame a los guardias.",
"Muy bien.",
"Muy bien, mi muelle junto al fuerte esta disponible para TI. Si quieres, le dire a mi capitan que remolque tu barco alli. Solo entonces puedo inspeccionar el dano y decirte cuanto tiempo y dinero me llevara.",
"MUELLE JUNTO AL FUERTE?? Uhh... Yo solo x que tengo... eeh... otro asunto urgente que debo atender primero. Despedir.",
"Despues de cerrar este dialogo, pulse ENTER para conversacion la interfaz de cambio de vela.",
"Salida",
"DLG_TEXT[36]",
"DLG_TEXT[37]",
"DLG_TEXT[38]",
"DLG_TEXT[39]",

};