string DLG_TEXT[34] = {
"Desaparece.",
"Ya me voy.",
"A menos que estés aquí para donar más dinero, será mejor que te vayas. ¡Ja, ja, ja, ja!",
"Te lo recordaré.",
"Volvemos a encontrarnos, capitán.",
"Ah, ya me parecía que olía a podrido.",
"Ven, únete a mí.",
"Ahora no. Tal vez en otro momento.",
"Con muchos gusto. ¿Me vas a invitar a un trago?",
", Dios te bendiga. ¡Has pagado mi deuda! ¡Gracias!",
"De nada. Toma tu recibo.",
"No me has pagado todavía, ¿verdad?",
"No, espera un poco más.",
"¡¿Cómo te atreves a hablarme así?!",
"Hablo como me da la gana. ¿Qué, quieres enseñarme modales?",
"Tienes suerte de que haya guardias alrededor, de lo contrario, mi espada ya estaría en tu garganta...",
"Morirías antes de que tu arma saliera de su vaina.",
"Capitán, si me permites el atrevimiento..., ¿me invitas a un trago? Me temo que ya he acumulado una cuenta considerable....",
"¿Cuánto debes?",
"Oh, lo siento mucho, pero debo irme...",
"500 piezas de oro.",
"¡Menuda deuda! Buena suerte para pagarlo.",
"¿Solo 500? No es para tanto. Tal vez pueda pagarlo por ti.",
"¡Oh! ¡Gracias! ¡Muchas gracias!",
"No, espera. No tengo el dinero encima.",
"¿Eso es todo? No hay problema. Te lo pagaré ahora mismo.",
"¡Oh, capitán, gracias de nuevo!",
"Volveré enseguida.",
"¡Ja! ¡Qué idiota! ¡Tabernero! ¡Tráeme vino!",
"Espera... Dijiste que no tenías dinero.",
"Pues parece que sí lo tenía, ¿no? Tal vez deberías tener más cuidado en quién confias, ¿eh? Ahora, vete de aquí.",
"Tú.... ¡ladrón! ¡Devuélveme mi dinero!",
"¡Ah, pero el timo ha sido perfectamente limpio, camarada! Ahora, sal de mi vista... a menos que prefieras que te pegue una palioza de muerte.",
"¡Hoy no!",

};