string DLG_TEXT[180] = {
". ¿Qué quieres, ",
"?",
"¿Puedo ayudarte, ",
"?",
"¿Es esta tu primera visita a nuestra ciudad, ",
"? No te he visto antes.",
"Soy ",
", capitán en propiedad del barco '",
"'. Tengo algunas preguntas, si tienes un momento.",
"Me llamo ",
". Me gustaría hacerte algunas preguntas.",
"Puedes llamarme capitán ",
". Solo quiero información.",
"Hola, capitán ",
". ¿Qué te trae a nuestra colonia?",
"Ah, capitán ",
". ",
", eres tú otra vez. Espero que tu viaje haya sido agradable. ¿Qué hay de nuevo?",
"Hola, ",
", ¿en qué puedo ayudarte?",
"¿Me he perdido algo mientras estaba fuera?",
"¿Ha pasado algo interesante mientras estaba fuera?",
"¿Qué historias cuentan estos días los viejos lobos de mar entre trago y trago de ron?",
"¿De qué se habla en las tabernas?",
"Busco chismes, rumores, cuentos... ¿Cuálquier cosa que no conozca puede ser útil.",
"Cuéntame tus chismorreos más frescos, camarada. Incluso el runor más inocente puede encerrar oportunidades de aventura o riqueza.",
"Sigo sin poder encontrar...",
"¡Es imposible encontrar nada en este laberinto! ¿Dónde está...",
"Me he perdido como un timonel borracho. ¡Otra vez!",
"Pareces de por aquí. Dime dónde puedo encontrar...",
"Por favor, dime cómo llegar a...",
"He tenido un mal día, así que ahorrarás muchas molestias para mí y para ti si me dices cómo encontrar...",
"Me gustaría conocer tu opinión sobre uno de los veicnos.",
"Necesito saber todo lo que puedas decirme sobre alguien que vive aquí en la ciudad.",
"¿Qué puedes decirme de...",
"Dime todo lo que puedas sobre una persona...",
"Espero que puedas decirme algo sobre una persona que tal vez conozcas.",
"Este lugar no es muy grande; apuesto a que conoces a todo el mundo. Hablemos.",
"Háblame de #sTortuga#.",
"¿Qué puedes decirme de este lugar dejado de la mano de Dios?",
"Me gustaría saber más sobre esta hermosa colonia.",
"¿Cuál es la historia de esta ciudad y de la isla?",
"¿Sabes algo interesante sobre #sTortuga#?",
"...",
"Lo siento. Pensé que eras otra persona.",
"Solo estoy de paso. Así que aparta o te aparto.",
"¿Qué te gustaría saber, ",
"?",
"¿Qué te interesa, capitán?",
"¿Qué quieres de mí?",
"Ciudades como esta siempre están llenas de cotilleos. Hazme un resumen.",
"¿Ha pasado algo interesante por aquí últimamente?",
"Solo quiero saber qué está pasando en el vecindario. ¿Alguien ha estafado a un amigo? ¿Alguien ha sido asesinado? ¿El posadero es realmente una mujer? Ya me entiendes.",
"¿Cómo puedo llegar a...",
"¿Puedes ayudarme a orientarme en la ciudad?",
"¿Dónde puedo encontrar...",
"¿Puedes hablarme de alguien que me interese?",
"Me gustaría obtener información sobre un lugareño. ¿Podrías ayudarme?",
"Me pregunto qué tiene que decir la gente de la ciudad sobre cierta persona...",
"¿Qué puedes decirme de #sTortuga#?",
"Me gustaría conocer la historia de tu ciudad.",
"Me gustaría obtener información sobre esta colonia.",
"Solo estoy de paso. Hasta luego.",
"Gracias. Hay una cosa más...",
"Ha sido un placer charlar contigo. ¡Hasta la vista!",
"¿Alguna otra cosa, capitán ",
"?",
"Oigámoslo, ",
".",
"Te escucho, ",
".",
"¿Cuál es la comidilla de la ciudad últimamente?",
"¿Qué historias cuentan estos días los viejos lobos de mar entre trago y trago de ron?",
"Ha pasado mucho tiempo desde que puse un pie en estas costas. ¿Qué me he perdido?",
"¿Podrías darme algunas indicaciones?",
"Me he perdido en estas calles.",
"Es mi primera vez en esta ciudad, y me gustaría que me dieras algunas indicaciones.",
"Me gustaría tu opinion sobre uno d elos vecinos.",
"Necesito saber todo lo que puedas decirme sobre alguien que vive aquí en la ciudad.",
"¿Podría darme alguna información sobre los lugarenos?",
"Háblame de #sTortuga#.",
"¿Qué puedes decirme de esta colonia?",
"Me gustaría saber algo sobre #sTortuga#.",
"Acabo de darme cuenta de que tengo que irme. Adiós.",
"¿A quién te refieres?",
"?",
"¿Estás preguntando por alguien en particular?",
"¿Quién te interesa?",
"Me refiero al gobernador.",
"Me interesa el dueño de la taberna.",
"El propietario del astillero.",
"Estoy hablando del comerciante local.",
"Nadie. Olvídalo.",
"Nuestro gobernador es francés, pero tiene contacto directo con los dos señores piratas instalados aquí.",
"Ya veo. Tengo otra pregunta para ti.",
"Gracias, Adiós.",
"Tiene el mejor ron para emborracharse... hip. Ahora que lo mencionas, creo que voy a volver a la taberna. ¡Tampoco es uno de esos aburridos a los que les da por interrumpir las peleas de borrachos! ",
"Ya veo. Tengo otra pregunta para ti.",
"Gracias, Adiós.",
"Creo que trabaja bien. Si está sobrio....",
"Ya veo. Tengo otra pregunta para ti.",
"Gracias, Adiós.",
"Es muy codicioso. Algunos dicen que era el ayudante de Baldewin Coffier, pero cuando la tienda se arruinó, se la compró por una miseria. No sé cómo es la calidad o el precio de sus productos, pero no parece ser muy... buena persona.",
"Ya veo. Tengo otra pregunta para ti.",
"Gracias, Adiós.",
"¿Adónde vas, ",
"?",
"No hay problema, capitán. ¿Adónde necesitas ir?",
"Será un placer guiarte, ",
". Pero, ¿adónde quieres ir?",
"¿Cómo puedo llegar a la taberna?",
"¿Dónde está el astillero?",
"¿Dónde puedo vender las mercancías que he traído?",
"Cuando entres en la ciudad, mantente a la izquierda y sigue el muelle.", //jrh 113 TABVRN
"Bien. Gracias por tu tiempo.",
"¿Dónde esta el astillero?",
"¿Dónde puedo conseguir un precio decente por las nercancías que he traído?",
"Después de los muelles, gira a la derecha. El astillero está justo antes del camino que lleva a la parte alta de la ciudad.",		//jrh 117 SHIPYARD
"Ya veo. ¿Y la taberna?",									
"¿Dónde puedo conseguir un precio decente por las nercancías que he traído?",
"Creo que eso es todo. Gracias por tu ayuda.",
"Ve a la parte alta de la ciudad. La tienda está en la plaza del patíbulo.", // jrh 121 STORE
"¿Dónde puedo encontrar el astillero local?",
"¿Cómo llego a la taberna?",
"Ya veo. Gracias por la información.",
"No sé por qué iba a interesarte, pero, ¿por qué no?",
"¿Qué es exactamente lo que te interesa, ",
"?",
"Por supuesto, ",
". Afortunadamente, es una historia bastante corta.",
"Me interesa la historia de la colonia...",
"Háblame de la colonia.",
"¿Hay algo en la isla además de la ciudad?",
"Tengo algunas preguntas más para ti, si no te importa.",
"Mira, camarada, estoy como una cuba y creo que ni siquiera puedo recordar mi nombre, ¿y tú me estás preguntando por la historia de este maldito agujero?",
"Gracias. Déjame hacerte unas preguntas más.",
"¿Sabes? Pensaba que iba a ser más interesante. Déjame preguntarte algo más.",
"Eso es todo lo que necesito. Gracias.",
"Gracias por tu tiempo. Hasta la vista.",
"Bueno #sTortuga# está en una pequeña isla que pertenece a La Española. Solo tenemos algunas plantaciones aquí.",
"¿Qué más puedes decirme sobre la colonia?",
"¿Qué más puedes decirme?",
"¿No me oyes? ¡Estoy como una cuba!",
"Ya veo. ¿Qué más?",
"No. Encontrarás un par de plantaciones, pero, en su mayor parte, la isla está poco colonizada.",
"En ese caso, tal vez me puedas decir más acerca de la colonia.",
"Entendido. Déjame preguntarte algo más.",
"¿Conoces a un contramaestre llamado Fred Bob?",
"¿Qué puedes decirme del capitán del puerto?",
"Oh, ¿Fred Bob? ¡No es un amotinado, te lo aseguro! Es un buen marinero, y un hombre fuerte al que quieres tener de tu lado cuando te superan en número. Es una lástima que lo hayan encarcelado. Todos esperamos que el gobernador lo libere, porque nadie más que ese pomposo primer oficial cree que sea culpable.",
"Interesante. Tengo otra pregunta para ti.",
"Muchas gracias, Adiós.",
"No sé cómo lo hace, pero nuestro capitán del puerto se asegura de conocer a todos los navegantes del archipiélago.",
"Ya veo. Una pregunta más, si no te importa.",
"Gracias por tu tiempo. Adiós.",
"¿Fred Bob? ¿El contramaestre? Es difícil entenderlo, pero mi hermano lo conoce bien. No es un amotinado. Ese oficial está equivocado. Todos esperamos que el gobernador lo libere. Debería estar en un barco, no en una prisión.",
"Buen hombre, excelente marinero. Yo no creo ni por un minuto que amenazara con amotinarse.",
"Ejem... Se me ha olvidado por quién iba a preguntar. Dame un segundo y me acordaré...",
"¿Cómo está el viejo herrero Tomas hoy en día?",
"Te refieres a Tomásina, ¿no, comandante? El viejo Tomas la palmó hace poco, y ahora es su esposa la que maneja el yunque. No se puede decir que haga un mal trabajo, la verdad.",
"Oh, cielos... ¿No le dan vahídos en esa profesión? No importa; pasemos a otra cosa.",
"Vaya, vaya. ¿Una viuda disponible que puede reparar una espada? Tendré que presentarle mis respetos inmediatamente...",
"Mi espada favorita de todos los tiempos está un poco embotada. ¿A quién la puedo confiar?",
"Me temo que nadie aquí podrá ayudarte con eso.",
"Ah, qué mal. Tendré que probar suerte en otra parte.",
"¿Dónde esta el astillero?",
"¿Dónde puedo conseguir un precio decente por las mercancías que he traido?",
"¿A quién puedo confiar mi espada? Su antaño agudo filo se ha embotado un poco.",
"¿Hay un sastre en #sTortuga#?",
"Claro que sí. La sastrería está en una gran casa azul en la parte baja de la ciudad. Cerca del pozo.",
"He oído hablar de unos cirujanos que viven aquí, en #sTortuga#. ¿Es eso cierto?",
"¿Dónde puedo encontrar al armero?",
"¿Puedes mostrarme el camino al taller del velero?",
"Claro. Uno vive en una pequeña casa de madera, frente al ayuntamiento.",
"El armero está en la casa de piedra detrás de la taberna.",
"Busca la bandera en el muelle. Ahí está la entrada.",
"¿Cómo llego a la torre? Está bloqueada por una reja.",
"Oh, pero es que se entra desde el ayuntamiento.",
"Se supone que hay un carruaje en algún lugar de Tortuga. ¿Sabes dónde?",
"Si, hay uno al lado del cirujano en la parte alta de la ciudad.",
};
