string DLG_TEXT[44] = {
"...",
"...",
"¡Ay! ¡Qué dolor de cabeza!",
"¿Estás sobrio?",
"Ahora sí. Pero no puedo recordar nada de lo que hice ayer. ¿Dónde estoy? ¿Y quién eres tú?",
"Estás en la cárcel y yo soy quien quizás podría sacarte de aquí. Si estás dispuesto a cooperar.",
"Pero, ¿por qué estoy en la cárcel? Puede que parezca un tipo grande y malo, pero nunca hago daño a nadie.",
"En realidad, eso es exactamente lo que hiciste. Ayer fuiste al burdel borracho y lastimaste a una mujer.",
"Oh. Lo siento mucho. ¿Está bien? Maldito alcohol. No sé lo que hago cuando estoy borracho. Pero no puedo resistirme a una botella de ron.",
"No te preocupes por eso. Vayamos al asunto urgente de sacarte de aquí. Primera pregunta: ¿eres el piloto del 'Arabella'?",
"Sí, lo soy. Pero no voy a darte mas informacion. Mi capitán, Pedro Rivera, seguramente me sacará de aquí.",
"¿A quién crees que estás engañando? Por lo que deduzco de mis fuentes, tu capitán es un mercenario despiadado al que no le importa nadie. Probablemente, te abandonará sin pensarlo dos veces.",
"Tal vez tengas razón. Mi capitán no es un buen hombre. Podría dejarme aquí pudriéndome.",
"Sí. Entonces, ¿que me dices? Podría dejarte aquí también. Para ser una cárcel, parece acogedora. ¿Tal vez te guste vivir aquí?",
"Oh, no, capitán. Cooperaré. ¡Por favor, sácame de aquí!",
"Me alegra que lo hayamos resuelto. Este es el trato: te sacaré de aquí y tú me ayudarás a conseguir lo que quiero: el barco de Pedro Rivera, el 'Arabella'.",
"El 'Arabella ' está anclado en Anse Casse-Bois. Puede llevar un maximo de 180 tripulantes, pero 40 tripulantes abandonaron el barco cuando el capitán aceptó la tarea de capturar o matar al famoso pirata Pieter Boelen. Yo también quería irme en ese momento, pero el capitán no me dejó. Dijo que si un oficial se iba, sería un mal ejemplo para la tripulación.",
"¿Por qué se fueron esos miembros de la tripulación? ¿Y por qué querías irte tú también?",
"¿No has oído hablar de Pieter Boelen? Es uno de los peores piratas del archipiélago.",
"¿Quieres decir que no es bueno pirateando? ¿O quieres decir que es un monstruo sediento de sangre o algo así?",
"No, para nada. Es uno de los piratas más exitosos y es bastante respetado por casi todos los otros piratas. Pero también se dice que es todo un caballero, que siempre ayuda a personas necesitadas y nunca mata a nadie si puede evitarlo. La tripulación que abandonó el barco lo respetaba tanto que se negaron a intentar cazarlo.",
"Interesante. Pero volvamos al tema que nos ocupa. Esto todavia deja a 140 tripulantes a bordo del 'Arabella'. No será una tarea fácil apresarlo. Y tampoco quiero perder a muchos de mis tripulantes.",
"¿No puedes olvidarte de todo esto? Pedro Rivera es un hombre peligroso y no es alguien con quien quieras enemistarte. Solo él vale lo que cinco hombres. Matará a cualquiera sin dudarlo. ¡Si me ve contigo, estaré muerto en segundos!",
"No te preocupes. Sé lo que hago. Tengo un plan. Y tú puedes permanecer al margen de las partes peligrosas si es lo que quieres. Voy a hablar con el guardia de la prisión para arreglar tu liberacion. Adiós.",
"¡Espera! ¡Por favor, permíteme ser tu oficial después de que te hagas con el 'Arabella'! Adoro a ese barco, aunque odio a su actual capitán. No quiero separarme de él.",
"Muy bien, entonces. Pero tendrás que dejar el ron. No quiero a un borracho agresivo a bordo de ninguno de mis barcos. ¡Y también tendras que mostrar un poco de coraje! El coraje no parece ser uno de tus principales puntos fuertes, ¡pero no puedo permitir que salgas huyendo tan pronto como tratemos de abordar una tartana! Piensa en eso mientras hablo con el guardia.",
"¡TXIKI ES LIBRE! Gracias, mi capitán.",
"Eres libre, sí. Y tu liberación me costó mucho dinero, así que no intentes ninguna tontería. Ahora es el momento de que cumplas tu parte, así que escucha atentamente. Volverás al 'Arabella' e informarás a la tripulación de que el posadero está dando ron gratis esta noche para celebrar el matrimonio de su hija.",
"¡Ron gratis! ¡Me gusta esta idea! ¡Qué gamas de que llegue esta noche!",
"No se te permite acercarte a la taberna. No con la forma en que te comportas después de ingerir bebidas alcohólicas. Lo que harás será asegurarte de que la mayor parte de la tripulación abandona el barco. Nos encontraremos en la plantación esta noche. Ahora vete.",
"¡Por fin! ¡Ahí estás!",
"¿Qué quieres decir? No llego tarde ni nada. De todos modos: he visto a algunos miembros de la tripulación corriendo hacia la taberna, así que parece que has tenido éxito. ¿Cuántos marineros estimas que quedan a bordo?",
"Tu plan fue incluso mejor de lo esperado. Me atrevo a decir que solo quedan unos diez hombres. Junto con el capitán, que, por supuesto, cuenta como cinco.",
"¡Excelente! Esto debería ser pan comido. Sígueme, ¡vamos a tomar el barco!",
"¡Espera, capitán! Prometiste que me permitirías quedarme fuera de esto. ¿Recuerdas?",
"Veo que tienes mucha fe en nuestro éxito, ¿no? Muy bien, entonces. Puedes quedarte en tierra durante el abordaje. Después de todo, te lo prometí. Pero hablaremos de tu falta de coraje después del abordaje. ¡Así que ten cuidado! ¡Porque triunfaré!",
"¡Ha sido increíble, capitán! ¡Te vi desde esta orilla e hiciste un magistral abordaje!",
"Es una pena que no compartieras este entusiasmo antes del ataque. De ahora en adelante, participarás en todos los abordajes. Si no, te despediré.",
"Perdona, capitán. ¿Nada de ron para mi y obligación de participar en los abordajes? Estoy empezando a pensar que habría estado mejor con mi anterior capitán.",
"No toleraré esa clase de comentarios. Podría considerarte un amotinado. Ya has visto que no hay nada que temer al unirse a los abordajes, ¡así que será mejor que encuentres tu coraje cuanto antes! En cuanto al ron: te permitiré beber de vez en cuando, pero si vuelves a terminar borracho y violento, te despediré también.",
"*¡Hip!* Qué cara más rara tienes.",
"Soy el rey del mundoooooo.",
"Qué guapa eres, niña.",
"Parece que estás demasiado borracho para hablar. Volveré mañana.", 

};
