string DLG_TEXT[77] = {
"No te ensenaron modales? No ves que estoy hablando con alguien y no te importa que te molesten?",
"Oh, no queria molestarte. Lo siento.",
"Esta bien, calmate, para ser ejercitos, tu tampoco me importas.",
"Lo siento, no ",
",capitan del 'Juno'?",
"Espera, ?estas ",
"Usted dirige el 'Juno'?",
"Lo siento, pero voy a zarpar pronto y no tengo tiempo para hablar contigo.",
"En ese caso no me atrevo a retrasarte. Buen viaje.",
"Entonces usted debe darse prisa, antes de que algo... te pasa algo inesperado.",
"Me alegro de volver a verte, me gustaria hablar contigo sobre una cosa.",
"Estoy escuchando, que quieres decirme?",
"He oido que busca un capitan de confianza que pueda escoltar su nave durante su viaje.",
"He oido que necesitas una escolta. Puedo hacerlo por ti.",
"!Cuanto me alegro de volver a verte! Para decirte la verdad me senti muy seguro bajo tu proteccion! .",
"Cuando piensas volver?",
"Cuando regresaremos, gordo? No puedo esperar a conseguir mi dinero.",
"Asi que, estamos de vuelta. Gracias por su ayuda, ",
".",
"Esta usted satisfecho con nuestra cooperacion?",
"Es eso? ?No necesitas nada mas de mi? Entonces Dame las monedas.",
"Esta bien, esta bien, admito que me emocione demasiado, No debio haber sido asi deliberadamente. Permitanme presentarme, estoy ",
", capitan de un barco mercante.",
"Y mi nombre es ",
". Bueno, parece que somos colegas, los dos somos capitanes.",
"Me llaman",
", ",
", probablemente has oido hablar de mi.",
"Oh! He oido hablar de ti! Eres un capitan bastante famoso, no? Me gustaria beber una taza de ron para que!",
"Me halagas. Yo tambien me alegro de conocerte.",
"Si no hubiera tenido asuntos urgentes en otro lugar, le habria dado a mis enemigos algo de polvo para oler!",
"No me atrevo a molestarle mas, Senor ",
".",
"Metete en tus asuntos y no metas la nariz en mis asuntos y estaras bien.",
"Si, y con quien tengo el honor de hablar?",
"Mi nombre es ",
". He oido que esta buscando un capitan de confianza que pueda escoltar su nave durante su viaje.",
"He oido que necesitas una escolta. Puedo hacerlo por ti.",
"No dudo de tu valor, ",
", pero tengo que dejarte ahora, me temo.",
"No me atrevo a retrasarte.",
"Por amor de Dios, quien dijo que estoy en contra?",
"Me gustaria pedirle que me haga un favor. Seria tan amable de dejarme un par de minutos?",
"Si, por supuesto, que pasa?",
"No ha sido tan sereno por aqui recientemente. La pirateria arroja un manto sobre estas aguas y estoy un poco preocupado porque mi barco es viejo y no lo esta una vez. Ademas, no tengo suficientes canones para conducir una defensa.",
"Entonces, quieres que mi barco proporcione proteccion en caso de un ataque pirata?",
"Si, realmente necesito una escolta y puedo pagarte 2.500 dolares. Por eso su barco me escoltara a #sisland_Falaise de Fleur# y de regreso.",
"De acuerdo, cuando zarpamos?",
"Tratar. Cuando vas a empezar el viaje?",
"No. Perdere mas dinero en este viaje del que ganare.",
"No, no es suficiente dinero para arriesgar mi nave.",
"No puedo aceptar tu oferta porque estoy muy ocupado ahora mismo.",
"No me interesa.",
"Cuanto antes mejor. Una vez que me hayas escoltado a #sisland_Falaise de Fleur# y de vuelta, te dare tu dinero.",
"Bien, dejame arreglar algunos de mis asuntos personales y estare a tu disposicion.",
"Tenemos un trato. Zarparemos tan pronto como termine con algunos asuntos en la ciudad.",
"Mi nave esta lista para el viaje de regreso. Por cierto, aqui esta la mitad del dinero que te debo.",
"Sigamos nuestro camino. Que la suerte este con nosotros.",
"Que estas esperando? !Moveos! No puedo quedarme en esta isla para siempre.",
"Oh, si! Gracias de nuevo. Aqui esta tu recompensa demasiado mala que tienes tu propia nave. Para ser honesto, yo con mucho gusto de contratar a usted, porque mi navegador, ",
"Zaid Murro",
", ha dejado su trabajo despues de este viaje.",
"C'est la vie. Bueno, si necesitas una escolta o algo, estoy a tu Servicio.", // revision ortografica por B.
"Si, si. Ahora me voy de aqui.",
"Bien, que piensas sobre ",
"comercio",
"?",
"Siempre es un placer tratar contigo. Yo lo hare.",
"Claro, voy a hacer eso.",
"Tengo que negarme. Mi tripulacion no trabajara gratis.",
"Dije que no voy a trabajar para ti, asi que encuentra a alguien mas.",
"Eso es muy malo entonces, voy a tener que tomar el riesgo y empezar el viaje yo mismo. Buena suerte.",
"Buena suerte a usted tambien, Senor.",
"Adios.",
"Si, realmente necesito escolta, pero preferiria navegar con menos satelites, ya sabes.",
"Siento oir eso. Pero tenia la intencion de deshacerme de algunas de mis naves, y despues podria escoltarte, si aun estas interesada.",
"No huyas, gordo! Tenia la intencion de deshacerme de algunos de los disturbios, se llaman a si mismos mis companeros, despues hacemos un trato!", // Minor spell check by B. 'thicaself' in Place of 'temself'. Pieter por favor correcto! 
};
