string DLG_TEXT[61] = {
"Capitan, ?sigue aqui? ",
"Mateus Santos",
"es poco probable que se sorprenda si se demora en atacarlo durante demasiado tiempo.",
"...",
"Que puedo hacer por TI?",
"Es tu nombre ",
"Vito Leone",
"Vito Leone",
"?",
"!Lo ha hecho muy bien, capitan! Aqui tienes tu 10000 de oro. ?Confio en que encontro bien a mi hija? ?No es bonita? Bueno, sera mejor que vaya y la deje salir de esa celda. Escucha, si alguna vez lo necesitas...planifique un funeral para alguien, asegurese de hacernos saber, vamos a proporcionar el mejor Servicio-con un descuento decente. Vengan los dos, tenemos mucho que discutir.",
"Gracias y adios.",
"Si, soy yo. Y usted debe ser ",
". He oido mucho sobre tu exito al realizar ciertos ... trabajos.",
"Llegaste hace una semana, ?y ya sabes quien soy y que he estado haciendo? ?Por que?",
"En mi linea de trabajo, la falta de informacion es mucho mas peligrosa que cualquier bala o espada. Veo que estas sorprendido - ",
"Mateus Santos",
"no te ha dicho quien soy, ?verdad?",
"Lo sabes todo, ?verdad? Si, ",
"Mateus Santos",
"me dijo que eres un mensajero, y la noticia que has traido es muy peligrosa.",
"Un mensajero? Todo un comodin, que ",
"Mateus Santos",
"de los suyos. Capitan, no soy un mensajero. Represento a una organizacion que un filisteo podria llamar el gremio de asesinos. Y no vengo a traer noticias, sino a sentenciar a un impostor.",
"?Es asi? Y quien es este impostor?",
"Nuestro estimado Senor ",
"Mateus Santos",
", como podrias haber adivinado. Hace dos anos, aparecio de la nada, mato al jefe de la rama local de nuestra organizacion, y asumio su lugar.",
"...",
"En teoria, podriamos cerrar los ojos ante esta imprudencia, si nos mostrara algo de respeto. Pero no solo mato a nuestro representante, tambien dejo de compartir beneficios con el gremio. Esto, como usted puede entender, no podriamos perdonar.",
"...",
"Tratamos de deshacernos de ",
"Mateus Santos",
"con la ayuda de mercenarios locales, pero es un hombre de recursos y ha logrado frustrar todos los atentados contra su vida. Ademas de todo esto, me ha robado algo muy preciado, y estoy decidido a que me lo devuelvan. Por todas estas razones el gremio ha decidido enviar a su propio hombre para tratar el problema.",
"Y ",
"Mateus Santos",
"me ha prometido una fuerte recompensa por la cabeza de los asesinos se.",
"!Por supuesto que lo hizo! Ahora que las cosas son realmente serias, el entiende con quien esta tratando, y tiene miedo. Pero, mi muerte no cambiara nada ahora - ",
"Mateus Santos",
"va a morir, muy pronto.",
"Asi que esto no me impedira matarte y conseguir mi recompensa.",
"Oh, podrias matarme...pero es probable que reciba una bala como recompensa por sus esfuerzos. ?En serio crees que ",
"Mateus Santos",
"?te dejare vivir despues de hablar conmigo? Me temo que este es su ultimo trabajo, capitan.",
"Hmm...pero si es como usted describe, ?que sugiere?",
"?Crees que soy un tonto? Quieres vivir, y diras cualquier cosa para salvarte. Te voy a matar y obtener mi recompensa!",
"Veo dos opciones para TI en esta situacion. El primero, dejame vivir y seguir tu propio camino. El segundo, ayudame a eliminar ",
"Mateus Santos",
". Esta Ultima opcion le hara ganar una considerable cantidad de dinero.",
"Hmm...No tengo ninguna objecion al dinero... y las cosas que he aprendido sobre el de otros estan dando a su historia algo de credibilidad. Pero, ?como planeas matar? ",
"Mateus Santos",
" Su casa esta bien custodiada, por decir lo menos...",
"De ninguna manera, tratar con ",
"Mateus Santos",
"!por tu cuenta! Estoy fuera de esto. Despedir.",
"Crees que soy un tonto? Quieres vivir, y diras cualquier cosa para salvarte. Te voy a matar y obtener mi recompensa!",
"Sus actividades recientes han mantenido a su empleador preocupado, y aunque su atencion se ha centrado en usted, se le ha escapado el aviso de que dos de sus subordinados de mayor confianza han sido sobornados. Se aseguraran de que su objetivo no tenga mas guardias sobre el, cuando ataquen su casa, de los que podran manejar. Ve ahora a su casa, una vez que lo hayas matado, busca en su morada. Cualquier tesoro que encuentres ahi, con la excepcion del precioso objeto que reclamo como mio, te estare esperando cerca, y luego te pagare tu 10000 oro.",
"En este punto no estoy seguro de en quien confiar excepto mi espada y mi pistola. Lo matare, pero si me has neurol, ten por seguro que trataras con ambos, y la informacion no sera lo unico que te faltara.",
"De ninguna manera, tratar con ",
"Mateus Santos",
"!por tu cuenta! No participare en esto. Despedir.",
"10.000 de oro es tentador, pero me ofrecieron 20.000 de oro para TI. Haz las paces con tu creador, porque la puja ha terminado.",

};