string DLG_TEXT[30] = {
"Hola, marinero, ¿te gustaría encontrar un verdadero tesoro?",
"¡Arrr!",
"Oye, marinero, ¿cómo te va?",
"Tengo un sombrero.",
"'Entra en mi salón', dijo la araña a la mosca...",
"Sí, se levanta el viento, y otra cosa se levanta también, si entiendes lo que quiero decir...",
"¿Qué se lleva un ratón cuando gira?",
"El segundo ratón se lleva el queso...",
"¡Estoy libre, pero no libre de coste!",
"¡Soy pirata!",
"Estoy aquí para desatascar tus cañerías.",
"Mis cañerías están muy sucias.",
"Disney se va a meter en tu cabeza.",
"Seguro que sí...",
"¡Puede que no sea el dios Neptuno, pero puedo provocar una tormenta en tu cama!",
"¡Soy pirata, no por el oro ni por la plata, sino por ese tesoro que tienes entre las patas!",
"¡Qué buena mercancía tienes, carino.",
"Me encantaría saquear tu aldea.",
"Ven aquí, chica, ¡quiero limpiar esa cubierta!",
"¡Quiero navegar por tus siete mares!",
"¡De verdad me levantas la vela mayor!",
"¡Puedes atracar en mi puerto cuando quieras!",
"¿Te has despertado?",
"Oooh...",
"¿Estás bien? ¿Qué tal tu cabeza?",
"¿Qué diablos pasó?",
"¿No lo recuerdas? Bebiste demasiado, te dormiste en la mesa y luego te robaron.",
"¿Qué? Oh... mi cabeza... ¿Quién se atrevió...?",
"¿Cómo voy a saberlo? ¡Es un barrio peligroso! Llegaron, me amenazaron, rebuscaron entre tus cosas y se fueron.",
"Muy bien. Lo perdido, perdido está. Al menos no encontraron el dinero oculto en mi cinturón.",
};