string DLG_TEXT[26] = { 
"Buenos días. Mi nombre es ",
"y soy el representante de la ",
". ¿Qué te trae a mi mesa?",
"Mi nombre es ",
". Hay un favor que me gustaría pedirte.",
"Espera, ¿esto es una oficina? Debo haberme equivocado de pasillo en algún momento. Adiós.",
"Pregunta. Pero, por favor, sé breve. Tengo mucho papeleo pendiente en mi escritorio.",
"¿Papeleo? ¡Sí, papeleo! Eso es exactamente con lo que necesito ayuda. Me gustaría evitar pagar comisión por la venta de mi cargamento.",
"Ah, eso parece una buena idea. También debería evitar que tu tripulación quiera firmar artículos, ¡y de ahí a la piratería solo hay un pequeño paso!",
"¡Parece que hablamos el mismo idioma! Cuantas más ganancias y cuantos menos piratas se aprovechen de los barcos mercantes, mejor.",
"Aunque, por supuesto, siempre es un placer ayudar a otros colegas comerciantes, debes entender que hay algunos... gastos administrativos. Puedo hacer lo que me pides, pero te costará 1.000.000 de piezas de oro.",
"Me imagino que el precio está tan inflado como prueba de que realmente soy me tomo en serio la idea de deciarme al comercio respetable. Es comprensible. Parece que tenemos un trato.",
"Eso suena muy divertido. ¿Qué tal si me voy y te dejo con tus asuntos? Gracias y adiós.",
"¿Piratería contra buques mercantes? No, no queremos nada de eso, en absoluto. Sin embargo, me acabas de dar una idea que no tiene nada que ver con esto. Y ahora me voy...",
"¡Espera! ¿Qué? Cuánto....? ¿Por un pedazo de papel? ¿¿Tanto oro?? Creo que tengo que ir a visitar al boticario.",
"¡Ahí lo tienes! Firmado, sellado y todo oficial. Pero te lo advierto, tu licencia será revocada inmediatamente ante el menor acto indigno.",
"Comprendo. No me cabe duda de que disfrutaré mi tiempo dedicando al honrado oficio del comercio. Ha sido un placer hacer negocios contigo.",
" y yo estoy al mando aquí.",
"¿Pagar commisiones por la venta de tu carga? ¿Qué eres, comerciante? En caso de que no te hayas prestado atención, esta ciudad pertenece a los piratas, y a los piratas les encanta adquirir la carga de los barcos mercantes sin pagar ninguna comisión, ¡o sin pagar nada de nada, más bien!",
"¿Piratas? ¡Arr, en ese caso, me apunto a practicar la piratería!",
"Compañía Comercial de las Indias Orientales",
"Compañía Holandesa de las Indias Occidentales",
"Casa de Contratación",
"Casa da Índia",
"Compañía Francesa de las Indias Occidentales",
"Compañía de las Indias Occidentales",
};