string DLG_TEXT[32] = {
"!querida mandataria! Estoy ",
", propietario del astillero local.",
"Y estoy ",
", capitan del barco ",
".",
", ",
". ?Necesitas los servicios de mi astillero?, ",
"?",
"De hecho, necesito que arregles un par de agujeros de bala y arregles algunas velas.",
"Ahora mismo, solo necesito hablar contigo.",
"No, solo pense en pasarme.",
"Bueno, estoy muy contento de conocerte. Si eres capitan, entonces mi astillero esta siempre a tu Servicio.",
"Perfecto, ",
". Vamos a empezar con esas reparaciones.",
"Gracias. Pero primero, hablemos.",
"La proxima vez, tal vez. Tengo que irme.",
"?Que es exactamente lo que te interesa, ",
"?",
"No, no creo que lo haga.",
"Ya veo. ?Necesitas algo mas, ",
"?",
"Me gustaria poner un par de parches en la vieja Banera que me trajo aqui!",
"Eso es todo, gracias. Adios!",
"?Que necesitas exactamente?",
"Necesito reparar mi nave, aunque podria considerar simplemente desguazarla y comprar una nueva.",
"Necesito instalar nuevas armas en mi nave.",
"Nada, gracias.",
"Me niego a comerciar con una persona de su reputacion y relaciones. Ahora salir, ",
", antes de que llame a los guardias.",
"Muy bien.",
"Muy bien, mi muelle junto al fuerte esta disponible para TI. Si quieres, le dire a mi capitan que remolque tu barco alli. Solo entonces puedo inspeccionar el dano y decirte cuanto tiempo y dinero me llevara. ",
"MUELLE JUNTO AL FUERTE?? Uhh... Yo solo x que tengo... eeh... otro asunto urgente que debo atender primero. Despedir.",

};
