string DLG_TEXT[99] = { 
", ",
".",
", ",
".",
"Oye, camarada, ¿no puedes parar un minuto para charlar un poco?",
"Hola, hola. Tienes el aire d elos verdaderos lobos de mar, como yo, así que, ¿por qué no charlamos un poco?",
"Lo siento, pero tengo prisa. Hablemos luego.",
"Déjame en paz. Me estoy cansando de ti. Adiós.",
"¿Quién eres? No me importa charlar un poco, en absoluto, pero me gustaría saber al menos tu nombre.",
"Mi nombre es ",
", y soy capitán del '",
"'.",
"¿Cuántas veces tengo que repetirme? Soy ",
", y soy capitán del '",
"'.",
"Lo siento, pero tengo prisa, y no tengo tiempo para hablar contigo.",
"No tengo ningún deseo de revelar mi identidad, y además, no tengo tiempo para charlar ociosamente. Así que vete.",
"¡Oh! ¿Capitán? Entonces, ¿ese es tu barco? No está mal, no está mal... Ni comparación con nuestra vieja bañera.",
"¿No te importa si te pregunto cuál es tu nombre?",
"¿Cómo te llamas, amigo?",
"Oh, lo siento, capitán. Soy ",
", del 'Juno'.",
"Estupendo, ",
", y ahora que nos hemos presentado, tengo algunas preguntas para ti.",
"Ahora, que sabes mi nombre, y yo sé el tuyo, ¿puedes finalmente contestar a mis preguntas, o vas a seguir haciéndote el tonto?",
"Lo siento, tengo que irme.",
"Terminemos nuestra conversación así.",
"Te escucho, capitán.",
"¿Qué está pasando en la ciudad? ¿Algo interesante?",
"Terminemos con esta charla ociosa y vayamos al grano.",
"¿Interesante...? Bueno, no sé qué decirte. Cada uno tiene sus propios intereses. Al comerciante le interesa una cosa, al marinero otra. Bueno, sé que ",
"Claire Larrouse",
"Claire Larrouse",
" llegó hace poco a la ciudad. Dicen que esta´reuniendo una tripulación para su nueva expedición.",
"Nunca había oido este nombre antes.",
"No me importa eso. Hablemos de negocios.",
"Eso es todo lo que quería saber.",
"Gracias. Eso es todo lo que quería saber.",
"Solo eso? Estos rumores que puedes escuchar en cada esquina. Buenas tardes.",
"Hablemos de cosas mas serias ahora..",
"Chismes, chismes. Es hora de hablar de cosas serias, ",
".",
"Capitán, ¿te has caído de la Luna o qué? Es uan espadachina y capitana famosa, y afortunada como un diablo.",
"Bueno, será famosa para algunos, pero no para mí. ¿Dónde dices que puedo encontrarla?",
"!Ja! He oído hablar de muchos supuestos espadachines que degollarían a un hombre mientras duerme y se las darían de grandes maestros. Bueno, ¿dónde dices que se aloja?",
"?Dónde va a ser? Por supuesto, estará en la taberna, o en algún otro lugar de la ciudad. Si yo fuera tú, iría a la taberna. Si Claire no está allí, aparecerá yarde o temprano.",
"Gracias. Ahora quiero hablar de negocios contigo.",
"Ya basta de tonterías. Vayamos al grano.",
"Gracias. Ahora, tengo que irme.",
"Iré a hablar con esa persona. Hasta la vista.",
"¿De qué quieres hablar?",
"¿Cuánto tiempo llevas en #sisla Muelle#?",
"¿Cuánto tiempo ha estado tu barco en este puerto?",
"¿Cómo ha ido nuestra singladura?",
"¿Y bien, te ha gustado navegar bajo mi protección?",
"¿Cómo va tu negocio?",
"Entonces, ¿te gusta ser un comerciante?",
"Por favor, recuérdame cuál era tu problema con los bandidos.",
"Una vez me hablaste de tu problema con los bandidos. ¿Puedes refrescarme la memoria?",
"Algunos de esos bandidos que han estado matando a tus animales están muertos, pero había demasiados en el campamento.\nNo te preocupes, voy a acabar con ellos.",
"Nadie te molestará, ni a ti ni a tus animales.",
"No, nada. Hasta la vista.",
"¡Que Dios te bendiga! ¡Me has ayudado mucho! Nunca te lo podré garadecer lo suficiente. Pero toma este catalejo. Lo encontré hace mucho en un galeón naufragado. Me sirvió bien en la mar y, como ya no lo necesitaré en tierra firme, quiero que lo tengas tú.",
"¡Aprecio mucho este regalo! No te preocupes. Si necesitas algo en el futuro, pídemelo.",
"Han aparecido unos bandidos en la isla, y están matando a mis animales. Me quejé a las autoridades locales, pero no prestaron atencion.\nPuedo apañármelas bastante bien para mi edad, pero creo que hay unos cinco de ellos, así que no puedo encargarme de todos.",
"Creo que puedo ayudarte. ¿Sabes dónde acampan esos bandidos?",
"¿Solo cinco personas? Haces una montaña de un grano de arena. ¡No me costará mucho enseñarles una lección! ¿Sabes dónde acampan esos bandidos?",
"¡Qué vergüenza! ¿Las autoridades no hacen nada para proteger a sus ciudadanos? Espero que el asunto se resuelva pronto.",
"¿Cinco personas? Eso es demasiado para mí.",
"A decir verdad, las cosas no van bien, capitán.",
"¿Qué pasa? ¿Has invertido dinero en algún negocio poco rentable?",
"No hay ningún problema, capitán. Decidí no abrir una tienda, sino comprar un rancho. ¿Sabes?, crecí en una granja, así que sé cómo cuidar de los animales.",
"Eso está bien, pero, ¿cuál es el problema?",
"¿Ser un ganadero? ¿Ese es el sueño de tu vida? Vaya, vaya... Entonces, ¿cuál es tu problema?",
"Todo iba bien al principio, pero entonces aparecieron algunos bandidos en la isla, que se dedican a matar a mis animales.\nTraté de denunciarlos a las autoridades locales, pero no me hicieron caso.\nPuedo apañármelas bastante bien para mi edad, pero creo que hay unos cinco de ellos, así que no puedo encargarme de todos",
"Creo que puedo ayudarte. ¿Sabes dónde acampan esos bandidos?",
"¿Solo cinco personas? Haces una montaña de un grano de arena. ¡No me costará mucho enseñarles una lección! ¿Sabes dónde acampan esos bandidos?",
"¡Qué vergüenza! ¿Las autoridades no hacen nada para proteger a sus ciudadanos? Espero que el asunto se resuelva pronto.",
"Entonces, ¿quieres que vaya y mate a esos sinvergüenzas? ¡En qué tiempos vivimos!",
"Bueno, ¿quién sabe? Supongo que en algún lugar de la selva. ¿De verdad quieres ayudarme? En ese caso, quiero recompensarte por tu amabilidad. Si te soy sincero, no tengo mucho dinero.\nPero perderé más dinero todavía si siguen matando a mi ganado. Cuando los mates, vuelve a verme. ¡Buena suerte!",
"Ey, no hay problema. ¿Por que no ayudar a un hombre necesitado?",
"Te ayudaré. Necesito un poco de ejercicio, de todos modos, y si tienes un poco de oro de sobra, eso también estaría bien...",
"¡Eso es maravilloso, ",
"! No hace mucho, me sentía seguro aquí, y también mis amigos.",
"Ah, no es nada. Por cierto, ¿dónde está tu 'Juno'?",
"Ya se ha hehco a la mar, y yo he ahorrado suficiente para abrir mi propio negocio en tierra.",
"Ya veo. Bueno, buena suerte. Espero volver a verte.",
"¿Así que has decidido convertirte en un comerciante? Vaya, vaya. Muy bien, buena suerte.",
"Buena suerte a ti también, capitán; ya es tiempo de que me vaya.",
"Adiós.",
"Ayer entregamos un cargamento de papel procedente de la colonia francesa. Nuestro capitán prefiere el comercio a todas las otras formas de hacer dinero, así que navegamos de un lado al otro de este archipielago.",
"¿Qué hay de los piratas? ¿Te molestan?",
"¿Y bien?, ¿cómo va todo? ¿Tienes miedo de los piratas?",
"Bueno, a veces nos dan algún susto. La última vez apenas escapamos de un Bergantín pirata, así que ahora nuestro capitán está buscando una escolta. Nuestro barco va muy cargado, es lento y poco maniobrable.",
"¿Dices que necesitas un barco de escolta? ¿Cuánto pagarías por este servicio?",
"Un barco de escolta, dices... Bueno, ¿cuántas monedas pondrás en mi bolsillo si accedo a escoltar tu barco?",
"¿Qué? No lo sé. Será mejor que le pregunte al capitán sobre eso. Debería estar en la tienda ahora mismo.",
"Le preguntaré a tu capitán. Gracias por tu ayuda.",
"Muy bien, hablaré con tu capitán.",

};
