string DLG_TEXT[28] = {
"I like your outfit.",
"Er.. Thank you.. I like yours too!",
"So, you think I might be able to help you on your quest?",
"Yes Catalina, if you'd be so kind.",
"Then you must contract with me to enlist my help. Remember, that I do things quickly. Think it over, or talk to some of the others first, but if you talk to me again we are contracted.",
"Yes Catalina, I understand.",
"You have spoken to me a second time, now we are contracted to work together on your quest. The word SWIM is only part of the information you need. We need to get the rest.",
"Yes Catalina, I couldn't see how it would lead me to a treasure.",
"It wasn't meant to. In case the message fell into the wrong hands, it has been split into parts.",
"Now you say it, that's pretty obvious?",
"Yes, perhaps it is. We need to find out how many parts, and where they are.",
"Oh! And how do we do that?",
"Ah! That's a little more complicated. Your father must have sent several messages with the rest of the information in those. Now, who could your father have sent letters to? Obviously within the family, he wouldn't have trusted anyone else. Who else is still alive in your family?",
"Well, me, my sister Bonnie.. and.. My brother Blaze.",
"So there you have it. Your sister has received nothing, else she would have told you, so it is your brother Blaze you need to find to complete the puzzle.",
"Mmmm! So how do I find him? I have no idea where he went to.",
"The last I heard he was in #sisland_Redmond#. The problem with that is that it is an English Island, and there is no way we could just sail in there under the pirate flag.",
"I see. So what do we do then?",
"I will join you as an officer, and we will sail on your ship, under the English flag. Then we should be able to land at #sisland_Redmond# without a problem. All we need to do after that is find your brother.",
"That sounds easy enough. I will make ready to sail.",
"Are you ready to sail then?",
"Yes, We're ready. Let's go.",
"Well I must say that was quite a trip. We'd better get on with the matter at hand though.",
"I'm glad you enjoyed it. I suppose we should go to the Tavern to see what we can find out?",
"No, no! I have contacts here you know. We are part of the same band of brothers, so to speak. We need to go to the Tailors Shop.",
"Oh! That sounds odd. But I suppose the less obvious things are the better the secret is kept.",
"We need to get a move on, we've work to do.",
"I'm coming.",
};