string DLG_TEXT[50] = {
"This is a suprise, I certainly didn't expect any visitors today. Actually, I don't expect any visitors at any time. But a pleasant surprise it is.",
"Are you O'Byrne?",
"That is me name for sure, lad. But who would ye be, if I don't know of any lad or lassie 'round here that I don't know, but who knows me? If ye know what I mean. Ye don't look like a Spanish colonist. Aye, yer a seafaring man, I can see! And an English one at that!",
"My name is Blaze. And if you don't know anybody, perhaps this is because you live in the wilderness of a godforsaken Spanish island?",
"Aye, yer a smart lad. But if ye've been looking for me, ye know who I am, right?\nI'm an Irish sailor who volunteered for a Spanish expedition! Aye, who thinks that such a creature exists? More scarce than a leprechaun they are, but here I am! I have a bad knee, courtesy of a shrapnel I took just off #sisland_Redmond#, and that's when it was time to settle down. Not much left for me in the old country, so one more time: Here I am!",
"That's an interesting story and it sounds almost as crazy as you look. So you truly are a hermit? You live here all by yourself?",
"This should answer yer question, lad! Blaze, this here's me daughter Annie, my dearest treasure. She's been out on the hunt so we have more to bite than fish and oatmeal! Annie, say hello to Blaze. He's a sailor and interested in old hermits, ha ha!",
"Daughter, ey? I can see the similarity.", // 7
"French pirates! Now we're in trouble!",
"What business would French pirates have here?",
"Hide and plot their next roguery I say! Aye, they don't have their eyes on #sGrand Cayman#, there's not much to gain in that jerkwater town. But the coast with its coves and islets is the perfect hideout to attack shipping between the mainland and ports like #sHavana# and #sRedmond#. Maybe the Frenchmen are not as stupid as they normally look!",
"...",
"The problem is, if they land in the bay and set up their camp here somewhere, we won't be save, Annie and me. Ye don't think stinkin' pirates would be peaceful neighbours to us? They'd kill us for joy or worse! We couldn't go out to hunt and chop wood, we'd have to hide in here shiverin', hopin' they won't discover us. Aye, Annie and meself, we can put up a fight, but we won't last. I can barely walk with this busted knee of mine.",
"Has something like this happened before, O'Byrne?",
"Aye, but back then, the pirates left the island after three days when a hefty storm came this way. But those three days were hell, livin' on the brink of being at the mercy of French scoundrels. I says we won't be that lucky every time.",
"But the Spanish colonists at the settlement, wouldn't they take you in? Wouldn't they do anything about the corsairs at all?",
"Yer funny, lad. Perhaps they're shiverin' like us. Perhaps they believe it's none of their business as long as the French don't attack #sGrand Cayman#. And no, they won't take us in. They hate us way too much\nWhy ye think we live out here? Because of the fresh air, sure. But also because the Spanish laugh at me limping and spurn me Irish heritage. If there's one thing they hate more than me, it's Annie. Her mother was a Spanish lass from the town, whom they taunted from the moment her belly started to grow.\nWhen the blasted fever took her, Annie and me were cast out. We prefer not to go to this hideous town.",
"That's terrible. But these people must have some kind of governor or whatever they call their local bigwig. I go there now, and talk to him.",
"Yer a good lad. Frankly I don't believe ye can convince him to even lift a butt cheek for us. But we're glad yer helpin' us.",
"I'll be back soon.", // 19
"Ye find the guvnor in the townhall of #sGrand Cayman#. If there's someone who can persuade him, yer that man, Blaze!",
"I'll see what I can do.", // 21
"Blaze! Did ye have any luck?",
"I'm afraid that so-called governor is as useful as a hole in the hull. We're on our own.",
"Blast it! Well, if nothing else, I'm glad yer saying 'we'. I take it yer tryin' to help us out here?",
"You're right, grandad! I'll be damned before I let some French pirates do whatever and wherever they please. I'm planning to teach them a little lesson.",
"Be careful with them pirates out there, lad.",
"I'll be doing my best!", // 27
"Blaze! Ye've been away for quite some time! What happened?",
"The corsairs won't bother you no more, that happened.",
"Tear me sails and sink me ship! I knew ye could do it! I better don't ask how ye did it, eh?",
"That's up to you, old man. But now we can take care of why I came here in the first place. Your name is on this map. I hope you have got some information for me in return?",
"I'll be jiggered! Aye, I know what this means!",
"Spit it out!",
"I already told ye I sailed with the Spanish, eh?\nWell, I was serving on a gunship from #sRedmond#. A pirate had just taken a merchant vessel with a cargo of silk, rum and sugar. Our mission was, to catch this pirate\nWe caught up with them near #sisland_Redmond#, right as a storm was brewing, and engaged them in battle. A shrapnel hit my leg. Hurt like hell and does to this day. The storm got worse, the pirates got away and I was washed overboard\nWhen I got me senses back, I had been fished out of the water by the very pirates we fought! They saved me life. I was sure they would kill me! But seeing I was Irish, they didn't. Even when they found out, I was from the Spanish gunship. The sawbones treated me wounds, the quartermaster fed me some of the stolen rum. They nursed me back to health, as good as they could\nI said I wanted to settle on land, and they agreed. Dropped me off at #sisland_Cayman# with a musket and enough supplies to set up a living for meself. They sailed and I never saw them again.",
"...",
"But the captain had given me a sealed paper. He made me swear, not to open it and only hand it out, when somebody is looking for it. This would be the case, when me name appears on a map. Now I suppose, this day has come, eh? So here it is. This paper has been with me for many years. Today, ye have more than deserved it.",
"Then I suppose we all came out as winners today. Thank you for the paper and the story, O'Byrne. I have to take this back to my sister.", // 37
"Don't be silly! Ye think I want me daughter to spend the rest of her days thumb twiddling in the jungle? If she has the opportunity to go on adventure and make something of her life, she should take it!",
"...",
"Always fair winds to ye, friend.",
"Likewise, old man!", // 41
"You've arrived not a second too soon, Blaze! If it weren't for ye, these filthy barbarians would have done me in for sure!",
"I was great, as usual, but Annie did her part in this as well, let's not forget that. Good shot, Annie! Right between the eyes from a strategic position, I like that!",
"Is it true then? You've dealt with the pirate ship?",
"I did, and it was one hell of a glorious carnage! The corsairs won't bother you no more.",
"Ye did great, Blaze! Ouch! My knee! I'm getting too old for this kind of adventure!",
"Let's get you inside then, grandad.", // 47
"Aah, that's better!",
"But now we can take care of why I came here in the first place. Your name is on this map. I hope you have got some information for me in return?",
}