string DLG_TEXT[28] = {
"Give no quarter... Take no prisoners...",
"You're a bit merciless, aren't you!",
"So, you think I might be able to help you on your quest?",
"Yes Captain, if you'd be so kind.",
"Then you must contract with me to enlist my help. Remember, that I show no mercy. So there will be a lot of fighting. Think it over, or talk to some of the others first, but if you talk to me again we are contracted.",
"Yes Captain, I understand.",
"You have spoken to me a second time, now we are contracted to work together on your quest. The word SWIM is deliberately jumbled. It should be MWSI.",
"MWSI... but hat makes no sense?",
"It does if you know what it means.",
"And... I assume you do. Is that correct?",
"Yes, perhaps I am. It means: Make War on a Spanish Island.",
"Oh! And how do we do that?",
"Ah! Not on our own. We will need some of the more, er, blood thirsty members of the brotherhood to join us.",
"This sounds like it is getting dangerous.",
"Not with the squadron of ships I propose, Miss Devlin.",
"But how will that lead us to the treasure? .",
"That I don't know, but I do know your father knew what he was doing. So things should come to light as we progress.",
"Are you sure about that?",
"Oh yes! Very sure. Your father was a clever man. He had this all worked out, I know. Do what you need now, we will meet you at the dock.",
"That sounds quite exciting. I will make ready to sail.",
"Are you ready to sail then?",
"Yes, we're ready. Let's go.",
"Well I must say that was quite a trip. We'd better get on with the matter at hand though. We cannot stay here long, the King's ships will soon be upon us. You are on your own now. Good luck!",
"Oh! Yes, I understand. I suppose we should go to the Tavern to see what we can find out?",
"No, no! I have contacts here you know. We are part of the same band of brothers, so to speak. You need to find XXXXXXXXXXX and mention my name.",
"Oh! I see. Well, I hope you all get back safely.",
"We will.",
"Goodbye, and thanks.",
};