string DLG_TEXT[28] = {
"So much to do... So much to do...",
"You seem very busy!",
"So, you think I might be able to help you on your quest? I must be frank with you. I am very busy, so I can tell you what to do, but I cannot come with you. You must handle the quest on your own.",
"Yes Captain, I realise what you are saying. If I accept your help with the quest, I am on my own in its execution.",
"Then you must contract with me to enlist my help. Remember, that I cannot come with you. Think it over, or talk to some of the others first, but if you talk to me again we are contracted.",
"Yes Captain, I understand.",
"You have spoken to me a second time, now we are contracted to work together on your quest. The word SWIM is, in the code we used, in reverse.",
"You mean as walk is to run, then swim would be to drown?",
"No, not that sort of reverse. In fact that would be opposite. In reverse SWIM becomes MIWS. That is the coded word we must examine.",
"Now you say it, that's pretty obvious?",
"Yes, perhaps it is.",
"So how do we examine MIWS?",
"WE don't. You need to know the code, which of course I do. I know most codes as it happens.",
"Ah! That is becoming apparent. So what is the code?",
"MI means Memorial Inscription, and WS is the name of the deceased.",
"WS? That could be anybody. William Smith for instance, and there must be hundreds of them in the island's church yards.",
"Not anybody at all. It will be a prominent person. And the only one that comes to mind is Weatherby Swann, but of course, he's not dead. He's currently the Governor of the English Islands.",
"If he's not dead, then what help is that then?",
"Your father had a very good reason for sending this, but I don't know what it is. All I can tell you is, go to #sisland_Redmond# and find out all you can about Weatherby Swann. You will find your answer there, I'm sure. Your father knew what he was doing, of that I'm sure.",
"That sounds quite exciting. I will make ready to sail.",
"Are you ready to sail then?",
"Yes, We're ready. We'll bid you thanks and farewell.",
"",
"",
"",
"",
"",
"",
};