string DLG_TEXT[84] = {
"Muy bien... їeres Horatio?",
"Sн, eso creo.",
"Horatio. Tienes....er...algunas cosas en la manga.",
"ЎOh! Gracias Archie. їQuй hacemos ahora?",
"Ya oнste al teniente. Pon la nave en marcha.. Vamos al.. cuarto de cubierta.",
"Estoy justo detrбs de ti.",
"! ЎEl Teniente Bracegirdle les estб contando a todos cуmo mataste a Simpson de un solo golpe! Y mнrate con tu nuevo y elegante uniforme. їPuedo preguntarle al teniente a quiйn tuvo que adular para eso?",
"ЎCбlmate, Archie! ЎFueron dos golpes! Ha! Ha! Parece que me voy a quedar atrбs mientras que el 'Indy' va a #sisland_Antigua#. ЎTodo lo que me queda es el barco alegre!",
"ЎAh! Un nuevo teniente. Una nueva nave. Y un nuevo cargamento de problemas me espera. Voy a navegar con el Indy, asн que debemos separarnos por ahora.",
"ЎArchie! ЎDetente! ЎDetente! Al menos Simpson no estarб ahн para molestarte. Buena suerte. Me voy a dormir un rato, estoy exhausto. Luego debo encontrar al Sr. Hunter.",
"Sн, pero їquй vamos a hacer al respecto?",
"Ahora mismo, Archie, vamos a seguir уrdenes. Vaya al Cuartel General de la Armada. Estб aquн arriba, en el jardнn redondo, creo.",
"ЎAlto! ЎAlto! El capitбn estб subiendo a bordo.",
"ЎYo no empecй!",
"Eso no importarб cuando llegue el capitбn.",
"Entendido.",
"! їQuй estбs haciendo aquн?",
"Una larga historia, Archie. їQuй es lo que te pasa? No tienes buen aspecto",
"Dйjame en paz ",
". No sabes lo que se siente aquн. Te machacarбn hasta que no seas nada.",
"ЎArchie! Contrуlate un poco. Vamos a hacer planes para escapar.",
"Escapar! Escapar! їCrees que no lo intentй? Cuatro veces escapй, cada vez que me capturaban de nuevo. La ъltima vez me metieron en un agujero en el suelo donde no podнa sentarme ni estar de pie durante un mes. Ya he tenido suficiente.",
"Esta vez serб diferente, Archie. Esta vez estamos todos juntos en esto.",
"Dejadme en paz. Sуlo dйjame en paz.",
"No te preocupes, Archie. Te pondrбs mejor. Ya verбs.",
". Todavнa estoy dйbil, pero me siento como un anciano.",
"Buen hombre. Al menos estбs de pie otra vez.",
"Dejadme en paz. Dйjame en paz.",
"ЎArchie! Descansa, hombre. Descansa.",
"їSu Gracia? їSu Gracia? Ella no es una Duquesa ",
". Es una actriz de Drury Lane. Solнa verla allн todo el tiempo.",
"ЎQuй! Debes estar equivocado, Archie.",
"Va a ser que no ",
". El teatro era uno de mis pasatiempos favoritos. La he visto en muchas obras de teatro.",
"No, no, no. Todavнa estбs un poco delirante, Archie.",
"Su nombre es Catherine Cobham. Ella es una actriz, te lo digo yo.",
"Es una duquesa Archie. La conocн en #sRedmond#.",
"El navнo espaсol se estб rompiendo en el arrecife ",
". їQuй podemos hacer?",
"Todos al bote y remen como el demonio hacia йl. Podemos salvar a algunos de ellos al menos.",
"Capitбn. He hablado con la tripulaciуn, y si la libertad condicional es para el Sr. ",
", entonces tambiйn a nosotros nos defenderб. A todos nosotros.",
"...",
"Es como en los viejos tiempos ",
". Como en los viejos tiempos. Supongo que podrнamos planear una fuga.",
"Sн, podrнamos. Es nuestro deber despuйs de todo.",
"No parece correcto en cierto modo. Quiero decir, con Don Masseredo tratбndonos tan razonablemente.",
"Las sombras de la guerra, Archie. Las sombras de la guerra. Las cosas tienden a ser muy confusas a veces.",
", Me alegro de volver a verte. Escuchй que fue una batalla infernal con los franceses.",
"Sн, Archie. Estuve cerca, pero їconoce nuestras nuevas уrdenes para unirnos al 'Renown'?",
"Sн, el capitбn James Sawyer y el Renown. ЎQuй tan afortunados somos! Uno de los capitanes mбs famosos de toda la marina. Hay que ir a #sGreenford# para unirse a la nave, segъn tengo entendido. їCуmo llegamos hasta allн?",
"A pie.",
"їCaminar? Bueno, eso NO es por lo que me unн a la marina.",
"No te preocupes por Archie. El ejercicio nos vendrб bien. Ven hasta la prуxima parada #sGreenford# serб mejor que nos vayamos. Al capitбn Sawyer no le gusta que le hagan esperar.",
"Nunca pasaremos por allн ",
". ЎLos espaсoles han visto el barco Y A NOSOTROS! Obviamente tienen sus armas preparadas en el puerto. Lo haremos mejor probando el viejo puente de cuerdas.",
"Sн, Archie, tienes razуn. Vayamos allн.",
"їCуmo vamos a tomar el fuerte? ",
"Usarй la pуlvora para volar la puerta. Cuando se vaya.... todo el mundo al fuerte. No deberнa haber tantos guardias.",
"Los comentarios del teniente Quelp sobre un ejйrcito de esclavos parecen ser ciertos. Apenas hay comida en este lugar. Los espaсoles no habrнan durado mбs que unos dнas con lo que les quedaba.",
"Tendremos que preocuparnos por eso mбs tarde, Archie. Ahora mismo tenemos que ver si volamos este lugar. їEncontraste algo de pуlvora?",
"Mucho! Eso sн tenнan. Sуlo que nada de comida. Hay mucho de eso apilado alrededor del patio.",
"Muy bien. Separйmonos y pongamos las cargas, luego nos vemos fuera de la puerta.",
"Me dispararon en el estуmago ",
"Debemos llevarte al cirujano Archie",
"Bueno, ЎEsa no era la bienvenida que esperaba!",
"Conozco a Archie, pero parecнa estar bajo mucha presiуn. Tal vez las cosas mejoren cuando lleguemos al mar.",
"Eso espero.",
"Subamos a bordo entonces.",
"Hay un barco que se acerca a Horatio.",
"їEs el capitбn?",
"No, pero es un oficial.",
"Muy bien, me encargarй de ello. Ve y revisa el cuarto de cubierta, Archie. Voy a ver al timonel.",
"El Capitбn no parece ser el hombre que pensй que era.",
"Tranquilo, vamos Archie. Йl tiene mucho en lo que pensar.",
"Eso es posible tal vez, Horatio. Pero se sale de sus casillas demasiado rбpido para mi gusto.",
"ЎArchie! Eso es suficiente.",
"їCуmo estб Mr. Wellard?",
"Estarб bien por la maсana, Archie.",
"Sуlo cumplнa con mi deber, Horatio. El capitбn se volviу loco y no habнa necesidad ni justificaciуn para ello.",
"Silencio Archie, viene el Sr. Bush.",
"El Capitбn estб peor ",
"Conozco a Archie y me preocupa.",
"Seсor.... Era yo..... Empujй al Capitбn Sawyer a la bodega.",
};