string DLG_TEXT[77] = {
"Buenos dнas Teniente.",
"Buenos dнas, Sir Arthur.",
"Entonces, Pellew, їpor quй llamу para que nos uniйramos a ti? Suena como si algo estuviera en marcha",
"[PIENSA: ЎQuй chica tan guapa! Y ella es la hermana del mayor.]",
"Capitбn. Creo que haremos mбs si Sharpe, Harper y yo vamos a la prisiуn e interrogamos al otro prisionero, mientras usted continъa su discusiуn. Podemos encontrarnos en la Academia mбs tarde. Buenos dнas, seсor. Y usted, teniente.",
"ЎOh! Sн. Buenos dнas, Mayor.",
"El Sr. Quelp no podнa esperar a ir a la casa del contrabandista para arreglar las cosas para mн, їverdad? Y por lo que aprendimos del prisionero, soy yo, en efecto, al que los franceses quieren eliminar.",
"Entonces, їquй hacemos ahora, seсor?",
"Tenemos dos opciones. El Sr. Quelp sin duda estarб corriendo por el tъnel mientras hablamos, para alertar a los franceses que estarй en la casa hoy a la tarde.", 
"Sin duda, seсor.",
"El Sr. Sharpe puede llevar su destacamento y esperar a que salgan del tъnel y luego tratar con ellos en consecuencia, o podemos aprovechar el tiempo que Quelp y los franceses tarden en organizarse, y usar el tъnel de la playa para llegar a tu barco y navegar hacia #sRedmond#.",
"Asн que, luchar o huir, entonces, seсor.",
"Si desea decirlo de esa manera, sн, teniente, luche o huya. їCuбl desea?",
"Con todo respeto, preferirнa que ambos, seсor. Combate Y LUEGO huir.",
"Explнquese, teniente.",
"Bueno, seсor, si el Sr. Sharpe prepara su tropa en la entrada principal, yo podrнa ir a la parte de atrбs y atraer a Quelp y a los franceses cuando lleguen. Sharpe y sus hombres los despacharбn.",
"Esa es la parte de la lucha que nos encargaremos. Y la huнda?",
"Cuando se ocupen de los franceses, tъ y yo podrнamos usar el tъnel de la playa, llegar a mi barco, y salir hacia #sRedmond#. Sin nadie vivo, los franceses en el campamento de piratas no sabrбn quй pasу ni adуnde fuiste.",
"ЎMaldita sea! No eran simples soldados de infanterнa. Eran tropas de primera. Higgins, ocъpese de nuestros hombres, creo que sуlo estбn heridos. Sin embargo, no hay seсales de Quelp, Ўeso parece extraсo! Necesitamos llegar a su nave ", 
"Sн, Mayor. En efecto, es extraсo, pero me temo que tenemos que salir de aquн rбpidamente. Por aquн al tъnel.",
". Nos preocuparemos por Quelp mбs tarde.", 
"Hiciste un buen trabajo. Los dos. Acaban de sacar a Edrington y me contу cуmo derrotaste a los franceses.",
"Gracias Sir Arthur, pero no sabemos si los franceses tienen intenciуn de desembarcar refuerzos en la playa.",
"Seсor",
"Eso no va a pasar. Logramos dar la vuelta al barco que desembarcу a nuestras tropas y ella persiguiу al barco francйs, asн que no habrб mбs tropas que desembarquen.",
"[PIENSA: Entonces, їpor quй nuestras tropas no volvieron con nosotros? Deben haber oнdo el caсуn.]",
"De todos modos, tengo una tarea mбs agradable para ti. Debes llevar estos documentos a #sGreenford#, al Cuartel General de la Marina. Con toda la velocidad que quieras. їLo has entendido?",
"Gracias Sir Arthur.",
"Bien...... Teniente Sharpe. Quiero que tome el mando del Segundo Batallуn mientras Edrington se recupera. Eso es todo caballeros. Buen dнa.",
".",
"Mi turno para las presentaciones, teniente. A su izquierda estб el teniente William Chumley, a su derecha, el fusilero Sharpe del 33er Batallуn.",
"Caballeros.",
"El teniente Chumley estarб al mando del destacamento principal, y Sharpe, de los escaramuzadores.",
"їEscaramuzadores? Creн que esto iba a ser una batalla",
"Teniente. Los escaramuzadores son un tanto inusuales en el sentido de que todos son muy buenos tiradores. Estamos pensando en ponerlos en su propio destacamento, pero eso es otra cosa.",
"Ya veo, seсor.",
"Bien. El Capitбn Pellew me ha seсalado que llevar el Infatigable a la costa en una misiуn de este tipo atraerнa demasiado la atenciуn de los franceses antes de que pudiйramos acercarnos a la orilla y arriesgarnos a que su flota se nos echara encima.",
"Puedo verlo, seсor. Estarнamos atrapados en la bahнa en aguas poco profundas. Lo que significarнa poco espacio para maniobrar, y eso pondrнa a la 'Indy' en una gran desventaja.",
"Mmmm. Bueno, tu teniente comandarб una nave mбs pequeсa que llevarб a las tropas y las desembarcarб en la playa. Obviamente, usted facilitarб los medios para su evacuaciуn despuйs de la batalla. їLo ha entendido?",
"Sн, Mayor. Completamente.",
"Buenos dнas, Comandante. Lamento lo del joven Kennedy. Un hombre valiente. Pero, debo preocuparme por el asunto que nos ocupa. Estoy a punto de lanzar una ofensiva para sacar a los franceses del Caribe.",
"їDe veras, Sir Arthur?",
"Sн. Tenemos la intenciуn de empezar por expulsar al enemigo de Guadalupe. Pero tengo un pequeсo problema, que tъ y Sharpe pueden resolver por mн.",
"Sн. Desde el maldito asunto del tъnel en Charlestown, alguien ha estado filtrando mis planes y tratando de matarme. Ahora Sharpe tiene algunas ideas, pero necesita un barco para llevarlas a cabo, y el Comodoro Pellew ha ofrecido sus servicios. їEstб preparado, Comandante?",
"Por quй.... Sн, seсor, por supuesto, pero no estoy seguro de que pueda ser de mucha ayuda en este asunto.",
"ЎTonterнas, hombre! Eres justo el hombre que necesito, y con Sharpe y sus rifles, sй que no necesito preocuparme mбs. Les deseo un buen dнa, caballeros, y les dejo que resuelvan los detalles.",
"Comandante Hornblower, me alegra ver que estб ileso. їCуmo va con los franceses?",
"Hasta ahora, seсor, estamos aguantando. Los fusileros de Sharpe los mantienen a raya, y nos las arreglamos para destruir uno de sus caсones.",
"ЎCapital Hornblower! ЎCapital!",
"Sн, seсor, pero no sй cuбnto tiempo podremos aguantar hasta que los franceses se den cuenta de que sуlo tenemos unos cuantos marineros y fusileros, y nos carguen con toda la fuerza. No podнamos resistir tal fuerza, seсor.",
"No hay que preocuparse por Hornblower. El barco que transporta al resto del Segundo Batallуn ha sido avistado dirigiйndose al puerto. їPodrб retener a los franceses una hora mбs?",
"Haremos todo lo posible, seсor.",
"Buen hombre! Entonces volverй y avisarй que los refuerzos deben venir directamente aquн cuando desembarquen.",
"Gracias, seсor.",
"Muy bien, disparar a ese.",
"їCuбl es su nombre?",
"Sharpe... Sargento. Segundo Batallуn 95 de fusileros Seсor.",
"Le estoy muy agradecido. Hizo un gran trabajo. Ahora le darй una muy difнcil. Le voy a dar una comisiуn de campo, Sharpe. A partir de este momento, serб teniente en la 95a.",
"Gracias, seсor.",
"Edrington, usted harб correr la voz sobre este ascenso, y le sugiero que permita que el teniente Sharpe use su tropa como crea conveniente en el prуximo combate. Eso es todo.",
"ЎHornblower! ЎSharpe! ЎSon un regalo para la vista! Estamos siendo atacados por los franceses desde la playa. No puedo sacar tropas del fuerte por miedo a que esto sea una treta y que realmente intenten invadir el puerto..",
"їQuй necesita que hagamos, Sir Arthur?",
"Tъ y Sharpe lleven a sus hombres a las afueras y eviten que los franceses entren en la ciudad.",
"Sн, sн, Sir Arthur...... ЎMatthews! Coge a Oldroyd y Styles y ve a ver quй pasa.",
"Esto va a ser algo muy reсido, caballeros. El cuerpo principal de tropas se encuentra en un barco rumbo a #sisland_Guadeloupe# para establecer un punto de apoyo para mi inminente ataque. He enviado una nave de bъsqueda para que regresen, pero eso llevarб tiempo.",
"Iremos a las afueras y mantendremos esa posiciуn para proteger su flanco, Sir Arthur.",
"Buen hombre. Debo quedarme aquн y organizar las pocas tropas que me quedan. Ahora vбyanse, no tenemos mucho tiempo, pero sй que puedo confiar en ustedes.",
"Me alegro de verle de nuevo, Hornblower.",
"Igualmente, seсor. Me alegro de verle.",
"En cuanto al plan Almirante, dudo que esta paz temporal con los franceses dure mucho tiempo, asн que tenemos que estar un paso por delante de ellos.",
"...",
"Tenemos esa parte de la operaciуn cubierta por el Capitбn Hornblower. їRecuerda al teniente Sharpe del 95?",
"Sн, Coronel, muy bien.",
"Bien. Bueno, йl y el mayor Hogan trabajan, digamos, juntos. Sharpe te llevarб a Hogan. Sharpe estб sirviendo actualmente en la Compaснa del Mayor Dunnitt de la 95ava.",
"Aquн estбn las уrdenes de liberaciуn de Sharpe que lo respaldan a йl y a sus hombres. Dбselas al capitбn Murray cuando llegues a la 95.",
"Er, Coronel. їDуnde estб la 95?",
"Estбn en las Islas Caimбn.",


};
