string DLG_TEXT[51] = {
"¡Ah! ... Hornblower.",
"Capitán Hammond.",
"¿Y bien, señor? Preséntese, no hay tiempo que perder.",
"H.. H... Hornblower, señor. H... Horatio Hornblower, guardiamarina. Quiero decir, teniente en funciones, Infatigable.",
"Certificados por favor.",
"A estas alturas está abatido.... Desarbolado señor.... Los acantilados de Dover bajo su dirección.... Están en serios problemas, Sr..... Hornblower.",
"Estaba en cubierta cuando el Capitán Sawyer fue empujado a la bodega, ¿no?",
"Sí, señor, yo estaba en cubierta, pero no lo empujaron, señor, se cayó.",
"¿De verdad, teniente? Pero sólo tenemos su palabra para eso, ¿no?",
"Sólo puedo repetirlo, señor, no fue empujado, se cayó.",
".",
"Comandante Hornblower. Su nave será retirada del servicio inmediatamente. Será trasladada a #sOxbay# y trabajará allí. Recibirá la mitad del pago hasta que sus servicios sean requeridos nuevamente. Y por supuesto, sin un barco al mando, volverá al rango de teniente.",
"lo entiendo Capitán, pero ¿dónde me alojo ahora?",
"¡Hombre de Dios! ¿Espera que la marina le mime? Debe ir a la ciudad y buscar alojamiento en alguna parte. Buenos días, señor.",
"¡Oh! ...",
"Seguro que el país no puede seguir manteniendo una marina de guerra. Si no, pagaremos este maldito impuesto todos los años.",
"¡Oh! Sí. Que tenga un buen día, capitán.",
"?",
"¡Ah! ... Hornblower.",
"Buenas noches, capitán Hammond.",
"Caballeros. Mi sobrino, Jack Hammond. Bueno, sube, muchacho. Acérquese. En su primera visita a los mares. Confía ser enviado a un barco.",
"...",
"¿Qué está insinuando, señor?",
"Considero ese comentario ofensivo, señor.",
"¿Le importaría retirar su declaración? ¿Con una disculpa?",
"Muy bien... Continuaremos con esto más adelante.",
"¡Por Dios, señor! No voy a tolerar esto. Tendré mi recompensa en un duelo a primera hora de la mañana.",
"Enviaré a un amigo para que te atienda",
"Así que a pesar de la heroica actuación de Hornblower, no tenemos ni idea de cuáles son los planes franceses.",
"Almirante Pellew, señor. Creo que hay una forma de superar ese problema.",
"Que Dios nos salve de estos jóvenes para su gloria...... Señor, debo insistir en que envíe a un oficial más experimentado.",
"¿Incluirá a mi sobrino en su grupo de tierra, verdad? Confío en que le permitirá templar su acero en los fuegos del combate.",
"Oh! Ciertamente lo consideraré, señor.",
"...",
"Capitán Hammond. ¿Entrega tu espada y dile a tus hombres que depongan sus armas, o prefieres que los maten a todos?",
"Nos superan en número. Bajen las armas.",
"Llévelos a la prisión, teniente.",
"Me alegro de verte de nuevo, Wolfe. Eso fue fácil, sin tropas de las que preocuparse ahora. ¿Tienes a Hornblower?",
"Todo bien cerrado. Ahora, enviemos las bengalas de señal y veamos a Pellew y a la flota navegar hacia su destrucción.",
"NO VUELVA Hornblower!",
"Capitán Hammond!",
"¡Y tú pensabas que tu enemigo era un rango inferior! Qué tonto eres, Hornblower.",
"Y qué traidor es usted, señor.",
"Suficiente con esto. ¡Wolfe! Estos hombres fueron detenidos tratando de escapar. Ocúpese de ellos.",
"Oh No! Jack Lad..... tú no.",
"Está muerto, señor. Murió luchando por su país.",
"Quería que lo encerraran en prisión contigo, Hornblower. Seguro de estar a salvo.",
"Y quería demostrar que era un oficial valiente. Lo que hizo.",
"¡Oh Dios! ¿Qué he hecho?.",
"Has traicionado a tu país, a tus camaradas e incluso has causado la muerte de tu sobrino. No eres buen hombre, ¿verdad?",
"Pare señor..... ¡Capitán Hammond! ¡No me obligue a dispararle, señor!",
};