string DLG_TEXT[46] = { 
"Capitбn Murray, Segundo Batallуn, Fusileros 95th, seсor.",
"Continъe.",
"Capitбn Murray, Segundo Batallуn, Fusileros 95th, seсor.",
"Continъe.",
"Seсor Comandante. їA quй debemos el placer de la presencia de un oficial naval de tan alto rango?.",
"Tengo уrdenes del almirante Pellew y del coronel Wellesley sobre su batallуn. їDуnde puedo encontrar a su oficial al mando?",
"Bueno, yo soy el capitбn Murray. El mayor Dunnitt estб al mando. Estб en aquella casa. Lo llevarй con йl, seсor.",
"Gracias, Capitбn. Le seguirй.",
"Estos papeles estбn en orden, seсor. Trasladen a Sharpe al comandante para tareas especiales.", 
"...",
"No... voy a... lograrlo. Dale a Sharpe,... mi espada. Dejadme. Saque... a los hombres... de aquн.",
"Capitбn....",
"[tos] Saquen a los hombres [tos] de aquн. Es es una orden. [tos] Dнgale a Sharpe que se haga cargo.",
"Si Capitбn.",
"?",
".",
".",
".",
"", 
".",
"?", 
".",
".",
".",
".",
".",
".",
".",
".",
"?",
".",
"?",
".",
".",
"",
".",
".", 
"",
"",
"",
"",
"",
"",
"",
"",
"", 
};
