string DLG_TEXT[15] = {
"Otro dнa mбs antes de la tormenta.",
"Eso es lo que firmamos.",
"",
"",
"",
"",
"ЎHoratio, espera! Todavнa estamos atrapados con ese matуn de Simpson. No sй cuбnto tiempo mбs podrй aguantarlo.",
"Todos sentimos lo mismo Clayton.",
"їTe encuentras bien? ",
"? Eso fue un buen golpe, y como siempre, huyу antes de que pudieras responder.",
"Estoy bien, Clayton. Creo que la ъnica manera de tratar con йl es retarlo a un duelo. Entonces no podrб huir, pero este no es el lugar ni el momento adecuado. Vayamos al astillero y luego volvamos a bordo.",
"ЎNo Horatio! ... ЎSimpson! Te reto a un duelo. ЎAquн, ahora!",
"ЎClayton!",
"Lo siento Horatio.. ",
"ЎQuй!",
}
