string DLG_TEXT[46] = { 
"Teniente Murray, Segundo Batallón, Fusileros 95th, señor.",
"Continúe.",
"Teniente Murray, Segundo Batallón, Fusileros 95th, señor.",
"Continúe.",
"Señor Comandante. ¿A qué se debe la presencia de un oficial naval de tan alto rango?.",
"Tengo órdenes del almirante Pellew y del coronel Wellesley sobre su batallón. ¿Dónde puedo encontrar a su oficial al mando?",
"Bueno, yo soy el teniente Murray. El mayor Dunnitt está al mando. Está en la casa de allí. Lo llevaré con él, señor.",
"Gracias Teniente. Le seguiré.",
".", 
".",
"?",
".",
"?",
"?",
"?",
".",
".",
".",
"", 
".",
"?", 
".",
".",
".",
".",
".",
".",
".",
".",
"?",
".",
"?",
".",
".",
"",
".",
".", 
"",
"",
"",
"",
"",
"",
"",
"",
"", 
};
