string DLG_TEXT[191] = {
"Hola, Hornblower. Confío en que todo le vaya bien ",
"Sí, gracias, teniente.",
"Soy el teniente segundo William Bush presentándose al servicio. ¿Dónde puedo encontrar al Capitán?",
"Aún no está a bordo, teniente. Soy el teniente tercero Horatio Hornblower. ¿Quizás le gustaría guardar su equipaje mientras lo esperamos? Debo ir a la cubierta del timón.",
"Encantado de conocerlo Mr. Hornblower. Sí, lo haré.",
"Podemos hablar más tarde, señor.",
"¡Ah! Gracias, teniente. Sí, señor.",
".",
"...",
"Se acercan varios más de ellos. Llegar a la cubierta del timón ",
", Póngase al timón. Debemos asegurarnos de que tenemos la nave. Archie, mire abajo. Los hombres de Sharpe deben estar ahí abajo. Y encuentre al teniente Buckland y al capitán Sawyer.",
"¡Captain Hornblower! pensé que era usted.",
"¡Sr. Bush! Pero ya no soy capitán, no tengo nave... ni condecoraciones, así que yo también soy teniente. De todos modos, ¿qué hace aquí?",
"Vengo aquí todos los meses a cobrar mi medio sueldo y me hospedo donde es barato.",
"Sí, Teniente.",
"Bueno, venga y quédese en mi alojamiento. Le aseguro que allí es barato .",
"No me importa pagar por adelantado, señora.",
"Tienes un admirador. La hija de tu casera. Vi la forma en que te miraba.",
"¿MARÍA? No! No, no, no, no. Tonterías.",
"Veremos Horatio. Veremos.",
"Ven. Te mostraré cómo complemento mi escaso sueldo en la casa del boticario.",
"¿El del boticario? ¿Te has metido en la medicina?",
"No. El boticario nos deja usar la habitación. Hay un juego de cartas privado de noche, y lo hago bastante bien. Sígueme.",
"¿Qué cree que quiere?",
"Bueno.... Dudo que quiera jugar al whist.",
".",
"No parece que necesitemos abrir la puerta.",
"¿Qué quiere decir, Sr. Bush?",
"Eche un vistazo ",
". Si no me equivoco, el comandante del fuerte acaba de rendirse.",
"Eso es muy extraño. Muy extraño, de hecho. Necesitamos ver qué está pasando aquí.",
"Algo no va bien aquí ",
". Los españoles se rindieron con demasiada facilidad. Espere aquí mientras el Sr. Kennedy y yo echamos un vistazo.",
"A la orden, Sr. Bush.",
"¿Estamos todos listos entonces? ¿Todos los explosivos puestos?",
"Entonces larguémonos de aquí. Cruze el puente tan rápido como pueda.",
"Prepárense, caballeros. En cualquier momento.",
"¡Bien hecho! Bien hecho, caballeros. Creo que podemos dar esta misión como cumplida.",
"Eso creo, Sr. Bush.",
"Es hora de volver al navío, caballeros.",
"El Sr. Kennedy y yo terminamos aquí. Si está listo, podemos ir fuera y poner los explosivos.",
"Me temo que me he hecho un corte feo en el vientre ",
"Tenemos que llevarte a la enfermería.",
"Teniente Bush, suba a bordo, señor.",
"Llegué unos minutos antes que usted, señor. Quería presentarme personalmente. Y permítame decirle, señor, que es un honor servir a las órdenes de un capitán con un historial tan distinguido.",
"¿De qué están hablando, caballeros?",
"Er... el tiempo Sr. Bush. Parece que está soplando un poco.",
"Sí, está soplando ahora. Tendremos que quitar un poco de vela.",
"A la orden, Señor Bush.",
"Tenemos que arreciar la gavia.",
"El Capitán tiene que ser informado primero, señor. Reglamento de la Junta Directiva.",
"Muy bien. Mr. Kennedy, ¿podría por favor?.",
"Caballeros. Tenemos la obligación de atender al Capitán en su camarote.",
"Señor.. Creo que Mr. Hornblower sólo estaba haciendo una observación.",
"Caballero... cuidado con sus palabras. Lo que está sugiriendo está al borde del motín. Y no necesito recordarle la pena por ese delito.",
"Pero la opción del Sr. Bush es arriesgar la nave y la tripulación frente al enemigo.",
"Eso podría ser así Mr. Hornblower, pero como Mr. Buckland señaló, es el Doctor Clive quien debe decidir.",
"Parece que no estamos solos, caballeros",
"Deben ser parte del ejército rebelde del que hablaba Buckland.",
"Puede ser Mr. Hornblower, pero no nos dejarán pasar, y son demasiados para que los asumamos. ¿Qué sugiere que hagamos?",
"Muy sencillo, señor Bush...... Archie.... Dispare el cañón, por favor",
"Horatio es usted muy ingenioso. Muy ingenioso. ¿Pero cómo sabía que el cañón estaría cargado?",
"No sé...... Parecía lógico que los españoles no tuvieran un cañón tripulado para proteger el puente, si no estuviera cargado.",
"Hmmm. Su lógica, o quizás su suerte, nunca deja de sorprenderme, Horatio. Pero volvamos a asuntos más urgentes. ¿Están todos los explosivos puestos?",
"¿Qué quería el almirante?",
"Un Comandante.... para el Hotspur.",
"Felicidades Horatio, er, Señor. No podría haber elegido a un hombre mejor.",
"Gracias, pero esa no es el Renown.",
"Pero es una buena nave, señor.",
"¿Usted cree que sí?",
"Sí, eso creo.",
"¿Cree usted también, Sr. Bush, que un teniente que sirvió en un setenta y cuatro, podría ser feliz sirviendo como teniente en un simple balandro?",
"Si fuera capitán Señor, creo que lo haría.",
"Entonces, ¿me haría el honor de ser mi primer teniente?",
"Soy yo quien se sentiría honrado, señor.",
"Temía de que no quisiera.",
"Temía que no me lo pidiera.",
"Bueno, tenemos una nave que preparar.",
"A la orden, Capitán.",
"Primero tenemos que ir a la taberna a contratar tripulación.",
"Siempre podemos encontrar un lugar para Matthews, señor.",
"¿Quiere sumarse a nuestros problemas, Styles? [¿Señor?] Styles, nunca deja de sorprenderme. [Gracias, señor].",
"¿Experiencia?",
"¿Qué lo trae al puerto?",
"Firme aquí Wolfe.",
"Bueno, eso llena a la tripulación, señor. Supongo que deberíamos volver a casa de la Sra. Mason y empacar nuestros baúles",
"Sí, tiene razón, William. Vamos a movernos, o no dormiremos esta noche.",
"Capitán, he terminado de empacar, y con su permiso, señor. Me gustaría dormir a bordo del Hotspur esta noche para preparar a la tripulación para mañana.",
"Muy bien, Sr. Bush. Permiso concedido, le veré a bordo por la mañana.",
"Sí, señor. Entonces le doy las buenas noches.",
"Buenas noches, Sr. Bush.",
"¿Qué fue todo eso?",
"No lo sé William, pero me siento incómodo al respecto, y no sé por qué.",
"Lo que no entiendo es por qué le pedía un contramaestre, cuando podía ir a la taberna local y lo más probable es que encontrara uno allí",
"Dejemos el tema por el momento, William. Quelp y yo nos conocemos desde hace un tiempo, y nunca fue bueno. Necesito tiempo para pensar. Subamos y encontremos la 95a.",
"Sí, Capitán. Lo siento, señor. Podríamos probar en la taberna. El Sr. Chadd está cuidando el buque, así que le di permiso a algunos de los tripulantes. Probablemente ya estén allí y puede que hayan oído algo.",
"Sí, hagamos eso.",
"¿Cree que es prudente unirse a una banda de guerrilleros, señor?",
"Tenemos órdenes de encontrar al mayor Hogan y es nuestra única opción ahora mismo. Vamos William, necesitamos dormir un poco. Conseguiré una habitación del tabernero.",
"Buenos días, señor. La nave y la tripulación están listas y los fusileros están a bordo.",
"Muy bien, Sr. Bush. Vamos a ver si nuestros compañeros guerrilleros están listos.",
"¿Sus órdenes, Capitán?",
"Lleve el Hotspur al mar. No quiero que la atrapen aquí en la bahía. Manténgase fuera de la vista de tierra un día, luego acérquese. Deberíamos estar de vuelta en la nave del comandante para entonces. Si no estamos aquí, debe tomar el Hotspur e informar al Almirante Pellew.",
"Gracias Sr. Bush. ",
"Y recuerden, No se enfrenten con los franceses. Por lo que sabemos, aún estamos en paz.",
"Gracias a Dios que ha vuelto, señor. Estábamos empezando a preocuparnos, los fusileros están a bordo, pero hay muchos barcos franceses por aquí. Necesitamos abordar de inmediato.",
"Cálmese, Sr. Bush. ¿Se reunió en la nave con el comandante Moreno?",
"Sí, señor. Por eso me tomé la libertad de traer el Hotspur inshore.",
"Bien. Tenemos que llegar a #sGreenford# y al Almirante Pellew a toda velocidad. Suba a bordo y levante el ancla, Sr. Bush. Se lo contaré todo en el camino.",
"El almirante obviamente ha leído su informe, señor.",
"Sí, Sr. Bush. Me pregunto qué habrá hecho con él.",
"Él valora su opinión, señor. Sin duda quiere discutir sus planes con usted.",
"Ya veremos, Sr. Bush. Ya veremos. Asegúrese de que la nave sea reabastecida mientras no estoy. Tengo el presentimiento de que no nos quedaremos aquí mucho tiempo.",
"Capitán, el navío está aprovisionado y listo para zarpar, y Wolfe ha sido liberado de la Sophie, así que está de vuelta con nosotros.",
"Gracias, señor Bush. Wolfe, suba a bordo. Al mar, Sr. Bush. Vamos a navegar hasta Anse Casse Bois en #sisland_Guadeloupe#, luego cruzar la isla, hasta el llamado faro, y destruirlo.",
"Eso suena mejor, Capitán.",
"Es más grande que eso. El capitán Hammond atacará y destruirá la batería del fuerte, para que el almirante Pellew pueda navegar y destruir la flota francesa.",
"Eso detendrá a los franceses de continuar sus planes de invasión.",
"Exactamente, Sr. Bush. Exactamente. Ahora vayamos a la nave, se espera que el Hotspur haga una buena demostración de sí mismo en esta aventura.",
"Mire señor, están el Capitán Hammond y el Teniente Quelp. ¿Quizás si nos damos prisa podemos compartir un bote con ellos de regreso al barco?",
"No hay prisa, Sr. Bush. Nuestro barco también está allí. Veo que Wolfe también está en el muelle. Me pregunto por qué no se sube a nuestro bote. Tal vez nos esté esperando. De todos modos, vayamos al mar, Sr. Bush. Tenemos un faro que volar.",
"Todos listos para desembarcar, Sr. Bush.",
"Retiren a los hombres, Matthews. El Almirante tiene otros planes para nosotros.",
"Pero señor, podríamos estar allí y volver antes de que él se enterara.",
"¿Está sugiriendo un motín, hombre?",
"¡No, señor! Sólo deseo que...",
"Yo también Matthews. Apoyaremos la acción. Prepárense para entrar con el escuadrón. [A la orden, señor.]",
"Sr. Hammond, Sr. Matthews, preséntense en la cubierta.",
"A la orden, señor.",
"Tenemos una señal del buque insignia para navegar a popa. Pronto estaremos en las zonas de acción.",
"Esto no me gusta, señor.",
"Relájese Matthews. El capitán Hammond se ha ocupado de las armas.",
"¡Cambie el rumbo a babor!",
"Si lo hacemos, encallaremos, señor.",
"¡Si no lo hacemos, nos harán pedazos! Cambiar el rumbo. Correremos bajo los cañones y desembarcaremos en los botes.",
"¡A la orden, señor! ¡TIMÓN A BABOR!",
"Hemos hecho nuestra parte, señor. Ahora le toca al Almirante Pellew.",
"Sí William, y por el sonido de esas armas, está haciendo un buen trabajo.",
"El Hotspur ha recibido una pequeña paliza, señor, pero podríamos volver a unirnos al escuadrón y a la lucha.",
"No, William, como dijo, hemos hecho nuestra parte. Tenemos que llevar el Hotspur de vuelta a Bridgetown para repararlo. Esperaremos al escuadrón allí.",
"Señor, Wolfe está en prisión.",
"Bien. Ese traidor finalmente obtendrá su recompensa.",
"Y señor, conocí al teniente Sharpe. Le gustaría unirse al interrogatorio. Se reunirá con usted en la prisión.",
"Gracias, Sr. Bush. Eso es todo por ahora.",
"Gracias por permitirme estar aquí, señor. Y permítame ser el primero en felicitarlos y desearles un largo y feliz matrimonio.",
"Gracias, Sr. Bush.",
"Un poco de ron, ¿eh, señor?",
"Son aliados de Su Majestad, Sr. Bush.",
"¿Aliados, señor? Pensé que esta parte del mundo pertenecía a España.",
" ha sido persuadido por Inglaterra para rebelarse contra España.",
"¿Entonces nuestro cargamento de armas es para él?",
"Si ",
" puede conquistar Cuba, España tendrá que tomar barcos y soldados de Napoleón para preservar sus colonias.",
"Sr. Bush, aquí están las llaves de mi caja de despacho que contiene las órdenes del Almirantazgo. Si no vuelvo a bordo a medianoche, asumirá el mando.",
"¿No ha vuelto a bordo, señor? Pero dijo que estaban de nuestro lado.",
"La guerra engendra extraños aliados, Sr. Bush.",
"Prepare los botes para almacenar el barco, Sr. Bush. Hay suficientes provisiones a bordo para que seamos independientes durante dos meses. Nuestra carga va a tierra.",
"A la orden, señor.",
"Sr. Bush, hay un buque español de 60 cañones que llegará antes del amanecer. Envía a tu mejor observador a la cima de esa colina para advertirnos de la llegada del enemigo.",
"El puesto de observación informa: 'Natividad' avistado, señor.",
"Oh, gracias, Sr. Bush, apagaremos las luces.",
"¡APAGUEN TODAS LAS LUCES!",
"¿Debo detener la carga, señor?",
"No, aún nos quedan unas horas.",
"¿No vamos a navegar por aguas abiertas, señor?",
"No, permaneceremos anclados aquí, bajo el amparo de este punto.",
"Sr. Bush, ¿podrían usted, el Sr. Gerard y el Sr. Longley darme el placer de su compañía en la cena de esta noche?",
"¡Gracias, señor! Er - ¿Esta noche, señor?",
"Nuestro joven guardiamarina puede estar arriesgando su vida antes del amanecer, Sr. Bush. Su estómago podría sentirse mejor con una comida.",
"Como son estos españoles. Había estado apostando a que harían exactamente eso.",
"Ahora, caballeros, esto es lo que planeo hacer. Sr. Bush, escoja un pelotón de los mejores nadadores de la tripulación, y luego entrégueles armas.",
"Sr. Bush, ¿podría llevar a los oficiales al '",
"' y ponerles grilletes.",
"Es una belleza, señor. La superintendente cree que vale 120.000 guineas. Eso le da a cada hombre un premio a bordo '",
"' 50 guineas en metálico.",
"El 'Natividad' no es un barco caro, Sr. Bush.",
"¿Cómo dice, señor?",
"Va a ser utilizada por nuestro aliado, Don Julián.",
"¿La está regalando, señor? Pero tu propia parte valdría 10.000.",
"No pedí cifras.",
"Pero señor, usted mismo dijo que don Julián estaba loco. ¿Puede confiar en él?",
"Descanse tranquilo, Sr. Bush. Sólo yo tendré que responder ante el Almirantazgo por esta decisión.",
"Don Julián está subiendo a bordo, señor.",
"Un saludo de 11 cañones, Sr. Bush",
"A la orden, señor. ¡FUEGO!",
"Sr. Bush, estamos regresando a la ",
"¿Qué es, Sr. Bush?",
"Lugre español, señor. Con una bandera blanca. Eso significará una charla.",
"Saca un arma.",
"Traigan a los prisioneros aquí.",
"Sr. Bush, le pido que les recuerde a todos que esto sigue siendo un barco de guerra",
};