string DLG_TEXT[44] = {
"Buen dнa.",
"Guardiamarina.",
"Teniente.",
"Comandante.",
"Capitбn.",
"Que tenga un buen dнa, teniente.",
"Buenos dнas, Comandante. їQuй le trae hoy por aquн?",
"Me dijeron que entregara estos documentos.",
"ЎAh! Sн. De hecho, son para mн. Mбs informaciуn sobre el tamaсo de la fuerza enemiga. Una pйrdida de tiempo, ahora los barcos y los hombres estбn fuera de servicio.",
"Fuera de servicio?",
"ЎOh! їNo te has enterado? El йxito de Wellesley en hacer retroceder a los franceses en #sSt John's# y el escuadrуn de Pellew hundiendo cinco de sus barcos ha hecho que los franceses firmen un tratado de paz. Asн que no necesitamos tantos barcos, ni hombres. Estбn siendo varados.",
"ЎOh! ЎNo! Los pobres diablos. Eso significa la mitad de la paga.",
"No te has enterado, їverdad? ... Me temo que usted y su nave estбn entre los que estбn siendo retirados. Deberнa ir a ver al capitбn Hammond.",
"Esto no suena nada bien.",
"Capitбn Hornblower, seсor.",
"їSi teniente?",
"Una seсal del buque insignia, seсor. Debe presentarse a bordo de inmediato.",
"Muy bien, Teniente. Gracias.",
"Buenos dнas, Comandante.",
"Buen dнa. Me dijeron que me presentara aquн.",
"Ah, sн. El Almirante Pellew le estб esperando.",
"Me pregunto quй tendrб para mн esta vez.",
"їQuй puedo hacer por usted hoy, seсor?",
"Estoy aquн para informar al Almirante Pellew.",
"Sн, creo que le estб esperando. Pase, seсor.",
"Gracias, Teniente.",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
};