string DLG_TEXT[54] = {
"Anнmate, Horatio. Pronto conseguirбs otra nave.",
"Eso espero, Marнa. Espero que sн.",
"Yo soy Marнa. Mi madre se ha ido a dormir.",
"ЎAh! Soy Horatio, Horatio Hornblower, retirado de la Marina de Su Majestad.",
"No estбs contento de que te hayan dado de baja, їverdad?",
"No sй que serб de mн. Sуlo conozco la vida en el mar.",
"No te preocupes, te harй compaснa, y puedes usar la vieja tartana de mi padre, estб amarrada en el puerto. Solнa usarlo para pescar cuando estaba en casa. Pero no es bueno para el mar abierto.",
"Gracias. Podrнa hacer eso. Voy a tener mucho tiempo libre.",
"Un centavo por tu pensamiento, Horatio.",
"ЎOh! .... Hola Marнa. Estaba deseando que la flota zarpara y pudiera conseguir de nuevo un puesto en un barco .",
"ЎHoratio! їQuieres decir que ya estбs cansado de mi compaснa?",
"ЎNo! ЎNo! Marнa. Es sуlo que llevo aquн tres meses y estoy muy atrasado con el alquiler. Necesito un puesto para ganar dinero.",
"Sуlo estaba bromeando Horatio. Y no te preocupes, he pagado el alquiler de esta semana por ti. Mamб no te perseguirб por ahora. Por cierto, notй que empeсaste tu espada. No conseguirбs un puesto sin una. Aquн tienes, toma esta.",
"Marнa.... Eres una buena amiga.",
"Espero ser mбs que eso Horacio.",
"Maria... Er...",
"De todos modos, tengo algunas noticias que deberнan animarte.",
"їEn serio? їY quй podrнa ser eso?",
"Hay algunos soldados en la ciudad que dicen que sirvieron contigo. Creo que dijeron fusileros. Les dije que vendrнa a buscarte. Estбn en la Taberna.",
"ЎFusileros! Marнa. Y gracias, me gustarнa volver a verlos. Por favor, discъlpame, irй a la taberna ahora.",
"Er! Lo siento madre, lo olvidй. Mr. Hornblower me dio media corona esta maсana. Estб en mi habitaciуn.",
"No quiere ser tan dura contigo.",
"Creo que se acuesta con Marнa, y por una razуn. No es un buen inquilino, de ninguna manera.",
"Creo que eres un verdadero caballero, Horatio.",
"Debo ir a la ciudad ahora, Marнa. Creo que tengo una manera de conseguir algo de dinero para el alquiler. Te verй mбs tarde.",
"Mr. Hornblower. No nos vas a dejar, їverdad? A veces mi madre se va de la lengua... ",
"Me han dado el mando de una nave. Zarpo maсana.",
"Entonces dйjame hacerte el equipaje, seсor.",
"Eres muy amable, pero ya lo he hecho.",
"Pero nunca te volverй a ver, seсor.",
"Lo siento, pero es mi deber.",
"Mr. Hornblower, seсor. Me avergьenza, seсor, que nos vea asн. Sucediу muy rбpido. No sabнa que estбbamos atrasados, y los alguaciles no nos escucharon y ahora no podemos ganar nuestra libertad.",
"Fuiste mi amiga en un momento de necesidad, Marнa, permнteme ser tuyo.",
"No, seсor, no debe hacerlo.",
"Es demasiado tarde, Marнa. Ya estб hecho.",
"Gracias, seсor. No sй quй decir.",
"No digas nada, Marнa. Sуlo ve y paga tus deudas. Debo volver al mar ahora, pero volverй de nuevo.",
"Mr. Hornblower, seсor. Vi el Hotspur, en el puerto. Esperaba que fuera una seсal de tu regreso.",
"Debe ser bueno para ti estar en casa de nuevo.",
"...",
"Lo es. Gracias, seсor, y tambiйn me alegro de verte. Entra.",
"їTienes suficiente para el alquiler?",
"Espero conseguir un puesto de institutriz y no puedo ser una carga por caridad.",
"No eres una carga, te lo aseguro.",
"No Mr. Hornblower, no puedo. Hay una palabra para una mujer que acepta dinero de un hombre.",
"Sн, y esa palabra es amiga.",
"Aprecio tu amistad. Pero no puedo mantener tu dinero y mi reputaciуn.",
"Mis disculpas.... por supuesto.... Deberнa haberlo hecho...",
"Marнa, por favor, no llores. Si te lo pidiera, Marнa... їpodrнas?.",
"Deberнa...?",
"їQuieres casarte conmigo?",
"ЎOh Horatio!",
"ЎHurra! ЎEstoy tan contenta de que estйs de vuelta y a salvo! Espero que te quedes mucho tiempo.",
"(Piensa: 'Hurra'? <estremecimiento>) Yo tambiйn me alegro de volver contigo, Marнa. Pero temo que mis obligaciones en el mar no permiten quedarme mucho tiempo.",

};