string DLG_TEXT[54] = {
"Anímate, Horatio. Pronto conseguirás otra nave.",
"Eso espero, María. Espero que sí.",
"Yo soy María. Mi madre se ha ido a dormir.",
"¡Ah! Soy Horatio, Horatio Hornblower, retirado de la Marina de Su Majestad.",
"No estás contento de que te hayan dado de baja, ¿verdad?",
"No sé que será de mí. Sólo conozco la vida en el mar.",
"No te preocupes, te haré compañía, y puedes usar la vieja tartana de mi padre, está amarrada en el puerto. Solía usarlo para pescar cuando estaba en casa. Pero no es bueno para el mar abierto.",
"Gracias. Podría hacer eso. Voy a tener mucho tiempo libre.",
"Un centavo por tu pensamiento, Horatio.",
"¡Oh! .... Hola María. Estaba deseando que la flota zarpara y pudiera conseguir de nuevo un puesto en un barco .",
"¡Horatio! ¿Quieres decir que ya estás cansado de mi compañía?",
"¡No! ¡No! María. Es sólo que llevo aquí tres meses y estoy muy atrasado con el alquiler. Necesito un puesto para ganar dinero.",
"Sólo estaba bromeando Horatio. Y no te preocupes, he pagado el alquiler de esta semana por ti. Mamá no te perseguirá por ahora. Por cierto, noté que empeñaste tu espada. No conseguirás un puesto sin una. Aquí tienes, toma esta.",
"María.... Eres una buena amiga.",
"Espero ser más que eso Horacio.",
"Maria... Er...",
"De todos modos, tengo algunas noticias que deberían animarte.",
"¿En serio? ¿Y qué podría ser eso?",
"Hay algunos soldados en la ciudad que dicen que sirvieron contigo. Creo que dijeron fusileros. Les dije que vendría a buscarte. Están en la Taberna.",
"¡Fusileros! María. Y gracias, me gustaría volver a verlos. Por favor, discúlpame, iré a la taberna ahora.",
"Er! Lo siento madre, lo olvidé. Mr. Hornblower me dio media corona esta mañana. Está en mi habitación.",
"No quiere ser tan dura contigo.",
"Creo que se acuesta con María, y por una razón. No es un buen inquilino, de ninguna manera.",
"Creo que eres un verdadero caballero, Horatio.",
"Debo ir a la ciudad ahora, María. Creo que tengo una manera de conseguir algo de dinero para el alquiler. Te veré más tarde.",
"Mr. Hornblower. No nos vas a dejar, ¿verdad? A veces mi madre se va de la lengua... ",
"Me han dado el mando de una nave. Zarpo mañana.",
"Entonces déjame hacerte el equipaje, señor.",
"Eres muy amable, pero ya lo he hecho.",
"Pero nunca te volveré a ver, señor.",
"Lo siento, pero es mi deber.",
"Mr. Hornblower, señor. Me avergüenza, señor, que nos vea así. Sucedió muy rápido. No sabía que estábamos atrasados, y los alguaciles no nos escucharon y ahora no podemos ganar nuestra libertad.",
"Fuiste mi amiga en un momento de necesidad, María, permíteme ser tuyo.",
"No, señor, no debe hacerlo.",
"Es demasiado tarde, María. Ya está hecho.",
"Gracias, señor. No sé qué decir.",
"No digas nada, María. Sólo ve y paga tus deudas. Debo volver al mar ahora, pero volveré de nuevo.",
"Mr. Hornblower, señor. Vi el Hotspur, en el puerto. Esperaba que fuera una señal de tu regreso.",
"Debe ser bueno para ti estar en casa de nuevo.",
"...",
"Lo es. Gracias, señor, y también me alegro de verte. Entra.",
"¿Tienes suficiente para el alquiler?",
"Espero conseguir un puesto de institutriz y no puedo ser una carga por caridad.",
"No eres una carga, te lo aseguro.",
"No Mr. Hornblower, no puedo. Hay una palabra para una mujer que acepta dinero de un hombre.",
"Sí, y esa palabra es amiga.",
"Aprecio tu amistad. Pero no puedo mantener tu dinero y mi reputación.",
"Mis disculpas.... por supuesto.... Debería haberlo hecho...",
"María, por favor, no llores. Si te lo pidiera, María... ¿podrías?.",
"Debería...?",
"¿Quieres casarte conmigo?",
"¡Oh Horatio!",
"¡Hurra! ¡Estoy tan contenta de que estés de vuelta y a salvo! Espero que te quedes mucho tiempo.",
"(Piensa: 'Hurra'? <estremecimiento>) Yo también me alegro de volver contigo, María. Pero temo que mis obligaciones en el mar no permiten quedarme mucho tiempo.",

};