string DLG_TEXT[69] = { 
"Parece que hay problemas.",
"Hum... Sí, Sr. Hunter.",
"¡Ah, teniente! Me alegro de verle en pie, señor. Soy el guardiamarina Hunter. He sido asignado a su brigada.",
"Así se me ha dado a entender. ¿Cómo están los heridos?",
"La mayoría están recuperados, señor, y disfrutando de un merecido permiso en tierra.",
"Tendrán que aprovecharlo al máximo. La 'Indy' volverá pronto y luego saldremos a la caza de barcos franceses y españoles.",
"¿No ha oído el cañón, señor? Los franceses ya están aquí.",
"¿QUÉ? ¿De qué está hablando, hombre?",
"Lleva dormido un par de días, señor. Tan pronto como la escuadra cruzó el horizonte, salieron de la nada. Tienen el puerto bloqueado. No tenemos barcos que puedan con ellos.", 
"Pero eso significa que cuando la 'Indy' doble el cabo a su regreso, se topará directamente con ellos. ¡Tenemos que advertirles!",
"¿Y cómo piensa ahcer eso, teniente? ¿Agitando una bandera desde lo alto de los acantilados?",
"No sea insolente, Hunter. Haremos que los barcos franceses cambien de posición.",
"¡Oh! ¿Y cómo vamos a hacer eso?",
"¿Qué es lo más importante a bordo de un barco en el mar, Hunter?",
"¿Comida y agua?",
"Correcto. Comida y agua. La comida la puedan llevar. Pero necesitan reponer su suministro de agua dulce siempre que puedan.",
"Tiene razón, señor. Una balandra se separa frecuentemente de su escuadra y desaparece por un tiempo. Luego, regresa.",
"Entonces es esa balandra la que hace la aguada, y solo hay un lugar cerca de aquí donde conseguir agua dulce.",
"¡Bahía Blanca!", 
"¡Exacto! Bahía Blanca. Hay un manantial en el valle, justo al lado de la playa.",
"¿Cuál es su plan, señor?", 
"Iremos allí, nos mantendremos al acecho y les cortaremos el suministro de agua. Tendrán que volver a la escuadra para pedir ayuda y la escuadra vendrá a la playa como apoyo.",
"No tenemos exactamente una tripulación completa. No seremos capaces de retenerlos por mucho tiempo, señor.",
"Nos preocuparemos de eso cuando lleguemos allí. Vamos, tenemos que darnos prisa. Es un largo camino a través de la selva. Nunca saldríamos del puerto en el bote.",
"Creo que puedo ayudar, teniente. Tengo un amigo, el Sr. Larr, al que llaman 'Smug'. Tiene un pequeño negocio de importación y exportación. Lo dirige desde una vieja casa junto al puente. Deberíamos ir allí. Conoce un atajo a la playa.",
"Espero que tenga razón, Sr. Hunter, necesitamos todo el tiempo posible. Vamos.",
"Los franceses ya están aquí, señor, y hay un bote llegando a tierra.",
"¡MALDICIÓN! No esperaba que llegaran tan pronto.",
"Hay algo peor, señor.",
"¿PEOR?",
"Nos están observando. A mi izquierda, señor.",
"?",
"Un maldito casaca roja. Dondequiera que estén, los problemas no están lejos.",
"Averigüemos qué está haciendo aquí. Sígame.",
"La tripulación está aquí, señor. Los tengo esperando en el túnel. ¿Qué hacemos ahora?",
"Es hora de vestirse. Sígame.",
"¡Teniente! Teniente, hay un barco acercándose a la bahía. Podría ser la 'Indy', pero está demasiado lejos para estar seguro; también podría ser un francés.", 
"Tenemos que darnos prisa, entonces. ¿Dónde está la tripulación?",
"¿Qué hacemos ahora, Sr. ",
"Comprobemos que el barco está en condiciones de navegar y que tenemos suficientes provisiones. Va a ser un largo viaje, Hunter.",
"¿No sería mejor esperar para unirnos a algunos barcos más grandes que vayan en la misma dirección? Por protección, quiero decir, señor.",
"No, Hunter. Mis órdenes son ir a toda velocidad, así que tenemos que ponernos en marcha.",
"¿Qué hacemos ahora, teniente?",
"Busque por aquí a ver qué podemos encontrar. Puede que haya algo útil para nuestra huida más tarde.",
"Déjelo, teniente. Se ha dado por vencido.",
"No, Hunter, cuando escapemos iremos todos juntos, y eso incluye al Sr. Kennedy.",
"Está perdiendo el tiempo, mírelo. Está sufriendo otro ataque.",
"Hunter, ¡cállese! Fue capturado en batalla. No sabe por lo que ha pasado.",
"Sr. ",
". Llevamos aquí una semana. Los hombres se están impacientando, creen que deberíamos intentar escapar ahora. Sólo hay cinco guardias aquí y podríamos vencerlos fácilmente.",
"¿Eso cree? ¿Y cuántos hay fuera? No lo ha pensado bien. De todos modos, ya se lo dije, Hunter, no nos iremos sin el Sr. Kennedy.",
"Entonces veamos cómo le va..., señor.",
"Sí, haremos eso.",
"A la orden, señor. Fijaré un rumbo siguiendo la costa cuando lleguemos a bordo.",
"No, Hunter. Deseo salir a mar abierto lo antes posible. No seguiremos el rumbo normal.",
"Mírelo. No mejora.",
"Sr. Hunter, tenemos que darle tiempo.",
"Nos retrasará cuando intentemos escapar. Tenemos que dejarlo.",
"No lo dejaremos, Hunter. Esta es mi última palabra al respecto.",
"¿Ha disfrutado del paseo..., señor?",
"Ha sido interminable, Hunter. Debo ir a ver cómo está el Sr. Kennedy.",
"Se lo sigo diciendo, señor. Él sólo nos retrasará.",
"Y yo se lo sigo diciendo, Sr. Hunter. No nos iremos sin él.",
"¿Ha tenido una buena cena, señor?",
"No fue todo placer, Hunter",
"¡Maldita sea! Eso es lo más cerca que han estado hasta ahora.",
"¿Qué quiere decir, Hunter?",
"Los franceses. No se acercan, así que disparan un tiro de vez en cuando, desde la boca de la bahía. Aún no han dado a nadie.",
"Entonces, vayamos a la playa y hagamos que muevan sus navíos.", 
};
