string DLG_TEXT[40] = {
"їTiene el dinero del alquiler, Mr. Hornblower?",
"Lo tendrй pronto, Sra. Mason.",
"їNecesitarб un lugar donde quedarse, seсor? ",
"Er,... Sн, parece que sн.",
"Cobro menos de lo que el Almirantazgo recomienda, desayuno y cena, y sбbanas limpias una vez a la semana.",
"ЎOh! ... Er... Sн, creo que eso se adaptarнa a mis necesidades.",
"No encontrarб otro lugar tan barato, y mi cocina no debe ser rechazada .",
"ЎOh! ... Er... Sн, gracias, gracias. їDonde estб?",
"Me llamo Mason. Sra. Mason, aunque el Sr. Mason falleciу hace algunos aсos..... Sнgame.",
"ЎOh! ... Er... Hornblower... Horatio Hornblower. Sн, sн, por supuesto. Er... Sra. Mason.",
"Esta es mi hija, Marнa. Tengo cosas que hacer, asн que dejarй que se presenten.",
"ЎOh! ... Er... Sн, gracias, Sra. Mason.",
"ЎOh! eres tъ.",
"El teniente Bush, la Sra. Mason, la dama de la Cбmara. El Sr. Bush serб mi invitado esta noche.",
"Usted es muy generoso con su hospitalidad, Sr. Hornblower, para alguien cuya renta estб muy atrasada.",
"Serб un chelнn para la cama. No puedo lavar las sбbanas por menos que eso, no con jabуn. Y eso le deja a Mr. Hornblower con 15 que nos debe.",
"Si pasaras menos tiempo soсando. Eres como tu padre, con la cabeza en las nubes, y mira adуnde lo llevу. Quiero el resto para el fin de semana. Por aquн.",
"Subirй enseguida.",
"Vaya, vaya, vaya. Pero si es el gran capitбn de navнo. Viene a burlarse de nuestra desgracia.",
"ЎMadam!",
"їEntonces no estб muerto, seсor?",
"Parece que no, madam.",
"Mi Marнa llorу cuando usted no estaba, seсor. Odio pensar lo mucho que llorarнa si no hubiera regresado.",
"їElla llorу?.",
"Llorу por usted, seсor. Aunque no sй la razуn.",
"Tendrй que hacer algunos preparativos para una boda, entonces. їA quiйn debo invitar como su padrino?",
"Si le parece bien, me gustarнa que el teniente William Bush hiciera los honores.",
"їEl oficial al que invitу a quedarse aquн? Parece bastante agradable. Y ahora es mejor que duermas un poco, Ўtienes un dнa ocupado por delante! Te veremos en la iglesia maсana.",
"Buenas noches, Sra. Mason.",
"Bueno, їno fue maravilloso? Y ahora, estoy agotada. їNos llevarнas a casa?",
"Por supuesto, Sra. Mason.",
"Ahora que somos familia, no necesitas ser tan formal. Puedes llamarme Ellen.",
"Muy bien, Ellen. Y yo soy Horatio.",
"ЎEh, tъ! Tъ no, Horatio, Ўtъ, 'curiosуn' que estбs delante del ordenador! Haz el favor de dar un poco de intimidad a una pareja de reciйn casados. Ya volverбs a verlos maсana.",
"...",
"",
"",
"",
"",
"...",
};