string DLG_TEXT[51] = { 
"Buenos días Teniente.",
"Buenos días, Harper.",
"Sólo hay uno, señor.",
"¿Uno? ¿Uno qué?",
"Cuerpo, señor. Sólo hay un cadáver. Este de aquí está inconsciente, así que él está.",
"¿Inconsciente?",
"Sí, señor. Después de nuestra charla, lo pinché con mi espada. Se apagó como una luz. Bastante sorprendente para un hombre tan grande.",
"¿Te dijo algo que nos ayudara? ¿Antes de que quedara inconsciente?",
"Eso es lo que hizo, señor. Lo hizo.", 
"¿Y?",
"Habrá otro pasadizo en el cuarto trasero. Lleva a la Academia y al campamento de piratas. Así es como han estado moviendo la mercancía.",
"?",
"¿Lo miraría ahora, teniente?.",
"¿Mirar qué? Todo lo que veo es mar.",
"¡Ah! ¡Su señoría! Pero es lo que navega en ese mar. Desde aquí tendría buena vista de todas las naves que entran y salen de la isla #sCharlestown#, para estar seguros.",
"Ya veo lo que quiere decir.",
"Bueno, este es el campamento de piratas para estar seguros, y si mis ojos no me engañan, dos oficiales franceses entraron en la casa de allá.",
"¿Oficiales franceses? ¿Aquí? Definitivamente algo está pasando. Pero, ¿qué? ",
"Quizás encontremos algo más cuando lleguemos a la Academia.", 
"Creo que es hora de salir de aquí. De vuelta por donde vinimos.",
"Querrá saber cómo llegar al pasadizo, teniente.", 
"Sí, Harper, eso ayudaría.",
"Dijo que siguiéramos el pasadizo, para la Academia. No se desvíe a otra parte.",
"¿Y el campamento Pirata?",
"Para el Campamento de los Piratas, dijo: siga recto hasta llegar a una antorcha encendida. Girar a la derecha. Luego continúa hasta llegar a otra antorcha encendida. Luego gire a la derecha nuevamente. Entonces sigue recto.",
"Espero poder recordarlo. ¿Y la entrada al pasadizo?",
"Eso está detrás de la tienda de la esquina, señor.",
"Muy bien. Vamos a seguir adelante.",
"Caballeros, hay un viejo minero por allí. Le pregunté qué vio u oyó. Dijo que le pareció oír disparos cuando bajó por el hueco y se acercó a mirar. Pero cuando subió no vio nada. No vio los cuerpos.",
"Gracias Harper.",
"Si le da igual..., Cooper y yo preferimos volver a la 95th. No parece correcto que estemos aquí, mientras el resto de los muchachos están bajo fuego.",
"Entiendo a Harper. Entonces vaya... y buena suerte.",
"Debo admitir que siento lo mismo. Volveré con usted.",
"No quiero apresurarlo, señor. Pero seríamos más útiles con nuestros hombres ahora mismo. Una compañía de tropas francesas acaba de salir por las puertas de la ciudad.",
"Por supuesto, Harper. Esperemos que no sea demasiado tarde. Sígame.",
"Me quedaré aquí fuera y vigilaré, señor. Ya sabe, por si acaso.",
"Buena idea, Harper. No tardaremos mucho.", 
"Mientras estaba aquí me di cuenta de que había muchos navíos grandes en el puerto, y las tropas que vimos también estaban acampadas ahí fuera.",
"¿Tropas en el campamento? Eso confirma la idea de la invasión. Me pregunto si deberíamos ir a ver",
"Está ocupado arreglando las cerraduras de las puertas de la ciudad. Eso debería detener cualquier refuerzo por un tiempo.",
"...",
"Hasta ahora, todo bien, señor.",
"Manténgase alerta. Aún no hemos llegado a casa.",
"Esperaba encontrarle. Tiene que venir a ver esto, señor. Cooper y yo tomamos el camino equivocado, pero no va a creer lo que nos encontramos.",
"Guíenos entonces, le seguiremos.",
"Deberíamos ir a ver cómo está el capitán Murray, señor.",
"Estoy de acuerdo. Tenemos que ver si se puede mover.",
"Mejor me adelanto y hago un poco de exploración, señores.",
"Buena idea, Harper. Esperaremos aquí.",
"De acuerdo, están allí. Pero hay todo un escuadrón  de ellos.",
"Más de lo que podemos soportar los tres. Deberíamos volver al claro. Con un poco de suerte, los otros fusileros estarán allí.",
};
