string DLG_TEXT[46] = { 
"їNecesita mi ayuda, seсor?",
"Hmm... tos.. Er... Sн.",
"Asн que usted es el valiente teniente del que el Sr. Hunter me ha estado hablando.",
"Teniente en funciones Horatio Hornblower. A su servicio, seсor.",
"Sн. Bien, Teniente en funciones, їquй puedo hacer por usted?",
"El Sr. Hunter me dijo que quizб conozca un atajo a la playa.",
"Asн es, teniente en funciones, pero tiene un precio.",
"Me lo esperaba. їCuбnto serнa la dolorosa?",
"100 monedas de oro.", 
"Por persona. Tengo que considerar el salario del Sr. Bryan.",
"De alguna manera, yo tambiйn esperaba eso. Aquн estб su dinero. їY ahora quй?",
"Atraviese la puerta a mi derecha. Encontrarб un tъnel. Lleva directamente a la playa. Bryan, muйvete.",
"Gracias.",
"",
"",
"",
"", 
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"", 
"",
"",
"",
"",
"",
"",
"",
"",
"", 
"",
};
