string DLG_TEXT[68] = { 
"Comandante Hornblower. Creo que es preciso actuar con cautela.",
"Sí, comandante. Coincido.",
"Por fin conozco al gran comandante Hornblower. He oído hablar mucho de usted, señor.",
"Comandante Moreno. Me honra demasiado.",
"Vamos, vamos, comandante. He oído hablar mucho de sus hazañas contra los franceses y los españoles.",
"Commandante, las historias tienden a embellecerse mucho con el paso del tiempo.",
"¡Modesto también! Un rasgo inusual entre los oficiales británicos. Muy bien, trabajaré con usted. ¿Qué es lo que quiere?",
"Comandante, necesito encontrar al mayor Hogan en #sisland_Guadeloupe#.",
"¿Y Richa... El teniente Sharpe y su tropa lo acompañarán en esta misión?", 
"Sí, comadante, lo harán.",
"Bien. Entonces podremos ayudarnos mutuamente, comandante. Necesito una reliquia de la iglesia de la ciudad. Podemos unir fuerzas para recuperarla.",
"Comandante, tengo órdenes estrictas de no provocar la guerra con Francia. Un acto así pondría eso en riesgo.",
"¡Bah! ¡Su estúpida tregua! ¿Cree que los franceses están sentados de brazos cruzados? Si va a la ciudad obtendrá información valiosa, de eso estoy segura.",
"Pero, comandante, no puedo iniciar hostilidades con los franceses... Mis órdenes...",
"No, como comandante británico no puede, pero si viaja conmigo como miembro de mi partida, se convierte en un guerrillero, y no estaría iniciando ninguna guerra.",
"Bueno, eso tiene sentido. ¿Cuál es su plan?",
"Navegamos hasta Anse Casse Bois en su barco y desembarcamos en la playa. Luego, vamos a encontrarnos con el mayor Hogan, y después a la iglesia a buscar la reliquia. Traeré ropa civil para usted y el teniente Sharpe. Mis hombres traerán mi propio barco rodeando la isla y estarán esperando en el puerto. Subiremos a bordo y nos iremos, sin ser detectados. Luego, volveremos a rodear la isla en sentido contrario, y usted embarcará en su barco y completará su misión.",
"Parece que podría funcionar. Muy bien. Estoy de acuerdo.",
"Entonces, ¿cuándo zarpamos?", 
"Tan pronto como hayamos descansado. Mi barco está listo. Nos veremos en el muelle por la mañana, Sr. Bush. Nos retiraremos a la taberna.",
"Estamos listos, comandante. Mis hombres están conduciendo mi barco al puerto de #sisland_Guadeloupe#, donde estarán listos para recogernos. También he mandado que dos se queden en Anse Casse Bois para que se adelaten y reconozcan el terreno.", 
"Veo que sabe organizarse, comandante. Hagámonos a la mar y recemos por una misión exitosa.",
"Mis hombres ya están aquí, así que podemos proceder. En el próximo valle, debemos girar a la izquierda hasta el siguiente valle.",
"En el próximo valle, giro a la izquierda. Lo tengo. Vámonos.",
"Esta parte es un poco complicada debido a la densidad de la vegetación, pero hay que continuar hasta la bifurcación del camino y desde allí tomar el camino de la izquierda.",
"Muy bien.",
"Bien, mis hombres están aquí. Todo recto hasta la plantación, comandante.",
"Por fin. Esto no es bueno para mis nervios.",
"Aquí hay muchas más tropas de las que necesita la guarnición, es más como un ejército en toda regla.",
"¡POR SUPUESTO! ¡Eso es! Es un ejercito. De hecho es un ejército de invasión. Debo llevar esta información al almirante Pellew de inmediato.",
"No olvide sus órdenes... y nuestro trato.",
"Lo sé, pero esto es muy importante.",
"Mire, Hogan está en esa casa grande en la parte de atrás de la plantación. Sería estúpido que volviera ahora sin obtener su información también. Nunca se sabe qué más puede haber averiguado.",
"Tiene razón, por supuesto. Sólo estoy furioso conmigo mismo por no haber visto la situación antes. Vamos, vayamos a ver a Hogan.",
"No del todo, comandante. Todavía tenemos el objeto que necesita recoger en la iglesia.",
"¡Ah, sí! La iglesia...",
"Richard y sus hombres se han ido. Espero que lo logren.", 
"Yo también. Vayamos a la iglesia y encontremos esa reliquia suya.",
"Yo sé dónde está. En un cuarto a la derecha del altar.",
"Entonces, vámonos. A la ciudad y a la iglesia.",
"¿Comandante?",
"¡Lo tengo! Está abierto.",
"Espere aquí, iré a buscarla.",
"Vaya lo más rápido que pueda.",
"¡La tengo! Tengo la reliquia. Démonos prisa en salir de aquí.",
"Estoy de acuerdo.",
"Ha sido más fácil de lo que pensaba. Todo lo que tenemos que hacer ahora es llegar a mi barco y zarpar.",
"...",
"Vamos, comandante. Debemos llegar al barco cuanto antes. Aún podremos aprovechar la marea.",
"Sí, tiene razón. A su barco, pues.",
"Lo entiendo, caballeros. La lealtad nos ata con poderosas ligaduras, y yo tengo lo que necesito por ahora.",
"Gracias, comandante. Le deseo suerte en sus aventura.",
"Gracias, comandante Hornblower. Me reuniré con el 'Hotspur' y les diré que les vayan a buscar a la playa.",
"Gracias de nuevo. Adiós.",
"Parece que hemos llegado antes que el 'Hotspur', pero me temo que no puedo quedarme, debo llevar la reliquia a su destino.",
"Entiendo, pero tengo una pregunta. Su barco..., lo conozco. Lo capturé a los franceses hace mucho tiempo. ¿Cómo lo consiguió?",
"¡Ja, ja, ja! Digamos que el mayor Hogan me hizo un gran favor al conseguir que las 'autoridades' me lo prestaran, para beneficiar a nuestra causa común.",
"¡Ah! El mayor Hogan. Estoy empezando a aprender mucho sobre él.",
"Bueno, debo irme, pero estaré ojo avizor por si me cruzo con el 'Hotspur'. Quédese aquí y hable con el teniente Sharpe y sus hombres, estoy segura de que le dirán más.",
"¿Sharpe y sus hombres? Tendré que encontrarlos primero.",
"Ellos están aquí. Nos han estado observando desde que desembarcamos... ¡Richard!... Ya puedes salir. Sabemos que estás ahí.",
"¿Están aquí?",
"¡Bienvenido, comandante! Doblemente bienvenido, ahora que Gran Bretaña ha recobrado el sentido común y ha reanudado la guerra contra Francia",
"Gracias, comandante. Me alegro de haberla encontrado aquí en Charlestown.",
"Todavía tengo mi barco; tal vez lo haya visto en el puerto. Cuando su flota asaltó Guadalupe, decidí dejar la zona por un tiempo. ¿En qué puedo ayudarle?",
"Uno de mis guardiamarinas, Thomas Wolfe, ha resultado ser en traidor. Escapó de una pelea en la playa y huyó hacia el interior. Esperaba que quizás tuviera alguna idea de adónde fue después",
"Puede que no fuera su hombre, pero cuando salíamos de la playa de Guadalupe hacia el norte, vimos un barco similar al mío, llamado 'Loup-Garou', que salía a toda prisa del puerto y se dirigía hacia el sur.",
"Y si ese era Wolfe dirigiéndose a un territorio francés más seguro, la única isla francesa en esa dirección es #sisland_Falaise de Fleur#. Gracias, comandante. Si ese era Wolfe, entonces lo encontraré.",
};
