string DLG_TEXT[50] = { 
"Se le nota muy fuerte, Sr. Haitch.",
"Hmm... tos.. ЎSu Seсorнa!",
"їEstarй a salvo con este Teniente, capitбn Pellew? ЎNo parece mбs que un niсo!",
"Er... Le aseguro que harй todo lo que estй en mi mano, su Excelencia.",
"Ahora estoy en sus manos, Sr. Haitch. Puedo llamarle Sr. Haitch, їno?",
"Er.. Sн, su Excelencia. Creo que deberнamos prepararnos para el mar. Buenos dнas, seсores.",
"їCуmo llegaremos a Inglaterra, teniente? їQuй rumbo tomaremos?",
"Navegaremos hacia el noreste a #sisland_Turks# y luego, norte, noreste a Inglaterra.",
"Hola de nuevo Teniente. Venga conmigo. Tengo a alguien que quiero que conozca.", 
"їSu Excelencia? їQuй estб haciendo aquн?",
"Sr. Haitch. Parece algo distraнdo. їPasa algo malo?",
"їCуmo llegу aquн, su Excelencia?",
"ЎJa! el capitбn espaсol vio un navнo con bandera britбnica y regresу aquн tan rбpido como pudo. Me tirу como a un barril de carne podrida.",
"їY los despachos, Su Excelencia?",
"ЎOh! Los di por una buena habitaciуn.",
"їQUЙ?",
"Cбlmese, Sr. Haitch, cбlmese. Sus despachos estбn a salvo. Los tengo conmigo. Ahora vamos, serб mejor que volvamos.", 
"Gracias, Su Excelencia.",
"Hola Teniente. Sуlo vine a ver cуmo estб hoy Mr. Kennedy .",
"Parece que se estб recuperando, Su Excelencia.",
"Me alegra oнrlo. Bueno, sуlo pasй por aquн. Nos vemos luego, Sr. Haitch.",
"Sн, su Excelencia.",
"Debo protestar, seсor. Esas no fueron mis palabras.",
"...",
"No lo recuerdo, seсor... їLe pareciу agradable Londres?",
"He oнdo que es una obra triste.",
"Usted lo sabrб mejor que yo. No estoy a menudo en Londres.",
"No me gustaba ese francesito. No, en absoluto.",
"їPor quй no? Parecнa gustarle. Pero tal vez sea porque estuvo en una obra que йl vio. Los Rivales, їno? O quizбs fue Macbeth... Srta. Cobham. їAcaso lo niega?",
"їPor quй deberнa hacerlo?",
"їPero por quй esta farsa? їTodo el asunto de la Duquesa?",
"Porque quiero volver a casa.",
"їDуnde estбn mis informes?",
"Escondidos.",
"Dйmelos a mн.",
"їPor quй? їSoy de repente poco fiable porque no soy duquesa?", 
"No. Porque ha mentido.",
"Confieso, seсor. Confieso mi estupidez al confiar en este chico. Si hubiera sabido que se meterнa en un nido de Dons, le aseguro que aъn estarнa descansando cуmodamente en #sredmond#.",
"Como estoy aquн prisionera en este aburrido puesto sin nadie que me acompaсe, salvo un viejo aristуcrata y un joven inexperto. Me hace sentir muy bien hablar, al fin, con un hombre.",
"Tal vez deberнamos retirarnos a mis aposentos, Coronel, donde podamos hablar mбs.",
"їQuй es lo que quiere?",
"Su falta de cortesнa no le honra, seсor.",
"їCуmo fue la velada con el coronel?",
"Hice lo necesario para proteger mi nombre, Y sus preciados despachos. Tuvo suerte de que anoche tuviera otra carta para jugar.",
"Su Excelencia... Srta. Cobham, lo siento. Hablй apresuradamente. Ahora que la conozco, le agradecerнa que me los guardara.", 
"їQuй? їPretende que vuelva a llevar las malditas cosas en mi ropa interior?",
"Si su Excelencia fuera tan amable.",
"Despuйs de una noche en el bote de remos del Seсor Hornblower, creo que podrнa dormir en la percha de la jaula de un loro",
"En ese caso, capitбn Pellew, deberнa llevar estos documentos. Mr. Hornblower me los dio para que los guardara cuando fuimos capturados por los espaсoles.",
"No sea tan duro con su teniente en funciones, capitбn. Si no fuera por su valentнa, no estarнamos hoy aquн.",

};
