string DLG_TEXT[46] = { 
"Seсor Wolfe. Thomas Wolfe.",
"Continъe.",
"...",
"Cinco aсos como timonel en los convoyes del norte.",
"Una joven en Leeds, seсor, con la barriga hinchada y un padre enfadado.",
"Me encantarнa, seсor.",
"Buen hombre.",
"?",
"Hornblower. Creo que es hora de rendirse.", 
"ЎWOLFE!",
"Espero que estйn todos cуmodos, caballeros. Me voy a capturar a sus marines, que creen que van a capturar la baterнa.",
"Usted es un traidor, Wolfe..",
"Debн haberle estirado el cuello cuando tuve la oportunidad.",
"Me rendirй, si garantiza que mis hombres no serбn maltratados.",
"Bueno, esto es un cambio inesperado. Que yo sea su prisionero.",
"En efecto. їCуmo consiguiу esa balandra?",
"Lleguй a #sPointe a Pitre#, que estaba en un caos total debido a su incursiуn.",
"їY luego?",
"La tripulaciуn de la balandra estaba en pбnico y desesperada por alguien que les diera уrdenes. Asн que lo hice. Les dije que нbamos a #sFalaise de Fleur# para informar de la incursiуn. Un capitбn britбnico hizo lo mismo cuando atacaron a #sOxbay# hace unos 50 aсos.", 
"Y ahora puede ser colgado.",
"Si hace eso, nunca conocerб a mi jefe.", 
"Ya lo hemos descubierto. El capitбn Hammond estб muerto.",
"їCharlie el Negro? Puede que haya sido importante en la marina, pero no era el jefe.",
"Entonces, їquiйn es el jefe?",
"Es mejor que te lo diga, ya que me lo sacarбs de un modo u otro. Vas tras Urнas Quelp. Pero no lo atraparбs si no me dejas salir de aquн.",
"їY por quй deberнamos hacer eso?",
"Se supone que debo encontrarme con йl en algъn lugar cerca de Santo Domingo. Y no me preguntes quй planea hacer despuйs porque nunca me lo dijo.",
"Tal vez no confнa en ti por alguna razуn.",
"Con el sarcasmo no conseguirбs a Quelp. Yo tampoco lo harй a menos que me saques de aquн.",
"De acuerdo, pero primero necesito ver al comandante de la prisiуn.",
"Vamos tierra adentro. Deberнa estar cerca de un molino.",
"De acuerdo, vamos.",
".",
".",
"",
".",
".", 
"",
"",
"",
"",
"",
"",
"",
"",
"", 
};
