string DLG_TEXT[17] = {
"Usted es Johan Elting, supongo",
"Correcto. Y supongo, que tú eres Baltasar Salgada.",
"Como dijiste: ¿Trajiste la cerveza como estaba previsto?",
"Sí, lo hice. Vamos a descargarla, no quiero quedarme aquí mucho tiempo, es muy arriesgado.",
"Bien, la cerveza está cargada en los vagones, podemos partir.",
"Ahora tenemos que hablar del dinero. Me debes 33.000 de oro por estos bienes.",
"Bueno... No puedo pagar ahora mismo. He tenido algunos problemas últimamente, así que te pagaré en unos meses.",
"¿Qué? ¡No eran los términos de este acuerdo! Tenías que pagarme cuando se entregara la cerveza.",
"Lo sé, pero no puedo hacerlo de otra manera.",
"Lo siento por ti, pero no puedo darte esto a crédito, perderé mi barco, voy a recargar la cerveza y la venderé en otro lugar.",
"¡NO! ¡Necesito la cerveza para pagar mis deudas! ¡No la toques!",
"¡Escúchame! Te lo he dicho, me pagas lo que me debes o me devuelves la cerveza. Si no, la recuperaré por la fuerza.",
"¡Vete al infierno, holandés, eres el hijo de un cerdo!",
"¿un cerdo eh?, ¡yo te meteré en una brasa para asarte al espeto, y conseguiré mi cerveza!",
"No, no tengo la cantidad adecuada. Pero, podemos hacer el trato, ¿no?",
"¡Claro que no! No cuentes conmigo para trabajar contigo nunca más. ¡Adiós!",
"¡Espera!", 
};
