string DLG_TEXT[53] = {
".....",
".....",
"¿Si?",
"¿Capitán Damski?",
"Correcto. ¿Qué es lo que quieres?",
"El Vicealmirante me envió. Me va a proporcionar una nueva clase de Jabeque.",
"¿¡La nave es para ti!?",
"En efecto. ¿Por qué lo preguntas?",
"Tenía entendido que sería entregada a un capitán español de alto rango. Usted no es español, ¿verdad? ¡Este es un barco especial!",
"Soy holandés, me llamo Johan Elting. Tu nombre tampoco es español, ¿verdad?",
"Cierto, no soy español. Yo era un capitán pirata hasta hace unos pocos años.",
"¿Qué está haciendo en #sHavana#?",
"Fui capturado y arrestado por los españoles.",
"Parece que compartimos el mismo destino.",
"El Vice-Almirante, de alguna manera sabía que yo era un buen armador antes de convertirme en un pirata, me presionó para que prestara servicio en lugar de la horca, no discutí.",
"Entiendo y comparto.",
"Pero no estoy aquí para contarte la historia de mi vida, vayamos al grano. Tengo que explicarte las características de mi último trabajo.",
"¡Debe ser una nave muy especial!",
"Sí, de hecho, supera el estándar en todos los aspectos. La bodega de carga es el doble de la norma, más cañones de un calibre mayor.",
"Debe ser más pesada y lenta.",
"No, porque el casco se ha hecho con una madera recién descubierta que sólo se encuentra aquí en el Caribe. Esta madera es más fuerte y ligera que cualquier otra usada en Europa.",
"Estoy impresionado.",
"Deberías estarlo... y además, es rápida y ágil. En las manos correctas llevará sorpresa y muerte a muchos enemigos desprevenidos y traerá a su capitán y tripulación gloria y fama.",
"No puedo esperar a verla. Tu fe en ella es contagiosa.",
"Está en el puerto esperándole, Capitán. Trátela bien.",
"Mi oficial asignado también estará allí, sin duda. Gracias por la nave. ¡Adiós Capitán Damski!",
"Buenas tardes, padre. Creo que se equivocó, no le pedí que viniera.",
"No soy un sacerdote, Capitán Damski. ¿No reconoce mi voz?",
"Sí, ya la he oído, pero no recuerdo dónde.",
"Hablé contigo en el astillero cuando me diste 'El Diablo'.",
"¡¿Capitán Elting?!",
"Él mismo y la persona que está conmigo es el Capitán Bartolomeu.",
"Pensé que las autoridades te habían matado después de tu deserción.",
"Lo intentaron muchas veces pero fracasaron, como puedes ver.",
"¿Qué estáis haciendo aquí?",
"Necesito tu ayuda.",
"¿Qué es lo que quieres exactamente?",
"¿Sabes algo sobre un tesoro azteca que la Flota de Plata ha transportado?",
"¿Un tesoro? No, nada. ¿Cómo lo sabes?",
"Una historia demasiado larga, te la explicaré otro día. ¿Nada sobre lo que pudo haber sido descargado de los navíos?",
"Si en el puerto se hubiera descargado un tesoro, seguro que la gente hablaría de ello.",
"¡Espera! Podría ayudarte.",
"¿Cómo?",
"Sé que el capitán de la flota, el capitán Villalobos, debe ver al gobernador mañana por la mañana. Yo también estaré en el ayuntamiento. Algunos de los navíos necesitan repararse antes de salir de La Habana. Parece que han encontrado una tempestad durante el viaje.",
"Podríamos confirmarlo. Incluso hemos tenido que hacer una visita a #sisland_Khael Roa#.",
"Todavía necesito una confirmación de los daños pero apuesto dos semanas por su estancia.",
"Humm... La mejor solución sería secuestrarlo después de la reunión y antes de que se reúna con su tripulación en el puerto. Sin olvidar que tenemos que ser discretos si no queremos que todos los guardias de esta ciudad nos ataquen.",
"Dejaré el ayuntamiento antes de que él vea que tendrá otros temas que hablar con el Gobernador. Podría estar contigo para avisarte de su llegada.",
"Muy bien, creo que tenemos un plan. ¿Podemos quedarnos en tu casa hasta mañana por la mañana?",
"Por supuesto.",
"¡Gracias!",
"¡Capitán! Ya viene, pero hay dos guardias con él.",
"No te preocupes. Yo y Bartolomeu nos encargaremos de ellos. Ahora, vuelve a tu trabajo antes de que te vea con nosotros.",
};
