string DLG_TEXT[23] = {
"......",
"......",
"Reconozco a Chico Cois pero, їquiйn eres tъ?",
"Su nuevo capitбn. Creo que sabe por quй estamos aquн.",
"Sн. Sнgame, tengo algo para usted.",
"Aquн estб el informe. Estaba escondido en mi casa.",
"Gracias. Se lo darй al Vicealmirante. ЎAdiуs!",
"ЎEspera! Tengo un problema. No estoy seguro de poder continuar con mi trabajo en #sisland_Cayman#.",
"їPor quй?",
"Creo que mi capitбn sospecha que soy un espнa, pero aъn no sabe para quiйn.",
"їCуmo lo sabes? їYa te ha interrogado?",
"No, pero ъltimamente me ha estado vigilando de cerca y me ha seguido, aunque sin demasiado йxito.",
"Eso es un problema sin duda...",
"Pensй que debнa matarlo, pero serнa demasiado peligroso para mн.",
"Bueno, podrнa matarlo yo pero necesito encontrarme solo con este tipo, y no entre sus soldados en el fuerte.",
"La situaciуn no es perfecta pero podrнas matarlo en la ciudad. En este momento, estб en el puerto comprobando la descarga de municiones y despuйs tiene que hablar con el gobernador.",
"Podrнa... pero discretamente.",
"їLo conociste?",
"Asн es. No te molestarб mбs. Yo lo matй.",
"ЎGracias! Me acabas de salvar.",
"*tono irуnico* Sн, tengo el mismo efecto que un sacerdote, pero uso diferentes medios.",
"ЎHA-HA! En efecto.",
"En el futuro, ten mбs cuidado cuando espнes. Tengo que irme ahora Dominico, Ўhasta pronto!",

};
