string DLG_TEXT[98] = {
"No creo haberte visto aquн antes, mi buen hombre.",
"Sн, es mi primera vez aquн. Mi nombre es ",
".",
"їY quй? їRecuerdas el nombre y la cara de todos?",
"Yo soy ",
", el dueсo de esta taberna.",
"Encantado de conocerte, ",
". їQuй tienes para ofrecer aquн, ademбs de una jarra de cerveza y una oreja dispuesta?",
"Relбjate, no busco darte ningъn problema. Mi nombre es ",
", y estoy aquн para hablar de negocios con usted, y luego ocuparme del mнo propio.",
"Bien, bien. Estoy escuchando.",
"Estoy buscando una tripulaciуn. Tal vez pueda decirme quiйn estб buscando un barco.",
"Mi ъltimo viaje me dejу corto de tripulantes. Seсбlame la carne de caсуn adecuada en tu taberna, y me pondrй en camino.",
"Sуlo necesito algo de informaciуn, si tienes un minuto.",
"їTienes un catre que no tenga que compartir con mil insectos?",
"Necesito un cuarto limpio con una cama. Me interesa la limpieza.",
"Lo siento, no tengo tiempo para charlar. Hasta luego.",
"Eso realmente depende de lo que quieras decir, ",
".",
"Me he enterado de que ",
"Raoul Rheims",
" llegу a esta ciudad recientemente.",
"Busco a un hombre llamado ",
"Raoul Rheims",
"Raoul Rheims",
". їSabe si ha estado en esta isla?",
"Estoy buscando a  ",
"Ferro Cerezo",
"Ferro Cerezo",
". Tal vez sepas dуnde puedo encontrarlo.",
"Estoy buscando a cierto hombre que vino a la isla no hace mucho tiempo. Es italiano, un hombre mayor. їLe suena de algo?",
"Estoy interesado en alguien llamado Artois Voysey. Es un joven alto con pelo oscuro. їHa aparecido por aquн?",
"Necesito un poco de trabajo. їNo conoces a ningъn niсo rico en esta isla que tenga miedo de viajar solo?",
"Cambiemos de rumbo, y hablemos de otra cosa.",
"Sн, lo he visto, pero dudo que te alegres.\nVerбs, este muchacho entrу aquн con un sinvergьenza, y cinco minutos despuйs la puerta se abre, y dos villanos con mбscaras negras entraron.\nSe llevaron a tu Artois con ellos, e hirieron gravemente a su amigo. Estб en una de las habitaciones de arriba ahora mismo.",
"ЎMil maldiciones! ЎNecesito verlo! Tal vez sepa quiйnes son estos alborotadores enmascarados.",
"Ahora, dйjame pensar... ЎOh, sн, por supuesto! Seсor ",
"Vito Leone",
" coincide con su descripciуn. Vino hace una semana y me alquilу una habitaciуn. Dijo que alguien vendrнa a buscarlo, y me pidiу que le dijera que lo estб esperando en la iglesia.",
"ЎGracias!",
"El hombre de la mesa cerca de la ventana se llama asн, si no me equivoco.",
"Gracias. Lo comprobarй.",
"ЎBaja la voz! Las paredes tienen oнdos, amigo mнo.",
"їY quй? No tengo secretos.",
"ЎTen cuidado! Dicen que el hombre trabaja para ",
"Desmond Ray Beltrop",
"Desmond Ray Beltrop",
" йl es el mismнsimo jefe de los contrabandistas de por aquн. Preferirнa no tener problemas con йl. Malo para el negocio.",
"Sн, ",
"Raoul Rheims",
" estб en la isla. Lo encontrarбs con ",
"Desmond Ray Beltrop",
"ї Cуmo puedo encontrarlo?",
"Es la primera vez que oigo eso. Tal vez se equivoque.",
"Sй con certeza que llegу aquн hace varios dнas. Iba a reunirse con ",
"Desmond Ray Beltrop",
"Desmond Ray Beltrop",
".",
"Silencio! Si valoras tu vida, no volverбs a decir ese nombre en voz alta. ЎMira! їViste a ese hombre que acaba de salir de la taberna? ЎAlйjate! ЎVete ahora, o harбs que el cielo caiga sobre mi cabeza!",
"ЎContrуlate, hombre! Estбs temblando en tus botas... y no sabes nada ъtil, їverdad? Bah. ЎAdiуs!",
"ЎRelбjate! Veo que no me sirves para nada. ЎAdiуs!",
"Lo siento, pero es muy tarde. Todo el mundo ya ha encontrado un lugar para pasar la noche. Vuelve por la maсana si quieres. O puedes pasar una noche aquн en la taberna.",
"Tal vez lo haga. їTienes una habitaciуn?",
"Puede que lo haga. Pero por ahora, tengo algunas preguntas mбs.",
"Resulta que tengo una vacante. їCuбnto tiempo planeabas quedarte?",
"Hasta maсana.",
"Sуlo hasta que caiga la noche.",
"Te costarб 5 de oro.",
"Bien. Aquн estб tu dinero.",
"Desgraciadamente, parece que una cama estб fuera de mi alcance en este momento. Dormirй en el salуn de la taberna.",
"ЎїQuieres cuбnto?! їMe dan una cesta de frutas con eso? Gracias, pero dormirй en la taberna.",
"Lo considerarй. Mientras tanto, necesito mбs informaciуn.",
"Te costarб 5 de oro.",
"Aquн estб su dinero.",
"Lamentablemente, es mбs de lo que me gustarнa gastar. Dormirй en el salуn de la taberna.",
"їPara quй es eso, una habitaciуn grande? No, gracias, dormirй en el salуn de la taberna.",
"Lo pensarй.",
"ЎEste es un establecimiento respetable! ЎDetйngase de inmediato, o llamarй a los guardias!",
"Estб bien, estб bien. Me voy",
"Si existe tal persona, puede que prefiera evitar llamar la atenciуn con tantos consortes - como espero que sepas.",
"Sн, lo olvidй. De acuerdo, volverй mбs tarde, cuando tenga menos naves, ja, ja.",
"No quiero ayudarte, por todo el daсo que le has hecho a mi paнs.",
"Estб bien. Adiуs.",
"Tus manos estбn cubiertas de sangre. їEn serio crees que alguien viajarб en tu compaснa?",
"ЎTienes razуn, todo el mundo me teme! ЎJa, ja!",
"Llegaste justo a tiempo. Un mercader de aquн buscaba navegar en compaснa de los compaсeros adecuados. Serб mejor que hables con йl. Aquн estб, entrando en la taberna.",
"Lo harй.",
"No, no hay nadie por el momento, tal vez la prуxima vez.",
"Hmm. Entonces esperarй.",
"їSabe si Bartolomeu o Portugues estuvo aquн recientemente?",
"їRecientemente? їNo sabes que estб aquн?",
"їQuй? No, no lo sabнa. їCuбndo llegу?",
"Hoy, con el enviado de nuestro gobernador. Iban al ayuntamiento cuando los vi fuera de la taberna.",
"їSabes por quй Bartolomeu vino a #sConceicao#?",
"No tengo ni idea, amigo mнo. Sуlo soy el tabernero.",
"Estб bien... Pero, їpuede decirme quй navнo amarrado en el puerto es el suyo?",
"Tiene una Caravela Latina llamada 'Santiago'.",
"Gracias. No tengo mбs preguntas.",
};
