string DLG_TEXT[16] = {
"......",
"......",
"Soy Hans Delorme, el mejor contrabandista de #sisland_Curacao#. Puedo encontrar cualquier cosa para ti.",
"No estoy buscando bienes en este momento, pero lo tendré en cuenta. Estoy buscando a alguien.",
"¿Quién, tal vez pueda ayudar?",
"Roche Brasiliano.",
"No trabajo para él, pero sé que no está en el pueblo en este momento.",
"¿Qué quieres decir? Alguien en #sWillemstad# dijo que vive aquí.",
"Sí, pero se fue a #sisland_Curacao# hace unos días por un tiempo.",
"¿Por qué?",
"Ni idea. Tal vez, quería atacar algunas naves... De todos modos, no quiero saberlo. Desde su llegada, casi se ha apoderado de la aldea. Incluso las autoridades nos evitan ahora.",
"Su casa es la que está custodiada por dos hombres, ¿no es así?",
"Sí, custodiada por sus hombres día y noche.",
"¿Sólo puede tener dos hombres en el pueblo?",
"No, hay más. Tal vez una docena o algo así. Por supuesto, cuando está en el pueblo su tripulación está con él, alrededor de 350 hombres.",
"Muchos hombres... Gracias Hans, tengo cosas que hacer ahora.",
};
