string DLG_TEXT[22] = {
"......",
"......",
"Hola Capitбn. He oнdo que has hundido el 'Belleville'. ЎFelicidades!",
"Gracias, seсor. їEntonces, tenemos que ir a #sisland_Khael Roa#?",
"Sн. Tenemos que explorar la isla y encontrar un buen lugar para un futuro asentamiento.",
"їCuбndo nos iremos a #sisland_Antigua#?",
"Tan pronto como la carga estй almacenada, puedes echar el ancla, estarй siguiйndote con mi navнo.",
"Estб bien. Voy a prepararme para la salida.",
"Esta bahнa es un puerto natural perfecto. Se podrнa construir un fuerte allн para protegerlos.",
"Sн, pero los acantilados no permiten que se construya un pueblo en este lugar y se necesita agua.",
"Muy cierto. Para eso, necesitamos explorar el interior.",
"ЎNo puedo creerlo! Ya hay un campamento en la isla.",
"Sн, y por lo que veo, pertenece a los franceses. ЎMira la bandera de esta cabaсa!",
"Tienes razуn, pero no los veo. El campamento estб desierto.",
"Tal vez, estйn explorando este monumento. Nunca he visto nada como esto antes, algo aterrador.",
"Creo que es un templo. He oнdo que los Mayas solнan construir asн en el continente, los usaban para sacrificios y para enterrar a sus reyes - con todo su oro.",
"Tal vez tambiйn construyeron este, parece que se fueron hace mucho tiempo, їme pregunto por quй?",
"Podrнamos echar un vistazo dentro, nunca sabemos lo que podrнamos encontrar, podrнa haber demonios o fantasmas para atraparnos.",
"De acuerdo, pero estemos en guardia.",
"Afortunadamente, los vi venir pero debemos dejar la isla. Podrнan llegar mбs soldados. Este lugar estб casi desierto.",
"Primero pensй que eran fantasmas, pero eran sуlo soldados franceses, seсor. No sabemos cuбntos franceses hay mбs en #sisland_Khael Roa#.",
"Volvamos a las naves. Tenemos que informar al Almirante de Puerto Lord Barham que los franceses ya estбn aquн.",
};
