string DLG_TEXT[77] = {
"......",
"......",
"Hola Capitán. Escuché que estás buscando a Roche Brasiliano.",
"Así es. El Vicealmirante dijo que usted podría ayudarme en esta tarea.",
"Haré lo que pueda. Es muy difícil encontrarlo. Sin embargo, recientemente, escuché que un ex oficial de Roche lo dejó después de un desacuerdo. Compró una plantación cerca de #sPointe a Pitre# gracias al oro ganado durante su vida de pirata.",
"Por fin algo de buena información. Ese hombre debería saber dónde tiene Roche su base.",
"Tal vez... De todos modos, es la única pista que tengo sobre Roche.",
"Bueno, siempre es mejor que nada.",
"De hecho, vamos a #sCharlestown#.",
"¿Qué te parece?",
"Ella miente tanto como respira.",
"Tal vez, ella sigue viéndole.",
"Creo que sí. Debe tener una casa en algún lugar de esta ciudad. Necesitaremos obtener información de ella de la manera difícil, podrías encontrar e irrumpir en su casa, dentro puede tener cartas o una pista sobre su relación con Roche.",
"Encontré su casa pero la puerta está cerrada. ¿Qué vamos a hacer?",
"Ella debe tener una llave, por supuesto. Necesitamos robarla pero en el burdel, sería peligroso. Harán sonar la alarma si nos descubren.",
"¿Y qué?",
"Ella vendría en pocos segundos.",
"Espérame frente a su casa mientras robo la llave.",
"¿Qué has encontrado?",
"Su próximo destino, Capitán Butcher. Esta es una carta de Roche explicando que se quedará en #sisland_Curacao# por un tiempo.",
"¿Hay una fecha en esta carta?",
"Sí, lo he comprobado. La carta fue escrita hace tres semanas.",
"No podrías encontrar mejor información que esta. Apuesto a que el enviado también debe estar allí.",
"Es una posibilidad. Vayamos a #sisland_Curacao# inmediatamente.",
"Mira a tu derecha.",
"¿Te fijaste en los guardias?",
"Parece ser la única casa vigilada en el pueblo.",
"Tal vez es la casa de Roche Brasiliano...",
"Deberíamos confirmar esto hablando con la gente de la taberna.",
"¿Qué opina, Capitán?",
"Roche no está aquí y dos hombres están vigilando su casa día y noche. En mi opinión, hay algo valioso dentro.",
"O alguien diría yo...",
"Sí, como un enviado español, por ejemplo. Esta noche, prepararemos una operación.",
"Los dos gilipollas no se alejaron de la puerta.",
"No es necesario esperar más, la calle está desierta. Tenemos que eliminar a estos hombres y revisar rápidamente la casa.",
"¡Más hombres de Roche vienen de la taberna! ¿Qué vamos a hacer?",
"Abandona el pueblo ahora con el enviado y regresa a #sHavana#. Mientras tanto, lucharé contra ellos.",
"¡Estás loco, Capitán!",
"No hay tiempo para discutir. Haga lo que le digo e informe al Vice-Almirante que buscaré a Roche.",
"¡Capitán Elting! Me alegro de verte.",
"Gracias, Capitán Butcher. Vine aquí porque el Vicealmirante Benavides me dijo que buscabas información sobre Bartolomeu o Portugués. ¿Es cierto?",
"Sí. Y, recientemente encontré algo.",
"¿Qué es exactamente?",
"Me enteré de que Bartolomeu capturó a Charles Baxter, un pirata inglés, el año pasado.",
"¿Cómo puede ayudarnos esta información a encontrar a Bartolomeu?",
"La última estancia conocida de Charles Baxter fue en #sisland_Quebradas Costillas#. Hay un asentamiento pirata en esa isla y apuesto a que podríamos conocer a algunos de sus amigos allí.",
"Interesante. Podríamos saber por qué Bartolomeu arrestó a Charles Baxter y a dónde lo llevó. Creo que tenemos una buena pista. ¡Vamos a #sisland_Quebradas Costillas#!",
"Creo que encontraremos en #sConceicao# otra pista sobre Bartolomeu.",
"Cierto. Vayamos a #sisland_Conceicao#.",
"Vi este barco en el puerto cuando desembarcamos.",
"Yo también. Sígueme, tengo un plan.",
"¿Cuál es tu plan, Capitán?",
"Sería demasiado peligroso capturar a Bartolomeu durante el día en #sConceicao#. Esperaremos a la noche para aprovechar la oscuridad y abordar su navío por sorpresa.",
"¿Qué haré yo?",
"Quedaos cerca del fuerte y apunten sus cañones a los del fuerte. Si mi abordaje es detectado por los soldados, quiero algo de protección para escapar.",
"¿Después?",
"Bueno, tan pronto como capture a Bartolomeu, dejaremos esta isla y nos iremos a La Habana, por supuesto.",
"Esperemos que todo vaya bien.",
"Eso espero. No quiero que me hundan en el puerto.",
"¿Quieres que lo lleve a la cárcel?",
"Sí, Capitán Butcher. Haga eso mientras veo al Vicealmirante Benavides.",
"¡Hecho! Está en la cárcel, Capitán.",
"Gracias. Sígueme, Capitán Butcher. Debemos ir a Eleuthera a arrestar a una amiga de Bartolomeu llamada Roxanne Lalliere.",
"¿Lalliere? La conozco, pero no es amiga de Bartolomeu.",
"Información dada por el propio Vice-Almirante. Vayamos primero a Puerto la Cruz para pedirle ayuda al Gobernador.", 
"¿Podemos ir a Alice?",
"Sí, ya hemos esperado bastante. El oficial inglés debe ser informado ahora por el mensajero.",
"La ciudad está 'limpia'. El oficial llevó a los guardias afuera.",
"Bien. Ella debe salir de la taberna en cualquier momento.",
"¡Es ella!",
"¡Venga, vamos!",
"Una pelea intensa.",
"Sí. Está muy nerviosa, sacó su cuchillo antes de que yo dijera que era mi prisionera. Llevémosla a Puerto la Cruz antes de que los soldados regresen.",
"¿Regresamos a Puerto la Cruz?",
"Sí, pero irás directamente a La Habana.",
"¿Por qué?",
"El Vicealmirante Benavides dijo que enviará al Capitán Padilla a Eleuthera cuando llegue de Santo Domingo. Sin embargo, el Capitán Padilla puede retrasarse en su misión. Prefiero que vayas allí e informes al Vicealmirante de que tenemos a Roxanne Lalliere y que necesitamos un galeón ya, aunque tenga que enviar el galeón del gobernador de La Habana.", 
};