string DLG_TEXT[20] = {
"......",
"......",
"¿Qué?",
"¡Hola, muñeca!",
"Eres un mercenario, ¿no? Hablas español con acento extranjero.",
"Soy holandés, Capitana Lalliere.",
"Debo confesar que pareces haber preparado un plan detallado para capturarme.",
"Por fin, conozco a una adversaria que admite mis habilidades.",
"No creí que fuera una amenaza importante para los españoles.",
"Por supuesto, tu expedición en Santiago no fue apreciada por las autoridades españolas. Aunque, esta no es la razón principal de tu arresto.",
"¿Qué quieres decir?",
"Lo sabrás mejor en La Habana cuando veas a Emilio Soares.",
"¿Emilio? ¿El oficial de Bartolomeu?",
"Exacto. Bueno, tengo más que hacer, así que disfruta de tu estancia en la cárcel.",
"Te tomaste tu valioso tiempo. Me estaba preocupando.",
"Lo hemos hecho lo más rápido posible. Ahora, tenemos que dejar Cuba. La Habana debe ser asediada por soldados después de lo que hicimos allí.",
"¿Qué hiciste, asesino? Mataste a mi mejor amigo.",
"Hice lo que tenía que hacer. La vida de pirata no es una solución para mí... y para ti, porque tu fin llegará pronto.",
"¡Maldito sea el día en que tu madre te dio a luz!",
"(Se oye abrir la puerta de la prisión) ¡Cállate! Alguien viene. Espero que no sea otro amigo tuyo.",
};
