string DLG_TEXT[15] = {
"......",
"......",
"Amigo, їno ves que quiero beber solo este excelente ron?",
"No te preocupes, sуlo estoy buscando a Vassal Bethune.",
"No lo busques porque estб delante de ti. їQuй es lo que quieres?",
"He oнdo que reclutas piratas, y la paga es muy buena.",
"Sн, pero no a cualquiera. Sуlo los buenos luchadores.",
"Tienes suerte porque soy de los buenos. Estuve en el ejйrcito holandйs durante muchos aсos.",
"їEn serio? Si eres tan bueno como dices, mi jefe estarб encantado de conocerte. Pero, tengo que advertirte, a йl no le gusta que lo decepcionen.",
"No lo harй. Por cierto, їquiйn es tu jefe?",
"No puedo decнrtelo todavнa. Lo sabrбs cuando lo conozcas. їTienes una nave?",
"Sн. Estб amarrada en el puerto.",
"En ese caso, llйvame a #sRedmond# si quieres conocerle.",
"De acuerdo, a #sRedmond# pues.",
"Estamos cerca de su casa. Sнgueme.",
};
