string DLG_TEXT[18] = {
"......",
"......",
"¿Qué?",
"¿William Cotter?",
"Sí, ¿qué quieres?",
"El gobernador de Puerto la Cruz dijo que te viera.",
"Sabía que vendrías. ¿Quién es la persona que quieres secuestrar?",
"Una corsaria francesa llamada Roxanne Lalliere. ¿La has visto?",
"Humm... La única mujer capitán que vi venir estos últimos días es una comerciante holandesa.",
"Debe ser ella. Al ver las relaciones entre Inglaterra y Francia, usa la bandera holandesa como tapadera. ¿Dónde está ella?",
"Ella está en la taberna con su oficial.",
"¿De noche, ella duerme en la taberna?",
"No, ella usualmente regresa a su nave.",
"Bien, tendremos la oportunidad de sorprenderla cuando regrese a la nave. El único problema son los guardias que patrullan la ciudad...",
"No te preocupes, puedo atraerlos temporalmente fuera de la ciudad durante tu operación.",
"¿Cómo?",
"Les diré que vi una patrulla española en la jungla cerca de las puertas y los llevaré allí.",
"Bien. Sólo tengo que esperar a que salga de la taberna esta noche.", 
};
