string DLG_TEXT[55] = {
"Hello, my #schild#. What brings you to the bosom of the Church? Did you come for confession, or perhaps to make a donation?",
"I have to speak with you, Padre.",
"I'd like to make a donation, Padre.",
"Just having a look around. I have to go.", //3
"I'm listening, my #schild#.",
"I don't have any business with you right now.",
"Of course, my #schild#. How much do you want to give?",
"I am sorry, Padre, but I can't make a donation just now.",
"I'm afraid 100 gold is all I can afford just now.",
"I should think the Lord would look kindly on 1000 gold.",
"I'm doing well these days, so I'll give 5000 gold piasters.",
"It's your decision, my #schild#. It's never too late to change - and keep in mind that all will be taken into account at the time of your death.",
"My death is still a long way off, God willing! Let's talk about something else.",
"Sorry, Padre. I've got to go.",
"I thank you for your gift in the name of the Holy Church, my #schild#.",
"I need to talk to you, Padre.",
"I'm sorry, Padre, but I've got to go.",
"I thank you for your gift in the name of the Holy Church, my #schild#.",
"I need to talk to you, Padre.",
"I'm sorry, Padre, but I've got to go.",
"I thank you for your gift in the name of the Holy Church, my #schild#.",
"I need to talk to you, Padre.",
"I'm sorry, Padre, but I've got to go.", //22
"I'm afraid ",
" gold is all I can afford just now.",
"I should think the Lord would look kindly on ",
" gold pieces.",
"I'm doing well these days, so I'll give ",
"On this joyous day, we celebrate the joining of these two people in holy matrimony. ",
", have you come here freely and without reservation to give yourselves to each other in marriage?",
"Yes.",
"Ahem. <Looks sharply at you.> Will you honour each other as man and wife for the rest of your lives?",
"I will.",
"Will you accept children lovingly from God, and bring them up according to the law of Christ and his Church?",
"Er... yes, I will.",
"May the Lord bless these rings which this man and this woman are about to give to each other.",
"#sgroom#, do you take #sbride# to be your wife? Do you promise to be true to her in good times and in bad, in sickness and in health, to love her and honour her all the days of your life?",
"I do.",
"#sbride#, do you take #sgroom# to be your husband? Do you promise to be true to him in good times and in bad, in sickness and in health, to love him and honour him all the days of your life?",
"...",
"You have each declared your consent to give yourself to the other, and to receive that gift with the love in which it is given. May the Lord bless and watch over this couple who have joined here today in His sight. What God has joined, men must not divide.",
"Arrr!",
"Who are you, and why do you interrupt these proceedings?",
"Ah, #svillain#. Yes, I remember reading about you. You were indeed married to #sromance#, but the marriage was without ",
"his",
"her",
" consent. The Holy Father in Rome has decreed that the marriage has been annulled and #sromance# is again free to marry.",
"No! There must be no bloodshed in this church!",
"Then forgive me, father, because I am about to sin.",
"What have you done? Blood has been spilled. This holy place is desecrated!",
"I wanted the fight to be outside, but #svillain# left me no choice.",
"I am loyal to Spain, but I am loyal to the Church first. And my first concern is to the Church, Excellency. No further ceremonies can be performed here until this building has been reconsecrated.",
"You are... most persuasive, Excellency. Very well, then. We shall continue. Er... where were we?",
"We were part way through exchanging promises, Father.",
"Ah, yes. Ahem. ",
};
