void CreateConceicaoCharacters(ref n)
{
	object chobj;
	ref ch;

	makeref(ch, chobj);

			// Jacinto Arcibaldo Barreto (townhall)
	ch.old.name = "Jacinto";
	ch.old.middlename = "Arcibaldo";
	ch.old.lastname = "Barreto";
	ch.name = TranslateString("","Jacinto");
	ch.middlename = TranslateString("","Arcibaldo");
	ch.lastname = TranslateString("","Barreto");
	ch.id		= "Jacinto Arcibaldo Barreto";
	ch.model = "huber_por";
	ch.sex = "man";
	ch.location	= "Conceicao_townhall";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.Dialog.Filename = "Jacinto Arcibaldo Barreto_dialog.c";
	ch.Dialog.Filename.GroupDialog = "governor.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "60";
	ch.experience = "0";
	ch.skill.Leadership = "6";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "5";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetHuberType(ch);
	LAi_RemoveLoginTime(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	ch.greeting = "Gr_Jacinto Arcibaldo Barreto";
	AddGameCharacter(n, ch);

// Conceicao soldiers' IDs  are "Con_soldier_1", etc

//Location: Conceicao Pier (an entrance to the town from the pier)

	//Soldier на входе в город
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "Con_soldier_1";
	ch.model = 2; // PB
	ch.sound_type = "soldier";
	ch.sex = "man";
	ch.equip.blade = "blade4";
	ch.location	= "Conceicao_port";
	ch.location.group = "goto";
	ch.location.locator = "goto12";
	ch.Dialog.Filename = "Conceicao Soldier_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	GiveItem2Character(ch, "blade4");
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	LAi_CharacterReincarnation(ch, true, false);
	ch.greeting = "Gr_Conceicao Soldier";
	AddGameCharacter(n, ch);

	//Soldier на входе в город -- one more
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "Con_soldier_2";
	ch.model = 1; // PB
	LAi_CharacterReincarnation(ch, true, false);
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Conceicao_port";
	ch.location.group = "goto";
	ch.location.locator = "goto13";
	ch.Dialog.Filename = "Conceicao Soldier_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Conceicao Soldier";
	AddGameCharacter(n, ch);

			//Patrol
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "Con_patrol_1";
	ch.model = 3; // PB
	LAi_CharacterReincarnation(ch, true, false);
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Conceicao_port";
	ch.location.group = "goto";
	ch.location.locator = "goto11";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Conceicao Soldier"; // was "Gr_Patrol"
	AddGameCharacter(n, ch);

			//Patrol
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "Con_patrol_2";
	ch.model = 4; // PB
	LAi_CharacterReincarnation(ch, true, false);
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Conceicao_port";
	ch.location.group = "goto";
	ch.location.locator = "goto5";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Conceicao Soldier"; // was "Gr_Patrol"
	AddGameCharacter(n, ch);

		//Maria Rivaldo -- towngirl3
	ch.old.name = "Maria";
	ch.old.lastname = "Rivaldo";
	ch.name = TranslateString("","Maria");
	ch.lastname = TranslateString("","Rivaldo");
	ch.id		= "Maria Rivaldo";
	ch.model	= "towngirl3";
	ch.sex = "woman";
	ch.fanatic = "1";
	ch.church = "Conceicao_church";
	ch.church.loc = "goto3";
	ch.back.location = "Conceicao_port";
	ch.back.locator = "goto11";
	ch.sound_type = "female_citizen";
	ch.location	= "Conceicao_port";
	ch.location.group = "goto";
	ch.location.locator = "goto11";
	ch.Dialog.Filename = "Conceicao Citizen_dialog.c";
	ch.greeting = "Gr_Woman_English Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	AddGameCharacter(n, ch);

		//Rodrigo Caldeira -- fisherman
	ch.old.name = "Rodrigo";
	ch.old.lastname = "Caldeira";
	ch.name = TranslateString("","Rodrigo");
	ch.lastname = TranslateString("","Caldeira");
	ch.id		= "Rodrigo Caldeira";
	ch.model	= "fisherman";
	ch.sex = "man";
	ch.sound_type = "seaman";
	ch.location	= "Conceicao_port";
	ch.location.group = "goto";
	ch.location.locator = "goto5";
	ch.Dialog.Filename = "Conceicao Citizen_dialog.c";
	ch.greeting = "Gr_Conceicao Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	AddGameCharacter(n, ch);

  //Aleixo Simos -- chelovek
	ch.old.name = "Aleixo";
	ch.old.lastname = "Simos";
	ch.name = TranslateString("","Aleixo");
	ch.lastname = TranslateString("","Simos");
	ch.id		= "Aleixo Simos";
	ch.model	= "chelovek";
	ch.sex = "man";
	ch.fanatic = "1";
	ch.church = "Conceicao_church";
	ch.church.loc = "goto4";
	ch.back.location = "Conceicao_port";
	ch.back.locator = "goto9";
	ch.sound_type = "male_citizen";
	ch.location	= "Conceicao_port";
	ch.location.group = "goto";
	ch.location.locator = "goto9";
	ch.Dialog.Filename = "Conceicao Citizen_dialog.c";
	ch.greeting = "Gr_Conceicao Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	AddGameCharacter(n, ch);

		//Miguel Filho -- chameleon
	ch.old.name = "Miguel";
	ch.old.lastname = "Filho";
	ch.name = TranslateString("","Miguel");
	ch.lastname = TranslateString("","Filho");
	ch.id		= "Miguel Filho";
	ch.model	= "chameleon";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Conceicao_port";
	ch.location.group = "goto";
	ch.location.locator = "goto4";
	ch.Dialog.Filename = "Conceicao Citizen_dialog.c";
	ch.greeting = "Gr_Conceicao Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	AddGameCharacter(n, ch);

// Conceicao town:

	//Victor Barros -- old_man1
	ch.old.name = "Victor";
	ch.old.lastname = "Barros";
	ch.name = TranslateString("","Victor");
	ch.lastname = TranslateString("","Barros");
	ch.id		= "Victor Barros";
	ch.model	= "old_man2";
	ch.sex = "man";
	ch.fanatic = "1";
	ch.church = "Conceicao_church";
	ch.church.loc = "goto5";
	ch.back.location = "Conceicao_town";
	ch.back.locator = "goto1";
	ch.sound_type = "male_citizen";
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto1";
	ch.Dialog.Filename = "Conceicao Citizen_dialog.c";
	ch.greeting = "Gr_Conceicao Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "10";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	AddGameCharacter(n, ch);

	//Paolo Milazar -- man5
	ch.old.name = "Paolo";
	ch.old.lastname = "Milazar";
	ch.name = TranslateString("","Paolo");
	ch.lastname = TranslateString("","Milazar");
	ch.id		= "Paolo Milazar";
	ch.model	= "man5";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto12";
	ch.Dialog.Filename = "Conceicao Citizen_dialog.c";
	ch.greeting = "Gr_Conceicao Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	AddGameCharacter(n, ch);

			//Soldier near the entrance from port
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "Con_soldier_3";
	ch.model = 5; // PB
	LAi_CharacterReincarnation(ch, true, false);
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto28";
	ch.Dialog.Filename = "Conceicao Soldier_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Conceicao Soldier";
	AddGameCharacter(n, ch);

			//Soldier near the entrance from port
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "Con_soldier_4";
	ch.model = 6; // PB
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto29";
	ch.Dialog.Filename = "Conceicao Soldier_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Conceicao Soldier";
	AddGameCharacter(n, ch);

			//Soldier near the residence
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "Con_soldier_5";
	ch.model = 2; // PB
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto21";
	ch.Dialog.Filename = "Conceicao Soldier_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Conceicao Soldier";
	AddGameCharacter(n, ch);

			//Soldier near the residence
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "Con_soldier_6";
	ch.model = 2; // PB
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto22";
	ch.Dialog.Filename = "Conceicao Soldier_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Conceicao Soldier";
	AddGameCharacter(n, ch);

			//Soldier near the entrance from jungle
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "Con_soldier_7";
	ch.model = 6; // PB
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto19";
	ch.Dialog.Filename = "Conceicao Soldier_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Conceicao Soldier";
	AddGameCharacter(n, ch);

			//Soldier near the entrance from jungle
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "Con_soldier_8";
	ch.model = 3; // PB
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto20";
	ch.Dialog.Filename = "Conceicao Soldier_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Conceicao Soldier";
	AddGameCharacter(n, ch);

			//Patrol
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "Con_patrol_3";
	ch.model = 2; // PB
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto13";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Conceicao Soldier"; // was "Gr_Patrol"
	AddGameCharacter(n, ch);

			//Patrol
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "Con_patrol_4";
	ch.model = 6; // PB
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Conceicao_port";
	ch.location.group = "goto";
	ch.location.locator = "goto18";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Conceicao Soldier"; // was "Gr_Patrol"
	AddGameCharacter(n, ch);

			//Patrol
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "Con_patrol_5";
	ch.model = 5; // PB
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Conceicao_port";
	ch.location.group = "goto";
	ch.location.locator = "goto9";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Conceicao Soldier"; // was "Gr_Patrol"
	AddGameCharacter(n, ch);

	//Irene Torres -- towngirl2
	ch.old.name = "Irene";
	ch.old.lastname = "Torres";
	ch.name = TranslateString("","Irene");
	ch.lastname = TranslateString("","Torres");
	ch.id		= "Irene Torres";
	ch.model	= "towngirl7";
	ch.sex = "woman";
	ch.fanatic = "1";
	ch.church = "Conceicao_church";
	ch.church.loc = "goto6";
	ch.back.location = "Conceicao_town";
	ch.back.locator = "goto13";
	ch.sound_type = "female_citizen";
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto13";
	ch.Dialog.Filename = "Conceicao Citizen_dialog.c";
	ch.greeting = "Gr_Woman_English Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	AddGameCharacter(n, ch);

	//Mateus Branco -- korsar
	ch.old.name = "Mateus";
	ch.old.lastname = "Branco";
	ch.name = TranslateString("","Mateus");
	ch.lastname = TranslateString("","Branco");
	ch.id		= "Mateus Branco";
	ch.model	= "korsar";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto18";
	ch.Dialog.Filename = "Conceicao Citizen_dialog.c";
	ch.greeting = "Gr_Conceicao Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	AddGameCharacter(n, ch);

		//Beatriz Medeiros -- towngirl1 or towngirl1_2 depending on period
	ch.old.name = "Beatriz";
	ch.old.lastname = "Medeiros";
	ch.name = TranslateString("","Beatriz");
	ch.lastname = TranslateString("","Medeiros");
	ch.id		= "Beatriz Medeiros";
	if (GetCurrentPeriod() < PERIOD_REVOLUTIONS) ch.model = "towngirl1_2";	// GR Use new southern model for Portuguese in most periods
	else ch.model = "towngirl1";						// and original northern model for British in later periods
	ch.sex = "woman";
	ch.fanatic = "1";
	ch.church = "Conceicao_church";
	ch.church.loc = "goto7";
	ch.back.location = "Conceicao_town";
	ch.back.locator = "goto9";
	ch.sound_type = "female_citizen";
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto9";
	ch.Dialog.Filename = "Conceicao Citizen_dialog.c";
	ch.greeting = "Gr_Woman_English Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	AddGameCharacter(n, ch);

		//Henrique d'Allmeida -- man6
	ch.old.name = "Henrique";
	ch.old.lastname = "d'Allmeida";
	ch.name = TranslateString("","Henrique");
	ch.lastname = TranslateString("","d'Allmeida");
	ch.id		= "Henrique d'Allmeida";
	ch.model	= "sailor2";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto11";
	ch.Dialog.Filename = "Conceicao Citizen_dialog.c";
	ch.greeting = "Gr_Conceicao Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	AddGameCharacter(n, ch);

	// Rodrigo Neves -- capitan
	ch.old.name = "Rodrigo";
	ch.old.lastname = "Neves";
	ch.name = TranslateString("","Rodrigo");
	ch.lastname = TranslateString("","Neves");
	ch.id		= "Rodrigo Neves";
	ch.model	= "chelovek1";
	ch.sex = "man";
	ch.fanatic = "1";
	ch.church = "Conceicao_church";
	ch.church.loc = "goto8";
	ch.back.location = "Conceicao_town";
	ch.back.locator = "goto17";
	ch.sound_type = "seaman";
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto17";
	ch.Dialog.Filename = "Conceicao Citizen_dialog.c";
	ch.greeting = "Gr_Conceicao Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	AddGameCharacter(n, ch);

		//  Padre Valentim -- Monk
	ch.old.name = "Padre";
	ch.old.lastname = "Valentim";
	ch.name = TranslateString("","Padre");
	ch.lastname = TranslateString("","Valentim");
	ch.id		= "Padre Valentim";
	ch.model	= "Monk";
	ch.sex = "man";
	ch.sound_type = "priest";
	ch.location	= "Conceicao_church";
	ch.location.group = "goto";
	ch.location.locator = "goto11";
	ch.Dialog.Filename = "Padre Valentim_dialog.c";
	ch.Dialog.Filename.group = "church.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetPriestType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	ch.greeting = "Gr_Padre Valentim";
	AddGameCharacter(n, ch);

	// Conceicao Tailor
	ch.old.name = "Abenito";
	ch.old.lastname = "de Soto";
	ch.name	= TranslateString("", "Abenito");
	ch.lastname	= TranslateString("", "de Soto");
	ch.id = "Abenito de Soto";
	ch.model = "man6";
	ch.sex = "man";
	ch.location	= "Conceicao_TailorsShop";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.IsTailor = true;
	ch.Dialog.Filename = "tailor_dialog.c";
 	ch.Dialog.Filename.Groupdialog = "tailor.c";
	ch.rank 	= 1;
	ch.nation = PORTUGAL;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "0";
	ch.skill.Fencing = "0";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "6";
	ch.skill.Sneak = "0";
	ch.money = "10";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	AddGameCharacter(n, ch);

// Smugglers_Lair:

		//  Tomaz Cid -- Black_Corsair
	ch.old.name = "Tomaz";
	ch.old.lastname = "Cid";
	ch.name = TranslateString("","Tomaz");
	ch.lastname = TranslateString("","Cid");
	ch.id		= "Tomaz Cid";
	ch.model	= "man1_2";
	ch.sex = "man";
	ch.sound_type = "soldier";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "character12";
	ch.Dialog.Filename = "smugglers citizen_dialog.c";
	ch.greeting = "Gr_QC Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCivilianGuardianType(ch); // KK
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	AddGameCharacter(n, ch);

		//  Aristides Chiamulera -- man5
	ch.old.name = "Aristides";
	ch.old.lastname = "Chiamulera";
	ch.name = TranslateString("","Aristides");
	ch.lastname = TranslateString("","Chiamulera");
	ch.id		= "Aristides Chiamuler";
	ch.model	= "korsar";
	ch.sex = "man";
	ch.sound_type = "soldier";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "character2";
	ch.Dialog.Filename = "smugglers citizen_dialog.c";
	ch.greeting = "Gr_QC Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCivilianGuardianType(ch); // KK
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	AddGameCharacter(n, ch);

		//  Francisco Baia -- chameleon
	ch.old.name = "Francisco";
	ch.old.lastname = "Baia";
	ch.name = TranslateString("","Francisco");
	ch.lastname = TranslateString("","Baia");
	ch.id		= "Francisco Baia";
	ch.model	= "chameleon";
	ch.sex = "man";
	ch.act.sound_type = "pirate";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "goto20";
	ch.Dialog.Filename = "smugglers citizen_dialog.c";
	ch.greeting = "Gr_QC Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetWarriorType(ch);
	LAi_warrior_DialogEnable(ch, true);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	AddGameCharacter(n, ch);

		//  Eloi Labat -- mongol
	ch.old.name = "Eloi";
	ch.old.lastname = "Labat";
	ch.name = TranslateString("","Eloi");
	ch.lastname = TranslateString("","Labat");
	ch.id		= "Eloi Labat";
	ch.model	= "mongol";
	ch.sex = "man";
	ch.act.sound_type = "pirate";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "goto25";
	ch.Dialog.Filename = "smugglers citizen_dialog.c";
	ch.greeting = "Gr_QC Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetWarriorType(ch);
	LAi_warrior_DialogEnable(ch, true);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	AddGameCharacter(n, ch);

		//  Paolo Jardim -- fatman
	ch.old.name = "Paolo";
	ch.old.lastname = "Jardim";
	ch.name = TranslateString("","Paolo");
	ch.lastname = TranslateString("","Jardim");
	ch.id		= "Paolo Jardim";
	ch.model	= "fatman";
	ch.sex = "man";
	ch.act.sound_type = "pirate";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "goto15";
	ch.Dialog.Filename = "smugglers citizen_dialog.c";
	ch.greeting = "Gr_QC Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetWarriorType(ch);
	LAi_warrior_DialogEnable(ch, true);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	AddGameCharacter(n, ch);

		//  Valentim Ribeiro -- bocman
	ch.old.name = "Valentim";
	ch.old.lastname = "Ribeiro";
	ch.name = TranslateString("","Valentim");
	ch.lastname = TranslateString("","Ribeiro");
	ch.id		= "Valentim Ribeiro";
	ch.model	= "bocman";
	ch.sex = "man";
	ch.act.sound_type = "pirate";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "goto23";
	ch.Dialog.Filename = "smugglers citizen_dialog.c";
	ch.greeting = "Gr_QC Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetWarriorType(ch);
	LAi_warrior_DialogEnable(ch, true);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	AddGameCharacter(n, ch);

		//  Nuno Abrao -- corsair2
	ch.old.name = "Nuno";
	ch.old.lastname = "Abrao";
	ch.name = TranslateString("","Nuno");
	ch.lastname = TranslateString("","Abrao");
	ch.id		= "Nuno Abrao";
	ch.model	= "corsair2";
	ch.sex = "man";
	ch.act.sound_type = "pirate";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "goto9";
	ch.Dialog.Filename = "smugglers citizen_dialog.c";
	ch.greeting = "Gr_QC Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetWarriorType(ch);
	LAi_warrior_DialogEnable(ch, true);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	AddGameCharacter(n, ch);

		//  Emilio Guerra -- capitan
	ch.old.name = "Emilio";
	ch.old.lastname = "Guerra";
	ch.name = TranslateString("","Emilio");
	ch.lastname = TranslateString("","Guerra");
	ch.id		= "Emilio Guerra";
	ch.model	= "capitan";
	ch.sex = "man";
	ch.act.sound_type = "pirate";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "goto6";
	ch.Dialog.Filename = "smugglers citizen_dialog.c";
	ch.greeting = "Gr_QC Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetWarriorType(ch);
	LAi_warrior_DialogEnable(ch, true);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	AddGameCharacter(n, ch);

		//  Pascoal Labat -- man2
	ch.old.name = "Pascoal";
	ch.old.lastname = "Labat";
	ch.name = TranslateString("","Pascoal");
	ch.lastname = TranslateString("","Labat");
	ch.id		= "Pascoal Labat";
	ch.model	= "man2";
	ch.sex = "man";
	ch.act.type = "soldier";
	ch.act.soundtype = "pirate";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "goto6";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetWarriorType(ch);
	LAi_warrior_DialogEnable(ch, true);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	ch.greeting = "Gr_QC Citizen"; // was "Gr_Patrol";
	AddGameCharacter(n, ch);

		//  Luis Chagas -- man2
	ch.old.name = "Luis";
	ch.old.lastname = "Chagas";
	ch.name = TranslateString("","Luis");
	ch.lastname = TranslateString("","Chagas");
	ch.id		= "Luis Chagas";
	ch.model	= "man2";
	ch.sex = "man";
	ch.act.type = "pirate";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "goto23";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetWarriorType(ch);
	LAi_warrior_DialogEnable(ch, true);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	ch.greeting = "Gr_QC Citizen"; // was "Gr_Patrol";
	AddGameCharacter(n, ch);

		//  Camilo Machado -- korsar 4/8/06 SCM Desmond Ray Beltrop
	ch.old.name = "Desmond Ray";
	ch.old.lastname = "Beltrop";
	ch.name 	= TranslateString("","Desmond Ray");
	ch.lastname = TranslateString("","Beltrop");
	ch.id		= "Desmond Ray Beltrop";
	ch.model	= "Beltrop1";
	ch.sex = "man";
	GiveItem2Character(ch, "pistol5");
	ch.equip.gun = "pistol5";
     //JRH ammo mod -->
	if (ENABLE_AMMOMOD) {	// LDH change
		TakenItems(ch, "gunpowder", 1 + rand(2));
		TakenItems(ch, "pistolbullets", 1 + rand(2));
	}
     //JRH ammo mod <--
	GiveItem2Character(ch, "blade27");
	ch.equip.blade = "blade27";
	ch.location	= "Smugglers_Residence";
	ch.location.group = "goto";
	ch.location.locator = "goto1";
	ch.Dialog.Filename = "Desmond Ray Beltrop_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "0";
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 120.0, 120.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_CITIZENS");
	ch.greeting = "Gr_camilo machado";
	AddGameCharacter(n, ch);

		//  Evaristo Filho -- korsar
	ch.old.name = "Evaristo";
	ch.old.lastname = "Filho";
	ch.name = TranslateString("","Evaristo");
	ch.lastname = TranslateString("","Filho");
	ch.id		= "Evaristo Filho";
	ch.model	= "man1";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.sound_type = "soldier";
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "goto28";
	ch.Dialog.Filename = "Evaristo Filho_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "0";
	LAi_SetCivilianGuardianType(ch); // KK
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	ch.greeting = "Gr_Evaristo Filho";
	AddGameCharacter(n, ch);

		//  Macario Regalo -- korsar
	ch.old.name = "Macario";
	ch.old.lastname = "Regalo";
	ch.name = TranslateString("","Macario");
	ch.lastname = TranslateString("","Regalo");
	ch.id		= "Macario Regalo";
	ch.model	= "man2";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.sound_type = "soldier";
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "goto29";
	ch.Dialog.Filename = "Evaristo Filho_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "0";
	LAi_SetCivilianGuardianType(ch); // KK
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	ch.greeting = "Gr_Evaristo Filho";
	AddGameCharacter(n, ch);

// --> RobC/Alan_Smithee Blacksmith mod
if (ENABLE_WEAPONSMOD)
{
		//Conceicao Blacksmith
	ch.old.name = "Diego";
	ch.old.lastname = "Uargo";
	ch.name = TranslateString("","Diego");
	ch.lastname = TranslateString("","Uargo");
	ch.id		= "Con_blacksmith";
	ch.model	= "blacksmith1"; // Estharos Change from blacksmith2 to this model
	ch.sound_type = "worker";
	ch.sex = "man";
	ch.location	= "Con_blacksmith";
	ch.location.group = "goto";
	ch.location.locator = "goto1";
	ch.Dialog.Filename = "Blacksmith3_dialog.c";
	ch.Dialog.Filename.Groupdialog = "Gunsmith_fetch.c";
	ch.nation = PORTUGAL;
	ch.greeting = "Gr_Redmond Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetStayType(ch); // LDH: Keep him from walking around all the time
	LAi_group_MoveCharacter(ch, "SMUGGLERS_CITIZENS");
	AddGameCharacter(n, ch);
}
// <-- RobC/Alan_Smithee Blacksmith mod
}
