void CreateHispaniolaCharacters(ref n)
{
	object chobj;
	ref ch;

	makeref(ch, chobj);

// Santo Domingo Port :

			// Soldier.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname 	= "";
	ch.id		= "SD_soldier_01";
	ch.model = 1; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Santo_Domingo_Port";
	ch.location.group = "goto";
	ch.location.locator = "goto23";
	ch.Dialog.Filename = "Isla Muelle soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = SPAIN;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier";
	AddGameCharacter(n, ch);

			// Soldier.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname 	= "";
	ch.id		= "SD_soldier_02";
	ch.model = 2; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Santo_Domingo_Port";
	ch.location.group = "goto";
	ch.location.locator = "goto24";
	ch.Dialog.Filename = "Isla Muelle soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = SPAIN;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier";
	AddGameCharacter(n, ch);

			// Patrol.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname 	= "";
	ch.id		= "SD_patrol_01";
	ch.model = 4; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Santo_Domingo_Port";
	ch.location.group = "goto";
	ch.location.locator = "goto22";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.nation = SPAIN;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	AddGameCharacter(n, ch);

			// Patrol.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname 	= "";
	ch.id		= "SD_patrol_02";
	ch.model = 5; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Santo_Domingo_Port";
	ch.location.group = "goto";
	ch.location.locator = "goto16";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.nation = SPAIN;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	AddGameCharacter(n, ch);

    ch.old.name = "Jehan";
    ch.old.lastname = "Labbe";
    ch.name    = TranslateString("","Jehan");
    ch.lastname    = TranslateString("","Labbe");
    ch.id        = "Jehan Labbe";
    ch.model    = "storeman1";
    ch.sex = "man";
    ch.sound_type = "seaman";
    ch.location    = "Santo_Domingo_Port";
    ch.location.group = "goto";
    ch.location.locator = "goto22";
    ch.Dialog.Filename = "SantoDomingo citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
    ch.nation = SPAIN;
    ch.rank    = 1;
    ch.reputation = "None";
    ch.experience = "0";
    ch.skill.Leadership = "1";
    ch.skill.Fencing = "1";
    ch.skill.Sailing = "1";
    ch.skill.Accuracy = "1";
    ch.skill.Cannons = "1";
    ch.skill.Grappling = "1";
    ch.skill.Repair = "1";
    ch.skill.Defence = "1";
    ch.skill.Commerce = "1";
    ch.skill.Sneak = "1";
    ch.money = "10";
    LAi_SetCitizenType(ch);
    LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

    ch.old.name = "Jose";
    ch.old.lastname = "Puebla";
    ch.name    = TranslateString("","Jose");
    ch.lastname    = TranslateString("","Puebla");
    ch.id        = "Jose Puebla";
    ch.model    = "old_man1";
    ch.sex = "man";
    ch.sound_type = "seaman";
    ch.location    = "Santo_Domingo_Port";
    ch.location.group = "goto";
    ch.location.locator = "goto8";
    ch.Dialog.Filename = "SantoDomingo citizen_dialog.c";
 	ch.greeting = "Gr_isla muelle citizen";
    ch.nation = SPAIN;
    ch.rank    = 1;
    ch.reputation = "None";
    ch.experience = "0";
    ch.skill.Leadership = "1";
    ch.skill.Fencing = "1";
    ch.skill.Sailing = "1";
    ch.skill.Accuracy = "1";
    ch.skill.Cannons = "1";
    ch.skill.Grappling = "1";
    ch.skill.Repair = "1";
    ch.skill.Defence = "1";
    ch.skill.Commerce = "1";
    ch.skill.Sneak = "1";
    ch.money = "10";
    LAi_SetCitizenType(ch);
    LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

    ch.old.name = "Esmeralda";
    ch.old.lastname = "Cruezo";
    ch.name    = TranslateString("","Esmeralda");
    ch.lastname    = TranslateString("","Cruezo");
    ch.id        = "Esmeralda Cruezo";
    ch.model    = "Daniell2";
    ch.sex = "woman";
	ch.sound_type = "female_citizen";
    ch.location    = "Santo_Domingo_Port";
    ch.location.group = "goto";
    ch.location.locator = "goto3";
    ch.Dialog.Filename = "SantoDomingo citizen_dialog.c";
	ch.greeting = "Gr_Sylvie Bondies";
    ch.nation = SPAIN;
    ch.rank    = 1;
    ch.reputation = "None";
    ch.experience = "0";
    ch.skill.Leadership = "1";
    ch.skill.Fencing = "1";
    ch.skill.Sailing = "1";
    ch.skill.Accuracy = "1";
    ch.skill.Cannons = "1";
    ch.skill.Grappling = "1";
    ch.skill.Repair = "1";
    ch.skill.Defence = "1";
    ch.skill.Commerce = "1";
    ch.skill.Sneak = "1";
    ch.money = "10";
    LAi_SetCitizenType(ch);
    LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

// Location: Santo_Domingo_town

			//Soldier near prison
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname 	= "";
	ch.id		= "SD_soldier_40";
	ch.model = 1; // PB
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Santo_Domingo_town";
	ch.location.group = "goto";
	ch.location.locator = "goto20";
	ch.Dialog.Filename = "Isla Muelle soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = SPAIN;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "5";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier";
	AddGameCharacter(n, ch);

			//Soldier near prison
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname 	= "";
	ch.id		= "SD_soldier_41";
	ch.model = 2; // PB
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Santo_Domingo_town";
	ch.location.group = "goto";
	ch.location.locator = "goto41";
	ch.Dialog.Filename = "Isla Muelle soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = SPAIN;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier";
	AddGameCharacter(n, ch);

			// Soldier near the entrance to the town from port
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname = "";
	ch.id		= "SD_soldier_03";
	ch.model = 3; // PB
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Santo_Domingo_town";
	ch.location.group = "goto";
	ch.location.locator = "goto8";
	ch.Dialog.Filename = "Isla Muelle soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = SPAIN;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier";
	AddGameCharacter(n, ch);

			// Soldier near the entrance to the town from port -- another one
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname = "";
	ch.id		= "SD_soldier_04";
	ch.model = 4; // PB
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Santo_Domingo_town";
	ch.location.group = "goto";
	ch.location.locator = "goto40";
	ch.Dialog.Filename = "Isla Muelle soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = SPAIN;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier";
	AddGameCharacter(n, ch);

			// Patrol
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname = "";
	ch.id		= "SD_patrol_03";
	ch.model = 5; // PB
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Santo_Domingo_town";
	ch.location.group = "goto";
	ch.location.locator = "goto4";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.nation = SPAIN;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	AddGameCharacter(n, ch);

			// Patrol
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname = "";
	ch.id		= "SD_patrol_04";
	ch.model = 6; // PB
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Santo_Domingo_town";
	ch.location.group = "goto";
	ch.location.locator = "goto27";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.nation = SPAIN;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	AddGameCharacter(n, ch);

			// Patrol
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname = "";
	ch.id		= "SD_patrol_41";
	ch.model = 1; // PB
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Santo_Domingo_town";
	ch.location.group = "goto";
	ch.location.locator = "goto17";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.nation = SPAIN;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	AddGameCharacter(n, ch);

    ch.old.name = "Basilio";
    ch.old.lastname = "Domingo";
    ch.name    = TranslateString("","Basilio");
    ch.lastname    = TranslateString("","Domingo");
    ch.id        = "Basilio Domingo";
    ch.model    = "bocman3";
    ch.sex = "man";
    ch.sound_type = "seaman";
    ch.location    = "Santo_Domingo_town";
    ch.location.group = "goto";
    ch.location.locator = "goto1";
    ch.Dialog.Filename = "SantoDomingo citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
    ch.nation = SPAIN;
    ch.rank    = 1;
    ch.reputation = "None";
    ch.experience = "0";
    ch.skill.Leadership = "1";
    ch.skill.Fencing = "1";
    ch.skill.Sailing = "1";
    ch.skill.Accuracy = "1";
    ch.skill.Cannons = "1";
    ch.skill.Grappling = "1";
    ch.skill.Repair = "1";
    ch.skill.Defence = "1";
    ch.skill.Commerce = "1";
    ch.skill.Sneak = "1";
    ch.money = "10";
    LAi_SetCitizenType(ch);
    LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

    ch.old.name = "Diego";
    ch.old.lastname = "Larga";
    ch.name    = TranslateString("","Diego");
    ch.lastname    = TranslateString("","Larga");
    ch.id        = "Diego Larga";
    ch.model    = "fatman2";
    ch.sex = "man";
    ch.sound_type = "seaman";
    ch.location    = "Santo_Domingo_Port";
    ch.location.group = "goto";
    ch.location.locator = "goto22";
    ch.Dialog.Filename = "SantoDomingo citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
    ch.nation = SPAIN;
    ch.rank    = 1;
    ch.reputation = "None";
    ch.experience = "0";
    ch.skill.Leadership = "1";
    ch.skill.Fencing = "1";
    ch.skill.Sailing = "1";
    ch.skill.Accuracy = "1";
    ch.skill.Cannons = "1";
    ch.skill.Grappling = "1";
    ch.skill.Repair = "1";
    ch.skill.Defence = "1";
    ch.skill.Commerce = "1";
    ch.skill.Sneak = "1";
    ch.money = "10";
    LAi_SetCitizenType(ch);
    LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

    ch.old.name = "Conzuela";
    ch.old.lastname = "Rodriguez";
    ch.name    = TranslateString("","Conzuela");
    ch.lastname    = TranslateString("","Rodriguez");
    ch.id        = "Conzuela Rodriguez";
    ch.model    = "towngirl3";
    ch.sex = "woman";
    ch.sound_type = "female_citizen";
    ch.location    = "Santo_Domingo_town";
    ch.location.group = "goto";
    ch.location.locator = "goto3";
    ch.Dialog.Filename = "SantoDomingo citizen_dialog.c";
	ch.greeting = "Gr_Sylvie Bondies";
    ch.nation = SPAIN;
    ch.rank    = 1;
    ch.reputation = "None";
    ch.experience = "0";
    ch.skill.Leadership = "1";
    ch.skill.Fencing = "1";
    ch.skill.Sailing = "1";
    ch.skill.Accuracy = "1";
    ch.skill.Cannons = "1";
    ch.skill.Grappling = "1";
    ch.skill.Repair = "1";
    ch.skill.Defence = "1";
    ch.skill.Commerce = "1";
    ch.skill.Sneak = "1";
    ch.money = "10";
    LAi_SetCitizenType(ch);
    LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

    ch.old.name = "Carla";
    ch.old.lastname = "Martinez";
    ch.name    = TranslateString("","Carla");
    ch.lastname    = TranslateString("","Martinez");
    ch.id        = "Carla Martinez";
    ch.model    = "towngirl5";
    ch.sex = "woman";
    ch.sound_type = "female_citizen";
    ch.location    = "Santo_Domingo_town";
    ch.location.group = "goto";
    ch.location.locator = "goto6";
    ch.Dialog.Filename = "SantoDomingo citizen_dialog.c";
	ch.greeting = "Gr_Sylvie Bondies";
    ch.nation = SPAIN;
    ch.rank    = 1;
    ch.reputation = "None";
    ch.experience = "0";
    ch.skill.Leadership = "1";
    ch.skill.Fencing = "1";
    ch.skill.Sailing = "1";
    ch.skill.Accuracy = "1";
    ch.skill.Cannons = "1";
    ch.skill.Grappling = "1";
    ch.skill.Repair = "1";
    ch.skill.Defence = "1";
    ch.skill.Commerce = "1";
    ch.skill.Sneak = "1";
    ch.money = "10";
    LAi_SetCitizenType(ch);
    LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

			// Soldier near the exit from town
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname = "";
	ch.id		= "SD_soldier_05";
	ch.model = 2; // PB
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Santo_Domingo_town";
	ch.location.group = "goto";
	ch.location.locator = "goto35";
	ch.Dialog.Filename = "Isla Muelle soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = SPAIN;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier";
	AddGameCharacter(n, ch);

			// Soldier near the the exit from town -- another one
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname = "";
	ch.id		= "SD_soldier_06";
	ch.model = 3; // PB
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Santo_Domingo_town";
	ch.location.group = "goto";
	ch.location.locator = "goto36";
	ch.Dialog.Filename = "Isla Muelle soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = SPAIN;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier";
	AddGameCharacter(n, ch);

			// Soldier near the 2nd exit from town
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname = "";
	ch.id		= "SD_soldier_07";
	ch.model = 4; // PB
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Santo_Domingo_town";
	ch.location.group = "goto";
	ch.location.locator = "goto22";
	ch.Dialog.Filename = "Isla Muelle Soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = SPAIN;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle Soldier";
	AddGameCharacter(n, ch);

			// Soldier near the the 2nd exit from town -- another one
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname = "";
	ch.id		= "SD_soldier_08";
	ch.model = 5; // PB
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Santo_Domingo_town";
	ch.location.group = "goto";
	ch.location.locator = "goto39";
	ch.Dialog.Filename = "Isla Muelle Soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = SPAIN;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle Soldier";
	AddGameCharacter(n, ch);

			// governor
	ch.old.name = "Salvador";
	ch.old.lastname = "Allende";
	ch.name = TranslateString("","Salvador");
	ch.lastname = TranslateString("","Allende");
	ch.id		= "Salvador Allende";
	ch.model = "hub_spa3";
	ch.sex = "man";
	ch.location	= "Santo_Domingo_townhall";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.Dialog.Filename = "Salvador Allende_dialog.c";
	ch.Dialog.Filename.GroupDialog = "governor.c";
	ch.nation = SPAIN;
	ch.rank 	= 1;
	ch.reputation = "60";
	ch.experience = "0";
	ch.skill.Leadership = "6";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "5";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_RemoveLoginTime(ch);
	LAi_SetHuberType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	ch.greeting = "Gr_christofor manuel de alencar";
	AddGameCharacter(n, ch);
// <-- KK

// Tortuga Port :

			//France Soldier
	ch.old.name = "Town guard";
	ch.old.lastname = "";
	ch.name 	= TranslateString("","Town guard");
	ch.lastname 	= "";
	ch.id		= "Tor_soldier_1";
	ch.model = 1; // PB
	ch.sound_type = "pirate";
	LAi_CharacterReincarnation(ch, true, false);
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	if (GetCurrentPeriod() >= PERIOD_GOLDEN_AGE_OF_PIRACY)
	{
		GiveItem2Character(ch, "pistol1");
		ch.equip.gun = "pistol1";
	}
	else
	{
		GiveItem2Character(ch, "pistol1a");
		ch.equip.gun = "pistol1a";
	}
	ch.location	= "tortuga_port";
	ch.location.group = "goto";
	ch.location.locator = "goto23";
	ch.Dialog.Filename = "Tortuga citizen_dialog.c";
//	ch.Ship.Type = "Sloop2";				//JRH		
	ch.Ship.Stopped = true;
	ch.rank 	= 1;
	ch.nation = FRANCE;
	ch.Flags.Pirate = 1;
	ch.Flags.Pirate.texture = 2;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "5";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch); // KK
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "TORTUGA_SOLDIERS");
	ch.greeting = "Gr_QC Citizen";
	AddGameCharacter(n, ch);

			//France Soldier
	ch.old.name = "Town guard";
	ch.old.lastname = "";
	ch.name 	= TranslateString("","Town guard");
	ch.lastname 	= "";
	ch.id		= "Tor_soldier_2";
	ch.model = 2; // PB
	ch.sound_type = "pirate";
	LAi_CharacterReincarnation(ch, true, false);
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Tortuga_port";
	ch.location.group = "goto";
	ch.location.locator = "goto21";
	ch.Dialog.Filename = "Tortuga citizen_dialog.c";			
//	ch.Ship.Type = "PiratBrig50";				//JRH		
	ch.Ship.Stopped = true;
	ch.rank 	= 1;
	ch.nation = FRANCE;
	ch.Flags.Pirate = 0;			
	ch.Flags.Pirate.texture = 0;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch); // KK
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "TORTUGA_SOLDIERS");
	ch.greeting = "Gr_QC Citizen";
	AddGameCharacter(n, ch);

			//Patrol
	ch.old.name = "Town guard";
	ch.old.lastname = "";
	ch.name 	= TranslateString("","Town guard");
	ch.lastname 	= "";
	ch.id		= "Tor_patrol_1";
	ch.model = 3; // PB
	ch.model	= "mongol";
	ch.sound_type = "pirate";
	LAi_CharacterReincarnation(ch, true, false);
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Tortuga_port";
	ch.location.group = "goto";
	ch.location.locator = "goto18";
	ch.Dialog.Filename = "patrol_dialog.c";			
//	ch.Ship.Type = "SchoonerXebec";				//JRH	
	ch.Ship.Stopped = true;
	ch.rank 	= 1;
	ch.nation = FRANCE;
	ch.Flags.Pirate = 4;
	ch.Flags.Pirate.texture = 2;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch); // KK
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "TORTUGA_SOLDIERS");
	ch.greeting = "Gr_QC Citizen";
	AddGameCharacter(n, ch);

			//Patrol
	ch.old.name = "Town guard";
	ch.old.lastname = "";
	ch.name 	= TranslateString("","Town guard");
	ch.lastname 	= "";
	ch.id		= "Tor_patrol_2";
	ch.model = 4; // PB
	ch.sound_type = "pirate";
	LAi_CharacterReincarnation(ch, true, false);
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Tortuga_port";
	ch.location.group = "goto";
	ch.location.locator = "goto12";
	ch.Dialog.Filename = "patrol_dialog.c";				
//	ch.Ship.Type = "FR_Sloop";			//JRH	
	ch.Ship.Stopped = true;
	ch.rank 	= 1;
	ch.nation = FRANCE;
	ch.Flags.Pirate = 5;
	ch.Flags.Pirate.texture = 0;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch); // KK
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "TORTUGA_SOLDIERS");
	ch.greeting = "Gr_QC Citizen";
	AddGameCharacter(n, ch);
 
		
	ch.old.name = "William";
	ch.old.lastname = "Neal";
	ch.name 	= TranslateString("","William");
	ch.lastname = TranslateString("","Neal");
	ch.id		= "William Neal";
	ch.model	= "pirat7";
	ch.headmodel = "h_pirat7";
	ch.sound_type = "pirate";
	ch.sex = "man";
	GiveItem2Character(ch, "blade20");
	ch.equip.blade = "blade20";
	if (GetCurrentPeriod() >= PERIOD_GOLDEN_AGE_OF_PIRACY)
	{
		GiveItem2Character(ch, "pistol7");
		ch.equip.gun = "pistol7";
	}
	else
	{
		GiveItem2Character(ch, "pistol7a");
		ch.equip.gun = "pistol7a";
	}
	if (ENABLE_AMMOMOD) {
		TakenItems(ch, "gunpowder", 1 + rand(2));
		TakenItems(ch, "pistolbullets", 1 + rand(2));
	}
	ch.location	= "Tortuga_port";
	ch.location.group = "goto";
	ch.location.locator = "goto5";
	ch.Dialog.Filename = "Tortuga citizen_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 10;
	ch.reputation = "20";
	ch.experience = "5000";
	ch.skill.Leadership = "6";
	ch.skill.Fencing = "7";
	ch.skill.Sailing = "6";
	ch.skill.Accuracy = "6";
	ch.skill.Cannons = "5";
	ch.skill.Grappling = "4";
	ch.skill.Repair = "5";
	ch.skill.Defence = "7";
	ch.skill.Commerce = "5";
	ch.skill.Sneak = "6";
	ch.money = "1000";
	ch.perks.list.BasicDefence = true;
	ch.perks.list.AdvancedDefence = true;
	ch.perks.list.SwordplayProfessional = true;
	ch.perks.list.CriticalHit = true;
	ch.perks.list.Gunman = true;
	ch.perks.list.ProfessionalGunman = true;
	ch.perks.list.HullDamageUp = true;
	ch.perks.list.CrewDamageUp = true;
	ch.perks.list.BasicDamageControl = true;
	ch.perks.list.Rigging = true;
	ch.perks.list.BasicDefence = true;
	ch.perks.list.AdvancedDefence = true;
	ch.perks.list.ShipSpeedUp = true;
	ch.perks.list.LightRepair = true;
	ch.perks.list.SharedExperience = true;
	ch.Ship.Name = "Spider";
	ch.Ship.Type = "Sloop1";
	ch.Ship.Cannons.Type = CANNON_TYPE_CULVERINE_LBS16;
	ch.ship.cargo.goods.BALLS = 1000;
	ch.ship.cargo.goods.GRAPES = 500;
	ch.ship.cargo.goods.KNIPPELS = 500;
//	ch.ship.cargo.goods.bombs = 1000;	// TIH done by setbaseship 7-7-06
	ch.Ship.Stopped = true;
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetWarriorType(ch);
	LAi_warrior_DialogEnable(ch, true);
	//LAi_SetSitType(ch);
	LAi_SetHP(ch, 200.0, 200.0);
	LAi_NoRebirthEnable(ch);
	ch.greeting = "Gr_Rys Bloom";
	LAi_group_MoveCharacter(ch, "TORTUGA_CITIZENS");
	AddGameCharacter(n, ch);

    ch.old.name = "Peter";
    ch.old.lastname = "Rodgers";
    ch.name    = TranslateString("","Peter");
    ch.lastname    = TranslateString("","Rodgers");
    ch.id        = "Peter Rodgers";
    ch.model    = "bocman18";
    ch.sex = "man";
    ch.sound_type = "pirate";
    ch.location    = "Tortuga_port";
    ch.location.group = "goto";
    ch.location.locator = "goto20";
    ch.Dialog.Filename = "Tortuga citizen_dialog.c";
    ch.nation = FRANCE;
    ch.rank    = 1;
    ch.reputation = "None";
    ch.experience = "0";
    ch.skill.Leadership = "1";
    ch.skill.Fencing = "1";
    ch.skill.Sailing = "1";
    ch.skill.Accuracy = "1";
    ch.skill.Cannons = "1";
    ch.skill.Grappling = "1";
    ch.skill.Repair = "1";
    ch.skill.Defence = "1";
    ch.skill.Commerce = "1";
    ch.skill.Sneak = "1";
    ch.money = "10";
    LAi_SetCitizenType(ch);
    LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

    ch.old.name = "Claire";
    ch.old.lastname = "Rodgers";
    ch.name    = TranslateString("","Claire");
    ch.lastname    = TranslateString("","Rodgers");
    ch.id        = "Claire Rodgers";
    ch.model    = "daniell3";
    ch.sex = "woman";
    ch.sound_type = "pirate";
    ch.location    = "Tortuga_port";
    ch.location.group = "goto";
    ch.location.locator = "goto15";
    ch.Dialog.Filename = "Tortuga citizen_dialog.c";
    ch.nation = FRANCE;
    ch.rank    = 1;
    ch.reputation = "None";
    ch.experience = "0";
    ch.skill.Leadership = "1";
    ch.skill.Fencing = "1";
    ch.skill.Sailing = "1";
    ch.skill.Accuracy = "1";
    ch.skill.Cannons = "1";
    ch.skill.Grappling = "1";
    ch.skill.Repair = "1";
    ch.skill.Defence = "1";
    ch.skill.Commerce = "1";
    ch.skill.Sneak = "1";
    ch.money = "10";
    LAi_SetCitizenType(ch);
    LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

// Townhall
	ch.old.name = "Bertrand";
	ch.old.lastname = "Ogeron";
	ch.name = TranslateString("","Bertrand");
	ch.lastname = TranslateString("","Ogeron");
	ch.id		= "Bertrand Ogeron";
	ch.model = "BadV";
	ch.sex = "man";
	ch.nation = FRANCE;	
	ch.location	= "Tortuga_Townhall";
	ch.location.group = "sit";
	ch.location.locator = "sit3";
	ch.Dialog.Filename = "Bertrand Ogeron_dialog.c";
//	ch.Dialog.Filename.GroupDialog = "governor.c"; // PB: This guy is NOT a regular governor!
	ch.rank 	= 20;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "10";
	ch.skill.Fencing = "5";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "8";
	ch.skill.Sneak = "5";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetHuberType(ch);
	LAi_group_MoveCharacter(ch, "TORTUGA_CITIZENS");
	ch.greeting = "Gr_Armand Delacroix";
	AddGameCharacter(n, ch);

	ch.old.name = "Guy";
	ch.old.lastname = "Lafleur";
	ch.name	= TranslateString("", "Guy");
	ch.lastname	= TranslateString("", "Lafleur");
	ch.id = "Guy Lafleur";
	ch.model = "9R_Purs";
	ch.sex = "man";
	ch.location	= "Tortuga_tailorsShop";
	ch.location.group = "goto";
	ch.location.locator = "stay1";
	ch.IsTailor = true;
	ch.Dialog.Filename = "tailor_dialog.c";
 	ch.Dialog.Filename.Groupdialog = "tailor.c";
	ch.rank 	= 1;
	ch.nation = FRANCE;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "0";
	ch.skill.Fencing = "0";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "10";
	ch.skill.Sneak = "0";
	ch.money = "10";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 6.0, 18.0);
	AddGameCharacter(n, ch);

// Tortuga : town part1

			// Soldier
	ch.old.name = "Town guard";
	ch.old.lastname = "";
	ch.name 	= TranslateString("","Town guard");
	ch.lastname 	= "";
	ch.id		= "Tor_soldier_3";
	ch.model = 5; // PB
	ch.sex = "man";
	ch.sound_type = "pirate";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	if (GetCurrentPeriod() >= PERIOD_GOLDEN_AGE_OF_PIRACY)
	{
		GiveItem2Character(ch, "pistol1");
		ch.equip.gun = "pistol1";
	}
	else
	{
		GiveItem2Character(ch, "pistol1a");
		ch.equip.gun = "pistol1a";
	}
	ch.location	= "Tortuga_port";
	ch.location.group = "soldiers";
	ch.location.locator = "soldier1";
	ch.Dialog.Filename = "Tortuga citizen_dialog.c";
//	ch.Ship.Type = "MerchantPinnace";				//JRH		
	ch.Ship.Stopped = true;
	ch.nation = FRANCE;
	ch.Flags.Pirate = 1;
	ch.Flags.Pirate.texture = 2;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch); // KK
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "TORTUGA_SOLDIERS");
	ch.greeting = "Gr_QC Citizen";
	AddGameCharacter(n, ch);

			// Soldier
	ch.old.name = "Town guard";
	ch.old.lastname = "";
	ch.name 	= TranslateString("","Town guard");
	ch.lastname 	= "";
	ch.id		= "Tor_soldier_4";
	ch.model = 6; // PB
	ch.sex = "man";
	ch.sound_type = "pirate";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	if (GetCurrentPeriod() >= PERIOD_GOLDEN_AGE_OF_PIRACY)
	{
		GiveItem2Character(ch, "pistol1");
		ch.equip.gun = "pistol1";
	}
	else
	{
		GiveItem2Character(ch, "pistol1a");
		ch.equip.gun = "pistol1a";
	}
	ch.location	= "Tortuga_port";
	ch.location.group = "soldiers";
	ch.location.locator = "soldier2";
	ch.Dialog.Filename = "Tortuga citizen_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 3;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch); // KK
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "TORTUGA_SOLDIERS");
	ch.greeting = "Gr_QC Citizen";
	AddGameCharacter(n, ch);

			// Soldier
	ch.old.name = "Town guard";
	ch.old.lastname = "";
	ch.name 	= TranslateString("","Town guard");
	ch.lastname 	= "";
	ch.id		= "Tor_soldier_5";
	ch.model = 0; // PB
	ch.sex = "man";
	ch.sound_type = "pirate";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Tortuga_port";
	ch.location.group = "soldiers";
	ch.location.locator = "soldier3";
	ch.Dialog.Filename = "Tortuga citizen_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch); // KK
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "TORTUGA_SOLDIERS");
	ch.greeting = "Gr_QC Citizen";
	AddGameCharacter(n, ch);

			// Soldier
	ch.old.name = "Town guard";
	ch.old.lastname = "";
	ch.name 	= TranslateString("","Town guard");
	ch.lastname 	= "";
	ch.id		= "Tor_soldier_6";
	ch.model = 1; // PB
	ch.sex = "man";
	ch.sound_type = "pirate";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Tortuga_port";
	ch.location.group = "soldiers";
	ch.location.locator = "soldier4";
	ch.Dialog.Filename = "Tortuga citizen_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch); // KK
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "TORTUGA_SOLDIERS");
	ch.greeting = "Gr_QC Citizen";
	AddGameCharacter(n, ch);

//JRH additional characters Tortuga_port -->

	ch.old.name = "Carpenter";
	ch.old.lastname = "";
	ch.name 	= TranslateString("","Carpenter");
	ch.lastname = "";
	ch.id		= "Tortuga_carpenter1";
	ch.model	= "gm_crew15";
	ch.sound_type = "pirate";
	ch.sex = "man";
	GiveItem2Character(ch, "bladeaxe3");
	ch.equip.blade = "bladeaxe3";
	ch.location	= "Tortuga_port";
	ch.location.group = "stay";
	ch.location.locator = "repair1";
	ch.Dialog.Filename = "Tortuga citizen_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 10;
	ch.reputation = "20";
	ch.experience = "5000";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "8";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetLoginTime(ch, 10.0, 22.0);
	LAi_SetStayType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Rys Bloom";
	//LAi_group_MoveCharacter(ch, "TORTUGA_CITIZENS");
	AddGameCharacter(n, ch);

	ch.old.name = "Jorge";
	ch.old.lastname = "Pereira";
	ch.name 	= TranslateString("","Jorge");
	ch.lastname = TranslateString("","Pereira");
	ch.id		= "Tortuga_carpenter2";
	ch.model	= "gm_crew20";
	ch.sound_type = "pirate";
	ch.sex = "man";
	GiveItem2Character(ch, "blade3");
	ch.equip.blade = "blade3";
	GiveItem2Character(ch, "pistol2");
	ch.equip.gun = "pistol2";
	if (ENABLE_AMMOMOD) {
		TakenItems(ch, "gunpowder", 1 + rand(2));
		TakenItems(ch, "pistolbullets", 1 + rand(2));
	}
	ch.location	= "Tortuga_port";
	ch.location.group = "stay";
	ch.location.locator = "repair2";
	ch.Dialog.Filename = "Tortuga citizen_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 10;
	ch.reputation = "20";
	ch.experience = "5000";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "8";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetLoginTime(ch, 10.0, 22.0);
	LAi_SetStayType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Conceicao Citizen";
	//LAi_group_MoveCharacter(ch, "TORTUGA_CITIZENS");
	AddGameCharacter(n, ch);

	ch.old.name = "Maarten";
	ch.old.lastname = "Peeters";
	ch.name 	= TranslateString("","Maarten");
	ch.lastname = TranslateString("","Peeters");
	ch.id		= "Tortuga_citizen1";
	ch.model	= "gm_crew1";
	ch.sound_type = "pirate";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Tortuga_port";
	ch.location.group = "goto";
	ch.location.locator = "goto39";
	ch.Dialog.Filename = "Tortuga citizen_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 10;
	ch.reputation = "20";
	ch.experience = "5000";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "8";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetLoginTime(ch, 14.0, 22.0);
	LAi_SetCitizenType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Douwesen Citizen"; 
	LAi_group_MoveCharacter(ch, "TORTUGA_CITIZENS");
	AddGameCharacter(n, ch);

	ch.old.name = "Herbert";
	ch.old.lastname = "Fawn";
	ch.name 	= TranslateString("","Herbert");
	ch.lastname = TranslateString("","Fawn");
	ch.id		= "Tortuga_citizen2";
	ch.model	= "gm_crew3";
	ch.sound_type = "pirate";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Tortuga_port";
	ch.location.group = "goto";
	ch.location.locator = "goto30";
	ch.Dialog.Filename = "Tortuga citizen_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 10;
	ch.reputation = "20";
	ch.experience = "5000";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "8";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetCitizenType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Rys Bloom";
	LAi_group_MoveCharacter(ch, "TORTUGA_CITIZENS");
	AddGameCharacter(n, ch);

	ch.old.name = "Roger";
	ch.old.lastname = "Leadbeater";
	ch.name 	= TranslateString("","Roger");
	ch.lastname = TranslateString("","Leadbeater");
	ch.id		= "Tortuga_citizen3";
	ch.model	= "gm_crew4";
	ch.sound_type = "pirate";
	ch.sex = "man";
	GiveItem2Character(ch, "barmansknife");
	ch.equip.blade = "barmansknife";
	GiveItem2Character(ch, "pistol2");
	ch.equip.gun = "pistol2";
	if (ENABLE_AMMOMOD) {
		TakenItems(ch, "gunpowder", 1 + rand(2));
		TakenItems(ch, "pistolbullets", 1 + rand(2));
	}
	ch.location	= "Tortuga_port";
	ch.location.group = "goto";
	ch.location.locator = "goto5";
	ch.Dialog.Filename = "Tortuga citizen_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 10;
	ch.reputation = "20";
	ch.experience = "5000";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "8";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetLoginTime(ch, 14.0, 22.0);
	LAi_SetCitizenType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Rys Bloom";
	LAi_group_MoveCharacter(ch, "TORTUGA_CITIZENS");
	AddGameCharacter(n, ch);

	ch.old.name = "Jordan";
	ch.old.lastname = "Richardson";
	ch.name 	= TranslateString("","Jordan");
	ch.lastname = TranslateString("","Richardson");
	ch.id		= "Tortuga_citizen4";
	ch.model	= "pir_cap4";
	ch.sound_type = "pirate";
	ch.sex = "man";
	GiveItem2Character(ch, "bladeclub");
	ch.equip.blade = "bladeclub";
	ch.location	= "Tortuga_port";
	ch.location.group = "goto";
	ch.location.locator = "goto9";
	ch.Dialog.Filename = "Tortuga citizen_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 10;
	ch.reputation = "20";
	ch.experience = "5000";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "8";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetLoginTime(ch, 0.0, 2.0);
	LAi_SetLoginTime(ch, 10.0, 24.0);
	LAi_SetCitizenType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Rys Bloom";
	LAi_group_MoveCharacter(ch, "TORTUGA_CITIZENS");
	AddGameCharacter(n, ch);

	ch.old.name = "Gerard";
	ch.old.lastname = "Dupray";
	ch.name 	= TranslateString("","Gerard");
	ch.lastname = TranslateString("","Dupray");
	ch.id		= "Tortuga_citizen5";
	ch.model	= "gm_crew10";
	ch.sound_type = "pirate";
	ch.sex = "man";
	GiveItem2Character(ch, "merchantsblade");
	ch.equip.blade = "merchantsblade";
	ch.location	= "Tortuga_port";
	ch.location.group = "goto";
	ch.location.locator = "goto3";
	ch.Dialog.Filename = "Tortuga citizen_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 10;
	ch.reputation = "20";
	ch.experience = "5000";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "8";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetCitizenType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_falaise de fleur citizen";
	LAi_group_MoveCharacter(ch, "TORTUGA_CITIZENS");
	AddGameCharacter(n, ch);

	ch.old.name = "Gabriel";
	ch.old.lastname = "Santana";
	ch.name 	= TranslateString("","Gabriel");
	ch.lastname = TranslateString("","Santana");
	ch.id		= "Tortuga_citizen6";
	ch.model	= "gm_crew11";
	ch.sound_type = "pirate";
	ch.sex = "man";
	GiveItem2Character(ch, "blade2");
	ch.equip.blade = "blade2";
	ch.location	= "Tortuga_port";
	ch.location.group = "goto";
	ch.location.locator = "goto34";
	ch.Dialog.Filename = "Tortuga citizen_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 10;
	ch.reputation = "20";
	ch.experience = "5000";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "8";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetLoginTime(ch, 0.0, 2.0);
	LAi_SetLoginTime(ch, 10.0, 24.0);
	LAi_SetCitizenType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_isla muelle citizen";
	LAi_group_MoveCharacter(ch, "TORTUGA_CITIZENS");
	AddGameCharacter(n, ch);

	ch.old.name = "Dirk";
	ch.old.lastname = "Maase";
	ch.name 	= TranslateString("","Dirk");
	ch.lastname = TranslateString("","Maase");
	ch.id		= "Tortuga_citizen7";
	ch.model	= "gm_crew18";
	ch.sound_type = "pirate";
	ch.sex = "man";
	GiveItem2Character(ch, "blade1");
	ch.equip.blade = "blade1";
	ch.location	= "Tortuga_port";
	ch.location.group = "goto";
	ch.location.locator = "goto37";
	ch.Dialog.Filename = "Tortuga citizen_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 10;
	ch.reputation = "20";
	ch.experience = "5000";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "8";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetLoginTime(ch, 14.0, 22.0);
	LAi_SetCitizenType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Douwesen Citizen"; 
	LAi_group_MoveCharacter(ch, "TORTUGA_CITIZENS");
	AddGameCharacter(n, ch);

	ch.old.name = "Lars";
	ch.old.lastname = "Andersson";
	ch.name 	= TranslateString("","Lars");
	ch.lastname = TranslateString("","Andersson");
	ch.id		= "Tortuga_citizen8";
	ch.model	= "gm_crew22";
	ch.sound_type = "pirate";
	ch.sex = "man";
	GiveItem2Character(ch, "guestsknife");
	ch.equip.blade = "guestsknife";
	GiveItem2Character(ch, "pistol2");
	ch.equip.gun = "pistol2";
	if (ENABLE_AMMOMOD) {
		TakenItems(ch, "gunpowder", 1 + rand(2));
		TakenItems(ch, "pistolbullets", 1 + rand(2));
	}
	ch.location	= "Tortuga_port";
	ch.location.group = "goto";
	ch.location.locator = "goto28";
	ch.Dialog.Filename = "Tortuga citizen_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 10;
	ch.reputation = "20";
	ch.experience = "5000";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "8";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetLoginTime(ch, 14.0, 22.0);
	LAi_SetCitizenType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Douwesen Citizen"; 
	LAi_group_MoveCharacter(ch, "TORTUGA_CITIZENS");
	AddGameCharacter(n, ch);
//<-- JRH

	// Soldier
	ch.old.name = "Town guard";
	ch.old.lastname = "";
	ch.name 	= TranslateString("","Town guard");
	ch.lastname 	= "";
	ch.id		= "Tor_soldier_7";
	ch.model = 2; // PB
	ch.sex = "man";
	ch.sound_type = "pirate";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Tortuga_Prison";
	ch.location.group = "goto";
	ch.location.locator = "goto16";
	ch.Dialog.Filename = "Tortuga citizen_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch); // KK
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "TORTUGA_SOLDIERS");
	ch.greeting = "Gr_QC Citizen";
	AddGameCharacter(n, ch);

	// Soldier
	ch.old.name = "Town guard";
	ch.old.lastname = "";
	ch.name 	= TranslateString("","Town guard");
	ch.lastname 	= "";
	ch.id		= "Tor_soldier_8";
	ch.model = 3; // PB
	ch.sex = "man";
	ch.sound_type = "pirate";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Tortuga_Prison";
	ch.location.group = "goto";
	ch.location.locator = "goto17";
	ch.Dialog.Filename = "Tortuga citizen_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch); // KK
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "TORTUGA_SOLDIERS");
	ch.greeting = "Gr_QC Citizen";
	AddGameCharacter(n, ch);

			// governor
	ch.old.name = "Isabelle";
	ch.old.lastname = "de Cussy";
	ch.name = TranslateString("","Isabelle");
	ch.lastname = TranslateString("","de Cussy");
	ch.id		= "Isabelle de Cussy";
	ch.model = "Liz1";
	ch.sex = "woman";
	ch.location	= "PoPrince_townhall";
	ch.location.group = "goto";
	ch.location.locator = "goto2";
	ch.Dialog.Filename = "Isabelle de Cussy_dialog.c";
	ch.Dialog.Filename.GroupDialog = "governor.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "60";
	ch.experience = "0";
	ch.skill.Leadership = "6";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "5";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_RemoveLoginTime(ch);
	LAi_SetStayType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	ch.greeting = "Gr_Estrella";
	AddGameCharacter(n, ch);
// <-- KK

	ch.old.name = "Charles";
	ch.old.middlename = "Aubert";
	ch.old.lastname = "de La Chesnaye";
	ch.name = TranslateString("","Charles");
	ch.middlename = TranslateString("","Aubert");
	ch.lastname = TranslateString("","de La Chesnaye");
	ch.id		= "French_WIC_Officer";
	ch.model	= "Huber_Fra3_17";
	ch.sex = "man";
	ch.location	= "French_WIC_Office";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.Dialog.Filename = "WIC Officer_dialog.c";
	ch.nation = FRANCE;
	ch.rank		= 1;
	ch.reputation	= "50";
	ch.experience	= "0";
	ch.skill.Leadership	= "1";
	ch.skill.Fencing	= "1";
	ch.skill.Sailing	= "1";
	ch.skill.Accuracy	= "1";
	ch.skill.Cannons	= "1";
	ch.skill.Grappling	= "1";
	ch.skill.Repair		= "1";
	ch.skill.Defence	= "1";
	ch.skill.Commerce	= "10";
	ch.skill.Sneak		= "1";
	ch.money = "1";
	LAi_SetHuberType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	ch.greeting = "Gr_turpin cabanel";
	AddGameCharacter(n, ch);

	///////////////////////////////////////////////////////////////////////////////////////////////
	// SOLDIERS
	///////////////////////////////////////////////////////////////////////////////////////////////
			//Soldier на входе в город
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname 	= "";
	ch.id		= "PoPrince_soldier_01";
	ch.model = 2; // PB
	ch.sound_type = "soldier";
	ch.sex = "man";
	LAi_CharacterReincarnation(ch, true, false);
	ch.equip.blade = "blade4";
	ch.location	= "PoPrince_Port";
	ch.location.group = "goto";
	ch.location.locator = "goto12";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	GiveItem2Character(ch, "blade4");
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	LAi_CharacterReincarnation(ch, true, false);
	ch.greeting = "Gr_falaise de fleur soldier";
	AddGameCharacter(n, ch);

  			//Soldier на входе в город -- one more
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname 	= "";
	ch.id		= "PoPrince_soldier_02";
	ch.model = 1; // PB
	LAi_CharacterReincarnation(ch, true, false);
	ch.sound_type = "soldier";
	ch.sex = "man";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "PoPrince_Port";
	ch.location.group = "goto";
	ch.location.locator = "goto13";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	AddGameCharacter(n, ch);

			//Patrol
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname 	= "";
	ch.id		= "PoPrince_patrol_01";
	ch.model = 3; // PB
	LAi_CharacterReincarnation(ch, true, false);
	ch.sound_type = "soldier";
	ch.sex = "man";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "PoPrince_Port";
	ch.location.group = "goto";
	ch.location.locator = "goto11";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	AddGameCharacter(n, ch);

			//Patrol
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname 	= "";
	ch.id		= "PoPrince_patrol_02";
	ch.model = 4; // PB
	LAi_CharacterReincarnation(ch, true, false);
	ch.sound_type = "soldier";
	ch.sex = "man";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "PoPrince_Port";
	ch.location.group = "goto";
	ch.location.locator = "goto5";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	AddGameCharacter(n, ch);

			//Soldier near the entrance from port
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname 	= "";
	ch.id		= "PoPrince_soldier_03";
	ch.model = 5; // PB
	LAi_CharacterReincarnation(ch, true, false);
	ch.sound_type = "soldier";
	ch.sex = "man";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "PoPrince_town";
	ch.location.group = "goto";
	ch.location.locator = "goto28";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	AddGameCharacter(n, ch);

			//Soldier near the entrance from port
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname 	= "";
	ch.id		= "PoPrince_soldier_04";
	ch.model = 6; // PB
	ch.sound_type = "soldier";
	ch.sex = "man";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "PoPrince_town";
	ch.location.group = "goto";
	ch.location.locator = "goto29";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	AddGameCharacter(n, ch);

			//Soldier near the residence
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname 	= "";
	ch.id		= "PoPrince_soldier_05";
	ch.model = 2; // PB
	ch.sound_type = "soldier";
	ch.sex = "man";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "PoPrince_town";
	ch.location.group = "goto";
	ch.location.locator = "goto21";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	AddGameCharacter(n, ch);

			//Soldier near the residence
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname 	= "";
	ch.id		= "PoPrince_soldier_06";
	ch.model = 2; // PB
	ch.sound_type = "soldier";
	ch.sex = "man";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "PoPrince_town";
	ch.location.group = "goto";
	ch.location.locator = "goto22";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	AddGameCharacter(n, ch);

			//Soldier near the entrance from jungle
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname 	= "";
	ch.id		= "PoPrince_soldier_07";
	ch.model = 6; // PB
	ch.sound_type = "soldier";
	ch.sex = "man";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "PoPrince_town";
	ch.location.group = "goto";
	ch.location.locator = "goto19";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	AddGameCharacter(n, ch);

			//Soldier near the entrance from jungle
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname 	= "";
	ch.id		= "PoPrince_soldier_08";
	ch.model = 3; // PB
	ch.sound_type = "soldier";
	ch.sex = "man";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "PoPrince_town";
	ch.location.group = "goto";
	ch.location.locator = "goto20";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	AddGameCharacter(n, ch);

			//Patrol
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname 	= "";
	ch.id		= "PoPrince_patrol_03";
	ch.model = 2; // PB
	ch.sound_type = "soldier";
	ch.sex = "man";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "PoPrince_town";
	ch.location.group = "goto";
	ch.location.locator = "goto13";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	AddGameCharacter(n, ch);

			//Patrol
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname 	= "";
	ch.id		= "PoPrince_patrol_04";
	ch.model = 6; // PB
	ch.sound_type = "soldier";
	ch.sex = "man";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "PoPrince_town";
	ch.location.group = "goto";
	ch.location.locator = "goto18";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	AddGameCharacter(n, ch);

			//Patrol
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname 	= "";
	ch.id		= "PoPrince_patrol_05";
	ch.model = 5; // PB
	ch.sound_type = "soldier";
	ch.sex = "man";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "PoPrince_town";
	ch.location.group = "goto";
	ch.location.locator = "goto9";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	AddGameCharacter(n, ch);

// Port-au-Prince citizens
    ch.old.name = "Frederic";
    ch.old.lastname = "Bagage";
    ch.name    = TranslateString("","Frederic");
    ch.lastname    = TranslateString("","Bagage");
    ch.id        = "Frederic Bagage";
    ch.model    = "nobleman";
    ch.sex = "man";
    ch.sound_type = "seaman";
    ch.location    = "PoPrince_Port";
    ch.location.group = "goto";
    ch.location.locator = "goto3";
    ch.Dialog.Filename = "PoPrince citizen_dialog.c";
	ch.greeting = "Gr_french citizen";
    ch.nation = FRANCE;
    ch.rank    = 1;
    ch.reputation = "None";
    ch.experience = "0";
    ch.skill.Leadership = "1";
    ch.skill.Fencing = "1";
    ch.skill.Sailing = "1";
    ch.skill.Accuracy = "1";
    ch.skill.Cannons = "1";
    ch.skill.Grappling = "1";
    ch.skill.Repair = "1";
    ch.skill.Defence = "1";
    ch.skill.Commerce = "1";
    ch.skill.Sneak = "1";
    ch.money = "10";
    LAi_SetCitizenType(ch);
    LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	AddGameCharacter(n, ch);

    ch.old.name = "Arielle";
    ch.old.lastname = "Dumont";
    ch.name    = TranslateString("","Arielle");
    ch.lastname    = TranslateString("","Dumont");
    ch.id        = "Arielle Dumont";
    ch.model    = "Dan_TG3";
    ch.sex = "woman";
    ch.sound_type = "female_citizen";
    ch.location    = "PoPrince_Port";
    ch.location.group = "goto";
    ch.location.locator = "goto7";
    ch.Dialog.Filename = "PoPrince citizen_dialog.c";
	ch.greeting = "Gr_Woman_French citizen";
    ch.nation = FRANCE;
    ch.rank    = 1;
    ch.reputation = "None";
    ch.experience = "0";
    ch.skill.Leadership = "1";
    ch.skill.Fencing = "1";
    ch.skill.Sailing = "1";
    ch.skill.Accuracy = "1";
    ch.skill.Cannons = "1";
    ch.skill.Grappling = "1";
    ch.skill.Repair = "1";
    ch.skill.Defence = "1";
    ch.skill.Commerce = "1";
    ch.skill.Sneak = "1";
    ch.money = "10";
    LAi_SetCitizenType(ch);
    LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	AddGameCharacter(n, ch);

    ch.old.name = "John";
    ch.old.lastname = "Dorian";
    ch.name    = TranslateString("","John");
    ch.lastname    = TranslateString("","Dorian");
    ch.id        = "John Dorian";
    ch.model    = "Espinosa";
    ch.sex = "man";
    ch.sound_type = "seaman";
    ch.location    = "PoPrince_town";
    ch.location.group = "goto";
    ch.location.locator = "goto4";
    ch.Dialog.Filename = "PoPrince citizen_dialog.c";
	ch.greeting = "Gr_french citizen";
    ch.nation = FRANCE;
    ch.rank    = 1;
    ch.reputation = "None";
    ch.experience = "0";
    ch.skill.Leadership = "1";
    ch.skill.Fencing = "1";
    ch.skill.Sailing = "1";
    ch.skill.Accuracy = "1";
    ch.skill.Cannons = "1";
    ch.skill.Grappling = "1";
    ch.skill.Repair = "1";
    ch.skill.Defence = "1";
    ch.skill.Commerce = "1";
    ch.skill.Sneak = "1";
    ch.money = "10";
    LAi_SetCitizenType(ch);
    LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	AddGameCharacter(n, ch);

    ch.old.name = "Denise";
    ch.old.lastname = "Fleur";
    ch.name    = TranslateString("","Denise");
    ch.lastname    = TranslateString("","Fleur");
    ch.id        = "Denise Fleur";
    ch.model    = "towngirl3_1";
    ch.sex = "woman";
    ch.sound_type = "female_citizen";
    ch.location    = "PoPrince_town";
    ch.location.group = "goto";
    ch.location.locator = "goto18";
    ch.Dialog.Filename = "PoPrince citizen_dialog.c";
	ch.greeting = "Gr_Woman_French citizen";
    ch.nation = FRANCE;
    ch.rank    = 1;
    ch.reputation = "None";
    ch.experience = "0";
    ch.skill.Leadership = "1";
    ch.skill.Fencing = "1";
    ch.skill.Sailing = "1";
    ch.skill.Accuracy = "1";
    ch.skill.Cannons = "1";
    ch.skill.Grappling = "1";
    ch.skill.Repair = "1";
    ch.skill.Defence = "1";
    ch.skill.Commerce = "1";
    ch.skill.Sneak = "1";
    ch.money = "10";
    LAi_SetCitizenType(ch);
    LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	AddGameCharacter(n, ch);

    ch.old.name = "Dimitri";
    ch.old.lastname = "Lunesque";
    ch.name    = TranslateString("","Dimitri");
    ch.lastname    = TranslateString("","Lunesque");
    ch.id        = "Dimitri Lunesque";
    ch.model    = "will_3";
    ch.sex = "man";
    ch.sound_type = "seaman";
    ch.location    = "PoPrince_town";
    ch.location.group = "goto";
    ch.location.locator = "goto24";
    ch.Dialog.Filename = "PoPrince citizen_dialog.c";
	ch.greeting = "Gr_french citizen";
    ch.nation = FRANCE;
    ch.rank    = 1;
    ch.reputation = "None";
    ch.experience = "0";
    ch.skill.Leadership = "1";
    ch.skill.Fencing = "1";
    ch.skill.Sailing = "1";
    ch.skill.Accuracy = "1";
    ch.skill.Cannons = "1";
    ch.skill.Grappling = "1";
    ch.skill.Repair = "1";
    ch.skill.Defence = "1";
    ch.skill.Commerce = "1";
    ch.skill.Sneak = "1";
    ch.money = "10";
    LAi_SetCitizenType(ch);
    LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	AddGameCharacter(n, ch);

	ch.old.name = "Bryan";
	ch.old.lastname = "the Disgruntled";
	ch.name = TranslateString("","Bryan");
	ch.lastname = TranslateString("","the Disgruntled");
	ch.id		= "Bryan the Disgruntled";
	ch.model	= "9Ja";
	ch.sex = "man";
	ch.sound_type = "pirate";
	ch.location	= "Buccaneers_Camp";
	ch.location.group = "goto";
	ch.location.locator = "goto39";
//	ch.Dialog.Filename = "Buccaneers_dialog.c";
	ch.Dialog.Filename = "BC_Citizens_dialog.c";
	ch.nation = PIRATE;
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetWarriorType(ch);
	LAi_warrior_DialogEnable(ch, true);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "QC_SOLDIERS");
	ch.greeting = "Gr_QC Citizen";
	AddGameCharacter(n, ch);

	ch.old.name = "Bloody";
	ch.old.lastname = "Norm Kidd";
	ch.name = TranslateString("","Bloody");
	ch.lastname = TranslateString("","Norm Kidd");
	ch.id		= "Bloody Norm Kidd";
	ch.model	= "Diller";
	ch.sex = "man";
	ch.sound_type = "pirate";
	ch.location	= "Buccaneers_Camp";
	ch.location.group = "goto";
	ch.location.locator = "goto36";
//	ch.Dialog.Filename = "Buccaneers_dialog.c";
	ch.Dialog.Filename = "BC_Citizens_dialog.c";
	ch.nation = PIRATE;
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetWarriorType(ch);
	LAi_warrior_DialogEnable(ch, true);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "QC_SOLDIERS");
	ch.greeting = "Gr_QC Citizen";
	AddGameCharacter(n, ch);

// Padre Iguaran
	ch.old.name = "Padre";
	ch.old.lastname = "Iguaran";
	ch.name = TranslateString("","Padre");
	ch.lastname = TranslateString("","Iguaran");
	ch.id		= "Padre Iguaran";
	ch.model	= "Animistse";
	ch.sex = "man";
	LAi_NoRebirthEnable(ch);
	ch.sound_type = "priest";
	ch.location	= "village_church";
	ch.location.group = "goto";
	ch.location.locator = "goto11";
	ch.Dialog.Filename = "Father Abbott_dialog.c";
	ch.Dialog.Filename.group = "church.c";
	ch.nation = SPAIN;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_NoRebirthEnable(ch);
	ch.greeting = "Gr_Padre Domingues";
	AddGameCharacter(n, ch);

    	ch.old.name = "Pablo";
   	ch.old.lastname = "Escriva";
   	ch.name    = TranslateString("","Pablo");
   	ch.lastname    = TranslateString("","Escriva");
   	ch.id        = "Pablo Escriva";
    	ch.model    = "9R_Purs";
    	ch.sex = "man";
    	ch.sound_type = "seaman";
	LAi_SetHP(ch, 200.0, 200.0);
	ch.questchar = true;
    	ch.location    = "BC_ForgerHouse";
    	ch.location.group = "goto";
    	ch.location.locator = "goto5";
    	ch.Dialog.Filename = "Pablo Escriva_dialog.c";
 	ch.greeting = "Gr_Francisco Cruz";
    	ch.nation = PIRATE;
    	ch.rank    = 5;
    	ch.reputation = "40";
    	ch.experience = "0";
    	ch.skill.Leadership = "1";
    	ch.skill.Fencing = "3";
    	ch.skill.Sailing = "1";
    	ch.skill.Accuracy = "1";
    	ch.skill.Cannons = "1";
    	ch.skill.Grappling = "1";
    	ch.skill.Repair = "1";
    	ch.skill.Defence = "2";
    	ch.skill.Commerce = "7";
    	ch.skill.Sneak = "7";
    	ch.money = "10";
	LAi_SetStayType(ch);
    	LAi_group_MoveCharacter(ch, "QC_CITIZENS");
	LAi_SetLoginTime(ch, 0.0, 24.0);
	AddGameCharacter(n, ch);
}
