void CreateIslaMuelleCharacters(ref n)
{
	object chobj;
	ref ch;

	makeref(ch, chobj);

			// Sylvie Bondies  француженка на исла муэле.
	ch.nation = FRANCE;
	ch.old.name = "Sylvie";
	ch.old.lastname = "Bondies";
	ch.name = TranslateString("","Sylvie");
	ch.lastname = TranslateString("","Bondies");
	ch.id		= "Sylvie Bondies";
	ch.model = "towngirl2";
	ch.sex = "woman";
	ch.sound_type = "female_citizen";
	ch.activity_begin = "0";
	ch.activity_end = "24";
	ch.location	= "house_of_Sylvie_Bondies";
	ch.location.group = "goto";
	ch.location.locator = "goto4";
	ch.Dialog.Filename = "Sylvie Bondies_dialog.c";
	ch.greeting = "Gr_Sylvie Bondies";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

// Zaid Murro - ESCORT VIGILA MENDES' SHIP + ZAID MURRO'S PROBLEM
	ch.nation = SPAIN;
	ch.old.name = "Zaid";
	ch.old.lastname = "Murro";
	ch.name = TranslateString("","Zaid");
	ch.lastname = TranslateString("","Murro");
	ch.id		= "Zaid Murro";
	ch.model = "bocman";
	ch.sex = "man";
	ch.sound_type = "seaman";
	ch.location	= "Muelle_port"; //NK reenable Zaid
	ch.location.group = "goto";
	ch.location.locator = "goto11";
	ch.Dialog.Filename = "Zaid Murro_dialog.c";
	ch.greeting = "Gr_zaid murro";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	ch.quest.end_escort = "0";
	ch.quest.bandits = "0";
	ch.quest_begin = "0";
	LAi_SetMerchantType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

			// Vigila Mendes.
	ch.nation = SPAIN;
	ch.old.name = "Vigila";
	ch.old.lastname = "Mendes";
	ch.name = TranslateString("","Vigila");
	ch.lastname = TranslateString("","Mendes");
	ch.id		= "Vigila Mendes";
	ch.model = "bocman4";
	ch.sex = "man";
	ch.sound_type = "seaman";
	GiveItem2Character(ch, "MerchantsBlade");
	ch.equip.blade = "MerchantsBlade";
	ch.location	= "Muelle_store"; //NK reenable Vigila
	ch.location.group = "goto";
	ch.location.locator = "locator5";
	ch.Dialog.Filename = "Vigila Mendes_dialog.c";
	ch.Ship.Name = "Juno";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	ch.Ship.Type = "Caravel1"; // PRS3
	// done by setbaseship - NK 05-04-09 ch.ship.cargo.goods.bombs = 1000;
	ch.Ship.Stopped = true;
	ch.quest.escort = "0";
	LAi_SetMerchantType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	ch.greeting = "Gr_vigila mendes";
	AddGameCharacter(n, ch);
	
			// IM Gov's wife by Catalina The Pirate
	ch.nation = SPAIN;
	ch.old.name = "Estrella";
	ch.old.lastname = "de Alencar";
	ch.name = TranslateString("","Estrella");
	ch.lastname = TranslateString("","de Alencar");
	ch.id		= "Estrella de Alencar";
	ch.model = "imgovwife";
	ch.sex = "woman";
	ch.activity_begin = "0";
	ch.activity_end = "24";
	ch.location	= "";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "Estrella De Alencar_dialog.c";
	ch.greeting = "Gr_Estrella";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	Lai_SetImmortal(ch, true);
	LAi_SetStayType(ch);    
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

		// Estrella Disguised -- added by CatalinaThePirate
	ch.old.name = "Estrella";
	ch.old.lastname = "Disguised";
	ch.name = TranslateString("","Estrella");
	ch.lastname = TranslateString("","Disguised");
	ch.id		= "Estrella Disguised";
	ch.model	= "Animistse";
	ch.sex = "man";
	ch.location	= "";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "Estrella Disguised_dialog.c";
	ch.nation = SPAIN;
	if (GetCurrentPeriod() >= PERIOD_GOLDEN_AGE_OF_PIRACY)
	{
		GiveItem2Character(ch, "pistol1");
		ch.equip.gun = "pistol1";
	}
	else
	{
		GiveItem2Character(ch, "pistol1a");
		ch.equip.gun = "pistol1a";
	}
     //JRH ammo mod -->
	if (ENABLE_AMMOMOD) {	// LDH change
		TakenItems(ch, "gunpowder", 1 + rand(2));
		TakenItems(ch, "pistolbullets", 1 + rand(2));
	}
     //JRH ammo mod <--
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.rank 	= 20;
	ch.reputation = "60";
	ch.experience = "250000";
	ch.skill.Leadership = "3";
	ch.skill.Fencing = "10";
	ch.skill.Sailing = "2";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "10";
	ch.money = "40000";
	Lai_SetImmortal(ch, true);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 160.0, 160.0);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	ch.greeting = "Gr_Estrella";
	AddGameCharacter(n, ch);
	
	//ПОРТ

			// Soldier.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "spain_soldier_01";
	ch.model = 1; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_port";
	ch.location.group = "goto";
	ch.location.locator = "goto12";
	ch.Dialog.Filename = "Isla Muelle soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier";
	AddGameCharacter(n, ch);

			// Soldier.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "spain_soldier_02";
	ch.model = 2; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_port";
	ch.location.group = "goto";
	ch.location.locator = "goto13";
	ch.Dialog.Filename = "Isla Muelle soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier";
	AddGameCharacter(n, ch);

			// Patrol.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "spain_patrol_01";
	ch.model = 4; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_port";
	ch.location.group = "goto";
	ch.location.locator = "character5";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier"; // was "Gr_Patrol"
	AddGameCharacter(n, ch);

			// Patrol.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "spain_patrol_02";
	ch.model = 5; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_port";
	ch.location.group = "goto";
	ch.location.locator = "goto10";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier"; // was "Gr_Patrol"
	AddGameCharacter(n, ch);

			// Port Administrator
	ch.nation = SPAIN;
	ch.old.name = "Citizen";
	ch.old.lastname = "";
	ch.name = TranslateString("","Citizen");
	ch.lastname = "";
	ch.id		= "spain_citizen_02";
	ch.model = "Mongol";
	ch.sex = "man";
	ch.sound_type = "seaman";
	ch.location	= "Muelle_port";
	ch.location.group = "goto";
	ch.location.locator = "goto6";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
	ch.nation = SPAIN;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

			// Uasco Mazinho.
	ch.nation = SPAIN;
	ch.old.name = "Uasco";
	ch.old.lastname = "Mazinho";
	ch.name = TranslateString("","Uasco");
	ch.lastname = TranslateString("","Mazinho");
	ch.id		= "Uasco Mazinho";
	ch.model = "man2";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.fanatic = "1";
	ch.church = "Muelle_church";
	ch.church.loc = "goto3";
	ch.back.location = "Muelle_port";
	ch.back.locator = "goto5";
	ch.location	= "Muelle_port";
	ch.location.group = "goto";
	ch.location.locator = "goto5";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

			// Rodrico Insulza.
	ch.nation = SPAIN;
	ch.old.name = "Rodrico";
	ch.old.lastname = "Insulza";
	ch.name = TranslateString("","Rodrico");
	ch.lastname = TranslateString("","Insulza");
	ch.id		= "Rodrico Insulza";
	ch.model = "fisherman";
	ch.sound_type = "seaman";
	ch.sex = "man";
	ch.location	= "Muelle_port";
	ch.location.group = "goto";
	ch.location.locator = "goto10";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

	// Isla Muella Tailor
	ch.old.name = "Jose";
	ch.old.lastname = "Gaspar";
	ch.name	= TranslateString("", "Jose");
	ch.lastname	= TranslateString("", "Gaspar");
	ch.id = "Jose Gaspar";
	ch.model = "korsar";
	ch.sex = "man";
	ch.location	= "Muelle_TailorsShop";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.IsTailor = true;
	ch.Dialog.Filename = "tailor_dialog.c";
 	ch.Dialog.Filename.Groupdialog = "tailor.c";
	ch.rank 	= 1;
	ch.nation = SPAIN;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "0";
	ch.skill.Fencing = "0";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "7";
	ch.skill.Sneak = "0";
	ch.money = "10";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	AddGameCharacter(n, ch);
	
	//church
			// Padre Domingues  церковник главный.
	ch.nation = SPAIN;
	ch.old.name = "Padre";
	ch.old.lastname = "Domingues";
	ch.name = TranslateString("","Padre");
	ch.lastname = TranslateString("","Domingues");
	ch.id		= "Padre Domingues";
	ch.model = "priest_spa";
	ch.sex = "man";
	ch.sound_type = "priest";
	ch.location	= "Muelle_church";
	ch.location.group = "goto";
	ch.location.locator = "goto11";
	ch.Dialog.Filename = "Padre Domingues_dialog.c";
	ch.Dialog.Filename.group = "church.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	ch.quest.escort = "0";
	LAi_SetPriestType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	ch.greeting = "Gr_Padre Domingues";
	LAi_SetLoginTime(ch, 0.0, 24.0);
	AddGameCharacter(n, ch);

			// second_spaniard_priest.
	ch.nation = SPAIN;
	ch.old.name = "Padre";
	ch.old.lastname = "Robano";
	ch.name = TranslateString("","Padre");
	ch.lastname = TranslateString("","Robano");
	ch.id		= "second_spaniard_priest";
	ch.model = "priest";
	ch.sex = "man";
	ch.sound_type = "priest";
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "goto11";
	ch.Dialog.Filename = "second_spaniard_priest_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	ch.quest.escort = "0";
	LAi_SetPriestType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	ch.greeting = "Gr_second_spaniard_priest";
	AddGameCharacter(n, ch);

	//residence
			// Christofor Manuel De Alencar  губернатор.
	ch.nation = SPAIN;
	ch.old.name = "Christofor";
	ch.old.middlename = "Manuel";
	ch.old.lastname = "De Alencar";
	ch.name = TranslateString("","Christofor");
	ch.lastname = TranslateString("","De Alencar");			//spell-checked by KAM: MAXIMUS - spell-checking must be placed into characters_names.txt
	ch.middlename = TranslateString("","Manuel");
	ch.id		= "Christofor Manuel De Alencar";
	ch.model = "Huber_Spa4_17"; // Thomas the Terror
	ch.sex = "man";
	ch.location	= "Muelle_Residence";
	ch.location.group = "sit";
	ch.location.locator = "Sit1";
	ch.Dialog.Filename = "Christofor Manuel De Alencar_dialog.c";
	ch.Dialog.Filename.GroupDialog = "governor.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	ch.quest.escort = "0";
	LAi_SetHuberType(ch);
	LAi_RemoveLoginTime(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	ch.greeting = "Gr_christofor manuel de alencar";
	AddGameCharacter(n, ch);

	//town01
			// Soldier.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "spain_soldier_03";
	ch.model = 2; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_town_01";
	ch.location.group = "goto";
	ch.location.locator = "goto9";
	ch.Dialog.Filename = "Isla Muelle soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier";
	AddGameCharacter(n, ch);

			// Soldier.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "spain_soldier_04";
	ch.model = 3; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_town_01";
	ch.location.group = "goto";
	ch.location.locator = "goto11";
	ch.Dialog.Filename = "Isla Muelle soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier";
	AddGameCharacter(n, ch);

			// Patrol.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "spain_patrol_03";
	ch.model = 6; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_town_01";
	ch.location.group = "goto";
	ch.location.locator = "goto23";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier"; // was "Gr_Patrol"
	AddGameCharacter(n, ch);

			// Patrol.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "spain_patrol_04";
	ch.model = 4; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_town_01";
	ch.location.group = "goto";
	ch.location.locator = "goto62";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier"; // was "Gr_Patrol"
	AddGameCharacter(n, ch);

			// Patrol.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "spain_patrol_05";
	ch.model = 3; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_town_01";
	ch.location.group = "goto";
	ch.location.locator = "goto82";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier"; // was "Gr_Patrol"
	AddGameCharacter(n, ch);

			// Patrol.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "spain_patrol_06";
	ch.model = 6; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_town_01";
	ch.location.group = "goto";
	ch.location.locator = "goto94";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier"; // was "Gr_Patrol"
	AddGameCharacter(n, ch);

			// Nunno Gats.
	ch.nation = SPAIN;
	ch.old.name = "Nunno";
	ch.old.lastname = "Gats";
	ch.name = TranslateString("","Nunno");
	ch.lastname = TranslateString("","Gats");
	ch.id		= "Nunno Gats";
	ch.model = "man1";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.fanatic = "1";
	ch.church = "Muelle_church";
	ch.church.loc = "goto4";
	ch.back.location = "Muelle_town_01";
	ch.back.locator = "goto33";
	ch.location	= "Muelle_town_01";
	ch.location.group = "goto";
	ch.location.locator = "goto33";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

			// Mergildo Deferr.
	ch.nation = SPAIN;
	ch.old.name = "Mergildo";
	ch.old.lastname = "Deferr";
	ch.name = TranslateString("","Mergildo");
	ch.lastname = TranslateString("","Deferr");
	ch.id		= "Mergildo Deferr";
	ch.model = "man2";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Muelle_town_01";
	ch.location.group = "goto";
	ch.location.locator = "goto21";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

			// Gisellus Aicega.
	ch.nation = SPAIN;
	ch.old.name = "Gisellus";
	ch.old.lastname = "Aicega";
	ch.name = TranslateString("","Gisellus");
	ch.lastname = TranslateString("","Aicega");
	ch.id		= "Gisellus Aicega";
	ch.model = "man3";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Muelle_town_01";
	ch.location.group = "goto";
	ch.location.locator = "goto79";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

			// Alonso Rodas.
	ch.nation = SPAIN;
	ch.old.name = "Alonso";
	ch.old.lastname = "Rodas";
	ch.name = TranslateString("","Alonso");
	ch.lastname = TranslateString("","Rodas");
	ch.id		= "Alonso Rodas";
	ch.model = "man4";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.fanatic = "1";
	ch.church = "Muelle_church";
	ch.church.loc = "goto5";
	ch.back.location = "Muelle_town_01";
	ch.back.locator = "goto62";
	ch.location	= "Muelle_town_01";
	ch.location.group = "goto";
	ch.location.locator = "goto62";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

			// Xabe Morayta.
	ch.nation = SPAIN;
	ch.old.name = "Xabe";
	ch.old.lastname = "Morayta";
	ch.name = TranslateString("","Xabe");
	ch.lastname = TranslateString("","Morayta");
	ch.id		= "Xabe Morayta";
	ch.model = "man5";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Muelle_town_01";
	ch.location.group = "goto";
	ch.location.locator = "goto87";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

			// Teodulfus Lastres.
	ch.nation = SPAIN;
	ch.old.name = "Teodulfus";
	ch.old.lastname = "Lastres";
	ch.name = TranslateString("","Teodulfus");
	ch.lastname = TranslateString("","Lastres");
	ch.id		= "Teodulfus Lastres";
	ch.model = "korsar";
	ch.sex = "man";
	ch.sound_type = "pirate";
	ch.fanatic = "1";
	ch.church = "Muelle_church";
	ch.church.loc = "goto6";
	ch.back.location = "Muelle_town_01";
	ch.back.locator = "goto73";
	ch.location	= "Muelle_town_01";
	ch.location.group = "goto";
	ch.location.locator = "goto73";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

			// Tasia Cobo.
	ch.nation = SPAIN;
	ch.old.name = "Tasia";
	ch.old.lastname = "Cobo";
	ch.name = TranslateString("","Tasia");
	ch.lastname = TranslateString("","Cobo");
	ch.id		= "Tasia Cobo";
	ch.model = "towngirl1_2"; // GR: was "towngirl1"
	ch.sex = "woman";
	ch.sound_type = "female_citizen";
	ch.location	= "Muelle_town_01";
	ch.location.group = "goto";
	ch.location.locator = "goto35";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_Woman_English citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

	//town02
			// Patrol.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "spain_patrol_07";
	ch.model = 3; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_town_02";
	ch.location.group = "goto";
	ch.location.locator = "goto8";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier"; // was "Gr_Patrol"
	AddGameCharacter(n, ch);

			// Patrol.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "spain_patrol_08";
	ch.model = 4; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_town_02";
	ch.location.group = "goto";
	ch.location.locator = "goto3";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier"; // was "Gr_Patrol"
	AddGameCharacter(n, ch);

			// Garci Crusellas.
	ch.nation = SPAIN;
	ch.old.name = "Garci";
	ch.old.lastname = "Crusellas";
	ch.name = TranslateString("","Garci");
	ch.lastname = TranslateString("","Crusellas");
	ch.id		= "Garci Crusellas";
	ch.model = "man1";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.fanatic = "1";
	ch.church = "Muelle_church";
	ch.church.loc = "goto7";
	ch.back.location = "Muelle_town_02";
	ch.back.locator = "goto33";
	ch.location	= "Muelle_town_02";
	ch.location.group = "goto";
	ch.location.locator = "goto2";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

			// Ermegildo Caminero.
	ch.nation = SPAIN;
	ch.old.name = "Ermegildo";
	ch.old.lastname = "Caminero";
	ch.name = TranslateString("","Ermegildo");
	ch.lastname = TranslateString("","Caminero");
	ch.id		= "Ermegildo Caminero";
	ch.model = "fatman";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Muelle_town_02";
	ch.location.group = "goto";
	ch.location.locator = "goto8";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
	ch.greeting = "Gr_Caminero";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

			// Necha Duany.
	ch.nation = SPAIN;
	ch.old.name = "Necha";
	ch.old.lastname = "Duany";
	ch.name = TranslateString("","Necha");
	ch.lastname = TranslateString("","Duany");
	ch.id		= "Necha Duany";
	ch.model = "towngirl2";
	ch.sex = "woman";
	ch.sound_type = "female_citizen";
	ch.location	= "Muelle_town_02";
	ch.location.group = "goto";
	ch.location.locator = "goto6";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_Woman_English citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

	//town03
			// Soldier.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "spain_soldier_05";
	ch.model = 2; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_town_03";
	ch.location.group = "goto";
	ch.location.locator = "character4";
	ch.Dialog.Filename = "Isla Muelle soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier";
	AddGameCharacter(n, ch);

			// Soldier.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "spain_soldier_06";
	ch.model = 4; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_town_03";
	ch.location.group = "goto";
	ch.location.locator = "character8";
	ch.Dialog.Filename = "Isla Muelle soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier";
	AddGameCharacter(n, ch);

			// Patrol.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "spain_patrol_09";
	ch.model = 2; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_town_03";
	ch.location.group = "goto";
	ch.location.locator = "goto13";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier"; // was "Gr_Patrol"
	AddGameCharacter(n, ch);

			// Patrol.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "spain_patrol_10";
	ch.model = 1; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_town_03";
	ch.location.group = "goto";
	ch.location.locator = "goto4";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier"; // was "Gr_Patrol"
	AddGameCharacter(n, ch);

			// Iuliano Enciso.
	ch.nation = SPAIN;
	ch.old.name = "Iuliano";
	ch.old.lastname = "Enciso";
	ch.name = TranslateString("","Iuliano");
	ch.lastname = TranslateString("","Enciso");
	ch.id		= "Iuliano Enciso";
	ch.model = "man5";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.fanatic = "1";
	ch.church = "Muelle_church";
	ch.church.loc = "goto8";
	ch.back.location = "Muelle_town_03";
	ch.back.locator = "goto13";
	ch.location	= "Muelle_town_03";
	ch.location.group = "goto";
	ch.location.locator = "goto13";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

			// Jose Isambero.
	ch.nation = SPAIN;
	ch.old.name = "Jose";
	ch.old.lastname = "Isambero";
	ch.name = TranslateString("","Jose");
	ch.lastname = TranslateString("","Isambero");
	ch.id		= "Jose Isambero";
	ch.model = "man1";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Muelle_town_03";
	ch.location.group = "goto";
	ch.location.locator = "goto14";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

			// Pepillo Lazaro.
	ch.nation = SPAIN;
	ch.old.name = "Pepillo";
	ch.old.lastname = "Lazaro";
	ch.name = TranslateString("","Pepillo");
	ch.lastname = TranslateString("","Lazaro");
	ch.id		= "Pepillo Lazaro";
	ch.model = "corsair1_2";
	ch.sex = "man";
	ch.sound_type = "pirate";
	ch.fanatic = "1";
	ch.church = "Muelle_church";
	ch.church.loc = "goto9";
	ch.back.location = "Muelle_town_03";
	ch.back.locator = "goto12";
	ch.location	= "Muelle_town_03";
	ch.location.group = "goto";
	ch.location.locator = "goto12";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

			// Sabiano Martinez.
	ch.nation = SPAIN;
	ch.old.name = "Sabiano";
	ch.old.lastname = "Martinez";
	ch.name = TranslateString("","Sabiano");
	ch.lastname = TranslateString("","Martinez");
	ch.id		= "Sabiano Martinez";
	ch.model = "man5";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Muelle_town_03";
	ch.location.group = "goto";
	ch.location.locator = "goto";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

			// Obecco Hidalgo.
	ch.nation = SPAIN;
	ch.old.name = "Obecco";
	ch.old.lastname = "Hidalgo";
	ch.name = TranslateString("","Obecco");
	ch.lastname = TranslateString("","Hidalgo");
	ch.id		= "Obecco Hidalgo";
	ch.model = "corsair2";
	ch.sex = "man";
	ch.sound_type = "pirate";
	ch.location	= "Muelle_town_03";
	ch.location.group = "goto";
	ch.location.locator = "goto2";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

	//town04
			// Soldier.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "spain_soldier_07";
	ch.model = 5; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_town_04";
	ch.location.group = "goto";
	ch.location.locator = "goto1";
	ch.Dialog.Filename = "Isla Muelle soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier";
	AddGameCharacter(n, ch);

			// Soldier.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "spain_soldier_08";
	ch.model = 5; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_town_04";
	ch.location.group = "goto";
	ch.location.locator = "goto40";
	ch.Dialog.Filename = "Isla Muelle soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier";
	AddGameCharacter(n, ch);

			// Soldier.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "spain_soldier_09";
	ch.model = 3; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_town_04";
	ch.location.group = "goto";
	ch.location.locator = "goto37";
	ch.Dialog.Filename = "Isla Muelle soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier";
	AddGameCharacter(n, ch);

			// Soldier.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "spain_soldier_10";
	ch.model = 1; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_town_04";
	ch.location.group = "goto";
	ch.location.locator = "goto25";
	ch.Dialog.Filename = "Isla Muelle soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier";
	AddGameCharacter(n, ch);

			// Patrol.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "spain_patrol_11";
	ch.model = 4; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_town_04";
	ch.location.group = "goto";
	ch.location.locator = "goto23";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier"; // was "Gr_Patrol"
	AddGameCharacter(n, ch);

			// Patrol.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name = "";
	ch.lastname = "";
	ch.id		= "spain_patrol_12";
	ch.model = 6; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, false);
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_town_04";
	ch.location.group = "goto";
	ch.location.locator = "goto13";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier"; // was "Gr_Patrol"
	AddGameCharacter(n, ch);

			// Vito Ordonez.
	ch.nation = SPAIN;
	ch.old.name = "Vito";
	ch.old.lastname = "Ordonez";
	ch.name = TranslateString("","Vito");
	ch.lastname = TranslateString("","Ordonez");
	ch.id		= "Vito Ordonez";
	ch.model = "man3";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.fanatic = "1";
	ch.church = "Muelle_church";
	ch.church.loc = "goto10";
	ch.back.location = "Muelle_town_04";
	ch.back.locator = "goto4";
	ch.location	= "Muelle_town_04";
	ch.location.group = "goto";
	ch.location.locator = "goto4";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

			// Velasconi Silloniz.
	ch.nation = SPAIN;
	ch.old.name = "Velasconi";
	ch.old.lastname = "Silloniz";
	ch.name = TranslateString("","Velasconi");
	ch.lastname = TranslateString("","Silloniz");
	ch.id		= "Velasconi Silloniz";
	ch.model = "man2";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Muelle_town_04";
	ch.location.group = "goto";
	ch.location.locator = "goto10";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

			// Andemio De Caxias.
	ch.nation = SPAIN;
	ch.old.name = "Andemio";
	ch.old.lastname = "De Caxias";
	ch.name = TranslateString("","Andemio");
	ch.lastname = TranslateString("","De Caxias");
	ch.id		= "Andemio De Caxias";
	ch.model = "man1_1";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Muelle_town_04";
	ch.location.group = "goto";
	ch.location.locator = "goto15";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

			// Isidro Edinho.
	ch.nation = SPAIN;
	ch.old.name = "Isidro";
	ch.old.lastname = "Edinho";
	ch.name = TranslateString("","Isidro");
	ch.lastname = TranslateString("","Edinho");
	ch.id		= "Isidro Edinho";
	ch.model = "corsair1";
	ch.sex = "man";
	ch.sound_type = "pirate";
	ch.location	= "Muelle_town_04";
	ch.location.group = "goto";
	ch.location.locator = "goto28";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

			// Francisco Cervano.
	ch.nation = SPAIN;
	ch.old.name = "Francisco";
	ch.old.lastname = "Cervano";
	ch.name = TranslateString("","Francisco");
	ch.lastname = TranslateString("","Cervano");
	ch.id		= "Francisco Cervano";
	ch.model = "fisherman";
	ch.sex = "man";
	ch.sound_type = "seaman";
	ch.location	= "Muelle_town_04";
	ch.location.group = "goto";
	ch.location.locator = "goto23";
	ch.Dialog.Filename = "Isla Muelle citizen_dialog.c";
	ch.greeting = "Gr_isla muelle citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);

// --> RobC/Alan_Smithee Blacksmith mod
if (ENABLE_WEAPONSMOD)
{
	//  Blacksmith 
	ch.old.name = "Robierto";
	ch.old.lastname = "Cabellodoferro";
	ch.name = TranslateString("","Robierto");
	ch.lastname = TranslateString("","Cabellodoferro");
	ch.id		= "Muelle_blacksmith";
	ch.model	= "blacksmith4";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "IM_blacksmith";
	ch.location.group = "goto";
	ch.location.locator = "goto1";
	ch.Dialog.Filename = "Blacksmith2_dialog.c";
	ch.Dialog.Filename.Groupdialog = "Blacksmith_fetch.c";
	ch.greeting = "Gr_zaid murro";
	ch.nation = SPAIN;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetStayType(ch); // LDH: Keep him from walking around all the time
	LAi_group_MoveCharacter(ch, "SPAIN_CITIZENS");
	AddGameCharacter(n, ch);
}
// <-- RobC/Alan_Smithee Blacksmith mod

//////////////////////////////////// AGUADILLA SOLDIERS ////////////////////////////////////

			// Soldier.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname = "";
	ch.id		= "aguadilla_soldier_01";
	ch.model = 1; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_shore_03";
	ch.location.group = "goto";
	ch.location.locator = "goto70";
	ch.Dialog.Filename = "Isla Muelle soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier";
	AddGameCharacter(n, ch);
	
			// Soldier.
	ch.nation = SPAIN;
	ch.old.name = "";
	ch.old.lastname = "";
	ch.name 	= "";
	ch.lastname = "";
	ch.id		= "aguadilla_soldier_02";
	ch.model = 2; // PB
	ch.sex = "man";
	ch.sound_type = "soldier";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Muelle_shore_03";
	ch.location.group = "goto";
	ch.location.locator = "goto72";
	ch.Dialog.Filename = "Isla Muelle soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SPAIN_SOLDIERS");
	ch.greeting = "Gr_isla muelle soldier";
	AddGameCharacter(n, ch);

}
