void CreateTurksCharacters(ref n)
{
	object chobj;
	ref ch;
	makeref(ch, chobj);

	// governor
	ch.old.name = "Dante";
	ch.old.lastname = "Siciliano";
	ch.name = TranslateString("", "Dante");
	ch.middlename = TranslateString("", "Siciliano");
	ch.lastname = TranslateString("", "Shaw");
	ch.id		= "Dante Siciliano";
	ch.model = "albermal";
	ch.sex = "man";
	ch.location	= "Turks_townhall";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.Dialog.Filename = "Nathan Kell (Gov)_dialog.c";
	ch.Dialog.Filename.GroupDialog = "governor.c";
	ch.nation = PIRATE;
	ch.rank 	= 1;
	ch.reputation = "60";
	ch.experience = "0";
	ch.skill.Leadership = "6";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "5";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_RemoveLoginTime(ch);
	LAi_SetHuberType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	ch.greeting = "Gr_Robert Christopher Silehard";
	AddGameCharacter(n, ch);

// Lighthouse:
	ch.old.name = "Robert";
	ch.old.lastname = "LeNoir";
	ch.name 	= TranslateString("", "Robert");
	ch.lastname = TranslateString("", "LeNoir");
	ch.id		= "Robert LeNoir";
	ch.model	= "pirat3";
	ch.headmodel = "h_pirat3";
	ch.sound_type = "pirate";
	ch.sex = "man";
	GiveItem2Character(ch, "blade24");
	ch.equip.blade = "blade24";
	GiveItem2Character(ch, "pistol5");
	ch.equip.gun = "pistol5";
	ch.location	= "Turks_House1_Inside";
	ch.location.group = "goto";
	ch.location.locator = "goto3";
	ch.Dialog.Filename = "Robert LeNoir_dialog.c";
	ch.nation = PIRATE;
	ch.rank 	= 50;
	ch.reputation = "25";
	ch.experience = "30000"		//chr.experience;
	ch.skill.Leadership = "9";
	ch.skill.Fencing = "10";
	ch.skill.Sailing = "7";
	ch.skill.Accuracy = "7";
	ch.skill.Cannons = "7";
	ch.skill.Grappling = "8";
	ch.skill.Repair = "6";
	ch.skill.Defence = "8";
	ch.skill.Commerce = "4";
	ch.skill.Sneak = "6";
	ch.money = "500";
	ch.perks.list.BasicDefence = true;
	ch.perks.list.AdvancedDefence = true;
	ch.perks.list.SwordplayProfessional = true;
	ch.perks.list.CriticalHit = true;
	ch.perks.list.Gunman = true;
	ch.perks.list.ProfessionalGunman = true;
	ch.perks.list.Rush = true;
	ch.perks.list.IronWill = true;
	ch.perks.list.FastReload = true;
	ch.perks.list.HullDamageUp = true;
	ch.perks.list.CrewDamageUp = true;
	ch.perks.list.BasicDamageControl = true;
	ch.perks.list.Rigging = true;
	ch.perks.list.BasicDefence = true;
	ch.perks.list.AdvancedDefence = true;
	ch.perks.list.ShipSpeedUp = true;
	ch.perks.list.LightRepair = true;
	ch.perks.list.SharedExperience = true;
	ch.perks.list.BasicCommerce = true;
	ch.Ship.Name = "Trompe Mort";
	ch.Ship.Type = "Shnyava1";
	// ch.Ship.Cannons.Type = CANNON_TYPE_CULVERINE_LBS24;
	ch.ship.cargo.goods.BALLS = 1000;
	ch.ship.cargo.goods.GRAPES = 500;
	ch.ship.cargo.goods.KNIPPELS = 500;
	// ch.ship.cargo.goods.bombs = 1000;
	ch.Ship.Stopped = true;
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetWarriorType(ch);
	LAi_warrior_DialogEnable(ch, true);
	//LAi_SetSitType(ch);
	LAi_SetHP(ch, 2000.0, 2000.0);
	LAi_NoRebirthEnable(ch);
	ch.greeting = "Gr_jean filaut";
	LAi_group_MoveCharacter(ch, "QC_CITIZENS");
	AddGameCharacter(n, ch);

// Grand Turk : Town part1

		//  Bill Barns -- killer
	ch.old.name = "Bill";
	ch.old.lastname = "Barns";
	ch.name 	= TranslateString("", "Bill");
	ch.lastname = TranslateString("", "Barns");
	ch.id		= "Bill Barns";
	ch.model	= "killer";
	ch.sex = "man";
	ch.sound_type = "soldier";
	GiveItem2Character(ch, "blade24");
	ch.equip.blade = "blade24";
	if (GetCurrentPeriod() >= PERIOD_GOLDEN_AGE_OF_PIRACY)
	{
		GiveItem2Character(ch, "pistol7");
		ch.equip.gun = "pistol7";
	}
	else
	{
		GiveItem2Character(ch, "pistol7a");
		ch.equip.gun = "pistol7a";
	}
	ch.location	= "Turks_port";			//JRH: new Turks
	ch.location.group = "goto";
	ch.location.locator = "goto6";
	ch.Dialog.Filename = "Turks Guards_dialog.c";
	ch.greeting = "Gr_QC Citizen";
	ch.nation = PIRATE;
	ch.rank 	= 30;
	ch.reputation = "None";
	ch.experience = "1500";
	ch.skill.Leadership = "2";
	ch.skill.Fencing = "8";
	ch.skill.Sailing = "3";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "6";
	ch.skill.Grappling = "3";
	ch.skill.Repair = "2";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "6";
	ch.money = "1";
	LAi_SetCivilianGuardianType(ch); // KK
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 800.0, 800.0);
	LAi_group_MoveCharacter(ch, "QC_SOLDIERS");
	AddGameCharacter(n, ch);

// Grand Turk : Town part2

	// Turks Tailor
	ch.old.name = "Samuel";
	ch.old.lastname = "Pugh";
	ch.name	= TranslateString("", "Samuel");
	ch.lastname	= TranslateString("", "Pugh");
	ch.id = "Samuel Pugh";
	ch.model = "bocman8";
	ch.sex = "man";
	ch.location	= "Turks_TailorsShop";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.IsTailor = true;
	ch.Dialog.Filename = "tailor_dialog.c";
 	ch.Dialog.Filename.Groupdialog = "tailor.c";
	ch.rank 	= 1;
	ch.nation = PIRATE;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "0";
	ch.skill.Fencing = "0";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "4";
	ch.skill.Sneak = "0";
	ch.money = "10";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	AddGameCharacter(n, ch);

// --> RobC/Alan_Smithee Blacksmith mod
if (ENABLE_WEAPONSMOD)
{
			//Turks Gunsmith
	ch.old.name = "Lorenza";
	ch.old.lastname = "Trevisano";
	ch.name = TranslateString("", "Lorenza");
	ch.lastname = TranslateString("", "Trevisano");
	ch.id		= "Turks_gunsmith";
	ch.model	= "33_Affrica"; // Estharos Change from blacksmith1 to this model
	ch.sound_type = "worker";
	ch.sex = "woman";
	ch.location	= "Turks_blacksmith";
	ch.location.group = "goto";
	ch.location.locator = "goto1";
	ch.Dialog.Filename = "Gunsmith_dialog.c";
	ch.Dialog.Filename.Groupdialog = "Gunsmith_fetch.c";
	ch.greeting = "Gr_Pirate_f";	// GR: was "Gr_Pirate" which does not exist, and anyway the character is female
	ch.nation = PIRATE; // TIH was missing Nov7'06
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetStayType(ch); // LDH: Keep him from walking around all the time
	LAi_group_MoveCharacter(ch, "TURKS_CITIZENS");
	AddGameCharacter(n, ch);
}
// <-- RobC/Alan_Smithee Blacksmith mod

// Levis, Librarian:
	ch.old.name = "Cornelius";
	ch.old.lastname = "Fisherman";
	ch.name = TranslateString("", "Cornelius");
	ch.lastname = TranslateString("", "Fisherman");
	ch.id		= "Librarian_Turks";
	ch.model	= "9R_Purs";
	ch.headmodel = "9R_Purs";
	ch.sound_type = "seaman";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Turks_library";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.Dialog.Filename = "Librarian.c";
	ch.nation = PIRATE;
	ch.rank 	= 15;
	ch.reputation = "None";
	ch.experience = "15";
	ch.skill.Leadership = "8";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "3";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "8";
	ch.skill.Commerce = "10";
	ch.skill.Sneak = "7";
	ch.money = "1500";
	ch.quest.sex = 0;
	ch.sex.time = 0;
	ch.questchar = true;
	//LAi_SetStayType(ch);
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 60.0, 60.0);
	LAi_group_MoveCharacter(ch, "TURKS_CITIZENS");
	LAi_SetSitType(ch);
	Lai_setImmortal(ch, true);
	ch.greeting = "Gr_Everard Gordon";
	AddGameCharacter(n, ch);

//End Librarian

// Pirate Lair :


	ch.old.name = "Carpenter";
	ch.old.lastname = "";
	ch.name 	= TranslateString("", "Carpenter");
	ch.lastname = "";
	ch.id		= "Carpenter";
	ch.model	= "bocman3";
	ch.headmodel = "h_bocman3";
	ch.sound_type = "seaman";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Turks_Cavern_01";
	ch.location.group = "goto";
	ch.location.locator = "goto36";
	ch.Dialog.Filename = "Carpenter.c";
	ch.nation = PIRATE;
	ch.rank 	= 10;
	ch.reputation = "None";
	ch.experience = "15";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "8";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "7";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "8";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "7";
	ch.money = "1";
	ch.quest.sex = 0;
	ch.sex.time = 0;
	//LAi_SetStayType(ch);
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 60.0, 60.0);
	LAi_group_MoveCharacter(ch, LAI_GROUP_PLAYER);
	LAi_SetSitType(ch);
	Lai_setImmortal(ch, true);
	ch.greeting = "Gr_Everard Gordon";
	AddGameCharacter(n, ch);


	ch.old.name = "Crewmember";
	ch.old.lastname = "";
	ch.name 	= TranslateString("", "Crewmember");
	ch.lastname = "";
	ch.id		= "Crew_member_01";
	ch.model	= "sailor7";
	ch.headmodel = "h_sailor7";
	ch.sound_type = "seaman";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Turks_Cavern_01";
	ch.location.group = "goto";
	ch.location.locator = "goto32";
	ch.Dialog.Filename = "Lair_crewmember.c";
	ch.nation = PIRATE;
	ch.rank 	= 10;
	ch.reputation = "None";
	ch.experience = "15";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "8";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "7";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "8";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "7";
	ch.money = "1";
	ch.quest.sex = 0;
	ch.sex.time = 0;
	//LAi_SetStayType(ch);
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 60.0, 60.0);
	LAi_group_MoveCharacter(ch, LAI_GROUP_PLAYER);
	LAi_SetSitType(ch);
	Lai_setImmortal(ch, true);
	ch.greeting = "Gr_engcrew member1";
	AddGameCharacter(n, ch);


	ch.old.name = "Crewmember";
	ch.old.lastname = "";
	ch.name 	= TranslateString("", "Crewmember");
	ch.lastname = "";
	ch.id		= "Crew_member_02";
	ch.model	= "sailor1";
	ch.headmodel = "h_sailor1";
	ch.sound_type = "seaman";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Turks_Cavern_01";
	ch.location.group = "goto";
	ch.location.locator = "goto31";
	ch.Dialog.Filename = "Lair_crewmember.c";
	ch.nation = PIRATE;
	ch.rank 	= 10;
	ch.reputation = "None";
	ch.experience = "15";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "8";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "7";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "8";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "7";
	ch.money = "1";
	ch.quest.sex = 0;
	ch.sex.time = 0;
	//LAi_SetStayType(ch);
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 60.0, 60.0);
	LAi_group_MoveCharacter(ch, LAI_GROUP_PLAYER);
	LAi_SetSitType(ch);
	Lai_setImmortal(ch, true);
	ch.greeting = "Gr_frcrew member";
	AddGameCharacter(n, ch);


	ch.old.name = "Crewmember";
	ch.old.lastname = "";
	ch.name 	= TranslateString("", "Crewmember");
	ch.lastname = "";
	ch.id		= "Crew_member_03";
	ch.model	= "sailor6";
	ch.headmodel = "h_sailor6";
	ch.sound_type = "seaman";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	GiveItem2Character(ch, "pistol5");
	ch.equip.gun = "pistol5";
	ch.location	= "Turks_Cavern_01";
	ch.location.group = "goto";
	ch.location.locator = "goto2";
	ch.Dialog.Filename = "Lair_crewmember.c";
	ch.nation = PIRATE;
	ch.rank 	= 10;
	ch.reputation = "None";
	ch.experience = "15";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "8";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "7";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "8";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "7";
	ch.money = "1";
	ch.quest.sex = 0;
	ch.sex.time = 0;
	//LAi_SetStayType(ch);
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 60.0, 60.0);
	LAi_group_MoveCharacter(ch, LAI_GROUP_PLAYER);
	Lai_setImmortal(ch, true);
	ch.greeting = "Gr_frcrew member2";
	AddGameCharacter(n, ch);


	ch.old.name = "Crewmember";
	ch.old.lastname = "";
	ch.name 	= TranslateString("", "Crewmember");
	ch.lastname = "";
	ch.id		= "Crew_member_04";
	ch.model	= "bocman";
	ch.headmodel = "h_bocman";
	ch.sound_type = "seaman";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	GiveItem2Character(ch, "pistol5");
	ch.equip.gun = "pistol5";
	ch.location	= "Turks_Cavern_01";
	ch.location.group = "goto";
	ch.location.locator = "goto30";
	ch.Dialog.Filename = "Lair_crewmember.c";
	ch.nation = PIRATE;
	ch.rank 	= 10;
	ch.reputation = "None";
	ch.experience = "15";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "8";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "7";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "8";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "7";
	ch.money = "1";
	ch.quest.sex = 0;
	ch.sex.time = 0;
	//LAi_SetStayType(ch);
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 60.0, 60.0);
	LAi_group_MoveCharacter(ch, LAI_GROUP_PLAYER);
	Lai_setImmortal(ch, true);
	LAi_SetSitType(ch);
	ch.greeting = "Gr_spacrew member1";
	AddGameCharacter(n, ch);


	ch.old.name = "Crewmember";
	ch.old.lastname = "";
	ch.name 	= TranslateString("", "Crewmember");
	ch.lastname = "";
	ch.id		= "Crew_member_05";
	ch.model	= "Black_corsair";
	ch.headmodel = "h_Black_corsair";
	ch.sound_type = "seaman";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	GiveItem2Character(ch, "pistol5");
	ch.equip.gun = "pistol5";
	ch.location	= "Turks_Cavern_01";
	ch.location.group = "goto";
	ch.location.locator = "goto29";
	ch.Dialog.Filename = "Lair_crewmember.c";
	ch.nation = PIRATE;
	ch.rank 	= 10;
	ch.reputation = "None";
	ch.experience = "15";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "8";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "7";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "8";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "7";
	ch.money = "1";
	ch.quest.sex = 0;
	ch.sex.time = 0;
	//LAi_SetStayType(ch);
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 60.0, 60.0);
	LAi_group_MoveCharacter(ch, LAI_GROUP_PLAYER);
	Lai_setImmortal(ch, true);
	LAi_SetSitType(ch);
	ch.greeting = "Gr_engcrew member1";
	AddGameCharacter(n, ch);


	ch.old.name = "Crewmember";
	ch.old.lastname = "";
	ch.name 	= TranslateString("", "Crewmember");
	ch.lastname = "";
	ch.id		= "Crew_member_06";
	ch.model	= "Chameleon";
	ch.headmodel = "h_Chameleon";
	ch.sound_type = "seaman";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	GiveItem2Character(ch, "pistol5");
	ch.equip.gun = "pistol5";
	ch.location	= "Turks_Cavern_01";
	ch.location.group = "goto";
	ch.location.locator = "goto10";
	ch.Dialog.Filename = "Lair_crewmember.c";
	ch.nation = PIRATE;
	ch.rank 	= 10;
	ch.reputation = "None";
	ch.experience = "15";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "8";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "7";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "8";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "7";
	ch.money = "1";
	ch.quest.sex = 0;
	ch.sex.time = 0;
	//LAi_SetStayType(ch);
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 60.0, 60.0);
	LAi_group_MoveCharacter(ch, LAI_GROUP_PLAYER);
	Lai_setImmortal(ch, true);
	LAi_SetSitType(ch);
	ch.greeting = "Gr_engcrew member1";
	AddGameCharacter(n, ch);


	ch.old.name = "Crewmember";
	ch.old.lastname = "";
	ch.name 	= TranslateString("", "Crewmember");
	ch.lastname = "";
	ch.id		= "Crew_member_07";
	ch.model	= "50evl2in";
	ch.headmodel = "h_50evl2in";
	ch.sound_type = "seaman";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	GiveItem2Character(ch, "pistol5");
	ch.equip.gun = "pistol5";
	ch.location	= "Turks_Cavern_01";
	ch.location.group = "goto";
	ch.location.locator = "goto11";
	ch.Dialog.Filename = "Lair_crewmember3.c";
	ch.nation = PIRATE;
	ch.rank 	= 10;
	ch.reputation = "None";
	ch.experience = "15";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "8";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "7";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "8";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "7";
	ch.money = "1";
	ch.quest.sex = 0;
	ch.sex.time = 0;
	//LAi_SetStayType(ch);
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 60.0, 60.0);
	LAi_group_MoveCharacter(ch, LAI_GROUP_PLAYER);
	Lai_setImmortal(ch, true);
	//LAi_SetSitType(ch);
	ch.greeting = "Gr_holcrew member1";
	AddGameCharacter(n, ch);

	ch.old.name = "Crewmember";
	ch.old.lastname = "";
	ch.name 	= TranslateString("", "Crewmember");
	ch.lastname = "";
	ch.id		= "Crew_member_08";
	ch.model	= "Bocman4";
	ch.headmodel = "h_Bocman4";
	ch.sound_type = "seaman";
	ch.sex = "man";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	GiveItem2Character(ch, "pistol5");
	ch.equip.gun = "pistol5";
	ch.location	= "Turks_Cavern_01";
	ch.location.group = "goto";
	ch.location.locator = "goto13";
	ch.Dialog.Filename = "Lair_crewmember.c";
	ch.nation = PIRATE;
	ch.rank 	= 10;
	ch.reputation = "None";
	ch.experience = "15";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "8";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "7";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "8";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "7";
	ch.money = "1";
	ch.quest.sex = 0;
	ch.sex.time = 0;
	//LAi_SetStayType(ch);
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 60.0, 60.0);
	LAi_group_MoveCharacter(ch, LAI_GROUP_PLAYER);
	Lai_setImmortal(ch, true);
	//LAi_SetSitType(ch);
	ch.greeting = "Gr_frcrew member3";
	AddGameCharacter(n, ch);
//JRH: new Turks

// Town, citizens
    ch.old.name = "Justin";
    ch.old.lastname = "Boogard";
    ch.name     = TranslateString("", "Justin");
    ch.lastname     = TranslateString("", "Boogard");
    ch.id        = "Justin Boogard";
    ch.model    = "bocman1";
    ch.sex = "man";
    ch.sound_type = "seaman";
    ch.location    = "Turks_port";			//JRH: new Turks
    ch.location.group = "goto";
    ch.location.locator = "goto3";
    ch.Dialog.Filename = "GrandTurks citizen_dialog.c";
    ch.greeting = "Gr_Oxbay Citizen";
    ch.quest.area = "Turks";
    ch.nation = PIRATE;
    ch.rank     = 1;
    ch.reputation = "None";
    ch.experience = "0";
    ch.skill.Leadership = "1";
    ch.skill.Fencing = "1";
    ch.skill.Sailing = "1";
    ch.skill.Accuracy = "1";
    ch.skill.Cannons = "1";
    ch.skill.Grappling = "1";
    ch.skill.Repair = "1";
    ch.skill.Defence = "1";
    ch.skill.Commerce = "1";
    ch.skill.Sneak = "1";
    ch.money = "10";
    LAi_SetCitizenType(ch);
    LAi_group_MoveCharacter(ch, "QC_CITIZENS");
    AddGameCharacter(n, ch);

    ch.old.name = "Jo";
    ch.old.lastname = "Peixe";
    ch.name     = TranslateString("", "Jo");
    ch.lastname     = TranslateString("", "Peixe");
    ch.id        = "Jo Peixe";
    ch.model    = "bocman5";
    ch.sex = "man";
    ch.sound_type = "seaman";
    ch.location    = "Turks_port";			//JRH: new Turks
    ch.location.group = "goto";
    ch.location.locator = "goto15";
    ch.Dialog.Filename = "GrandTurks citizen_dialog.c";
    ch.greeting = "Gr_Oxbay Citizen";
    ch.quest.area = "Turks";
    ch.nation = PIRATE;
    ch.rank     = 1;
    ch.reputation = "None";
    ch.experience = "0";
    ch.skill.Leadership = "1";
    ch.skill.Fencing = "1";
    ch.skill.Sailing = "1";
    ch.skill.Accuracy = "1";
    ch.skill.Cannons = "1";
    ch.skill.Grappling = "1";
    ch.skill.Repair = "1";
    ch.skill.Defence = "1";
    ch.skill.Commerce = "1";
    ch.skill.Sneak = "1";
    ch.money = "10";
    LAi_SetCitizenType(ch);
    LAi_group_MoveCharacter(ch, "QC_CITIZENS");
    AddGameCharacter(n, ch);

    ch.old.name = "Francisco";
    ch.old.lastname = "Valderrama";
    ch.name     = TranslateString("", "Francisco");
    ch.lastname     = TranslateString("", "Valderrama");
    ch.id        = "Francisco Valderrama";
    ch.model    = "corsair3";
    ch.sex = "man";
    ch.sound_type = "seaman";
    ch.location    = "Turks_port";			//JRH: new Turks
    ch.location.group = "goto";
    ch.location.locator = "goto21";
    ch.Dialog.Filename = "GrandTurks citizen_dialog.c";
    ch.greeting = "Gr_Oxbay Citizen";
    ch.quest.area = "Turks";
    ch.nation = PIRATE;
    ch.rank     = 1;
    ch.reputation = "None";
    ch.experience = "0";
    ch.skill.Leadership = "1";
    ch.skill.Fencing = "1";
    ch.skill.Sailing = "1";
    ch.skill.Accuracy = "1";
    ch.skill.Cannons = "1";
    ch.skill.Grappling = "1";
    ch.skill.Repair = "1";
    ch.skill.Defence = "1";
    ch.skill.Commerce = "1";
    ch.skill.Sneak = "1";
    ch.money = "10";
    LAi_SetCitizenType(ch);
    LAi_group_MoveCharacter(ch, "QC_CITIZENS");
    AddGameCharacter(n, ch);

    ch.old.name = "Christine";
    ch.old.lastname = "Hoppe";
    ch.name     = TranslateString("", "Christine");
    ch.lastname     = TranslateString("", "Hoppe");
    ch.id        = "Christine Hoppe";
    ch.model    = "towngirl2";
    ch.sex = "woman";
    ch.sound_type = "female_citizen";
    ch.location    = "Turks_port";			//JRH: new Turks	
    ch.location.group = "goto";
    ch.location.locator = "goto25";
    ch.Dialog.Filename = "GrandTurks citizen_dialog.c";
    ch.greeting = "Gr_Woman_English Citizen";
    ch.quest.area = "Turks";
    ch.nation = PIRATE;
    ch.rank     = 1;
    ch.reputation = "None";
    ch.experience = "0";
    ch.skill.Leadership = "1";
    ch.skill.Fencing = "1";
    ch.skill.Sailing = "1";
    ch.skill.Accuracy = "1";
    ch.skill.Cannons = "1";
    ch.skill.Grappling = "1";
    ch.skill.Repair = "1";
    ch.skill.Defence = "1";
    ch.skill.Commerce = "1";
    ch.skill.Sneak = "1";
    ch.money = "10";
    LAi_SetCitizenType(ch);
    LAi_group_MoveCharacter(ch, "QC_CITIZENS");
    AddGameCharacter(n, ch);

//JRH -->
		// Admiral of the Coast 21
	ch.name = TranslateString("", "Admiral");
	ch.lastname = "";
	ch.id		= "CB21";
	ch.model = "Sk3Pri";
	ch.sex = "man";
	//ch.sound_type = "pirate";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Turks_church";
	ch.location.group = "barmen";
	ch.location.locator = "bar1";
	ch.Dialog.Filename = "CoastbrotherTurks_dialog.c";
	ch.nation = PIRATE;
	ch.Flags.Pirate = 3;
	ch.Flags.Pirate.texture = 0;
	ch.rank 	= 3;
	ch.reputation = "20";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	Lai_setImmortal(ch, true);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 100.0, 100.0);
	ch.questchar = true;//MAXIMUS: identifier for captives
	AddGameCharacter(n, ch);

				// Brother of the Coast 2
	ch.name = TranslateString("", "Coastbrother");
	ch.lastname = "";
	ch.id		= "CB2";
	ch.model = "Animist4A";
	ch.sex = "man";
	//ch.sound_type = "pirate";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Turks_church";
	ch.location.group = "goto";
	ch.location.locator = "monk1";	
	ch.Dialog.Filename = "CoastbrotherTurks_dialog.c";
	ch.nation = PIRATE;
	ch.Flags.Pirate = 2;
	ch.Flags.Pirate.texture = 0;
	ch.rank 	= 3;
	ch.reputation = "20";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	Lai_setImmortal(ch, true);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 40.0, 40.0);
	ch.questchar = true;//MAXIMUS: identifier for captives
	AddGameCharacter(n, ch);

				// Brother of the Coast 3
	ch.name = TranslateString("", "Coastbrother");
	ch.lastname = "";
	ch.id		= "CB3";
	ch.model = "Animist4B";
	ch.sex = "man";
	//ch.sound_type = "pirate";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Turks_church";
	ch.location.group = "goto";
	ch.location.locator = "monk2";	
	ch.Dialog.Filename = "CoastbrotherTurks_dialog.c";
	ch.nation = PIRATE;
	ch.Flags.Pirate = 2;
	ch.Flags.Pirate.texture = 0;
	ch.rank 	= 3;
	ch.reputation = "20";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	Lai_setImmortal(ch, true);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 40.0, 40.0);
	ch.questchar = true;//MAXIMUS: identifier for captives
	AddGameCharacter(n, ch);

				// Brother of the Coast 4
	ch.name = TranslateString("", "Coastbrother");
	ch.lastname = "";
	ch.id		= "CB4";
	ch.model = "Animist4C";
	ch.sex = "man";
	//ch.sound_type = "pirate";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Turks_church";
	ch.location.group = "goto";
	ch.location.locator = "monk3";	
	ch.Dialog.Filename = "CoastbrotherTurks_dialog.c";
	ch.nation = PIRATE;
	ch.Flags.Pirate = 2;
	ch.Flags.Pirate.texture = 0;
	ch.rank 	= 3;
	ch.reputation = "20";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	Lai_setImmortal(ch, true);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 40.0, 40.0);
	ch.questchar = true;//MAXIMUS: identifier for captives
	AddGameCharacter(n, ch);

				// Brother of the Coast 5
	ch.name = TranslateString("", "Coastbrother");
	ch.lastname = "";
	ch.id		= "CB5";
	ch.model = "Animist4A";
	ch.sex = "man";
	//ch.sound_type = "pirate";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Turks_church";
	ch.location.group = "goto";
	ch.location.locator = "monk4";	
	ch.Dialog.Filename = "CoastbrotherTurks_dialog.c";
	ch.nation = PIRATE;
	ch.Flags.Pirate = 2;
	ch.Flags.Pirate.texture = 0;
	ch.rank 	= 3;
	ch.reputation = "20";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	Lai_setImmortal(ch, true);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 40.0, 40.0);
	ch.questchar = true;//MAXIMUS: identifier for captives
	AddGameCharacter(n, ch);

				// Brother of the Coast 6
	ch.name = TranslateString("", "Coastbrother");
	ch.lastname = "";
	ch.id		= "CB6";
	ch.model = "Animist4B";
	ch.sex = "man";
	//ch.sound_type = "pirate";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Turks_church";
	ch.location.group = "goto";
	ch.location.locator = "monk5";	
	ch.Dialog.Filename = "CoastbrotherTurks_dialog.c";
	ch.nation = PIRATE;
	ch.Flags.Pirate = 2;
	ch.Flags.Pirate.texture = 0;
	ch.rank 	= 3;
	ch.reputation = "20";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	Lai_setImmortal(ch, true);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 40.0, 40.0);
	ch.questchar = true;//MAXIMUS: identifier for captives
	AddGameCharacter(n, ch);

				// Brother of the Coast 7
	ch.name = TranslateString("", "Coastbrother");
	ch.lastname = "";
	ch.id		= "CB7";
	ch.model = "Animist4C";
	ch.sex = "man";
	//ch.sound_type = "pirate";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Turks_church";
	ch.location.group = "goto";
	ch.location.locator = "monk6";	
	ch.Dialog.Filename = "CoastbrotherTurks_dialog.c";
	ch.nation = PIRATE;
	ch.Flags.Pirate = 2;
	ch.Flags.Pirate.texture = 0;
	ch.rank 	= 3;
	ch.reputation = "20";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	Lai_setImmortal(ch, true);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 40.0, 40.0);
	ch.questchar = true;//MAXIMUS: identifier for captives
	AddGameCharacter(n, ch);

				// Brother of the Coast 8
	ch.name = TranslateString("", "Coastbrother");
	ch.lastname = "";
	ch.id		= "CB8";
	ch.model = "Animist4A";
	ch.sex = "man";
	//ch.sound_type = "pirate";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Turks_church";
	ch.location.group = "goto";
	ch.location.locator = "monk7";	
	ch.Dialog.Filename = "CoastbrotherTurks_dialog.c";
	ch.nation = PIRATE;
	ch.Flags.Pirate = 2;
	ch.Flags.Pirate.texture = 0;
	ch.rank 	= 3;
	ch.reputation = "20";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	Lai_setImmortal(ch, true);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 40.0, 40.0);
	ch.questchar = true;//MAXIMUS: identifier for captives
	AddGameCharacter(n, ch);

				// Brother of the Coast 9
	ch.name = TranslateString("", "Coastbrother");
	ch.lastname = "";
	ch.id		= "CB9";
	ch.model = "Animist4B";
	ch.sex = "man";
	//ch.sound_type = "pirate";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Turks_church";
	ch.location.group = "goto";
	ch.location.locator = "monk8";	
	ch.Dialog.Filename = "CoastbrotherTurks_dialog.c";
	ch.nation = PIRATE;
	ch.Flags.Pirate = 2;
	ch.Flags.Pirate.texture = 0;
	ch.rank 	= 3;
	ch.reputation = "20";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	Lai_setImmortal(ch, true);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 40.0, 40.0);
	ch.questchar = true;//MAXIMUS: identifier for captives
	AddGameCharacter(n, ch);

				// Brother of the Coast 10
	ch.name = TranslateString("", "Coastbrother");
	ch.lastname = "";
	ch.id		= "CB10";
	ch.model = "Animist4C";
	ch.sex = "man";
	//ch.sound_type = "pirate";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Turks_church";
	ch.location.group = "goto";
	ch.location.locator = "monk9";	
	ch.Dialog.Filename = "CoastbrotherTurks_dialog.c";
	ch.nation = PIRATE;
	ch.Flags.Pirate = 2;
	ch.Flags.Pirate.texture = 0;
	ch.rank 	= 3;
	ch.reputation = "20";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	Lai_setImmortal(ch, true);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 40.0, 40.0);
	ch.questchar = true;//MAXIMUS: identifier for captives
	AddGameCharacter(n, ch);

			// Brother of the Coast 11
	ch.name = TranslateString("", "Coastbrother");
	ch.lastname = "";
	ch.id		= "CB11";
	ch.model = "Animist4A";
	ch.sex = "man";
	//ch.sound_type = "pirate";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Turks_church";
	ch.location.group = "goto";
	ch.location.locator = "monk10";	
	ch.Dialog.Filename = "CoastbrotherTurks_dialog.c";
	ch.nation = PIRATE;
	ch.Flags.Pirate = 2;
	ch.Flags.Pirate.texture = 0;
	ch.rank 	= 3;
	ch.reputation = "20";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	Lai_setImmortal(ch, true);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 40.0, 40.0);
	ch.questchar = true;//MAXIMUS: identifier for captives
	AddGameCharacter(n, ch);

				// Brother of the Coast 12
	ch.name = TranslateString("", "Coastbrother");
	ch.lastname = "";
	ch.id		= "CB12";
	ch.model = "Animist4B";
	ch.sex = "man";
	//ch.sound_type = "pirate";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "Turks_church";
	ch.location.group = "goto";
	ch.location.locator = "monk11";	
	ch.Dialog.Filename = "CoastbrotherTurks_dialog.c";
	ch.nation = PIRATE;
	ch.Flags.Pirate = 2;
	ch.Flags.Pirate.texture = 0;
	ch.rank 	= 3;
	ch.reputation = "20";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	Lai_setImmortal(ch, true);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 40.0, 40.0);
	ch.questchar = true;//MAXIMUS: identifier for captives
	AddGameCharacter(n, ch);

			// Leader of the Coast 1
	ch.name = TranslateString("", "Leading");
	ch.lastname = TranslateString("", "Coastbrother");
	ch.id		= "CB1";
	ch.model = "monk4";
	ch.sex = "man";
	//ch.sound_type = "pirate";
	GiveItem2Character(ch, "blade13");
	ch.equip.blade = "blade13";
	GiveItem2Character(ch, "pistol5");
	ch.equip.blade = "pistol5";
	if (ENABLE_AMMOMOD) {	// LDH change
		TakenItems(ch, "gunpowder", 1 + rand(2));
		TakenItems(ch, "pistolbullets", 1 + rand(2));
	}
	ch.location	= "Turks_church";
	ch.location.group = "goto";
	ch.location.locator = "monk12";
	ch.Dialog.Filename = "CoastBrotherTurks_dialog.c";
	ch.nation = PIRATE;
	ch.Flags.Pirate = 0;
	ch.Flags.Pirate.texture = 0;
	ch.rank 	= 7;
	ch.reputation = "20";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "7";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "0";
	ch.perks.list.BasicDefence = true;
	ch.perks.list.AdvancedDefence = true;
	ch.perks.list.CriticalHit = true;
	ch.perks.list.SwordplayProfessional = true;
	ch.perks.list.Gunman = true;
	ch.money = "0";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	Lai_setImmortal(ch, true);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 120.0, 120.0);
	ch.questchar = true;//MAXIMUS: identifier for captives
	AddGameCharacter(n, ch);

				// Brother of the Coast 13 Blowhorn style
	ch.name = TranslateString("", "Coastbrother");
	ch.lastname = "";
	ch.id		= "CB13";
	ch.model = "Blowhorn_monk";
	ch.sex = "man";
	//ch.sound_type = "pirate";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
//	ch.location	= "Turks_church";
//	ch.location.group = "goto";
//	ch.location.locator = "monk11";	
	ch.Dialog.Filename = "CoastbrotherTurks_dialog.c";
	ch.nation = PIRATE;
	ch.Flags.Pirate = 2;
	ch.Flags.Pirate.texture = 0;
	ch.rank 	= 3;
	ch.reputation = "20";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	Lai_setImmortal(ch, true);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 40.0, 40.0);
	ch.questchar = true;//MAXIMUS: identifier for captives
	AddGameCharacter(n, ch);
	
//PW poker competition characters showcasing location=====================	
	
	ch.old.name = "Reginald";
	ch.old.lastname = "Longoustine";
	ch.name 	= TranslateString("", "Reginald");
	ch.lastname 	= TranslateString("", "Longoustine");
	ch.id		= "Reg_L";
	ch.model	= "Reg_L";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Turks_poker_entre";
	ch.location.group = "goto";
	ch.location.locator = "goto8";
	ch.Dialog.Filename = "Poker twins_dialog.c";		
	//ch.greeting = "Gr_Oxbay Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.last_theme = "";
	LAi_SetStayType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	LAi_SetImmortal(ch, true);
	AddGameCharacter(n, ch);
	
	
	ch.old.name = "Bouncer";
	ch.old.lastname = "";
	ch.name 	= TranslateString("", "Bouncer");
	ch.lastname 	= TranslateString("", "");
	ch.id		= "bouncer";
	ch.model	= "bouncer";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Turks_poker_entre";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.Dialog.Filename = "Poker_Bouncer_dialog.c";	
	//ch.greeting = "Gr_Oxbay Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.last_theme = "";
	LAi_SetSitType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	LAi_SetImmortal(ch, true);
	AddGameCharacter(n, ch);


//<-- JRH
}
