string DLG_TEXT[23] = {
"Order something or get lost!.",
"Don't ever talk to me again in that way.",
"What would you like to drink Captain?",
"Rum and the best quality only!",
"Give me a bottle of wine.",
"Beer and be quick about it.",
"I'll take some water thank you.",
"Ahh, we have a little problem here - we have run out of rum for the moment.",
"I see, give me something else instead.",
"A good choice Captain - it's only 250 gold per bottle.",
"Well that sounds very cheap - something wrong with the wine?",
"Not at all Captain. We have our own hrmm 'import', that's all.",
"Fine give me a bottle at once then.",
"No I don't want to spend money on wine at the moment. Give me something else.",
"A tankard of strong beer - only 5 gold Captain.",
"Fine let's have some beer then.",
"Here you are Captain.",
"Cheers!",
"No I don't want to spend money on beer at the moment. Give me something else.",
"And water you'll have Captain!",
"Well I ... (meant a glass stupid)",
"Oh no! Give me anyting then.",
"Very good barman.",

};