string DLG_TEXT[42] = {
"Hello Captain Pyle, I have got something that you're looking for ... ",
"Hello who are you, how do you know who I am and what I'm up to?",
"Lots of questions - but you'll need the medicine chest first. Welcome back again.",
"Alright I'll be back Miss ...",
"So there you are Captain Pyle. May these items help you get the citizens back!",
"What? How can you possibly know anything about ...?",
"I know everything, goodbye Captain Pyle.",
"---", 
"Please Captain - in here - quick!",
"Huh?",
"No, he can't - But I can!",
"Hmm? (Ok what am I thinking about now then?)",
"Oh stop that will you. There's no time for games.",
"(Isn't it!!!)",
"He's got more documents that could be of interest to you mister De Foe.",
"Oh sure here are some ancient scrolls and books. Please take them.",
"He's got a 'Woodes-Rogers' too!",
"Yes I got it from the governor!",
"Captain, add those pistols you took from the guards to that deal...",
"Alright, I didn't know you had an interest in weapons?",
"I have to make a living as a trader -",
"- is that so strange?",
"I see great danger for you Captain.",
"Oh yeah? (She can see the future as well!?)",
"I can see the future as well, yes.",
"Hrmm I see... (Scary that's what I think!)",
"You want those pirates out from there?",
"Indeed I do.",
"Very well. Mister De Foe -",
"- please give me the shipyard key.",
"Don't be so sure about that -",
"- I'll make it fit!",
"It was easy to find volunteers for an expedition like yours Miss Rogers! -",
"- I even got more men than we need, maybe they're something for Captain Pyle?",
"There was also a notebook, wasn't it?",
"Well, hmm... yes. Governor Rogers claims that this map piece belonged to Hornigold.",
"Maybe that was the kind of joke Teach was so fond of. If he was killed, the 'lucky' one to find his pistols would exactly know who he had to kill.",
"Let's assume Teach divided the original map in six pieces, regarding the pistols. So there could be five more pieces to find...",
"Life is just an illusion...",
"Hmm, well ... ahh ... hmm?",
"The two first lines are the sailors",
"and the third line the officers.",


};