string DLG_TEXT[66] = {
"And who might you be?",
"Captain Howard Pyle, at your service Sir.",
"I am honored to meet you, please see if you could get us some rum from that big barrel by the fireplace.",
"Very well, let's take a drink mister ...?",
"The distillery is empty you say? What a pity! I'll be happy to see you for a drink another time then.",
"Yes maybe we'll meet again, I didn't quite catch your name though ...",
"Please young Captain we're in desperate need for some rum here!",
"Alright alright I'll see if I can get you some.",
"You certainly have the look of a pirate, may I make an interview with you Captain?",
"What are you saying? Of course I am not a pirate!",
"No molasses you say? Perhaps you could light the fire for us to start with - it's getting freezing cold in here!",
"No molasses you say? What about the wood then? It's freezing cold in here - Perhaps you could light the fire for us to start with",
"Interesting with this gathering of pirate captains - maybe I could get a interview with some of those famous characters - what do you think Captain Pyle?",
"Hmm, I think you should think more of your own security mister ...",
"No I'm sorry Captain, but I have a lot of very exciting notes to write out fair. This is material enough for a volume II I think.",
"So you're staying - is that it?!",
"Yes Captain, this is my great opportunity. But thank you anyway.",
"You're welcome mister...",
"De Foe, Daniel De Foe at your service Captain.",
"The famous author! I should have guessed. Pleased to meet you Sir.",
"Very well then.",
"What is it now Captain?",
"You'll find food and drink in the other cave - and a better bed too.",
"That sounds good Captain, thank you very much!",
"This bed wasn't comfortable at all, look what I found in it!",
"A spade!",
"Maybe you have visited my house earlier Captain?!",
"Well I  - ehh - hrm... (Can he read my mind or what??!!)",
"I'm happy to see you enjoy reading my books - perhaps you could please return them now.",
"Sure, I mean.. it was...",
"That really is a rare item for a researcher like myself. Are you willing to trade it?",
"What do you offer mister De Foe?",
"I have an ammunition bag that looks like it belongs to that belt of yours...",
"Hmm, that's interesting. Where have you got it?",
"Never mind Captain, let's say I got it from a person I made an interview with. Do we have a deal?",
"Sure why not. Let's exchange items!",
"So we meet again young Captain! It was a great time we had at Vane's wasn't it!",
"If you say so - I'm happy to see they let you return home unharmed.",
"Take care Captain - Charles Vane and associates do not trust Rogers' officers at all.",
"Vane's right - they have already tried to kill me!",
"Very impressive! What are you up to now Captain?",
"I have to get Vane and his captains out from Rogers' rooms to the ships!",
"I have the keys to the shipyard...",
"You do?",
"Sure, I live down there.",
"Please Mister De Foe open it at once!",
"Sure, here it is -",
"- but it doesn't fit anywhere else!",
"Are you gonna breathe on it -",
"- or what??!!",
"Hornigold's ship was the starting point for many of the more famous pirates. When Woodes Rogers was appointed governor of the Bahamas Captain Hornigold asked for and received a pardon.",
"Hmm, but why did he give away the map to Governor Rogers, or didn't he?",
"This is the story that Samuel Bellamy, a former member of Hornigold's crew, told me, and it was confirmed by Olivier La Bouche, whom Hornigold cruised in tandem with at that time.",
"Please go on, this is exciting... ",
"Hornigold left New Providence Island with Edward Teach (Blackbeard) among his crew. After capturing a sloop, Teach was given command of the prize. In the spring of the year 1717, they seized a large French ship...",
"Yes...?",
"Governor Alexander Spotswood of Virginia gave Lieutenant Robert Maynard the command of two sloops.  Maynard killed Teach and beheaded him, tied the 
head to the bowsprit of his ship, and set sail for Virginia.",
"I thought that was only a legend!",
"Almost you say. Did they take your map-piece!?",
"No, I had fastened it with tar under my foot. So even though they took my shoes they missed it!",
"Oh come on, you know better than to ask that. By the way did you recieve the package I sent to the poor Governor?",
"In fact I did. And those hints were really helpful...",
"Maybe you should leave all those bottles and things here at the farm. We'll take care of it.",
"Sure, why not.",
"No, she didn't. Good luck, Captain.",
"Thank you and Good Bye.",


};