string DLG_TEXT[43] = {
"Oh, you must be the brave young captain who saved poor Caroline?",
"Indeed I am, now tell me what kind of place this is! (And why you are dressed up in that funny way)",
"This kind Sir is the finest shop in the entire archipelago - we sell all kind of weapons, furniture and paintings here.",  
"I see, well maybe another day... (Is it a woman with a moustache or...)",
"Even if the shop isn't open yet, take these keys and look around for a while. If you find anything of interest, please keep it. See it as a gift from the Governor Rogers' shop!",
"Okay thank you then! (Or a man with ...?)",
"Welcome back traveller, you have come for the medicine chest I guess.",
"Hello Dave, that's true - what have you got?",
"Oh we do have a chest no problem with that - I have placed it in the shop for you. But medicines, I'm sorry that's another thing ...",
"Alright I'll take a look then.",
"Yes captain, you have come to the right place: I can get you a violin.",
"Now that sounds good! Where is it?",
"There is one little thing kind sir ... The instrument is mine.",
"And you don't want to sell it, right?",
"On the contrary captain, but can you afford it?",
"How much Dave?",
"2000 for the violin and that's a very friendly price. What do you say?",
"You must be joking - I can get a blade for that!",
"I see you don't know the right value of anything else than weapons. Do as you wish - but it's the finest instrument in the whole Caribbean I can assure you - and the only violin too.",
"Alright, give me that fiddle.",
"You're right I don't have the money ... yet. I'll be back.",
"You have to pick up the instrument yourself in my bedroom - I can't leave the shop.",
"Here's your 2000 Dave.",
"Ahh, we're happy to help you Captain. Now you can help us...",
"Sure Dave, what can I do for you?",
"If you find any blades please hand them over to us - we can easily sell them in the store.",
"Of course. Now what - how do we get out of here?",
"And Courtney and Cook and not to forget that scary doctor. Now go and help Caroline, Captain.",
"Yeah I should be on my way again.",
"But Captain Rogers, the ships are not fully equipped -",
"- there are still lots of things needed!",
"Benjamin Hornigold, the notorious pirate - or was it the famous pirate hunter. In any case that's one thing that we can easily sell in the Shop.",
"Okay, I think I'll keep it as a curiosity. (you never know...)",
"Remember Teach was the one who searched 'La Concorde', maybe he found something?",
"We'll never know. Now to another matter: the pistols. Where did Governor Rogers get them?",
"We sell all kind of weapons, furniture and paintings.",
"That's good to know Dave.",
"... but this time I'll make an exception: Captain, here are your pistols...",
"Oh thank you indeed Dave. (Oops, I missed to pick them up!)",
"Oh, by the way Captain, have you visited the poor sailor Selkirk yet?",
"No where is he?",
"He's living in the Governors Bootyroom.",
"Okay. (I know where that is)",

};