string DLG_TEXT[53] = {
"Don't you dare to adress a First Mate in that manner again, you insolent hireling!",
"Umm... err... I see. Goodbye.",
"Hey, you there! You look suspicious to me. Who the hell are you? Show me your papers!",
"Who the hell are YOU? Identify yourself, and be quick about it!",
"Halt! I have never seen you before, but you have the face of a pirate! Can you prove that you are none?",
"I am ",
" , and here are my captain's comission and my shippapers to prove it. Was that quick enough for your rather short temper?",
"Your crew has been equipped with more weapons. I don't like it at all but you're allowed to choose a blade from that wall behind you. Just give me the number of the blade and be quick about it.",
"And who might you be?",
"It's Sir to you and I'm not an anonymous officer in these waters... Now take a sword or get lost!",
"Alright, alright I'll pick a blade.",
"Which blade number peasant?!",
"Let me see ... I want to try nr 1.",
"Or maybe ... nr 2.",
"Give me nr 3!",
"Or should we say ... nr4?",
"I'll take the last one!",
"That long sabre is really something extraordinary!",
"Let me try it.",
"Try another one youngster?",
"No I'll keep this! Goodday",
"Yeah, let me take a look at the other blades.",
"I don't think so, that happens to be my own blade. Put it back at once and choose another one!",
"A short broad sabre, almost a cutlass if you like...",
"The blade has some damage and must be repaired before it's sold. Take another one!",
"A very nice looking rapier - even women like it.",
"I can't give you that - it's the last one. We'll get more rapiers within a week. Now pick another sword!",
"Now that's an extra fine rapier -look at the engravings...",
"It's reserved for a customer. Anyway it's not for a simple seaman like you. Make another choice!",
"An ordinary rapier - all in black - for discreet use?",
"Alright 'Master Sworsman' take it and disappear. But - you think you can outdraw me ehh?!!!",
"One day we'll meet again baldhead ...",
"Use your fire kits sailor-boy!",
"Oh no! Are you going to start with that too. And besides I don't have any fire kits?",
"Come on boy - light the fire now!",
"Hrmm?",
"This mission is meaningless I can tell you - no one has brought any medicines so far. We have to bribe the scum I say. Try to get some food for example.",
"Well I really don't know if I ...",
"You don't think...! You havn't even managed to find the doctor, Mr Dover yet!!",
"Alright I'll get the food - on condition that you help me open this chest.",
"Sure - why not? Turn around and the chest will be open in a second!",
"(Boasting of course - this could be interesting) Okay!",
"They havn't even started delivering their medicines yet!",
"I see, I'll come back later then.",
"I told you to get some food didn't I?!",
"I'll get the food - don't worry.",
"You have to be much quicker to obey orders under my command boy.",
"First I'm not under your command - second Yes I think I can outdraw you!",
"Very well you managed to bring some food after all.",
"Picked some locks recently, have you?",
"Alright boy, take these bottles and get lost - I sure have more important things to do.",
"Well, this collection of remedys looks really good. You're able to obey orders after all!",
"I don't like it at all but you're allowed to choose a blade from that wall behind you. Just give me the number of the blade and be quick about it.",

};