string DLG_TEXT[44] = {
"I took that ship Hornigold, not you or La Buze -",
"- and from this day on we will each go our separate way!",
"You can take all cargo and half of the volunteers -",
"- but I'll keep the prize Captain!!",
"Calm down Captain -",
"- take this and thanks for the ship.",
"Just one more thing Hornigold -",
"- hand over one of your pistols!",
"Alright. You gentlemen who want to join me - ",
"- step over here.",
"If those two sloops manage to get off the ground before we do -",		//10
"- then we're in real trouble.",
"It may be of value one day -",
" - if we survive the fight...",
"But first, you've got two pistols -",
"- hand over one of them.",
"Go below and be ready with your pistol at the gunpowder magazine -",
"- if they take the sloop: blow us all to hell!",
"Mister Hands, if you please...",
"Aye aye, Captain.",
"What is it now?",
"Uhh, sorry to disturb you Captain.",
"I have a business proposal for you Governor -",
"- we found this abandoned ship...",
"Such as..?",
"",			//25
"Freedom is Slavery - Ignorance is Strength - ",
"- War is Peace.",
"She was running the Jolly Roger I swear it -",
"and English, no I wouldn't say that.",
"I have a paper here that may pass as a 'commission' -",
"- what do you say?",
"How about this Governor:",
"you'll get a share of the ship's cargo too.",
"Let's say... 60 hogsheads -",
"- of the finest Sugar?",
"And of course... 20 hogsheads of the same Sugar for you, Mister Secretary. -",
"- Now where do you want these goods to be delivered?",
"If I don't now and then kill one of you -",
"- you will forget who I am!",
"He saved my life once -",
"- now I have saved his...",
"No, you are going to help him - call the french surgeons, Major Bonnet. All four of them.",
"And besides that...",


};