string DLG_TEXT[23] = {
"Captain, I have no time to talk to you right now.",
"See you later then.",
"Captain, I have no time to talk to you right now.",
"See you later then.",
"I know how to fire a Critical Shot with your cannons.",
"I know how to inflict Increased Crew Damage to an enemy ship.",
"I know how to inflict Increased Sail Damage to an enemy ship.",
"I know how to inflict Increased Ship Damage to an enemy ship.",
"I know how to inflict Increased Sail or Crew Damage to an enemy ship.",
"I know how to inflict Increased Ship or Crew Damage to an enemy ship.",
"I know how to inflict Increased Ship or Sail Damage to an enemy ship.",
"I know how to inflict Increased Ship, Sail or Crew Damage to an enemy ship.",
"I want to know more about Increased Ship Damage.",
"I want to know more about Increased Sail Damage.",
"I want to know more about Increased Crew Damage.",
"I certainly say yes to that!",
"Maybe later.",
"There should be seven coins in the box, no more no less.",
"Is that so?",
"If you want to know more about the Collection Box -",
"- ask someone else.",
"Captain, now you know as much as we do about the Collection Box!",
"Okay, I have it all in my Questbook.",

};