string DLG_TEXT[32] = {
"Yes...?",
"Sorry to bother you Sister. My name is Howard Pyle and...",
"Oh no - it finally happened.",
"Is there a problem, Sister Richards?",
"I know why you have come here Captain Pyle. And also what you are!",
"I'm just an ordinary and honest sailor...",
"Stop it!! You're a pirate just like my brother was. And you're here for the map! Right?",
"Well if you put it that way, Sister.",
"How many lives did you have to take to get here. All the other five bandits?",
"Listen, I have not murdered one single person. (because of this) Is it true that he got it from Blackbeard himself?",
"Very well then. This is what happened: the pirate Teach blockaded Charles Town town with his flotilla.",
"Queen Anne's Revenge and some sloops I think?",
"Yes, Quees Anne's Revenge was his very large flagship. Israel Hands was captain of the sloop Adventure, Major Stede Bonnet and my brother on the sloop Revenge. And an additional fourth small sloop serving them as a tender.",
"Their demands from the city were very humble I have heard.",
"Not to these people. You must remember that they were all more or less infected with the 'French disease'.",
"Syphilis yes. Now did they get what they needed so badly?",
"The entrance to Charles Town was protected by a Fort high on a cliff. A Fort that could sink all the ships any minute...",
"Yes...",
"The medicines didn't help my brother...",
"I'm sorry to hear that Sister. Are you willing to trade the map to me?",
"Certainly not.",
"Why not?",
"Because I don't have it any longer.",
"What??!! So where is it then?",
"The abbess got it. As she keeps all our personal belongings.",
"Do you think she's willing to sell it?",
"It's up to her to decide. I have no interest in my brothers piece of paper.",
"Where is the Abbess? Can I talk to her?",
"Try her private room, it's on the upper floor.",
"Thank you very much for your time, Sister Richards.",
"Before you leave Captain, I've got something for you...",
"Well, thank you Sister!",


};