string DLG_TEXT[20] = {
"Give a coin to a poor unfortunate, my dear",
"and God will give you luck for your kindness!",
"Please! Give me some money for food -- and, er, perhaps some drink!",
"I beg of you!",
"Oh,",
"show a little charity to someone less fortunate than yourself. Please?",
"Can it be, ",
"that you don't even have money? Perhaps you should join me in my, um, work.",
"Charity is a virtue, ",
"but I'll need more coin.",
"I'm sorry, ",
"it appears you're a little bit short on funds right now?",
"Generosity suits you,",
"may fortune always favor you!",
"Alas, ",
"it appears you don't even have money to spare for charity?",
"I'm sorry,",
"charity is a virtue, but business is business. I'll need money.",
"Give a coin to a poor man",
"and it will come back to you tenfold!",

};
