string DLG_TEXT[45] = {
"Halt! Who goes there?",
"Me.",
"Halt! Who are you and what are you doing aboard this ship?",
"I'm one of the dock workers here. I've just been hired by Captain ",
" to help ",
" with loading the ship.",
"That doesn't surprise me. ",
" is always shirking and running off for a drink. Alright, go ahead.",
"Captain ",
" is expecting me. Perhaps you'd care to tell him that his lady friend has arrived? And then you can explain why I'm being delayed. He really was looking forward to my visit.",
"Er... no. There won't be any delay. Go right ahead, ",
".",
"Thank you, sir.",
"Alright, I see you - come out of there!",
"What's wrong?",
"I'll tell you what's wrong. I've spoken to the captain. ",
"He hasn't hired any new dockers lately.",
"He's not expecting any female company.",
" That means you're probably a spy. Surrender now and perhaps I'll let you live long enough to meet the captain yourself.",
"No, I think I'll stay here. And so will you!",
"Stop! We have reason to believe that there is a spy aboard. Who are you and what are you doing?",
"I'm a dock worker unloading cargo.",
"Let me see your authorisation papers.",
"Here's my authorisation!",
"If we admit to being spies, can we have some time in the brig? It would be easier than lugging cargo all day.",
"You lazy idlers! Get back to work!",
"And good luck catching the real spies, if there are any.",
"I have been visiting the captain.",
"I already asked about that. He has had no female visitors.",
"Of course he denied it to you! He'll probably be in trouble if his superiors find out, which is why he hid me in the hold. I'm about ready to scream and let the whole town know I'm here! And Captain ",
" will probably make sure you get in trouble as well!",
"Alright, no need to be like that. If the captain has been mistreating you, perhaps I can make amends later?",
"That's very kind of you. Perhaps I'll take you up on your offer if you have time ashore. Now, if you'll stand aside, I'll leave the ship, please.",
"This here is the house of our boss. We're his bodyguards. That means we're responsible for his body. We're not responsible for your body, so take it away before it gets damaged.",
"Alright, I'm going. I wasn't interested in your boss' body anyway.",
"Ah, good! You haven't left yet.",
"Who are you?",
"I'm ",
". My job is to provide equipment to agents such as yourself when they depart on missions. I almost missed you. You must be ",
".",
"You know who I am and what I am doing?",
"Yes. Knowing things is our business, isn't it? Now, as to your mission. You may need to dispose of enemies without drawing attention, so here are some poisoned throwing knives. Don't waste them.\nAnd here's a little something to help you enter places the enemy doesn't want you to enter. It's not perfect and may get jammed in a lock, so again, don't use it until you have to.",
"How will I know when I need to use this equipment?",
"Thanks. I'm sure this will be very useful at some time.",
"Providing equipment is my job. Knowing the right time to use it is yours. The point is, don't waste the equipment or you might not have it when you really need it.",
}