string DLG_TEXT[23] = {
"So there you are, ",
"! I almost thought you wouldn't have the courage to show up!",
"Well, as you can see, I am here. So no worries there!",
"Worrying? Me? Ha! The only thing that could worry me is that you spill your blood all over my precious clothes!",
"Well, we will see who is going to bleed.",
"Very well, then. Let us settle this matter once and for all.",
"I don't have anything to settle, #sfriend#. Your sister just was very, very friendly, ha ha!",
"I don't have anything to settle, #sfriend#. Your brother just was very, very friendly, ha ha!",
"You are a sore loser indeed. The ship is mine. I beat you fair and square and without cheating!",
"#sputa#! You are a #sgender# without honour!",
"Now, that is an insult you will have to pay for!",
"Go to hell, ",
"! En Garde!",
"En Garde!",
"my friend",
"mon ami",
"amigo mio",
"meu amigo",
"mijn vriend",
"my friend",
"min vän",
"Hija de puta",
"Hijo de puta",
};
// First version of "my friend" is for Personal and Pirate character and should be the player's language
// Second version of "my friend" is for English character and should not be translated
