string DLG_TEXT[50] = {
"You look flustered, is everything well with you?",
"Oh! Err... Yes, M'lady.",
"Ahem..hem...hem...",
"My name is ",
"? You're not related to the Duke of Wellington?",
"He's my brother.",
"But... A Spanish lugger!",
"There's yellow fever in #sIsla Muelle#. When Captain ",
" set off in search of you, he was good enough to...",
"<You hear screaming from the direction of the boarding area.>",
"Forgive me, ",
", but I was about to tell you that I require passage to #sGreenford# for myself and my maid.",
"Not in the ",
"What other British ship is in these waters, sir? Do you suggest that we swim home?",
"I suggest that your ladyship return to #sIsla Muelle# and embark on a ship which has frills and fancies enough for women passengers.",
"A thousand people died in #sIsla Muelle# this week.",
"May I ask why you were in #sIsla Muelle# in the first place?",
"Because, sir, the British packet I was sailing in was captured months ago by the Spaniards. I was their prisoner until the alliance.\nAnd I must say that I was treated by the enemy with more courtesy than I have received so far from the captain of His Majesty's Ship ",
"Ahem...hem...",
"Exactly!",
"This removes any possibility of your ladyship's remaining aboard.",
"Indeed?",
"We are on our way to fight a ship twice our strength. If we're defeated, you'll be in the hands of a butchering maniac!",
"If I return to #sIsla Muelle#, I'll probably die of the fever. And since there's a good chance of death in either case, I must insist upon making the choice myself.",
"And now, if your ladyship will accompany Mr. ",
", perhaps you'll come to regret your insistence.",
"I hope I'm not disturbing the ship's routine, Mr. ",
"Oh no, not in the least, ma'am.",
"I'm afraid ",
" Hornblower thinks otherwise.",
"Well, he's got a lot on his mind right now, ma'am. If he doesn't retake the 'Natividad', he's in for serious trouble.",
"Surely it isn't his fault if Spain changed sides in the war?",
"I'm afraid the Admiralty won't stop to consider that, ma'am.",
"You're fond of the ",
", aren't you?",
"Fond, ma'am? Why, he's the best officer in the service! He's a better sailor than Mr. Bush, a better gunner than Mr. Gerard, and when it comes to navigation, Mr. Crystal doesn't hold a candle to him!",
"Gentle and warm-hearted. I see what he means!",
"<Shout from above> MR. ",
"Yes, dear. You've come back to me.",
"Oh, yes. Yes, my dear.",
"If I only knew how!",
"On his eyes and on his mouth, your ladyship.",
"<Kisses Longley as instructed.>",
"How did you know?",
"It was the way she said goodbye to him at #sGreenford#. As though she was kissing him goodnight.",
"And she was...",
"That was sweet of you.",
"Goodbye, ",
". Thank you for your kindness.",
"Goodbye, Lady Barbara.",
}
