string DLG_TEXT[34] = {
".....",
".....",
"What are you doing in front of my house?",
"I suppose you are Laura Cotton. In fact, I need your help.",
"Yes, I'm Laura Cotton and for your help it's 50 gold coins paid in advance.",
"Well, it isn't this kind of help.",
"No? So goodbye!",
"Wait! if you help me, you'll receive much more money. I can fully guarantee you.",
"Explain!",
"This work is really easy. You just need to attract in your house a Navy officer by offering your *services*",
"Why a Navy officer? What's your idea in the back of your mind?",
"I cannot tell you. But don't worry, we don't want to kill him. We just want his uniform.",
"I could have trouble helping you.",
"Do you think he will go and talk to his hierarchy informing them he was in the house of a prostitute when some bandits stole his outfit? I don't think so.",
"Hummm. In my case, I can always say I don't know you and you were trying to steal my possessions.",
"Right. So, we have a deal?",
"Depends on the money you can pay...",
"200 gold coins.",
"I don't think so. I want the double or no deal.",
"That's pricey, don't you think so?",
"I have the feeling it's important for you to have this outfit. So, I bet you can pay more.",
"Alright, you drive a hard bargain. I agree to pay.",
"Wait not so fast! It's 200 right now and 200 after you have the uniform.",
"Alright, take these 200 gold coins but don't try to deceive me. I would not be so gallant.",
"I agree but I don't have this sum right now. I'll be back in a few hours with the money.",
"I hope so if you want I help you. You'll find me in the town.",
"So? Have you got my money?",
"Yes finally. Take these 200 gold coins but don't try to deceive me. I would not be so gallant.",
"Almost. I'll be back soon.",
"Thank you, don't worry. Tomorrow at night, I'll be in the tavern. I will easily find this officer there. Wait just for me near my house.",
"We'll do.",
"First, pay me the rest of my reward.",
"Thank you. When he wakes up, I'll tell him I was attacked and robbed.",
"I appreciate. Good luck!",
};
