string DLG_TEXT[15] = {
"Another day before the mast.",
"That's what we signed up for.",
"",
"",
"",
"",
"Horatio, wait! We're still stuck with that bully Simpson. I don't know how much longer I can put up with him.",
"We all feel the same Clayton.",
"Are you alright ",
"? That was quite a punch, and as usual, he ran off before you could respond.",
"I'm alright Clayton. I think the only way to deal with him is to challenge him to a duel. Then he can't run away, but this isn't the right place or the right time. Let's get to the shipyard, then back on board.",
"No Horatio! ... Simpson! I challenge you to a duel. Here, now!",
"Clayton!",
"Sorry Horatio.. ",
"What!",
}
