string DLG_TEXT[40] = {
"I am Colonel Francisco Manuel Ortega at your service.",
"Good day Colonel.",
"It is my sad duty to surrender the fort, its troops and the island to you...?",
"Lieutenant Horatio Hornblower, of His Majesty's Ship Renown, Colonel, and I accept your surrender.",
"Thank you Lieutenant.",
"I would be pleased if you would accompany us while we inspect the fort.",
"Of course Lieutenant. This way if you please.",
"Thank you Colonel.",
"As you see Lieutenant, what is left of my garrison are assembled for your orders, and there is a British naval officer who was a prisoner here, whom I will release to you.",
"Thank you Colonel. Would you be so kind as to release the officer and join your troops please.",
"",
".",
".",
".",
".",
"!",
".",
"!",
".",
".",
".",
".",
".",
".",
".",
"",
".",
"",
"",
"..",
".",
"",
"",
"",
"",
"",
"",
"",
"",
"",
};