string DLG_TEXT[65] = {
"Any orders Mr. Hornblower?",
"Not at the moment Matthews.",
"Mr. ",
", Sir. There are two ships fighting out there. It looks like the 'Indy' Sir, and a Spaniard.",
"Yes Mr. Matthews, I see them. Thank you.",
", Sir. The path to the fort is over here. But if Mr. Buckland doesn't take the 'Renown' out to sea soon I'm a'feared that the Spanish will see her.",
"You're right Matthews, and we will lose the element of surprise. Let's get moving then. Come on men.",
", Sir. Dreadful news. The Spanish have captured the Renown. They had other troops hidden in the pass and after Mr. Buckland had boarded they rowed out and boarded her. We were still coming down the beach, so were too late to intercept them.",
"Then we had better do something about it then Mr. Matthews. They have left a boat so jump to it men. Let's take the Renown back.",
"We're in a bit of a state here Sir. The soldiers were trying to use this old cannon here, but couldn't load it fast enough.",
"But your men can load really quickly!",
"Yes Sir we can, and we have. It's loaded now. We just need to wait for their next volley, and while they are blinded by their smoke we can fire and reload. They are reloading their cannon now, so we are fairly safe for the moment.",
"Good. Well done Matthews. I'll fire it, you and the others get ready to reload.",
"Aye aye, Sir. Just wait for the next volley. It'll be three shots. Then you can run up and fire. Their muskets can't hit us very well from where they are, but there's always the risk of a lucky shot, Sir.",
"Good that's what we will do then. Wait for the next volley.",
"When you're ready Sir, just go to the end and wait for the three French cannon to fire, then just step forward to fire our one.",
"Very well Matthews, be ready to reload. I want to get a second shot away as fast as we can.",
"Come on Oldroyd, Styles! Put your backs into it! ... We have them beat Sir! You're loaded, and they're not ready yet.",
"Good work men!",
"Fire when ready Sir!",
"Right! Everybody clear!",
"A hit Sir! A hit! They're breaking their line. Come and take a look Sir! But be sure not to pass me.",
"Let's not get too far ahead of ourselves Mr. Matthews. Reload.... Just in case.",
"Look Sir! Harper and Tongue have moved up towards the guns, and Mr. Sharpe and the others are close by.",
"And the French officer has turned his men. They are coming back.",
"Should we charge the French Sir? To help Harper and Tongue?",
"No Matthews, Sharpe and Harper know what they are doing. We will just have to watch the situation for a minute.",
"The French have broken again Sir!",
"Yes.... They didn't know where those shots came from.",
"Sir?",
"They know we could hit one of them with a lucky shot from here, but two shots, two deaths, they know we must be close to them.",
"What now Sir?",
"Keep the gun manned, just in case. Other than that, consolidate your position here. The French will be forming a plan, of that you can be sure.",
"Aye aye Sir. Will you be going forward on your own then, Sir?",
"No Matthews, I must go and find out where the reinforcements are. I shall go and see the Colonel at Naval H.Q. I will be back as soon as I can.",
"I don't think you'll be needing to Sir. The Colonel has just arrived here.",
"What?",
"Does that change our orders Sir?",
"No Matthews. Hold the position here as I said, and see if you can get some of these fires out. I am going to see what Sharpe and Lieutenant Quelp are up to. They have reached the French gun position.",
"Mr. Hornblower Sir, We managed to recover two of the French cannon, and have put them in a defensive position. But we don't have enough men to man them Sir. Perhaps the soldiers could help. Even then we may only have time to fire each one once.",
"Good idea Matthews. It's better than nothing. Do you agree Milord?",
"Your not going to like this Mr. Hornblower, but the French have brought up more cannon.",
"Oh! No! So THAT'S what they had hidden in the valley. This is going to be more difficult than I thought.... Don't fire till we see what they're up to.",
"Looks like they got one of ours and we got one of theirs. Their guns are finished though. They won't be firing again. We should be able to fire one more volley. At the troops this time though.",
"Our third gun looks like it might be reloading, but the French infantry looks like it is about to advance. Get ready everyone. This is it!",
"We got one of their guns Mr. Hornblower. That will make them think for a moment at least.",
"It might mean they are going to start their advance. Although I thought they would try to pound us down a bit more first. They are reloading though.",
"Captain Hornblower Sir! Good to see you back in command.",
"...",
"Landing party's ready captain.",
"Mr. Matthews. You will stay at the boat with the marines, once we've landed, to cover our retreat. Now, we need a volunteer to carry the explosives.",
"We will wait here for you, sir.",
"Good Matthews. Be prepared, set up a defensive line with the marines. I'm sure the French wont be far behind us, once they hear the bang.",
"You can rely on us, Captain.",
"I know I can Matthews. Well, we'd better be off to the lighthouse.",
"Where's the Captain, sir?",
"They.. They've been cut off.",
"Give me six men. Tell them to fix bayonets.",
"There's a company of soldiers headed up there, and more on the way.",
"We must do what we can, sir.",
"Oh No! We must withdraw. If we stay on this beach we will be cut down where we stand.",
"We can't leave without the Captain, sir.",
"For God's sake Matthews, the Captain's been cut off. Get the men into the boat.",
"Not without an order, sir.",
"Those are his orders. Damn You!",
};