string DLG_TEXT[69] = { 
"It looks like trouble.",
"Hmm.. Yes it does Mr. Hunter.",
"Ah! Lieutenant glad to see you up and about sir. I'm Midshipman Hunter. I have been assigned to your division.",
"So I am given to understand. How are the wounded doing?",
"Most are recovered sir, and enjoying some well deserved shore leave.",
"They need to make the most of it. The 'Indy' will be back soon and then we will go looking for some French and Spanish ships.",
"Haven't you heard the cannon, sir? The French are already here.",
"WHAT? What are you talking about man?",
"You've been asleep for a couple of days sir. As soon as the squadron went over the horizon they came out of nowhere. They have the port blockaded. We have no ships that could take them on.", 
"But that means when the 'Indy' turns the point on her return, she will sail straight into them. We have to warn her.",
"And how will you be doing that Lieutenant? Wave a flag from the cliff tops?",
"Don't be impudent Hunter. We shall make the French ships move their position.",
"Oh! And how will we be doing that then?",
"What's the most important thing on board a ship at sea Hunter?",
"Food and water?",
"Correct. Food and water. Food they can carry. But they need to replenish their water supply with fresh water when they can.",
"You're right sir. A sloop detaches herself from their main squadron and disappears for a while. Then returns.",
"Then it's her getting their water, and there's only one place they can get it from near here.",
"White Bay!", 
"Exactly! White Bay. There's a spring in the valley just off the beach.",
"So what is your plan sir?", 
"We will go there, lay in wait, and cut them off from the water supply. They will have to go back to the squadron for assistance, and the squadron will come to the beach in support.",
"We don't exactly have a full ship's crew. We aren't going to be able to hold them off for long sir.",
"We will worry about that when we get there. Come on we need to get a move on. It's a long journey through the jungle. We'd never get out of the harbour in the jolly boat.",
"I think I can help there Lieutenant. I have a friend, Mr. Larr, 'Smug' they call him. He has a small er.. import, export business. He runs it out of the old house by the bridge. We should go there. He has a short cut to the beach.",
"I hope you're right Mr. Hunter, we need all the time we can get. Let's go then.",
"The French are here already sir, and there's a boat coming ashore.",
"BLAST! I didn't expect them to get here so soon.",
"There's worse, sir.",
"WORSE?",
"We're being watched. On my left sir.",
"?",
"A bloody lobster. Where ever they are, trouble isn't far away.",
"Let's find out what he's doing here. Follow me.",
"The crew are here sir. I've got them standing by in the tunnel. What do we do now?",
"It's time to dress up. Follow me.",
"Lieutenant! Lieutenant, there's a ship bearing down on the bay. It could be the 'Indy' but she's too far out to be sure so it could also be a Frenchman.", 
"We need to get a move on then. Where are the crew?",
"What do we do now Mr. ",
"We check the ship is seaworthy and we have enough supplies. It's going to be a long journey Hunter.",
"Wouldn't we do better to wait to join some larger ships going our way. For protection I mean, Sir.",
"No Hunter. My orders are to make all speed, so we need to get moving.",
"What de we do now Lieutenant?",
"Search around the place to see what we can find. Something may come in useful for our escape later.",
"Leave him Lieutenant. He's given up.",
"No Hunter when we escape, we all go together, and that includes Mr. Kennedy.",
"You're wasting your time, look at him. He's having another fit.",
"Hunter. Shut up! He was captured in battle. You don't know what he's been through.",
"Mr. ",
". We've been here a week now. The men are getting restless, they think we should try to escape now. There are only five guards in here and we could easily overpower them.",
"Really? And how many are there outside? You haven't thought it through. Anyway, I told you Hunter, we won't leave without Mr. Kennedy.",
"Then let's see how he is doing.. Sir.",
"Yes, we can do that.",
"Aye Aye Sir. I will set a course following the coast when we get aboard.",
"No Hunter. I wish to get out to open sea as soon as possible. We will not take the normal course.",
"Look at him. He's no better.",
"Mr. Hunter, we need to give him time.",
"He'll just slow us down when we try to escape. We have to leave him.",
"We will not leave him Hunter. That is my final word on the matter.",
"Did you have a nice walk... Sir?",
"Interminable Hunter. I must go and see how Mr. Kennedy is doing.",
"I keep telling you Sir. He will only slow us down.",
"And I keep telling you, Mr. Hunter. We will not leave without him.",
"Did you have a nice dinner.. sir?",
"It wasn't all pleasure, Hunter",
"Damnation! That was the closest they've got so far.",
"What on earth do you mean Hunter?",
"The French. They won't come in close, so they fire a shot from time to time, from the mouth of the bay. They haven't hit anything yet.",
"Then let's get to the beach and get them to move their ships.", 
};
