string DLG_TEXT[40] = {
"Bye the bye. It might be better if you were to address me as Milord. I am in fact the Earl of Edrington.",
"Yes Milord.",
"Have a care Mr. Hornblower. Stand where you are, or I will have you shot.",
"Major... It's not what it seems.",
"Bye the bye. It might be better if you were to address me as Milord. I am in fact the Earl of Edrington, commander of the Second Battalion.",
"And I find you here having just shot a sergeant and a lieutenant. You are under arrest.",
"But Milord, the lieutenant shot the sergeant. I only shot the lieutenant. I mean...",
"Condemned out of your own mouth. Take the traitor away men.",
"Milord!",
"Who's in charge here?",
"I am Major. Commander Horatio Hornblower of the...",
"Good. Well I am here with the reinforcements, and it seems none too soon. We can not have the army running around all over the place under the command of a naval officer. Sergeant! you and your men will join the column. Lieutenant take charge of them.",
"Milord! We were pursuing the French. We had just driven them off from their gun positions outside the town and followed them here. We had no time to spike the guns, nor bury our dead, but we have located their main force.",
"Then it is even more advantageous that I arrived when I did. We will at least be able to carry out this part of the battle in a military manner.",
"Now, where are these French troops?",
"In the valley over there, Milord.",
"Good. Then lead on Commander we will enter the valley and then take up our battle line.",
"Commander, Colonel Sir Arthur himself, rushed me off the boat to secure the outskirts of the town, where I find you had left the French cannon unguarded. I then followed you into this valley and find our men dead and unburied. I have of course had them buried. It seems that I am doing a lot of clearing up after you Commander.",
"But Milord, we haven't had a chance to reconnoiter the enemy position as yet. I would suggest that your lordship and I do that first. We should also take Sergeant Sharpe along.",
"You have obviously given the matter more thought than I.... Sergeant! Forward if you please. Chumley! Take command of the column, and prepare for the advance on our return.",
"Bless my soul if that isn't Sir Arthur himself over there. Come to watch me thrash the French no doubt.",
"No doubt Milord.",
"But Sir.. er, Milord, there are some French soldiers hiding here in this valley, we were trying to flush them out.",
"Flush them out! From the beach! You really do need me to show you how to fight a battle. Those French will have been gone from here as soon as they heard us coming. Now, where are the French troops?",
"The sounds of that gunfire will have obviously alerted the French so we will just have to make a frontal assault now.",
"If I might suggest, Milord?",
"Suggest what?",
"What little element of surprise we had has now gone. So I would respectfully suggest Milord that you place part of your Company on the beach to stop the French ship from landing any support, should it return.",
"That makes sense.",
"Then the rest of us should return to the town and make our stand there. We will most certainly lose a lot of men if we go into the valley now as it is a bottle neck going through and the men could not spread out enough to avoid being shot.",
"Agreed, but it will reduce the number of men we have for that defence with the rest of them on the beach.",
"Yes Milord, but when they hear the fighting start, if they cannot see the French ship, then they will have time to come up behind the French and we will have them trapped between us.",
"But how will they know they have enough time to leave the shore if the French ship is in sight?",
"If Lieutenant Quelp goes with them Milord, he will know how long it would take the French ship to disembark more troops, and can advise your men accordingly.",
"Very well.... Lieutenant Chumley! Take a column with Lieutenant Quelp and take up a defensive position on the beach. We will return to the town. Let's move quickly.",
"Company! ... About Face! ... March off to the town.",
"I agree. We need as much firepower as we can muster, we don't have enough men to form a line. It is going to be a purely defensive battle. At least until the rest of the Battalion show up.",
"Good. Lieutenant Sharpe, put out your riflemen to cover our flank. Everybody... into position.",
"We need to get back there too, and quickly.",
"",
};