string DLG_TEXT[46] = { 
"Lieutenant William Chumley Sir. 33rd Regiment of Foot.",
"An honour Sir.",
"Lieutenant William Chumley Sir. 95th Rifles.",
"An honour Sir.",
"The troops are disembarked. The French won't be long in coming, they must have got word of our ship coming in hours ago.",
"Well, at least we landed unopposed Lieutenant, but I hear something, drums I think.",
"Time for battle Lieutenant..... Skirmishers forward if you please Mr. Sharpe... 33rd make ready... To the rear if you please Mr. ",
"Sir.",
"That was a bloody business... Mr. Sharpe, take some troops to defend the jolly boat if you please, and have others assist the wounded aboard. We need to be away from here, and quickly.", 
"Can I help Lieutenant?",
"Get us to the ship Lieutenant. I can hear more drums, which means more French troops are coming, and we couldn't withstand another attack as we are.",
"Ah! I get your point Lieutenant.",
"Then back to the ship. Get us to #sRedmond# with all speed Mr. ",
"Aye Aye Lieutenant.",
"No Lieutenant, #sOxbay# is nearer, and some of the men are badly wounded and in need of attention. We shall sail there first in order that they might get that attention sooner.",
"May I remind you Lieutenant ",
", that I am the senior lieutenant here.",
"That Sir, only applies on land. When at sea the ship is under my command, and I say we shall sail to #sOxbay#, and that Lieutenant, is my final word on the matter. We sail for #sOxbay# to get the wounded treated sooner.",
"You were right about the wounded needing attention, Horatio. I should have realised it myself. Anyway they are ashore now and I am going to check up on them.", 
"Very well William. Doubtless we will meet up later when we can discuss when we shall be able to leave here.",
"I have to arrest you gentlemen regarding the death of Captain Sawyer. I am relying on your honour to present yourselves at Naval H.Q. forthwith, and therefore will not embarrass you by putting you under guard. I hope I am not mistaken in this trust?", 
"No Sir you are not. We will be there immediately, but what of lieutenants Bush and Kennedy?",
"They will be taken to the military hospital where they will be treated for their wounds.",
"Thank you Lieutenant.",
".",
".",
".",
".",
".",
"?",
".",
"?",
".",
".",
"",
".",
".", 
"",
"",
"",
"",
"",
"",
"",
"",
"", 
};
