string DLG_TEXT[175] = {
"......",
"......",
"Captain Johan Elting?",
"Right. Are you my new officer?",
"Yes, Captain. I'm Chico Cois. I have already made the preparations for our voyage and the crew is waiting for you onboard ship.",
"Do you know our mission?",
"Yes. A soldier came and gave me the instructions. We have to meet a spy in #sGrand Cayman# and bring a report back. I know this spy so I will give you some useful details about him during the voyage.",
"Alright, we only have one month to accomplish this task so let's look lively now.",
"What are your orders captain?",
"Follow me, we are going to check his house.",
"Damn it, he's not at home?",
"What bad luck! And now?",
"Maybe, he is still at the fort. We should wait for him.",
"I don't like waiting. I think we should find him first, just in case he has been caught.",
"Wait captain! You will be arrested if he has beeen caught or you will put him at serious risk if he hasn't.",
"Humm.. Alright, let's wait a bit. Maybe, he's just late.",
"You could poison him.",
"How?",
"I've got two poisoned throwing knifes.",
"You're right. I could kill him before he enters the townhall. Give me the knives!",
"Take them!",
"In the meantime, you and Domenico wait for me here. I must be back soon.",
"This is the special weapon the Vice-Admiral was talking : a stinkpot.",
"How does it work?",
"Throw it among a group of soldiers and they will be quickly killed by the smoke.",
"Interesting.",
"But be careful with the wind direction so as not to be killed by the smoke too.",
"Thanks Chico, I'll remember it. Now, let's go to #sPort au Prince#.",
"What did he say?",
"Let's talk outside. It will be safer.",
"So?",
"Just few people know the ship's mission.",
"It won't be easy to find out what the French are preparing.",
"No, but maybe I have a solution. The captain of 'La Fougueuse' met the governor just after his arrival, there is a possibility he gave him an order of mission.",
"An order of mission? That is to say there is a document in the townhall?",
"Indeed. If I find it, I would have proof of France's treachery and will know the mission without alerting them.",
"Alright, but the townhall is guarded by soldiers... Even at night.",
"Yes. Guards at the door. Don't worry about that, Chico. Tonight, I will find a way into the townhall, in the meantime go and wait for me at the ship.",
"Did you succeed, Captain?",
"Yes, I found the order of mission,the ship has been ordered to #sisland_Conceicao#, just as we suspected. The French didn't waste much time in helping the Portuguese.",
"So, we need to stop her leaving.",
"Exactly. If the innkeeper is right tomorrow is its last day in #sFalaise de Fleur#. I think the easiest way to stop the ship would be to capture or kill this Captain Aurelien Bergerat. We need to know the Captain's movements by tomorrow morning and act quickly.",
"So that we can prepare an ambush?",
"Yes. But, let's rest tonight. Tomorrow will be a hard day.",
"I've got good news.",
"You're back, Chico! Good, tell me what you discovered?",
"It wasn't easy, but I found out that the Captain will see the tailor and the Governor this morning.",
"It was probable he would meet the Governor before he left, but why the tailor?",
"He left many of his clothes there a few days ago. He most likely wants to get them back before going to #sisland_Conceicao#.",
"He must be one of those peacock Captains, more concerned with their dress than with their ships. Let's wait for him at the port to be sure not to miss him coming ashore.",
"That's him in the quay!",
"Damn!! Two soldiers are with him. We cannot capture him. We will have to kill him and his soldiers, we need to be discreet and there are too many people about.",
"I have a way to kill him - discreetly.",
"How Chico?",
"I've got a time-bomb.",
"A time-bomb? What is it?",
"It's like a big grenade with a long fuse. I could put it in his path, sneak away and the bomb will explode a few seconds later.",
"Wonderful!! [THINKS: I wonder if this was for me if I failed] Let's follow the captain to choose the right moment for the ambush.",
"His soldiers are in front of the tailor's shop.",
"Yes. He must be inside. In a few minutes, he will be going to the Townhall. Follow me, we are going to prepare the ambush near the Loanshark's Office.",
"He must be on his way now. What's your plan Captain?",
"Stay here. When you see him, light the fuse of your time-bomb, put it on the ground and get out of there. The explosion will bring the soldiers like flies to a corpse. After that, wait for me at Octopus Bay with our ship.",
"Alright.",
"Good luck Chico!",
"I'm glad to see you made it.",
"Thanks Chico. Did you have any trouble getting out of town?",
"No, I took advantage of the confusion and left town hidden by the scared crowd. The guards didn't know which way to go in all the confusion. What about you?",
"I went to the church and waited for quiet, before making sure the French captain was dead. I didn't think that small bomb would be quite so powerful.",
"I used my best powder. What are your orders now? Are we to leave the island yet?",
"Not yet. We'll stay here until tomorrow morning. I want to be sure the French ship does not leave to help #sisland_Conceicao#.",
"Would you like me to find out their plans tomorrow?",
"Yes. But be careful, the guards will be suspicious of any foreigners asking questions.",
"Bad news Captain! The ship sailed from #sisland_Falaise de Fleur# during the night.",
"What?! How is it possible? Who's in command of 'La Fougueuse'?",
"An officer of the ship has been field promoted by the Governor himself and is assisted by one of the Governor's own Captains.",
"Dash it! The ambush only quickened things. We don't have any time to waste. Let's sail for #sisland_Conceicao# and hope we can catch up to the lineship.",
"Did you note the ship moored at the port entry looks a lot like 'La Fougueuse'?",
"Indeed she does. But she doesn't fly the French flag and her name has been changed if it is her.",
"Do you think it is her and the French have disguised her?",
"I'm quite sure of it. Their mission is secret and they don't want the Spaniards to know what they are up to.. At least, they tried. But let's go to the tavern, maybe we could find proof of our theory for the Vice-Admiral.",
"Now, we have the evidence. There is almost a French soldier in each corner of #sConceicao#.",
"*ironic tone* Right. The Portuguese governor should rename his town Saint-George.",
"What's the plan now?",
"I don't think we have any option but to sink her.",
"Don't tell me you want to attack her.",
"With our ship? Of course not. Her size and the fact she is under the protection of the fort make a boarding impossible. But sabotaging the ship is feasible.",
"How can we?",
"Thanks to your time-bombs. And a lot of their crew will be ashore.",
"You've made a mistake, Captain. These bombs can kill people but to make a hole in the hull of a lineship! 'La Fougueuse' is not a toy boat.",
"You're right. But, you know warships have one or two gunpowder stores, understand.",
"I do now! You want to place the time-bombs near these stores. A cunning plan.",
"Yes. Even a lineship's hull can't stand up to such an explosion.",
"It will be dangerous to sneak onboard, there will be sentries and.....",
"If you have a better idea I'm all ears.",
"Humm... no, nothing better comes to mind.",
"Alright, we have settled it. Tonight, I'll go and do the deed. In the meantime, prepare the time-bombs.",
"Here are two time-bombs. All I could make. They will have to be enough for your operation.",
"Thank you. If I'm not back before dawn, return to #sHavana# and inform the Vice-Admiral I failed the mission.",
"Use a bottle of ether, Captain.",
"What?",
"With that, you can stun anyone. You just need to wait till she leaves the brothel.",
"And I will have time to search for the key amongst her clothes. Great idea, Chico!",
"I will come with you, Captain.",
"No, Chico. I have another task for you. While I deal with the formalities, you'll recon the fort. I want to sabotage the cannons tonight.",
"I've already found a way to leave the port.",
"Good. When you find the fort entry, join me in the tavern.",
"I thought he wouldn't release me. Sorry Captain for the trouble.",
"Don't be sorry, it's my fault. I should have known - the mission was ambitious to say the least.",
"Anyway, even though I didn't get into the fort, I found a way in.",
"Really? Where is it?",
"Unfortunately. I was arrested before reaching the fort. But, there is a way along the cornice. From what I saw, it seems there is a tunnel to get into the fort.",
"Thanks for the information, Chico, I know enough now. Let's get back to the tavern.",
"It's late, Captain. What's your plan?",
"I'm going to change my clothes in the warehouse so that nobody can recognize me. At this hour, the victualler is gone.",
"Have you got the time-bombs for the cannons?",
"Yes. I'll put them behind each cannon. In the meantime, you'll leave the port with the ship. If necessary, take care of the guards at the port so that they can't sound the alarm.",
"And where will I meet you after you've destroyed the cannons?",
"Head to the fort but wait for the explosions before approaching it. It will fire on the ship if it sees you sailing at night.",
"Alright, Captain. I'm going to prepare my departure.",
"Good luck Chico!",
"What a great fireworks!",
"Ha-Ha! As you say, Chico. Their cannons are useless now. But I had a fight to get to them. Did you have trouble leaving the port?",
"Just a bit! Some of the crew and I had to kill a few before weighing anchor.The guards just didn't stop patrolling near the ship.",
"Good. Well done, we can now return to Havana. We should have a fine reward.",   
"What’s your plan, Captain?",
"I can’t enter the town, too dangerous, the authorities must know I work for the Spanish authorities. So, go there and try to obtain some information about Berend de Voor, he’s the captain of the #sisland_Douwesen# Fort and my former captain.",
"What kind of information you want?",
"In the past, from time to time, he used to patrol the jungle around the town with his men. Check if he continues doing this kind of mission. If yes, find when the next mission is.",
"Alright, I go right now.",
"I’ve got the information!",
"How did you do this?",
"Talking to some soldiers in the tavern... and paying them some drinks, of course.",
"Good. So, what did they tell you?",
"Tomorrow, he will patrol the jungle near the smugglers village.",
"Excellent! We have our opportunity to capture him.",
"He's coming, Captain!",
"Let me talk to him.",
"Done! He’s locked up in the hold.",
"Good. Tonight, open discreetly the hold’s door so that he can escape. Don’t let any crew members in his way. I’ll be on the shore in order to check his flight.",
"The ship is ours, Captain!",
"Thanks, Chico. Where is Bartolomeu?",
"We didn't find him. He isn't on the ship.",
"What? How is it possible? He isn't in the town or on his ship, so where is he?",
"I only found his officer, the man on your right.",
"I'm going to interrogate him.",
"Yes?",
"Take the officer to my ship. He'll be useful for finding his captain.",
"And the crew?",
"Lock them in the hold of this ship so that we can leave the island without troubles.",
"You alone? Where are my men?",
"Chico? What a surprise! So you are captain, now.",
"Right. The Governor of Havana promoted me and gave as first mission to arrest you.",
"A hard mission for a first one.",
"Yes, but I'm not an unexperienced fighter.",
"Of course, but a captain doesn't only need to be a good fighter. He must be a good leader and take the right decisions. This is what you didn't do letting your men being ambushed.",
"How did you know I was looking for you?",
"I must say I was lucky. A patrol detected your arrival and when they described the ship, I knew this ship was 'El Diablo'.",
"The luck is an important element in these dangerous missions.",
"Yes, but you should have ordered your crew to check if there were Dutch troops following me away.",
"Too late for learning. Now, tell me why you betrayed me and the Spanish authorities on #sisland_Eleuthera#.",
"Your superiors thought because I worked for them I could accept all their decisions. But I'm not a Spaniard, Chico. I'm a Dutchman and after the slaughter of Oranjestad, I knew I would leave this life of an assassin.",
"If you are Dutch, I'm Spaniard and a mission to accomplish. I won't give it up. Surrender, Captain!",
"I hoped to avoid this situation but it seems we need to settle our difference with a duel.",
"Let's see if the pupil surpasses the master.",
"En garde!",
"Why you didn't kill me?",
"Because I still respect you, Chico. Now, you are my prisoner but I'll let you return to Havana.",
"We are at Bahia de San Antonio, aren't we?",
"Yes, Chico. Now you are free, you'll be in Havana today.",
"I didn't think you would be so generous after what I did. I won't forget that.",
"I hope so because I won't be generous next time you hunt me.",
"I swear I'll refuse any mission whose goal is to arrest or kill you.",
"It's a brave attitude because you know declining a mission can signify your dismissal or even the jail.",
"I know but you deserve it. Thanks, Captain.",
"Good luck and goodbye Chico!",
};
