string DLG_TEXT[23] = {
"......",
"......",
"I recognize Chico Cois but who are you?",
"His new Captain. I think you know why we are here.",
"Yes. Follow me, I have something for you.",
"Here's the report. It was hidden in my house.",
"Thanks. I will give it to the Vice-Admiral. Goodbye!",
"Wait! I have a problem. I am not sure that I can continue with my work in #sisland_Cayman#.",
"Why?",
"I think that my captain suspects that I am a spy but he doesn't yet know for whom.",
"How do you know, has he questioned you yet?",
"No, but I he has been keeping a close watch on me recently and I have been followed, not very well though.",
"That's a problem indeed...",
"I thought I should kill him but it would be too dangerous for me.",
"Well, I could kill him but I need to meet this guy alone and not among his soldiers in the fort.",
"The situation is not perfect but you could kill him in the town. At the moment, he's in the port checking the unloading of ammunitions and afterwards he has to talk to the governor.",
"I could.. but discreetly.",
"Did you meet him?",
"Right. He won't bother you anymore. I killed him.",
"Thanks! You just saved me.",
"*ironic tone* Yes, I have the same effect as a priest, except I use different means.",
"HA-HA! Indeed.",
"In the future, be more careful when you spy. I have to go now Dominico, see you soon!",

};
