string DLG_TEXT[24] = {
"......",
"......",
"Who are you and how did you find my village?",
"The Arawak chief told me to see you. He said you could help me.",
"Help? What kind of help?",
"I want your help for fighting the Dutch of the island. I’ll pay well for this work.",
"Gold?",
"Yes, I have gold for your tribe. A lot of gold...",
"Interesting... We could help you but we are not sufficiently numerous to attack the Dutch.",
"Don’t worry, I’ll come with an army. I just need an additional force to let no chance to the Dutch troops.",
"Alright. Pay us now and we’ll help you. We want 100000 gold coins.",
"What? That’s too much.",
"We won’t die for nothing, white man.",
"50000 gold coins is enough.",
"No, it’s 100000 or leave our village.",
"Well, I’ve got 50000 gold coins with me. I give you this money and I’ll pay the rest after the battle.",
"Alright. When will your army be here?",
"Over the next weeks. I’ll see you just before the siege of Oranjestad. See you!",
"You’re back. Does it mean the battle will start soon?",
"Yes, the soldiers are surrounding Oranjestad.", 
"And my money?",
"I brought the gold.",
"Alright. What do you want we do?",
"Captain Padilla, the chief of the expedition, will give you the orders. Gather your warriors, we go to Oranjestad.",
};
