string DLG_TEXT[15] = {
"......",
"......",
"Matey, don't you see I want to drink this excellent rum alone?",
"Don't worry, I'm just looking for Vassal Bethune.",
"Don't look for him because he's in front of you. What do you want?",
"I've heard you recruit pirates, and the pay is very good.",
"Yes, but not anybody. Only good fighters.",
"You're lucky because I'm a good one. I was in the Dutch army for many years.",
"Really? If you are so good as you say, my boss will be happy to meet you. But, I need to warn you - he doesn't like to be disappointed.",
"He won't be. By the way, who's your boss?",
"I can't tell you that yet. You'll know it when you meet him. Do you have a ship?",
"Yes. she's moored in the port.",
"In that case, take me to #sRedmond# if you want to meet him.",
"Alright to #sRedmond# it is.",
"We are near his house. Follow me.",
};
