string DLG_TEXT[28] = {
".....",
".....",
"Captain Bartolomeu? Can I speak with you?",
"Of course, Captain Dierman.",
"There is a problem. Captain Elting is still not back.",
"What? It's impossible to spend so much time to go and return from the cloister.",
"No doubt.",
"I'm going to look for him in the town. Let's hope he wasn't arrested by the guards. Thank you for warning me.",
"Ha! Captain! Hummm... You're alone. Does it happen anything wrong with Captain Elting?",
"Bad news. Captain Elting was arrested in the cloister by the Spanish.",
"Where is he?",
"Not in the jail but in a secret place under the church. And there is another problem, Governor Montavez knows his name and what he did in Havana.",
"So, they are going to kill him.",
"Indeed, if nothing done, tomorrow he'll be hanged.",
"Dash it! I should free him.",
"No, it's my fault if he was arrested. I asked him to go there. Tonight, I'll free him.",
"Do you need some of my men for this?",
"No, thanks. It will be a sneaky mission. I don't want to alert all the guards of this town. Remember, we still have a mission to accomplish here.",
"I know, Captain. That's why you shouldn't go there. If you are arrested, the operation against the San Felipe fort is over.",
"You're right. But, I must take the risk. I have no choice and I'm sure I can succeed.",
"As you wish, Captain. I'll wait until tomorrow noon. Afterwards, I and my men will return to Curacao.",
"I understand.",
"Congratulations Captain! You did it.",
"Thank you. Fortunately, everything went without any big incident.",
"And for me and my men?",
"You and your troops will land the fort by the sea without being detected of course. Prepare the assault waiting for the Portuguese forces on the opposite side of the fort. Remember, the Portuguese and Dutch attacks must be simultaneous to disorganize the Spanish defence. Both attacks must quickly arrive at the top of the fort to succeed the operation.",
"We did it! Now the fort is ours.",
"Yes, but for a short time. The town 's garrison must arrive soon. Let's install a long fuse in the powder warehouse. I want the fort without powder to protect our ships.",  
};