string DLG_TEXT[28] = {
".....",
".....",
"I think Governor Ogeron introduced me, Captain Bartolomeu.",
"Yes. You are his Captain, Arnaud Fontaines himself.",
"Exactly. Ready to attack the fort?",
"Before going to #sisland_Isla Muelle# we need to go to #sFalaise De Fleur#.",
"Why this detour?",
"Captain Lalliere will also participate in this expedition.",
"Very good news. It will be easier with her as well, She is er -competent- in these kinds of missions.",
"True. I already noted her ability during an expedition at Santiago on Cuba.",
"Can we go?",
"Yes, no need to waste more time in #sTortuga#.",
"Aaaahhhh...",
"Someone knocked you out. Let me help you.",
"Thank you, Captain. He attacked by surprise.",
"Who?",
"Montbars.",
"What?! Why did he do that?",
"When I saw the explosion in the fort, I immediately landed to help you. I met Montbars here saying he would ask his crew for some help. I was making to the fort, when he stunned me.",
"I understand now. He must have stolen the gold with the help of his crew.",
"He was stupid because the Brethren of the Coast will never forgive him.",
"Sure. But for now, he's got our gold.",
"We have to return to #sTortuga# and inform Governor Ogeron.",
"Indeed. It would be impossible to find Montbars right now. He must be in hiding, waiting for things to cool off.",
"If I had known, I would have killed Montbars on the Aguadilla's shore.",
"Don't think anymore, we can't change the past. Maybe a new opportunity will arise.",
"You're right. Goodbye Captain!",
"See you.", 
};