string DLG_TEXT[71] = {
"....",
"....",
"Yes?",
"Hello, I'm Dom Guillermo de la Rosa, envoy of the King. I arrived today from Spain. May I know your name?",
"My name is Lucia Montavez.",
"Montavez? Do you belong to the Governor's family?",
"I'm his daughter.",
"It is indeed a pleasure to meet you. I had no idea he had a daughter so beautiful.",
"(She blushes) Thank you. You flatter me.",
"I only speak the truth. I couldn't help but notice you seem less than enthralled with the party.",
"These functions are above all for the men. Discussing of politics, wars, and so on are not topics I care for.",
"I understand. There are certainly more pleasant things to talk about.",
"Dom Guillermo, we talked so much I didn't notice the time. It's late, I must go.",
"I'm sorry, you're right. I completely lost track of time. It must have been the enchanting company.",
"Well, I enjoyed your company tonight. Perhaps, if your envoy duties allow, you could see me tomorrow?",
"Your father wants to show me the town. I have no idea how long that might take.",
"I'll be in the residence's garden in the afternoon. Try to be there if you can.",
"I shall do my utmost. Good night, Lady Montavez.",
"Dom Guillermo! Thank goodness it's you.",
"Good afternoon, Lady Montavez. Is this man causing you trouble? I would gladly see him out for you.",
"Gentlemen, please. I don't want a quarrel here. Dom Ortega was just about to leave. Weren't you, Dom Ortega?",
"Thank you, Dom Guillermo. I appreciate your timely arrival.",
"Forgive me for interrupting your chat, but I didn't care for the way he spoke to you. Who is he?",
"Dom Sebastian Ortega, a young nobleman of Cartagena. His family rules the slave trade of this colony and is one of the richest of the Caribbean.",
"Slave trade, eh? I felt there was something unsavoury about him.",
"I don't care for his family's trade, either. Unfortunately, he believes I could be his future wife.",
"Is that something you're considering?",
"No, never. However, my father is in favour a marriage between our family and the Ortegas.",
"And he could force you to marry him, I'm guessing.",
"Unfortunately, yes. I would do anything to avoid it, but I feel the 'deadline' is approaching.",
"There is always room for optimism, Lady Montavez. Things can change.",
"I hope so. I am truly glad you decided to come and visit with me.",
"Sadly, I'm here to meet your father. He's waiting for me. He wants to continue the tour of the town.",
"As you said, things can change. Some urgent business has come up that requires my father's undivided attention.",
"I hope it isn't anything serious.",
"During lunch, he said he something about a problem with the Dutch. It seemed to upset him.",
"Did he say anything more?",
"No. He doesn't usually share the details of his work.",
"Perhaps I can be of assistance to him. My apologies, Lady Montavez, but I must see your father right away.",
"Of course, Dom Guillermo. I hope to see you again soon.",
"So do I, Lady Montavez. I would like nothing better.",
"Dom Guillermo? Is that you?",
"Lady Montavez, I hope I didn't disturb you.",
"Not at all. To what do I owe the pleasure of your visit?",
"I had some time to spare this morning, and I wondered if I might entice you to show me around Cartagena. Your father introduced me to the commercial sites, but I was hoping you could show me more interesting things.",
"[Smiling coyly] Why, Dom Guillermo! Only suitors may invite me. Are you my new suitor?",
"[Embarrassed] Oh! I didn't realise- As pleasant as that would be, I would not think of breaching protocol. I've already run afoul of Dom Ortega once.",
"Only in Dom Ortega's dreams would I marry him! I wish he had never heard my name",
"[THINKS: Good news!] But, your father's wishes...",
"Are my father's wishes alone. I will simply have to change his mind about any wedding. Optimism, just as you suggested. But enough about Dom Ortega. Wait here. There are a couple of things I need to do before our walk together.",
"So you accept- Wonderful! I promise not to budge from this spot until your return.",
"OH MY GOD! What happened to you?",
"It looks worse than it is, Lady Montavez. I was attacked by brigands. Trust me, they got the worst of it.",
"Brigands, here? I'm shocked. This is the more peaceful part of Cartagena.",
"Well, there is a first time for everything. But no matter. Would you like to take that stroll with me now?",
"We can still do that. I'm going to ask to the Captain of the guards to assign some of his men to protect us, though.",
"As you wish.",
"Thank you, Dom Guillermo, for the pleasant walk. I enjoyed being with you.",
"It was a pleasure for me, as well. I hope we'll have the chance to do it again soon.",
"Of course, why not tomorrow morning at the same time?",
"Wonderful! I shall see you tomorrow. Until then, Lady Montavez.",
"What happened, Dom Guillermo? I heard an explosion in the town, and soon after I saw the fort burning.",
"I need to tell you the truth. I'm not Dom Guillermo, the King's envoy. I'm Bartolomeu o Portugues. A pirate.",
"What are you saying these things? Is this some cruel joke at my expense?",
"No, I'm being honest with you. I've used the King's envoy's identity to infiltrate Cartagena, to do as much damage as possible.",
"You're nothing but a criminal. And you used me as a pawn. Why?",
"I'm no more a criminal than the Spanish authorities here in the Caribbean. But, Lucia, I did not use you. I couldn't. You must believe that. I- I need to know if you would consider leaving Cartagena to be with me.",
"Do you realise what you're asking of me? If I agree, it means betraying my father and my family.",
"I'm asking you to risk everything, just as I am risking everything now for you. I've fallen in love with you, Lucia. I'm praying you feel the same for me.",
"I don't know... It's all happening so fast. I need time to think.",
"I was afraid of this very thing. But I understand. And I'm sorry, I can't stay in Cartagena any longer and must sail with the tide. I'll instruct my crew to watch for you, if you decide to go with me. I pray to God this isn't the last I see of you. No matter what, know I will always treasure our time together. Goodbye, Lucia.",
};