string DLG_TEXT[26] = {
".....",
".....",
"Yes, Sir?",
"Sorry to disturb you, but we're looking for a captain.",
"That's fine, I was just leaving anyway. Does this captain have a name?",
"Charles Baxter. Do you know him?",
"Know HIM!?! Are you friends with that murdering swine?",
"It seems you do know him. Don't worry, we are not his friends.",
"I have good reason to hate that low down dirty son of a... black pirate!",
"What has he done to you?",
"He killed my son a few days ago. He was drunk when he met my son in the street. He began to provoke my son. My son just said to leave him alone. Baxter didn't like that and killed him in cold blood, without remorse or another word.",
"I bet the Governor didn't arrest him either.",
"Of course not, our good Governor is owned by Charles Baxter.",
"As I've said before, this pirate has no limits. However, I could avenge your son, if you help me.",
"I shouldn't tell you this in church, but I have been praying for someone to help make things right, to give that Baxter what he justly deserves and a bit more. The good Lord has heard my prayers.",
"Yes, yes, the Lord has sent me [Thinks: and someone who will pay], but first, I need to know if the caravel moored in the port is his ship?",
"Yes. Why do you ask?",
"I want to seize her, as well.",
"That should be easy at the moment! The fort is under repairs. An explosion occured in the powder magazine a week ago. The fort will take a few days before it is operational again.",
"Excellent! We are lucky.",
"I will pray for your success.",
"Thank you. Just before I go, could you tell me where Charles is?",
"Hard to say. Did you visit his house?",
"No. Where is it?",
"It's the house just near to the tavern.",
"Thanks. I'll avenge your son's death. It won't bring him back, but Charles will cause no more mothers to cry.",

};