string DLG_TEXT[80] = {
"......",
"......",
"Well, well, well... Welcome aboard my ship. I'm Alfonso Galindez, Commander of this small Spanish fleet. And you, who are you?",
"I'm Jorge Coelho, a simple merchant. Why did you stop my ship?",
"Simple merchant. Of course, you're joking aren't you? Do you think I'm so stupid not to recognize pirates!",
"Pirates? I think you make a mistake. Be sure I'm a...",
"Stop! despite your modifications to this ship, I'm quite sure this ship is Spanish. My soldiers are going to inspect your cargo. If you convey stolen goods, I will arrest you and you'll be charged for pirating at #sSanto Domingo#.",
"There is a misunderstanding.",
"Any problems, Sir?",
"Hello my friend, do you have a ship or boat?",
"Yes, I do. I'm fisherman. Why do you ask?",
"I need transport. I'd like to go to Boca de Hubon to meet some friends at the Buccaneer Camp.",
"Humm. And how much do you pay for this?",
"500 gold coins for taking us there and to bring us back here?",
"Not enough. I want twice that...!",
"Well, that seems a high price for some ferrying work.",
"Right. But I bet you are willing to pay this sum. You lot look like you're on the run or up to no good and that means extra risk and extra pay?",
"You're smart. Ok, 1000 gold coins for this work.",
"Join me at Boca de Yuman. In the meantime, I'll sail my Tartane there.",
"Alright.",
"Ready to go?",
"Yes. We have no time to waste!",
"Wait!",
"What's the problem?",
"I want my money now.",
"Why not wait till we get back? You've only done half of the job.",
"Yes, but I don't completely trust you. So if you want to get back to Boca de Yuman, give me all the money now.",
"Here's the money. You are very suspicious.",
"Humm. I don't have this money right now. So wait for me here, I get your pay from #sPort au Prince#.",
"Have you got my money?",
"Thanks, I'll wait for you here. But, don't take too much time at the Camp.",
"Don't worry. I'll be back soon. Just a thought : don't try to leave me here now that I've paid you. Savvy?",
"Absolutely.",
"Alright.",
"Can we go?",
"Yes, let's weigh anchor.",
"Ok, I did my job. Goodbye and thank you!",
"Thanks! And next time be less...suspicious. ",
"Hello my son, you are new to my parish? Do you need the help of God?",
"Not immediately. First, I need your help.",
"What do you mean?",
"Give me what you have?",
"WHAT! Don't tell me you are thieves! Stealing is a sin.",
"Really? What shame! I repeat : Give me what you have!",
"But I'm not a rich man. All I have are my clothes.",
"Perfect! That's exactly what I want. AMEN!",
"Wait a moment! Oh sorry Father, I didn't recognize you. What are you doing here at this hour?",
"Good evening my son. I have been summonsed by an old man in the town, he is just about to die. We came to pray in his house among his family.",
"How sad, I guess we all must departe this life sometime! Please forgive me, Father, I'll keep you no longer. And my apologies, we have orders to check everybody entering the town.",
"I understand. Thank you my son. God bless you!",
"Hey! Are you hidding a sword under your robe? What does a Priest want with that?!",
"I came to give you my blessing!!",
"Pirates?!",
"And PROUD of it!",
"Stop! Nobody can enter at this hour.",
"How dare you stop me! Are you so blind that you aren’t able to recognize an officer of your own army.",
"Ah... Sorry, Captain. Of course, this measure is only for civilians. I didn’t recognize your uniform in the dark.",
"That’s better, private. I've just been for a walk outside the walls. The night is so hot and I have been having difficulties in sleeping.",
"Captain, it’s the first time I've seen you. When did you arrive in the town?",
"Humm.. A couple of days ago onboard a ship from Havana. Well, now I have no time for any more explaining, or I'll have to go for another walk. Return to your post.",
"At your command, Captain!",
"Stop! What do you want?",
"Don’t you see? I’m bringing a prisoner.",
"At this hour?",
"Of course, he was arrested in the tavern a few minutes ago after starting a fight.",
"Another drunkard.. Alright, come in!",
"Of course, she was arrested a few minutes ago after starting a fight.",
"This is what happens when we give a weapon and rum to a woman, Haha!! Alright, come in!",
"Hello matey! What do you want to drink?",
"In fact, I want an information. I'd like to know if at the moment there is someone in your tavern that works in the fort.",
"A soldier, you mean?",
"No, a civilian. Certainly, there are no-military people working in the fort.",
"Yes, of course. I know Agilo Casamayor, he's a cook. But, he has just left my tavern.",
"Where did he go?",
"He went home.",
"Can you tell me where he lives?",
"At the first floor of a house in front of the port gates...",
"Thanks, I'm going to talk to him.",
"ALARM!!! ALARM!!!",
"Damn it!",
};