string DLG_TEXT[88] = {
"¿Cuál es nuestro beneficio?",
"¡Anamaria!",
"¡Robaste mi bote!",
"¡Aïee! En realidad....lo tomé prestado sin permiso pero con la intención de traerlo de vuelta.",
"¡Pero no lo hiciste!",
"Tendrás otro.",
"humm...",
"¿Qué me dices?",
"Sí, podemos juntar nuestro dinero para pagarle a la tripulación. ¡Sí! ¡Leven anclas!",
"Capitán, parece que tu tripulación está perdiendo la batalla. ¿No estás muy decepcionado? ¡Ha! ¡Ha!",
"Contra los inmortales. ¿Cómo podría haber sido un resultado diferente? ¡MIREN! ¡La Srta. Swann está escapando de la nave!",
"¿QUÉ?",
"No creo que tenga nada más que decir.",
"Está bien, está bien, hazlo a tu manera entonces.",
"Querido capitán, ahora no podemos permitir que eso suceda. Ven, habla con tu Anamaria un rato. ¡Estoy seguro de que se nos ocurrirá algo que hacer!",
"Eso podría ser, tal vez, pero tengo un problema. Tengo que ir a lugares, no tengo barco y casi no tengo dinero.",
"Querido, querido. Eso no servirá, ¿verdad? Pero tengo buenas noticias. Aquí está tu brújula, Barbossa dijo que no funcionó después de que él consiguió el tesoro, así que se lo vendió al dueño de la tienda, y yo lo compré barato. Aquí tienes, ¿qué más? ",
"No necesito nada más en este momento. Gracias por la brújula. [PIENSA: Barbossa no supo cómo usar mi brújula, eso son buenas noticias]", // TALISMAN - PIENSA se movió de la línea anterior
"¿Yo, querida? Sólo tengo una tartana en el puerto, pero no es de tu clase. Harías mejor en reservar un pasaje a #sisland_Redmond#. He oído que la Marina está vendiendo muy buenos barcos a bajo precio.",
"Oh bueno, gracias por la charla de todas formas, mejor me voy. [PIENSA: Una tartana podría llevarme a #sisland_Redmond# ¡Al menos!]",
"Hola Capitán. Necesito un puesto de oficial. ¿Me ayudará?",
"Sí, siempre estoy dispuesto a ayudar a una dama. Bienvenida a bordo.",
"No, lo siento, no necesito ningún oficial en este momento....",
"Gracias Capitán. No necesito un puesto, sólo buscaba a alguien con quien compartir una aventura. Me gustaría darte esta parte del mapa como muestra de mi sinceridad. Búscame en la bahía del Faro y te contaré más sobre ello.",
"¿Huh? ¡Oh! Okay. [PIENSA: No, ¡otra mujer misteriosa! ¡Necesito un trago!]",
"Entonces, Capitán, ¿qué piensas del mapa del tesoro que te di? ¿Podemos usarlo?",
"Bueno Anamaria, parece mostrar el tesoro de Cortez.",
"¡El tesoro de Cortez! ¡Se supone que es un tesoro enorme! Pero está en una especie de isla mística.",
"Sí, y la buena noticia es que tengo otra parte del mapa. Parece que ha sido dividido en cuatro partes, y tenemos dos de ellas.",
"Sí, y la buena noticia es que tengo otras dos partes del mapa. Parece que ha sido dividido en cuatro partes, y tenemos tres de ellas.",
"Creo que es una gran aventura para mí. Hazme una oferta y te contaré más al respecto.",
"Bueno, voy a buscar el resto del mapa. Te daré dos diamantes si me dices de dónde sacaste tu parte del mapa, y qué más sabes del tesoro....",
"Bueno, voy a buscar el resto del mapa. Te daré mil piezas de oro si me dices de dónde sacaste tu parte del mapa, y qué más sabes del tesoro.",
"Bueno, voy a buscar el resto del mapa. No tengo nada con lo que negociar, así que te deseo toda la suerte del mundo. Adiós.",
"Muy bien, tenemos un trato. Un pirata borracho me vendió mi parte del mapa. Dijo que pertenecía al Capitán Barbossa. Encontrar la isla no es fácil, se llama Isla de Muerte, y dicen que necesitas una brújula especial para encontrarla. También necesitarás el mapa completo o de lo contrario la cueva donde está escondido el tesoro no podrá ser encontrada.",
"Muy bien, tenemos un trato. Un pirata borracho me vendió mi parte del mapa. Dijo que pertenecía al Capitán Barbossa. Encontrar la isla no es fácil, se llama Isla de Muerte, y dicen que necesitas una brújula especial para encontrarla. También necesitarás el mapa completo o de lo contrario la cueva donde está escondido el tesoro no podrá ser encontrada.", // TALISMAN cambiado
"Gracias Anamaria. Debo irme ahora. [PIENSA: ¡Me pregunto si la brújula es la que me dio Tia Dalma!]",
"Ya he oído ese nombre antes. ¿Cómo encuentro a este Capitán Barbossa?",
"Está en #sFalaise de Fleur# en #sisland_Falaise de Fleur#. Iré hasta allí contigo.",
"Hmmm... #sisland_Falaise de Fleur#. Es una isla francesa. Necesitaré cambiar mi bandera para entrar allí y conocer a Barbossa.",
"Tendrás que hacer más que eso. Tiene un archienemigo que patrulla constantemente #sisland_Falaise de Fleur# y evita que Barbossa se vaya. Si puedes matarlo, y luego ir a ver a Barbossa, tendrás una mejor acogida.",
"Eso suena bastante fácil para mí. ¿Quién es este archienemigo y dónde puede ser encontrado?",
"Nadie sabe su nombre, sólo su nave, el Volcano. Sugiero que naveguemos hasta el extremo norte de la isla, lejos del fuerte, y luego navegar en el sentido de las agujas del reloj alrededor de la isla hasta que encontremos el Volcán...",
"...Entonces hundirla. Luego ir a ver Barbossa. OK. Vamos a hacerlo.",
"Cuidado Capitán. Si haces esto habrás pisado una telaraña, y eso podría traerte mucho dolor....",
"¿Qué quieres decir con 'pisar una telaraña'?",
"Quiero decir que hay mucha gente que quiere el tesoro de Cortéz, y tienen los oídos muy finos para escuchar a cualquiera que se mueva hacia él. Contactando con Barbossa sabrán lo que estás haciendo. Tu vida estará en riesgo si continúas.",
"¡Olvida a Anamaria, soy el Capitán Jack Sparrow! Puedo ser más listo, más inteligente y más astuto que cualquiera, así que vamos a navegar.",
"Ya veo. Tal vez debería dejarlo en paz entonces. Te haré una buena oferta y me iré.",
"Capitán... No me siento bien con esto.",
"¿Qué es lo que quieres decir?",
"La forma en que Cabanel respondió... y la forma abrupta en que se fue. Un minuto eres un héroe... al minuto siguiente te ignora. Ese hombre tiene algo en mente, o está en la telaraña y nosotros la pisamos de nuevo.",
"Tienes buen ojo. Dijiste que contactar con Barbossa podría plantear problemas. ¿Qué sugieres?",
"No vamos por la ciudad a la playa. Reabastecer el navío, hacer reparaciones, si es necesario, pero luego hay que salir de aquí y navegar. Podemos acceder a la playa desde el mar.",
"Eso suena a un plan, y Cabanel todavía nos estará observando. Lo haremos.",
"No tan rápido, Capitán. Necesitarás la brújula primero.",
"¿Brújula? Ya tengo una brújula.",
"No como esa, no. Es muy especial. No sé dónde la encontrarás, pero tienes que conseguirla primero. También he oído que un hombre llamado Cutler Beckett está buscando este mapa y esa brújula. Si te encuentras con él, ten cuidado con los rumores que dicen que es muy peligroso y que no es de fiar. Esperaré aquí en el faro a que regreses.",
"Muy bien. Iré a ver qué puedo encontrar. Adiós.",
"De nuevo aquí Capitán, ¿tiene ya la brújula?",
"Sí, lo sé. Entonces, ¿dónde se encuentra este personaje de Barbossa?",
"¿Y qué dijo entonces? ¿Te dio algo?",
"Nada... ¡absolutamente nada!",
"Entonces nos hemos perdido algo. Debe haber algo más que él quiere... Tengo una idea. Dame un día o dos y nos vemos en el faro en #sisland_Oxbay#.",
"No sé qué tienes en mente, pero te seguiré la corriente. Te veré en el faro en dos días.",
"Le vi entrar navegando. Bonito navío, pero será mejor que pasemos a las formalidades. ¿Quién es usted, señor? ¿Y a quién representa? ¿Y quién le ha enviado aquí?",
"Bueno, ve más despacio con las preguntas si quieres que te responda, querida. Mi nombre es Capitán ",
" y yo represento a la Hermandad, enviada por el Capitán Petros. Tú, supongo, ¿eres Anamaria?",
"Bien, son respuestas correctas. En efecto, lo soy. Así que, en cuanto al asunto que nos ocupa, ¿Entiendo que necesitas saber dónde reside actualmente el Capitán Nathan Kell?",
"Sí, y cualquier otra cosa que piense que pueda ayudarme será muy bienvenida.",
"Lo encontrarás aquí, está en algún lugar de #sGreenford#. Tiene una habitación secreta en algún lugar. Pero ten cuidado por donde viajas, Cutler Beckett también está en la isla y ha estado preguntando si alguien te ha visto. Y aquí está el pedazo de mapa azteca que te enviaron a recoger.",
"¡Ah! Sir Cutler, sí, él estaría interesado en mí, ¿no? Muy bien, tendré cuidado. Mientras tanto, iré a buscar al Capitán Kell, y gracias por el mapa, querida.",
"Bien. Cuando haya terminado su negocio con él, tal vez tenga la amabilidad de volver aquí y llevarme a bordo de su nave. Esta isla se está volviendo demasiado peligrosa para mí.",
"Por supuesto, querida señora. La veré pronto.",
"Capitán Jack Sparrow, me pareció oír tu voz. ¿Por qué tan triste? Parece que llevas el peso del mundo sobre tus hombros....",
"Ese cerdo de Barbossa me ha robado. Se llevó mi barco, mi dinero y mi mapa .., er, y otros objetos de valor.",
"Capitán, necesito hablar contigo.",
"¿Qué es? Tengo cosas que hacer.",
"Sé que tienes compromisos, capitán. Sólo toma esto, y cuando tengas tiempo, búscame en la Bahía del Faro. Debo irme ahora. Estoy siendo vigilada.",
"¿Qué pasa con las mujeres de esta isla? ¡Siempre tienen un lugar a donde ir!",
"Entonces, Capitán, ¿tienes el pedazo de mapa y la brújula?",
"Me gusta oir lo del mapa, pero ¿por qué necesito una brújula? ¡Tengo una brújula!",
"Ambos son muy importantes y debe ser esa brújula. Pregunta por la ciudad y puede que te lleven a la brújula y en el camino encuentres el mapa .",
"Volveré a la ciudad y veré qué puedo averiguar, y volveré aquí cuando tenga el mapa y la brújula.",
"Sí, la mala noticia es que sólo tengo este trozo, volveré cuando tenga más trozos.",
"¡Sólo necesitamos una pieza más del mapa entonces! Conseguí mi pedazo de un borracho que obtuvo el pedazo del mapa del Capitán Hector Barbossa. Tal vez deberíamos localizarlo. Encontrar la isla no es fácil, se llama Isla de la Muerte, y dicen que necesitas una brújula especial para encontrarla. También necesitarás el mapa completo o de lo contrario la cueva donde está escondido el tesoro no podrá ser encontrada.", // TALISMÁN cambiado
"Lo encontrarás aquí, está en algún lugar de #sGreenford#. Tiene una habitación secreta en algún lugar. Ten cuidado por donde viajas, Cutler Beckett también está en la isla y ha estado preguntando si alguien te ha visto.", // TALISMÁN AÑADIDO ---->
"¡Ah! Sir Cutler, sí, él estaría interesado en mí, ¿no? Muy bien, tendré cuidado. Mientras tanto, iré a buscar al capitán Kell.",

};
