string DLG_TEXT[145] = {
"Ah, Capitán ",
", no nos hemos conocido. Mi nombre es Barbossa - Capitán Barbossa - y no pude evitar escuchar su interés en el pirata fugitivo.",
"Encantado de conocerlo, Capitán. Mi interés está en la horca, no en el propio pirata, le aseguro. [PIENSA: No sé quién eres, o quién podrías ser.]",
"Sólo el ahorcamiento, ¿eh? yo sospecho que eres miembro de la Hermandad, así que quizás tu interés sea mentira",
"¿Hermandad? ¿Qué hermandad? [PIENSA: Esto podría ser una trampa... Pero también podría no serlo. Este tipo es muy astuto. Tal vez no debería haber tomado esa última taza de ron]",
"Veo que es un hombre precavido, Capitán. Muy sabio. Muy bien, le sugiero que navegue a una de las costas locales, o tal vez a una casa. Se está moviendo mucho, y lo dejaré así.",
"Le agradezco su información y me despido, por el momento.",
"¿Qué es lo que quiere decir? [PIENSA: ¡No sabe que el tesoro está maldito! Creo que le seguiré la corriente por un tiempo.]",
"Danielle",
".",
"Por fin has llegado.",
"¿Has localizado ",
"Raoul Rheims",
"?",
"Una cosa más, Capitán.",
"¿Si?",
"Vi a dos hombres caminando por #sTortuga# recientemente, y por lo que descubrí fueron una vez cañoneros de la Marina Real.",
"¿Y cómo se llaman estos hombres?",
"Pintel y Ragetti.",
"Excelente...",
"Creo que deberíamos contratar a Pintel y Ragetti antes de conseguir el tesoro, Capitán",
"¿Estás enamorada de Pintel o algo así?",
"¿Ves esa mesa cerca de la puerta? Ese es ",
"Raoul Rheims",
". Te sugiero que hables con él, antes de que desaparezca... Ahora, si me disculpas, tengo otros asuntos que necesitan mi atención.",
"Algo me dice que no querría saber lo que estás tramando. De todas formas, gracias por tu ayuda. Vamos, hablaremos más tarde.",
"He tenido contacto con él de vez en cuando.",
"¿Y dónde fue eso? ¿Dónde puedo encontrar a ",
"Raoul Rheims",
" y por qué decidiste ayudarnos.",
"Bueno, para ser precisos, Capitán, creo que usted y yo deberíamos reunirnos con ",
"Danielle",
" para estos asuntos. Creo que podríamos trabajar bien juntos y ganar mucho dinero.",
"Ya veo. Pero sigo teniendo curiosidad por Reims, ¿cómo lo encontraste?",
"¡Ah! Capitán, ",
". estoy pensando que ambos somos iguales.",
"Por favor. Ya basta con familiaridades. No sé si se puede confiar en ti.",
"Danielle",
" tenía razón sobre ti... eres demasiado sospechoso.",
"Qué ",
"Danielle",
" piensas o dices que asunto tuyo. Pero debo saber cómo conoces al hombre que buscamos y por qué decidiste ayudar ",
"Danielle",
", o responderás ante mi espada!",
"Está bien, está bien, cálmate. Conozco ",
"Raoul Rheims",
" muy bien - fuimos, por así decirlo, vecinos una vez. En cuanto a ",
"Danielle",
", He decidido ayudarla porque una vez me ayudó en una situación muy desagradable. Y como dije, Capitán, deberíamos trabajar juntos",
"Convincente. Lo comprobaré Entonces, ¿dónde dijiste ",
"Raoul Rheims",
" se está escondiendo?",
"No lo dije. Deberías hablar con ",
"Danielle",
", primero - tal vez ella tiene otros planes.",
"De acuerdo, hablaré con ella.",
", Confío en que estés disfrutando de esta hermosa isla",
"Sí, ¡mucho, gracias!",
". Pienso que es hora de que unamos nuestras fuerzas.",
"¡Huh! ¿De qué demonios estás hablando?",
"Hablo del mapa de Cortez, ese tesoro que buscas. Tengo la parte que te falta. Te daré el mapa si aceptas una propuesta que tengo.",
"Bueno, tienes mi atención. ¿Cuál sería tu propuesta, entonces?",
"Me tomas como tu primer oficial, y navegamos a por el tesoro de Cortez y dividimos el botín entre nosotros.",
"¿Qué quieres decir?",
"Capitán, tienes una buena, buena nave. Tienes la orientación que nos llevará directo al tesoro de Cortez. Tengo la parte que falta en el mapa y conozco las aguas de esos mares. Así que navega conmigo por el tesoro de Cortez.",
"¿Cuáles serían tus condiciones?",
"Ah Capitán, cincuenta, cincuenta. Justo en el medio. Esa es mi forma de trabajar. La mitad para ti y la otra mitad para mí y luego seguimos nuestro camino. Tú puedes seguir tu camino y yo navegaré hacia el sol. ¡Los dos libres y limpios, y muy, muy ricos!",
"Haces que parezca muy fácil. ¿Consigo la mitad del tesoro de Cortez y luego soy libre de terminar mis otros asuntos?",
"La vida es simple, Capitán, si lo piensas bien. Ambos obtenemos oro fácil y tú puedes hacer lo que quieras después. ¿Qué dices entonces?",
"Bien, hagámoslo. Primero iremos por el tesoro de Cortez. Pero yo soy el capitán de esta empresa. Eso que quede claro.",
"Capitán, Capitán. Estaré encantado de servir como su oficial, pero para hacer las cosas justas debería darme la dirección de la Isla de la Muerte. Así podremos confiar el uno en el otro porque ninguno puede trabajar sin el otro, ¿verdad?",
"Ya veo lo que dices. Sé a dónde vamos, y tú tienes la parte del mapa que quiero. De acuerdo. Te daré la orientación tan pronto como embarquemos en la nave.",
"¡Excelente! Capitán. ¿Qué le parece si terminamos la charla y nos vamos a navegar. Tenemos que ir a la Isla de la Muerte antes de que cambie el tiempo. Aquí está la parte del mapa que necesitas. ¡Ja! ¡Ja! Estamos en camino de ser ricos, muy ricos de hecho.",
"Muy bien. Embarquemos sin más demora.",
"Estoy pensando que cuando esté completamente equipado, con una brújula adecuada, podríamos navegar tras un tesoro.",
"¡Oh! pues volveré, para entonces.",
". Tenemos que hablar. Creo que nuestra situación ha cambiado.",
" Es hora de que nos separemos. Ya no necesitaré tu ayuda. Tengo tu brújula, y necesito TODO el oro. Es mucho mejor que la mitad, y este navío me servirá bien.",
"Tú, perro traidor... Te atravesaré aquí mismo donde estás.",
"¿Tu dedo es tan afilado, Capitán? Parece que ha dejado sus armas en su camarote, así que está en cierta desventaja.",
"¡MALDITA SEA! Nunca debí haber confiado en ti. ¡No tienes un hueso decente en tu cuerpo!",
"No seas tan poco amable, capitán. No soy tan malo. Te daré una pistola y una bala para que puedas cazar para comer,... o... volarte los sesos si te sientes muy solo en la encantadora isla en la que te dejaré. Tal vez puedas usarla para hacer una señal a un barco. ¡HA! ¡HA! ¡HA! Entretanto, navegaré de vuelta a la Isla de la Muerte por el tesoro.",
"¡No! ¡Creo que me la quedaré para atravesar tu malvado corazón cuando nos encontremos de nuevo!",
"No nos volveremos a ver, Capitán, esta isla está lejos de los puntos clave de las rutas comerciales. Verás pasar los barcos, pero ninguno desembarcará. Nadie te encontrará, así que adiós... y mantén tu pólvora seca. ¡HA! ¡HA! HA! Navegue hacia los hombres de la isla, no demasiado cerca, creo que puede nadar la última milla.",
"¡Disfruta de la vida mientras puedas perro! ¡Y no olvides de que nos volveremos a encontrar!",
"¡Apártese de mi vista! ¡Está en mi camino!",
"¿Eh? Muy cierto.",
"¿Cómo diablos saliste de esa isla?",
"Cuando me abandonaste en esa tierra olvidada por Dios, te olvidaste de una cosa muy importante: soy capitán ",
"Bueno, no cometeré ese error de nuevo.",
"¿Qué pasó mientras estaba inconsciente?",
"El amante de la señorita Swann logró liberarla y lograron escapar, llevándose el medallón con ellos. Llegaron a su barco y luego ellos y la tripulación del escorbuto zarparon. Pero, cuando te haya matado, lo perseguiré en el #scursed_ship#.",
"¿Cuándo entenderás que somos inmortales y que no tienes ninguna posibilidad contra nosotros? Hemos hundido el Interceptor, capturado a su tripulación y tenemos a la Srta. Elizabeth como nuestra prisionera. Y tu amigo herrero no está en ninguna parte. Así que ahora podemos regresar a la Isla de la Muerte y levantar la maldición.",
"¡No es posible!",
"¡No es probable!",
"Lo siento mucho, pero no puedo atenderte ahora mismo. Tengo algunos asuntos que atender primero con el Sr. Turner.",
"¿No quieres hacerlo?",
"No, creo que si.",
"Su funeral.",
"De acuerdo. ¿Por qué no quieres hacerlo?",
"Porque el HMS Dauntless, orgullo de la Armada del Rey, está flotando justo en la costa esperándote.",
"¡Disparen a los marineros!",
"Pero tengo una solución. Ordene a sus hombres que remen hasta el Dauntless, ellos hacen lo que mejor saben hacer. Entonces tendrás dos barcos. Tomarás el más grande como tu buque insignia y me nombrarás Capitán del #scursed_ship#. Puedes presentarte como el Comodoro Barbossa. ¿Entiendes? ¿Qué te parece?",
"Huumm ... interesante ... ¡Estoy de acuerdo!",
"¿Qué están haciendo mis hombres? ¡Están tardando demasiado! Ya deberían haber regresado del Dauntless. ¿Intentas engañarme?",
"¿Por qué piensas eso? (coges una moneda maldita)",
"¿Qué es lo que haces? ¡Ya basta! ¡Voy a matarte, traidor!",
"¡Ah! ... un plan sin duda, pero tiene un defecto.",
"Un defecto, por cierto, y ¿qué podría ser?",
"Bueno, la sangre de la chica no quitó la maldición, ¿verdad? Ella no es la que quieres.",
"En efecto... Lo repito, y por supuesto sabrás de quién es la sangre que necesito.",
"Puede que sí... y puede que no. Sé que necesitas el medallón primero, y si me matas, no estarás seguro de a quién buscas, ¿verdad?",
"Muy astuto, ",
", muy inteligente. Que así sea. Navegarás con nosotros mientras te perseguimos. A los hombres del barco, a la nave.",
"Ahora estamos hablando.", 
"¡Ah! Si, ",
", hablando yo, ¡y mirando también! Estarás guiando el camino de vuelta al Pearl. Te estaré vigilando todo el camino, así que nada de trucos.",
"No, nada de trucos. Necesitamos encontrar el Interceptor.",
"Muy bien, Sr. Turner. Acepto sus términos y ahora está obligado a cumplirlos. Liberaré a la tripulación del Interceptor en pequeños botes. Son buenos marineros, así que llegarán a tierra. En cuanto a la Srta. Swann y el querido capitán, conozco un lugar agradable donde pueden pasar las horas. ¡HA! HA! ¡HA!",
"Er, Will. ¡Desearía que hubieras sido un poco más específico con tus términos!",
"[Will Turner] ¡ESPERE!",
"La orientación no te ayudará. No encontrarás la isla de esa manera, necesitarás que te lleve allí. Zarpemos y te llevaré directamente a ella. Después de todo, ambos estaremos en el mismo barco, así que no me iré sin ti, ¿verdad?",
"Como usted diga, Capitán. ¿Qué le parece si terminamos la charla y nos vamos a navegar? Tenemos que ir a la Isla de la Muerte antes de que cambie el tiempo. Aquí está la parte del mapa que necesita. ¡Ja! ¡Ja! Estamos en camino de ser ricos, de hecho muy ricos.",
"¿Esto es todo entonces? ... La famosa Isla de la Muerte? ... Entonces, ¿dónde cavamos?",
"Todavía no, todavía tenemos un camino por recorrer para encontrar el tesoro.",
"Que hermosa vista Capitán, esto hace estimular mi corazón.",
"Sí, se ve bastante bonito, ¿no? Será mejor que vayamos a buscar a la tripulación para empezar a cargar.",
"¡Ah! Tenemos un problema, Capitán. Creo que nos ha seguido un escuadrón de navíos británicos. Nos hundirán con seguridad y todo estará perdido.",
"¡QUÉ! ¿Por qué no dijiste algo antes de que navegáramos?",
"No quería preocuparle, capitán. Después de todo no estaba seguro, pero tengo un plan para sacarnos de aquí.",
"Más vale que sea algo bueno. Tú nos metiste en este lío. Así que... ¿Qué es?",
"Izamos la bandera portuguesa antes de zarpar. No dispararán por ello, pero pueden detenerse y registrarnos. Así que si dejamos el tesoro aquí por ahora, y navegamos a #sGrand Cayman#, siendo un puerto británico, eso disipará todo tipo de sospechas.",
"Así que dejamos el tesoro por ahora, navegamos como portugueses, y si nos paran no encontrarán nada y nos dejarán ir. Entonces podemos volver más tarde cuando el escuadrón se haya ido. ¿No es así?",
"Más inteligente que nunca, Capitán. Tan listo como siempre. Sí, y siendo portugueses podemos desembarcar en #sisland_Cayman# sin problemas y volver en un día o dos.",
"Bien. Eso suena a buen plan. Vámonos.",
"¿Ve lo que yo veo, capitán?",
"Parece que ya llegamos. Echemos un vistazo más de cerca.",
" el hombre que nos libró de ese villano Blunden de negro corazón.",
"Esperaba que su muerte fuera personalmente de mayor importancia para usted.",
"¡Ja, ja! Suena como si estuvieras buscando una recompensa, querido Capitán.",
"Yo... bueno... no exactamente. Quiero decir, er... no el dinero, esperaba que tuvieras parte de un mapa... o algo.",
"Capitán, no tengo mapas para vender o regalar, así que le deseo una buena navegación. Buen día.",
"¿Eso es todo?",
"Sí, Capitán, como usted dice... Eso es todo. Ahora déjeme con mis pensamientos, si le parece bien.",
"¡Oh! ... Buen día entonces.",
 
};