string DLG_TEXT[80] = {
"ЎCantemos juntos una canciуn de marineros!",
"...",
"ЎAh, aquн viene ahora nuestro oro! Ven conmigo, no iremos lejos.",
"De acuerdo.",
"Espere aquн, y traerй a nuestro prisionero.",
"Simplemente date prisa.",
"Dinero en efectivo - ЎAsн es como hacemos negocios aquн!",
"Aquн estб tu oro, hombre gracioso.",
"Quй gracioso. ЎNo serнa una risa si me quedara el oro para mн y os masacrara a ti y a tus amigos como cerdos que sois!",
"Es un placer tratar contigo.",
"Me encantarнa que te fueras.",
"їQuй? ЎNo tienes suficiente dinero! Tratando de engaсarnos, їEh? ЎMuere!",
"ЎMaldiciуn!",
"Ves, eso no es tan gracioso. Yo matarнa a nuestro invitado antes de que tu espada limpiara su vaina. Entonces nadie se reirнa.",
"Estб bien, estб bien. Algunas personas no tienen sentido del humor. Aquн estб tu dinero.",
"ЎBuenos dнas! Buen Capitбn, un centavo, o una pieza de oro fino, o ron, medio barril.",
"Aquн estб tu centavo, mi hombre. Espero que ayude.",
"Aquн hay una pieza de oro mi hombre. Gбstala sabiamente.",
"De alguna manera no creo que seas el pobre borracho que pretendes ser. їCuбl es tu historia?",
"No me hagas perder el tiempo, viejo bribуn, probablemente tienes mбs dinero que yo.",
"---",
"---",
"ЎAh! Capitбn, parece que usted puede ser la persona que he estado buscando.",
"Bueno, despuйs de haber olido tu mal aliento, no creo que estй buscando a gente como tъ despuйs de todo.",
"En efecto, їy quй te hace pensar eso?",
"Habнas pensado que si realmente era un borracho, el casero me habrнa echado hace horas.",
"ЎHmmm! Algo asн, debo admitir. Entonces, їpor quй has estado buscбndome a mн en particular?",
"No eres tъ, en particular, sino alguien que es astuto y tiene ingenio.",
"Bueno, creo que podrнa encajar en esa descripciуn. Entonces, їpodemos ir al grano?",
"Muy bien. Si estбs dispuesto a correr un poco de riesgo, hay una damisela, digamos, 'en apuros' que podrнa necesitar la ayuda de un joven y fuerte capitбn como tъ. їEstбs dispuesto a hacerlo?",
"No, creo que no. Las damas siempre parecen meterme en problemas. Asн que te deseo un buen dнa.",
"ЎLas damas en apuros son una especialidad mнa! їQuй tengo que hacer?",
"Como quieras, mi valiente capitбn. La dama en cuestiуn ha estado escuchбndonos hablar, y me acaba de seсalar que cree que tъ podrнas ayudarla. Se acaba de escabullir afuera y te estarб esperando detrбs de la taberna. Ve ahora, y reъnete con ella allн.",
"ЎMuy intrigante! Irй a conocer a esta misteriosa mujer tuya. [PIENSA: Podrнa haber alguna oportunidad en esto.]",
"Como quieras, mi audaz capitбn. Me encargarй de que no fracases. Sube al barco del contrabandista y navega a #sTortuga#.",
"Gracias, sй que esto va a ser rбpido. Prуxima parada #sTortuga#.",
"La aventura de Jack Sparrow es la que has buscado. Sуlo sъbete a tu barco y navega a ese puerto.",
"Navegarй hacia allн desde aquн. No llevarб mucho tiempo.",
"Un largo viaje, mi capitбn, esa es una buena manera de navegar. Te he dado comida para que tu bъsqueda no falle.",
"ЎAh! Gracias. Cuando me despierte estarй en el muelle del puerto de #sisland_Turks#.",
"Buen Capitбn, harй lo que me pidas. Irбs a #sTortuga#, lo cual no es una tarea fбcil.",
"Asн que necesito encontrar al Sr. Gibbs cuando llegue allн.",
"Parece que vas a necesitar mi ayuda de nuevo, Capitбn.",
"ЎOye! їTe mueves? їQuй estб pasando aquн? Nada tiene sentido hasta ahora.",
"Paciencia, capitбn, paciencia... Este no es el lugar para hablar. Vamos arriba.",
"Mбs vale que sea bueno. їY puedes dejar ese disfraz de mendigo borracho? Se enreda, ya sabes.",
"Sй que estбs confundido, pero tenнamos que estar seguros de que eras el indicado para el trabajo.",
"ЎTrabajo! їQuй trabajo? Y sн, estoy confundido.",
"Sabes por quй estoy aquн, amigo. їPodemos ir al grano?",
"No me hagas perder el tiempo, viejo bribуn, probablemente tienes mбs dinero que yo.",
"Sй por quй estбs aquн, sabes que soy el mejor. Solo asegъrate de que lo dices en serio y no lo has adivinado. їHas preestablecido tus niveles, equipamiento y todo? Si no, mi querido capitбn, caerбs en el lodo.",
"ЎUy! Lo siento, no, esto no es lo que querнa. Adiуs.",
"Sн... Estoy probando las aguas. Si sabes lo que quiero decir.",
"Entonces, mi hermoso Capitбn, їa dуnde irбs? Solo dime tu deseo, y asн lo harй.",
"Me quedarй aquн mismo, gracias y verй quй sucede.",
"Necesito probar el motнn con Barbossa.",
"Quiero empezar por ir a #sTortuga#, donde me encuentre con Anamaria.",
"Quiero navegar a #sisland_Redmond# para una 'Entrada a lo Grande'.",
"Quiero ir con Norrington a #sisland_Turks# para la lнnea de misiones alternativa de CotBP.",
"Yo quiero ir a #sTortuga#, donde recojo un equipo y encuentro el #scursed_ship#.",
"Como desee, mi valiente capitбn, pasa por delante de la flota. Navega hasta el Faro, y encontrarбs a Barbossa.",
"Gracias Billy. Lo intentarй.",
"Como desees mi audaz Capitбn. Me encargarй de que no fracases. Sube a bordo del barco del contrabandista y navega a #sTortuga#.",
"Gracias, sй que esto va a ser rбpido. Prуxima parada #sTortuga#.",
"Bueno, bueno, bueno... Capitбn ",
" en persona. Eres un pequeсo percebe persistente, їno?",
"Digamos que soy un percebe que no vas a raspar, pedazo de alga podrida.",
"Palabras duras para un joven tan joven. Supongo que has venido a rescatar a estas encantadoras hermanas. Desafortunadamente es hora de la realidad, asн que saca tu espada.",
"Ha llegado tu hora, Brock. Despнdete.",
"Me gustarнa ir al regreso de las hermanas en #sisland_Oxbay#.",
"Me gustarнa ir a examinar el cofre del hombre muerto.",
"Quiero navegar a #sisland_Redmond# para una 'Entrada a lo Grande'.",
"La aventura de Jack Sparrow es la que has buscado. Sуlo salta a tu barco y navega a ese puerto. No te olvides del querido viejo Henry, eso estarнa bien. Para que la bъsqueda funcione, debes hablar con йl dos veces.",
"Quiero la primera escena de motнn.",
"OKAY. Espera un momento.",
"Quiero probar la escena de la tormenta.",
"Luego navega a la Bahнa del Faro desde aquн.",
"Quiero probar a Ragetti y a Pintel.",
"Bien, entonces, navega hasta #sTortuga#.",
"їQuй hay de esa iglesia en Isla Cruces? ЎDйjame verla!",

};