string DLG_TEXT[80] = {
"¡Cantemos juntos una canción de marineros!",
"...",
"¡Ah, aquí viene ahora nuestro oro! Ven conmigo, no iremos lejos.",
"De acuerdo.",
"Espere aquí, y traeré a nuestro prisionero.",
"Simplemente date prisa.",
"Dinero en efectivo - ¡Así es como hacemos negocios aquí!",
"Aquí está tu oro, hombre gracioso.",
"Qué gracioso. ¡No sería una risa si me quedara el oro para mí y os masacrara a ti y a tus amigos como cerdos que sois!",
"Es un placer tratar contigo.",
"Me encantaría que te fueras.",
"¿Qué? ¡No tienes suficiente dinero! Tratando de engañarnos, ¿Eh? ¡Muere!",
"¡Maldición!",
"Ves, eso no es tan gracioso. Yo mataría a nuestro invitado antes de que tu espada limpiara su vaina. Entonces nadie se reiría.",
"Está bien, está bien. Algunas personas no tienen sentido del humor. Aquí está tu dinero.",
"¡Buenos días! Buen Capitán, un centavo, o una pieza de oro fino, o ron, medio barril.",
"Aquí está tu centavo, mi hombre. Espero que ayude.",
"Aquí hay una pieza de oro mi hombre. Gástala sabiamente.",
"De alguna manera no creo que seas el pobre borracho que pretendes ser. ¿Cuál es tu historia?",
"No me hagas perder el tiempo, viejo bribón, probablemente tienes más dinero que yo.",
"---",
"---",
"¡Ah! Capitán, parece que usted puede ser la persona que he estado buscando.",
"Bueno, después de haber olido tu mal aliento, no creo que esté buscando a gente como tú después de todo.",
"En efecto, ¿y qué te hace pensar eso?",
"Habías pensado que si realmente era un borracho, el casero me habría echado hace horas.",
"¡Hmmm! Algo así, debo admitir. Entonces, ¿por qué has estado buscándome a mí en particular?",
"No eres tú, en particular, sino alguien que es astuto y tiene ingenio.",
"Bueno, creo que podría encajar en esa descripción. Entonces, ¿podemos ir al grano?",
"Muy bien. Si estás dispuesto a correr un poco de riesgo, hay una damisela, digamos, 'en apuros' que podría necesitar la ayuda de un joven y fuerte capitán como tú. ¿Estás dispuesto a hacerlo?",
"No, creo que no. Las damas siempre parecen meterme en problemas. Así que te deseo un buen día.",
"¡Las damas en apuros son una especialidad mía! ¿Qué tengo que hacer?",
"Como quieras, mi valiente capitán. La dama en cuestión ha estado escuchándonos hablar, y me acaba de señalar que cree que tú podrías ayudarla. Se acaba de escabullir afuera y te estará esperando detrás de la taberna. Ve ahora, y reúnete con ella allí.",
"¡Muy intrigante! Iré a conocer a esta misteriosa mujer tuya. [PIENSA: Podría haber alguna oportunidad en esto.]",
"Como quieras, mi audaz capitán. Me encargaré de que no fracases. Sube al barco del contrabandista y navega a #sTortuga#.",
"Gracias, sé que esto va a ser rápido. Próxima parada #sTortuga#.",
"La aventura de Jack Sparrow es la que has buscado. Sólo súbete a tu barco y navega a ese puerto.",
"Navegaré hacia allí desde aquí. No llevará mucho tiempo.",
"Un largo viaje, mi capitán, esa es una buena manera de navegar. Te he dado comida para que tu búsqueda no falle.",
"¡Ah! Gracias. Cuando me despierte estaré en el muelle del puerto de #sisland_Turks#.",
"Buen Capitán, haré lo que me pidas. Irás a #sTortuga#, lo cual no es una tarea fácil.",
"Así que necesito encontrar al Sr. Gibbs cuando llegue allí.",
"Parece que vas a necesitar mi ayuda de nuevo, Capitán.",
"¡Oye! ¿Te mueves? ¿Qué está pasando aquí? Nada tiene sentido hasta ahora.",
"Paciencia, capitán, paciencia... Este no es el lugar para hablar. Vamos arriba.",
"Más vale que sea bueno. ¿Y puedes dejar ese disfraz de mendigo borracho? Se enreda, ya sabes.",
"Sé que estás confundido, pero teníamos que estar seguros de que eras el indicado para el trabajo.",
"¡Trabajo! ¿Qué trabajo? Y sí, estoy confundido.",
"Sabes por qué estoy aquí, amigo. ¿Podemos ir al grano?",
"No me hagas perder el tiempo, viejo bribón, probablemente tienes más dinero que yo.",
"Sé por qué estás aquí, sabes que soy el mejor. Solo asegúrate de que lo dices en serio y no lo has adivinado. ¿Has preestablecido tus niveles, equipamiento y todo? Si no, mi querido capitán, caerás en el lodo.",
"¡Uy! Lo siento, no, esto no es lo que quería. Adiós.",
"Sí... Estoy probando las aguas. Si sabes lo que quiero decir.",
"Entonces, mi hermoso Capitán, ¿a dónde irás? Solo dime tu deseo, y así lo haré.",
"Me quedaré aquí mismo, gracias y veré qué sucede.",
"Necesito probar el motín con Barbossa.",
"Quiero empezar por ir a #sTortuga#, donde me encuentre con Anamaria.",
"Quiero navegar a #sisland_Redmond# para una 'Entrada a lo Grande'.",
"Quiero ir con Norrington a #sisland_Turks# para la línea de misiones alternativa de CotBP.",
"Yo quiero ir a #sTortuga#, donde recojo un equipo y encuentro el #scursed_ship#.",
"Como desee, mi valiente capitán, pasa por delante de la flota. Navega hasta el Faro, y encontrarás a Barbossa.",
"Gracias Billy. Lo intentaré.",
"Como desees mi audaz Capitán. Me encargaré de que no fracases. Sube a bordo del barco del contrabandista y navega a #sTortuga#.",
"Gracias, sé que esto va a ser rápido. Próxima parada #sTortuga#.",
"Bueno, bueno, bueno... Capitán ",
" en persona. Eres un pequeño percebe persistente, ¿no?",
"Digamos que soy un percebe que no vas a raspar, pedazo de alga podrida.",
"Palabras duras para un joven tan joven. Supongo que has venido a rescatar a estas encantadoras hermanas. Desafortunadamente es hora de la realidad, así que saca tu espada.",
"Ha llegado tu hora, Brock. Despídete.",
"Me gustaría ir al regreso de las hermanas en #sisland_Oxbay#.",
"Me gustaría ir a examinar el cofre del hombre muerto.",
"Quiero navegar a #sisland_Redmond# para una 'Entrada a lo Grande'.",
"La aventura de Jack Sparrow es la que has buscado. Sólo salta a tu barco y navega a ese puerto. No te olvides del querido viejo Henry, eso estaría bien. Para que la búsqueda funcione, debes hablar con él dos veces.",
"Quiero la primera escena de motín.",
"OKAY. Espera un momento.",
"Quiero probar la escena de la tormenta.",
"Luego navega a la Bahía del Faro desde aquí.",
"Quiero probar a Ragetti y a Pintel.",
"Bien, entonces, navega hasta #sTortuga#.",
"¿Qué hay de esa iglesia en Isla Cruces? ¡Déjame verla!",

};