string DLG_TEXT[149] = {
"Habla con otro capitán.",
"Claro que sí.",
"¿Qué es lo que quieres?",
"Me resultas algo familiar... ¿Eres el pirata francés que la East India Trading Company está buscando? ¿Capitán Chevalle?",
"No puedes ayudarme y yo no puedo ayudarte.",
"Ah, ya veo. Entonces no hay necesidad de que me quede aquí, ¿eh?",
"¿Y qué si lo soy?",
"Yo soy ",
", capitán del '",
"Entonces muy bien. Sí, soy Chevalle. Y también he oído hablar de ti. Tú también eres un pirata, ¿verdad? Tal vez puedas ayudarme con algo.",
"¿Qué tienes en mente?",
"Tengo que salvar a mi tripulación.",
"No lo entiendo. ¿Qué le pasó a tu tripulación para que tengas que salvarlos?",
"Hace unas semanas, conocí a un pirata inglés en un viaje de saqueo. Decidimos enfrentarnos a algunos barcos ingleses, en medio de la batalla, mi compañero empezó a atacar mi barco. Mi compañero no era un pirata como yo, sino un oficial de la Compañía Comercial de las Indias Orientales, con la tarea de capturarme. Intenté luchar para salir de esto, pero al mismo tiempo mi intendente se volvió en mi contra, él se quedaría con el barco si ayudaba al oficial a capturarme. Entonces me capturaron y nos pusieron a mí y a mi leal tripulación en la bodega de mi propio barco, en #Redmond# nos llevaron a la cárcel. Me las arreglé para escapar, cuando nos llevaron allí, pero mi tripulación fue encerrada. ¡Sacre Bleu!",
"Deberías estar contento de salir de allí. ¿De verdad tienes intención de volver?",
"Mi tripulación son mis amigos. No los dejaré. Sólo necesito algunos hombres y un barco para rescatarlos.",
"Ah, ya veo. ¿Y qué clase de beneficio hay para mí?",
"Puede que sea famoso, pero no soy un pirata rico. Aunque salve a mi tripulación, no podré conseguir otro barco. Sin embargo, no tengo la intención de dejar de piratear y estoy seguro de que mis compañeros me seguirán dondequiera que vaya. Tenemos mucha experiencia en estas aguas, así que podríamos unirnos a tu tripulación.",
"No es una mala propuesta, mon meilleur capitaine. Es un trato. Zarpemos para #sRedmond#.",
"Lo siento, amigo. No me interesa.",
"¡Fantástico! Estoy seguro de que no te arrepentirás de tener un par de manos adicionales a bordo, monsieur.",
"Espero que así sea.",
"¡Esta isla está infestada de casacas rojas!",
"En efecto. Los ingleses tienen patrullas por todas partes. ¡Lleguemos a la ciudad rápidamente! No tengo intención de quedarme aquí más tiempo del necesario.",
"¡Rápido! Vienen los guardias ingleses. Deben pensar que somos contrabandistas.",
"O te vieron revolcándote en la cubierta del barco. Te dije que te quedaras bajo cubierta. ¡Prepárense para pelear!",
"¡Oye! ¿Quién eres?",
"Mi nombre es ",
". Soy un comerciante y he venido aquí para vender algunos productos a su tendero. Me está esperando.",
"Tengo que comprobar su afirmación con el tendero. ¡Espere aquí!",
"¿Por qué tales precauciones? Esta es la primera vez que tengo que ser revisado cuando entro a un pueblo para vender algunas mercancías.",
"Cuando los piratas son colgados en público, tenemos que controlar la identidad de todos los extranjeros, señor.",
"¿Un ahorcamiento? ¿Quién va a bailar con Jack Ketch entonces, eh?",
"Los miembros de la tripulación de un tal Capitán Chevalle. Es un pirata muy peligroso y lo mismo ocurre con su tripulación.",
"¿Cuándo van a ser colgados? ¿Y dónde?",
"Hoy al mediodía frente a la iglesia. Pero parece que tienes mucho interés en ese ahorcamiento. ¿Conoce a estos piratas? Si es así, infórmeme y arreglaré una cuerda para un ahorcamiento más.",
"¡No hay tiempo que perder, Capitán! Estos soldados no nos dejarán pasar pronto, así que debemos luchar para entrar",
"Vámonos antes de que aparezcan más guardias. No tenemos mucho tiempo, es casi mediodía.",
"Estoy de acuerdo. Sólo espero que no lleguemos demasiado tarde.",
"Mis hombres están en el patio de la iglesia, esperando la ejecución.",
"Los veo.",
"Entonces, ¿cuál es tu plan?",
"Voy a tener una pequeña charla con el verdugo.",
"*Tono sarcástico* ¿Y en el improbable caso de que no deje ir a mis hombres?",
"Normalmente funciona bien. Pero si no, dejaré que mi cuchilla hable. Mientras me ocupo de él, deberías atacar a los soldados.",
"No será fácil.",
"Lo sé, pero ¿qué opción tenemos?",
"¿Qué estás haciendo aquí?",
"Quiero tener una mejor vista de la ejecución.",
"Te gusta presumir, ¿verdad? ¡Veamos cómo te lucirás sin tu cabeza!",
"Estás muy feliz de matar, ¿no? El verdugo debe haber sido la perfecta elección de carrera para ti. Desafortunadamente, esa carrera pronto terminará.",
"¡Ja! ¡Mis hombres casi empezaban a pensar que los dejaría morir con los ingleses! ¡Pero espera! ¿Dónde está Jean-Bart?",
"No tenemos tiempo para hablar ahora mismo. Debemos irnos ahora. Seguro que vendrán más soldados.",
"¡Lo hicimos! ¡Escapamos! No fue tan difícil.",
"No, no lo fue. Eso es lo que me preocupa. Fue demasiado fácil salir de la ciudad.",
"No te preocupes, sé feliz, mon ami!",
"¡Mira! ¡Una patrulla de soldados ingleses! Eso no me hace feliz, prefiero una botella de ron. ¡Prepárate para otra pelea!",
"Tenías razón. No estábamos a salvo todavía. Esperemos que sea la última vez que veamos a los soldados ingleses. He visto suficientes casacas rojas para toda la vida.",
"Será mejor que salgamos de esta isla rápidamente. Volvamos al barco.",
"Creo que ahora estamos a salvo. ¿Podemos hablar un poco? Tengo un favor más que pedirte.",
"Déjame adivinar. ¿Jean-Bart?", 
"Exactamente. Jean-Bart Lafin es mi mano derecha. Según uno de mis tripulantes, se escapó de camino a la cárcel.",
"Ya veo. ¿Pero dónde está ahora?",
"Le dijo a la tripulación que quería llegar a #sisland_Aruba#. Dijo que buscaría un barco y dejaría #sRedmond#.",
"Si vamos a encontrar a dicho miembro de la tripulación, será mejor ir a #sisland_Aruba# y ver lo que podemos encontrar allí. Tal vez algún marinero en el puerto lo haya visto. Pero será mejor que vayamos allí rápidamente antes de que lleguen noticias de nuestras hazañas.",
"(Unos minutos después) ¡Mis hombres están a bordo!",
"Bien. Fijemos un rumbo.",
"Muchas gracias. Todos mis hombres están rescatados ahora. Ahora todo lo que tenemos que hacer es salir de aquí.",
"En efecto. ¿Qué tal si vamos a #sisland_Quebradas Costillas#? A Jean-Bart parece gustarle #sisland_Quebradas Costillas#.",
"Eso sería genial, capitán. Las #sQuebradas Costillas# es mi pied-a-terre. Me encantaría ir allí antes de que comencemos nuestra mutua campaña de asaltos.",
"¿Una campaña de asalto? Parece que tienes bastantes planes. ¡Me parece bien!",
"¡Hola, capitán!",
"¿Te conozco?",
"Probablemente no. Pero imagino que conoces a mi jefe.",
"Tal vez. ¿Quién es él?",
"Lord Beckett, el jefe de la EITC aquí en el Caribe.",
"Ah. Esperaba que ya nos hubiéramos librado de los ingleses. Pero aquí estamos, supuestamente a salvo en #sQuebradas Costillas#, y todavía seguimos enfrentados con los soldados.",
"Te das cuenta muy rápido. Estas afueras están rodeadas por mis hombres, así que no intenten escapar. Tú y tu amigo nos seguirán a nuestro barco y te entregaremos a Lord Beckett.",
"No estoy muy entusiasmado con tu plan, amigo. Si peleamos contigo ahora, tendremos una oportunidad de sobrevivir. Si nos rendimos y te seguimos hasta mi viejo 'amigo' Beckett, seguro que nos ahorcan.",
"Como quieras, entonces. ¡Prepárate para morir!",
"Eso no suena tan amistoso.",
"Espero que sea la última vez que oigamos hablar de ese Beckett.",
"Yo también, pero eso no lo contarás.",
"Parece que finalmente terminamos nuestra misión de rescate. Muchas gracias por tu ayuda. Entonces, ¿quieres que me convierta en tu oficial o no?",
"Por supuesto. Ese era el trato, ¿no? ¡Hay tanto que podemos hacer todavía juntos! ¡Y me gusta el sonido de esa campaña de saqueo!",
"Eso no será necesario. Sigue tu propio camino e intenta conseguir una nave para ti, sólo hay lugar para un capitán en mi nave.",
"¡Excelente! ¡Vamos a saquear este archipiélago!",
"¡No tengo ninguna duda de eso, amigo!",
"Como quieras. Buena suerte, monsieur. Tal vez te vea de nuevo algún día.",
"Tal vez. ¡Buena suerte para ti también!",
"Lo siento, capitán.",
"¿Sobre qué? ¿Sobre que me dejaste y de repente te escapaste? ¡Más vale que tengas una buena explicación para eso!",
"No te pongas nervioso, capitán. Déjame contarte una historia. Hace años fui el orgulloso capitán del mejor barco que he capitaneado, una veloz carabela llamada 'Santiago'. Intercambié mucho con Bucaneros en esos días y la velocidad de 'Santiago' me permitió escapar de cualquier soldado que intentara capturarme. Un día estaba en el campamento de Bucaneros en #sisland_Hispaniola#, junto con la mayoría de mi tripulación, cuando mi enemigo jurado, el mercenario inglés Pedro Rivera, tomó mi barco.",
"Quieres decir 'requisado'. Término náutico. En cualquier caso: Escuché mucho sobre ese barco tuyo, pero no sobre ese hombre que perseguiste en la tienda.",
"Cuando yo y mi tripulación llegamos a la orilla, el 'Santiago' solo estaba fondeando. Cuatro miembros de la tripulación de Pedro Rivera estaban a punto de remar de regreso al barco con algunos de mis productos descargados. Los capturamos antes de que pudieran llegar a la nave.",
"¿Y ese era uno de los hombres que capturaste?",
"Exactamente. No pudieron ayudarme a encontrar a su capitán o a mi barco y se negaron a quemarropa a unirse a mi tripulación, así que no me sirvieron de nada y los dejé ir de nuevo. No me gusta matar a nadie si no tengo que hacerlo.",
"Pareces ser un buen tipo para ser un pirata. Pero supongo que quieres recuperar tu barco y crees que este hombre podría haberse reincorporado a la tripulación de Pedro Rivera para saber dónde está tu barco",
"Correcto de nuevo. Nada me gustaría más que estar de pie en la cubierta de mi querido 'Santiago' una vez más, con la rueda en mis manos y el viento y el rocío del mar en mi cara.",
"Hablaré con el marinero discretamente e intentaré sacarle información. Puede que te reconozca si te ve, así que intenta ser discreto.",
"Te dejaré dirigir mi nave de vez en cuando. Y un día te daré un barco mejor que el 'Santiago'. Pero no creo que sea una buena idea empezar una búsqueda inútil por todo el Caribe para localizar tu barco perdido.",
"Eso realmente no nos llevó más lejos, ¿verdad?",
"Al menos no te reconoció. ¿Y no te diste cuenta de que dijo que el barco en el que navega no estaba en el puerto? Un capitán ordinario siempre anclaría su barco en el puerto, bajo la protección de los cañones del fuerte.",
"¿Así que has averiguado algo?",
"Sí. El burdel está cerrado porque uno de los invitados hirió a una de las damas. Podría ser nuestro hombre. Así que voy a visitar la cárcel y hablar con él.",
"¿Has hablado con el hombre de la cárcel? ¿Es el navegante que buscamos? ¿Y qué hay de mi barco?",
"Hablé con él y de hecho es el hombre que estábamos buscando. Lo convencí de que nos ayudara y hasta ahora ha sido muy útil. ¡Le gustará saber que Pedro Rivera está en Anse Casse-bois y también el 'Santiago'!",
"¡Es una muy buena noticia! ¿Así que vamos a ir allí ahora mismo? ¡No puedo esperar a conocer a mi buen amigo Pedro! Tiene una cita urgente con el extremo afilado de mi cuchillo.",
"¡Calma, Bartolomeu! ¿Qué pasó con tu reticencia a matar a alguien?",
"¡Haré una excepción con la escoria que me robó el barco!",
"Hay 140 hombres a bordo del 'Santiago'. ¿Propones que nos encarguemos de todos ellos? ¿Sólo nosotros dos? No lo creo. No quiero que me maten, ni tengo intención de perder a ningún miembro de la tripulación en un abordaje a gran escala.",
"¿Buenas o malas noticias?",
"Las dos cosas. La mala noticia es que tuve que pagar mucho dinero. La buena noticia es que valió la pena. El navegante ha sido liberado. Iré a verlo ahora en la cárcel y le explicaré la primera parte de mi plan. Iremos a la taberna después para arreglar la segunda parte.",
"Ahora entiendo tu plan, pero ¿realmente tenemos que esperar aquí? Hemos estado aquí afuera por horas. ¿Por qué no vamos a conocer al navegante?",
"Sólo necesito comprobar que el navegante hizo su parte. De lo contrario, no tiene sentido tratar de tomar la nave. ¡Sígueme!",
"¡Míralos! Parece que tienen bastante prisa. ¡No pueden resistirse a la llamada del ron gratis!",
"Sí. Estos borrachos no sabrán lo que les ha pasado cuando sepan que su barco no está mañana. Vamos a la plantación ahora. Pijuan debería estar allí esperándonos.",
"Eso nos ahorra dos hombres para luchar a bordo del barco. Finalmente puedo ver mi 'Santiago' de nuevo. Estoy impaciente por estar en su cubierta de nuevo. Ha pasado demasiado tiempo.", 
"Estoy bastante ansioso por llegar allí también. ¿Te gusta nadar, Bartolomeu?",
"No, en realidad no. Pero por mi nave haré una excepción.",
"Muy bien. Vámonos.",
"¡No! ¡Espera! Pedro es mi enemigo, no el tuyo. Lucharé yo contra él.",
"Entiendo, Bartolomeu. ¡Pero ten cuidado!",
"¡Esta escoria se merecía lo que le esperaba! Muchas gracias por tu ayuda, capitán. ¡Nunca pensé que volvería a ver al 'Santiago' de nuevo!",
"¡Bien hecho, Bartolomé! Ahora veo de dónde viene ese dicho portugués! Iré a tierra para encontrarme con Pijuan. Me reuniré contigo más tarde.",
"¿Así que estás diciendo que podría ser un miembro de la tripulación de un barco pirata?",
"En efecto. ¡Quizás incluso un tripulante del 'Santiago'! Haremos una visita al burdel y veremos si podemos conseguir que ese navegante nos ayude más.",
"Entonces tienes un plan diferente.",
"En efecto, lo tengo. Pero no va a funcionar sin la ayuda del navegador. Todavía está en la cárcel, así que necesito hablar con el gobernador para sacarlo de allí.",
"¡Bonjour capitán! Lo siento por salir corriendo como lo hice, pero me enteré de que el Capitán Villanueva estaba en #sTortuga#.",
"Ahora está bien, Capitán, sobre todo porque sé que hay dinero de por medio",
"¡Es mi país el que está insultando!",
"...",
"¡Deje de insultar a mi país!",
"Entonces puedo ir y tomar el barco con François.",
"Capitán, sería mejor no perder más tiempo. Puede ir a su nave. Nos uniremos a ustedes.",
"Muy bien.",
"Ahora, sabemos que la isla no está desierta.",
"Sí y parece ser peligroso. Tenemos que estar en guardia. Sigamos con nuestro paseo.",
"El puerto parece estar en calma. Sin embargo, hay un barco francés en el puerto, 'La Licorne'. Parece tener poca tripulación.",
"...",
"La plata está cargada Capitán.",
"¡Genial! Vamos a navegar para #sTortuga#. Tenemos negocios que hacer allí.",
"Capitán, creo que debería tomar el mando del barco, ya que es un barco francés...",
"Um...",
"(Deja de luchar) ¿Adónde fue, capitán?",
"El barco está ahora bajo el mando de los hombres de François y está navegando para unirse a nuestros barcos.",
"Incluso si lo fuera, ¿esperarías que lo admitiera ante una persona que no es miembro de los Hermanos de la Costa?",
"Tienes razón. Si recuerdo bien, es posible unirse a ellos en el asentamiento pirata de #sisland_Quebradas Costillas#. Podría pensar en hacer eso.",

};
