string DLG_TEXT[95] = {
"Bienvenido, ",
". Considйrate en casa, amigo mнo - Ўy piensa en mн como en una familia!",
"Uh... sн. Gracias. Yo soy ",
".",
"Hola, ",
"! ",
".",
"Bueno, ahora - Ўmira quiйn se ha quedado a la deriva en la marea! Me alegro de verte, ",
".",
"Es maravilloso tenerte aquн, ",
". їQuй puedo ofrecerte hoy?",
"Necesito algunos hombres fuertes para ayudar en mi barco. Prefiero inteligentes, pero me conformarй con tranquilos.",
"Espero que tengas un momento para hablar.",
"Necesito una habitaciуn. Una limpia.",
"їTiene un montуn de paja gratis en este granero?",
"Lo siento. Estaba a punto de salir, ",
". Te verй por ahн.",
"Oh, se asegurarб de ello usted mismo, seсor ",
". Mi nombre es ",
". Soy el dueсo de esta humilde taberna.",
"Necesito contratar una tripulaciуn, ",
".",
", hablemos...",
"їTienes una habitaciуn que pueda usar? ",
"Me gustarнa quedarme aquн por un tiempo.",
"Puede que te haga una visita mбs tarde.",
"Por supuesto. їDe quй le gustarнa hablar, Capitбn ",
"?",
"Un tipo amigable como usted seguramente escucharб muchos rumores interesantes. Me gustarнa saber quй estб pasando estos dнas.",
"Hay algo en mi mente...",
"їSi?",
", un hombre llamado ",
"Ewan Glover",
"Ewan Glover",
" dijo que me esperarнa aquн.",
"Necesito un trabajo. їNo conoces a ningъn niсo rico en esta isla que tenga miedo de viajar solo?",
"Buenos dнas. їEn quй puedo ayudarle?",
"Estoy buscando a un joven espaсol. Su nombre es Lucas Da Saldanha. Tal vez lo haya visto.",
"Ya sabes, ",
", Te verй en otro momento.",
"Si es asн, йl prefiere navegar con menos satйlites, ya lo sabes.",
"Sн, lo olvidй. Muy bien, volverй mбs tarde, cuando tenga menos naves, ha-ha.",
"No quiero ayudarlos, han causado muchos problemas a mi paнs",
"Sуlo mira a este patriota. Bueno, adiуs",
"Tus manos cubiertas de sangre. No pienses seriamente que alguien viajarб contigo",
"ЎTienes razуn, todo el mundo me tiene miedo! ЎJa, ja!",
"Viniste justo a tiempo, un comerciante de aquн estaba buscando la compaснa adecuada para viajar, serб mejor que hables con йl. Aquн estб, entrando en la taberna ahora.",
"Lo harй.",
"No, no hay nadie para ese momento, tal vez la prуxima vez.",
"Hm, entonces esperarй.",
"Interesante. Por cierto, estoy buscando aсadir algunas espaldas fuertes a mi tripulaciуn.",
"Me gustarнa hablar con usted, si tiene un momento.",
"Lo siento, me voy, ",
". Estoy seguro de que te verй de nuevo.",
"Por favor, cuando quiera.",
"Necesito aсadir algunas espaldas fuertes a mi tripulaciуn.",
"їTienes un momento para hablar?",
"Lo siento, ya me iba, ",
". Nos vemos.",
"Sн, de hecho, estuvo aquн. ",
"Ewan Glover",
" recientemente saliу con alguna u otra dama. Si puedes quedarte, ",
", Estoy seguro de que volverб pronto.",
"Gracias. Esperarй aquн.",
"Oh, este lugar generalmente estб lleno de hombres dispuestos a zarpar en el barco correcto. Pero ya es tarde. Comenzarбn a vagar por la maсana \nїQuizбs te gustarнa alquilar una habitaciуn y esperar?",
"Estб bien. їTienes una habitaciуn libre?",
"Puede que lo haga, pero primero tengo otras preguntas.",
"Tengo una o dos habitaciones. їCuбnto tiempo espera quedarse?",
"Hasta maсana.",
"Sуlo hasta esta noche.",
"Bien, bien. Serбn 5 piastras.",
"Me parece justo. Aquн tienes.",
"Eso es demasiado caro para mi sangre. Supongo que pasarй la noche en el salуn comъn con los otros pobres y tacaсos.",
"їQuй obtengo por eso їmi propia bailarina? No importa. No serб la primera vez que pase una noche en una taberna.",
"Lo pensarй.",
"Te costarб 5 monedas de oro.",
"Muy bien, aquн estб tu dinero",
"Eso es mбs de lo que me importa pagar por una noche de alojamiento. Si es necesario, apoyarй mi cabeza en una de las mesas de la taberna.",
"їQuй obtengo por eso? їMi propia bailarina? No importa. No serб la primera vez que pase una noche en una taberna.",
"Lo pensarй un poco. Hablemos de otra cosa.",
"ЎCaballeros, por favor! ЎDetengan esto de inmediato o llamarй a la guardia!",
"Estб bien. Relбjate. Me voy.",
"Sн, lo recuerdo. Un buen tipo, y un buen cliente... siempre pagу generosamente.",
"їSabes dуnde estб ahora?",
"No estoy seguro donde fue, pero es posible que pueda decirte por quй se fue...",
"Por favor, hбgalo. ЎEs vital que lo sepa!",
"Bueno, se rumorea que el joven espaсol tratу de pasar el tiempo con la hija de la gobernadora Silehard. No sй lo que pasу, pero vino aquн despuйs con el mбs negro de los humores. A la maсana siguiente, йl y su velero se habнan ido, y nadie lo ha visto desde entonces.",
"їLa hija del gobernador? El hombre tiene buen gusto, їno? їHay alguna posibilidad de que pueda hablar con ella, o Silehard la vigila demasiado de cerca?",
"Oh, puedes estar seguro de que cuando no la estб vigilando, alguien de su paga lo hace por йl. Bueno, йl tiene sus razones, їno? Es una chica muy guapa. Ocasionalmente da un paseo fuera de la ciudad, pero siempre es escoltada por varios guardias.",
"Esos guardias no deberнan ser un problema - no tengo la intenciуn de secuestrarla ni nada, sуlo hacer algunas preguntas. Gracias, Charles, has sido de gran ayuda.",
"Se suponнa que me encontrarнa con Lord Beckett aquн, pero parece que no puedo encontrarlo. їLe has visto ъltimamente?",
"ЎAh! Su seсorнa tuvo algunos negocios en una de las otras islas. Volverб en un dнa o dos. No me preocuparнa ",
"Pero tengo algo para йl, y habнamos arreglado esta reuniуn.",
"Relбjese Capitбn, йl volverб. Sуlo sigue con tus otros asuntos por ahora.",
"Muy bien, lo harй.",
};