string DLG_TEXT[117] = {
"¡Ah! ¡Un nuevo visitante en mi taberna! Bienvenido, ",
"¡ La mejor hospitalidad del archipiélago está a su disposición!",
"Hola. Mi nombre es ",
".",
"Gracias. Mi nombre es ",
".",
"De nada. Por favor, siéntese, beba un buen ron, ¡pruebe una de mis especialidades! Se alegrará de hacerlo.",
"Me alegro de volver a verte, ",
". Tome cualquiera de las mesas libres y descanse sus huesos.",
"¡Oh, eres tú! No te he visto en años. ¿Puedo empezar con un vaso de vino para mojar el silbato?",
"Si le da lo mismo, me gustaría ir directamente a los negocios.",
"El tiempo es corto, amigo, y tengo asuntos serios que discutir.",
"Lo siento. Estoy demasiado ocupado para la hospitalidad en este momento.",
"Cálmate. Sólo pasé a ver quién estaba aquí; ya me voy.",
"Encantado de conocerte, ",
". Mi nombre es ",
".",
"Por supuesto, ",
", eres el jefe. ¿En qué puedo ayudarte?",
"Estoy buscando añadir a mi tripulación. ¿Podría indicarme quién podría estar buscando trabajo?",
"Las recientes batallas me han dejado sin mano de obra. Necesito encontrar algunos chicos que estén buscando un trabajo.",
"Me gustaría hablar de negocios.",
"¿Tiene una habitación disponible? Me gustaría quedarme aquí por un tiempo.",
"Estoy buscando una habitación limpia con una cama limpia. Nada más y nada menos.",
"No tengo tiempo para hablar ahora mismo. Pasaré más tarde.",
"Lo siento, estoy ocupado ahora. Pero volveré para charlar cuando esté libre.",
"¡Claro! ¿Y qué negocio es ese?",
"Estoy buscando a un caballero que quizás conozca. Me temo que no sé su nombre, pero sé que ha estado estudiando las lenguas nativas locales.",
"Estoy buscando a un caballero que quizás conozca. Me temo que no sé su nombre, pero sé que ha estado estudiando las lenguas nativas locales.",
"Estoy buscando a un hombre llamado ",
"Raoul Rheims",
"Raoul Rheims",
". ¿Sabes si ha estado en la isla?",
"Tiene a ",
"Ferro Cerezo",
" ha estado aquí recientemente?",
"Necesito encontrar ",
"Ferro Cerezo",
". ¿Lo has visto?",
"¿Qué dicen sobre el secuestro de este sacerdote local?",
"Me gustaría saber si cierto hombre ha estado aquí. Su nombre es Nigel Blythe, y parece un completo bribón.",
"Necesito algo de trabajo. ¿No conoces a ningún niño rico en esta isla que tenga miedo de viajar solo?",
"Sabes, ahora que lo pienso, no tengo ningún negocio.",
"¡Jaja! Parece que te ha molestado lo suficiente si hablas de él de esa manera.",
"Eso es cierto. Pero no respondiste a mi pregunta. ¿Estaba aquí o no?",
"Sí, sólo unas horas antes de que vinieras. Habló con un hombre.\nSegún recuerdo, discutieron, pero luego encontraron un interés común.",
"¿Has oído algo más? ¿Dónde se ha ido?",
"No lo sé. Pero el muchacho con el que hablaba es de aquí... lo he visto antes.",
"¿Dónde? ¡¿Dónde vive?!",
"¡Cálmese! Vive en una casa justo detrás de mi taberna. Cuando salgas de la taberna verás puertas que conducen a un pequeño patio. Y el hombre es un muchacho gordo con ropa de cuero.",
"¡Ese es el tipo que necesito! Gracias.",
"¡Toda la colonia está hablando de ello! ¡Imagínese irrumpir en una iglesia a plena luz del día y secuestrar al Padre! Y desaparecieron antes de que nadie pudiera hacer nada.", // --> edited by Cat for Animists Quest fix
"¿Quiénes eran? ¿Hombres con máscaras?",
"No. Por lo que he oído, sólo eran los degolladores habituales. Pero es curioso que menciones las máscaras...",
"¿Gracioso? ¿Por qué?",
"No hace mucho tiempo, un hombre apareció aquí con una máscara.",
"¿En serio? ¿Qué quería?",
"¿Por qué es tan importante para ti? No estoy seguro de que deba compartir su negocio con otros clientes.",
"Creo que podría estar conectado con el secuestro del sacerdote. Quieres ayudar con eso, ¿no?",
"Sí, supongo que sí. Muy bien, hace tres semanas, este hombre apareció, vestido con una máscara. Fue muy cortés, especialmente para los estándares de hoy en día. Nunca le dijo una mala palabra a nadie. Se llamaba a sí mismo un semental.",
"Semental, ¿hmm? Continúa.",
"Bueno, los ciudadanos de aquí no estaban muy seguros de él, pero nunca hizo nada malo - sólo pasó mucho tiempo hablando con los jóvenes del lugar - y eso no fue tan malo. Por una vez, parecían menos interesados en meterse en problemas.",
"¿Y después?",
"Y entonces ... sucedió algo. Ahora todos los chicos jóvenes se preparan para salir de la ciudad en una campaña con él. El hijo del tonelero se peleó con su padre y se fue de casa. El tonelero estaba bastante enojado por eso, y fue a hablar con nuestro hombre misterioso - pero pronto salió corriendo de la casa del hombre como si mil demonios estuvieran detrás de él.\nEsa misma noche el tonelero tomó un poco de ron de tripa podrida en algún lugar, se emborrachó horriblemente y terminó ahogado. ¿En qué estaba pensando, caminando por el muelle de noche, cuando apenas podía caminar? Y, ¿sabe una cosa? A su hijo no parecía importarle.",
"Eso es extraño, de hecho. ¿Dónde puedo encontrar a este muchacho?",
"¿El hijo del tonelero? Él vagará por la ciudad en alguna parte. Ha estado suelto desde que desapareció el hombre con túnica.",
"Lo encontraré. ¿Cómo se llama?",
"Jordano",
"es su nombre. Un chico guapo, como su padre, el pobre. Echaremos de menos al tonelero; era un buen hombre.", // <-- edited by Cat for Animists Quest fix
"Gracias.",
"Por supuesto, ",
". De hecho, está sentado en la mesa allí.",
"Gracias.",
"Por supuesto, ",
". Estuvo aquí, pero recientemente ha navegado a #sConceicao#.",
"Gracias.",
"Raoul Rheims",
"? El nombre me suena familiar, pero hace tiempo que no lo oigo. Siento no poder ser de más ayuda.",
"No te preocupes por eso. Tendré que seguir buscando. Déjame preguntarte algo más.",
"Desgraciadamente, no puedo ayudarte.",
"Lamento oír eso. Tal vez has visto a la dama llamada ",
"Danielle",
"Danielle",
"?",
"Sí, lo he hecho. Se pasó por aquí hace unos minutos. Parecía disgustada, aunque no le pregunté por qué.",
"Bien. Tal vez todavía pueda alcanzarla.",
"Es bastante tarde para eso. Tendrás mejor suerte si vuelves por la mañana. O tal vez te gustaría pasar una noche en la taberna.",
"Tal vez lo haga. ¿Tiene una habitación libre?",
"Tal vez lo haga. Pero déjame preguntarte algo más primero.",
"Tengo una habitación disponible. ¿Cuánto tiempo planea quedarse?",
"Hasta mañana.",
"Sólo hasta el anochecer.",
"Bien. Te costará 5 monedas de oro.",
"Está bien. Aquí tienes.",
"En ese caso, me temo que mi cartera y yo pasaremos una noche en el salón común.",
"No, gracias. Si ese es el precio, ahorraré algunas monedas y pasaré una noche en el salón común.",
"Tal vez más tarde. Déjame preguntarte sobre algo más.",
"Bien. Te costará 5 monedas de oro.",
"Está bien. Aquí tienes.",
"En ese caso, me temo que mi cartera y yo pasaremos una noche en el salón común.",
"No, gracias. Si ese es el precio, ahorraré algunas monedas y pasaré una noche en el salón común.",
"Lo pensaré. Gracias.",
"¡Por favor! ¡Detén esta locura de una vez! ¡No me hagas llamar a los guardias!",
"¡Está bien! Me voy a ir.",
"Si existe una persona así, es posible que prefiera evitar llamar la atención con tantos compañeros, como espero que sepa.", 
"Sí, lo olvidé. De acuerdo, volveré más tarde, cuando tenga menos barcos ¡JaJa!.",
"No quiero ayudarte, con todo el daño que le has hecho a mi país.",
"Sólo mira a este patriota. Bueno, adiós.", 
"Tus manos están cubiertas de sangre. ¿En serio crees que alguien viajará contigo?",
"Tienes razón. Todos me tienen miedo. Qué divertido.",
"Llegaste justo en el momento adecuado. Un comerciante de aquí estaba buscando la compañía adecuada para viajar. Deberías hablar con él. Aquí está, entrando en la taberna.",
"Lo haré.",
"No, no hay nadie en quien pueda pensar en este momento. Tal vez la próxima vez.",
"Hmm. Entonces esperaré.",
"He oído que has capturado a un pirata. ¿Cuándo es el ahorcamiento? Siempre disfruto de un buen ahorcamiento. ¡Bebidas para todos!",
"¡Bah! Se escapó, ¡Esos tontos que se hacen llamar carceleros!, pero los soldados lo encontrarán pronto.", 
"Bueno, al menos no me he perdido nada todavía. Guarda esos tragos para más tarde, amigo.",

};
