string DLG_TEXT[28] = {
"Estamos navegando... Estamos navegando...",
"Te gusta mucho esa canción, ¿verdad?",
"¿Quién eres tú?",
"Un amigo del Capitán Petros y Sir Christopher Mings.",
"¿Y quiénes son ellos?",
"Miembros de la Hermandad.",
"¡Ah! Así que al menos no son enemigos. ¿Qué estáis haciendo aquí?",
"El Capitán Petros nos dijo que vinieramos a rescatar a un pirata capturado. ¿Dicho pirata sería usted entonces?",
"Sí, aunque ya no estoy capturado. Bueno, debo decir que fue un gran gesto de su parte. ¿Puedes sacarme de aquí?",
"Esa es la idea, amigo, a menos que quieras quedarte y disfrutar de las vistas. Esto es el Caribe después de todo. Por cierto, ¿tienes una parte de un viejo mapa?",
"Lo tenía, pero me lo quitaron cuando me capturaron.",
"¡Maldita sea! Bueno, es inevitable, supongo.",
"Sí, he oído que un capitán llamado Barbossa se lo compró a los guardias. Ahora lo tiene, así que debe saber algo sobre a dónde lleva.",
"¡Barbossa! Vaya, vaya. He tenido el placer de conocerlo.",
"¿Qué deberíamos hacer al respecto entonces?",
"Nada por ahora. Vamos a llevarte de vuelta a Petros primero. Tendré el placer de tratar con Barbossa más tarde.",
"Lo último que oí fue que estaba en Jamaica. El problema es que es una isla inglesa, y no hay manera de que podamos navegar allí bajo la bandera pirata, a menos que tengamos algo de ayuda.",
"¿Qué ayuda es esa entonces?",
"Le pediré a otros miembros de la hermandad que se unan a nosotros. De esa manera tendremos una flota propia. Podemos intentar tomar el pueblo, o desembarcar en una playa desierta. Todo lo que tenemos que hacer después de eso es encontrar a tu hermana. Haz lo que necesites ahora, nos encontraremos en el muelle.",
"Eso parece bastante lógico. Me prepararé para navegar.",
"¿Estás listo para navegar entonces?",
"Sí, estamos listos. Vamos.",
"Bueno, debo decir que fue un gran viaje. Aunque será mejor que sigamos con el asunto que tenemos entre manos. No podemos quedarnos aquí mucho tiempo, los navíos del Rey pronto estarán sobre nosotros. Ahora estás por tu cuenta. ¡Buena suerte!",
"¡Oh! Sí, lo entiendo. Supongo que deberíamos ir a la Taberna para ver qué podemos averiguar",
"No, no. Tengo contactos aquí, ya sabes. Somos parte de la misma banda de hermanos, por así decirlo. Necesitas encontrar a XXXXXXXXXXX y mencionar mi nombre.",
"¡Oh! Ya veo. Bueno, espero que todos regresen a salvo.",
"Lo haremos.",
"Adiós, y gracias.",
};