string DLG_TEXT[117] = { 
"Me han dicho que se ha esforzado mucho para solicitar una audiencia. Mi nombre es ",
". Ahora, por favor, dígame el propósito de su visita, ",
".",
"Mi nombre es ",
".",
"Ah, eres tú otra vez. ¿Qué te trae por aquí esta vez? ",
"Me gustaría hablar con usted sobre algunos negocios.",
"Lo siento, pero hay cosas que tengo que hacer.",
"Entonces, ¿por qué me distraes de los asuntos de estado más importantes?",
"Me gustaría hablar con usted sobre un pequeño negocio.",
"Sólo estoy aquí para presentar mis respetos. Nada más, ",
"En ese caso, por favor deje mi estudio y déjeme volver a asuntos más importantes.",
"Sí, por supuesto. Siento haberle molestado.",
"Le escucho, ",
".",
"Estoy aquí para obtener mi recompensa por la muerte de Dirty Garry.",
"Lo siento, pero no tengo nada de que hablar ahora mismo",
"Oh, he oído hablar de lo que has hecho. En nombre de toda la colonia le muestro nuestro agradecimiento.",
"Así es, me gustaría ver una recompensa.",
"Eres tan bromista. Ja, ja. Aquí está tu dinero.", 
"Gracias, soy su humilde servidor.",
"Así que, sobre la apuesta que hiciste... tras conseguir la aprobación de nuestro departamento de impuestos veo que tenemos... déjame ver... seis mil.",
"¿Qué? ¡El trato era de 10 mil!",
"No puedo ayudarte. En el futuro, trata de estar más calmado.",
"Lo que usted diga, señor. Sucio cerdo...",
", ¿es consciente de que está acusado de asesinato? Se le vio cerca del cuerpo de la víctima. ¿Qué dice en respuesta a esta acusación?",
"No tiene nada que ver conmigo. ¡El hombre ya estaba muerto cuando entré en la habitación! Me dijeron que sólo estaba herido, y que podría tener alguna información importante para mí.",
", Me acaban de decir que un hombre fue capturado cuando intentaba salir de la ciudad con un cuchillo manchado de sangre en su poder. Confesó el asesinato del que se le acusaba. Puede quedar libre inmediatamente.",
"Gracias. Sabía que podía confiar en la justicia aquí en #sConceicao#.",
"Deseo desertar a Portugal.",
"¿En serio? Muy bien, ahora eres ciudadano portugués.",
"Le agradezco su infinita amabilidad, señor.",
"¿Oh, sí? Tengo una propuesta para usted, capitán.",
"¿En serio?",
"Me he enterado de que ha completado la tarea con éxito; ¡mis felicitaciones, capitán! Aquí está su recompensa.",
"Gracias, fue un placer ayudarles.",
"Debe destruir el ",
" Buque ",
"de guerra pirata",
" amenazando el envío ",
". Si la hundes, te recompensaré con la gran suma de ",
" oro. ¿Qué dice usted, capitán?",
"No volverá a oír hablar de ella, eso se lo prometo.",
"Me temo que no puedo ayudarle.",
"Anhelo el perdón, su Excelencia.",
"Estoy interesado en informarme sobre las relaciones de Inglaterra con otras naciones.",
"Estoy buscando una carta de marca.",
"Ah, ",
", qué bueno de su parte pasar por aquí. Me gustaría presentarle a mi ",
". Ella vendrá una vez que hayamos terminado el negocio.",
"He oído que me van a ascender.",
"Ya no puedo servir a ",
", su Excelencia.",
"Estoy harto de servir ",
"Como seguro de que usted es un capitán capaz, y para recompensar mi tiempo en la presentación de su caso a ",
", Debo pedirle ",
" Oro.",
"De ninguna manera.",
"Muy bien.",
" siempre se complace en aceptar nuevos capitanes a su servicio. ",
"Actualmente estamos en guerra con ",
"",
"no hay un gran poder, pero ",
". Por supuesto, ",
"Los piratas siempre deben ser hundidos al verlos.",
" En vista de su servicio anterior, ",
" le concede el rango de ",
"Haré que se sienta orgulloso, su Excelencia.",
"Has dañado a ",
", y ",
" no se olvida de sus enemigos. ¡Váyase de inmediato, o los guardias le echarán por las orejas!",
"...",
"Usted ha causado ",
" gran daño, capitán, pero ",
" está dispuesto a pasar por alto tus transgresiones pasadas... por un precio: ",
"Muy bien, señor. Acepto.",
"Un placer tratar con usted, ",
"Y usted, su Excelencia.",
"¡En efecto, así es! Excelente trabajo. Su nuevo rango es ",
". Además, se le concede ",
" acres de tierra por orden de ",
"Gracias, señor.",
"Esté seguro de que, ",
" lamentará perder su servicio.",
"Sí, lo estoy.",
" no se toma a bien a los traidores, ",
"Uh, no importa.",
"Muy bien. Pero espero que lo reconsidere, con el tiempo...",
"Adiós, ",
"¿Eh?",
"Difícil.",
"Bueno, tengo una misión si estás interesado.",
"Tal vez. ¿Qué es exactamente?",
"Hace dos meses, un convoy de barcos mercantes británicos partió a #sisland_Cayman# para navegar a #sisland_Antigua#. Mi hija, Elizabeth, estaba a bordo de una de las naves. El convoy nunca llegó. Después de un mes envié a mi mejor capitán a buscarla. Pero luego no he oído ninguna noticia del 'Relámpago'.",
"¿Entonces quiere que busque tanto la fragata como el convoy? ¿Por qué no envía otro barco propio?",
"Desafortunadamente, no tengo los recursos militares para prescindir de otra de mis naves. Con #sisland_Cayman# siendo una pequeña colonia, mi gente me despreciaría si comprometiera la seguridad de la colonia por una causa personal.",
"Muy bien, señor. Ahora vamos a las cosas que importan. ¿Cuánto me pagará si traigo de vuelta a su hija?",
"No puedo permitirme más de 40000 monedas de oro.",
"Eso me parece bastante bien. Acepto su oferta. Pronto tendrá noticias mías.",
"Lo siento, Gobernador, pero tengo que declinar. No puedo dedicar el tiempo necesario para tal esfuerzo.",
"¡Muchas gracias! Por favor, haga que encontrar a mi hija sea su mayor prioridad, capitán.",
"Haré lo que pueda, señor.",
"Lo entiendo, capitán. Espero encontrar otro corsario dispuesto a hacer el trabajo.",
"La mejor de las suertes, gobernador.",
"¡Gracias a Dios! ¡Trajiste a mi hija de vuelta!",
"En efecto, Gobernador, ¡pero el pirata que secuestró a su hija también vino aquí!",
"Un oficial me informó de la llegada del barco pirata hace unos minutos. Por favor, Capitán, ayude a mis soldados a repeler al enemigo. Mientras dure la lucha, voy a esconder a Elizabeth en una habitación secreta de la residencia.",
"Sabia decisión, señor. ¡Voy al puerto ahora mismo!",
"¡Felicidades Capitán! Hizo un trabajo fantástico.",
"Gracias señor, fue una misión peligrosa.",
"¡Claro! Elizabeth me habló de Davy Jones. Ese Pirata parece ser el Diablo. Afortunadamente, gracias a ti, no volverá pronto.",
"Eso creo, Gobernador. Ahora que la misión está cumplida, tengo otras prioridades, pero antes podríamos hablar de la recompensa.",
"Por supuesto. Como acordamos, aquí están las 40.000 monedas de oro. Gracias de nuevo y adiós Capitán.",
"Adiós Gobernador.",
"...",
"...",
"Hace algún tiempo, un convoy de barcos mercantes británicos partió a #sisland_Cayman# para navegar a #sisland_Antigua#. Mi hija, Elizabeth, estaba a bordo de una de las naves. El convoy nunca llegó. Después de un mes envié a mi mejor capitán a buscarla. Pero luego no he oído ninguna noticia del 'Relámpago'.",

};
