string DLG_TEXT[234] = {
"Dame un centavo y evitarás que llore, ", // SJG All dialogue changed here for Jack Sparrow Story
" ¡Dame algo de oro y evitarás que me muera!",
"Sé lo de Davy, la Mancha y el Kraken. ¡Sé sobre los Piratas y a quiénes están atacando! Podría contarte algunas historias, cómo los fantasmas pueden tocar al hombre, sobre el tesoro, la bruja y el maldito Holandés Errante. Así que dame una moneda, sólo una o dos, hazme una pregunta y mira cómo lo hago",
"Oh ",
", ayudar a un pobre mendigo, nunca se sabe, podría decirte algo que te sirva bastante .",
"Lo siento, no doy limosnas, sobre todo a los malos poetas mendigos",
"No tengo nada más pequeño que una pieza de oro. ¿Será suficiente una para evitar que te mueras de hambre por un tiempo?",
"No te daré una limosna -- pero te haré ganar algo de dinero si estás dispuesto.",
"Gracias, ",
"! Serás un hombre con suerte, ya verás. ¡Cuidado con el viejo Davy, el lugar y el barco!",
"Sí, claro. Tienes tu moneda. Ahora, deja los acertijos y la poesía y respóndeme algunas preguntas.",
"Gracias. Ya puedes irte.",
"No hay dinero para Henry, ",
"Seas pobre o malo. Cuidado, en estas aguas, el Kraken ha sido visto. ",
"(Devolver.)",
" Henry sabe mucho, es pobre pero es inteligente. Al responder a preguntas, es el mejor en el arte, ",
", Haz tu pregunta y te atenderé bien. Henry puede hablar hasta bien entrada la noche.",
"¿Conoces bien el pueblo?",
"¿Has oído alguna palabra del gobernador de #sRedmond#?",
"¿Sólo puedes hablar con acertijos? No debería perder mi tiempo haciendo preguntas a un mendigo.",
"Lo siento, ",
" Henry es pobre y no posee mucho, ¿Qué podría decirte que no tienes. \n Sus preguntas son desconcertantes, lo encuentro bastante difícil. Para buscar una respuesta, intente preguntarle al guardia.",
"Puede que tengas razón. No debería perder mi tiempo haciendo preguntas a un mendigo.",
"No estoy preguntando a nadie más ahora mismo. Te lo estoy preguntando a ti, y para con las rimas, me estás rallando el coco",
"No hay dinero para Henry, ",
" eres pobre o eres malo, ten cuidado, en estas aguas, una bruja será vista. ",
"(Devolver.)",
" El conocimiento es mío, es todo lo que tengo. Hazme tu pregunta, te diré muchas cosas. ",
"?",
"¿Dónde puedo encontrar la taberna?",
"¿Dónde está el astillero?",
"¿Dónde puedo vender los buenos productos que he traído conmigo?",
"La caridad es una virtud, ",
", Sé que con esta respuesta pensará que soy bastante descarado, pero para darle una respuesta necesitaré más dinero.",
"Debes estar bromeando. ¡No voy a pagar por información de un mendigo! ¡Y PARA de hacer rimas cansinas!",
"¿Cuánto?",
"Te escucho,",
"¿Conoces bien el pueblo?",
"¿Ha escuchado alguna palabra sobre el gobernador de #sRedmond#?",
"Puede que tengas razón. No debería perder mi tiempo haciendo preguntas a un mendigo.",
"¿Un trago para el Capitán? ¿Algo de comida y una canción? Directamente con el Gobernador no te equivocarás mucho. La taberna que encontrará a la izquierda de la plaza, y mucha gente buena le espera allí.",
"Bien. Gracias.",
"¿Dónde está el astillero?",
"¿Dónde puedo conseguir algunas monedas para la mercancía que he traído conmigo?",
"El propio astillero, detrás de las puertas de la ciudad en la orilla -- pero la oficina del gerente es un paseo corto, y no más, ",
" a la izquierda de las puertas. Verá el cartel colgado, pase por su puerta principal y pronto lo oirá golpear. ",
".",
"Gracias. ¿Y cómo puedo encontrar la taberna?",
"¿Dónde puedo vender algunos de los bienes que he traído conmigo?",
"Gracias por la información. Es todo lo que necesito por ahora.",
"Ve derecho por el medio, y esto no es un acertijo, ",
", en la plaza, una vista realmente buena, el edificio que necesitas está justo ahí a tu derecha.",
"¿Dónde está el astillero de la ciudad?",
"¿Puedes indicarme dónde está la taberna?",
"Gracias. Eso es todo por ahora.",
" oro, por favor, ",
" Mi vida será corta si esto sale a la luz. Henry tiene enemigos rondando por ahí.",
"Muy bien, aquí está tu dinero. ¡Escúpelo, que NO pagaré sólo por más poesía!",
"No voy a pagar tanto. Sólo estoy buscando algunas respuestas... no tienes que grabarlas en oro.",
"Bien, Bien., ",
" Acércate más amigo, esto es lo que he oído, el Gobernador dicen que ¡no es un buen pájaro!",
"¿Eso es todo? ¿Eso es todo lo que tienes para mí? Voy a necesitar un reembolso.",
"Dime algo que no sepa. Mejor aún, deja de hacerme perder el tiempo. ¡Piérdete!",
"Lo siento, ",
". Parece que estás un poco corto de fondos ahora mismo.",
"(Devolver.)",
"No, en absoluto, ",
"¡ El Gobernador es codicioso. Lo esconde bastante bien, lejos de la gente, pero Henry se da cuenta. Es rico y tan poderoso y aún no es demasiado viejo, ¡no se detiene ante nada para conseguir más oro! Pero él no es tu preocupación, no en este buen día. Hay otro más astuto, eso es todo lo que diré",
"Hasta ahora, no estoy impresionado con el beneficio de mi inversión, ¡y la poesía tampoco ha mejorado!",
"Genial. Lo tendré en cuenta. Adiós.",
"Los bucaneros comen cangrejo, los reyes también. Presta atención a estas palabras, mientras los peces que ves volar, cuando rompas su fino código, te dirán de quién es la mentira",
"¡Nada más que acertijos y poesía! ¡Poesía y acertijos! Empiezo a sospechar que no tienes nada útil que decirme.",
"Dame una moneda sólo una, o dos, hazme una pregunta, y yo responderé para ti. ",
" hemos hablado antes, una respuesta que di, sé que por la rima no eras apto para el delirio",
"Caridad, Caridad es todo lo que pido, si no como pronto, me comeré la pierna",
", una bolsa de oro, ¿es eso pedir demasiado? Yo no pido más, no eres un toque suave",
"¿Lo has olvidado? No creo en las limosnas, y la rima tampoco ha mejorado",
"¿Otra vez tú? Bien, cógelo.",
"Te daré algo de dinero, pero responderás algunas preguntas a cambio.",
"Gracias, ",
"¡ Su bondad en sí misma, una alegría de contemplar, Henry está agradecido de haber conseguido su oro!",
"Por cierto, me gustaría saber algo.",
"Gracias. Puedes irte.",
"Por desgracia, ",
", parece que ni siquiera tienes dinero para gastar en caridad.",
"(Devolver.)",
"Claro, ",
". Es lo menos que puedo hacer por alguien tan amable. Pregunte lo que quiera, realmente no me importa.",
"¿Conoces la ciudad?",
"¿Qué escuchas sobre el Gobernador de #sRedmond#?",
"Sabes, no se me ocurre ninguna pregunta para ti ahora, ¡y estoy realmente HARTO de esta poesía basura!",
"Lo siento mucho, ",
", pero tus preguntas son difíciles, para encontrar lo que quieres, intenta preguntarle al guardia.",
"Tal vez. Pero te estoy pidiendo a ti.",
"Supongo que tienes razón. No podrías tener la información que necesito.",
"Por desgracia, ",
", parece que ni siquiera tienes dinero para gastar en caridad.",
"(Devolver.)",
"El conocimiento es mío, es todo lo que tengo, dame algo de oro y te diré mucho, ",
"?",
"¿Dónde puedo encontrar una bebida y algo de conversación?",
"¿Dónde está el astillero?",
"¿Dónde puedo conseguir el mejor precio para las mercancías que he traído conmigo?",
"Lo siento, ",
". Oro le preguntaré antes de seguir adelante, una vez que te lo haya dicho, sé que te habrás ido.",
"¿Estás bromeando? ¡No voy a comprar respuestas de un mendigo común! Especialmente a uno que es el peor poeta que he escuchado",
"¿Cuánto?",
"Te escucho.",
"¿Conoces la ciudad?",
"¿Qué escuchas sobre el Gobernador de #sRedmond#?",
"Supongo que tienes razón. No podrías tener la información que necesito.",
"Un trago para el Capatain, el mejor ron, bebiendo toda la noche hasta que se le adormezca la nariz. Vaya a la plaza principal cerca del complejo del Gobernador, la Taberna que encontrarás está justo al lado de tu puerto.",
"Ya lo tengo. Gracias.",
"¿Dónde está el astillero?",
"¿Dónde puedo conseguir el mejor precio para las mercancías que he traído conmigo?",
"El propio astillero está detrás de las puertas de la ciudad, en la orilla. Pero la oficina del gerente ya no existe, ",
", a la izquierda de las puertas. ¿Puedes ver el cartel que se balancea, pasa por la puerta, pronto lo oirás cantar, ",
"?",
"Ya veo. ¿Y dónde está la taberna?",
"¿Dónde puedo vender los buenos productos que he traído conmigo?",
"Gracias por la información. Es todo lo que necesito. Ahora soy un maldito poeta, ¡mejor que me vaya!",
"Ve directo al centro, esto no es un acertijo ",
". Cuando llegas a la plaza, una vista realmente buena, la tienda que encontrarás, está justo a la derecha.",
"¿Cómo puedo llegar a la taberna?",
"¿Dónde está el astillero?",
"Gracias. Eso es todo lo que quería saber. ¡Ya es suficiente poesía por hoy!",
"Por favor, ",
", Mi vida será corta si esto sale a la luz, Henry tiene enemigos deambulando por ahí.",
"De acuerdo, bien. ¡Toma tu dinero y habla!",
"A ese precio, creo que puedo prescindir de los secretos de un mendigo, ¡y de la poesía basura!",
"Acércate más, ",
". ¡Diré lo que he oído, el Gobernador, dicen, no es un buen pájaro! .",
"¿Eso es todo? ¿Eso es todo lo que tienes para mí? Voy a necesitar un reembolso.",
"Dime algo que no sepa. Mejor aún, deja de hacerme perder el tiempo. ¡Piérdete!",
"Lo siento, ",
". Parece que estás un poco corto de fondos ahora mismo.",
"(Devolver.)",
"No, en absoluto, ",
"¡ El Gobernador es codicioso, lo esconde bastante bien, pero Henry, él sabe, sí, Henry puede decirlo. Rico y tan poderoso y no demasiado viejo, pero todo lo que quiere es conseguir más oro! Pero él no es tu preocupación, no en este buen día. Hay otro más astuto, ¡eso es todo lo que diré!",
"Hasta ahora, no estoy impresionado con el beneficio de mi inversión, y tampoco estoy impresionado con la poesía",
"Genial. Lo tendré en cuenta. Adiós.",
"Qué tal esto: Los bucaneros comen cangrejos, los reyes también. Presta atención a estas palabras mientras ves volar a los peces, ¡léelas de nuevo y te dirán de quién es la mentira! ",
"Adivinanzas y poesía, poesía y adivinanzas, ¿es todo lo que tienes? Empiezo a sospechar que no tienes nada útil que decirme.",
"Darle una moneda a un pobre hombre, ",
", ¡Sé de brujas, del Kraken y del oro, historias de Davy que no se han contado!",
"¡Por favor! Dame algo de dinero, nunca se sabe, ¡podría decirte algo que te sirva de mucho!",
"Oh ",
", muéstrame un poco de misericordia, no seas tan frío, ¿un poco de ron o de whisky, tal vez un poco de oro?",
"Lo siento, no doy limosnas, y tu poesía no ha mejorado, ¿verdad?",
"Oh, eres tú otra vez. Toma, cógelo.",
"Gracias, ",
". Su generosidad no tiene fondo, un pozo sin fondo, Arrr, señor. Es tan amable, Henry puede decir.",
"Espero que puedas refrescarme la memoria de algunas cosas que hemos hablado antes.",
"Gracias. Ya puedes irte.",
"¿Puede ser, ",
", que ni siquiera tienes dinero para la caridad? Tal vez deberías unirte a mí en mi... trabajo. ",
"(Devolver.)",
"Con mucho gusto, ",
". El gobernador que estoy pensando es de lo que se trata, ven un poco más cerca, sabes que no puedo gritar.",
"No, no tiene nada que ver con el Gobernador. Sólo estoy un poco perdido en este momento.",
"Exactamente. ¿Qué me dijiste de él?",
"No tengo ninguna pregunta para usted ahora mismo.",
"Estoy seguro de que es culpa mía que lo hayas olvidado. Tu memoria es como la mía, envejeciendo y bastante podrida, ",
", Acérquese, amable señor, acérquese un poco más, no quiero que esto lo escuche ningún viejo oyente.",
"Soy todo orejas.",
"¡Estás muy cerca de temblar de miedo! Hablemos de otra cosa.",
"¡Ah! No hay problema, ",
". Te apuntaré a la derecha, como una buena brújula de la Marina, directo a donde vas, sin alboroto y sin trasero.",
"¿Dónde puedo encontrar la taberna?",
"Estoy buscando el astillero de #sRedmond#.",
"He traído mercancía que me gustaría vender. ¿Dónde puedo hacerlo?",
"Gracias, ",
". ¿Qué más puedo hacer? ¿Qué más necesitas.., o ya hemos terminado?",
"Necesito algunas direcciones. ",
"No necesito nada, gracias, ¡especialmente más poesía! . Adiós.",
"Ah, un trago para el Capitán, algo de comida y una canción. Ve derecho por la calle, no puedes equivocarte. Cuando llegues a la plaza, al complejo del Gobernador, a la taberna verás, justo al lado de tu puerto.",
"Ya lo tengo. Gracias.",
"¿Dónde está el astillero?",
"¿Dónde puedo vender los buenos productos que he traído conmigo?",
"El propio astillero está detrás de las puertas de la ciudad en la orilla. Pero la oficina del gerente ya no existe, ",
", a la izquierda de las puertas. ¿Puedes ver el cartel que se balancea? Pasa por la puerta, pronto lo oirás cantar. ",
"?",
"Ya veo. ¿Y la taberna?",
"¿Dónde puedo vender mis productos?",
"Ya veo. Gracias por su ayuda.",
"Pasa por la calle central ",
", y cuando llegues a la plaza, una vista muy bonita, la tienda que encontrarás, justo a tu derecha.",
"¿Dónde está el astillero local?",
"¿Cómo llego a la taberna?",
"Ya veo. Eso es todo lo que quería saber.",
"Recuerde, el Gobernador es un hombre codicioso, y sin embargo no es demasiado viejo, se sienta allí en su palacio, sólo soñando con más oro. Pero no es él quien debe vigilar, no está entre los esquiroles, ¡recuerde lo que le dije sobre los bucaneros y los cangrejos!",
"Así es, y te dije que estaba harto de toda esta poesía. ¿Cuál era la parte del cangrejo?",
"Sí, ahora lo recuerdo. Gracias.",
"Los bucaneros comen cangrejos, los reyes también los comen. Estudiando estas palabras, ¡dice de quién después de ti! Escribe como una lista, eso es lo que debes hacer, Luego lee abajo a la izquierda, Hey Presto! tu pista!",
"Sí. Todo lo estoy recordando. ¡Necesito estudiar la frase de los bucaneros y los reyes para saber de quién debo cuidarme!",
"¡Ah! Capitán, has vuelto, pero tienes el ceño fruncido. Henry parece que debe ayudarte ahora.",
"Henry, escucha, tengo un gran problema. Acabo de conocer al verdadero Cutler Beckett y me ha dicho que capture al impostor, pero no sé por dónde empezar a buscar, o si es un impostor, o si debería molestarme del todo con ello.",
"Piense bien, mi querido capitán, piense bien y piense despacio. Lo que haces ahora te envía a donde irás. No hay vuelta atrás cuando la respuesta que has dado. Tu vida se fijará en cómo vivirás. Puedes seguir tu búsqueda del arco iris para encontrar, o abandonar esta vieja vida y dejarla atrás. Puedes navegar por los anchos mares en la aventura más rara, pero quién sabe qué problemas te esperan allí.",
"Mis opciones son entonces, ¿mantenerme en esta búsqueda u olvidarme de ella y elegir una nueva vida?",
"Corrija mi querido capitán, en la encrucijada que usted está parado y cómo usted decide mostrará donde usted está aterrizando.",
"De acuerdo. Me quedaré en la búsqueda y encontraré al otro Cutler Beckett.",
"Bien. Empezaré una nueva vida, un nuevo país y encontraré a Beckett de esa manera. Necesito un cambio.",
"Entonces dile a tu viejo amigo Henry qué es lo que sabes, y él te aconsejará dónde deberías ir.",
"Bueno, tengo este documento que era para el otro Beckett. Parece que es parte de un mapa.",
"¡Ah! Sí, mi querido Capitán, será un mapa. Si encuentras las partes que faltan, entonces estará completo. Lleva a un vasto tesoro como no has visto antes. Y las partes a completar son en total sólo cuatro. Ve a buscar al hombre de Reims como te han dicho, tiene una parte del mapa, que lleva al oro. Pero tenga cuidado, querido capitán, no todo es lo que parece. Siga su cabeza, no su corazón, ni sus sueños.",
"¿Qué? ¿Otro acertijo? Ahora no es sólo la poesía la que juega con mi mente. ¿Y qué hay del otro Beckett?",
"Uno lleva al otro, querido Capitán, ya lo verás. Ambos se unen como el cielo y el mar. El mapa fue dividido en partes como usted sabe, y aquellos que las partes llevan, saben donde deben ir. Se encontrarían en una isla sus partes para ponerlas de nuevo pero entonces encontrarán lo que les falta.",
"¿Qué les falta? No lo entiendo. ",
"No se preocupe, querido capitán, ya tiene suficiente en su plato. Date prisa en zarpar antes de que sea demasiado tarde.",
"Está bien, está bien. Me iré a la isla pirata.",
"Bueno, tengo este documento que era para el otro Beckett pero parece estar en código.",
"¡Ah! Sí, mi querido Capitán, un código para estar seguro, de un plan para la invasión, para el comercio y más. Su Beckett tiene un plan para hacer bien, que el comercio en estas islas sea como debe ser. La nación a la que sirve para el comercio hace mucho, y para saber más sobre ello vaya a hablar con los holandeses. Los holandeses tienen una compañía que comercia cerca y lejos, y ese comercio, mi querido capitán, lo traen para estar aquí. ",
"¿Así que ayudaré a los holandeses a tomar estas islas?",
"¿No puedo detenerlos?",
"La elección será tuya cuando te encuentres con tu Beckett, en una isla que es holandesa y aún no has llegado allí.",
"Bien, bien, buscaré a Beckett en una de las islas holandesas.",
"De nuevo, mi querido capitán, y se ve bastante bien. Si me paga 1.000 por un secreto, le diré.",
"Mil en oro. Te estás volviendo codicioso, ¿no es así Henry?",
"Oh Capitán eso es cruel, Henry está de su lado. Este secreto paga bien, pero usted puede decidir.",
"Bien, aquí tienes 1.000. Más vale que sea bueno o probarás mi espada.",
"Gracias, amable capitán, no haré una broma. Ve directamente al astillero y véndeles tu barco.",
"¡Vender mi barco! ¿Estás loco además de codicioso?",
"No Capitán, no es así, cuando el Gobernador te encuentres. Verás que el consejo de Henry fue realmente muy dulce. Pero, por favor, no olvide cuando se haya terminado ese negocio, ir al astillero y a la tienda y a la taberna.",
"De acuerdo. Iré a vender mi barco y luego veré al Gobernador. ¡Más vale que esto me salga bien, o volveré!",
"¡Ah! Capitán, de nuevo necesita el consejo de Henry. Si tienes algo de dinero de sobra, eso estaría bien.",
"Henry, ¡realmente eres un viejo mendigo agarrador de dinero! Estoy quebrado y no tengo barco, sólo una vieja tartana agujereada.",
"Mi Capitán, tus opciones son pocas, como verás, y como eres tan pobre, te los daré gratis.",
"Bueno, debo decir que es una sorpresa. Entonces, ¿qué debo hacer?",
"Hay un barco en el puerto que te quedaría muy bien. Si vas allí y lo robas... bueno, nunca se sabe. O, Weatherby Swann es el gobernador en estos días, usted podría ir a él y ver lo que paga. O, si su sueño es empezar la vida de nuevo, simplemente caminar alrededor de la ciudad y disfrutar de la buena vista.",
"De acuerdo. Le daré una oportunidad a la nave... Hay dos soldados ahí abajo custodiándola. Iré a echar un vistazo.",
"Sí, tienes razón, estoy cansado de todo esto de andar por ahí. Iré a ver al gobernador, a ver qué tiene para ofrecer. Al menos paga bien.",
"Una buena elección mi Capitán, esto te llevará a tus sueños. Hable con esos soldados, ellos le darán los medios.",
"Gracias Henry, y aprecio el 'sin cargo' ¡esta vez!",
"Sí. Creo que empezaré de nuevo y trataré de olvidar mi pasado.",

};