string DLG_TEXT[37] = {
"ЎSaludos, seсor! Servimos perritos calientes frescos o perritos de mar mohosos. їQuй serнa para usted, ",
"?",
"Nada. Estoy aquн por negocios.",
"Los negocios son para los hombres de negocios! ЎLa cocina es para Hylie el chef! No te molestarй.",
"No, espera... no me estбs molestando. De hecho, es usted con quien tengo que hablar.",
"No tan rбpido. Quiero hablar contigo.",
"ЎSoy todo ojos y oнdos, seсor! їAle, vino o ron?",
"Necesito contratar algunos marineros.",
"Estoy buscando aumentar mi tripulaciуn.",
"Hablemos de negocios.",
"Necesito una habitaciуn.",
"їTiene una habitaciуn libre en este lugar?",
"No importa. Me tengo que ir.",
"Como quieras, ",
". ЎїQuй tiene en mente, seсor?!",
"Se supone que hay aquн un primer compaсero de Sao Feng, que se encontrу con una misteriosa corbeta.",
"En realidad, no es nada importante.",
"ЎEres un bastardo con suerte! ЎTengo una habitaciуn limpia sуlo para ti! їCuбnto tiempo te vas a quedar?",
"Me quedarй a pasar la noche.",
"Sуlo hasta el atardecer.",
"ЎCinco ochos en la luz, seсor!",
"Estб bien. Aquн tienes.",
"їTanto? Parece que pasarй la noche en el salуn de la taberna.",
"їPara quй? їPara la residencia del gobernador? No, gracias.",
"Lo pensarй. Dйjame hacerte otra pregunta.",
"ЎCinco ochos en la luz, seсor!",
"Estб bien. Aquн tienes.",
"їTanto? Parece que pasarй la noche en el salуn de la taberna.",
"їPara quй? їPara la residencia del gobernador? No, gracias.",
"De acuerdo, lo pensarй.",
"ЎLlega tarde, seсor! ЎLa mayorнa de la tripulaciуn ha subido a bordo!\nMejor que esperes hasta maсana, їQuizбs podrнas pasar la noche en su lugar? ",
"їTiene una habitaciуn libre?",
"No. Tengo otra pregunta.",
"Deja a la sirvienta en paz. Las chicas trabajadoras estбn... dondequiera que estй el burdel.",
"ЎRelбjate! Me voy.",
"Sн, Ўese serнa el tipo llamado Tai Huang! ЎTienes suerte, estб sentado allн junto a la ventana!",
"Gracias.",

};