string DLG_TEXT[199] = {
"їQuй estбs mirando? No esperabas que una mujer estuviera a cargo aquн, їverdad? Bueno, esta anciana, ",
", puede mostrarte que todavнa tiene un poco de Ўpуlvora en su barril!",
"Oye, їde dуnde sacas tus modales, ",
"?",
"їEstoy en lo cierto? їTu nombre es?",
"Los aprendн donde nacн -- en una sucia choza a las afueras de Lisboa. Eran lo suficientemente buenos entonces, y no veo ninguna razуn para cambiarlos.",
"Los niсos de hoy en dнa... Me parece justo -- Actъa como un perro de mar si quieres, pero presta atenciуn a mi consejo y ten en cuenta con quiйn hablas en ese tono",
"Bueno, mi nombre es ",
".",
"Guarda tus consejos para ti, ",
".",
"їQuй es lo que necesitas? їViniste aquн a mojar tu silbato?",
"Dime -- їcуmo te convertiste en propietaria de una taberna?",
"Quiero saber algo.",
"Sуlo quiero encontrar algunos tripulantes para mi barco.",
"їNo dijiste que tenнas una habitaciуn libre?",
"їHay una cama libre en tu posada?",
"Lo siento. Me tengo que ir.",
"Si, en efecto. Su navegante estaba enfermo de malaria, por lo que Rheims no podнa llevarlo consigo.",
"їSigue en la isla?",
"No, no. Se recuperу hace mucho tiempo. Entonces Rhino lo llamу. Tuvieron una larga conversaciуn, y luego el navegante se fue.",
"їEs todo lo que sabes? їAdуnde se fue?",
"Bueno, le oн decir algo sobre #sGreenford#. Dijo que tiene una casa allн. Probablemente una mentira... pero tal vez no. \n Si lo estбs buscando, pregunta por ",
"Giraldo Figuiera",
"Giraldo Figuiera",
" en #sisland_Greenford#.",
"Gracias.",
"Tengo una habitaciуn... pero їcuбnto tiempo piensas quedarte?",
"Hasta maсana.",
"Sуlo hasta que oscurezca.",
"Bien. Te costarб 5 piezas de oro.",
"Estб bien. Aquн estб tu dinero.",
"їTanto? Supongo que mi cartera y yo dormiremos bajo una mesa aquн en la taberna.",
"Si ese es el precio, paso. Siempre puedo dormir en la sala comъn.",
"Lo pensarй.",
"Te costarб 5 piezas de oro.",
"Bien. Aquн tienes.",
"їTanto? Supongo que mi cartera y yo dormiremos bajo una mesa aquн en la taberna.",
"Si ese es el precio, paso. Siempre puedo dormir en la sala comъn.",
"Tal vez mбs tarde. Hablemos de otra cosa.",
"ЎOh, Dios mнo! ЎHe contado esta historia cientos de veces!",
"Estoy seguro de que estбs cansada de contarle a todo el mundo la historia de tu vida. Pero estoy realmente interesado. їQuizбs podrнas hacer una excepciуn por mн?",
"ЎAsн que dilo por centйsima vez! No finjas que no es tu tema favorito.",
"Bueno, їno eres un diablo de lengua plateada?",
"їQuй tal si me cuentas tu historia?",
"ЎNo interrumpas a tus mayores, cachorro! Estoy llegando a eso. Sucediу hace unos 30 aсos... yo era una chica bastante joven entonces. \n Pasй la mayor parte del tiempo pensando en el sonido de las olas, el olor del mar, las noches estrelladas...chicos...",
"Continъa.",
"Estб bien. Ya he oнdo suficiente. Vayamos al grano.",
"Un dнa, apareciу un joven marinero. Me hizo perder la cabeza, sн. \n Me convenciу para navegar a un paнs fabuloso donde dijo que cualquiera podrнa hacerse rico en poco tiempo e incluso vivir feliz despuйs.",
"їSe referнa al Nuevo Mundo?",
"Vale, creo que ya tengo lo esencial. Hablemos de negocios.",
"Eres bastante agudo, їno? Sн, se referнa al Nuevo Mundo. Como dije, era joven y tonta. Asн que me fui con йl.",
"Pero, їcуmo un marinero ordinario te trajo a bordo de un barco de la marina? ЎEso va en contra de las normas!",
"Creo que puedo entender el resto. Hablemos de negocios.",
"Sн, era contra las reglas, incluso en esos dнas. Asн que me ayudу a esconderme en la bodega -- ...justo al lado de las galletas, Ўpor favor!",
"їY te quedaste allн todo el tiempo?",
"Estб bien. Ya he oнdo suficiente. Vayamos al grano.",
"Bueno, no. Me encontraron, por supuesto. Resultу que no era tan buen marinero en esos dнas. \n El mareo fue algo horrible, de veras. ЎMedia hora en el mar, y pensй que me estaba muriendo! Empecй a gritar pidiendo ayuda. \n їQuй otra cosa podнa hacer?",
"їY quй pasу?",
"Vale, creo que ya tengo lo esencial. Hablemos de negocios.",
"Mi encantador marinero fue ejecutado por romper las reglas del barco, y decidieron tirarme por la borda para alimentar a los tiburones. \n Lo habrнan hecho tambiйn si un barco con la bandera negra no hubiera aparecido en el horizonte en ese momento.",
"De la sartйn al fuego, їeh?",
"Creo que puedo entender el resto. Hablemos de negocios.",
"Eso es mбs o menos lo mismo. Me encerraron en una cabaсa mientras luchaban contra los piratas. Supongo que pensaron que decidirнan quй hacer conmigo mбs tarde. \n Por suerte para mн, los piratas ganaron.",
"Asн que caнste en las manos del pirata -- Ўїy eso fue una suerte?!",
"Y el resto es historia, їeh? Bien... Vayamos al grano.",
"Algo asн, sн. La puerta de mi cabaсa fue abierta por un hombre muy joven. ЎOh, era tan guapo! \nOlvidй todos mis miedos cuando lo vi en la puerta.",
"їQuй pasу despuйs?",
"Creo que puedo entender el resto. Hablemos de negocios.",
"Bueno, їno te gustarнa saberlo? ЎIncluso una anciana tiene que guardar algunos secretos para sн misma!",
"ЎPerdуn! No quise decir...",
"їAhora te pones mojigata? ЎNo te hagas la tonta!",
"Me parece justo. Guarda tus secretos, y vayamos al grano.",
"ЎJa! No era tu intenciуn! Mнrate -- ЎNunca habнa visto a un marinero sonrojarse antes!",
"їNo eres inteligente? Tal vez todavнa hagas algo por ti mismo -- si no mueres primero.",
"їPor quй no me dices lo que pasу despuйs de que te encontraste en la orilla?",
"Vamos. Cuйntame el resto de la historia, ",
".",
"Estб bien. Ya he oнdo suficiente. Vayamos al grano.",
"Estб bien, estб bien. Allн, en el barco, conocн a un hombre que hoy se llama ",
"Isenbrandt Jurcksen",
"Isenbrandt Jurcksen",
". En aquel entonces, era un gran hombre de ojos azules. \nY supongo que yo tambiйn le gustaba. Se batiу en duelo con el capitбn del barco por mн -- y terminу asumiendo el trabajo de capitбn.",
"їQuiйn es ",
"Isenbrandt Jurcksen?",
"?",
"Creo que puedo entender el resto. Hablemos de negocios.",
"їNunca has oнdo hablar de йl? їCуmo es posible que no sepas nada del capitбn pirata mбs famoso del archipiйlago, comandante de la escoria de la sociedad durante estos treinta aсos?",
"Bien, ahora lo sй. Cuйntame mбs sobre esos primeros dнas.",
"Vale, creo que ya tengo lo esencial. Hablemos de negocios.",
"Bueno, navegamos juntos por un tiempo -- y lleguй a amar ese tipo de vida. Pero un dнa, tuvimos una pelea tormentosa por nada. Tenнa mi propio dinero para entonces, asн que me fui y equipй mi propio barco.",
"їTe convertiste en capitбn de un barco pirata?",
"Estб bien. Ya he oнdo suficiente. Vayamos al grano.",
"Sн, Ўmaldita sea! ЎMe convertн en una muy buena capitбn! Todos los comerciantes de estas aguas me temнan. Tenнa un precio por mi cabeza, pero siempre me las arreglй para deshacerme de mis perseguidores o destruirlos.",
"їY quй pasу despuйs?",
"Es una gran historia. Dйjame preguntarte sobre algo mбs.",
"Fui gravemente herida mientras abordaba una corbeta inglesa al mando de un persistente compaсero que me perseguнa desde hacнa varios meses. Casi muero. Despuйs de recuperarme de eso, decidн que era hora de retirarme. \nDe repente, una vida tranquila en tierra firme me pareciу bien. Asн que abrн esta taberna.",
"Vaya historia. Gracias por contarla. Ahora dйjame preguntarte sobre algo mбs.",
"ЎEres una buena contadora de historias, anciana! Casi haces que te crea. Pero vayamos al grano ahora.",
"Bien. їQuй es lo que quieres?",
"Estoy buscando a un hombre llamado ",
"Raoul Rheims",
"Raoul Rheims",
".",
"їPuedes decirme si una corbeta llamado 'Crimson Blood' entrу en la bahнa?",
"Nada. Hablemos de otra cosa.",
"ЎїAh, esos locos?! Sн, han estado aquн, pero yo los dejarнa en paz si fuera tъ. Un bribуn de aquн se peleу con ellos, y le cortaron sin pestaсear.",
"Gracias por la advertencia, pero tengo que encontrarlos.",
"No te preocupes -- Yo puedo apaсarmelas solo. їPodrнas decirme dуnde puedo encontrarlos?",
"Lo siento, muchacho, pero no puedo ayudarte con eso. Se fueron, y no tengo ni idea de dуnde.",
"їHablaron con alguien antes de irse?",
"No que yo sepa. Podrнas preguntar por ahн. Tal vez alguien mбs pueda ayudarte.",
"Gracias. Lo harй.",
"їQuй te hace pensar que puedo ayudarte? їCуmo puede una vieja posadera saber dуnde estб un sinvergьenza?",
"Preguntй por ahн. La gente dice que el tipo que estoy buscando se alojу aquн en tu posada.",
"Escuchй un rumor de que estaba en el puerto. Me imaginй que el posadero local probablemente sabrнa algo sobre eso.",
"їA quiйn le importa lo que digan esos chismes? Yo no sй nada",
"їPor quй tengo la sensaciуn de que estбs ocultando algo?",
"Mira... Ўno quiero causar a un buen hombre mбs problemas de los que ya tiene!",
"Prometo que no le causarй mбs problemas de los que йl mismo se ha causado.",
"No voy a causarle problemas. Sуlo tengo asuntos importantes con йl.",
"Mira, te dije que no sй nada. ЎEso significa que no sй nada! ЎAhora vete!",
"Estб bien, estб bien. No sabes nada. Le preguntarй a alguien mбs.",
"Si no estuvieras rodeado de sinvergьenzas que creen que colgaste la luna, harнa un poco de convencimiento con mi espada...",
"їQuй significa eso?",
"Nada especial. Es sуlo que tengo la misiуn de encontrar a este hombre y llevarlo a #sRedmond#.",
"A #sRedmond#, їeh? Tal vez estбs diciendo la verdad despuйs de todo. ",
"Raoul Rheims",
" una vez dijo que necesitaba llegar a #sRedmond#, pero se encontrу con algunas dificultades para hacerlo. Tal vez puedas ayudarle.",
"Esas son mis уrdenes exactamente -- para llevarlo a #sRedmond# vivo y a salvo.",
"Estб bien. Entonces escucha. Como dije, йl mismo estaba navegando hacia allн por un asunto importante, pero alguien disparу un tiro en su proa y lo obligу a cambiar de planes.",
"їY a dуnde lo han llevado sus nuevos planes?",
"Dijo algo sobre #sisland_Conceicao#. Tiene un amigo allн -- Desmond Ray Beltrop, jefe de los contrabandistas locales.",
"Gracias por la informaciуn. Me has ayudado mucho.",
"їCrees en todo lo que dice la gente? No sй nada. ЎNo me molestes de nuevo!",
"De acuerdo, supongo que tendrй que pedirle a alguien mбs.",
"Oh, somos tan importantes, їverdad? їY quй podrнa ser este negocio?",
"Necesito... llevarle una carta de un amigo.",
"Muy bien, muchacho. Te dirй a dуnde ha ido.",
"Entonces, їdуnde estб?",
"Una carta, їeh? їPuedo verla? їO estбs mintiendo?",
"No puedo mostrбrtela. Es... alto secreto.",
"ЎMentiroso! ЎVete antes de que haga que los muchachos te echen!",
"De acuerdo, me irй. Pero te arrepentirбs de esto.",
"Es un poco tarde para eso. Vuelve por la maсana, y este lugar estarб lleno de potenciales miembros de la tripulaciуn. O, mejor aъn, quйdate aquн por la noche.",
"їTiene una habitaciуn libre?",
"Tal vez mбs tarde. Dйjame preguntarte algo mбs.",
"Tengo una habitaciуn. їCuбnto tiempo la necesitas?",
"Hasta maсana.",
"Sуlo hasta que oscurezca.",
"Bien. Te costarб 5 piezas de oro.",
"Estб bien. Aquн estб su dinero.",
"їTanto? Supongo que mi cartera y yo dormiremos bajo una mesa aquн en la taberna.",
"Si ese es el precio, paso. Siempre puedo dormir en la sala comъn.",
"Lo pensarй.",
"Te costarб 5 piezas de oro.",
"Bien. Aquн estб tu dinero.",
"їTanto? Supongo que mi cartera y yo dormiremos bajo una mesa aquн en la taberna.",
"Si ese es el precio, paso. Siempre puedo dormir en la sala comъn.",
"Estб bien. Lo pensarй.",
"ЎDetengan este ultraje ahora mismo, o serбn expulsados de aquн!",
"Bien, bien. Ya me iba.",
"Sуlo necesito hacerte algunas preguntas.",
"їPor quй todo el mundo piensa que el posadero siempre lo sabe todo?",
"Bueno, puede que sepas si alguien se estб quedando en tu posada, їverdad?",
"Eso podrнa saberlo. De lo contrario, ve a buscar una biblioteca. їQuiйn crees que se hospeda aquн?",
"Ah sн, nuestro guapo y encantador borracho francйs. Estб en la mesa de las escaleras, nadando en un barril de ron, el borracho. Todo un dandi, un gran sombrero rojo, una pluma.",
"Ves, eso no fue tan difнcil.",
"Esto deberнa ser entretenido. Es tan capaz de matarte como de hablar contigo. O ambas cosas, Ўja ja!",
"Ummm...Feliz de estar a tu servicio.",
"Tambiйn estoy buscando a un hombre llamado Beckett. їLo has visto u oнdo hablar de йl?",
"їBeckett, Beckett? ЎEse perro! No se atreverнa a poner un pie aquн. ЎUn verdadero pirata odia a ese!",
"Bien. Un tema delicado, lo siento.",
"ЎBueno, benditas sean mis viejas botas! Si no es nuestro valiente asesino de agentes de impuestos.",
"Las noticias viajan rбpido por aquн, їno?",
"Mбs rбpido de lo que parece tu espada. No la mataste, їsabes?",
"I... Er... їQuй quieres decir? [PIENSA: ЎSуlo la noqueй, pero no pensй que la encontrarнan tan pronto!]",
"Sуlo estaba herida. Algunos de los chicos la trajeron aquн. Ahora se estб recuperando arriba.",
"ЎOh! Er... їPuedo hablar con ella un momento? [PIENSA: No quiero que me delate aquн.]",
"ЎOh! ЎNo, no, no! Capitбn. El gran hombre ha dejado уrdenes de mantenerla bajo vigilancia. Y NO visitas!",
"Ya veo. їPor quй tantas precauciones? Ella es sуlo una persona despuйs de todo.",
"Porque ella, y las otras chicas que tenemos allн, traerбn un hermoso rescate, dicen.",
"їOtras chicas? їQuй otras muchachas? їQuiйnes son entonces?",
"ЎYa basta de preguntas, mi amigo! Si quieres saber mбs, ve a hablar con el gran hombre.",
"Puede que lo haga.",
"Se acabaron las bromas. Ahora, їquй puedo hacer por ustedes?",
"їTienes una habitaciуn que podamos usar hasta maсana?",
"No, la basura de mi habitaciуn estб ocupada por un par de agradables jovencitas. Por orden del propio gran hombre. Puedes dormir en una mesa si quieres.",
"No, Creo que lo dejaremos por ahora.",
"O.K. La mesa.",
"Bienvenido a mi taberna. Yo soy ",
" y sн, soy una mujer y Ўestoy a cargo!",
"Bien, soy el Capitбn ",
" y esta joven es ",
"Susan Shaypen",
"Bien, bien, Capitбn ",
". їQuiйn es esta mujer que estб contigo?",
"Esta joven es ",
"... Inteligente.",

};
