string DLG_TEXT[94] = { 
"Buenos días, Capitán",
"Buenos días a usted también, señor",
"Capitán, soy el Guardiamarina James Norrington del King's Ship Repulse, ¿puedo saber con quién hablo? ¿no le he visto antes en estas aguas?",
"Por supuesto. Soy el capitán ",
". ¿Qué está haciendo aquí?",
"Capitán, el Repulse se refugió aquí debido a un poderoso huracán que vino de la nada. Habíamos oído hablar de ataques piratas en la zona, por lo que se me ha encomendado la tarea de obtener información de importancia sobre el asunto.",
"¡Ja! He pasado por aguas tormentosas últimamente, y por favor, llámame ",
", no hay necesidad de ser tan formal, relájate. Estoy en el proceso de reorganizar mi nave. ¿De dónde eres?",
"Gracias Cap..., quiero decir ", 
",... y estaría muy contento si me llamaras James. Nací en Inglaterra de una familia modesta. Demasiadas bocas que alimentar, así que decidí unirme a la Marina para hacer mi fortuna, y colgar algunos ¡¡piratas!!",
"¡Ah! Así que los piratas son de su interés. ¿Dónde está el Repulse ahora? No lo vi en el puerto.",
"¡Oh! se reaprovisionó y continuó su viaje. Ella debería regresar dentro de un mes, momento en el que debo hacer mi informe sobre la situación de los piratas, pero mi información es un tanto deficiente en este momento.",
"Bueno, puedo proporcionar algo de ayuda allí. Hay un asentamiento pirata al este de aquí, en Nevis. Es un lugar muy grande completamente equipado para atender incluso a navíos de línea.",
"Gracias ",
", que añadirá consistencia a mi informe... Voy a caminar por los acantilados para ver si puedo ver algún barco pirata desde allí.",
"Bueno James, tengo asuntos que atender, pero espero  nuestra próxima reunión, tal vez. ¡Buena suerte en tu información!",
"Hola de nuevo, ", 
"Eres un cerdo ",
". Sabía que no se podía confiar en ti.",
"¡Ah! Pero puedes confiar en que soy más listo que tú. Como puedes ver, he capturado tu nave.",
"Te sobreestimas. Sólo hice un mínimo de fuego para no dañar a la Dauntless. De lo contrario, te habría hundido.",
"Bueno, al menos puedes recordar esto como un día en el que casi capturaste al Capitán ",
"¡Bah! Eres sólo un pirata, ¡y el peor que he visto!",
"Aún así, te superé. De todas formas, debo ocuparme de tomar el control de la nave. Tú y tu tripulación pueden nadar hasta la orilla. No está muy lejos. Que tengas un buen día.",
"Haré eso James. Mantenerme a salvo. Te veré pronto de nuevo, estoy seguro.",
"Hola de nuevo... Pensé que tenías cosas que hacer",
"Capitán, mi navío se desvió aquí debido a un huracán muy fuerte. Me dejaron aquí mientras ella continuaba su viaje, con la tarea de obtener información sobre la actividad pirata en la zona. Entonces los franceses atacaron.",
"Entonces... ¿cómo es que sigues caminando por ahí? Y llámame ",
", podemos prescindir de las formalidades, ¡especialmente en estas circunstancias!",
"Gracias Cap..., quiero decir, ",
" y puedes llamarme James. Mi navío aún estaba en el mar, entonces los franceses me capturaron pues no tenía forma de escapar. Tuve que pagar mi libertad condicional para no intentar escapar, a cambio los franceses me dejaron vagar por el pueblo en vez de sentarme en una celda. Creo que ellos piensan, que soy un rango demasiado bajo para ser una amenaza para ellos.",
"James, mi navío está amarrado cerca de aquí, cuando haya terminado lo que vine a hacer debes escabullirte conmigo.",
"Parece que estamos en deuda contigo por tu noble acto. Te daría la mano, señor... ¡Espera! ... ¿qué es eso en tu muñeca? ... Bueno, bueno, la marca de un pirata. ¿Tuviste un roce con la Compañía de las Indias Orientales, verdad? Y por tu tatuaje veo que eres ",
"CAPITÁN ",
" si es tan amable, señor.",
"Creo que nos hemos visto antes, pero parece que te has convertido en pirata, pero ni siquiera tienes un barco. Es una pena. Eres, sin duda, el peor pirata que he visto en mi vida. Guardias... Llévenselo y cuélguenlo en alto.", 
"¿Es eso justo, después de 'un acto tan noble'?",
"¡Qué sorpresa! Mira quién está aquí, el Sr. ",
"Es CAPITÁN si lo recuerdas. No creí que nos volveríamos a encontrar tan pronto, Comodoro.",
"Por supuesto que no. Me alegra saber que la Srta. Swann está viva con usted. Ahora Capitán, acompañará a estos hombres al timón y nos dará la dirección de la Isla de Muerta. Quiero eliminar la última amenaza pirata real en el Caribe, el #scursed_ship#. Entonces debería considerar todos los posibles significados de la frase 'silencioso como la tumba'. ¿Me explico bien?",
"Inevitablemente claro.",
"¡Por fin! Hemos llegado a la Isla de Muerta. Sin embargo, observo que el #scursed_ship# está demasiado cerca del Dauntless. Esto no me gusta. Cualquier intento de asaltar las cuevas podría convertirse en una emboscada.",
"No si eres tú quien hace la emboscada. Voy y hago que Barbossa envíe a sus hombres en sus pequeños botes, tus compañeros los bombardean con tus cañones.",
"Tu idea parece demasiado obvia.",
"¡Por eso funcionará!", 
"Muy bien, te dejaré ir. ¡Pero no intentes cambiar de bando!",
"[a voluntad] Pensé que tendríamos que soportar algún tipo de intento de fuga mal concebido, pero no de ti, Turner.",
"[Voluntad] Debo hacer lo que debo.",
"Olvidas tu lugar, Turner",
"[Voluntad] Está aquí mismo... entre tú y ",
"Bien, ",
" Parece que tu suerte finalmente se ha agotado.",
"¿Suerte, Comodoro? Creo que no. Es mi habilidad como CAPITÁN la que me ayuda a superarme.",
"¡Habilidad! ¿Habilidad? ",
", Eres, sin duda, el peor pirata que he visto nunca.",
"Aún no has visto mis verdaderas habilidades... [Miras la espada de Norrington]",
"¿Qué...? ¡Guardias, guardias! ¡Cogedle! Bájenlo.",
"[arrebatas la espada de Norrington] Atrápame si puedes...",
"¡Curioso! Te atraparé y luego veremos lo buen pirata que eres realmente.",
"Comodoro, piense en esto como el día en que casi atrapó al Capitán ",
"Tienes razón ",
", No me gustan los piratas, y especialmente tú. Ahora, debo pedirles a ustedes dos 'caballeros' que me acompañen de vuelta al barco. Srta. Elizabeth, si quiere tomar mi brazo...",
"Justo cuando crees que podrías estar obteniendo algo de ventaja... ",
" Nos encontramos una vez más. ¿Cómo superaste a los franceses esta vez?",
"Digamos que tengo mis maneras, pero ¿qué hay de ti? Veo que todavía eres libre de moverte.",
"¡Oh! En efecto y más que eso. Hemos oído hablar de una fuerza de invasión que viene a relevarnos. Así que he organizado una milicia local para que podamos proporcionar alguna ayuda.",
"Bueno, eso será más temprano que tarde. El Gobernador ha estado equipando la flota y reuniendo tropas, pero eso es todo lo que puedo decir por el momento.",
"¡Qué! Entonces no hay tiempo que perder. Debo despedirme de ti ",
". Yo también tengo asuntos que atender, y gente que organizar, debemos estar listos de inmediato.",
"Adiós, James, y buena suerte. Sé que conseguirás tu ascenso con esto.",
"¡Una alianza con PIRATAS! ¡Debes estar LOCO! Absolutamente loco.",
"Capitán, déjeme terminar, por favor.",
"¡Acaba, acaba de una vez! Esto es una locura. Todo el mundo sabe que no podemos confiar en los piratas.",
"No se puede confiar en los piratas, capitán, eso es cierto, pero, hay una manera de confiar en ellos para hacer lo que queremos.",
"¡Su Señoría, debo protestar! ¡Esto significaría que yo navegaría bajo una bandera PIRATA!",
"Sólo por un corto tiempo Capitán.",
"¡No puedo creer que esté navegando como un pirata!",
"Relájese Capitán. Recuerde que está haciendo esto por Inglaterra.",
"¡Perro traidor! ¡Has estafado a todo el mundo! No puedo creer que me hayan hecho parte de todo esto.",
"Veo que te has recuperado completamente de tu desmayo. No es un buen ejemplo para representar a un oficial inglés.",
"¡BUEN EJEMPLO! ... Me estaba ahogando con tus piadosas palabras... ¡'pirata honesto' por cierto! Mírate. Estafaste al Gobernador con 200.000 en oro y engañaste a los piratas para que atacaran a los franceses.",
"No es así, capitán, no es así. No le ha costado al Gobernador ni un centavo más de lo que le dije en la residencia, y sabíamos que los franceses atacarían a los piratas, eventualmente. Sólo les advertí para darles la ventaja. ¿Y usted? Puede volver al Gobernador habiendo evitado una gran batalla, y probablemente tenga un gran ascenso también. ¡Todo el mundo gana!",
"Pero... humph... er... Usted obtiene 200.000 en oro.",
"Creo que es un pequeño precio a pagar por salvar las colonias, y necesito una nave. Como dije, 'Todos ganan'.",
"Hmmm... Llévame de regreso a mi nave. Necesito salir de esta isla infestada de piratas.",
"Como quiera, Capitán. Vámonos.",
"Volveré con el Gobernador para hacer mi informe. ¿Te quedas aquí o vienes conmigo?",
"Me quedaré aquí, capitán Norrington. No creo que su informe me describa bien, y necesito conseguir un barco.",
"Hmmm... Bueno, has evitado lo que podría haber sido un desastre para nosotros, así que quizás cuanto menos se diga sobre los detalles del asunto, mejor. Te dejaré un barco, por si lo necesitas.",
"Gracias Capitán. Tal vez nos volvamos a encontrar. Luchando contra los franceses, tal vez. Adiós, y no olvides salir al mar antes de cambiar de bandera. ¡Me temo que debes seguir siendo un pirata un poco más!",
"No me lo restriegues. Nunca viviré esto... ¡siendo un pirata de verdad!",
"¡Ja, ja! Cosas peores pasan en el mar, ya sabes!",
"¡Perro insolente! ¡Cómo te atreves!",
"¿Qué? ¿Te refieres a esto?",
 
};
