string DLG_TEXT[50] = {
"Capitбn, su reputaciуn apesta. No tengo intenciуn de tratar con usted.",
"Es tu elecciуn, supongo. Tъ te lo pierdes.",
"Permнtame presentarme. Yo soy ",
"Joaquin Da Saldanha",
"Joaquin Da Saldanha",
", almirante de la flota espaсola. Me alegro de conocerle, capitбn - el gobernador le recomendу como un hombre que puede tratar con cualquier problema.",
"El gobernador me halaga. Aunque tengo mucha experiencia con los problemas...",
"Capitбn, їha cambiado de opiniуn sobre ayudarme a encontrar a mi hijo?",
"Sн, creo que puedo ayudarte ahora. Pero necesitarй algo para empezar. їPuedes al menos darme una idea general de dуnde debo buscar?",
"Lo siento, almirante, pero no puedo ayudarle en este momento.",
"ЎCapitбn! їHa encontrado a mi hijo?",
"Aъn no lo he hecho, almirante. Pero no se preocupe. Lo harй.",
"ЎAh, capitбn! ЎJusto a tiempo!",
"Tengo noticias sobre su hijo, almirante...",
"Capitбn, їtodavнa estбs aquн? ЎїA quй estбs esperando?!",
"Relбjese. Encontrarй a su hijo.",
"ЎCapitбn, su ayuda ha sido inestimable! Nunca lo olvidarй.",
"Estoy contento de que todo haya salido bien.",
"Perfecto. Tengo algunos asuntos para usted, capitбn. Verб, mi hijo, ",
"Lucas Da Saldanha",
", desapareciу de su casa hace varios meses, sуlo unos dнas antes de casarse. Como puede imaginar, fue una gran vergьenza para mн.",
"Sн, por supuesto.",
"Cuando supe que Lucas se habнa dirigido al Nuevo Mundo, solicitй una asignaciуn como almirante de la flota de las Indias Occidentales - para poder venir aquн y encontrarlo.",
"їPero no has tenido йxito?",
"Por desgracia, no. Cada vez que creo que he seguido el rastro de ",
"Lucas Da Saldanha",
", Pronto lo pierdo de nuevo. Quiero que intentes encontrarlo. Ofrezco una recompensa de 10000 monedas de oro. їTe parece bien?",
"Me viene bien. Pero necesitarй algo de informaciуn...",
"Siento decepcionarle, almirante - pero me temo que no puedo aceptar esta misiуn en este momento.",
"Sуlo sй que ",
"Lucas Da Saldanha",
" fue visto por ъltima vez en la taberna de #sFalaise de Fleur#. Podrнas empezar por ahн. No me decepciones, capitбn.",
"Harй todo lo que pueda. Adiуs.",
"Sй que serб difнcil encontrarlo. Pero todavнa tengo mis esperanzas. Si tienes alguna noticia, puedes encontrarme aquн.",
"Adiуs, almirante.",
"Perdona la interrupciуn, pero el tiempo es corto. Aquн tienes 3000 de oro por tu molestia. Ahora, escucha con atenciуn: Me han informado que ",
"Lucas Da Saldanha",
" ha sido capturado por piratas. Exigen un rescate de 20000 monedas de oro.",
"Ya veo. їQuй piensa hacer? ",
"ЎVoy a pagar el rescate, por supuesto! ",
"Lucas Da Saldanha",
" vale mбs para mн que el mero oro. ЎEs mi hijo! Por favor, entrega este dinero a los piratas, y trae a mi hijo aquн ileso. Recibirбs el oro de 10000 que te prometн.",
"Yo lo harй. їDуnde llevo el rescate?",
"Lo siento, pero me temo que esta misiуn se ha vuelto demasiado peligrosa para que yo pueda continuarla. Adiуs, almirante.",
"A #sisland_Conceicao#. Uno de los piratas te estarб esperando en la taberna de la guarida de los contrabandistas. Te mostrarй la seсal especial que me dieron, para que te reconozca. Y recuerda - si los piratas no consiguen el rescate en un mes, matarбn a ",
"Lucas Da Saldanha",
".",
"No se preocupe, almirante. Su hijo estarб aquн pronto.",
"Me alegra darle estas 10000 monedas de oro, capitбn. Ciertamente se lo ha ganado. ЎLe deseo suerte!",
"Gracias, seсor. Adiуs.",

};
