string DLG_TEXT[66] = {
"Vete ahora, perro marino con escorbuto. ¡Los de tu clase no son bienvenidos aquí!",
"...",
"Bienvenido Capitán. Estoy en deuda con usted por devolverme a mis hijas ilesas, y será un gran alivio para su madre saber que han regresado a salvo.",
"Estoy encantado de haber sido de utilidad, su señoría.",
"Venga, venga señor, es usted demasiado modesto. Te arriesgaste mucho para obtener su libertad. Mis hijas mencionaron tu valentía al entrar en el campamento pirata.",
"Como dije, Su Señoría, estoy feliz de haber sido útil.",
"Bueno, Capitán, ese servicio no quedará sin recompensa. Puede elegir entre el oro o un nuevo barco. ¿Cuál es su gusto?",
"Su Señoría, no soy digno de un servicio tan pequeño, pero el oro siempre es agradable de recibir. [PIENSA] ¡Viene otro día de paga!",
"Su Señoría, mi barco ha tenido mejores días, así que uno nuevo sería muy beneficioso. ",
"Muy bien, capitán. Toma este oro y vete con mi más sincero agradecimiento.",
"Que así sea, Capitán. Aquí están los papeles que le otorgan el título de propiedad de su nuevo barco, que encontrará en el puerto.",
"Le agradezco su generosidad, Su Señoría.",
"Lamento tener asuntos de Estado urgentes que atender, así que debo pedirle que se vaya.",
"Sí, Su Señoría.",
"Debo preparar a la familia para un viaje a Inglaterra ahora que nos hemos reunido.",
"Yo también tengo otros asuntos que atender, así que me despido de usted, mi Señor.",
".",
"Aquí hay una pieza de oro amigo mío. Gástala sabiamente.",
"De alguna manera no creo que seas el pobre borracho que pretendes ser. ¿Cuál es tu historia?",
"No me hagas perder el tiempo, viejo bribón, probablemente tienes más dinero que yo.",
"---",
"---",
".",
"Bueno, después de haber olido tu mal aliento, no creo que esté buscando a gente como tú después de todo",
"Claro, ¿y qué te hace pensar eso?",
"Habías pensado que si realmente era un borracho, el casero me habría echado hace horas.",
"¡Hmmm! Algo así, debo admitir. Entonces, ¿por qué has estado buscándome a mí en particular?",
"No fuiste tú, en particular, sino alguien que es astuto y tiene su ingenio.",
"Bueno, creo que podría encajar en esa descripción. Entonces, ¿podemos ir a los negocios?",
"Muy bien. Si está dispuesto a arriesgarse un poco, hay una damisela, digamos, 'en apuros' que podría necesitar la ayuda de un joven y fuerte capitán como usted. ¿Está dispuesto a hacerlo?",
"No, creo que no. Las damas siempre parecen meterme en problemas. Así que te deseo un buen día.",
"¡Las damas en apuros son una especialidad mía! ¿Qué tengo que hacer? .",
"Como quiera, mi valiente capitán. La dama en cuestión ha estado escuchándonos hablar, y me acaba de señalar que cree que usted podría ayudarla. Se acaba de marchar fuera y te esperará detrás de la Taberna. Ve ahora, y reúnete con ella allí.",
"¡Muy intrigante! Iré a conocer a esta misteriosa mujer tuya. [PIENSA:] Podría haber algún beneficio en esto.",
"Como quiera, mi audaz capitán. Me encargaré de que no fracase. Navega a #sTortuga# y aborda el barco del contrabandista.",
"Gracias, sé que esto va a ser rápido. Próxima parada #sTortuga#.",
"La aventura de Jack Sparrow es la que has buscado. Sólo salta a tu barco y navega a ese puerto.",
"Navegaré hacia allí desde aquí. No llevará mucho tiempo.",
"Un largo viaje, mi capitán, es una buena manera de navegar. Te he dado comida para que tu búsqueda no fracase.",
"¡Ah! Gracias. Cuando me despierte estaré en el muelle del puerto de #sisland_Turks#.",
"Buen Capitán, haré lo que me pidas. Irás a #sTortuga# lo cual no es una tarea fácil.",
"Entonces necesito encontrar al Sr. Gibbs cuando llegue allí.",
"Parece que necesitarás mi ayuda de nuevo, Capitán.",
"¡Oye! Te las ingenias por ahí, ¿no? ¿Qué está pasando aquí? Nada tiene sentido ahora mismo.",
"Paciencia Capitán, paciencia... Este no es el lugar para hablar. Vamos arriba.",
"Más vale que sea bueno. ¿Y puedes dejar ese disfraz de mendigo borracho? Irrita, ya sabes.",
"Sé que estás confundido, pero teníamos que estar seguros de que eras el indicado para el trabajo.",
"¡Trabajo! ¿Qué trabajo? Y sí, estoy confundido.",
"Sabes por qué estoy aquí, Billy. ¿Podemos ir al grano?",
"No me hagas perder el tiempo, viejo bribón, probablemente tienes más dinero que yo.",
"Sé por qué estás aquí, sabes que soy el mejor. Solo asegúrate de que lo dices en serio y no lo has adivinado. ¿Has preestablecido tus niveles, equipamiento y todo? Si no, mi querido capitán en el lodo, caerás.",
"¡Uy! Lo siento, no, esto no es lo que quería. Adiós.",
"Sí... Estoy probando las aguas. Si sabes lo que quiero decir.",
"Entonces, mi amable capitán, ¿a dónde irás? Sólo dime tu deseo, y lo cumpliré.",
"Me quedaré aquí mismo, gracias y veré qué sucede.",
"Necesito probar el motín con Barbossa.",
"Quiero empezar por ir a #sTortuga#, donde me encuentre con Anamaria.",
"Quiero navegar hasta #sRedmond# para la secuencia de la 'Gran Entrada'.",
"Quiero ir con Norrington a #sisland_Turks# Isla para la línea de misión secundaria de CotBP.",
"Quiero ir a #sTortuga#, donde recojo una tripulación y encuentro el #scursed_ship#.",
"Como desees, mi valiente capitán, pasa por delante de la flota. Navega hasta el Faro, y a Barbossa lo encontrarás.",
"Gracias Billy. Lo intentaré.",
"Como desee mi audaz Capitán. Me encargaré de que no fracase. Nageva a #sTortuga# y aborda el barco del contrabandista.",
"Gracias, sé que esto va a ser rápido. Próxima parada #sTortuga#.",
"Venga, venga señor, es usted demasiado modesto. Te arriesgaste mucho para obtener su libertad. Mis hijas mencionaron tu valentía al entrar en el campamento pirata. Y sus servicios en este esfuerzo, Señora Shaypen, le han ganado una considerable promoción.",
"Bueno, Capitán, ese servicio no quedará sin recompensa. Hay un buen navío recientemente capturado, que ahora os concedo en reconocimiento de vuestros servicios a la corona. Está amarrado en el puerto. Aquí están los documentos de propiedad.",

};