string DLG_TEXT[96] = { 
"Me han dicho que se ha esforzado mucho para solicitar una audiencia. Mi nombre es ",
". Ahora, por favor, dígame el propósito de su visita, ",
".",
"Mi nombre es ",
".",
"Ah, eres tú otra vez. ¿Qué te trae por aquí esta vez? ",
"Me gustaría hablar con usted sobre algunos negocios.",
"Lo siento, pero hay cosas que tengo que hacer.",
"Entonces, ¿por qué me distraes de los asuntos de estado más importantes?",
"Me gustaría hablar con usted sobre un pequeño negocio.",
"Sólo estoy aquí para presentar mis respetos, #saddr#. Nada más.",
"En ese caso, por favor deje mi despacho y déjeme volver a asuntos más importantes.",
"Sí, por supuesto. Siento haberle molestado.",
"Lo siento, pero no tengo nada de que hablar ahora mismo",
"¿Ah, sí? Tengo una propuesta para usted, capitán.",
"¿En serio?",
"Me he enterado de que ha completado la tarea con éxito; ¡mis felicitaciones, capitán! Aquí está su recompensa.",
"Mi agradecimiento, fue un placer ayudarles.",
"Debe destruir el ",
" buque ",
"de guerra pirata",
" amenazando el envío ",
". Si la hundes, te recompensaré con la gran suma de ",
" oro. ¿Qué dice usted, capitán?",
"No volverá a oír hablar de ella, eso se lo prometo.",
"Me temo que no puedo ayudarle.",
"Solicito perdón, su Excelencia.",
"Estoy interesado en conocer acerca de #sgov_nation# relaciones con otras naciones.",
"Estoy buscando una carta de marca.",
"He oído que me van a ascender.",
"Ya no puedo servir a ",
", Su Excelencia.",
"Ya he terminado de servir ",
"Como seguro de que usted es un capitán capaz, y para recompensar mi tiempo en la presentación de su caso a ",
", Debo pedirle ",
" oro.",
"No es una posibilidad.",
"Muy bien.",
"#sgov_nation# siempre se complace en aceptar nuevos capitanes a su servicio. ",
"Actualmente estamos en guerra con ",
"",
"no hay un gran poder, pero ",
". Por supuesto, ",
"Los piratas siempre deben ser hundidos al verlos.",
" En función de su servicio anterior, ",
" le concede el rango de ",
"Haré que se sienta orgulloso, su Excelencia.",
"Has dañado a ",
", y ",
" no se olvida de sus enemigos. ¡Váyase de inmediato, o los guardias le echarán de la oreja!",
"...",
"Usted ha causado ",
" gran daño, capitán, pero ",
" está dispuesto a pasar por alto tus transgresiones pasadas... por un precio: ",
"Muy bien, señor. Acepto.",
"Un placer tratar con usted, ",
"Y con usted, su Excelencia.",
"¡En efecto, es así! Excelente trabajo. Tu nuevo rango es ",
". Además, se le concede ",
" acres de tierra por orden de ",
"Gracias, Señor.",
"¿Estás seguro?, ",
" lamentará perder su servicio.",
"Sí, lo estoy.",
" no se toma a bien a los traidores, ",
"Uh, no importa.",
"Muy bien. Pero espero que lo reconsidere..., con el tiempo.",
"Adiós, ",
"¿Eh?",
"Difícil.",
"Bueno, tengo una misión por si estás interesado.",
"Tal vez. ¿Qué es exactamente?",
"Hace dos meses un convoy de barcos mercantes franceses partió de #sisland_Falaise De Fleur# para navegar a #sHavana#. Mi hija, Justine, estaba a bordo de una de las naves. El convoy nunca llegó. Después de un mes envié a mi mejor capitán a buscarla. Pero desde ese día no he oído ninguna noticia de 'La Foudre'.",
"¿Así que quieres que busque tanto la fragata como el convoy? ¿Por qué no envías otro barco propio?",
"Desafortunadamente, no tengo los recursos militares para prescindir de otra de mis naves. Con #sFalaise De Fleur# siendo la única colonia en #sisland_Falaise De Fleur#, Mi gente me despreciaría si comprometiera la seguridad de la colonia por una causa personal.",
"Muy bien, señor. Ahora vamos a las cosas que importan. ¿Cuánto me pagarás si traigo de vuelta a tu hija?",
"No puedo permitirme más de 40000 monedas de oro.",
"Eso me parece muy bien. Acepto tu oferta. Pronto tendrás noticias mías.",
"Lo siento, Gobernador, pero tengo que declinar. No puedo dedicar el tiempo necesario para tal esfuerzo.",
"¡Muchas gracias! Por favor, haga que encontrar a mi hija sea su mayor prioridad, capitán.",
"Haré lo que pueda, señor.",
"Lo entiendo, capitán. Espero encontrar otro corsario dispuesto a hacer el trabajo.",
"La mejor de las suertes, gobernador.",
"¡Gracias a Dios! ¡Trajiste a mi hija de vuelta!",
"En efecto, Gobernador, pero el pirata que secuestró a su hija ¡también vino aquí!",
"Un oficial me informó de la llegada del barco pirata hace unos minutos. Por favor, Capitán, ayude a mis soldados a repeler al enemigo. Mientras dure la lucha, voy a esconder a Justine en una habitación secreta de la residencia.",
"Sabia decisión, señor. ¡Voy a la batalla ahora mismo! (PIENSA: Espero que no tenga que pelear mucho)",
"¡Felicidades Capitán! Hizo un trabajo fantástico.",
"Gracias señor, esta misión fue peligrosa.",
"¡Claro! Justine me habló de Davy Jones. Ese Pirata parece ser el Diablo. Afortunadamente, gracias a ti, no volverá pronto.",
"Eso creo, Gobernador. Ahora que la misión está cumplida, tengo otras prioridades pero antes hablemos de la recompensa, sí... ¿entiende?",
"Por supuesto. Como acordamos, aquí están las 40.000 monedas de oro. Gracias de nuevo y adiós Capitán.",
"Adiós Gobernador.",
"...",
"...",
"Hace algún tiempo un convoy de barcos mercantes franceses partió de #sisland_Falaise De Fleur# para navegar a #sHavana#. Mi hija, Justine, estaba a bordo de una de las naves. El convoy nunca llegó. Después de un mes envié a mi mejor capitán a buscarla. Pero desde ese día no he oído ninguna noticia de 'La Foudre'.",

};
