string DLG_TEXT[37] = {
"ЎBienvenido! Tome asiento en la mesa libre. їQuй le gustarнa pedir?, ",
"?",
"Nada. Estoy aquн por negocios.",
"ЎOh! Lo siento mucho. No quise molestarte. Volverй a mi trabajo.",
"No, espera... no me estбs molestando. De hecho, eres tъ con quien tengo que hablar.",
"No tan rбpido. Quiero hablar contigo.",
"Soy todo oнdos. їEn quй puedo ayudarte?",
"Necesito contratar algunos marineros.",
"Estoy buscando aumentar mi tripulaciуn.",
"Hablemos de negocios.",
"Me gustarнa una habitaciуn.",
"їTienes una habitaciуn libre en este lugar?",
"No importa. Me tengo que ir.",
"Por supuesto, ",
". їQuй tienes en mente?",
"Se supone que estб aquн un primer oficial de Sao Feng que se encontrу con una misteriosa corbeta.",
"En realidad, no es nada importante.",
"Tengo una vacante. їCuбnto tiempo planeabas estar con nosotros?",
"Me quedarй a pasar la noche.",
"Sуlo hasta el anochecer.",
"Bien. Te costarб cinco piezas de oro.",
"Estб bien. Aquн tienes.",
"їTanto? Parece que pasarй la noche en el salуn de la taberna.",
"їPara quй? їPara la residencia del gobernador? No, gracias.",
"Lo pensarй. Por ahora, dйjame hacerte otra pregunta.",
"Te costarб cinco piezas de oro.",
"Estб bien. Aquн tienes.",
"їTanto? Parece que pasarй la noche en el salуn de la taberna.",
"їPara quй? їPara la residencia del gobernador? No, gracias.",
"De acuerdo, lo pensarй.",
"Bueno, es bastante tarde. Todo el mundo que puedas contratar habrб encontrado un lugar para pasar la noche.\nEs mejor que esperes hasta maсana. їTal vez podrнa alquilarte una habitaciуn? ",
"їTienes una habitaciуn libre?",
"No. Tengo otra pregunta.",
"ЎAmigos, por favor! Basta de esta locura. ЎNo me hagas llamar al guardia!",
"ЎRelбjate! Ya me voy.",
"Ah, йse es Tai Huang. Lo encontrarбs en la mesa junto a la ventana.",
"Gracias.",

};