string DLG_TEXT[62] = {
"Bienvenido, ",
". No creo que nos hayamos conocido antes. Soy Laurence Wellman, capitбn del puerto.",
"Hola, Laurence. Yo soy ",
", capitбn del ",
".",
"Le doy la bienvenida, ",
". їVienes a mн por negocios?",
"Hola, ",
". Vi tu navнo entrando en el puerto. Estaba seguro de que me visitarнas pronto",
"Ah, capitбn ",
". їQuй te trae a mн?",
"Hola, Laurence. Me gustarнa hablar contigo.",
"Estoy a tu servicio, ",
".",
"їDуnde puedo reparar y equipar mi navнo en #sRedmond#?",
"їEs posible encontrar un trabajo aquн?",
"Conocн a un marinero en el muelle que fue expulsado de su barco.",
"Justo detrбs de las puertas de la ciudad, encontrarбs la oficina del gerente del astillero. La tienda local estб \nen la plaza de la ciudad, justo enfrente de la residencia del gobernador.",
"Ya veo. їY dуnde estб la taberna?",
"їPuedo encontrar un trabajo aquн?",
"Gracias. Adiуs.",
"La taberna de Young Windem estб frente a la residencia del Gobernador, \nal otro lado de la calle de la tienda de Thomas O'Reily.",
"Gracias. Adiуs.",
"їPuedo encontrar un trabajo aquн?",
"Bueno, a veces los comerciantes fletan sus barcos para el transporte de sus mercancнas, pero no he tenido ninguna solicitud de este tipo recientemente. \nTъ ",
" podrнas hacerle una visita al Gobernador Silehard; puede que tenga algъn trabajo para ti. \nO bien, puedes ir a la taberna y hablar con los propios comerciantes - normalmente encontrarбs unos cuantos allн.",
"Como dije, a veces los comerciantes fletan sus barcos para el transporte de sus mercancнas, pero no he tenido ninguna solicitud de este tipo recientemente.",
" Hazle una visita al Gobernador Silehard; es probable que tenga algъn consejo para ti. \nY habla con los clientes en la taberna - encontrarбs todo tipo de gente relajбndose allн.",
"їDуnde puedo arreglar y equipar mi nave en #sRedmond#?",
"Entiendo. Gracias.",
"Conocн a un marinero en el muelle que fue expulsado de su barco.",
"Pregъntale al tabernero, Windem, y habla con O'Reily, el comerciante local.",
"їDуnde puedo arreglar y equipar mi nave en #sRedmond#?",
"Conocн a un marinero en el muelle que fue expulsado de su barco.",
"Gracias por tu consejo. Adiуs.",
"Ah, probablemente era Bloom. Fue despedido porque golpeу a un oficial. Tiene suerte de que no lo hayan colgado.",
"їQuй ha pasado?",
"Bueno, Bloom parece estar muy apenado por todo eso...",
"Ya veo. Tengo un par de preguntas mбs para ti.",
"Es una historia un poco complicada. A decir verdad, no puedo decir que Bloom sea culpable. \nVerбs, vino a la defensa de la camarera de la taberna cuando un navegante borracho intentу poner sus garras sobre ella. \nEso fue honorable de su parte, por supuesto - pero Bloom es un tipo de mal genio, y cuando el navegante lo insultу, \nBloom derribу al hombre.",
"Entiendo. Bueno, Bloom parece estar muy apenado por todo eso...",
"Es una pena. Gracias por contarme la historia. Adiуs.",
"Es demasiado tarde para lamentarlo ahora. Nunca volverб a trabajar en un barco.",
"Seguramente hay alguna forma de que se le pueda levantar el castigo, їno es asн?",
"Quй lбstima. Parece un buen hombre. Bueno, te verй por ahн, Laurence.",
"Ya sabes, ",
", tal vez haya una manera, para eso. Podrнa cambiar de opiniуn si algъn hombre digno respondiera por Bloom.",
"їMe consideras un hombre digno?",
"No parece probable que el pobre hombre encuentre a alguien por aquн que haga eso por йl.",
"Desde luego que sн. їTe ofreces a responder por йl? Entonces, cambio mi decisiуn. \nYa que respondes por Bloom, te recomiendo que lo contrates para que lo vigiles. \nSi vuelve a hacer algo asн, tu reputaciуn sufrirб.",
"Lo vigilarй. ЎGracias, y adiуs!",
"Dйjame preguntarte algo mбs, si me permites.",
"Pareces un hombre respetable, pero debo admitir que no te conozco lo suficiente \npara dejarte responder por el joven Bloom. Por favor, no te ofendas, ",
", pero\ntendrб que encontrar otro patrуn.",
"Bien, adiуs, Laurence.",
"Dйjame preguntarte algo mбs, si me permites.",
"ЎOye! ЎTъ! ... Es un chelнn amarrar su bote aquн, ... Y ... como se estб hundiendo, necesitarй saber su nombre.",
"їQuй dices a tres chelines... y nos olvidamos del barco... y del nombre?",
"Bienvenido a #sRedmond# Sr. er... Smith. Tengo otros asuntos que atender ahora, asн que no puedo quedarme aquн todo el dнa charlando con usted. Asн que haga el pago y me irй.",
"Por supuesto... їentonces dуnde estб mi dinero? ... Oye, їquй hacen esos marineros con esas cuerdas ahн arriba?",
"ЎQuй diablos! ... no es nada bueno, sin duda. Serб mejor que vaya a ver quй pasa.",
"Sн, sн. Te pagarй cuando vuelvas.",

};