string DLG_TEXT[37] = {
"¡Estoy siempre en deuda con usted, señor!",
"No, en absoluto. Me han pagado un buen dinero por tu salvación.",
"¿Pero quién eres tú? ¿Por qué me salvaste?",
"Llevemos esto fuera.",
"Por favor, dime quién eres tú. ¿Por qué me salvaste?",
"Hablaremos más tarde. Por ahora, salgamos de aquí. No tengo ningún deseo de charlar con un guardia francés.",
"¿De todos modos, quién eres tú?",
"Yo soy ",
". Tu padre estaba muy preocupado por tu desaparición, y me envió a buscarte.",
"Ya veo. Iba de camino a verle cuando me encontré con el problema del que me acabas de rescatar. Te debo mi vida.",
"No me lo agradezcas. Me pagaron bien por mis esfuerzos.",
"Sin embargo, me salvaste la vida, y te estoy agradecido. ¿Ahora iremos a ver a mi padre?",
"Sí. No perdamos más tiempo.",
"Capitán, no tengo palabras para expresar mi gratitud. Tal vez me deje servir como parte de su tripulación. No soy un mal espadachín, y sé manejar una nave.",
"Siempre hay lugar para un hombre capaz, especialmente uno leal. Bienvenido a mi tripulación.",
"Aprecio tu oferta, pero no puedo aceptarla en este momento.",
"Lo entiendo. Pero, de nuevo, se lo agradezco, capitán. A menudo me encuentran en la residencia del gobernador. Búsqueme allí si cambia de opinión.",
"Lo tendré en cuenta. ¡Buena suerte!",
"¡Capitán, me alegro de verle! Todavía me complacería servir en su tripulación, si ha cambiado de opinión.",
"De hecho, es así. Me vendría bien un tripulante capaz.",
"Lo tendré en cuenta. ¡Buena suerte!",
"Disculpe capitán, ¿puedo hablar con usted?",
"Sí, ",
"Lucas Da Saldanha",
", ¿Qué es?",
"Me preguntaba si podría ir a ver a la señorita ",
"Arabella Silehard",
" ¿Otra vez?",
"No veo por qué no, navegaremos a #sisland_Falaise De Fleur# proximamente.",
"No, si navegas conmigo ahora no tendré a uno de mis oficiales huyendo como un cachorro enfermo de amor",
"Capitán, creo que deberíamos ir a ver al gobernador como sugirió el capitán Maggee.",
"Sí, creo que podrías tener razón.",
"Capitán, debemos encontrar a ",
"Elizabeth Shaw",
"!",
"Yo me encargaré de ello ",
"Lucas Da Saldanha",

};