string DLG_TEXT[43] = {
"Conozco esa nave, dicen que nadie puede atraparla. Pero luego estбn los que dicen que no es una nave de verdad.",
"ЎAh! Ella estб muy bien, mбs o menos. Pero el Interceptor aquн es muy rбpido, їverdad?",
"Oh sн, es la mбs rбpida. Y no te acerques mucho a ella... no se te permite hacerlo, amigo.",
"ЎOh! Lo siento... Es sуlo que es un buque tan bonito..., un navнo.",
"їCuбl es su propуsito en #sRedmond#, Seсor Smith?",
"Yo...",
"Creo que dice la verdad.",
"_",
"їCуmo te llamas entonces?",
"Smith, o Smithy, si quieres. ",
" ",
".",
"ЎCaramba! Es un milagro que no haya visto las rocas.",
"їLa salvarбs entonces?",
"No sй nadar.",
"!",
"No Capitбn. Debes liberar a los esclavos.",
"їCуmo lo hago?",
"Matando a los tres guardias que estбn a la vuelta de la playa. Estбn bloqueando mi camino a la cбrcel donde los esclavos estбn siendo retenidos,... y por cierto, es posible que tu tripulaciуn no te ayude.",
"їPor quй tengo la sensaciуn de que podrнas hacerlo por tu cuenta y no necesitas mi ayuda?",
"La sabidurнa despierta tu mente de nuevo Capitбn. Tienes razуn, no necesito tu ayuda, pero necesito que demuestres tus palabras con hechos.",
"їY eso por quй?",
"Haga el trabajo, Capitбn, y luego regrese a mн aquн y le darй la respuesta.",
"Me estoy metiendo en algo muy profundo, lo sй, pero no me gusta la idea de esclavos, asн que volverй en breve.",
"Usted ha tenido йxito Capitбn.",
"Sн, fui capaz de...",
"Esa fue una afirmaciуn, no una pregunta, Capitбn ",
", me has confirmado tu carбcter y te has probado a ti mismo, asн que ahora tengo algo especial que debes comprarme.",
"їMato a tres hombres y quieres venderme algo?",
"No Capitбn, esta no es una venta ordinaria. Dame 500 en oro para que pueda sobornar al carcelero y conseguir trasladar a los esclavos lejos de aquн a un lugar seguro, y obtienes esta brъjula.",
"ЎUna brъjula! Ya tengo una brъjula.",
"No una brъjula como йsta. Йsta te llevarб a lo que mбs desea tu corazуn. Sнguela con cuidado.",
"їQuieres decir como el Cofre de Cortez?",
"Si eso es lo que mбs deseas, entonces sн.",
"Hmmm. Eso suena como si supieras algo diferente. ",
"Sй, capitбn, que no puede volver a su patrуn.",
"ЎAh! Sн. Eso serб un problema. Bueno, tengo que ir a otro lugar.",
"Sн Capitбn, de regreso al faro en #sOxbay#.",
"їTambiйn sabes de eso? Muy bien, vamos a negociar, aquн estб mi oro.",
"Y aquн estб tu brъjula. Tu futuro es muy complejo, Capitбn, pero deberнas irte ahora. Otros guardias estбn llegando.",
"Sн, deberнa, pero їquй hay de ti?",
"No se preocupe por mн, capitбn. Desaparecerй antes de que lleguen. Hasta que nos encontremos de nuevo.",
"Quieres decir 'si' nos volvemos a encontrar... no, no es asн, ya sabes que nos encontraremos, їno?",

};