string DLG_TEXT[40] = {
"Este puede ser el camino a seguir.",
"¡hmm!",
"Obviamente acabas de llegar Capitán, y eso es una gran suerte, ya que he estado buscando a alguien como tú.",
"¿De verdad? Cuéntame más.",
"No soy el típico panecillo de trapo que se encuentra en estas aguas. Tengo mi propio navío y suficiente oro para equiparlo.",
"¿Cuál es el punto de interés?",
"Tengo información sobre el Tesoro de Cortés y necesito un socio que me ayude a conseguirlo.",
"El Tesoro de Cortez - parece que casi todo el mundo está detrás de eso.",
"¡Ah! De hecho, Capitán, lo están, pero, todos están siguiendo los arañazos en los trozos de pergamino.",
"Te refieres a los mapas, creo.",
"Sí, sí, mapas, pero todos están perdiendo el tiempo. El tesoro no puede ser encontrado de esa manera.",
"¿En serio? ¿Y sabes cómo se puede encontrar?",
"Sí, pero necesito primero que te comprometas a unirte a mí antes de que te lo diga.",
"No lo creo. Creo que necesito ganar más experiencia antes de emprender tal aventura.",
"Muy bien, me comprometo a acompañarte en tu aventura.",
"Adiós entonces Capitán.",
"Adiós.",
"Excelente Capitán. Haz lo que necesites para equiparte y equipar tu nave, luego nos vemos en el muelle y te explicaré todo.",
"Muy bien, te veré en el muelle en breve.",
"Me alegro de verte de nuevo, no puedo esperar para irme. ¡Todos los demás por aquí apestan a algas o a bicuits de mar!",
"Bueno, estoy listo para marchar. Entonces, ¿cuál es el plan?",
"Los indios son la clave. Ellos ya saben dónde está el tesoro.",
"Entonces, ¿por qué no van a buscarlo?",
"No lo quieren. Sólo les interesan las calaveras de cristal que usan para sus rituales.",
"¡Ah! ¿Quieres decir que cogemos las calaveras, se las damos a los nativos y ellos nos dicen dónde está el tesoro?",
"Eso es todo. Sólo que no sé cuántos y de qué color.",
"¿Qué tal dos de cada color, rojo, azul y claro, para empezar?",
"Sí. Podemos intentarlo. Deberíamos recorrer las islas para encontrarlas. Tengo 5.000 en oro que pondré para su compra. Tendremos que vivir de nuestro ingenio, y del dinero de los barcos de premio, para conseguir más dinero.",
"Suena justo. Entonces zarpemos y hablemos de vez en cuando para ver cuántas tenemos. Algunos de los comerciantes de aquí pueden tener algunas para la venta.",
"Mira, si lo deseas... cuando tengamos suficientes, navegaremos hacia #sisland_Battle Rocks# para reunirnos con los indios.",
"Sigamos con ello entonces.",
"Necesitamos mantener nuestros recursos separados en caso de que seamos atacados en el mar. Dame el dinero, yo me ocuparé de eso, tú te quedarás con el tesoro mientras lo conseguimos.",
"Muy bien.",
"Bien. Ahora prepárate para morir, capitán. Tengo todo lo que necesito, el juego ha terminado para ti. Te atrapé astutamente, ¿no?",
"¿QUÉ?",
"",
"",
"",
"",
"",
};