string DLG_TEXT[18] = {
"Es hora de que zarpemos.",
"Conforme.",
"A menos que me equivoque, usted es el capitбn que esperбbamos conocer. ЎGracias por su ayuda! Si no fuera por usted, estarнa descansando en el lecho marino con el resto de mi tripulaciуn.",
"Sн. Perdн muchos hombres buenos de mi propia tripulaciуn. Despuйs de una de las andanadas, uno de mis hombres fue golpeado con trozos de madera voladores en ambos brazos y en el ojo.",
"їЙl estб bien?",
"Larry perdiу ambos brazos y su ojo derecho, pobre tipo. Sus dнas de navegaciуn han terminado. їPero por quй decidiу echar el ancla aquн? Tengo уrdenes de escoltarte a #sIsla Muelle#.",
"Tuve que llevar a un pasajero a tierra. Yo tambiйn tengo уrdenes, ya ves.",
"No me dijeron nada sobre eso - pero es justo. Es tu negocio, no el mнo.",
"Asн es, ",
". Cada uno de nosotros tiene sus deberes, y no necesitamos discutirlos.",
"En efecto. їPodemos irnos ahora? Me gustarнa ponerlos a usted y a su nave a salvo tan pronto como sea posible.",
"Nada me retiene ahora aquн.",
"ЎGenial! Entonces no perdamos mбs tiempo",
"ЎSн, capitбn!",
"Los tenemos a todos, capitбn, es libre de escapar.",
"ЎїQuй estбs haciendo aquн?!",
"Devolviendo el favor. Dejй a nuestro amigo maltйs y luego vi a ese hombre y a los soldados esperбndote fuera de la iglesia. Asн que decidн seguirlo y atacar en el momento oportuno.",
"Gracias, amigo mнo. Es muy de agradecer.",

};
