string DLG_TEXT[145] = {
"Hola, hijo mío. ¿Qué te trae al seno de la Iglesia? ¿Has venido para confesarte, o quizás para hacer una donación?",
"Tengo que hablar con usted, Padre.",
"Me gustaría hacer una donación, Padre.",
"Sólo estoy echando un vistazo. Tengo que irme.", //3
"Te escucho, hijo mío.",
"Necesito acceso a la biblioteca de la iglesia, Padre.",
"Tengo esos papeles que te robaron.", //6
"Los papeles que me enviaste para buscar ahora descansan en el fondo del mar - junto con el que los robó.",
"Me pidieron que le entregara esta carta.",
"Me pidieron que le entregara esta carta.",
"Me temo que no fui capaz de cumplir su misión. Cuando llegué a la isla, el 'Montanez' ya estaba en combate con dos barcos piratas, y la hundieron.", //10
"He llevado a cabo tu misión. El barco que me pidió que escoltara está atracado en el puerto.",
"No tengo ningún negocio contigo ahora mismo.",
"¡Lo has hecho bien, hijo mío! ¿Tu viaje ha ido bien?",
"No del todo. Cuando finalmente conocí la barcaza, había sido atacada por dos barcos piratas empeñados en hundirla a toda costa.", //14
"¡Agradezco al Señor que fueras liberado sano y salvo! ¿Hay algo más?",
"Sí, hay otra cosa. El capitán de la nave dejó un pasajero en #sisland_Cuba#...",
"Sí, ya lo sé. De hecho, ese fue el objetivo de toda la empresa. La llegada de este hombre al archipiélago es muy importante para la Iglesia. Creo que lo conocerá algún día.",
"Ya veo. Padre, ¿tiene esto algo que ver con las mujeres desaparecidas?", //18
"Ah, ya veo. Bien, entonces, aquí está su recompensa - y si quiere, por favor permítame proponerle una nueva misión.",
"Gracias, Padre. ¿Y cuál es esta nueva tarea?",
"Mi Señor - ¡esta es una noticia muy grave! Obviamente alguien conoce nuestros planes y se opone activamente a ellos. Rezo para que haya sobrevivientes que lleguen a la costa y escapen de ser capturados.", //21
"Lo lamento mucho, Padre.",
"Nada de eso, hijo mío. Hiciste todo lo que pudiste, y creo que sería injusto no pagarte por tu intento de ayudar a la Santa Iglesia.",
"Gracias.",
"Ahora, ¿aceptarías llevar a cabo otra misión para mí?",
"Primero, me gustaría que me respondiera algunas preguntas, si no le importa.",
"Nada extraordinario. Lleve esta carta al Padre Bernard en #sisland_Redmond#. Y por favor, ten cuidado, asegúrate de que nadie la vea excepto él. Ahora tengo razones para creer que tenemos un traidor entre nosotros.",
"Eso parece. Me iré ahora, si puedo.", //28
"Sí, y que el buen Dios esté contigo, hijo mío.",
"Amén a eso, Padre.",
"Déjame ver. Sí... sí, ¡es justo lo que pensaba! Lo has hecho bien, pero déjame hacerte un par de preguntas.",
"Por supuesto. ¿Qué te gustaría saber?",
"Déjame ver. Sí... sí, ¡es justo lo que pensaba! ¿Pero quién abrió la carta?",
"¡Nadie la abrió, Padre! ¿Cree que yo haría tal cosa?",
"Te diste cuenta de eso, ¿verdad? Sabía que esto no terminaría bien.", //35
"Entonces, ¿quién la abrió?",
"Me estaban esperando en la bahía cuando desembarqué. No tuve más remedio que dejarles ver la carta. Hombres con máscaras... ¡era como si supieran que iba a desembarcar allí!",
"Ya veo. Esto es fácilmente perdonable, hijo mío - especialmente desde que previmos esto y escribimos la carta en clave. En realidad nos has ayudado a engañar a nuestro enemigo. Me complace pagarte la suma que te prometí.",
"Gracias.",
"Está claro que no sientes remordimiento por lo que has hecho. Esa es tu elección, por supuesto. ¡Pero te pediré que dejes esta iglesia!", //40
"Como quieras.",
"No, espera. Lo siento, Padre. Estuvo mal por mi parte.",
"¿Ha tenido algún problema en su viaje?",
"Bien, ",
"Padre Bernard",
", me pidió que desembarcara en una bahía aislada para escapar de los problemas - pero me estaban esperando allí...",
"Habla claro en la casa del Señor, hijo mío. Estás sugiriendo que...",
"No estoy sugiriendo nada. No tengo suficientes pruebas para acusar a nadie. Sin embargo, tiene que estar de acuerdo en que esto es muy sospechoso. En la bahía, tres hombres enmascarados me esperaban, y estaban muy interesados en la carta. Tan interesados, de hecho, que me vi obligado a matarlos.", //48
"Ya veo que ",
"Padre Bernard",
" no fue imprudente darte esta misión.",
"Hay más, Padre. Cuando busqué en los cuerpos de mis atacantes, encontré un extraño medallón en el cuello de cada uno.",
"¿Tienes uno de estos medallones? Sí... Este es de hecho un emblema satánico... Esto no presagia nada bueno. Pero volvamos a los negocios. Aquí está tu recompensa.", //53
"Gracias.",
"Tengo otra misión para ti, si estás interesado. Y la recompensa será mucho más generosa esta vez.",
"¿Qué quieres que haga?",
"Pronto llegará un barco de Europa con algunas personas vitales para nuestra causa. Tengo todas las razones para creer que esa nave será atacada, así que tu tarea es reunirte con ella cerca de #sisland_Cuba# y escoltarla hasta nuestro puerto.",
"Dime el nombre del navío, y haré todo lo que pueda.",
"Es una barcaza llamada 'Montanez', bajo el mando de ",
"Mergildo Hurtado",
", un oficial español.",
"Está bien. Esa debería ser toda la información que necesito. Zarparé tan pronto como sea posible - cuanto más rápido me ponga en camino, mejores serán mis posibilidades de éxito.", //62
"Lamento oír eso. Esos papeles eran muy importantes para la iglesia.",
"Deberías alegrarte de que tus enemigos no puedan usarlos en tu contra, Padre.",
"Eso es cierto. Pero aún así es una pena perderlos.",
"Lo siento. ¿Significa esto que no puedo tener acceso a la biblioteca?",
"Tal vez debería, pero me parece que usted es un hombre que encontraría una manera, sin importarle.",
"Entonces, ¿puedo entrar?",
"Sí, puedes. Tienes todo el día para leer. Es extraño, sin embargo - eres la segunda persona que ha querido entrar ahí tan desesperadamente.", //69
"Gracias, Padre.",
"¡Perfecto! Por favor, dámelas ahora mismo.",
"Aquí están.",
"¡No tan rápido, Padre!", //73
"¿Qué quieres decir, hijo mío?",
"He averiguado qué tipo de papeles son estos - así que naturalmente su precio ha subido.",
"¡¿Me estás chantajeando?!",
"¿Creías que tu túnica de sacerdote te hacía inmune a una pequeña y honesta extorsión? Si no quiere que estos papeles caigan en las manos equivocadas, me dará acceso a la biblioteca y a 5000 monedas en efectivo.",
"¿No tienes miedo del Señor? ¿Dónde puedo encontrar ese dinero?",
"Bueno, revisemos estas notas, ¿sí? Sí, aquí está: '...Se dieron 17000 monedas de oro para equipar el barco y contratar marineros... Lo que estoy pidiendo es sólo una fracción de esa cantidad.",
"¡Suficiente! Nos pueden escuchar. Aquí está tu dinero. ¡Ahora dame esos papeles!",
"Son todos tuyos. ¿Y qué hay de la biblioteca?", //81
"Has hecho un buen trabajo por el bien de la Iglesia, hijo mío. Serás recompensado.",
"¿Qué hay de la biblioteca? ¿Puedo entrar ahí?",
"Oh, sí. Me había olvidado de eso. Por supuesto que puedes entrar. Es extraño, sin embargo - eres la segunda persona que ha querido entrar allí tan desesperadamente.",
"Gracias, Padre.",
"Me temo que eso no es posible. La biblioteca está cerrada para los laicos.",
"Tal vez puedas hacer una excepción por mí. Mira - tengo mi propio barco y mi propia tripulación. Tal vez si me ayudas con mi problema, yo pueda ayudar con algunos de los tuyos.",
"¿Eres un capitán? Entonces tal vez puedas ayudarme a mí y a la Iglesia española.",
"¡Genial! ¿Qué quieres que haga?", //89
"Algunos papeles muy importantes fueron robados hace varios días de la iglesia. Sospecho que fueron cogidos por ",
"Ferro Cerezo",
"Ferro Cerezo",
". Desafortunadamente, no tengo ninguna evidencia sólida contra él.",
"Entonces, ¿quieres que averigüe si tiene los papeles y te los devuelva si los tiene?",
"Sí. Son documentos muy importantes. No dejes ninguna piedra sin remover en tu búsqueda por ellos.",
"¿Dónde puedo encontrar a este hombre?",
"Me las arreglé para averiguar que tiene su propia nave. Es un balandro, si no me equivoco. Y se le ve a menudo en #sConceicao# - probablemente esté metido en el contrabando.",
"Lo encontraré. ¿Me permitirá el acceso a la biblioteca si traigo los papeles de vuelta?", //98
"Por supuesto. Podrás pasar un día entero allí, aunque no entiendo por qué un marinero estaría interesado en eso.",
"Bendígame entonces, Padre, y me iré.",
"Por supuesto, hijo mío. ¿Cuánto quieres dar?",
"Lo siento, Padre, pero no puedo hacer una donación en este momento.",
"Me temo que 100 de oro es todo lo que puedo permitirme en este momento.",
"Creo que el Señor vería con buenos ojos 1000 de oro .",
"Me va bien estos días, así que daré 5000 piastras de oro.",
"Es tu decisión, hijo mío. Nunca es demasiado tarde para cambiar, y ten en cuenta que todo se tendrá en cuenta en el momento de tu muerte.",
"Mi muerte está todavía muy lejos, si Dios quiere. Hablemos de otra cosa.",
"Lo siento, Padre. Me tengo que ir.",
"Te agradezco tu regalo en nombre de la Santa Iglesia, hijo mío.",
"Necesito hablar con usted, Padre.",
"Lo siento, Padre, pero tengo que irme.",
"Te agradezco tu regalo en nombre de la Santa Iglesia, hijo mío.",
"Necesito hablar con usted, Padre.",
"Lo siento, Padre, pero tengo que irme.",
"Te agradezco tu regalo en nombre de la Santa Iglesia, hijo mío.",
"Necesito hablar con usted, Padre.",
"Lo siento, Padre, pero tengo que irme.", //117
"Sí, creemos que sí. ¿Está investigando eso usted mismo?",
"Estoy actuando en nombre del jefe de esas mujeres.",
"Muy amable de tu parte estar tan preocupado, hijo mío.",
"Bueno, también soy un hombre práctico, Padre. Lo que sea que ponga oro en mi cartera.",
"Responderé lo que pueda, hijo mío.", //122
"¿Tiene esto algo que ver con las mujeres desaparecidas?",
"Sí, creemos que sí. ¿Está investigando eso usted mismo?",
"Estoy actuando en nombre del jefe de esas mujeres.",
"Ah, ya veo. Es evidente que será beneficioso para ambos si trabajamos juntos en esto, para que podamos ser más fuertes juntos frente a este mal.", //126
"Muy bien, Padre. ¿Cuál es su próxima misión para mí?",
"¡Capitán! ¡Gracias al Señor! ¡Qué horrible lucha!", //128
"¿Está bien, Padre?",
"¡Las mujeres!",
"¿Dónde están?",
"¡Han estado reteniendo a los niños en su barco! ¡Debes ir tras ellos!",
"Están bien. Aquí están las llaves que encontré del líder. Saca a las chicas de sus celdas ahora. Una vez que me ocupe de la nave, te llevaré de vuelta a la iglesia. Sólo tengo que hablar con las mujeres primero.",
"Rezaré por ti, hijo mío.",
"Esta va a ser una gran lucha, Padre. Rece por todos nosotros.",
"Tenga cuidado, capitán. Su líder es astuto. Hay una sala detrás de ese trono.",
"Hmm...", //137
"Me temo que ",
" oro es todo lo que puedo permitirme ahora mismo.",
"Creo que el Señor vería con buenos ojos ",
" piezas de oro.",
"Me va bien estos días, así que le daré ",
"Muchas gracias por salvarme a mí y a las damas capitán.",
"Debo llevar a las damas con su jefe e ir a ver al Padre Bernard. Adiós, Padre.",

};
