string DLG_TEXT[28] = {
"Vi har meget at lave - - Tenemos mucho que hacer, Capitán",
"Sí, por supuesto.",
"Necesito preparar mi propia nave Capitán Jack, para no retrasar la misión. Te veré en el mar.",
"Sí, Capitán Willemoes, si es tan amable. [PIENSA: Habla muy bien, no es de extrañar que sea un diplomático.]",
"En cuanto a la ubicación, si es adecuada para ustedes, creo que puedo resolver esa situación. Y con respecto al antagonismo entre las diversas bandas de piratas creo que puedo ser de más ayuda, si lo desean.",
"¿Quieres decir que lo tienes todo asegurado entonces? [PIENSA: ¿Por qué los diplomáticos usan seis palabras cuando sólo una sería suficiente?]",
"No tan rápido Capitán ",
". Hay una alternativa para su participación en esta aventura, que me gustaría explicarle.",
"Oh, ¿en serio? Bueno, entonces escuchemos al Teniente Willemoes. [PIENSA: esto va a tomar un tiempo, me imagino. Ojalá tuviéramos esta reunión con una botella de ron.]",
"El curso alternativo de tu participación es que te concentres en financiar este esfuerzo yendo tú mismo a buscar el tesoro de Cortez.",
"El tesoro de Cortez, ¿eh? Continúa.",
"El Capitán Konrad, junto con los demás, procederá a ir a #sisland_Turks# Island como dijo. Tú, sin embargo, volverás a #sisland_Guadeloupe# con los capitanes Maximus y Philippe y se unirán al capitán Drow y al capitán Rackham. Desde allí procederá a localizar y recuperar el tesoro, lo que permitirá a la Hermandad cumplir con su obligación financiera con mi Gobierno en relación con el nuevo asentamiento.",
"Pero no tengo el mapa completo.",
"Ahí está la belleza de este plan, Capitán ",
". Dada la ayuda adicional y los conocimientos de los capitanes Maximus, Philippe, Drow y Rackham, debería ser de poca importancia para usted poder localizar el mapa en poco tiempo. Además, deberían ser capaces de defenderse de cualquier eventualidad.",
"¿Y cómo llego a #sisland_Guadeloupe#?",
"Como dijo el Capitán Konrad, usted usará el navío del Capitán Damski que intercambiará con el suyo cuando todos nos encontremos de nuevo en el nuevo asentamiento.",
"¡Ah! El nuevo asentamiento. Todavía no sé dónde está.",
"Pero el Capitán Maximus sí. Él te llevará allí una vez que el tesoro haya sido encontrado.",
"Bueno, has respondido a todas mis preguntas. [PIENSA: Y no ralló tanto tiempo como pensé.]",
"",
"",
"",
"",
"",
"",
"",
"",
};