string DLG_TEXT[56] = {
"...",
"...",
"Buen día. ¿Puedo preguntarle quién es usted?",
"Soy ",
", capitán del ",
"Soy Pieter Boelen, corsario holandés y capitán del encantador navío, el 'Amsterdam'. Encantado de conocerle.",
"¿Qué te trae hoy a esta ciudad infestada de piratas?",
"Me propongo ayudar a todos los piratas honestos de este archipiélago. Esta vez hay algunos rumores de que el gobernador de #sSantiago# está planeando algún tipo de acción contra esta colonia. Estoy tratando de averiguar si hay algo de verdad en eso. Podrías ayudarme si quieres y ganar también algo de dinero en el camino .",
"¿Dinero? Soy todo oídos, capitán. ¿Qué quiere que haga?",
"No puedo dejar esta isla en caso de que el ataque llegue mientras estoy fuera. Debo seguir aquí para defender a mis amigos. Sin embargo, sería posible que usted visitara #sSantiago# para averiguar si hay algo de verdad en el rumor.",
"Necesitaría engañar a un oficial de #sSantiago# para que me diera esa información. Esta parece una misión bastante peligrosa. Podrían colgarme por espionaje si me descubren.",
"Depende de ti. Te daré 20000 monedas de oro si tienes éxito. Tómalo o déjalo.",
"Muy bien. Tenemos un acuerdo. No me importa un poco de peligro.",
"Lo siento. Esto parece demasiado peligroso para mí. Te deseo la mejor de las suertes defendiendo esta colonia.",
"¡Excelente! Espero tener noticias tuyas pronto. Y ten cuidado.",
"No te preocupes, lo haré. Te veo en un par de días.",
"¡Ah! ¡Estás aquí! ¿Has averiguado lo que el gobernador español está planeando?",
"Sí, lo hice. Malas noticias, me temo. El gobernador de #sSantiago# tiene la intención de tomar el control de esta isla. Su ataque llegará en los próximos días.",
"Ya veo. Lleva a tus hombres y ve al faro para evitar que el enemigo desembarque allí cuando lleguen. Me ocuparé de la defensa del puerto con mi navío y tripulación de confianza.",
"Bien. Me iré ahora mismo y prepararé una cálida bienvenida para nuestros invitados. ¡Buena suerte!",
"¡¡AHHHH!! ¡Ahí está! ¿Has tenido éxito?",
"¡Claro que sí! Que esto sea una lección para los españoles. ¡Los piratas seguirán siendo libres!",
"¡Excelente, capitán! También hemos podido evitar que desembarquen en el puerto. Desafortunadamente mi hermoso navío, el 'Amsterdam', ha sido dañado durante la batalla y no puedo arriesgarme a salir con él hasta que hagamos algunas reparaciones. No podemos asegurar de que los españoles no lo intentarán de nuevo, pero sí podemos estar seguros de que si lo intentan de nuevo, traerán una flota mucho más grande. Necesitaré ayuda de los piratas de #sTortuga#. ¿Me llevas allí mientras mi barco está reparándose?",
"Claro. No hay problema. Será un honor tenerte como invitado a bordo de mi nave.",
"Gracias por su ayuda, capitán. Su ayuda ha sido decisiva. No podríamos haberlo hecho sin usted. Hicieron mucho más de lo que esperaba, así que es justo que aumente tu recompensa. ¿Qué me dices de 40000 monedas de oro?",
"¡Oh! muy amable de tu parte. Tengo otras cosas que hacer ahora, pero estoy seguro que con la ayuda de los piratas de #sTortuga# podrás defenderte de cualquier ataque español. Me despediré de ti ahora, pero espero que nos volvamos a ver algún día. ¡Adiós y buena suerte, Pieter!",
"Buenos días, capitán. ¿Puedo ser tan atrevido como para preguntarle su nombre y por qué está en compañía de un oficial inglés?",
"Mi nombre es ",
", y este oficial y yo acabamos de regresar de una misión con los franceses. Y usted es el Capitán Pieter Boelen, creo, Capitán del 'Amsterdam'.",
"Sí, pero me ha despertado la curiosidad, ¿un oficial inglés en una misión con los franceses? Eso no suena muy probable, ¿a menos que sea un traidor?",
"Oh no, Capitán Boelen, no es un traidor. Representaba a su gobierno en un asunto de máximo secreto. De hecho, es por eso que estamos aquí.",
"Eso suena como la apertura a una petición de dinero, Capitán ",
", y eso no me complace.",
"No es así, Capitán. Ni mucho menos. Verá, conozco su reputación de ayudar a los piratas honestos y creo que podría ser de ayuda en ese sentido, siendo yo mismo un pirata honesto.",
"Su capitán inglés parece que está a punto de ahogarse. ¿No está bien?",
"¡Oh! Está bien. No ha navegado mucho, así que puede estar un poco mareado por nuestro viaje.",
"Muy bien. Entonces, si no es dinero lo que busca, ¿cuál es la ayuda que podría proporcionar?",
"Los franceses pagaron a los ingleses para que les permitieran aprovisionarse en sus islas. Creo que tienen intención de volverse contra los piratas.",
"En cuanto a que los franceses se volvieran contra nosotros, sabíamos que eso pasaría. Pero, no tan pronto. ¿Qué pruebas tiene de su afirmación?",
"¿Qué tal 100.000 en oro que nos pagaron los franceses?",
"¡Cielo santo! ¿Está SEGURO de que su capitán inglés está bien? ¡Se está poniendo muy morado!",
"Sí, sí... los estómagos débiles son cosa de familia.",
"Hmmm. Así que nos daría 100.000 en oro y nos avisaría de antemano de un ataque francés. ¿Qué quieres a cambio?",
"Garantizar la seguridad de la isla natal de los piratas es todo lo que busco.",
"Muy Noble Capitán ",
", muy noble de hecho. ¡Oh, Dios mío! Deberías mirar a tu capitán inglés. Parece que se ha desmayado.",
"¡Ah! Sí. Supongo que debería, pero mientras tanto, aquí está el dinero. ¿Qué piensa hacer?",
"¡Oh! Creo que podemos sorprender un poco a los franceses nosotros mismos, y con el dinero podemos tener mejor equipo. No creo que lleguen al archipiélago.",
"Buena suerte Capitán Boelen. Esperemos que nos encontremos de nuevo algún día.",
"¡Ah! Capitán ",
", has vuelto, y debo confesar, en el momento oportuno.",
"¿Qué quieres decir?",
"Nuestra principal flota pirata ha navegado para enfrentarse a los franceses, gracias a su aviso. Pero ahora he recibido noticias de que el gobernador de Santiago #sSantiago# está planeando algún tipo de acción contra esta colonia. Estoy tratando de averiguar si hay algo de verdad en eso o no.",
"Déjame adivinar, me necesitas para navegar a #sSantiago# y encontrar algún funcionario allí, y ver si es cierto o no, ¿correcto?",
"Es usted muy astuto, capitán, como adiviné en nuestro encuentro anterior. Le pagaremos 20000 en oro por sus molestias. ¿Hará esta misión por nosotros?",
"Lamento no poder ahora. Debo continuar equipando mi navío para estar listo para el ataque francés.", 
 
};
