string DLG_TEXT[57] = {
"Dйjadnos.",
"...",
"No tan rбpido, ",
"Ў No creerбs que puedes evitarnos!, їverdad?",
"No creo que quiera hablar contigo.",
"Entonces hazlo rбpido, tengo prisa.",
"No creo que vayas a ninguna parte. Ahora danos la carta que llevas.",
"їQuizбs podrнamos beber una taza de cerveza y seguir nuestro camino? їNo?",
"ЎїQuй quieres de mн?!",
"Dime dуnde estб tu escondite y te dejarй morir rбpidamente.",
"їQuй quieres de mн, cerdo?",
"Estamos aquн para liberarte.",
"їQuй quieres de mн, cerdo?",
"Estamos aquн para liberarte.",
"Nos estamos acercando a la colonia. Hasta ahora, no pareces ser alguien de mucha confianza. Veamos si te comportas.",
"Como quieras.",
"Entonces, estabas diciendo la verdad. Estбs muy familiarizado con nuestra hermandad. Todavнa no sй cuбndo y cуmo te uniste a nosotros, pero por ahora no importa. El ritual comenzarб pronto. Tenemos que llegar a la cueva. Estoy seguro de que no te opondrбs a escoltarme al templo, a mн y a varias personas del lugar.",
"Por supuesto, sуlo dime a dуnde vamos.",
"Atravesaremos la jungla despuйs de desembarcar en la orilla de los Arrecifes Blancos. La cueva estб situada allн.",
"Entonces ya tengo lo que necesitaba. Ahora es tu hora de morir.",
"їQuй? Entonces tъ eres...",
"...ЎNo soy quien crees! En garde - hermano.",
"En ese caso, una vez que desembarquemos, espero verte en la taberna.",
"Bien.",
"Eso es muy bonito. їY por quй se me ha concedido ese honor?",
"No hay tiempo para explicar. En cualquier momento pueden descubrir que sus papeles de liberaciуn son falsos.",
"їEs asн? Bueno, le permito que me acompaсe a la colonia de #sGrand Turk# en isla #sisland_Turks#. Despuйs de eso llegarй al fondo de este asunto, y decidiremos quй hacer contigo.", // <--Cat
"Como quieras.",
"ЎNo puedes intimidarme! ЎNo le temo a la muerte!",
"Hm... de hecho...",
"їQuй es la muerte para mн? ЎMe liberarб para tomar mi asiento al lado de mi amo!",
"Bien, entonces no le temes a la muerte. їCуmo te sienta la vida en esta celda?",
"...",
"Tal vez esta celda sea demasiado cуmoda para usted. Tal vez prefiera algo mбs hъmedo y oscuro.",
"...",
"Tal vez podrнamos inundar el suelo con agua frнa, para que no pueda descansar...",
"ЎAlto! Te lo contarй todo. їQuй es lo que necesitas?",
"їDуnde estб tu escondite, pestilencia excremental?", // <--Cat
"Cerca de la colonia de #sGrand Turk#. En... tos... tos... no-o-o-o.",
"їQuй? ЎAch! ЎVillano cobarde!", // <--Cat
"ЎDeja de hacer el tonto! Voy a contar hasta tres, danos la carta, o si no... Uno...",
"ЎTres!",
"ЎLlevas cierta carta! Tenemos que leerla. \nNo te preocupes, tenemos una copia del sello con el que estб sellado. Prometo que el cliente no se darб cuenta. \nHбganos este favor y le pagaremos 1000 de oro. їQuй dice usted?",
"їQuй digo? Hmm, їcуmo lo digo...? ЎNO! Y ve a pegar tu sello en algъn lugar cбlido y acogedor.",
"Hmm... 1000 dуlares de oro... Suena tentador. Creo que tenemos un trato. Aquн estб la carta.",
"Eres un hombre inteligente, ",
". Aquн estб su dinero. Ahora echaremos un vistazo a la carta. \nUh-hum, sн... Me lo imaginaba... Ahora, se equivocan en esto... Asн que, he averiguado todo lo que necesito saber. Ahora... para sellar la carta... їVes?, el sello es idйntico. Puedes irte.",
"Estб bien.",
"Entonces nos veremos obligados a matarte.",
"ЎIntйntalo!",
"El alcaide estб muerto, asн que me perteneces. ЎAhora ven y muйstrame la guarida de los animistas!",
"Hah, te dirнgirбs a la isla de #sisland_Turks#. ЎAllн mis compaсeros te eliminarбn!",
"Bien, lo que sea... Sуlo ven conmigo.",
"Eso es muy bonito. їY por quй se me ha concedido ese honor?", // Cat --> 
"No hay tiempo para explicar. Por el momento he intimidado a los guardias. Cuando dejen de orinarse en los pantalones, quizб reъnan el valor suficiente para frustrar nuestro intento de liberarte. Tenemos que irnos ahora.", 
"Bah, їagua? ЎEl agua no me asusta ni apaga los fuegos sagrados que arden en mi interior!",
"Bien, me estoy cansando de esto. Tal vez deberнa hacerte cosquillitas con mi espada", // <--Cat

};
