string DLG_TEXT[420] = {
"Preséntese, por favor. No creo que le conozca.",
"Mi nombre es ",
", y soy el capitán del ",
".",
"Capitán ",
". Confío en que tenga buena salud. Entonces, ¿a qué debo el honor de su visita?",
"Hola, ",
", Hola. ¿Cuál es el propósito de su visita?",
"Le escucho, ", // NK
". ¿De qué se trata?",
"Tengo asuntos que discutir.",
"Esperaba que tuviera trabajo para un capitán capacitado.",
"Sólo pasaba por aquí, señor. Adiós",
"Bien, Capitán ",
", Puedo ver por tu cara que tienes algo que decirme.",
"Lamento informar que el asentamiento de #sisland_Oxbay# ha sido atacado.",
"¿Ha vuelto con el prisionero? ¿Dónde está? Quiero verlo.",
"Lo siento, señor, le traigo malas noticias. El prisionero escapó antes de que yo llegara a #sOxbay#.",
"Hmm... tiene mi atención, capitán.",
"Hablemos de ello más tarde, señor.",
"Acabo de volver de #sOxbay#, señor.",
"Su tarea se ha llevado a cabo.",
"Desgraciadamente, no tengo nada para usted en este momento. Aunque no dude en preguntar más tarde.",
"Tengo asuntos que discutir.",
"Es sólo una visita de cortesía. Y ahora, adiós.",
"Muy bien, Capitán ",
", pero antes de buscar una audiencia conmigo, deberías considerar elegir los argumentos más adecuados.",
"¿Tiene trabajo para un capitán capacitado?",
"Sólo pasaba por aquí, señor. Adiós.",
"Jajaja, no sea tan modesto, capitán. ¡Quizás quieras decir que ellos empezaron primero!",
"Bueno, de hecho, ese es el caso, señor.",
"De todos modos, estoy feliz de entregarte esta recompensa por luchar con los piratas.",
"Gracias, señor. Deberíamos discutir algo.",
"Gracias. ¿Podría preguntarle si tiene trabajo para un capitán capacitado?",
"Estoy agradecido, señor, por esta recompensa. Desafortunadamente, debo seguir mi camino. Adiós.",
"",
"Hmm, esta noticia es inquietante... ¿Pero cómo puede haber piratas en estas aguas? \nEl escuadrón comandado por el Capitán Tomlison me aseguró que habían atrapado o hundido a todos estos ¡sinvergüenzas!",
"Eso es todo, señor. Estos no eran piratas. Eran barcos franceses, con tropas francesas.",
"¿Qué? Lo sabía. Su señoría, Carl, debería haber dado un disparo de advertencia hace mucho tiempo. \nPor favor, cuéntamelo todo. ¿Cómo te las arreglaste para escaparte? ¿Cuántos barcos, cuántos cañones y tropas? ¿De dónde vinieron? \n¿Está seguro de que eran barcos de la flota francesa?",
"Por supuesto, señor. Las banderas francesas fueron lo primero que observé.",
"¡Esto es terrible, terrible! Soldados franceses en suelo inglés, y casi no hay oro en el tesoro de la colonia para hacer una guerra abierta. ¿Cómo protegeremos nuestros hogares? \nMe temo que, ",
", que esto le afectará a usted y a su nave.",
"¿A mí? ¿Cómo?",
"Estábamos hablando del escuadrón francés.",
"Hmm. No me gusta como suena eso. Mejor me voy, señor.",
"Verá, capitán, después de la campaña contra los piratas, sólo quedan dos barcos de guerra en servicio, y estos son demasiado valiosos como para desperdiciarlos en tal empresa. A la luz de esto, he oído la orden de requisar y armar barcos privados donde sea necesario para la defensa de nuestras tierras. \nLo siento, capitán, pero su barco no estará exento de esta orden.",
"¿Qué? ¡No dejaré que te apoderes de mi nave!",
"Ah, sí... sí... Entonces, ¿qué tipo de barcos se utilizaron para asediar el fuerte? ¿Qué tipo de armas tenían? ¿Cuántos soldados?",
"Conté al menos tres naves: ",
"Estimado ",
", a mi pesar, no puedo dejarte ir. Debo requisar tu nave y ponerla contra estos invasores.",
"Disculpe, señor, no escuché lo que dijo...",
"Si se resiste, capitán, tendré que confiscar su barco. \nTrate de entender que no tengo otra alternativa.",
"Bueno, entonces, déjeme ofrecerle una alternativa - Mi nave y yo estamos a su servicio.",
"¿Vas a obligarme? ¡Adelante, inténtalo!",
"Su información no es de gran ayuda, capitán. Es una pena, porque su situación no es envidiable. Voy a decirle algo de todos modos, ",
".",
"Dígame algo interesante... Soy todo oídos, señor",
"Una excelente decisión, Capitán ",
". Me alegra que hayamos encontrado una resolución que nos conviene a ambos. Ahora, a su tarea. Me parece que en lugar de presionarte para que te pongas al servicio del ejército, sería mejor que\nactúe solo.",
"¿Qué quiere decir, señor?",
"Ignoraré su insolencia por ahora, capitán. Pero tenga en cuenta que hay un arma cargada en mi escritorio y hay guardias en la puerta. Ahora déjeme continuar...",
" En ese caso, me gustaría ser yo mismo el capitán de mi navío. ¡Déjeme navegarlo por usted, señor!",
"Como una nueva cara en estas aguas, espero que usted sea la clave para obtener más información sobre las fuerzas francesas. \nDesde la colonia vecina en la isla, se puede cruzar a través de la selva y penetrar en las murallas de la ciudad, y allí descubrir más de los ciudadanos locales.\nTal vez incluso podría escuchar a escondidas a las propias tropas francesas.",
"¿Quieres que me meta en la ciudad capturada y averigüe los planes franceses para la colonia?",
"¿Y qué hay del pago, señor?",
"Sí... Un plan audaz como digo. Si tiene éxito, quizás sepamos dónde esperar un nuevo ataque, y más importante, cómo liberar nuestra colonia.",
"Lo entiendo. Le deseo lo mejor, señor.",
"Por cierto, ¿podría adelantar parte del pago antes de que me ponga en marcha?",
"Si necesita dinero, capitán, aquí tiene 1000 de oro. Pero gástelo en preparar el barco para el viaje. Tenga en cuenta que voy a deducir este dinero de su pago final.",
"Gracias, señor.",
"Lamentablemente, Capitán ",
", No puedo pagarle por adelantado - nuestros fondos deben ser gastados en la construcción de un escuadrón y en preparar el fuerte para una posible campaña militar.",
"Qué inspirador.",
"Le aseguro, capitán, que será compensado. Pero no intente engañarme. Si trata de escaparse de sus deberes, \nAnunciaré que eres un pirata, y el escuadrón del Capitán Tomilson te perseguirá hasta el final de tus días.",
"¡Si queda algo después de la batalla con los franceses!",
"Hmm... Nuestra conversación ha ido un poco mal. Recuerde, su tarea es recuperar la información sobre los planes franceses para #sOxbay#. \nHabla con la gente del lugar, ve a la taberna, seguro que está intacta y abierta, estoy seguro que a los franceses no les importa descansar después de la batalla.\nHaga lo que pueda para averiguar los planes del comando francés. \nCréame, en este caso seré muy generoso con mi recompensa. Buena suerte, ",
"Adiós, señor.",
"Escuche, ",
", piense en ello como un mal necesario. Al final, debería sentirse afortunado. \nHas sido aceptado al servicio de la Corona, una posición que muchos desean disfrutar. Además, soy conocido por ser generoso con mis capitanes",
"Espero ser testigo de esa generosidad pronto.",
"Hmm... Felicitaciones por su regreso, capitán. Por favor, haga su informe.",
"Los ciudadanos de #sOxbay# no tienen aprecio por sus captores.",
"¿Y se las arregló para averiguar lo que esta invasión significa para los futuros planes franceses?",
"Están usando #sOxbay# como un peldaño para un asalto a #sRedmond#. El escuadrón que permanece en #sOxbay# está esperando la munición, planeada para llegar desde #sisland_Falaise de Fleur# a bordo de una nave de carga. Una vez que se reabastezcan, van a zarpar y atacar #sRedmond#.",
"Esta información es invaluable. Has demostrado tu valor. Gracias por tu servicio, ",
". Aquí está 3000 de oro como pago.",
"Gracias, señor.",
"Ahora, a la luz de estas noticias, su próxima tarea es asegurarse de que la munición no llegue a #sOxbay#. Cuando finalmente nos encontremos con los franceses en la batalla, cuanta menos pólvora tengan, mejor.",
"¿Quieres que hunda la barcaza?",
"Le dejaré el método a usted, capitán. Abordarlo, hundirlo... esa es su decisión. Lo principal es evitar que los franceses obtengan esa munición.",
"¿Y qué hay de su escolta? Puede ser demasiado para mi nave.",
"Sí. Seguro que tiene una escolta. Seguro, ",
".",
"De acuerdo. Pero, ",
", tal vez haya una manera de usar eso a nuestro favor.\nYa que has demostrado que tienes la habilidad de deslizarte en territorio hostil, y mantener tu ingenio, deberías zarpar hacia #sFalaise de Fleur#. Con un poco de ingenio y unas pocas preguntas bien hechas, tal vez puedas encargarte de la escolta antes de que zarpe...",
"Suena dudoso... pero lo intentaré.",
"Bien, ",
", pero no te olvides de dirigirte a mí apropiadamente.",
"Nosotros, los piratas, no estamos acostumbrados a tales formalidades...",
"Entonces recuerda que mientras me sirvas a mí, servirás a la Corona. Tenga en cuenta esto, capitán.",
"Sí, señor.",
"Tengo entendido que se las arregló para exprimir la vida del escuadrón francés",
"Absolutamente, señor.",
"Después de que zarparas, envié otro capitán a #sisland_Oxbay#. Se las arregló para descubrir una gran cueva en la isla cerca de una playa aislada. \nTengo la intención de desembarcar una guarnición de soldados y esconderlos en esta cueva. Una vez que estén en su lugar, usaré estos soldados para liberar la ciudad mientras hacemos un ataque coordinado desde el mar y la tierra.",
"Un plan razonable, pero dudo que haya suficiente espacio en mi nave para un destacamento entero.",
"No es necesario, capitán. Ya me he ocupado del transporte. Su tarea será vigilar la nave de desembarco a lo largo de su ruta. El balandro 'Albion' comandado por el Capitán ",
"Ewan Glover",
"Ewan Glover",
", está anclado en el puerto. ",
"Ewan Glover",
" te esperará en las puertas de la ciudad.",
"Ya veo. Entonces, supongo que me despediré...",
"Espera, no he terminado. Tienes que escoltar el balandro de 'Albion' al puerto de #sGreenford# en #sisland_Oxbay#. \nUn hombre local, leal a la Corona, le mostrará el camino a la cueva. Después de eso, una vez más te infiltrarás en #sOxbay#, y buscarás a uno de nuestros agentes escondido en la ciudad.",
"Eso es mucho para recordar. Entonces, ¿qué debo hacer cuando llegue al agente?",
"Tiene información muy importante. Por eso debes hacer todo lo posible para asegurarte de que sobreviva y pueda transmitirnos esa importante información.",
"¿Y el nombre del agente?",
"Counterspy",
". Ha hecho contactos con los ciudadanos locales. Si no puedes encontrarlo inmediatamente, pregunta por ahí. Pero hágalo discretamente.",
"Como quieras. Ahora, ¿cuándo recibiré el pago de mi última misión?",
"No se preocupe, ",
", aquí está su oro.",
"Me alegra oír eso, señor.",
"Ahora puede irse, capitán. Estaré esperando su próximo informe.",
"Adiós, señor.",
"Bien, Capitán ",
"..., Pensaba mejor de ti. Pero lo hecho, hecho está. Por lo menos parte de la tarea se ha completado.",
"Pero...",
"Felicitaciones, capitán. Honestamente, no puedo decirle el alivio que ha sido desde que lo acepté a mi servicio.",
"Gracias, señor",
"No me interesan sus explicaciones, capitán. Escuché su informe de ",
"Counterspy",
" y explicó lo que pasó. Sólo estoy decepcionado de que debido a su fracaso, habrá más sangre perdida en esta guerra.",
"Lo siento, ",
", Hice lo mejor que pude.",
"... Bueno... Estas cosas pasan. Después de todo, gracias a usted, hemos tenido la oportunidad de reconstruir nuestro escuadrón.",
"Entonces, ¿cuál es mi próxima tarea?",
"Vas a participar en el asalto de #sOxbay# como parte de nuestro escuadrón. No hace falta decir que tienes que prepararte. \nEspero que esto sea suficiente para ti. Y, he deducido una parte de
su pago debido a la pérdida del 'Albion'.",
"¿Cuándo zarparemos?",
"Pronto. Por ahora, haz lo que necesites en la ciudad, y cuando llegue el momento, se te notificará. Y descansa un poco y relájate. Cada capitán debería tener una buena noche en la taberna después de una navegación.",
"Lejos de eso, pero en tus palabras hay un núcleo de verdad.",
"Eso no es importante. Mi mensajero te encontrará. Buena suerte, capitán.",
"Adiós.",
"counterspy",
" me acaba de informar de sus hazañas. Y ",
"Ewan Glover",
"Ewan Glover",
" parecía bastante satisfecho con su crucero juntos.",
"Hmm... No puedo interpretarlo como una hazaña.",
"Ja. Eres demasiado modesto. Bueno, aquí está tu recompensa. Te sugiero que hagas que tu navío esté en condiciones de navegar. Tendrás que zarpar de nuevo muy pronto.",
"¿Y qué clase de misión será esta vez?",
"El asedio a #sOxbay#. Te unirás a nuestro escuadrón que va a liberar la isla.",
"¿Y cuándo zarpará el escuadrón?",
"Pronto. Por ahora, haz lo que necesites en la ciudad, y cuando llegue el momento, se te notificará. Y descansa un poco y relájate, cada capitán debe tener una buena noche en la taberna después de una navegación. Enviaré allí un mensajero a por ti.",
"Está bien. Me iré ahora.",
"¡¿Ah?! ¡¿Qué?! ¡¿Qué estás haciendo aquí?! ",
"¿ ",
"Danielle",
"¿¡¡",
"Siento interrumpir su sueño, querido gobernador, pero tenemos preguntas que necesitan respuesta.",
"¿Qué quieres decir? ¡Váyase ahora, y consideraré perdonarle la vida!",
"Creo que no entiende su posición, gobernador, ",
". Ya no das las órdenes. Y si piensas en no responder, entonces ",
"Danielle",
", puede verse obligada a ejercitar sus elegantes técnicas de esgrima.",
"¡Está bien, está bien, por favor! No seas tan rebelde. Por supuesto que responderé a todas sus preguntas... Sólo envaina tu espada, ",
"Danielle",
", ¡por favor, contenedlo! Su mirada me pone nervioso.",
"Calla y escucha. Sabemos todo acerca de sus tratos con el tesoro, y usted tiene mucho por lo que responder.",
"¡Por favor, demonios, no me hagan daño!",
"Una valoración halagadora, pero por ahora, debería decirnos lo que sabe sobre el ídolo que abre la puerta del palacio.",
"¡No les diré nada, sinvergüenzas! ¡Guardias!",
"¡Oh no!",
"Danielle",
"¡ ¡Vamos a nuestras naves!",
"¡¿Escapó?! ¿Cómo puede ser?",
"No lo explicaron. Sólo que la búsqueda del fugitivo sigue en curso.",
"¡Maldita sea! ¡Esta situación se está saliendo de control!",
"Disculpe, señor, pero tengo buenas noticias para usted.",
"Entonces, oigámoslo, ",
", No tengo todo el día.",
"Encontré un rastro del capitán que traicionó a Inglaterra y su confianza.",
"Raoul Rheims",
"¿ Es verdad. No es la peor noticia de hoy.",
"Estoy listo para atraparlo ahora, si le complace, señor.",
"Por supuesto, los buenos vientos para ti, ",
". Y capitán... esta vez tiene que traerlo de vuelta. Y tenga en cuenta que hasta que llegue aquí, no debe hablar con nadie, ni siquiera con usted. ¿Está claro?",
"Sí, señor. Haré todo lo que usted diga.",
"¡ Has estado fuera tanto tiempo que he empezado a preocuparme por ti!",
"Estoy bien, y he completado tu tarea.",
"Para ser honesto, estoy sorprendido, no esperaba resultados positivos de esta expedición. \nEntonces, te las arreglaste para conseguir toda la colección para mí, ¿verdad?",
"Sí señor, excepto un ídolo. Fue comprado por un extraño.",
"¿Un ídolo? Echemos un vistazo a lo que falta.",
"Aquí, véalo usted mismo, señor.",
"Es cierto, falta un ídolo, qué lástima.",
"¿Quiere que encuentre este también, señor?",
"No, no te preocupes, ",
". Aunque aprecio que estés listo para ayudar. En cambio, tengo otra tarea para ti. Encontraré a alguien más para enviarlo tras el ídolo. \nOh, sí, casi lo olvido. Aquí está el pago que le prometí.",
"Gracias, señor, es muy generoso, muy generoso de verdad. Tengo curiosidad por saber qué misión tiene para mí.",
"Sí, bueno... Varios minutos antes de su llegada, ",
", Me informaron que un pirata fue capturado en #sGreenford#. Este pirata en particular siempre ha logrado escaparse de mi alcance muchas veces y me ha molestado mucho. \nQuiero que me traigas este pirata.",
"Suena bastante simple, señor. ¿Puedo irme?",
"Sólo un momento, ",
". Aprecio su entusiasmo, pero eso no es todo.",
"Lo siento, señor.",
"A su llegada a #sGreenford#, hable con el comandante de la prisión, ",
"El comandante de la prisión de Greenford",
"El comandante de la prisión de Greenford",
". \nMuéstrale esta carta, y él liberará al prisionero bajo tu custodia. \nCuando regreses, recibirás 5000 de oro.",
"Entendido, señor.",
"Espero que su regreso signifique que ha completado mi tarea y que ha entregado la carta a su destinatario.",
"Sí, señor. Pero fue un desafío. Los modales de los piratas dejan mucho que desear, pero tenga la seguridad de que ha recibido la carta.",
"Bien hecho. Espero que la próxima tarea también sea tan hábilmente manejada, ",
".",
"¿Y cuál sería ese trabajo?",
"Espera, no hay necesidad de apresurarse, ",
". Primero, déjame darte tu recompensa.",
"Gracias, señor. Es un placer trabajar con usted, señor.",
"Y tu adulación es siempre apreciada, ",
". Ahora, vayamos a los negocios.",
"Soy todo oídos, señor.",
"Tu próximo esfuerzo, ",
", es algo personal para mí. En mi posición puede ser un poco contrario a la ética utilizar las fuerzas imperiales para mis propios asuntos. Así que estoy especialmente interesado en usarte.",
"Estoy intrigado, señor. Mientras no quiera que me enfrente solo a la flota francesa...",
"Tienes sentido del humor, ",
", pero no nos distraigamos del tema principal.",
"Lo siento, señor.",
"Un navío fue capturado por piratas hace varios días, '",
"capitán pirata 06",
"', se dirigía a Europa desde Nueva Luz. Mientras pasaba por nuestra colonia, los piratas atacaron. \nAdemás de los bienes comerciales habituales, había varios ídolos dorados a bordo. Estos son raros tesoros incas que he pedido para mi colección. \nMe las arreglé para descubrir al señor pirata que ordenó la captura. Su nombre es ",
"Alistair Garcilaso",
"Alistair Garcilaso",
". \nDicen que él y su banda de carniceros y ladrones se esconden en la jungla de #sisland_Douwesen#, pero no sé exactamamente. \nTe necesito, ",
", para encontrarlos y traer mi colección de alguna manera. \nMe doy cuenta de que no es la tarea más fácil, y por eso te doy 10000 ahora y una cantidad igual si la misión se completa con éxito. \nComo he mencionado, detesto usar personal del ejército para asuntos personales. Y, la mera idea de desembarcar tropas en #sisland_Douwesen#... bueno, nos arriesgaríamos a un conflicto con los holandeses. \nEres mi única esperanza.",
"Encontrar hombres que no desean ser encontrados no es una tarea fácil, pero creo que le sirvo bien, y en efecto, esta es una suma generosa.",
"Bueno, si logras esto, bien valdrá la pena, ",
". Así que, sin más preámbulos, aquí está su pago. Buena suerte.",
"Volveré tan pronto como pueda, señor.",
"Has vuelto, ",
", pero ¿dónde está ",
"Raoul Rheims",
"? No lo veo contigo.",
"He fallado, señor, perdí el rastro en la guarida del contrabandista.",
"Me decepcionas, ",
". ¡¿Una misión tan simple, y no pudiste completarla?! Tenía una opinión más alta de ti.",
"Tiene mis disculpas, señor. Sin embargo, si me permite, me las arreglé para averiguar lo que ",
"Raoul Rheims",
" es lo siguiente que va hacer. Va a una expedición. Aquí está su diario, explicándolo.",
"No es mi naturaleza castigar el fracaso, especialmente cuando se ha hecho un esfuerzo serio. Pero espero que no fracase en su próxima misión.",
"Gracias por confiar en mí, señor. Haré todo lo posible para no volver a decepcionarlo.",
"De nada, ",
". A propósito, aquí está los 5000 de oro que prometí darte, aunque no son totalmente merecidos.",
"Gracias, señor. Su generosidad me sorprende.",
"Ya es suficiente, ",
". No tienes que adularme. Ahora... Hablemos de negocios. Tengo entendido que has estado en el nido del pirata\nAsí que, ahora que sabes a dónde ir, necesito que cojas esta carta y se la entregues al señor pirata. Se llama ",
"Isenbrandt Jurcksen",
"Isenbrandt Jurcksen",
". \nAhora, antes de que se alarmen, estoy seguro de que tienen curiosidad por la posible comunicación que podría tener con este demonio. Puede que recuerde que ",
"Raoul Rheims",
" ahora sabe demasiado para que yo lo deje escapar\nSi no son capaces de atraparlo, estos piratas pueden. Entonces, ¿cuándo vas a empezar tu viaje?",
"Mi navío está listo para zarpar, señor.",
"Perfecto. Entonces zarpe inmediatamente. Después de que hayas cumplido con tu deber, regresa a mí por la recompensa. ¿Está todo claro, ",
"?",
"Sí, señor, zarparé inmediatamente.",
"Bien, nadie puede molestarnos.",
"Adelante, señor.",
"Primero, me gustaría compartir noticias alegres - #sOxbay# es libre\nNos ayudaste mucho en nuestra búsqueda de la victoria. Gracias.",
"De nada. ¿tal vez tengas algo para mí a continuación?",
"Por supuesto. ¡Quiero que me traigas a la persona que nos traicionó y puso nuestra colonia en tal peligro! Su nombre es ",
"Raoul Rheims",
"Raoul Rheims",
".",
"Si puedo preguntar, ¿qué hizo?",
"¡Inquisitivo! Me gusta eso. No te equivoques. Reims es el traidor más vil a la Corona. Y un traidor de su propia tripulación también. Estaba llevando a cabo una misión muy importante cuando cambió de lealtad\nCuando uno de sus tripulantes me advirtió de la traición de Reims, casi pudimos prevenir esta calamidad\nLamentablemente, el pobre hombre ya estaba a las puertas de la muerte, y no podía decirme hacia dónde se dirigía Reims\nSabemos que se detuvieron en el campamento pirata para reabastecerse. Deberías ir a este campamento pirata y si ",
"Raoul Rheims",
", sigue ahí, arréstenlo\nSi no lo encuentran, descubran lo que puedan.",
"Entendido. Sin embargo, enfrentarse a los piratas es peligroso. Espero ser bien compensado.",
"Y lo serás. Te pagaré 5000 de oro ahora y 5000 cuando vuelvas con el traidor.",
"Un precio justo. Seguiré mi camino, señor.",
"¿Cómo es que eres libre? ¿Qué ha pasado? ¿Qué pasa con los guardias?",
"Lo siento, pero fui encarcelado injustamente. No iba a estar atrapado allí para siempre. Cuando recuperé mi arma, sólo busqué mi libertad.",
"Lo siento, ",
"¡ Ha habido un terrible error. \nMis soldados debían arrestar a un espía francés. \nClaramente te confundieron con el espía.",
"Gracias por disculparse, señor, no estaba seguro de que volvería a ser libre.",
"Aplaudo su habilidad y astucia. Te honra, pero el carcelero debería ser colgado por dejarte escapar",
"Me temo que no tiene a nadie a quien colgar, señor. Ya se han ocupado de él.",
"El carcelero es asunto tuyo. Ahora, si fuera tan amable de explicarme la razón por la que me encontré en la cárcel...",
"Señor, me gustaría hablar en su nombre. Él dice que era bastante hábil con las armas en su día. Necesito un buen artillero, y con su permiso, me gustaría encargarme de él.",
"Hmm. I suppose leniency can be considered, ",
", pero este carcelero sirve a la colonia - No puedo dejarlo ir.",
"Entonces dígame su precio por reemplazarlo, señor.",
"1000 de oro serán suficientes.",
"Un trato justo, señor. Acepto",
"Ah, bueno. Esto es más de lo que esperaba. Será mejor que este carcelero te sirva.",
"Llévatelo, pero luego te arrepentirás, he oído que es un borracho.",
"Tendré en cuenta su advertencia, señor. Ahora, tal vez le gustaría explicarme por qué fui arrestado.",
"Eres demasiado sediento de sangre, pero eso puede ser lo que se requiere para este mundo - tu mano nunca vacilará con lástima.",
"Eso espero, señor. Ahora, si puede, por favor dígame por qué me ha arrestado",
"Un terrible error. Un terrible error. Mis soldados fueron enviados a arrestar a un espía francés. Mis agentes me aseguraron que estaba en la taberna en ese mismo momento\nParece que ya se había ido, y mis soldados te arrestaron en su lugar.",
"Bueno, un misterio está resuelto. Puedes imaginar mi angustia cuando me encontré en ese oscuro y espantoso lugar.",
"Un terrible error. Un terrible error. Mis soldados fueron enviados a arrestar a un espía. \nMis agentes me aseguraron que estaba en la taberna en ese mismo momento. \nParece que ya se había ido, y mis soldados te arrestaron en su lugar.",
"Bueno, un misterio está resuelto.",
"Bueno, ahora que hemos terminado con todas estas tonterías, me gustaría que vinieras conmigo a mi estudio.\n Tengo asuntos importantes que discutir con usted.",
"Por supuesto, señor.",
"Por favor, acepte mis disculpas una vez más por las acciones de mis soldados. \nCreo que este dinero le demostrará cuánto lamento el incidente.",
"Gracias, señor. Por mi parte, le agradezco su amabilidad hacia mí.",
"Deseo servir a Inglaterra, Su Excelencia.",
"#sgov_nation# siempre se complace en aceptar nuevos capitanes a su servicio. ",
"Actualmente estamos",
"Actualmente no estamos",
" en guerra con ",
"El ",
"ninguna nación",
". Por supuesto,",
" pero",
" Los piratas siempre deben ser hundidos al verlos.",
"Haré que se sienta orgulloso, su Excelencia.",
"¿Cómo lo estoy haciendo, señor?",
"Has hundido ",
" barcos enemigos, ",
" barcos piratas, un total de ",
" barcos.",
"Gracias.",
"Espero que no tenga problemas con mi servicio, señor.",
"¡Claro que no, capitán! De hecho, es un placer para mí otorgarle una comisión en la Marina de Su Majestad Británica. Como oficial será recompensado por cada barco que hunda al servicio de Inglaterra.",
"Me siento honrado, Su Excelencia, y me esforzaré por estar a la altura de la confianza que Su Majestad me tiene.",
"Me gustaría cobrar mi salario, señor.",
"Bueno, has hundido ",
" barcos enemigos, ",
" barcos piratas, ",
" total de las naves. Sus salarios actuales son ",
", así que un total de ",
"Gracias señor.",
"¡Escoria traidora! Hundir los barcos de tus compatriotas, ¿verdad? Quedas relevado del servicio militar, ¡tu nombre será borrado de la lista, y no quiero volver a ver tu cara en esta ciudad!",
"...",
" desde la última vez, aquí está ",
" oro",
"He oído que estoy listo para un ascenso.",
"¡En efecto, lo estás! Excelente trabajo. Tu nuevo rango es ",
"Gracias señor.",
" Barcos españoles, ",
" Barcos holandeses, y ",
"¿Ah, sí? Tengo una propuesta para usted, capitán.",
"¿En serio?",
"Me he enterado de que ha completado la tarea con éxito; ¡mis felicitaciones, capitán! Aquí está su recompensa.",
"Mi agradecimiento, fue un placer ayudarles.",
"Debes destruir el ",
" buque ",
"",
" amenazando el envío ",
". Si la hundes, te recompensaré con la gran suma de ",
" oro. ¿Qué dice usted, capitán?",
"No volverás a oír hablar de ella, eso te lo prometo.",
"Me temo que no puedo ayudarle.",
"Ah, ",
", ¡Me alegro de verte! Yo soy el Señor ",
", enviado por Su Majestad para arrestar a Silehard y traerlo de vuelta a Gran Bretaña; o, en su defecto, para tratar más... directamente sobre él... Usted, ",
", han hecho mi tarea mucho más fácil.",
"Fue un placer, mi señor.",
"Fue un placer, mi señor. ¡De hecho, tengo una sorpresa para usted!",
"Solicito el perdón, su Excelencia.",
"Estoy interesado en saber acerca de #sgov_nation# las relaciones con otras naciones.",
"Estoy buscando una carta de marca.",
", Qué bueno que pases por aquí. Me gustaría presentarte a mi ",
". Ella vendrá una vez que hayamos terminado el negocio.",
"No puedo seguir sirviendo ",
", Su Excelencia.",
"Estoy rayado de servir ",
"Como seguro de que es un capitán competente, y para recompensar mi tiempo en la presentación de su caso a ",
", Debo pedirle ",
" oro.",
"De ninguna manera.",
"Muy bien.",
" En vista de su anterior servicio, ",
" le otorga el rango de ",
"Has perjudicado a ",
", y ",
" no se olvida de sus enemigos. ¡Váyase de inmediato, o los guardias le echarán por las orejas!",
"Has causado ",
" un gran daño, capitán, pero ",
" está dispuesto a pasar por alto sus transgresiones pasadas... por un precio: ",
"Muy bien, señor. Acepto.",
"Un placer tratar con usted, ",
"Lo mismo digo, Su Excelencia.",
". Además, se le concede ",
" acres de tierra por orden de ",
"¿Está seguro?, ",
" lamentará perder su servicio.",
"Sí, lo estoy.",
" no se toma a bien a los traidores, ",
"Uh, no importa.",
"Muy bien. Pero espero que lo reconsidere... con el tiempo.",
"Adiós, ",
"¿Eh?",
"Señor, he visto una flota francesa cerca de #sOxbay#!",
"¿En serio? ¿Cuántos barcos? ¿Y qué estaban haciendo?",
"Umm... lo siento, no puedo decirlo. Una terrible tormenta me alejó antes de que pudiera investigar.",
"Una tormenta, ¿eh? Bah, apuesto a que huiste como las ranas. De todos modos, sin detalles sobre la misión de los franceses, su supuesta información no es más que un rumor inútil.",
"De acuerdo, te daré tu información. Tal vez entonces me tomes en serio. Adiós, señor.",
"Su Majestad lamentará no tener a Silehard en la Torre. Pero esto al final es igual. De hecho, es un placer para mí recompensarle por este servicio a Gran Bretaña con la gran suma de 200.000 de oro.",
"Es usted muy generoso, mi señor.",
"¿En serio?",
"En efecto. Capturé a Silehard; mis hombres lo están trayendo aquí mientras hablamos.",
"¡Oh, excelente! Su Majestad estará muy complacido. ¡Tan complacido, de hecho, que estoy seguro de que autorizará personalmente que le entregue la gran suma de 400.000 de oro como recompensa por tal servicio!",
"El servicio generoso proporciona recompensas generosas, ",
".\nSu Majestad también ha creído conveniente confiarme la gobernación de esta isla, llamándome a salir de la jubilación; pero siempre estoy feliz de servir a Su Majestad y a Gran Bretaña. Pero estoy divagando. Así que de ahora en adelante seré su representante ante la Corona, dándole tareas y recompensando su servicio.",
"Sería un honor servir a un hombre tan famoso como usted.",
"Estoy seguro de que lo hará bien, mi señor, pero me temo que debo seguir mi camino.",
"Me halaga, ",
".\nAhora, déjenos discutir su situación. Usted fue obligado a la hostilidad con nuestro país por las lamentables acciones de Silehard; pero ",
" sabe que esto no fue culpa suya.",
" por lo tanto está disponible para retomar el servicio en su rango anterior. Bienvenido de nuevo, ",
"Su destreza ha impresionado tanto ",
" que me ha encargado que le otorgue de inmediato una carta de marca.",
"Gracias, mi Señor.",
"Primero, me gustaría compartir algunas noticias gratificantes - #sOxbay# es libre. Nos ayudaste mucho en nuestra búsqueda de la victoria. Gracias.",
"Difícil.",
"El resto de las naves estuvieron ocultas por la niebla.",
"Pronto. Por ahora, haz lo que necesites en la ciudad, y cuando llegue el momento, se te notificará. Yo mismo debo salir de aquí ahora para una conferencia de gobernadores. Lord Cutler Beckett se hará cargo temporalmente de esta oficina, su nave debería estar atracando mientras hablamos. Por ahora, descanse y relájese. Cada capitán debería tener una buena noche en la taberna después de una navegación

.",
"Pronto. Por ahora, haz lo que necesites en la ciudad, y cuando llegue el momento, se te notificará. Yo mismo debo salir ahora de aquí para una conferencia de gobernadores. Lord Cutler Beckett se hará cargo temporalmente de esta oficina, su nave debería estar atracando mientras hablamos. Por ahora, descanse y relájese, cada capitán debe tener una buena noche en la taberna después de una navegación. Lord Beckett enviará allí un mensajero para usted
.",

};
