string DLG_TEXT[136] = {
"Bienvenidos a Singapur, soy Sao Feng el Seсor Pirata del Mar de la China Meridional. Entonces, їquй negocios tiene para mн?",
"Quisiera ofrecer mis servicios.",
"їEs usted capitбn? їCуmo te llamas?",
"Me llamo Capitбn ",
", capitбn del '",
"'.",
"Bien, recordarй tu nombre. Ahora, dime quй te hizo venir a mн.",
"Me gustarнa hablar de negocios con usted.",
"Nada. Me voy, si me lo permite.",
"Puedes irte. Pero no desaparezcas completamente, es posible que tenga planes para ti.",
"Como usted diga, #saddr#.",
"Soy todo orejas. їQuй te hizo venir a mн?",
"Negocios, #saddr#.",
"Me voy.",
"Entonces hablemos de negocios.",
"Algo parece preocuparte.",
"Su misiуn fue un йxito. Como puede ver, he traнdo aquн a sus damas desaparecidas.",
"Quiero hablar de un hombre que encuentra el favor de su gracia.",
"Su misiуn estб cumplida, seсor.",
"No tengo nada que discutir con usted en este momento, #saddr#",
"Sн, ya lo sй, aquн estб su recompensa. Espero que en el futuro pueda utilizar sus servicios.",
"Cuando quieras, #saddr#.",
"Entonces, їde quiйn quieres hablar?",
"Un bucanero, #sBernardo Gamboa#, seсor.",
"",
"",
"Ah. ЎїEse hombre?! їY quй quieres que diga? Por lo que sй, su reputaciуn es intachable...",
"Podrнas equivocarte. Por lo que sй, secuestrу a un hombre de tu pueblo.",
"Ah, ah, ah. їEstбs seguro de eso? No quiero insultarlo injustamente.",
"Si no te importa, investigarй esto en privado. Nadie sabrб de tu participaciуn. Si no secuestrу a este hombre, tu relaciуn con йl permanecerб intacta, si lo hizo, entonces le mostrarнas a todos lo justo y poderoso que eres.",
"Hmmm... Eso no es irrazonable. De hecho, no arriesgo nada en este caso. Usted puede averiguar lo que estб pasando. Si su misiуn termina con йxito, le recompensarй. Pero, ya que esta es su iniciativa, serб una modesta suma.",
"Gracias seсor.",
"Recuйrdame, їde quй estбbamos hablando?",
"Estбbamos hablando de un hombre secuestrado.",
"Ah, sн, lo recuerdo. Segъn tengo entendido, realmente fue secuestrado.",
"Sн. El sinvergьenza no quiso devolverlo y fue masacrado por sus propios hombres.",
"Bueno, no hay pirata, no hay problema. Aquн estб tu recompensa. Puedes salir de mi habitaciуn ahora...",
"Como quieras.",
"Ah, їentonces crees que puedes ayudarme con mis problemas?",
"Sн. Si lo permites, oh gran Sao Feng.",
"Puedo decir que eres un hombre inteligente, asн que te dirй algo.",
"Soy todo un par de orejones.",
"Hoy encontraron a dos hombres muertos. Uno de ellos tenнa un trozo de tela carmesн en la mano. \nVarias horas antes, habнan descubierto que una corbeta fue vista navegando lejos de la isla a toda vela. \n y para colmo mis dos guardaespaldas han desaparecido.",
"їY esto detiene tu investigaciуn?",
"Bueno... Es obvio que mis guardaespaldas fueron secuestrados y sacados de la isla. En circunstancias normales, yo mismo los buscarнa. Sin embargo, debo quedarme en Singapur y no puedo marcharme a buscarlos porque me llevarнa demasiado tiempo. \nDeberнas entenderlo, Capitбn. El mar ofrece muchos lugares para esconderse. De todos modos, si te conmueve tanto el dolor de esta historia, te ofrezco un desafнo para encontrar a mis damas. \nPrometo que si la bъsqueda tiene йxito, te mostrarй mi gratitud.",
"De acuerdo, estoy de acuerdo, pero primero me gustarнa saber dуnde puedo encontrar un testigo que vio la corbeta.",
"No, no quiero gastar mi tiempo en tales chorradas.",
"їAceptas? ЎPerfecto! Puedes encontrar al testigo en la taberna. Fue mi primer oficial quien vio el navнo, lo vio mientras patrullaba una regiуn para mн.",
"Gracias, їpuedo irme ahora?",
"Deseo servir a los piratas de Singapur, Su Excelencia.",
"Los piratas de Singapur siempre se complacen en aceptar nuevos capitanes a su servicio. ",
"Actualmente estamos",
"Actualmente no estamos",
" en guerra con ",
"El ",
"ninguna naciуn",
". Por supuesto,",
" pero",
" otros Piratas siempre deberнan ser hundidos al verlos.",
"Harй que se sienta orgulloso, su Excelencia.",
"їCуmo lo estoy haciendo, seсor?",
"Has hundido ",
" Barcos franceses, ",
" buques piratas, un total de ",
" navнos.",
"Gracias.",
"Espero que con mi deber no haya problemas, seсor.",
"ЎClaro que no, capitбn! De hecho, es un placer para mн otorgarle una comisiуn en la Marina de Su Alteza Real. Como oficial serб recompensado por cada barco que hunda al servicio de los piratas de Singapur.",
"Me siento honrado, Su Excelencia, y me esforzarй por estar a la altura de la confianza que me tiene Su Alteza Real.",
"Me gustarнa cobrar mi salario, seсor.",
"Bueno, has hundido ",
" Barcos franceses, ",
" Barcos piratas, ",
" total de las naves. Sus salarios actuales son ",
", asн que un total de ",
"Gracias seсor.",
"ЎEscoria traidora! Hundir los barcos de tus compatriotas, їverdad? Quedas destituido del ejйrcito, tu nombre serб borrado de la lista, Ўy no quiero volver a ver tu cara en esta ciudad!",
"...",
" desde la ъltima vez, aquн tienes ",
" oro",
"He oнdo que estoy listo para un ascenso.",
"ЎEn efecto, lo estбs! Excelente trabajo. Tu nuevo rango es ",
"Gracias seсor.",
" Barcos Espaсoles, ",
" Barcos ingleses, y ",
"їAh, sн? Tengo una propuesta para usted, capitбn.",
"їEn serio?",
"Me he enterado de que ha completado la tarea con йxito; Ўmis felicitaciones, capitбn! Aquн estб su recompensa.",
"Mi agradecimiento; fue un placer ayudaros.",
"Debes destruir el ",
" buque ",
"de guerra pirata",
" amenazando el envнo ",
". Si la hundes, te recompensarй con la gran suma de ",
" oro. їQuй dice usted, capitбn?",
"No volverб a oнr hablar de ella, lo prometo.",
"Me temo que no puedo ayudarle.",
"Solicito el perdуn, su Excelencia.",
"Estoy interesado en aprender sobre #sgov_nation# las relaciones con otras naciones.",
"Estoy buscando una carta de marca.",
"Ah, ",
", Quй suerte que te hayas pasado por aquн. Me gustarнa presentarte a mi ",
". Ella vendrб una vez que hayamos terminado el negocio.",
"Ya no puedo seguir sirviendo ",
", Su Excelencia.",
"Estoy rayado de servir ",
"Como seguro de que es un capitбn capacitado, y para recompensar mi tiempo en la presentaciуn de su caso a ",
", Debo pedirle ",
" oro.",
"De ninguna manera.",
"Muy bien.",
" En vista de su anterior servicio, ",
" le otorga el rango de ",
"Has hecho daсo a ",
", y ",
" no se olvida de sus enemigos. ЎVбyase de inmediato, o los guardias le echarбn por las orejas!",
"...",
"Has causado ",
" un gran daсo, capitбn, pero ",
" estб dispuesto a pasar por alto tus transgresiones pasadas... por un precio: ",
"Muy bien, seсor. Acepto.",
"Un placer tratar con usted, ",
"Y con usted, su Excelencia.",
". Ademбs, se le concede ",
" acres de tierra por orden de ",
"їEstб seguro?, ",
" lamentarб perder su servicio.",
"Sн, lo estoy.",
" no se toma a bien a los traidores, ",
"Uh, no importa.",
"Muy bien. Pero espero que lo reconsidere, con el tiempo...",
"Adiуs, ",
"їEh?",
"Difнcil.",
"No eres miembro de los Hermanos de la Costa. Hasta que no te unas a ellos en el asentamiento de piratas en #sisland_Quebradas Costillas#, Ўno tenemos nada que discutir!",
"Ah, claro. Perdуn. Considerarй esa posibilidad.",

};