string DLG_TEXT[50] = { 
"Tengo mi oнdo bien informado, Capitбn.",
"Bien por ti.",
"Puede que quieras visitar al capitбn de la taberna.",
"Estб bien. Gracias.",
"їHas oнdo al ъltimo capitбn?",
"No. Pero estoy seguro de que estoy a punto.",
"Dicen que el mapa del tesoro de Cortez ha sido encontrado.",
"їEn serio?",
"Sн, dicen que Barbossa lo encontrу. Estб en una especie de isla secreta.", 
"Bueno, no puede ser tan secreto si lo sabes, їverdad?",
"ЎCapitбn! Estoy tratando de ayudarte.",
"Muy bien, entonces mi querido amigo, adelante.",
"No necesito tu ayuda ahora mismo. Estoy muy ocupado, їentiendes?",
"Dicen que se emborrachу celebrando su buena fortuna y que alguien se lo robу. Lo dividiу en cuatro partes, lo hizo, y las escondiу por las islas.",
"Saben mucho 'ellos'їno?, Asн que, uno podrнa preguntarse їpor quй no van a buscar el tesoro 'ellos' mismos?",
"ЎAh! Capitбn, dicen que Barbossa descubriу quiйn lo robу, e hizo que los mataran.",
"Supongo que despuйs de que consiguiera que le dijeran dуnde habнan escondido las piezas", 
"Ahн estб el capitбn de feria. Dicen que Barbossa estaba tan enfadado que hizo que los mataran antes de que se lo dijeran.",
"Hmm... No es muy inteligente. їDe todos modos quiйn es este Barbossa?",
"Es un Seсor de los Piratas. Йl estб bien conectado con los cнrculos piratas.",
"їEn serio? Bueno, creo que es suficiente informaciуn por el momento. Tengo asuntos que atender. Nos vemos de nuevo. ЎOh! Y dale mis saludos a 'Ellos'.",
"Hola de nuevo capitбn, їvolviste tan pronto? No he oнdo nada nuevo todavнa.",
"No, no, no es eso. Tengo una propuesta para ti. Necesito encontrar a alguien en #sisland_Isla Muelle#, y creo que podrнas ser el hombre adecuado para averiguar dуnde estб.",
"Eso no suena muy difнcil. їPor quй no puedes hacerlo tъ mismo?",
"Porque el hombre es prisionero de los espaсoles, y creo que se me podrнa reconocer como colaborador de la Compaснa, con mi barco en el puerto y cualquier charla suelta de la tripulaciуn. Si lo haces, no te prestarбn tanta atenciуn. Harй que valga la pena.",
"їCuбnto, vale la pena? Si es un prisionero, entonces tienen que ser las autoridades las que lo tengan. Hablar con las autoridades puede ser difнcil, si sabes a lo que me refiero.",
"їDigamos 500 en oro? La mitad ahora, el resto cuando volvamos.",
"Tenemos un trato, capitбn. Thomas encontrarб al hombre por usted. Ya verбs como lo hace. A propуsito, usa esta ropa. Te Parecerбs menos a un hombre de la Compaснa. їCuбndo nos vamos?",
"Sуlo acompбсame. Necesito revisar los suministros de la nave. Cambiarse de ropa es una buena idea. Aquн estбn los 250 en oro como primer pago.",
"Espera Capitбn, te perderбs la mejor parte. Me las arreglй para conseguir parte del mapa para ti, aquн estб.",
"Gracias, Thomas. Aquн tienes 100 piezas de oro por tus molestias. Mantente a salvo hasta que nos encontremos de nuevo.",
"Quй casualidad encontrarle aquн, Capitбn. їEstб buscando a alguien?",
"Sн, escuchй que un barco llegу aquн recientemente desde #sOxbay# y necesito saber si un tal Billy Brock estaba a bordo.",
"ЎEse contrabandista! Los piratas de aquн no lo aguantarнan. Es demasiado torcido incluso para ser un sacacorchos. Me temo que ha sido mal informado Capitбn, йl no se irб de #sOxbay#.",
"їQuieres decir que todavнa estб allн?",
"Bueno, llegamos capitбn.", 
"Sн, lo hicimos.",
"Este lugar parece una verdadera madriguera de conejos.",
"Pareces ocupado, pero estoy seguro de que descubrirбs algo. Serб mejor que nos separemos ahora. Ve a ver quй puedes averiguar. Yo harй lo mismo.",
"Sн, sн, capitбn. їCuбl es el plan entonces? Para despuйs, quiero decir...",
"Nos reuniremos en la taberna mбs tarde para comparar notas.",
"Me temo que sн, capitбn. Serб mejor que lo busque usted mismo esta vez y no escuche los rumores.",
"De acuerdo, se trata de #sOxbay# volvamos allн.",
"",
"", 
"",
"Es bueno verlo de nuevo, capitбn. He oнdo que el Almirante espaсol de #sSanto Domingo# en #sisland_Hispaniola# ha perdido a su hijo.",
"Gracias por la informaciуn, Thomas.",
"Espera Capitбn, todavнa tengo que decirte la parte mбs importante. Dicen que la ъnica manera de encontrar la isla es con alguna extraсa brъjula azteca, y para descubrir el tesoro necesitas todas las piezas del mapa. їPor quй esto es asн?, no lo sй, tu suposiciуn es tan buena como la mнa, Capitбn.",
"Gracias Thomas, eso es muy interesante. Aquн tienes 100 piezas de oro por tus molestias. Mantente a salvo y si descubres algo mбs, hбzmelo saber.",

};
