string DLG_TEXT[58] = { 
"їTe gusta mi ъltimo uniforme?",
"Sн, capitбn.",
"Reconocerнa esa cara en cualquier lugar.",
"Oh, їen serio?",
"Sн, eres ",
", o no soy Thomas el Terror, el capitбn mejor vestido del Caribe.",
"Capitбn ",
", si no te importa.",
"Lo recordarй. Asн que eres el hijo de Teague, їeh? їQuй te trae a estas aguas?", 
"Preferirнa no discutir las relaciones familiares por el momento. Estoy pensando en ir a #sOxbay# para ver quй negocios puedo conseguir allн.",
"#sOxbay#, їeh? Bueno, es una coincidencia. Yo mismo voy para allб, el sastre acaba de recibir de Francia un nuevo material que me interesa para un nuevo uniforme que estoy diseсando. Tal vez podrнamos viajar juntos.",
"Pareces muy tranquilo. Por lo que me han dicho, todo el Caribe estб a punto de explotar.",
"ЎAh! Has hablado con Tia Dalma. Acabo de verla salir de la residencia.",
"No en detalle, pero acabo de 'verla'. [PIENSA: Bueno, casi hablй con ella... Asн que su nombre es Tia Dalma.]",
"Sн, es una historia profunda. їCuбnto sabes?",
"No mucho. Alguien o algo viene aquн y eso parece ser la raнz de todos los problemas.",
"ЎAh! Es mбs profundo que eso capitбn. Tia Dalma no es todo lo que parece ser. Ella fue una vez la amante de Davy Jones.", 
"ЎOh! їY tuvieron una riсa de amantes, supongo?",
"Por decirlo suavemente. Algunos dicen que es una princesa del vudъ y que causa muchas travesuras echando maldiciones a la gente, incluнdo a Davy Jones. Todo es muy turbio. La Hermandad le hizo algo y eso la tiene bastante alocada, segъn he oнdo.",
"їQuй es lo que le hicieron?",
"Nadie fuera de la Hermandad lo sabe y no lo diremos. Puedo decirte que es algo por lo que ella no puede hacer nada.",
"їPor eso fue a ver a mi padre? їPara hacer que cambie de opiniуn? [PIENSA: 'No lo diremos' Eso significa que es un miembro. їEntonces, de ahн conoce a mi padre?. Hmmm]",
"No lo sй, no estaba allн.",
"Cierto, y no escuchй nada de eso cuando entrй.",
"Entonces, no sabes nada.",
"Excepto que sй que algo estб en marcha.",
"Harбs bien en tenerlo en cuenta.",
"Lo harй. Sin embargo, no soy un pirata, asн que no me afectarб realmente, їverdad?",
"Tal vez. Pero los piratas afectan a toda la zona y lo que sucede, de una manera u otra. Asн que puede que te atraiga de todas formas.",
"ЎHmmm! Puedo ver cуmo esto podrнa ser una molestia.",
"Bueno, ya basta de esta pesadilla. їVamos a navegar a #sOxbay#? Dos naves juntas tendrбn menos posibilidades de ser atacadas.",
"Sн, eso parece una buena idea. Te verй en el puerto.",
"ЎOh! Antes de que me olvide. Aquн hay un pequeсo recuerdo de nuestro viaje. Podrнa ser ъtil.",
"Tomo nota. Gracias.",
"Bueno, te dejo ahora, Capitбn ",
", Necesito ir a la sastrerнa.", 
"Adiуs, capitбn. Gracias por tu ayuda.",
"Bien. El mejor rumbo en esta йpoca del aсo es, al salir del puerto, navegar de Este a Sureste hasta llegar a #sisland_Redmond#. Pasa la isla por nuestro lado de babor, y luego mantйn ese rumbo hacia #sOxbay#.",
"Hola de nuevo Capitбn. їQuй te trae a esta bella isla?",
"Hola Thomas. Estoy en una misiуn. Parece que uno de los oficiales del EITC ha sido capturado por los espaсoles, y me han enviado para intentar que regrese.",
"ЎAh! Me enterй de eso. Acerca de algunas circunstancias inusuales que rodean ese asunto.",
"їCircunstancias inusuales? їQuй quieres decir con eso?",
"No quiero hablar de eso aquн. Demasiados ojos y oнdos. Lo que puedo decirte, es que tienes dos opciones.",
"їY son?",
"La manera fбcil, comprarlo al Gobernador, unos 20.000 en oro deberнa bastar, o la manera difнcil, rescatarlo tъ mismo.", 
"Creo que reunirй el dinero y lo comprarй a cambio.",
"Estoy listo para el desafнo. їCуmo hago para rescatarlo?",
"Muy bien capitбn, no necesitarбs mi ayuda en ese caso. Me despido de ti. Escuchй que el sastre acaba de recibir algo de seda fina.",
"Tenemos que unir fuerzas. Se escapу de la cбrcel hace dos noches, pero sй dуnde se esconde. Asegъrate de estar preparado para una pelea, y luego nos encontramos fuera de la herrerнa.",
"El rojo te queda bien, Capitбn. Esperemos que no termine siendo tu sangre. Supongo que estбs listo",
"Sн, estoy listo. їDуnde nos vamos a encontrar con йl?",
"Siempre haces preguntas en los lugares mбs inoportunos. Aquн no. Tenemos que ir a la selva, atravesar esa puerta y seguir recto, pero prepбrate para una pelea.",
"Pelear es mi segundo nombre. Vбmonos.",
"Un momento. No serб tan fбcil, no podemos llevarlo por la ciudad, los guardias lo estбn buscando. Mira, volveremos, coge tu barco y podrбs recogerlo en la playa.",
"Bien pensado, Thomas. Espera aquн, teniente, sуlo tardarй unas horas. Volvamos al barco entonces.",
"Espera Jack. Te voy a dejar aquн, tengo cosas que hacer. Es Oyster Beach lo que quieres, lo sabes, їno?",
"Muy bien, Thomas, lo entiendo. Gracias de nuevo por tu ayuda. Hasta luego.",
"Gracias, Thomas."

};
