string DLG_TEXT[65] = {
"Normalmente, deberнa preguntar quiйn eres, capitбn ",
", pero, como ves, ya estoy al tanto de eso.",
"Muy impresionante, seсora. Os saludo. Y no preguntarй cуmo lo sabйis, tengo la sensaciуn de que es una de las preguntas que un sabio no harнa. [PIENSA: Especialmente cuando recuerdo haberte visto con mi padre, y sospecho que tъ tambiйn recuerdas haberme visto.]",
"Ahora soy yo la que estб impresionada, capitбn ",
". Veo que entiendes que la sabidurнa es el principio de todo conocimiento.",
"Gracias, seсora. Me gustarнa saber vuestro nombre. [PIENSA: Serб mejor que no le diga que ya lo sй.] ",
"Mi nombre es Tia Dalma y ahora ya nos hemos presentado. Entonces, їquй te trae por aquн, apuesto capitбn?",
"Si conocйis mi nombre, Tia Dalma, entonces estoy seguro de que sabйis por quй estoy aquн.",
"Oh, si, capitбn. Sй por quй estбs aquн, y tambiйn sй que tъ no lo sabes.",
"їQuй? ЎClaro que lo sй! Estoy aquн para recoger un cargamento.",
"їAh, sн, capitбn?... їY de quй es ese cargamento?",
"ЎAH! Ahн me habйis pillado. Admito que no sй quй cosas son las que componen el cargamento, la verdad. Sуlo se me ordenу recogerlo.",
"Pobre capitбn, el cargamento no se compone de 'cosas', sino de personas. Has venido a recoger esclavos.",
"ЎESCLAVOS! ЎNO! No soy un comerciante de esclavos. ЎNunca!",
"Lo sй, capitбn, por eso te lo digo.",
"Zarparй de inmediato. No quiero tener nada que ver con el comercio de esclavos.",
"No, capitбn. Debes liberar a los esclavos.",
"їCуmo hago eso?",
"Matando a los tres guardias que estбn doblando la esquina mбs allб de la playa. Estбn bloqueando el camino a la cбrcel donde estбn los esclavos... Y, por cierto, tu tripulaciуn no puede ayudarte.",
"їPor quй tengo la sensaciуn de que podrнais hacerlo por vuestra cuenta, y que no necesitбis mi ayuda?",
"Otro destello de sabidurнa, capitбn. Estбs en lo cierto, no necesito tu ayuda, pero sн necesito que demuestres tus palabras con hechos.",
"їPor quй?",
"Hazlo, capitбn. Despuйs, vuelve a verme aquн y te darй la respuesta.",
"Estoy metiйndome hasta el cuello en algo que llega muy hondo, lo sй, pero no me gusta la idea de la esclavitud, asн que volverй en breve.",
"Has tenido йxito, capitбn.",
"Sн, he logrado...",
"Era una afirmaciуn, no una pregunta, capitбn ",
", has confirmado tu carбcter y te has probado a ti mismo, asн que ahora tengo algo especial que debes comprarme, y tambiйn te darй nuevas ropas mбs apropiadas para tu nueva situaciуn.",
"їMato a tres hombres y quieres venderme algo?",
"No, capitбn, no es una venta ordinaria. Dame 500 piezas de oro para que pueda sobornar al carcelero y conseguir pasaje para que los esclavos puedan irse de aquн a un lugar seguro, y tendrбs esta brъjula y estas prendas nuevas.",
"ЎUna brъjula! Ya tengo una brъjula.",
"No es una brъjula como esa. Esta brъjula te llevarб a lo que tu corazуn mбs desea. Sнguela con atenciуn.",
"їQuieres decir como el cofre de Cortйs?",
"Si eso es lo que mбs deseas, sн.",
"Hmmm. Eso suena como si supieras algo mбs al respecto. ",
"Sй, capitбn, que no puedes volver a presentarte ante quien te enviу aquн.",
"ЎAh! Sн. Eso serб un problema. Bueno, tengo otro lugar adonde ir.",
"Sн, capitбn, de vuelta al faro de #sisland_Oxbay#.",
"їTambiйn sabes de eso? Muy bien, haremos un intercambio, aquн estб mi oro.",
"Y aquн tienes la brъjula y las prendas nuevas. Tu futuro serб muy complejo, capitбn, pero deberнas irte ya. Vendrбn mбs guardias.",
"Sн, deberнa, pero їquй hay de ti? [PIENSA: ЎGUAU! їCуmo ha hecho eso?]",
"No te preocupes por mн, capitбn. Desaparecerй antes de que lleguen. Hasta que nos volvamos a ver.",
"Querrбs decir 'si' nos volvemos a ver... No. Pensбndolo mejor, tъ ya sabes que nos volveremos a ver, їno es asн?",
"No es una brъjula como esta. Deberнas llevбrsela a tu patrуn tan pronto como puedas.",
"No puedo volver a presentarme ante Beckett, no despuйs de esto.",
"Sн, pero Beckett ya no es tu patrуn, їverdad? Estбs trabajando para la Hermandad.",
"їTambiйn lo sabes? Toma el dinero y dame la brъjula. Me asustas, їsabes?.",
"Has fracasado de la forma mбs miserable, capitбn. Me temo que tendrбs que volver con las manos vacнas.",
"No puedo hacer eso, esta es mi primera misiуn. Perderй mi empleo, lo perderй todo.",
"Entiendo tu dilema, capitбn, y podrнa ayudarte, pero el precio serб terrible.",
"No me importa, cueste lo que cueste, lo aceptarй.",
"Eso suena muy ominoso. Tal vez vuelva y afronte las consecuencias despuйs de todo. Adiуs.",
"Muy bien, Capitбn, aquн tienes la brъjula y las prendas que necesitas.",
"No como esta. Y tъ has aceptado mis condiciones, asн que el trato estб hecho. Necesitarй todo tu dinero, capitбn.",
"Bueno, es un precio alto, pero no es lo que yo llamarнa terrible.",
"El oro es sуlo una parte de la transacciуn. Ya te darбs cuenta del resto mбs adelante. Adiуs, capitбn.",
"ЎAh! Eso suena un poco mбs terrible. Me irй mientras pueda. Adiуs.",
"Deja en paz a este hombre, Davy Jones, y llйvame en su lugar. ЎTe lo ruego!",
"...",
"їQuй quieres, capitбn?",
"Nada por el momento.", 
"Davy Jones ... Deja a este hombre en paz, Ўno le ha llegado la hora de seguirte al fondo del mar!",
"...",
"Davy Jones volverб pronto a seguirte la pista, me imagino. Si me llevas a mi cabaсa en Pelogostos, intentarй ayudarte.",
"Gracias. Vamos a Pelogostos, entonces.",

};
