string DLG_TEXT[43] = {
"No nos precipitemos, Comodoro, el hombre salvó a mi hija después de todo.",
"Sí, señor, una observación importante. Salvar vidas es un acto noble.",
"Sí, sí, no deberíamos precipitarnos. Métalo en prisión mientras llevo a mi hija a la residencia para que se recupere y se cambie de ropa. Siempre podemos colgarlo mañana.",
"¡No es exactamente lo que tenía en mente! ... ¡Creo que es hora de que esté en otro lugar! Sólo recuerda esto como el día en que casi atrapas al Capitán ",
"¡Ah! Así que este es el famoso Capitán ",
". Lo creas o no, estábamos hablando de ti.",
"¿De verdad, su excelencia? Dada la actual compañía, dudo que haya sido una buena conversación.",
"No es así, Capitán. A pesar de sus defectos, tiene las habilidades que necesitamos desesperadamente en este momento.",
"¿Cómo es eso, señor?",
"La situación en Europa ha empeorado mucho. Los franceses han reunido una gran flota, y los informes indican que planean apoderarse de las islas.",
"De hecho, señor, eso es inquietante, pero ¿por qué me involucraría eso a mí?",
"Tienen la intención de aliarse con los piratas para aumentar la presión sobre nosotros, y con su historia pasada ... er, si está dispuesto, podría ayudarnos a frustrar estos esfuerzos.",
"En cuanto a mi historia, siento que he sido muy incomprendido, y me gustaría tener la seguridad de que mi historial será borrado.",
"Por mi parte, su historial es claro, y permitiré que Sir Cutler Beckett hable por usted mismo.",
"Soy todo oídos, Señor.",
"Cállese, capitán Norrington. Deje que el hombre termine lo que tiene que decir. Continúe, ",
"Gracias, Señor. Como dijo el Capitán Norrington, no se puede confiar en los piratas, PERO, se puede hacer en que confíen unos en otros, y como pirata, puedo ordenar esa confianza.",
"En efecto, Capitán ",
". ¿Y por favor, cómo nos beneficiaría eso a nosotros?",
"Los franceses no son estúpidos. También creen que no se puede confiar en los piratas. Han comprado una alianza temporal que les permite reabastecer sus barcos, eso es todo. Y por una gran suma de dinero, estaré obligado. Pero conociendo a los franceses, ese dinero no será pagado hasta que los suministros hayan sido cargados.",
"Eso es lógico. Pero, ¿y qué? Todavía no ayuda a nuestra causa, y a la defensa de estas islas.",
"Bien, Señor, todo lo que tenemos que hacer es mostrar a los piratas que no se les pagará, y se volverán contra los franceses, y sabemos que los franceses se volverán contra los piratas una vez tengan lo que necesitan.",
"Vamos Capitán, esto empieza a mostrar algún interés.",
"Si le digo a los piratas lo que los franceses están haciendo, entonces los piratas atacarán a la flota francesa por nosotros, dejando al escuadrón de Norrington libre para someter a las otras islas francesas.",
"[A voluntad] A nuestro regreso a Port Royal, te concedí clemencia. ¿Y así es como me lo agradeces? ¿Arrojando tu suerte con él? ¡Es un pirata!",
"[Voluntad] Y un buen hombre. Si todo lo que he logrado aquí es que el verdugo ganará dos pares de botas en lugar de una, que así sea. Al menos mi conciencia estará limpia.",
"Elizabeth... Elizabeth... ¡Espera!",
"Has perdido a tu compañero. Cupido ha hecho su trabajo.",
"¿Y cómo ejecutarías esta artimaña para estar seguro de tu éxito?",
"Mi plan sería este señor. Navegaré hacia #sisland_Turks# y difundir la noticia de que me reuní con la flota francesa y que me dieron el dinero para pagar a los ingleses, para que puedan reabastecer sus barcos en los puertos ingleses.",
"¡QUÉ! Pero, ¿qué lograría con eso?",
"Al entregar el dinero, como prueba fehaciente, podría hacerles creer que los franceses vienen de hecho a apoderarse de sus islas, no los ingleses, Y si el Capitán Norrington pudiera acompañarme como mi primer oficial, eso añadiría aún más credibilidad a la misión.",
"¡Silencio Norrington! Este plan realmente tiene sentido. ¿Cuánto dinero necesitaríamos para esta empresa, capitán?",
"Sugeriría 300.000 en oro, mi Señor. Ahorrará más que eso al no tener que poner los barcos de Norrington en el mar, además de mantener su flota intacta para asuntos más urgentes.",
"Un plan audaz ",
". Muy bien, haré que le entreguen los 300.000 a su nave. ¿Cuándo puede zarpar?",
"¡Ah! Hay otro pequeño asunto.",
"¿Y qué es?",
"No tengo por el momento un barco que sea adecuado para el viaje, ni que transmita mi categoría como representante de los ingleses.",
"¡Hmmm! Muy bien. Capitán Norrington, proporcione al buen capitán una fragata y creo debería navegar con él como su primer oficial. Sólo para proteger nuestra inversión, ¿entiende?. Y Sir Cutler, tal vez usted sería lo suficientemente amable para proporcionar la escolta en el Interceptor hasta que estén libres de nuestras aguas y tengan que izar la bandera pirata.",
"Err... Gracias Señor, nos iremos tan pronto como sea posible.",
"41",
"42",

};