string DLG_TEXT[43] = {
"Spadaj!",
"...",
"Witaj, #slad#! Wyglądasz mi na starego wilka morskiego. Może zechcesz dołączyć do mojej załogi?",
"A na jakich warunkach?",
"Niezłe przedstawienie! Jesteś lepszy, niż przypuszczałem. Może jednak przydasz mi się do czegoś.",
"Czy teraz wierzysz, że jestem kapitanem?",
"Podziwiasz morze, co? Sam czasem nie mogę się oprzeć tym widokom. Serce mi się kraje, kiedy pomyślę, że więcej ich nie ujrzysz.",
"Cóż to, starcze - wygląda na to, że zerwałeś naszą umowę.",
"Brawo. Nie jesteś taki głupi, na jakiego wyglądasz. Oddaj pistolet i szpadę, a odeskortujemy cię bezpiecznie do #sisland_Oxbay#",
"Naprawdę? A co na to twoja załoga? ",
"To akurat najmniej mnie obchodzi.",
"Może i cię nie obchodzi. Nie mogę się jednak pozbyć wrażenia, że praca dla takiego kłamliwego psa nie jest dla twoich ludzi szczytem marzeń. Może dlatego tak ciężko było skompletować ci załogę.",
"Mów tak dalej, a długo nie pociągniesz.",
"Być może. A może lepiej pogadam z twoimi ludźmi. Co wy na to, panowie? Dobrze wam z Kapitanem Mam-Was-Gdzieś, a może wolelibyście zakosztować prawdziwej przygody?",
"Jak na kogoś w twojej sytuacji to mocne słowa. Chyba nie wierzysz, że ktoś da się na nie nabrać.",
"Spójrz za siebie, kapitanie, i zapytaj mnie raz jeszcze.",
"Nie muszę spoglądać za siebie. Bardzo ostrożnie dobieram sobie załogę. Większość z nich nawet nie zna naszego języka.",
"Cóż, warto było spróbować. Hej, czy to w oddali, między wodą a niebem, to ląd? Na razie, kapitanie!",
"Że co? Nie słuchać #spronoun#, głupcy! Ja tu dowodzę!",
"Chyba mają inne zdanie na ten temat. Jeśli ich nie powstrzymam, pewnie cię zabiją.",
"Potrzebuję kilku żeglarzy, na których mógłbym polegać. Płacę 10 sztuk złota teraz i kolejne dwieście po robocie. Co ty na to?",
"Za tę stawkę... czy ja wiem. Zrób mnie kapitanem, to wtedy się zastanowię.",
"Gadaj, gdzie twój statek, jeśli ci życie miłe, i przekonaj załogę, że teraz ja tu rządzę.",
"Mam dla ciebie lepszą propozycję. Pomóż mi dostać się do Oxbay, a nieźle zapłacę, jak tylko przybędziemy na miejsce.",
"Z tym nie powinno być problemu. Jestem w dosyć dobrych stosunkach z Anglikami.",
"Umowa stoi! Wypływamy?",
"Butny z ciebie człowieczek, kapitanie. Pamiętaj jednak, że tylko ja dowodzę na moim statku.",
"Wybacz, jeśli nie wyraziłem się jasno. To nie była prośba! Jeżeli się nie poddasz, będę musiał użyć siły.",
"Nawet gdyby pojawił się ktoś, kto lepiej się do tego nadaje? ",
"Lepiej ode mnie? Słuchaj no, chłoptasiu, może w Anglii, w wannie u mamusi, dowodziłeś i całą flotą, ale ja mówię o prawdziwym morzu i prawdziwym statku!",
"I szukasz prawdziwego kapitana. Sprawdź mnie!",
"W porządku. Ale to będzie twój pogrzeb. Widzisz tamtego osiłka przy stole? Pokonaj go, a pogadamy. Hej, ",
"Gervasio Serrao",
", ten człowiek właśnie nazwał cię robalem!",
"Świetnie, rozgniotę go też jak robala!",
"Jestem pod wrażeniem. Ale umiejętność fechtunku nie czyni z ciebie jeszcze kapitana.",
"Nie? W takim razie poddaj mnie innej próbie. No, dalej.",
"Czyli... cały wysiłek na marne? Chyba więc cię zabiję i po prostu zabiorę sobie ten twój statek.",
"Słuchaj, chłopcze, setnie mnie ubawiłeś, ale to już zaczyna się robić nudne. Jeśli nie chcesz zostać jednym z moich marynarzy, to przestań mi zawracać głowę.",
"Jak chcesz. Poszukam szczęścia gdzie indziej.",
"Zobaczymy, czy będziesz znudzony, jak się już z tobą rozprawię!",
"Szukasz kłopotów? W porządku, da się załatwić!",
"Zobaczmy, na co cię stać, starcze!",

};