string DLG_TEXT[98] = {
"Wynoœ siê! Nie mam zamiaru rozmawiaæ z takimi jak ty!",
"...",
"Czego chcesz ode mnie? Nie widzisz, ¿e jestem zajêty?",
"Muszê z tob¹ pomówiæ, ",
".",
"Domyœlam siê, ¿e imiê ",
"Ferro Cerezo",
" jest ci obce, prawda? W takim razie pora to zmieniæ.",
"Mówisz, ¿e nazywasz siê ",
"? Jesteœ cz³owiekiem, którego szukam!",
"Oczywiœcie. Zawsze jestem rozchwytywany.",
"Nie b¹dŸ œmieszny. Jestem tu, by odebraæ dokumenty, które ukrad³eœ z koœcio³a na Isla Muelle.",
"Tak. Wiedzia³em, ¿e ",
"Padre Domingues",
" bêdzie niepocieszony, gdy odkryje, ¿e dowody na jego lichwê wpad³y w moje rêce.",
"Jeœli przeczyta³eœ te dokumenty, to nasza rozmowa mo¿e przybraæ mniej przyjacielsk¹ formê.",
"Jeœli te dokumenty mówi¹ to, co twierdzisz, mo¿e powinieneœ pokazaæ je stra¿om?",
"Niech bêdzie po twojemu. Kupiê od ciebie te papiery.",
"Co masz na myœli?",
"Pewnie o mnie s³ysza³eœ. Jestem ",
"Dobry Bo¿e! Oczywiœcie, ¿e s³ysza³em o najokrutniejszym piracie grasuj¹cym po tych wodach!",
"Zamknij siê i dawaj papiery. Na pewno zrobiê z nimi coœ po¿yteczniejszego.",
"Ale... Ja mia³em zamiar...",
"Mówi³eœ coœ?!",
"Nie, nie! To nic! Proszê, weŸ je!",
"¯egnaj.",
"Nie w¹tpiê. Cieszê siê, ¿e ciê spotka³em. Mój statek nie nadaje siê do dalekich podró¿y. \nJeœli obiecasz mi, ¿e dostarczysz te dokumenty do Europy, chêtnie ci je oddam.",
"Zgoda. Takie uczynki nale¿y karaæ.",
"To jest do zrobienia. Za jedyne 10000 sztuk z³ota.",
"Co powiesz na 5000?",
"Umowa stoi.",
"Nie ma mowy. Nie marnuj mojego czasu. Idê st¹d.",
"Bêdziesz tego ¿a³owaæ!",
"Lubisz siê targowaæ? Ja te¿. Wezmê 9000.",
"6000",
"Doskonale. Oto twoje pieni¹dze.",
"Nie ma mowy. Nie marnuj mojego czasu. Idê st¹d.",
"Jak sobie chcesz.",
"Chcesz mnie obrabowaæ! 8000 i to moje ostatnie s³owo.",
"To za du¿o jak na moj¹ kieszeñ.",
"Zgoda. Oto twoje z³oto.",
"Nie ma mowy. Nie marnuj mojego czasu. Idê st¹d.",
"Mo¿e byæ.",
"Wiêc wynoœ siê i nie zawracaj mi g³owy! Muszê trochê odpocz¹æ przed nastêpnym rejsem.",
"Mo¿e jeszcze siê zobaczymy.",
"Mam nadziejê, ¿e coœ na tym skorzystasz.",
"To moja sprawa.",
"Znasz moje imiê? Dobrze, powiedz, czego chcesz.",
"Potrzebujê dokumentów, które ukrad³eœ z koœcio³a na Isla Muelle.",
"A wiêc ten stary lis, ",
"Padre Domingues",
" ciê tu przys³a³!",
"Niewa¿ne, z czyjego polecenia tu przybywam. Chcê dostaæ te dokumenty.",
"Za³ó¿my, ¿e wiem, o czym mówisz. Powiedz mi zatem, dlaczego mia³bym ci je oddawaæ? Czy wiesz chocia¿, co jest w tych papierach?",
"Nie. Wiem tylko, ¿e muszê je odzyskaæ.",
"A wiêc ten stary hipokryta nie powiedzia³ nawet swemu ch³opcu na posy³ki, jak niewygodne s¹ dla niego te papiery? Bêdzie niepocieszony, gdy dowie siê, ¿e dowody jego lichwy wpad³y w moje rêce.",
"Jeœli znasz treœæ tych dokumentów, to przypuszczam, ¿e ton naszej dyskusji musi ulec zmianie.",
"Niech bêdzie po twojemu. Kupiê od ciebie te papiery.",
"Co masz na myœli?",
"Pewnie o mnie s³ysza³eœ. Jestem ",
".",
"O mój Bo¿e! Jak¿e móg³bym nie s³yszeæ o najokrutniejszym kundlu grasuj¹cym po tych wodach!",
"Wybaczam ci tê zniewagê, ale jeœli jeszcze raz nazwiesz mnie kundlem, wyrwê ci jêzyk.",
"B³agam o wybaczenie! Nie to chcia³em powiedzieæ!",
"Zamknij siê i dawaj papiery. Wiem, co z nimi zrobiæ.",
"Ale... Ja mia³em zamiar...",
"Coœ mówi³eœ?!",
"Nie, nie! To nic! Proszê, weŸ je!",
"¯egnaj.",
"To jest do zrobienia. Za jedyne 10000 sztuk z³ota.",
"Co powiesz na 5000?",
"Umowa stoi.",
"To rozbój w bia³y dzieñ!",
"Nie jestem zainteresowany. IdŸ ju¿.",
"Skoro wiesz, ile s¹ warte te dokumenty, nasza rozmowa musi przybraæ inny obrót.",
"Bêdziesz tego ¿a³owaæ!",
"W¹tpiê. S³uchaj - jeœli nie chcesz p³aciæ, to sp³ywaj.",
"Dobrze. Ale pewnego dnia bêdziesz ¿a³owaæ, ¿e nie wykaza³eœ odrobiny dobrej woli.",
"Podoba mi siê twój styl, ch³opie! Co powiesz na 9000?",
"Myœlê, ¿e 6000 brzmi lepiej.",
"Dobra. Oto twoje pieni¹dze.",
"Nie, to nie zadzia³a. A teraz wynoœ siê i daj mi zaj¹æ siê interesami. Nied³ugo wyruszam w rejs.",
"Jak chcesz, ale bêdziesz tego ¿a³owaæ. I to nied³ugo.",
"Chcesz mnie obrabowaæ! 8000 i to moje ostatnie s³owo.",
"To za du¿o jak na moj¹ kieszeñ.",
"Doskonale. Oto twoje pieni¹dze.",
"Nie, to nie zadzia³a. A teraz wynoœ siê i daj mi zaj¹æ siê interesami. Nied³ugo wyruszam w rejs.",
"Nie ma sprawy. Jeszcze siê spotkamy, a wtedy ja bêdê mia³ przewagê.",
"Wiêc wynoœ siê i nie zawracaj mi g³owy! Muszê trochê odpocz¹æ przed nastêpnym rejsem.",
"Wiesz... Kiedy siê rozczarujê, bywam z³y.",
"Grozisz mi?",
"Informujê. Jeœli nie chcesz, aby ten dzieñ by³ twoim ostatnim, lepiej oddaj papiery po dobroci.",
"Zaraz, zaraz, poznajê ciê! Ty jesteœ tym kapitanem, który pracuje dla angielskiego gubernatora!",
"Zgadza siê. Teraz widzisz, ¿e nie warto ze mn¹ zadzieraæ?",
"Chyba jednak zaryzykujê. ZejdŸ mi z oczu!",
"Ostrzega³em ciê.",
"Dobrze, ju¿ dobrze! Bierz te papiery, choæ nie wiem, na co siê przydadz¹ twojemu szefowi. Bierz je i idŸ.",
"To rozumiem!",

};