string DLG_TEXT[32] = {
"Jeњli pozwolisz, ",
".",
"Oczywiњcie.",
"Jeњli pozwolisz, jestem teraz zajкty. Proszк, daj mi zjeњж, a potem bкdziesz mуgі zadawaж swoje pytania.",
"...",
"Czego chcecie, smarkacze?",
"Czy to pan jest ",
"?",
"O czym bкdziemy wiкc rozmawiaж? Kto to jest?!",
"Kto?! Gdzie?!",
"Ehm... ehm... ten kundel w koсcu mnie dopadі.",
"Gubernator Silehard?",
"I jego banda іotrуw.",
"Proszк, leї spokojnie i oszczкdzaj oddech. Te rany s№ zbyt powaїne... nie wydaje mi siк, byњ zdoіaі dotrzeж na mуj statek.",
"Wiem, dziewczyno, wiem. Ehm, ehm... Czy wiesz, dlaczego ",
"Robert Christopher Silehard",
" pragn№і mojej њmierci?",
"Tak, chodzi o skarb Inkуw.",
"W rzeczy samej. Silehard poї№daі go od chwili, gdy pierwszy raz o nim usіyszaі. Bіagam ciк - sprz№tnij mu go sprzed nosa. Niech to bкdzie zemsta za moj№ њmierж... ehm ehm.",
"Tak, i zajmк siк teї samym gubernatorem. Moїesz byж tego pewny. Nasyіa na mnie mordercуw od chwili, gdy dowiedziaіam siк o skarbie.",
"Nie. Nie zabijaj go, moja maіa. Jest zbyt potкїny, za dobrze strzeїony. A znacznie waїniejszy jest skarb.",
"Dlaczego?",
"Jest tu wiкcej tajemnic, niї siк zdaje. Informacje, ktуre posiada ",
"Robert Christopher Silehard",
", nie s№ peіne. Dopiero niedawno zdoіaіem to ustaliж, lecz jest duїo, duїo wiкcej.\nNa pocz№tku mojej pogoni za skarbem znalazіem legendк, ktуra opisuje, jak go odszukaж.\nNiestety byі to tylko niepeіny odpis z biblioteki koњcielnej na Puerto Rico.\nJestem pewny, їe znajdziesz tam kompletn№ wersjк. I jeszcze jedno. \nZdob№dџ pos№їek Khirucatceliti, a on otworzy drzwi...",
"Їegnaj. Spoczywaj w pokoju...",
"Tak? Kim jesteњcie i czego ode mnie chcecie?",
"Spokojnie, chcemy tylko porozmawiaж.",
"Widzк po waszych twarzach, їe ta rozmowa nie bкdzie zbyt przyjemna, ale chyba nie mam wyboru.\nChodџmy do mego domku pod miastem, tam porozmawiamy.",
"Niech pan nawet nie myњli o ucieczce!",
"Nie myњlк.",
"W porz№dku, wiкc chodџmy.",

};