string DLG_TEXT[125] = {
"Och, przyjacielu, jestem niestety zbyt zajкty, by rozmawiaж w tej chwili. Wіaњnie wpadіem na nowy pomysі i jestem odrobinkк zamyњlony.",
"W porz№dku. Tylko uwaїaj, nie wysadџ nas wszystkich w powietrze.",
"Pomocy! Ratunku!",
"Trzymaj siк! Nadchodzк!",
"Pomocy! Ratunku!",
"Dziкkujк, nie bкdк ryzykowaж dla ciebie їycia.",
"Och! Dziкkujк, ogromnie dziкkujк, ",
", gdyby nie ty, te prostaki rozerwaіyby mnie na strzкpy.",
"Proszк bardzo.",
"Wybacz, przyjacielu, ale przeprowadzam doњwiadczenie, ktуre wymaga mej uwagi, wiкc muszк ciк teraz opuњciж.\nNie miej mi tego za zіe. W moim domu przebywa para bardzo miіych ludzi. Przypuszczam, їe to spotkanie ciк ucieszy.",
"Dobrze, chкtnie spotkam siк z twoimi goњжmi.",
"Miіo ciк widzieж, gdzie jest ",
"Danielle",
"?",
"Hmm... Myњlaіem, їe jest juї tutaj.",
"O nie! Co ci siк staіo, ",
"? Nie jesteњ sob№... spуjrz na swoje ubranie, a te blizny, jesteњ caіy mokry!",
"Daj mi zіapaж oddech! I trochк wina - umieram z pragnienia.",
"Oto on.",
"To ma byж to? Jeњli to jest jacht, to ja jestem cesarz chiсski! To po prostu іуdџ rybacka!",
"Tylko tyle mogк ci zaproponowaж, ",
", nie gniewaj siк na mnie.",
"Przepraszam. Chyba nie mam wyboru. Wyruszк na poszukiwania ",
"Danielle",
" w tej balii.",
"Oto twoje wino. Teraz opowiedz mi, co siк staіo?",
"To dіuga historia. Czy ",
"Danielle",
" jest tutaj? Nie widzк jej statku.",
"Nie, jeszcze nie przybyіa.",
"Do diabіa! Ta dziewczyna nie moїe usiedzieж na miejscu dіuїej niї przez chwilк. A ja przy moim szczкњciu straciіem statek!",
"Hmm... Mam niewielki jacht. Moїe ci siк przyda?",
"Jacht? Ty stary lisie, dlaczego nie powiedziaіeњ wczeњniej?",
"Cуї, to bardzo maіy jacht...",
"Pokaї mi go.",
"Nie, jeszcze nie przybyіa.",
"Do diabіa! Ta dziewczyna nie moїe usiedzieж na miejscu dіuїej niї przez chwilк. Muszк j№ odszukaж.",
"O czym ty mуwisz? Zawdziкczam ci їycie! Czy mogк poznaж twe nazwisko?",
"Nazywam siк ",
", jestem kapitanem.",
"Jakїe ciekawe! Dokonaіem kilku wynalazkуw, ktуre moїna by zamontowaж na twoim statku.\nOch, dlaczego wci№ї tu stoimy? Jestem ci tak wdziкczny za ratunek... Nalegam, byњ udaі siк do mego domu, chcк siк odwdziкczyж. Chodџ, chodџ.",
"Dobrze, chodџmy do twego domu. Tylko nie rуb niczego z moim statkiem.",
"Musimy dostaж siк z powrotem na statek. Obawiam siк, їe zniszczenie њwi№tyni moїe wywoіaж trzкsienie ziemi albo coњ jeszcze gorszego! Inkowie byli specjalistami od wyszukanych puіapek.",
"Puіapek powoduj№cych trzкsienie ziemi? Jak dla mnie to trochк zbyt wymyњlne.",
"Tak, tak! No dobrze, zaіуїmy, їe nie bкdzie trzкsienia ziemi - ale napisy na њcianach њwi№tyni mуwiіy o straszliwej karze, ktуra zetrze z powierzchni ziemi sprawcуw tego њwiкtokradztwa.",
"W porz№dku, zatem ruszajmy.",
"Њpiesz siк, kapitanie! Їadne skarb na Ziemi nie jest wart utraty їycia!",
"Spokojnie, juї stawiamy їagle.",
"Tak, to chyba nie taki zіy pomysі...",
"Mogіa przynamniej poczekaж na odpowiedџ.",
"Idџmy za jej przykіadem, ",
". Ja pуjdк w prawo, a ty, kapitanie, idџ prosto. Jeњli ci to odpowiada.",
"A co to za rуїnica!? Postaraj siк tylko nie zgubiж.",
"Nie s№dzк. Inskrypcje mуwiіy, їe puіapka znajduje siк przy wejњciu do wnкki boga sіoсca. Zdaje siк, їe to tam, gdzie zaczyna siк labirynt.",
"Labirynt?",
"Tak, labirynt. Nie wspominaіem o nim? Aby dotrzeж do skarbu, musisz przebyж labirynt. Przypuszczam, їe tylko jedno z przejњж doprowadzi nas do skarbu.",
"S№dzк, їe ludzie, ktуrzy wybudowali tк њwi№tyniк mieli skіonnoњж do їartуw.",
"Uwaїajcie w њwi№tyni, przyjaciele. Na tabliczkach jest napisane, їe u wejњcia do wnкki boga sіoсca znajduje siк puіapka.\nNiestety, nie opisano tam sposobu unieszkodliwienia puіapki, powiedziano jednak, їe wskazуwki znajduj№ siк w њwi№tyni.",
"Dziкki za przestrogк. Czy ukoсczyіeњ juї tіumaczenie?",
"Tak, lecz papier zawilgotniaі i pomarszczyі siк. Nie wszystko udaіo mi siк odczytaж. Byіo tam coњ o wnкce i o bogu, ktуry obecnie њpi. Nie s№dzк, by warto byіo poњwiкcaж temu wiкksz№ uwagк. To pewnie tylko indiaсska bajka.",
"Do diabіa! Gdzie te skarby?",
"Przypuszczam, їe wejњcie do skarbca, a mуwi№c dokіadniej, do grobowca znajduje siк we wnкce.",
"No to naprzуd.",
"Zaczekaj. Problem w tym, їe do њwi№tyni moїna wejњж tylko wtedy, gdy jest oњwietlona sіoсcem! To jakiњ skomplikowany mechanizm, nie wiem dokіadnie...",
"Naprawdк? W takim razie zaczekamy na sіoсce. Mam tylko nadziejк, їe pora deszczowa nie zaczyna siк dzisiaj.",
"Jeњli mnie pamiкж nie zawodzi, idziemy do њwi№tyni.",
"Ach, tak, rzeczywiњcie.",
"Och, kapitan ",
"! Co tu robisz? Ciebie rуwnieї wtr№cili do wiкzienia?",
"Nie, przyjacielu, przybywam ci na ratunek.",
"Na ratunek? Jak? Nie przypuszczam, by udaіo ci siк namуwiж naczelnika do wypuszczenia mnie bez rozkazu gubernatora!",
"Tak wіaњciwie juї go na to namуwiіem, ",
".",
"Naprawdк? Jest pan zadziwiaj№cym czіowiekiem, kapitanie, czemu jednak tak nagle zaczyna mi pan pomagaж?",
"Szczerze mуwi№c, potrzebujк od ciebie pewnej przysіugi.",
"Hmm... Jestem do usіug, kapitanie, ale czy moglibyњmy kontynuowaж tк rozmowк w jakimњ innym miejscu?",
"Oczywiњcie. Chodџmy do latarni, a po drodze wszystko ci opowiem.",
"...Ryzykanctwo i lekkomyњlnoњж! Nie mogк uwierzyж, їe ludzie s№ do tego zdolni...",
"Kaїdy z nich ma wіasn№ koncepcjк zabawy.",
"Chcecie wiкc, abym przetіumaczyі indiaсski tekst z tego papieru? Szczegуlnie interesuje was ta czeњж, ktуra mуwi o tym, jak dostaж siк do њwi№tyni, mam racjк?",
"Tak. Mуwiіeњ, їe znasz jкzyk tubylcуw.",
"Tak, tak... Spкdziіem wiele czasu na badaniu miejscowej ludnoњci... i, ",
", jeњli wyruszacie na wyprawк w poszukiwaniu tej њwi№tyni, jadк z wami!",
"...Z jakiego powodu?",
"Wiem, po co siк tam wybieracie... zapewniam jednak, їe nie potrzebujк tego. Chcк tylko byж na miejscu, by wszystko zobaczyж i moїe dokonaж jakiegoњ wspaniaіego odkrycia!",
"Hmm... Nie chciaіbym naraїaж ciк na trudy dіugiej morskiej podrуїy...",
"To bzdura! Przysiкgam, ",
", їe jeњli nie zgodzicie siк zabraж mnie ze sob№, nie przetіumaczк ani sіowa z tego tekstu!",
"W takim razie zgoda. Weџmiemy ciк ze sob№.",
"Wyњmienicie! Jestem niezmiernie wdziкczny! Jeњli chodzi o tіumaczenie, to potrzebujк trochк czasu. Myњlк, їe zajmie mi to kilka dni. Ten dialekt jest doњж niezwykіy.",
"Naprawimy statek i przygotujemy siк do podrуїy.",
"Ach, to ty, kapitanie! Prawie ukoсczyіem tіumaczenie. Jeszcze tydzieс i bкdк gotуw.",
"Nie moїemy tyle czekaж. Moїe dokoсczysz pracк w trakcie podrуїy?",
"Tak, to znakomity pomysі, czemu nie? Czy boli mnie gіowa na morzu? Chyba nie... Dostajк choroby morskiej? Nie s№dzк... W takim razie zgoda. Ciekawi mnie tylko... sk№d ten poњpiech?",
"Przypuszczam, їe bitwa w porcie nie pozostaіa niezauwaїona, wiкc moїe powinienem wyjaњniж...",
"Bitwa? Jaka bitwa? W jakim porcie?",
"...Gubernator Silehard nie zamierza robiж nam prezentu z tej kolonii... podejrzewam raczej, їe planuje powiesiж nas przy pierwszej okazji.",
"Powiesiж? Ach, rozumiem. Bкdк kontynuowaж tіumaczenie w podrуїy. Musze powiedzieж, їe mamy szczкњcie, wyruszaj№c wіaњnie o tym czasie. Podobno do zatoki Cozumel da siк wpіyn№ж tylko dwa razy w roku.",
"Dlaczego statki nie mog№ przybijaж do wyspy o dowolnej porze?",
"Wedіug tekstu legendy jakieњ naturalne zjawisko oddziaіuje na pіywy.",
"Zapewne dlatego ",
"Raoul Rheims",
" nie mуgі dostaж siк do њwi№tyni.",
"Byж moїe. Legenda mуwi teї o innych niebezpieczeсstwach. Zagroїeniach, ktуre czyhaj№ na tych, co chc№ skraњж serce bogu sіoсca.",
"Proszк tіumaczyж dalej. Masz kilka nastкpnych dni na zbadanie caіoњci. Chodџmy na statek.",
"Tak na marginesie, kapitanie, bкdк potrzebowaж osobnej kajuty. Najlepiej gdzieњ w okolicach rufy, aby krzyki zaіogi nie rozpraszaіy mnie podczas pracy nad tіumaczeniem.",
"Hmm. W porz№dku. Dostaniesz tak№ kajutк.",
"Bez poњpiechu, przyjaciele. Wіaњnie stoimy na progu. Gdzieњ w pobliїu powinno znajdowaж siк tajne wejњcie do komory grobowej.",
"Myњlisz, їe powinniњmy zacz№ж opukiwaж њciany?",
"Absolutnie nie. To obrazy na њcianach powinny nam powiedzieж, jak mamy odnaleџж wejњcie do grobowca, i ostrzec nas przed ewentualnymi puіapkami.",
"Czy nie mamy juї za sob№ wszystkich niebezpieczeсstw?",
"W№tpiк w to. Inkascy budowniczowie zrobili, co w ich mocy, by zabezpieczyж њwi№tyniк. Jestem pewny, їe czeka nas jeszcze wiele niebezpieczeсstw.\nCуї, za niedіugo zobaczymy. A teraz dajcie mi chwilк pomyњleж.",
"Proszк bardzo.",
"O nie! Nie dotykaj!",
"O co chodzi?",
"To puіapka.... O nie! Juї dotkn№іeњ tego kamienia!",
"O nie! Powiedz, co siк staіo?",
"To ostatnia puіapka, pozostawiona przez twуrcуw њwi№tyni! Czemu nie zaczekaіeњ! Mogіem odczytaж inskrypcje, by dowiedzieж siк, jak tego unikn№ж, ale nie, musiaіeњ coњ pomacaж!",
"Jeњli to puіapka, to dlaczego jeszcze їyjemy?",
"Jeњli bкdziemy dіuїej zwlekaж, zginiemy na pewno! Puіapka otwiera kanaі, ktуry doprowadza wodк z gуrskiego jeziora do jaskiс pod њwi№tyni№. \nWulkan drzemi№cy pod њwi№tyni№ jest wci№ї czynny, wiкc moїesz sobie wyobraziж, co bкdzie, gdy duїa iloњж wody zaleje rozpalon№ lawк!",
"Hmm. Doprawdy...? Myњlisz, їe bкdzie tu trochк duszno?",
"Duszno? Para wysadzi њwi№tyniк w powietrze! Musimy uciekaж!",
"A co ze skarbem?",
"Zapomnij o skarbie! Musimy siк st№d wydostaж!",
"Czy nie ma їadnej drogi?...",
- Zabierz mnie z powrotem do domu, kapitanie. Proszк? Obawiam siк, їe w moim wieku jest o wiele wiкcej przygody niї potrzebujк.
„Masz racjк, wypіyсmy”.
„Proszк, kapitanie! Musimy wyjњж!”,
"W porz№dku!",
„Cуї, kapitanie, to z pewnoњci№ byіa przygoda!”,
„To prawda, Clement. Cieszк siк, їe wszyscy dotarliњmy bezpiecznie.”,
„Straszne, їe nie moїemy wrуciж do њwi№tyni, aby dowiedzieж siк wiкcej o tych zagubionych ludziach”.
„Przepraszam, їe nie mogliњmy zostaж, їeby znaleџж zіoto, jeњli takie byіo.”,
„Och, myњlк, їe tam jest zіoto, kapitanie, to tylko kwestia znalezienia sposobu na zdobycie tego… Hmmm…”,
- Klemensie, jeњli ktoњ moїe to zrobiж, moїesz. Jeszcze raz dziкkujк za twoj№ pomoc.
„...”,
"Јaskawy?",
„Czy mуgіbyњ mnie zabraж z powrotem do mojej latarni”,
„? Naprawdк muszк przestudiowaж wszystkie notatki, ktуre robiіem.”,
„Oczywiњcie, Clement.”,

};