string DLG_TEXT[306] = {
"Proszê siê przedstawiæ. My siê chyba nie znamy.",
"Nazywam siê ",
", jestem kapitanem statku '",
".",
"Kapitan ",
". Ufam, ¿e cieszy siê pan dobrym zdrowiem. Czemu zawdziêczam zaszczyt pañskiej wizyty?",
"Witam, ",
", witam. Jaki jest cel pañskiej wizyty?",
"S³ucham pana, kapitanie ",
". O co chodzi?",
"Mam pewn¹ sprawê do omówienia.",
"Mia³em nadziejê, ¿e ma pan jak¹œ pracê dla zdolnego kapitana.",
"Tak tylko wst¹pi³em, sir. Do widzenia.",
"Kapitanie ",
", widzê z pañskiej twarzy, ¿e chce mi pan coœ powiedzieæ.",
"Z przykroœci¹ donoszê, ¿e osada w #sOxbay# zosta³a zaatakowana.",
"Przywióz³ pan jeñca? Gdzie on jest? Chcê go zobaczyæ.",
"Przykro mi, sir, przynoszê z³e wieœci. Jeniec uciek³ zanim dotar³em do #sOxbay#.",
"Hmm, s³ucham pana uwa¿nie, kapitanie.",
"Porozmawiajmy o tym póŸniej, sir.",
"W³aœnie wróci³em z #sOxbay#, sir.",
"Pañskie zadanie zosta³o wykonane.",
"Niestety, nie mam w tej chwili ¿adnych wieœci. Ale proszê dowiadywaæ siê póŸniej.",
"Mam sprawê do omówienia.",
"To tylko wizyta grzecznoœciowa. Do widzenia.",
"W porz¹dku, kapitanie ",
", ale przed prób¹ spotkania siê ze mn¹, powinien pan by³ staranniej rozwa¿yæ dobór tematów.",
"Czy ma pan mo¿e pracê dla zdolnego kapitana?",
"Tak tylko wst¹pi³em, sir. Do widzenia.",
"Hahahaha, niech pan nie bêdzie taki skromny, kapitanie. Mo¿e powie pan, ¿e to oni zaczêli!",
"Tak siê sk³ada, ¿e to prawda, sir.",
"W ka¿dym razie mi³o mi wrêczyæ panu tê nagrodê za walkê z piratami.",
"Dziêkujê, sir. Jest coœ, o czym powinniœmy pomówiæ.",
"Dziêkujê. Przy okazji, nie ma pan mo¿e pracy dla zdolnego kapitana?",
"Jestem wdziêczny, Sir ",
", za tê nagrodê. Niestety, na mnie ju¿ czas. Do widzenia.",
"To niepokoj¹ca wiadomoœæ... Ale sk¹d piraci na tych wodach?\nEskadra dowodzona przez kapitana Tomlinsona zapewnia³a mnie, ¿e z³apali albo zatopili wszystkich tych szubrawców!",
"W tym rzecz, sir. To nie byli piraci. To by³y francuskie okrêty z francuskimi ¿o³nierzami.",
"Co?! Wiedzia³em. Carl ju¿ dawno powinien by³ daæ salwê ostrzegawcz¹.\nProszê opowiedzieæ mi o wszystkim. Jak uda³o siê panu przeœlizgn¹æ? Ile okrêtów, ile dzia³ i ¿o³nierzy? Sk¹d przyp³ynêli?\nJest pan pewien, ¿e to by³y okrêty francuskiej floty?",
"Absolutnie, sir. Francuskie flagi to pierwsza rzecz, któr¹ zauwa¿y³em.",
"To straszne, straszne! Francuscy ¿o³nierze na angielskiej ziemi i resztki z³ota w skarbcu kolonii na prowadzenie otwartej wojny. Jak mamy broniæ w³asnych domów?\nObawiam siê, ",
", ¿e ta sprawa dotyczy te¿ pana i pañskiego statku.",
"Mnie? W jaki sposób?",
"Mówiliœmy o francuskiej eskadrze.",
"Hmm. Nie podoba mi siê to. Lepiej pójdê, sir.",
"Widzi pan, kapitanie, po kampanii przeciwko piratom zosta³y nam tylko dwa okrêty wojenne, które zreszt¹ s¹ zbyt cenne na tak¹ wyprawê. Z uwagi na to, niniejszym wydajê rozkaz zarekwirowania i uzbrojenia prywatnych statków, gdziekolwiek s¹ one potrzebne do obrony naszych terenów.\nPrzykro mi, kapitanie, ale pañski statek nie jest wy³¹czony z tego rozkazu.",
"Co? Nie pozwolê zarekwirowaæ mojego statku!",
"Tak, tak... A wiêc jakich okrêtów u¿yto do oblê¿enia fortu? Jak¹ mieli broñ? Ilu ¿o³nierzy?",
"Naliczy³em piêæ okrêtów... 24-dzia³owy bryg, 20-dzia³owy szkuner... Reszta okrêtów by³a przes³oniêta mg³¹.",
"Drogi ",
", przykro mi, ale nie mogê pana wypuœciæ. Muszê zarekwirowaæ pañski statek i wys³aæ go na najeŸdŸców.",
"Przepraszam, sir, nie us³ysza³em, co pan powiedzia³...",
"Jeœli bêdzie pan stawia³ opór, kapitanie, bêdê musia³ skonfiskowaæ pañski statek.\nProszê zrozumieæ, ¿e nie mam innego wyjœcia.",
"Pozwolê sobie zaproponowaæ inne wyjœcie - mój statek i ja jesteœmy na pañskie us³ugi.",
"Chce mnie pan zmusiæ? Proszê bardzo, œmia³o!",
"Pañskie informacje nie s¹ zbyt pomocne, kapitanie. Wielka szkoda, bo pañska sytuacja nie jest do pozazdroszczenia. I tak coœ panu powiem, ",
".",
"Powie mi pan coœ? Ciekawe... Zamieniam siê w s³uch, sir.",
"Doskona³a decyzja, kapitanie ",
". Cieszê siê, ¿e znaleŸliœmy rozwi¹zanie, które pasuje nam obu. A teraz przejdŸmy do pañskiego zadania. Wydaje mi siê, ¿e zamiast zmuszaæ pana do s³u¿by w armii, lepiej bêdzie\ndaæ panu woln¹ rêkê.",
"Co ma pan na myœli, sir?",
"Chwilowo zignorujê pañsk¹ bezczelnoœæ, kapitanie. Proszê jednak pamiêtaæ, ¿e mam na biurku na³adowan¹ broñ, a za drzwiami s¹ stra¿e. Pozwolê sobie kontynuowaæ...",
"W takim razie, chcia³bym sam dowodziæ moim statkiem! Proszê mi pozwoliæ ¿eglowaæ nim dla pana, sir!",
"Mam nadziejê, ¿e jako nowa twarz na tych wodach zdobêdzie pan wiêcej informacji na temat oddzia³ów francuskich.\nZ s¹siedniej kolonii na wyspie mo¿e pan przejœæ przez d¿unglê i przedostaæ siê przez mury miasta, a w œrodku dowie siê pan wiêcej od mieszkañców.\nByæ mo¿e uda siê panu pods³uchaæ samych francuskich ¿o³nierzy.",
"Chce pan, bym zakrad³ siê do zajêtego miasta i dowiedzia³ siê, jakie s¹ plany Francuzów wzglêdem kolonii?",
"A co z zap³at¹, sir?",
"Tak... To œmia³y plan. Jeœli siê powiedzie, mo¿e bêdziemy wiedzieli, gdzie spodziewaæ siê nastêpnego ataku, i co wiêcej, jak uwolniæ nasz¹ koloniê.",
"Rozumiem. ¯yczê panu pomyœlnoœci, sir.",
"Przy okazji, mo¿e móg³bym otrzymaæ czêœæ zap³aty z góry, zanim wyruszê?",
"Jeœli potrzeba panu pieniêdzy, kapitanie, oto 1000 sztuk z³ota. Ale niech pan je wyda na przygotowanie statku do podró¿y. Proszê pamiêtaæ, ¿e potr¹cê tê kwotê z ostatecznej zap³aty.",
"Dziêkujê, sir.",
"Niestety, kapitanie ",
", nie mogê zap³aciæ panu z góry - musimy przeznaczyæ fundusze na zbudowanie eskadry i przygotowanie fortu na ewentualn¹ kampaniê wojenn¹.",
"Bardzo mnie to pobudzi³o do dzia³ania.",
"Zapewniam pana, kapitanie, otrzyma pan rekompensatê. Ale proszê nie próbowaæ mnie oszukaæ. Jeœli spróbuje siê pan wymigaæ od swojego obowi¹zku\nog³oszê, ¿e jest pan piratem, a eskadra kapitana Tomlinsona bêdzie pana œcigaæ po kres pañskich dni.",
"Jeœli coœ z niej zostanie po walkach z Francuzami!",
"Hmm, nasza rozmowa zboczy³a nieco w niew³aœciw¹ stronê. Proszê pamiêtaæ, pañskim zadaniem jest uzyskanie informacji o planach Francuzów wzglêdem #sOxbay#.\nNiech pan porozmawia z miejscowymi, pójdzie do tawerny - na pewno bêdzie otwarta, Francuzi bêd¹ chcieli odpocz¹æ po bitwie.\nNiech sie pan postara o jak najwiêcej informacji na temat planów dowództwa francuskiego.\nProszê mi wierzyæ, odp³acê panu za to bardzo szczodrze. Powodzenia. ",
"Do widzenia, sir.",
"Proszê pos³uchaæ, ",
", to z³o konieczne. Powinien pan uwa¿aæ siê za szczêœciarza.\nZosta³ pan przyjêty w s³u¿bê Koronie, co jest dla wielu marzeniem. Poza tym znany jestem ze szczodroœci dla moich kapitanów!",
"Mam nadziejê, ¿e szybko siê przekonam o tej szczodroœci.",
"Hmm... gratulujê powrotu, kapitanie. Proszê o sprawozdanie.",
"Obywatele #sOxbay# nie przepadaj¹ za najeŸdŸcami.",
"Uda³o siê panu dowiedzieæ, co ta inwazja oznacza dla przysz³ych planów Francuzów?",
"U¿ywaj¹ #sOxbay# jako bazy przysz³ego ataku na Redmond. Eskadra stoj¹ca w #sOxbay# czeka na amunicjê, która ma przyp³yn¹æ z Falaise de Fleur na statku towarowym. Gdy uzupe³ni¹ zapasy, postawi¹ ¿agle i zaatakuj¹ Redmond.",
"Te informacje s¹ bezcenne. Udowodni³ pan sw¹ wartoœæ. Dziêkujê za pañskie us³ugi, ",
". Oto zap³ata 3000 sztuk z³ota.",
"Dziêkujê, sir.",
"Zwa¿ywszy na pañskie doniesienia, pañskim nastêpnym zadaniem bêdzie dopilnowanie, by amunicja nie dotar³a do #sOxbay#. Gdy wreszcie staniemy do walki z Francuzami, im mnie prochu bêd¹ mieli, tym lepiej.",
"Chce pan, ¿ebym zatopi³ tê barkentynê?",
"Co pan z ni¹ zrobi, zostawiam panu do wyboru, kapitanie. Aborda¿, zatopienie... Decyzja nale¿y do pana. Przede wszystkim Francuzi nie mog¹ dostaæ tej amunicji.",
"A co z eskort¹? Mo¿e byæ zbyt potê¿na dla mojego statku.",
"Tak. Na pewno bêdzie eskorta. Z pewnoœci¹, ",
".",
"Zgoda. Ale, ",
", byæ mo¿e da siê j¹ wykorzystaæ z po¿ytkiem dla nas,\nskoro udowodni³ pan, ¿e potrafi siê wkraœæ na wrogi teren i zachowaæ przy tym spryt. Wyp³ynie pan do #sisland_Falaise. Korzystaj¹c z rozumu i kilku odpowiednio umiejscowionych pytañ mo¿e uda siê panu za³atwiæ eskortê zanim podniesie ¿agle...",
"Brzmi to niezbyt pewnie, ale spróbujê...",
"Dobrze, ",
", ale proszê nie zapominaæ, ¿e powinien pan siê do mnie odpowiednio zwracaæ.",
"Nie jestem przyzwyczajony do takich formalnoœci...",
"Proszê zatem pamiêtaæ, ¿e dopóki s³u¿y pan mi, s³u¿y pan Koronie. Niech to panu nie wyleci z g³owy, kapitanie...",
"Tak, sir.",
"Rozumiem, ¿e uda³o siê panu wyeliminowaæ francusk¹ eskadrê?",
"Absolutnie tak, sir.",
"Gdy wyp³yn¹³ pan, wys³a³em innego kapitana do #sOxbay#. Odkry³ on du¿¹ jaskiniê na wyspie w pobli¿u ustronnej pla¿y.\nZamierzam pos³aæ tam garnizon ¿o³nierzy i ukryæ ich w jaskini. Gdy bêd¹ na miejscu, wykorzystam ich do uwolnienia miasta, w czasie gdy my przeprowadzimy skoordynowany atak z morza i l¹du.",
"Rozs¹dny plan, ale nie s¹dzê, by na moim statku zmieœci³ siê ca³y oddzia³.",
"Nie ma takiej potrzeby, kapitanie. Ju¿ za³atwi³em transport. Pañskim zadaniem bêdzie strze¿enie okrêtu desantowego na jego trasie. Slup 'Albion', którym dowodzi kapitan ",
"Ewan Glover",
"Ewan Glover",
", jest zacumowany w porcie. ",
"Ewan Glover",
" bêdzie czeka³ na pana przy bramie miasta.",
"Rozumiem. W takim razie czas na mnie...",
"Proszê poczekaæ, nie skoñczy³em. Musi pan eskortowaæ 'Albion' do przystani #sGreenford# na #sisland_Oxbay#.\nMiejscowy cz³owiek, lojalny Koronie, wska¿e panu drogê do jaskini. Nastêpnie przeniknie pan ponownie do #sOxbay# i znajdzie jednego z naszych agentów ukrytego w mieœcie.",
"Strasznie du¿o do zapamiêtania. Co mam robiæ, gdy znajdê agenta?",
"On ma bardzo wa¿ne informacje. Dlatego pan musi dopilnowaæ, by prze¿y³ i przekaza³ je nam.",
"Jak siê nazywa ten agent?",
"Counterspy",
". Zdoby³ kontakty wœród miejscowej ludnoœci. Jeœli nie znajdzie go pan od razu, proszê popytaæ. Ale dyskretnie.",
"Jak pan sobie ¿yczy. A kiedy mogê siê spodziewaæ zap³aty za moj¹ ostatni¹ misjê?",
"Proszê siê nie martwiæ, ",
", oto pañskie z³oto.",
"Mi³o to s³yszeæ, sir.",
"Teraz mo¿e pan odejœæ, kapitanie. Nie mogê siê doczekaæ nastêpnego raportu.",
"Do widzenia, sir.",
"Có¿, kapitanie ",
"... Mia³em o panu lepsze mniemanie. Ale co siê sta³o, to siê nie odstanie. Przynajmniej czêœæ zadania zosta³a wype³niona.",
"Ale...",
"Gratulujê, kapitanie. Powiem szczerze, nie mogê wyraziæ s³owami, jakim wybawieniem pan jest, odk¹d przyj¹³em pana na s³u¿bê.",
"Dziêkujê, sir.",
"Nie jestem zainteresowany pañskimi wyjaœnieniami, kapitanie. Pañskie sprawozdanie przekaza³ mi ",
"Counterspy",
", wyjaœniaj¹c, co siê sta³o. Jestem po prostu rozczarowany, bo z powodu pañskiej pora¿ki w tej wojnie przeleje siê wiêcej krwi.",
"Przykro mi, ",
", robi³em, co mog³em.",
"... Có¿, bywa i tak. W koñcu dziêki panu mieliœmy mo¿liwoœæ odbudowania naszej eskadry.",
"Jakie jest moje nastêpne zadanie?",
"Bêdzie pan bra³ udzia³ w ataku na #sOxbay# jako czêœæ naszej eskadry. Nie trzeba mówiæ, ¿e musi siê pan przygotowaæ.\nMam nadziejê, ¿e tyle panu wystarczy. Aha, odj¹³em czêœæ pañskiej zap³aty ze wzglêdu na utratê 'Albionu'.",
"Kiedy wyruszamy?",
"Wkrótce. Na razie proszê za³atwiæ potrzebne sprawy w mieœcie, a w odpowiednim czasie pana powiadomimy. Proszê te¿ trochê odpocz¹æ i odprê¿yæ siê. Ka¿dy kapitan powinien po rejsie spêdziæ solidny wieczór w tawernie.",
"Nie w g³owie mi to, ale w pañskich s³owach jest ziarnko prawdy.",
"To niewa¿ne. Mój pos³aniec pana znajdzie. Powodzenia, kapitanie.",
"¯egnaj.",
"counterspy",
" powiadomi³ nas w³aœnie o pañskich wyczynach. A ",
"Ewan Glover",
"Ewan Glover",
" wygl¹da³ na zadowolonego z waszego wspólnego rejsu.",
"Hmm... Nie przypominam sobie ¿adnych wyczynów.",
"Ha. Jest pan zbyt skromny. Oto pañska nagroda. Sugerujê, by doprowadzi³ pan swój statek do stanu u¿ywalnoœci. Wkrótce bêdzie pan znów musia³ wyp³yn¹æ.",
"Co to bêdzie za misja tym razem?",
"Oblê¿enie #sOxbay#. Do³¹czy pan do naszej eskadry, która oswobodzi wyspê.",
"A kiedy wyrusza ta eskadra?",
"Wkrótce. Na razie proszê za³atwiæ potrzebne sprawy w mieœcie, a w odpowiednim czasie pana powiadomimy. Proszê te¿ trochê odpocz¹æ i odprê¿yæ siê. Ka¿dy kapitan powinien po rejsie spêdziæ solidny wieczór w tawernie. Wyœlê do pana pos³añca.",
"W porz¹dku, pójdê ju¿.",
"Co?! Co ty tu robisz?! ",
"? ",
"Danielle",
"?!!",
"Przepraszam, ¿e zak³ócam pañski sen, drogi gubernatorze, ale mamy pytania, które wymagaj¹ odpowiedzi.",
"Jak to? Proszê wyjœæ natychmiast, a zastanowiê siê nad oszczêdzeniem panu ¿ycia!",
"Chyba przecenia pan swoj¹ pozycjê, gubernatorze, ",
". Pan ju¿ nie wydaje rozkazów. A jeœli pan choæby pomyœli bez pytania, wtedy ",
"Danielle",
" mo¿e poczuæ siê zmuszona do przeæwiczenia swoich eleganckich technik szermierczych.",
"Dobrze, dobrze! Nie ma potrzeby byæ tak niegrzecznym. Oczywiœcie, odpowiem na wszystkie wasze pytania... Tylko schowaj swój miecz, ",
"Danielle",
", proszê, powstrzymaj go! Jego spojrzenie bardzo mnie niepokoi.",
"Proszê byæ cicho i s³uchaæ. Wiemy o pañskich postêpkach ze skarbem. NieŸle pan sobie nagrabi³.",
"Proszê, wy diab³y, nie róbcie mi krzywdy!",
"To pochlebne okreœlenie, ale na razie powie nam pan, co wie o pos¹¿ku otwieraj¹cym drzwi do pa³acu.",
"Nic wam, szubrawcy, nie powiem! Stra¿e!",
"O nie! ",
"Danielle",
"! Uciekajmy na statki!",
"Uciek³? Jak to siê mog³o staæ?",
"Nie wyjaœnili tego. Powiedzieli tylko, ¿e poszukiwania uciekiniera trwaj¹.",
"Cholera! Sytuacja wymyka siê spod kontroli!",
"Przepraszam, sir, ale mam dla pana dobre wieœci.",
"S³ucham, ",
", nie mam ca³ego dnia!",
"Znalaz³em œlad kapitana, który zdradzi³ Angliê i pañskie zaufanie.",
"Raoul Rheims",
"? To prawda. To nie jest najgorsza wiadomoœæ dzisiaj.",
"Jestem gotów, by go schwytaæ, jeœli pan sobie ¿yczy, sir.",
"Oczywiœcie, pomyœlnych wiatrów, ",
". Aha, kapitanie... Tym razem musi go pan tu doprowadziæ. Proszê te¿ pamiêtaæ, ¿e zanim tu przybêdzie, nie powinien z nikim rozmawiaæ, nawet z panem. Czy to jasne?",
"Tak, sir. Zrobiê wszystko tak, jak pan mówi.",
"! Tyle czasu pana nie by³o, zacz¹³em siê martwiæ!",
"Wszystko w porz¹dku, wype³ni³em zadanie.",
"Szczerze mówi¹c, jestem zdumiony, nie oczekiwa³em pozytywnego rezultatu tej ekspedycji.\nUda³o siê panu zebraæ dla mnie ca³¹ kolekcjê, tak?",
"Tak, sir, oprócz jednego pos¹¿ka. Kupi³ go jakiœ nieznajomy.",
"Jednego pos¹¿ka? Zobaczmy, czego brakuje.",
"Proszê samemu zobaczyæ, sir.",
"To prawda, jednego pos¹¿ka brakuje, co za szkoda.",
"Chce pan, ¿ebym go znalaz³, sir?",
"Nie, proszê siê tym nie przejmowaæ, ",
", ale doceniam, ¿e jest pan skory do pomocy. Zamiast tego mam dla pana inne zadanie. Znajdê kogoœ innego, ¿eby odnalaz³ pos¹¿ek.\nAch, prawie zapomnia³em. Oto obiecana zap³ata.",
"Dziêkujê, sir. Jestem ciekaw, jak¹ misjê ma pan dla mnie.",
"Tak... Kilka minut przed pañskim przybyciem, ",
", poinformowano mnie, ¿e w Greenford schwytano pirata. Ten pirat zawsze wyœlizgiwa³ mi siê z r¹k, czym bardzo mnie irytowa³.\nChcê, ¿eby pan go tu przywióz³.",
"Brzmi niezbyt skomplikowanie, sir. Mogê ju¿ iœæ?",
"Chwileczkê, ",
". Doceniam pañski entuzjazm, ale to nie wszystko.",
"Przepraszam, sir.",
"W Greenford odda pan list, którego adresatem jest ",
"Bridgetown Prison Commendant",
"Bridgetown Prison Commendant",
".\nProszê mu przekazaæ ten list, a on uwolni wiêŸnia pod pañski nadzór.\nPo powrocie otrzyma pan 5000 sztuk z³ota.",
"Zrozumia³em, sir.",
"Mam nadziejê, ¿e pañski powrót oznacza wykonanie zadania i dorêczenie listu do odbiorcy.",
"Tak, sir. Ale by³o to prawdziwe wyzwanie. Piraci nie odznaczaj¹ siê najlepszymi manierami, jednak mo¿e pan byæ spokojny. List dotar³ do adresata.",
"Dobra robota. Mam nadziejê, ¿e nastêpnym zadaniem zajmie siê pan równie umiejêtnie, ",
".",
"A co to mo¿e byæ za robota?",
"Chwileczkê, nie ma powodu do poœpiechu, ",
". Najpierw dam panu nagrodê.",
"Dziêkujê, sir. Praca dla pana to przyjemnoœæ, sir.",
"A pañskie pochlebstwa uchodz¹ mi mimo uszu, ",
". A teraz przejdŸmy do interesów.",
"Zamieniam siê w s³uch, sir.",
"Pañskie nastêpne zadanie, ",
", to dla mnie sprawa doœæ osobista. Na moim stanowisku u¿ywanie oddzia³ów Imperium do w³asnych celów by³oby raczej nieetyczne. Dlatego te¿ jestem zainteresowany pañskimi us³ugami.",
"Zaintrygowa³ mnie pan. Oby tylko nie kaza³ mi pan w³asnorêcznie pokonaæ ca³ej francuskiej floty.",
"Ma pan poczucie humoru, ",
", ale nie zbaczajmy z g³ównego tematu.",
"Przepraszam, sir.",
"Kilka dni temu piraci schwytali statek '",
"pirate captain 06",
", p³yn¹cy do Europy z New Light. Gdy przep³ywa³ niedaleko naszej kolonii, piraci zaatakowali.\nOprócz zwyk³ych towarów handlowych na pok³adzie by³o kilka z³otych pos¹¿ków. To rzadkie inkaskie skarby, które zamówi³em do mojej kolekcji.\nOdkry³em, ¿e herszt piratów, który zleci³ porwanie statku, nazywa siê ",
"Alistair Garcilaso",
"Alistair Garcilaso",
".\nMówi¹, ¿e wraz ze swoj¹ szajk¹ rzeŸników i z³odziei ukrywa siê w d¿ungli Douwesen, ale nie wiem, gdzie dok³adnie. Chcê, by pan, ",
", odnalaz³ ich i zwróci³ mi moj¹ kolekcjê.\nZdajê sobie sprawê, ¿e to nie naj³atwiejsze zadanie, i dlatego ju¿ teraz dajê panu 10000 i drugie tyle po udanym zakoñczeniu misji.\nJak wspomnia³em, brzydzê siê wykorzystywaniem ¿o³nierzy do spraw prywatnych. Poza tym sama myœl o desancie ¿o³nierzy na Douwesen... grozi³by nam konflikt z Holendrami.\nPan jest moj¹ jedyn¹ nadziej¹.",
"Odnalezienie ludzi, którzy nie chc¹ zostaæ odnalezieni, to nie³atwe zadanie, ale chyba s³u¿ê panu dobrze, a ta sumka jest ca³kiem spora.",
"Jeœli uda siê panu wykonaæ zadanie, bêdzie tego warta, ",
". A wiêc, bez dalszego odwlekania, oto pierwsza czêœæ zap³aty. Powodzenia.",
"Wrócê jak najszybciej, sir.",
"Wróci³ pan, ",
", ale gdzie jest ",
"Raoul Rheims",
"? Nie widzê go z panem.",
"Zawiod³em, sir, zgubi³em trop w kryjówce przemytników.",
"Rozczarowa³ mnie pan, ",
". Taka prosta misja i nie uda³o siê panu jej wykonaæ?! Mia³em o panu wy¿sze mniemanie.",
"Najmocniej przepraszam, sir, ale uda³o mi siê dowiedzieæ, co ",
"Raoul Rheims",
" zamierza teraz zrobiæ. Wyrusza na ekspedycjê.",
"W mojej naturze nie le¿y karanie za niepowodzenia, szczególnie gdy zosta³ w³o¿ony powa¿ny wysi³ek. Ale mam nadziejê, ¿e nie zawiedzie pan w kolejnej misji.",
"Dziêkujê za okazane mi zaufanie, sir. Zrobiê, co tylko bêdê móg³, by ponownie pana nie zawieœæ.",
"Nie ma za co, ",
". Przy okazji, oto obiecane 5000 sztuk z³ota, chocia¿ do koñca pan na nie nie zas³u¿y³.",
"Dziêkujê, sir. Pañska szczodroœæ mnie zadziwia.",
"Starczy tego, ",
". Nie potrzebujê pana pochlebstw. A teraz porozmawiajmy o interesach. Rozumiem, ¿e by³ pan w gnieŸdzie piratów\nwiêc skoro zna pan drogê, chcia³bym, by zaniós³ pan ten list do herszta piratów. Nazywa siê ",
"Isenbrandt Jurcksen",
"Isenbrandt Jurcksen",
".\nProszê siê nie niepokoiæ, na pewno jest pan ciekaw, jakie¿ informacje mogê mieæ dla tej kanalii. Mo¿e pan pamiêta, ¿e ",
"Raoul Rheims",
" wie teraz za du¿o, bym móg³ pozwoliæ mu uciec.\nSkoro pan nie by³ w stanie go schwytaæ, mo¿e tym piratom siê uda. Kiedy mo¿e pan wyruszyæ w podró¿?",
"Mój statek jest gotów do wyp³yniêcia, sir.",
"Doskonale. W takim razie ruszajcie natychmiast. Gdy wype³ni pan swoje zadanie, proszê wróciæ do mnie po nagrodê. Czy wszystko jasne, ",
"?",
"Tak jest, sir, wyp³ynê natychmiast.",
"Dobrze, nikt nam nie przeszkodzi.",
"S³ucham, sir.",
"Po pierwsze, chcia³bym podzieliæ siê z panem radosn¹ nowin¹ - #sOxbay# zosta³o uwolnione.\nBardzo nam pan pomóg³ w walce o zwyciêstwo. Dziêkujê.",
"Nie ma za co. A mo¿e ma pan jeszcze coœ dla mnie.",
"Oczywiœcie. Chcia³bym, ¿eby przyprowadzi³ pan do mnie osobê, która nas zdradzi³a i narazi³a koloniê na takie niebezpieczeñstwo! Ten cz³owiek nazywa siê ",
"Raoul Rheims",
"Raoul Rheims",
".",
"Jeœli wolno mi spytaæ, co on takiego zrobi³?",
"Dociekliwy! To mi siê podoba. Bez dwóch zdañ, Rheims to nikczemny zdrajca Korony. Oprócz tego zdradzi³ w³asn¹ za³ogê. Wype³nia³ bardzo wa¿ne zadanie i niespodziewanie zmieni³ barwy.\nGdy jeden z cz³onków jego za³ogi ostrzeg³ mnie o zdradzie Rheimsa, niemal uda³o siê nam zapobiec temu nieszczêœciu.\nNiestety, biedaczek by³ ju¿ jedn¹ nog¹ w grobie i nie móg³ powiedzieæ mi, dok¹d zmierza³ Rheims.\nWiemy, ¿e zatrzymali siê w obozie piratów, by uzupe³niæ zapasy. Powinien pan tam pop³yn¹æ i jeœli ",
"Raoul Rheims",
" wci¹¿ tam jest, aresztowaæ go.\nJeœli go nie bêdzie, proszê dowiedzieæ siê jak najwiêcej.",
"Zrozumia³em. Jednak konfrontacje z piratami s¹ niebezpieczne. Spodziewam siê niez³ego wynagrodzenia.",
"I takie pan otrzyma. Zap³acê panu 5000 sztuk z³ota w tej chwili i 5000 po dostarczeniu zdrajcy.",
"Uczciwa cena. Ruszam w drogê, sir.",
"Jak to mo¿liwe, ¿e jest pan wolny? Co siê sta³o? Co ze stra¿ami?",
"Przykro mi, ale zosta³em niesprawiedliwie uwiêziony. Nie zamierza³em zostaæ tam na zawsze. Gdy odzyska³em broñ, wydosta³em siê na wolnoœæ.",
"Przepraszam, ",
"! Zasz³a straszliwa pomy³ka.\nMoi ¿o³nierze mieli aresztowaæ francuskiego szpiega.\nNajwyraŸniej pomylili pana z nim.",
"Dziêkujê, za przeprosiny, sir. Nie by³em pewien, czy jeszcze kiedykolwiek ujrzê wolnoœæ.",
"Podziwiam pañskie umiejêtnoœci i przebieg³oœæ. To przynosi panu zaszczyt, ale stra¿nik w wiêzieniu powinien zawisn¹æ za to, ¿e pozwoli³ panu uciec!",
"Obawiam siê, ¿e nie ma kogo wieszaæ, sir. Ju¿ siê nim zaj¹³em.",
"To pañska sprawa. Mo¿e móg³by mi pan teraz wyjaœniæ, dlaczego znalaz³em siê w wiêzieniu.",
"Chcia³bym wyst¹piæ w jego imieniu. Mówi, ¿e w swoim czasie ca³kiem sprawnie pos³ugiwa³ siê dzia³ami. Potrzebny mi dobry artylerzysta i, za pañskim pozwoleniem, chcia³bym w³¹czyæ go do mojej za³ogi.",
"Hmm, chyba mogê potraktowaæ go ³askawie, ",
", ale ten stra¿nik jest w s³u¿bie kolonii - nie mogê go puœciæ ot tak.",
"Proszê wiêc podaæ mi cenê za zast¹pienie go innym, sir.",
"Wystarczy 1000 sztuk z³ota.",
"Uczciwa cena, sir. Zgadzam siê. ",
"To wiêcej ni¿ siê spodziewa³em. Bêdzie lepiej, jeœli ten stra¿nik bêdzie s³u¿y³ panu.",
"Proszê go zabraæ, ale mo¿e pan tego póŸniej ¿a³owaæ, s³ysza³em, ¿e to pijak.",
"Wezmê pod uwagê pañskie ostrze¿enie, sir. A teraz mo¿e wyjaœni mi pan, czemu zosta³em aresztowany.",
"Jest pan zbyt spragniony krwi, ale mo¿e w³aœnie to jest potrzebne na tym œwiecie - pañska rêka nigdy nie zadr¿y z ¿alu.",
"Mam tak¹ nadziejê, sir. A teraz mo¿e zechce mi pan powiedzieæ, czemu kaza³ mnie aresztowaæ?",
"Straszliwa pomy³ka. Straszliwa. Moi ¿o³nierze zostali wys³ani, by aresztowaæ francuskiego szpiega. Agenci zapewniali mnie, ¿e by³ w tawernie akurat w tym momencie.\nWygl¹da na to, ¿e on ju¿ wyszed³ i moi ¿o³nierze aresztowali pana zamiast niego.",
"Có¿, jedna zagadka siê wyjaœni³a. Mo¿e pan sobie wyobraziæ moje zaniepokojenie, gdy znalaz³em siê w tym ciemnym, strasznym miejscu.",
"Straszliwa pomy³ka. Straszliwa. Moi ¿o³nierze zostali wys³ani, by aresztowaæ.\nAgenci zapewniali mnie, ¿e by³ w tawernie akurat w tym momencie.\nWygl¹da na to, ¿e on ju¿ wyszed³ i moi ¿o³nierze aresztowali pana zamiast niego.",
"Có¿, jedna zagadka siê wyjaœni³a.",
"Skoro ju¿ zakoñczyliœmy to ca³e nieporozumienie, chcia³bym, ¿eby przeszed³ pan ze mn¹ do mojego gabinetu.\nMam powa¿ne sprawy do omówienia z panem.",
"Oczywiœcie, sir.",
"Jeszcze raz proszê przyj¹æ przeprosiny za dzia³ania moich ¿o³nierzy.\nMyœlê, ¿e ta suma przekona pana, jak mi przykro z powodu tego wypadku.",
"Dziêkujê, sir. Ja z mojej strony dziêkujê panu za pañsk¹ dobroæ wobec mnie.",
"Ale¿ Proszê, ",
". "Oczywiœcie. Chcia³bym, ¿eby przyprowadzi³ pan do mnie osobê, która nas zdradzi³a i narazi³a koloniê na takie niebezpieczeñstwo! Ten cz³owiek nazywa siê ",
"Raoul Rheims",
"Raoul Rheims",
".",
"Jeœli wolno mi spytaæ, co on takiego zrobi³?",
"Dociekliwy! To mi siê podoba. Bez dwóch zdañ, Rheims to nikczemny zdrajca Korony. Oprócz tego zdradzi³ w³asn¹ za³ogê. Wype³nia³ bardzo wa¿ne zadanie i niespodziewanie zmieni³ barwy.\nGdy jeden z cz³onków jego za³ogi ostrzeg³ mnie o zdradzie Rheimsa, niemal uda³o siê nam zapobiec temu nieszczêœciu.\nNiestety, biedaczek by³ ju¿ jedn¹ nog¹ w grobie i nie móg³ powiedzieæ mi, dok¹d zmierza³ Rheims.\nWiemy, ¿e zatrzymali siê w obozie piratów, by uzupe³niæ zapasy. Powinien pan tam pop³yn¹æ i jeœli ",
"Raoul Rheims",
" wci¹¿ tam jest, aresztowaæ go.\nJeœli go nie bêdzie, proszê dowiedzieæ siê jak najwiêcej.",
"Zrozumia³em. Jednak konfrontacje z piratami s¹ niebezpieczne. Spodziewam siê niez³ego wynagrodzenia.",
"I takie pan otrzyma. Zap³acê panu 5000 sztuk z³ota w tej chwili i 5000 po dostarczeniu zdrajcy.",
"Uczciwa cena. Ruszam w drogê, sir.",
"Jak to mo¿liwe, ¿e jest pan wolny? Co siê sta³o? Co ze stra¿ami?",
"Przykro mi, ale zosta³em niesprawiedliwie uwiêziony. Nie zamierza³em zostaæ tam na zawsze. Gdy odzyska³em broñ, wydosta³em siê na wolnoœæ.",
"Przepraszam, ",
"! Zasz³a straszliwa pomy³ka.\nMoi ¿o³nierze mieli aresztowaæ francuskiego szpiega.\nNajwyraŸniej pomylili pana z nim.",
"Dziêkujê, za przeprosiny, sir. Nie by³em pewien, czy jeszcze kiedykolwiek ujrzê wolnoœæ.",
"Podziwiam pañskie umiejêtnoœci i przebieg³oœæ. To przynosi panu zaszczyt, ale stra¿nik w wiêzieniu powinien zawisn¹æ za to, ¿e pozwoli³ panu uciec!",
"Obawiam siê, ¿e nie ma kogo wieszaæ, sir. Ju¿ siê nim zaj¹³em.",
"To pañska sprawa. Mo¿e móg³by mi pan teraz wyjaœniæ, dlaczego znalaz³em siê w wiêzieniu.",
"Chcia³bym wyst¹piæ w jego imieniu. Mówi, ¿e w swoim czasie ca³kiem sprawnie pos³ugiwa³ siê dzia³ami. Potrzebny mi dobry artylerzysta i, za pañskim pozwoleniem, chcia³bym w³¹czyæ go do mojej za³ogi.",
"Hmm, chyba mogê potraktowaæ go ³askawie, ",
", ale ten stra¿nik jest w s³u¿bie kolonii - nie mogê go puœciæ ot tak.",
"Proszê wiêc podaæ mi cenê za zast¹pienie go innym, sir.",
"Wystarczy 1000 sztuk z³ota.",
"Uczciwa cena, sir. Zgadzam siê. ",
"To wiêcej ni¿ siê spodziewa³em. Bêdzie lepiej, jeœli ten stra¿nik bêdzie s³u¿y³ panu.",
"Proszê go zabraæ, ale mo¿e pan tego póŸniej ¿a³owaæ, s³ysza³em, ¿e to pijak.",
"Wezmê pod uwagê pañskie ostrze¿enie, sir. A teraz mo¿e wyjaœni mi pan, czemu zosta³em aresztowany.",
"Jest pan zbyt spragniony krwi, ale mo¿e w³aœnie to jest potrzebne na tym œwiecie - pañska rêka nigdy nie zadr¿y z ¿alu.",
"Mam tak¹ nadziejê, sir. A teraz mo¿e zechce mi pan powiedzieæ, czemu kaza³ mnie aresztowaæ?",
"Straszliwa pomy³ka. Straszliwa. Moi ¿o³nierze zostali wys³ani, by aresztowaæ francuskiego szpiega. Agenci zapewniali mnie, ¿e by³ w tawernie akurat w tym momencie.\nWygl¹da na to, ¿e on ju¿ wyszed³ i moi ¿o³nierze aresztowali pana zamiast niego.",
"Có¿, jedna zagadka siê wyjaœni³a. Mo¿e pan sobie wyobraziæ moje zaniepokojenie, gdy znalaz³em siê w tym ciemnym, strasznym miejscu.",
"Straszliwa pomy³ka. Straszliwa. Moi ¿o³nierze zostali wys³ani, by aresztowaæ.\nAgenci zapewniali mnie, ¿e by³ w tawernie akurat w tym momencie.\nWygl¹da na to, ¿e on ju¿ wyszed³ i moi ¿o³nierze aresztowali pana zamiast niego.",
"Có¿, jedna zagadka siê wyjaœni³a.",
"Skoro ju¿ zakoñczyliœmy to ca³e nieporozumienie, chcia³bym, ¿eby przeszed³ pan ze mn¹ do mojego gabinetu.\nMam powa¿ne sprawy do omówienia z panem.",
"Oczywiœcie, sir.",
"Jeszcze raz proszê przyj¹æ przeprosiny za dzia³ania moich ¿o³nierzy.\nMyœlê, ¿e ta suma przekona pana, jak mi przykro z powodu tego wypadku.",
"Dziêkujê, sir. Ja z mojej strony dziêkujê panu za pañsk¹ dobroæ wobec mnie.","Oczywiœcie. Chcia³bym, ¿eby przyprowadzi³ pan do mnie osobê, która nas zdradzi³a i narazi³a koloniê na takie niebezpieczeñstwo! Ten cz³owiek nazywa siê ",
"Raoul Rheims",
"Raoul Rheims",
".",
"Jeœli wolno mi spytaæ, co on takiego zrobi³?",
"Dociekliwy! To mi siê podoba. Bez dwóch zdañ, Rheims to nikczemny zdrajca Korony. Oprócz tego zdradzi³ w³asn¹ za³ogê. Wype³nia³ bardzo wa¿ne zadanie i niespodziewanie zmieni³ barwy.\nGdy jeden z cz³onków jego za³ogi ostrzeg³ mnie o zdradzie Rheimsa, niemal uda³o siê nam zapobiec temu nieszczêœciu.\nNiestety, biedaczek by³ ju¿ jedn¹ nog¹ w grobie i nie móg³ powiedzieæ mi, dok¹d zmierza³ Rheims.\nWiemy, ¿e zatrzymali siê w obozie piratów, by uzupe³niæ zapasy. Powinien pan tam pop³yn¹æ i jeœli ",
"Raoul Rheims",
" wci¹¿ tam jest, aresztowaæ go.\nJeœli go nie bêdzie, proszê dowiedzieæ siê jak najwiêcej.",
"Zrozumia³em. Jednak konfrontacje z piratami s¹ niebezpieczne. Spodziewam siê niez³ego wynagrodzenia.",
"I takie pan otrzyma. Zap³acê panu 5000 sztuk z³ota w tej chwili i 5000 po dostarczeniu zdrajcy.",
"Uczciwa cena. Ruszam w drogê, sir.",
"Jak to mo¿liwe, ¿e jest pan wolny? Co siê sta³o? Co ze stra¿ami?",
"Przykro mi, ale zosta³em niesprawiedliwie uwiêziony. Nie zamierza³em zostaæ tam na zawsze. Gdy odzyska³em broñ, wydosta³em siê na wolnoœæ.",
"Przepraszam, ",
"! Zasz³a straszliwa pomy³ka.\nMoi ¿o³nierze mieli aresztowaæ francuskiego szpiega.\nNajwyraŸniej pomylili pana z nim.",
"Dziêkujê, za przeprosiny, sir. Nie by³em pewien, czy jeszcze kiedykolwiek ujrzê wolnoœæ.",
"Podziwiam pañskie umiejêtnoœci i przebieg³oœæ. To przynosi panu zaszczyt, ale stra¿nik w wiêzieniu powinien zawisn¹æ za to, ¿e pozwoli³ panu uciec!",
"Obawiam siê, ¿e nie ma kogo wieszaæ, sir. Ju¿ siê nim zaj¹³em.",
"To pañska sprawa. Mo¿e móg³by mi pan teraz wyjaœniæ, dlaczego znalaz³em siê w wiêzieniu.",
"Chcia³bym wyst¹piæ w jego imieniu. Mówi, ¿e w swoim czasie ca³kiem sprawnie pos³ugiwa³ siê dzia³ami. Potrzebny mi dobry artylerzysta i, za pañskim pozwoleniem, chcia³bym w³¹czyæ go do mojej za³ogi.",
"Hmm, chyba mogê potraktowaæ go ³askawie, ",
", ale ten stra¿nik jest w s³u¿bie kolonii - nie mogê go puœciæ ot tak.",
"Proszê wiêc podaæ mi cenê za zast¹pienie go innym, sir.",
"Wystarczy 1000 sztuk z³ota.",
"Uczciwa cena, sir. Zgadzam siê. ",
"To wiêcej ni¿ siê spodziewa³em. Bêdzie lepiej, jeœli ten stra¿nik bêdzie s³u¿y³ panu.",
"Proszê go zabraæ, ale mo¿e pan tego póŸniej ¿a³owaæ, s³ysza³em, ¿e to pijak.",
"Wezmê pod uwagê pañskie ostrze¿enie, sir. A teraz mo¿e wyjaœni mi pan, czemu zosta³em aresztowany.",
"Jest pan zbyt spragniony krwi, ale mo¿e w³aœnie to jest potrzebne na tym œwiecie - pañska rêka nigdy nie zadr¿y z ¿alu.",
"Mam tak¹ nadziejê, sir. A teraz mo¿e zechce mi pan powiedzieæ, czemu kaza³ mnie aresztowaæ?",
"Straszliwa pomy³ka. Straszliwa. Moi ¿o³nierze zostali wys³ani, by aresztowaæ francuskiego szpiega. Agenci zapewniali mnie, ¿e by³ w tawernie akurat w tym momencie.\nWygl¹da na to, ¿e on ju¿ wyszed³ i moi ¿o³nierze aresztowali pana zamiast niego.",
"Có¿, jedna zagadka siê wyjaœni³a. Mo¿e pan sobie wyobraziæ moje zaniepokojenie, gdy znalaz³em siê w tym ciemnym, strasznym miejscu.",
"Straszliwa pomy³ka. Straszliwa. Moi ¿o³nierze zostali wys³ani, by aresztowaæ.\nAgenci zapewniali mnie, ¿e by³ w tawernie akurat w tym momencie.\nWygl¹da na to, ¿e on ju¿ wyszed³ i moi ¿o³nierze aresztowali pana zamiast niego.",
"Có¿, jedna zagadka siê wyjaœni³a.",
"Skoro ju¿ zakoñczyliœmy to ca³e nieporozumienie, chcia³bym, ¿eby przeszed³ pan ze mn¹ do mojego gabinetu.\nMam powa¿ne sprawy do omówienia z panem.",
"Oczywiœcie, sir.",
"Jeszcze raz proszê przyj¹æ przeprosiny za dzia³ania moich ¿o³nierzy.\nMyœlê, ¿e ta suma przekona pana, jak mi przykro z powodu tego wypadku.",
"Dziêkujê, sir. Ja z mojej strony dziêkujê panu za pañsk¹ dobroæ wobec mnie.",
„Chcê s³u¿yæ Anglii, wasza Ekscelencjo.”,
„#sgov_nation# zawsze chêtnie przyjmuje nowych kapitanów do swojej us³ugi.”,
"Jesteœmy",
„obecnie w stanie wojny”,
„the”,
„ka¿dy naród”,
". Oczywiœcie,",
" ale",
„Piraci zawsze musz¹ byæ zatopieni na widoku”,
„Sprawiê, ¿e bêdziesz dumny, twoja Ekscelencjo.”,
„Jak siê czujê, sir?”,
„Zaton¹³eœ”,
„wrogie statki”,
„pirackie statki, w sumie”,
" statki.",
"Dziêkujê Ci.",
„Mam nadziejê, ¿e nie bêdziecie k³óciæ siê z moj¹ s³u¿b¹, sir.”
„Rzeczywiœcie nie, kapitanie! W rzeczywistoœci mam przyjemnoœæ przyznaæ ci prowizjê w marynarce Jego Królewskiej Moœci. Jako oficer zostaniesz nagrodzony za ka¿dy statek, który zatopisz w s³u¿bie Anglii”.
„Jestem zaszczycony, Wasza Ekscelencjo, i postaram siê sprostaæ zaufaniu, jakim darzy mnie Jego Wysokoœæ”.
„Chcia³bym odebraæ moj¹ pensjê.”
„Có¿, zaton¹³eœ”
„wrogie statki”,
„statki pirackie”,
„ca³kowita liczba statków. Twoje obecne p³ace s¹”,
„, wiêc ³¹cznie”,
"Dziêkujê Panu.",
„Traumatyczna szumowina! Zanurz statki twoich rodaków, prawda? Zostajesz wypisany z wojska, twoje imiê wyrwa³o siê z roli, a ja nigdy wiêcej nie chcê widzieæ twojej twarzy w tym mieœcie!”,
„...”,
„od ostatniego razu, tutaj”,
„z³oto”
„S³ysza³em, ¿e mam awans.”,
„Naprawdê jesteœ! Doskona³a praca. Twoja nowa ranga to”,
"Dziêkujê Panu.",
„Hiszpañskie statki”,
„Holenderskie statki i”,
„O tak? Mam dla ciebie propozycjê, kapitanie.”,
"W rzeczy samej?",
„Dowiedzia³em siê, ¿e zadanie zosta³o wykonane pomyœlnie; moje gratulacje, kapitanie! Oto twoja nagroda.”,
„Dziêkujê, to by³a przyjemnoœæ ci pomóc.”,
„Musisz zniszczyæ”,
" statek ",
„groŸba wysy³ki”
„. Jeœli j¹ zatopisz, nagrodzê ciê ogromn¹ sum¹”,
„z³oto. Co mówisz, kapitanie?”,
„Nie us³yszysz o niej wiêcej, ¿e obiecujê”.
„Obawiam siê, ¿e nie mogê ci pomóc”,
„Ach”,
„Tak dobrze ciê widzieæ! Jestem Panem”,
„, wys³any przez Jego Wysokoœæ, aby aresztowaæ Sileharda i sprowadziæ go z powrotem do Wielkiej Brytanii; albo, jeœli to siê nie uda, poradziæ sobie bardziej ... bezpoœrednio ... z nim.
„znacznie u³atwi³o mi zadanie”.
„To by³a moja przyjemnoœæ, milordzie”.
„To by³a moja przyjemnoœæ, panie. W rzeczywistoœci mam dla ciebie niespodziankê!”,
„Pragnê przebaczenia, wasza Ekscelencjo.”,
„Jestem zainteresowany poznaniem relacji #sgov_nation# z innymi narodami.”,
„Szukam listu od Marque.”,
„,dobrze z twojej strony, ¿e przestaniesz. Chcia³bym przedstawiæ moje”,
„.Wchodzi, kiedy skoñczymy interesy.”,
„Nie mogê ju¿ s³u¿yæ”,
",Wasza Ekscelencjo.",

„Jestem w s³u¿bie”,
„Jako ubezpieczenie, ¿e jesteœ zdolnym kapitanem, i za wynagrodzenie mojego czasu na przedstawienie swojej sprawy”,
„Muszê ciê o to poprosiæ”,
„z³oto”,
"Nie ma mowy.",
"Bardzo dobrze.",
„W œwietle twojej poprzedniej s³u¿by”,
„przyznaje ci rangê”,
„Skrzywdzi³eœ”,
",huh? ",
„nie zapomina o swoich wrogach. WyjdŸ natychmiast, albo stra¿nicy wyrzuc¹ ciê na twoje ucho!”,
„Spowodowa³eœ”,
„wielka krzywda, kapitanie, ale”,
„jest gotów przeoczyæ swoje przesz³e wykroczenia ... za cenê:”,
„Bardzo dobrze, proszê pana. Akceptujê.”,
„Z przyjemnoœci¹ radzê sobie z tob¹”,
„A ty, twoja Ekscelencjo.”,
„. Ponadto otrzymujesz nagrodê”,
„akry ziemi wed³ug kolejnoœci”,
"Jesteœ pewny, ",
„bêdzie mi przykro straciæ twoj¹ us³ugê.”,
"Tak, jestem.",
„nie przyjmuje ³askawie”,
„Niewa¿ne.”,
„Bardzo dobrze. Ale mam nadziejê, ¿e z czasem siê zastanowisz ...”,
"Do widzenia, ",
„Huh?”
„Sir, widzia³em francusk¹ flotê w pobli¿u #sOxbay#!”,
„Rzeczywiœcie? Ile statków? I co oni robili?”,
„Umm… przepraszam, nie mogê powiedzieæ. Straszna burza odepchnê³a mnie, zanim zd¹¿y³em zbadaæ.”
„Burza, prawda?
„W porz¹dku, dam ci twoje dane. Mo¿e wtedy weŸmiesz mnie powa¿nie. Do widzenia, sir.”
„Có¿, Jego Wysokoœæ bêdzie ¿a³owa³, ¿e nie ma Sileharda w Wie¿y. Ale to by³o tak samo ostateczne. W rzeczywistoœci, mam przyjemnoœæ nagrodziæ ciê za tê us³ugê dla Wielkiej Brytanii z ogromn¹ sum¹ 200 000 z³otych.”,
„Jesteœ najhojniejszy, mój panie”.
"W rzeczy samej?",
„Rzeczywiœcie. Schwyta³em Sileharda; moi ludzie przyprowadzaj¹ go tutaj, jak mówimy”.
„Och, œwietnie! Jego Wysokoœæ bêdzie bardzo zadowolona. Tak bardzo siê cieszê, ¿e jestem pewien, ¿e osobiœcie upowa¿ni mnie do wyp³acenia ci ogromnej sumy 400 000 z³otych jako nagrody za tak¹ us³ugê!”,
„Hojna s³u¿ba przynosi hojne nagrody”,
„Jego Majestat uzna³ równie¿ za stosowne powierzyæ mi rz¹d gubernatora tej wyspy, wzywaj¹c mnie do przejœcia na emeryturê, ale zawsze chêtnie s³u¿ê Jego Królewskiej Moœci i Wielkiej Brytanii. Ale ja dygresjê. z Koron¹, daj¹c ci zadania i nagradzaj¹c twoj¹ s³u¿bê. ”,
„By³oby zaszczytem s³u¿yæ cz³owiekowi tak s³awnemu jak ty”.
„Jestem pewien, ¿e dobrze zrobisz, panie mój, ale obawiam siê, ¿e muszê byæ w drodze”.
"Pochlebiasz mi, ",
Teraz porozmawiajmy o twoim stanowisku. ¯a³osne dzia³ania Sileharda zmusi³y ciê do wrogoœci z naszym krajem;
„wie, ¿e to nie z twojej winy”.
„jest zatem gotów zabraæ ciê z powrotem do s³u¿by na poprzednim stanowisku. Witaj ponownie”,
„Twoja sprawnoœæ jest tak imponuj¹ca”,
„¿e kaza³ mi natychmiast przekazaæ ci List od Marki”.
"Dziêkujê panu.",
„Po pierwsze, chcia³bym podzieliæ siê pewnymi radosnymi wiadomoœciami - # sOxbay # jest bezp³atny. Pomog³eœ nam bardzo w naszym d¹¿eniu do zwyciêstwa. Dziêkujê.”,
"Twardy.",
„Reszta statków by³a zas³oniêta mg³¹”.
„zg³osi³, ¿e odda³”
„, który zosta³ umieszczony pod twoim rozkazem. Ale teraz nie masz takiego statku. Gdzie to jest?”,
„Er ...”,
„Czy starasz siê zachowaæ to dla siebie? A mo¿e sprzeda³eœ? Tak czy inaczej, ten statek jest w³asnoœci¹”,
". Zwrócisz mi go, albo z³apiesz inny statek tego samego typu. Nie wracaj tutaj, dopóki nie bêdziesz mia³",
„gotowy do przekazania mnie”,
„Bardzo dobrze, proszê pana.
"Dlaczego wci¹¿ tu jesteœ, ",
„? IdŸ i przynieœ mi”,
„Przepraszam, sir. By³em w³aœnie w drodze, ¿eby go zdobyæ.”,
};