string DLG_TEXT[49] = {
"Proszк, zostaw mnie w spokoju. Dobrze siк tu bawiк!",
"Ja tylko...",
"Gіuchy jesteњ? Powiedziaіem, їebyњ zostawiі mnie w spokoju. Wyjdџ albo zawoіam їoіnierzy, їeby przybili ciк do drzwi tawerny!",
"Hej!",
"Czego chcesz?",
"Nazywam siк ",
".",
"Nie obchodzi mnie, jak siк nazywasz. Przeszkadzasz mi. Potrzebujesz czegoњ? Jeњli nie, to znikaj.",
"Ja... Ja chcк pracowaж na statku!",
"Wygl№dam na kwatermistrza? Idџ do doku i pogadaj tam z ludџmi. Nie mieszam siк z hoіot№. Teraz spіywaj, ja siк tu dobrze bawiк!",
"Nie, proszк poczekaж! Nie interesuje mnie bycie marynarzem pokіadowym. Dlatego przychodzк do pana, kapitanie.",
"Rozumiem. Jakie stanowisko ciк interesuje?",
"Wielu mуwi, їe jestem doskonaіym nawigatorem.",
"Co ty powiesz? Trzeba byіo od razu tak mуwiж. Њwietnie siк skіada! Mojego nawigatora zabito w czasie szturmu na Speightstown i szukam nowego.\nJeњli postawisz mi kolejkк, moїesz uwaїaж siк za zatrudnionego!",
"(Do wіaњciciela tawerny)... Jeszcze kolejkк!",
"Nawigator musi mieж dokіadne mapy naszych tras...",
"Przepraszam, ale moїe omуwimy szczegуіy pуџniej? Na razie moїe pomoїe mi pan њwiкtowaж i opowie o swoim statku?",
"Њwietny pomysі! Za twoj№ now№ pracк! Hep... wiкcej rumu! Jutro rano idџ do portu i zapytaj o statek '",
".",
"Kiedy wypіywamy w morze?",
"W morze? Kiedy przypіynie statek z... hep... amunicj№. Tylko trzymaj jкzyk za zкbami na ten temat! Nikt nie moїe wiedzieж o tym statku!",
"Tak jest, sir!",
"To inna rozmowa! Przynieњ mi jeszcze kubek rumu! Hep... Dobra, czas iњж na statek... Co za zapadіa mieњcina, nawet jednego burdelu nie ma!",
"Sir! Jeszcze jedna kolejka i...",
"I co? Za twoje zdrowie, nawigatorze! To sso siaіeњ mi... hep... powiesieњ?",
"Їe bкdк tкskniі za moj№ cioteczk№. Mieszka niedaleko, w pobliїu murуw miasta...",
"Rozumiem. Siaіeњ siк z ni№... hep... Poїegnaж? Nic z tego! Prowadџ mnie na statek!",
"Na pewno bкdк tкskniі za jej cуrkami. Bкd№ z nich piкkne mіode damy po caіym tym czasie.",
"Czekaj. Eee... Moїe powinieneњ zіoїyж im wizytк... hep... Tak... hep... Choњmy zaraz!",
"Tak jest, sir!",
"Hep! Z drogi! Mуj przyjaciel i... hep... ja idziemy odwiedziж p-panie!",
"...",
"Na sso szekasz? Choњmy!",
"Idк!",
"Czekaj. Dzie idziemy? Widzк tylko dїunglк!",
"Ma pan racjк. Zatrzymajmy siк tu.",
"Czemu?",
"Їeby mуgі mi pan powiedzieж wszystko, co wie, o statku, ktуry wiezie amunicjк.",
"Co? Nie jesteњ nawigatorem, prawda? Jesteњ angielskim szpiegiem!",
"Gratulujк bystroњci.",
"Skandal! Oszust! Niczego siк ode mnie nie dowiesz i zadbam, їebyњ nikomu nie powiedziaі. Stawaj do walki, tchуrzu!",
"Kapitanie, proszк siк uspokoiж. Ledwo pan stoi, nie mуwi№c juї o walce.",
"Sіuchaj! Upiіeњ mnie celowo!",
"Powiedz mi wszystko, a ciк oszczкdzк. Skіam, a bкdк musiaі wyci№gn№ж z ciebie informacje innymi sposobami.",
"Oui, oui. Powiem ci. Barkentyna o nazwie 'Oiseau' ma przywieџж zapasy broni, їebyњmy mogli opanowaж caі№ wyspк. Podobno stoi w porcie na Martinique.\nKapitan 'Oiseau' czeka w doku na eskortк.",
"Barkentyna pozostanie w porcie do przybycia eskorty?",
"Oui. Tak s№dzк... Tylko tyle wiem...",
"Powiedziaіeњ mi, ile chciaіem wiedzieж. Moїesz iњж.",
"Dziкkujк za informacjк, kapitanie, ale teraz, niestety, bкdк musiaі pana zabiж.",

};