string DLG_TEXT[56] = {
"Tak?",
"Nie, nic.",
"Dzień dobry. Zdaje się, że ",
"Danielle",
" mówiła coś o mnie?",
"Tak, oczywiście, ",
". Nazywam się ",
". Można powiedzieć, że jestem starym przyjacielem ",
"Danielle",
".",
"W końcu przybyłeś.",
"Dowiedziałeś się, gdzie jest ",
"Raoul Rheims",
"?",
"Słyszałem, że oboje szukacie tej samej osoby.\nTak się składa, że wiem, gdzie go znaleźć.",
"Wiesz, gdzie jest ",
"Raoul Rheims",
"? Skąd?",
"Powiedzmy, że byliśmy kiedyś sąsiadami.",
"Możesz nas do niego zaprowadzić?",
"Oczywiście. W mgnieniu oka.",
"Doskonale...",
"Widzisz ten stół przy drzwiach? To jest ",
"Raoul Rheims",
". Radzę porozmawiać z nim, zanim zniknie... Teraz, jeśli wybaczysz, mam inne sprawy do załatwienia.",
"Coś mi mówi, że nie chcę wiedzieć, co kombinujesz. W każdym razie dziękuję za pomoc. Idź, porozmawiamy później.",
"Słyszałem o twoim związku.",
"Lepiej, żeby niektóre rzeczy pozostały prywatne. Powiedz, jak się dowiedziałeś, gdzie jest ",
"Raoul Rheims",
" i czemu postanowiłeś nam pomóc.",
"Szczerze mówiąc, nie chcę ci pomagać. Wspieram tylko ",
"Danielle",
" i pomagam jej w tej sprawie.",
"Rozumiem. Ale wciąż ciekawi mnie Rheims, jak go znalazłeś?",
"Jak sobie życzysz, ",
".",
"Dość tych poufałości. Nie wiem, czy można ci ufać.",
"Danielle",
" miała rację - jesteś zbyt podejrzliwy.",
"Co ",
"Danielle",
" myśli lub mówi, to jej sprawa. Ale muszę się dowiedzieć, skąd znasz człowieka, którego szukamy, i dlaczego pomagasz ",
"Danielle",
". Mów, bo zrobię ci krzywdę!",
"Dobrze, dobrze. Uspokój się. ",
"Raoul Rheims",
" jest mi dobrze znany - byliśmy kiedyś, jeśli można tak powiedzieć, sąsiadami. Jeśli chodzi o ",
"Danielle",
", postanowiłem jej pomóc, bo ona kiedyś pomogła mi w bardzo nieprzyjemnej sytuacji.",
"Przekonujące. Sprawdzę to. To gdzie według ciebie ",
"Raoul Rheims",
" się ukrywa?",
"Nie powiedziałem. Najpierw powinieneś porozmawiać z ",
"Danielle",
" - może nie zechce, byś z nami poszedł.",
"Dobrze, porozmawiam z nią.",

};