string DLG_TEXT[56] = {
"Tak?",
"Nie, nic.",
"Dzieс dobry. Zdaje siк, їe ",
"Danielle",
" mуwiіa coњ o mnie?",
"Tak, oczywiњcie, ",
". Nazywam siк ",
". Moїna powiedzieж, їe jestem starym przyjacielem ",
"Danielle",
".",
"W koсcu przybyіeњ.",
"Dowiedziaіeњ siк, gdzie jest ",
"Raoul Rheims",
"?",
"Sіyszaіem, їe oboje szukacie tej samej osoby.\nTak siк skіada, їe wiem, gdzie go znaleџж.",
"Wiesz, gdzie jest ",
"Raoul Rheims",
"? Sk№d?",
"Powiedzmy, їe byliњmy kiedyњ s№siadami.",
"Moїesz nas do niego zaprowadziж?",
"Oczywiњcie. W mgnieniu oka.",
"Doskonale...",
"Widzisz ten stуі przy drzwiach? To jest ",
"Raoul Rheims",
". Radzк porozmawiaж z nim, zanim zniknie... Teraz, jeњli wybaczysz, mam inne sprawy do zaіatwienia.",
"Coњ mi mуwi, їe nie chcк wiedzieж, co kombinujesz. W kaїdym razie dziкkujк za pomoc. Idџ, porozmawiamy pуџniej.",
"Sіyszaіem o twoim zwi№zku.",
"Lepiej, їeby niektуre rzeczy pozostaіy prywatne. Powiedz, jak siк dowiedziaіeњ, gdzie jest ",
"Raoul Rheims",
" i czemu postanowiіeњ nam pomуc.",
"Szczerze mуwi№c, nie chcк ci pomagaж. Wspieram tylko ",
"Danielle",
" i pomagam jej w tej sprawie.",
"Rozumiem. Ale wci№ї ciekawi mnie Rheims, jak go znalazіeњ?",
"Jak sobie їyczysz, ",
".",
"Doњж tych poufaіoњci. Nie wiem, czy moїna ci ufaж.",
"Danielle",
" miaіa racjк - jesteњ zbyt podejrzliwy.",
"Co ",
"Danielle",
" myњli lub mуwi, to jej sprawa. Ale muszк siк dowiedzieж, sk№d znasz czіowieka, ktуrego szukamy, i dlaczego pomagasz ",
"Danielle",
". Mуw, bo zrobiк ci krzywdк!",
"Dobrze, dobrze. Uspokуj siк. ",
"Raoul Rheims",
" jest mi dobrze znany - byliњmy kiedyњ, jeњli moїna tak powiedzieж, s№siadami. Jeњli chodzi o ",
"Danielle",
", postanowiіem jej pomуc, bo ona kiedyњ pomogіa mi w bardzo nieprzyjemnej sytuacji.",
"Przekonuj№ce. Sprawdzк to. To gdzie wedіug ciebie ",
"Raoul Rheims",
" siк ukrywa?",
"Nie powiedziaіem. Najpierw powinieneњ porozmawiaж z ",
"Danielle",
" - moїe nie zechce, byњ z nami poszedі.",
"Dobrze, porozmawiam z ni№.",

};