string DLG_TEXT[65] = {
"Get out of my house before I call my men!",
"...",
"Who are you, #ssir#, and why are you here? You have three seconds to answer before my men throw you into the street!",
"I'm here on business. I'm told you recently captured a ship carrying Indian figurines.",
"What is this?! You've killed my men! Who are you?",
"I'll ask the questions, and if you're smart, you'll answer. The cargo from that ship you captured - where is it now?",
"What do you want?",
"I'm interested in a pirate ship. I believe it belongs to your brotherhood.",
"Come in, captain, come in. You'll get no trouble from me - you'll find I'm a wiser man than my predecessor. What brings you here?",
"I'm interested in a pirate ship. I believe it belongs to your brotherhood.",
"And what ship would that be? Has its captain been a problem for you? If he's one of us, I swear I'll hang him myself - we don't need trouble around here.",
"You're a wise man. You'll live a long life, no doubt. Unfortunately, I don't yet know who was in command of the vessel in question. It was a black ship with red sails, and left the colony under cover of night.",
"A black ship with red sails? That ship has nothing to do with me or mine. We've been victims of those monsters ourselves.",
"Victims? How do you mean?",
"I mean this ship sunk one of my barques, and now three of my men have gone missing in the jungle.",
"The men on this black ship - do you know who they are?",
"I have no idea, but I wouldn't advise you to get mixed up with them.\n There's something unnatural about that vessel. Several of my men swear they heard children crying on it.",
"That is strange indeed. Any idea where they were headed?",
"I have a lot of ships, my friend. You'll have to narrow it down.",
"It was a black warship with red sails. What do you know about it?",
"You've run afoul of her, too, have you? I suppose if it's crossed you, you're no enemy of mine.",
"What are you talking about?",
"The black ship. It's not one of mine. In fact, she sank one of my barques, and three of my men were lost in the jungle.",
"So you have no idea who the men on this warship are?",
"No idea at all. I'm not even sure they're human, my friend. My men watched that ship as she departed, and they swear they heard the sound of children crying from its deck.",
"That is disturbing indeed. Any idea where they were headed?",
"This ship is nothing but trouble.",
"Just what is your interest in it, if I may ask?",
"The cargo is my only interest. Is it still intact?",
"I lost my own ship and all of my crew during the storm. I wouldn't be here speaking with you now if I hadn't been on the captured barque. \nAs it is, I barely escaped a French corvette, and wouldn't have managed that if I hadn't taken to shallow waters. \nThen this crazy lass who killed my bos'n shows up, looking for one of these cursed idols.",
"Do I look like a bartender? Then why tell me your problems? I'm only interested in the cargo.",
"Pay attention, #sgender#! I'm not speaking figuratively when I say those idols are cursed. Just a few hours ago, the ship carrying them was sunk.",
"Sunk? Then I'm wasting my time here. Goodbye.",
"You want to buy these idols? Then, let's talk. Frankly, I'll be happy to see them gone. They're trouble, and no mistake!",
"Then I'll assume you're in a bargaining mood. How much do you want for them?",
"I didn't say anything about buying them. Quite the contrary. You're going to give them to me as a gift.",
"You must understand, I have to find some way to pay for the loss of that sunken ship. Which means I'll need 10000 gold.",
"I never thought I'd pay so much for a bunch of useless trinkets - but here's your money.",
"For a handful of heathen idols? Name another price. And aim lower this time.",
"I have a better idea: Just give me what I want, and I'll go.",
"Fine, then. 8000 gold. But that's my final offer. Show me the money or I'll show you the door.",
"It's a deal.",
"Forget it. It's 10000 gold, or you'll never even see the idols.",
"You drive a hard bargain, but I don't have time to haggle. Here's your money.",
"I'd like to propose a simple solution to this problem: You give me the idols right now, and you keep your head.",
"That's bold talk for a #sgender# without an army. I can call my men any time I like.",
"Yes, well - you have a point there. How much did you say you wanted?",
"Call out to them, and you won't draw another breath!",
"Fine! These idols have brought me nothing but grief. Take them and get out!",
"A wise decision. It's best for both of us, really.",
"Killing me will do you no good. The idols are on my ship, under heavy guard. I doubt even you can capture them.",
"Thanks very much for telling me where to find them. And now, I'm afraid, you're a loose end that needs trimming!",
"I'd best be going now.",
"You're bluffing!",
"You think so? Then I'll just have to prove you wrong.",
"You're right. I was bluffing. And now I'm going.",
"Please, just go! I don't know anything!",
"Wrong answer. Try again, and this time think about how much you enjoy breathing.",
"Those idols! They've brought me nothing but trouble. First the storm, then the corvette, then that slip of a girl who killed my boss for one of them - and now they've brought you. Take the bloody things and be off!",
"A wise decision. It's best for both of us, really.",
"A very wise decision. And now I'll just make sure you're not around to tell anyone about our little transaction.",
"We've been keeping a log. They always seem to be headed to #sGreenford#.",
"I thank you for the information.",
"We've been keeping a log. They always seem to be headed to #sGreenford#.",
"I thank you for the information.",

};
