string DLG_TEXT[9] = {
"A simple box, half buried in the ground. Serves as obstruction and can be boobytrapped by means of a grenade.",
"That thing is just a useless nuisance. Boatswain! Clear this away. And put the planks into our store.",
"Just the place for a boobytrap. A grenade with a flintlock wired to the lid will be a nice surprise for any nosey guy. And hardly anyone will resist the temptation...",
"I'd better leave that thing alone...",
"Hey, you there in front of the keyboard! This is a building that YOU created, so how about creating your own dialog as well? Just use Notepad to open the file program\dialogs\ ",
" and overwrite this text with your own. Then follow the instructions in the comments.",
"Overwrite this with the dialogtext of the NPC.",
"Text of the player dialogoption link.l1 which ends the dialog.",
"Text of the player dialogoption link.l2 which leads to another exchange.",
};