string DLG_TEXT[22] = {
"Tell me, what are you doing on my ship?!",
"I'm here on business.",
"I'm here on behalf of the governor.",
"What? This isn't my ship?! Sorry - my mistake!",
"What, that dog who fancies himself a noble?",
"Yes, that's the dog I mean. He's ordered me to search your ship, as you're a suspect in a kidnapping.",
"Search my ship?! I'll have you keel-hauled, and you can search the hull for barnacles as we leave port!",
"You can try. But I feel it's only fair to tell you the fort's gun crews have orders not to let your ship out of the harbor.",
"I think not, ",
"Corentin Lucay",
"! The girl is mine! And no one is going to tell me what to do!",
"...",
"I'll kill you!",
"...",
"What business is that? You want me to escort your ship somewhere?",
"No. I'm looking into the fate of a certain girl...",
"What? That dog sent you to steal his hussy back?!",
"That's about the size of it.",
"I'll make you a friendly offer, landlubber, since you don't seem to know who you're dealing with. You leave your money, weapons, and clothes here on my ship, and I'll let you leave in one piece.",
"It's an intriguing proposition, but my blade and I have a counter-offer. En garde!",
"That's you again! Surely you didn't come here to be killed again?",
"Not at all. This time it'll be you who will visit the black waters of Styx.",

};
