string DLG_TEXT[52] = {
"Hmm, what's your problem, ",
"? Who is after your head?",
"What?",
"Hello. Who are you?",
"I'm ",
". And I'm in need of your help.",
"Sorry, I'm mistaken.",
"So, you are in need of my help again?",
"That's the pirate life...",
"Thank goodness, no. Such help is too expensive.",
"So you are in trouble with the pirates?",
"Indeed. I'd like to normalize the relations with my brothers of the coast.",
"Spain.",
"Portugal.",
"Holland.",
"France.",
"I just changed my mind.",
"Do you need to make peace with our community?",
"I'm afraid I don't understand.",
"Perhaps you'd be interested in my services?",
"I don't know, what do you have to offer?",
"I help people settle their problems.",
"Such as?",
"Well... Let's say, during your voyages, you partake of a few fat pirate ships. Before you know it, the whole pirate community is after your head, and life becomes difficult. If you come to me, I can help restore relations between you and pirates.\nOf course, this service does not come easily, and for me to arrange such things can cost a considerable amount. But you'll be able to visit pirate ports and towns and trade there again..",
"What guarantees do you provide that my 'relations' would be restored?",
"I'm the governor of #sTortuga#. My decisions are respected.",
"All right, I'd like to use your services.",
"That will cost ",
" gold.",
"Agreed.",
"Too much.",
"That will cost ",
" gold.",
"Agreed.",
"This is too much for me. Goodbye!",
"Deal. That will cost ",
" gold.",
"Agreed.",
"Too much.",
"That will cost ",
" gold.",
"Agreed.",
"Too much.",
"That will cost ",
" gold.",
"Agreed.",
"Too much.",
"Excuse me, you don't have enough gold. No deal.",
"Argh! Perhaps I'll return when I have more to offer.",
"You can set sail now. Everything will be settled as soon as possible.",
"Thank you. Take care.",
"That's not all.",

};