string DLG_TEXT[126] = {
"I'll report this cruelty to the government of ",
"! This is treachery!",
"Dirty rat! How dare you attack a ship under the flags of ", 
"?! The same flags I saw on your own masts!", 
"You attacked the ship of your allies. The government of ", 
" will not ignore this act!",
"Our forces are weak, therefore we made the decision to surrender. How do you intend to act in regard to me and my crew, captain?",
"We wait upon your nobleness and kindness. What will you do with me and my crew, captain?",
"Be prudent, ",
" will be sure to hunt you down.",
" gold from your trunk will serve me for my troubles, and your cargo hold is certainly not empty yet! Ha ha...",
"Flags... allies... treachery... aren't those words a bit too... potent?",
"Tomorrow I'll act in the service of another government. I don't care what you are talking about!",
"I have time to decide your fate. However, for now, I'd like to take ",
" gold from your trunk.",
"I'll cut you all down like pigs! That is my final decision!",
"Those who want to join me, I'll take as crewmembers. Others will be shut in my cargo hold while I decide their fate. The troublesome will serve as a forage for the sharks.",
"Cutthroats, my ",
" friends will not forgive you! You have incurred large troubles upon yourself.",
"My ",
" friends will certainly know about this. They are REALLY dangerous people, captain.",
"Let's be civilized about this, ",
"Do you want to live, Captain? Be my officer.",
"We can avoid unnecessary bloodshed if you voluntarily give me ",
" gold, while your crew lay down their arms.",
"Those of ",
" trusted me, and counted on my devotion. I'd rather die than put a black mark on my name!",
"Foolishness - the most dangerous and expensive vice. This is your choice.",
"I don't think I have much of a choice, and no one is waiting for me on dry land. I used to serve ",
", but now I serve to you.",
"And what can you do as an officer?",
"Hmm... I dislike your sly tongue... I'll think about it.",
"Are you satisfied, captain?",
"What do you think, captain?",
"Would such an officer be good enough for you, captain?",
"Maybe... Maybe... And how much do you want in return?",
"'Professionals' like you can be found for any amount in any port! I'm not interested.",
"What do you think about ",
"?",
"That is too expensive. Think about your situation a bit.",
"OK, accepted. Welcome aboard. Oh, and If you betray me, not even Davy Jones himself will be able to lengthen your life.",
"I'll think about it.",
"Well, maybe you'll agree to ",
"All right, but for this price you had better be worth it!",
"I understand my position, captain, but I'll lose my self-respect if I agree to a lesser price.",
"You won't regret your decision, captain. I guarantee it.",
"I hope...",
"GOLD!!! That's all you care about, captain?",
"Those who want to join me, let's say ",
" men, I'll spare. All others I'm afraid, will be left to their fates.",
"I hope...",
" gold?",
"I might let you and your men go...",
"All ",
" men can join me, if they wish. For you... I can offer the place of officer on my ship.",
" However, what will be of my crew?",
" What will be of my crew?",
" Do you guarantee a life for me and my crew?",
"Be lenient, captain. Here is your ",
" gold. I hope your word is worth it.",
"My word is harder than diamond. You are free... and, of course, your crew is as well. But I'll clean out a bit of your cargo hold first! Ha ha...",
"What are you talking about?! Which word!? I didn't promise you anything. Thank's for the money... and send my regards to Davy Jones!",
"Your sailors have been sent to Davy Jones' locker. You can join them, or join me.",
"Lying rat! I'll cut out your heart!",
"Better save yours...",
"I will repeat myself only once! Will you be my officer?",
"I respect that, and I am not going to be soiled by such a man as you...",
"As you wish... Hang him, men!",
"Such pathetic last words.",
"Spare the crew, captain! ",
" crew are not guilty of anything but being sailors. I'll accept your terms, if you let them live.",
"All right, all right... I'll let you go, and I'll leave your crew alive. But my crew will finish off loading first.",
"Would you serve as my officer? Your sailors will remain under your command. What say you?",
"Only ",
" men remained on my ship. What will you do with them?",
"No one remained on my ship. You are guilty of this!",
"Enough! ... Men! lock 'em in the brig! I'll see to his fate later...",
"I don't know what to do with you and your crew. Do you want to be my officer?",
"Very attractive offer. Well... I agree.",
"I hope I won't regret this...",
"With your pathetic abilities?! Don't make me laugh. I prefer to be a free captain.",
"Your ship fell to my 'pathetic abilities'... it seems you are the 'pathetic' one here... being a merciful man, I can offer you a position as an officer.",
"The Kraken awaits you...",
"I won't overrun my ship with cutthroats, and there won't be enough food for all the mouths.",
"You and your mad dogs deprived me more than half of crew. For you it means one thing... a short drop and a sudden stop.",
"I can't completely trust you yet. We'll see...",
"Your crew!? Please! They're my men already! And if you want to live, join me too.",
"Looks like there is no place for me in your squadron.",
"Maybe you'll serve as my officer?",
"Captain ",
", by your leave... It stinks of carrion here. Whether not from you?",
"For you I'm Captain ",
". And for your words I'll cut out your heart and feed it to the sharks.",
"Your jabber will not change your fate. En garde!!!",
"Baaahh... This is ",
". You are more like a filthy worm than a captain...",
"I will accept your crew of ",
"Thank you captain! They are a good crew. What will you do in regards to me?",
"Maybe you'll serve as my officer?",
"I could let you go... for the right price.",
"Such a shame to bloody that really nice suit. But, I think I'm gonna have to kill you now.",
" Do you want to be my companion?",
", isn't it? Pathetic to call yourself a captain! I'll be delighted to slit your throat!",
"Thanks for your visit, ",
". I'd like to introduce you to my blade...",
"Captain! ... ",
", isn't it? Measly little bug! I'll be delighted to slit your throat!",
" How do you intend to act in regard to me and my crew, ",
". Bloodspill is not needed. Otherwise, those I serve in ",
"Sparrow. You are just the dirty pirate I knew you to be.",
"But I captured your ship now, didn't I?",
"Don't flatter yourself, pirate. I only stopped firing in order not to damage HMS Interceptor and HMS Dauntless futher.",
"I think, if you review the situation, you will find that in fact, I just outmaneuvered you Commodore.",
"Next time we meet I shall look forward to seeing you hung, and watch you maneuver on the end of a rope, Sparrow.",
"Ha Ha! In the mean you may remember this as the day you almost caught Captain Jack Sparrow. For now you and your crew will repair to the Dauntless and I will bid you good day Commodore.",
"You sir have killed my leader, for this you shall DIE!",
"So ",
", You have caught up with me at last, what are you going to do with me now?",
"Men! lock him in the brig! I'll decide to give him back to England or to do something else with him later.",
"I am going to kill you. You traitor.",
"What can you offer me besides gold?",
"Well I can learn you some tricks maybe. What do you want to learn?",
"I would like to learn how to turn my ship quickly.",
"I would like to learn how to reload my cannons faster.",
"I would like to learn how to board ships easier.",
};
