string DLG_TEXT[24] = {
"What do you want? I prefer not to talk with strangers.",
"I can see that. If you want me to leave you alone - tell me where has Blythe has gone?",
"Nigel?",
"Yes. Don't pretend that you don't know him.",
"And what's that got to do with anything? Get lost!",
"That lad is working for me...",
"Working for you? He didn't say anything about working for anybody.",
"All right, he was working for me. Until one day he disappeared with one of my ships.",
"Heh-heh. What an unfortunate surprise...",
"Hey, I don't see anything funny in that! And laughing could become harmful for your health!",
"All right, all right.... Some might pay a lot to keep such an embarrassing secret quiet. '#spronoun1# ship was stolen from under #spronoun2# nose?' My, my, a secret like that is worth no less than five thousand gold, I should think.",
"How about I put a few grams of lead in your head?",
"Don't try to threaten me. Everybody knows you're the kind, tenderhearted type who helps widows and cripples. Heh-heh!",
"All right, all right, I agree.",
"Everything has its end, don't you know that?",
"Great. Now talk.",
"That's right, but...",
"No 'buts', you pig! I'm out of my patience already!",
"All right, all right. I'm talking now. So, you said - Nigel. He went to #sisland_Quebradas Costillas# to pick up his former crewmates.",
"What for?",
"He talked of his lost ship stuck on a shoal somewhere, but I didn't ask him for details.",
"I got it. Farewell.",
"I'm not in mood to talk with some weak-wristed mollycoddle.",
"And who do you think you're calling a 'weak-wristed mollycoddle'?",

};
