string DLG_TEXT[59] = {
".",
".",
"So, you are to help me retrieve our ancient skull?",
"I thought it was the other way round. But yes, we are going to find the skull.",
"I accompany you to your ship. There I stay until we arrive at Madinina.",
"Good idea. Some people might be scared of you.",
"Yes. So when we are at Madinina, we land at beach, not at town. If we land at town, people may attack us. Beach safer.",
"True enough. When we approach #sisland_Falaise de Fleur#, we'll go to the beach.",
"Follow me. The skull is on the other island. I know a way to get there.",
"Very well, lead on.",
"We go through here to bridge. Bridge very old. Be careful not to fall through holes.",
"How do you know the bridge hasn't been repaired?",
"Nobody live on other island. No need to repair bridge.",
"Maybe someone has moved there since your people left? They might have repaired it.",
"If no holes in bridge, be careful of people on other island.",
"Great. If the bridge isn't dangerous then the island is.",
"Walk near side of bridge, not in middle. Side strengthened by rope. Middle not strengthened by anything.",
"Yes, I can see. Some planks are broken in the middle. They're probably the ones I don't want to walk on.",
"Skull somewhere near here. I will find it. You keep watch.",
"Shouldn't I help search?",
"If you wish, but you will not find skull. I will find hiding place of skull.",
"Fair enough.",
"I have the crystal skull. We can return to my tribe on Karoukera now.",
"Very well, let's head back to the ship.",
"Remember, bridge weak. Stay to side.",
"Yes, I don't want to fall through one of the holes.",
"You have stolen the sacred skull from me. Now you will die!",
"You're not going to be able to sail home, you know. But if you want to fight, so be it!",
"Alright, ",
", give him the skull.",
"The amber skull is sacred to my people. I will not give it to this son of a snake!",
"Your people won't get it back if we're both dead. If we let him have the skull now, we can get it back later.",
"You are sure that you can take back the skull?",
"More sure than if we're buried under a ton of rock.",
"Your words are wise. Very well.",
"Now we trapped. Only way out is back to bridge.",
"And the jungle. I don't know what I'm going to eat, but you probably won't starve.",
"You refer to our custom of eating our enemies. You disapprove?",
"Yes. Cannibalism is the lowest form of savagery.",
"Hmm. We partners, so I not kill you. But jungle has other dangers.\nIf you die first, I definitely eat you. Question is, if I die first, what will you do? Bone appetite.",
"That's 'bon appetit'!",
"Why waste bones?",
"Very funny. But it won't come to that. ",
" didn't do a good job of demolishing this cave. I reckon that together we can push that boulder out of the way.",
"Then what? Enemy sail away with crystal skull.",
"Not necessarily. Cannons are expensive and he won't want to leave that one behind. Right now, his men will be working to get it back on his ship. If we get out, we can get back to ours.",
"Then what? Skull on his ship, we on your ship.",
"Then, my friend, we become pirates. Come on, let's shift that rock.",
"Captain, we found this in one of the enemy ship's chests. We overheard you talking to that Indian about some crystal skull and figured this might be it.",
"Thank you! Yes, that's it alright. Extra ration of rum all round!",
"Captain, the enemy ship sank in shallow water. We sent a diver down to look for anything valuable looking and he came up with this.",
"Then give the diver an extra ration of rum. For that matter, you can all have one for today's work.",
"Looks like we're stuck, captain. That rock is blocking our way out.",
"Yes, but I reckon we can move it. Help me, then we can get back to our ship before ",
" gets back to his.",
"This is not Karoukera. You do not bring ancient skull back to my people. Then I take it back from you!",
"I was forced to surrender the skull to an enemy. This #sperson# promised to get it back. #sPronoun1# then kept that promise. I allowed #spronoun2# to carry the skull back to you.",
"This is port. We should not be here. We should go to beach.",
"I know, but I have things to do here.",
}