string DLG_TEXT[98] = {
"I am told you went to great lengths to speak with me. My name is ",
". And now, will you please tell me the purpose of your visit, ",
".",
"My name is ",
".",
"Ah, it is you again? Why are you here this time?",
"I'd like to do a little business with you.",
"I'm terribly sorry, but I have more important things to do.",
"So, why do you come here and distract me from important affairs of state?",
"I'd like to talk to you about a small piece of business.",
"Just a polite visit, #saddr#, nothing more.",
"In that case, please leave my study and let me get back to my work.",
"Yes, of course. Sorry I disturbed you.",
"As the English say, I am all ears, ",
".",
"...",
"I wish to serve #sgov_nation#, your Excellency.",
"#sgov_nation# is always pleased to accept new captains into her service. ",
"We are",
"n't",
" currently at war with ",
"the ",
"any nation",
". Of course,",
" but",
" Pirates are always to be sunk on sight.",
"I'll make you proud, your Excellency.",
"How am I doing Sir?",
"You've sunk ",
" English ships, ",
" pirate ships, a total of ",
" ships.",
"Thank you.",
"I hope you have no qurrel with my service, #saddr#.",
"Indeed not, captain! In fact, it is my pleasure to award you a commision in His Most Catholic Majesty's Navy. As an officer you will be rewarded for each ship you sink in the service of #sgov_nation#.",
"I am honored, your Excellency, and will endeavor to live up to His Most Catholic Majesty's trust in me.",
"I'd like to pick up my wages, Sir.",
"Well, you've sunk ",
" Dutch ships, ",
" Pirate ships, So ",
" total ships. Your current wages are ",
", so a total of ",
"Thank you, Sir.",
"Traitorous scum! Sink your countrymen's ships, will you? You are hereby discharged from the military, your name struck from the roll; and I never want to see your face in this town again!",
"...",
" since last time, here's ",
" gold",
"I've heard I'm up for promotion.",
"You are indeed! Excellent work. Your new rank is ",
"Thank you, Sir.",
" Dutch ships, and ",
"Oh yes? I have a proposition for you, captain.",
"Indeed?",
"I have learned that you completed the task successfully; my congratulations, captain! Here is your reward.",
"My thanks; it was a pleasure to aid you.",
"You must destroy the ",
" vessel ",
"quest pirate",
" menacing the shipping off ",
". If you sink her, I will reward you the hefty sum of ",
" gold. What say you, captain?",
"You shall not hear of her again, that I promise.",
"I'm afraid I can't help you.",
"I crave forgiveness, your Excellency.",
"I'm interested to learn about #sgov_nation# relations with other nations.",
"I'm looking for a Letter of Marque.",
"Ah, ",
", so good of you to stop by. I'd like to introduce my ",
". She'll come in once we've finished business.",
"I can no longer serve ",
", your Excellency.",
"I'm through serving ",
"As insurance that you are an able captain, and to recompense my time in presenting your case to ",
", I must ask you for ",
"Not a chance.",
"Very well.",
" In light of your previous service, ",
" grants you the rank of ",
"You have harmed ",
", and ",
" does not forget his enemies. Leave at once, or the guards will toss you out on your ear!",
"You have caused ",
" great harm, captain, but ",
" is willing to overlook your past transgressions...for a price: ",
"Very well, Sir. I accept.",
"A pleasure dealing with you, ",
"And you, your Excellency.",
". In addition, you are awarded ",
" acres of land by order of ",
"Are you sure, ",
" will be sorry to lose your service.",
"Yes, I am.",
" does not take kindly to turncoats, ",
"Uh, never mind.",
"Very well. But I hope you will reconsider, in time...",
"Goodbye, ",
"Huh?",
"Tough.",

};
