string DLG_TEXT[22] = {
"Leave me alone, lad. You're bothering me.",
"...",
"Well, would you look at that! A shepherd takes up a sword and thinks it'll keep us from our feast!",
"So, it's you who's robbing the local ranchers?",
"Hey, it's the girl that killed our lads! Get her!",
"Good lord! How many of you are there?",
"Wait! I need to talk.",
"What do you need?",
"I'm told you recently became the owner of a certain girl. I'd like to buy her from you.",
"She's not for sale.",
"You showed up just in time. I was planning to get rid of her.",
"Then you're ready to sell. How about 5000 pieces of gold, and we call it a deal?",
"Sorry, that won't do.",
"I accept your offer!",
"All right. 5500 gold pieces. Take it or leave it.",
"I'll take it!",
"No. I don't think we'll be able to do business, after all.",
"That's very insightful. You're pretty smart for an oaf. Now...if you want to live, drop that rusty blade of yours and run!",
"Drop your swords before I cut them out of your hands!",
"Shut your mouth before I cut out your tongue!",
"I'll teach you some respect!",
"Just try it!",

};