string DLG_TEXT[47] = {
"Don't bother me while I'm working!",
"...",
"Do you have any orders for me, Captain?",
"No, not yet.",
"A new prisoner, heh-heh!",
"Why are you so happy about it?",
"Here is your weapon. Now, to get out of here, you have to kill all the soldiers on guard. There are two or three of them.",
"Thank you, I am in your debt. I'll meet you at the port.",
"Thanks for the sword...but I admit, I tend to bear a grudge. Do you remember you swore that I'd be hobbling on crutches till the end of my days? Well, now I am afraid that you are the one who will be hobbling about.",
"What do you need? I served as a gunner in the past, you know! So I'm not to be trifled with.",
"No need to get worked up. In fact, I'd like to hire you to work for me.",
"I am glad you managed to free yourself, captain. Is our agreement still in force?",
"Yes, how much do you want for your services?",
"No, I don't need your services.",
"Me? You are kidding, captain, aren't you?",
"Do I look like a frivolous fellow? How much do you want for your services?",
"Just 1500 gold per month, #ssir#, and I am completely at your service!",
"All right, consider yourself hired. Welcome to our crew.",
"I don't think that your services are worth that much money. Goodbye.",
"Don't you understand? A new prisoner means that our governor will give us some money for his keep, and I'll snatch a part of it, heh-heh.",
"How did you come to such a life?",
"A prisoner wants to chat? All right, let's chat...but I doubt you'll be so sociable for long. Soon you will just be sitting on your bed, staring at the ceiling like the others. I've seen a lot of prisoners in my life.",
"You haven't answered my question yet.",
"It's a long story...but what a hell...you've got plenty of time to kill, heh-heh, so why don't I tell you my story?",
"You're right. I've got plenty of time, so tell me all about it...",
"Don't interrupt me, or I'll show you something, heh-heh. You'll spend the rest of your life walking on crutches.",
"Watch your words! The fact that I happen to sit here in this prison cell doesn't mean that I'll endure the insults of my humble jailer!",
"You call me a humble jailer!? Just so you know, once I was the finest gunner in this whole damned archipelago!",
"Bah, do you think I believe that? Who would dismiss a first-class gunner from a ship?",
"I didn't think it could happen to me, either. All this misfortune, and it all because of the cursed rum. They turned me out, and didn't even pay me for my last half year of work.",
"Help me get out of here, and I'll hire you to work for me on my ship as a gunner. I'll put a stop to your drinking while we sail...but you can drink to your heart's content when you go ashore!",
"To put out to sea again? Damn! Don't torment me, cap!",
"I am not joking. Just open the door, give me my weapon back, and I'll get out of here and meet you at the port at my ship '",
"'.",
"No, I don't like the idea. Why should I risk my life?! Sit yourself down, pal, and I'll just go about my businesses.",
"Wait!",
"It's a deal, captain...but you'd better not be fooling me!",
"Don't worry, I keep my word.",
"...",
"Attwood, drunk again...",
"Captain, I thought we had an agreement - what I do on shore is my own business. I'm not getting drunk on the ship, so there's nothing for you to worry about.",
"And you got yourself in a fight again.",
"It's not just some fight, cap! It's a matter of honor. That guy called me a son of a jackal and a land-rat.",
"No arguing! Get on the ship!",
"A matter of honor? No one dares to insult my officers. En garde, scum.",
"I thought you were a good #sgender#, cap...",
"...",

};