string DLG_TEXT[55] = {
"Why are you here?",
"I'm just looking around. I shall leave now.",
"Tell that admiral of yours in #sRedmond# that I am still waiting for the weapons he promised. And tell him that El Supremo does not like to be kept waiting!",
"Certainly. If I find an admiral in #sRedmond#, I shall ask about your weapons.",
"Human beings do not address me as 'Señor'! And those are not the amounts I was promised! Where are the rest?",
"Err...",
"You sold them, didn't you? Or you lost them? It does not matter. You failed to deliver them. And for failing El Supremo, there is only one penalty!",
"You should know that if I do not return to my ship, she will turn her guns on this fort and level it.",
"And you should know that I know the history of this place. Your navy tried to 'level it' once before, with a bigger ship than yours, and failed.",
" Indeed, I believe that you were there. Or have you forgotten?",
"Oh.",
" at your service. King George of England charges me with messages of his friendship.",
"I am not interested in the words of a mere king.",
"Ahem.",
"Have you brought me the guns and powder for my conquest of #sisland_Cuba#?",
" muskets, ",
" barrels of powder, and cannons for your fortress, Señor.",
"Human beings do not address me as 'Señor'! Make arrangements with Admiral Hernandez for landing your cargo.",
"I can hand over nothing until my ship is reprovisioned.",
"I have given you an order! Perhaps outside, you saw various criminals suffering punishment. They too disobeyed me.",
"If I am not back aboard the '",
"' in one hour, she'll train her guns on your fort and reduce it to rubble.",
"With you in it, Captain?",
"That is my order.",
"Such earthly matters are beneath me. We are allies, are we not? Make known your needs to Admiral Hernandez.",
"When you have landed my weapons, I intend to move on #sSantiago# and burn it. Perhaps you will accompany me?",
"My orders are to blockade #sIsla Muelle#.",
"It is your loss. A burning town is a magnificent sight!",
"You are in luck, ",
". This scum, who enters without knocking, brings news of a visitor from #sHavana#.",
"An ally?",
"I hardly think so.\nThree months ago the Spanish viceroy sent a diplomat who warned me to curb my political ambitions. In answer, I sent part of him back to #sHavana#. His head, to be precise.",
"Then the Spanish already know of your plan.",
"This visitor comes armed, to destroy my city. She is a Spanish warship of 60 guns, the 'Natividad'.",
"A Spanish ship of the line in these waters? When does she arrive?",
"According to this wretch, before dawn.",
"I must take measures to prepare my ship. See that my provisions are sent out immediately.",
"#srank#! You will not destroy the 'Natividad'. You will capture her and turn her over to me.",
"If I capture the 'Natividad', she will be a prize belonging to my king.",
"Your king would not wish you to offend me! You are charged with a mission, ",
". To aid me in my conquest of #sisland_Cuba#. If I fail, England fails.",
"I cannot surrender a British prize ship without authority from the Admiralty.",
"Think, ",
", think! With two ships, we could crush all the Spanish in the Caribbean!\nThere are 10000 troops in #sIsla Muelle# whom you could blockade while I destroy #sSantiago# and #sHavana#.\nYou would be helping your country's cause.",
"Before I can turn the 'Natividad' over to you, Señor, I must first capture her! Now you must excuse me.",
"You will remember in future, ",
", that the correct signal for El Supremo is 23 guns.",
"Our king himself receives only 21.",
"That is why I always have 23. I have noticed before, ",
", that you have shown a little disrespect, but I have been mild enough to attribute it to your foreign breeding.",
"You did not kill many.",
"I didn't want to deprive you of your crew, Supremo.",
"I shall kill the officers then, and replace them with my own. Where are they?",
"I greatly regret that I threw them overboard this morning. With their hands and feet tied, of course.",
"That is a pity. I was looking forward to making an example of them, in case any of these wretches hesitated to serve me. But there are other ways.\nWe sail tonight! You will proceed east to blockade #sIsla Muelle#. I shall take care of the west.",
}