string DLG_TEXT[76] = { 
"Apparently you care very much for the affairs in Europe. I am pleased to see that. My name is ",
" and I am special emissary to ",
".",
"My name is ",
".",
"Ah, it's you again. What brings you here this time? ",
"I'd like to talk to you about some business.",
"I'm sorry, but there are things that I have to do.",
"Being the only official in the Caribbean to my nation demands a lot of time. What brings you to me that is so important?",
"I'd like to talk to you about a small piece of business.",
"I'm just here to pay my respects, #saddr#. Nothing more.",
"In that case, please leave my study and let me get back to more important matters.",
"Yes, of course. Sorry I disturbed you.",
"I'm sorry, but I don't have anything to talk about right now",
"Oh yes? I have a proposition for you, captain.",
"Indeed?",
"I have learned that you completed the task successfully; my congratulations, captain! Here is your reward.",
"My thanks; It was a pleasure to aid you.",
"You must destroy the ",
" vessel ",
"quest pirate",
" menacing the shipping off ",
". If you sink her, I will reward you the hefty sum of ",
" gold. What say you, captain?",
"You shall not hear of her again, that I promise.",
"I'm afraid I can't help you.",
"I crave forgiveness, your Excellency.",
"I'm interested to learn about #sgov_nation# relations with other nations.",
"I'm looking for a Letter of Marque.",
"I've heard I'm up for promotion.",
"I can no longer serve ",
", your Excellency.",
"I'm through serving ",
"As insurance that you are an able captain, and to recompense my time in presenting your case to ",
", I must ask you for ",
" gold.",
"Not a chance.",
"Very well.",
"#sgov_nation# is always pleased to accept new captains into her service. ",
"We are currently at war with ",
"",
"no great power, but ",
". Of course, ",
"Pirates are always to be sunk on sight.",
" In light of your previous service, ",
" grants you the rank of ",
"I'll make you proud, your Excellency.",
"You have harmed ",
", and ",
" does not forget his enemies. Leave at once, or the guards will toss you out on your ear!",
"...",
"You have caused ",
" great harm, captain, but ",
" is willing to overlook your past transgressions... for a price: ",
"Very well, Sir. I accept.",
"A pleasure dealing with you, ",
"And you, your Excellency.",
"You are indeed! Excellent work. Your new rank is ",
". In addition, you are awarded ",
" acres of land by order of ",
"Thank you, Sir.",
"Are you sure, ",
" will be sorry to lose your service.",
"Yes, I am.",
" does not take kindly to turncoats, ",
"Uh, never mind.",
"Very well. But I hope you will reconsider, in time...",
"Goodbye, ",
"Huh?",
"Tough.",
"What are your orders, #saddr#?",
"I must manage this colony.",
"Do you know about some hostilities on near waters, #saddr#?",
"There are things I have to do.",

};
