string DLG_TEXT[23] = { 
"Help! Help! They're gonna string me up, please help!",
"Aah! Please help me, #ssir#! Get these bastards away from me!",
"Please, #ssir#, have mercy and help me escape from these brigands! I beg you!",
"What's going on here?",
"What's this business about?",
"What's the trouble?",
"I used to run in a gang with them... But I've seen the error of my ways and want to live an honest life I can be proud of. But those bastards would rather see me dead than free!",
"These bandits... I was once a thief, but I have found faith and just want to settle down and live an honest life. I tried to sneak off, but they saw me and now they will drag me back and torture me! Please, help me!",
"In the name of God, #ssir#, you have to help me! I want to leave this life of crime, but now my former 'friends' will stop at nothing to make me suffer, to make an example out of me!",
"Ahh, now I understand.",
"Sincerely, #ssir2#, I cannot thank you enough for your help!",
"Honesty prevails! Thank you so much for helping me get out of this wicked life, I'll never forget what you've done for me today.",
"Thank God you were here! I would never have expected someone to step up for a stranger like that. It is good to know there are still kind and valiant souls in this world.",
"One redeemed soul is worth ten of these cretins.",
"I got this #sgem# during my very first job and kept it as a memento. But I want to leave that life behind, so I'd like you to have it.",
"Thanks. Make sure you stay away from that kind of life from now on.",
"I'll tell everyone what you have done for me today! They'll know what a brave and kind #sgentleman# you are.",
"Thank you. May you have good fortune in the future.",
"These used to be the tools of my 'trade', but I shall not be needing them any more. Perhaps you can put them to better use, or just get rid of them.",
"Thanks. Hopefully you will find a true trade and acquire some honest tools.",
"Hey, you're ",
", aren't you? I've heard nothing but good about you, and what you did here proves it. Perhaps there is a way I can repay you.",
"What have you in mind?",
};