string DLG_TEXT[306] = { 
"Greetings, stranger, take my humble advice.",
"Yes, with pleasure.",
"I don't need your advice.",
"Greetings, wayfarer. Where are you going?",
"Oh, just off on my own affairs.",
"It's none of your business.",
"Good day, stranger. How are you doing?",
"Fine, thank you.",
"I've got no time to talk to you.",
"Hello. I haven't seen you here before. Are you a sailor?",
"Yes, I've just moored here.",
"I've got no time to talk to you.",
"Greetings, foreigner. It's good to see you here.",
"Hello.",
"Excuse me, but I can't talk to you right now.",
"Greetings, sailor. Do you want to hear good advice?",
"Good day. Speak out.",
"I've got no time to waste.",
"Good day, stranger. I've got some goods you may be interested in.",
"So let's bargain.",
"I've got no time to talk to you.",
"Good day, stranger. Does your crew keep getting hurt in nasty, yet lucrative 'accidents'? I can offer you a simple bandage to stop their bleeding at the bargain price of 120 gold a piece!",
"Indeed I can't afford to lose my crew. I'll take it! And I'll be sure to talk to you again if I need more.",
"120 gold, eh? I think I've seen 'em cheaper at the store in town. And THAT is where I'll get them from if I need them!",
"Good day, sailor. I'm in reduced circumstances, won't you help me?",
"Hmm, why should I...",
"That's your problem.",
"Sir, won't you help a poor sufferer with a couple coins?",
"Of course, the Church teaches us to help our neighbor.",
"Walk away, poor man, and don't bother me any more.",
"My sir, don't leave me in such poverty! Spare me a coin, please, so I can buy food.",
"Don't worry, my poor fellow. Here are 10 coins for you.",
"Walk away, poor man, and don't try to ask any more.",
"Good day. As I see you're a bold fellow, obviously you are fighting a lot?",
"Yes, of course.",
"That's my business. Goodbye.",
"Greetings. Not often do I encounter such respectable persons here. You must be a captain?",
"Yes, what can I do for you?",
"You know I'm in hurry. Goodbye.",
"Good day. You are walking here without any pressing business?",
"Generally, yes. I'll be glad to talk to you.",
"No, I'm busy.",
"Be warned that even the towns aren't safe from crime anymore these days. The godfather of Archipelago, the notourious Nathan Kell, has organized mobs of thugs and robbers that rule the streets. So be careful if you walk around in town, anyone carrying a weapon may assault you, even if he looks like a honest citizen at first sight.",
"Thank you for your advice.",
"Many dangerous thugs haunt the streets nowadays. Watch the passer-bys carefully: anyone carrying a weapon may be a criminal. If you want to avoid them stay clear of the main streets.",
"I'd rather fight them.",
"I'm not interested in this kind of advice. Goodbye.",
"If you have to fight them try to single out some of them and lure them away from their comrades so that they don't overwhelm you with superior numbers. Or take position in a narrow passageway where your flanks are protected. And try to engage enemies which carry guns in a swordfight before they have a chance to fire at you.",
"All right, I'll remember.",
"Traveling by foot has become really dangerous recently. There are a lot of privateers who are so short of cash that they rob travellers. Even in towns you aren't safe anymore. Many people nowadays are being killed in their homes or in backalleys where the guards do not patrol, and if it is no local citizen but a traveller like you and me nobody is really eager to catch the murderer. But after every murder the guards become very vigilant for some time and clear the streets of all those petty criminals.",
"Yes, and besides that?",
"I've got no time to talk to you.",
"Many travellers that look like vagabonds or beggars are in reality wealthy merchants carrying a lot of money. They disguise themselves as poor people because rich travelers are frequently being robbed.",
"Thank you.",
"The townguards are nothing but a bunch of idlers and corrupt cowards. Only the worst scum of the European armies volunteers for service in these godforsaken colonies. They usually turn a blind eye if there is a fight, they only interfere if some influential citizen is being attacked. But if they feel threatened they strike back in blind fear, and attack anyone wielding a blade, often confusing friend and foe in their panic.",
"Very interesting, thanks.",
"Smuggling is a blooming business here, and many caves and vaults are being used by smugglers as hideout and for storing contraband. Be careful, they do not like uninvited visitors. But occasionally you may also run into unarmed civilians in those hideouts, usually townfolk trading with the smugglers. Though killing unarmed people is never a good thing to do, no one will blame you if one of these traders is killed in a fight. However, be on your guard; they may sometimes turn against you and grab a weapon...especially if you've, err, returned from far away and continued where you left off.", // ccc apr15 NK 4-24
"Allright, I'll take care to hit only those who draw a blade on me. Don't want some collateral damage to tarnish my reputation, eh?", // ccc apr15
"Be careful when you walk into a tavern and keep your hand on your sword's hilt. Many sailors get rowdy when drunk, and you may well run into a fight. And should you get into a tavernbrawl take advantage of the tables and benches to protect your flanks.",
"Good advice, thank you.",
"These islands were once the realm of the savage Alkellani tribesmen. But by now settlers from America have taken the fertile land away from the Alkellani, and the few natives that are still alive live in scattered jungle hideouts on the brink of starvation. They have strange customs, these savages: the men tend the houses, while the women do the hunting at night. And they use to wear dreadful masks and wargarments made of dried human skin.",
"Like amazones, eh? It might be interesting to meet them....",
"If you will give me twenty coins, I will tell everyone how kind you are. Don't be concerned that I'm poor. I've many friends, and they will always be glad to see you here.",
"Waste money just for some beggar to talk around about me? Well, no thanks.",
"Yes? All right, twenty gold is not so much to give to a man in such need.",
"I'm grateful for what you have done. I offer you such thanks as I have. Drink this magical remedy now - it will restore you to full health.",
"Thank you, too.",
"Thank you. I've little to show my gratitude, but at least take this item. Maybe you will find a good use for it.",
"I will take it with pleasure.",
"Thank you, good man.",
"Don't mention it.",
"Captain, will you take me aboard your ship? I've long dreamed of exciting naval battles and long ocean voyages.",
"Of course. You will be my officer.",
"No, I don't need fresh sailors.",
"Pay me, and I will show you a couple of tricks to beat anyone in a hand-to-hand fight. Or would you like to learn some defensive moves?",
"I don't need your advice. I know this all very well, and can even teach you.",
"Show me your offensive moves.", // ccc oct06
"I don't need your advice. I know this all very well, and can even teach you.",
"Show me your defensive moves.", // ccc oct06
"Thank you, but I don't need any help just now.",
"Some time ago I was a sailor, too...a famous adventurer. I can tell you a lot about managing the crew on your ship.",
"I don't need your advice. I know this all very well, and can even teach you.",
"Yes, I'd like to know more about it.",
"Thank you, but I don't need any help just now.",
"I'm a sailor, too...a navigator. For a few coins, I will share my secrets that will help you better guide your ship.",
"I don't need your advice. I know this all very well, and can even teach you.",
"Yes, I'd like to know more about maneuvering.",
"Thank you, but I don't need any help just now.",
"I'm a gunner on a British warship. With great pleasure, I can teach you to calculate the trajectory of a cannon ball, and to hit your target every time.",
"I don't need your advice. I know this all very well, and can even teach you.",
"Tell me, and I will pay as much as you ask.",
"Thank you, but I don't need any help just now.",
"I'm a gunner on a British warship. I can tell you how to reduce your cannons' reload time.",
"I don't need your advice. I know this all very well, and can even teach you.",
"Tell me, and I will pay as much as you ask.",
"Thank you, but I don't need any help just now.",
"I'm a gunner on a British warship. I can tell you many stories about the art of grappling.",
"I don't need your advice. I know this all very well, and can even teach you.",
"Tell me, and I will pay as much as you ask.",
"Thank you, but I don't need any help just now.",
"I'm working in the shipyard, and I know all about repairing and building ships. If you'll pay me, I will teach your crew to repair the ship faster.",
"I don't need your advice. I know this all very well, and can even teach you.",
"Tell me, and I will pay as much as you ask.",
"Thank you, but I don't need any help just now.",
"I'm a trader. I can tell you some commercial tricks that will help you increase your profits from all your transactions.",
"I don't need your advice. I know this all very well, and can even teach you.",
"Tell me, and I will pay as much as you ask.",
"Thank you, but I don't need any help just now.",
"So, are you ready to pay me ",
"?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
" for my secrets of fencing?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
"?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
" for the secrets of defence?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
"?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
" for my lessons in crew management?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
"?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
" for my secrets of maneuvering?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
"?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
" for lessons about cannon accuracy?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
"?", 
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
" for the secrets of cannons reloading?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
"?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
" for advice about grappling?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
"?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
" for my secrets of repair?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
"?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
" for advice in commerce?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"Thank you, you are so kind.",
"Don't mention it.",
"Injuries? Terrible bleeding? I've got more bandages if you need them! Just give the word.",
"It seems my salty seadogs just CAN'T take proper care of themselves. I'll take another!",
"And the word is NO. I'll be going now.",
"So you want to bargain?",
"Yes, I'd like to purchase something.",
"No, excuse me for interrupting.",
"What do you want? I thought we had covered it all.",
"No, nothing.",
"What orders, captain.",
"Nothing.",
"Do you want to hear some advice?",
"Yes, I'm interested in hearing what you have to say.",
"No, excuse me for interrupting.",
"Be warned that even the towns aren't safe from crime anymore these days. The godfather of Archipelago, the notourious Nathan Kell, has organized mobs of thugs and robbers that rule the streets. So be careful if you walk around in town, anyone carrying a weapon may assault you, even if he looks like a honest citizen at first sight.",
"Thank you for your advice.",
"Many dangerous thugs haunt the streets nowadays. Watch the passer-bys carefully: anyone carrying a weapon may be a criminal. If you want to avoid them stay clear of the main streets.",
"I'd rather fight them.",
"I'm not interested in this kind of advice. Goodbye.",
"If you have to fight streetcriminals try to single out some of them and lure them away from their comrades so that they don't overwhelm you with superior numbers. Or take position in a narrow passageway where your flanks are protected. And try to engage enemies which carry guns in a swordfight before they have a chance to fire at you.",
"And besides...",
"I've got no time to talk to you.",
"The townguards are nothing but a bunch of idlers and corrupt cowards. Only the worst scum of the European armies volunteers for service in these godforsaken colonies. They usually turn a blind eye if there is a fight, they only interfere if some influential citizen is being attacked. But if they feel threatened they strike back in blind fear, and attack anyone wielding a blade, often confusing friend and foe in their panic.",
"Looks like I can expect no protection from them.",
"Smuggling is a blooming business here, and many caves and vaults are being used by smugglers as hideout and for storing contraband. Be careful, they do not like uninvited visitors. But occasionally you may also run into unarmed civilians in those hideouts, usually townfolk trading with the smugglers. Take care not to hurt them, cause killing unarmed people always damages your reputation, no matter where this happens.", // ccc apr15
"Allright, I'll take care to hit only those who draw a blade on me. Don't want some collateral damage to tarnish my reputation, eh?", // ccc apr15
"If you have trouble with the law for some reason you just have to hide at some quiet location for some time. The authorities usually calm down quickly here in the tropics, and there are so many criminals here that the guards soon won't remember your face anymore.",
"Good advice. Thank you.",
"These islands were once the realm of the savage Alkellani tribesmen. But by now settlers from America have taken the fertile land away from the Alkellani, and the few natives that are still alive live in scattered jungle hideouts on the brink of starvation. They have strange customs, these savages: the men tend the houses, while the women do the hunting at night. And they use to wear dreadful masks and wargarments made of dried human skin.",
"Like amazones, eh? It might be interesting to meet them....",
"229",
"Sorry, I know nothing about shipping, and I never talk to sailors. They are such a rowdy lot.",
" Whatever it is, I am innocent! And all my relatives will swear that I was with them when it happened.",
"Oops, you! Nnn... COUGH nice to meet you again...",
"Oh, YOU again! Eh, ehem... I'm terribly busy, gotta go...",
"Stop! You won't go anywhere! You stole my money, and the guards will take care of you!",
"You dirty thief, I'll have you arrested right here!",
"You will go only to prison from here, you pickpocket!",
"Listen, if you run you'll run into trouble, but if you give me my #smoney# gold back I'll forget everything.",
"Be a sensible fellow, let's strike a deal: you can keep my money, I don't care much for gold. But give me the diamondring back, it's a present from my wife.",
"Careful! You are in mortal danger! My purse is a Thiefbuster TM thievetrap with a poisoned lancet inside!",
"You thief, Ill slash your throat right away!",
"I'll cut your thievish fingers off with this very cutlass!",
"Have I told you that this ancient sword was once used to amputate the hands of pickpockets? Shall we try if it is still sharp enough for that?",
"Ha, you will achieve nothing here with such blatant methods. You have no real proof against me, and I have good connections to the authorities. Piss off, sucker!",
"Allright, so Ill have to get my money back by other means. Maybe I should kill you right on the spot... But maybe I'd better wait till I catch you alone...",
"WHAT? Oh no, in your purse were only... AARRGH, you caught me off guard. I am getting too old for this business, I'd better change my profession and become an honest beggar. Will you help me start a new life and not denounce me? Here is your money back.",
"Allright. I wish you more success in your new branch of business. Goodbye.",
"Well, keep some Gold to get your enterprise started. It's okay, no need to thank me. Farewell.",
"Hey, hold it! Calm down, don't do something rash! Here is your money back, and if you leave me alone I'll give you this beautiful piece of jewelry. Isn't it a masterpiece? How about it?",
"It's surely a STOLEN masterpiece, eh? No, I won't touch such a hot item. Listen, I'll leave you alone if you take this back to it's legitimate owner. And don't you try to fool me! You may go now.",
"Hmm... suddenly so submissive and generous? Or are you trying too corrupt me with stolen jewels? Forget it, keep that hot stuff, I just want MY money back.",
"Beautiful... and booty, right? You are trying to turn me into a receiver, eh? No, I won't sink so low, I only reclaim my legitimate possessions.",
"Oh, really beautiful! GIMME THAT! And get lost now.",
"I'd better not ask you how you got this. Who cares? Thank's a lot, goodbye.",
"Shhh, don't show that stuff off here on the street. Pass the bucks, and the stone, but discreetly, please!",
" ( The edge of a well filled purse peeps out of the pocket of your new acquaintance )",
" Hey, your purse is about to fall out of your pocket. Be more careful with it. ",
" ( Slowly, very, very slowly do you move your hand into the pocket and grab the purse )",
" ( Faster than a lightning do you snatch the purse and run away )",
" ( You look into another direction with emphasis, make an innocent face, whistle a tune and grab the purse without looking at it )",
" ( You pretend to stumble, grab your victims coat for a hold and shake the purse out of the pocket. )",
" ( You 'accidently' drop your inventory on the floor, and as your victim helps you pick up your gear you take the purse. )",
" ( You ask your victim if the guy behind it is the notorious Blackbeard. As your horrified victim whirls around you grab the purse )",
" ( You got the purse! It bears a label: Thiefbuster TM )",
" AARGH!! Thiefbuster TM purses are boobytrapped with poisoned lancets or explosives! I'd better throw this deathmachine away!",
" Bah! Some copycat put that label on this simple purse to scare thieves away. I'll open it! No risk no gain!",
"WHAT? And I have already passed it on to... Blast, you got me! But you will not get your purse back if you bugger me any longer, believe me, cause i don't have it anymore. I work in a team of pickpockets. I am the grabber, true, but I immediately pass the loot on to a runner so that I won't be nailed if I am being caught and searched. And if what you say about the content of your purse is true we will never see my runner again. So it won't help you if you rouse a rabble here, be a reasonable fellow, if you let me of the hook I'll give you this jewelry as compensation.",
"No, I insist on justice being done. Maybe you are lying and you still have my money. I'll have you arrested right here!",
"Well, sending you to prison will surely not cover my losses, but that gem possibly will. Pass it and piss off. And be quick about it before I change my mind and fetch my money back with my blade!",
"269",
"I'd rather talk about maritime affairs. As frequent traveller you surely know a lot about that, don't you? Are there any merchants plying the coastal traderoutes? Or pirates harassing them?",
"I am more interested in the latest news about the local shipping. Have you heard of any pirateships or merchants in the vicinity lately?",
"I am only concerned about the local shipping. You surely talk to a lot of sailors here, eh? Have they reported any strange sails lately?",
"Now that you ask, yes, there are some. Be careful that you don't bump into them, hehe. Very dangerous at sea, you know, I prefer to stay ashore. I always say that if the Lord had wanted us to roam the seas he would have given us fins and gills, eh? Hehe.",
"Oh, I myself have sighted a few sails while walking on the cliffs. But it was to hazy to identify them exactly. You know, one ship looks like the other to me.",
"Why, of course are there the usual taverntales of sailors who claim that they have just by a hair's breadth escaped a terrible pirate lurking right at the portentrance. But I don't care for such drunken talk, I am more concerned about all the thiefs and thugs lurking ashore. You wouldn't believe how many privateers try to sneak into this town!",
"Oh, well, thanks for this very enlightening piece of intelligence. Perhaps should I do some more detailed recconnaissance myself.",
"Allright, allright. I'll scout the coastal waters myself. Sorry for having disturbed you.",
"You are a hopeless landlubber, eh? Well, carry on kicking dust! Let us mariners take care of the waters.",
"Good day Captain! It's a lucky day for you!",
"What do mean?",
"Don't disturb me if you don't want I cut your throat mate.",
"I have a secret to sell! Do you want to become a rich man?",
"What are you talking about? Speak on!",
"Listen! A dying old pirate told me where he and his companions hid a treasure stolen from the Spanish! The only thing you need to become a rich man are a good ship and food for the trip.",
"And why don't you go yourself to take the treasure for you?",
"Because I can't leave this cursed island and I have no ship! All the pirates have disappeared now but this treasure has a great value!",
" it is composed of gold, jewels, emeralds and indian gold idols! Are you interested or not, captain?",
"And how much do you want for this secret?",
" gold",
"Here's the money. Tell me where to find the treasure. I hope that your story is true. Otherwise I'll come back here to kill you!",
"No, it's too much.",
"Wait a second, then ask me again. I must straighten my collar...",
"OK.",
"Hmm... I have seen you before... during a ship skirmish some time ago, on a quarterdeck I think... HEY, you are the devious bastard who sailed close to our ship. We thought you were friendly right up to the moment you opened your gun-ports, fired into our ship, then boarded us and slaughtered our crew! ALARM! A pirate in disguise!",
" Should have killed ALL witnesses of my piratical past...",
"296",
"Psst... hey, I have something here you may be interested in.",
"Uhm, sure, show me what you got.",
"No, I don't think so.",
"Sorry ",
"lad",
"lass",
", but my offer was once in a lifetime. Now get lost before I run you through!",
"...",
"gold back, I'll forget everything.",

};
