string DLG_TEXT[33] = {
"Ah, a customer for our new store. I have only recently taken over this shop, after the last owner was killed by robbers. They have become a real nuisance lately.. What can I do for you, ",
"Welcome to my new store, #ssir#. I have inherited it from my cousin, who was found here a few days ago, a bullet in his head and no money in the cashbox anymore. Happens a lot lately.. What is your desire?",
"Welcome, #ssir#. What brings you to to my new store? Errr.. you are not another mugger, are you? .. Of course not, excuse my skittishness, but my predecessor as owner of this store was slain only recently...",
"Dear me, merchant seems to be a rather dangerous profession! Thanks heaven that I have a more secure job.. Never mind, I'd like to have a look at your wares.",
"Hmmm, maybe I should better not jingle with my gold in such a dangerous place.. ",
"What can I do for you, ",
"What is your desire?",
"What brings you here?",
"I'd like to have a look at your wares.",
"Just passing by...",
"So what do you need, cargo or... Hey, what's that noise... Oh no, another robbery! Oh please, help me! Here, I give you ",
" Gold...",
" Can't get out of here without a fight anyway, eh? But thank you nevertheless.",
"So what do you need, cargo or personal items?",
"Cargo please.",
"Let's get personal.",
"DLG_TEXT[16]",
"DLG_TEXT[17]",
"DLG_TEXT[18]",
"DLG_TEXT[19]",
"DLG_TEXT[20]",
"DLG_TEXT[21]",
"DLG_TEXT[22]",
"DLG_TEXT[23]",
"DLG_TEXT[24]",
"DLG_TEXT[25]",
"DLG_TEXT[26]",
"DLG_TEXT[27]",
"DLG_TEXT[28]",
"DLG_TEXT[29]",
"DLG_TEXT[30]",
"DLG_TEXT[31]",
"DLG_TEXT[32]",

};