string DLG_TEXT[52] = {
"Hey, ",
", you bastard! Finally got you! Remember how you once had my skin flogged off for 'insolence'... Now I'll give you insolence!",
", you won't escape from my revenge this time. You'll regret that you once cut my balls off for raping that nun... I have already killed HER, and now I'll kill you!",
"Ha, the #sgender# I hate most - Captain ",
"! Do you know what kept me alive on the desolate rock on which you had marooned me? The wish to kill you one day... THIS day!",
"I should have killed you back then, when you were an easy prey..",
"Here comes harsh punishment for the sins of my youth...",
"An ugly nemesis from an ugly past...",
" old shipmate! Finally have I found you! Har, the good old times.. The fun we had! Remember how we tied that fat merchant to the mainyard.. with his own guts from his split belly.. HARHARHAR",
" old fellow! Great to meet you once again. Oh, if we only could sail together once more and have some fun like in the good old days. Remember how we forced that priest to yield the treasure of his church? How we used his very own paintings of tortured martyrs as examples to torture HIM.. HARHARHAR",
"Now if that isn't my old shipmate ",
"! I've missed you, never had so much fun like when we buccaneered together. Remember how we stormed the ramparts of Puerto Bello while using those catpured nuns as living shields? How the Dons shot at us regardless, but most bullets got stuck into them holy sisters.. HARHARHAR",
"Ah, yes.. BRUHAHAHA Hilarious joke that was.. Weren't we a bunch of merry pranksters, hehe? We should write a book about our stunts.",
"Aye, I remember.. and that memory makes me cringe with shame! But in contrast to you I have changed my evil life for the better: nowadays I FIGHT pirates!",
"Excuse me, Sir, I have never seen you before, and I have NEVER done anything like that. Good day.",
"What? ME sailing with you? Never! I am an honest merchant and I won't even TALK with your kind!",
"Umm.. err.. you must confuse me with someone else. I am SURE that we've NEVER met before!",
" Then fight we shall, cause I despise nothing more than a hypocritical turncoat!",
"So you learned nothing from your mistakes? Then I'll have to teach you a lesson now...",
"I am only a clerk of the commander.",
"I am not going to spoil my sword's edge on a clerk's bones. I bet I will desperately need a very sharp blade behind the next door...",
"A clerk, eh? Your clothes look mighty expensive for a clerk. You have probably access to the garrison's warchest, eh? Well, hand it over to me or I'll spoil your coat... WITH CLERKSBLOOD!",
"Oh, I fear that wouldn't be a popular book. People have so many romantic illusions about piracy, they probably just don't want to hear that pirates were occupied more with rape and torture than with heroic fighting\nSpeaking of that, do you have work for a fighting man? I am sort of unemployed at the moment.. For an old mate like you I'd even forfeit the usual hiring bounty.",
"Umm.. sorry, my ship is absolutely crammed with men at the moment.. But maybe another time.. We'll keep in touch, til then!",
"I'd be only to glad to have a tough guy like you with me. Grab your dunnage and join me.",
"DLG_TEXT[25]",
"DLG_TEXT[26]",
"DLG_TEXT[27]",
"DLG_TEXT[28]",
"DLG_TEXT[29]",
"DLG_TEXT[30]",
"DLG_TEXT[31]",
"DLG_TEXT[32]",
"DLG_TEXT[33]",
"DLG_TEXT[34]",
"DLG_TEXT[35]",
"DLG_TEXT[36]",
"DLG_TEXT[37]",
"DLG_TEXT[38]",
"DLG_TEXT[39]",
"DLG_TEXT[40]",
"DLG_TEXT[41]",
"DLG_TEXT[42]",
"DLG_TEXT[43]",
"DLG_TEXT[44]",
"DLG_TEXT[45]",
"DLG_TEXT[46]",
"DLG_TEXT[47]",
"DLG_TEXT[48]",
"DLG_TEXT[49]",
"DLG_TEXT[50]",
"DLG_TEXT[51]",

};