string DLG_TEXT[65] = { 
"He, what are YOU doing in this secret Army fortification! Are you a spy?",
"Please spare my life, I beg you! I am a civilian!",
"Leave me alone! I don't belong to those brutes in uniform!",
"Just be quiet and get lost!",
"Shut up! I must get on before reinforcements arrive!",
"Get out of my way! I have some real men to fight!",
"Shhh! You look like a smart fellow to me, mate. You and me, we will plunder stores and chests of this place, eh? . *WINK*",
"I'll slash you into pieces if you raise the alarm! Do what I say and you'll stay in one piece.",
"Do what I want or you'll die!",
"I'll spare your miserable life only if you cooperate!",
"Calm down, friend! Do I look like someone who harms civilians? Trust me, we'll get on well.",
"Allright, allright! What do you want?",
"Believe me, I won't do anything rash if you don't either. But what are you up to?",
"Got it! So what's next?",
"You surely don't look like a soldier. Who are you?",
"Tell me, what's a civilian doing in this oh so secret fort?",
"I just want to know, what's your business here?",
"I am an envoy of His Majesty's War Secretary, and I am here to inspect these fortifications.",
"So be MY envoy now and tell the governor that I demand the immediate and unconditional surrender of the town, or I will bombard it with these very guns. I have excellent gunners in my crew, and they will turn the townhall into a heap of rubble.",
"I'll let you live if you show me where your purse is hidden... Yes, there's a good boy.. eh, envoy.",
"Ah, Mylord, I am pleased to meet a person of such high standing and importance, albeit under such.. ehem.. a little unusual and, I fear, unpleasant circumstances. Please accept my most humble apologies for this unfortunate accident which is, I assure you, only the result of a misunderstanding. Actually I came here to seek peace and friendship. To prove my good intentions I will not molest you with my presence any longer, while you will surely grant me a letter of marquee in return... Yes, we diplomats understand each other, eh? I am most obliged to you, my good Lord.",
"Be warned, young man, and mind the severe implications of such an impudent AND imprudent deed: such an insolent demand may provoke a violent retaliation. And the conquest of this town might disturb the balance of power in the Archipelago. (i.e. mess up the mainquest ;-) )",
"Bah, I don't fear any retaliation. And I can always restore the balance of power by giving the town back to it's current ruler. Never mind the implu... implodations, go and tell the governor that I demand nothing less than the key to this town!",
"Hmm... it might be less imprudent if I just take your purse. Though you'll still find that impudent, eh? Here is my warning for you, old man: mind the severe implications of my blade in your belly and give me your gold.",
"Your most honourable Lordship, I see that you are a man of diplomacy and wisdom. Yes, the balance of power is very dear to my heart as well. Therefore I seek good relations with your proud nation. Let's strike a wellbalanced deal: I spare the town, and YOU, in return for an amnesty and a letter of marquee... Yes, we diplomats understand each other, eh? I am most obliged to you, my good Lord.",
"I don't trust you! ALARM! RAISE THE MILITIA!",
"I won't put my fate into YOUR hands! ALARM! Call in the patrols!",
"There can be no deal with someone like you! ALARM! Fetch the townguard!",
"... Bah, I'll fight them all till the town surrenders. And next time I'll treat you different, believe me!",
"Your boldness was rewarded... THIS time. The Governor will rather surrender than risk an assault on this impregnable fort. What are your terms?",
"I'll spare you and the town if you swear allegiance to Portugal.",
"Swear allegiance to the United Provinces of the Netherlands. Oranje boven...",
"Swear allegiance to Brtain. Rule, Britannia, rule the waves... AND this town...",
"Swear allegiance to France. Three cheers to his Majesty Louis, the new ruler of this town...",
"Swear allegiance to Spain. Long live his Most Catholic Majesty Felipe, who will restore this town to the true belief...",
"I am only interested in gold and goods. Deliver all your posessions to my ship and I'll leave you alone again.",
"... Looks like I have no choice but to give you my ",
"... But it can't be helped. SIGH Goodbye, my beloved ",
"... Allright, allright, here are ",
" Gold.",
"Don't swear, thank God that you are still alive and get lost!",
"Thank's a lot, it was a pleasure to do business with you. Farewell.",
"Good boy! And now get out of my way! I have some real men to fight!",
"I am only a clerk of the commander.",
"I am not going to spoil my sword's edge on a clerk's bones. I bet I will desperately need a very sharp blade behind the next door...",
"A clerk, eh? Your clothes look mighty expensive for a clerk. You have probably access to the garrison's warchest, eh? Well, hand it over to me or I'll spoil your coat... WITH CLERKSBLOOD!",
"I am an inspector from the Royal Ordinance Board, and I am here to inspect the stores of this armory.",
"Don't let me keep you from your work. And as soon as I have conquered this fort I expect a perfect report on my stores. Dismissed, carry on.",
"I could do with some Royal ordinace. Deliver a load of bombs to my ship, and don't you dawdle, or you can inspect your intestines... lying before your slit belly!",
"In that case you can surely give me some of these new special weapons. Come on, deliver, or I'll let you inspect open powderkegs... with a burning torch tied between your hands!",
"I am a recruiting agent, and I have just arrived with a shipload of.. eh.. volunteers fresh from pris.. eh.. prime families, I mean.",
"You mean you are a crimp who sells pressed fools and the scrapings of the goals to caribic garrisons, eh? Where most of them will die from yellow fever in the first months, so that there is always demand for your trade, eh? I despise leeches like you. Get lost before I crimp you for service in Verruckt's brothel!",
"Those poor guys will be much better off on my prime ship than in some buginfested barracks. So march your 'volunteers' to my vessel right away. And if you don't cooperate I will 'recruit' you as well: as 'cabin boy' for your former victims!",
"Nobody should profit from selling men into slavelike service! So give me your crimping money... NOW!",
"I am a chandler, and I have bought a contract for supplying this garrison with grain for the horses, spirits for woundtreatment, wood for stockades and canvas for tents. I was just about to get help for unloading my wagon.",
"Bah, boring stuff. Go and feed your horses, chandler.",
"Hmm, maybe I could use that stuff for slightly altered purposes? Chandler, hop on your wagon and drive to my ship. There you'll get help for unloading, hehe. And if you fail to arrive I'll make your heart fail as well, believe me! Go and deliver! NOW!",
"You BOUGHT the contract? And probably you cheat and deliver inferior stuff, eh? Well, that's the way of 17th century public private partnership. But that includes also bribes and protection money to all who could could cut off your trade, eh? Like ME, who could cut also of your head...",
"I want to become an ensign in this regiment, and I came here to buy a post. But they didn't accept me, even though I offered a considerable sum. Too old, they said. The cretins...",
"You should be grateful, had they accepted you I would have killed you by now. Get lost, or you'll get your first fencing lesson... and your last one as well.",
"A considerable sum, eh? Give it to me and I'll secure you a nice officer post. I have a lot of influence in this regiment... Thank's a lot.",
"Don't waste your talents in the Army, they offer nothing but sore feet and buginfested barracks. But the sea offers adventure and prizemoney. Join the Navy, become MY officer!",
"Adventure? PRIZEMONEY? Sounds great! I am ready to follow you in a moment, I must only fetch my dunnage first. I'll meet you behind the next gate.",
"Great, I can do with reinforcements. Welcome to the crew! And now look lively about your dunnage. See ya!",
"You mean you are a crimp who sells pressed fools and the scrapings of the goals to caribic garrisons, eh? Where most of them will die from yellow fever in the first months, so that there is always demand for your trade, eh? I despise leeches like you. Get lost before I crimp you for service in the #sisland_Oxbay# Mines!",

};
