string DLG_TEXT[52] = {
"Welcome to my tavern! ",
" will make you comfortable for sure!",
"Thank you, but ",
" needs no comforting.",
"Ah, Captain ",
"! Such a coincidence: only half an hour ago some guy enquired about your whereabouts, a rather tough looking sailor. Said he was an old shipmate of yours and wanted to join you as boatswain. He is still here, having a drink upstairs.",
"Ah, I'd be glad to drink and sail with an old mate! And maybe he is a good officer.. I'll join him right away.",
"Umm.. considering my bloody past I'd rather not meet any 'old shipmate'. A privateer doesn't have many old friends, but rather many old enemies...",
"How can I help you?",
"Point me to the rabble looking for work. I need some cutthroats who don't ask too many questions.",
"I'm looking to hire some sailors for my crew.",
"I'm a bit short of hands. Do you know any tars who seek a ship?",
"Do you have a free room? I'd like to stay here for a while.",
"I need a clean room with a clean bed. Nothing fancy.",
"I'd like to rest here for a while.",
"I don't need anything at the moment. Goodbye.",
"Well, we have only recently moved to this building, and our future guestrooms are not yet furnished, sorry. How long did you plan to stay?",
"Until morning.",
"Just until nightfall.",
"Why don't you make yourself comfortable on that bench in the corner over there? We don't have that much customers yet, so you wont be disturbed that much. I'll fetch you a blanket...",
"All right, that will do for me. If one can sleep in the foul damp atmosphere of an overcrowded ship one can certainly sleep here as well.",
"Thanks. That's at least more comfortable than a hammock on a crowded gun deck. But please shake the fleas out of that blanket, will you?",
"Well, better than sleeping on the beach...",
"Hmm, maybe I'll rather stay in the house of a friend. That is, if I can find a friend in this town...",
"In that case you should talk to that guy who's just come in. He's an old sea dog and knows each and every tar in this hemisphere.",
"Just the man I need..",
"I fear there are no sailors for hire here at the moment. You'd better try again another day.",
"Too bad...",
"DLG_TEXT[28]",
"DLG_TEXT[29]",
"DLG_TEXT[30]",
"DLG_TEXT[31]",
"DLG_TEXT[32]",
"DLG_TEXT[33]",
"DLG_TEXT[34]",
"DLG_TEXT[35]",
"DLG_TEXT[36]",
"DLG_TEXT[37]",
"DLG_TEXT[38]",
"DLG_TEXT[39]",
"DLG_TEXT[40]",
"DLG_TEXT[41]",
"DLG_TEXT[42]",
"DLG_TEXT[43]",
"DLG_TEXT[44]",
"DLG_TEXT[45]",
"What's the latest gossip in town? Any news from the other colonies?",
"What's the latest buzz?",
"Any news?",
"DLG_TEXT[49]",
"DLG_TEXT[50]",
"DLG_TEXT[51]",
"What's the latest gossip in town? Any news from the other colonies? [give one piece of gold]",
"What's the latest buzz? [give one piece of gold]",
"Stop gibbering nonesense! Do you know anything, which could be interesting to me? [give one piece of gold]",
"Do you have a cousin named Sven?",
};