string DLG_TEXT[95] = {
"Oh! I did not see you there, ",
"!",
"Please pardon me, seсorita.",
"Sorry I startled you, m'lady.",
"Oooh, Capitбn ",
"! You are back! Madre del Dios, is he all right?",
"I found him well and healthy, Doсa Estrella.",
"I haven't found him yet, Seсora. But I will be leaving soon.",
"Wait. You are a sea capitбn. Are you carrying a letter to be delivered here?",
"Yes, I have a letter.",
"No, I'm sorry, seсorita, I am not.",
"Gracias Dios! Finally! Give it to me, por favor.",
"Wait. It says on the outside that there is to be a reward.",
"Yes, yes of course. Mi Dios, five thousand gold, will that do to keep your lips sealed?",
"That's very generous, seсorita, thank you. But you seem troubled. Is there anything I can do?",
"Then go away, capitбn, and leave me to my tears.",
"You seem troubled. Is there anything I can do?",
"All right seсorita. Again, sorry to have bothered you.",
"I don't know you. How could I possibly trust you?",
"Well, my name is ",
" ",
" and my ship is '",
".' Perhaps you have heard of me?",
"Ah. You have a point there. Perhaps I should say farewell.",
"I don't know you. How could I possibly trust you?",
"Well, my name is ",
" ",
", and my ship is '",
".' Perhaps you have heard of me?",
"Ah. You have a point there. Perhaps I should say farewell.",
"Oh! The famous Capitбn ",
"! Oh, si, yes, I have heard of you. Stories of your exploits have reached even this insignificant colony of Espaсa. I am Doсa Estrella de Alenзar, wife of the governor of this wretched island.",
"Please, seсora, you may call me ",
".",
"Oh! You are the notorious Capitбn ",
"! Please leave me alone, or I shall call the guards!",
"As you wish.",
"Very well, Capitбn ",
". Here is your reward. But I am sorry, I don't see how you might help me.",
"You don't sound very happy to be here, Doсa Estrella.",
"Very well, Capitбn ",
". But I am sorry, I don't see how you might help me. Please leave me be.",
"As you wish.",
"I hate this place. I do not love my husband, but I cannot leave him. Yes, I am very unhappy. These letters are my only escape from an otherwise completely unsatisfying and miserable life.",
"You are too young to be so bitter.",
"You are very kind, Capitбn ",
". Kind and perhaps generous too?",
"One simply has to ask, m'lady.",
"And one can just as easily accept as refuse, correct, Capitбn?",
"Very true. What is it you want?",
"How did you get this letter? Who gave it to you?",
"A new officer I recently hired. He said he got it off of a pirate. A dead pirate.",
"Mi Dios, I pray that he is not dead!",
"You are exchanging letters with a pirate, Doсa Estrella?",
"Capitбn ",
", I beg you, please tell me my love is not dead!",
"M'Lady!",
"Oh ",
" Capitбn ",
", please help me, or I shall go mad from not knowing!",
"Seсora, do not weep! I will find out what I can.",
"I will give you a generous reward, Capitбn, if only you will find out if my beloved is still alive... Or Dios mio, dead. I pray he is not dead! Please. Find him for me, Capitбn. Find him.",
"Ummm... If I sail anywhere, I need provisions and pay for my men.",
"Here. It is all I have left for now. I can get more but only if you make a solemn promise to keep silent about this whole affair. No one - NO ONE - can know about this.",
"Oh yes, Seсora. My lips are sealed. You have my word. Absolutely. What is his name and where does he live?",
"He is on #sisland_Quebradas Costillas#. Armand Delacroix. His ship is the 'Voodoo Queen'.",
"Voodoo Queen? I've heard of her. She's big and scary-looking. And I've heard of him too. He's got a tough reputation. No quarter given. Are you sure this is the man? You seem not the type of woman who would go for such a rough man.",
"He was once a French Chevalier, Caballero, a Knight, and is a very courtly, educated, and charming man.",
"If you say so, Doсa Estrella.",
"I love him.",
"How did you meet him, if I may ask?",
"He boarded and took the ship upon which I was traveling.",
"And obviously spared your life.",
"I was being transported to #sisland_Isla Muelle# from Spain to marry a man I had never met. My soon-to-be husband's navy managed to rescue me from what they termed a fate worse than death. Armand had his men plunder the ship, and... Well... Before they all escaped, my bold pirate and I had become lovers.",
"And your husband never suspected?",
"Have you ever met Cristofor de Alenзar, ",
" Capitбn? It was an arranged marriage, a marriage of convenience, and we have had no...contact. How could he know?",
"Ah. I see. I promise, I'll find Delacroix for you, Doсa Estrella.",
"Thank you, Capitбn ",
". Please, take this cross to show to Armand. It is just a token made from an old coin, but he made it for me, and will recognize it. You will recognize him because he wears one just like it around his own neck. And fair sailing to you. I shall not rest until you return.",
"I'll be back as soon as I find news.",
"Santa Maria! Oh, gracias, thank you, mi Dios, gracias!",
"M'Lady... M'Lady... Here... Here is your token back, and a handkerchief. Now dry your tears. He's all right.",
"T-th-thank you, ",
" Capitбn. You are a kind #sperson#.",
"There is more, Seсora.",
"I need to reward you, Capitбn ",
".",
"Well, yes. But more importantly for you M'Lady, Armand has found a way to get you off #sisland_Isla Muelle#.",
"Mi Dios! At last! How?",
"With my help, Seсora. Do you think you can trust me?",
"I have already trusted you far beyond the trust I give to my oldest friends, Capitбn. Si, yes. I know you can be trusted.",
"It will be dangerous.",
"I am ready to risk anything to be with my beautiful Armand.",
"All right then. Here is what we will do... ",

};
