string DLG_TEXT[22] = {
"Capitбn ",
".",
"...The disguise is perfect, m'lady!",
"I am trembling, ",
" Capitбn.",
"Don't be afraid, Doсa Estrella.",
"I am not afraid. I am excited.",
"Well, don't be excited, either. This is dangerous, and we have a long way to go.",
"Do not worry, I was taught to use the sword and pistol I carry.",
"That could come in handy, Doсa Estrella, but upon my soul, please don't put yourself into any danger, or Armand will have my hide.",
"You are risking your life for us, Capitбn ",
". I shall back you up, if need be.",
"Very well, then. Let's go. Follow me, keep close, and whatever else you may do, please, please keep quiet.",
"That was clo -- ",
"Shhh! I told you to stay silent! This is not over yet. Now be wary; there are more dangers out here than the monkeys and the Akellani. Come on, let's go.",
"He is close, I know it! Armand! ARMAND!",
"M'Lady! Be quiet!",
"Armand! Madre del Dios, soldados!",
"Soldiers! We should wait for them here and take them one by one. Spread out and get ready!",
"Farewell, Capitбn ",
". To me, you are a hero of the highest honor.",
"M'Lady, it was an honor to meet you. Go and be safe, be happy.",

};