string DLG_TEXT[40] = {
"Welcome! Take a seat at the free table. What would you like to order, ",
"?",
"Nothing. I'm here on business.",
"Oh! I'm very sorry. I didn't mean to bother you. I'll go back to my work.",
"No, wait - you're not bothering me. In fact, you're the one I need to speak with.",
"Not so fast. I want to talk to you.",
"I am all ears. How can I help you?",
"I need to hire some sailors.",
"I'm looking to add to my crew.",
"Let's talk business.",
"I'd like a room.",
"Do you have a free room in this place?",
"Never mind. I've got to go.",
"Certainly, ",
". What's on your mind?",
"Tell me: Who owns the house near your tavern?",
"Actually, it's nothing important.",
"I do have a vacancy. How long were you planning to be with us?",
"I'll be staying the night.",
"Just until sundown.",
"Fine. It'll cost you five gold pieces.",
"All right. Here you go.",
"That much? It looks like I'll be spending the night in the tavern hall.",
"For what - the governor's residence? No, thanks.",
"I'll think about it. For now, let me ask you another question.",
"It'll cost you five gold pieces.",
"All right. Here you go.",
"That much? It looks like I'll be spending the night in the tavern hall.",
"For what - the governor's residence? No, thanks.",
"All right, I'll think about it.",
"Well, it's pretty late. Everyone you might hire will have found a place to spend the night.\nYou're better off waiting 'til morning. Maybe I could rent you a room? ",
"Do you have a free room?",
"No. I have another question.",
"Friends, please! Enough of this madness. Don't make me call out the guard!",
"Relax! I'm leaving.",
"I need someone skilled in preparing documents.",
"What sort of documents?",
"You know - unofficial. The sort I wouldn't be able to get from an honest writer in town.",
"Ah, I see what you mean. You probably want to speak to Pablo Escriva.\nHe arrived here round about the time the authorities in #sSanto Domingo# realised that the colonel supposedly signing some army payslips was actually in Spain.\nHe lives in the big stone house along from the store.",
"Thank you, Pablo Escriva sounds like just the sort of man I need.",
};