string DLG_TEXT[154] = {
"It's good to see you, ",
". My name is ",
", and I am entirely at your service.",
"And my name is ",
". I'm the captain of a fine ship.",
"It's good to see you again, ",
".",
"It's you again? I was hoping I'd never see you here again.",
"And good health to you ",
".",
"You can't wait, peddler.",
"Would you like to inspect my wares?",
"That would be nice. Show me what you've got.",
"Later, but right now I have one thing to talk to you about.",
"Some other time when I come in here again.",
"Are we going to trade big or do you want the small stuff, Captain?",
"I want to sell the load I brought in.",
"I want to buy a few things for myself personally.",
"We won't at all. Have a nice day.",
"I'm listening to you, what do you want to talk about?",
"I'm listening to you.",
"I've been instructed to deliver a shipment to you.",
"Don't you need a captain, sir? I have a fine ship, and I can take any cargo wherever you wish.",
"Shh... Shh. I'm from ",
"Ah, it's you again! Are you trying to get me into more trouble?",
"Just pay for the sandal I delivered to you, and you won't see me again.",
"I want to talk to you about a load of sandalwood delivered to you not so long ago, and the money you had to pay for it...",
"What? Is this you?!",
"You didn't wait, asshole?!",
"Is that you again?!",
"Recognize me? Now let's talk seriously. Very serious. So serious, in fact, that I recommend you lock up the shop so we won't be disturbed.",
"What can I do for you, monsieur?",
"I need to talk to you. So lock up the shop to avoid any misunderstandings - it's going to be a long conversation.",
"What? Is this you?!",
"Yes... And I have an offer for you that you can't refuse.",
"You've ruined me! Now they will confiscate my store and send me to the mines!",
"If you pass the store to #sBeltrop#, I'll put in a good word for you.",
"There's no time to talk now, though.",
"No, you don't. At least not as long as you're sinking #snation_desc# ships.",
"In that case, goodbye.",
"I'm sorry, but I don't have anything for you right now.",
"Okay, I'll stop by sometime later.",
"I'm sorry, but your vessel is not so capacious to fulfill the errand I wish to give you.",
"Well, I'll come over later then.",
"Oh! I was just about to ask you for a favour myself. The thing is, I need to deliver a shipment to ",
", as soon as possible. If you can do it in a month, you will receive when you arrive on site ",
" piastres of reward. How's that?",
"I agree.",
"It doesn't work for me.",
"I told you earlier today that I don't have anything for you.",
"Oh, I'm sorry.",
"You remembered your assigned case too late, don't you think? I've already gotten everything I wanted. Goodbye.",
"Have a nice day.",
"Oh! I've been waiting for it for a long time. Here is your reward, young ",
"You're welcome.",
"I have no need of your services at this time.",
"That's too bad. Then let's talk about something else.",
"Oh! You must have brought the load of sandalwood I've been waiting for so long?",
"Exactly. Maybe your men can handle the unloading?",
"Of course! In the meantime, you rest in the room upstairs.",
"That's a good suggestion, I think I'll take it.",
"It's done, I can only imagine the revenue I'll get from selling this contraband, ahaha... Oh, who's that?!",
"What the?!",
"(To the soldiers): This is just my visitor, gentlemen. (To you): Get out of here and don't try to resist them. This is a test, come see me in two hours and we'll settle things.",
"(To the soldiers): Uh. I see I'm disturbing you... Well, shall I go?",
"What sandal, what money! What are you talking about!",
"Ha! Have you decided to deny the fact that the cargo was delivered to you?",
"No, no, but I don't have this cargo! It was confiscated, I had to pay a huge fine, and I'm on the verge of ruin!",
"How interesting. And #sBeltrop#, for some reason, is sure it's all your doing, and has asked me to look into the matter.",
"God forbid! Do you think I want to make an enemy in the form of a man as powerful as #sDesmondRay#?!",
"I think I need money from you, tax-fencer, and as soon as possible!",
"Have mercy! I have a family, a daughter to prepare for marriage! Give me at least a reprieve!",
"For the last time, money on the barrel!",
"Okay, how many days do you need to raise the money?",
"All right, all right. I'll report your problems to #sBeltrop#.",
"Where am I going to get it? I'm on the verge of ruin!",
"It's not my problem. #sBeltrop# needs the money, and if I were you, I wouldn't persist.",
"Okay, okay, here's your money.",
"Oh, you bastard! So you had money!",
"I told you - this is my daughter's dowry! How am I going to marry her off now?",
"Stop whining. I hope I don't see you again. Goodbye.",
"Oh, not much! Just a couple days, no more! You get a room in the tavern for now, and I'll find you there as soon as I get the money together.",
"Deal.",
"Thank you, you are so kind to me, monsieur.",
"Keep your thanks to yourself.",
"What are you speaking about?! If it's about money, then I... I haven't collected it yet, wait a little longer.",
"You didn't collect it, did you say?! And for the murderers, then, there was gold?!",
"What are you talking about! I wouldn't dare, I wouldn't dare, I assure you!",
"Yeah, I would even believe you if you weren’t shaking so much and didn’t stink of sweat from fear.",
"I just have malaria! That's why I'm shaking, I'm sick, #smonsieur#, that's the explanation!",
"Stop explaining! I need the money. NOW!",
"But I told you before...",
"Either I put a bullet in your forehead or you give me the money.",
"Ahem... Okay, just, for God's sake, don't kill me! Here... Here's the full amount.",
"Great. And consider yourself lucky, lease-monger.",
"What are you implying?!",
"#sBeltrop# doesn't like you twisting the cards, bargainer. He doesn't like it VERY much...",
"What?! You dare threaten me, puppy?!",
"I? No, it’s not I who’s threatening you, it’s #sBeltrop#, and I’m just working for him.",
"Puppy?! Did you think twice before you said that?! I'm going to ram those words back down your throat!",
"And what does this bloodsucker want from me?!",
"To sell your store...",
"What's wrong with you? Tell your #sBeltrop# that I'm not selling my store!",
"Then I'll have to kill you.",
"All right. I'll leave, but #sBeltrop# will probably send someone less patient in my place.",
"You won't intimidate me, and I get to keep my store!",
"Time will tell. (Try to discreetly slip your ring into his pocket).",
"Time will tell. (Leave).",
"Yes, yes, of course!",
"But ",
"(You managed to distract #sshopkeeper# with a conversation and quietly toss him a couple of your rings, as well as a bag of money with your initials embroidered on it).",
"...",
"Hey! Take your hands off my pocket, you scoundrel!",
"Okay, okay, I'm just leaving now.",
"That was the last straw! Who are you calling a scoundrel? I'm going to feed you to the sharks!",
"You're bluffing! The city is full of soldiers, and if you lay a finger on me, you'll be hanged!",
"Check it out! Argh!",
"You're right, risking your neck for the pleasure of seeing your corpse...",
"Yeah! I knew it! You don't have enough courage!",
"That's it! You've pissed me off!",
"Yell or shout, drooling won't help the cause. Like I said, I'm here on #sBeltrop#'s orders.",
"You #snation# dog! I'm not afraid of you! Guards!",
"Say hello to the devil when you meet him!",
"Get out of here! I don't want anything to do with you!",
"Your word is my law. I can imagine how upset Susanne will be...",
"S... Susanne?! What did you do to her?!",
"Nothing yet, but I have some business with her... But we can come to an agreement.",
"Anything, just let her go!",
"Now that's a different conversation! Sell your store.",
"I don't get it...",
" wants you to sell your store. Or rather hand it over to me, and he'll put his man here.",
"Are you crazy?!",
"Well, since we didn't agree, I'll let my crew have some fun with your daughter...",
"Wait! All right! I'll pack my things and leave today. Just set my daughter free.",
"Great. Meet me at the tavern in three hours, I'll get a room. When you hand me the keys, I'll give you Susanne.",
"Goodbye, I'm going to Europe.",
"Have a good sailing.",
"You'll rot in hell!",
"Get out!",
"Damn you! Here... just a minute... here are your papers. You are now the owner of this store, now leave me alone, I must pack my things!",
"It's a pleasure doing business with you.",
"I have accomplished what we agreed upon. Here are the keys to the store and the necessary papers.",
"Very well. I will also keep my word - go to the port, there you will see your daughter.",
"Now get lost. I'll keep your daughter, ha-ha!",
"What? This is absurd! I'm completely innocent!",
"Ah, all right! Look, it's up to you!",
"I am not guilty! I was tricked!",
"N-n-no... I don't know how I got it...",
" sent me a message that I was to expect 300 sandal. You only brought ",
". Where is the rest?",
"Err... some of it must have fallen overboard in a storm. I'll buy more somewhere to make up the full load.",
"Well, ",
"? Do you have the full load of 300 sandal now?",
"Yes, I'll wait upstairs again while your men unload it.",
};