string DLG_TEXT[177] = {
". What is it, ",
"?",
"May I help you, ",
"?",
"Is this your first time in our town, ",
"? I haven't seen you before.",
"I'm ",
", captain and owner of the ship '",
".' I've got some questions if you have a moment.",
"My name is ",
". I'd like to ask you some questions.",
"You can call me captain ",
". I'd just like some information.",
"Hello, captain ",
". What brings you to our colony?",
"Ah, captain ",
". ",
", it's you again. I hope your journey was a pleasant one. What's new?",
"Hello, ",
". How can I help you?",
"Did I miss anything while I was away?",
"Has anything interesting happened while I was gone?",
"What stories are the old sea dogs swapping over their rum these days?",
"What's the buzz in the tavern?",
"I'm looking for gossip, rumors, tall tales...anything I don't know may be of use.",
"Dish me up some of your freshest gossip, friend. There may be adventure or money to be found in even the smallest tidbit.",
"I still can't find...",
"It's impossible to find anything in this maze! Where is...",
"I'm as lost as a drunken navigator. Again!",
"You look like a local. Tell me where I can find...",
"Please tell me how to get to...",
"I've had a rotten day, so you'll save us both grief if you'll just tell me how to find...",
"I'd like your opinion on a local citizen.",
"I need to know whatever you can tell me about someone who lives here in town.",
"What can you tell me about...",
"Tell me whatever you can about one fellow...",
"I'm hoping you can tell me something about a person you may know.",
"This place isn't too big - I'll bet you know everyone who lives here. Let's talk.",
"Tell me about #sGrand Turk#.",
"What can you tell me about this god-forsaken place?",
"I'd like to know more about this fine colony.",
"What's the story of this town and the island?",
"Do you know anything of interest about #sGrand Turk#?",
"...",
"I'm sorry. I thought you were someone else.",
"I'm just passing through. So stand aside or be pushed.",
"What would you like to know, ",
"?",
"What interests you, captain?",
"What do you want from me?",
"Towns like this are usually swimming with gossip. Give me the highlights.",
"Has anything interesting happened around here lately?",
"I just want to know what's going on in the neighborhood. Someone's swindled a friend? Someone's been killed? The innkeeper's not really a woman? You get my drift.",
"How can I get to...",
"Can you help me find my bearings here in town?",
"Where can I find...",
"Can you tell me about someone I'm interested in?",
"I'd like some information about one local fellow. Could you help?",
"I'm wondering what people in town have to say about a certain person...",
"What can you tell me about #sGrand Turk#?",
"I'd like to know the history of the town.",
"I'd like to get some information about this colony.",
"I'm just walking here. I'll see you later.",
"Thank you. There is one more thing...",
"It was nice to chat with you. So long!",
"Anything else, captain ",
"?",
"Let's hear it, ",
".",
"I'm listening, ",
".",
"What's the talk of the town these days?",
"What stories are the old sea dogs swapping over their rum these days?",
"It's been a long time since I've set foot on these shores. What have I missed?",
"Could you give me some directions?",
"I've gotten myself absolutely lost in these streets.",
"It's my first time in this town, and I'd like some directions.",
"I'd like your opinion on a local citizen.",
"I need to know whatever you can tell me about someone who lives here in town.",
"Could you give me some information about the locals?",
"Tell me about #sGrand Turk#.",
"What can you tell me about this colony?",
"I'd like to know something about #sGrand Turk#.",
"I've just realized I have to be somewhere. Goodbye.",
"Who do you mean,",
"?",
"Are you asking about someone specific?",
"Who exactly do you want to know about?",
"I mean the governor.",
"I am interested in the owner of the tavern.",
"The owner of the shipyard.",
"I'm talking about the local trader.",
"No one. Never mind.",
"Aye our Governor is in very good contact with the pirate lords. He's supporting piracy here in Caribbean waters in cooperation with the leader of the pirate settlement on #sisland_Quebradas Costillas#. He maybe can make a ceasefire agreement with them for you.",
"I see. I have another question for you.",
"Thank you, bye-bye.",
"She has the best rum to get drunk hic-cup. Now you mention it, I think I'll be heading back there. ",
"I see. I have another question for you.",
"Thank you, bye-bye.",
"Ahh our shipwright. Well without him our ships would be done for after a few shots. He refits the ships we capture and can make them faster for us. I think he calls that 'corsair refit'.",
"I see. I have another question for you.",
"Thank you, bye-bye.",
"He is very greedy. He bought the business for a low price. I don't know about the quality or price of his goods, but he doesn't seem to be a very...good person.",
"I see. I have another question for you.",
"Thank you, bye.",
"Where are you headed, ",
"?",
"Not a problem, captain. Where do you need to be?",
"I'm happy to guide you, ",
". But where do you want to go?",
"How can I get to the tavern?",
"Where's the shipyard?",
"Where can I sell the goods I've brought with me?",
"Alright, alright. If you enter the town, head left and continue under the laundry up the stairs. There's our tavern.",
"Fine. Thanks for your time.",
"Where's the shipyard?",
"Where can I get a decent price for the goods I've brought to town?",
"The shipyard is near the pier in the port.",
"I see. And the tavern?",
"Where can I get a decent price for fine goods I've brought to town?",
"I think that's everything. Thanks for your help.",
"When entering the town, head right, The Store is the second on the right side.",
"Where can I find the local shipyard?",
"How do I get to the tavern?",
"I see. Thanks for the information.",
"I'm not sure why you'd be interested, but why not?",
"What exactly are you interested in, ",
"?",
"Of course, ",
". Fortunately, it's a fairly short story.",
"I'm interested in the history of the colony...",
"Tell me about the colony.",
"Is there anything on the island besides the town?",
"I have a few more questions for you, if you don't mind.",
"Fellow, I'm drunk's hell nd I think I can't even rememember ma name an' you're ask'ng me 'bout the histry of this goddamn nest?",
"Thanks. Let me ask you a few more questions.",
"You know, I really thought that was going to be more interesting. Let me ask you something else.",
"That's all I need. Thanks.",
"Thanks for your time. Farewell.",
"Not really. Other than an old fort and a lighthouse, the rest of the island is pretty deserted.",
"What else can you tell me about the colony?",
"What else can you tell me?",
"There are vague rumours of a pirate hideaway somewhere on the island.",
"I see. What else?",
"No. You'll find a fort and a lighthouse, but it's largely jungle.",
"In that case, maybe you can tell me more about the colony.",
"Got it. Let me ask you something else.",
"//PW not used",
"//PW not used",
"//PW not used",
"Interesting. Oh, I have another question for you.",
"Thank you very much, farewell.",
"//PW not used",
"I see. One more question, if you don't mind, please?",
"Thank you for your time. Bye.",
"//PW not used",
"//PW not used",
"Ehm... I plumb forgot who I was going to inquire of. Just give me a second and it'll come back to me...",
"How's the reputation for quality work of your blacksmith? Well thought of is he?",
"She is very good. One of the finest in the Caribbean maybe...  and a gunsmith to boot.",
"She? Oh my it's heavy work... still if she has the talent and skill that's all that matters in the end.",
"Well. A smith who can mend a blade and gun? I shall have to pay my respects immediately...",
"My all-time best most favourite sword in the world here has gotten a bit dull as of late. To whom might I entrust it?",
"I should expect you'd be pleased with the services of our blacksmith. She is in the house next to the Shipyard near the shore.",
"Perfect! Thanks for your help.",
"Where's the shipyard?",
"Where can I get a decent price for fine goods I've brought to town?",
"To whom might I entrust my sword? Its once-fine edge has gotten a bit dulled.",
"What can you tell me about the proprietors of the Poker Tournament?",
"Ronnie and Reggie? They think they are big fish but are really bottom feeders so they fit right in here, but don't quote me I want to keep breathing!",
"I'll have to watch my step then. Thank you for the insight.",
"How do I find the right building for the Poker Tournament?",
"Ronnie and Reggies place? Easiest is start from the Tavern, you'll need a drink anyway if you're seeing them. When you leave and walk down the steps it's straight in front of you a three storey gable ended building.",
"It was first settled by the Spanish until it fell under pirate control for a spell, now the British think they run things.",
"It was first settled by the Spanish but they mostly lost interest and the pirates moved in and took over.",
"It was settled by the Spanish with not much enthusiasm and is quite poor. You may find as many pirates as Spanish around town.",
"Ahh our shipwright. Well it's not like in the old days. They used to make 'corsair' alterations I believe. These days it's just standard stuff. Still his work's good enough for most.",
};
