string DLG_TEXT[28] = {
"'ello guv! I'm the king of England!",
"Of course you are. Now, out of my way, you loony old man!",
"Are you 'ere tah clean meh shoes?",
"Yes. I'm here to clean your... I'M GOING TO KILL YOU!!!",
"I got a spot o' information for you, ya know from the inside...",
"The inside of what? You're just a crazy old man.",
"The sun is shining, the birds are chirpin', and all Gregor wants is a spot o' rum! Could ya give an old man some RUM? I'm actually allergic to rum... so uh... never mind",
"I only wish there were a way to count how many pieces I'm going to cut you in if you don't shut up.",
"You're a filthy BASTARD you are! Always walking around in your clean clothes, YOU'VE GOT A MULLET YOU KNOW!!! FILTHY TRASH EATER!!!",
"Mullets are the most noble of hairstyles you old fool!",
"THE INSIDE OF YOUR DIRTY MULLET!!!",
"After I kill you, I'll have you made into a new pair of boots.",
"That was harsh...",
"Ha, silly old man, I love you!",
"I USED tah be THE GREATEST merchant in the... IN THE WORLD!!! still 'ave some o' me old stuff!!! I'll sell it to ye if ye be interested...",
"Sure, I've got nothing to lose...",
"BUG-OFF! You are so cramping my style.",
"17",
"18",
"19",
"20",
"21",
"22",
"23",
"24",
"25",
"26",
"27",
};