string DLG_TEXT[54] = {
"Hello. I am an officer ",
" of His Majesty of #snation#.",
"My name is ",
".",
"Did you approach me for a friendly chat, or do you have some actual business with me? ",
"I thought we might chat for a bit.",
"I'm here on business, officer. Rather important business.",
"I'm afraid I must disappoint you, then, ",
". I have no time for idle talk.",
"I'm sorry to have bothered you.",
"What kind of business?",
"It's concerning a merchant named ",
"Patric Cardone",
"Patric Cardone",
".",
"The man whose Indian relics were stolen.",
"That's right.",
"And what does that have to do with me?",
"Do you know where ",
"Lucien Bescanceny",
"Lucien Bescanceny",
" lives?",
"Of course I do. He's made quite a name for himself with his illegal activities.",
"Indeed. And if you'll pay him a visit, you'll find he has a lot of interesting information about the statuettes that disappeared.",
"What makes you think he would talk to me?",
"Maybe he won't. If he refuses, then search his room. You'll find the statuettes in there.",
"How can you be so sure?",
"I've already been to his place. He confessed everything.",
"All right, I'll go and talk to him. But if this is some sort of scam...",
"It's no scam, officer. You'll see.",
"Wait... Old F... Ummm, Aufort, yes of course! Are you the Captain of the Guard?",
"I am, but what business is that of yours?",
"I've come to talk with you about Fred Bob.",
"Ah the mutineer. Sad case, really. I don't believe he did it. Neither does the governor, if you come right down to it. He'd be happy to let the man go.",
"Then why is Fred Bob still in the stockade?",
"The governor is new here, and still worried about keeping his job. Fred Bob's former first officer has a lot of influence back in #snation#.",
"Do you think he'd be appeased if I offered to become responsible for Fred Bob and hire him onto my ship?",
"I see. Well since I don't like to get involved in political situations, perhaps I should say farewell.",
"Appeased? What a remarkable idea. Yes, I know for a fact that both the governor and his former first officer would be delighted to see him gone. They've ordered me to 'do something' with him, in fact. This may be a good solution for all.",
"Well then it's settled. I'll take him with me when I leave, and he'll be my responsibility.",
"You seem a respectable #sgender#, but I must admit I don't know you well enough to let you vouch for Fred Bob. Please don't be offended, ",
", but he'll have to find another patron.",
"Sorry to hear that. Well, goodbye, captain.",
"Let me ask you something else, if I may.",
"But captain, you are thoroughly aware of the situation if Fred Bob gets into any trouble while here and under your command? Your reputation will be at stake.",
"Don't worry about that. If he causes any problems after I've vouched for him, I'll personally make sure it's the very last trouble he'll have any breath left to commit.",
"Well, captain. I wish you well with him. Frankly I'm glad to see Fred Bob go. He's so sad when we lock him in at night. He loves the sea, and no matter what that officer accused him of, he's a very good mariner and a very good man.",
"I don't think either you nor I will be sorry we've helped him.",
"Good fortune and a strong wind at your back, captain.",
"Thank you, captain. Good fortune and a strong garrison at yours.",
"Indeed. Well, I visited him while I was looking for the relics for ",
". He attacked me and I had to kill him. Before he died, he confessed that he hid the statuettes in his house.",
"Alright, I'll go and search his house. But if this is some sort of scam...",
"Wait... Cris... Ummm, Crespo, yes of course! Are you the Captain of the Guard?",
};
