string DLG_TEXT[118] = {
"I desire you, #ssir#, to lower your voice to a discreet level. A.. (cough) guest of mine is resting in the room upstairs. Exhausted by.. (cough) social events. So what is your desire, #ssir#?",
"Oh, awfully sorry to disturb your affair.. (cough) social affairs, I mean. I'd better take my leave.. discreetly, of course.",
"I am ",
", and I desire to enquire if you have any tasks for me and my fighting ship. ",
"?? You are known as enemy of the Crown! GUARDS!! ARREST THIS SPY!!",
"Oh, how boring. Yet another privateer who thinks the Caribbean is full of fat prizeships waiting only for him. #ssir#, I have the whole Leeward Islands squadron at my discretion, and every naval commander is only too eager to go on a cruise. Do you really believe I'd give any profitable mission to you instead of my cron.. (cough) loyal followers?",
"So you give me the menial tasks that your flashy cronies look down upon? No, thank you. I will rather go for ENEMY merchants.. those full of gold and plunder.",
"Well, an escort mission is better no task at all.. especially if I can be of service to Your Lordship.",
"Umm, my secretary just slipped me a note that you have already more ships in your fleet than you can keep control of.",
"You are right, more than four ships make a squadron rather unwieldy. I'll get rid of one right away.",
"Umm, my secretary just slipped me a note that you have already an escorting contract with another merchant.",
"Thanks for reminding me, after all I promised him my undivided attention and a speedy escort. Should set sail with him right away!",
"What a fortunate coincidence, cause just this very moment that nuisance of a pedlar enters my office to nag me once again... AH, COME IN MY DEAR FELLOW! So nice to see you again, I always look forward to our cosy chats. I'll really miss your company, but this dashing hero here will escort you away from me: Commodore ",
" is my best officer and has already performed countless daring and vital tasks for the Navy.",
"COUGH.. Seems like you must be a good actor to make a career in the Navy..",
"With pleasure, #ssir#. Antigua is no ordinary port but a naval base, actually one of the most important in the Caribbean, due to its strategic position near the main passage between Windward and Leeward Islands, and the fortifications are impregnable! \nThe whole harbour is a military area, so you'll meet few civilians here. Apart from those thieves or saboteurs! So be on your guard if you see some suspicious figure.. Speaking of thieves, there is a small civilian settlement in front of the naval station's gate: a slum with cheap taverns where sailors are being plundered and crimped, and cheating traders who sell you back what the muggers took away from you before...",
"Sounds like I'll enjoy my stay here. Thanks for the hints, goodbye.",
"If I may bother Your Lordship with a humble question: where I can get provisions for my ship?",
"Well, the naval yard office is at the end of the jetty. The big building near the jetty is the magazine of the Agent-Victualler. \nBut as Antigua is no ordinary port but a naval base its facilities are normally reserved for ships of our navy. Our privateers are being supplied if they pay for it, but all other ships won't get any stores or repairs here in port. \nAs a last resort you can try the civilian traders in the outskirts of the harbour, and maybe you can hire some men there as well. But beware, there are lots of scum and cutthroats out there.",
"Makes me feel at home... Thanks for the hints, goodbye.",
"Interesting, and can you tell me a bit about this harbour in general?",
"Is there really nothing I can do for you?",
"Well, there is one favour that you could do me - and believe me, those who do me a favour are being favoured in this port. There are always nagging merchant captains who demand ships to escort them. Oh, how those common traders bore me, nothing but peddlars, they simply lack any style. Too timid to sail on their own, too stingy to man and arm their ships for selfdefense. One such merchant has become a real pest, always calling in the morning when a gentlemen with manners is supposed to lie in the arms of his mist.. (cough) Morpheus, always nagging me for lack of zeal, threatening to blast my career by means of his influence at court.. I'd be much obliged if you could rid me of this nuisance by escorting him - as far away from me as possible.",
"DLG_TEXT[23]",
"DLG_TEXT[24]",
"DLG_TEXT[25]",
"DLG_TEXT[26]",
"DLG_TEXT[27]",
"DLG_TEXT[28]",
"DLG_TEXT[29]",
"DLG_TEXT[30]",
"DLG_TEXT[31]",
"DLG_TEXT[32]",
"DLG_TEXT[33]",
"DLG_TEXT[34]",
"DLG_TEXT[35]",
"DLG_TEXT[36]",
"DLG_TEXT[37]",
"DLG_TEXT[38]",
"DLG_TEXT[39]",
"DLG_TEXT[40]",
"DLG_TEXT[41]",
"DLG_TEXT[42]",
"DLG_TEXT[43]",
"DLG_TEXT[44]",
"DLG_TEXT[45]",
"DLG_TEXT[46]",
"DLG_TEXT[47]",
"DLG_TEXT[48]",
"DLG_TEXT[49]",
"DLG_TEXT[50]",
"DLG_TEXT[51]",
"DLG_TEXT[52]",
"DLG_TEXT[53]",
"DLG_TEXT[54]",
"DLG_TEXT[55]",
"DLG_TEXT[56]",
"DLG_TEXT[57]",
"DLG_TEXT[58]",
"DLG_TEXT[59]",
"DLG_TEXT[60]",
"DLG_TEXT[61]",
"DLG_TEXT[62]",
"DLG_TEXT[63]",
"DLG_TEXT[64]",
"DLG_TEXT[65]",
"DLG_TEXT[66]",
"DLG_TEXT[67]",
"DLG_TEXT[68]",
"DLG_TEXT[69]",
"DLG_TEXT[70]",
"DLG_TEXT[71]",
"DLG_TEXT[72]",
"DLG_TEXT[73]",
"DLG_TEXT[74]",
"DLG_TEXT[75]",
"DLG_TEXT[76]",
"DLG_TEXT[77]",
"DLG_TEXT[78]",
"DLG_TEXT[79]",
"DLG_TEXT[80]",
"DLG_TEXT[81]",
"DLG_TEXT[82]",
"DLG_TEXT[83]",
"DLG_TEXT[84]",
"DLG_TEXT[85]",
"DLG_TEXT[86]",
"DLG_TEXT[87]",
"DLG_TEXT[88]",
"DLG_TEXT[89]",
"DLG_TEXT[90]",
"DLG_TEXT[91]",
"DLG_TEXT[92]",
"DLG_TEXT[93]",
"DLG_TEXT[94]",
"DLG_TEXT[95]",
"DLG_TEXT[96]",
"DLG_TEXT[97]",
"DLG_TEXT[98]",
"DLG_TEXT[99]",
"DLG_TEXT[100]",
"I can tell by your face that you have a question to ask of me.",
"How did you guess? I'm looking for a frigate sent here by the #sFalaise de Fleur# governor.",
"'La Foudre' moored here just recently. Why do you ask?",
"I'm looking for the daughter of Governor Le Moigne. She left for #sHavana# over two months ago and...",
"Say no more. The captain of the frigate explained everything already.",
"I think Governor Le Moigne worries too much.",
"Don't be so hasty to say that. After the crew left Havana they were to go to Saint Martin to see if they could provide any aid to their struggle with the Dutch. It seems more is going on than just a missing governor's daughter. At the coast of Hispaniola 'La Foudre's' captain found the debris of the convoy. They had been caught up in a violent storm, during which a pirate ship appeared and sank the entire convoy.",
"Debris alone are not enough to warrant such a preposterous assumption. One pirate ship sinking an entire convoy? That sounds highly unlikely.",
"This story came from three surviving crew members who were terrified to even have to speak of this pirate ship when the frigate's captain asked about it.",
"That does sound somewhat worrisome. So then what did the frigate's captain do?",
"He decided to chase this pirate ship immediately. I argued against it. I thought he should stay here for a couple of days and prepare a fleet. But I could not convince him and he set sail for Marigot straight away.",
"Marigot, eh? I'll go there as well and see what I can find out. Thanks for your help.",
"You again? Any luck?",
"It's Davy Jones! He did it! Can you spare me some ships?",
"I'm afraid not.",
"Bugger!",
"I'm looking for the daughter of Governor Le Moigne. She left for #sHavana# some time ago and...",

};