string DLG_TEXT[32] = {
"Hello.",
"Goodbye.",
"ЎMi Supremo! ЎMi Supremo! ЎHay un navio a corta distancia al sureste, que viene en nuestra direcciуn! ЎCreo que es el Natividad!",
"All hail El Supremo!",
"Oh well, and now please excuse me.",
"Signal from the point, sir. 'Natividad' has gone about. One more turn and she'll be at the harbour mouth.",
"Very good, Lieutenant.",
"Lookout reports 'Natividad' has anchored, sir.",
"Snugged down for the night, eh?",
"Sir, it was me that was up there on lookout. I saw a small village not far from here. You'll be wanting to avoid that, I'm thinking.",
"Indeed we will, Mr. ",
". Did you see the route we should take?",
"Aye, sir. The first turn to the left goes to that village, so we skip that. The next turn is left of a small hill with a big tree and that's the one we want.",
"Thank you, Mr. ",
"ЎRendнos! ЎRendнos, Espaсoles! ЎRendнos!",
"You may retain your sword, captain.",
"But we have surrendered! There are rules of war.",
"Believe me, Seсor captain, if Don Julian as much as sees you during the coming day, he'll have you all killed. Those are his 'rules of war'.",
"There are women aboard! What are these Spaniards up to?",
"You'd better get the sling ready.",
"And that's not all, ma'am. He's as gentle and warm-hearted as any man as ever sailed for the king.",
"<Shout from above> MR. OLDROYD!",
"How's her ladyship settling in, Mr. Oldroyd?",
"She's below tending to the wounded, sir!",
"WHAT?",
"She insisted on helping, sir. There's so many, sir.",
"She's down there in all that mess?",
"No stopping her, sir. She just put on a boatswain's jacket and went to work.",
"Well go below, man, and help her!",
"Aye aye, sir!",
"Good to see you, sir. The admirals are upstairs.",
"Thank you, Lieutenant.",
}