string DLG_TEXT[18] = {
"We will be victorious!",
"...",
"Greetings! I've heard a lot about you -- and, in fact, your help was greatly appreciated.",
"I'm glad to meet you, too. But what help do you mean? Oh, wait... You're talking about that little stir near #sisland_Oxbay#'s shores?",
"A favor, commander? What if someone stole your son or daughter, and some bureaucrat demanded a favor before he let you save your child?! Outrageous! Does such a man even have a heart?",
"",
"Exactly, ",
". You were a great help to us then. If not for you, I suppose I'd be in some shark's belly now.",
"And unless I'm mistaken, you're the mysterious passenger that landed in #sGreenford#'s port. Correct?",
"Mysterious? Ah, I think I understand what you mean. Yes, that's me.",
"Then maybe you'll tell me your name and how you're connected to recent events.",
"Of course. My name is ",
". I'm a Maltese knight. A few years ago, I took part in destroying an evil cult of Satanists in Italy...",
"And now you've come here to finish the job?",
"Exactly. And, if you don't mind, I'd like to join forces with you. Believe me, I won't be useless.",
"Well, you know the face of the enemy and I'm sure you can fight. I see no reason to refuse you, so welcome aboard.",
"You won't regret this, captain. Where would you have me follow you first?",
"To #sisland_Isla Muelle#! We need additional information.",

};
