string DLG_TEXT[93] = { 
"I'm told you've gone to great lengths to request an audience. My name is ",
". Now, if you please, tell me the purpose of your visit, ",
".",
"My name is ",
".",
"Ah, it's you again. What brings you here this time? ",
"I'd like to talk to you about some business.",
"I'm sorry, but there are things that I have to do.",
"So, why do you distract me from the very important affairs of state?",
"I'd like to talk to you about a small piece of business.",
"I'm just here to pay my respects, #saddr#. Nothing more.",
"In that case, please leave my study and let me get back to more important matters.",
"Yes, of course. Sorry I disturbed you.",
"I'm sorry, but I don't have anything to talk about right now.",
"Oh yes? I have a proposition for you, captain.",
"Indeed?",
"I have learned that you completed the task successfully; my congratulations, captain! Here is your reward.",
"My thanks; It was a pleasure to aid you.",
"You must destroy the ",
" vessel ",
"quest pirate",
" menacing the shipping off ",
". If you sink her, I will reward you the hefty sum of ",
" gold. What say you, captain?",
"You shall not hear of her again, that I promise.",
"I'm afraid I can't help you.",
"I crave forgiveness, your Excellency.",
"I'm interested to learn about #sgov_nation# relations with other nations.",
"I'm looking for a Letter of Marque.",
"I've heard I'm up for promotion.",
"I can no longer serve ",
", your Excellency.",
"I'm through serving ",
"As insurance that you are an able captain, and to recompense my time in presenting your case to ",
", I must ask you for ",
" gold.",
"Not a chance.",
"Very well.",
"#sgov_nation# is always pleased to accept new captains into her service. ",
"We are currently at war with ",
"",
"no great power, but ",
". Of course, ",
"Pirates are always to be sunk on sight.",
" In light of your previous service, ",
" grants you the rank of ",
"I'll make you proud, your Excellency.",
"You have harmed ",
", and ",
" does not forget his enemies. Leave at once, or the guards will toss you out on your ear!",
"...",
"You have caused ",
" great harm, captain, but ",
" is willing to overlook your past transgressions... for a price: ",
"Very well, Sir. I accept.",
"A pleasure dealing with you, ",
"And you, your Excellency.",
"You are indeed! Excellent work. Your new rank is ",
". In addition, you are awarded ",
" acres of land by order of ",
"Thank you, Sir.",
"Are you sure, ",
" will be sorry to lose your service.",
"Yes, I am.",
" does not take kindly to turncoats, ",
"Uh, never mind.",
"Very well. But I hope you will reconsider, in time...",
"Goodbye, ",
"Huh?",
"Tough.",
"Congratulations, Captain! We were waiting for you. This operation was a hard blow for the Spanish. From now on, they can't underestimate the privateers any more.",
"Indeed, Governor. However, we need to be cautious. The Spanish are proud, they could retaliate at any time.",
"I know. Don't worry, I shall get ready for any Spanish attacks. I suppose you, Morgan and my partner want to share the El Morro's loot now.",
"Yes, Governor.",
"Very well. Don't forget to spend your money in my town. People will appreciate it!",
"I'll remember. Goodbye, Excellency.",
"Excellency, I have reason to believe the French will attack this town from the land. ",
" will arrange for the landward gate to be open at night, allowing the French to attack the town from behind.",
"What utter nonsense! The ",
" family are well respected in this town. ",
"And you are not. Now, get out before I have you arrested for defamation!",
"I am sorry I can not convince you. If you will not heed the warning then there is little more I can do. Goodbye.",
"And you are a known enemy of the Crown. Guards! Arrest this criminal and take #spronoun# to the prison!",
"Your mistake, Excellency. When the French arrive, you'll probably end up in the cell next to me!",
"You are most fortunate, Captain ",
"Is that what you call 'fortunate'? To be imprisoned for trying to warn you about an attack on your town?",
"No, you are fortunate that there was such an attempted attack.\nThough I could not accuse #svillain# without evidence, I had the army conduct night exercises in the churchyard. They ambushed #svillain#'s men and prevented them from opening the gate. With the wall secure, the French were easily driven back.\nAs a reward for your timely warning, I am pleased to offer you amnesty for all your past crimes against England.",
"It seems I owe you an apology, Captain ",
" - and the thanks of this town! Even after I doubted you, your action saved us from the French invasion about which you warned us. As a reward, please accept 20000 gold coins.",
"Thank you, Excellency.",
"There is another service you could perform. ",
" is now a known traitor. Should you bring #spronoun# in, dead or alive, the reward will be substantial.",
"Most interesting. I look forward to finding out how substantial.",
};
