string DLG_TEXT[62] = {
"Welcome, ",
". I don't believe we've met before. I am Laurence Wellman, harbor master.",
"Hello, Laurence. I'm ",
", captain of the ",
".",
"I welcome you, ",
". Do you come to me on business?",
"Hello, ",
". I saw your ship entering the port. I felt sure you would call on me soon.",
"Ah, captain ",
". What brings you to me?",
"Hello, sir. I'd like to talk to you.",
"I am at your service, ",
".",
"Where can I repair and equip my ship in #sRedmond#?",
"Is it possible to find a job here?",
"I met a sailor at the dock who was banned from his ship.",
"Right behind the city's gates, you'll find the shipyard manager's office. The local store is \nin the city's square, just front of the governor's residence.",
"I see. And where is the tavern?",
"Can I find a job here?",
"Thanks. Goodbye.",
"Young Windem's tavern is in front of the Governor's residence, \nacross the street from Thomas O'Reily's store.",
"Thank you. Farewell.",
"Can I find a job here?",
"Well, sometimes merchants charter their ships for the transportation of their goods, but I haven't had any such requests recently. \nYou ",
" could pay a visit to Governor #sgov_lastname#; he may have some work for you. \nOr, you can go to the tavern and talk with the merchants themselves - you'll usually find a few there.",
"As I said, sometimes merchants charter their ships for the transportation of their goods, but I haven't had any such requests recently.",
" Pay a visit to Governor #sgov_lastname#; he'll likely have some advice for you. \nAnd speak with the patrons in the tavern - you'll find all sorts of people relaxing there.",
"Where can I fix and equip my ship in #sRedmond#?",
"I see. Thanks.",
"I met a sailor at the dock who was banned from his ship.",
"Ask the tavern-keeper, Windem, and talk with O'Reily, the local trader.",
"Where can I fix and equip my ship in #sRedmond#?",
"I met a sailor at the dock who was banned from his ship.",
"Thanks for your advice. Goodbye.",
"Ah, that was probably Bloom. He was fired because he struck an officer. He's lucky they didn't hang him.",
"What happened?",
"Well, Bloom seems to be very sorry about all that...",
"I see. I've got a couple more questions for you.",
"That's kind of a complicated story. To tell the truth, I can't say that Bloom is guilty. \nYou see, he came to the defence of the barmaid in the tavern when a drunken navigator tried to put his paws on her. \nThat was honorable of him, of course - but Bloom is a hot-tempered fellow, and when the navigator insulted him, \nBloom decked the man.",
"I see. Well, Bloom seems to be very sorry about all that...",
"That's a shame. Thanks for telling me the story. Goodbye.",
"It's too late to be sorry now. He'll never work on a ship again.",
"Surely there's some way his punishment might be lifted, isn't there?",
"That's too bad. He seems like a good man. Well, I'll see you around, Laurence.",
"You know, ",
", maybe there is a way, at that. I might change my mind if some worthy man would vouch for Bloom.",
"Do you consider me a worthy man?",
"It doesn't seem likely that the poor fellow will find someone around here to do that for him.",
"I certainly do. Are you offering to vouch for him? Then I reverse my decision. \nSince you're vouching for Bloom, I'd recommend you hire him so you can keep an eye on him. \nIf he does something like this again, your reputation will suffer.",
"I'll keep an eye on him. Thank you, and goodbye!",
"Let me ask you something else, if I may.",
"You seem a respectable man, but I must admit I don't know you well enough \nto let you vouch for young Bloom. Please don't be offended, ",
", but\nhe'll have to find another patron.",
"Well, goodbye, Laurence.",
"Let me ask you something else, if I may.",
"Hey! You! It's a shilling to tie your boat up here... AND... as it's sinking, I shall be needing to know your name.",
"What do you say to THREE shillings... and we forget about the boat... and the name?",
"Welcome to #sRedmond# Mr. er... Smith. I have other business to attend to now, so I can't stand here all day chattering to you. So just make the payment and I shall be off.",
"Of course... now where is my money? Hey what are those sailors doing with those ropes up there?",
"What the... up to no good, no doubt. I'd better go and see what's going on.",
"Yes, yes. I'll pay you when you get back.",

};
