string DLG_TEXT[68] = {
"Hello fellow traveler. You look like you are looking for something, something precious. Maybe I can help you with that. For the right price of course....",
"What is it you sell?",
"I sell stories my dear. Are you interested in one of my stories?",
"I would like to hear a story.",
"Which story would you like to hear? It'll only cost you 10 coins. That's a fair price right?",
"Death the Sweetheart",
"Happy Boz'll",
"[placeholder]",
"[placeholder]",
"...",
"Sorry I don't have the money now.",
"I'm not interested after all.",
"There was once a pretty young girl with no husband, no father, no mother, no brothers, no kinsfolk: they were all dead and gone. She lived alone in a hut at the end of the village; and no one came near her, and she never went near any one. One evening a goodly wanderer came to her, opened the door, and cried, 'I am a wanderer, and have been far in the world. Here will I rest; I can no further go.' The maiden said, 'Stay here, I will give thee a mattress to sleep on, and, if thou wilt, victuals and drink too.'",
"The goodly wanderer soon lay down and said, 'Now once again I sleep; it is long since I slept last:' 'How long?' asked the girl; and he answered, 'Dear maid, I sleep but one week in a thousand years.' The girl laughed and said, 'Thou jestest, surely? thou art a roguish fellow.' But the wanderer was sound asleep.",
"Early next morning he arose and said, 'Thou art a pretty young girl. If thou wilt, I will tarry here a whole week longer.' She gladly agreed, for already she loved the goodly wanderer. So once they were sleeping, and she roused him and said, 'Dear man, I dreamt such an evil dream. I dreamt thou hadst grown cold and white, and we drove in a beautiful carriage, drawn by six white birds.",
"Thou didst blow on a mighty horn; then dead folk came up and went with us--thou wert their king.' Then answered the goodly wanderer, ' That was an evil dream.' Straightway he arose and said, 'Beloved, I must go, for not a soul has died this long while in all the world. I must off, let me go.' But the girl wept and said, 'Go not away; bide with me.' 'I must go,' he answered, 'God keep thee.'",
"But, as he reached her his hand, she said sobbing, 'Tell me, dear man, who thou art then.' 'Who knows that dies,' said the wanderer, 'thou askest vainly; I tell thee not who I am.' Then the girl wept and said, 'I will suffer everything, only do tell me who thou art.' 'Good,' said the man,' 'then thou comest with me. I am Death.' The girl shuddered and died.",
"That's the end of the story, I hope you liked it.",
"Thank you that was a wonderful story.",
"I'm not interested.",
"Wonst upon a time there was a Romano, and his name was Happy Boz'll, and he had a German-silver grinding-barrow, and he used to put his wife and his child on the top, and he used to go that quick along the road he 'd beat all the coaches.",
"Then he thought this grinding-barrow was too heavy and clumsy to take about, and he cut it up and made tent-rods of it. And then his donkey got away, and he didn't know where it was gone to; and one day he was going by the tent, and he said to himself, 'Bless my soul, wherever's that donkey got to?' And there was a tree close by, and the donkey shouted out and said, 'I'm here, my Happy, getting you a bit o' stick to make a fire.' Well, the donkey come down with a lot of sticks, and he had been up the tree a week, getting firewood.",
"Well then, Happy had a dog, and he went out one day, the dog one side the hedge, and him the other. And then he saw two hares. The dog ran after the two; and as he was going across the field, he cut himself right through with a scythe; and then one half ran after one hare, and the other after the other. Then the two halves of the dog catched the two hares; and then the dog smacked together again; and he said, 'Well, I've got 'em, my Happy'; and then the dog died.",
"And Happy had a hole in the knee of his breeches, and he cut a piece of the dog's skin, after it was dead, and sewed it in the knee of his breeches. And that day twelve months his breeches-knee burst open, and barked at him. And so that's the end of Happy Boz'll.",
"I'm having weird dreams about a giant plumed serpent. I thought that maybe you can tell me more about this creature.",
"Oh! Are you seeing Quetzalcoatl in your dreams? That's very interesting. I can't tell you anything about him though.",
"Why not you seem to know what I'm talking about?",
"I can't tell you, but I can show you!",
"Show me? How?",
"I think you are affected by him in some way, so when we bring you in a good trance you should be able to find the answers you are looking for inside yourself.",
"And how can we do that?",
"Well .... seeing as you need my help with this it's going to cost you.",
"How much?",
"Well first off all you will need to gather me some opium to get you in the right trance. There seems to be a bloke in the Smugglers Camp on this island who has some. Tell him I send you and he will sell it to you.",
"Is that everything?",
"Well of course not. You will also need to pay me for my services. This will cost you a lot more than the normal stories. Let's say 500, that sounds about right. Meet me back here once you've got everything you need.",
"Okay",
"I've got everything you asked me to gather. Can you now show me what these weird dreams mean?",
"Yes it seems you've got everything we need. I'll take the opium now, the money will come after we are done. This will take me some time to prepare. Can you meet me in the tavern in 3 days?",
"Ah you made it! Good, I've already arranged the room upstairs so let's go there! Wait you still have the money right?",
"Ofcourse but are you going to explain me what is going to happen?",
"Yes yes, but not here. Now come on.",
"Okay now it's time to tell you what will happen. I've created a potion from the Opium you gave me. This potion will bring you in a deep sleep. If the stories are true you will experience some weird dreams. These dreams should give you an idea of what is going on.",
"Do you know for sure this is safe?",
"My ancestors have been doing stuff like this for ages. Most people woke up.",
"Most? You mean not all of them?",
"Some got lost in the dreams and never came back. But I'm sure you will wake up. In the meantime I will stay here to make sure you are safe.",
"Okay let's get this over with.",
"Oh! You are finally awake! I started to worry. You've been sleeping for almost 12 hours!",
"WHAT! it only felt like a few minutes!",
"Did you see anything?",
"Yes, I saw Quetzalcoatl, he was in Cartagena and tried to hand me a book. But I couldn't hold the book and it fell to the ground.",
"Hmmmm..... Maybe you should go there. I'm not sure what good it will bring you, but it might give you some answers.",
"That sounds like a reasonable plan. Thank you for the help.",
"It's just business. I believe we agreed on 500 right?",
"Indeed we did, here it is.",
"I feel like this is more than just business. It doesn't feel right to just give you the money and leave.",
"So I'm not the only one having this idea? That's so great to hear. Captain I wasn't sure how long it would take so I booked the room for the whole day. That means we still have half a day left. Would you mind spending that day with this lonely girl?",
"I would love too",
"I'm sorry, that's not what I had in mind. Let's just keep it a business relation. Here is the money.",
"You forgot to bring the money? Are you stupid? I'll wait here, get the money as quickly as possible!",
"Captain, it's time to go. Thank you for this wonderfull day. But you really should be going now. I don't think these dreams are good. They must mean something.",
"Don't you want to go with me?",
"No captain, I have my life and you have yours. That's okay, it really is. I don't mind you leaving, just promise me once this is all over you come visit me again.",
"I will! That's a promise!",
"Ah my love, you have returned. Do you want to hear one of my stories?",
"I would love to tell you a story. Which story would you like to hear?"
};
