string DLG_TEXT[52] = {
"You are not a pirate lad and you will regret your intrusion",
"...",
"Hi, I've heard that you are an able captain and as me, you are an enemy of the French crown!",
"Your information is precise, captain!",
"You are not enough a good captain to be here in front of me. Get out if you want to live!",
"All right. I'll come back later.",
"My name is Mary Wood. I'm the captain of the Morning Star, a beautiful Brigantine!",
"Indeed?",
"Perhaps we could associate our ships and do expeditions together. With our two ships, we could make some great things and become a good strike force!",
"Is that a trick question? Keep talking.",
"I'm not interested. Sorry.",
"Well! Here is the terms! You won't have to provide goods for my crew during our association but you can assume the repairs of my ship in friendly ports if you want. right?",
"Will I have to pay salary for you and your crew?",
"No, of course and my crew will not be food on your rations in see but... Follow my advert! When you'll cease our partnership, all the plunder will be divide in two equal parts and if all the plunder won't be equal to ",
"Calm down. do you doubt of my loyalty? Your proposition sounds good to me man. When do we take see?",
"Sorry but I think I'm able to make expeditions without partner!",
"As soon as possible! I want to smell rapidly the beautiful perfum of powder and blood! Ah Ah!",
"Well but if i need to talk to you or stop our Partnership? How to proceed?",
"We'll meet here in town. This port is good protection from our ennemies. You couldn't Provide Planks, Sailcloth and munitions for my ship but each time we will spend few days here, My crew will automatically resupply my ship!",
"Aye! I hope that our association will remain engraved in the memory of nations as one of the worst of caribbean seas!",
"Here is a good safe anchorage. If we spend some days here, I will resupply my ship and make some repairs!",
"It would be a good thing to spend days here",
"We can't stay here! We should have to sail away!",
"The time has come to separate us and stop here our partnership my friend",
"How many days will we spend here?",
"1 day will be enough",
"5 days spent in a safe place will be very good for our crew moral!",
"I changed my mind!",
"In this case, i think the time has come to divide our gold in 2 equal parts!",
"It's time my captain!",
"You know, I think i will keep all the booty for me!",
"I changed my mind..Why do we have to separate us after all!",
". You are my brother captain and i'll be ever here fo you if you would sail with me again!",
"I'll thinking about it my friend. Hope to see you again one day!",
"Cutthroat! you are already dead!",
"We will see",
"My old friend! What a pleasure to see you alive! Which good wind brings you in those waters?",
"Only a friendly visit to discuss with my old friend!",
"I want to organise a new expedition with you captain! I have a lot of ennemies in these waters so your ship and your experience will be a help!",
"With the same terms of previous expedition lad? Fifty-fifty with a booty of ",
"Of course. are you doubting of my fidelity towards you?",
"all things considered, it will be for another time. i will think about it",
"Ahoy my friend! Let's have a drink to our new expedition! I began rusting in this port!",
"Let's have a drink to our gold!",
"You try to abuse me my friend! did you hide some gold from my look? If it's all that you have to share, I think that I'm going to keep all the booty for me and kill you right away!",
"You believe you'll kill me so easily captain?",
"Every French alive in this world is my ennemy and i've heard that you are a friend of the French crown! You are lucky to be ashore Lad! As long as you'll be accepted in the french ports, we shall have to make nothing together captain!",
" Aye! One day perhaps!",
" Gold minimum, I will cut your throat, brother!",
" For you and ",
" for me",
" gold minimum to be shared!",

};