string DLG_TEXT[89] = {
"Pie Iesu Domine..Dona aeis requiem. THUMP. (The monk pummels himself with a heavy book in an act of repentance..) Eheh? Don't interrupt my one man procession! ... ",
"Please forgive me, but you do not look quite like an average monk should look...",
"I'm sorry padre, please accept my apologies and this 100 gold for the poor of the archipelago.",
"Hmm, what should a monk look like?",
"Somewhat less self confident, a little more suppliant, and definately a lot less dangerous.",
"I don't know, but definitely.. well, I thought you were a walking sack of potatoes, ya know, with the silly sacklike cloak and all. Your head looked like a big rotten scurvy smitten potato",
"You are no monk! You are a spy! Perhaps even a looney masquerading as a potato sack! Shouldn't you be in Bedlam?",
"It was nice to talk to you, but I have to go now. Maybe we could meet again when you're a little more specific...",
"Good bye, Padre, or whatever you are...",
"Ah, you again, do you have another answer for me? How DO I look?",
"I don't know what you are, but you are not like the other monks I know I just can't shake tha feeling that yer too daft.",
"Spy? Spy! I'm a monk, I live quite piously, I obey my elders, I say my prayers and I'm almost completely chaste. Please shut the %&$#s_hash_#@ up you pirate %&$#s_hash_#@!!!",
"Ok, calm down. I don't want to have any trouble. I'm leaving.",
"Hey, you are unarmed. Shouldn't you be a little more careful talking in this way to an armed man?",
"Ah, you again, haven't you learned your lesson?",
"Please accept my apologizes. It was very kind to let me live. No spy would have done so willingly.",
"OK. Here are your weapons. I will ask my question again: how should a monk look?",
"Who told you that I'm unarmed?",
"I can't see any weapon!",
"And now I can't see your weapon anymore. I guess this is a lesson you have to learn: never judge a man based on appearances alone.",
"Ough... how did you do that? Where are my weapons?",
"Interesting. Could it be? Maybe. Now I will ask you a question: What is stronger, a fine sword or a feather?",
"The sword. Ever tried to fight against a sword waggling around a feather?",
"The feather, not in a fight, but on the long term it could kill more men than all swords put together.",
"Neither, it depends on the mind that masters the sword or the feather!",
"Congratulations! I'm sure you will win a lot of fights with your sword, but you will lose at last, for he who lives by the sword shall die by the sword.",
"I don't understand what you are talking about. I'm leaving...",
"What? You have spent some time thinking about my question again? Ok! Let's hear your answer: What is stronger, a fine sword or a feather?",
"Not bad, but why are you carrying a sword with you and not a feather? I'm not sure if this is really your answer.",
"I want to survive on the short term, too. Good bye... you damn pious burlap sack of potatoes.",
"You're walking on the smart side, aren't you? Can you prove that you are really that smart?",
"I hope so. What do you have in mind?",
"I offer ye these relics three, each with special powers but all with a great burden... ",
"Please be a little more specific!",
"If you take one you will not be able to leave the archipelago--and be able to come back and resume where you left off--until you give it back to a specific member of my order.",
"And the powers?",
"We will see if you are as smart as smart can be! It's for you to choose! Oh, and I'm out of Holy hand-grenades so don't bother asking.",
"I'll take the cross that will increase my combat skills.",
"I'm too weak to be a real swashbuckler, I'll take the one that will double my health.",
"The third cross will help me in commerce and trade whether legitimate or illicit? I need that!",
"The burden is too high, and I was looking for a Holy hand-grenade. Apparently you haven't any.",
"If you ever feel the need to leave the archipelago -and be able to resume where you left off, when you come back, return the relic back to the member of my order ",
"I'm sure that I'll find him, when I want to leave the archipelago. Thank you and farwell!",
"Come back if you change your mind. OR if you feel drastically burdened you could try destroying it in the fires of a certain Mount Doom, that would work. ",
"You are very kind to me. Good bye!",
"It's you again. Do you want to take the challenge? We will see if you are the mind that masters the powers wisely! It's for you to choose!",
"My order told me about you. Do you want to take the challenge now? We will see if you are the mind that masters the powers wisely! It's for you to choose!",
"I sense the aura of the burden you carry. It is difficult to carry one of our relics, isn't it? Do you wish to relinquish the cross and be able to leave the archipelago and yet resume where you left off, when you come back? ",
"Yes, it's time for me to go, but... I'LL BE BACK!!!",
"No, I will continue to carry the burden... and enjoy its powers too!",
"I sense the aura of the burden you carry. Do you want to rid yourself of it? You have to find the member of my order... ",
"I hope I survive until then!",
"If you ever want to take the challenge again, come back to me or another member of my order.",
"It's not ours to decide what the future will be! Perhaps we'll meet again, perhaps not.",
"I'll take the challenge again, when I'm back!",
"The burden is too much for me, I don't think that we will meet again. Good bye!",
"What a surprise! What a surprise! If it isn't Captain ",
"I know that voice! Lord Beckett... it is you isn't it?",
"Keep your voice down. Too many ears around this place. Sit down, sit down and we will talk.",
"Alright, but you owe me an explanation I think. Who are you? I have met the real Lord Beckett, and in the Governor's residence so? ...",
"Yes it is. But I am having a great problem with knowing who you are.",
"Firstly, I am Lord Beckett, or one of them... Lord Cuthbert Ulysses Beckett.",
"Cuthbert! You said your name was Cutler!",
"That is my brother, Lord Cutler Oswald Beckett.",
"This is going awfully slowly, M'lord... I suppose I should call you that again... What's going on here?",
"Alright, alright Captain ",
", I owe you that much. My brother and I are the younger twin sons of the Duke of Middlesex. Our elder brother will inherit the Ducal title so my brother and I each sought our fortune in commerce.",
"There's more of you! I'm not sure we should continue this conversation.",
"Patience, patience my dear fellow. It is only Culter and I in these waters. We both worked for the Honarable East India Company and things went well till we heard a story about the Chest of Cortez. It turned my brothers head and he is hell bent on finding it.",
"What's wrong with that. A spot of treasure hunting is what we are all about surely?",
"It has become all consuming with him, to the point where he will remove anyone who he thinks might be getting close to it before him... including me. And I am getting close with some of the information I have found.",
"You mean the documents I have been getting for you, don't you? They have something to do with it, don't they?",
"You are very smart Captain, which by the way, is why I chose you in the first place. I involved you to try to thwart my brothers plans, and yes, the documents are parts of a map to the treasure. When complete the location is revealed.",
"And there are four parts... right M'lord?",
"As sharp as ever Captain. Yes, four parts. I believe you have one part and I have another so we are half way there. I shall give you my part, here it is, I believe my brother's men are on my trail, hence the disguise, so it is not safe with me. You can return them both to me when we meet again. Keep them safe.",
"Meet again, M'lord, and where and when will that be?",
"Don't worry, I will find you. I am sure you have other things you need to be doing. So I will bid you goodbye for the moment Captain, I am expecting someone to meet me here. Keep the documents safe. In the meantime I will resume my disguise.",
"Er... Yes, M'lord... Goodbye for the moment.",
"That's better, we can see anyone approaching now.",
"That's as may be, but I still need that explanation.",
"We meet again M'lord. Your voice is becoming quite familiar. What are you doing on this island?",
"I came to collect some idols, but I believe you beat me to it. So I thought I'd sit here and see who came and went.",
"Ah! Your Lorship's intelligence is as up to date as ever.",
"Indeed, indeed. But to the point. It is time to prove our mutual trust. I know my brother sent you to get the idols, and I need to spoil his plans. So, Captain, let me look at the cargo of idols, I just need to know what's there before he does and that will take the wind out of his sails.",
"I don't know M'lord. That sounds awfully risky... for me.",
"How so? How so? He will never know someone just 'looked' at them. I just have a feeling that one of the boxes is empty, and I want to be sure.",
"Very well M'lord, I will trust you. Take a look.",
"Thankyou Captain. Thankyou. This will indeed alter his plans. Take this money to cover your inconvenience. You should go now, but have no fear we shall meet again.",
"I'm sure we will M'lord. I'm sure we will.",

};
