string DLG_TEXT[13] = {
"*Gives Jack's Compass*",
"Thanks",
"How're you doing, captain?",
"Fine, thank you. Is there anything I can do for you?",
"Perhaps. But there IS something I can do for you. Here. Take this. Perhaps you can find some use for it.",
"Thanks. Now what could I do for you?",
"I have been without a ship for too long. Would you please allow me to be your boatswain?",
"Yes, please. But you'd better be good.",
"No, thanks.",
"Don't worry about that. I'm just about as experienced as you are.",
"That sounds quite good. I'm looking forward to seeing you in action.",
"Take what you can!",
"Give nothing back!",
};