string DLG_TEXT[46] = {
"Hey, it's a hot time in the old town today, ain't it?!",
"Uh, yeah.",
"What do you want? If you're not going to join in the excitement, don't interrupt it.",
"You think this is fun, you scaly beast?",
"Excitement? Looks like you're about to burn someone.",
"So, you decided not to interfere? That's a wise choice. Now get out of here!",
"Are you looking for trouble?",
"I said get out, unless you want to join the old man!",
"Look, everyone saw you hit me first.",
"So what? You think someone's gonna rush to your aid? I see a lot of my friends here - don't see any of yours, stranger.",
"I won't need any friends when the soldiers show up.",
"Yeah? Where are they now? What makes you think they'd help you?",
"The most important thing is that they don't bother us.",
"Sure, join us! Where else can you see such a show?",
"Show? You call it a show when a man is being consumed by flames?",
"Hey, it's better than working in the port!",
"Yes, I can tell you fellows are bored to death.",
"You know, it's thanks to the likes of you that this colony is considered the most barbaric in the whole archipelago. Governor ",
"Robert Christopher Silehard",
" himself has complained to me about that many times.",
"Right. You brainless beasts of burden can't come up with any other entertainment for yourself.",
"Perhaps I can offer you something more exciting?",
"Wouldn't you rather have a drink...or six? I'm buying.",
"No real man would stand and watch an old gentleman being burned alive.",
"The governor himself? You're joking!",
"Do I look like I'm joking? He sent me here to see just how bad things had gotten. He's not going to care for my report.",
"You're lying. Can you guess what we do with liars around here? Get lost.",
"Can you guess what I do with men who speak to me that way, scum?",
"All right, all right! I don't want any problems.",
"Report? Don't make me laugh! The whole archipelago is swimming in piracy!",
"That may be, but old men aren't smoldering in every colony. Have you informed the Church of your plans to burn this man?",
"No need. I believe the Church will approve of our actions.",
"Well, well. What did you say your name was?",
"You're ruining everything, you know that? Just take the old man and go!",
"Now we're talking.",
"Do you know how much my friends and I can drink. What makes you think you can pay for all of us?",
"I've got 2000 gold that says I can. You could all drink yourselves unconscious with that kind of money.",
"No, I don't suppose I do have that kind of money, now that you mention it. But can you really see this execution as just a bit of fun?",
"Sounds good to me! But maybe we should burn the old man first...",
"Leave him for me. I'll take care of him.",
"Who did you call a beast?!",
"So you're deaf as well as stupid? I called you a beast. Only an animal could find a spectacle like this entertaining.",
"What are you doing here? You want trouble? Well, that can be arranged easily enough!",
"What? You'd hide behind your friends, would you? I should've expected as much from the kind of coward who would burn an old man for laughs.",
"You think I'm afraid of you? I'll be happy to correct that mistake!",
"Bring it on, animal!",

};