string DLG_TEXT[19] = {
"*blank, cowlike stare*... ",
"Hey... buddy... ya want a hit?",
"Stars, man, I can see stars! It's so... cosmic!",
"... I've got it! I can see so clearly now, it's all so simple! The secret to life... the universe... and everything! It's... *falls motionless* zzzz...",
"Yo, matey... spare a dime?",
"There's a nice lady walkin' around here somewhere with some great juice, man!",
"Another satisfied customer, I see.",
"Ooh, bawdy.",
"Uh... who let these lizards in here?",
"I would like to buy what you're having.",
"Aye, matey. Just be warned, not many people will buy this stuff. It will cost you ",
" per piece.",
"Okay, I'll buy 1.",
"Okay, I'll buy 12.",
"Okay, I'll buy 72.",
"Never mind, I'm not in the market",
"Here you go. If I were you, I would stay away from the guards while you have this on you and lay low for a while. They might come after you if they see you with this.",
"Thank you... I think.",
};