string DLG_TEXT[70] = {
"Welcome to the church, #saddr#.",
"You're not my father. Don't address me that way again.",
"Good day, father.",
"Why, you disrespectful heathen! Get out! You defile the house of God with your presence!",
"I wasn't planning on staying long, anyway.",
"May God bless you and your deeds. Have you come to me for some purpose?",
"I'd like to make a donation.",
"I'm here for confession.",
"I'm sorry. I must be going.",
"Not really. How does the parish fare?",
"I think the woman we talked about will soon come back to the church.",
"The woman we talked about - I wasn't able to change her mind. I'm sorry, father.",
"Oh! This is a great deed you've done, #saddr#. I'm glad to know a young sailor who doesn't wallow in sin as the others do.",
"I'm sorry, father. It turns out I've got no money.",
"Here's 100 gold for your good work.",
"I should think the Lord would look kindly on 1000 gold.",
"I'm doing well these days, so I'll give 5000 gold.",
"It's your decision, my #saddr#. It's never too late to change - and keep in mind that your good works will be taken into account at the time of your death.",
"My death is still a long way off, God willing! Let's talk about something else.",
"Sorry, father. I've got to go.",
"I thank you for your gift in the name of the Holy Church, #saddr#.",
"I need to talk to you, father.",
"I'm sorry, father, but I've got to go.",
"I thank you for your gift in the name of the Holy Church, #saddr#.",
"I need to talk to you, father.",
"I'm sorry, father, but I've got to go.",
"I thank you for your gift in the name of the Holy Church, #saddr#.",
"I need to talk to you, father.",
"I'm sorry, father, but I've got to go.",
"Of course, #saddr#. I'm listening.",
"I've changed my mind. Maybe some other time.",
"I have sinned, holy father...",
"It is in man's nature to sin, #saddr#. But to ask forgiveness is divine.",
"Yes, but I...I've plundered ships, and sent some to the bottom of the ocean. I've drawn my sword in anger and taken lives....",
"But there were no Frenchmen among them, were there?",
"Of course not, father.",
"Yes, holy father. Even Frenchmen.",
"Then God forgives your sins, #saddr#.",
"Thank you, father. I'll be going now.",
"What?! God will never forgive such a sin! Leave His house at once!",
"Goodbye, father.",
"It's all right, #saddr#.",
"Thank you, father. I'll be going now.",
"What are you saying? Is there anyone who doesn't come to church?",
"It's all right, #saddr#.",
"In that case, father, I'll be going.",
"Alas, there is one wayward girl - she leads a lonely life and it's impossible to persuade her to come to church.",
"That's a shame, father - but I'm sure sooner or later you'll change her mind.",
"Maybe it's possible to talk with this girl and persuade her to return to the flock.",
"I've tried many times, #saddr#, but to no avail.",
"Well, if you can't persuade her, I don't imagine anyone can. Farewell.",
"I could try, if you'd like. Sometimes people will speak with strangers in a way they would never speak even with their priest.",
"I'd be most grateful if you tried. This girl lives by the gates that lead to the heart of the city. Her name is ",
"Elzire Ayarai",
"Elzire Ayarai",
".",
"I'll do my best, father.",
"No, #saddr#. I don't believe you could change anything.",
"Very well. Goodbye, then, father.",
"That's too bad, #saddr#. To be honest, I had truly hoped you might help.",
"Farewell.",
"Oh, she's already been here. She even had me take her confession and asked for forgiveness. And she spoke very well of you.",
"I'm pleased everything turned out so well, father. Farewell.",
"I'm afraid ",
" gold is all I can afford just now.",
"I should think the Lord would look kindly on ",
" gold pieces.",
"I'm doing well these days, so I'll give ",
"But there were no Spaniards among them, were there?",
"Yes, holy father. Even Spaniards.",
};
