string DLG_TEXT[43] = {
"Welcome to the church, #saddr#.",
"You're not my father. Don't address me that way again.",
"Good day, father.",
"Why, you disrespectful heathen! Get out! You defile the house of God with your presence!",
"I wasn't planning on staying long, anyway.",
"May God bless you and your deeds. Have you come to me for some purpose?",
"I'd like to make a donation.",
"I'm here for confession.",
"I'm sorry. I must be going.",
"Oh! This is a great deed you've done, #saddr#. I'm glad to know a young sailor who doesn't wallow in sin as the others do.",
"I'm sorry, father. It turns out I've got no money.",
"Here's 100 gold for your good work.",
"I should think the Lord would look kindly on 1000 gold.",
"I'm doing well these days, so I'll give 5000 gold.",
"It's your decision, #saddr#. It's never too late to change - and keep in mind that your good works will be taken into account at the time of your death.",
"My death is still a long way off, God willing! Let's talk about something else.",
"Sorry, father. I've got to go.",
"I thank you for your gift in the name of the Holy Church, #saddr#.",
"I need to talk to you, father.",
"I'm sorry, father, but I've got to go.",
"I thank you for your gift in the name of the Holy Church, #saddr#.",
"I need to talk to you, father.",
"I'm sorry, father, but I've got to go.",
"I thank you for your gift in the name of the Holy Church, #saddr#.",
"I need to talk to you, father.",
"I'm sorry, father, but I've got to go.",
"Of course, #saddr#. I'm listening.",
"I've changed my mind. Maybe some other time.",
"I have sinned, holy father...",
"It is in man's nature to sin, #saddr#. But to ask forgiveness is divine.",
"Yes, but I...I've plundered ships, and sent some to the bottom of the ocean. I've drawn my sword in anger and taken lives....",
"But there were no #snation# among them, were there?",
"Of course not, father.",
"Yes, holy father. Even #snation#.",
"Then God forgives your sins, #saddr#.",
"Thank you, father. I'll be going now.",
"What?! God will never forgive such a sin! Leave His house at once!",
"Goodbye, father.",
"I'm afraid ",
" gold is all I can afford just now.",
"I should think the Lord would look kindly on ",
" gold pieces.",
"I'm doing well these days, so I'll give ",

};
