string DLG_TEXT[105] = {
"Good to meet you, ",
". My name is ",
", and I am at your service.",
"Thanks. I'm Captain ",
".",
"Glad to see you again, ",
".",
"You! I'd hoped you'd never darken my door again.",
"Good day, ",
".",
"Sorry about that, ",
"Do you want to see my goods?",
"Sure. Show me what you have in stock.",
"Not right now. Let's talk.",
"No, thanks. Maybe next time.",
"Are you looking to buy or sell?",
"I've got some goods I want to sell.",
"I'd like to buy some gear.",
"Neither, thanks. So long.",
"I'm all ears. What's on your mind?",
"I'm looking for work for my ship and crew.",
"I'm interested in a worker of yours, Clauss. I'd like to pay off his debt.",
"Pay for him? Sure, you can do that. He has worked off a part of his debt...",
"Enough. Just tell me how much money do I have to give you.",
"Let me check my papers...aha...yes.... Yes, here it is. Clauss owes me 2632 gold.",
"Hmm, the lad spent up a lot. Here's your money. Now tell me, where can I find Clauss?",
"I think I'll delay the payment a bit.",
"I've sent him to the tavern to get a keg of ale. You'll find him there.",
"Thanks.",
"I'm afraid I don't need your services just now.",
"That's too bad. Let's talk about something else.",
"I refuse to trade with a person of your reputation and relations. Now get out, ",
", before I call the guards.",
"Very well.",
"Now look who's here! The young Captain and the runaway brothel girl.",
"If you make a sound, that's the last thing you ever do shop-keeper!",
"You don't have any chance at all if you kill me Captain, they have already surrounded the store.",
"I think you are bluffing.",
"Maybe we could come to an agreement instead Captain. You're gold is always welcome!",
"I don't believe you, we'll try the door and run for the gate.",
"What agreement store-keeper?",
"Think we'd rather try another jump instead.",
"Maybe it's best to leave the same way we arrived.",
"You'll get no gold from me, but I agree to kill you!",
"Your puny stick is not gonna help you here",
"Prepare to die shop-keeper!",
"Sure, meet the brothel thugs outside the bedroom windows.",
"Oh shut up, old man.",
"The gate is too far away, Captain, not to speak about the blood-thirsty brothel guys waiting outside the door.",
"We'll see for ourselves, right?!",
"Go ahead, jump and break your bones, Captain.",
"Careful now or I'll break YOUR bones merchant!",
"I can show you the only safe way out of here Captain.",
"If I should believe you, what's your prize for that store-keeper?",
"You seem to be a reasonable #sgender#, Captain. For the low cost of half your gold you both may survive this little incident.",
"You must be joking! Forget get it!",
"You want half of my money - tell me - how do I know you won't alarm the boys outside immediately after we have left?",
"I'm no murderer like others in the town. I'm only trying to run some decent, well hmm yes, business in this dirty town.",
"Well, I don't trust you, killer or not.",
"But you have to, Captain, they're gonna smash the door to pieces any minute!",
"No, we'll do like this: You're gonna make us company for a while, fat man!",
"If you give me the money first Captain, I'll follow you out.",
"Not so fast store-keeper, first you shall tell us how to escape from this town.",
"You really enjoy doing business, right, Captain?",
"For the last time spit it out or I'll run you through!",
"Very well then, I have a key here in my pocket. It's the key to the roof, from up there you'll have no problem jumping to the shipyard roof.", 
"Here, take the gold. Hurry now and show us the way!",
"Hmm, there is only one thing, Captain...",
"No more business I hope.",
"I'm afraid so, Captain. Unfortunately you have not paid yet for that gun you 'bought' here earlier today...",
"Quick, merchant, how much for it?",
"It's an excellent weapon, Captain. Shall we say ... the rest of your gold?",
"I don't believe it!!",
"For that reasonable price I get you some new ammunition as well.",
"Very generous indeed. Take the money for God's sake and move your feet!",
"Oh by the way, Captain, there is a conference held in the hall upstairs and ...",
"No more talking please!",
"This is very important, kind #ssir#. I'm not sure the meeting will let us pass.",
"I paid (a fortune) for the way out so see to it or I ...",
"The best would be to use gowns, like the Brothers do.",
"I'm not afraid of some harmless monks!",
"Harmless? It's the annual meeting of the Brothers of ...",
"I really don't care what monastary they come from. NOW GET ON YOUR FEET MAN!",
"No need to get upset, young Captain. I have some clothes ready for you and the girl if you want #ssir#.",
"Oh, let's take them, maybe that will put an end to this conversation.",
"Take? I wouldn't use that word, Captain, rent is more appropriate I figure. This is a Store after all.", 
"It's easy to remember that you know.",
"Do we have a deal then, Captain?",
"Only one thing .... HOW MUCH??",
"I provide these fine clothes as a guarantee for your safety, my Captain. Why not just give me YOUR clothes as an exchange?",
"No! Enough of this! To the roof at once.",
"Ok ok ok, I trade my Captains uniform for a pair of robes.",
"Remember I warned you, Captain...",
"Oh shut up now.",
"Very wise indeed, #ssir#. There is a gown in the bedroom, on the wall behind the door.",
"Caroline, please change in there while I keep an eye or both on this 'gentleman'.",
"Captain, please take a look in the wardrobe behind you, while I change clothes myself.",
"Right.",
"Hurry, Captain, the Brothers may be here any moment!",
"Take it easy shop-keeper, are you alright Caroline?",
"Captain, I assure you it is perfectly safe for you and the girl.",
"Not one single word from you fatman...", 
"But Captain, I...",
"JUMP NOW!",
"Agreement you say - what exactly do you have in mind?",

};