string DLG_TEXT[134] = {
"I heard that you want to see me. So, what business do you have with me?",
"I'd like offer my services.",
"So you're a ship's captain then. What is your name?",
"My name is ",
", captain of the '",
"'.",
"Good, I'll remember your name. Now, what brings you here?",
"I'd like to talk business with you.",
"Nothing. I'll take my leave, if you'll allow me.",
"You can leave. But don't disappear completely, it's possible I'll have plans for you.",
"As you say, #saddr#.",
"I'm listening. What brings you here?",
"Business #saddr#.",
"I'm leaving.",
"Then let's talk business.",
"I am here on behalf of those women standing by your entrance.",
"Your mission is a success. The missing children have been returned to their parents",
"I want to talk about a man who finds favor from your grace.",
"Your mission is accomplished, #saddr#.",
"I don't have anything to discuss with you at the moment, #saddr#",
"Yes, I already know that, here is your reward. I hope that in future I will be able to use you.",
"Any time, #saddr#",
"So, who do you want to discuss.",
"A buccaneer, #sBernardo Gamboa#, #saddr#.",
"",
"",
"Ah. That man?! And what do you want me to say? As far as I know, his reputation is stainless...",
"You would be wrong. From what I know he kidnapped a girl from your town.",
"Ah, ah, ah. Are you sure about that? I don't want to insult him unjustly.",
"If you don't mind, I will investigate this privately. No one will know of your involvement. If he didn't kidnap this girl, your relationship with him will remain intact, if he did, then you would show to everybody how just and powerful you are.",
"Hmmm... That is not unreasonable. Indeed, I don't risk anything in this case. You may find out what's going on. If your mission ends successfully, I'll reward you. But, since this is your initiative, it will be a modest sum.",
"Thank you #saddr#.",
"Remind me, what were we discussing?",
"We were talking about a kidnapped girl.",
"Ah, yes, I recall. As I understand, she really was kidnapped.",
"Yes. The scoundrel didn't want to give the girl back and was slaughtered by his own men.",
"Well, no pirate - no problem. Here is your reward. You can leave my room now...",
"As you please.",
"Ah, that's what you wanted to discuss...",
"I don't understand why you don't take this more seriously. Isn't it your responsibility to provide for safety of the colony's citizens?",
"Captain, I'll forgive your criticism of me this once. Don't do it again if you want find favor in this office. \nAs to those women... I can tell that you are a smart man, so, I will tell you something.",
"I am all ears.",
"Two soldiers were found dead today. One of them had a piece of a crimson fabric in his hand. \nSeveral hours before they were discovered a frigate was spotted sailing away from the island under full sail.",
"And this halts your investigation?",
"Well... It's obvious the kidnapped children were taken away from the island. Under the circumstances the search isn't worth the money that will be spend on such an expedition. \nMoreover, they could be anywhere. You should understand that Captain. The sea offers many places to hide. \nAnyway, if you are so touched by the grief of those women, I offer you a challenge to find their children. \nI promise that if the search will be successful, I'll show my gratitude to you.",
"All right, I agree, but first I'd like to know where I can find a witness who saw the frigate.",
"No, I don't want to spend my time on such nonsense.",
"You accept? Perfect! You can find the witness in the tavern. It was a merchant captain who sighted that ship.",
"Thank you, may I take leave of you now?",
"I wish to join the Brethren, sir.",
"The Brethren is always glad to accept new captains into the fold. ",
"We are",
"n't",
" currently at war with ",
"the ",
"any nation",
". Of course,",
" but",
" all pirate enemies are to be sunk on sight.",
"I'll make you proud, sir.",
"How am I doing, Sir?",
"You've sunk ",
" French ships, ",
" pirate ships, a total of ",
" ships.",
"Thank you.",
"I hope you have no qurrel with my service, Sir.",
"Indeed not, captain! In fact, it is my pleasure to welcome you into the Brethren. You will be rewarded for each ship you sink in the service of the Brotherhood.",
"I am honored, Sir, and will endeavor to live up to the chief's trust in me.",
"I'd like to pick up my wages, Sir.",
"Well, you've sunk ",
" French ships, ",
" Pirate ships, ",
" total ships. Your current wages are ",
", so a total of ",
"Thank you sir.",
"Traitorous scum! Sink your countrymen's ships, will you? You are hereby discharged from the military, your name struck from the roll; and I never want to see your face in this town again!",
"...",
" since last time, here's ",
" gold",
"I've heard I'm up for promotion.",
"You are indeed! Excellent work. Your new rank is ",
"Thank you Sir.",
" Spanish ships, ",
" English Ships, and ",
"Oh yes? I have a proposition for you, captain.",
"Indeed?",
"I have learned that you completed the task successfully; my congratulations, captain! Here is your reward.",
"My thanks; It was a pleasure to aid you.",
"You must destroy the ",
" vessel ",
"quest pirate",
" menacing the shipping off ",
". If you sink her, I will reward you the hefty sum of ",
" gold. What say you, captain?",
"I'll deal with her.  You can count on that.",
"I'm afraid I can't help you.",
"I want to make peace with the Brethren.",
"I'd like to know about #sgov_nation# relations with the great powers.",
"I want to join the Brethren of the Coast.",
"Ah, ",
", kind of you to stop by. I'd like you to meet my ",
". She'll come in once we've finished business.",
"I can no longer serve ",
", sir.",
"I'm through serving ",
"As insurance that you are an able captain, and to recompense my time in presenting your case to ",
", I must ask you for ",
" gold.",
"Not a chance.",
"Very well.",
" In light of your previous service, ",
" grants you the rank of ",
"You have harmed ",
", and ",
" does not forget his enemies. Leave at once, or the guards will toss you out on your ear!",
"...",
"You have caused ",
" great harm, captain, but ",
" is willing to overlook your past transgressions... for a price: ",
"Very well, Sir. I accept.",
"A pleasure, ",
"And you, sir.",
". In addition, you are awarded ",
" acres of land by order of ",
"Are you sure, ",
" will be sorry to lose your service.",
"Yes, I am.",
" does not take kindly to turncoats, ",
"Uh, never mind.",
"Very well. But I hope you will reconsider, in time...",
"Goodbye, ",
"Huh?",
"Tough.",

};
