string DLG_TEXT[92] = { 
"I'm told you've gone to great lengths to request an audience. My name is ",
". Now, if you please, tell me the purpose of your visit, ",
".",
"My name is ",
".",
"Ah, it's you again. What brings you here this time? ",
"I'd like to talk to you about some business.",
"I'm sorry, but there are things that I have to do.",
"So, why do you distract me from the very important affairs of state?",
"I'd like to talk to you about a small piece of business.",
"I'm just here to pay my respects. Nothing more, ",
"In that case, please leave my study and let me get back to more important matters.",
"Yes, of course. Sorry I disturbed you.",
"I'm listening, ",
".",
"I'm sorry, but I don't have anything to talk about right now.",
"I wish to defect to Portugal.",
"Indeed? Very well, you are now a Portugese citizen.",
"I thank you for your infinite kindness, sir.",
"Oh yes? I have a proposition for you, captain.",
"Indeed?",
"I have learned that you completed the task successfully; my congratulations, captain! Here is your reward.",
"My thanks; It was a pleasure to aid you.",
"You must destroy the ",
" vessel ",
"quest pirate",
" menacing the shipping off ",
". If you sink her, I will reward you the hefty sum of ",
" gold. What say you, captain?",
"You shall not hear of her again, that I promise.",
"I'm afraid I can't help you.",
"I crave forgiveness, your Excellency.",
"I'm interested to learn about French relations with other nations.",
"I'm looking for a Letter of Marque.",
"Ah, ",
", so good of you to stop by. I'd like to introduce my ",
". She'll come in once we've finished business.",
"I've heard I'm up for promotion.",
"I can no longer serve ",
", your Excellency.",
"I'm through serving ",
"As insurance that you are an able captain, and to recompense my time in presenting your case to ",
", I must ask you for ",
" gold.",
"Not a chance.",
"Very well.",
" is always pleased to accept new captains into her service. ",
"We are currently at war with ",
"",
"no great power, but ",
". Of course, ",
"Pirates are always to be sunk on sight.",
" In light of your previous service, ",
" grants you the rank of ",
"I'll make you proud, your Excellency.",
"You have harmed ",
", and ",
" does not forget his enemies. Leave at once, or the guards will toss you out on your ear!",
"...",
"You have caused ",
" great harm, captain, but ",
" is willing to overlook your past transgressions...for a price: ",
"Very well, Sir. I accept.",
"A pleasure dealing with you, ",
"And you, your Excellency.",
"You are indeed! Excellent work. Your new rank is ",
". In addition, you are awarded ",
" acres of land by order of ",
"Thank you, Sir.",
"Are you sure, ",
" will be sorry to lose your service.",
"Yes, I am.",
" does not take kindly to turncoats, ",
"Uh, never mind.",
"Very well. But I hope you will reconsider, in time...",
"Goodbye, ",
"Huh?",
"Tough.",
"Yes, captain? What do you want?",
"I am in search of the French frigate 'La Foudre'. She sailed here a couple of days ago. Has she arrived yet?",
"No, I have not seen any frigate here. I am still waiting for a convoy that was supposed to be here a fair while ago.",
"Are you sure? #sHavana# Port Admiral Talicerdor assured me she set sail to #sMarigot# looking for that very convoy.",
"All that I can say is that the convoy was supposed to go to #sHavana# to get supplies from the Spanish and then sail the supplies here to help us with the Dutch.",
"Ah well the governer of #sFalaise De Fleur# has sent me to investigate as his daughter was on one of the ships in the convoy.",
"That is not good news, sorry I can't be of more assistance.",
"Thanks for your help anyway, I hope I can pick up the trail soon. Goodbye.",
"Well, well, well. A thief... I'd even say petty thief, and a captain. Shame on you, ",
"Allow me, I'm not guilty of anything!",
"And #spronoun# persists? Your guilt has been proven, and there is no doubt that you stole Jean Maginot's family ring!",
"But I didn't steal it! I demand an investigation! After all, I'm a captain. Is my word worth nothing?",
"You're tiring me. Guards, take him away!",
"Yes. But... the devil...",
};
