string DLG_TEXT[26] = {
"Just play every hand, you can't miss them all.",
"A pair of balls beats everything!",
"It's morally wrong to let a sucker keep his money.",
"In the long run there's no luck in poker but the short run is longer than most people think.",
"You show your mettle by what hands you fold not what hands you play.",
"Poker is war. People pretend it is a game.",
"Poker is a hard way to make an easy living.",
"The beautiful thing about poker is that everybody thinks they can play.",
"If you lose your head you will next lose all your chips.",
"Poker is 100 percent skill and 50 percent luck.",
"When a player with money meets a player with experience, the player with experience leaves with the money and the player with money leaves with experience.",
"The cardinal sin in poker is becoming emotionally involved.",
"Don't challenge strong players, challenge weak ones. That's what they're there for.",
"Whoever coined the phrase 'a man's got to play the hand that was dealt him' was most certainly one poor bluffer.",
"Poker is a lot like sex. Everyone thinks they are the best, but most don't have a clue what they are doing.",
"Old card players never die, they just shuffle away.",
"The rule is this: you spot a man's tell, you don't say a word.",
"Nobody is always a winner, and anybody who says he is, is either a liar or doesn't play poker.",
"Poker is a fascinating, wonderful, intricate adventure on the high seas of human nature.",
"A faint heart never filled a spade flush.",
"Dogs are lousy poker players. When they get a good hand, they wag their tails.",
"What I know about poker you can fit in a thimble with room left over, but I'm learning.",
"Right, err OK.",
"Err right, OK.",
"Don't let it get to you.",
"And?",
}