string DLG_TEXT[60] = {  
"Can't you see that I'm on duty! Don't bother me.",
"All right, all right.",
"Who are you?!",
"I... well... it's...",
"Wait a minute, sir, we have a few questions for you.",
"Yes?",
"Are you ",
"That's me, what exactly is the problem?",
"We'd like to search you because you're suspected of stealing.",
"Really, it's even funny! But if you insist, then please search.",
"To have some soldier go through my pockets?! Are you out of your mind?!",
"Thank you for your cooperation. So... hmm... hmm... yeah... and this thing belongs to you, too?!",
"This? The ring? Ahem... I have no idea how it ended up in my pocket.",
"Well, then, I suggest you come with us.",
"What the?! All right, all right, don't grab your swords, I'll obey, I'm innocent.",
"No way! This is all a set-up and I'm not going anywhere with you!",
"Okay, now hand over your weapons, please.",
"Here you are, I have nothing to fear.",
"My sword? Don't you want too much?!",
"Thank you, now come along...",
"I'm following you.",
"In that case, we'll have to detain you by force.",
"Ha! Try it!",
"It's just that someone wants you dead. Say hello to the devil, sucker.",
"Devil!",
"Uh. I see I'm disturbing you... Well, shall I go?",
"I want to report a theft, officer.",
"(To Jean Maginot): You are suspected of smuggling and theft of personal property from this man.",
"(To Jean Maginot): You are suspected of stealing personal property from this person.",
"Bah! What audacity! You have been declared an enemy of the state, a reward has been placed on your head, and you want to inform me about the theft?! Guards!",
"Devil... I didn't think...",
"What does this have to do with me? Go to a civil judge.",
"Should I, the captain, appeal to a civil judge? Well, you have order here!",
"Oh, I'm sorry, I didn't know... this fact changes the matter and I'm listening to you carefully, monsieur.",
"From time to time I deal with Jean Maginot, the store owner... Don't get me wrong, nothing illegal...",
"Please continue.",
"So this time I stopped by to ask him what he had new and he offered to sell me some sandalwood!",
"But the thing is that we don’t get along very well, and he’s always trying to shortchange me.",
"Are you sure about this?!",
"More than that, officer! And when I told him it was against the law, he got really mad at me. We argued, and when I left the store, I found my ring and wallet missing.",
"Let's go with you to the store to deal with the situation on the spot.",
"I'm following you, officer.",
"Continue...",
"In general, we quarreled a lot, and when I left, I discovered that some of my personal belongings were missing.",
"Let's go with you to the store to deal with the situation on the spot.",
"I'm following you, officer.",
"(To Jean Maginot): That's what we will check. Mind if I search your belongings and the store premises?",
"(Jean): I protest! Why should I be subjected to such humiliation?",
"(To Jean Maginot): Your lack of cooperation doesn't play into your hands, monsieur. Like it or not, I'm going to search you and this store.",
"(Jean): Ah, all right! Look, it's up to you!",
"(Some time later, to Jean Maginot): Well, well, well... These are the items belonging to the #snoble# who came with me, and there's contraband in your basement.\nI'm sorry to disappoint you, but until the official investigation is complete, I'm closing the store and I'll ask you to come with me.",
"(Jean): I am not guilty! I was tricked!",
"The court will sort it all out. And now I’ll ask you, Jean, to come with me, and you, #ssir#, I’ll ask you to leave the store.",
"Okay...",
"(To Jean Maginot): We’ll check this now... so... what is this? Is this yours?",
"(Jean): N-n-no... I don't know how I got it...",
"(To Jean Maginot): Well... theft... is, at a minimum, confiscation of property and hard labour...",
"(You, interrupting the officer): Uh-uh! Hard labour? Maybe we can make a deal with him. The quarry is too harsh a punishment.",
"Well... I see no reason to disturb you.",
"Thank you, officer.",
};