string DLG_TEXT[80] = {
"Shove off, don't bother me.",
"...",
"Oh come now, dear cap'n. I know what interests you.",
"Excuse me, cap'n, but I've got some information that may interest you. Things that may help you out.",
"What might that be?",
"And what could you possibly have that would be of interest to me?",
"Ah! Hee-hee. Don't be getting ahead of yourself, cap'n. First, let's discuss payment. I promise you won't be able to find out anything without me.",
"Here to strike a deal, cap'n? A fistful of coins in trade for some information about Mr. Rheims?",
"Remind me. How much do you want?",
"Are you ",
"?",
"Perhaps. Do you know anything about Indian trinkets?",
"I do indeed, #ssir#. And a bit more on the topic, if you follow my meaning.",
"I can show you the way, but guiding you along these treacherous paths will cost you some money. If you'd rather go alone, I'll show you the way, and you can head off yourself.",
"You'd better come with me and show me how to get there.",
"Tell me how to get there, and I'll go by myself.",
"Don't worry, cap'n, we'll be there soon.",
"We'd better...",
"You've been falling behind, captain. Keep pace.",
"This is ridiculous. I think you'd better tell me where we are.",
"Oh don't try and hold out on me. I know what you're up to. Maybe I'll just take all your money myself.",
"What?",
"Not so fast, ",
", it will cost you 100 gold.",
"Fair enough. Here's your money.",
"You want too much! Just give me directions and I'll find it myself.",
"Ha! You're cheap or stupid, maybe both. All right, listen. Go deep into the jungle now till you see the fork.\nOne path goes to the left and another one straight. Choose the one that goes straight.\nLater you'll see another fork and you should keep going straight again.\nWhen you reach the third fork turn to the left, you'll be right where you ought to be.",
"That's a lot to remember. I hope I won't get lost.",
"Great, let's go now.",
"Show me the way, but no tricks. I'll keep an eye on you at all times. ",
"Yes. Let's head on, there are many who'd like to eavesdrop on us.",
"And where do you propose we go? I'm not...",
"Calm down, I am not going to hurt you. We'll just take a walk.",
"All right, but keep in mind I know how to defend myself.",
"Sure, sure, calm down, I can tell you're an able #sgentleman#. Come now, enough chat, let's head on.",
"Lead the way.",
"Here we are. And since I have things to do, I'll leave you now.",
"Goodbye.",
"Let me be clear. Give me your money!",
"I warned you, I'm capable of defending myself. You're about to find out how capable I really am.",
"I know who you're are looking for. I can help you.",
"I know who you're are looking for. I can help you.",
"What do you know?",
"Tell me what you know.",
"Hey, let's discuss payment first. Do you think I am going to give you this information for free?",
"Hmm...I think I deserve a reward for my services.",
"How much do you want?",
"Well, how much do you need?",
"Give me 1500 gold and I'll tell you everything I know.",
"Nothing much...just 1500 gold.",
"Take your money.",
"Here, take it. Now tell me everything you know about this fellow.",
"That's quite a sum. And perhaps it's not worth that much to me...",
"Don't you think that that's a bit too much?",
"You've a fine touch for extortion. But have you considered what would happen if I don't want to pay you so much gold?",
"No money - no information. Come back when you can pay me.",
"If it's important to you, you'll have to pay me sooner or later.",
"Take your money.",
"Here, take it. Now tell me everything you know about this fellow.",
"Then I'll return if I still need that information.",
"Why should I believe that you're the only blowhard who can tell me what I need to know.",
"That's quite a sum. And perhaps it's not worth that much to me...",
"I traded a few words with a sailor from that fellow's crew, and he told me that they were headed for #sisland_Conceicao#.\nHe said that they had some business with the head of the local smugglers named Desmond Ray Beltrop.",
"Great! Now step aside now, I am in a hurry.",
"I'll check it out. If this your information proves worthless, I'll return and I won't be so polite. Is that clear?",
"What do you mean?",
"Let me be clear. Do you want to live? Now do you understand me?",
"I don't have that much money!",
"All right, then give me all you have and tell me what you know.",
"I don't believe this, you, you...you're threatening ME?",
"Seems the appropriate thing to do. Now give me your money now and tell me everything you know.",
"Unbelievable. They were right about, you, hard as nails. Here, take it. That's all I have.",
"Well, that's certainly not much. I hope your information about where Rheims was heading is worth more.",
"Raoul Rheims",
"All right, all right, calm down. I am going to tell you everything right away.",
"Hurry up!",
"Ah, you filthy swine! I'll make you lick my boots clean!",
"Don't you think that's going too far?",
"...",
"...",

};
