string DLG_TEXT[59] = {
"Leave us.",
"...",
"Not so fast, ",
"! You don't think you can avoid us, do you?!",
"I don't think I want to talk to you.",
"Then make it quick, I'm in a hurry.",
"I don't think you'll be going anywhere. Now give us the letter that you're carrying.",
"Maybe we could just drink a mug of ale and be on our way? No?",
"What do you want from me?!",
"Tell me where your hideout is, and I'll let you die a quick death.",
"What do you want from me, you swine?",
"We're here to set you free.",
"What do you want from me, you swine?",
"We're here to set you free.",
"We are getting close to the colony. So far, you haven't seemed to be very trustworthy. Let's see if you'll behave yourself.",
"As you wish.",
"So, you were telling the truth. You are really familiar with our brotherhood. I still don't know when and how you joined us, but for now it doesn't matter. The ritual will start soon. We need to get to the cave. I'm sure you won't object to escorting me and several local people to the temple.",
"Not at all, just tell me where we are going.",
"A small island nearby. The temple is situated there.",
"Then I have what I needed. Now it's your time to die.",
"What?! Then you are...",
"...Not who you think! En garde - brother.",
"In that case, once we land I had better see you at the tavern.",
"Well.",
"That's so nice. And why have I been granted that honor?",
"There's no time to explain. At any moment they may discover that your release papers are fake.",
"Is that so? Well, I will allow you to escort me to the Spanish colony on #sisland_Isla Muelle#. After that I will get to the bottom of this matter, and decide what to do about you.", // <--Cat
"As you wish.",
"You can't intimidate me! I'm not afraid of death!",
"Hm...indeed...",
"What's death to me! It will release me to take my seat beside my master!",
"Okay, so you're not afraid of death. How does life in this cell suit you?",
"...",
"Perhaps this cell is too comfortable for you. Perhaps you'd prefer something more damp and dark.",
"...",
"Perhaps we could flood the floor with cold water, so you won't be able to rest...",
"Stop! I will tell you everything. What do you need?",
"Where is your hideout, you excremental pestilence?", // <--Cat
"Near the Spanish colony. On... cough... Puerto... cough... no-o-o-o.",// <-- PW
"What? Ach! Villainous lily-livered snipe!", // <--Cat
"Stop fooling around! I'm going to count to three, give us the letter, or else! One...",
"Three!",
"You're carrying a certain letter! We need to read it. \nDon't worry, we've got a copy of the stamp it's sealed with. I promise the client won't notice. \nDo us this favor and we will pay you 1000 gold. What do you say?",
"What do I say? Hmm, how do I put it...? NO! And go stick your stamp somewhere warm and cozy.",
"Hmm... 1000 gold... Sounds tempting. I think we have a deal. Here's the letter.",
"You're a wise #sgender#, ",
". Here's your money. Now we'll have a look at the letter. \nUh-hum, yes... I thought so... Now, they're wrong about this... So, I've learned all I need to know. Now...to seal the letter.... See, the stamp is identical? You may go.",
"All right.",
"Then we'll be forced to kill you.",
"Try it!",
"The warden's dead, so you belong to me. Now come along and show me to the Satanists' lair!",
"Hah, head to the small island south of #sisland_Isla Muelle#. There my companions will destroy you!", // <--PW
"Okay, whatever... Just come with me.",
"That's so nice. And why have I been granted that honor?", // Cat --> 
"There's no time to explain. I've intimidated the guards for now. After they stop pissing in their pants, they may gather together enough courage to thwart any attempt to free you. We have to go NOW.", 
"Pah, water? Water does not scare me nor quench the sacred fires that burn within me!",
"Fine, I grow weary of this. Perhaps I should just tickle you with my blade, hm?", // <--Cat
"Any orders, master?",
"None. Don't disturb me.",
};
