string DLG_TEXT[52] = {
"You are not a pirate, #sladlass#, and you will regret your intrusion",
"...",
"Bonjour, lad! Here's my Lair! I've heard that you are an able captain and as me, you are an enemy of the Spanish crown!",
"Your informations are precise, captain!",
"You are not a good enough captain to be here in front of me. Get out if you want to live!",
"All right. I'll come back later.",
"My name is Robert LeNoir. I'm the captain of the Trompe Mort, a good Shnyava. Excuse me for my bad English, capitaine!",
"Never mind, captain!",
"Perhaps we could associate our ships and do expeditions together. With our two ships, we could make some great things and become a good strike force!",
"Is that a trick question? Keep talking.",
"I'm not interested. Sorry.",
"Bien! Here is the terms! You won't have to provide goods for my crew during our association but you can assume the repairs of my ship in friendly ports if you want! Right?",
"Will I have to pay a monthly salary for you and your crew?",
"No of course, and my crew will not be using your rations at sea but... Follow my advert! When you'll cease our partnership, all the plunder will be divided in two equal parts and if all the plunder won't be equal to ",
"Calm down. do you doubt of my loyalty? Your proposition sounds good to me, man. When do we take see?",
"Sorry but I think I'm able to make expeditions without a partner!",
"As soon as possible! I want to smell the beautiful perfume of powder and blood soon! Ah Ah!",
"Well, but if I need to talk to you or stop our partnership? How to proceed?",
"We'll meet here in my Lair. This place is quiet and you will at home here as long as you will, be my friend. You won't have to provide planks, sailcloth and munitions for my ship, but each time we will spend few days here, my crew will automatically resupply my ship!",
"Aye! I hope that our association will remain engraved in the memory of nations as one of the most fearsome of the Caribbean seas!",
"Here is a good safe anchorage. If we spend some days here, I will resupply my ship and make some repairs!",
"It would be a good thing to spend days here",
"We can't stay here! We should have to sail away!",
"The time has come for us to separate and end our partnership, my friend",
"How many days will we spend here?",
"1 day will be enough",
"5 days spent in a safe hidden place will be very good for our crew moral!",
"I've changed my mind!",
"In this case, I think the time has come to divide our gold in 2 equal parts!",
"It's time, my captain!",
"You know, I think I will keep all the booty for myself!",
"I've changed my mind..why do we have to sail separate ways after all?",
". You are my fellow captain and I'll always be here for you if you would sail with me again! Bon vent à toi!",
"I'll thinking about it, my friend. Hope to see you again one day!",
"Cutthroat! you are already dead!",
"We shall see",
"My old friend! What a pleasure to see you alive! Which good wind brings you in those waters?",
"Only a friendly visit to discuss with my old brother!",
"I want to organize a new expedition with you, my #sladlass#! I have a lot of enemies in these waters so your ship and your experience will be a help!",
"With the same terms of previous expedition, #sladlass#? Fifty-fifty with a booty of ",
"Of course. Are you doubting of my fidelity towards you?",
"All things considered, it will be for another time. I will think about it",
"Ahoy my friend! Let's have a drink to our new expedition! I've begun rusting in this little house!",
"Let's have a drink to the wench of #sTortuga#!",
"You try to cheat me, my friend! Did you hide some gold from me? If it's all that you have to share, I think that I'm going to keep all the booty for myself and kill you right away!",
"You believe you'll kill me so easily, my #sladlass#?",
"Every Spaniard alive in this world is my enemy and I've heard that you are a friend of the Spanish crown! You are lucky to be ashore, #sladlass#! As long as you are welcome in the Spanish ports, we shall have to make nothing together captain!",
" Aye! One day perhaps!",
" gold minimum, I shall cut your throat, captain!",
" For you and ",
" for me",
" gold minimum to be shared!",

};