string DLG_TEXT[60] = {
"Ah! A new visitor in my tavern! Welcome, ",
"! The finest hospitality in the archipelago is at your disposal!",
"Hello. My name is ",
".",
"Thank you. My name is ",
".",
"You're most welcome. Please, have a seat, drink some good rum, try one of my specialties! You'll be glad you did.",
"I'm glad to see you again, ",
". Take any of the free tables and rest your bones.",
"Oh, it's you! Haven't seen you for ages. Can I start you off with a glass of wine to wet your whistle?",
"If it's all the same to you, I'd like to get straight to business.",
"Time is short, friend, and I have serious matters to discuss.",
"I'm sorry. I'm too busy for hospitality at the moment.",
"Settle down. I just dropped in to see who was here; I'm already leaving.",
"Pleased to meet you, ",
". My name is ",
".",
"Of course, ",
", you're the boss. How can I help you?",
"I'm looking to add to my crew. Could you point me to anyone who might be looking for work?",
"Recent battles have left me short-handed. I need to find some lads who are looking for a job.",
"I'd like to talk business.",
"Do you have a room available? I'd like to stay here for a while.",
"I'm looking for a clean room with a clean bed. Nothing more, nothing less.",
"I don't have time to talk right now. I'll come by later.",
"Sorry, I'm busy now. But I'll be back for a chat when I'm free.",
"Indeed! And what business is that?",
"I need some work. Don't you know any rich boy on this island who is afraid to travel alone?",
"You know, now that I think of it, I don't have any business.",
"It's rather late for that. You'll have better luck if you come back in the morning. Or perhaps you'd care to spend a night in the tavern.",
"Perhaps I would. You have a free room?",
"Maybe I will. But let me ask you something else first.",
"I do have a room available. How long do you plan to stay?",
"Until morning.",
"Just until nightfall.",
"Fine. It'll cost you 5 gold coins.",
"All right. Here you go.",
"In that case, I'm afraid my wallet and I will be spending a night in the common hall.",
"No thanks. If that's the price, I'll save a few coins and spend a night in the common hall.",
"Maybe later. Let me ask you about something else.",
"Fine. It'll cost you 5 gold coins.",
"All right. Here you go.",
"In that case, I'm afraid my wallet and I will be spending a night in the common hall.",
"No thanks. If that's the price, I'll save a few coins and spend a night in the common hall.",
"I'll think about it. Thanks.",
"Please! Stop this madness at once! Don't make me call for the guards!",
"All right! I'm going.",
"If there is such a person, he might prefer to avoid attracting attention with so many consorts - as I'd expect you to know.", 
"Yes, I forgot. All right, I'll come back later, when I've got fewer ships, ha-ha.",
"I don't want to help you, with all the harm you've done to my country.",
"Just look at this patriot. Well, goodbye.", 
"Your hands are covered in blood. Do you seriously think anybody will travel with you?",
"You are right. Everyone's afraid of me. How amusing.",
"You came just at the right time. One merchant here was searching for the right company to travel in. You should speak to him. Here he is, coming into the tavern.",
"I'll do that.",
"No, there is nobody I can think of at the moment. Maybe next time.",
"Hmm. Then I will wait.",
"I'm looking for someone who knows his way around the jungle, who has perhaps found an old temple.",
"Ah, yes! Mauricio Juradu over there said something about how he barely got away from a temple surrounded by Indians.",
"Thanks! He sounds as though he could help.",
};
