string DLG_TEXT[115] = { 
"I'm told you've gone to great lengths to request an audience. My name is ",
". Now, if you please, tell me the purpose of your visit, ",
".",
"My name is ",
".",
"Ah, it's you again. What brings you here this time? ",
"I'd like to talk to you about some business.",
"I'm sorry, but there are things that I have to do.",
"So, why do you distract me from the very important affairs of state?",
"I'd like to talk to you about a small piece of business.",
"I'm just here to pay my respects. Nothing more, ",
"In that case, please leave my study and let me get back to more important matters.",
"Yes, of course. Sorry I disturbed you.",
"I'm listening, ",
".",
"I'm here to get my reward for the death of Dirty Garry.",
"I'm sorry, but I don't have anything to talk about right now",
"Oh, I've heard about what you've done. From the face of all colony I will show you our appreciation.",
"That's right, I'd like to see a reward.",
"You're such a joker. Ha ha. Here is your money.", 
"Thank you, I'm your humble servant.",
"So, about the bet you made...after getting the approval of our tax department I see we've got...let me look...six thousand.",
"What?! The deal was 10 thousand!",
"I can't help you. In the future, try to be more calm.",
"Whatever you say, sir. Dirty swine....",
", are you aware that you stand accused of murder? You were seen near the victim's body. What do you say in response to this charge?",
"It has nothing to do with me. The man was already dead when I entered the room! I was told he was only injured, and that he might have some important information for me.",
", I've just been told that a man was captured as he attempted to leave town with a blood-stained knife in his possession. He confessed to the murder you were accused of. You may go free immediately.",
"Thank you. I knew I could trust in justice here on Conceição.", //spell-checked by KAM
"I wish to defect to Portugal.",
"Indeed? Very well, you are now a Portugese citizen.",
"I thank you for your infinite kindness, sir.",
"Oh yes? I have a proposition for you, captain.",
"Indeed?",
"I have learned that you completed the task successfully; my congratulations, captain! Here is your reward.",
"My thanks; It was a pleasure to aid you.",
"You must destroy the ",
" vessel ",
"quest pirate",
" menacing the shipping off ",
". If you sink her, I will reward you the hefty sum of ",
" gold. What say you, captain?",
"You shall not hear of her again, that I promise.",
"I'm afraid I can't help you.",
"I crave forgiveness, your Excellency.",
"I'm interested to learn about Spain relations with other nations.",
"I'm looking for a Letter of Marque.",
"Ah, ",
", so good of you to stop by. I'd like to introduce my ",
". She'll come in once we've finished business.",
"I've heard I'm up for promotion.",
"I can no longer serve ",
", your Excellency.",
"I'm through serving ",
"As insurance that you are an able captain, and to recompense my time in presenting your case to ",
", I must ask you for ",
" gold.",
"Not a chance.",
"Very well.",
" is always pleased to accept new captains into her service. ",
"We are currently at war with ",
"",
"no great power, but ",
". Of course, ",
"Pirates are always to be sunk on sight.",
" In light of your previous service, ",
" grants you the rank of ",
"I'll make you proud, your Excellency.",
"You have harmed ",
", and ",
" does not forget his enemies. Leave at once, or the guards will toss you out on your ear!",
"...",
"You have caused ",
" great harm, captain, but ",
" is willing to overlook your past transgressions...for a price: ",
"Very well, Sir. I accept.",
"A pleasure dealing with you, ",
"And you, your Excellency.",
"You are indeed! Excellent work. Your new rank is ",
". In addition, you are awarded ",
" acres of land by order of ",
"Thank you, Sir.",
"Are you sure, ",
" will be sorry to lose your service.",
"Yes, I am.",
" does not take kindly to turncoats, ",
"Uh, never mind.",
"Very well. But I hope you will reconsider, in time...",
"Goodbye, ",
"Huh?",
"Tough.",
"The Vice-Admiral Benavides told you need some help to find the envoy of the King.",
"Excellent! I knew I could count on him. So how long have you been working for the Vice-Admiral?",
"I've been working for him for many months. He said you already started the search.",
"Indeed. Unfortunately, I don't have enough ships for my search. At the moment, my men are finishing their search along the South coast of the island and I also sent a ship to #sIsla Muelle# to check if the ship has sunk or is crippled.",
"You think the ship has been overtaken by the storm?",
"I think so. It's a strong possibility.",
"How can I help then, Governor?",
"Firstly, I would like you search along the North coast of #sisland_Hispaniola#. There is a remote possiblility that the ship has strayed off course during the storm, if this is the case there is a slim chance of finding her there.",
"Yes, Governor. This is worth checking, if only to limit the possibilities.",
"I found the ship, Governor. The soldier with me is the only survivor. The ship had been attacked by pirates.",
"And they kidnapped the envoy...",
"Just so. How do you know this?!",
"I've just received a letter from the kidnapper. The envoy will be only released on payment of a large ransom. My King will be upset that we in the Caribbean haven't been able to protect his envoy, heads will roll.",
"Maybe I could intervene and find Roche Brasiliano and then rescue the envoy.",
"Roche Brasiliano is the kidnapper?",
"The Pirate did not sign the ransom letter?",
"No, of course not. He obviously wanted to remain anonymous.",
"At last a break, we now have the advantage over him. He thinks we don't know who he is.",
"If you succeed in releasing the envoy, you'll be handsomely rewarded.",
"The problem is I don't know where to start my search for him.",
"And I can't help you in your search. I have no information about this pirate.",
"The Vice-Admiral Benavides is always well informed, I think I will sail back to #sHavana#. He should have some useful information about Roche Brasiliano.",
"You're right Captain, do that. You can leave the soldier here, we will see to his wounds and he'll be employed in my garrison.",
"Thank you, Governor.", 
};
