string DLG_TEXT[76] = {
"What are you doing here?",
"Relax, I've brought the goods!",
"What do you think? I brought the goods!",
"Look, get out of here! If you ruin the deal, we'll kill you!",
"You dare threaten me?",
"You'll choke on those words, scoundrel!",
"Calm down. I'll be on my way. Goodbye.",
"I suppose you have them in your pockets? Come on, where's your ship and the goods?",
"I wanted to make sure everything was all right first.",
"I didn't want to risk my ship. I wanted to check if everything was all right first.",
"The deal is off!",
"We won't cheat you. Come on, bring your ship, and watch for the coastal patrols.",
"Alright. Wait for me here.",
"What? DO you jest?",
"I'm completely serious.",
"You can't fool us like that! You'll pay for this with your head!",
"I doubt it!",
"You'll regret this!",
"Go howl somewhere else, scurvy dogs!",
"You'll regret this!",
"Go howl somewhere else, scurvy dogs!",
"Aha, good. So...",
". The price is ",
". So it will be ",
" total. Deal?",
"Deal.",
"No deal. I'll look for another buyer.",
"What are you doing here? You don't have anything to sell! This isn't what we want. Everything you've got we can buy in town!",
"No luck.",
"Glad to hear that. Shall we continue? ",
". The price is ",
". So it will be ",
" total. Deal?",
"Deal.",
"No deal. I'll look for another buyer.",
"Well...",
". The price is ",
". So it will be ",
" total. Good enough?",
"Sure.",
"Nah. I think I'll go look for another buyer.",
"And finally...",
". The price is ",
". ",
" total. That all right?",
"Yep.",
"No deal. I'll look for another buyer.",
"No luck? You arrange a meeting and then just say 'no luck'? Get out of here. You'd be wise to honour your deals in the future!",
"You were expecting honour among thieves? That's funny.",
"The total sum is ",
" gold. Your money, our goods!",
"Deal!",
"Too much! No deal!",
"Here is your money. Now let's go and offload the stuff...",
"My crew has already dumped it on the beach. I didn't want to wait for the coastguard to show up.",
"You won't go nowhere from here. Now that I have your money I'll just keep the goods as well. And to escape the wrath of your smuggling brethren I'll claim that the coastguard killed you and confiscated the contraband. Of course there must be no witnesses, which means...",
"Swell. Goodbye then.",
"Till next time.",
"Wait a minute! I am a bit short of provisions for my ship. Do you happen to have such stuff in that pile of goods over there?",
"That pile contains indeed provisions, plun... eh.. salvaged from a ship that.. umm.. had an unfortunate accident near this beach. But we were about to burn it all, can't bother ourselves with such lowprofit stuff, and we mustn't leave evide.. eh.. litter on this beautiful beach. You can buy it, all or nothing, for 1000 G.",
"I love buying surprise packages! Here is the money, dump the stuff in my hold. It was a pleasure to do business with you, goodbye.",
"1000 Gold for a heap of drenched wheat and torn sails? No, thanks and farewell.",
"I'd like to skip this good if you don't mind.",
"Very well.",
"Let's continue, shall we?",
"You skipped everything! Do I look like an idiot you can fool around?",
"How did you get those guards away? That was too easy! You will betray us won't you? En Garde!",
"No... No... WAIT!",
"By order of the governor, you are under arrest. Drop your weapons and proceed to the boat!",
"And be taken to be hanged? Not likely! Get #sperson#, lads!",
"Thank you. Now that you have proven yourselves to be smugglers, you are under arrest!",
"A government agent! Kill #sperson#, mates!",
"Then die like the criminal dogs you are!",
"Why are you here? We were told to expect #samount# of #scargo#. Why do you not have it?",
"Why are you still here? We have no further business with you. Leave, now!",
"Alright, I'm going.",
};