string DLG_TEXT[23] = {
"Drop your weapons, ",
". You are under arrest.",
"Under arrest?! What for?",
"I have a warrant to arrest, ",
", and all who are with him.",
"What?! Who gave you that order?",
"Drop your weapon! You're under arrest!",
"What's going on?! Are you out of mind?",
"You are under arrest, ",
". Please, come with us.",
"If the odds weren't in your favor, you'd find me less agreeable. But fine, take me away. I insist on informing the Governor about my arrest, however. After all, I'm working for him.",
"Lay down your arms, now!",
"You'll not get away with this!",
"The Governor ",
"Robert Christopher Silehard",
". You've got one minute to drop your weapons and surrender.",
"I'm afraid this is all a terrible mistake. Let's go see the Governor and we'll clear up this whole mess.",
"Fool! It was the Governor who ordered me to bring you to jail. The only way you'll leave is via the gallows.",
"You filthy dog! You will taste my steel!",
"That's none of your business, swine! Do not argue with the officer!",
"Don't talk to me in that tone of voice, peasant!",
"You are not in the position to demand anything. Come with us.",
"Devil.",

};