string DLG_TEXT[48] = {
"Hello, my name is ",
".",
"It's very nice to meet you, ",
", my name is ",
". I am sorry but I have business to attend to, let's talk some other time.",
"Hello, beauty, my name is ",
", but for you I am just ",
". I'll see you later.",
"I am so glad to see you, ",
"!",
" Everyone in town is talking about you and your exploits!",
"Yes, yes, but I am in a hurry now.",
"Not now! Oh sorry I may be a little rude sometimes but I know my job very well. I have things to do now but I'll talk with you later.",
"...",
"...",
"Hello, stranger. You're the captain, aren't you? Judging by your smell - Captain! Oh, I love the sea so much\nI wish my dad was a captain, I'd sail with him, catching the spray of the waves, but he's just a merchant... Tell me what it's like to sail, to feel the deck beneath my feet...",
"Stop, stop, stop! Let's go a little slower! ",
"Hello again, ",
"!",
"Hello, ",
". It's nice to see you again. ",
"As I understand it, you are the daughter of Jean Maginot",
".",
", and your name is...",
"Oh, I didn't introduce myself! I'm so absent-minded. My name is ",
", and you guessed my father's name... Do you know him?",
"Oh! Do you know my father, then?",
"Of course I know! I can be said to be your dad's confidant!",
"Whether I know him or not makes no difference to you? Now get out of my way, wench.",
"Ugh! What a rude guy! My dad definitely wonâ€™t mess with people like you!",
"Your dad?! Ha! I'm afraid you don't know much about him! And in general - get out of the way.",
"Strange, but he didn't tell me anything about you...",
"Ha! Do you think he will let you in on all his affairs?!",
"You see, it's not always parents who initiate their children into their plans and don't always introduce them to their friends...",
"You're wrong! My father always tells me about all his acquaintances and affairs!",
"How misguided you are, baby, ha-ha.",
"You may be right, but...",
"I see you don't believe me... Maybe this ring will change your mind?",
"Dad's ring?! How did you get it?!",
"You see... He's having some trouble with some smugglers, and he's worried that you might get kidnapped...",
"Daddy's in trouble?!",
"Yes, but don't despair, everything will be fine. In the meantime, he asked me to hide you somewhere private.",
"Ah! And he gave you a ring so that I would believe you! What a smart dad!",
"There, clever. But we must hurry. Run to my ship, the crew has been warned, and I'll finish some business here.",
"What about my things? How about saying goodbye to dad?!",
"We don't have time for that!",
"Okay, whatever you say.",
"See you on the ship.",

};