string DLG_TEXT[22] = {
"I am looking for a specific type of officer.",
"What exactly are you looking for?",
"I need a boatswain to help me take care of my crew.",
"A cannoneer would be quite welcome. My crew keeps missing their targets.",
"It is said that quartermasters help dealing with traders.",
"Do you know about those pesky rocks at sea? I could really use a navigator to help me avoid them.",
"My ship is so large I have a hard time managing everything at the same time. I need a first mate to assist me.",
"Holes in my ship. Always holes in my ship! Oh, how I wished I had a good carpenter to fix them when I get into another sea battle.",
"Casualties after a battle are always such a waste. I need a doctor to help me keep my shipmates alive.",
"Not really an officer per se; I just need some muscle!",
"Never mind, I'll just see what I can find on my own.",
"Unless I am much mistaken, I think one just walked in.",
"What a lucky break! And such a coincidence too. Well, you won't hear me complaining if it works out...",
"What's the latest gossip in town? Any news from the other colonies?",
"What's the latest buzz?",
"Any news?",
"I would only need it for a few hours, is that okay?",
"We aren't a brothel! If you just need to wait, you can do that here. Just take a seat and enjoy a drink!",
"Okay that'll be one cup of rum and 1 hour of fun.",
"Okay that'll be one cup of rum and 3 hours of fun.",
"Okay that'll be one cup of rum and 8 hours of fun.",
"Never mind, I will spend my time elsewhere."
};