string DLG_TEXT[232] = {
"Are you here to make a trade deal or are you interested in the highest quality of personal items?",
"I'd like to examine your stock of trade goods.",
"Let me look through your range of personal items.",
"Just passing through. Goodbye.",
"Hello, ",
". Welcome to my shop.",
"Thank you, my name is ",
".",
", ",
". It's nice to see you. Are you ready to strike a bargain ",
"?",
"Well, what did you bring for us this time, captain ",
"? Or perhaps you're here for other reasons?",
"Captain. So glad to see you. I am at your service!",
"Let's see what you have.",
"In a moment perhaps. First I'd like to talk.",
"Farewell.",
"Good to meet you, #ssir#. I, ",
", hope we'll have a rewarding future together.",
"Well, ",
", let's see what you have.",
"I'd like to talk to you, ",
".",
"Farewell.",
"Here to chat, captain? With you it's always a pleasure.",
"I'm looking for work.",
"I'm looking for work.",
"I'm listening.",
"I was asked to deliver some cargo to you.",
"Surely you must have some job you'd like done. I'd be happy to lend you my services for a fee.",
"Arnaud Matton",
" has received his goods, ",
".",
"I've here on behalf of ",
"Arnaud Matton",
"Arnaud Matton",
".",
"I'd like to talk about one of your workers.",
"I would like an explanation. Starting with the men who ambushed me at the beach and tried to kill me?",
"Tell me who tried to kill me at the beach? Were they working for you!",
"I completed the mission, sir.",
"Your cargo was delivered as scheduled.",
"It's not a good time to talk.",
"You're right on time, ",
", I need a captain for some... hmm... delicate business.",
"I guess this is my lucky day. So what exactly do you want me to do?",
"Sounds good. What kind of job is it?",
"I need someone to hand-deliver cargo to #sFalaise de Fleur# and give it to someone in particular.",
"What do you mean? You want me to deliver contraband?",
"Wait a second, this doesn't sound right. Do you want me to deliver some contraband?",
"Yes, ",
". I'd like you to do this favor for me I assure you, your reward will be impressive.",
"Tell me how much and maybe we'll come to an agreement.",
"How much?",
"I'm sorry, I'm not a smuggler.",
"No, too risky for me.",
"The offer is 6000 gold. Half of which I will pay you now.",
"That's a fair deal. Now let's get to the details.",
"Deal. Now tell me what I have to do.",
"That's hardly sufficient for the risk involved for my ship and crew.",
"Only 6000? I wouldn't lift a finger for that amount!",
"Good. Now, let's talk business. I need you to land your ship on the deserted beach located the other side of the island. You need to do this today.",
"All right, what's next?",
"Okay, I can do that. What next?",
"My workers will be waiting for you and they'll load your ship with the cargo that I need delivered.",
"Who should I deliver it to in #sFalaise de Fleur#?",
"And who is it intended for? Once I reach the French colony, I'll need to know the contact.",
"You have to find ",
"Andre Juliao",
"Andre Juliao",
", he'll be waiting for you at the tavern.",
"Good. Now that the details are sorted, I'll prepare my ship for sail.",
"Let's not waste time then. I'll prepare my ship and you take care of loading. I don't see any problem with that.",
"I'm sorry, but I should've mentioned that there may be some, er, complications with this type of venture.",
"I'm ready for anything, but I don't appreciate when someone tries to kill me. I demand an explanation.",
"Complications? That's such a civilized way to put it. Now, why don't I pierce your hide and we'll see how you like it!",
"Please, calm down, I'll explain everything.",
"I'm waiting.",
"You'd better explain in a hurry.",
"Those people who attacked you are the members of the smuggler's guild. I had used their services before. \nBut they've been acting very impudently recently and demanded a very high commission so, I refused to work with them.",
"So, they decided to take revenge on you and thought that by killing me they'd ruin your chances for an alternate means of transporting these goods. Am I right?",
"So, they decided to teach you a lesson, right?",
"Exactly, ",
". Furthermore, on pain of death they ordered me to load my goods on their ship and then sailed away to who knows where.",
"So, our deal is off, isn't it?",
"Wait a second, you're going to cancel our deal?!",
"I'm afraid so. I don't have my gear anymore and I've already put up a considerable sum of money towards the operation.",
"How long ago did they sail away? Maybe I'll be able to catch them and take the booty...",
"How long ago did they sail away? Maybe I'll be able to catch them and take the booty...",
"I really can't help you.",
"Well, there is nothing to do about that. Farewell!",
"They sailed away less than an hour ago. If you manage to catch them and satisfy our original deal, I'll pay you 2000 more.",
"Then let's not delay! You can be sure that your goods will be in #sFalaise de Fleur# shortly.",
"You have a deal. I'll set sail immediately. Get your money ready!",
"Is everything all right?",
"Yes, but I think he suspects something. So, be careful.",
"Everything is fine, but if I were you I'd be more careful, it looks like he suspects something.",
"Thanks for the warning, but let's settle accounts. Here is your reward. I hope we'll work together in the future.",
"Maybe you are right.",
"If you pay as much in the future, I am sure we will.",
"The maximum I can offer you is ",
"commerce",
" gold.",
"Hmm, good. Agreed.",
"Not what I had hope for, but I imagine I'm unlikely to get more from you. It's a deal.",
"Not interested. Farewell.",
"This is an insult. What is this you're offering?",
"As you wish, ",
".",
"Let's see what you have.",
"Let's end this conversation. Farewell.",
"Hmmm...Yes, I was looking for a captain to help courier some goods. I've made an agreement to deliver some articles to the owner of a store on #sisland_Falaise de Fleur#. \nBut because of the current affairs between France and England no one wants to make this voyage.",
"How much will you pay me for this cargo delivery?",
"What kind of goods?",
"Thank you, ",
", I am not interested in that. Farewell.",
"I used to pay 1000 gold but under the circumstances I'm prepared to go as high as 1500. I hope you are fine with that.",
"1500 gold? Perhaps you can offer a little bit more?",
"Sounds good. I'll do this for you.",
"Thank you, ",
", but I'm not interested. Farewell.",
"Normal goods... silk, rum, spices, no contraband, don't worry!",
"I don't question your honesty.",
"Thank you, ",
", but I'm not interested. Farewell.",
"2000 gold? ... All right, I agree. Otherwise I'll not be able to deliver these goods.",
"Now we're talking. I agree.",
" ",
", I've changed my mind. I can't do it.",
"It's too much! I won't be able to pay you this much. I need to make at least a small profit, ",
". This is my livelihood.",
"All right. Pay me 1500 gold and I'll deliver your cargo.",
"Then we have no agreement, ",
".",
"Thank goodness! I'll finally be able to send this cargo! Don't forget, ",
", who you are supposed to deliver the cargo to! His name is Arnoir Matton on #sisland_Falaise de Fleur#!",
"Show me what you have for sale.",
"Don't worry. I'll see you soon, ",
".",
"Thank goodness! I'll finally be able to send this cargo! Don't forget, ",
", who you are supposed to deliver the cargo to! His name is Arnaud Matton, on #sisland_Falaise de Fleur#!",
"Show me what you have for sale.",
"Don't worry. I'll see you soon, ",
".",
"Thank you, ",
"! Do you want the gold I promised to pay you?",
"Of course, I want to get ",
" gold that I earned.",
"Why do you ask me that, ",
"?",
"Here are ",
" gold coins. Now, be sure to call on me whenever you're in port. It's nice doing business with you, captain.",
"Thank you, ",
". Here is something else...",
"Good bye, ",
". Good luck!",
"Well, I could put this money on interest and over time you would get much more money...",
"No, thanks. I need the money now.",
"I am all ears.",
"Arnaud Matton",
"Arnaud Matton",
" hired me to deliver cacao for you.",
"Finally! I've been waiting for a shipment, but the war has changed all my plans.",
"Where should I unload?",
"Don't worry about a thing. I'll send someone to your ship now to take care of the unloading.",
"Great! Now let's see what you have for sale.",
"Good.",
"You mean Marc?",
"Yes, I'd like to ransom him.",
"You know, I don't want anyone to ransom him. I hope he'll collect some money soon in order to return to his homeland and I don't want to deprive him of his right to do that.",
"But that's why I want to ransom him.",
"You are saying you want to do that in order to bring him home?",
"Exactly.",
"It's nice to know there are some noble-minded people left in the world.",
"So, you agree?",
"Yes, certainly, if you pay me 3000 gold.",
"Hey! You know, it's too expensive for me.",
"Here is your money. Can I take Marc now?",
"Yes, of course. Tell him that I am very happy that he is going to return to his homeland finally.",
"I will.",
"No, I don't need your services. At least as long as you're sinking English ships.",
"In that case, goodbye.",
"I'm sorry, but I don't have anything for you at the moment.",
"I'll come back later, then.",
"I'm sorry, but your ship doesn't have the required cargo space needed to fulfill the assignment I have in mind.",
"I'll come back later, then.",
"Oh! I was just going to ask you to do me a favor. Thing is, I need some cargo delivered to ",
", and as soon as possible. If you manage to do it in a month's time, you'll receive ",
" gold when you arrive. How do you like my offer?",
"I definitely like it.",
"I can't accept it.",
"I already told you today that I don't have anything for you.",
"Oh, sorry.",
"You've remembered about your assignment a bit too late, don't you think? I'll take the goods anyway, but don't expect to be paid. Pay closer attention next time! Goodbye.",
"Farewell.",
"Oh! I've been waiting for this for a long time. Here is your reward, my good ",
"Always welcome.",
"I refuse to trade with a person of your reputation and relations. Now get out, ",
", before I call the guards.",
"Very well.",
"I would like to restock my ammo supplies.",
"A good choice, ",
". I will deliver ",
" loads of gunpowder, ",
" pistol bullets, ",
" loads of grapeshot, and ",
" musket bullets to your ship for just ",
" I can also restock your officers' ammo and gunpowder supply, if you want. This will cost an additional ",
" pieces of eight.",
"Just give me some ammo and gunpowder for my officers.",
"Maybe next time. I am not in the mood for ammo and powder right now.",
"I accept your offer! Bring the stuff to my ship and equip my officers, too.",
"Seems like I have run out of money... Err, I mean: I have changed my mind.",
"What? I won't support such a profiteering!",
"I offer only the best quality for you, ",
". Thank you for the trade and have a nice day.",
"I'll be back.",
"No problem, ",
". Come back, when you are in need of fine goods.",
"I surely will, ",
"Unfortunately I have a very urgent meeting right now. See you later!",
"Okay, fill weapons lockers of my ships with a fresh load of ammo and gunpowder. That will be enough for now.",
"I'd like some gunpowder and ammunition for my weapons locker. And no questions!",
"Oops... I have forgotten my purse. It's in the other trousers.",
"There was indeed another job that needed doing, but word has reached me that my contact person in #sFalaise de Fleur#... passed away under rather mysterious circumstances.",
"Hey, don't look at me like that! I'm sure I had nothing to do with it. Or did I? I don't think I did...",
"Unfortunately I have not heard from my contact person in #sFalaise de Fleur# for quite some time.",
"Maybe he got himself into trouble with that gang of smugglers that got caught there a while back. Better to steer clear of that!",
"There is indeed something that needs doing. But I'm not certain my contact person would be quite willing to trust you just yet. You may have to get yourself a bit more well liked by a... certain group of people.",
"'Certain group of people', eh? That sounds a bit shady... I'm not sure I like the sound of this.",
"There is a cargo that I need to be transported, but it appears that you do not have enough space available to carry it.",
"That can be rectified. I'll come back when I have some more room.",
};
