string DLG_TEXT[38] = {
"Thanks again for what you've done, ",
".",
"Don't mention it.",
"Oh, leave me alone! If you're looking for company, talk to somebody else!",
"As you wish.",
"What's your problem? I've done nothing to you!",
"What do you want?!",
"Nothing.",
"Let's talk about your daughter.",
"Oh, thank you! Thank you! I've seen my daughter finally! I'm so sorry I have nothing to reward you with... Wait, you can take this sword!",
"It's quite unusual. Wherever did you get this thing?",
"When I was younger, I had a lust for treasure, and went to many islands. Though many had nothing of value, I did manage to find a small deserted hideaway. They say it was the home of a famous sea captain. The sword was there.",
"I see. Well, thanks for the gift.",
"Really?! You - you're jackals, feasting on the bones of others!",
"Calm yourself! You should really sit alone for a while.",
"Who do you mean by that?",
"You! All of you! Pirates, corsairs, smugglers! You're all devils, the whole lot of you!",
"What happened that turned you this way?",
"Maybe it's a mistake that I'm telling you all this, but you do seem a better person than the rest of those bastards...",
"I'm flattered, but please, go on.",
"This is none of your business! Look at you! Untrustworthy and vile. You sail the same seas as those reptiles!",
"Do as you like. If you don't want to tell me - don't tell me.",
"My daughter, ",
"Tanneken Oremans",
", a gentle, trusting girl...",
"Let me guess - This has something to do with pirates?",
"Yes! One of the worst, ",
"Bernardo Gamboa",
". He has seduced my daughter! \nI told her I was opposed to their courtship, but she wouldn't listen to me, and 3 days ago she disappeared! \nI'm sure that this Spaniard kidnapped her!",
"Why don't you turn to the officials for help?",
"Turn to the officials? Oh, dear #schild#, you are deceived. The snake that took my daughter counts the Governor among his friends!",
"I see. Well, I hope there is a happy ending to your tale.",
"Perhaps I can help. Where can I find this lad?",
"His ship is in port. You'll have no problem finding it.",
"I'll see what I can do.",
"Go away, I've told you everything! Don't torment me with your questions!",
"Very well, go on, drink your rum and hope your daughter comes back to you.",
"Easy, easy. Tell me where I can find the man who kidnapped your daughter.",

};