string DLG_TEXT[102] = {
", from '",
"', if I am not mistaken?",
"No, you are not mistaken...but how do you know about that?",
"That's my profession to know everything about everyone. By the way, my name is ",
".",
"I am glad to meet you. I've got a couple of questions for you.",
", ",
".",
" I've got a couple of questions for you.",
"I believe that I have some information that you'll be interested in. I know who sells contraband in your town.",
"I know who sells contraband in your town.",
"I know who deals with contraband here in your town, Mocie.",
"Did you check that information that I gave you?",
"I am captain of a ship that is to escort the barque 'Oiseau' to #sOxbay#.",
"Yes, I am listening.",
"I'd like to get some information about the town.",
"I've heard that you have some problems with the smugglers.",
"I believe that I have some information that you'll be interested in. I know who sells contraband in your town.",
"I know who sells contraband in your town.",
"I am a captain of the ship that was hired to escort the barque 'Oiseau' to #sOxbay#.",
"What? Is everyone in the town is gossiping about that already? I'd like to know where they find all this out.",
"Well, for instance, I have learned about it from the port's workers.",
"Well, if everyone already knows, there's no point in denying it. Yes, I have some problems with the smugglers. Why do you care?",
"Well, I just was curious about that. Let's talk about something else.",
"The thing is that I'd like to help you...but not for free, of course.",
"What kind of help can you offer me?",
"I find those smugglers for you, and you pay me 5000 coin for the service.",
"Well, if you know where to find them, why don't I just call for the guards, and then you'll tell me everything... and without charge.",
"Possibly because you can't be sure I really know anything yet, and because you can't be sure you'll get what you want that way?",
"Try that, my friend, and I'll be checking the color of your own heart's blood.",
"Hmm. Let us assume that I believe you...then how are you going to find the smugglers?",
"Well, that is my problem, isn't it?",
"All right. If you find the smugglers, you'll get 5000 gold...but keep in mind that if you try to trick me...",
"What are you talking about? I am not going to trick you. I am being completely honest with you.",
"Do you have any evidence?",
"It happens that I do. Here, take a look at these letters.",
"Do you have any evidence?",
"It happens that I do. Here, take a look at these letters.",
"You are quite right. These papers do cast a light upon this shady transaction. What do you want for your services?",
"I have rendered you the service absolutely for free, and I want nothing from you except your gratitude.",
"I suppose that 500 gold would be fair compensation for me.",
"No, it shouldn't be like that. Here is 1500 gold for your help...along with my gratitude to you.",
"I don't dare delay you any longer.",
"Good. Here is your money. And now, if you'll forgive me, I have work to do.",
"I don't dare delay you any longer.",
"You are right. These papers do cast a light upon this shady transaction. Here is your money. And now, if you'll forgive me, I have work to do.",
"I don't dare delay you any longer.",
"Really? Who is it?",
"This is ",
"Raoul Calmes",
"Raoul Calmes",
".",
"I can't believe that! ",
"Raoul Calmes",
" is a very respected man.",
"Well, you can make sure of it yourself, monsieur, and I'll wait for you.",
"Yes, I guess that's a good idea, ",
". You'll have only yourself to blame if you are wrong.",
"I have nothing to be afraid of.",
"Great. Then I'll ask you to wait for me at the residence's entrance. I'll check your information, and if it's true, you'll get your money.",
"Good, I'll follow your advice, monsieur.",
"Yes, it turned out that you are right. Here is your reward. And now I am sorry I am in a hurry, but the gentleman governor is going to give me an audience.",
"I am always happy to help you.",
"What do you want to know? I must tell you right away not to waste my time with questions concerning directions...I am not an idle fishwife.",
"Hmm. Then I won't delay you any more.",
"I'd like to know about the story of ",
"Rachel Blacque",
"'s family. As I understand, you know them very well.",
"Yes, you are right. I know them, but that's a very sad story.",
"Yes, I've heard that old man, ",
"Milon Blacque",
", is distraught with grief.",
"Alas, that's the truth. The death of his only son shocked him very much.",
"What happened with him?",
"Indeed, that's quite sad...but I really must be going.",
"With the son? Five years ago he sailed to #sRedmond# on his ship, and no one has ever seen him since then.",
"Yes, that is tragic.. but perhaps he is still alive?",
"I don't think so. Five years have already passed. He would have sent word if he was alive.",
"Maybe you are right. I've heard that the old man is not alone. His adopted daughter is taking care of him, is that true?",
"Rachel Blacque",
"? She is a good girl. She sacrifices much in taking care of the old man, and in addition, she's got her own problems.",
"Thank you. You were a great help.",
"That's my profession - to know everything about those who arrive in my port. By the way, my name is ",
".",
"It's nice to meet you. I've got a couple of questions for you.",
"Ah, yes, I was warned about that. Are you sure your ship is well prepared to ensure her safety on the voyage? And did you talk already with ",
"No, I have yet to make his acquaintance.",
"Yes, he is going to finish the loading soon.",
"He should be here somewhere. As a matter of fact, as soon as you come to an agreement with him, you can set sail.\nI am not going to check anything. I've got plenty of other things to worry about.",
"Here he comes. Can you see him? He is in a dark blue waistcoat. As a matter of fact, as soon as you come to an agreement with him, you can set sail.\nI am not going to check anything. I've plenty of other problems to worry about.",
"Thank you, ",
".",
"All right, then give me your deed, and as soon as you are ready, you can set sail.\nI am not going to check anything. I've plenty of other problems to worry about.",
"Thanks for your kindness, ",
".",
"Virgile Boon",
"",
"Captain ",
", as you can hear, your reputation has proceded you. That pirate was really hurting our trading routes, I am sure you will receive a warm welcome here where ever you go.",
"Thank you kindly sir. Do you by chance know of the whereabouts of a Captain Barbossa?",
"Captain Barbossa.. hmm.. Why, yes I do as it happens. You will find him in Octopus Bay. I am told it is his favourite fishing spot. You can get there by going though the town, across a small patch of jungle and you're there.",
"Thank you sir. I will bid you adieu.",
};
