string DLG_TEXT[155] = {
", How can I help you?",
"I am happy to see you here, ",
". Do you need my services?",
"Hello, ",
". I don't believe I'm had the honor of an introduction...",
"My name is ",
".",
"",
" is at your service.",
"I am ",
".",
"Glad to see you, ",
". If you need my services, I am ready to render them to you right now.",
". Are you on business here?",
"Hello, ",
". How can I help you. I can do transactions in any currency.",
"I want to borrow some money.",
"I badly need a little gold.",
"How about giving me a little credit?",
"I'd like to place some money at a favorable rate of return.",
"Can I store some pirate's booty?",
"Can I leave some gold here for a rainy day?",
"Goodbye, ",
".",
",",
", did you come to pay off your debts? Ah, yes...you owe me ",
" gold.",
"Hello, captain. I am glad to see you up to the mark. Are you ready to pay me ",
" those...gold that you borrowed from me?",
"I welcome you, ",
". I hope that your sailing was successful, and that you brought my money and the interest you owe me.",
" gold.",
"I am ready to pay your money back.",
"I can repay you a debt.",
"It's time to pay off a debt.",
"Unfortunately, I can't do that right now.",
"Next time, ",
".",
"Alas, no. I'll be back when I find the money.",
"...",
"I am glad to see you, ",
". If you need my services, I am ready to help you.",
". Are you on business here?",
"Hello, ",
". How can I help you? I can make transactions in any currency.",
"I'd like to withdraw my deposit.",
"It's time to retrieve my money you're keeping for me.",
"I want my gold back, and my interest.",
"Goodbye, ",
".",
"...",
"Nice to meet you. I am ",
". My occupation is lending money at interest.",
"My name is ",
". I am a moneylender. If you ever need some money, I'd be glad to help you.",
"You probably already know that my name is ",
". I am rather well known here.... Well, let's get down to business. Do you need my services?",
"I want to borrow some money.",
"I badly need a little gold.",
"How about giving me a small credit?",
"I'd like to place some money at a favorable rate of return.",
"Can I store my pirate booty?",
"Can I leave some gold here for a rainy day?",
"Goodbye, ",
".",
"Oh, sure, please. How much do you need?",
"Not much.",
"Quite a bit.",
"The more the better.",
"Great! It's always easier to work with a small amount of money. It's less risky. I can give you ",
" gold.",
"That's a deal. At what interest?",
"Alas, that's not fine for me. Can we do something about it?",
"I guess I'd rather not get into debt. Goodbye.",
"That's not a problem. I hope that ",
" gold will help to solve your problems. That's quite a tidy sum.",
"You've got a deal. At what interest?",
"Alas, that's not fine for me. Can we do something about it?",
"I guess I'd rather not get into debt. Good-bye.",
"Hmm. Yes, that's risky but...all right, I can lend you money in the amount of ",
" gold. I hope you understand, captain, that's really a large sum. I want you to be in earnest about this.",
"You've got a deal. At what interest?",
"Alas, that's not fine for me. Can we do something about it?",
"I guess I'd rather not get into debt. Goodbye.",
"%% per month. Considering what I know about you, I can't offer you better terms.",
"That's all right with me. We just need to discuss the terms.",
"I guess I'd rather not get into debt. Goodbye.",
"Considering what I've heard about you, ",
", I'll be waiting for the repayment within ",
" months. And then, as you will appreciate, I'll have to take measures to collect.",
"Well, I accept your terms and your money with pleasure.",
"Alas, you haven't got a deal. Good-bye.",
"I am very glad, but let me warn you. I've been in this business for a long time, and I know how to get my money back. So, if you ever have any ideas about pocketing my money, forget that!\nI don't want to offend you...it's just a friendly warning.",
"Hmm, I see. Well, goodbye.",
"Well, watch out! The interest is accumulating, and besides, you are running short on time.",
"Don't worry. I'll see you.",
"Oh! It's just wonderful! Any time you need money, I am at your service.",
"Thank you. It's so nice to deal with a businessman who repays his debt on time. You know, anything might happen...",
"Oh, I was right when I was so positive about you, ",
"! I hope this is not the last time you use my services!",
"I want to borrow some money.",
"I badly need a little gold.",
"How about giving me a small credit?",
"I'd like to place some money at a favorable rate of return.",
"Can I store my pirate booty?",
"Can I store some gold here for a rainy day?",
"Good-bye, ",
".",
"I see an intelligent #sgender#! So, how much money would you like to invest?",
"All right. Rest assured that this money will be safe and sound here, and that you'll receive interest, too. By the way, how much are you going to give me?",
"I can tell that you know the how and why of things. How much do you want to deposit?",
"A quarter of my wealth - ",
" gold.",
"A half of my wealth - ",
" gold.",
"All I have - ",
" gold.",
"Good. I can offer you...hmm...let's say... interest for this sum of money, ",
"%%. Of course, that's the rate per month.",
"I am fine with that.",
"I'd better change the amount of money, then.",
"I think I would rather not invest at this time. Farewell.",
"Good. I can offer you...hmm...let's say... interest for this sum of money, ",
"%%. Of course, that's the rate per month.",
"I am fine with that.",
"I'd better change the amount of money, then.",
"I think I would rather not invest at this time. Farewell.",
"Good. I can offer you...hmm...let's say... interest for this sum of money, ",
"%%. Of course, that's the rate per month..",
"I am fine with that.",
"I'd better change the amount of money, then.",
"I think I would rather not invest at this time. Farewell.",
"Now you can be sure that whatever happens, you won't be without money. If you decide to withdraw a deposit, you can come any time.",
"All right. Good luck.",
"Considering the interest that we agreed on last time, and considering the amount of time that has passed, I figure I owe you ",
" gold... Are you sure that you want to withdraw this money now?",
"Absolutely. Give it to me.",
"You know, I guess you are right. I am not going to withdraw my deposit now. Farewell.",
"Oh. That's a pity. I was just getting used to having these coins around... he-he. Well, come again some time.",
"If I have need, I will come, of course. Farewell.",
"You're still alive? And now you return to pay me my money? Don't bother - I already lost so much you could never pay me back! And now I won't be satisfied until I see you dead!",
"You can die for such careless words!",
"Get out of my house! I don't want to see you ever again!",
"...",
"I'd like to divide the plunder.",
"I am honored by your allowing me to serve you, captain. If you haven't sold your officers' ships, and all your goods and cannon, you should do so first and come back to me. As it stands, each crewman's share will be ",
" gold--I'm sure they'll be ",
"--and your share will be ",
" gold. The starting capital for your next venture will be ",
". You'll have to start recruiting your crew again. Are you sure you wish to divide the plunder, captain?",
"Yes.",
"No.",
"Very well. I am sure the crew will be ",
" with their shares. Good luck on your next expedition!",
"Thank you.",

};