string DLG_TEXT[51] = {
"Leave me alone!",
"...",
"I assume you're going to claim to me now?",
"That's right. Now stop arguing! I'll order my men to escort you to my ship.",
"No, you're wrong. You're free.",
"To think of it - I gave up everything for this scoundrel! What a fool I was! What should I do now?!",
"The best thing would be to return home.",
"I suppose you're right. Would you escort me to the governor of this colony?",
"I'm afraid I can't. If I show up in the governor's residence, his soldiers will arrest me.",
"I don't see any reason to refuse.",
"Oh, but don't worry! You're under my protection! I know this sounds silly, but I'm certain that when they learn who I am they will let you go freely. They'll be afraid to anger my father.",
"That might work, but I'm not taking any chances.",
"All right, if you say so. Let's hope you're right.",
"Pity... I wish I could convince you. But, thank you for your help. Good luck.",
"Good luck to you, too. I hope you won't run into any more trouble on your way home.",
"I can't believe noble people still exist in these times!",
"I not sure about noble, but there are kind folk around. By the way, how did you manage to find yourself in such a situation?",
"My name is ",
" and I am from an influential family...",
"Really? Why are you here then? And how did you fall into this scoundrel's hands?",
"I'm afraid it's a long story...",
"I'm not in a hurry...",
"Love. Love is to blame.... As the daughter of an official with the French court, I dared to fall in love with a simple man. A captain...",
"Go on.",
"My father found out and forbade me to meet with my beloved, who had gone to the New World. Oh, I missed him so much, so much!",
"And you decided to follow him?",
"Yes. Incognito, I bought a ticket for a ship heading here, but pirates attacked us. You know the rest of the story.",
"A sad story. Maybe I can help find your fiance for you?",
"Well. I'll leave you to search for your beloved one. Farewell.",
"Oh, you shouldn't, you've done so much for me already...",
"Listen, I want to help you. How else do you expect to find him?",
"You're so kind to me!",
"Tell me, what is your beloved's name? And where might I find him?",
"His name is ",
"Raymond Bouchez",
" and he was last seen at one of the #snation# colonies, I believe. It seems to me, it was at #sisland_Falaise de Fleur#.",
"Then let's be on our way. By the way, my cabin will be wholly for your needs...",
"(To Raymond) - My love, I've found you at last! But...who is this woman beside you?!",
"...",
"(To Raymond) - What?! She's an ordinary strumpet! Is this how you spent your time while I was looking for you? While I was suffering?!",
"...",
"Ah! Please, there should be no bloodshed. Let's just leave. I don't want see this disgusting creature anymore!",
"I suppose you're right. There's no point climbing into the mud to wallow with pigs. He's not worth it.",
"How dare you talk to me like that?! I'm not just some commoner, I'm from an influential family! My name is ",
"!",
"Yeah, and I'm Neptune, King of the Sea. Just stay quiet and wait for my men.",
"Oh, then excuse me. I should watch my tongue. In that case, what are you doing here?",
"My God! ...",
"Very in time...",
"You called me, captain?",
"Yes. Take this sugar-girl and lock in a cargo-hold. And, by the way, tell to fellows - don't touch by hands... Bha-ha-ha-ha...",

};