string DLG_TEXT[30] = {
"Ahoy matey, would you like to find some REAL booty?",
"Arrr!",
"Hey sailor, what's shakin?",
"I have a hat.",
"'Come into my parlour' said the spider to the fly...",
"Aye, shiver me timbers, and shiver something else if you get what I'm saying...",
"What does a mouse get when it spins?",
"The second mouse gets the cheese...",
"I'm free but not free!",
"I'm a pirate!",
"I'm here to unclog your pipes.",
"My pipes are REALLY messy.",
"Disney is going to mess with your head.",
"They sure are...",
"I may not be Fred Flinstone, but I can sure make your bed rock!",
"Is that a keg in your pants? Because I'd like to tap that ass!",
"That is some fine-lookin' cargo you got there, sweetie.",
"I'd love to pillage your village.",
"Come 'ere, girl, I wanna swab that deck!",
"I wanna sail all seven of your seas!",
"You really hoist my mainsail!",
"You can sail into my port anytime!",
"Are you awake?",
"Ohhh...",
"Are you all right? How's your head?",
"What the hell happened?",
"Don't you remember? You drank too much - fell asleep at the table - and then you were robbed!",
"What? Oh... my head.... Who dared...?",
"How should I know? It's a rough neighbourhood! They came in, threatened me, went through your pockets, and left.",
"All right. What's lost is lost. At least they didn't find my moneybelt.",
};