string DLG_TEXT[126] = {
"Never! The #scursed_ship# attacked the town and they have captured Eliza... er, the Governor's daughter.",
"It sounds to me that she is more than 'the Governor's daughter' to you! And who was it knocked me out?",
"I,... I don't know what you mean, it's just that you are a pirate and they said you were talking about the #scursed_ship#, so you might know where she's going, so we could go and rescue Eliz..., er, the Governor's daughter.",
"Now why should I do that. It seems everyone here wants me hung. Now you ask me to risk my neck.",
"I could get you out of here. I built these cells, these are half-pin barrel hinges, with the right leverage and the proper application of strength the door will lift free.", // TALISMAN changed
"Built the cells did you lad, leverage indeed. Very resourceful. You look very familiar to me, what might your name be then?", //TALISMAN changed
"William Turner, named after my father. Most people just call me Will.",
"Indeed, indeed. Now I kow why I knew your face. Do you by chance have a 'Lucky Coin'?",
"I'd fight anyone for her, I'd even die for her.",
"Oh great! no worries there then. Open the door and we will get going.",
"What are we going to do?",
"Commandeer a ship.",
"Steal a ship! I can't do that!",
"Two seconds ago you were prepared to kill and to die, now you're getting a bit picky over borrowing a ship. Do you want to get her back or not?",
"Of course I do.",
"Then make your mind up. Do we have an agreement or not?",
"Yes we have an agreement.",
"Good, open this door, give me a sword and let's get to the port. We need to get a ship and then get a crew. But one thing at a time, the ship first.",
"What do we do now?",
"Get out to the Dauntless as fast we can, we then board and send its little crew back to port. The Interceptor will get to sea soon after us. We must lure her to board us. While they are searching the ship we will, shall we say, 'swap ships' and then set sail for #sTortuga#... savvy?",
"That changes things I'm thinking. Look if you get me out of here and help me get a ship, I will take you to the #scursed_ship# and help get your lady back. How far would you go to save her?",
"I did have. Mother said my father sent it to me. I wore it as a necklace, but the ship I was on was sunk by pirates on the way here. I got knocked out, so I don't remember much. I was rescued by an English ship but I lost the necklace sometime then.",
"So what do we do now?",
"I'm going to look for an old friend : Mr Gibbs. He will help us to hire some sailors. In the meantime, seize the chance to appreciate #sTortuga#. As I have said before, if every town were like this one, no man would ever feel unwanted.",
"A better one",
"A better one!?",
"That one (Will pointing their ship out)",
"What one? That one? ... Aye that one.",
"Not yet! We wait for the opportune moment.",
"When's that? when it's of greatest profit to you?",
"May I ask you something? Have I ever given you reason not to trust me? Do us a favour. I know it's difficult for you, but please stay here and try not to do anything stupid.",
"Sorry ",
"Are you O.K.?",
"Yes, What happened during the fight?",
"I had a cursed coin covered with my blood which I threw into the treasure.",
"Because of that Barbossa's crew lost their immortality, so Commodore Norrington must have won the fight.",
"I think so. But, I doubt that's good news for me. He doesn't like pirates, especially this one.",
"Escape while you can! The #scursed_ship# is waiting for you at Rocky Shore.",
"And you? What are you going to do? Come with me!",
"Impossible, I don't want to leave Elizabeth. Don't waste your time, there is a rope on the wall. Use it to join the ship. Meanwhile, I will delay the arrival of the soldiers.",
"Thanks Will. We'll meet again.",
"What are you doing in my house?",
"Sorry but I'm ",
" captain of the ship '",
". I've heard you're going to prepare an expedition and you need a partner.",
"That is true, and you want to take part in this?",
"Maybe. Nevertheless, I'd like to know more details about this expedition.",
"Well, I knew that the spaniards discovered a big deposit of silver in the archipelago two years ago...",
"I've never heard this information. How do you know this?",
"I captured a spanish galleon a few weeks ago. Aboard there was an official of #sSantiago# who agreed to give me this information in exchange for his release.",
"And you believed him?! Maybe, he only concocted this story so you'd let him go. ",
"Of course, I didn't release him. He's prisoner on #sTortuga# and I'll only let him go after confirming the information.",
"And where is the deposit of silver?", 
"Well, he told me it was on a deserted island in the middle of the archipelago.",
"It could be #sisland_Battle Rocks#...",
"Do you know to go there?",
"Yes, I could take you there. I've never visited this island. It seems to be very inhospitable and it will be hard to find a location to moor. The coast is uneven.",
"If the spaniards have settled the island, I think we are able to moor there, aren't we?",
"Yes, of course. And if your prisoner is right, what about the loot?",
"The stolen silver will be sold at #sTortuga# and we'll fairly share the profits. what do you think?",
"Indeed, we could earn a lot.. Ok, I accept to be your partner. when do we leave #sTortuga#?",
"I have the feeling that the expedition is too risky. You should look for someone else.",
"Well captain, maybe I'll see you again one day.",
"Maybe, goodbye!",
"Excellent! I've already made the preparations so we can go right now. But before, let me just introduce my fiancée, Miss Elizabeth Swann, to you. She'll be useful during this expedition. Indeed, she's a good fighter!",
"Finally, we found a shore.",
"Indeed, I was right when I said the coast is uneven. Let's go into the jungle to see if the spaniards have settled the island.",
"Me too!",
"Now, we are so close to the goal, I'm not willing to give up.",
"Dash it! He escaped.",
"NO GOOD! Now, he's going to warn the convoy...",
"We have no option but to attack the convoy as quickly as possible.",
"I think so. Let's go.",
"I checked out. The boxes are full of silver.", 
"I love hearing news like this! Let's go to the ships. I want the silver under the protection of our cannons.",
"The sale of the silver has yielded 150 000 gold coins. Normally, it would be 75 000 for each one. But it would be fairly to give a part to Konrad Kulczycki and his companions right?",
"Exactly, Captain Turner. They deserve it. Their help has been decisive. What do you think about 30 000 gold coins for them?",
"I agree. So, there will be 60 000 for each one.",
"Excellent! This expedition has been very profitable.",
"You brought us in under a pirate flag. I'm not a pirate!",
"You are now! And do you think they would have let us sail in here unhindered if we flew the King's colours?",
"You. You're the one they're hunting. The pirate.",
"You seem somewhat familiar. Have I threatened you before?",
"I make a point of avoiding familiarity with pirates.",
"Ah, well, then it would be a shame to put a black mark on your record. So, if you'll excuse me... I'll be going.",
"You threatened Miss Swann.",
"Only a little... I mean I had to get her out of the water, now didn't I?",
"You insult her! Draw your sword!",
"If you insist! But I am very good, you know.",
"Well as you see, I'm good too. I not only make these swords, I practise three hours a day.",
"You need to find yourself a girl, mate! Or perhaps the reason you practice three hours a day is that you're a eunuch. Are you?", 
"I practice three hours a day so that when I meet a pirate, I can kill it! Anyway, the guards are here now, so the jig's up.",
"Oh dear, oh dear! And I was just starting to have fun.",
"WAIT! This is not justice!",
"I like your style Will. Very dramatic!",
"This man has helped the crown, not betrayed it.",
"Keep going, keep going. I'm liking it more and more.",
"What do we do now?",
"We go to Barbossa's cave... Mr. Gibbs, check out the beach, then stay with the ship, and remember... Keep the Code.",
"WAIT! It is me you want. My name is Will Turner, my father was Bootstrap Bill Turner, his blood runs in my veins.", // TALISMAN changed from -->I am the son of Bootstrap Bill Turner, it is my blood that will lift the curse.",
"Now Will, let's not do anything stupid here.",
"My conditions for my surrender are that you let Elizabeth and the Interceptor's crew go, and er, ",
" too. You must release them, or I will jump overboard and be lost to Davy Jones locker and the curse will never be lifted.", // TALISMAN changed
"Glad you remembered me there lad.",
"I heard all that. You'll get no money for me pirate! I'm not the son of a nobleman.",
"Quiet down lad. I know who you are. You are the son of William Turner of England. You are currently on the run because you stole the Interceptor to go sailing after Elizabeth Swann who is currently a prisoner on the #scursed_ship#. Savy?",
"How did you know all that? And why did you do what you just did?",
"I know your father, lad, and he asked me to look out for you. Which is what I'm doing. So we need to get to #sTortuga# and then after the #scursed_ship#, and your Elizabeth.",
"My father would never know a pirate! What did you do to him?",
"Look lad, your father and me go back a long way. He sent you a weird coin right? And you lost it, right? Your father and I help each other out from time to time, and this time it's me who's helping him, by helping you, Savvy?",
"Well, I suppose so, if you know that much. So you'll help me rescue Elizabeth, yes?",
"One thing at a time, #sTortuga# first, we will need a crew and I know we can get one there. So let's get aboard shall we, before dear Oswald really thinks it through? And comes back for you.",
"You. ",
"Aye.",
"You are familiar with that ship - the #scursed_ship#?",
"I've heard of it.",
"Where does it make berth?",
"Where does it make berth? Have you not heard the stories? Captain Barbossa and his crew of miscreants sail from the dreaded Isla de Muerta. It's an island that cannot be found except by those who already know where it is.",
"The ship's real enough. Therefore its anchorage must be a real place. Where is it?",
"Why ask me?",
"Because you're a pirate.",
"And you want to turn pirate yourself, is that it?",
"--",
"--",
"Here they come.",
"What are you doing with my face?",

};