string DLG_TEXT[35] = {
"You look like a naval officer. Normally I'd love to buy a drink for someone serving #spronoun# country so valiantly, but I'm afraid I'm waiting for a friend.",
"Thank you. I hope your friend arrives soon.",
"You look like the sort of #sperson# who is willing to take risks for money and probably willing to bend a few rules, am I right? I have a proposition for you. Are you interested?",
"That depends on the proposition.",
"Sorry, you must have mistaken me for someone else.",
"Then follow me upstairs. This is best discussed privately.",
"Lead on, then!",
"You know how governors are, right? Taking people's money, calling it 'taxes', then treating themselves to fine ships and fine food? How would you like to get your hands on a governor's money?",
"Presumably the governor isn't going to just give it to you, but if you have a plan, I'm interested.",
"More likely we'd end up as a guest in said governor's prison for the rest of our very short lives. Count me out.",
"Indeed I do have a plan. We shall disguise ourselves as soldiers. Then we simply march into the town hall, claim we're arresting the governor on charges of fraud, confiscate his cashbox as evidence, and leave town before anyone realises what's happened.",
"'Simply' is right! If it's that simple, why hasn't anyone tried it before?",
"Everything is simple after someone has done it for the first time. But that's the point. It takes nerve to pull it off, but it's so blatant that they'll never suspect it's a bluff.",
"OK, you've got me convinced. When do we hit the town hall?",
"There's simple and there's stupid, and this sounds stupid. Find someone else.",
"Not this town. #sDouwesen# is a much richer prize. We just need to find a ship.",
"It's your lucky day, then. I have a ship. Follow me.",
"Good day.",
"Good bye.",
"That is true, officer. I was doing nothing wrong. This #sperson# has a ship and I have paid #spronoun# for passage.",
"I'm not going down there! Horrible, slimy...",
"What - the tunnel or the people in it?",
"Both. If you insist on going in there, then this is where we part company.",
"Suit yourself.",
"Hello, ",
"! So they got you as well?",
"Yes. What did they catch you doing?",
"It was a bit silly, really. I'd been fined for something trivial, then I tried to break into the court cashier's office to get the money back.",
"What happened?",
"Breaking out was harder than breaking in. A guard patrol came by just as I was climbing out of the window. Why are you in here?",
"Remember that idea of yours to rob the governor by posing as an officer and arresting him? After we parted company, I decided to try it. I got a soldier drunk, stole his uniform, got some fake papers saying I'd been commissioned, and paid the tailor to adjust the uniform. Then I paid the governor a little visit.",
"Didn't they fall for it?",
"Oh, they fell for it alright. I'd probably have got away with it if I'd stayed away from #sDouwesen# afterwards.",
"That's a wonderful tale. Would you mind if I wrote a book about it? I seem to have plenty of time to do the writing.",
"Not at all. It was your idea, after all.",
}