string DLG_TEXT[29] = {
"Please leave. I have work to do.",
"...",
"But I need to speak with you.",
"Really? Well, speak up.",
"I want to know what you and the priest's assistant were talking about.",
"Tell me what you and the priest's assistant talked about...or else.",
"I am sorry. I don't know what you are talking about.",
"To be blunt, I believe you falsified several letters, and I want to know if it's true or not.",
"And what evidence do you have? Opinions are not facts. All those rumours about my past don't give you the right to accuse me now.",
"Calm yourself. Your past is none of my concern. I'm not judging you. I'm only interested in those letters.",
"Listen, you can tell me what I want to know in polite conversation, or at the tip of my sword. But you better tell me everything...or else.",
"And I already told you I don't know what you are talking about.",
"Perhaps I can make it worth your while?",
"Well, then perhaps I'll have to use more unpleasant methods of questioning.",
"You want to offer me money?",
"Yes, if you'll tell me whether it was you who wrote those letters or not. As soon as I know the truth, I'll leave, and you won't have any further problems.",
"Ah, but the truth is costly. Pay me 2000 gold, and then I'll tell you.",
"Perfect, here is your money.",
"That's exactly the answer I would expect from the one who wrote those letters.",
"I can tell you the truth for free. No, I didn't falsify those letters, and I had nothing to do with them. Now leave me alone.",
"All right.",
"You should have guessed I was involved after I agreed to take the money from you.",
"I wanted to make sure.",
"I admit that you outwitted me. Yes, it was me who wrote those letters, so I hope you don't have any more questions for me?",
"No, go on about your business, goodbye.",
"Your threats do not inspire me.",
"So, you're not going to tell me anything? Then it's time to make you talk.",
"Defend yourself!",
"Let's see what kind of fighter you are.",

};