string DLG_TEXT[15] = {
"ЎAsн que ahн estбs, ",
"! ЎCasi pensй que no tendrнas el coraje de aparecer!",
"Bueno, como puedes ver, estoy aquн. ЎAsн que no te preocupes!",
"їPreocuparme? їYo? ЎJa! ЎLo ъnico que me preocupa es que derrames tu sangre sobre mis preciosas ropas!",
"Bueno, veremos quiйn es el que sangra.",
"Muy bien, entonces. Resolvamos este asunto de una vez por todas.",
"No hay nada que resolver, #sfriend#. Tu hermana solamente fue muy, muy amistosa conmigo, Ўja ja!",
"No hay nada que resolver, #sfriend#. Tu hermano solamente fue muy, muy amistoso conmigo, Ўja ja!",
"Eres muy mal perdedor. El barco es mнo. ЎTe vencн justamente y sin trampas!",
"#sputa#! ЎDiablo de #sgender# sin honor!",
"ЎEso es un insulto que tendrбs que pagar!",
"ЎVete al infierno, ",
"! En Guardia!",
"ЎEn Guardia!",
"amigo mнo",
};
