string DLG_TEXT[24] = {
".....",
".....",
"їQuiйn eres, seсor?",
"Soy el capitбn Joaquim de Almeida. Conocн a un empleado de la empresa comercial de tu marido en #sEleuthera#.",
"ЎGracias a Dios que estбs aquн! Mi esposo estб en peligro y pensй que tъ podrнas ser el hombre indicado para lidiar con esta situaciуn.",
"їQuй le pasу a tu marido?",
"Mi marido fue a #sSantiago# por negocios pero fue capturado por piratas y ahora piden un rescate si quiero volver a verlo vivo.",
"Entonces, es un secuestro. їCуmo se pusieron en contacto contigo?",
"He recibido una carta. Debo pagar el rescate contactando con alguien en #sSantiago.",
"їPor quй no pagas el rescate?",
"Piden mucho y, sobre todo, no tengo confianza en ellos. Podrнan quedarse con el rescate y matarlo de todos modos.",
"Tienes razуn al decir que es una situaciуn peligrosa. Yo tambiйn podrнa morir en esta misiуn.",
"Si vuelves con mi marido, te pagarй 30.000 monedas de oro.",
"Yo esperaba mбs, seсora...",
"Entiendo... bueno, mi ъltima oferta son 40.000 monedas de oro. no puedo pagar mбs.",
"Eso estб mejor. Estoy de acuerdo en ayudarte. їQuiйn es el hombre con el que debo contactar en #sSantiago#?",
"No es suficiente, por desgracia. Debo rechazar tu oferta. Encuentra a algъn otro para esta misiуn. ЎAdiуs!",
"Lo harй. Adiуs, capitбn.",
"En la carta, los piratas me dijeron que tenнa que hablar con el tabernero de #sSantiago# y preguntar por Abel Barco.",
"Muy bien. harй lo que pueda para traer de vuelta a su marido.",
"Gracias, capitбn. Estoy ansiosa por ver el final de esta pesadilla.",
"ЎGracias, capitбn! ЎMuchas gracias! ЎLo hizo! Mi marido ha vuelto.",
"No fue fбcil. Pero sн, lo hicimos.",
"Como prometн, aquн estб su recompensa: 40.000 monedas de oro.",
};
