string DLG_TEXT[34] = {
".....",
".....",
"їQuй estбs haciendo frente a mi casa?",
"Supongo que tъ eres Laura Cotton. La verdad es que necesito tu ayuda.",
"Sн, soy Laura Cotton y mi ayuda cuesta 50 monedas de oro. Por adelantado.",
"Bueno, no es esa clase de ayuda.",
"їNo? ЎPues adiуs!",
"ЎEspera! Si me ayudas, recibirбs mucho mбs dinero. Te lo garantizo.",
"ЎExplнcate!",
"Este trabajo es muy fбcil. Solo tienes que ofrecer tus servicios a un oficial de la Armada y atraerlo hasta tu caso.",
"їPor quй un oficial de la Armada? їQuй estбs tramando?",
"No puedo decнrtelo. Pero no te preocupes, no queremos matarlo. Solo queremos su uniforme.",
"Podrнa meterme en problemas si te ayudo.",
"їCrees que el oficial irб a informar a sus superiores de que estaba en casa de una prostituta cuando unos bandidos lo dejaron en cueros? No lo creo.",
"Hum. En mi caso, siempre puedo decir que no te conozco y que estabas intentando robarme.",
"Correcto. Entonces, їtenemos un trato?",
"Depende del dinero que puedas pagarme...",
"200 piezas de oro.",
"Me parece que no. Quiero el doble o no hay trato.",
"Un poco caro, їno te parece?",
"Me da la sensaciуn de que ese uniforme es muy importante para ti. Asн que estoy segura de que puedes pagar mбs.",
"Estб bien, sabes negociar. Te pagarй.",
"ЎNo tan rбpido! Son 200 ahora y otros 200 cuando tengas el uniforme.",
"Estб bien, toma estas 200 piezas de oro, pero no intentes engaсarme. En ese caso, no creas que serнa tan galante.",
"De acuerdo, pero no tengo tanto dinero encima ahora mismo. Volverй en unas horas con el dinero.",
"Eso espero, si quieres que te ayude. Me encontrarбs en la ciudad.",
"їY bien? їTienes mi dinero?",
"Sн, por fin. Toma estas 200 piezas de oro, pero no intentes engaсarme. En ese caso, no creas que serнa tan galante.",
"Casi. Volverй pronto.",
"Gracias. No te preocupes. Maсana por la noche, estarй en la taberna. Serб fбcil encontrar allн a ese oficial. Esperadme cerca de mi casa.",
"Eso haremos.",
"Primero, pбgame el resto de mi dinero.",
"Gracias. Cuando depsierte, le dirй que a mн tambiйn me atacaron y me robaron.",
"Gracias. ЎBuena suerte!",
};
