string DLG_TEXT[340] = {
"Hemos llegado al puerto en el asentamiento pirata en Nevis. Hice levantar mi Roger personal para que nadie nos dé problemas. Los oficiales y una parte de su tripulación han elegido hacer su camino a través de la selva para Charlestown. Supongo que no quieren ser perseguidos por los ingleses como traidores. Por desgracia, no tienes esa opción. No puedo agradecerte lo suficiente por lo que hiciste por mi tripulación y por mí.",
"El Capitán Champers era un cerdo de hombre y lo que pretendía para usted era monstruoso. No vi una opción.",
"Perros traicioneros. Supongo que lo vi venir. ¿Qué puedo hacer por usted, Capitán?",
"Lo siento Capitán Fletcher, no hay tiempo para cháchara. necesito estar lejos antes de que aparezca la Marina. Sé que una tormenta está furiosa pero enfrentaré ese riesgo, y zarparé de inmediato. ¡Adiós y buena suerte!",
"He terminado con esta vida pero mis hombres necesitan un hogar. Son buenos marineros, ferozmente leales, y te deben sus vidas. Harías bien en aceptarlos. Deberías revisarlos y asignarles tareas que se ajusten a sus habilidades. Sugiero al Sr. Sullivan como primer oficial, pero por supuesto la elección depende de usted. (Abra la ventana de sus Pasajeros para ver a sus nuevos oficiales)",
"Sí, hablé con Sullivan. Parece un marinero competente y un buen tipo. Estoy seguro de que su gente sabe lo que está haciendo.",
"Las autoridades te perseguirán con una voluntad poderosa por lo que has hecho. Estarán buscando tu cabeza ya sea por tierra o por mar.",
"Cierto. Tendré que estar al tanto de los asesinos así como de la Marina.",
"Tienes que cuidarte las espaldas todo el tiempo, y será mejor que te lleves un guardaespaldas cuando estés en tierra. El Sr. Kildare es especialmente intimidante y un excelente contramaestre.",
"Tendré cuidado. ¿Hay algo más, Robert?",
"Sí, hay algunos asuntos que tendrá que atender de inmediato.",
"Muy bien, sigue adelante.",
"Recuerdo todo muy bien. Gracias.",
"No importa todo eso, la Marina podría estar dirigiéndose hacia nosotros ahora mismo! ¡Tengo que salir de babor ahora, antes de que me atrapen en el ataque, tormenta furiosa o no!",
"En primer lugar, lleve su equipo personal. Recuerde, siempre debe tener su espada, pistola y catalejo con usted. Quién sabe lo que puede suceder.",
"Dónde se guardó todo cuando me mudé a la cabina del capitán?",
"Todos tus efectos están en el gran cofre detrás de ti. He traído tu armario también.",
" Sólo acércate a él y verás el 'Icono de la mano' en la esquina superior izquierda de la pantalla \nEsto significa que puedes hacer algo allí. Cuando vea el icono, simplemente pulse el botón 'Acción'.",
"Ya veo.",
"Si usa una caja o un cofre de esta manera, verá una interfaz que le permitirá tomar objetos del contenedor o ponerlos en él \nAhora, coja sus posesiones, Capitán, y hable conmigo de nuevo cuando haya terminado.",
"Muy bien, un momento.",
"No has olvidado algo? Parece que aún no has tomado todas tus posesiones.",
"Oh sí, cómo podría olvidarlo! Discúlpame un momento.",
"Muy bien. Antes de continuar, debemos ocuparnos de una cosa importante que podría determinar su supervivencia durante las visitas. Cada nave tiene un armario de armas donde se almacenan las armas usadas por los grupos de abordaje, usted podrá encontrarlo en la 'Cabina del Capitán'. Este casillero tiene un símbolo especial, un cuchillo cruzado con una pistola, pero se accede a él como un cofre normal. Cuanto mejores sean las armas que ponga allí, más exitosa será su tripulación durante el combate cuerpo a cuerpo.",
" Su tripulación pondrá todas las armas de vuelta después de la acción de embarque, junto con los que toman de los enemigos derrotados. ",
"Su tripulación se llevará las armas con ellos, lo que debe recordar para reponer con frecuencia los suministros en el armario de armas. ",
"Cuando usted esté en la cabina de una nave capturada puede inspeccionar el armario de armas que hay allí, para encontrar armas adicionales.",
"Por cierto, podría enseñarte un poco sobre esgrima, si quieres. Pregúntame.",
"Supongo que me vendría bien un poco de entrenamiento. Enséñame.",
"No estoy interesado en esto, Robert. sigamos adelante.",
"Me estoy rayando con esto. Ya es suficiente.",
"¡Genial! Ahora usted debe equipar sus armas y catalejo. Para hacer eso pulse la 'Pantalla de caracteres' (f2) y luego seleccione el icono 'Inventario' en la parte superior derecha de la pantalla. Una vez dentro de su inventario, usted verá algunas categorías en la parte inferior de la pantalla, 'Arma', 'Medicamentos', 'Artículos', 'Mapas' y 'Objetos de misión'. Para equipar tu espada haz clic en el icono 'Arma' y luego busca tu espada, luego haz clic en el icono 'equipo'para equiparla o en el icono 'liberar' para des-equiparla. Haga lo mismo para su pistola.",
" Cuando haya terminado haga clic en el icono 'Elementos' y elija su catalejo y equípelo. También puede utilizar la tecla 'quick-equip' en el teclado. Tenga en cuenta que su hoja debe estar equipada antes que su pistola. También tenga en cuenta que, no todos los artículos pueden ser equipados. Ahora equipe su espada, pistola y catalejo, y luego hable conmigo de nuevo.",
"Solo un momento...",
"No podrás defenderte muy bien solo con tus puños.",
"Muy bien.",
"Oye, te olvidaste de tu pistola. también debería estar equipada.",
"Por favor discúlpeme, estoy bastante abrumado por toda esta nueva información!",
"Lo haré ahora.",
"Ahora, para ayudar a sus huéspedes, poner ese montón de ",
" en tu armario de armas",
"OK.",
"Entiendo la idea; los pones ahí y sigamos con cosas más importantes.",
"Parece que aún no ha equipado el armario de armas.",
"espera un momento...",
"No hay problema. Preste atención, por favor. En la esquina inferior izquierda verá el icono de su carácter. La barra roja de arriba es su salud. La barra azul representa el estado de carga de su arma. Y el círculo por encima de esas barras muestra cuántos disparos le quedan en su pistola.",
"Entiendo",
"Bien. Necesitamos algo de espacio para nuestros ejercicios. Sígueme; cuando te acerques a la puerta verás el icono 'Open Lock' en la esquina superior izquierda de la pantalla. Pulse la tecla 'Acción' para ir a la siguiente ubicación.",
"Una pista sobre.",
"Ahora, desenvaina tu espada con la tecla 'Desenvaina/Envaina Espada'. Primero deberás familiarizarte con los controles, para que no te ataque. Utilice la tecla 'Acción' para atacar y la tecla 'Pistola' para disparar su pistola.",
"Déjame intentarlo.",
"Sólo un segundo. Para ganar rápidamente un poco de distancia entre tú y el enemigo, puedes saltar hacia atrás pulsando la tecla 'Esquivar'. Ten en cuenta que no puede hablar con nadie con el arma desenvainada. Así que antes de hablar, envaine su arma pulsando la tecla 'Desenvaina/Envaina Espada' de nuevo.",
"Lo tengo. Ahora déjame intentarlo.",
"Bueno, ¿estás seguro de que has entendido todo hasta ahora?",
"Sí, y gracias por la instrucción Robert",
"No, creo que lo intentaré de nuevo.",
"Estoy harto de toda esta instrucción, vamos a seguir adelante con otras cosas.",
"Muy bien, eso es suficiente. ¿Estás listo para algo de acción real?",
"¡Claro que sí, vamos!",
"Aún no. Déjame practicar un poco más.",
"No hay problema.",
"Gracias.",
"Voy a luchar contra tí esta vez. Ten cuidado y no olvides de que se puede bloquear los golpes entrantes con la tecla 'Bloque'. Si te apresuras en el combate sin pensar, pronto estarás alimentando a los buitres.",
"Lo tengo. vamos a empezar.",
"¡No está mal, no está mal! Ten en cuenta que si has sido herido en una pelea puedes recuperar algo de salud usando pociones, vendas y otros elementos curativos. Para ello debe pulsar la tecla 'Menú rápido' y seleccionar el icono Usar. A continuación, pulse la tecla 'Acción', seleccione el elemento de curación de la lista, y pulse la tecla 'Acción' de nuevo.",
"Ya veo. ¿Qué sigue?",
"Quiero entrenar un poco más. Vamos a luchar de nuevo.",
"Basta de estas lecciones. Estás despedido.",
"Hmm... parece que necesitas más práctica... Ten en cuenta que si has sido herido en una pelea puedes recuperar algo de salud usando pociones, vendas y otros elementos curativos. Para ello debe pulsar la tecla 'Menú rápido' y seleccionar el icono Usar. A continuación, pulse la tecla 'Acción' y seleccione el elemento de curación de la lista, y pulse la tecla 'Acción' de nuevo. Ahora, vamos a intentarlo de nuevo.",
"Si tú lo dices... Empecemos de nuevo.",
"Mejoraré mis habilidades más tarde. ¿Qué sigue?",
"Basta de estas lecciones confusas.",
"Siempre listo!",
"Préparese.",
"Eso es mucho mejor. Ahora puedo dejarte ir a tierra sin ninguna preocupación.",
"Qué es lo siguiente?",
"Sigo pensando que necesito más práctica.",
"Basta de estas lecciones. Despedido.",
"No... supongo que llevará más tiempo enseñarte esgrima adecuada. Quizás deberías pasar unos días a bordo entrenando.",
"¿Podemos intentarlo una vez más?",
"Me recuperaré más tarde. ¿Qué sigue?",
"Bien. Antes de salir de la nave déjeme contarle sobre sus habilidades. Puesto que un capitán experto siempre tiene más oportunidad de sobrevivir en este mundo cruel, usted debe evolucionar su personaje\nluchando contra enemigos y completar misiones, su personaje gana puntos de experiencia. Cuando tiene suficiente experiencia, su personaje obtiene nuevo rango y puntos de habilidad. Al utilizar estos puntos en diferentes habilidades, puede mejorar varios aspectos del personaje\npara tener toda información del personaje pulse la tecla 'Pantalla de caracteres' (F2). Allí podrá ver rango, reputación, dinero, habilidades y puntos de éxito. Ahora tienes algunos puntos de habilidad\nque puede distribuirlos ahora o más tarde.",
"¿Cómo puedo distribuir puntos de habilidad? ",
"Bien. Antes de irnos, déjame hablar sobre tus habilidades y destrezas. Pues un capitán hábil siempre tiene más posibilidades de sobrevivir en este mundo cruel, deberás evolucionar tu personaje\nluchando contra enemigos y completando misiones, tu personaje gana puntos de experiencia. Cuando tienes suficiente experiencia, tu personaje obtiene nuevo rango y puntos adicionales de habilidad y atributos. Mientras que tendrás la opción de decidir qué habilidad te gustaría mejorar, varias habilidades mejorarán de acuerdo a tus acciones.\nPor ejemplo, durante la esgrima, tu habilidad de combate mejorará. Cuando la mejora alcanza el 100 por cien, ganará un nivel superior.\nPara tener toda información sobre tu personaje pulsa la tecla 'Pantalla del personaje' (F2). Allí verás rango, reputación, dinero, habilidades y puntos de golpe del personaje, así como porcentaje necesario para subir una habilidad al siguiente nivel. Ahora tienes un punto de habilidad\nPuede repartirlo ahora o más tarde.",
"Me gustaría saber cómo ganar más puntos de habilidad.",
"¿Puedo obtener una descripción de las diferentes habilidades?",
"Olvídate de esos puntos de habilidad, vamos a continuar con algo más.",
"Si desea hacerlo ahora, abra la 'Pantalla de caracteres' (F2), luego seleccione la habilidad deseada y pulse la tecla 'Acción' para aumentar su valor\nPara obtener una Habilidad debe elegir el icono de Habilidad en la parte inferior de la pantalla y pulse la tecla 'Acción'. Luego verá una lista de todas las habilidades. Seleccione la que desea aprender y pulse la tecla 'Acción' de nuevo para leer la descripción de la habilidad. Para aprender una Habilidad pulsa la tecla 'Acción' por tercera vez\nAlgunas no pueden ser aprendidas hasta que hayas aprendido sus requisitos previos.",
"Lo haré ahora.",
"Olvídate de esos puntos, vamos a continuar con algo más.",
"Háblame cuando hayas terminado y continuaremos.",
"Claro. ¿Cuál te interesa?",
"Liderazgo.",
"Cuerpo a cuerpo.",
"Navegación.",
"Precisión.",
"Cañones.",
"Abordaje.",
"Reparación.",
"Defensa.",
"Comercio.",
"Suerte.",
"Puedes mejorar el liderazgo hablando con la gente de las ciudades, completando misiones y pagando a tu tripulación regularmente.",
"Gracias. ¿Y los otros?",
"Basta. Háblame de otra cosa.",
"Para mejorar tu habilidad Melee, obviamente deberías practicar mucho con tu espada, ¡ten cuidado de no herir a transeúntes inocentes!",
"Usted mejorará su habilidad de navegación cuanto más activamente navegue su barco. Aquí las tormentas y tornados también pueden ayudar a mejorar su experiencia, aunque seguramente dañarán su nave también.",
"Disparando ya sea su pistola o cañones se puede ganar puntos en Precisión. El uso de una pistola es más eficaz.",
"Hacer progresos en Cañones requiere que luches y golpees a otros barcos o fuertes durante las batallas.",
"Mejorarás en Abordaje cada vez que lances un gancho.",
"Observe cómo el armador repara sus naves, y obtendrá experiencia en la reparación. Cuando empiezas a reparar tu barco durante las batallas marítimas, también conseguirás el mismo efecto.",
"Convertirse en un maestro de la defensa requiere experiencia de bloqueo durante peleas de espadas y la reparación de buques en el astillero o durante una batalla marítima.",
"Si usted trata a menudo con los comerciantes, puede mejorar rápidamente su habilidad en el comercio. Cuando tu Comercio es bajo el comerciante te desplumará; ¡cuando es alta les harás eso a ellos!",
"La suerte mejorará cuando juegues a las cartas en las tabernas. También la mejorarás al terminar misiones y al hablar con personas encontradas; pero ten cuidado, Capitán, cuando su suerte es baja, algunos de ellos pueden tratar de robar sus pertenencias.",
"¿Necesita algún consejo sobre cómo debe distribuir sus puntos de habilidad? ¿Poner algo en Melee Combat y algo en Liderazgo para empezar, o quizás Comercio para cuando vendamos nuestro cargamento?\nBut no hay prisa con eso, siempre se puede hacer en su momento o más tarde cuando surja la necesidad.",
"Esta habilidad le permite controlar mejor a su gente. Si tienes una voluntad fuerte, tu tripulación tendrá menos probabilidades de rendirse en una pelea. También al verte tan seguro y fuerte, tus enemigos estarán desmoralizados y podrían rendirse antes. Esta habilidad es muy útil para un capitán de un velero en estas aguas.",
"Creo que distribuiré mis puntos ahora.",
"El daño inflingido en una pelea con tu espada depende de esta habilidad. También afecta la posibilidad de perforar bloqueos enemigos y bloquear con éxito los ataques enemigos.",
"Esta habilidad muestra lo bueno que eres navegando tu barco. Si esta habilidad es alta, tu barco será más rápido y más ágil bajo tu mano.",
"Un buen objetivo puede ayudarle a ganar una batalla marítima incluso contra un enemigo abrumador. Esta habilidad representa con qué precisión sus artilleros pueden disparar bombas y bolas. Recuerde, disparando manualmente desde la cubierta siempre le da una mejor precisión.",
"Esta habilidad está relacionada con la precisión y también es importante para las batallas navales. Cuanto más alta esta habilidad, más rápido su tripulación recargará los cañones, y más rápido que va a disparar una salva.",
"Esta habilidad es muy útil para cualquier pirata o corsario. Le permite lanzar con precisión ganchos de embarque para atrapar una nave enemiga y tratar de tomarla con su grupo de embarque.",
"Esta habilidad le permite reparar su nave en mar abierto. Cuanto mayor sea la habilidad, mayor es el porcentaje de daño que puede reparar. Además, usted necesitará tener algunas tablas y lona a bordo de su barco para llevar a cabo cualquier trabajo de reparación.",
"La tripulación es la parte más frágil de la nave y la más importante. Sin suficiente tripulación cualquier nave se vuelve incontrolable y torpe. La habilidad de defensa le ayuda a proteger a su tripulación del fuego de cañón enemigo. También disminuye las pérdidas de tripulación en las batallas marítimas.",
"La habilidad del comercio es esencial para los comerciantes y mercaderes. Con un comercio alto usted consigue mejores precios en las tiendas y a veces usted puede incluso conseguir un descuento al contratar a un oficial.",
"Bueno, estas islas son sólo semi civilizadas. Las autoridades siguen siendo débiles, y muchos aventureros y criminales directos vienen aquí para aprovecharse de eso. Así que las calles y las tabernas están llenas de ladrones, contrabandistas, jugadores y asesinos a sueldo, y tú debes ser inteligente en la calle si deseas tratar con esos tipos y evitar trampas y robos. Ya sea que apuestes, pelees, pases contrabando o te roben, si tienes mucha suerte, tendrás más éxito, ¡tendrás menos daños y obtendrás mayores ganancias!",
"Ahora debería recordarte el negocio del que necesitas encargarte.",
"Vamos.",
"En primer lugar, hay carga para vender, debes vender al comerciante local de aquí, que no es muy difícil de encontrar.\nAdemás, el barco recibió algunos daños en la última batalla y necesita ser reparado. El astillero local debe manejar fácilmente las reparaciones.\nLuego, tendrás que contratar nuevos tripulantes para reemplazar a los que se irán. Habla con el tabernero local sobre la contratación de más tripulación, y recuerda que siempre se puede preguntar por direcciones a la gente.",
"¿Eso es todo?",
"Casi. Su catalejo parece viejo y rayado, no le dará la ventaja que necesita en estas aguas peligrosas. ¿Tal vez podrías comprar uno nuevo? Debería estar disponible para la venta en algún lugar de la ciudad.",
"Una cosa más, estas aguas están llenas de barcos de la Marina Real, es posible que desee levantar la bandera inglesa cuando salga del puerto. Puede cambiar su bandera entrando en la pantalla de caracteres (F2) y luego en la pantalla de 'relaciones'. ¡Ondeando la bandera inglesa puedes engañar al fuerte y escabullirte entre ellos, si la suerte está de tu lado!",
"Vamos.",
"Si quieres comprar un nuevo catalejo puedes hacerlo ahora mismo. Veo algunos mercaderes bajo sus tiendas.",
"Muy bien, vamos a hacerlo.",
"Puedo hacerlo más tarde. Continuemos con algo más.",
"Usted puede irse. Voy a encontrar mi camino por los alrededores.",
"Tenemos que movernos al centro de la ciudad. Debemos ir a las puertas de entrada y luego seguir adelante a través de la puerta de al lado de la otra parte de la ciudad. Sígame a las puertas y cuando vea el icono 'Candado abierto' en la esquina superior izquierda de la pantalla, pulse la tecla 'Action' para ir a la siguiente ubicación.",
"El asentamiento pirata se encuentra lejos de la costa, en medio de la selva. Para llegar allí, debemos ir detrás de esas rocas, y luego girar a la izquierda cerca de una cabaña. Más tarde debemos ver la empalizada. Acércate a la puerta de madera después de mí y cuando veas el icono 'Candado abierto' en la esquina superior izquierda de la pantalla, pulsa la tecla 'Acción' para ir a la siguiente ubicación.",
"¡Ni siquiera hay un comerciante callejero aquí! Afortunadamente, aprendí que podíamos comprar un catalejo en la tienda local. Iremos allí para vender nuestra carga, y ver si tienen un nuevo catalejo.",
"Como usted desee. Sígame.",
"...",
"Habla con uno de esos hombres bajo las tiendas de campaña. Están vendiendo diferentes bienes. Deberías de comprarles un nuevo catalejo. Pregúntales qué tienen que ofrecer. Verás cuatro categorías en la parte superior de la pantalla, 'Arma', 'Medicinas', 'Objetos' y 'Mapa'. En cada categoría verás una lista de 'Objetos', haga clic en el elemento que necesita, a continuación, elija cuántos desea y haga clic en 'OK' para hacer la compra, a continuación, ya estará listo para irse.",
"Lo tienes. Genial. Ahora vamos a vender la mercancía que trajimos a la isla.",
"Bien. ¿Dónde podemos hacer eso?",
"Lo haré yo mismo. Regresa a la nave.",
"Oye, ¿dónde está ese nuevo catalejo? ¡No lo veo!",
"Lo voy a comprar ahora.",
"He decidido no comprarlo ahora. Continuemos.",
"Voy a seguir solo, Robert.",
"Como usted diga. Ahora vamos a vender los bienes que trajimos a la isla.",
"La tienda local está en el distrito más adelante. Te guiaré allí.",
"La tienda local debería estar dentro de las murallas del pueblo. Sígame a las puertas y cuando vea el icono 'Candado abierto' en la esquina superior izquierda de la pantalla, pulse la tecla 'Acción' para ir a la siguiente ubicación.",
"Sé dónde está la tienda, y tienes algunas mercancías a bordo que deberías vender para conseguir dinero para pagar las reparaciones de los barcos y la reposición de la tripulación. Para ver qué productos tienes a bordo debe pulsar la tecla 'Pantalla de caracteres' (F2) y luego seleccionar 'bodega de carga'. A continuación, elija una nave de las disponibles para ver. Verá una lista de productos que su barco tiene a bordo. Puede desplazarse a la derecha o la izquierda. También puede ver la cantidad de munición que ha dejado en su nave.",
"Gracias por la información. ¿Nos vamos ahora?",
"Ya no necesito tu ayuda.",
"Sígueme. Te mostraré la puerta correcta y luego estarás por tu cuenta. Pero si tienes alguna pregunta, házmela.",
"Ahora ve a hablar con el comerciante. Vende tú ",
" y ",
"Para conseguir un catalejo, dígale al comerciante que usted quiere comprar algunos equipos personales y que debe tener uno para la venta. Después de que usted deba vender nuestra carga, que es ",
"pero no compres nada, necesitamos dinero para arreglar nuestra nave y contratar más tripulación. ¿Necesita más detalles sobre el comercio?",
"Podemos utilizar el dinero adquirido del comercio para contratar a la tripulación y reparar la nave. ¿Necesitas más aclaraciones?",
"Sí, eso sería útil.",
"No, yo puedo manejarlo.",
"Es muy simple. Hable con el comerciante y dígale que desea comerciar con mercancías de carga. Luego seleccione un barco que se utilizará para el comercio. Después de que veas una lista de mercancías. Selecciona una mercancía que deseas vender o comprar y pulsa la tecla 'Acción'. A continuación, selecciona el botón 'Comprar' o 'Vender' y elige la cantidad deseada que quieres comprar o vender. A continuación, pulsa la tecla 'Acción' de nuevo para confirmar la transacción.",
"Gracias por la explicación.",
"Te esperaré fuera de la tienda. Por cierto, si usted no ha asignado sus puntos de habilidad todavía puede ponerlos en su habilidad de Comercio para obtener más ganancias de sus transacciones.",
"Te esperaré fuera de la tienda. Recuerde que tratar mucho con los comerciantes le ayudará a elevar su 'Comercio' habilidad, dándole la oportunidad de obtener un mejor trato con ellos.",
"De acuerdo, muchas gracias.",
"Usted debe vender todos los bienes que tiene. Pero eso está bien por ahora. A continuación le mostraré cómo se puede contratar a la tripulación para su barco. Esto se puede hacer en una taberna.",
"Bien.",
"Lo encontraré yo mismo. Eres libre de irte.",
"Ahora que tenemos dinero podemos ir y contratar una tripulación extra. Para eso, vamos a la taberna.",
"Sígueme. te llevaré a la taberna.",
"Voy detrás de tí.",
"Sí. Aquí se puede contratar tripulación. Además, a veces se puede encontrar un buen oficial para su barco en una taberna, hablar con la gente tal vez le dé suerte. Para reclutar a nueva tripulación hable con el dueño de la taberna, que está de pie en el bar, y pregúntele acerca de la reposición de la tripulación. A continuación, seleccione una nave para asignar a la tripulación, a continuación, seleccione el botón 'Contratar'. Después de eso, seleccione cuántos marineros desea. No obstante, preste atención a la moral de la tripulación. Luego pulse la tecla 'Acción' para pagar su oro y contratar a estos marineros.",
"A veces sucede que no hay tripulación libre en una isla... desafortunadamente, pero tendrá que navegar a otra isla para contratar a la tripulación\nAhora contrate alguna tripulación. Le esperaré fuera.",
"Estaré allí pronto..",
"Estamos bien. Todo lo que tienes que hacer ahora es reparar el barco. Mientras contratabas a la tripulación, fui y encontré el astillero local.",
"Bien. vamos para allá.",
"Sé dónde está. Puede volver a la nave.",
"Disculpe, pero será mejor que contrate tanta tripulación como pueda. Su nave siempre debe estar bajo su completo control. Pero, ya que siempre se puede hacer más tarde, podemos ir a arreglar nuestra nave ahora. He encontrado el astillero local.",
"¡Sí, sí! Sígame",
"Voy.",
"Ahora estamos en el astillero. Aquí puede reparar su nave, mejorarla, venderla o comprar otra. Además, en un astillero puede instalar diferentes cañones en su nave. ¿Quiere que le dé instrucciones sobre cómo reparar su nave?",
"Sí, sí, dímelo",
"No, puedo manejar eso.",
"Muy bien. Hable con el armador y pídale que revise su barco. Entonces elija un barco que necesita ser reparado, usted tiene sólo uno en este momento. Luego seleccione 'Reparar'. Si usted tiene suficiente dinero sólo tiene que pulsar la tecla 'Acción' después de resaltar el botón 'Arreglar Todo', y su barco será totalmente reparado\nSi no, entonces usted tendrá que seleccionar un porcentaje de casco y aparejo para ser reparado. Seleccione Casco y luego establezca el valor deseado. A continuación, haga lo mismo con Velas. A continuación, seleccione 'Aceptar' y pulse la tecla 'Acción' para confirmar las reparaciones.",
"Muy bien, muchas gracias.",
"Bueno, si es así, te esperaré afuera.",
"Supongo que eso es todo. Puedo darte algunas sugerencias sobre qué hacer si quieres. Por mi parte, he terminado con la vida en el mar. He perdido una mano, una pierna y ayer casi pierdo mi pellejo. ¡Me voy a retirar aquí, en esta taberna! mis días son para beber y apostar. El Sr. Sullivan y los demás te servirán bien.",
"Supongo que eso es todo. Te puedo dar algunas sugerencias de qué hacer si quieres\nTodo lo que sueño es pasar mi vida de jubilación, cruzando los mares sólo para la relajación, y tal vez un poco de beneficio personal, aquí y allá. Verás, he estado en el mar desde que era niño y ahora es el momento de dejar todo eso atrás ¡y disfrutar de la taberna local!",
"Gracias por toda tu ayuda, Robert.",
"Si alguna vez necesitas contratar nuevos oficiales los encontrarás para ser contratados en la Taberna, y estaré encantado de ayudarte con mi consejo cada vez que pases.",
"¿Puede darme algunas sugerencias sobre qué hacer a continuación?",
"Háblame de navegar mi barco.",
"Háblame de disparar cañones.",
"Háblame de abordar naves enemigas.",
"Hábleme de pagar a mis oficiales y tripulación.",
"Hábleme de 'Navegación directa'.",
"Háblame de la 'Moral' de la tripulación.",
"Háblame de izar 'Banderas'.",
"Gracias por su ayuda. ¡Adiós!",
" en la colonia de ",
"Bueno, cuando estuve en la última tienda, me di cuenta de que tienen precios muy bajos para ",
". Si fuera tú, lo compraría aquí y navegaría hacia ",
" - puedes conseguir un buen precio para ",
" allí. También obtendrá una ganancia considerable para ",
"Desafortunadamente no puedo ayudarlo, Capitán.",
"Muy bien. Pero antes de que te vayas, debo recordarte a qué negocio ibas a atender mientras estabas en tierra.",
"Casi. Su catalejo es viejo y arañado. Usted debe conseguir uno nuevo. Debe estar disponible para la venta en algún lugar de la ciudad.",
"Y una cosa más: Mishipman Percy era leal al capitán y corrió a tierra tan pronto como llegamos. Sin duda la guarnición del fuerte está aprendiendo lo que pasó incluso ahora. Le aconsejo que vuele el unión Jack cuando salga de este puerto.", // KK
"...Si necesitas mi ayuda de nuevo, estaré en la taberna local.",
"Gracias. Hasta la vista",
"Como desees. Puedo darte algunas sugerencias de qué hacer si quieres, pero ahora debo dejarte \n. Estoy cansado de la vida en el mar. He perdido una mano, una pierna, y ayer casi pierdo mi pellejo. ¡Me voy a retirar bien aquí, en la taberna que hay! El Sr. Sullivan y los demás te servirán bien.",
"¿Puede darme algunas sugerencias sobre qué hacer a continuación?",
"Bueno, dirigir un barco no es tan duro como parece. Los barcos se mueven con el viento. Cuanto más duro sopla el viento, más rápido va el barco. Usted puede fijar sus velas en dos posiciones; Completo y Batalla, o golpearlos por completo\nEn posición de batalla, el barco se vuelve más maniobrable, pero la velocidad máxima se reduce. Con todas las velas, su barco se mueve más rápido pero gira más lento. Siempre esté atento a la dirección del viento, su barco no irá muy rápido si usted está navegando contra él.",
"Disparar en modo tercera persona es simple, sólo mantenga a los enemigos dentro del rango de disparo de sus cañones y pulse el botón 'Disparar' cuando los cañones están cargados. Sus cañoneros apuntarán automáticamente los cañones a su enemigo\nSea consciente de que durante el modo primera persona, puede utilizar el disparo manual así como el disparo automático, pero tenga cuidado si utiliza el disparo manual, independientemente de si apunta a un buque amigo, o no, le disparará\nDisparar manualmente desde la cubierta es un poco complicado. Deberías apuntar tus cañones a barcos enemigos, pero no como lo haces con una pistola o mosquete. No olvides que los cañones disparan sobre la trayectoria balística y que debes elevar el cursor apuntando más alto si el enemigo está lejos de ti\nO bajarlo si el enemigo está cerca. Incluso puedes hacer un fuego directo, pero sólo si tu enemigo está muy cerca de ti.",
"Para embarcar en una nave enemiga deberías acercarte mucho a ella. Sus velocidades respectivas también deben ser casi las mismas a menos que tenga la habilidad especial o alta habilidad Abordaje\nEntonces necesita abrir el 'Menú de Comando Rápido' y seleccione el comando Embarque. Entonces tendrás que abrirte camino a través de las cubiertas de la nave enemiga con tu tripulación, cortando y matando a los marineros enemigos, ¡saqueando a medida que avanzas!\nDespués de ganar la batalla de embarque, puede saquear todas las mercancías de esa nave o llevársela con usted si tiene un oficial adecuado para asignar como capitán en la nave capturada.",
"Hay dos maneras de pagar a su tripulación. Usted puede pagar por 'Salario' o 'Firmando Artículos' con ellos. Tenga en cuenta que algunos de su tripulación podrían desertar si usted tiene poco liderazgo al cambiar entre 'Salario' y 'Dividir el botín'.",
"Háblame de pagar 'Salario'.",
"Háblame de 'Firmando Artículos'.",
"Si usted está pagando el salario, el 8 del mes la ventana de salario aparecerá preguntándole si desea pagar a su tripulación. Si eliges no pagar, la moral de la tripulación bajará. Bajará menos si tienes la ventaja de la 'Voluntad de Hierro'. Si la moral de la tripulación baja lo suficiente se amotinarán, y eso es algo que no quieres. La moral será más estable, pero no tan alta como si hubiera firmado artículos.",
"Para 'Firmar Artículos' con su tripulación y oficiales, usted debe estar dispuesto a dividir su botín. Puede firmar el artículo usando la 'Pantalla de Caracteres' (F2) y luego ir a 'Nave' y luego hacer clic en el icono 'Tripulación', también puede hablar con cualquiera de su tripulación a bordo de su barco o a 'Loan Shark' cuando esté en tierra. Cuando quieras dividir tu botín regresa al 'Loan Shark' y dile que quieres dividir tu botín, entonces él te explicará qué hacer.\nAl hacerlo, tendrás que dividir tu botín para pagar a tu tripulación y mantenerlos felices. Al dividir su botín usted podrá elevar su Moral más alto (que con la opción de 'Salario') pero será más difícil mantener el control. Digamos que si eres codicioso y ganas mucho dinero y no lo compartes con tu tripulación, será más difícil para ti mantener la moral alta; un capitán demasiado codicioso siempre consigue una tripulación rebelde.",
"'Navegación directa' es simple si tienes la marcha correcta y un buen sentido de orientación. El significado de 'Navegación directa' es que ahora se puede navegar de una isla a otra, mientras estás en vista '3D Navegación'. No es necesario volver al mapa del mundo para navegar de isla en isla\nNo obstante, utilizando el mapa del mundo será más rápido que '3D Navegación' PERO 'Navegación Directa' le da la oportunidad de disfrutar de la vista mientras navega directamente de isla en isla. Usted puede encontrar alguna carga flotante o tesoro a lo largo del camino, o incluso encontrar otros buques\nSin una brújula es difícil conseguir su orientación a menos que usted sea un viejo marinero experimentado como yo. Ten en cuenta que cada hora que pases en '3D Navegación' añadirá un día a tu viaje. Si observa que su tiempo de viaje es muy largo, puede utilizar la tecla 'Aceleración' para adelantar el tiempo más rápido.",
"La 'Moral' de su tripulación es muy importante. Con alta 'Moral' su tripulación funcionará muy bien, con baja Moral el rendimiento de su tripulación será baja y estará sujeto a un posible 'Motín', si deja que la 'Moral' se hunda mucho\nHay maneras de mantener su moral alta, manteniendo el nivel alto de su comida y ron, pagando a su tripulación con 'Salario' le dará buen promedio en 'Moral', 'Firmar artículos' aumentará su moral más alto que 'Salario', pero es más difícil mantenerlo así\nTambién puede aumentar la moral doblando las raciones de ron. ¡Pero hay posibilidad de una pelea de borrachos!\nSu 'Moral' bajará si se niega a pagar a su tripulación, pierde demasiadas peleas, baja la ración de comida y ron, se queda sin comida o ron durante su viaje, la contratación de más tripulación en la taberna, tener mucho dinero de la tripulación en tu poder (mejor sería poner alguno en armario-armas del barco) y tomando nueva tripulación tras captura de una nave enemiga.",
"La bandera puede ser útil si se usa correctamente. También representa a diferentes naciones como; 'Inglaterra', 'Francia', 'Holanda', 'España', 'Portugal', 'Pirata' y 'Colores personales' (su bandera). Si cambias la bandera de una nación a otra, puede ser muy útil. Si tu enemigo es 'Francia' y tienes que amarrar en 'Puerto Francés', Cambiar a la bandera 'francesa' te ayudará a entrar en ese puerto sin sospechas\n recomiendo que si izas otra bandera porque tienes que entrar en 'puerto hostil', hazlo antes de ver la'Isla'. No querrás que los guardias que vigilan la 'ciudad' o el 'fuerte' te vean cambiando de 'bandera', ¿verdad? Sea consciente de su 'Fama', cuanto más famoso sea, más difícil será colarse. Ser popular es bueno y malo, supongo\nTambién puedes fingir que eres un barco 'francés' navegando con bandera 'francesa' y buscar un posible objetivo 'francés' y una vez que te acercas a él, levantas la'Bandera' apropiada y te enfrentas a tu enemigo.",
"Nos vemos, Capitán. espero que le vaya bien en el Caribe.",
"Claro. Espero que seas feliz en tierra firme.",
"Necesita mi consejo, capitán?",
"Te llamé porque, como ya sabrás, planeo dejar esta vida de perro marino y retirarme en esta isla. Por lo tanto, como entiendo completamente y apoyo sus aspiraciones, decidí concederle una nave propia. Tome el mando de eso ",
" que capturamos recientemente. No la necesito e incluso la llamé '",
"' para alegrarte",
"¡Oh Dios mío... ESA nave no! Esperaba obtener el mando de su ",
"Excelente, justo lo que necesitamos para salir del puerto sin que lo noten. Estoy seguro de que la tormenta que viene no será tan mala, ¡así que me voy! Buena suerte en el asentamiento.",
"¿Qué has dicho? no he oído.",
"Gracias, muchas gracias... me encargaré de este barco como si fuera hecho por mis propias manos!",
"Robert, me gustaría darte las gracias por todo y desearte suerte en tierra firme. Ahora me gustaría visitar la ciudad.",
"Para un mejor comienzo puedes tomar cosas de ese cofre, encontrarás armas y un catalejo allí. También puedes elegir entre el resto, incluso el dinero que encuentres allí. Oh, y también traje tu vestuario aquí en caso de que quieras cambiar.",
"Usted puede ir a la ciudad si lo desea; Tengo algunas cosas que hacer aquí. Nos encontraremos en la taberna local.",
"Felicitaciones por su ascenso, ",
". Por la presente son requeridos y destinados para comandar la nave asignada a usted, y para hundir, quemar o tomar como un premio todas las naves enemigas que pueda.",
"Sí sí, sí, señor!",
"Cualquier barco que capturen será llevado a puerto y subastado. Recibirán una parte del dinero, al igual que sus oficiales y tripulación. No se le permite abandonar el mando de su propia nave bajo ninguna circunstancia. ¿Lo entiende?",
"Sí, señor. lo entiendo.",
"Muy bien. Entonces que los buenos vientos y la buena fortuna naveguen con usted, ",
"Gracias, Sr. Zarparé tan pronto como llegue a puerto.",
"Capitán, ¿está seguro de que quiere hacer esto? Sabe que lo que hizo no fue del todo honorable.",
"La señora sabía lo que estaba haciendo. Si su hermano no puede lidiar con eso, entonces él puede tratar conmigo!",
"Capitán, aunque estamos felices de servir bajo su mando, no tenemos mala voluntad hacia nuestro comandante anterior. Es sólo un hombre desafortunado.",
"¡Me acusó de hacer trampa! ¿Cómo se atreve a hacer algo así? Le haré pagar por eso.",
"Por la presente se le ordena ir encubierto en este pueblo hostil y generar tantos problemas para nuestros enemigos como sea posible. Será peligroso y no espero que nos volvamos a ver.",
"Entendido, Sr. A partir de ahora, iré por mi cuenta.",
"¡Capitán, tenemos suerte de haber llegado a este puerto amistoso a través de esa horrible tormenta! La nave ha sufrido daños sustanciales y hemos perdido a muchos de la tripulación.",
"Será costoso prepararnos para zarpar de nuevo. Desafortunadamente, no tenemos medios honestos para hacerlo en esta isla. Tendremos que arriesgarnos y ver si podemos encontrar un agente de contrabando en la taberna.",
"Capitán, ¿está seguro de que no puede ser convencido de hacer el trabajo que se suponía que haríamos? ¡Hasta que esta maldición sea levantada, nunca podremos poner un pie en tierra! Y todo este aspecto sospechoso no es tan importante.",
"¿Transportar a las almas perdidas que murieron en el mar por la diosa del mar? ¡Nunca! ¡He sido traicionado y el mundo conocerá mi ira! Ningún barco en el mar está a salvo de mí.",
"Capitán, todas las monedas que pudimos encontrar han sido guardadas en el armario de armas como usted ordenó. ¡Pero parece que algunas han desaparecido, señor! Uno de los tripulantes debe habérselas llevado.",
"¿Es así? ¡Antes de que nos demos cuenta, estarán esparcidos por todo el Caribe y nos será difícil recuperarlos! Iré a tierra inmediatamente para iniciar la búsqueda.",
"No puedo creer que el fuerte de #sTortuga# no nos disparara entrando en el puerto!",
"No había nada de que preocuparse. El gobernador francés de aquí es realmente muy indulgente con todos los que izan una bandera pirata. Haría bien en recordar que!",
"No había nada de qué preocuparse. Francia gobierna aquí y estamos en paz con Francia.",
"Siento que el barco te esté mareando, pero no tenemos cuartos diferentes disponibles para tí. Ahora, por favor, sal de mi camarote.",
"Muy bien, entonces. esperemos no caer por la borda en esta tormenta. Usted podría meterse en un montón de problemas con su patrón si usted pierde uno de sus pasajeros!",
"El caballero sabía lo que estaba haciendo. Si su hermano no puede lidiar con eso, entonces él puede tratar conmigo!",
"Buenas noches, mi #schild#.",
"Tú... ¡Mantente alejado de mí!",
"Un poco tarde para eso. Es un barco precioso, ¿no?",
"¿Por qué estás aquí?",
"Oh, nunca he estado lejos, ",
" Estaba a tu lado, aunque fuera en el fin del mundo.",
"Fuiste tú.... quien me mantuvo vivo.",
"No, no, no, ",
" Estas son las almas a bordo de esta nave. En cada una de tus batallas, las recoges, ellas obedecen tu voluntad y te protegen. Como yo lo ordene. Me hace sentir muy orgulloso. Los gritos, el olor a pólvora y sangre. Es como cuando haces una inversión que sigue creciendo hasta el día en que se cobra. Y ese día ha llegado, ",
",",
" para esparcir a los muertos en tu camino y extender mi influencia en este mundo.",
"Hágalo usted mismo.",
"No funciona de esa manera. Estás bajo contrato, ¿recuerdas? Un día, me verás reaparecer reclamando las almas a bordo y tal vez tu alma te sea devuelta. Ese día, no estaré lejos. Estaré atento.",
"Eso está descartado.",
"No tienes elección. Olvida tu antigua vida.... es mía, ",
".",
" La muerte es sólo el principio.",
};
