string DLG_TEXT[429] = {
"Oh, it's you, ",
". What are you doing here?",
"None of your business ",
". And I could ask you the same question - but I'm too busy for that.\nSo just find a place to sit and leave me alone.",
"I didn't expect to see you here!",
"Glad to see you, too, ",
". I'm told you're spending your free time saving old people these days.",
"Now it's my turn to interrupt you. Where did you find such a useful lad, ",
"?",
"That's my secret, ",
". But you've heard what he had to say. So now we can work together, like I offered before.",
"Glad to see you waited for me. Now we can go together.",
"Of course. As soon as ",
"Vincent Bethune",
" here tells us where we're going.",
"It's an ambush! Get yourselves to his house and lock yourselves in.\nI'll hold them off for as long as I can.",
"Take care of yourself!",
"What on earth is going on here?!",
"Ah. ",
"Vincent Bethune",
" told me about you. You're ",
"Robert Christopher Silehard",
"'s errand boy!",
"Finally awake, are you?",
"What happened?",
"The time has come to pay a visit to the governor and ask him some pointed questions.",
"I'm right with you. Let's go.",
"Good, but we can't barge into the residence in broad daylight. Let's wait in the tavern until night falls.",
"Smart thinking. And I could use a drink.",
"Look, the sooner we get some answers from the governor, the sooner we can trust each other again.",
"Yes. I suppose you're right.",
"First of all, let's get out of this town.",
"Agreed.",
"We should split up here. We can get into more trouble that way.\nYou track down that lad who copied the legend, and I'm going to go after the idol.",
"That works for me. We can meet up at the lighthouse, where the old man lives.",
"??? What are you doing here?!",
"I was looking for you! How could I be so stupid?!",
"Well, look what the tide washed in. I thought we agreed to meet at the lighthouse.",
"I got tired of waiting.",
"Well, I think you'll agree the wait was worth it. I've found a logbook. Let's see, now...hang on.... Blast it! There's nothing here about where to find him! Wait - quiet! I swear I heard a door creak. Someone's coming!",
"So? Now I can find that Spanish corsair who supposedly kidnapped the girl.",
"Go to the pirate's ship.",
"Not yet. It's not time for that.",
"Now I need to look for that girl. If she's not around here somewhere, I'm in deep trouble.",
"...",
"I barely got away from those fanatics! This business is turning out to be hotter than I thought.",
"I should report this to Padre Domingues. But who's this?",
"Lucas's kidnappers demanded the ransom to be brought to this tavern, but they don't seem to be here themselves.\nAha, those two at the bar seem to be waiting for someone...",
"No need to waste time. They're probably the ones I need. (Show them the sign.)",
"Maybe I should eavesdrop on their conversation a bit first? (Listen to the conversation.)",
"Luck smiles on me today. ",
"Pepin Bertillon",
"'s ship is docked, so its captain should be somewhere around. The only thing left to do is to find him and put a few holes in his chest.\nBut first I've got to know for sure it's him I'm killing - the locals are a violent bunch, and a mistake could cause me a lot of trouble.",
"...",
"Don't bother yourself with that. I don't believe you're one to waste time, so...\nI'm guessing you're here for a lad named ",
"Raoul Rheims",
". Like it or not, I'm going with you.",
"Fine, ",
", you may accompany me.",
"How long should we wait?",
"Researcher",
" did say it could take days.",
"It's already been a week. I need action!",
"We're talking about hundreds of pounds of gold. Isn't that worth a week of waiting?",
"To you, maybe. I can't take much more of this. I need to be on the move. Why can't he finish the translation on the ship?",
"You know, I never thought of that.",
"Yeah, I guess a pirate doesn't have much use for common sense, does he? So what use do you have for the gold, ",
"?",
"What?",
"Should I talk slower? What. Will. You. Do. With. Your share of the treasure?",
"I'll buy an English island, I suppose, and make my own rules. Or maybe I'll become an English peer. That could have its rewards. And you?",
"That's a secret.",
"All right. Be that way.",
"Are you going to stand against the regular fleet?",
"No. I'm going to shatter it!",
"I'll command the fort! Just watch out for the cannonade!",
"Just hit what you aim at!",
"We won! They'll be writing songs about that battle, or I'm an old sea hag! We could take the whole archipelago together! Or the entire Caribbean!",
"Sure we could. But it might make more sense to have a chat with ",
"Researcher", // NK - "Moses Blinman",
" first.",
"Listen to you, ",
"! You should be ashamed of yourself, crushing a sweet girl's dreams with your boring logic!",
"Treasure always comes first, my dear. Afterwards, if you still want to conquer the Caribbean, I'll be right with you. Consider it a promise.",
"I hope the scholar fellow had enough time to examine those squiggles. I doubt we could resist a second attack.",
"I'm not sure the governor has any more warships.",
", the temple seems to be situated somewhere inland. Let's take a walk!",
"Right, but we don't want to call attention to ourselves. We should leave the crew here until we've checked out this temple with our own eyes.",
"I can't believe we made it! It's just a matter of time before we're rolling in ancient gold!",
"If there's any gold there at all.",
"Don't say that! We couldn't have come so far for nothing!",
"We'll see.",
"There are three passages here, and any one could be the right one. Where should we go?",
"I don't know. This could be the trap ",
"Researcher",
" was talking about.",
"Then we should split up. We'll cover more ground that way. I'll take the left passage for myself, and we'll see who finds the treasure first!",
"Hey, wait...",
"Looks like we can go to #sisland_Khael Roa# now!",
"I'm not sure it'll be so easy.",
"Maybe we should go ahead and search the temple while he's reading those squiggles.",
"Not without some idea of where we're going! The devil himself could get lost in that maze!",
"Have it your way, but I'm going for a walk. Oh! I already see something! Keep in mind I found it first!",
"What?",
"That's got to be the alcove ",
"Researcher",
" was talking about. But where's the treasure?",
"I don't know. Even if we pried all the gold from the walls, it wouldn't amount to much...",
"We can't waste much more time looking, ",
". They'll capture the town!",
"I just want to be sure you don't sink me, too, after we take care of the English fleet.",
"Now, that really hurts, ",
".",
"Kidding! I'm just kidding. Good luck!",
"Good Lord! What was that?",
"I don't know!",
"Three thousand devils, ",
"! No one could survive that! My treasure! Could we just try to get part of it? Just a wee bit?",
"I don't know. I suppose it's not the only treasure in the world.",
"What's the difference? Oh, this is such a bitter loss!",
"Somehow I get the feeling you're not as disappointed as you pretend to be.",
"I shouldn't go back there. I need to get out of #sRedmond# and fast!",
"That was a tough one, no? Are you still in one piece?",
"Well, I don't think I'm going to die today, anyway.",
"Glad to hear it - although I'm not sure Death generally cares what people like us think.",
"Let's go spring ",
"Researcher",
" from the jail.",
", one thing at a time. Let's save the poor old man first.",
"Whatever you say.",
"What should we do now? We can't find the treasure if we can't translate that legend. And I'm afraid the old man...",
"We've already set ourselves against the #sGovernor# and the English crown. What do we have to lose if we just capture that miserable town and free Aurentius?",
"I didn't realize you had suicidal tendencies. But if you're serious about this, then let's have a little fun!",
"Now you're talking! And I'm feeling like a real pirate. I'll attack the fort from the sea, and you and your men can lay siege to the town from land. What do you say?",
"I say I've created a monster, ",
". But I'm ready when you are!",
"Calm down! What happened?",
"What happened? I was told you were dead! I sailed to #sGreenford# to find out what really happened. The tavern owner told me he hadn't seen you. Then some lad approached me out of the blue and said he knew where you were. And I fell for it like a fool!",
"Relax. Everything's all right now. What happened then?",
"I sailed here to #sIsla Muelle# with that lying dog. He said that we'd meet with the pirates holding you prisoner. He led me into the jungle - and then ran off when I was jumped by two friends of his. By the time I'd dealt with them and returned to shore, he was gone. And so was my ship!",
"You went through all that for me? Cold and haughty Danielle rushed my rescue without a second thought!",
"Keep talking, and you'll be mumbling around my saber!",
"I'm through! Not another word, I promise! So...the tablets are completely lost to us?",
"You really do think I'm just a foolish girl, don't you? No, I kept them with me.",
", my dear, did I ever tell you you're the smartest lady pirate I know?",
"No. As I recall, you've mostly been enraptured by my 'unmatched sharp tongue.' Now tell me: How in the world did you get here?",
"After I captured the ship that was sent to deliver the idol to the #sGovernor#, I set a course for our meeting place. But I ran into foul weather and was washed overboard like a landlubber. I was sure I was dead, but as it happened I found myself washed ashore near #sisland_Douwesen#.",
"Yes. Fortune does favor the foolish.",
"Easy, now! I've had a rough time of it. When I came to my senses, I staggered into #sDouwesen# and managed to get a small ship. Not long after, I ended up here. You can well imagine how surprised I was to see my old ship in Muelle harbor. She was still being repaired after that storm.",
"Incredible! Fortune favors the foolish, but even you aren't fool enough to be THAT lucky!",
"Well, in that case...I made it all up. Yes! Just a tall tale to entertain you. At any rate, here I am.",
"And here I am. And now we have the idol. We should sail together to #sisland_Oxbay# and talk to Aurentius about translating that legend.",
"Oh, I didn't dare to dream you'd say that! Sailing together - it sounds so... sweet!",
", dear, do shut up!",
"Yes, I'm working for him.",
"You devil! And you've set an ambush for me at the town gate?!",
"I didn't...",
"Die!",
"Still playing hard to get, are you? Fair enough...",
"Just be quiet, ",
", will you?",
"It seems funny to you? I'd like to see you laughing with a pile of kindling at your feet!",
"So he was serious? I thought you helped him carry some food or something.",
"Seriously, though - what are you doing here?",
"I'm trying to find someone, but the closer I get, the harder things go for me.",
"I've been having more than my share of trouble, too.\nAnd all because of some lad. He's a captain, too, as it happens. Goes by the name of ",
"Raoul Rheims",
"Raoul Rheims",
".",
"Are you serious? We're looking for the same man! But why are you after him?",
"Gold, of course! A very powerful man wants a word with that devil, and he's promised me a tidy sum if I bring him in.",
"I see. Maybe we could look for him together.",
"I'm all for that, but I'll tell you up front that I have no clue where he is.",
"We're even, then - neither do I.",
"Well, we can't do any worse together than we've done apart. And it's got to be some kind of fate, our meeting like this.\nWhen shall we go searching for our mutual 'friend'?",
"Well, I have some business to settle here...",
"No problem. Actually, I've got some loose ends to tie up, myself.",
"Fine. Let's meet here in one week. What do you say?",
"Perfect. I'll see you then.",
"Good luck!",
"Don't you remember anything?",
"My head is splitting, ",
". Don't push me. Why don't you explain what you're doing here?",
"Hey, if anybody should be mad, it should be me! Catching that dagger where I did wasn't the most pleasant thing that ever happened to me!",
"You deserve it! I know you're hunting me for the English governor. Let's just settle this now. Draw your blade!",
"Settle down, ",
". You've got it all wrong. I'm not hunting you at all. I didn't even know that ",
"Robert Christopher Silehard",
" wanted you dead.",
"Don't give me that, ",
"! You've always said you'd do anything for money!",
"Oh, come on, ",
"! I was playing around! You expected me to be a scoundrel. You like scoundrels! I couldn't disappoint you.",
"What are you talking about?! I always considered you a honest man!",
"Oh, no! All that time we knew each other, and we were always at odds.",
"That's true enough! You were always trying to snatch the best jobs from under my nose!",
"But when did I ever do anything to you? From where I stand, it looks like I was always saving your skin!",
"Maybe. But you're still working for a man who wants me dead!",
"Yes, I was, ",
". I've recently...retired. But ",
"Robert Christopher Silehard",
" doesn't know that yet.",
"What, didn't he pay you enough?",
"Money's not the issue. Not this time. I just decided I didn't want to work for a man like him anymore.",
"What are you saying? You're a free man? Then leave me be!",
"Fine! I see you're as stubborn as ever. Good luck with the three corpses you've got on your hands.",
"?!",
"What else do you want?",
"...",
"Did you have something else to say, or can I go?",
"...Thank you...for your help, ",
". I'd be dead if not for you.",
"Forget it. Can I go?",
"Wait, ",
"! What are you going to do now?",
"I'm going to pose some questions to a certain dirty governor.",
"Just wait a minute, will you? You can't go there alone. That's suicide! If ",
"Robert Christopher Silehard",
" suspects anything at all, he'll kill you just to be safe!",
"Thanks, but I'll take my chances!",
"Not without me, you won't!",
"Why? I'll be fine alone.",
"First off, I have my own questions to ask him. And, second - ",
"What?",
"I know a good place to cast anchor on #sisland_Redmond#, where no one will be waiting for us.",
"All right, fine. We'll join forces for now.",
"Fine! But if you deceive me once more, ",
", I'll kill you, I swear!",
"What's going on? Those soldiers were trying to kill us!",
"I don't know, ",
", but you should head out of town - it's dangerous here.",
"So...where could he keep that paper? Let's see.",
"(Start searching)",
"The whole town is in a panic! They're shouting that the port is on fire. We can't go that way.",
"I have an idea. We'll say there are French troops in town. Shout it at the top of your lungs! It'll confuse the guards!",
"It looks like I see Nigel Blythe's figure far ahead. Interesting. Where could he be going?",
"...",
"Hm...Maybe I'm wrong, but it seems that one of my crew - Artois Voysey - just entered the town.",
"...",
"Officer Edgar Attwood just left my ship without my permission.",
"...",
"Hell! Somebody shot Artois! I must take him to a tavern and find a doctor for him!",
"...",
"Snorri: ...ing in this hole for two weeks already, and there's still no gold! And you told us that the old man will surely pay!",
"...",
"Billy: He will pay, he definitely will. But to gather so much gold is not such a quick thing to do.",
"...",
"Snorri: And what if he just doesn't give a devil's spit about his damn son?! What if instead of gold, a galleon full of bloodthirsty Spaniards comes here?!",
"...",
"Billy: Enough already! Have you ever seen a father who'd abandon his son in a situation like this? Don't worry, the admiral will pay the ransom. He doesn't really have a choice.",
"I've heard enough. These are the ones that I need. (Show them the sign)",
"Now to free Padre Domingues!",
"The cells are off to the right. Let's go.", 
"(I see a small mound of stones)",
"I bet there is something buried here. I'm going to dig.",
"(Ten minutes later)",
"What a beautiful sword! But there is a name engraved on the blade...",
"BARTOLOMEU! WHERE ARE YOU GOING???",
"Hmm... He doesn't seem to hear me anymore. I better follow him. He seems to be running to the store.",
"(A sudden storm is roaring)",
"Strange. Where did that storm suddenly come from? I better leave this place quickly.",
"(Another sudden storm is roaring)",
"Another sudden storm? I don't like this.",
"(The Spaniards detect your presence)",
"MOOOVEEEE!!!!! BROTHERS OF THE COAST!!!",
"(You see the port soldier)",
"That's him again! Let's catch him!",
"(Barbossa talking to his crew)", 
"Gentlemen, the time has come! Our torment is nearing an end! For ten years we've been tested and tried. And each man here has moved his mettle a hundred times over and a hundred times again. Punished we were the lot of us, disproportionate to our crime. Here it is! The cursed treasure of Cortés himself. Every last piece that went astray we have returned. Save for this!",
"Maybe you are immortal, but I can still knock you out idiot! Now, I have to join my crew to invert the situation on my ship.",
"Captain ",
"You are accused for crimes against the Crown. Said crimes being numerous in quantity and sinister in nature. The most egregious of these to be cited herewith: piracy, smuggling, sailing under false colours, arson, kidnapping, looting, poaching, brigandage, pilfening, depravity, depredation and general lawlessness. For these crimes, you are sentenced to be hung by the neck until dead. May God have mercy on your soul.",
"... I would seem not! ...",
"Oh well! ... I shall have to do the noble deed myself.",
"[The cursed coin in the necklace around Elizabeth's neck has called the #scursed_ship#]",
"Hmm... not one of my better days!",
"Now, there's a ship that might give me some leverage. I should go and take a closer look.",
"(I see the sand has been moved)",
"Someone has buried something here.",
"(Two minutes later)",
"A MAP! I bet the gold is there.",
"(Eight boxes of gold are in the cave)",
"I found the gold... but only a small part of the gold stolen in Aguadilla. Where is the rest?",
"(A few days later)",
"Time has come to see again my informer. Let's hope he found something.",
"(Two days later in the tavern)",
"Tonight, I must see the treasure.",
"(You listen to the conversation of these soldiers)",
"They belong to the Silver Fleet... I must warn Elting they installed a fortified camp in front of the fort.",
"I found no paper...",
"...but never mind - this dirty piece of parchment will do.",
"What!! The figure of a death's-head just where I had made the drawing of the beetle. No, my own sketch is upon the reverse, just as I had made it.",
"Had the skull been then there from the beginning, of course I could not have failed to notice it. So where did the skull come from???",
"I need to copy this 'text' before it vanishes again -",
"- Jupiter can go to Moultrie village and buy some paper there!",
"I can swear there's more hidden on this document. Maybe the coating of dirt might have something to do with the failure.",
"I'll try to rinse the parchment with hot water!",
"Now let's do a more methodical -",
"- investigation of the parchment.",
"Now the skull is gone! Only my sketch of the beetle remains. Let me think:",	//299
"When I drew the scarabæus there was no skull apparent upon the parchment. When I had completed the drawing I gave it to Mr Poe, and observed him narrowly until he returned it. He, therefore, did not design the skull, and no one else was present to do it. Then it was not done by human agency. And nevertheless it was done.",
"The weather was chilly (oh rare and happy accident!) and a fire was blazing upon the hearth.",
"I was heated with exercise and sat on the bed far from the fireplace. Mr Poe, however, had drawn a stool close to the chimney.",
"When I consider all these particulars, I doubt not for a moment that heat has been the agent in bringing to light, upon the parchment, the skull which I saw designed upon it.",
"Chemical preparations exist, and have existed time out of mind, by means of which it is possible to write, upon either paper or vellum, so that the characters shall become visible only when subjected to the action of fire.",
"I knew it! There are some some figures arranged in lines!",
"I have made all I can for now. Tomorrow I'll try something else but now it's time to go to sleep.",
"A new day - and I'm going to try a better way to heat up that parchment...",
"... but first: I have to get the fire burning again. It's freezing cold in here.",
"If I place the parchment on a clean and dry plate or dish on that cauldron, maybe the document will become more thoroughly heated.",
"But no, I don't know where the oven-proof dish is and we're out of wood. I'll have to wake up Jupiter!",	//310
"I must hurry now and to write the full code down -",
"- before it vanishes again!",
"I have got all the six items -",
"- now let's place them in the Detective Kit!",
"I'm very curious to see what Mr Poe",
"has come up with...",						//316
"Hmm, let's be careful now Jupiter, we're getting close to the Plantation Gates -",
"- wonder how we can get in without being noticed...",
"Alright, there it is. ",
"Now tell me Jupiter do you know where the slave barracks are located?",			//320
"Look Jupiter -",
"- patrolling guards everywhere down there!",
"Okay, here you are: Ink, Pen and a piece of Paper -",
"- now please show me the shape of that rock.",
"Now that was new to me, Jupiter. I had no idea about your kungfu skills!?",
"Well, JRH thought it was time for something completely different here...",
"I found the Lever in the grass Jupiter. But it's no use placing it again ...",
"... guess it will only fall down.",
"I saw something - a Skull in a Big Tree!?",
"Better look again.",						//330
"Guess that's it! Now I just have to find that Tulip-Tree.",
"Just a lot of green - I'm not sure which way to look...",
"What am I supposed to do here?",
"Admire the view?",
"Okay, I found Devil's Seat. Let's return to Charleston again -",	//335
"- I'll need a Spyglass, a Compass and a Sextant to solve this.",
"There it is! And it looks just like the sketch,",
"now I have to find a way up the Rock.",
"I had hoped they were gone. What shall we do Jupiter -",
"- turn back?",							//340
"Jupiter, would you please go to Fort Moultrie and visit lieutenant G -",
"- ask him if we can borrow a Spyglass. They must have some items of that kind at the Fort!",
"Let me think: not the window, the boom is broken, the blades on the wall can't be moved. ",
"The only chance I've got is to use my Gunpowder and the Tinderbox. Maybe I can set fire to a piece of paper and await the Gunpowder explosion from a safe place?",
"I have to try using the Boom as a lever -",
"- to open the hatch.",
"First I'll make a roll of the mountain sketch -",
"- then I'll fill it up with Gunpowder!",
"The only spot where I can take cover -",
"- is in the corner behind the bookshelf.",
"No one here!",
"Ok, I'll rest here until they show up.",
"Oh no, they have removed the wooden steps!",
"How can we now place the Lever?",
"No! Look Jupiter - ",
"- the maroons must have guessed our destination.",
"Guess we can just follow the shore around the cliff to that Raft.",
"---",
"Are you coming Jupiter?",
"Yeah yeah, old Jup's here.",
"Yes, this must be the Tulip-Tree I saw! It's the only one with a brown stem.",
"Do you think you can climb it Jupiter?",
"Now Jup, I want you to work your way out upon that limb as far as you can -",
"- if you see anything strange, let me know.",
"Jupiter, do you hear me?",
"Yes, Massa Will, hear you ebber so plain.",
"Try the wood well, and see if you think it very rotten.",
"Him rotten, massa, sure nuff, but not so berry rotten as mought be. Mought ventur out leetle way pon de limb, dat's true.",	//368
"I knew it! We're heading in the right direction, Jupiter.",
"Uhu?",
"You'll see, but first we have to go back to Charleston and get some tools. I think we should consult mr Poe too...",
"Very well massa, let's go.",
"Looks like the maroons have left Jupiter?",
"Hmm, not so sure bout dat massa Will.",
"Damned! They got here before us, Jupiter.",
"!!!",
"Never mind de flour -",
"- I need them sacks for better things.",			//378
"No it's not locked but it's stuck.",
"I'll need something sharp to bend open this Chest.",
"Okay, so I'm first here -",
"- it's just to wait for massa Will and Mr Poe.",
"Aha, Edgar's not here yet -",
"- think I'll take a little nap while waiting.",
"I really need my Pistol, but it's still at the Blacksmith for repairs -",
"- and I don't have any money to get it back.",
"Worker's Tools are another thing. Perhaps I can 'borrow' some at the Church.",
"I'll look for the Priest, he should know how to get in there, even though the Church is closed for repairs these days.",	//388
"How did the Priest think we're could meet here!",
"Or maybe...Is there another way in?",				//390
"Hmm, the Gate is locked - ",
"- but first I have to collect all the stuff I need.",
"The ammunition to this new Percussion Lock Pistol was a little tricky -",
"- but now I'm ready to join my friend William outside town.",
"Jupiter, what are you doing?",
"Are you out on the branch with the Skull yet?",
"Well now, Jupiter, do exactly as I tell you — do you hear?",
"Yes, massa.",
"Pay attention, then! — find the left eye of the skull.",
"Hum! hoo! dat's good! why dare aint no eye lef at all.",				//400
"Curse your stupidity! do you know your right hand from your left?",
"Yes, I nose dat — nose all bout dat — tis my lef hand what I chops de wood wid.",
"To be sure! you are left-handed and your left eye is on the same side as your left hand. 
Now, I suppose, you can find the left eye of the skull, or the place where the left eye has been. Have you found it?",
"---",											//404
"Very good Jupiter, now please lower the rope six - seven feet!",
"Six - seven feet down, yes massa.",
"Are you ready Edgar, to mark the spot when I remove the GoldBug?",
"Sure, I'll use one of the pegs I found in the Church.",				//408
"You scoundrel, speak I tell you! — answer me this instant without prevarication! — which — which is your left eye?",
"Oh, my Golly, Massa Will! aint dis here my lef eye for sartain?",
"I thought so! — I knew it! — hurrah!",
"Jupiter, was the skull nailed to the limb with the face outwards, or with the face to the limb?",
"De face was to the limb massa.",
"Well, then, was it this eye or that through which you dropped the beetle?",
"Twas dis eye, massa — de lef eye — jis as you tell me.",
"Give me that Spade Jupiter.",
"If you say so, massa Will.",
"Jupiter, did you bring any Sacks from home?",
"Sure did massa Will, here take some.",
"Okay, take one Sack each -",
"- we can't carry all to the Boat now. We'll return to the Chest as soon as possible.",
"Jupiter, the maroon leader you called Hero, he was close to you, is that so?",
"This has been a very very long day -",
"- let's all get some sleep now!",
"There seems, however, only one plausible way of accounting for them
 — and yet it is dreadful to believe in such atrocity as my suggestion would imply. 
It is clear that Kidd — if Kidd indeed secreted this treasure, which I doubt not — 
it is clear that he must have had assistance in the labor.",	//425
"But, this labor concluded, he may have thought it expedient to remove all participants in his secret. 
Perhaps a couple of blows with a mattock were sufficient, while his coadjutors were busy in the pit, 
perhaps it required a dozen — who shall tell?",			//426
"I wonder if Lieutenant G knows anyhing about cipher -",
"- this means absolutely nothing to me.",

};
