string DLG_TEXT[35] = {
"Can't you see that the Cathedral is closed for repairs!",
"All right, all right.",
"Yeah I know. In fact that's why I have to get into the Church.",
"Is that so? Well it's locked anyway.",
"But there's an entrance from the Sacristy, right?",
"Indeed it is but the workers have locked it from the inside.",
"I guess I have to break in then...",
"No you're not! Maybe there's another chance...",
"Yes?",
"There is a way through the Wine cellars.",
"No problem.",
"Oh but there is! You have to pass the Old Mine as well.",
"And?",
"The rumour has it that Undead Creatures are moving around down there.",
"I'm not afraid.",
"But you should be. However if you'll get into the Cathedral alive maybe you can do me a favour?",
"Sure why not. Just show me the way to the Wine Cellar.",
"In time. Please follow me to the Sacristy first.",
"Okay, let's go.",
"Mister Poe. In the Cathedral please search for my Hymn Book. I've saved some very important documents inside. One of them is a Special Letter.",
"A Hymn Book with a Special Letter you say. Okay, how do I get into the Church?",
"First you have to climb up to the Town Terrace - there's a ladder somewhere as I recall it.",
"And then?",
"Then it's easy. Just find the Door to the Wine Cellar.",
"See you later then, Father.",
"Not so fast Mister Poe. I've got something you'll need badly in the Old Mine.",
"Yes?",
"Here. It's Holy Water so I'll hope you handle it with respect!",
"What's the purpose, Father?",
"If... you meet anything unholy - just pour a few drops on it. It may save your life.",
"Alright let's meet here later.",		//30
"No. I'm sorry but I'm a very busy Priest. Can you deliver the Book and the Letter to the House with the Gate, it's the one opposite to detective Mr Dupin's office.",
"Yes sure, Father. (The Brothel, I can't believe it!) I'll do that.",
"I know what you think Mister Poe but remember I'm a Priest for ALL the people in Charleston. Besides that I will pay you for your services.",
"Very good, Father. I'll be there.",

};