string DLG_TEXT[251] = {
"Dat was my last shot, massa Will.",
"Yes, I'm out of ammo too. Let's pick up the marsh-hens and return home.",
"Here, let me take dat sack.",
"If you say so Jupiter. Let's take the way through the shipwreck and saunter along the bank, in quest of shells and entomological specimens.",
"What de matter, massa?",
"Oh, nothing Jup.",
"De bug I see is a goole bug, solid, ebery bit of him, inside and all, sep him wing — neber feel half so hebby a bug in my life.",
"A Gold-Bug you say? Hmm, let's go back and search more closely!",
"Massa Will, you say noffin at all bout de bug?",
"Maybe you're right Jupiter. We'll go back and try to catch it!",
"Careful Massa Will, someone in de house!",	//10
"Are you sure Jupiter?",
"See de smoke Massa? I didn't light de fire I keep a tellin on you.",
"Oh oh, who can it be?",
"I take de guns massa.",
"Yes, thanks Jupiter.",
"What de matter, massa?",
"Don't you recognize our friend Mr Poe, Jup?",
"Dey aint no tin in him, Massa Will, I keep a tellin on you, de bug is a goole bug, solid, ebery bit of him, inside and all, sep him wing — neber feel half so hebby a bug in my life.",
"Well, suppose it is, Jup, is that any reason for your letting the birds wait?",
"Dinner!",	//20
"Very good, let's eat.",
"What's dat, massa?",
"A scrap of dirty paper I think. But I can use it to catch the scarabжus!",
"Oh it's getting late - I go to bed now massa Will - I have lock de door for night.",
"Thank you. One thing Jupiter, do you know where the large cauldron is?",
"Down stairs.",
"Good night then.",
"Jup, I want you to go to the boathouse - I think we have some wood left there.",
"De boothouse you say. And de Ovenproof Dish is in de food cellar, massa Will.",
"Thank you Jupiter. (I don't dare to ask where he had put the key.)",		//30
"I want you to go to Moultrie village and buy some sheets of paper.",
"Gimme de money, massa Will.",
"I have no money... take that big fish - I'm sure the village can sell it to the tourists.",
"Okay, Jupiter will go.",
"Oh yes, one more thing - could you also visit Lieutenant G at the Fort and bring me the Gold-Bug back.",
"I'm going to the Fort Jupiter, I need Lieutenant G:s help with this cipher.",
"See you later, massa Will.",
"Jupiter, did Lieutenant G leave any password for me?",
"What words, massa Will?",
"A paper maybe?",			//40
"Only de paper de golebug was in.",
"Show me that paper Jupiter.",
"Okay, a letter or a note then?",
"What letter, massa Will?",
"But it's in de middle of de night, massa Will.",
"Yes, it's too early. Let's rest for a while before going to Charleston.",
"But it's already late in the evening, massa Will.",
"Yes, it's too late. Let's wait until tomorrow before going to Charleston.",
"Jupiter, Mr Poe has moved I have heard. You know where?",
"Jupiter not sure, massa Will.",	//50
"But you escorted Mr Poe home the other night?",
"It was so dark Mr Poe had problem find de gate.",
"A gate. Well that's something - let's search for it!",
"'DEGREES' ??",
"!",
"Jupiter, have you ever heard of any building which went by the name of the Bishop's Hostel or Hotel?",
"Bessop, yes I know dat plantation very well...",
"Bessop, you say - hmm why not. Jupiter, where is that plantation situated?",
"We just exit de town on de jungle side, massa.",
"Is that so?",				//60
"Maybe we can sneak into de plantation at night, massa Will.",
"Yes, that's the only chance. But we need something to distract the guards with...",
"You mean fireworks or bombs?",
"Fireworks - that's a good idea. Wonder who's selling that kind of things.",
"The Chinese sell fireworks, massa.",
"The Chinese? You mean at the Chinese restaurant?",
"Yeah, hope de malaria is gone.",
"We'll see Jupiter.",
"Oh no, you want us to ",
"do de dangerous work hah?",		//70
"Okay, I do de Restaurant. You do de reading and stuff, massa Will.",
"Very good, it's all settled then. Now how do I start?",
"Massa Will, de Chinese sent some more stuff to you...",
"Let me see - what is it?",
"Charcoal.",				//75
"Salpeter.",
"Sulfur.",
"Charcoal and Salpeter.",
"Charcoal and Sulfur.",
"Salpeter and Sulfur.",			//80
"Charcoal, Salpeter and Sulfur.",
"Very good, hand it over Jup.",
"Massa Will, this is the last time de Chinese can help you with ingredients. He's ran out of eberything.",
"Is that so. Well, let me see what you've got there.",
"Gimme dose barrels Massa - yo get empty ones from Jup.",	//85
"Ahh, very good Jupiter.",
"I run de restaurant now, Massa.",
"We climb dat mountain massa Will and see de plantation from above first.",
"Good idea Jupiter, let's find a way up!",
"See de house with smoke - barracks are just behind it. Two barracks massa, one for de women and one for de male slaves.",	//90
"Hmm, the Plantation seems to be very well guarded...",
"Yes, look a watch-tower on your side massa.",
"Yeah, that way is impossible. They'll see me at once, maybe on the other side?",
"You go in alone massa Will?",
"Indeed I do, it's far to dangerous for a black man to enter this place. Maybe I can talk my way out of it if I get caught.",
"I see. Jup will do Firework outside, right? And look - they have a watch-tower on my side too.",
"You're right Jupiter. We'll have to get closer, keep your head down and follow me.",
"What is it massa Will?",
"I think it's better to wait until tonight.",
"Yeah, you have to hide among dose bales, massa Will, when you get inside.",	//100
"(Save..? What does he mean?) Okay, let's go down.",
"Keep close to de mountain side massa and wait for de Fireworks before you climb over dat fence.",
"I'll do that Jupiter.",
"Gimme dat Tinderbox and de Fireworks Chest, massa Will.",
"Sure, here you are Jupiter. Remember to check the numbers before you shoot the Rockets.",
"You want Jup to remove dat box, massa Will?",
"Sure, can you really do that?",
"What if I do de Lever and keep it in place while you continue alone massa Will?",
"But, that will leave you behind Jupiter.",		//109
"And you all by yourself to dat mystery Rock.",
"Hmm, that's okay. Here, take the Lever and give me a second to get to the Gate.",
"Good luck then massa Will.",
"See you later Jupiter and watch out for those bandits.",
"You okay massa Will?",
"Sure, please open the Gate again. And Jupiter, pick up that lever when it falls to the ground. We'll need it later.",
"No idea go back. Let's hope for the best.",
"But they are bandits?",
"Maroons, massa Will, maroons. Let me do de talkin', maybe we still have a chance.",
"You sure about this Jupiter?",
"Hello Hero, yeah I am a free man since long ago and massa Will found a Gole Bug - ",
"- you can see for yourself.",
"Where to now, massa Will? ",
"We need a Sextant, a Compass and a Spyglass.",
"To de Store then.",
"You know where it is Jupiter?",
"Sure, you have sent me there many times. It's next door to Mr Poe.",
"Let's go then.",
"They ate each other.",
"What are you talking about, you can't mean...?",
"Sure thing, Jup will go. Here's de tinderbox massa Will. And be careful with dat Pym... ",
"Just rumours Jupiter, nothing to worry about. Let's meet at Mr Poe's house Jupiter. ",
"You okay Massa?",
"Yes I'm fine, thank you Jupiter. And you got a Spyglass I see.",
"Here you are Massa Will...",
"Very good!",
"Ahh, massa Will. Jup have idea...",
"Let's here it Jupiter.",
"We can take de ladder from de mountain.",
"Hmm yes, that's very good. (why didn't I think of that!)",
"But massa Will, you know dat would happen?",
"Yes of course, I'm only checking things here...",
"We have to do something else here.",
"Hmm yes, I wonder how we both could get through...",
"We need a plank to block de gate when it go down Massa Will!!",
"YES! You're right, maybe we can use one of the planks from the bridge?",
"I go get one massa Will.",
"Very good Jupiter, I'll search for the lever again.",
"Did you see the raft down under de bridge Massa? Maybe we can sail around de bad guys.",
"Raft? Show me Jup but not a sound.",
"There it is, but how do we get down there Massa Will?",
"Hmm, I'll have to take a closer from the bridge.",
"Here, let me take dat boom.",
"Very well, let's go.",
"Yes, massa, Jup climb any tree he ebber see in he life.",
"Then up with you Jupiter.",
"How far mus go up, massa?",
"Get up the main trunk first, and then I will tell you which way to go. Just give me a second to get a better view, Jupiter.",
"Which way mus go now, Massa Will?",
"Keep up the largest branch — the one on this side.",
"How much fudder is got for go?",					//160
"How high up are you?",
"Ebber so fur, can see de sky fru de top ob de tree.",
"Never mind the sky, but attend to what I say. Look down the trunk and count the limbs below you on this side. How many limbs have you passed?",
"One, two, three, four, fibe — I done pass fibe big limb, massa, pon dis side.",
"Then go one limb higher.",
"Mos feerd for to ventur pon dis limb berry far — tis dead limb putty much all de way.",
"Did you say it was a dead limb, Jupiter?",
"Yes, massa, him dead as de door-nail — done up for sartain — done departed dis here life.",
"What in the name of heaven shall I do?",
"I'm gwine, Massa Will — deed I is, mos out to de eend now.",		//170
"Out to the end! Do you say you are out to the end of that limb?",
"Soon be to de eend, massa, — o-o-o-o-oh! Lor-gol-a-marcy! what is dis here pon de tree?",
"Well! What is it?",
"Why taint noffin but a skull — somebody bin lef him head up de tree, and de crows done gobble ebery bit ob de meat off.",
"A skull, you say! — Very well! — How is it fastened to the limb? — What holds it on?",
"Sure nuff massa, mus look. Why dis berry curous sarcumstance, pon my word — dare's a great big nail in de skull, what fastens ob it on to de tree.",
"Very good Jupiter, you can go down now.",				//177
"Quick massa, back off to de other side of the gate...",
"Huh? You have a plan?",
"Hurry up massa Will. We have to get to de raft before they open de gate again.",
"!!!",
"We have to be very silent now massa, so de maroons don't hear us.",
"Yes, let's sneak around them Jupiter.",
"What are we doing here? De maroons will soon find us...",
"I'm looking for the entrance to that Cave we visited earlier Jup.",
"Oh no! What are we going to do now, massa Will?",
"Let's search this god-forgotten Cave thoroughly. Maybe we can find something useful.",
"Look massa! De maroons already here.",
"Let's continue Jupiter.",
"They're gone massa!?",							//190
"Hmm, it's to good to be true. Lets's be very careful Jup.",
"Sacks in de Grot - yeah I know. I get a Musketoon too but where's de Key to de Weapons Chest, massa?",
"There are Sacks in the Attic too, Jupiter. The Key I think we agreed to hide in one of the Jars.",
"And we need de Boat for de big Treasure, massa Will.",
"Do you think you can find the way sailing our Boat to Bishop's Hostel?",
"Ahh, there you are at last.",
"You've brought a Weapon and the Boat too Jup, very good indeed.",
"I've got Gunpowder massa Will, but no Grapeshots.",
"Hmm...",
"Yes, massa, Jup climb any tree...",					//200
"Yeah I know Jupiter, this time I want you to bring the rope I've got here.",
"No problem - give it to me.",
"Here, also take the Goldbug. Use it as a weight at the end of the rope.",
"Oh no! Claws enuff, massa, and mouff too. I nebber did see sich a d—n bug — he kick and he bite ebery ting what cum near him.",
"But he's dead now Jup.",
"Mought ventur out leetle way pon de limb by myself, dat's true.",
"By yourself! — What do you mean?",
"Why I mean de bug. Tis berry hebby bug. Spose I drop him down fuss, and den de limb won't break wid just de weight ob old Jupiter.",
"You infernal scoundrel! What do you mean by telling me such nonsense as that? As sure as you drop that beetle I'll break your neck. Look here, Jupiter, do you hear me?",
"Yes, massa, need'nt hollo at poor Jup dat style.",
"Well! now listen! — we're searching for a Fortune and you're scared of an insect! Please Jupiter, venture out on the limb, and don't let go of the beetle.",
"I'm gwine, Massa Will — deed I is, — mos out to de eend now.",
"Very good!",								//213
"Is de lef eye of de skull pon de same side as de lef hand of de skull, too? — cause de skull aint got not a bit ob a hand at all — 
nebber mind! I got de lef eye now — here de lef eye! what mus do wid it?",
"Let the beetle drop through it, as far as the string will reach — but he careful and not let go your hold of the string.",
"All dat done, Massa Will, mighty easy ting for to put de bug fru de hole — look out for him dare below!",
"Yes!!",
"Gimme dat spade massa Will.",
"Thank you Jupiter.",
"I know I know...",
"It's made of metallic, massa. ",
"I think you're right Jupiter. Let's hurry now - maybe this is the right spot!",
"Here are more empty sacks...",
"Thanks Jupiter, let's return to the Treasure Chest before the maroons show up.",
"Sacks yes massa. But Jup only got two left.",
"Hmm, maybe you're strong enough to take the Chest this time Jupiter?",
"Hero knows what he's doing. He won't loose us.",
"Hmm, you seem to know him very well?",
"Hand over de Rope end massa Will - I go with de raft to keep an eye on de Treasure.",
"Very good Jup.",
"He...he was my cousin.",
"Oh, I'm sorry Jup.",
"I hope it was de last ones...",
"Indeed, let's loot them before we return home with the Treasure.",
"Massa Will, hand over your Sack. It's the last one.",
"Thank you Jupiter.",
"I stay up too massa - got things to do...",
"Very well, good night then.",
"And dis all cum ob de goole-bug! de putty goole bug! de poor little goole-bug, what I boosed in dat sabage kind ob style! Aint you shamed ob yourself, Jupiter? — answer me dat!",
"You moved it all here and put it in some order too?",
"Sure did massa Will, now take a look.",
"What a great job you did here Jupiter! Now let me see what we have got.",
"Now I have only one last question massa Will: 
What are we to make of de skellingtons found in de hole?",
"This is a question I am no more able to answer than yourself.",
"Mister Poe is so tired. He's been busy wid writing dem papers all night...",
"Yes, he told me.",
"And in the sugarcane fields. Maybe I can also find some safe zones in those buildings. The guards all seem to be out patrolling.",
"I've been down dere massa, so listen carefully, you can only save in de safe zones.",
"'Fire by numbers', ehh?",
"Ha!",

};