string DLG_TEXT[79] = {
"Hello Mr Legrand, what are you up to today?",
"We've been out hunting, but also found both shells and something else...",
"Ok, what is it - can you show me? You know how enthusiastic I am on all subjects connected with Natural History.",
"Of course, look we found a Gold-Bug!",
"Please Mr Legrand, would you let me take it to the fort?",
"Hmm ... well I ... very well then. I'll send Jupiter to get it back tomorrow.",
"Any luck today, Mr Legrand?",
"No Lieutenant, nothing so far.",
"Massa Will, you say noffin at all bout de bug?",
"Maybe you're right Jupiter. We'll go back and try to catch it!",
"Any luck today, Jupiter?",//10
"No, noffin at all.",
"Hello Jupiter, I guess Mr Legrand sent you.",
"Yes, he want de bug back.",
"Of course, I have wrapped the scarabæus in paper for protection. Please see to that Mr Legrand gets it at once.",
"Goodbye.",
"I want to ask you something about your military service.",
"Sure, go ahead.",
"Do you send or recieve any coded messages here at Fort Moultrie?",
"No never - you see this outpost is not the most important in America.",
"Hmm, that was bad. I need help with a cipher I found the other day.",		//20
"We studied the basics of cryptograms at West Point. I have a book somewhere at home...",
"Can I borrow it, Lieutenant?",
"Of course! Here, take the Key to my house. Feel free to look around everywhere for that old book.",
"Thank you my friend.",
"Oh, hello Mr Legrand. Let me ask you, did you manage to figure out which one of the symbols that have to be 'E' ?",//25
"No, I don't have the slightest idea.",
"Maybe you should go back inside and try again. Don't forget to check the Questbook.",
"You're right, I'll do that. See you later then, Lieutenant.",	
"Yes it's  '?'",	//serie 1
"Yes it's  '*'",	//30
"Yes it's  '3'",
"Yes it's  '5'",
"Yes it's  'R'",
"Yes it's  '4'",
"Yes it's  '6'",
"Yes it's  'T'",
"Yes it's  '8'",
"Yes it's  '_'",
"Yes it's  '1'",	//serie 2
"Yes it's  '0'",	//40
"Yes it's  '.'",
"Yes it's  '9'",
"Yes it's  '2'",
"Yes it's  ';'",
"Yes it's  ')'",
"Yes it's  ':'",
"Yes it's  'X'",
"Yes it's  '('",
"Very good. Maybe you have an idea about the complete word  'THE' . Let's start with  'T'?",
"Hmm, you've really analyzed the text. I guess you've got  'H' too?",			//50
"Ahh, Mr Legrand. I've heard you got something from the medicine woman. Maybe you should examine it carefully.",
"I think you're right so far. Maybe you need help from someone who has more linguistic knowledge than I do.",
"Yes! We'll go and visit the author Mr Poe in Charleston.",
"Do that. But first, can I have my crypto book back please.",
"Oh, I'm sorry - here you are. It was a great help for me.",
"Ahh, Mr Legrand. Have you studied my old cipher book yet?",
"Oh, hello Jupiter. What can I do for you?",
"Massa Will sent me to ask if he can borrow a Spyglass.",
"Yeah, sure. But you'll have to do me a favour Jupiter.",
"What's dat...? ",									//60
"If you please would raise the flag on top of the South Tower. The flag is in my office.",
"Jup will do dat - gimme de key...",
"Nice view, isn't it?",
"Huh?",
"Mr Legrand, what brings you here today - maybe you have come to return the Spyglass?",
"Yes of course, here it is.",
"There's something more on your mind...",
"Yes Lieutenant. I need a powerful weapon and am willing to pay for it.",
"We have this new type of firearm, Revolver called. However it is very expensive.",
"Yes yes, that would be perfect. The thing is I'm a little short of cash...",		//70
"Well I can't give it to you for nothing. I'm sorry Mr Legrand.",
"Perhaps you're interested in trading it for some valuable items?",
"Hmm maybe, but that's up to my Sergeant.",
"Can I visit him and if so where can I find him?",
"He's got a litle room in the Gate Tower. His office he says.",
"Alright, thank you Lieutenant. I'll pay him a visit.",
"You'll need this Key to the Gate Tower.",
"Thanks Lieutenant.",

};