string DLG_TEXT[46] = {
"Get lost!",
"...",
"Hello, #slad#! You look like a real sea wolf. Would you care to join my crew?",
"On what terms?",
"That was some performance! You're better than I expected. You might just be worth something to me.",
"Do you believe I'm a captain now?",
"Admiring the sea, are you? I never get tired of it myself.", // KK " It breaks my heart to think you'll never look on it again.", "Well, now - "
"Since we set sail our course is ENE, straight to #sisland_Oxbay#. Meanwhile to reach #sisland_Isla Muelle# we should go N. It looks like you've decided to break our agreement, old man.",
"Good guess. You may be smarter than you look. Give me your sword and pistol, and we'll see you safely to the #sisland_Oxbay# mines.",
"Will you? And what will your crew think of that? ",
"What do I care what they think?",
"Maybe you don't. But I can't help thinking your men may not enjoy working for a lying dog like yourself. Maybe that's why you've had such a hard time finding sailors for your crew.",
"Talk all you like. It'll do you no good.",
"Perhaps you're right. Maybe I should talk to your men instead. What do you say, gentlemen? Are you happy with Captain Small-Time, here, or are you ready for the really big scores?",
"That's big talk for a condemned #sperson#. Do you actually expect anyone to fall for it?",
"Look behind you, captain, and ask me that again.",
"I don't need to look. I chose my crew very carefully. Fact is, most of them don't even speak English.",
"Pirate scum!", // KK "Well, I gave it a shot. Hey, is that the shore over there, between the land and the sky? So long, captain!",
"What? Don't listen to #spronoun#, you fools! I'm your captain!",
"They seem to have other ideas. They may just kill you - if I don't beat them to it!",
"I need some sailors I can count on. Pay is 10 gold now, and 200 more after the raid. What do think?",
"At that price, I don't think much. Make me a captain, and I might think again.",
"If you want to live, you'll tell me where your ship is and tell your crew I'm in charge now.",
"I have an offer I think you'll like even better: Get me to #sIsla Muelle#, and I'll pay you as soon as we arrive.", // KK: no point for Nathaniel to go to Oxbay
"That shouldn't be a problem. I'm on generally good terms with the Spanish.",
"Then it's a deal! Shall we set sail?",
"You've got nerve, captain, and good taste to boot. But, no - no one runs my ship but me.",
"I'm sorry if I wasn't clear, but that wasn't a request. If you won't give it up, I'll have to take it by force.",
"Not even when someone shows up who can do the job much better than you? ",
"Better than me? Look, #schild#, you may have commanded an entire fleet in your mother's washtub back in England, but we're talking about a real ship!",
"And you're looking at a real captain. Test me!",
"Fair enough. It's your funeral. See that big oaf at the table there? Win a fight with him, and we'll talk. Hey, ",
"Gervasio Serrao",
", this fellow here called you an earthworm!",
"Very well, I'll squash him like an earthworm then!",
"I'm impressed. But a talent for swordplay doesn't make a #sgender# a captain.",
"No? Then give me another test. Name it.",
"All that sweat for nothing? Fine! I'll just have to kill you and take your ship.",
"Look, #schild#, this has been amusing, but I'm growing bored. If you don't want to work for me as a sailor, don't waste any more of my time.",
"Fine. I'll try my luck somewhere else.",
"We'll see how bored you are when I'm finished with you!",
"You're looking for trouble, are you? That can be arranged!",
"Do your worst, old man!",
"Hey! What are you doing here?!",
"Is that the shore over there, between the land and the sky? So long, captain!",
"Catch",

};
