string DLG_TEXT[71] = {
"Hello, ",
". I'm ",
"Ewan Glover",
"Ewan Glover",
", captain of the light naval brig 'Albion'",
"Pleased to meet you, ",
"Ewan Glover",
".",
"The pleasure is mine, captain. Silehard himself told me how you left the French without any gunpowder or cannon balls. And so deftly done! I don't mind telling you, I was very impressed.",
"Thank you, ",
"Ewan Glover",
", you flatter me.",
"Not at all. But I'm sure we'll have time enough to discuss our adventures over a mug of ale someday soon. For now, we have work to do.",
"Are you ready to set sail?",
"Yes I am. But, ",
", your fleet is too large and cumbersome to be effective. Leave one of your vessels here in #sRedmond#, and I'll join you when you're ready.",
"All right, ",
"I'm ready to make way. As soon as you set sail, I'll follow you.",
"Excellent. I'll see you on the seas!",
"I'll wait for you at the tavern. Ask ",
"Charles Windem",
" about me.",
"It's a deal. I'll call for you.",
"Sorry, ",
", but I'm in a hurry. I plan to set sail soon.",
"You're right, of course. I won't delay you further.",
"Hello, ",
". So, is there a free place for me?",
"Not yet, I'm afraid. You'll have to wait a bit longer.",
"We're preparing to set sail. Are you ready?",
"As ready as I'll ever be, although I'll be sorry to leave this pleasant harbor and its very good rum.",
"I'll soon return.",
"I'm always ready. I'll meet you at the port.",
"I'll see you",
"We should be going now. I want to be done with this as soon as possible.",
"Me too, so let's set sail.",
"Let's go to the tavern, ",
". The best way to wait for nightfall is with a tankard of good ale in front of you.",
"Hard to argue with that. Lead on!",
"I'll catch up with you later. I have other business to take care of first.",
"Fair enough. When you're finished, come to the tavern. I'll have the bartender keep some mulled wine warm for you!",
"You're most gracious. I'll be back soon.",
"So, where's that local fellow who was supposed to meet us?",
"Let's hang about for a while. He'll probably be here soon.",
"...and then that beauty proclaimed: 'Unless you become a respectable captain, you need not even dream about me!'",
"So you became a captain?",
"Yes. But somewhere along the way, I realized that woman meant nothing to me, lovely as she was. She didn't want me; she wanted to spend a captain's money! So why should I return?",
"Makes sense to me.",
"We should be on the move soon. It's already dark!",
"By the way, have you heard the tell of this haughty officer who used the king's frigate for his own personal purposes?",
"What are you on about now?",
"I'd love to hear about it - some other time. Now let's go!",
"A frigate came from Glasgow to #sRedmond# recently. It was supposed to be the new flagship for the #sisland_Redmond# fleet. They had the idea there in London that trouble might start in the colonies...",
"So?",
"Well, when the French captured #sOxbay#, the captain of the frigate received a secret order direct from Governor Silehard. \nThe following day, the frigate put out to sea, and the governor ended up having to commandeer civilian ships to fend off the French fleet!",
"Interesting. But there's no clear reason to suspect wrongdoing.",
"No clear reason? The war was on his doorstep, and the governor sent the most powerful ship in the fleet off to God knows where? Maybe he has a deal with the French!",
"You realize that's a deadly serious accusation. But I'll ask Silehard about the frigate.",
"Sure. You do that. And let me know what he says. I'll be very interested to hear it.",
"I will. Now let's go tend to business.",
"You're here at last, captain. Sit down, please, ",
". Your mulled wine is on the way.",
"Thank you.",
"My work here is finished. I'm headed back to #sRedmond#. Shall we sail together? There's safety in numbers.",
"I'm sorry, no. I can't leave just yet.",
"You have another mission to complete, do you? Well, good luck, then,",
".",
"And to you. I'll see you around, ",
".",
"Hey! We've lost our way! We need to get to #sGreenford#'s port, not this desolate beach.",
"There's no mistake. I just have some business here, and once I'm done with it, I'll get you to #sGreenford#.",

};
