string DLG_TEXT[56] = {
"Hello #saddress#, let me show you the sights of this town for only one gold piece! (The simpleton holds up two fingers instead of one.)",
"Who are you?",
"I'm not a tourist, and I don't need a guide!",
"My name is ",
", ",
". I'm a sailor from the 'Oiseau'. We're waiting here for an escort ship and I thought I'd make a bit of money on the side, to give to the church here.",
"I see... interesting. Would you mind if I were to ask you a couple of questions?",
"All right. You can go, sailor.",
"Yes, ",
" captain. I understand.",
"You can go.",
"Yes, I have ",
"Information comes at a price...",
"How much do you want?",
"Five gold pieces, alms for the church of course ",
".",
"All right. Here's your 'alms for the church'.",
"I don't have that kind of money now.",
"I'm not going to pay you to answer questions!",
"Thank you, ",
". It really is for the church, I swear by Davy Jones! Now what did you want to know?",
"You said you were from the 'Oiseau'...",
"I'm sorry, ",
". but I'll wait until you bring the money, the church really needs it to help the poor.",
"It's a deal.",
"Yes, ",
". It's my third year of sailing on her.",
"And you're waiting for an escort ship to arrive?",
"Where is your ship headed?",
"No, ",
", it's already in port. It's being loaded with provisions and ammunition as we speak, but we'll put to sea any day now.",
"What kind of ship is this?",
"Where is the captain of this ship?",
"That's everything I wanted to know. You can go.",
"Alas, ",
", I don't know. We sailors weren't told. It's probably a secret, military matters I suspect.",
"And you're waiting for an escort ship?",
"That's everything I wanted to know. Thanks.",
"It's a brig called 'Le Requin.' It's not part of the French king's fleet. The captain is a civilian who was recently hired to guard our ship.",
"Where's the captain of this ship?",
"That's all I need. You can go.",
"I don't know, ",
". But you can ask at the tavern. I know he was there earlier, he had been staying in the room upstairs, and he may still be there?",
"And what's the name of 'Le Requin's captain?",
"Amiel Berangere",
"Amiel Berangere",
", ",
".",
"Thank you, ",
".",
"Hello again, ",
". You needed Amiel Berangere. He was staying upstairs at the tavern, #ssir#.",
"Hello again, ",
". I think you said you didn't need my services, correct?",
"I do actually have a question.",
"You're right. Goodbye, sailor.",

};
