string DLG_TEXT[51] = {
"Yes, ",
"? Can't you see that I'm busy?",
"Excuse me, I'm ",
". I'm to escort your ship to #sOxbay#.",
"Finally, someone has arrived! I thought you'd never come.",
"Are you ready to put to sea?",
"Within moments. My men are loading and lashing the cargo\nBut before we go we'll need to inform the harbor master, ",
"Turpin Cabanel",
"Turpin Cabanel",
" and collect our permit so that we may leave\nAny questions?",//MAXIMUS: fix
"Where can I find the harbor master?",
"I already took care of that.",
"Over there, in the house by the dock, the one raised up on pilings. That's the port office. Now go get the permit. I'll wait for you here.",
"Yes sir, I'll be back soon.",
"Excellent. Let's get underway.",
"We can set sail immediately.",
"Where is your ship?",
"Hmm...well, it's hidden. In a secluded bay.",
"Blast and ballast, #sgender#! Why isn't it in port? Go bring your ship here on the double. We need to set sail as soon as possible!",
"Yes sir, I'll bring it to port now.",
"Excuse me, ",
"! You're a captain, aren't you?",
"Yes, I have a ship. Are you ",
"Virgile Boon",
"Virgile Boon",
"?",
"You know me?",
"I am none other than... ",
". I'm to escort your ship to #sOxbay#.",
"Finally, someone has arrived! I thought you'd never come.",
"Are you ready to put to sea?",
"Within moments. My men are loading and lashing the cargo. \nBut before we go we'll need to inform the harbor master, ",
"Turpin Cabanel",
"Turpin Cabanel",
" and collect our permit so that we may leave.",
"I already took care of that.",
"Did you get the permit from the harbor master?",
"No, not yet.",
"We're ready.",
"What are you waiting for? Hurry up and get it!",
"I'll not be ordered about like one of your deckhands, ",
"Virgile Boon",
". Everything in good time.",
"We're ready to sail. That's good enough time for me.",
"Be careful, captain. You may end up paying for your rudeness.",
"I don't want to take the chance that the fort may fire on my ship.",
"Are you an enemy spy, then? If not, go and see the governor. He should be able to guarantee your safety.",
"He'll also probably want a lot of money. I'm not paying to escort you, I'm being paid! If you won't sail round to Octopus Bay then you can find another escort. And you can also explain to the governor why the army on #sisland_Oxbay# still has no supplies.",
"Very well, I'll go to see the governor.",
"Alright, it seems I have no choice. Return to your ship and I shall sail round to join you.",
"I'm on my way.",
};
